### ISSUE TITLE
Icon Request: fa-clothes-hanger / fa-clothing

### ISSUE THREAD

**Issue by natoot** [FortAwesome/Font-Awesome#12659] opened 2018-03-21 09:54 UTC
Hello,

I need a clothing icon to be part of a room amenities list (wardrobe) for an hotel website. I couldn't find anything close to that while searching on font awesome current icons list.

Anything representing clothing would be ok (but a clothes hanger to represent a wardrobe would be perfect).
Example :
![image](https://user-images.githubusercontent.com/1754533/37703429-23a9cbf0-2d0f-11e8-8c21-3806593dcffb.png)

Example from Icons8 : https://icons8.com/icon/2989/hanger

Thank you!

**Comment by tagliala** [comment] 2018-04-06 12:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1659, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 12:59 UTC
