### ISSUE TITLE
Icon-request: popup window

### ISSUE THREAD

**Issue by Gitoffthelawn** [FortAwesome/Font-Awesome#6706] opened 2015-06-09 19:37 UTC
An icon indicating a popup window will appear

**Comment by tagliala** [comment] 2015-06-10 10:03
duplicate of #2478, please +1 that request

editing #2478 to add popup-windows in the title

closing here

**Closed by tagliala** 2015-06-10 10:03 UTC

**Comment by Gitoffthelawn** [comment] 2015-06-12 23:08
Thanks!  Done.  You are awesome.
