### ISSUE TITLE
Icon Request: fa-wire-messenger

### ISSUE THREAD

**Issue by idamcevski** [FortAwesome/Font-Awesome#10800] opened 2017-03-17 16:06 UTC
Icon for Wire messenger https://wire.com/en/

to be used on the web, obviously :)
![wire](https://cloud.githubusercontent.com/assets/25502979/24051939/0b5a248a-0b34-11e7-9d8f-30c1d2d7409f.png)

**Comment by tagliala** [comment] 2017-03-17 16:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10190, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-17 16:54 UTC
