### ISSUE TITLE
Icon Request: fa-zendesk

### ISSUE THREAD

**Issue by andreabianco** [FortAwesome/Font-Awesome#7910] opened 2015-11-18 10:22 UTC
Hi! I would like to request a zendesk icon

![image](https://cloud.githubusercontent.com/assets/7753046/11238497/6a52cdd8-8de6-11e5-974d-f8332f9dacef.png)

I'm interested only for the logo.
Thanks :)

**Comment by tagliala** [comment] 2015-11-18 10:45
duplicate of #5652, please +1 that request

closing here

**Closed by tagliala** 2015-11-18 10:45 UTC
