### ISSUE TITLE
icon-request: beatport & trackitdown

### ISSUE THREAD

**Issue by MehdiDehghani** [FortAwesome/Font-Awesome#8977] opened 2016-04-14 05:32 UTC
Hi, 
Huge thanks for your awesome font.

Please add beatport.com & trackitdown.net logos.

Have fun.

**Comment by tagliala** [comment] 2016-04-14 08:52
Duplicate of #2890 and #3104, please +1 those requests

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-14 08:52 UTC
