### ISSUE TITLE
Icon request: icon-mysql

### ISSUE THREAD

**Issue by Bamuel** [FortAwesome/Font-Awesome#8234] opened 2015-12-30 01:57 UTC
A mySQL icon :D 
![](http://assets.toptal.io/uploads/blog/category/logo/60/sql.png)
![](http://tankws.com/images/mysql.png)

**Comment by aethior** [comment] 2015-12-30 02:44
Hi @Bamuel,

This suggestion is duplicate of #6052. Please +1 that.

Regards.

**Closed** 2015-12-30 02:49 UTC
