### ISSUE TITLE
Icon Request: icon-octobercms

### ISSUE THREAD

**Issue by felixinx** [FortAwesome/Font-Awesome#7185] opened 2015-08-09 22:01 UTC
Hi,

I use [October CMS](http://github.com/october/octobercms) a lot, and will like to have a clean icon for this product, using Font Awesome.
Here is the logo;
![October Logo](https://octobercms.com/themes/website/assets/images/october.png)

Thanks.

**Comment by TheChen5** [comment] 2015-08-09 22:13
Dupe of #7102 
+1 that
I couldn't really blame you for not knowing this was already a request because when you search for it, there would be no results for this
Still, just remember... :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-09 22:32
I got #7185 searching for both october cms and octobercms

btw thanks again and closing here

**Closed by tagliala** 2015-08-09 22:32 UTC
