### ISSUE TITLE
Icon Request: fa-mixed-charts

### ISSUE THREAD

**Issue by Tango1979** [FortAwesome/Font-Awesome#8718] opened 2016-03-07 22:15 UTC
Good afternoon and congratulation for your "awesome" job! :-)
I'm doing a chart website and i made a page where i have more than 1 chart.
For example a bar chart in the first panel, a pie into the second and a X-Y graph into the third.
Can you provide an icon for multi-chart? Maybe a mix of all existing charts icons?

Thank you and again congratulations!

**Comment by tagliala** [comment] 2016-03-08 10:39
Maybe a duplicate of #1076 ?

**Comment by Tango1979** [comment] 2016-03-08 14:30
Good morning Geremia,
thank you for your promptly answer.
Honestly what i need is a little bit different, immagine that i have a page
with 3 or 4 different ghaps all together, so my idea is to have an image
that includes a bar chart, a pie and a X-Y line.
I know that is not easy to include all this stuff in only one image, but
should be great, because today it's normal have websites (especially for
finance and marketing) that shows to the users different charts in the same
time.
Thank you very much and congratulation again!

P.S.
Are you italian?

2016-03-08 5:39 GMT-05:00 Geremia Taglialatela <notifications@github.com>:

**Comment by tagliala** [comment] 2016-03-08 14:41
It would be great If you could find a single color example (on google images) suitable for 14px icon size, so I can properly rename and label this issue.

Please also consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Yes, I'm Italian :)

**Comment by Tango1979** [comment] 2016-03-08 14:44
Allora parliamo nella nostra lingua madre che e' meglio... :-)
Piacere sono Simone.
Ok, mi metto alla ricerca di qualche icona interessante e appena la trovo
ti ricontatto, ok?

Grazie e ancora complimenti per l'ottimo lavoro realizzato!

Saluti!

2016-03-08 9:41 GMT-05:00 Geremia Taglialatela <notifications@github.com>:

**Comment by tagliala** [comment] 2016-03-08 14:46
Ciao Simone

Tra poco distruggerò il messaggio perché qui comunque dobbiamo parlare in inglese

Grazie, posta qui l'esempio. Visto che nessuno ha richiesto questa icona fino ad oggi, è opportuno considerare una soluzione personalizzata.

**Comment by Tango1979** [comment] 2016-03-14 18:53
Good afternoon Geremia, sorry to bother you again, I found a picture that
can be a good starting point for you to create an icon as I requested.
This picture contains all 3 types of charts, can you create a font like
that (maybe square instead of rectangular)?

Thank you so much, have a good day!

Simone

Il giorno 8 marzo 2016 09:47, Geremia Taglialatela <notifications@github.com

**Comment by tagliala** [comment] 2016-03-14 19:39
Please post your examples here: https://github.com/FortAwesome/Font-Awesome/issues/8718 (email attachments don't work) so I can properly manage this issue

> This picture contains all 3 types of charts, can you create a font like
that (maybe square instead of rectangular)?

If you need new icons, you should customize the font by yourself: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by Tango1979** [comment] 2016-03-14 19:42
I like an icon like this attached with all 3 type of charts
![icon-klipstarts](https://cloud.githubusercontent.com/assets/17712353/13757527/5ce9dd46-e9fb-11e5-9b1f-c63ec9beb9d7.png)

**Comment by tagliala** [comment] 2022-03-13 15:16
I'm going to consider this closed by https://fontawesome.com/icons/chart-mixed?s=solid

Feel free to open a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2022-03-13 15:16 UTC
Labels: new icon, Available in FA Pro, charts-diagrams (category)
