### ISSUE TITLE
Icon request: fa-brands fa-gab

### ISSUE THREAD

**Issue by AverageJ0E** [FortAwesome/Font-Awesome#18781] opened 2022-03-06 05:25 UTC
Please add fa-brands fa-gab

**Comment by tagliala** [comment] 2022-03-06 09:08
Hi!

This request is a duplicate of #10304, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-03-06 09:08 UTC
