### ISSUE TITLE
Flutter framework and dart programming icons

### ISSUE THREAD

**Issue by saiderflash** [FortAwesome/Font-Awesome#17241] opened 2020-10-06 09:41 UTC
Please add icons for flutter and dart.

**Comment by tagliala** [comment] 2020-10-06 10:17
Hi!

Thanks for being part of the Font Awesome Community.

Flutter is a duplicate of #14878, please add a 👍 reaction to that request.
Dart is a duplicate of  #8003, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-10-06 10:17 UTC
