### ISSUE TITLE
Icon Request: fa-user-test

### ISSUE THREAD

**Issue by ronovar** [FortAwesome/Font-Awesome#7204] opened 2015-08-11 18:49 UTC
Could someone added to fontawesome icons thease new icons?

fa-user-test is similat like fa-user-plus (i use this in my website as ADD User button icon and need ADD Test User button icon) so that plus symbol is renamed to letter "T" that means Test...here is in example: http://postimg.org/image/kfhkfr9gr/

fa-user-edit is similar to fa-user-plus (i use it as EDIT user button icon) but if can be changed to combine fa-user-plus and fa fa-edit so like above but replace letter "T" with fa fa-edit.

I need these two icons to complete my website.

Thanks.

**Comment by tuzzmaniandevil** [comment] 2015-08-11 21:30
:+1:

**Comment by tagliala** [comment] 2015-08-12 08:52
user edit is a duplicate of #5951

this issue refers to #1181. You will find there a solution for user-edit

Renaming as user-test

**Comment by ronovar** [comment] 2015-08-12 09:21
Thanks...but i could not find icon in fontawesome webpage of issue #5951 (user-edit) and if you could please add in new release of fontsawesome these two icons user-edit and user-test.

Thanks.

**Comment by tagliala** [comment] 2015-08-12 11:44
#5951 is a request

if you need those icons in a short while, I suggest you to consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by ronovar** [comment] 2015-08-15 16:26
Ok i have converted png file from this site: https://www.iconfinder.com/icons/175178/edit_user_icon to png using this site: https://convertio.co/png-svg/ and now i im trying to convert converted svg to web font but every online svg to ttf web font failed to convert svg...could you please post link od tutorial how to convert png files to web fonts files? Or write a short tutorial with tools needed? I think most of users will then convert custom png and add it to fontsawesome library. Thanks

**Comment by tagliala** [comment] 2015-08-15 20:49
Do not use .pngs. You need an svg file represeting "user-test". You can use any svg editing tool of your choice

Then there is this guide, linked in the wiki: https://dyscribe.com/article/create-your-own-custom-iconfont/

**Comment by sensibleworld** [comment] 2024-07-10 21:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/user-pen?f=classic&s=solid)

**Closed by sensibleworld** 2024-07-10 21:33 UTC
Labels: new icon, web application icons (legacy category), FA Pro

**Comment by tagliala** [comment] 2024-07-20 11:55
@sensibleworld  There is a request to combine `user` + `T`, maybe this request can be considered as "declined"
