### ISSUE TITLE
Icon Request: Fan

### ISSUE THREAD

**Issue by lennybacon** [FortAwesome/Font-Awesome#13685] opened 2018-08-02 12:51 UTC
We have the pro version and are pretty happy. But... we still have another icon library (icomoon) referenced *just for one icon*. We would love to get rid of it and use the font awesome one - if you build it...

![image](https://user-images.githubusercontent.com/272164/43584661-4abe67ba-9663-11e8-8de3-635dbdf10621.png)

**Comment by tagliala** [comment] 2018-08-02 15:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3684, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-02 15:17 UTC
