### ISSUE TITLE
Icon Request: fa-etsy

### ISSUE THREAD

**Issue by swebster89** [FortAwesome/Font-Awesome#6247] opened 2015-04-17 17:41 UTC
Love your icons! Wish there was one for Etsy.

![etsy-app-logo](https://cloud.githubusercontent.com/assets/11997769/7207411/f7786830-e4fe-11e4-89e6-98e4f5392f03.png)

![etsy-logo-01](https://cloud.githubusercontent.com/assets/11997769/7207432/0d26fa20-e4ff-11e4-8d2c-8cfa2992fb9e.png)

**Comment by tagliala** [comment] 2015-04-19 21:55
duplicate of #1962 , please +1 that request

closing here

**Closed by tagliala** 2015-04-19 21:55 UTC
