### ISSUE TITLE
Icon request: fa-cricket-bat

### ISSUE THREAD

**Issue by ayoubkhan558** [FortAwesome/Font-Awesome#16699] opened 2020-05-22 11:29 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/20210961/82663572-5a509e80-9c49-11ea-9469-9a444cca9347.png)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-22 17:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5706, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-22 17:02 UTC
