### ISSUE TITLE
Icon Request: fa-contact

### ISSUE THREAD

**Issue by JasonMe** [FortAwesome/Font-Awesome#8345] opened 2016-01-15 05:59 UTC

**Comment by AndreLGava** [comment] 2016-01-15 10:02
Maybe this is related to this? https://github.com/FortAwesome/Font-Awesome/issues/825
if yes please close this issue and mark a +1 on that one.

Thanks

**Comment by tagliala** [comment] 2016-01-15 10:41
@AndreLGava thanks

Considering this a duplicate of #825

**Closed by tagliala** 2016-01-15 10:41 UTC

**Comment by JasonMe** [comment] 2016-07-18 01:53
just like phone book

**Comment by tagliala** [comment] 2016-07-18 09:41
@JasonMe #898
