### ISSUE TITLE
Icon request - icon-copyright

### ISSUE THREAD

**Issue by ndweekes** [FortAwesome/Font-Awesome#880] opened 2013-03-25 00:46 UTC
A copyright symbol would be jolly useful. Would like to put all the info at the bottom of website ie. social links, phone, email etc as icons instead of text. Only one missing is a copyright symbol.

**Comment by aleksandar-todorovic** [comment] 2016-01-25 17:11
Shouldn't this be closed? This icon has already been added.

**Comment by netAction** [comment] 2016-01-25 19:59
+1 for rotated symbol (copyleft)

**Comment by aleksandar-todorovic** [comment] 2016-01-25 21:53
@netAction Check #2934. There's also a workaround posted there.

**Comment by aethior** [comment] 2016-02-14 00:10
Added to v4.2. `fa-copyright` (http://fontawesome.io/icon/copyright/)

cc @tagliala

**Comment by tagliala** [comment] 2016-02-14 00:21
duplicate of #375, added in 4.2.0

**Closed by tagliala** 2016-02-14 00:21 UTC
