### ISSUE TITLE
Icon Request: fa-wheelchair-alt

### ISSUE THREAD

**Issue by kegill** [FortAwesome/Font-Awesome#5527] opened 2015-01-29 19:09 UTC
The Accessible Icon Project has redesigned the standard wheelchair-as-accessible-proxy icon. The new design is ADA compliant. It features a person with agency, in control of movement/power. 

It would be great if FontAwesome helped this effort by providing an alternative to the stock/static wheelchair icon. The new icon has a public domain CC license. 

Details: http://www.accessibleicon.org/icon.html

**Comment by tagliala** [comment] 2015-01-29 21:51
duplicate of #2746, please +1 that request

closing here

**Closed by tagliala** 2015-01-29 21:51 UTC
