### ISSUE TITLE
Icon Request: fa-google-play

### ISSUE THREAD

**Issue by sanjaykarki** [FortAwesome/Font-Awesome#6969] opened 2015-07-17 06:44 UTC
Please add icon for Google Play.

![google_play](https://cloud.githubusercontent.com/assets/4466090/8741883/074b12ae-2c7f-11e5-85e9-a03b71a68ee8.png)

**Comment by tagliala** [comment] 2015-07-17 10:17
duplicate of #2272 , please +1 that request

**Closed by tagliala** 2015-07-17 10:17 UTC
