### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by JoshuaRepko** [FortAwesome/Font-Awesome#19770] opened 2023-06-19 13:19 UTC
Hi, I would like to request a transmission/grid - tower icon

**Comment by tagliala** [comment] 2023-06-19 13:31
Hi!

Thanks for being part of the Font Awesome Community.

Like this one? https://fontawesome.com/icons/tower-cell?f=classic&s=solid

**Comment by JoshuaRepko** [comment] 2023-06-19 13:37
Hi,

It's close to what I'm looking for, but this is a cellphone tower. But I'm looking for a transmission tower, just like in the attachment.

The given picture with 2 bars instead of wireless waves, should do the trick.

Kind regards,


Met vriendelijke groet,
Joshua Repko
Engineer regeltechniek
Newtonstraat 5
1704 SB Heerhugowaard 
T  +31722100110
www.domoticapartners.nl
***@***.***
Van: Geremia Taglialatela ***@***.***>
Verzonden: maandag 19 juni 2023 15:32
Aan: FortAwesome/Font-Awesome ***@***.***>
CC: Joshua Repko ***@***.***>; Author ***@***.***>
Onderwerp: Re: [FortAwesome/Font-Awesome] Icon request: icon-name (Issue #19770)


Hi!

Thanks for being part of the Font Awesome Community.

Like this one? https://fontawesome.com/icons/tower-cell?f=classic&s=solid

-

**Comment by tagliala** [comment] 2023-06-19 14:00
Hi, email attachments don't work

Please open https://github.com/FortAwesome/Font-Awesome/issues/19770 with a web browser and paste the example there

**Comment by JoshuaRepko** [comment] 2023-06-19 14:12
Hi,

Does it work like this, the attachment? Else you can type 'transmission tower' in google image viewer.

Kind regards,


Met vriendelijke groet,
Joshua Repko
Engineer regeltechniek
Newtonstraat 5
1704 SB Heerhugowaard 
T  +31722100110
www.domoticapartners.nl
***@***.***
Van: Geremia Taglialatela ***@***.***>
Verzonden: maandag 19 juni 2023 16:01
Aan: FortAwesome/Font-Awesome ***@***.***>
CC: Joshua Repko ***@***.***>; Author ***@***.***>
Onderwerp: Re: [FortAwesome/Font-Awesome] Icon request: icon-name (Issue #19770)


Hi, email attachments doesn't work

Please open #19770<https://github.com/FortAwesome/Font-Awesome/issues/19770> with a web browser and paste the example there

-

**Comment by tagliala** [comment] 2023-06-19 14:31
Ok, thanks

So this is a duplicate of #2766, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-06-19 14:31 UTC
