### ISSUE TITLE
Icon Request: House . Home with outlines only

### ISSUE THREAD

**Issue by Dsign** [FortAwesome/Font-Awesome#9518] opened 2016-07-05 14:06 UTC
Unless there's a way to do this, I noticed that some icons such as the heart have two versions, one outlined and a version filled. I noticed there is already a house or home icon, my ask is for an outlined version.

**Comment by aethior** [comment] 2016-07-05 14:28
Duplicate of #2210. Please :+1: that.

**Closed** 2016-07-06 00:36 UTC
