### ISSUE TITLE
Icon request: icon-family

### ISSUE THREAD

**Issue by jerearaujo03** [FortAwesome/Font-Awesome#8381] opened 2016-01-20 20:37 UTC
I want family icons, like mother, father, child, and the entire family

**Comment by jerearaujo03** [comment] 2016-01-20 20:38
Example: 
![icon-family](https://cloud.githubusercontent.com/assets/7424471/12462357/94762c44-bf9c-11e5-82d4-f0f45871f8d0.png)

**Comment by tagliala** [comment] 2016-01-21 09:01
duplicate of #3277, please +1 that request

closing here

**Closed by tagliala** 2016-01-21 09:01 UTC
