### ISSUE TITLE
Icon request: icon-plus-minus (±)

### ISSUE THREAD

**Issue by ameesme** [FortAwesome/Font-Awesome#9064] opened 2016-04-26 13:36 UTC
A styled plus-minus icon, used to indicate that a value's correctness is debatable, or a prediction or estimation.

Made some quick sketches on some post-its.
![img_20160426_153504](https://cloud.githubusercontent.com/assets/3008683/14819920/90fe642c-0bc4-11e6-89ed-98a192127b85.jpg)

**Comment by PeterShaggyNoble** [comment] 2016-04-26 16:46
Dupe of [#6885](https://github.com/FortAwesome/Font-Awesome/issues/6885), you should +1 that one instead.

**Closed** 2016-04-26 17:20 UTC
