### ISSUE TITLE
Icon Request: fa-golf 

### ISSUE THREAD

**Issue by sdh100shaun** [FortAwesome/Font-Awesome#6995] opened 2015-07-20 20:19 UTC
golf tee flag representative to be used to represent a golf course

**Comment by tuxy** [comment] 2015-07-23 00:23
fa-golf-course icon:

![Golf Course](http://i.imgur.com/7kDNqXS.png)
Source: http://www.flaticon.com/free-icon/golf-hole-and-flag_55568

fa-golf-player icon:

![Golf Player](http://i.imgur.com/BMZfyNg.png)
Source: http://www.flaticon.com/free-icon/golf-player_39675

**Comment by tagliala** [comment] 2015-07-23 10:07
duplicate of #5348, please +1 that request

closing here

**Closed by tagliala** 2015-07-23 10:07 UTC

**Comment by tuxy** [comment] 2015-07-24 04:09
@tagliala, the #5348 is wrong because this request is for fa-golf-player and fa-golf-course and NOT for golf ball or golf club.

**Comment by tagliala** [comment] 2015-07-24 11:55
I can say that #5348 is an icon that represents golf. I don't know how dave will implement that, maybe a golf ball, maybe a tee flag... If you want to request a specific icon, please open a new request with a proper title (eg: icon-golf-player)

**Comment by amosvanhorn** [comment] 2016-10-13 06:57
+1

**Comment by Cengiz25** [comment] 2016-10-13 12:26
+1

**Comment by kimarudg** [comment] 2017-02-11 21:52
+1

**Comment by stefbozic** [comment] 2017-03-09 13:49
+1

**Comment by AngerLiss** [comment] 2017-04-13 19:51
+1

**Comment by duy205711** [comment] 2017-10-02 08:41
+1
