### ISSUE TITLE
Icon Request: fa-ask.fm

### ISSUE THREAD

**Issue by PaJson** [FortAwesome/Font-Awesome#8980] opened 2016-04-14 10:35 UTC
Social Link
https://ask.fm/
https://ask.fm/apple-touch-icon-114x114.png

**Comment by tagliala** [comment] 2016-04-14 10:40
Duplicate of #3762, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-14 10:40 UTC
