### ISSUE TITLE
Icon request: fa-buffer

### ISSUE THREAD

**Issue by fezde** [FortAwesome/Font-Awesome#9282] opened 2016-05-26 20:40 UTC
Buffer is a great social media management solution. They are also happy (just like all the icon requests) so they would perfectly fit in here. Their logo is also simple, so it should be easy to include.
<img width="127" alt="bildschirmfoto 2016-05-26 um 22 39 24" src="https://cloud.githubusercontent.com/assets/11369714/15589363/d5a8193e-2392-11e6-952c-813c73b7622e.png">

You can contact them via twitter `@buffer`

It would be great if we could have its icon in FA. I would use it in all my sharing sections....

---
edit by tagliala: removed the mention to `@buffer`

**Comment by tagliala** [comment] 2016-05-26 21:34
Duplicate of #2110, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-26 21:34 UTC
