### ISSUE TITLE
Icon request: leetcode

### ISSUE THREAD

**Issue by clivelo** [FortAwesome/Font-Awesome#19473] opened 2022-12-14 13:05 UTC
### Use case
For personal websites linking to your Leetcode profile. Useful for recruiters browsing your portfolio to see your progress on Leetcode.

### Example image
![image](https://user-images.githubusercontent.com/51747571/207602312-ef7a624f-d798-47bc-87d1-4717a8c9615a.png)

### Icon request checklist
- [x] The title starts with "Icon request: " and is followed by the requested icon name
- [x] This icon does not represent a brand
- [x] This is a single icon or matched pair (Ex: lock / unlock)
- [x] The request is for a concrete object, or I've included an example image
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2022-12-14 13:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15337 , please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-12-14 13:12 UTC
