### ISSUE TITLE
Icon Request: fa-running

### ISSUE THREAD

**Issue by bertbirdie** [FortAwesome/Font-Awesome#9440] opened 2016-06-22 03:07 UTC
Black conventional stick man running

**Comment by tagliala** [comment] 2016-06-22 09:57
Duplicate of #1156 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-22 09:57 UTC
