### ISSUE TITLE
Icon Request: Instagram

### ISSUE THREAD

**Issue by paper9oll** [FortAwesome/Font-Awesome#9393] opened 2016-06-12 08:36 UTC
Hi Developer,

Please release a inverse `fa-instagram` icon as the new instagram logo does not goes well with `:hover` styles

Thanks You.

**Comment by tagliala** [comment] 2016-06-12 08:55
Duplicate of #9223, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-12 08:55 UTC

**Comment by paper9oll** [comment] 2016-06-12 09:14
I actually searched but don't understand what is "squared" hence opening a new issue/request.

Anyway thanks you

**Comment by tagliala** [comment] 2016-06-12 13:44
It is like [facebook-square](http://fontawesome.io/icon/facebook-square/), [twitter-square](http://fontawesome.io/icon/twitter-square/)...
