### ISSUE TITLE
Icon request: fa-plugdj

### ISSUE THREAD

**Issue by Ariuw** [FortAwesome/Font-Awesome#9597] opened 2016-07-19 21:24 UTC
This can be used something like Facebook, because always people do some partys on that and it can be helpful

<img src="https://camo.githubusercontent.com/1b62d5a1b07b05549a44ded7dacb90a03e8ac439/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313237393036342f323231343838342f64303766396437322d393964662d313165332d386165332d3535343437646261363666612e706e67">

I hope that it can be added!

**Comment by tagliala** [comment] 2016-07-19 23:34
Duplicate of #2932, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-19 23:34 UTC
