### ISSUE TITLE
Icon Request: fa-info-circle-o

### ISSUE THREAD

**Issue by Meilan** [FortAwesome/Font-Awesome#11070] opened 2017-05-16 13:39 UTC
First of all, big thank you for the great work and such amazing resources.

I am thinking it could be nice to have "fa-info-circle-o".
I would like to use it together with "fa-question-circle-o".

Thank you :)

![fa-info-circle-o](https://cloud.githubusercontent.com/assets/2938128/26108733/a6713e34-3a4d-11e7-961f-a7ba4cf1d279.png)

![image](https://cloud.githubusercontent.com/assets/2938128/26110324/4d198152-3a52-11e7-8f1e-64e348ad6325.png)

**Comment by tagliala** [comment] 2017-05-16 17:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3224, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-16 17:17 UTC
