### ISSUE TITLE
Icon to represent a single calendar event

### ISSUE THREAD

**Issue by taalas** [FortAwesome/Font-Awesome#12404] opened 2018-02-21 07:45 UTC
With `calendar` and `calendar-alt` we already have options for a filled and an empty calendar, also there are plenty of icons for adding and removing events.

Would it be possible to add an icon representing a single event (think `calendar-alt` but only one square inside the calendar, something like this https://material.io/icons/#ic_event)?

**Comment by tagliala** [comment] 2018-02-21 20:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3609, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-21 20:43 UTC
