### ISSUE TITLE
Icon request: Microsoft Azure (brand)

### ISSUE THREAD

**Issue by qJake** [FortAwesome/Font-Awesome#14072] opened 2018-10-05 20:46 UTC
I'm surprised that AWS is represented readily in FontAwesome, but there is no Microsoft Azure icon.

Requesting this be added:

![azure](https://user-images.githubusercontent.com/652006/46559304-950b9480-c8b5-11e8-8f46-996b9d21cb05.png)

As an SVG: [azure.zip](https://github.com/FortAwesome/Font-Awesome/files/2452203/azure.zip)

[Microsoft Azure website](https://azure.microsoft.com/en-us/overview/what-is-azure/) for reference.

**Comment by AverageCakeSlice** [comment] 2021-09-26 19:42
I'd like to second this! Azure services would be a really great bonus, like TFS/DevOps, or Azure Pipelines

**Comment by aethior** [comment] 2022-04-15 01:27
This request is duplicate of #5212.
Please add a 👍 reaction to that request.

cc/ @tagliala

**Closed** 2022-04-15 07:03 UTC
