### ISSUE TITLE
Icon Request icon-ripple (icon-xrp)

### ISSUE THREAD

**Issue by William2030** [FortAwesome/Font-Awesome#11719] opened 2017-11-06 21:25 UTC
An icon for ripple such as the one below:
![xrp 1](https://user-images.githubusercontent.com/31596855/32464755-123040ee-c30f-11e7-8110-1506deebeaac.png)

**Comment by tagliala** [comment] 2017-11-06 22:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5829, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-06 22:56 UTC

**Comment by William2030** [comment] 2017-11-07 03:15
I simply did a search for icons. Will #5829 be in classic black/white like the one above?! I hope so. I expect it can be changed from blue to black if not. Still cool. :+1:
