### ISSUE TITLE
Icon request: Unpin

### ISSUE THREAD

**Issue by hadi-shamsabadi24** [FortAwesome/Font-Awesome#13542] opened 2018-07-14 06:38 UTC
### What can it be used for?

pin or upin file some online filemanager & etc.

**Comment by tagliala** [comment] 2018-07-14 10:13
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #10749 ?

Or it is https://fontawesome.com/icons/thumbtack?style=solid

?

**Comment by nancycg** [comment] 2020-01-17 06:24
Do we have a unpin icon available? I know font awesome is having pin icon but I can not find unpin which should be a cross line in mid of pin icon maybe... Please reply!

**Comment by sensibleworld** [comment] 2024-07-12 16:20
`thumbtack-slash` will be in our next release

**Closed by sensibleworld** 2024-07-12 16:20 UTC
Labels: waiting for feedback
