### ISSUE TITLE
Icon Request: icon-footsteps (shoe prints)

### ISSUE THREAD

**Issue by HuMarts** [FortAwesome/Font-Awesome#3175] opened 2014-04-01 08:54 UTC
Hello!
I would be very pleased to be able to use an icon that fits the category "Walking"
To me a simple drawing of footsteps would be perfect. Or, as an alternative, a walking person should be fine too!.
Best regards,
Huub Martens.

**Comment by tomay** [comment] 2015-01-30 00:54
+1

**Comment by zdila** [comment] 2015-01-30 10:33
+1

**Comment by sebastian301082** [comment] 2015-02-22 08:20
+1

**Comment by stevenyhof** [comment] 2016-03-31 17:17
+1

**Comment by grantneufeld** [comment] 2016-04-21 21:46
+1(ish). The audit-trail request got merged into this request. If this ends up serving the function of an icon to represent an audit-trail, then I’m a +1.

An example use case: I have a system that has workflows for a financial institution. Auditors (and managers) need to be able to review the actions taken, who took them, and when. So, when viewing something in the system, I need to link to the “audit trail” for that thing. In coding terms, the audit trail is sort of like the version history for a project.

**Comment by warrenma65** [comment] 2016-11-16 06:52
Any progress with this? I'd really like to see a footsteps or feet icon!

**Comment by wlievens** [comment] 2016-12-06 21:43
+1

**Comment by XtheOne** [comment] 2017-09-07 22:44
+1

**Comment by AbdAllahBoda** [comment] 2017-10-01 06:06
+1

**Comment by jamesjieye** [comment] 2018-04-12 14:53
+1

**Comment by manuelph** [comment] 2018-08-07 06:09
+1

**Comment by mccrearyk** [comment] 2019-03-13 14:02
+1

**Comment by aethior** [comment] 2022-02-28 14:12
Duplicate of #2788.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-02-28 14:48
~Sorry, reopening here. I think this is about footprints rather than shoeprints. Editing the title~

My bad. Footprints is here #13650

**Closed** 2022-02-28 14:49 UTC
Labels: new icon, web application icons
