### ISSUE TITLE
Icon request: fa-envelope-opened

### ISSUE THREAD

**Issue by RodolpheGohard** [FortAwesome/Font-Awesome#6579] opened 2015-05-28 13:48 UTC
It would be nice to have the "opened" version of fa-envelope.

This can be used to differenciate read/unread mail, or to emphasis the action of opening a mail when hovering with the mouse.

like these:
* http://images.clipartpanda.com/envelope-clipart-black-and-white-12065629392075203596qubodup_16x16px-capable_black_and_white_icons_9.svg.med.png
* http://image.shutterstock.com/display_pic_with_logo/349072/138737618/stock-vector-envelope-icon-138737618.jpg

**Comment by tagliala** [comment] 2015-06-07 09:13
duplicate of #897, please +1 that request

closing here

**Closed by tagliala** 2015-06-07 09:13 UTC
