### ISSUE TITLE
Icon request: peoples

### ISSUE THREAD

**Issue by mayurjadhav** [FortAwesome/Font-Awesome#11521] opened 2017-09-13 11:21 UTC
Hi,

Could you please create icon for peoples? Only two users icon, Please see the attachment.
<img width="59" alt="screen shot 2017-09-13 at 4 50 55 pm" src="https://user-images.githubusercontent.com/1706282/30374783-c190abd2-98a3-11e7-827b-79490584d4a3.png">

**Comment by tagliala** [comment] 2017-09-14 16:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2883 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-14 16:09 UTC
