### ISSUE TITLE
Icon Request: fa-cooky

### ISSUE THREAD

**Issue by Niubbo75** [FortAwesome/Font-Awesome#11697] opened 2017-11-01 11:16 UTC
Hello, I would like to have a cooky icon to use on websites near link to cookies policy's page.
I have think about a couple of cookies to use as icon.
Thank you in advance.

**Comment by tagliala** [comment] 2017-11-01 13:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2845 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-01 13:11 UTC
