### ISSUE TITLE
Icon request: Venmo

### ISSUE THREAD

**Issue by vmbiohazard** [FortAwesome/Font-Awesome#15847] opened 2019-11-25 12:08 UTC
**What can it be used for?**
To show a new payment method.

**Example image (optional)**
- https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWsDzVhG4De9BGEHC11IaG-Kwl_iFq2KWUvuqt6-jskMv1pR5W&s
- https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS91ndw_9uBg_SLrUKO_IOc1qkdh9OTAsdfjSfV6YfS28C-_DhH&s

**Icon request checklist**
- [ Pair (venmo, cc-venmo) ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ yes ] I have included at least one example image if it could be helpful (optional)
- [ yes ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by JoshuaDoshua** [comment] 2019-11-29 03:32
#4659
note, this is a much much older issue and doesn't follow the new icon-request format

**Comment by tagliala** [comment] 2019-11-29 07:37
Hi!

Thanks for being part of the Font Awesome Community.

> note, this is a much much older issue and doesn't follow the new icon-request format, especially for unambiguous requests like this one

thanks for finding the duplicate. This is not a problem at all for the older issues 👍

Closing here as a duplicate of #4659

**Closed by tagliala** 2019-11-29 07:37 UTC
