### ISSUE TITLE
Icon request: users-times, users-plus, user-check, and users-check

### ISSUE THREAD

**Issue by susanm74** [FortAwesome/Font-Awesome#11042] opened 2017-05-09 13:23 UTC
Hi there,

So user-times & user-plus icons both already exist, and I think they're great! So much so, that I think it would also be great to have a "users-times" icon, "users-plus" icon, along with user-check and users-check! Would this be possible?

Thanks,
Sue

**Comment by susanm74** [comment] 2017-05-09 13:27
In terms of use cases:
- user-times & user-plus have both been great to far to represent adding or removing individuals
- users-times & users-plus would be great to represent adding or removing groups of individuals
- user-check and users-check would be great to represent saving both individuals and groups of individuals, respectively.

Thanks again!
Sue

**Comment by tagliala** [comment] 2017-05-09 14:22
Hi!

Thanks for being part of the Font Awesome Community.

You should split this request:
* It is fine to have `user-times` and `users-plus` in a single request, given that they are strictly related and there are already `user-plus` and `user-times`. You can use this request
* `users-check` needs to be put in a separate request
* `user-check` is a duplicate of #6053, please 👍  that request

[Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

Please also take a look at #1181, you will find a solution there

**Closed** 2023-04-04 09:16 UTC
Labels: waiting for feedback
