### ISSUE TITLE
Icon Request: fa-satelite

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7011] opened 2015-07-23 00:09 UTC
fa-satelite icon:

![Satelite](http://i.imgur.com/sv2cAmA.png)
Source: https://www.iconfinder.com/icons/322495/satelite_icon#size=128

**Comment by tagliala** [comment] 2015-07-23 10:09
duplicate of #2404 , please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-07-23 10:09 UTC

**Comment by tuxy** [comment] 2015-07-24 04:01
@tagliala, done. Thank You!

**Comment by khanabuzaid** [comment] 2016-06-23 10:32
hi,
how to use this fa-satelite in awesome font.
which version in provide this icon.
