### ISSUE TITLE
Icon request: icon-badge

### ISSUE THREAD

**Issue by larach** [FortAwesome/Font-Awesome#7670] opened 2015-10-13 13:14 UTC
Hello, 
I need an icon that represent an award/badge, something more like this  : https://cdn2.iconfinder.com/data/icons/awards-and-seals-2/500/Award_certificate_medal_seal_badge_collection-512.png

I want to use it on a website using font awesome icons with a country showing that the company has 20 years of experience and more - something to feel proud of.

I hope you can add it - Many many thanks :)

Lara

**Comment by tagliala** [comment] 2015-10-13 21:30
duplicate of  #4246, please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-10-13 21:30 UTC
