### ISSUE TITLE
 circled numbers

### ISSUE THREAD

**Issue by polinac** [FortAwesome/Font-Awesome#6784] opened 2015-06-19 01:05 UTC
I would like to have circled numbers icons. Like this:
![image](https://cloud.githubusercontent.com/assets/12117128/8245526/811909d0-15e4-11e5-85f4-6708ae4a9ad6.png)

Thank you for the great product!!!

**Comment by tagliala** [comment] 2015-06-21 10:35
duplicate of #6099 , please read throughout the comments there

closing here

**Closed by tagliala** 2015-06-21 10:35 UTC
