### ISSUE TITLE
Icon Request: fa-irc

### ISSUE THREAD

**Issue by zombiesbyte** [FortAwesome/Font-Awesome#11428] opened 2017-08-22 12:15 UTC
I've tried to find an official icon but there doesn't seem to be one (maybe I haven't looked hard enough). Regardless, perhaps Font Awesome can fill that gap with more Awesomeness.

**Comment by tagliala** [comment] 2017-08-22 12:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3337, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-22 12:35 UTC
