### ISSUE TITLE
Icon Request: fa-handshake

### ISSUE THREAD

**Issue by samuelzl** [FortAwesome/Font-Awesome#10008] opened 2016-09-30 18:35 UTC
Hi, I'm enjoying and using the Font Awesome icons and I have to really thank you guys, you're really awesome.
I'm looking for a handshake icon to use on franchise categories, but I can't find it so I'm trying to request it here.
see you!

**Comment by aethior** [comment] 2016-10-01 06:56
Duplicate of #878. ´fa-handshake´ is planned for v5.0.

**Closed** 2016-10-01 11:41 UTC
