### ISSUE TITLE
Icon request: icon-warranty

### ISSUE THREAD

**Issue by girishk087** [FortAwesome/Font-Awesome#7619] opened 2015-10-06 13:07 UTC
Requesting for a new Icon for Warranty.

use plan: in e-commerce platform we can you this for warranty icon

**Comment by tagliala** [comment] 2015-10-06 15:19
could you please provide an example?

**Comment by girishk087** [comment] 2015-10-06 17:36
I'm designing a website using shopify in that I need to specify the warrenty of the product to show that I need icon.

**Comment by TheChen5** [comment] 2015-10-07 01:41
A visual representation is needed (like a image).

**Comment by tagliala** [comment] 2015-10-07 08:11
right. this could be a duplicate

**Comment by girishk087** [comment] 2015-10-07 12:03
No this is not a duplicate. with this mail im sending the images find the
attachments below.

it will be good with image download,jpg not the download1.jpg

On Wed, Oct 7, 2015 at 1:42 PM, Geremia Taglialatela <
notifications@github.com> wrote:

> right. this could be a duplicate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/7619#issuecomment-146109865>
> .
>



-- 
With Regerds
GIRISH K (9591646543)

**Comment by girishk087** [comment] 2015-10-07 12:07
See this image also

On Wed, Oct 7, 2015 at 5:33 PM, Girish k <girishk087@gmail.com> wrote:

> No this is not a duplicate. with this mail im sending the images find the
> attachments below.
>
> it will be good with image download,jpg not the download1.jpg
>
> On Wed, Oct 7, 2015 at 1:42 PM, Geremia Taglialatela <
> notifications@github.com> wrote:
>
>> right. this could be a duplicate
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FortAwesome/Font-Awesome/issues/7619#issuecomment-146109865>
>> .
>>
>
>
>
> --
> With Regerds
> GIRISH K (9591646543)
>



-- 
With Regerds
GIRISH K (9591646543)

**Comment by tagliala** [comment] 2015-10-07 12:43
@girishk087 please do not attach file via email, it will not work

Post your example here: https://github.com/FortAwesome/Font-Awesome/issues/7619

**Comment by girishk087** [comment] 2015-10-10 14:24
![download](https://cloud.githubusercontent.com/assets/12954928/10411592/8b0aee42-6f88-11e5-82c6-417426afe058.jpg)
![download](https://cloud.githubusercontent.com/assets/12954928/10411591/8b0b10ac-6f88-11e5-9f1c-5bdfde68b4a7.png)


Like this kind of icon

**Comment by tagliala** [comment] 2015-10-10 18:42
ok, this is a duplicate of #1182 , I should ask you to +1 that request and post there your examples

closing here

**Closed by tagliala** 2015-10-10 18:42 UTC
Labels: waiting for feedback
