### ISSUE TITLE
Icon request: Rocky Linux

### ISSUE THREAD

**Issue by Dulux-Oz** [FortAwesome/Font-Awesome#19259] opened 2022-08-11 06:42 UTC
Hi All,

How about an icon for Rocky Linux

https://seeklogo.com/vector-logo/409448/rocky-linux

Cheers

Dulux-Oz

**Comment by istiak101** [comment] 2022-08-12 03:28
Duplicate of https://github.com/FortAwesome/Font-Awesome/issues/19166

**Comment by tagliala** [comment] 2022-08-12 06:35
thanks, searching by "Rocky Linux" does not bring up that result. Will edit #19166's title to improve search

**Closed as completed by tagliala** 2022-08-12 06:35 UTC
Labels: brand icon
