### ISSUE TITLE
fa-circle-o-notch is not centered

### ISSUE THREAD

**Issue by section6mcclen** [FortAwesome/Font-Awesome#3670] opened 2014-06-09 21:24 UTC
It appears that when you animate this font with fa-spin, the circle is slowing moving around (as if the center of the vector is not the center of the circle). This is extremely noticeable the larger it gets, so an fa-5x for example clearly shows the icon moving (rather than just rotating) when fa-spin is applied. Compared with fa-spinner which rotates without any movement to the center of the icon.

**Comment by hugotox** [comment] 2016-02-08 18:02
Hi! Please do not close this. The issue is present even in the font awesome examples page http://fortawesome.github.io/Font-Awesome/examples/

**Comment by isjns** [comment] 2016-04-19 12:43
This seems to be the case for a lot of icons. If you use FontAwesomeFX and then retrieve the icon as a `Text` node and then do `Text.setRotation(x)` while incrementing x (to create a spinning animation), all circular icons I've tried, e.g. "circle-o-notch", "cog" and "spinner", gets a "wobbling/shaking" effect due to the icon not being perfectly centered.

**Comment by tagliala** [comment] 2016-08-14 12:22
Since circle-o-notch already has some issues, I'm adding this to 5.0.0 milestone so Dave will eventually take a look

Ref: #9753 #8403

**Comment by LeanKit-Hunter** [comment] 2017-02-08 18:27
If this is still under consideration - this may help.

I was running into the same issue with the wobbly spinning and tried to replicate the icon manually as SVG instead and was experiencing wobble that way as well.

I think the notch removed at the top is shortening the file and making it off center. Changing the notch's placement allowed the SVG to still retain the full dimensions of a circle. When I changed my SVG to have the notch removed at about 45 degrees, the animation went a lot smoother.

![circle-notch-option](https://cloud.githubusercontent.com/assets/3309844/22751228/473ea3ac-edf9-11e6-9c32-fd2a3ca9983b.png)

**Comment by jpecor-pmi** [comment] 2017-11-07 20:07
I was able to remove the wobble effect from the spinning fa-circle-o-notch by manually setting the `transform-origin`, accounting for the missing height due to the notch.
```css
/* fix wobble on spinning circle-o-notch */
.fa-spin.fa-circle-o-notch {
    transform-origin: 50% 48.95%;
}
```

**Comment by tagliala** [comment] 2017-12-17 13:09
I'm going to close this one, because this is a duplicate of #671.

The issue does not depend on the centering of the circle, and it is still present in FA 5.0.1 webfont on firefox

Webfont: https://jsfiddle.net/tagliala/tgzouajm/18/

But the SVG does not have this issue:

SVG: https://jsfiddle.net/tagliala/f019sa7v/7/

Sorry but we can't fix this, please consider an SVG spinner

**Closed by tagliala** 2017-12-17 13:09 UTC
