### ISSUE TITLE
Icon request: lightbulb-shines

### ISSUE THREAD

**Issue by petergroenewegen** [FortAwesome/Font-Awesome#12409] opened 2018-02-21 13:38 UTC
Something like this:
https://thenounproject.com/search/?q=lightbulb&i=1263005

Use: convey the concept of 'bright idea' better

**Comment by tagliala** [comment] 2018-02-21 16:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2817, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-21 16:13 UTC
