### ISSUE TITLE
Icon request: Get Icon for AI 'hint'

### ISSUE THREAD

**Issue by Martin-HZK** [FortAwesome/Font-Awesome#20103] opened 2024-02-07 15:49 UTC
### Use case

When we are designing applications, chances are that we will have the AI recommendation system to give idea. Shopping is an example.

### Example image

I recommend an *ChatGPT* icon for the brand, and an *AI(merely the 'AI' in letters)* or *Robot* icon indicating that there lies the functionality for the user to get possible AI recommendations.

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2024-02-07 16:02
Hi!

Thanks for being part of the Font Awesome Community.

If you are interested in requesting an icon for Chat GPT, please open a new request using the Brand Request template

AI is related but not identical to #16690. I would avoid to leave `AI` and `Artificial Intelligence` both open at the same time, and `AI` is language-dependent, so we were looking for ideas to represent AI. In that case, I would consider this as a duplicate of  #16690

**Comment by Martin-HZK** [comment] 2024-02-07 16:15
Thank you for your timely response! Many thanks!!

**Comment by sensibleworld** [comment] 2024-07-11 14:12
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed as not planned by sensibleworld** 2024-07-11 14:12 UTC
Labels: new icon, Declined
