### ISSUE TITLE
Icon Request: fa-etsy

### ISSUE THREAD

**Issue by superdev1944** [FortAwesome/Font-Awesome#8181] opened 2015-12-19 17:47 UTC
Hello,

I would like to request an Etsy (https://www.etsy.com/) icon / logo.
Here's an example: https://www.etsy.com/images/favicon.ico

Thank you,
this icon would be a huge help!

**Comment by tagliala** [comment] 2015-12-19 20:06
duplicate of #1962 , please +1 that request

closing here

**Closed by tagliala** 2015-12-19 20:06 UTC
