### ISSUE TITLE
fa-kakao

### ISSUE THREAD

**Issue by narumam** [FortAwesome/Font-Awesome#10730] opened 2017-03-02 00:50 UTC
Famous sns icon in Korea. Hope you will accept this request, Thank you.
fa-kakao
[kakao.pdf](https://github.com/FortAwesome/Font-Awesome/files/812456/kakao.pdf)

**Comment by tagliala** [comment] 2017-03-02 22:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3688 or #6669 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-02 22:54 UTC
