### ISSUE TITLE
Icon request: desktop-plus

### ISSUE THREAD

**Issue by dimitrivdp** [FortAwesome/Font-Awesome#17903] opened 2021-05-15 08:31 UTC
Hi,

could it be possible to add a screen sharing icon.

Today we are using 'display'. But we would like to have the display icon with a plus inside, like the 'video-plus' icon that we are already using.

KR

Dimitri.

**Comment by tagliala** [comment] 2021-05-15 08:36
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #15050?

**Comment by dimitrivdp** [comment] 2021-05-16 07:16
That's more to switch/on and switch of screen sharing. 

We think more in the context of 'starting screen scharing'. We use similar icons for start video, add file and start chat.

<img width="260" alt="Screenshot 2021-05-16 at 09 12 48" src="https://user-images.githubusercontent.com/368730/118388875-4c004d00-b627-11eb-83d6-163a1847dedb.png">

KR

Dimitri.

**Comment by tagliala** [comment] 2021-05-16 10:24
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/528/
Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment] 2024-07-11 15:55
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 15:55 UTC
Labels: new icon, web application icons (legacy category), Declined
