### ISSUE TITLE
Icon request: icon-chronometer

### ISSUE THREAD

**Issue by raphaelluchini** [FortAwesome/Font-Awesome#6596] opened 2015-05-29 17:14 UTC
Would be great we have a chronometer icon, useful to control time, show time counter, etc.

Here an example:
![img](http://cdns2.freepik.com/free-photo/_318-64956.jpg)

**Comment by tagliala** [comment] 2015-05-29 19:21
duplicate of #1340, please +1 that request

closing here

**Closed by tagliala** 2015-05-29 19:21 UTC
