### ISSUE TITLE
icon request : Plug Dj

### ISSUE THREAD

**Issue by Coolwhip3** [FortAwesome/Font-Awesome#3587] opened 2014-05-30 19:00 UTC
I was thinking we could have a icon for the popular music/dj'ing website, http://plug.dj
It would look like this : 
http://www.google.ca/url?sa=i&source=images&cd=&docid=1DTtnuxkVeqBJM&tbnid=A3A9aZ7XqFcJmM:&ved=0CAgQjRw4CA&url=http%3A%2F%2Fwww.planetminecraft.com%2Fblog%2Fplugdj---dubstep-den-music-website%2F&ei=ftWIU-ugKIKMyAT7x4GgDQ&psig=AFQjCNGjcD_tigkY7V7xrMEeU9ZCgOkl8w&ust=1401562878701200

**Comment by Escendrix** [comment] 2015-03-26 04:31
this is a duplicate of #2932, please +1 it!

**Comment by tagliala** [comment] 2015-03-26 18:48
@Escendrix thanks

closing here

**Closed by tagliala** 2015-03-26 18:48 UTC
Labels: brand icons, new icon
