### ISSUE TITLE
"Pulse" effect broken on fontawesome.com

### ISSUE THREAD

**Issue by ALPIXELMaiki** [FortAwesome/Font-Awesome#14630] opened 2019-02-12 10:32 UTC
Hi Fontawesome team,

I twitted you several weeks about the broken "pulse" effect on your Homepage.
No answer :(

Your pulse exemple looks like a broken spin effect, but not a pulse effect at all !

Cheers (bisous)

---

edit by tagliala: removed zip attachment

**Comment by tagliala** [comment] 2019-02-12 14:11
Hi!

Thanks for being part of the Font Awesome Community.

> I twitted you several weeks about the broken "pulse" effect on your Homepage.

Sorry, please use github to report issues

> Your pulse exemple looks like a broken spin effect, but not a pulse effect at all !

That is working as intended 😅 

It is designed to work for this use case: https://jsfiddle.net/tagliala/z12wdapb/20/

If you want a heartbeat like pulse, please implement your own css animation

https://jsfiddle.net/tagliala/z12wdapb/24/

Hope it helps

Closing here

**Closed by tagliala** 2019-02-12 14:11 UTC

**Comment by ALPIXELMaiki** [comment] 2019-02-12 14:15
Oh ! thanks for your answer.
In this case, i think "pulse" is not the good name for this effect :)

Thanks a lot for your work.
Cheers (bisous)

**Comment by tagliala** [comment] 2019-02-12 14:24
You're welcome

> In this case, i think "pulse" is not the good name for this effect :)

FWIW, as a non English native speaker, I agree with you 👍
