### ISSUE TITLE
icon request: Close icon thin

### ISSUE THREAD

**Issue by Activee** [FortAwesome/Font-Awesome#7230] opened 2015-08-14 01:52 UTC
the current close icon http://fortawesome.github.io/Font-Awesome/icon/times/
is thick. It would be nice to have a close icon that is like 1 pixel thick. cheers.

PS: Font awesome is awesome.

**Comment by TheChen5** [comment] 2015-08-14 02:32
maybe fa-times-thin ?
I like the idea
+1

**Comment by TheChen5** [comment] 2015-08-14 02:33
Some icons thinner would make font awesome look more clean.

**Comment by YesThatAllen** [comment] 2015-08-14 11:52
:+1: 

I came here to make this request.. especially `fa-ban-thin`  just like there's `fa-circle-thin` already

**Comment by tagliala** [comment] 2015-08-14 16:04
duplicate of #1540 , please +1 that request

closing here

**Closed by tagliala** 2015-08-14 16:04 UTC
