### ISSUE TITLE
Support for SmugMug

### ISSUE THREAD

**Issue by jiripik** [FortAwesome/Font-Awesome#11993] opened 2017-12-26 10:24 UTC
Would it be possible for you to add a SmugMug icon from http://help.smugmug.com/customer/portal/articles/84541?b_id=1644?

**Comment by tagliala** [comment] 2017-12-26 12:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2561, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-26 12:06 UTC
