### ISSUE TITLE
Icon Request: fa-kakao-talk

### ISSUE THREAD

**Issue by onishibaki** [FortAwesome/Font-Awesome#6301] opened 2015-04-23 13:30 UTC
For social Icons. Thank you

![kakaotalk-logo](https://cloud.githubusercontent.com/assets/11409034/7298103/304e467a-e982-11e4-8727-1013fe171d53.png)

**Comment by tagliala** [comment] 2015-06-06 14:58
just notice this is a duplicate of #3688. no need to +1 that request, I will do it

**Closed by tagliala** 2015-06-06 14:58 UTC
