### ISSUE TITLE
Icon request fa-ebay

### ISSUE THREAD

**Issue by AdRock952** [FortAwesome/Font-Awesome#6764] opened 2015-06-16 08:00 UTC
Hi Font Awesome

Please can I request a new icon for eBay?  I see there is an icon for PayPal but nothing for eBay

Many thanks

Adam

**Comment by tagliala** [comment] 2015-06-16 09:23
duplicate of #1783 , please +1 that request

closing here

**Closed by tagliala** 2015-06-16 09:23 UTC
