### ISSUE TITLE
Bug: "transgender" icon renders as "mars-and-venus" icon

### ISSUE THREAD

**Issue by MartinSchmid2409** [FortAwesome/Font-Awesome#19609] opened 2023-03-13 18:05 UTC
### Bug description

Adding the icon with css classes "fa-solid fa-transgender" renders it as "fa-solid fa-mars-and-venus".

I´ve started to use v6.3.0 just now, so I don´t know if this a new issue or was already a bug in previous versions.

Using "transgender" as unicode "f225" just renders fine, on the other hand.

### Font Awesome version

v6.3.0

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

Windows 10

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment] 2023-03-13 18:23
Hey @MartinSchmid2409. Thanks for the report. This was a change we made in version 6.0 to be more consistent with our naming, and with the established default icons used in the transgender community. You can see more about that here: https://github.com/FortAwesome/Font-Awesome/issues/10432

But based on the scenario you described above, it looks like you might still be using v5, but referencing the v6 icon search.

**Comment by MartinSchmid2409** [comment] 2023-03-13 18:38
Hi, well, I am not a real expert on these gender signs, but it seems to be a bug as FontAwesome was never used in my project beforehand, but got a fresh v6.3.0 installation.

Also, it does not make any sense to render "transgender" (meaning transsexuality or sometimes non-binary gender identity) as "mars-venus" (meaning intersexuality or bigender identity). These are two different meanings. Your reference to #10432 does not make much sense in this context.

Also, the icon for "non-binary" gender is actually missing: https://en.wikipedia.org/wiki/Non-binary_gender (icon below)

I know, this is somehow science by itself. But your implementation is not correct and incomplete.

**Comment by sensibleworld** [comment] 2023-03-13 18:59
In version 5, the icon named "transgender" rendered as a circle with an arrow point up-right and a cross pointing down.

<img width="289" alt="CleanShot 2023-03-13 at 14 52 38@2x" src="https://user-images.githubusercontent.com/529604/224801327-b3f55846-34a1-4ac0-9cea-d96073e5c947.png">

With version 6, after feedback in the referenced thread (as well as others who wrote in to support), we corrected the default "transgender" icon and renamed the existing icon to "mars-and-venus".

<img width="717" alt="CleanShot 2023-03-13 at 14 56 19@2x" src="https://user-images.githubusercontent.com/529604/224802164-0fe9a1e8-5b6b-4ef2-b5e1-9ad24098031d.png">

Do you have a link to the project that we could take a look at to see what might be happening?

(Also, thanks for the recommendation of the non-binary icon. That would make a good addition to Font Awesome.)

**Comment by MartinSchmid2409** [comment] 2023-03-13 19:15
Concerning the concept, you made the right corrections.

Still, the implementation is wrong. 

As you can see on the screenshot: transgender renders as mars-venus. It´s a bug.

![transgender_bug](https://user-images.githubusercontent.com/1540028/224807653-649a9443-08b5-4344-b32e-abecbff9ac75.png)

**Comment by sensibleworld** [comment] 2023-03-13 19:19
How are you serving the icons? Is this with one of our hosted kits, or are you self-hosting?

**Comment by MartinSchmid2409** [comment] 2023-03-13 19:20
Self-hosted.

I downloaded "6.3.0 for the web" -> "Free for web" directly from your site.

**Comment by sensibleworld** [comment] 2023-03-13 19:24
Thanks. We'll look into what might be happening.

**Comment by tagliala** [comment] 2023-03-13 19:47
I cannot reproduce here: http://jsfiddle.net/tagliala/vuren0mg/4/

Can you please provide a reproducible test case?

**Comment by MartinSchmid2409** [comment] 2023-03-13 23:27
I can only tell what I did in my project.

Added FA to `<head>`:

```
<link href="#{request.contextPath}/web/lib/css/fontawesome-free-6/css/fontawesome.min.css" rel="stylesheet" type="text/css" />
<link href="#{request.contextPath}/web/lib/css/fontawesome-free-6/css/solid.min.css" rel="stylesheet" type="text/css" />
<link href="#{request.contextPath}/web/lib/css/fontawesome-free-6/css/brands.min.css" rel="stylesheet" type="text/css" />
```

Added FA to my standard font:

`font-family: 'Montserrat', sans-serif, 'Font Awesome 6 Free', 'Font Awesome 6 Brands';`

----------------------

Again, when using the unicode representation of the transgender symbol, it is shown as expected. 

But using the class "fa-transgender" leads to the aforementioned bug.

----------------------

I also used ~30 other FA icons in my project. They do not have this issue.

**Comment by tagliala** [comment] 2023-03-14 08:44
Hi,

thanks for the details.

The usage is not the one suggested (font awesome should not be a fallback of other fonts), however I'm still not able to reproduce: https://jsfiddle.net/tagliala/vuren0mg/8/

I think that there could be a different version of FA or some css rules conflicting, so if it is possible please provide a reproducible test case

**Comment by MartinSchmid2409** [comment] 2023-03-14 20:59
I cannot provide a test case. This is a huge project I am working on. 

But I can assure you there is no older version of FA in place. I am sure that none of my CSS rules cause this bug.

**Comment by sensibleworld** [comment] 2023-08-09 17:45
As we haven't been able to reproduce the issue, I'm going to close this. If it's still a problem, certainly let us know! And if you have a link to a site we can take a look at, even better.

Thanks!

**Closed as completed by sensibleworld** 2023-08-09 17:45 UTC
Labels: bug, needs-triage
