### ISSUE TITLE
Icon Request: Letterbox

### ISSUE THREAD

**Issue by sarahk** [FortAwesome/Font-Awesome#13950] opened 2018-09-14 20:28 UTC
A letterbox to use alongside physical addresses would be handy.
thanks!
![mailbox-closed-flag-up](https://user-images.githubusercontent.com/666147/45573608-390aad00-b8c1-11e8-8693-1fb2a01f0731.png)

**Comment by tagliala** [comment] 2018-09-14 22:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4849, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-14 22:43 UTC
