### ISSUE TITLE
Icon Request: fa-markdown

### ISSUE THREAD

**Issue by slavidodo** [FortAwesome/Font-Awesome#8393] opened 2016-01-23 11:02 UTC
"Styling with markdown" icon.
```html
<i class="fa fa-mark-down"></i>
```
![markdown](http://kirkstrobeck.github.io/whatismarkdown.com/img/markdown.png)

Thanks!

**Comment by tagliala** [comment] 2016-01-23 11:20
duplicate of #1557 , please +1 that request

closing here

**Closed by tagliala** 2016-01-23 11:20 UTC
