### ISSUE TITLE
Balloon???

### ISSUE THREAD

**Issue by terminalbe** [FortAwesome/Font-Awesome#17508] opened 2020-12-26 05:31 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-12-26 09:55
Hi!

Thanks for being part of the Font Awesome Community.

I think this request is a duplicate of #10494

If it isn't a duplicate, please fix the title, provide an example of the icon you need and comment in this request

Meanwhile, closing here

**Closed by tagliala** 2020-12-26 09:55 UTC

**Comment by terminalbe** [comment] 2020-12-28 04:19
So it’s been around for 3 years, and nothing has been done about it? And this is what we are paying for???

Best regards,
Cheng-Yu Lee
Senior Marketing Consultant
Terminal Be Design Group

**Comment by tagliala** [comment] 2020-12-28 08:16
> So it’s been around for 3 years, and nothing has been done about it?

Hi again,

You may be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work
