### ISSUE TITLE
Icon request: icon-open book / magazine / catalog

### ISSUE THREAD

**Issue by carissam** [FortAwesome/Font-Awesome#10093] opened 2016-10-20 15:09 UTC
Hi there,

I LOVE Font Awesome, but am looking for an open book/magazine/catalog icon for my company's website. I know there is already a book icon, but it is closed, and therefore more limited in its use. An open book concept (where you can see the pages rather than just the cover) would allow people to use the icon to represent either a book, magazine, online catalog, study guide, business plan... the options are endless! 

Personally, I would like it to represent an online flipbook catalog of our products. 

I have attached photos of a few different icons I found on Canva, that represent what I am looking for. Any of these (or variations of these) would be perfect! I found them on canva by searching for "book icon" and "booklet icon". 

Thank you so much! Keep making Font Awesome, well, **awesome**! :)
Carissa

![book 3](https://cloud.githubusercontent.com/assets/18664239/19565628/81a0415e-96b5-11e6-9f1f-948e8a68ef30.JPG)
![book 2](https://cloud.githubusercontent.com/assets/18664239/19565626/81959b50-96b5-11e6-81d7-68f8de8a1cf0.JPG)
![book icon 1](https://cloud.githubusercontent.com/assets/18664239/19565627/819eaf24-96b5-11e6-9a16-14ab5060bb79.JPG)

**Comment by tagliala** [comment] 2016-10-20 15:47
Duplicate of #176 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-20 15:47 UTC
