### ISSUE TITLE
Brand request: Anilist.co

### ISSUE THREAD

**Issue by ukriu** [FortAwesome/Font-Awesome#20200] opened 2024-04-20 06:59 UTC
### Description

[AniList](https://anilist.co/) is a site to track, share or discover your anime/manga/light novels. It has leaderboards and a versatile tracking system, its a competitor to [myanimelist](https://myanimelist.net/).
It is useful for persona websites which would like to use this brand icon to link their AniList profiles and share their progress/ratings for shows.

Here is an example SVG icon for AniList: 
![anilist](https://github.com/FortAwesome/Font-Awesome/assets/80760888/cd112419-d4e9-47ed-b5da-a4d7b0662d6f)
(I wasn't able to find the brand toolkit/guidelines)

### Official website

https://anilist.co/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2024-04-20 07:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17954 , please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-04-20 07:54 UTC
Labels: brand icon
