### ISSUE TITLE
Icon request: fa-transciever

### ISSUE THREAD

**Issue by VA6DAH** [FortAwesome/Font-Awesome#3868] opened 2014-07-07 15:22 UTC
Useful for: anyone needing a transciever (e.g. broadcasters, radio stations, etc)

Examples:

![image](https://cloud.githubusercontent.com/assets/7734467/3497313/8e237864-05ea-11e4-9c39-2db7aa2e349c.png)

**Comment by elmer-t** [comment] 2018-03-23 22:31
+1

**Comment by sensibleworld** [comment] 2024-07-11 13:51
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/4471)

**Closed by sensibleworld** 2024-07-11 13:51 UTC
Labels: new icon, web application icons (legacy category), Duplicate
