### ISSUE TITLE
Icon request: sketchfab logo

### ISSUE THREAD

**Issue by Ollie-Anderson** [FortAwesome/Font-Awesome#19000] opened 2022-05-03 18:55 UTC
it would be very useful fo r3d artists to be able to link to sketchfab for their personal pages or next to embedded models. i would greatly apprec iate this icon being added.

here's a link to the site: https://sketchfab.com/

thanks

**Comment by tagliala** [comment] 2022-05-03 19:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2757, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-05-03 19:09 UTC
