### ISSUE TITLE
Icon Request: fa-cc-dankort

### ISSUE THREAD

**Issue by balexandre** [FortAwesome/Font-Awesome#9591] opened 2016-07-18 20:28 UTC
[Dankort](https://www.google.com/search?q=dankort&source=lnms&tbm=isch): Danish credit card

![](https://upload.wikimedia.org/wikipedia/commons/5/51/Dankort_logo.png)

**Comment by aethior** [comment] 2016-07-19 09:21
Duplicate of #8460. Please :+1: that.

**Closed** 2016-07-19 09:37 UTC
