### ISSUE TITLE
Icon Request: fa-3d-print

### ISSUE THREAD

**Issue by OnlyDrey** [FortAwesome/Font-Awesome#9949] opened 2016-09-22 12:13 UTC
3D printers are getting really popular and there is no icon? It is cool that the fa-print icon exists. But a 3D print icon in 2016 is a must.

http://www.freeiconspng.com/uploads/3d-printer-icon-5.png

**Comment by tagliala** [comment] 2016-09-22 13:36
Duplicate of #7625, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-22 13:36 UTC
