### ISSUE TITLE
Icon Request: fa-gel

### ISSUE THREAD

**Issue by dlapi10** [FortAwesome/Font-Awesome#10362] opened 2016-12-14 10:15 UTC
Georgian Lari icon https://www.nbg.gov.ge/index.php?m=630&lng=eng

**Comment by tagliala** [comment] 2016-12-14 13:50
Duplicate of #3973, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-14 13:50 UTC
