### ISSUE TITLE
Icon Request: fa-forklift

### ISSUE THREAD

**Issue by GerritP** [FortAwesome/Font-Awesome#11470] opened 2017-08-31 00:40 UTC
Hi there,

a forklift icon would be very useful:

![image](https://user-images.githubusercontent.com/31493266/29901000-13581cc8-8dbb-11e7-8818-c6b026b5a28a.png)

Greetings

**Comment by tagliala** [comment] 2017-08-31 09:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #692 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-31 09:17 UTC
