### ISSUE TITLE
Icon request: wave-icon

### ISSUE THREAD

**Issue by mtpultz** [FortAwesome/Font-Awesome#12513] opened 2018-03-04 08:19 UTC
### What can it be used for?

Wave indicator for weather and ocean-related applications.

### Example image (optional)

![image](https://user-images.githubusercontent.com/599498/36943666-0dafc9da-1f4a-11e8-955c-a3faa16a6a6a.png)

![image](https://user-images.githubusercontent.com/599498/36943645-e35e01e2-1f49-11e8-96a6-110ac4fe4274.png)

![image](https://user-images.githubusercontent.com/599498/36943654-f7051faa-1f49-11e8-8a31-989008270236.png)

**Comment by tagliala** [comment] 2018-03-04 10:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2266, please add a 👍  reaction to that request and post there your examples

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-04 10:54 UTC
