### ISSUE TITLE
Icon request: Buy Me a Coffee

### ISSUE THREAD

**Issue by DylanDevelops** [FortAwesome/Font-Awesome#19868] opened 2023-08-20 23:25 UTC
### Use case

This website is for receiving money from users to fund projects and people.

### Example image

SVGs ([From the branding kit](https://www.buymeacoffee.com/downloads)):
![logo-mark-3](https://github.com/FortAwesome/Font-Awesome/assets/48571264/351b849a-32c4-4a6a-b729-69e54e0afd48)

![bmc-logo](https://github.com/FortAwesome/Font-Awesome/assets/48571264/549a2ec2-bd88-4785-b7c8-dcff818be31c)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by DylanDevelops** [comment] 2023-08-20 23:25
I'm not sure if brands are allowed in here, but there's font awesome for twitter, GitHub, youtube, etc..

**Comment by tagliala** [comment] 2023-08-21 07:21
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16336, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-08-21 07:21 UTC
Labels: new icon
