### ISSUE TITLE
Icon request: c-sharp

### ISSUE THREAD

**Issue by jessipearcy** [FortAwesome/Font-Awesome#15504] opened 2019-09-09 14:35 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
Developer portfolio site, learning to code sites, other awesome c# stuff

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/29112432/64539876-e2259100-d2e4-11e9-98e5-38dcdd311d42.png)

**Icon request checklist**
- [single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-09-09 14:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8365, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-09 14:54 UTC
