### ISSUE TITLE
Icon Request: fa-waves

### ISSUE THREAD

**Issue by roarytubbs** [FortAwesome/Font-Awesome#7840] opened 2015-11-06 16:12 UTC
Would love to see an icon for water

**Comment by TheChen5** [comment] 2015-11-06 23:34
Would icon-tint work?
http://fortawesome.github.io/Font-Awesome/icon/tint/

**Comment by roarytubbs** [comment] 2015-11-09 02:20
I'm thinking something more like the waves icon on this site - http://fontello.com/

**Comment by tagliala** [comment] 2015-11-09 11:25
So let's rename this

**Comment by jckb188** [comment] 2017-01-26 21:03
+1

**Comment by nikkiroylance** [comment] 2017-02-03 12:56
+1

**Comment by tagliala** [comment] 2017-07-08 11:24
I'm going to consider this as a duplicate of #2266, which has more +1s and it's older

**Closed by tagliala** 2017-07-08 11:24 UTC
Labels: new icon, video player icons
