### ISSUE TITLE
Icon request: icon-multi-devices

### ISSUE THREAD

**Issue by lologic** [FortAwesome/Font-Awesome#11552] opened 2017-09-23 16:11 UTC
It would be nice to have the combination of the existing device incons as a "multi device icon". Would be very useful to tell visitors of a website that this product works on all devices.  Here what I expect.

![multidevices](https://user-images.githubusercontent.com/26777182/30774938-8b12f9cc-a08a-11e7-8b06-3e931ca256be.JPG)

**Comment by tagliala** [comment] 2017-09-24 08:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1446 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-24 08:07 UTC
