### ISSUE TITLE
Icon Request: fa-aparat

### ISSUE THREAD

**Issue by Mojtabarahimi8** [FortAwesome/Font-Awesome#12535] opened 2018-03-07 16:07 UTC
aparat is number one video service in iran, you can find in their logos in here
https://www.aparat.com/logo

**Comment by tagliala** [comment] 2018-03-07 16:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5204 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-07 16:13 UTC
