### ISSUE TITLE
Icon request: fa-aspect-ratio

### ISSUE THREAD

**Issue by delijah** [FortAwesome/Font-Awesome#19647] opened 2023-04-03 14:45 UTC
### Use case

Choosing an aspect ratio (from a list of available aspect ratios) for an image.

### Example image

<img width="103" alt="Screenshot 2023-04-03 at 16 45 24" src="https://user-images.githubusercontent.com/237739/229544893-f8b46a2e-1b3a-417c-928f-cf905addc90c.png">

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by delijah** [comment] 2023-04-13 08:15
We could achieve having a decent icon combining the faExpand icon with the faUpRightAndDownLeftFromCenter. So i'd be ok if you feel like closing this PR.

**Comment by aethior** [comment] 2023-04-13 20:13
Duplicate of #8182.
Please add a 👍 reaction to that request.

Regards.

**Comment by tagliala** [comment] 2023-04-13 20:30
Thanks, I was not able to find that request

**Closed as completed by tagliala** 2023-04-13 20:30 UTC
Labels: new icon
