### ISSUE TITLE
Icon request: step-over

### ISSUE THREAD

**Issue by JerGallagher-TMobile** [FortAwesome/Font-Awesome#18139] opened 2021-08-04 17:18 UTC
**What can it be used for?**
Debugging icon to step over a breakpoint

**Example image **
![image](https://user-images.githubusercontent.com/56324769/128224935-dd5e0c06-2402-429e-b057-9c3df6fb9393.png)

Related icons are:
- step-into
- step-out
- step
![image](https://user-images.githubusercontent.com/56324769/128225355-2e3845e8-4339-4802-9cee-7a0b5a9b7dbe.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-08-04 17:34
Subset of #18138

**Comment by sensibleworld** [comment] 2024-07-11 15:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/5673)

**Closed by sensibleworld** 2024-07-11 15:23 UTC
Labels: new icon, web application icons (legacy category), Duplicate
