### ISSUE TITLE
Icon Request: fa-car-wrench

### ISSUE THREAD

**Issue by TrieuNguyenHo** [FortAwesome/Font-Awesome#8921] opened 2016-04-08 06:15 UTC
describle that something is damaged.

**Comment by truls1502** [comment] 2016-04-08 09:17
Hi @TrieuNguyenHo, could you please give an example? And what is the damage related to?

**Comment by TrieuNguyenHo** [comment] 2016-04-09 08:10
Hi, I'm building an mobile app for check car, if car has any damage I will
click to an icon and system will recognizes that car has damaged and store
the information in Database, so I need an icon that refer to an damaged
car. Please help me, thank you.

2016-04-08 16:18 GMT+07:00 Truls <notifications@github.com>:

> Hi @TrieuNguyenHo <https://github.com/TrieuNguyenHo>, could you please
> give an example? And what is the damage related to?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/8921#issuecomment-207343126>
>



-- 
Nguyễn Hồ Hải Triều.
Java Developer at DOU's Network.
Phone: 0963102024.

**Comment by truls1502** [comment] 2016-04-09 09:00
Hi @TrieuNguyenHo . Do you have any preference how the icon should look?

I just tried to combine with multiple icons such as:

```html
<!DOCTYPE html>
<html>
<head>
<title>Font Awesome Icons</title>
<style>
.damaged {
  color: red;
}
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>

<span class="fa-stack fa-3x">
  <i class="fa fa-car fa-stack-1x"></i>
  <i class="fa fa-ban fa-stack-2x damaged"></i>
</span>

<span class="fa-stack fa-2x">
  <i class="fa fa-car fa-stack-2x"></i>
  <i class="fa fa-wrench fa-stack-2x fa-rotate-270 damaged"></i>
</span>

</body>
</html>
```

Otherwise you might ask for new icon if they doesn't suit what you need. I just googled and found what I think would be ok as you described. What do you think about it http://amwbmwspecialists.co.uk/communities/8/000/001/505/258//images/5526444_110x110.png or http://www.autodimensionsplusofnyinc.com/image/105194877.png?

**Comment by tagliala** [comment] 2016-04-09 09:25
Duplicate of #8817, please +1 that request

Please also consider @truls1502 's suggestion

closing here

**Comment by TrieuNguyenHo** [comment] 2016-04-11 01:44
Dear,
Thank you for your supporting.

2016-04-09 16:25 GMT+07:00 Geremia Taglialatela <notifications@github.com>:

> Closed #8921 <https://github.com/FortAwesome/Font-Awesome/issues/8921>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/8921#event-621021363>
>



-- 
Nguyễn Hồ Hải Triều.
Java Developer at DOU's Network.
Phone: 0963102024.

**Comment by TrieuNguyenHo** [comment] 2016-04-11 02:03
Sorry, I think  http://www.autodimensionsplusofnyinc.com/image/105194877.png is
good, please help me create that icon. Thank you.

2016-04-11 8:44 GMT+07:00 Hải Triều Nguyễn Hồ <hohaitrieuntu@gmail.com>:

> Dear,
> Thank you for your supporting.
>
> 2016-04-09 16:25 GMT+07:00 Geremia Taglialatela <notifications@github.com>
> :
>
>> Closed #8921 <https://github.com/FortAwesome/Font-Awesome/issues/8921>.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FortAwesome/Font-Awesome/issues/8921#event-621021363>
>>
>
>
>
> --
> Nguyễn Hồ Hải Triều.
> Java Developer at DOU's Network.
> Phone: 0963102024.
>



-- 
Nguyễn Hồ Hải Triều.
Java Developer at DOU's Network.
Phone: 0963102024.

**Comment by tagliala** [comment] 2016-04-11 09:23
Reopening as `fa-car-wrench`

**Comment by tagliala** [comment] 2016-04-11 09:25
@TrieuNguyenHo you need a proper .svg file of that icon and you can easily customize fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by TrieuNguyenHo** [comment] 2016-04-11 16:23
Thank you so much.

2016-04-11 16:25 GMT+07:00 Geremia Taglialatela <notifications@github.com>:

> @TrieuNguyenHo <https://github.com/TrieuNguyenHo> you need a proper .svg
> file of that icon and you can easily customize fontawesome:
> https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/8921#issuecomment-208248303>
>



-- 
Nguyễn Hồ Hải Triều.
Java Developer at DOU's Network.
Phone: 0963102024.

**Comment by sensibleworld** [comment] 2018-08-09 19:41
https://fontawesome.com/icons/car-mechanic?style=solid

**Closed by sensibleworld** 2018-08-09 19:41 UTC
Labels: new icon, released, web application icons
