### ISSUE TITLE
Icon Request: fa-cloche

### ISSUE THREAD

**Issue by maljukan** [FortAwesome/Font-Awesome#11099] opened 2017-05-21 22:45 UTC
Use case: Websites for restaurants, cooking, dinning
![dome-cloche](https://cloud.githubusercontent.com/assets/1965698/26288005/9839516a-3e87-11e7-8baf-a6656b1a49a7.jpg)

**Comment by tagliala** [comment] 2017-05-22 08:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3453, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-22 08:41 UTC
