### ISSUE TITLE
5.2.0 Desktop contains 5.1 OTF files

### ISSUE THREAD

**Issue by dscottfont** [FortAwesome/Font-Awesome#13762] opened 2018-08-13 15:22 UTC
Downloading the desktop files for 5.2.0 to Mac results in OTF files that read 5.1 in the file description, and do not contain new glyphs.

**Comment by InsanityMeetsHH** [comment] 2018-08-13 15:51
See #13667

**Comment by tagliala** [comment] 2018-08-13 16:19
Duplicate of #13667, please read that thread

Closing here

**Closed by tagliala** 2018-08-13 16:19 UTC

**Comment by dscottfont** [comment] 2018-08-13 19:15
@tagliala @InsanityMeetsHH - can you connect the dots - I've looked into #13667 and there does not appear to be an answer, other than it is coming with 5.3 ? How can I currently use a new glyph only available in 5.2 in sketch on desktop?

**Comment by tagliala** [comment] 2018-08-13 22:48
>  How can I currently use a new glyph only available in 5.2 in sketch on desktop?

The version number is wrong, but the font file is correct

Please try to uninstall FA 5.1, restart your mac and install 5.2
