### ISSUE TITLE
Icon Request: fa-ce-mark

### ISSUE THREAD

**Issue by hellsing71** [FortAwesome/Font-Awesome#7079] opened 2015-07-29 20:08 UTC
No, it's not a new face icon.

The CE marking is superwidely used, it is a mandatory conformity marking for products sold within the European Economic Area (EEA). It looks like this:

![280px-conformite_europeenne_ logo svg](https://cloud.githubusercontent.com/assets/8152173/8968314/ac3fdc06-363c-11e5-853b-54119e436b34.png)

Important: its not a simple pair of uppercase C+E letters. This is how it must be drawn:

![draw-ce-marking](https://cloud.githubusercontent.com/assets/8152173/8968406/3aecafec-363d-11e5-8c23-327f83a90de4.png)

It could be used on manufacturers' and e-commerce sites that delivers to or within the European Union.

Maybe our friends over the ocean are interested in an FCC conformity mark, too.

**Comment by TheChen5** [comment] 2015-07-29 20:50
Dupe of #4927
+1 that
:mag:before:heavy_plus_sign:

**Comment by hellsing71** [comment] 2015-07-30 11:31
Sorry for not checking.

**Closed** 2015-07-30 11:31 UTC
