### ISSUE TITLE
Icon request: icon-key-pad

### ISSUE THREAD

**Issue by dlhuffmanjr** [FortAwesome/Font-Awesome#13121] opened 2018-05-11 17:46 UTC
like something that could represent the dial pad on a phone.  Perhaps a 3x3 or a 4x3 grid would work.

**Comment by InsanityMeetsHH** [comment] 2018-05-14 11:26
May be you could build it by your own with [Layering, Text, & Counters](https://fontawesome.com/how-to-use/svg-with-js)
[icon 1](https://fontawesome.com/icons/th?style=solid), [icon 2](https://fontawesome.com/icons/square?style=solid) and some digits as text.

**Comment by tagliala** [comment] 2018-05-14 12:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6266, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-14 12:01 UTC
