### ISSUE TITLE
phone with direction

### ISSUE THREAD

**Issue by neburton70** [FortAwesome/Font-Awesome#15280] opened 2019-07-19 14:26 UTC
For use in a report showing Inbound and Outbound calls

use:
Existing fas fa-phone with a small direction arrow going out
Existing fas fa-phone with a small direction arrow going in

**Comment by tagliala** [comment] 2019-07-19 14:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3701 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-07-19 14:27 UTC
