### ISSUE TITLE
Icon Request: fa-shoppingbag

### ISSUE THREAD

**Issue by shaimanor** [FortAwesome/Font-Awesome#7094] opened 2015-07-30 16:42 UTC
I believe this has been asked for many times and despite updates to fontawesome I do not see this.

I would love a shopping bag rather than a shopping cart to be included. Cart's are for supermarkets while most shops online sell their products in bags!

Thank you for your great work!

**Comment by tagliala** [comment] 2015-07-30 17:24
duplicate of #829

**Closed by tagliala** 2015-07-30 17:24 UTC
