### ISSUE TITLE
Icon request: icon-signature

### ISSUE THREAD

**Issue by MustangChris04** [FortAwesome/Font-Awesome#12726] opened 2018-03-28 20:34 UTC
Hello, 

Just a suggestion to add a "Signature" button. I think this would be helpful to represent someone's signature, or as a button that someone can click on to sign their name. Currently the pencil icons look too much like an "edit" icon, and don't really represent a cursive signature. 

I was thinking something like this: https://www.iconfinder.com/icons/515481/autograph_handwritten_sign_signature_icon#size=256 

or this: https://www.iconfinder.com/icons/181722/sign_signature_icon#size=256 

Cheers!

**Comment by tagliala** [comment] 2018-04-06 15:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5663 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 15:45 UTC
