### ISSUE TITLE
Icon request: organic-food, non-gmo

### ISSUE THREAD

**Issue by thammuio** [FortAwesome/Font-Awesome#15281] opened 2019-07-19 15:54 UTC
**What can it be used for?**
Used for representing Organic and non-GMO Food 

**Example image (optional)**
I do not have and examples.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-07-19 16:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8291, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-07-19 16:04 UTC

**Comment by thammuio** [comment] 2019-07-19 17:00
@tagliala thanks for your reply. this request id for couple of things 1. Organic Food, 2. non-GMO Food.
I checked the existing requests, but they are requesting to make well known logos to convert into icons as here - https://github.com/FortAwesome/Font-Awesome/issues/8291 and https://github.com/FortAwesome/Font-Awesome/issues/8290 . But what I was looking is for general icons that represent 1. Organic Food, 2. non-GMO Food (like how a smiley face can represent happiness). 

Let me know your thoughts if this makes sense or Let me know if these symbols already exist in current icons.

**Comment by tagliala** [comment] 2019-07-19 19:22
if organic food and non-gmo food are two separate concepts and require two separate icons, we should keep them in two separate requests

Since there is no example in this icon and no example in #8291, I cannot tell if they are two separate icons or they aren't

If you want me to reopen this as `organic-food` and leave #8291 for `non-gmo` that's fine, but we should provide a single color, 16px icon suitable example
