### ISSUE TITLE
Icon Request: fa-periscope, fa-snapchat

### ISSUE THREAD

**Issue by Souvik1991** [FortAwesome/Font-Awesome#8357] opened 2016-01-17 09:27 UTC
We are using font awesome to display icons in our site. But we find out that there are no icon available for periscope and snapchat.
So, can you please create icons for periscope and snapchat. So, that we can integrate those icons in our product.
Thanks in advance.

![periscope-logo](https://cloud.githubusercontent.com/assets/5055345/12376747/02fd9db6-bd2a-11e5-94fd-343c6fa0b1b3.jpg)
![snapchat](https://cloud.githubusercontent.com/assets/5055345/12376748/03009dc2-bd2a-11e5-870a-c51769d03b35.png)

**Comment by aethior** [comment] 2016-01-17 12:00
Hi @Souvik1991,

Snapchat is duplicate of #3906 and periscope is duplicate of #8356.

Regards.

**Closed** 2016-01-17 15:09 UTC
