### ISSUE TITLE
Icon request: view-360

### ISSUE THREAD

**Issue by phidang0810** [FortAwesome/Font-Awesome#13738] opened 2018-08-09 03:09 UTC
### What can it be used for?

I need view-360 icon for 360video project, and panorama image.
I think it's very popular

### Example image (optional)

![image](https://user-images.githubusercontent.com/7651665/43875668-889f38ae-9bbb-11e8-8170-261c5ae5f47e.png)

Link reference: http://glyphicons.com and search "360"

**Comment by tagliala** [comment] 2018-08-09 07:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #772, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-09 07:30 UTC
