### ISSUE TITLE
Card Deck Icons

### ISSUE THREAD

**Issue by pioz** [FortAwesome/Font-Awesome#13901] opened 2018-09-06 12:09 UTC
I would like the addition of card deck icons like these:
![deck](https://static.thenounproject.com/png/20461-200.png)
![deck](https://static.thenounproject.com/png/219525-200.png)

**Comment by tagliala** [comment] 2018-09-06 15:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2101, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-06 15:54 UTC
