### ISSUE TITLE
cPanel Icon!

### ISSUE THREAD

**Issue by owenbick** [FortAwesome/Font-Awesome#7245] opened 2015-08-17 01:32 UTC
A nice icon would be the CP part of the cPanel logo :smile:

**Comment by TheChen5** [comment] 2015-08-17 03:37
I like cPanel
BUT...
This is a dupe of #2846 
Please +1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-17 08:09
closing here

**Closed by tagliala** 2015-08-17 08:09 UTC
