### ISSUE TITLE
Icon Request: fa-msedge

### ISSUE THREAD

**Issue by martinkearn** [FortAwesome/Font-Awesome#7320] opened 2015-08-27 14:11 UTC
An icon for the new Microsoft Edge browser which replaces Internet Explorer in Windows 10

For example:
![image](http://betanews.com/wp-content/uploads/2015/07/microsoft_edge_icon-600x400.jpg)

**Comment by caduvieira** [comment] 2015-08-27 20:12
Will be in 4.4.1 dupe of #7059

**Closed** 2015-09-14 15:47 UTC
