### ISSUE TITLE
Icon Request: fa-user-o

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [FortAwesome/Font-Awesome#9356] opened 2016-06-07 12:11 UTC
fa-user-o

**Comment by tagliala** [comment] 2016-06-07 13:26
Duplicate of #3671 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-07 13:26 UTC
