### ISSUE TITLE
Icon Request: icon-Academia, icon-ResearchGate

### ISSUE THREAD

**Issue by lashend** [FortAwesome/Font-Awesome#12011] opened 2017-12-29 02:06 UTC
I would love an FA icon I could use to link to my Academia and ResearchGate Profiles. 

Here are the sites: 
www.academia.edu
www.researchgate.net

And here are their logos: 
![academia](https://user-image
![academia](https://user-images.githubusercontent.com/33768520/34427667-c40580fa-ec12-11e7-8632-8e603264e486.png)
![researchgate](https://user-images.githubusercontent.com/33768520/34427668-c42bc44a-ec12-11e7-9b41-81520e4aa879.png). 

Thank you! :)

**Comment by tagliala** [comment] 2017-12-29 09:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2751 and #3634, please add a 👍  reaction to those requests.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-29 09:19 UTC
