### ISSUE TITLE
Icon Request: fa-semaphore

### ISSUE THREAD

**Issue by smtrejo** [FortAwesome/Font-Awesome#10865] opened 2017-03-30 16:30 UTC
Hi,

I'd like to use a semaphore icon on a webform that indicates sercives's status.

Thank you.

**Comment by PeterShaggyNoble** [comment] 2017-03-30 16:34
See #2456.

**Comment by aethior** [comment] 2022-03-09 02:26
Duplicate of #2456.

cc/ @tagliala

**Closed** 2022-03-09 16:27 UTC
