### ISSUE TITLE
Icon request: flip-rotate

### ISSUE THREAD

**Issue by ZHENYAio** [FortAwesome/Font-Awesome#15891] opened 2019-12-02 11:44 UTC
Could be used to flip objects by 180deg, like cards/tiles to view the back/front.

<img width="55" alt="flip-rotate" src="https://user-images.githubusercontent.com/13453103/69956695-f7cfde80-1500-11ea-901c-9eee2d7eca5a.png">

Other names: flip-horizontal, rotate-y, rotate-axis

**Comment by tagliala** [comment] 2019-12-13 22:17
Hi!

Thanks for being part of the Font Awesome Community.

I'm pretty confident this is a duplicate, but at the moment I'm not able to find the original request.

If you have some synonyms in mind, please try a search here: https://github.com/FortAwesome/Font-Awesome/search?type=Issues

**Comment by spoike** [comment] 2020-02-11 13:55
There are a bunch of flip/mirror icon suggestions.

* #14426
* #11624
* #3955
* #2531

**Comment by sensibleworld** [comment] 2024-07-11 18:22
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/16550)

**Closed by sensibleworld** 2024-07-11 18:22 UTC
Labels: new icon, design (category), Duplicate
