### ISSUE TITLE
wedding icon (couple icon or something as we can use for wedding)

### ISSUE THREAD

**Issue by nehasingh15** [FortAwesome/Font-Awesome#13616] opened 2018-07-25 13:40 UTC
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by nehasingh15** [comment] 2018-07-25 13:48
as i have seen there is not a single icon which can be use for wedding theme so i request to please provide couple icon or any new which can be use for wedding or couple

**Comment by tagliala** [comment] 2018-07-25 20:23
Hi!

Thanks for being part of the Font Awesome Community.

Could this be considered a duplicate of #3025?

**Comment by tagliala** [comment] 2018-10-26 11:16
No feedback, closing here

**Closed by tagliala** 2018-10-26 11:16 UTC
Labels: waiting for feedback
