### ISSUE TITLE
Icon request: iron

### ISSUE THREAD

**Issue by MarGraz** [FortAwesome/Font-Awesome#9143] opened 2016-05-07 17:09 UTC
I'm creating a website for a B&B, and I saw that in fontawesome there isn't an icon to indicate iron for host use.
It's possible to add this new icon to font awesome?

Thank you again

![iron-icon](https://cloud.githubusercontent.com/assets/19241483/15093412/2b7f5b08-1487-11e6-8a3e-42645d981f0b.png)

**Comment by tagliala** [comment] 2016-05-07 17:17
Duplicate of #1171, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-07 17:17 UTC
