### ISSUE TITLE
Icon Request: fa-operator

### ISSUE THREAD

**Issue by thehavknots** [FortAwesome/Font-Awesome#6036] opened 2015-03-22 04:38 UTC
for customer service bullet,

**Comment by tagliala** [comment] 2015-03-22 13:35
could you please post an example?

**Comment by thehavknots** [comment] 2015-03-22 19:34
![operator2](https://cloud.githubusercontent.com/assets/11593748/6771026/ebe26800-d0a8-11e4-826f-f837b0fc98a9.jpg)
![05_operator](https://cloud.githubusercontent.com/assets/11593748/6771027/ebe9767c-d0a8-11e4-908b-6046ca578623.png)

**Comment by kwendenarmo** [comment] 2015-03-23 22:42
+1

**Comment by seanfrasure** [comment] 2015-03-24 11:39
+1

**Comment by ericfmatos** [comment] 2016-04-27 17:21
+1

**Comment by tagliala** [comment] 2016-04-27 17:27
closing as a duplicate of #5586

**Closed by tagliala** 2016-04-27 17:27 UTC
Labels: waiting for feedback
