### ISSUE TITLE
Icon Request: fa-tsu

### ISSUE THREAD

**Issue by chrismartin308** [FortAwesome/Font-Awesome#7789] opened 2015-10-31 20:18 UTC
tsū is an invite-only platform that rewards social activity for all users.You can share photos, videos, and any type of content with your friends and followers.

We (They not me) believe in quality content, real ownership, and the value of one’s own network.
We recognize members for their likeness, image and content.
Our content creators earn fair value for all the social things they already do.

http://www.tsu.co/
http://tsumoney.org/wp-content/uploads/Tsu_logo_big_highquality_white_background.jpg
![image](http://tsumoney.org/wp-content/uploads/Tsu_logo_big_highquality_white_background.jpg)

**Comment by tagliala** [comment] 2015-10-31 20:22
Duplicate of #6676, please +1 that request

Closing here

**Closed by tagliala** 2015-10-31 20:22 UTC
