### ISSUE TITLE
Icon request: toolbox

### ISSUE THREAD

**Issue by Furburger** [FortAwesome/Font-Awesome#8421] opened 2016-01-27 05:43 UTC
Hi

I think a toolbox icon would be very useful.

![toolbox64](https://cloud.githubusercontent.com/assets/5500245/12605014/752ad6aa-c4c9-11e5-88b2-4d7da5302726.png)

**Comment by tab13tab13** [comment] 2016-01-27 16:45
Agreed. If not generic toolbox, then hammer or screwdriver, etc.

**Comment by tagliala** [comment] 2016-01-27 17:11
duplicate of #4407, please +1 that request

closing here

**Closed by tagliala** 2016-01-27 17:11 UTC

**Comment by tromney** [comment] 2016-02-06 15:27
+1
