### ISSUE TITLE
Icon Request: icon-medal

### ISSUE THREAD

**Issue by s1doryak** [FortAwesome/Font-Awesome#5386] opened 2015-01-14 07:04 UTC
Hi there. I am in need of a medal icon.
I think it useful for award lists etc.

Many thanks.

![medal-with-star-and-ribbon_318-9647](https://cloud.githubusercontent.com/assets/7103375/5735272/6d8e4464-9bd4-11e4-9c3e-43570a148ac8.jpg)

**Comment by tagliala** [comment] 2015-01-14 08:39
duplicate of #1898 , please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-01-14 08:39 UTC
