### ISSUE TITLE
Icon request: clock-rotate-right

### ISSUE THREAD

**Issue by bastowj** [FortAwesome/Font-Awesome#18870] opened 2022-03-30 09:21 UTC
Currently only clock-rotate-left exists - If possible pls make the mirrored version available as clock-rotate-right

**Comment by tagliala** [comment] 2022-05-02 11:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is legit, but it is possible to use the current `fa-flip-horizontal` helper in both CSS and SVG frameworks to get an icon for the same use case.

Of course the clock hangs will be flipped too

Demo: https://jsfiddle.net/tagliala/bfa6uhse/125/

Ref: https://fontawesome.com/v6/docs/web/style/rotate#contentHeader

**Comment by sensibleworld** [comment] 2024-07-11 15:14
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/19001)

**Closed as completed by sensibleworld** 2024-07-11 15:14 UTC
Labels: new icon, time (category), Duplicate
