### ISSUE TITLE
Icon Request: fa-uturn-left, fa-uturn-right

### ISSUE THREAD

**Issue by TheChen5** [FortAwesome/Font-Awesome#6961] opened 2015-07-16 02:26 UTC
It would be great for directions.
fa-uturn-left - http://cdn3.volusion.com/dxezs.rjeyq/v/vspfiles/photos/PR-TH-3869-2.jpg
fa-uturn-right - http://etc.usf.edu/clipart/68000/68005/68005_119_w1-11_s_md.gif
[Left for US, etc; Right for Britain, etc.]

**Comment by sensibleworld** [comment] 2024-07-10 21:43
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/10023)

**Closed by sensibleworld** 2024-07-10 21:43 UTC
Labels: new icon, arrows (category), Duplicate
