### ISSUE TITLE
Icon request: fa-clean

### ISSUE THREAD

**Issue by kwagdy** [FortAwesome/Font-Awesome#11632] opened 2017-10-16 14:30 UTC
Example usage: representing home/house cleaning
![image](https://user-images.githubusercontent.com/15840617/31617371-ae68471e-b297-11e7-9981-269c9bb17330.png)

**Comment by tagliala** [comment] 2017-10-16 15:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #239 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-16 15:22 UTC

**Comment by kwagdy** [comment] 2017-10-17 00:04
Thank you for the feedback, done.
