### ISSUE TITLE
Icon Request: fa-messenger

### ISSUE THREAD

**Issue by JauCarre** [FortAwesome/Font-Awesome#10649] opened 2017-02-11 07:46 UTC
For use Messenger App of Facebook.

**Comment by tagliala** [comment] 2017-02-11 10:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6912 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-11 10:07 UTC
