### ISSUE TITLE
Icon request: icon-trailer

### ISSUE THREAD

**Issue by aclyles91** [FortAwesome/Font-Awesome#9581] opened 2016-07-15 16:29 UTC
I'd like to see a trailer icon.

**Comment by tagliala** [comment] 2016-07-15 21:10
Duplicate of #7369, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-15 21:10 UTC
