### ISSUE TITLE
Icon Request: fa-php

### ISSUE THREAD

**Issue by ambar-septian** [FortAwesome/Font-Awesome#6754] opened 2015-06-14 18:38 UTC
Hi Font Awesome Team, I want request icon for php logo, i will use it for category tutorial such html, css and etc.

![image](https://cloud.githubusercontent.com/assets/12516002/8149886/196afd76-12ff-11e5-89fb-0a0d3bdbaf78.png)

Thank you very much :)

**Comment by FabianCernota** [comment] 2015-06-24 14:26
+1

**Comment by tagliala** [comment] 2015-06-24 21:39
duplicate of #1420 , please +1 that request

please also consider http://mfizz.com/oss/font-mfizz for technology icons

**Closed by tagliala** 2015-06-24 21:39 UTC
