### ISSUE TITLE
Icon Request: black sad or frowny face

### ISSUE THREAD

**Issue by mxims** [FortAwesome/Font-Awesome#9409] opened 2016-06-15 18:54 UTC
I would really appreciate if you can include these two icons, that I can include on status reports. With these icons I can fill them with RED or Green, instead of those existing face icons, which can only be outlined.

![noun_286016_cc](https://cloud.githubusercontent.com/assets/3341557/16093126/7f7c6332-32ef-11e6-8a27-5116efb417c3.png)
![noun_116456_cc](https://cloud.githubusercontent.com/assets/3341557/16093133/82cd77ec-32ef-11e6-90c2-7dae25d4b6da.png)

**Comment by tagliala** [comment] 2016-06-15 21:23
Duplicate of #1681, please add a :+1: reaction to that request

**Closed by tagliala** 2016-06-15 21:23 UTC
