### ISSUE TITLE
Icon Request: fa-palette

### ISSUE THREAD

**Issue by hollyfaber** [FortAwesome/Font-Awesome#5710] opened 2015-02-18 17:37 UTC
You could use a palette icon for anything art related.
![27557](https://cloud.githubusercontent.com/assets/11063465/6252802/7ad8002a-b762-11e4-84c1-bb154f68aa96.png)
![color_palette](https://cloud.githubusercontent.com/assets/11063465/6252804/7ce3ca84-b762-11e4-8170-85530a085d7e.png)

**Comment by tagliala** [comment] 2015-02-19 15:17
duplicate of #244, please +1 that request

closing here

**Closed by tagliala** 2015-02-19 15:17 UTC
