### ISSUE TITLE
Icon request: Inkscape Brand logo

### ISSUE THREAD

**Issue by emma-15** [FortAwesome/Font-Awesome#14810] opened 2019-03-25 04:10 UTC
![inkscape](https://user-images.githubusercontent.com/48891420/54894744-1073f900-4e8a-11e9-89ec-63dc1bc30a24.png)

**Comment by tagliala** [comment] 2019-03-25 09:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13770, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-03-25 09:53 UTC
