### ISSUE TITLE
Icon request: icon-first-prize

### ISSUE THREAD

**Issue by tizata** [FortAwesome/Font-Awesome#6322] opened 2015-04-25 19:12 UTC
![icon1_3](https://cloud.githubusercontent.com/assets/12114927/7334284/dccbcdf2-eb97-11e4-814b-40f2d6acdc7f.png)

That's my second issue if it possible!? Thanks a lot in advance :)

**Comment by tagliala** [comment] 2015-04-25 19:53
almost a duplicate of #1898 , if #1898 is ok for your needs then please close this request and +1 #1898, thanks!

**Comment by tagliala** [comment] 2022-03-13 14:01
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2022-03-13 14:01 UTC
Labels: waiting for feedback
