### ISSUE TITLE
Icon request: icon-troy

### ISSUE THREAD

**Issue by firatcanulukaya** [FortAwesome/Font-Awesome#14674] opened 2019-02-23 23:38 UTC
### What can it be used for?

Payment Icon. This is Turkish Payment System logo/icon.
(for Turkish: TROY - Türkiye Ödeme Yöntemi)
I love your system. but TROY has no logo. It may be nice to add.

### Example image (optional)

https://bkm.com.tr/wp-content/uploads/2015/10/Troy-Logo-01.jpg

### Icon request checklist

- [? ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [✔️ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✔️ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✔️ ] I have included at least one example image if it could be helpful (optional)
- [? ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-05-27 13:11
Duplicate of #10655

**Closed by tagliala** 2019-05-27 13:11 UTC
Labels: brand icon
