### ISSUE TITLE
Icon request: tailwind css

### ISSUE THREAD

**Issue by yeasinaman** [FortAwesome/Font-Awesome#18523] opened 2021-12-20 05:11 UTC
**What can it be used for?**
this could be used for commercial purposes

**Example image (optional)**
https://yt3.ggpht.com/ikv41jMTr1uHGdILrJhvbfVJcDt4oqhwApKX37TjAleF_cRPbF2W-waj7uMnS5JySvnlvAlTCg=s900-c-k-c0x00ffffff-no-rj

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [✓] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical unicorn)
- [✓] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✓] I have included at least one example image if it could be helpful (optional)
- [✓] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-12-20 08:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17012, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-12-20 08:54 UTC
