### ISSUE TITLE
Icon request: baby-changing

### ISSUE THREAD

**Issue by jacksonj04** [FortAwesome/Font-Awesome#13848] opened 2018-08-30 15:19 UTC
### What can it be used for?

An icon to represent baby changing facilities

### Example image

![car_servicess-19-512](https://user-images.githubusercontent.com/619082/44861458-78ee5500-ac70-11e8-8039-961df1bcc1c1.png)
(https://www.iconfinder.com/icons/1722421/bathroom_diaper_change_toilet_baby_icon)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-30 15:44
Hi!

Thanks for being part of the Font Awesome Community.

Since the example represents a baby with a diaper, I will consider this a duplicate of #691

**Closed by tagliala** 2018-08-30 15:44 UTC
