### ISSUE TITLE
Icon Request: fa-goodreads

### ISSUE THREAD

**Issue by SonadoraCompulsiva** [FortAwesome/Font-Awesome#8261] opened 2016-01-02 12:59 UTC
I want to use this new icon in my Blog, I need it because I am using the Twitter and Instagram icon and I wan to have something in that line. So I have that social network so I want to put it in the Blog.

Thanl you, you are amazing

**Comment by aethior** [comment] 2016-01-02 14:10
Hi @SonadoraCompulsiva,

This suggestion is duplicate of #1715. Please +1 that.

Regards.

**Closed** 2016-01-02 16:33 UTC
