### ISSUE TITLE
Icon request: airplane-seat

### ISSUE THREAD

**Issue by laurensnl** [FortAwesome/Font-Awesome#16087] opened 2020-01-19 10:07 UTC
**What can it be used for?**
- Travel apps
- Flight search apps

**Example image (optional)**
![icons8-flight-seat-80](https://user-images.githubusercontent.com/4354382/72679044-b9d84b00-3aab-11ea-83cd-80ea77452bd4.png)
![icons8-flight-seat-100](https://user-images.githubusercontent.com/4354382/72679045-bd6bd200-3aab-11ea-93e1-188b04167d0d.png)

**Icon request checklist**
- [x] This is a **single icon** or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-01-19 11:24
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5658, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-19 11:24 UTC

**Comment by laurensnl** [comment] 2020-01-19 12:11
The example icon on #5658 was different so I thought to add a new request with the icon as we would like to have it included in Font Awesome. My apologies if this is considered as a duplicate. I've given the 👍 on #5658.

**Comment by tagliala** [comment] 2020-01-19 12:59
@laurensnl don't worry, feel free to paste your example at #5658

Examples are important, but the decision on how implement the icon will be made by the team.

If the implemented icon has some issues, we can open a new request and ask for a redesign
