### ISSUE TITLE
Icon Request: fa-memory

### ISSUE THREAD

**Issue by ninwaya** [FortAwesome/Font-Awesome#7923] opened 2015-11-19 12:41 UTC
![memory2](https://cloud.githubusercontent.com/assets/15895566/11270909/fe8e7a88-8ec2-11e5-8f31-1df6350057c7.png)
![memory](https://cloud.githubusercontent.com/assets/15895566/11270911/03fdf84a-8ec3-11e5-838c-098e7a222b4d.png)

car was 128 pixel, therefore i sent you one 128 pixel and other 6 pixel

**Comment by MVcodeartbr** [comment] 2015-11-27 15:00
what is this? could you explain more?

**Comment by tagliala** [comment] 2015-11-27 15:34
It should be a table game, but I'm having difficulties to have a 14px, single color example of this icon

**Comment by tagliala** [comment] 2015-11-27 15:35
btw closing here as a duplicate of #7905, still waiting for proper feedback there

**Closed by tagliala** 2015-11-27 15:35 UTC
