### ISSUE TITLE
Icon Request: fa-support / fa-call-center

### ISSUE THREAD

**Issue by jjr2000** [FortAwesome/Font-Awesome#10992] opened 2017-04-25 13:53 UTC
It would be great to have an icon that can be used for a support page link, which may have multiple contacts, etc.

The icon would be a mix of fa-user and fa-headphones but with an added microphone so it looks a bit like this but without the green.
![image](https://cloud.githubusercontent.com/assets/14221773/25388860/e011bca0-29c6-11e7-938f-4cc4e1961527.png)

**Comment by tagliala** [comment] 2017-04-25 14:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5586 or #1146 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-25 14:54 UTC
