### ISSUE TITLE
Icon request : empty

### ISSUE THREAD

**Issue by imabot2** [FortAwesome/Font-Awesome#11818] opened 2017-11-30 10:52 UTC
Is it possible to get an empty icon. With nothing inside, no drawing, no border ... but with the same size as other icons. I know it can seems weird, I plan to use it for displaying hidden icons when mouse is hover. 

At least, it should not be too long to create !!!

**Comment by tagliala** [comment] 2017-11-30 11:52
Hi!

Thanks for being part of the Font Awesome Community.

The bad news is that since font awesome icons have different width by design, it makes no sense to have an empty icon of the same width of other icons.

The good news is that there is already an empty icon: `fa-fw` :)

Troubleshooting: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#need-a-blankempty-icon

Fiddle showing a proper use case: http://jsfiddle.net/tagliala/7z9b557v/

Hope it helps, closing here

Ref: #1606

**Closed by tagliala** 2017-11-30 11:52 UTC
