### ISSUE TITLE
Missing Blogger Icon

### ISSUE THREAD

**Issue by wayne54321** [FortAwesome/Font-Awesome#8922] opened 2016-04-08 09:20 UTC
Hi
You don't have Blogger icon from ages. I have been using FontAwesome for many of my projects but always gets struck whenever need to use Blogger icon. 

Are you adding it in near future?

**Comment by truls1502** [comment] 2016-04-08 09:41
Hi @wayne54321, are you thinking about this blogger-icon from www.blogger.com?

As a hint from me when you are requesting a icon when it is regarding issue's title, check the guidelines: http://fontawesome.io/community/#requesting-new-icons.

**Comment by tagliala** [comment] 2016-04-08 09:48
Duplicate of #1088 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-08 09:48 UTC
