### ISSUE TITLE
Icon request: arm (body part)

### ISSUE THREAD

**Issue by robkovacs** [FortAwesome/Font-Awesome#16789] opened 2020-06-12 15:20 UTC
**What can it be used for?**
There are other icons for basic body parts: head-side, ear, etc. Besides what I specifically need it for, I assume it would be good for any application where you need to reference arm issues (such as medical applications/products).

**Example image (optional)**
💪

**Icon request checklist**
- [X] This is a **single icon**
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-06-12 16:07
Hi!

Thanks for being part of the Font Awesome Community.

Byceps is a duplicate of #2076

Maybe this is a request for a different representation of an arm?

**Comment by robkovacs** [comment] 2020-06-12 17:09
Sorry, didn't think to look for biceps/muscles while searching for duplicates. Really for my use case, a less muscle-y, more generic, version would be preferred, something more like this:

![noun_arm_1100412](https://user-images.githubusercontent.com/2268116/84528565-ef294380-acad-11ea-8cf3-86aeff0d0804.png)

**Comment by aethior** [comment] 2022-05-21 00:54
@tagliala `medical-health (category)` label for this request?

**Comment by sensibleworld** [comment] 2024-07-11 16:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 16:37 UTC
Labels: new icon, medical / health (category), Declined
