### ISSUE TITLE
Icon request: cards

### ISSUE THREAD

**Issue by nahasco** [FortAwesome/Font-Awesome#14881] opened 2019-04-11 17:57 UTC
### What can it be used for?

It can be used at a gift card shop

### Example image (optional)

![image](https://user-images.githubusercontent.com/49368477/55980047-4263c880-5c9c-11e9-98e6-a9a00a94fc31.png)
![image](https://user-images.githubusercontent.com/49368477/55980101-69ba9580-5c9c-11e9-8c83-b18b750099e1.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-04-16 15:48
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #2101, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-16 15:48 UTC

**Comment by tooomm** [comment] 2021-09-25 13:23
With the closing of https://github.com/FortAwesome/Font-Awesome/issues/2101, which did not address this, i would like to see this reopened for generic card icons (single, hand, stack/deck) to represent any card game or the here mentioned gift cards for example.
