### ISSUE TITLE
JSONfeed.org icon

### ISSUE THREAD

**Issue by darkenedsky** [FortAwesome/Font-Awesome#11111] opened 2017-05-24 20:00 UTC
https://jsonfeed.org/graphics/icon.png

**Comment by tagliala** [comment] 2017-05-24 21:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11106, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-24 21:51 UTC
