### ISSUE TITLE
Icon Request: fa-hexagon, fa-hexagon-o

### ISSUE THREAD

**Issue by lidiexy** [FortAwesome/Font-Awesome#7093] opened 2015-07-30 16:19 UTC
Good Morning Font-Awesome Team
Thanks for your amazing work, maybe you can add a series of icons related with geometry. I know you have squares and circles, but what about triangles  filled and bordered (not caret or arrows), pentagon, hexagon and some others. I can help you sending to you the SVG or other Vector File (Adobe Illustrator perhaps).
![request-shapes](https://cloud.githubusercontent.com/assets/851009/8988598/c66a18f6-36ac-11e5-8eb5-87a8bc5ffc37.png)

Thank you again,
Lidiexy Alonso

**Comment by TheChen5** [comment] 2015-07-30 16:54
Must be a dupe of #1302 and other shape requests.
+1 those.
:mag:before:heavy_plus_sign:

**Comment by lidiexy** [comment] 2015-07-30 17:06
Thanks TheChen5 I put my +1 in those, but they request a variant of mine.

**Comment by lidiexy** [comment] 2015-07-30 17:12
Sorry I vote +1, but I'm seen that is requested since Jun 14, 2013...

**Comment by tagliala** [comment] 2015-08-03 08:13
@TheChen5 thanks

@lidiexy that request is scheduled for 5.0.0 but if you need those icons before, please consider a custom build https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2015-08-03 08:13 UTC
