### ISSUE TITLE
Icon request: icon-mower

### ISSUE THREAD

**Issue by RushtonPippin** [FortAwesome/Font-Awesome#18735] opened 2022-02-21 22:49 UTC
A group of icons for landscaping work.

**Comment by tagliala** [comment] 2022-02-22 10:05
Hi!

Thanks for being part of the Font Awesome Community.

Can this be considered a duplicate of #14925 ?

**Comment by aethior** [comment] 2022-03-20 19:06
> Can this be considered a duplicate of #14925 ?

I think you can close here. :)

**Closed as completed** 2022-03-20 19:35 UTC
Labels: waiting for feedback
