### ISSUE TITLE
Icon Request: fa-hackerrank

### ISSUE THREAD

**Issue by jstephens0** [FortAwesome/Font-Awesome#7809] opened 2015-11-03 15:21 UTC
Icon for https://www.hackerrank.com/

**Comment by caduvieira** [comment] 2015-11-03 17:00
Dupe of #5702
Please +1 that one

**Closed** 2015-11-14 11:11 UTC

**Comment by ayush29feb** [comment] 2015-11-14 18:26
PLus One for that

**Comment by sam95** [comment] 2016-11-29 12:03
Please +1 for that.

**Comment by saurabhg22** [comment] 2017-07-04 07:37
+1

**Comment by tagliala** [comment] 2017-07-04 07:39
Duplicate of #5702

🔒
