### ISSUE TITLE
Icon Request: customs officer

### ISSUE THREAD

**Issue by lroal** [FortAwesome/Font-Awesome#8784] opened 2016-03-18 12:59 UTC
For declaration.
https://commons.wikimedia.org/wiki/File:Aiga_customs.svg

**Comment by lroal** [comment] 2016-03-18 13:01
It seems like I am not the only one. #7929

**Comment by tagliala** [comment] 2016-03-18 15:05
Duplicate of #7929 , please +1 that request

closing here

**Closed by tagliala** 2016-03-18 15:05 UTC
