### ISSUE TITLE
Icon request: blender-logo

### ISSUE THREAD

**Issue by ghemouzg** [FortAwesome/Font-Awesome#16443] opened 2020-04-09 12:21 UTC
**What can it be used for?**
icon for brand blender.org a free open source 3D software.

**Example image (optional)**
<img src="https://cdn.worldvectorlogo.com/logos/blender-1.svg" width="32" height="32"/>

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate.(There is duplicated thread, but it was opened in 2016)
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-23 13:21
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8273, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-23 13:21 UTC
