### ISSUE TITLE
Icon Request: fa-feather

### ISSUE THREAD

**Issue by DragonhelmDL** [FortAwesome/Font-Awesome#10223] opened 2016-11-14 23:13 UTC
I would like to request a feather icon. It could be used to represent a quill, nature, birds, etc.

Here is an example:
https://www.iconfinder.com/icons/612390/art_bird_feather_nature_pen_icon

Thanks!

**Comment by aethior** [comment] 2016-11-15 00:13
Duplicate of #9082. Please 👍 that.

**Closed** 2016-11-15 15:58 UTC
