### ISSUE TITLE
Icon Request: fa-parking

### ISSUE THREAD

**Issue by DonaldTdz** [FortAwesome/Font-Awesome#9396] opened 2016-06-13 02:14 UTC
Can I request font awesome for parking?
![parking](https://cloud.githubusercontent.com/assets/19897418/15995542/83a5691e-314f-11e6-8c9d-c39f9722a37a.png)

**Comment by tagliala** [comment] 2016-06-13 12:54
Duplicate of #1559, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Please also keep consider using the standard unicode point

```css
.fa-uppercase-p::before {
  content: 'P';
}
```

Closing here

**Closed by tagliala** 2016-06-13 12:54 UTC
