### ISSUE TITLE
Icon request: feet (or barefoot)

### ISSUE THREAD

**Issue by Doronh75** [FortAwesome/Font-Awesome#15656] opened 2019-10-07 20:51 UTC
cosmetics products for foot/feet

**Comment by v-aryan** [comment] 2023-02-03 14:16
Hey I am interested to work on this issue , can you describe it in brief ?

**Comment by sensibleworld** [comment] 2024-07-11 18:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/19522)

**Closed by sensibleworld** 2024-07-11 18:23 UTC
Labels: new icon, web application icons (legacy category), Duplicate
