### ISSUE TITLE
Icon Request: fa-ruler

### ISSUE THREAD

**Issue by wayofthefuture** [FortAwesome/Font-Awesome#10734] opened 2017-03-02 23:01 UTC
ruler :)

**Comment by tagliala** [comment] 2017-03-02 23:21
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1096 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-02 23:21 UTC
