### ISSUE TITLE
Icon request: racecar

### ISSUE THREAD

**Issue by evamvid** [FortAwesome/Font-Awesome#13954] opened 2018-09-16 02:45 UTC
### What can it be used for?

Similar applications for the normal car icons, or as symbol for speed or performance.

### Example image (optional)

![racecar-image](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.silhouette-illust.com%2Fwp-content%2Fuploads%2F2017%2F06%2Fnorimono_formula-car_32544-300x300.jpg&f=1)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-03-11 22:03
Duplicate of #12846.

cc/ @tagliala

**Closed** 2022-03-11 22:20 UTC
Labels: new icon, transportation (category)
