### ISSUE TITLE
Icon request: icon-siren

### ISSUE THREAD

**Issue by Sylpalmai** [FortAwesome/Font-Awesome#15839] opened 2019-11-22 09:20 UTC
Used in emergency related apps indicating that the ambulance-firefighter needs to use the siren.

Could have a matched pair of turned off siren.

![siren](https://user-images.githubusercontent.com/58068144/69413667-8f6b4b00-0d11-11ea-8f8d-2a8c5b9543e6.png)

**Comment by tagliala** [comment] 2019-11-22 13:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12879, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-11-22 13:11 UTC
