### ISSUE TITLE
Icon Request: fa-issuu

### ISSUE THREAD

**Issue by jesuslopezmorales** [FortAwesome/Font-Awesome#8461] opened 2016-01-30 17:06 UTC
I'm sorry for my english in advance.
I take care of a website for a friend and I would be interested issuu icon, the website related magazines. I attached the original logo issuu to see if you can add please.
Thank you very much for your excellent work.
Best regards
https://www.google.es/imgres?imgurl=http://www.brandsoftheworld.com/sites/default/files/styles/logo-thumbnail/public/102010/issuu_logo_vertical.jpg%253Fitok%253DMQmQs4nX&imgrefurl=http://www.brandsoftheworld.com/logo/issuu&h=200&w=200&tbnid=uYjSaT2on5vI0M:&docid=s8v2NxDT4u-2wM&ei=fO2sVqmTK4GRUeX0v5AI&tbm=isch&ved=0ahUKEwipwZDWgtLKAhWBSBQKHWX6D4IQMwggKAAwA
![descarga](https://cloud.githubusercontent.com/assets/2565725/12697147/2d5b7d42-c77c-11e5-8228-46119fdd315e.jpg)
A

**Comment by tagliala** [comment] 2016-01-30 20:16
duplicate of #6220 , please +1 that request

closing here

**Closed by tagliala** 2016-01-30 20:16 UTC
