### ISSUE TITLE
Icon request: Blogspot

### ISSUE THREAD

**Issue by Mouro001** [FortAwesome/Font-Awesome#8700] opened 2016-03-04 14:27 UTC
Can you have please the blogspot icon?
![image](https://cloud.githubusercontent.com/assets/8522686/13529665/3f49e9cc-e215-11e5-9736-31dc4abdf388.png)

**Comment by tagliala** [comment] 2016-03-04 15:18
duplicate of #1088 , please +1 that request

closing here

**Closed by tagliala** 2016-03-04 15:18 UTC
