### ISSUE TITLE
Update Request: fa-instagram

### ISSUE THREAD

**Issue by jakuuub** [FortAwesome/Font-Awesome#9175] opened 2016-05-11 14:55 UTC
Instagram just updated their app and all app icons:

http://blog.instagram.com/post/144198429587/160511-a-new-look

It would be great if you could update this really soon

**Comment by tagliala** [comment] 2016-05-11 15:08
No need to +1, this will be done in the next release

**Comment by NoelBroda** [comment] 2016-05-11 21:18
Not a bug

**Comment by davegandy** [comment] 2016-05-12 13:56
Added to milestone wip branch. Closing.

**Closed by davegandy** 2016-05-12 13:56 UTC
Labels: brand icons, bug
