### ISSUE TITLE
Add duck to font's

### ISSUE THREAD

**Issue by HoffmannP** [FortAwesome/Font-Awesome#8512] opened 2016-02-09 11:06 UTC
We had to use the real image of a duck as button icon in our presentation for the management, I'd prefer a symbol in font-awesome.
See _Duck (Feature)_ in http://blog.pixelastic.com/2015/01/24/duck-in-computer-jargon/, http://blog.codinghorror.com/new-programming-jargon/, http://www.businessinsider.com/20-hilarious-programming-jargon-phrases-you-should-know-when-talking-to-engineers-2012-7?IR=T for context.

Example image (invisible due to white on transparent):
![duck](https://cloud.githubusercontent.com/assets/432592/12914607/8697c2b6-cf25-11e5-8feb-5832e5490f0c.png)
/Example

**Comment by tagliala** [comment] 2016-02-09 11:13
duplicate of #4721, please +1 that request

closing here

**Closed by tagliala** 2016-02-09 11:13 UTC
