### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by gabegodin** [FortAwesome/Font-Awesome#14871] opened 2019-04-10 12:31 UTC
### What can it be used for?

I am hoping to create a widget for all digital music service providers and would like options to add other logos, for example Pandora, Deezer, and more.

### Example image (optional)
![image](https://user-images.githubusercontent.com/13857367/55878733-fc5b1780-5b6a-11e9-9aef-e8cd32e027fd.png)
![image](https://user-images.githubusercontent.com/13857367/55878750-08df7000-5b6b-11e9-8a57-bfd903ffcd84.png)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-04-10 13:12
Hi!

Thanks for being part of the Font Awesome Community.

Deezer is a duplicate of #2802 , please 👍 that request
Pandora is a duplicate of #5676 , please 👍 that request

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Also, please open individual requests

All duplicates, closing here

**Closed by tagliala** 2019-04-10 13:12 UTC
