### ISSUE TITLE
Icon Request: fa-openhub

### ISSUE THREAD

**Issue by bochecha** [FortAwesome/Font-Awesome#10979] opened 2017-04-23 12:06 UTC
Font Awesome already provides glyphs of logos for services like Github or Linkedin. This is super useful for links to user profiles on those services.

In the same vein, it would be great to have a glyph for the Open Hub logo.

Maybe based on their favicon: https://www.openhub.net/favicon.ico

Especially if the glyph is the background of their logo, that is the "OH" is transparent and the background is colored with the font `color` property.

**Comment by tagliala** [comment] 2017-04-23 12:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8347, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-23 12:43 UTC

**Comment by bochecha** [comment] 2017-04-23 12:44
Wow, and I had even already commented there. 😮 

My apologies for the duplicate.

**Comment by tagliala** [comment] 2017-04-23 13:37
don't worry no problem.

@bochecha I'm sorry that your request is not popular, please consider to [Customize Font Awesome](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome)
