### ISSUE TITLE
Icon Request: fa-trip advisor

### ISSUE THREAD

**Issue by jascott711** [FortAwesome/Font-Awesome#6826] opened 2015-06-25 17:49 UTC
Hello good people at Font-Awesome,

I love what you've done, allowing me to further customize websites with awesome icons!

I plan on using this icon to link to a restaurant's Trip Advisor page.

Please let me know if this is possible, if not, do not worry! I am crafty and I'll figure out a way :dancers: 

Thanks,
Jesse

![tripadvisor-black](https://cloud.githubusercontent.com/assets/5749951/8361275/28077320-1b40-11e5-89ae-3015d9f5b9ce.png)

**Comment by tagliala** [comment] 2015-06-25 18:42
this is a duplicate of #412 , which is scheduled for 5.0.0 release

please +1 that request

closing here

**Closed by tagliala** 2015-06-25 18:42 UTC
