### ISSUE TITLE
Icon request: tiktok

### ISSUE THREAD

**Issue by maddisondesigns** [FortAwesome/Font-Awesome#15148] opened 2019-06-13 04:42 UTC
**What can it be used for?**
Brand icon for social media platform, TikTok (https://www.tiktok.com)

**Example image (optional)**
![TikTok](https://user-images.githubusercontent.com/2078245/59404079-8f713180-8de8-11e9-9d78-cd90b0d92d91.png)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-06-13 10:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14340 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-06-13 10:35 UTC

**Comment by maddisondesigns** [comment] 2019-06-13 10:42
@tagliala Apologies for that. I did make sure to perform a search but that issue didn't show in the results. Thanks for the link.

**Comment by tagliala** [comment] 2019-06-13 13:36
@maddisondesigns don't worry 👍
