### ISSUE TITLE
Icon Request: cents

### ISSUE THREAD

**Issue by jjannetty** [FortAwesome/Font-Awesome#3904] opened 2014-07-14 19:10 UTC
Hey, I recently was/am in need of a ¢ icon and I love using font-awesome, so I thought I would make a request to see if y'all would be down to add one to the currency section.

**Comment by karthik-rp** [comment] 2016-10-05 06:02
+1

**Comment by vhenri** [comment] 2017-10-24 20:03
+ 1

**Comment by tagliala** [comment] 2018-03-07 18:05
fff

This is a duplicate of #1602, let's use that one

**Closed by tagliala** 2018-03-07 18:05 UTC
Labels: currency icons, new icon

**Comment by harshvardhan-shah** [comment] 2020-07-12 13:21
can you make "C" look more like  ₿  ?
