### ISSUE TITLE
Icon request: icon-fuel

### ISSUE THREAD

**Issue by erikaursi** [FortAwesome/Font-Awesome#10128] opened 2016-10-27 11:43 UTC
Hi!
I'm a designer who creates layouts for websites. I currently work for a website that sells real estate and vehicles that uses FontAwesome icons by default.
I'd like an icon for “fuel”. It'd be a gas pump drawing. It can be used to identify both the kind of fuel (gas, diesel, etc.) and gas stations.
Here are some images for reference:
![icons_fuel](https://cloud.githubusercontent.com/assets/23098388/19765927/d766c4d6-9c29-11e6-9103-69f2b6eedfd3.jpg)

**Comment by tagliala** [comment] 2016-10-27 12:00
Duplicate of #1676 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-27 12:00 UTC
