### ISSUE TITLE
Icon request: sea-wave

### ISSUE THREAD

**Issue by lainwir3d** [FortAwesome/Font-Awesome#17709] opened 2021-03-09 09:11 UTC
**What can it be used for?**
For surfing people, for seafarers, when you go on holidays at the sea. The current results for "wave" are kind of "generic".

**Example image (optional)**
![image](https://user-images.githubusercontent.com/6573376/110446236-40405980-80bf-11eb-8196-3c477730897c.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-03-09 09:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2266, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-09 09:37 UTC

**Comment by lainwir3d** [comment] 2021-03-09 09:59
Alright, sorry I indeed searched but found nothing. I guess I'm still a bit sleepy. Cheers
