### ISSUE TITLE
Icon Request: credit card terminal

### ISSUE THREAD

**Issue by nabsource** [FortAwesome/Font-Awesome#13737] opened 2018-08-09 02:46 UTC
What can it be used for?
credit card equipment

Example image (optional)
https://cdn2.iconfinder.com/data/icons/online-shopping-11/100/23-512.png link to example

Icon request checklist
[single ] This is a single icon or matched pair (Ex: lock / unlock)
[x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
[ x] I have searched for existing issues and to the best of my knowledge this is not a duplicate
[x ] I have included at least one example image if it could be helpful (optional)
[x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-09 07:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7326, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-09 07:28 UTC
