### ISSUE TITLE
Icon Request: fa-globe-europe

### ISSUE THREAD

**Issue by bruc13** [FortAwesome/Font-Awesome#5435] opened 2015-01-21 09:41 UTC
Hi, 
It would be usefull to have a different Continets Icons, not just USA.
If i make the Icon bigger, and will use it for example as Service in Europa. - nout usable for this.
http://fortawesome.github.io/Font-Awesome/icon/globe/

Thanks

**Comment by tagliala** [comment] 2015-01-21 09:59
duplicate of #281 , please read comments there

closing here

**Closed by tagliala** 2015-01-21 09:59 UTC
