### ISSUE TITLE
Icon request: fa-backspace

### ISSUE THREAD

**Issue by dvolvenl** [FortAwesome/Font-Awesome#8581] opened 2016-02-15 15:54 UTC
A backspace icon, quite handy to put on buttons in applications. Something like:

http://cdn.flaticon.com/svg/61/61167.svg

Or an open version:

https://cdn3.iconfinder.com/data/icons/social-productivity-line-art-3/128/delete-512.png

**Comment by tagliala** [comment] 2016-02-15 20:18
duplicate of #1980, please +1 that request

closing here

**Closed by tagliala** 2016-02-15 20:18 UTC
