### ISSUE TITLE
Icon Request: fa-dentist or fa-dental

### ISSUE THREAD

**Issue by pplschmp** [FortAwesome/Font-Awesome#9087] opened 2016-04-29 19:26 UTC
An icon for a dentist or a tooth, would be great!

**Comment by tagliala** [comment] 2016-04-29 21:50
duplicate of #1289 , please +1 that request

closing here

**Closed by tagliala** 2016-04-29 21:50 UTC

**Comment by Kushal-Pandya** [comment] 2017-06-27 14:36
+1
