### ISSUE TITLE
Icon Request: fa-leave-call

### ISSUE THREAD

**Issue by arjunbhandari3** [FortAwesome/Font-Awesome#17136] opened 2020-09-11 02:44 UTC
**What can it be used for?**
To leave a call 

**Example image (optional)**
![IMG_20200911_083037.jpg](https://user-images.githubusercontent.com/33949575/92847650-1d333680-f409-11ea-83ab-f2cf6b9ddb78.jpg)

**Icon request checklist**
- [✓ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ✓] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ✓] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ✓] I have included at least one example image if it could be helpful (optional)
- [✓ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-09-11 12:47
Hi!

Thanks for being part of the Font Awesome Community.

I think this could be a duplicate of #4405

**Comment by aethior** [comment] 2022-04-15 03:18
> I think this could be a duplicate of #4405

You're right. There is also a rounded icon.
Check https://fontawesome.com/icons/circle-phone-hangup

Regards.

cc/ @tagliala

**Closed** 2022-04-15 07:29 UTC
