### ISSUE TITLE
Icon request: Cardano

### ISSUE THREAD

**Issue by lepidotteri** [FortAwesome/Font-Awesome#14918] opened 2019-04-17 18:39 UTC
### What can it be used for?

Blockchain developers or web developers will need it

### Example image (optional)

[cardano-logo.png (all-white image)](https://www.cardano.org/wp-content/uploads/2017/07/cardano-logo.png)
[Cardano project website](https://www.cardano.org/)

### Icon request checklist

- [✓] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [✓] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✓] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✓] I have included at least one example image if it could be helpful (optional)
- [✓] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-04-17 21:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12020, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-17 21:07 UTC
