### ISSUE TITLE
Icon request: icon-tools

### ISSUE THREAD

**Issue by naluoli** [FortAwesome/Font-Awesome#12467] opened 2018-02-27 00:03 UTC
### What can it be used for?

Show tools, work, work box, under construction.

### Example image (optional)

![image](https://user-images.githubusercontent.com/36716550/36703005-7c3a1e86-1b0e-11e8-8a31-062b4c45cbcf.png)

### Icon request checklist

- [single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ yes] I have included at least one example image if it could be helpful (optional)
- [yes ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-02-27 11:52
Hi @naluoli, 

Thanks for being part of the Font Awesome Community.

> I have searched for existing issues and to the best of my knowledge this is not a duplicate

Please double check that you have searched on every request you made: https://github.com/FortAwesome/Font-Awesome/issues/created_by/naluoli, becase there are other duplicates

This request is a duplicate of #736 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-27 11:52 UTC
