### ISSUE TITLE
Icon Request: fa-package

### ISSUE THREAD

**Issue by rickdepeer** [FortAwesome/Font-Awesome#10754] opened 2017-03-07 09:47 UTC
An icon that represents mail delivery for packages
![shipping-box](https://cloud.githubusercontent.com/assets/12747977/23650674/37f58b9c-0323-11e7-8004-08793a42709b.png)

**Comment by allor** [comment] 2017-03-10 03:58
+1

**Comment by tagliala** [comment] 2017-03-10 09:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #908, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-10 09:33 UTC
