### ISSUE TITLE
Icon Request: fa-layer-send-front, fa-layer-send-back, fa-layer-move-back, fa-layer-move-forward

### ISSUE THREAD

**Issue by charlesmudy** [FortAwesome/Font-Awesome#10100] opened 2016-10-21 10:38 UTC
Hi,

I'm working on a project that needed a custom font, I found a similar concept from this https://www.wix.com/support/html5/article/arranging-elements-using-the-editor-toolbar. I came up with this:

![fa-layers](https://cloud.githubusercontent.com/assets/1445007/19595678/4d0cfc30-978b-11e6-9e6c-147f79665693.jpg)

**Comment by tagliala** [comment] 2016-10-21 11:24
Duplicate of #1445, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-21 11:24 UTC
