### ISSUE TITLE
Icon Request: icon-industrial-helmet

### ISSUE THREAD

**Issue by TERACOM** [FortAwesome/Font-Awesome#12003] opened 2017-12-28 01:29 UTC
Thanks for considering it.

**Comment by tagliala** [comment] 2017-12-28 09:46
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #5790?

**Comment by tagliala** [comment] 2018-03-14 10:47
No feedback.

Considering this a duplicate of #5790

**Closed by tagliala** 2018-03-14 10:47 UTC
Labels: waiting for feedback
