### ISSUE TITLE
Icon request: fa-category

### ISSUE THREAD

**Issue by anonymous675** [FortAwesome/Font-Awesome#16424] opened 2020-04-05 11:44 UTC
**What can it be used for?**
It can be used for display on an article his category

**Example image (optional)**
![](https://image.freepik.com/free-icon/category_318-30744.jpg)

**Icon request checklist**
- [ ] This is a single icon
- [ ] The title starts with "Icon request: " and is followed by the requested icon name
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful
- [ ] The request is for a concrete object

**Comment by tagliala** [comment] 2020-04-05 12:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1343, please add a 👍 reaction to that request.

You can also consider:
- https://fontawesome.com/icons/sitemap?style=solid
- https://fontawesome.com/icons/folder-tree?style=solid (FA Pro)
- https://fontawesome.com/icons/folders?style=solid (FA Pro) ([Fa Free SVG implementation](https://jsfiddle.net/tagliala/L17f528g/364/))

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-04-05 12:54 UTC
