### ISSUE TITLE
Icon request: vsco

### ISSUE THREAD

**Issue by R-Taneja** [FortAwesome/Font-Awesome#15300] opened 2019-07-29 00:17 UTC
**What can it be used for?**
It can be used as a link to someone's VSCO profile.

**Example image (optional)**
Image hosted here: https://ibb.co/jGjS0bp

**Icon request checklist**
- [Y] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [Y] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [Y] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Y] I have included at least one example image if it could be helpful (optional)
- [Y] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-07-29 12:56
Hi!

Thanks for being part of the Font Awesome Community.

I need to know if this is a duplicate of #2280. If it is not a duplicate, could you please elaborate why and provide differences between VSCO Grid and VSCO?

I can see the logo you have posted here: https://github.com/FortAwesome/Font-Awesome/issues/2280#issuecomment-170396145

**Comment by R-Taneja** [comment] 2019-07-29 13:01
Hello,

The request that you have linked is requesting for VSCO's old logo to be
added as an icon. They have since updated their logo and brand, so I
believe it would be better to include the updated icon in Font Awesome.

For reference:
https://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_vsco_done_in_house.php

Thank you,
Rohan

**Comment by tagliala** [comment] 2019-07-29 13:05
@R-Taneja ok, that's fine to use the old request. It is not a problem if the logo has been changed in the years, we will use the official latest available version of the logo

It would also benefit of old 👍s

Closing here as a duplicate of #2280

**Closed by tagliala** 2019-07-29 13:05 UTC
Labels: waiting for feedback
