### ISSUE TITLE
Icon Request: fa-wine-glass

### ISSUE THREAD

**Issue by carterdesign** [FortAwesome/Font-Awesome#11758] opened 2017-11-14 18:27 UTC
Was hoping a new icon could be created, a Wine Glass. This would be used on Winery, Restuarant, Cruise, Concert sites etc.

![images](https://user-images.githubusercontent.com/33667779/32797331-516c394e-c926-11e7-8858-89eec48f7861.png)
![wine-glasses-silhouette-hi](https://user-images.githubusercontent.com/33667779/32797351-59732e7c-c926-11e7-930d-a189715f9bb3.png)

**Comment by tagliala** [comment] 2017-11-14 19:21
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3614, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-14 19:21 UTC
