### ISSUE TITLE
Icon Request: icon-radiation

### ISSUE THREAD

**Issue by webscot** [FortAwesome/Font-Awesome#8299] opened 2016-01-08 19:24 UTC
Icon Request: icon-radiation

Many uses including labeling non-irradiated food.

![radiation](https://cloud.githubusercontent.com/assets/16613531/12207257/caaca926-b602-11e5-8817-124ba8670d66.jpg)

**Comment by caduvieira** [comment] 2016-01-08 20:55
Dupe of #4470
please +1 that one

**Closed** 2016-01-08 23:55 UTC
