### ISSUE TITLE
fa-receipt and fa-file-invoice icons are not getting displayed in browser chrome 70.x and Mozila

### ISSUE THREAD

**Issue by sujithkamath** [FortAwesome/Font-Awesome#14225] opened 2018-11-05 17:53 UTC
Can you please check this on priority??

**Comment by tagliala** [comment] 2018-11-05 22:07
Hi!

Thanks for being part of the Font Awesome Community.

[receipt](https://fontawesome.com/icons/receipt?style=solid) has been introduced in Font Awesome 5.0.13

[file-invoice](https://fontawesome.com/icons/file-invoice?style=solid) has been introduced in Font Awesome 5.1.0

Please double check that you are using at least Font Awsome >= 5.1, I'm pretty confident that this is your issue

You should also check for third party plugins loading outdated versions of Font Awesome that may interfer with your design

If you still think there is an issue with Font Awesome, please provide a reproducible test case and fill out [bug report template]((https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md))

Closing here

**Closed by tagliala** 2018-11-05 22:07 UTC

**Comment by sujithkamath** [comment] 2018-11-06 09:46
@tagliala Hi There! I'm using fontawesome v5.5.0 minified css.

**Comment by tagliala** [comment] 2018-11-06 12:31
@sujithkamath as I mentioned before, please check your third-party library and plugins, because they could load older versions of font awesome

If you still think there is an issue with font awesome, please provide a reproducible test case

Demo fiddle with working icons on FA 5.5.0 css: http://jsfiddle.net/tagliala/rodg718s/1/
