### ISSUE TITLE
Icon Request: file-corrupted

### ISSUE THREAD

**Issue by mateusleon** [FortAwesome/Font-Awesome#5449] opened 2015-01-22 20:08 UTC
I've noticed that the file icons doesn't have a version (or two, counting the filled and the non-filled versions) of one icon indicating files corrupted.

I'm pretty sure that the icon seems like one file with a rupture in the middle, like a paper torn, but I didn't found any example.

Please let me know if is acceptable and if it'll considered.

Thanks!

**Comment by Phasesaber** [comment] 2015-01-23 08:54
+1

**Comment by kwendenarmo** [comment] 2015-02-06 22:57
+1

**Comment by aethior** [comment] 2022-04-15 00:59
Duplicate of #12408. *(the other request has more upvotes)*

cc/ @tagliala

**Comment by mateusleon** [comment] 2022-04-15 01:32
@aethior how can one past issue be a duplicate of a future issue?

**Comment by aethior** [comment] 2022-04-15 01:49
> @aethior how can one past issue be a duplicate of a future issue?

Hi @mateusleon,

You're right, your request is older than the other, but I considered this issue duplicated of #12408 because that request has more upvotes. The intention is only to avoid duplicate requests.

In any case I am not a moderator, just an FA user trying to help.

**Comment by tagliala** [comment] 2022-04-15 07:43
Hi @mateusleon

Yes, sorry. Sometimes I can miss duplicates because of poor search or synonyms I do not think about (broken vs corrupted, in this case)

The newer request has more upvotes, so in these cases it is preferable to go for the request with more upvotes

**Closed by tagliala** 2022-04-15 07:43 UTC
