### ISSUE TITLE
Icon request: aparat icon

### ISSUE THREAD

**Issue by frost4mage** [FortAwesome/Font-Awesome#9811] opened 2016-08-25 09:33 UTC
[Aparat.com](http://www.aparat.com) is the most popular Iranian video hosting website. And it has a nice logo.
I want to ask you to add this logo to your awesome awesome font. thank you.

**Comment by tagliala** [comment] 2016-08-25 10:17
Duplicate of #5204, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-25 10:17 UTC
