### ISSUE TITLE
Icon Request: fa-dumbbell

### ISSUE THREAD

**Issue by sigmarc** [FortAwesome/Font-Awesome#9493] opened 2016-06-29 11:10 UTC
Hi!
Would it be possible to add an icon with the gym dumbbell?
I am using [leaflet.js](http://leafletjs.com/) as mapping library and the plugin [Leaflet.awesome.markers ](https://github.com/lvoogdt/Leaflet.awesome-markers). 
I am making a map with gyms around Madrid and I would like to use the marker with one of your icons. Unfortunately I couldn't find one that represented a gym. I think the dumbbell is quite the symbol for it :)

![dumbbelll](https://cloud.githubusercontent.com/assets/12531862/16450058/37bdae72-3dfb-11e6-82d9-0a7ae9d29cdd.png)

Thank you very much!!

**Comment by aethior** [comment] 2016-06-29 11:52
Duplicate of #1500. Please :+1: that.

**Closed** 2016-06-29 13:32 UTC

**Comment by harshvaghani** [comment] 2020-05-07 11:27
brother I would highly recommend that u should use map box API for your project in that project we have a dumbbell as an icon.
