### ISSUE TITLE
Icon Request: fa-flower

### ISSUE THREAD

**Issue by colinrcummings** [FortAwesome/Font-Awesome#10692] opened 2017-02-20 22:31 UTC

**Comment by tagliala** [comment] 2017-02-20 23:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2037 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-20 23:47 UTC
