### ISSUE TITLE
Icon request: icon-notion

### ISSUE THREAD

**Issue by rickbenetti** [FortAwesome/Font-Awesome#19965] opened 2023-10-22 03:00 UTC
It would be nice to have the notion icon.

![notion-logo](https://github.com/FortAwesome/Font-Awesome/assets/1049908/a0c9ba87-c0d2-41df-9670-c02bde096621)

**Comment by tagliala** [comment] 2023-10-22 07:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15830, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-10-22 07:49 UTC
