### ISSUE TITLE
Icon request: icon-pos (point of sale)

### ISSUE THREAD

**Issue by ibarquero** [FortAwesome/Font-Awesome#6792] opened 2015-06-19 20:28 UTC
Well, I'm requesting an icon for a POS (Point of Sale). I'm going to use in several things, apps, websites and presentations.

Thanks for all as always.
![icon-pos](https://cloud.githubusercontent.com/assets/7978975/8262397/58004aee-168f-11e5-8b29-5d6d7db95eca.jpg)

**Comment by tagliala** [comment] 2015-07-01 10:43
quite complex for 14px icon size

**Comment by aethior** [comment] 2022-05-07 14:21
`fa-cash-register` solves this request?
Check https://fontawesome.com/icons/cash-register

Regards.

**Comment by tagliala** [comment] 2022-05-07 14:35
I would say yes

Duplicate of #3467

For a POS terminal, please use #7326

**Closed by tagliala** 2022-05-07 14:35 UTC
Labels: new icon, web application icons (legacy category), payments & shopping (category)
