### ISSUE TITLE
Icon request: fa-shop

### ISSUE THREAD

**Issue by stijnvanbael** [FortAwesome/Font-Awesome#7034] opened 2015-07-24 12:18 UTC
For representing physical shop locations. Example: 

![](http://simpleicon.com/wp-content/uploads/shop-4.png)

**Comment by donjajo** [comment] 2015-07-24 23:15
Exactly looking for this too!

**Comment by TheChen5** [comment] 2015-07-26 00:17
Dupe of #1958 .
"+1" that one.
*Search before creating.*

**Comment by tagliala** [comment] 2015-07-26 13:10
@TheChen5 thanks

**Closed by tagliala** 2015-07-26 13:10 UTC

**Comment by pmarsilio** [comment] 2016-09-04 08:43
+1
