### ISSUE TITLE
Icons not showing when using Gem

### ISSUE THREAD

**Issue by rydigital** [FortAwesome/Font-Awesome#6773] opened 2015-06-17 10:23 UTC
Using Font-awesome using the ruby gem (ruby-2.2.2, font-awesome-sass-4.3.2). The font icons look fine locally, but are broken when viewed remotely or when deployed on a server.

I have followed the instructions [laid out here](https://github.com/FortAwesome/font-awesome-sass) but when I look at my compiled CSS the expected unicode numbers have been replaced by boxes:

```CSS
.fa-glass:before {
  content: "";
}
```

instead of

```CSS
.fa-glass:before {
  content: "\f000";
}
```

I have already tried including `@charset "UTF-8";` at the top of my SASS file which imports font-awesome.

**Comment by tagliala** [comment] 2015-06-17 13:26
duplicate of #6552 and refers to #6728

Do you have a public website showing the issue?

**Comment by rydigital** [comment] 2015-06-17 14:18
Not yet. I'll add one asap.

**Comment by rydigital** [comment] 2015-06-17 17:19
[I've a reduced case basic website](http://fa-test.rystage.com) which shows the problem.

What I see:
![screen shot 2015-06-17 at 18 13 13](https://cloud.githubusercontent.com/assets/12184917/8213889/4b4a3ada-151d-11e5-9daa-4261d9070545.png)

What others see:
![font-awesome-01](https://cloud.githubusercontent.com/assets/12184917/8213895/54d858f2-151d-11e5-8090-9df480619430.png)

**Comment by tagliala** [comment] 2015-06-17 18:20
This is not always an issue, eg: http://ruby2-rails4-bootstrap-heroku.herokuapp.com/

The [css file](http://ruby2-rails4-bootstrap-heroku.herokuapp.com/assets/application-4b4327813c67b4171a16a276ba8ebe42382f7ee69ba7f259d8ea714a82b85461.css) has the same problem `fa-fighter-jet:before{content:""}`. Maybe the content-type header set to gzip causes this issue?

BTW this needs to be fixed

Closing here, let's continue on  #6552

**Closed by tagliala** 2015-06-17 18:20 UTC
Labels: waiting for feedback
