### ISSUE TITLE
Icon Request: fa-weight

### ISSUE THREAD

**Issue by Scowen** [FortAwesome/Font-Awesome#11286] opened 2017-07-13 09:20 UTC
Use case: When trying to show the weight of an object using an icon instead of having to type "Weight: 55.4kg".

Icon representation: 
I've take these from Google Search so avoid copyrights!
https://d30y9cdsu7xlg0.cloudfront.net/png/9409-200.png 
https://image.freepik.com/free-icon/weight-tool_318-61825.jpg (minus the "kg" text)

**Comment by tagliala** [comment] 2017-07-13 09:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2735 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-13 09:57 UTC
