### ISSUE TITLE
Icon Request: icon-flipboard

### ISSUE THREAD

**Issue by ladykisok** [FortAwesome/Font-Awesome#8935] opened 2016-04-10 06:56 UTC
Hi,

Could you please make an icon for the social news sharing magazine site, "Flipboard". Attached is the logo. Thanks

![icon_flipboard](https://cloud.githubusercontent.com/assets/18375144/14408559/da4ef79c-ff38-11e5-864d-2808a9cabd3b.png)

**Comment by tagliala** [comment] 2016-04-10 08:38
Duplicate of #1382 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-10 08:38 UTC
