### ISSUE TITLE
Icon Request: fa-transparency

### ISSUE THREAD

**Issue by kabe243** [FortAwesome/Font-Awesome#8135] opened 2015-12-10 13:53 UTC
We are developing a mapping application with many different layers. We have a transparency slider for the layers. For that a transparency icon would be great.
![image](https://cloud.githubusercontent.com/assets/144657/11716989/562162dc-9f45-11e5-88de-2d211fc0ff5e.png)
![image](https://cloud.githubusercontent.com/assets/144657/11717000/6421b27e-9f45-11e5-8a8f-79493733b7be.png)

**Comment by MrZach** [comment] 2015-12-11 02:21
Duplicate of [#8082](https://github.com/FortAwesome/Font-Awesome/issues/8082).

Please :mag: before :heavy_plus_sign:.

**Closed** 2015-12-11 08:54 UTC
