### ISSUE TITLE
Icon request: icon-sailboat

### ISSUE THREAD

**Issue by pieterjandesmedt** [FortAwesome/Font-Awesome#9906] opened 2016-09-12 07:55 UTC
A sailboat would be a good addition to the transportation set. It's a very recognizable shape and a lot of sailing-related open source projects and websites would benefit from it. Thanks for considering!

![sailing-boat-black-shape_318-34193](https://cloud.githubusercontent.com/assets/9006284/18428590/184072be-78cf-11e6-873a-9b06150e7b35.png)

**Comment by tagliala** [comment] 2016-09-12 10:51
Duplicate of #5079, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-12 10:51 UTC

**Comment by pieterjandesmedt** [comment] 2016-09-13 08:30
Done. I was searching for 'sailboat' and couldn't find that. I saw you added it to the title of #5079. Thanks!
