### ISSUE TITLE
icon-request: fa-telegram

### ISSUE THREAD

**Issue by amirniknami** [FortAwesome/Font-Awesome#9386] opened 2016-06-10 18:59 UTC
telegram now is very popular messaging app . so it needed to add it

**Comment by aethior** [comment] 2016-06-10 19:20
Hi @amirniknami,

This request is duplicate of #3034. Please +1 that.

Regards.

**Comment by pablodgonzalez** [comment] 2016-06-10 22:50
+1

**Closed** 2016-06-11 09:21 UTC
