### ISSUE TITLE
Icon request: fa-check-slash

### ISSUE THREAD

**Issue by delijah** [FortAwesome/Font-Awesome#19646] opened 2023-04-03 14:44 UTC
### Use case

The "slash"-variant of the "check" icon.

Currently we are using the "check" icon to show that an article is published. If the article gets unpublished we need to show a meaningful icon as well.

### Example image

<img width="111" alt="Screenshot 2023-04-03 at 16 42 28" src="https://user-images.githubusercontent.com/237739/229544074-ab941074-a0d9-449f-800b-77c7dfd7cd1c.png">

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2023-04-03 19:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #18090, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-04-03 19:55 UTC
Labels: new icon
