### ISSUE TITLE
Icon Request: fa-icon-on-foot

### ISSUE THREAD

**Issue by Colinyell01** [FortAwesome/Font-Awesome#7427] opened 2015-09-09 14:16 UTC
Hi there,

Love the icon set - incredibly well designed and useful. I notice you welcome suggestions for new icons so thought I'd share my own suggestion as I found myself in need of a particular icon that I couldn't see in the current set. It's an icon for a person 'on foot' to compliment the existing transportation icon set. 

For example, if I was using the icons in the context of a travel experience I might wish to see options available to me by car, cycling, walking or public transport such as bus or trains. Most of these transport options are already covered but I wasn't able to find one to represent 'walking' - hence my suggestion. Another use case could be to denote 'nearby' in icon form. 

In terms of style, I'd propose a similarity to the current icon-set for transport, so the icon would sit alongside these in many contexts. There is a male/female icon which could be tweaked a little to represent movement (e.g. slightly bent leg to denote walking). Hope that's useful. Look forward to seeing further updates :-)

Existing transportation icon set:
![family](https://cloud.githubusercontent.com/assets/14200250/9764104/0bf13b0c-5705-11e5-9759-8335af48733e.png)

Proposed icon style for fa-icon-on-foot:
![icon-on-foot](https://cloud.githubusercontent.com/assets/14200250/9764346/7c607bf4-5706-11e5-83d1-3a81ba89cfe5.png)

**Comment by kjodle** [comment] 2015-09-09 16:33
+1

This would be useful in a number of contexts.

**Comment by fr0980y** [comment] 2015-09-09 21:02
+1

**Comment by caduvieira** [comment] 2015-09-10 16:05
Dupe of #844

**Comment by tagliala** [comment] 2015-09-11 11:15
@caduvieira thanks

closing here

**Closed by tagliala** 2015-09-11 11:15 UTC
