### ISSUE TITLE
Icon Request: icon-researchgate

### ISSUE THREAD

**Issue by katiek21532** [FortAwesome/Font-Awesome#10537] opened 2017-01-19 14:41 UTC
Scientists like to provide links on their laboratory/research pages to their profiles on Research Gate, which is kind of like a social media app for scientists:

![rg2](https://cloud.githubusercontent.com/assets/25103559/22110843/38e70ea8-de2b-11e6-8a5e-f14c00f580fa.png)
![rg](https://cloud.githubusercontent.com/assets/25103559/22110844/38e837c4-de2b-11e6-9998-1e179563971f.png)

**Comment by tagliala** [comment] 2017-01-19 14:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3634, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-19 14:55 UTC
