### ISSUE TITLE
Surf icon

### ISSUE THREAD

**Issue by SeanFmcdonnell** [FortAwesome/Font-Awesome#12853] opened 2018-04-13 17:20 UTC
something like this https://www.iconfinder.com/icons/508043/beach_carrying_man_person_surf_surf_board_surfer_icon#size=128

**Comment by tagliala** [comment] 2018-04-13 20:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1822 please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-13 20:04 UTC
