### ISSUE TITLE
Icon request: fiverr

### ISSUE THREAD

**Issue by Haseeb99** [FortAwesome/Font-Awesome#16364] opened 2020-03-25 07:17 UTC
**What can it be used for?**
This icon can be used with other brand icons like Facebook, LinkedIn for linking social and professional profiles. 

**Example image**

![fiverr](https://user-images.githubusercontent.com/45782139/77510964-c99c5300-6e91-11ea-9a6d-f1f33b56c846.png)

**Example image (alternate)**

![fiverr-alt](https://user-images.githubusercontent.com/45782139/77511236-7b3b8400-6e92-11ea-84d1-49c80c30cc95.png)

**Comment by tagliala** [comment] 2020-03-25 10:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5970, please slap like 👍on that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-25 10:17 UTC
