### ISSUE TITLE
Icon request: icon-ski

### ISSUE THREAD

**Issue by isifun** [FortAwesome/Font-Awesome#8335] opened 2016-01-13 14:58 UTC
Hi all, What do you think about this icon for for winter activities ? 
Thank you
![sport22](https://cloud.githubusercontent.com/assets/6671049/12297663/78681f64-ba0e-11e5-9c84-7afcf8ab397f.png)

**Comment by aethior** [comment] 2016-01-13 15:38
Duplicate of #6878. Please +1 that.

Regards.

**Closed** 2016-01-13 15:45 UTC

**Comment by andyanderso** [comment] 2016-06-24 16:44
+1

**Comment by futureweb** [comment] 2018-03-16 16:35
+1
