### ISSUE TITLE
Icon Request: MongoDB

### ISSUE THREAD

**Issue by Nojil** [FortAwesome/Font-Awesome#13197] opened 2018-05-23 14:29 UTC
Used when creating a personal profile page detailing your skills.

![mongodb1](https://user-images.githubusercontent.com/11978772/40430921-73d53922-5e63-11e8-8dcd-1662136c3212.png)
![mongodb2](https://user-images.githubusercontent.com/11978772/40430922-73e5c6f2-5e63-11e8-884e-8cbd32fa67f6.png)

**Comment by tagliala** [comment] 2018-05-23 21:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2725, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-23 21:15 UTC
