### ISSUE TITLE
font-awesome-logo-full breaks the fontawesome homepage

### ISSUE THREAD

**Issue by Killerbear** [FortAwesome/Font-Awesome#13395] opened 2018-06-22 18:35 UTC
### Describe the problem

In the icon search list the font-awesome-logo-full isnt showing up.
https://fontawesome.com/icons?d=gallery&q=font-awesome-logo

And the detail page of this icon breaks the fontawesome homepage a lot :)
https://fontawesome.com/icons/font-awesome-logo-full?style=solid

### What did you expect?

I expected to see the icon at all in the preview list.
And the detail list to handle large icons.

Maybe someone has to layout the detail page a little different for very long icons.

**Comment by tagliala** [comment] 2018-06-22 20:33
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

This request is a duplicate of #13160

Closing here

**Closed by tagliala** 2018-06-22 20:33 UTC
