### ISSUE TITLE
fa-premium icon request

### ISSUE THREAD

**Issue by smallersign** [FortAwesome/Font-Awesome#12384] opened 2018-02-18 13:30 UTC
Hi, need this icon.

[https://image.flaticon.com/icons/png/512/14/14165.png](url)

**Comment by tagliala** [comment] 2018-02-18 13:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #486 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-18 13:36 UTC
