### ISSUE TITLE
Icon Request: fa-restroom

### ISSUE THREAD

**Issue by cpc-web** [FortAwesome/Font-Awesome#10086] opened 2016-10-19 15:40 UTC

**Comment by tagliala** [comment] 2016-10-19 18:22
Duplicate of #2670 ?

Closing here, please follow our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Closed by tagliala** 2016-10-19 18:22 UTC
