### ISSUE TITLE
Icon Request: folder/file icons with plus/cross (add/delete)

### ISSUE THREAD

**Issue by LaurentFl** [FortAwesome/Font-Awesome#7155] opened 2015-08-06 10:34 UTC
Hi,

I'd like to add a add folder icon in my application, like user-plus.
Can you add it in Font Awesome?

Thank you!
Laurent.

**Comment by tagliala** [comment] 2015-08-06 11:15
duplicate of #1525 , please +1 that request

refers to #1181

**Closed by tagliala** 2015-08-06 11:15 UTC

**Comment by LaurentFl** [comment] 2015-08-06 11:50
Hi,

Thank you for your advise.
I use FontAwesone in a Java application so I cannot use css with overlay but I test it with a StackPane and it's working fine!

Thx.
