### ISSUE TITLE
NFC Icon

### ISSUE THREAD

**Issue by MGKVWeb** [FortAwesome/Font-Awesome#8785] opened 2016-03-18 13:07 UTC
I think Font-Awesome need also a NFC Icon

https://en.wikipedia.org/wiki/Near_field_communication

https://en.wikipedia.org/wiki/Near_field_communication#/media/File:NFC-N-Mark-Logo.png

**Comment by aethior** [comment] 2016-03-18 14:24
Hi @MGKVWeb,

This request is duplicate of #1695. Please +1 that.

Regards.

**Closed** 2016-03-18 14:57 UTC
