### ISSUE TITLE
Icon Request: fa-fa Mop

### ISSUE THREAD

**Issue by jes-sea** [FortAwesome/Font-Awesome#9862] opened 2016-09-06 00:37 UTC
depict cleaning

**Comment by tagliala** [comment] 2016-09-06 09:43
Duplicate of #239 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-06 09:43 UTC
