### ISSUE TITLE
Icon request: icon-dice

### ISSUE THREAD

**Issue by naluoli** [FortAwesome/Font-Awesome#12458] opened 2018-02-26 23:30 UTC
### What can it be used for?
Dice icon can be used for Chance, or gambling

### Example image (optional)

![image](https://user-images.githubusercontent.com/36716550/36701899-dae4b50e-1b09-11e8-9d00-edb7f4019fe5.png)

### Icon request checklist

- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [yes ] I have included at least one example image if it could be helpful (optional)
- [yes ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-02-28 13:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2622 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-28 13:34 UTC
