### ISSUE TITLE
Icon request: active-shooter

### ISSUE THREAD

**Issue by wmd-jrc** [FortAwesome/Font-Awesome#15543] opened 2019-09-16 19:48 UTC
A gun icon would be used for active shooter notification across campuses. 

Example Icons:
https://www.shutterstock.com/image-illustration/gun-icon-isolated-on-white-background-1459538387

https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/256x256/plain/gun.png

**Comment by tagliala** [comment] 2019-09-17 07:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3888, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-17 07:01 UTC

**Comment by JosephWeaver** [comment] 2019-09-30 00:58
Maybe if they addressed the other issue instead of ignoring it, people would stop creating this as a new issue. Just a thought...
