### ISSUE TITLE
Icon request: fa-cleaning or fa-clean

### ISSUE THREAD

**Issue by ChNitz** [FortAwesome/Font-Awesome#8822] opened 2016-03-24 11:18 UTC
Need a new icon for a cleaning service. Maybe something like this

![cleaning](https://cloud.githubusercontent.com/assets/18049407/14015551/28d5686a-f1ba-11e5-8866-9298917dd5b8.jpg)

or
![cleaning2](https://cloud.githubusercontent.com/assets/18049407/14015600/80b0d376-f1ba-11e5-8414-2d4abb80e4ad.jpg)

Best regards

Christian

**Comment by tagliala** [comment] 2016-03-24 11:52
related to #239 , duplicate of #8597.

I'm going to close this, if you want to request the second icon please provide a better titile and I will reopen

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Closing here

**Closed by tagliala** 2016-03-24 11:52 UTC
