### ISSUE TITLE
Icon request: laundry

### ISSUE THREAD

**Issue by MarGraz** [FortAwesome/Font-Awesome#9142] opened 2016-05-07 17:05 UTC
I'm creating a website for a B&B, and I saw that in fontawesome there isn't an icon to indicate laundry services.
It's possible to add this new icon to font awesome?

Thank you again

![laundry](https://cloud.githubusercontent.com/assets/19241483/15093392/b45d3180-1486-11e6-92e8-5e57da2fa7a8.png)

**Comment by tagliala** [comment] 2016-05-07 17:16
Duplicate of #5914, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-07 17:16 UTC

**Comment by MarGraz** [comment] 2016-05-07 17:26
Sorry :'(
