### ISSUE TITLE
Icon Request: icon-hexagon icon-square icon-hexagon-radius icon-square-radius

### ISSUE THREAD

**Issue by Uranbold** [FortAwesome/Font-Awesome#1302] opened 2013-06-14 12:14 UTC
Hello,

I need some geometrical fonts. Specially hexagon and hexagon + radius and also square, square + radius.

Image request link is here. 

https://www.dropbox.com/s/j8rpzrqblp8hges/fontawesome-add-requist.png

Thanks for awesome icons.

**Comment by vyskoczilova** [comment] 2015-01-13 23:57
+1

**Comment by tylerconover** [comment] 2015-01-24 18:29
+1

**Comment by JvanderHeide** [comment] 2015-01-31 20:40
:+1:

**Comment by ray10** [comment] 2015-02-03 23:13
+1

**Comment by SJCPROJECT** [comment] 2015-02-04 09:27
+1 needed asap please :)

**Comment by Braintelligence** [comment] 2015-03-03 00:21
:+1: +1

**Comment by Artistan** [comment] 2015-03-08 22:21
+1 
trying the unicode hex but it does not work on all browsers

**Comment by Haixing-Hu** [comment] 2015-03-15 10:11
+1
I also need a hexagon icon.

**Comment by pixelloop** [comment] 2015-03-18 04:40
I also need a hexagon icon too. Would be awesome to have 15 or so geometrical shapes in a font awesome category, as people are saying great for stacking and other purposes.

**Comment by giovdi** [comment] 2015-03-20 21:03
+1

**Comment by zeOrb** [comment] 2015-04-19 14:00
+1 for hexagon!

**Comment by monapasan** [comment] 2015-05-31 07:35
+1

**Comment by Alorse** [comment] 2015-06-03 13:01
+1

**Comment by c0r3yz** [comment] 2015-06-04 20:12
+1

**Comment by tomatau** [comment] 2015-07-20 09:07
Any progress with this? It was opened a long time ago with many :+1: and no feedback for over a month.

**Comment by J4G-** [comment] 2015-07-24 01:47
+1

**Comment by lidiexy** [comment] 2015-07-30 17:00
+1 :+1:

**Comment by nunomazer** [comment] 2015-07-31 11:25
+1

**Comment by tolean** [comment] 2015-08-03 13:57
+1

**Comment by jaspersorrio** [comment] 2015-08-12 07:10
+1

**Comment by tabame** [comment] 2015-09-05 19:36
+1

**Comment by kviktor** [comment] 2015-09-21 18:41
+1

**Comment by nakhbari** [comment] 2015-10-02 16:56
+1

**Comment by Casper-O** [comment] 2015-10-17 20:26
+1

**Comment by brianfryer** [comment] 2015-10-21 16:01
+1

**Comment by pjdicke** [comment] 2015-10-27 20:37
+1

**Comment by mlecke** [comment] 2015-10-31 00:15
+1

**Comment by brunoocasali** [comment] 2015-11-05 03:17
:+1:

**Comment by SamBrishes** [comment] 2015-11-14 13:46
+1

**Comment by codyn329** [comment] 2015-11-30 21:58
+1

**Comment by ryankane** [comment] 2015-12-04 06:20
:+1: Why is this not already a thing?

Three potential class names...

* fa-hex-o (outline)
* fa-hex-thin (thin outline)
* fa-hex (solid)

**Comment by lwa** [comment] 2015-12-13 00:08
+1

**Comment by codynguyen1116** [comment] 2016-01-06 22:20
+1

**Comment by ekote** [comment] 2016-01-23 16:06
+1

**Comment by saruulmn** [comment] 2016-01-24 06:03
+1

**Comment by ArthurianX** [comment] 2016-01-24 18:34
+1

**Comment by jsturgisRN** [comment] 2016-02-02 23:42
+1

**Comment by redayoub** [comment] 2016-02-08 19:11
+1

**Comment by javvarcar** [comment] 2016-02-27 23:59
+1

**Comment by cherrador** [comment] 2016-02-29 03:50
+1 This are could be extremely useful for stacks, we need also a rectangle.

**Comment by cmorgannorris** [comment] 2016-03-08 23:02
+1

**Comment by Oregand** [comment] 2016-03-25 11:46
+1

**Comment by danielrvt** [comment] 2016-04-10 01:31
+1

**Comment by AndreLGava** [comment] 2016-04-16 13:33
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-hexagon was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by AAudusseau** [comment] 2016-04-21 16:57
+1

**Comment by rajdeep225** [comment] 2016-04-28 13:04
+1

**Comment by jimtrue** [comment] 2016-04-30 19:37
+1

**Comment by scarbies** [comment] 2016-05-12 15:02
+1

**Comment by umairrazzaq** [comment] 2016-05-26 22:53
+1

**Comment by jschouwstra** [comment] 2016-07-17 15:22
+1

**Comment by acjohnson** [comment] 2016-08-10 03:04
+1

**Comment by xerenade** [comment] 2016-08-25 21:43
+1

**Comment by arnaudriegert** [comment] 2016-09-08 13:31
+1

**Comment by cherrador** [comment] 2016-10-05 01:02
For those waiting for hexagons. I needed them badly, so I did some research and found this awesome site to build hexagons with CSS http://csshexagon.com/

However, there you design one, then you copy and paste the code. The problem is that is one shot and not dynamically flexible because all the units are pixels. So I break down the geometry and math required and converted to em units. Then I added a couple of tricks to add icons inside, variables to change the color and width only on one place and using filters to add drop shadow. 

![sample-1](https://cloud.githubusercontent.com/assets/12229855/19097505/878a5e24-8a62-11e6-8153-b4a0194f3f67.png)

This will only only Firefox and Chrome as it, because Edge still do not support CSS variables, forget about Internet "Exploder".  At least, if you need support for Edge then you will need to replace the variables on all the locations where the variables are used, but it will make the hexagon color and width static and cannot be changed on the fly.

Based on this research other shapes could be possible, but I do not have them time and I do not have need for them at the moment. 

Here is a jsfiddle with the FA stack extensions that I have been working with some samples.

https://jsfiddle.net/cherrador/jomgLb2h/

Let me know if you find this useful or if you have some suggestions.

**Comment by atilkan** [comment] 2016-10-19 00:34
+1

**Comment by justi** [comment] 2016-11-12 13:15
👍

**Comment by cjindustries** [comment] 2016-12-20 09:11
+1

**Comment by jacobnbrum** [comment] 2017-03-06 22:02
+1

**Comment by fgroch** [comment] 2017-03-13 08:41
+1

**Comment by lffg** [comment] 2017-03-14 17:42
+1 
Bump.

**Comment by lacivert** [comment] 2017-03-16 18:18
:+1

**Comment by matedon** [comment] 2017-05-18 16:04
+1

**Comment by rcarrico** [comment] 2017-06-06 21:55
+100

**Comment by bobzhen** [comment] 2017-07-10 12:39
+1

**Comment by lffg** [comment] 2017-07-10 19:43
+ 1

**Comment by LuqiYan** [comment] 2017-08-23 16:12
+1

**Comment by pkostadinov-2create** [comment] 2017-10-18 14:48
+1

**Comment by lotter1001** [comment] 2017-11-24 12:43
+1

**Comment by katie1348** [comment] 2017-12-14 15:45
A hexagon to use as a container would be nice. 

It would give something nice to place the icons within.

Other geometric shapes would also be excellent.

**Comment by sensibleworld** [comment] 2018-03-30 00:57
These were released as part of Font Awesome 5 :) Icons have a slight rounding on the edges, as that's consistent with our general look/feel: https://fontawesome.com/icons?d=gallery&c=shapes

**Closed by sensibleworld** 2018-03-30 00:57 UTC
Labels: new icon, web application icons
