### ISSUE TITLE
Minecraft Icon Request

### ISSUE THREAD

**Issue by The-Decoder97** [FortAwesome/Font-Awesome#15652] opened 2019-10-04 13:37 UTC
![image](https://user-images.githubusercontent.com/56162013/66211664-1fa9ee00-e6da-11e9-988a-e0b12fe257c6.png)

**Comment by tagliala** [comment] 2019-10-04 13:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1776, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-10-04 13:38 UTC
