### ISSUE TITLE
Icon request: flip-vertical, flip-horizontal

### ISSUE THREAD

**Issue by devou33** [FortAwesome/Font-Awesome#14426] opened 2018-12-19 19:48 UTC
Current requests are stale or different.

### What can it be used for?
In a CAD or Vector/Image editor, user can flip along an axis creating a mirror of the previous object.

### Example image (optional)
![screen shot 2018-12-19 at 1 09 28 pm](https://user-images.githubusercontent.com/7987602/50242240-5bfc9f80-038f-11e9-918e-b447e84678d8.png)

### Icon request checklist

- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by devou33** [comment] 2019-01-14 16:38
@tagliala, I created this ticket because the existing tickets do not have any details and/or are ancient, so I doubt they will progress. Can we either either merge this request in with one that you think is flushed out OR merge the others into this one?

**Comment by tagliala** [comment] 2019-01-14 18:11
Hi @devou33 thanks, since #11625 has just one +1, like this one, I'm going to close that in favour of this.

**Comment by lisivets** [comment] 2021-05-11 18:57
It will be good if this issue will be resolved someday ;-) I need this icons too.

**Comment by Tobjoern** [comment] 2021-05-17 20:02
Yes! I also need this one.

**Comment by tiesont** [comment] 2021-12-24 07:14
@tagliala If I want to plus-1 the concept (icons for flipping over an axis) but not this particular suggestion (that's not the icon I see in the editors I use which have this functionality), is the preference to simply upvote this issue and let the FA team figure out the correct glyphs, or to create a new issue/request instead?

**Comment by tagliala** [comment] 2021-12-24 09:45
Hi,

> is the preference to simply upvote this issue and let the FA team figure out the correct glyphs, or to create a new issue/request instead?

Upvote and comment with a different example

**Comment by toverux** [comment] 2022-03-26 15:50
I need this too! I don't really understand the glyphs in the proposal (well I have context so it's ok, but without it it doesn't seem obvious). Here's the Figma I'm implementing, I find them to make more sense:

![image](https://user-images.githubusercontent.com/1343250/160246944-31067ef8-8ad9-419e-9b7c-71c6cd89f696.png)

(Also, note the rotation arrow, it's clear that it's a 90° rotation, while the [two](https://fontawesome.com/icons/rotate-left?s=solid) [icons](https://fontawesome.com/icons/rotate-right?s=solid) for that in FontAwesome aren't that clear. An *-alt variant like this would be great).

**Comment by namrog84** [comment] 2023-10-02 21:33
Was just looking for something specifically like this and was disappointed fortawesome didn't already have something like this :(

**Comment by sensibleworld** [comment] 2024-07-11 19:08
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/3955)

**Closed by sensibleworld** 2024-07-11 19:08 UTC
Labels: new icon, design (category), Duplicate
