### ISSUE TITLE
Icon Request: fa-health

### ISSUE THREAD

**Issue by atindersingh67** [FortAwesome/Font-Awesome#8441] opened 2016-01-28 15:56 UTC
![health-sign-blue-icon 1](https://cloud.githubusercontent.com/assets/12206263/12649711/c6d71b16-c605-11e5-9da4-b79924000ac4.png)

**Comment by tagliala** [comment] 2016-01-28 16:07
Duplicate of #4325, please +1 that request

closing here

**Closed by tagliala** 2016-01-28 16:07 UTC
