### ISSUE TITLE
fa-layers-text does not render with SVG with JS and there is no official workaround

### ISSUE THREAD

**Issue by julienlegault** [FortAwesome/Font-Awesome#18235] opened 2021-09-02 16:46 UTC
**Describe the bug**
Layered icon and text does not render the text. 

**To Reproduce**
https://fontawesome.com/v6.0/docs/web/style/layer

Look at the calendar and certificate demo icons. They do not have the text that should be rendered within them (27 and NEW).

There is documentation that this is a know issue, but the documentation fails to provide an example for fixing the issue, and the official docs do not have any clear way that the issue could be fixed. 

**Expected behavior**
The fa-layers-text class should render the text to the page, or the documentation should explain what custom css needs to be used to create the same effect. 

**Screenshots**
![The broken stacks](https://user-images.githubusercontent.com/23064156/131883499-832c4aa9-31f9-4194-a3bb-567392fb8ad1.png)

![The known issue documentation](https://user-images.githubusercontent.com/23064156/131883560-50c2fb0d-0c74-4944-afe9-19bb4676ca8e.png)

**Version and implementation**
Version: 
Browser and version: 

- [X] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

I know that [this](https://github.com/FortAwesome/Font-Awesome/issues/13497) bug has been used to track this issue in the past, but I am looking for a more immediate fix (maybe just a documentation update) as that bug has been open for a couple years now.

**Comment by tagliala** [comment] 2021-09-02 18:00
Hi!

Thanks for being part of the Font Awesome Community.

> I know that this bug has been used to track this issue in the past, but I am looking for a more immediate fix (maybe just a documentation update) as that bug has been open for a couple years now.

Apologies, but I need to close this issue because it is a duplicate

We do not have an immediate fix, otherwise we would have shared it

Feel free to ask there if someone has a workaround

Closing here (as a duplicate of #13497)

**Closed by tagliala** 2021-09-02 18:00 UTC
