### ISSUE TITLE
Icon Request: fa-church

### ISSUE THREAD

**Issue by erzbistum** [FortAwesome/Font-Awesome#10620] opened 2017-02-06 08:39 UTC
It would be nice, to have a church-icon, e.g. for christian topics or as a tourist attraction.

With best regards out of the shadows of Cologne cathedral. :-)

**Comment by tagliala** [comment] 2017-02-06 10:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2088 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-06 10:25 UTC

**Comment by heyjoecampbell** [comment] 2018-02-23 17:09
There's already a request thread:
https://github.com/FortAwesome/Font-Awesome/issues/2088#issuecomment-368071285
