### ISSUE TITLE
Icon request: fa-toothbrush

### ISSUE THREAD

**Issue by James1x0** [FortAwesome/Font-Awesome#5623] opened 2015-02-09 17:51 UTC
It would be nice to have a tooth & toothbrush icon to refer to dentistry & dental applications. Healthcare icons are great, but these would be a good addition.

---

![toothbrush-512](https://cloud.githubusercontent.com/assets/6146261/6111926/cb70a296-b049-11e4-85f2-4aafd4eabf34.png)

**Comment by tagliala** [comment] 2015-02-09 19:13
tooth is  a duplicate of #1289 , please +1 that request

leaving this open as tootbrush

**Comment by James1x0** [comment] 2015-02-09 19:14
@tagliala Will do, thanks.

**Comment by G-Driver** [comment] 2015-03-20 13:00
+1

**Comment by dvorapa** [comment] 2015-08-25 21:48
+1

**Comment by jamiegiles** [comment] 2016-08-02 15:29
+1

**Comment by cgarveyie** [comment] 2018-03-03 14:45
+1

**Comment by sensibleworld** [comment] 2018-08-22 11:44
https://fontawesome.com/icons/toothbrush?style=solid

**Closed by sensibleworld** 2018-08-22 11:44 UTC
Labels: medical / health (category), new icon, released, web application icons
