### ISSUE TITLE
Icon Request: fa-tag-o

### ISSUE THREAD

**Issue by blogjw** [FortAwesome/Font-Awesome#10349] opened 2016-12-12 00:51 UTC
please, make it real

**Comment by tagliala** [comment] 2016-12-12 12:33
Duplicate of #4673, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-12 12:33 UTC
