### ISSUE TITLE
Icon request: painting (art, picture-frame, mona-lisa)

### ISSUE THREAD

**Issue by saunders3000** [FortAwesome/Font-Awesome#16696] opened 2020-05-22 03:01 UTC
**What can it be used for?**
Art work

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by saunders3000** [comment] 2020-05-22 03:03
![image](https://user-images.githubusercontent.com/2328628/82626992-d34ee800-9bae-11ea-9cb1-b5beb269abc7.png)

![image](https://user-images.githubusercontent.com/2328628/82627001-da75f600-9bae-11ea-8512-1f6b12dd90ae.png)

**Comment by aethior** [comment] 2022-04-02 15:27
*Related Unicode Emoji* https://github.com/FortAwesome/Font-Awesome/issues/222
🖼 [U+1F5BC](https://emojipedia.org/emoji/%F0%9F%96%BC/) Framed Picture
Also known as `Painting` and `Picture Frame`.

**Comment by sensibleworld** [comment] 2024-07-11 16:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.]()

**Closed by sensibleworld** 2024-07-11 16:37 UTC
Labels: new icon, images (category), Duplicate
