### ISSUE TITLE
Icon Request: fa-gym

### ISSUE THREAD

**Issue by rehanahmed38** [FortAwesome/Font-Awesome#7154] opened 2015-08-06 07:44 UTC
Well I am about to create website for gym and I am using Awesome fonts pack for the website icon but I can not find any gym related icons that I can use in website. Kindly include gym related icons so the look and feel of icon is more similar to the website theme.

Thanks

**Comment by TheChen5** [comment] 2015-08-06 21:48
Dupe of #5826
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-07 14:22
thanks, but please do not +1 #5826 

I still think #1500 is a better representation

**Closed by tagliala** 2015-08-07 14:22 UTC

**Comment by JoaoMarcosSampaio** [comment] 2017-03-07 15:00
+1
