### ISSUE TITLE
Icon Request: fa-icon-azn

### ISSUE THREAD

**Issue by amrahkarim** [FortAwesome/Font-Awesome#10954] opened 2017-04-16 11:14 UTC
Hi, it is Azerbaijanian manat symbol, I need to use this icon on my website.
![450px-azeri_manat_symbol svg](https://cloud.githubusercontent.com/assets/27621222/25070708/f3ec45e8-22ae-11e7-99b8-8f2154bbde69.png)

**Comment by tagliala** [comment] 2017-04-16 17:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1460, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-16 17:12 UTC
