### ISSUE TITLE
Icon request: scooter

### ISSUE THREAD

**Issue by yabisko** [FortAwesome/Font-Awesome#7806] opened 2015-11-03 14:37 UTC
![scooter-02-256-8](https://cloud.githubusercontent.com/assets/15632696/10910645/39d17f9a-8249-11e5-8ad8-1715003fcf93.png)

**Comment by caduvieira** [comment] 2015-11-03 14:54
Dupe of #6897
Please +1 that one

**Closed** 2015-11-14 11:22 UTC
