### ISSUE TITLE
Icon Request: fa-pram / fa-buggy / fa-stroller

### ISSUE THREAD

**Issue by SupremeSimon** [FortAwesome/Font-Awesome#12751] opened 2018-04-01 12:21 UTC
Baby in or out of a pram. just to reference a child.

**Comment by einavsh** [comment] 2018-05-16 09:58
+1
![index](https://user-images.githubusercontent.com/13317047/40110533-de7ab2bc-5908-11e8-9207-948a82888cff.png)

**Comment by tagliala** [comment] 2018-05-16 13:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6124, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-16 13:39 UTC
