### ISSUE TITLE
Icon Request: fa-aparat

### ISSUE THREAD

**Issue by professormahi** [FortAwesome/Font-Awesome#10933] opened 2017-04-13 08:05 UTC
Please add Aparat icon. Aparat is a video sharing service in Iran. 

link: [http://www.aparat.com](http://www.aparat.com)

Icon is:
![aparat_icon_color_black_1024](https://cloud.githubusercontent.com/assets/7943375/24995866/a8aeadca-2045-11e7-9469-1fcb5b628e3d.png)

**Comment by tagliala** [comment] 2017-04-13 08:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5204 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-13 08:09 UTC
