### ISSUE TITLE
Icon request: mountain

### ISSUE THREAD

**Issue by jckb188** [FortAwesome/Font-Awesome#10569] opened 2017-01-25 15:40 UTC

**Comment by tagliala** [comment] 2017-01-25 15:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4109, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-25 15:59 UTC
