### ISSUE TITLE
Icon not working: "fas fa-fan" https://fontawesome.com/icons/fan?style=solid

### ISSUE THREAD

**Issue by arsenanai** [FortAwesome/Font-Awesome#15785] opened 2019-11-07 10:39 UTC
**Describe the bug**
I wanted to use icon: https://fontawesome.com/icons/fan?style=solid. But it won't work

**To Reproduce**
```
<span class="fa-stack fa-4x">
              <i class="fas fa-square fa-stack-2x"></i>
              <i class="fas fa-fan fa-stack-1x text-secondary"></i>
            </span>
```

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
Should work

**Screenshots**
![image](https://user-images.githubusercontent.com/4026277/68381846-bc015d80-017c-11ea-84f3-6e64156e7844.png)

**Version and implementation**
Version: 5.11.2
Browser and version: Version 78.0.3904.87 (Official Build) (64-bit)

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2019-11-07 13:50
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot reproduce.

Demo: https://jsfiddle.net/tagliala/1nyx6efz/6/

I'm using `fa-inverse` because I think that `text-secondary` is a class specific to your application

Please try the following:
- [fa-fan](https://fontawesome.com/icons/fan?style=solid) has been introduced in FA 5.10.1, please make sure that you are using at least FA >= 5.10.1. Sometimes it happens that a third-party library/plugin/theme overwrite your Font Awesome version of choice
- Other suggestions at https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Hope it helps

Closing here

**Closed by tagliala** 2019-11-07 13:50 UTC
