### ISSUE TITLE
Icon request: laser-cutting

### ISSUE THREAD

**Issue by Consilia78** [FortAwesome/Font-Awesome#14195] opened 2018-10-30 17:17 UTC
### What can it be used for?
Hello,
I need this icon for my website.

I think this is useful for anyone involved in this type of work.
Thank you
### Example image (optional)
![taglio-laser](https://user-images.githubusercontent.com/44615660/47736769-ae62ef00-dc6f-11e8-80da-a2d1aa888e60.png)

or

![114961-200](https://user-images.githubusercontent.com/44615660/47736778-b4f16680-dc6f-11e8-8be2-2158afefd5e9.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment] 2024-07-11 19:11
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/9890)

**Closed by sensibleworld** 2024-07-11 19:11 UTC
Labels: new icon, Duplicate
