### ISSUE TITLE
Icon request: icon-canoe

### ISSUE THREAD

**Issue by yukoninfo** [FortAwesome/Font-Awesome#16340] opened 2020-03-21 00:39 UTC
**What can it be used for?**
Whenever you need to show a Canoe. An iconic mode of transportation used widely in Canada and I'm sure in other parts of the world.

<img width="723" alt="Screen Shot 2020-03-20 at 5 38 14 PM" src="https://user-images.githubusercontent.com/6411566/77215530-becc7180-6ad1-11ea-9f76-520a1c4a2230.png">

**Comment by tagliala** [comment] 2020-03-21 09:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13240, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-21 09:43 UTC
