### ISSUE TITLE
Brand request: Grafana

### ISSUE THREAD

**Issue by joshbartholomew** [FortAwesome/Font-Awesome#19572] opened 2023-02-20 10:27 UTC
### Description

Have seen this elsewhere but still don't have it for some reason... Can we have Grafana logo added please? 

https://grafana.com/

### Official website

https://grafana.com/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2023-02-20 10:31
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19438, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-02-20 10:31 UTC
Labels: brand icon
