### ISSUE TITLE
Brand request: Moodle

### ISSUE THREAD

**Issue by mtsyr3** [FortAwesome/Font-Awesome#19639] opened 2023-03-30 11:23 UTC
### Description

Would like to have Moodle icons with something denoting the version number for use in documentation/guidance that will be used by staff and students.

### Official website

https://moodle.org/

### Brand guidelines

https://moodle.com/wp-content/uploads/2023/01/Moodle_GlobalBrandGuidelines_Dec22.pdf

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by aethior** [comment] 2023-04-13 20:06
Duplicate of #2167?

**Closed as completed** 2023-04-13 20:31 UTC
Labels: brand icon
