### ISSUE TITLE
fa-pencil-alt, fa-wine-glass-alt, fa-untappd don't display using CDN

### ISSUE THREAD

**Issue by mwaltuch** [FortAwesome/Font-Awesome#14359] opened 2018-12-04 20:17 UTC
I'm declaring:
```
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/solid.css' integrity='sha384-rdyFrfAIC05c5ph7BKz3l5NG5yEottvO/DQ0dCrwD8gzeQDjYBHNr1ucUpQuljos' crossorigin='anonymous'>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/brands.css' integrity='sha384-QT2Z8ljl3UupqMtQNmPyhSPO/d5qbrzWmFxJqmY7tqoTuT2YrQLEqzvVOP2cT5XW' crossorigin='anonymous'>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/fontawesome.css' integrity='sha384-u5J7JghGz0qUrmEsWzBQkfvc8nK3fUT7DCaQzNQ+q4oEXhGSx+P2OqjWsfIRB8QT' crossorigin='anonymous'>
```
but when referenced in this context, fa-wine-glass-alt and fa-pencil-alt don't display:
```
<li>
   <a class="mw1" href="club.html">
      <span class="icon major style3 fas fa-wine-glass-alt"></span>
      <h3 class="mwh3">Wine Club</h3>
      <p>Free tastings, wines of the month, discounts, and more.</p>
   </a>
</li>
                        
<li>
<a class="mw1" href="email.html">
   <span class="icon major style5 fas fa-pencil-alt"></span>
      <h3 class="mwh3">Sign Up</h3>
      <p>Sign up for our mailing list.</p>
</a>
</li>
```
or in this context fa-untappd doesn't display:
```
 <li>
         <h4 class="icon fab fa-untappd"><span class="label">Untappd</span></h4>
         <a href="https://untappd.com/v/xxxxxx/nnnnnn">untappd.com</a>
</li>
```
Other icons display just fine; for example: fas fa-calendar-alt in the first context and fas fa-clock in the second. 
I'm looking for suggestions as to where to solve the issue or any pointers you can give me.

**Comment by tagliala** [comment] 2018-12-04 20:52
Hi!

Thanks for being part of the Font Awesome Community.

I've filled in a fiddle with your code and I'm not able to reproduce: http://jsfiddle.net/tagliala/m5na9bsL/1/

Could you please check that there isn't a third-party plugin/theme/library interfering with your font awesome version?

Ref: https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting#icon-noshow

Closing here but feel free to keep commenting

**Closed by tagliala** 2018-12-04 20:52 UTC
