### ISSUE TITLE
Icon Request: fa-sailingboat

### ISSUE THREAD

**Issue by beamaria** [FortAwesome/Font-Awesome#11167] opened 2017-06-13 09:20 UTC
hi, it would be nice to have a sailing boat icon to put in websites related to nautical races/sailing clubs etc.
Ideally a very simple icon like this: ⛵️(this is from a Facebook page of traditional sail boats); basically two little triangles with a thick line under them should suit...
Thanks!

**Comment by tagliala** [comment] 2017-06-13 10:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5079, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-13 10:02 UTC

**Comment by beamaria** [comment] 2017-06-13 10:47
Sorry I didn’t find it previously!
Anyway I added my request… Thanks!

Elisabetta Petroni
