### ISSUE TITLE
Icon request: icon-name Responsive Web Design

### ISSUE THREAD

**Issue by Amber-Pittman** [FortAwesome/Font-Awesome#13444] opened 2018-06-28 04:48 UTC
### What can it be used for?

Hey there! First time doing this, so if what I'm doing/asking for is not the right way to go about it, I apologize in advance. 

Background Info: 
I'm in the process of learning to code. I'm using freeCodeCamp as my main source of education for now. Currently, I'm working on the [personal portfolio project](https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage) and what I'd like to do is separate my projects by focus and use icons to represent each focus. 

For the "Responsive Web Design Projects, I was hoping Font-Awesome could create an icon for this? Like a Desktop Screen, Tablet, and Mobile grouped together?

### Example image (optional)

FlatIcon has _[something similar](https://www.flaticon.com/free-icon/responsive-design-symbol_65381)_ to what I'm looking for but they want full credit on the page itself instead of in the HTML/CSS sections. I want this page to eventually get better as I learn more (planning to use it to gain traction towards a job). I have no problem crediting but at the end of the day, it's going to junk-up my portfolio. 

### Icon request checklist

- [X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X ] I have included at least one example image if it could be helpful (optional)
- [X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Thanks in advance for any help you can provide. Again, if I did this wrong, my apologies. 

Amber

**Comment by tagliala** [comment] 2018-06-28 08:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1446 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-28 08:04 UTC
