### ISSUE TITLE
Icon request: audio-mack

### ISSUE THREAD

**Issue by RemarkableAjay** [FortAwesome/Font-Awesome#17118] opened 2020-09-04 14:28 UTC
[audiomack-2.0-media-kit.zip](https://github.com/FortAwesome/Font-Awesome/files/5175420/audiomack-2.0-media-kit.zip)
**What can it be used for?**
Its an icon for audiomack, a popular music streaming platform

**Example image (optional)**
https://audiomack.com/audiomack-2.0-media-kit.zip

**Icon request checklist**
- [x] This is a single icon or matched pair (Matched`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Yes: Icon request: audio-mack`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate (Yes)
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-04-15 03:20
Hi @RemarkableAjay,

This request is duplicate of #12317.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed** 2022-04-15 07:29 UTC
