### ISSUE TITLE
Icon request: icon-ansible

### ISSUE THREAD

**Issue by k4ch0** [FortAwesome/Font-Awesome#17057] opened 2020-08-19 20:15 UTC
**What can it be used for?**

Ansible is an IT automation tool that simplifies IT orchestration and app deployment. We find your icons extremely useful and an Ansible icon would be really cool. We currently have on in slack that we use from time to time. I've attached a screenshot as well. It could be named fa-ansible or just ansible.

This is a follow up from issue: #5938

**Example image (optional)**

![Ansible](https://cloud.githubusercontent.com/assets/7010629/6618270/dd8e701e-c897-11e4-8802-522f438aa1d0.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate 
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-08-20 07:27
Hi @k4ch0 ,

This is a duplicate of #5938. We should use just one request for icon, and it is important to use just one request to preserve upvotes, so I have to close this.

Since this is is your second attempt to open a duplicate for Ansible #17053, are there any question about contributing guidelines?

**Closed by tagliala** 2020-08-20 07:27 UTC

**Comment by iDustbin** [comment] 2022-06-24 05:10
ansible not existend ? when do you plan to include it ?
