### ISSUE TITLE
Icon Request: fa-conference-badge

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9994] opened 2016-09-29 18:18 UTC
Conference badge for use within a healthcare data app
![conference-badge](https://cloud.githubusercontent.com/assets/539719/18966527/8d44e062-864f-11e6-82af-a7446c8fad91.png)

**Comment by tagliala** [comment] 2016-09-30 09:06
I'm going to consider this a duplicate of #825

**Closed by tagliala** 2016-09-30 09:06 UTC

**Comment by yesi79** [comment] 2017-07-25 22:55
Perhaps a duplicate, but I like my design better :-)

**Comment by tagliala** [comment] 2017-07-26 07:54
@yesi79 this was considered a duplicate of icon-id-card which is now available in filled-in and outline versions: http://fontawesome.io/icon/id-card-o/ http://fontawesome.io/icon/id-card-o/

I could reopen this, if you want, but you could find an example which fits 16px icon size better
