### ISSUE TITLE
Icon request: fa-blogspot

### ISSUE THREAD

**Issue by simplynice25** [FortAwesome/Font-Awesome#7136] opened 2015-08-04 17:51 UTC
The title says it all.

**Comment by TheChen5** [comment] 2015-08-04 20:20
This might be a dupe of #1088 
Blogger should be the same as Blogspot
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-06 13:02
@TheChen5  thanks :)

**Closed by tagliala** 2015-08-06 13:02 UTC
