### ISSUE TITLE
Icon request: screw

### ISSUE THREAD

**Issue by kraly** [FortAwesome/Font-Awesome#16996] opened 2020-08-05 20:34 UTC
This is an example
![123](https://user-images.githubusercontent.com/651501/89461197-6a442e80-d720-11ea-9674-9d529f19197b.png)

**Comment by tagliala** [comment] 2020-08-05 21:13
Hi!

Thanks for being part of the Font Awesome Community.

Is there an alternative name that we can use?

We already have `fa-bolt`: https://fontawesome.com/icons/bolt

**Comment by kraly** [comment] 2020-08-05 21:14
Hi,

it's a Bolt or Screw not a lighting bolt.

**Comment by tagliala** [comment] 2020-08-05 21:26
Going for screw, we also have #16301

**Comment by kraly** [comment] 2020-08-05 23:02
Thanks for the reply,

i'm looking something like the files attached

**Comment by sensibleworld** [comment] 2024-07-11 16:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/17992)

**Closed by sensibleworld** 2024-07-11 16:33 UTC
Labels: new icon, web application icons (legacy category), Duplicate
