### ISSUE TITLE
Font-icons image sizes are different

### ISSUE THREAD

**Issue by anilapu** [FortAwesome/Font-Awesome#6268] opened 2015-04-20 06:56 UTC
This is not a issue.This is an improvement. If icon images are same then inputgroup-addon class will have same width for each fontawsome class
![icons](https://cloud.githubusercontent.com/assets/9476474/7225100/66dff2dc-e758-11e4-8306-e6ecb9e53a48.png)

**Comment by ejio** [comment] 2015-04-20 07:03
For anyone interested in resolving this on their sites, add fa-fw to the icon class, e.g.

    <i class="fa fa-fw fa-question"></i>

A global "fix" can be achieved through CSS by applying the following:

    .fa-*{
        width:1.28571429em;
        text-align:center
    }

Note the value above may be subject to change in future updates.

**Comment by anilapu** [comment] 2015-04-20 07:06
Thanks @ejio this is very helpful.

**Closed** 2015-04-20 08:20 UTC

**Comment by tagliala** [comment] 2015-04-20 09:48
Hi @anilapu , as pointed out by @ejio  you should use `fa-fw` as in examples: http://fontawesome.io/examples/#bootstrap

Icons in FA are not of the same width by design choice. Note that fa-fw could cause lose of pixel perfection. If you are interested in giving the same width to all icons, you can override the `.fa` class (no need of universal selectors like `.fa-*`)

**Comment by anilapu** [comment] 2015-04-20 09:53
Hi @tagliala , that may be true but in my opinion using with some other class is a good practice so we won't loss original characteristics.

**Comment by tagliala** [comment] 2015-04-20 13:41
@anilapu I do agree, you should add `fa-fw`.

I was talking about the above example... In other words if you always need to write `fa fa-icon`, it is better to override the `.fa` selector instead of adding `.fa-*` to your stylesheet

**Comment by anilapu** [comment] 2015-04-21 04:33
@tagliala , I agree that

**Comment by ejio** [comment] 2015-04-21 05:37
@tagliala @anilapu 

Updated my post to reference the best practice discussion further down the issue.
