### ISSUE TITLE
Icon Request: tik-tok (brand)

### ISSUE THREAD

**Issue by Wingo5315** [FortAwesome/Font-Awesome#14922] opened 2019-04-20 07:19 UTC
It could be a monochrome, solid version of the below:
![](https://purepng.com/public/uploads/thumbnail/tik-tok-logo-o3r.png)

**Comment by tagliala** [comment] 2019-04-20 12:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14340, please add a 👍 reaction to that request.

I've edited the title of #14340 because a search for `tik-tok` did not produce results, now it should be fixed

Closing here

**Closed by tagliala** 2019-04-20 12:07 UTC
