### ISSUE TITLE
Icon request: icon-tshirt

### ISSUE THREAD

**Issue by cinqlair** [FortAwesome/Font-Awesome#11671] opened 2017-10-26 05:42 UTC
Hi guy, 

Thank you for the great job you do. It would be nice to have a new t-shirt icon. 
Simple, beautiful and refined as you know how to do !

![white-t-shirt](https://user-images.githubusercontent.com/25717685/32036564-e59eef5e-ba20-11e7-9341-652353c7ca21.png)
![t-shirt 1](https://user-images.githubusercontent.com/25717685/32036573-f745d68c-ba20-11e7-9ff6-f2f33e8dbf98.png)

**Comment by tagliala** [comment] 2017-10-26 08:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #715 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-26 08:41 UTC
