### ISSUE TITLE
fa-triathlon

### ISSUE THREAD

**Issue by ps-devinsmith** [FortAwesome/Font-Awesome#19156] opened 2022-06-29 15:11 UTC
Hi, I am in need of a sport/event icon to represent a sporting event known as a triathlon which consists of running, biking, and swimming.

**Comment by tagliala** [comment] 2022-06-29 15:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14304, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-06-29 15:27 UTC

**Comment by ps-devinsmith** [comment] 2022-06-29 17:25
Thanks.
