### ISSUE TITLE
Icon Request: fa-trailer

### ISSUE THREAD

**Issue by Pumizo** [FortAwesome/Font-Awesome#10676] opened 2017-02-17 12:32 UTC
Hi,

I would love to have a "trailer" icon on font awesome. It's commonly used in transport sites and many other occasions.

Thanks in advance and keep up the excellent work!

Example image:
[https://www.iconexperience.com/_img/i_collection_png/512x512/plain/truck_trailer.png](url)

**Comment by tagliala** [comment] 2017-02-17 13:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7369, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-17 13:06 UTC
