### ISSUE TITLE
Icon-request: icon-hellocoton

### ISSUE THREAD

**Issue by Petoush** [FortAwesome/Font-Awesome#8523] opened 2016-02-10 14:30 UTC
www.hellocoton.fr french website for making a directory of female blogs
![alt tag](https://goo.gl/photos/9wuEsuKxWbXh12yCA)

**Comment by tagliala** [comment] 2016-03-17 20:00
duplicate of #5008, please +1 that request

closing here

**Closed by tagliala** 2016-03-17 20:00 UTC
Labels: brand icons, new icon
