### ISSUE TITLE
Icon request: not-under-18

### ISSUE THREAD

**Issue by BelarusAndreas** [FortAwesome/Font-Awesome#17851] opened 2021-04-27 04:57 UTC
**What can it be used for?**
An icon which can use to mark a content that was not for people under 18.  

**Example image (optional)**
[Wikimedia.org - Icon not-under18](https://commons.wikimedia.org/wiki/File:Icon-not-under18.svg)

**Comment by tagliala** [comment] 2021-04-27 08:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5298, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-04-27 08:14 UTC
