### ISSUE TITLE
Icon Request: fa-crown

### ISSUE THREAD

**Issue by cosminrr** [FortAwesome/Font-Awesome#10903] opened 2017-04-06 15:32 UTC
A crown icon would be useful! 
I use Font Awesome right now and I need a crown Icon...

**Comment by PeterShaggyNoble** [comment] 2017-04-06 16:05
Dupe of #486; you should 👍 that.

**Comment by NonameSLdev** [comment] 2017-04-25 08:13
Close this issue?

**Closed** 2017-04-25 11:43 UTC
