### ISSUE TITLE
Icon request: icon-celiac

### ISSUE THREAD

**Issue by ivanlori** [FortAwesome/Font-Awesome#14872] opened 2019-04-10 13:40 UTC
Hi, it could be useful to have an icon for celiac like the ones below.
![Annotazione 2019-04-10 153609](https://user-images.githubusercontent.com/7620920/55883567-dc494980-5ba6-11e9-96e5-7ecd14aa6945.jpg)

**Comment by tagliala** [comment] 2019-04-10 15:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2405, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-10 15:15 UTC
