### ISSUE TITLE
Icon Request: Diaspora social network

### ISSUE THREAD

**Issue by altsheets** [FortAwesome/Font-Awesome#7830] opened 2015-11-05 14:55 UTC
This is the network https://en.wikipedia.org/wiki/Diaspora_(social_network)
and this the software https://en.wikipedia.org/wiki/Diaspora_(software)

There are ready icons and logos, e.g.:
* http://creativekaizen.deviantart.com/art/Diaspora-Icon-Set-257241499
* http://naesk.deviantart.com/art/Diaspora-Artwork-Toolkit-254178705
* https://wiki.diasporafoundation.org/Logos,_icons_and_visual_art

Perhaps this will help too?
* https://github.com/ruhrspora/diaspora_glyphs

I am asking because I want to integrate 4 more 'social buttons' into my jekyll website, and one of them is DIASPORA (see issue https://github.com/PanosSakkos/personal-jekyll-theme/issues/41#issuecomment-154021145 ).

I know there have already been diaspora icon requests here:
* https://github.com/FortAwesome/Font-Awesome/issues/414
* https://github.com/FortAwesome/Font-Awesome/issues/459

They got many +1 likes 
... in those 3 years.

Thanks a lot for considering to include Diaspora into FontAwesome.

**Comment by tagliala** [comment] 2015-11-13 21:09
Sorry but this is a duplicate of #414 and I need to close this one

If you need this icon in a short while, please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2015-11-13 21:09 UTC

**Comment by altsheets** [comment] 2015-11-13 22:23
> Sorry but this is a duplicate of #414

I know.

>  and I need to close this one

no problem. Sorry for causing work.

As that #414 was >> 3 years old, I just thought a new issue might help.

> please consider a custom build

Thanks a lot for the hint.

For now, I have simply chosen a completely different icon ([3rd from the right](http://altsheets.ddns.net/assetgraphs/v2/products/#contact)). Not perfect, but nice too.

**Comment by tagliala** [comment] 2015-11-14 09:01
Thanks for your understanding :+1:
