### ISSUE TITLE
Icon Request: fa-coub

### ISSUE THREAD

**Issue by WhiSky1337** [FortAwesome/Font-Awesome#11409] opened 2017-08-15 23:37 UTC
On my webpage I'm using icons to redirect on my accounts(social, steam, etc.), but I didn't found coub icon. Please add it :)
![coub](https://user-images.githubusercontent.com/22481607/29341198-8cceebea-822b-11e7-8843-bb6956a68922.png)

**Comment by tagliala** [comment] 2017-08-16 08:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3957, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-16 08:16 UTC
