### ISSUE TITLE
Icon request: restroom

### ISSUE THREAD

**Issue by chris-kuhn** [FortAwesome/Font-Awesome#13631] opened 2018-07-26 03:24 UTC
### What can it be used for?

Universal restroom symbol

Any website listing amenities including restrooms such as hotels, booking, bus and travel websites

### Example image (optional)

https://www.iconfinder.com/icons/286632/bathroom_couple_female_girl_human_male_man_person_restroom_silhouette_toilet_wc_woman_icon

### Icon request checklist

- [ X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X] I have included at least one example image if it could be helpful (optional)
- [ X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-26 17:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2670, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-26 17:04 UTC
