### ISSUE TITLE
Icon Request: fa-codeigniter

### ISSUE THREAD

**Issue by InsiteFX** [FortAwesome/Font-Awesome#8091] opened 2015-12-05 12:58 UTC
The CodeIgniter Commuity would like to request an icon for the CodeIgniter Framework.

You can see the CodeIgniter logo icon here:

https://github.com/FortAwesome/Font-Awesome/issues/8087

Thank you
InsiteFX

**Comment by tagliala** [comment] 2015-12-05 13:00
Duplicate of #4316 , please +1 that request

closing here

**Closed by tagliala** 2015-12-05 13:00 UTC

**Comment by riwakawebsitedesigns** [comment] 2016-06-28 23:46
+1

**Comment by tagliala** [comment] 2016-06-29 08:42
duplicate of #4316, :lock:
