### ISSUE TITLE
Icon Request: fa-kzt

### ISSUE THREAD

**Issue by aktaumag** [FortAwesome/Font-Awesome#9707] opened 2016-08-05 08:38 UTC
Hello
Thank you for your icons.
I want to ask to make an icon - the currency of Kazakhstan (tenge, KZT) - ₸

[wikipedia - Kazakhstani_tenge](https://en.wikipedia.org/wiki/Kazakhstani_tenge)

Thank you. You are super!

**Comment by tagliala** [comment] 2016-08-05 11:16
Duplicate of #2378, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-05 11:16 UTC
