### ISSUE TITLE
Icon request: Program windows

### ISSUE THREAD

**Issue by exetico** [FortAwesome/Font-Awesome#9118] opened 2016-05-04 15:39 UTC
In the past time, i have really needed some "program icons" like:
![image](https://cloud.githubusercontent.com/assets/3549445/15019646/2016c612-121f-11e6-950e-c648efbfb1c1.png)
(Best ^^)

![image](https://cloud.githubusercontent.com/assets/3549445/15019603/febe746a-121e-11e6-9c3d-d256266f1603.png)
![image](https://cloud.githubusercontent.com/assets/3549445/15019609/05383e7a-121f-11e6-873a-7481c96ed03e.png)
![image](https://cloud.githubusercontent.com/assets/3549445/15019617/08d987b4-121f-11e6-9f85-2be8a51d9319.png)

It would really help me out, then using Font-Awesome in websites with program-window like links.

**Comment by tagliala** [comment] 2016-05-04 15:43
Duplicate of #3585 , please +1 that request and post there your examples

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-04 15:43 UTC
