### ISSUE TITLE
Icon Request: IMDb & Crew United

### ISSUE THREAD

**Issue by neu1886** [FortAwesome/Font-Awesome#7007] opened 2015-07-22 16:38 UTC
Hi would be great, if you can add the following 2 Brands:
## IMDb
![IMDb](http://ia.media-imdb.com/images/M/MV5BMTQ0Nzc4NDcxNl5BMl5BcG5nXkFtZTgwODAzNDg0MjE@._V1_.png)
http://www.imdb.com/pressroom/brand_guidelines/

## Crew United
![Crew United](https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xfa1/v/t1.0-1/p160x160/11324_10150319993989959_1646655805_n.jpg?oh=75dcd2c826925d14b662d3f7851776c7&oe=564D0324&__gda__=1447847071_c0cfa2a471c3277bb16fb04a5a44a30a)
http://english.crew-united.com

Thanks for your work!!!

**Comment by tuxy** [comment] 2015-07-22 23:14
Better iMDb Icon:

![iMDb Icon](http://i.imgur.com/RraYT1y.png)

Source: http://www.iconarchive.com/show/ios7-icons-by-icons8/Cinema-Imdb-icon.html

**Comment by tagliala** [comment] 2015-07-30 19:24
imdb is a duplicate of #998 , please +1 that request

let's use #7089  for crew united

closing here

**Closed by tagliala** 2015-07-30 19:24 UTC
