### ISSUE TITLE
fas fa-dice cannot use in freeIcon

### ISSUE THREAD

**Issue by yam4863245** [FortAwesome/Font-Awesome#17154] opened 2020-09-16 10:04 UTC
fas fa-dice cannot use in freeIcon

**Comment by tagliala** [comment] 2020-09-16 11:22
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

Sorry, can't reproduce.

Demo (using FA 5.14.0 CSS): https://jsfiddle.net/tagliala/0x1qe4by/

[fa-dice](https://fontawesome.com/icons/dice?style=solid) has been introduced in Font Awesome 5.0.13.

Please make sure that you are using FA >= 5.0.13

Please also double check that there aren't third-party plugins/themes/libraries loading an older version of Font Awesome that may have priority over yours

If you are still experiencing this issue, please open a new request, fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md), and provide a reproducible test case

Hope it helps

Closing here

Ref: 
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Closed by tagliala** 2020-09-16 11:22 UTC
