### ISSUE TITLE
Icon request: t-shirt

### ISSUE THREAD

**Issue by monselars** [FortAwesome/Font-Awesome#6387] opened 2015-05-05 08:05 UTC
Hi! First of all – thank you so much for such a nice font-type, it's genius! I love it. It helps me a lot :-)
I was browsing your icons and noticed that you don't have any icons for clothes. I was wonder if you could make a T-shirt icon? Otherwise I'll just use your cart (it's for a webshop). 

Thank you anyways, you're the greatest! 
- says a webdesigner and develeoper.

**Comment by tagliala** [comment] 2015-05-16 20:02
Duplicate of #715 , please +1 that request

closing here

**Closed by tagliala** 2015-05-16 20:02 UTC
