### ISSUE TITLE
Icon Request: fa-netease-music

### ISSUE THREAD

**Issue by brunommpreto** [FortAwesome/Font-Awesome#17821] opened 2021-04-16 02:51 UTC
https://www.easyicon.net/language.en/1188681-NetEase_music_icon.html

**Comment by tagliala** [comment] 2021-04-16 08:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8255, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-04-16 08:05 UTC
