### ISSUE TITLE
Icon Request: fa-king-chrown

### ISSUE THREAD

**Issue by andrkrn** [FortAwesome/Font-Awesome#5962] opened 2015-03-14 13:39 UTC
icon for ambassador or king

![king chrown image](https://cdn0.iconfinder.com/data/icons/online-shopping-3/78/Shopping_icons_vector-11-512.png)

**Comment by tagliala** [comment] 2015-03-14 15:22
duplicate of #1903 , please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-03-14 15:22 UTC

**Comment by dngunraj** [comment] 2015-03-26 20:34
+1
