### ISSUE TITLE
Icon Request - Type Tool | fa-text / fa-typetool

### ISSUE THREAD

**Issue by webdev20** [FortAwesome/Font-Awesome#8839] opened 2016-03-27 17:13 UTC
Cannot find this kind of font icon, so I send a request for it.

![type-tool](https://cloud.githubusercontent.com/assets/4498399/14066659/a6821d5a-f479-11e5-8d8b-e725bc3c7280.png)

Thank you :)

**Comment by tagliala** [comment] 2016-03-27 19:19
is this a brand?

**Comment by aethior** [comment] 2016-07-08 20:16
Duplicate of #8349.

cc @tagliala

**Closed** 2016-07-08 20:41 UTC
