### ISSUE TITLE
Icon Request: fa-audit

### ISSUE THREAD

**Issue by dannyemf** [FortAwesome/Font-Awesome#9070] opened 2016-04-27 15:29 UTC
Audit, audit trail, audit search

**Comment by PeterShaggyNoble** [comment] 2016-04-27 15:41
Dupe of [#3175](https://github.com/FortAwesome/Font-Awesome/issues/3175) (via [#2806](https://github.com/FortAwesome/Font-Awesome/issues/2806); you should +1 that one instead

**Closed** 2016-04-27 17:28 UTC
