### ISSUE TITLE
Icon books

### ISSUE THREAD

**Issue by pmerinocobaleda** [FortAwesome/Font-Awesome#9645] opened 2016-07-26 09:48 UTC
Name: icon-books
![books-01](https://cloud.githubusercontent.com/assets/20659929/17133564/e3018462-5326-11e6-80f1-c25fc84a0545.png)

**Comment by tagliala** [comment] 2016-07-26 10:10
Duplicate of #5098, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-26 10:10 UTC
