### ISSUE TITLE
Request For New icons

### ISSUE THREAD

**Issue by Gajendrasinh** [FortAwesome/Font-Awesome#5376] opened 2015-01-12 11:51 UTC
Hi ... I need to use usb icon if possible then release one usb icons

**Comment by tagliala** [comment] 2015-01-12 12:07
duplicate of #2165 , please +1 that request

closing here

**Closed by tagliala** 2015-01-12 12:07 UTC

**Comment by zebulon888** [comment] 2019-04-11 11:15
How about new ICONS for:
GAB (https://gab.com)
DISSENTER (https://dissenter.com)
MINDS (https://www.minds.com/)
STEEMIT (https://steemit.com/)
BITCHUTE (https://www.bitchute.com)
DTUBE (https://d.tube/)
