### ISSUE TITLE
Icon Request: fa-blogger

### ISSUE THREAD

**Issue by tiennguyenvan** [FortAwesome/Font-Awesome#7100] opened 2015-07-31 02:41 UTC
Why we have Wordpress icon, but not have Blogger? So we must find workaround solution to work with FontAwesome or simple not use it.

![blogger-logo-01](https://cloud.githubusercontent.com/assets/12868514/8999746/fc6340ba-3768-11e5-92fc-1956b75f585e.png)
![blogger-logo-02](https://cloud.githubusercontent.com/assets/12868514/8999747/00733e44-3769-11e5-99d4-4187f9bb6427.png)

Million people need blogger icon, just create one, it's easy.

Thank you.

**Comment by TheChen5** [comment] 2015-07-31 05:09
Dupe of #1088 
+1 that
It looks like it is going to be in 5.0.0 version
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-07-31 07:22
@TheChen5 thanks

**Closed by tagliala** 2015-07-31 07:22 UTC
