### ISSUE TITLE
Icon request: icon-code-alt

### ISSUE THREAD

**Issue by johnsheehan** [FortAwesome/Font-Awesome#1552] opened 2013-07-11 03:42 UTC
The current icon-code has a very liberal definition of code and should really be called icon-markup. I would like to see icon-code-alt be a pair of braces `{ }`. Using actual text braces doesn't look quite right next to the other icons.

**Comment by Saluev** [comment] 2015-07-14 22:15
+1

**Comment by TheChen5** [comment] 2015-08-09 00:49
+1

**Comment by helenst** [comment] 2015-09-28 10:30
:+1: I'm working on a system based around software projects / code repositories which are very rarely markup-related. Something like this would be far more suitable than the icon depicting markup.
![braces](https://cloud.githubusercontent.com/assets/217966/10133310/3416d6b8-65d4-11e5-9681-39db9cae8ef4.png)

**Comment by tagliala** [comment] 2015-09-28 11:52
hmmm #1797 is a duplicate of this one, with a better title and more +1s

I will close this one, I will take care to add your +1s on #1797

**Closed by tagliala** 2015-09-28 11:52 UTC
Labels: enhancement, new icon, web application icons
