### ISSUE TITLE
Icon request: fa-layout, fa-layout-*

### ISSUE THREAD

**Issue by relosmot** [FortAwesome/Font-Awesome#13639] opened 2018-07-26 15:10 UTC
### What can it be used for?
This set of icons could be used in a number of different ways, including, but not limited to:
- UI/UX settings fields for choosing a website layout.
- Website theme/plugin/template sales pages to show software features.
- Design/development project quotes for a client.
- Theme/template builder software for visual representation of settings buttons.

### Rough Draft Example/Ideas
_This example is mainly here to show popular/potential column structures._
_The header area, rounded corners, thickness & shape are all potential variables for design._

![site-layout-icon-idea](https://user-images.githubusercontent.com/5460538/43269289-28004230-90b8-11e8-93ed-2d2f8da0df69.png)

Would love to hear if anyone has ideas to expand on this as well. 

**Cheers!**
Tom

**Comment by tagliala** [comment] 2018-07-26 15:29
Hi!

Thanks for being part of the Font Awesome Community.

layout is a duplicate of #6100 

Since contributing guidelines for Font Awesome Free does not allow requests for icon sets, I need to close this request.

If you want, you could open single individual request (layout-two-colums, layout-left-column...) or request a set in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Closed by tagliala** 2018-07-26 15:29 UTC
