### ISSUE TITLE
Icon Request: fa-lightbulb-circle-o

### ISSUE THREAD

**Issue by pekpyt1** [FortAwesome/Font-Awesome#10746] opened 2017-03-06 15:27 UTC
![3](https://cloud.githubusercontent.com/assets/26226305/23616346/23e61bb2-0292-11e7-8816-b30c5977be2d.png)

**Comment by tagliala** [comment] 2017-03-06 17:02
@pekpyt1 since lightbulb-o and circle-o are available, please consider the stacking feature: http://fontawesome.io/examples/#stacked

Please also consider a pure css solution

**Comment by sensibleworld** [comment] 2024-07-11 20:08
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/13672)

**Closed by sensibleworld** 2024-07-11 20:08 UTC
Labels: new icon, web application icons (legacy category), Duplicate
