### ISSUE TITLE
Icon Request: fa-grouping

### ISSUE THREAD

**Issue by Denni007** [FortAwesome/Font-Awesome#6614] opened 2015-06-01 13:09 UTC
To symbolise the action to group objects e. g. two images or image and text-module

**Comment by tagliala** [comment] 2015-06-07 13:15
could you please provide an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

There is a request for galleries: #855

**Comment by Denni007** [comment] 2015-06-08 07:57
Objects like that:
https://www.iconfinder.com/icons/308001/shapes_icon#size=128
with an outline of that:
https://www.iconfinder.com/icons/294915/resize_scale_size_icon#size=512

Perhaps a combination of a text-icon, an image-icon and a triangle with a border around to represent the group. Imagine you have in photoshop image objects and text objects and you want to resize or move them as group. To create the group I need an meaningful icon

**Comment by Denni007** [comment] 2015-06-08 08:18
![image](https://cloud.githubusercontent.com/assets/6861243/8030512/bb803b7c-0dc7-11e5-8492-66644592a9e6.png)

**Comment by tagliala** [comment] 2015-06-08 09:16
Duplicate of #4951, please +1 that request

closing here

**Closed by tagliala** 2015-06-08 09:16 UTC
Labels: waiting for feedback
