### ISSUE TITLE
Icon request: eventbrite

### ISSUE THREAD

**Issue by ctxkovalan** [FortAwesome/Font-Awesome#13571] opened 2018-07-19 00:06 UTC
### What can it be used for?

This can be used to link to an organiser page. 

### Example image (optional)

You can take a look at their favicon (https://www.eventbrite.co.uk/favicon.ico) and make a couple of variations. E.g: The letter E with and without the background.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-19 10:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #428, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-19 10:39 UTC

**Comment by ctxkovalan** [comment] 2018-07-19 11:34
Sorry about that, I searched your website rather than GitHub itself.

---- On Thu, 19 Jul 2018 11:40:28 +0100 notifications@github.com wrote ----

Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #428, please add a 👍 reaction to that request.

Please make sure you search existing requests before opening new ones

Closing here

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
Email Disclaimer

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this email. You cannot use or forward any attachments in the email. Please notify the sender immediately by email if you have received this email by mistake and delete this email from your system.
