### ISSUE TITLE
Icon Request: fa-location

### ISSUE THREAD

**Issue by webdevninja** [FortAwesome/Font-Awesome#7385] opened 2015-09-03 23:20 UTC
So there's this thing on google maps where its the icon that you press to get your location and its like a circle with four lines set across.
![screenshot](https://cloud.githubusercontent.com/assets/14117763/9673292/d70e4c38-5270-11e5-9c21-5e79ae39793a.png)

**Comment by tagliala** [comment] 2015-09-13 12:07
duplicate of #560 , please +1 that request

closing here

**Closed by tagliala** 2015-09-13 12:07 UTC
