### ISSUE TITLE
Icon request: fa-quantity

### ISSUE THREAD

**Issue by byebyeJohn** [FortAwesome/Font-Awesome#6948] opened 2015-07-14 08:23 UTC
I would like to use a quantity icon. Probably the # would already be sufficient. I can use this to indicate the quantity of products left on my webshop.

**Comment by tagliala** [comment] 2015-07-26 13:41
duplicate of #1123, scheduled for 5.0.0 but please +1 that request

closing here

**Closed by tagliala** 2015-07-26 13:41 UTC
