### ISSUE TITLE
Icon request: penguin

### ISSUE THREAD

**Issue by si458** [FortAwesome/Font-Awesome#14158] opened 2018-10-22 13:14 UTC
### What can it be used for?

for zoo websites with lots of different penguins/animals

### Example image (optional)

https://png.icons8.com/windows/1600/pinguin.png

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-10-22 14:16
duplicate of #14157

**Closed by tagliala** 2018-10-22 14:16 UTC
