### ISSUE TITLE
Icon Request: fa-discord

### ISSUE THREAD

**Issue by SeGirardot** [FortAwesome/Font-Awesome#11501] opened 2017-09-08 07:21 UTC
Hello :)

Could you add a Discord icon under the "Brand Icons" category please ?

Here is a preview [Discord](https://camo.githubusercontent.com/5a3b831c5896aa1e9bf719029b2911e9476a6751/687474703a2f2f692e696d6775722e636f6d2f74796f764963652e706e67)

Thank you very much for your attention :)

**Comment by tagliala** [comment] 2017-09-08 08:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-08 08:23 UTC
