### ISSUE TITLE
Icon request: fa-tracking

### ISSUE THREAD

**Issue by abhimanyusingh** [FortAwesome/Font-Awesome#13590] opened 2018-07-21 02:07 UTC
I need an icon of tracking like this one.
![tracking](https://user-images.githubusercontent.com/3057450/43031122-3aee06fa-8c69-11e8-9f8f-81e3ad4ed06c.png)

Thanks!

**Comment by tagliala** [comment] 2018-07-21 12:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7068, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-21 12:48 UTC
