### ISSUE TITLE
Icon Request: icon-flowchart

### ISSUE THREAD

**Issue by vreschke** [FortAwesome/Font-Awesome#11634] opened 2017-10-16 20:34 UTC
Mainly plan to use them on pages to direct users to flowcharts.
![flowe](https://user-images.githubusercontent.com/32852540/31633914-572b0c30-b287-11e7-8039-c24797222b3d.png)
![data-workflow-icon](https://user-images.githubusercontent.com/32852540/31633984-8ba448fa-b287-11e7-9f46-6ccd18245490.png)

**Comment by tagliala** [comment] 2017-10-16 22:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7549, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-16 22:02 UTC
