### ISSUE TITLE
Icon Request: icon-line-chart-inc (alias), icon-line-chart-dec

### ISSUE THREAD

**Issue by GramThanos** [FortAwesome/Font-Awesome#11086] opened 2017-05-18 09:04 UTC
Hi, since there is an *icon-line-chart* with an increasing arrow, can we add the corresponding icon with a decreasing arrow?

*fa-line-chart-inc (alias)* will be the same with [*fa-line-chart*](http://fontawesome.io/icon/line-chart/) and
*fa-line-chart-dec* will be the one with decreasing arrow

**Comment by Cosmo326** [comment] 2019-06-02 00:16
I was thinking more of a line-chart with a small horizontal arrow for no change
<img width="81" alt="Screen Shot 2019-06-01 at 8 14 39 PM" src="https://user-images.githubusercontent.com/3832113/58755067-139eed00-84aa-11e9-923c-56545eee9dd0.png">

**Comment by tagliala** [comment] 2019-06-02 08:26
Hi,

aliases has been removed

chart-line-down is available in FA Pro 5.3.0 and newer and is a duplicate of #5193 

Please open a new request if you are interested in a straight line over a chart

Closing here

**Closed by tagliala** 2019-06-02 08:26 UTC
