### ISSUE TITLE
Icon request: Quality Control

### ISSUE THREAD

**Issue by Minikibber** [FortAwesome/Font-Awesome#10423] opened 2016-12-22 12:04 UTC
![nellcor-quality-icon](https://cloud.githubusercontent.com/assets/24714037/21425063/13a3603c-c847-11e6-9f7f-22cf5c1a8bdd.png)
![quality-check-icon](https://cloud.githubusercontent.com/assets/24714037/21425064/13a4f384-c847-11e6-82ac-9851428e2224.png)

**Comment by tagliala** [comment] 2016-12-22 13:46
Duplicate of #773, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-22 13:46 UTC
