### ISSUE TITLE
Icon request: ios-share-icon

### ISSUE THREAD

**Issue by seiler108** [FortAwesome/Font-Awesome#14957] opened 2019-04-29 20:16 UTC
### What can it be used for?

iOS 7+ style share icon (square with straight arrow from top). For Apple specific platfroms (iOS and MacOS) It is a single icon. Looks like one or two requests have been made for this but haven't seen any updates regarding this issue since 2014. Thanks FontAwesome!

This could also just be updating the current "share" icon to align with the newer iOS 7+ and MacOS style.

### Example image (optional)

![Screen Shot 2019-04-29 at 3 10 48 PM](https://user-images.githubusercontent.com/37448021/56923839-2714fd80-6a91-11e9-91c9-d4a689409fdd.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-04-29 21:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10619, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-29 21:11 UTC
