### ISSUE TITLE
Icon request: hand-wave

### ISSUE THREAD

**Issue by idoshkedi** [FortAwesome/Font-Awesome#15061] opened 2019-05-25 09:51 UTC
A hand waving hello or goodbye - the most useful hand icon (surely more than hand-rock, hand-paper, hand-scissors and hand-lizard), is still missing from FA. Please add it!

**Comment by tagliala** [comment] 2019-05-25 09:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13687, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-05-25 09:52 UTC

**Comment by geigel** [comment] 2020-09-24 00:21
How in gods name is "wave" _**STILL**_ not part of the set?
