### ISSUE TITLE
Icon request: fa-friends

### ISSUE THREAD

**Issue by akashpinnaka** [FortAwesome/Font-Awesome#9916] opened 2016-09-15 08:43 UTC
Hello

This is to request you for the icon which refers to group of friends. ex: facebook friends button.

Thanks
Akash Pinnaka

**PS: Thanks for**_t_ **awsome icons**

**Comment by tagliala** [comment] 2016-09-15 10:01
Duplicate of #2883 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-15 10:01 UTC

**Comment by akashpinnaka** [comment] 2016-09-16 10:09
Thanks for pointing this. :) I added the reaction
