### ISSUE TITLE
Icon request - fa-network - fa-internet

### ISSUE THREAD

**Issue by Shad0wGeneral** [FortAwesome/Font-Awesome#9159] opened 2016-05-10 05:06 UTC
Hi just want to request an icon based on the RJ45 Connector.

http://www.veryicon.com/icon/ico/System/Icons8%20Metro%20Style/Ethernet%20Ethernet%20off.ico

http://www.iconsplace.com/icons/preview/white/rj45-256.png

**Comment by tagliala** [comment] 2016-05-10 16:55
Duplicate of #2565, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-10 16:55 UTC
