### ISSUE TITLE
Icon Request: Mouse Click

### ISSUE THREAD

**Issue by danskionline** [FortAwesome/Font-Awesome#1740] opened 2013-08-08 18:01 UTC
Hey Dave,

I think that would be nice, although icon-hand-up works too, in a way.

Cheers.

**Comment by aethior** [comment] 2016-07-08 20:31
Checking Google Images one of the proposed images is `fa-hand-pointer-o` (http://fontawesome.io/icon/hand-pointer-o/). Without an example is difficult know what is the proposed icon exactly.

@tagliala What do you think about this?

**Comment by tagliala** [comment] 2016-07-08 20:42
yes, or we could consider this a duplicate of #2376

**Closed by tagliala** 2016-07-08 20:42 UTC
Labels: new icon, web application icons
