### ISSUE TITLE
Icon Request: fa-textbox

### ISSUE THREAD

**Issue by mikethedj4** [FortAwesome/Font-Awesome#5328] opened 2015-01-03 21:15 UTC
![textbox-icon](https://cloud.githubusercontent.com/assets/2473707/5603786/62d1808a-935b-11e4-9966-6c180f53d309.png)

I'm working on a web design application for touch users. I love using Font-Awesome for my apps and I noticed when it comes to html element components there's only a few to choose from and some elements like buttons, select element, textbox's, textarea's are not available. I also plan on adding moduals so users can add their twitter feed, lightbox, slider/fotorama, email, etc:

In this case I've already designed the icon for a textbox (.svg & .png). Because I enjoy using Font-Awesome I thought I'd come here and request it.

**Comment by tagliala** [comment] 2015-01-04 14:21
duplicate of #1811 , please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-01-04 14:21 UTC
