### ISSUE TITLE
Icon Request: fa-skull

### ISSUE THREAD

**Issue by parixitjani** [FortAwesome/Font-Awesome#6381] opened 2015-05-04 13:12 UTC
Some use cases
Use for ratting of scariness.
Use as list icon.
Use as image of dander
![skull-icon](https://cloud.githubusercontent.com/assets/4978655/7454035/427307f0-f28d-11e4-8c28-472300050d46.jpg)

**Comment by tagliala** [comment] 2015-05-16 20:01
duplicate of #918 , please +1 that request

closing here

**Closed by tagliala** 2015-05-16 20:01 UTC
