### ISSUE TITLE
Icon Request: fa-untappd

### ISSUE THREAD

**Issue by bbarto3** [FortAwesome/Font-Awesome#7379] opened 2015-09-03 14:55 UTC
request for shipbottombrewery.com to add an icon for Untappd (https://untappd.com/shipbottombrewery)

two bottle "cheers-ing" is their current icon. (attached)

any help would be greatly appreciated. 

thank you!
![ut_icon_32](https://cloud.githubusercontent.com/assets/14111319/9661765/377f01d0-522a-11e5-9e87-e8377bc4bc1e.png)

**Comment by tagliala** [comment] 2015-09-13 19:01
duplicate of #1971, please +1 that request

closing here

**Closed by tagliala** 2015-09-13 19:01 UTC
