### ISSUE TITLE
Icon request: fa-line

### ISSUE THREAD

**Issue by mcpe-yossi1114** [FortAwesome/Font-Awesome#9557] opened 2016-07-13 08:46 UTC

**Comment by mcpe-yossi1114** [comment] 2016-07-13 08:47
LINE PNG logo image is here:
http://line.me/en/logo

**Comment by tagliala** [comment] 2016-07-13 09:31
Duplicate of #2631 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-13 09:31 UTC
