### ISSUE TITLE
Icon request: fa-openstreetmap

### ISSUE THREAD

**Issue by juanblas09** [FortAwesome/Font-Awesome#16717] opened 2020-05-25 23:24 UTC
**What can it be used for?**
The OpenStreetMap communities all around the world could use it for its website. Also it can be used in other pages that links OpenStreetMap

**Example images**
It could be a simplified version of the map and the magnifying glass for the OpenStreetMap Community.

Original: https://wiki.openstreetmap.org/wiki/File:Public-images-osm_logo.svg
Inspiration for icon: https://wiki.openstreetmap.org/wiki/File:Logo_simple.svg

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-26 06:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4317, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-26 06:39 UTC
