### ISSUE TITLE
Icon Request: fa-vero

### ISSUE THREAD

**Issue by lizneen** [FortAwesome/Font-Awesome#15581] opened 2019-09-21 00:24 UTC
Vero is a widelu used social media app. I think it would be great to create an icon for vero.co
![index](https://user-images.githubusercontent.com/55607681/65365114-9cba6b00-dbe4-11e9-90cb-6fccccc303fa.jpeg)

**Comment by tagliala** [comment] 2019-09-21 08:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12758, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-21 08:48 UTC
