### ISSUE TITLE
fa-aum

### ISSUE THREAD

**Issue by esvanr** [FortAwesome/Font-Awesome#13559] opened 2018-07-17 07:10 UTC
![om](https://user-images.githubusercontent.com/41048818/42801824-34ee8bd2-89a1-11e8-87f3-4c979acd3451.jpg)

**Comment by esvanr** [comment] 2018-07-17 07:11
Can this be made into a symbol with code fa-aum?

**Comment by tagliala** [comment] 2018-07-17 09:04
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information about this request?

Is this a brand?

What does that mean?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by tagliala** [comment] 2021-05-26 08:52
Duplicate of #3522

**Closed by tagliala** 2021-05-26 08:52 UTC
Labels: waiting for feedback
