### ISSUE TITLE
Icon request: syringe

### ISSUE THREAD

**Issue by chodaboy14** [FortAwesome/Font-Awesome#10111] opened 2016-10-24 20:51 UTC
I work in the health industry and would like a syringe icon to use as a blood collection icon.
![syringe](https://cloud.githubusercontent.com/assets/23040452/19663396/4af51012-9a98-11e6-8b48-bbd426224d7a.png)

**Comment by tagliala** [comment] 2016-10-24 21:53
Duplicate of #1779 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-24 21:53 UTC
