### ISSUE TITLE
Icon request: scooter

### ISSUE THREAD

**Issue by FrancMunoz** [FortAwesome/Font-Awesome#16737] opened 2020-05-28 14:14 UTC
**What can it be used for?**
Motorcycle icon could be improved showing a modern motorbike or scooter.

**Example image (optional)**
![istockphoto-1070585644-1024x1024](https://user-images.githubusercontent.com/8903413/83152192-d3df0580-a0fd-11ea-9b7c-7a574e1c0198.jpg)

**Icon request checklist**
- [X] This is a single icon 
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X]  The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-28 15:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6897 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-28 15:50 UTC

**Comment by FrancMunoz** [comment] 2020-05-28 15:59
Oh! I Apologize!

Thank you!

**Comment by tagliala** [comment] 2020-05-28 16:08
No problem, please post there your example
