### ISSUE TITLE
Icon Request: fa-fuel-pump

### ISSUE THREAD

**Issue by eddiegichuhi** [FortAwesome/Font-Awesome#5642] opened 2015-02-11 04:52 UTC
![fuel-pump-icon](https://cloud.githubusercontent.com/assets/5633919/6142222/853c1e02-b177-11e4-9139-2717e072c410.png)

**Comment by tagliala** [comment] 2015-02-13 00:21
duplicate of #1676 , please +1 that request

closing here

**Closed by tagliala** 2015-02-13 00:21 UTC
