### ISSUE TITLE
https://kit-free.fontawesome.com/ this site is showing up as non secure 

### ISSUE THREAD

**Issue by kaizensystech** [FortAwesome/Font-Awesome#16486] opened 2020-04-17 15:59 UTC
https://kit-free.fontawesome.com/ this site is showing up as non secure which is causing the icons failed to load

**Comment by tagliala** [comment] 2020-04-17 16:24
Thanks for reporting this, we are aware of the situation and sorry for the inconvenience

More information: https://status.fortawesome.com/

Duplicate of: #16482

**Closed by tagliala** 2020-04-17 16:24 UTC
