### ISSUE TITLE
Icon request: social-blade

### ISSUE THREAD

**Issue by xndmartins** [FortAwesome/Font-Awesome#16954] opened 2020-07-25 22:53 UTC
Use as an icon to link the status of social networks through the SocialBlade website stasts.

https://commons.wikimedia.org/wiki/File:Social_Blade_logo.svg

**Comment by tagliala** [comment] 2020-07-26 07:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15360, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-07-26 07:23 UTC
