### ISSUE TITLE
Icon request: Booksy

### ISSUE THREAD

**Issue by YallaWebDesign** [FortAwesome/Font-Awesome#19543] opened 2023-02-01 20:57 UTC
### Use case

Booksy is an online application designed to simplify the booking processes for both customers and businesses in the health and beauty industry. It comes with mobile apps that can be downloaded from the App Store and Google Play. 

### Example image

![booksy](https://user-images.githubusercontent.com/124207939/216161621-f367cf9d-e862-43b9-a726-476d86dfa602.svg)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2023-02-01 21:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15051, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-02-01 21:04 UTC
Labels: new icon
