### ISSUE TITLE
Icon Request: fa-no-smoking

### ISSUE THREAD

**Issue by ChiefNetNut** [FortAwesome/Font-Awesome#11821] opened 2017-12-01 11:15 UTC
Looking for a smoking and no smoking icon to be used on a contact form for an insurance company
![smoking1600](https://user-images.githubusercontent.com/21238216/33480637-4db2d57c-d689-11e7-995e-d3b66734aeb7.png)
![smoking_not_allowed](https://user-images.githubusercontent.com/21238216/33480638-4dce460e-d689-11e7-8fda-54d19e501429.png)

**Comment by tagliala** [comment] 2017-12-01 12:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #726 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-12-01 12:37 UTC
