### ISSUE TITLE
Icon Request: fa-workflow

### ISSUE THREAD

**Issue by thiazzz** [FortAwesome/Font-Awesome#7646] opened 2015-10-09 15:28 UTC
Useful for indicating a workflow in a website or app

**Comment by caduvieira** [comment] 2015-10-09 17:14
Dupe of #3576 ?

**Comment by thiazzz** [comment] 2015-10-09 17:23
I was thinking of something like this:
http://www.cdevworkflow.com/wp-content/uploads/2011/06/workflow-1.png?d7ea3f

Or
https://mglearns.wikispaces.com/file/view/workflow.jpg/423368716/workflow.jpg

**Comment by tagliala** [comment] 2015-10-10 18:56
duplicate of #3576, please +1 that request and post there your examples

please also consider using sitemap: http://fortawesome.github.io/Font-Awesome/icon/sitemap/

**Closed by tagliala** 2015-10-10 18:56 UTC
