### ISSUE TITLE
add please icon komoot

### ISSUE THREAD

**Issue by snagovskiy** [FortAwesome/Font-Awesome#16718] opened 2020-05-26 06:09 UTC
add please icon komoot (https://www.komoot.com). Thanks!

**Comment by tagliala** [comment] 2020-05-26 06:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15242, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-26 06:39 UTC
