### ISSUE TITLE
Icon request: icon-booking

### ISSUE THREAD

**Issue by pcha** [FortAwesome/Font-Awesome#10073] opened 2016-10-15 23:50 UTC
Booking.com is an online accommodation booking website.
I need insert a link to my booking.com profile in a webpage.
This is the icon:
![booking](https://cloud.githubusercontent.com/assets/10269965/19414105/06fbc814-9319-11e6-8fbc-e265317915fb.png)

**Comment by tagliala** [comment] 2016-10-16 10:13
Duplicate of #5257, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-16 10:13 UTC
