### ISSUE TITLE
Icon request: icon-plug-slash

### ISSUE THREAD

**Issue by shanipreempt** [FortAwesome/Font-Awesome#14733] opened 2019-03-11 09:59 UTC
### What can it be used for?
Represents as unplugged, disable, not connected

### Example image (optional)
![image](https://user-images.githubusercontent.com/48435993/54115273-d53aea00-43f4-11e9-8f5d-df61790636a1.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-03-11 10:33
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/13/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by tagliala** [comment] 2019-06-07 14:26
Oh, that's a duplicate of #14434

**Closed by tagliala** 2019-06-07 14:26 UTC
Labels: new icon, web application icons
