### ISSUE TITLE
Icon Request:  weather icon

### ISSUE THREAD

**Issue by baykorhan** [FortAwesome/Font-Awesome#8960] opened 2016-04-12 12:18 UTC
Hi,

weather icon set is very poor.. This is forcing us to use another font icon set.

Thank you.

**Comment by PeterShaggyNoble** [comment] 2016-04-12 13:56
Dupe of [#155](https://github.com/FortAwesome/Font-Awesome/issues/155). You should +1 the icons you want there.

**Comment by tagliala** [comment] 2016-04-12 13:58
Sorry, can't leave this open.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

This is the very same use case described in the Customization wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application) our suggestion is to customize Font Awesome.

I suggest you to customize font awesome

Closing here

**Closed by tagliala** 2016-04-12 13:58 UTC
