### ISSUE TITLE
Icon Request : icon-cot

### ISSUE THREAD

**Issue by darrenin1** [FortAwesome/Font-Awesome#10623] opened 2017-02-06 11:37 UTC
We build websites for Hotels and we would use icons for facilities. So a cot for the room for example.

**Comment by aethior** [comment] 2022-05-20 01:29
Duplicate of #5071?

cc/ @tagliala

**Comment by tagliala** [comment] 2022-05-20 09:50
Thanks

**Comment by tagliala** [comment] 2022-05-20 09:51
We should investigate the effort to build a bot to search for duplicates, including synonyms

**Closed by tagliala** 2022-05-20 09:50 UTC
Labels: new icon, web application icons (legacy category)
