### ISSUE TITLE
Newspaper Icon Is Not Aligned

### ISSUE THREAD

**Issue by HuizhengXu** [FortAwesome/Font-Awesome#7576] opened 2015-09-30 16:17 UTC
Newspaper icon is not aligned vertically with other icons. The lean height of the icon looks very standard, but the icon is positioned a little bit higher than others:

![newspaper](https://cloud.githubusercontent.com/assets/6979880/10198847/e9132402-676b-11e5-83d9-8b1eade8e378.PNG)

**Comment by TheChen5** [comment] 2015-10-01 03:55
If you are using it on a website, how I do it is
`` <span style="vertical-align:-2px;"><i class="fa fa-newspaper-o"></i></span>``
Every icon font isn't perfect.

**Comment by HuizhengXu** [comment] 2015-10-01 04:22
Thanks for the solution. 

Spotted it accidentally and thought it seems like an easy fix, so I might as well post it just to calm my OCD.

**Comment by TheChen5** [comment] 2015-10-01 04:36
Glad you're satisfied with it (I think...)
I have to use the ``vertical-align`` many times for icons. Font Awesome, Google icons, all icons have this problem.

**Comment by tagliala** [comment] 2015-10-01 08:01
I want to take a deeper look at this issue

**Comment by tagliala** [comment] 2016-10-01 15:18
The problem is that this icon has an odd height. It could be slightly improved, but I cannot solve this issue. Newspaper is not the only icon having this problem, there's a lack of uniformity in icon size.

btw... assigning this to Dave and adding to 5.0.0 milestone

**Comment by tagliala** [comment] 2016-10-03 22:57
Ref: #9563

**Comment by tagliala** [comment] 2017-12-17 13:17
https://jsfiddle.net/tagliala/tgzouajm/20/

Seems fixed to me

**Closed by tagliala** 2017-12-17 13:17 UTC
Labels: enhancement, web application icons
