### ISSUE TITLE
Icon request: gog-store

### ISSUE THREAD

**Issue by darrius1923** [FortAwesome/Font-Awesome#16763] opened 2020-06-02 18:18 UTC
**What can it be used for?**
The icons could be used on websites related to video games, either to show what platform they are available on or that the icon works as a link to reach the required website
**Example image (optional)**
https://es.wikipedia.org/wiki/GOG.com

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-04-11 22:14
Duplicate of #8925.

cc/ @tagliala

**Closed** 2022-04-12 09:14 UTC
Labels: brand icon
