### ISSUE TITLE
Icon request: icon-NFC

### ISSUE THREAD

**Issue by Nathanael-design** [FortAwesome/Font-Awesome#17023] opened 2020-08-11 13:04 UTC
**What can it be used for?**
Near Field Communication icon

**Icon request checklist**
- This is a single icon 

[Logo-nfc.zip](https://github.com/FortAwesome/Font-Awesome/files/5056818/Logo-nfc.zip)

Nathanaël Perrin - Designer

**Comment by tagliala** [comment] 2020-08-11 13:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1695, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-08-11 13:19 UTC
