### ISSUE TITLE
Icon Request: fa-moneybag

### ISSUE THREAD

**Issue by rwb196884** [FortAwesome/Font-Awesome#10949] opened 2017-04-15 13:34 UTC
This sort of thing.
<img src="http://simpleicon.com/wp-content/uploads/money-bag-2.png">

Maybe `fa-sokoban`?!

**Comment by tagliala** [comment] 2017-04-15 13:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1414, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-15 13:45 UTC
