### ISSUE TITLE
Icon Request: fa-cc-interac

### ISSUE THREAD

**Issue by jmadore** [FortAwesome/Font-Awesome#11556] opened 2017-09-25 13:48 UTC
Interac is the Canadian debit scheme.
It is very common to include Interac in any payments related interface.

![image](https://user-images.githubusercontent.com/7064917/30811587-a2c632f8-a1d6-11e7-93f6-591f56e4b30f.png)

**Comment by timtjtim** [comment] 2017-09-26 15:46
Is it similar to Visa / Mastercard?

**Comment by jmadore** [comment] 2017-09-26 16:13
Yes, except is Debit only ( money comes out of your bank account immediately)

https://en.m.wikipedia.org/wiki/Interac

**Comment by timtjtim** [comment] 2017-09-26 16:29
+1 thrn

**Comment by Cat5TV** [comment] 2017-11-02 17:27
Duplicate 4445

**Comment by tagliala** [comment] 2018-04-07 17:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4445, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-07 17:28 UTC
Labels: brand icon, payment icons

**Comment by Cat5TV** [comment] 2018-04-07 17:40
@tagliala the issue you link to is for fa-interac. This issue (the one you closed) is for fa-cc-interac. It's my opinion that this one (fa-cc-interac) is correct, and not the other. The designation should be fa-cc-interac, **not** fa-interac.

**Comment by timtjtim** [comment] 2018-04-07 18:14
I don’t think the specific name matters in this case - it’s asking for the same icon, right?
