### ISSUE TITLE
Icons are not loading at fontawesome.com

### ISSUE THREAD

**Issue by itslukej** [FortAwesome/Font-Awesome#16483] opened 2020-04-17 15:21 UTC
**Describe the bug**
Icons on https://fontawesome.com/icons?d=gallery are not loading. Chrome devtools shows that https://use.fortawesome.com/349cfdf6.js and others have a certificate error

```
$ curl https://use.fortawesome.com/349cfdf6.js
curl: (51) SSL: no alternative certificate subject name matches target host name 'use.fortawesome.com'
```

**To Reproduce**
Visit https://fontawesome.com/icons?d=gallery

**Expected behavior**
The icons should load

**Screenshots**
![image](https://user-images.githubusercontent.com/8759737/79585034-1fe26780-80c7-11ea-8d58-4fd7d952175d.png)

**Version and implementation** 
Browser and version: Google Chrome | 81.0.4044.113 (Official Build) (64-bit) (cohort: 81_Win_92)

- [x] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by vishnu-dev** [comment] 2020-04-17 15:24
Duplicate of #16482

**Comment by SuperCC25** [comment] 2020-04-17 15:33
Same, icons not loading as of now. Certificate seems expired.
![bug](https://user-images.githubusercontent.com/62890467/79586494-2fe65100-809f-11ea-96b3-b79a735c3e89.png)

**Comment by vidguy** [comment] 2020-04-17 15:44
Same here.

**Comment by tagliala** [comment] 2020-04-17 15:49
Thanks for reporting this, we are aware of issues on the CDN :(

https://status.fortawesome.com/

**Closed by tagliala** 2020-04-17 15:49 UTC
