### ISSUE TITLE
is  fa-wikipedia-w properly sized

### ISSUE THREAD

**Issue by kmcintyre** [FortAwesome/Font-Awesome#8221] opened 2015-12-26 07:08 UTC
Below is a snippet of my...I've got a bunch of nav elements with css before.  The other styles line up width and height.  Any reason why wikipedia is just so much bigger?  I can small it down but then height alignment breaks.

Cheers.

nav.twitter::before {
    color: #55acee;
    font-family: FontAwesome;
    content: "\f099";
    font-size: 24px;
}
nav.wikipedia::before {
    font-family: FontAwesome;
    content: "\f266";
    font-size: 16.5px;
}
nav.url::before {
    font-family: FontAwesome;
    content: "\f0c1";
    font-size: 24px;
}
nav.instagram::before {
    color: #3f729b;
    font-family: FontAwesome;
    content: "\f16d";
    font-size: 24px;
}  
nav.facebook::before {
    color: #3b5998;
    font-family: FontAwesome;
    content: "\f230";
    font-size: 24px;
}
nav.linkedin::before {
    color: #0077b5;
    font-family: FontAwesome;
    content: "\f08c";
    font-size: 24px;
}
nav.angelco::before {
    font-family: FontAwesome;
    content: "\f209";
    font-size: 24px;
}
nav.pinterest::before {
    color: #bd081c;
    font-family: FontAwesome;
    content: "\f0d2";
    font-size: 24px;
}

**Comment by tagliala** [comment] 2015-12-26 18:36
Fiddle: https://jsfiddle.net/tagliala/syduuue9/3/

**Comment by kmcintyre** [comment] 2015-12-26 19:43
Okay - so not everything is perfectly square.  But can we say wikipedia is poorly sized?
https://jsfiddle.net/syduuue9/8/

**Comment by tagliala** [comment] 2015-12-26 19:54
What I can do is assign this issue to milestone 5.0.0 so dave will take a look

**Comment by kmcintyre** [comment] 2015-12-26 20:01
Quick question.  I would think "squarish" behavior would be the goal.  I understand something like fa-facebook is much thinner by design so it isn't mandatory.  But elements that are 26x28 could be  candidates to square.

**Comment by adelriosantiago** [comment] 2016-05-07 03:41
+1 A bit oversized, yes

![cattura](https://cloud.githubusercontent.com/assets/5462382/15090038/c0f94256-13ca-11e6-8abe-e112aee56efd.PNG)

**Comment by knoxyouout** [comment] 2016-05-11 15:54
![wiki icon misaligned](https://cloud.githubusercontent.com/assets/6611709/15187365/d763906c-176e-11e6-872d-7e2a9052736b.png)

Issues with vertical alignment as well.

**Comment by tagliala** [comment] 2016-05-11 16:52
@knoxyouout please use `fa-fw` for the above use case. Icons in font awesome have not the same width by design choice

https://jsfiddle.net/tagliala/vs1qm5jL/1/

**Comment by tagliala** [comment] 2017-12-17 13:38
I think this is fixed

FA4: https://jsfiddle.net/tagliala/tgzouajm/24/
FA5: https://jsfiddle.net/tagliala/tgzouajm/24/

**Closed by tagliala** 2017-12-17 13:38 UTC
Labels: brand icons, enhancement
