### ISSUE TITLE
Icon request: CSharp

### ISSUE THREAD

**Issue by DevidCIC** [FortAwesome/Font-Awesome#12121] opened 2018-01-17 14:17 UTC
The language is very popular. A Use case would be to indicate that some features are very specific to this language. 

![csharp](https://user-images.githubusercontent.com/26143044/35047119-507c5bc2-fb99-11e7-964e-624fb83e3394.jpg)

**Comment by tagliala** [comment] 2018-01-17 14:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8365, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-17 14:30 UTC
