### ISSUE TITLE
Icon request: Palm Tree

### ISSUE THREAD

**Issue by rodlowe** [FortAwesome/Font-Awesome#13736] opened 2018-08-08 22:45 UTC
### What can it be used for?

Travel, vacations, beaches

### Example image (optional)

Sample purloined from competitor
![palm_tree](https://user-images.githubusercontent.com/9307446/43868341-c5f81e98-9b32-11e8-8746-9addda9bccb9.png)

### Icon request checklist

- [single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-09 07:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7640, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-09 07:26 UTC
