### ISSUE TITLE
npm icon

### ISSUE THREAD

**Issue by ozluy** [FortAwesome/Font-Awesome#9105] opened 2016-05-03 13:19 UTC
Would be nice if you create an NPM icon

**Comment by tagliala** [comment] 2016-05-03 13:20
Duplicate of #2584, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-03 13:20 UTC
