### ISSUE TITLE
Icon Request: fa-t-shirt

### ISSUE THREAD

**Issue by Adrien972** [FortAwesome/Font-Awesome#9220] opened 2016-05-15 15:25 UTC
I am developing a online clothes store in which I need icons related to clothes please 
![glyphicons-284-t-shirt](https://cloud.githubusercontent.com/assets/16823108/15275054/bc030d7e-1a8f-11e6-8a1a-e98663eb82ba.png)
.

**Comment by tagliala** [comment] 2016-05-15 15:26
Duplicate of #715 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-15 15:26 UTC
