### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by thierrybu** [FortAwesome/Font-Awesome#14265] opened 2018-11-12 16:09 UTC
I want to request for make a icon for skiing
![ski_1310494](https://user-images.githubusercontent.com/44977275/48359661-b7a38100-e69d-11e8-9920-d5ecb0927ce2.png)

**Comment by tagliala** [comment] 2018-11-12 20:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6878 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-11-12 20:59 UTC
