### ISSUE TITLE
Icon request: reset password

### ISSUE THREAD

**Issue by inland-rob** [FortAwesome/Font-Awesome#17262] opened 2020-10-12 19:40 UTC
**What can it be used for?**
 When a systems admin wants to send a reset password email/text to a user

**Example image (optional)**
Could be the key icon you already have with a circle arrow overlay
fa-undo and fa-lock individually don't convey the message. 
However, fa-key + fa-undo (but reversed to be clockwise) could work to get the message across.
Seems others have similar request going back 3 years.

**Icon request checklist**
- [✓] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [✓] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✓] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✓] I have included at least one example image if it could be helpful (optional)
- [✓] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-10-12 19:44
Hi!

Thanks for being part of the Font Awesome Community.

> Seems others have similar request going back 3 years.

This request is a duplicate of #10516, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-10-12 19:44 UTC

**Comment by inland-rob** [comment] 2020-10-12 20:08
It's been 3 years, can this icon be prioritized higher?
Surely things can move faster for people who pay for FA.
Thanks.

**Comment by tagliala** [comment] 2020-10-12 20:28
> It's been 3 years, can this icon be prioritized higher?

Please take a look here: https://fontawesome.com/community/leaderboard/new#faqs
