### ISSUE TITLE
Icon Request: fa-signature

### ISSUE THREAD

**Issue by JD-Robbs** [FortAwesome/Font-Awesome#10164] opened 2016-11-04 13:37 UTC
Hello lovely people!

I'm proposing `fa-signature` - just to see if there is any appetite among the community.

### Examples:
- https://upload.wikimedia.org/wikipedia/commons/a/a0/WikiFont_signature_icon.svg
- https://www.iconfinder.com/icons/181722/sign_signature_icon
- https://www.iconfinder.com/icons/515481/autograph_handwritten_sign_signature_icon#size=128
- https://www.iconfinder.com/icons/536629/agreement_agreement_signature_agreement_signing_contract_contract_signing_icon#size=128

### Use Cases:
- Acceptance of contracts/T&Cs/etc.
- e-signing/digital signatures

**Comment by tagliala** [comment] 2016-11-04 13:52
Duplicate of #5663 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-04 13:52 UTC

**Comment by JD-Robbs** [comment] 2016-11-04 14:30
Should've searched `issues` and not the repo itself - duh! 

Thanks!

**Comment by tagliala** [comment] 2016-11-04 16:29
@JD-Robbs no problem, you're welcome
