### ISSUE TITLE
Icon Request: fa-cc-maestro

### ISSUE THREAD

**Issue by webpeople** [FortAwesome/Font-Awesome#7537] opened 2015-09-25 06:05 UTC
I think this icon is urgently needed in addition to Visa, MasterCard and Amex.

![index](https://cloud.githubusercontent.com/assets/14832580/10094124/2c408f3a-635c-11e5-9b9d-ffffc69716e9.jpg)

**Comment by tagliala** [comment] 2015-09-25 14:25
refers to #4266

**Comment by aplaceforallmystuff** [comment] 2015-12-15 20:02
+1

**Comment by Hoolite** [comment] 2016-06-28 07:20
+1

**Comment by dynamicsites** [comment] 2016-07-08 06:52
+1

**Comment by tagliala** [comment] 2016-10-27 16:20
fff

Duplicate of #4266, please 👍 that request

**Closed by tagliala** 2016-10-27 16:20 UTC
Labels: new icon, payment icons

**Comment by mrjamiebowman** [comment] 2018-02-19 20:29
+1
