### ISSUE TITLE
Icon Request: fa-package

### ISSUE THREAD

**Issue by heichner** [FortAwesome/Font-Awesome#11708] opened 2017-11-03 08:30 UTC
A package or a parcel.
similar to e.g.  http://www.iconarchive.com/show/windows-8-icons-by-icons8/Business-Package-icon.html

**Comment by tagliala** [comment] 2017-11-03 10:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #908 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-03 10:23 UTC
