### ISSUE TITLE
Icon Request - fa-bible

### ISSUE THREAD

**Issue by meirinaldojunior** [FortAwesome/Font-Awesome#10193] opened 2016-11-10 01:38 UTC
make an icon format bible. please!

**Comment by tagliala** [comment] 2016-11-10 10:04
Duplicate of #8123, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-10 10:04 UTC
