### ISSUE TITLE
Icon Request: fa-voucher

### ISSUE THREAD

**Issue by ptahchiev** [FortAwesome/Font-Awesome#9130] opened 2016-05-05 16:20 UTC
Something in the likes of:

https://cdn0.iconfinder.com/data/icons/everyday-objects-line-art-1/128/gift-card-128.png

**Comment by tagliala** [comment] 2016-05-05 16:22
Duplicate of #8692 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-05 16:22 UTC

**Comment by ptahchiev** [comment] 2016-05-05 16:24
Sorry.. I searched for voucher and coupon.
