### ISSUE TITLE
Icon request: Google Blogger.com icon

### ISSUE THREAD

**Issue by mmjaeger** [FortAwesome/Font-Awesome#8750] opened 2016-03-14 14:22 UTC
Hello
any chance that the blogger icon gets added any time soon.

Thank you

**Comment by tagliala** [comment] 2016-03-14 14:24
duplicate of #1088 , please +1 that request

closing here

**Closed by tagliala** 2016-03-14 14:24 UTC

**Comment by mmjaeger** [comment] 2016-03-14 15:08
adding +1 to that issue doesn't seem to do much as this has been a request
for 3 years

On Mon, Mar 14, 2016 at 7:25 AM, Geremia Taglialatela <
notifications@github.com> wrote:

> Closed #8750 <https://github.com/FortAwesome/Font-Awesome/issues/8750>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/8750#event-588771535>.
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by tagliala** [comment] 2016-03-14 16:09
Sorry, I need to keep track of issues and having a duplicate will not help

Please take a look here if you need this icon in a short while: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
