### ISSUE TITLE
Icon Request: fa-books

### ISSUE THREAD

**Issue by samuelbradshaw** [FortAwesome/Font-Awesome#8563] opened 2016-02-14 07:18 UTC
I'm looking for an icon of multiple books lined up on a shelf. This is for a link to a contents menu where several books are listed. It could also be used in a library/bookstore context.
I'm envisioning something roughly like this (attached):
![books](https://cloud.githubusercontent.com/assets/7323052/13032449/77b1ef7c-d2b0-11e5-8c47-957ab51f2ce9.png)

**Comment by tagliala** [comment] 2016-02-14 12:49
duplicate of #5098, please +1 that request

closing here

**Closed by tagliala** 2016-02-14 12:49 UTC
