### ISSUE TITLE
Icon Request: fa-preview, or fa-quickview

### ISSUE THREAD

**Issue by Sayant** [FortAwesome/Font-Awesome#8133] opened 2015-12-09 22:36 UTC
I need an icon to indicate a "quick view" on a document versus opening it in a new page, and don't see anything existing or requested that quite matches... some print preview icon suggestions come close, but still they don't exist yet...

Maybe https://github.com/FortAwesome/Font-Awesome/issues/640 but not quite..? (almost 3 years old now... but I +1'd it)

Include a few use cases for your requested icon. How do you plan on using it?
- To explicitly indicate that the user can preview, or quick-view on an item to see data
- Can also be used as a "print preview" icon, or "details" icon

Attach a single color image or two that represent the idea you're going for.

![quickview-icon](https://cloud.githubusercontent.com/assets/15697093/11701027/3b90be18-9e9b-11e5-83c6-4f99964d43c4.png)

**Comment by tagliala** [comment] 2015-12-10 11:47
closing as a duplicate of #640

**Closed by tagliala** 2015-12-10 11:47 UTC
