### ISSUE TITLE
Icon Request: fa-icon-microtube

### ISSUE THREAD

**Issue by darnassiano** [FortAwesome/Font-Awesome#11448] opened 2017-08-27 15:30 UTC
I would like to request an icon that depicts a laboratory microcentrifuge tube. It will be used for a Biotech startup webpage and laboratory products. It can also be used for general purpose in medicine, chemistry, molecular biology and science research.

I made the vector for the icon using your scheme:

![g4389-gray](https://user-images.githubusercontent.com/18491554/29751397-70a47c6a-8b12-11e7-85f7-0428e43af708.png)

**Comment by tagliala** [comment] 2017-08-27 22:39
Hi!

Thanks for being part of the Font Awesome Community.

Could this be considered a duplicate of #6825 ?

**Comment by timothymillar** [comment] 2017-09-21 05:07
+1 
I would say that the proposed [fa-testtube](#6825) is more of a duplicate of [fa-flask](http://fontawesome.io/icon/flask/) than this is a duplicate of fa-testtube.

Microtubes are very general purpose e.g. storing samples in freezers. A test tube is much more specific to an active experiment.

**Comment by rmwthorne** [comment] 2018-04-27 08:56
@darnassiano can you upload the vector and license it CC BY 4.0 License, please?

**Comment by sensibleworld** [comment] 2024-07-12 17:50
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-12 17:50 UTC
Labels: waiting for feedback
