### ISSUE TITLE
Icon request: Epic Games

### ISSUE THREAD

**Issue by danzo12345** [FortAwesome/Font-Awesome#19958] opened 2023-10-19 09:25 UTC
Lots of other gaming platforms already have their icons uploaded. Could we also get one for Epic Games Store created :)

**Comment by tagliala** [comment] 2023-10-19 09:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13724, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-10-19 09:33 UTC
