### ISSUE TITLE
Icon Request: fa-x-ray

### ISSUE THREAD

**Issue by alajarrah** [FortAwesome/Font-Awesome#11725] opened 2017-11-08 11:15 UTC
radiography section icon

xray sign:
https://www.google.jo/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwii17uA7K7XAhUIchQKHZRZA38QjRwIBw&url=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2Fradiology%2Bicon&psig=AOvVaw0YqY-uEdtwZ3S85saGqoaN&ust=1510225844090367

or xray photo:
https://www.google.jo/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjslZbg7K7XAhWDPRQKHZhvBnUQjRwIBw&url=http%3A%2F%2Fwebmail.vfa-foto.com%2Findex.php%3Fstock%3Ddepositphotos%26search%3Dradiology&psig=AOvVaw0YqY-uEdtwZ3S85saGqoaN&ust=1510225844090367

**Comment by PeterShaggyNoble** [comment] 2017-11-08 11:49
This is a duplicate of #681; you should give that a 👍 instead.

**Closed** 2017-11-08 12:02 UTC
