### ISSUE TITLE
Icon Request: icon-douban

### ISSUE THREAD

**Issue by YuyingWu** [FortAwesome/Font-Awesome#5339] opened 2015-01-05 03:54 UTC
![douban](https://cloud.githubusercontent.com/assets/7309680/5609079/908a4ada-94d1-11e4-88b7-bbf56c7a467e.png)

[Douban](http://www.douban.com) is a Chinese SNS website, which has 1 billion registered users.

This is [Douban's wiki](http://en.wikipedia.org/wiki/Douban).

I love fontAwesome, it has icons of Chinese SNS website, like icon-weibo and icon-weixin, I really want icon-douban as well, thank you ：）

I've already prepared a icon, if it's not perfect, please see [developer of douban](http://developers.douban.com/wiki/?title=resource).

**Comment by tagliala** [comment] 2015-01-05 10:56
duplicate of #1841 , please +1 that request

closing here

**Closed by tagliala** 2015-01-05 10:56 UTC

**Comment by cssjidi** [comment] 2015-01-26 09:40
+1

**Comment by lanegg** [comment] 2016-04-16 02:37
+1

**Comment by tagliala** [comment] 2016-04-16 09:41
locking this duplicate
