### ISSUE TITLE
Icon Request: fa-ruler or fa-measure

### ISSUE THREAD

**Issue by anaszakaria** [FortAwesome/Font-Awesome#9978] opened 2016-09-29 04:32 UTC
Hi,

I want a to request for a ruler or any types of measuring icons, to be used for development of web applications. Thanks a lot! Cheers!
![ruler_icon](https://cloud.githubusercontent.com/assets/22513714/18941105/c73882ec-8640-11e6-8238-24e639a4ae47.png)

**Comment by tagliala** [comment] 2016-09-29 09:53
Duplicate of #1096 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-29 09:53 UTC
