### ISSUE TITLE
Icon request: fa-tunein

### ISSUE THREAD

**Issue by MikeWriting** [FortAwesome/Font-Awesome#13509] opened 2018-07-09 18:15 UTC
### What can it be used for?

TuneIn Radio host podcasts and radio stations. Creators can use the TuneIn brand icon on websites and email newsletters.  Ref. https://tunein.com/

### Example image (optional)
![tunein_2017_logo](https://user-images.githubusercontent.com/38844304/42467187-36351a10-837f-11e8-9ee9-4797f7745734.png)

I've created an SVG also.

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-09 21:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3159, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-09 21:12 UTC

**Comment by MikeWriting** [comment] 2018-07-09 22:07
Tagliala, the 4 year old request #3159 has a logo for tunein that’s no longer used.
