### ISSUE TITLE
Icon Request: fa-vevo

### ISSUE THREAD

**Issue by fmdlancian** [FortAwesome/Font-Awesome#11663] opened 2017-10-24 01:47 UTC
http://comingsoon.vevo.com/comingsoon_files/Logo.svg

**Comment by tagliala** [comment] 2017-10-24 10:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3428, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-24 10:53 UTC
