### ISSUE TITLE
Icon Request: math-symbols

### ISSUE THREAD

**Issue by jaedevonko** [FortAwesome/Font-Awesome#14337] opened 2018-11-30 19:44 UTC
I work with a company that deals with lots of data and constantly come across requests for mathematical symbols such as for function, equations, sum, etc. Many of these can be solved by latin symbol equivalencies. Attaching some images as examples. 

[function_icon.pdf](https://github.com/FortAwesome/Font-Awesome/files/2634778/function_icon.pdf)
[Greek_letter_change.pdf](https://github.com/FortAwesome/Font-Awesome/files/2634779/Greek_letter_change.pdf)
[Greek_letter_delta.pdf](https://github.com/FortAwesome/Font-Awesome/files/2634780/Greek_letter_delta.pdf)
[Greek_letter_sum.pdf](https://github.com/FortAwesome/Font-Awesome/files/2634781/Greek_letter_sum.pdf)

**Comment by tagliala** [comment] 2018-11-30 20:33
Hi!

Thanks for being part of the Font Awesome Community.

Sigma and function are available in FA 5 Pro
https://fontawesome.com/icons/function?style=solid
https://fontawesome.com/icons/sigma?style=solid

delta is a duplicate of #3764, please add a 👍 reaction to that request

Before opening a new request, please make sure that it follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2018-11-30 20:33 UTC

**Comment by jaedevonko** [comment] 2018-11-30 21:16
Thanks! I tried doing a search, but couldn't find the two existing ones.
That's great news.

Jae Ko

Director of Product Design


atscale.com <http://www.atscale.com>
