### ISSUE TITLE
Icon request: fa-golf

### ISSUE THREAD

**Issue by MarvDann** [FortAwesome/Font-Awesome#11044] opened 2017-05-09 17:53 UTC

**Comment by tagliala** [comment] 2017-05-09 17:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5348 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-09 17:56 UTC
