### ISSUE TITLE
Icon Request: fa-ballet-shoes (dance slippers)

### ISSUE THREAD

**Issue by AndrewVonGregor** [FortAwesome/Font-Awesome#7563] opened 2015-09-29 08:36 UTC
![ballet-pointe-shoes](https://cloud.githubusercontent.com/assets/14886446/10158997/5f0e843a-664a-11e5-9c19-1e7a8d9356bd.png)

**Comment by aethior** [comment] 2022-03-12 18:14
*Related Unicode Emoji* #222
🩰 [U+1FA70](https://emojipedia.org/emoji/%F0%9F%A9%B0/) Ballet Shoes
Also known as `Pointe Shoe`.


Related requests:
👠 High-Heeled Shoe https://github.com/FortAwesome/Font-Awesome/issues/3473
👟 Running Shoe https://github.com/FortAwesome/Font-Awesome/issues/3704
👞 Man’s Shoe https://github.com/FortAwesome/Font-Awesome/issues/6031
🩰 Ballet Shoes https://github.com/FortAwesome/Font-Awesome/issues/7563

**Comment by sensibleworld** [comment] 2024-07-10 21:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7564)

**Closed by sensibleworld** 2024-07-10 21:33 UTC
Labels: new icon, clothing-fashion (category), Duplicate
