### ISSUE TITLE
Icon request: fa-douban

### ISSUE THREAD

**Issue by Xuewa** [FortAwesome/Font-Awesome#3408] opened 2014-05-14 14:18 UTC
![ux_1400077001_035265](https://cloud.githubusercontent.com/assets/7582058/2972195/989857a8-db72-11e3-865b-8ad663417e0b.png)

**Comment by tagliala** [comment] 2015-04-13 22:26
closing as a duplicate of #1841, please +1 that request

**Closed by tagliala** 2015-04-13 22:26 UTC
Labels: brand icons, new icon
