### ISSUE TITLE
Icon request: icon-admin

### ISSUE THREAD

**Issue by Rubik0** [FortAwesome/Font-Awesome#12176] opened 2018-01-29 05:08 UTC
Icon for an administrator message
uses cases:
- The icon appears in the profile of the user who wrote the message
- The icon appears in the section support

It would be really helpful for one of my project.

![1](https://user-images.githubusercontent.com/35910158/35493994-36e2c50e-04d9-11e8-8b38-890caea01850.png)

**Comment by tagliala** [comment] 2018-01-29 09:21
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3397, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-29 09:21 UTC
