### ISSUE TITLE
Icon Request: non-binary

### ISSUE THREAD

**Issue by pickbreaker** [FortAwesome/Font-Awesome#17528] opened 2021-01-02 14:20 UTC
**What can it be used for?**
Expressing non-binary gender in forms, etc.

**Example image (optional)**
![Non-binary gender symbol](https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Nonbinary_Gender_Symbol.svg/1024px-Nonbinary_Gender_Symbol.svg.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-03-08 17:24
Duplicate of #17914.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-08 17:35
Ok, closing here in favor of #17914, which has more details

**Closed by tagliala** 2022-03-08 17:35 UTC
