### ISSUE TITLE
Icon Request: Macdonald Brand logo

### ISSUE THREAD

**Issue by pixieaka** [FortAwesome/Font-Awesome#14801] opened 2019-03-23 23:28 UTC
![mcdonalds_PNG17](https://user-images.githubusercontent.com/17777237/54872885-1909f800-4dd4-11e9-824b-7d47e5714a8e.png)

**Comment by tagliala** [comment] 2019-03-24 09:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4627, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-03-24 09:02 UTC
