### ISSUE TITLE
Inconsistent icon sizes: fa-trash-o, fa-thumbs-up

### ISSUE THREAD

**Issue by HousewifeHacker** [FortAwesome/Font-Awesome#10078] opened 2016-10-17 15:14 UTC
At the same font-sizes, I expect the icons to take up about the same amount of space with similar height and width. At font-size 18px, the fa-trash-o is too narrow while the fa-thumbs-up is too wide.

**Comment by tagliala** [comment] 2016-10-17 15:51
Hi, it is definitely true and I agree but Font Awesome does not use same width icons by design choice.

You can try adding `fa-fw` class to add some space around icons: https://jsfiddle.net/tagliala/4Lcpvhoo/12/

AFAIK, inconsistent sizes shuld be addressed in the 5.0.0 version but I can't find Dave's comment about this matter

Take also a look at my vector icons roundup: http://tagliala.github.io/vectoriconsroundup/

I'm going to close this one because this issue is related to a very large number of icons and it requires a whole font redesign.

REF: #1624, #7409

**Closed by tagliala** 2016-10-17 15:51 UTC
Labels: enhancement
