### ISSUE TITLE
Icon Request : fa-hitbox

### ISSUE THREAD

**Issue by valk96** [FortAwesome/Font-Awesome#9744] opened 2016-08-11 21:55 UTC
Hi,

Since there is a [twitch icon](https://www.twitch.tv/), could you add an icon for [hitbox](http://www.hitbox.tv/) please?

[#1687
](https://github.com/FortAwesome/Font-Awesome/issues/1687) [#3511](https://github.com/FortAwesome/Font-Awesome/issues/3511)

Thanks
V. Hutter

**Comment by tagliala** [comment] 2016-08-11 22:04
Duplicate of #3511, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-11 22:04 UTC
