### ISSUE TITLE
Icon request: icon-prezi

### ISSUE THREAD

**Issue by MarieLSJ** [FortAwesome/Font-Awesome#11644] opened 2017-10-18 04:10 UTC
Hi! I was wondering if there could be a Prezi icon to link to our Prezi accounts on websites designed with Hugo?

Here's the icon: 
![image](https://user-images.githubusercontent.com/32890656/31700636-b8ba210e-b398-11e7-88e3-c874831d5219.png)

Here's my [Prezi account](https://prezi.com/user/wnnx_zegj5cb/).

Thanks!

**Comment by tagliala** [comment] 2017-10-18 08:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2089 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-18 08:25 UTC
