### ISSUE TITLE
Icon Request: fa-couple

### ISSUE THREAD

**Issue by shammai** [FortAwesome/Font-Awesome#5560] opened 2015-02-02 13:18 UTC
Thanks for the great icons.
I would really like to have an icon that symbolizes a couple (i.e. husband and wife).
It would look like the person icon, but instead of 1 person it would have 2.  
It would be similar to the fa-users icon but instead of 3 people it would be 2.  I think having them overlap a little will indicate that they are one icon.
A male/female couple would be ideal.

Thanks so much for considering this addition.

**Comment by laviku** [comment] 2015-04-20 20:59
+1 
I was thinking something like this
https://cdn4.iconfinder.com/data/icons/eldorado-navigation/40/couple_2-128.png

**Comment by tagliala** [comment] 2015-04-20 21:03
oddly similar to #2670, it's almost a duplicate :grin: 

There are also: #3025

**Comment by laviku** [comment] 2015-04-20 21:05
hmm you're right, the wedding rings would be good as well.

**Comment by shammai** [comment] 2015-04-21 19:06
I was thinking about something more along the lines of:
http://www.anchorgreenpri.moe.edu.sg/qql/slot/u530/quicklinks/parent_icon.png
Obviously in just one solid color.  But the idea is a mother and father
together.

**Comment by oddityoverseer13** [comment] 2015-04-30 17:17
+1

**Comment by lyhil** [comment] 2015-08-03 10:41
+1

**Comment by caduvieira** [comment] 2015-09-16 14:08
Other examples:
http://unicode-table.com/en/#1F46B
http://unicode-table.com/en/#1F46C
http://unicode-table.com/en/#1F46D

**Comment by dkniffin** [comment] 2015-09-16 15:46
Yes @caduvieira! we should have all three of these icons added.

**Comment by mewcrazy** [comment] 2016-04-18 05:39
+1

**Comment by tagliala** [comment] 2016-04-18 09:16
Closing here as a duplicate of #4825

**Closed by tagliala** 2016-04-18 09:16 UTC
Labels: waiting for feedback

**Comment by aRBemo58** [comment] 2016-07-05 16:39
disappointed there have been request for three years and still no toilet! trying to use unicode U+1F6BD

**Comment by asarican** [comment] 2018-05-04 05:26
Hi,
Define new icon with css like this:
.fa-couple:before {
	content: "\f183\f182";
}
it prints male&female next to each other. You can name your icon name anything you want or modify existing which you didn't use.
