### ISSUE TITLE
Icon Request: fa-running

### ISSUE THREAD

**Issue by ChrisKlinglmayr** [FortAwesome/Font-Awesome#10739] opened 2017-03-04 11:51 UTC
Using it for a sports chapter on my website
![running-icon-on-transparent-background-hi](https://cloud.githubusercontent.com/assets/26183566/23578533/3b32ed5a-00d9-11e7-81c0-5d14acd6d86d.png)

**Comment by tagliala** [comment] 2017-03-04 12:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1156, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-04 12:46 UTC
