### ISSUE TITLE
Icon Request: fa-leaderboard

### ISSUE THREAD

**Issue by ClubhouseGolf** [FortAwesome/Font-Awesome#7358] opened 2015-09-01 20:12 UTC
Hi there, just sending a request in for a "leaderboard" icon. Would be used for any type of leaderboard in scoring systems.

Thanks,
Austin
![leagueleaderboard](https://cloud.githubusercontent.com/assets/10716324/9615117/3942399a-50c4-11e5-98c1-9b7a2fef9e21.png)

**Comment by casman300** [comment] 2015-09-12 11:27
+1

**Comment by tagliala** [comment] 2015-09-13 09:27
This could be considered a dup of #1750

**Comment by jpsantos7** [comment] 2015-10-16 17:20
+1

**Comment by mshovelt** [comment] 2016-02-18 16:53
+1

**Comment by trubachev** [comment] 2016-08-31 14:33
+1

**Comment by aethior** [comment] 2016-10-01 21:55
> This could be considered a dup of #1750
Yes, I think you can close here and use `leaderboard` as alias in the other request.

**Comment by adimoraret** [comment] 2018-11-09 01:21
+1

**Comment by YashKumarVerma** [comment] 2020-05-19 01:13
still waitinf for feedback ?

**Comment by tagliala** [comment] 2020-05-19 09:29
This could be considered a dup of #4467

**Comment by iabduul7** [comment] 2020-07-28 07:47
+1

**Comment by Volen99** [comment] 2021-06-13 07:46
+1

**Comment by tagliala** [comment] 2021-06-13 08:04
Hi,

since I did not get a feedback with an example, I will consider this a duplicate of #4467 (sports podium), so please +1 that request.

Font Awesome itself uses [fa-trophy-alt](https://fontawesome.com/v5.15/icons/trophy-alt?style=solid), available in FA Pro, to represent its own [Leaderboard](https://fontawesome.com/community/leaderboard/new)

![image](https://user-images.githubusercontent.com/556268/121799591-4ea59080-cc2d-11eb-9abf-08af1f4c30c9.png)

Free user can use [fa-trophy](https://fontawesome.com/v5.15/icons/trophy?style=solid), or recreate fa-trophy-alt icon by combining `fa-trophy` and `fa-star`, taking advantage of the SVG Framework, [Power Transforms](https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms) and [Masking](https://fontawesome.com/how-to-use/on-the-web/styling/masking) features.

Demo: https://jsfiddle.net/tagliala/L17f528g/549/

Feel free to open a new request by filling in our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md).

For this specific use case please provide:
- A concrete object in the title
- An example
- An explanation on why the existing requests like sports-podium #4467 and existing icons like `fa-trophy` and `fa-trophy-alt` cannot be used to represent a leaderboard

Closing here

**Closed by tagliala** 2021-06-13 08:04 UTC
Labels: waiting for feedback
