### ISSUE TITLE
Fence Icon.

### ISSUE THREAD

**Issue by sammead92** [FortAwesome/Font-Awesome#11072] opened 2017-05-16 15:35 UTC
Fence icon needed for website I am building.

**Comment by tagliala** [comment] 2017-05-16 17:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10980, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-16 17:15 UTC
