### ISSUE TITLE
Icon request: dot-square (indeterminate check box)

### ISSUE THREAD

**Issue by devou33** [FortAwesome/Font-Awesome#14498] opened 2019-01-14 17:29 UTC
### What can it be used for?
Indeterminate check box

Kind of like the circle-dot, it's a square within a square. Can be done with stacking, but I would like to use the same styling that we do with Radios and circle-dot. Too complex for repeated use in replacing checkboxes.

Most web browsers use a square and not a 'minus' as Dave had suggested years ago.

### Example image (optional)

![03xd7](https://user-images.githubusercontent.com/7987602/51128351-3c6d6100-17ed-11e9-8c43-519a3b7c2d20.png)

![dot-square](https://user-images.githubusercontent.com/7987602/51129219-80616580-17ef-11e9-8765-c9b0f60d8a90.png)

### Icon request checklist

- [x] This is a single icon (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by devou33** [comment] 2019-01-28 21:41
@tagliala, can you please tag this or reject it?

**Comment by tagliala** [comment] 2019-01-28 23:01
@devou33 thanks for bringing this to my attention, and sorry because I've missed your request

This is a duplicate of #2055, please +1 that one

Closing here

**Closed by tagliala** 2019-01-28 23:01 UTC

**Comment by tagliala** [comment] 2019-01-28 23:03
maybe you've missed it because there was a typo in the title, I've fixed that
