### ISSUE TITLE
Qzone

### ISSUE THREAD

**Issue by utf6** [FortAwesome/Font-Awesome#12719] opened 2018-03-28 09:56 UTC
don't have Qzone icon

**Comment by tagliala** [comment] 2018-04-06 14:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3993, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 14:51 UTC
