### ISSUE TITLE
Icon Request: fa-follow

### ISSUE THREAD

**Issue by bjackson2016** [FortAwesome/Font-Awesome#9576] opened 2016-07-14 19:25 UTC
Used to differentiate between allowing a user to share your content and linking to your social media pages. There are many similar icons to [this one](https://thenounproject.com/term/follow/109074/) around the internet but none on Font Awesome (which is my favorite and one of the easiest ways to insert icons). I would use this Icon a lot including to replace the "share" icon in situations like [this](http://codepen.io/bjackson2016/pen/OXxYwB).

**Comment by tagliala** [comment] 2016-07-14 22:51
This is a duplicate of #1509, please take a look there

**Closed by tagliala** 2016-07-14 22:51 UTC
