### ISSUE TITLE
Icon request: whatsapp-channel

### ISSUE THREAD

**Issue by Sadam36** [FortAwesome/Font-Awesome#20037] opened 2023-12-03 02:55 UTC
![IMG_20231203_074859](https://github.com/FortAwesome/Font-Awesome/assets/113505060/2bc15cc4-4705-4a3d-bc71-895342ca2d49)

Icon request for WhatsApp Channel

**Comment by tagliala** [comment] 2023-12-03 08:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19980, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-12-03 08:25 UTC
