### ISSUE TITLE
Icon request: control-tower

### ISSUE THREAD

**Issue by corstian** [FortAwesome/Font-Awesome#14467] opened 2019-01-04 12:52 UTC
### What can it be used for?

There are use-cases in which you want to signal to the user that certain functionality is meant to take control. Like a control center, or in this case, tower.

### Example image (optional)

![image](https://user-images.githubusercontent.com/5021647/50688893-cd8f4b80-1027-11e9-9e65-ad147789751f.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-01-04 17:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8687, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-01-04 17:43 UTC

**Comment by corstian** [comment] 2019-01-04 20:11
Whoops excuse me, looked over that one...

**Comment by tagliala** [comment] 2019-01-04 22:10
@corstian do not worry! 👍
