### ISSUE TITLE
Icon request: Filter-plus

### ISSUE THREAD

**Issue by abhishekbaronia07** [FortAwesome/Font-Awesome#20493] opened 2024-12-06 13:31 UTC
![noun-add-filter-5667478](https://github.com/user-attachments/assets/caed8266-0771-40d1-be7f-30b84e6201a9)

**Comment by tagliala** [comment] 2024-12-06 14:08
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/19357#issuecomment-2225926395, please check there why this request has not been accepted (but it is possible to create this icon with FA Pro or with FA Free and stacking/layering)

**Closed as completed by tagliala** 2024-12-06 14:08 UTC
