### ISSUE TITLE
fa-telegram-square

### ISSUE THREAD

**Issue by cyclone9** [FortAwesome/Font-Awesome#13463] opened 2018-06-30 09:30 UTC
is there any chance to add telegram square icon?
tnx

**Comment by tagliala** [comment] 2018-06-30 09:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11449, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-30 09:57 UTC
