### ISSUE TITLE
Couldn't find package "@fortawesome/pro-duotone-svg-icons@^6.2.0" required by "module-name version" on the "npm" registry.

### ISSUE THREAD

**Issue by shaheryarkhan2021** [FortAwesome/Font-Awesome#19333] opened 2022-09-14 14:16 UTC
Description:
FontAwesome is added to a node module and was working fine till version 5. I updated the version to 6 due to some requirements and when I try to compile it inside the created package it works fine. But when I add the package and run `yarn install` to install that package I start receiving errors
Note: I already have a pro license and font-awesome dependencies get installed without an issue in the node module

**Comment by tagliala** [comment] 2022-09-14 14:55
~Sorry, this is a duplicate of #19312~

~Please try with 6.1.2 instead of 6.2.0, it should work~

~Please follow #19312 to be updated when the bug will be fixed~

**Comment by tagliala** [comment] 2022-09-14 14:56
Sorry, misread the bug.

Please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+)

**Closed as completed by tagliala** 2022-09-14 14:55 UTC

**Comment by shaheryarkhan2021** [comment] 2022-09-14 14:57
sure

**Comment by shaheryarkhan2021** [comment] 2022-09-14 17:40
@tagliala  issue resolved. I added the token in the parent repo and it started working. 
Thanks for your time

**Comment by shaheryarkhan2021** [comment] 2022-09-15 10:53
@tagliala I still believe this is a bug or I am making some mistake because is my application get's used as a third-party I will not be sending them my fontAwesome license key. Please have a look I have reported it as a bug
 https://github.com/FortAwesome/Font-Awesome/issues/19336
