### ISSUE TITLE
Icon Request: levels for fa-signal

### ISSUE THREAD

**Issue by monoflo** [FortAwesome/Font-Awesome#11319] opened 2017-07-22 21:50 UTC
Can you make the `fa-signal` icon have varying levels like the `fa-thermometer` and `fa-battery` icons?

With `fa-battery`, for instance, you can select between . . .
- `fa-battery-4` or `fa-battery-full`
- `fa-battery-3` or `fa-battery-three-quarters`
- `fa-battery-2` or `fa-battery-half`
- `fa-battery-1` or `fa-battery-quarter`
- `fa-battery-0` or `fa-battery-empty`

I would like to display WiFi signal strength on the Raspberry Pi application I'm building. If the RPi moves outside of the range of the WiFi network, it will stop working, so having a signal strength indicator would be extremely useful in my application. 

As the icon has five bars, I could see five or six levels for the icon. Something like . . .
- `fa-signal-5` (the current `fa-signal`)
- `fa-signal-4`
- `fa-signal-3`
- `fa-signal-2`
- `fa-signal-1`
- `fa-signal-0`

[Current `fa-signal` icon page](http://fontawesome.io/icon/signal/) &bull; [Relevant image](https://cdn1.iconfinder.com/data/icons/signal-level-2/100/Signal_black-01-41-128.png)

**Comment by tagliala** [comment] 2017-07-23 08:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1870, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-23 08:27 UTC
