### ISSUE TITLE
Icon Request: fa-usps, fa-fedex, fa-ups, fa-dhl, fa-capost, fa-royalmail, fa-delivery, fa-shipping-box

### ISSUE THREAD

**Issue by batteriesinaflash** [FortAwesome/Font-Awesome#7131] opened 2015-08-03 21:26 UTC
SHIPPING LOGO REQUEST..

fa-usps (USPS Postal Service)
fa-fedex (FedEx Service)
fa-ups (UPS Service)
fa-dhl (DHL Service)
fa-capost (Canada Postal Service)
fa-royalmail (United Kingdom Postal Service)
fa-delivery (Delivery Truck)
fa-shipping-box (Shipping Box)

Shipping Logos for Web developers specializing in Ecommerce. If necessary I can provide the logos in vector format for easy integration.

Suggestions pictures are in order to the logo order in this request

![usps](https://cloud.githubusercontent.com/assets/1796939/9047642/15ca93ba-39e8-11e5-8fe6-1d32cb22e1ce.jpg)

![fedex](https://cloud.githubusercontent.com/assets/1796939/9047732/a092c27e-39e8-11e5-9bd9-3a8d9a1b1616.png)

![ups](https://cloud.githubusercontent.com/assets/1796939/9047703/74d5b376-39e8-11e5-909d-d2f481902b09.png)

![dhl](https://cloud.githubusercontent.com/assets/1796939/9047743/b6f663ea-39e8-11e5-87ec-3d786c81bb92.png)

![ca post](https://cloud.githubusercontent.com/assets/1796939/9047817/5396345a-39e9-11e5-9500-e46311a61623.png)

![royal-mail](https://cloud.githubusercontent.com/assets/1796939/9047826/673e3944-39e9-11e5-9437-8d2ed058c132.jpg)

![delivery truck](https://cloud.githubusercontent.com/assets/1796939/9047838/7109d014-39e9-11e5-8ec6-b989891e0419.png)

![shipping box](https://cloud.githubusercontent.com/assets/1796939/9047934/2c62aff2-39ea-11e5-82c7-0ca592700590.png)

![wooden-pallet](https://cloud.githubusercontent.com/assets/1796939/9048086/4789cbfc-39eb-11e5-9645-104da72df314.jpg)

Respectfully,

Avel U

**Comment by TheChen5** [comment] 2015-08-06 02:58
USPS, UPS, FedEx, and DHL are a dupe of #1502 
Should get rid of those requests
:mag:!

**Comment by batteriesinaflash** [comment] 2015-08-06 22:02
Sorry @TheChen5 ,

Didnt think to search for other request when I posted this. However... I did make the USPS svg files. I can do the rest if these are expectable including the request form #1502. 

You can view it from dropbox link since i can add it directly here..
https://www.dropbox.com/sh/je4eo66fqk3dew2/AADtl6QG-kgQjRMgKYh736nwa?dl=0

**Comment by tagliala** [comment] 2015-08-07 14:20
Sorry, I can't leave this open since this request does not meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

>
* Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

#1502 is a borderline request, it should be splitted in individual requests.

#5870 is better

**Closed by tagliala** 2015-08-07 14:20 UTC
