### ISSUE TITLE
Icon request: c-sharp

### ISSUE THREAD

**Issue by mohammad-hosein-shahpouri** [FortAwesome/Font-Awesome#17466] opened 2020-12-09 13:43 UTC
**What can it be used for?**
It's a programming Language
**Example image (optional)**
Insert the example image here if necessary.
**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-04-24 04:41
Hi @mohammad-hosein-shahpouri,

Duplicate of #8365.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed** 2022-04-24 07:41 UTC
