### ISSUE TITLE
Icon Request: fa-workstation

### ISSUE THREAD

**Issue by chizernn** [FortAwesome/Font-Awesome#9669] opened 2016-07-28 14:06 UTC
System unit. Example in the application
Thanks!
![15363997- - - - - - -](https://cloud.githubusercontent.com/assets/20704692/17215460/99aec606-54e5-11e6-9d54-d4d899b16e4c.jpg)
![22299560-vector-black-pc-components-icons-set-stock-photo](https://cloud.githubusercontent.com/assets/20704692/17215471/a18df266-54e5-11e6-92c3-a83320cf2993.jpg)

**Comment by tagliala** [comment] 2016-07-28 14:13
Duplicate of #2361, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-28 14:13 UTC
