### ISSUE TITLE
Icon Request: Patient

### ISSUE THREAD

**Issue by petcurfew** [FortAwesome/Font-Awesome#3780] opened 2014-06-25 20:40 UTC
An icon representing a Patient (medical context/fa-user-patient):

![image](https://cloud.githubusercontent.com/assets/1471600/3391238/26d2fc48-fca8-11e3-9155-682a7aac2716.png)

To be used in a Patient Scheduling Portal, and to complement the fa-user-md icon.

**Comment by niteshp** [comment] 2016-04-28 01:19
@tagliala I see mine was a dupe of this one.  Would you know if this is still on the anvil (this request was opened ~ 2yrs back) ?  If so, when might it be released ?

**Comment by seysoosey** [comment] 2016-06-21 08:11
+1

**Comment by im-jdamb89** [comment] 2016-06-28 16:56
+2

To be used in medical app for doctors seeing patients. Agreed, would be good complement to fa-user-md.

**Comment by kimberley-johnston** [comment] 2017-07-25 21:16
+1

**Comment by gomes2191** [comment] 2017-10-10 17:48
In my opinion, it would be better to have a generic icon that works for a dental clinic patient and for a medical clinic

**Comment by aethior** [comment] 2022-03-01 00:10
Hi @petcurfew,

This icon was added in v5.4.0.
Check https://fontawesome.com/icons/user-injured

Regards.

cc/ @tagliala

**Comment by aethior** [comment] 2022-03-12 18:28
@tagliala I think you can close here. :)

**Closed** 2022-03-12 18:31 UTC
Labels: new icon, medical / health (category), users & people (category)
