### ISSUE TITLE
Icon Request: fa-datatype-xx

### ISSUE THREAD

**Issue by tpham** [FortAwesome/Font-Awesome#8303] opened 2016-01-09 21:49 UTC
It would be nice to have various icons representing common data types (string, number, boolean, array, object, etc.) One use would be to show data from a database. Thank you very much for many wonderful icons you've created!

**Comment by AndreLGava** [comment] 2016-01-10 01:28
Yea thats sounds good but how would you design this? a string just letter 'A'? a number just '5' or '7'? a boolean it coud the icon-toogle? an array, maybe '[...]' and an object? maybe icon-target? post an example how you imagine this ;)

**Comment by tpham** [comment] 2016-01-10 04:07
Here are some of my thoughts:
- For string, it could be an icon of two overlapping A and Z letters, or something like A...Z (letters A and Z connected by ellipsis)
- For number, it could be something like 1...9 (two numbers 1 and 9 connected by ellipsis)
- For array, [...]
- For object, {...}
- For boolean, probably just two letters T/F
- For binary, something like 010101

**Comment by tagliala** [comment] 2016-01-10 12:38
Duplicate of #6460, closed because requests like this don't meet contributing guidelines

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

object: #1797
binary: #6812

**Closed by tagliala** 2016-01-10 12:38 UTC
