### ISSUE TITLE
icon request: guitar amplifier

### ISSUE THREAD

**Issue by KungFuJosh** [FortAwesome/Font-Awesome#13854] opened 2018-08-30 23:17 UTC

**Comment by tagliala** [comment] 2018-08-31 06:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8215, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-31 06:28 UTC
