### ISSUE TITLE
Icon Request: cruise-ship

### ISSUE THREAD

**Issue by xmuskrat** [FortAwesome/Font-Awesome#15277] opened 2019-07-18 15:28 UTC
**What can it be used for?**
Passenger cruise ships

**Example image (optional)**
![image](https://user-images.githubusercontent.com/59917/61470842-9256c900-a936-11e9-9652-ade22cc92390.png)

![image](https://user-images.githubusercontent.com/59917/61470459-fe84fd00-a935-11e9-9339-9e3cbf9f27b9.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by xmuskrat** [comment] 2019-07-18 15:31
![image](https://user-images.githubusercontent.com/59917/61470802-7f43f900-a936-11e9-9daa-b97d0fab1f8c.png)

**Comment by tagliala** [comment] 2019-07-18 18:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5628, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-07-18 18:23 UTC

**Comment by anusreemn** [comment] 2020-06-15 05:37
@tagliala #5628  is a cruise rather than a ship. And, it would be preferable for a 2-D ship image since it is easier to rotate the icon based on the direction of the movement of the vehicle.

Hence, requesting to re-opening this request ticket.
