### ISSUE TITLE
Authenticatication now required for free installation

### ISSUE THREAD

**Issue by tacman** [FortAwesome/Font-Awesome#15964] opened 2019-12-18 16:37 UTC
Suddenly I can't install the free version anymore...

yarn add --dev @fortawesome/fontawesome-free
yarn add v1.19.2
[1/4] Resolving packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffontawesome-free: authentication required".
info If you think this is a bug, please open a bug report with the information provided in "/var/www/bard/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
tac@tac-xps13:/var/www/bard$ tail yarn-error.log 
      find-up "^3.0.0"
      get-caller-file "^2.0.1"
      os-locale "^3.1.0"
      require-directory "^2.1.1"
      require-main-filename "^2.0.0"
      set-blocking "^2.0.0"
      string-width "^3.0.0"
      which-module "^2.0.0"
      y18n "^4.0.0"
      yargs-parser "^13.1.0"

**Comment by tagliala** [comment] 2019-12-19 10:28
Hi!

Thanks for being part of the Font Awesome Community.

> Authenticatication now required for free installation #15964

It is not required by the free installation, but with our private npm repository  `npm.fontawesome.com`

Please check your `.npmrc` files and remove the configuration if you want to use the public npm/yarn repository

Hope it helps

Closing here, but feel free to comment

**Closed by tagliala** 2019-12-19 10:28 UTC

**Comment by tacman** [comment] 2019-12-19 12:27
Yep, that was it.  Thanks.  I didn't check in the .npmrc file (since it had my token), but hadn't realized that would change the yarn.lock file.

**Comment by cosmicwanderer7** [comment] 2022-04-23 11:20
npm config rm "@fortawesome:registry" https://npm.fontawesome.com/
npm config rm "//npm.fontawesome.com/:_authToken" FONT-AWESOME-PACKAGE-TOKEN

**Comment by Isaac-Tait** [comment] 2023-03-13 15:34
I am having this issue as well. 

```
Trace: 
  Error: https://npm.fontawesome.com/@fortawesome%2ffontawesome-svg-core: authentication required
      at params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:66145:18)
      at self.callback (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:140890:22)
      at Request.emit (node:events:512:28)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:141862:10)
      at Request.emit (node:events:512:28)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:141784:12)
      at Object.onceWrapper (node:events:626:28)
      at IncomingMessage.emit (node:events:524:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I do not have a `.npmrc` file in my root. I am trying to install the free plugins after trying pro for a year...

**Comment by tagliala** [comment] 2023-03-13 16:05
Hi,

as per the error message

> `Error: https://npm.fontawesome.com/@fortawesome%2ffontawesome-svg-core: authentication required`

There is an attempt to use the private npm repository

Please remove font awesome from the lock file and reinstall, it should use the public npm repository

If it doesn't work, please double check npm and yarn config and ensure that they are not reading `.npmrc` from a parent directory in the root

- `yarn config list`
- `npm config list`

Should not show anything related to font awesome. You can add `--verbose` to check where the tools are reading configuration files

**Comment by Isaac-Tait** [comment] 2023-03-13 16:25
Thank you @tagliala for your help.

I ran `yarn config list --verbose` and it showed:

```
info npm config
{
  '@fortawesome:registry': 'https://npm.fontawesome.com/',
  '//npm.fontawesome.com/:_authToken': 'myapi',
  '//registry.npmjs.org/:_authToken': 'mytoken'
}
```

I think the issue is stemming from attempting to use `Global Setup` in the Package Manager docs https://fontawesome.com/v5/docs/web/setup/use-package-managers#global-set-up

After [reading the NPM dos](https://docs.npmjs.com/cli/v6/commands/npm-config) I ran `npm config delete "@fortawesome:registry" https://npm.fontawesome.com/  ` and now I am able to install `@fortawesome/fontawesome-svg-core` without returning the aforementioned error

**Comment by imjared** [comment] 2023-03-16 11:36
For whatever reason, running the commands above didn't solve for me. My solve steps:
1. Run `npm config list`, see that fortawesome is set in the config.
2. Open output of the first line in a text editor. For me, the output was `; "user" config from /Users/jaredlaser/.npmrc`
3. Delete any references to fontawesome and save the `.npmrc`
4. Confirm with `npm config list`

**Comment by itgulle** [comment] 2025-11-18 09:42
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> > Authenticatication now required for free installation
> 
> It is not required by the free installation, but with our private npm repository `npm.fontawesome.com`
> 
> Please check your `.npmrc` files and remove the configuration if you want to use the public npm/yarn repository
> 
> Hope it helps
> 
> Closing here, but feel free to comment

worked well
