### ISSUE TITLE
Icon Request: fa-loader

### ISSUE THREAD

**Issue by angl1** [FortAwesome/Font-Awesome#10654] opened 2017-02-12 16:20 UTC
Can we get a icon for a piece of heavy equipment, we are going to use it for a placement icon on our site for searching construction materials, www.dirtseek.com. Thanks in advance!
![pit](https://cloud.githubusercontent.com/assets/25724861/22863847/33dc0fd8-f115-11e6-85e0-cfd4cea98085.png)

**Comment by aethior** [comment] 2022-05-06 23:16
Hi @nick,

Duplicate of #10032.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed** 2022-05-07 10:59 UTC
