### ISSUE TITLE
Font-awesome kit: it loads all font versions

### ISSUE THREAD

**Issue by Shulepov** [FortAwesome/Font-Awesome#15618] opened 2019-09-28 09:27 UTC
Why it loads so much font versions?
Screenshot: https://imgur.com/a/98UST2m

**Comment by livthomas** [comment] 2019-10-01 08:02
You've probably encountered the same problem that is being discussed in issue #15167.

**Comment by tagliala** [comment] 2019-10-01 08:06
@livthomas thanks for the heads-up.

Closing this as a duplicate of #15167.

I've opened a new internal ticket to increase the priority of that issue, but unfortunately we still don't have a solution, sorry

**Closed by tagliala** 2019-10-01 08:06 UTC
