### ISSUE TITLE
Icon Request: fa-cross

### ISSUE THREAD

**Issue by davidfreels** [FortAwesome/Font-Awesome#8673] opened 2016-02-29 12:37 UTC
Can you please add a cross (†) into the mix of Font Awesome icons? For about 2000 years it's been an internationally recognized symbol for billions of Christians and Christianity worldwide. Thanks.

**Comment by tagliala** [comment] 2016-02-29 12:40
duplicate of #1611 , please +1  that request

closing here

**Closed by tagliala** 2016-02-29 12:40 UTC
