### ISSUE TITLE
Icon request: terrace or patio o deckchair

### ISSUE THREAD

**Issue by Romain-cotton** [FortAwesome/Font-Awesome#20098] opened 2024-02-06 11:16 UTC
Hi !
We'd like to suggest that you create **a terrace or patio icon**, or perhaps a **deckchair icon**.

Kind regards :)

**Comment by tagliala** [comment] 2024-02-06 11:26
Hi!

Thanks for being part of the Font Awesome Community.

This request should be a duplicate of #11347, please add a 👍 reaction to that request and close this one if it is

**Comment by Romain-cotton** [comment] 2024-02-06 13:20
Hi !

Thanks for your reply.

I don't think these 2 requests are identical.
I was thinking more of this kind of icons : 

Sunbath / Seck chair :
https://www.iconfinder.com/icons/3761948/beach_deck_chair_sunbath_thailand_beach_tropical_area_icon?coming-from=related-results

Terrace / deck / patio :
https://www.iconfinder.com/icons/10089705/terrace_deck_patio_sunbath_beach_strand_vacation_veranda_holiday_icon

What do you think about?
Thanks.

**Comment by Romain-cotton** [comment] 2024-02-06 14:26
Maybe in category "travel-hotel" and/or "household"

**Comment by sensibleworld** [comment] 2024-07-15 14:43
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed as not planned by sensibleworld** 2024-07-15 14:43 UTC
Labels: waiting for feedback
