### ISSUE TITLE
Icon request: fa-rwd (responsive web design)

### ISSUE THREAD

**Issue by TMMC** [FortAwesome/Font-Awesome#8701] opened 2016-03-04 14:29 UTC
Example of use cases: portfolio, short description of project.
I have not full/clear idea how it could look, maybe sth. like the image below? To simplyfy it - no shadows, tablet within monitor and mobile phone within tablet or beside it - just the loose idea.
![diseno-web-responsive-design](https://cloud.githubusercontent.com/assets/300390/13528376/e337d012-e215-11e5-9bbd-a3d0861b9ef9.jpg)

Src: [Wikipedia](http://bit.ly/1p4otFE)

###### Notes to [#8674](https://github.com/FortAwesome/Font-Awesome/issues/8674) (not related to the `fa-rwd`)
I took a look at [font-mfizz](http://fizzed.com/oss/font-mfizz) and they seem to be very nice solution but... It's another fonts library to include moreover they do not have icons/brands/technologies which I think are essential (at least for me of course), so I prefer to ask about adding those ones to Font Awesome if possible. Maybe it is possible to merge font-mfizz and Font Awesome?

**Comment by tagliala** [comment] 2016-03-04 15:17
duplicate of #1446 , please +1 that request

closing here

**Closed by tagliala** 2016-03-04 15:17 UTC
