### ISSUE TITLE
icon-save

### ISSUE THREAD

**Issue by annieshangguan** [FortAwesome/Font-Awesome#10656] opened 2017-02-13 09:33 UTC
i hope icon-save have to change！

**Comment by tagliala** [comment] 2017-02-13 17:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #800, please share a constructive criticism there

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-13 17:53 UTC
