### ISSUE TITLE
icon-request: hammer-sickle

### ISSUE THREAD

**Issue by vampwrotesatori** [FortAwesome/Font-Awesome#14453] opened 2018-12-31 20:12 UTC
Reason: Let us mother land lovers show our love in html 

Example: https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Hammer_and_sickle_red_on_transparent.svg/1200px-Hammer_and_sickle_red_on_transparent.svg.png

Icon request checklist

    [✓] This is a single icon
    [✓] The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
    [✓] I have searched for existing issues and to the best of my knowledge this is not a duplicate
    [✓] I have included at least one example image if it could be helpful (optional)
    [✓] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by pwliaom** [comment] 2019-02-08 13:00
I very need this icon，too.

**Comment by tagliala** [comment] 2019-02-08 13:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6098, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-02-08 13:08 UTC
