### ISSUE TITLE
Icon request:csdn

### ISSUE THREAD

**Issue by Lanboo** [FortAwesome/Font-Awesome#15141] opened 2019-06-11 07:07 UTC
**What can it be used for?**

1. CSDN (Chinese Software Developer Network), a professional IT community in China, was founded in 1999. It is dedicated to providing knowledge dissemination, online learning, career development and other life cycle services for software developers in China.
2. My Blog URL in CSDN

**Example image (optional)**
![](https://csdnimg.cn/public/favicon.ico)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-06-11 07:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11972, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-06-11 07:54 UTC

**Comment by Lanboo** [comment] 2019-06-12 09:40
Thank you very much!
