### ISSUE TITLE
Icon Request: fa-bing

### ISSUE THREAD

**Issue by Ben77SD** [FortAwesome/Font-Awesome#5920] opened 2015-03-10 19:15 UTC
Icon request: icon-bing
![bing](https://cloud.githubusercontent.com/assets/11412880/6583064/ed5ec2de-c71e-11e4-978d-4e712833c1b9.png)

**Comment by tagliala** [comment] 2015-03-11 10:15
duplicate of #2499 , please +1 that request

closing here

**Closed by tagliala** 2015-03-11 10:15 UTC

**Comment by Ben77SD** [comment] 2015-03-11 14:40
+1
