### ISSUE TITLE
Icon Request: fa-icon-basket

### ISSUE THREAD

**Issue by wrick17** [FortAwesome/Font-Awesome#5347] opened 2015-01-06 11:46 UTC
for use as a basket like a file basket or a container as a cart.
![basket 1](https://cloud.githubusercontent.com/assets/8253932/5628051/a8db7162-95c7-11e4-9ac6-cde4822b6eb0.png)

**Comment by tagliala** [comment] 2015-01-06 13:02
duplicate of #962 , please +1 that request

closing here

**Closed by tagliala** 2015-01-06 13:02 UTC
