### ISSUE TITLE
Fireworks

### ISSUE THREAD

**Issue by ellenSnod** [FortAwesome/Font-Awesome#17829] opened 2021-04-19 15:14 UTC
**What can it be used for?**
Events in calendar or a party

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by ellenSnod** [comment] 2021-04-19 15:16
request for icon font-awesome

**Comment by tagliala** [comment] 2021-04-19 15:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11730, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-04-19 15:16 UTC

**Comment by ellenSnod** [comment] 2021-04-19 15:20
I don't know how this works. Can you open it if that is what is needed. I do not see where I am to "like" it.

**Comment by tagliala** [comment] 2021-04-19 15:23
>  I do not see where I am to "like" it.

Sure, assuming you are using GitHub on the desktop, open the issue at #11730, click on the emoji at the top right corner and click on 👍🏼 

![image](https://user-images.githubusercontent.com/556268/115261534-fcb42300-a133-11eb-89e6-b2cce22b579c.png)
