### ISSUE TITLE
Icon Request: fa-parking

### ISSUE THREAD

**Issue by Alticaro** [FortAwesome/Font-Awesome#5647] opened 2015-02-11 11:48 UTC
Hi !
To complete the description of a access plan (for exemple)
Like this --->  http://www.aero-parc.fr/img/parking_home.png

Thanks ! :-)

**Comment by tagliala** [comment] 2015-02-14 23:06
duplicate of #1559 , please +1 that request

closing here

**Closed by tagliala** 2015-02-14 23:06 UTC
