### ISSUE TITLE
telegram-plane does not work

### ISSUE THREAD

**Issue by Ampsicora** [FortAwesome/Font-Awesome#13338] opened 2018-06-18 11:37 UTC
Hi, I tried to use the telegram plane icon but seems it doesn't exist if I write:

`<i class="fab fa-telegram-plane"></i>`

and also with:

`<i class="fa fab fa-telegram-plane"></i>`

This is the link to the icon:
https://fontawesome.com/icons/telegram-plane?style=brands

**Comment by tagliala** [comment] 2018-06-18 11:47
Hi!

Thanks for being part of the Font Awesome Community.

(telegram-plane)[https://fontawesome.com/icons/telegram-plane?style=brands] has been introduced in Font Awesome 5.0.0. Please make sure that you are using FA >= 5.0.0

Hope it helps

Closing here

If you think that there are issues in Font Awesome, please open a new issue following our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Closed by tagliala** 2018-06-18 11:47 UTC

**Comment by AndreKoepke** [comment] 2019-05-23 09:17
On FA 5.8.2: `fa-telegram` and `fa-telegram-plane` dosen't show up.
It seems, that symbol does not exsits.

From `fontawesome.css`:
```css
.fa-telegram:before {
  content: "\f2c6"; }
```

I have to use the `fa-paper-plane`.

**Comment by tagliala** [comment] 2019-05-23 09:19
@AndreKoepke I cannot replicate.

Please take a look at: https://jsfiddle.net/tagliala/ryncaLg7/5/

Remember, in Font Awesome 5 we have a new syntax for brands:
```
<span class="fab fa-telegram"></span>
<span class="fab fa-telegram-plane"></span>
```

**Comment by AndreKoepke** [comment] 2019-05-23 09:36
Found the problem. We using https://github.com/FortAwesome/angular-fontawesome and I found there an open ticket about this: https://github.com/FortAwesome/angular-fontawesome/issues/125  

@tagliala thank you for your fast answer.

**Comment by ket-c** [comment] 2021-01-28 13:07
use **fab fa-telegram** instead of **fas fa-telegram** or **fas fa-telegram**
so the key change is **fab**

**Comment by shyynux** [comment] 2024-01-31 10:37
Still not working for me, it is displaying the old solid telegram icon only

**Comment by tagliala** [comment] 2024-01-31 10:51
Hello, 

`telegram-plane` is an alias for `telegram` in FA6. I do not remember the reason, sorry

If this problem is related to FA5, please provide a reproducible test case

**Comment by shyynux** [comment] 2024-01-31 10:57
hey thanks for replying, i used the **faPaperPlane** so no issues now. I was trying to use telegram-plane which is discontinued in FA5. In FA5 we just have telegram solid one.

**Comment by tagliala** [comment] 2024-01-31 11:09
> In FA5 we just have telegram solid one.

In the latest FA5 release (5.15.4) both telegram icons are available

Demo: https://jsfiddle.net/tagliala/ryncaLg7/12/

**Comment by shyynux** [comment] 2024-01-31 11:13
oh alright thanks, it shows this for me

<img width="1139" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/128243259/b23cea30-9e81-499b-920e-79ed7f261a35">

[Link](https://fontawesome.com/v5/icons/telegram-plane?f=brands&s=solid)

when i click on 'view the latest', it shows this
<img width="1142" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/128243259/62f23542-492c-4524-a2a7-fdc0ff828368">

[Link](https://fontawesome.com/icons/telegram-plane?f=brands&s=solid)

**Comment by tagliala** [comment] 2024-01-31 11:31
> when i click on 'view the latest', it shows this

Yes, I can confirm that in 6.x telegram-plane is an alias of telegram. I do not remember the reason but it appears that the logo in FA6 is the only official one
