### ISSUE TITLE
Icon request: horseshoe

### ISSUE THREAD

**Issue by newHagen** [FortAwesome/Font-Awesome#15636] opened 2019-10-01 09:33 UTC
**What can it be used for?**
For horse-related content and in some countries it a symbol for luck.
Flat from above view (U-Shape)
Either with slits or holes, opening to the top.

**Example image (optional)**
[German military horseshoe in 1941](https://upload.wikimedia.org/wikipedia/commons/2/24/Hufeisen_R%C3%BCckseite_Milit%C3%A4r_Deutschland_1941.jpg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment] 2024-07-11 18:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/5306)

**Closed by sensibleworld** 2024-07-11 18:23 UTC
Labels: new icon, animals (category), Duplicate
