### ISSUE TITLE
Icon request: icon-agreement

### ISSUE THREAD

**Issue by andrelmfreitas** [FortAwesome/Font-Awesome#10007] opened 2016-09-29 23:46 UTC
Hello,

I am Brazilian and I do not speak English.

I need an icon as an agreement between two people.

I have created the icon in Inkscape in the mold of fontawesome-WebFont.

There's no way I direct sending the SVG file?

![fa-agreement](https://cloud.githubusercontent.com/assets/22532913/18976126/cd736182-8685-11e6-94c0-8d7188efb90b.png)

**Comment by tagliala** [comment] 2016-09-30 08:55
Duplicate of #878 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 08:55 UTC
