### ISSUE TITLE
Object doesn't support property or method 'from'" in stats.js

### ISSUE THREAD

**Issue by vinod2992** [FortAwesome/Font-Awesome#9607] opened 2016-07-20 18:18 UTC
Cannot read property 'asyncLoading' of undefined

**Comment by tagliala** [comment] 2016-07-20 21:24
could you please provide more details on this issue?

**Comment by mikeybeck** [comment] 2016-08-01 06:07
I've just come across this same error and may be able to provide a little more info..

The console says "Font Awesome CDN reporting has been enabled", then gives the error "Uncaught TypeError: Cannot read property 'asyncLoading' of undefined" in the stats.js file (https://cdn.fontawesome.com/js/stats.js)

**Comment by tagliala** [comment] 2016-08-01 09:42
are you able to provide a reproducible test case or a website showing the issue?

**Comment by mhagesfeld** [comment] 2016-08-01 13:31
I am getting this error as well, but only when I run it locally from my machine.  On our live site it works fine.  This is a secure site, so I thought maybe if I tried "https://use.fontawesome.com/4078cb6882.js" instead of "//use.fontawesome.com/4078cb6882.js" but still getting the error.

Specifically I get: "Unable to get property 'asyncLoading' of undefined or null reference"
on line 104: const {enabled: asyncEnabled} = window.FontAwesomeCdnConfig.asyncLoading;

It does log "Font Awesome CDN reporting has been enabled" on the console

This is in IE 11.

**Comment by mhagesfeld** [comment] 2016-08-01 13:36
Update: I got a new embed code, and now I am getting:

> Object doesn't support property or method 'from'"

on line 70 of stats.js:

`function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }`

**Comment by mhagesfeld** [comment] 2016-08-01 13:48
To confirm, this is only in Internet Explorer

**Comment by tagliala** [comment] 2016-08-01 14:04
I think I can confirm. `stats.js` is using `Array.from` which is part of ES6

Ref: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by tagliala** [comment] 2016-08-01 14:07
@robmadole could you please take a look at this?

**Comment by robmadole** [comment] 2016-08-01 14:24
@tagliala @vinod2992 @mhagesfeld I can confirm this error. We are using Babel to transpile our ES6 code. Looks like I forgot the polyfill. I'm fixing this now.

**Comment by robmadole** [comment] 2016-08-01 15:40
@vinod2992 @mikeybeck @mhagesfeld this has been fixed and deployed to cdn.fontawesome.com. Can you re-publish your embed code (just edit the embed and click save without changing anything) and see if it's fixed for you?

**Comment by mhagesfeld** [comment] 2016-08-02 12:48
I tried and did not get a fix.  When you say "edit the embed" what do you mean exactly?  Change the number?  I added a query string to try and get a reload.

**Comment by robmadole** [comment] 2016-08-02 14:49
@mhagesfeld actually scratch that. You do not need to re-publish anything. So this is still throwing an error in IE? Would it be possible for you to share a URL with me? I've tested this myself and no longer see the problem so maybe I missed something.

**Comment by mhagesfeld** [comment] 2016-08-02 18:23
@robmadole - it wasn't working still with the old one, but the new ID seems to be working fine now, thank you.

**Comment by tagliala** [comment] 2016-08-02 22:37
I'm going to close this one. Please comment if the issue isn't solved

**Comment by RaneClowd** [comment] 2016-09-19 20:26
I was having this error too (the "Cannot read property 'asyncLoading' of undefined" one, not the "Object doesn't support property or method 'from'"). This was happening for me in Chrome (and potentially all browsers, I just haven't checked).

On line 108 the stats.js file would reference window.FontAwesomeCdnConfig.asyncLoading, but window.FontAwesomeCdnConfig wouldn't exist. I was previously using https://use.fontawesome.com/9eca80e962.js to load. Viewing that in a browser shows that it defines FontAwesomeConfig on the window (instead of FontAwesomeCdnConfig).

I have a new embed code now and it defines FontAwesomeCdnConfig, so I'm good to go. But I thought I might give the info since others might still be having the problem.

**Comment by Shadetheartist** [comment] 2017-01-27 00:17
Issue still not solved.

**Comment by robmadole** [comment] 2017-01-28 16:02
Yuck, yeah I need more guards on this script. Thanks for the report @RaneClowd. I'll fix this up a little better so it doesn't complain for older embed codes.

**Comment by robmadole** [comment] 2017-04-17 12:38
We've removed the stats feature from the CDN product so this should no longer cause any problems. Older embed codes may still try to load the `stats.js` script but that file is not empty. I would recommend creating a new embed code and using that for anyone who is having trouble.

**Closed by robmadole** 2017-04-17 12:38 UTC
Labels: bug, cdn
