### ISSUE TITLE
Icon Request: fa-fish

### ISSUE THREAD

**Issue by rcrisp** [FortAwesome/Font-Awesome#5671] opened 2015-02-13 19:48 UTC
I would love an icon representing a very simple version of a fish.

This would be useful as an icon to represent pets, fishing, or fish-related things in general :)

Something along the lines of these outlines, but it would probably work better completely filled in for an icon:

![fa-fish2](https://cloud.githubusercontent.com/assets/7253818/6194208/0d985ed6-b390-11e4-8526-e7b511676e25.jpeg)

![fa-fish1](https://cloud.githubusercontent.com/assets/7253818/6194209/0d9f5ab0-b390-11e4-8a6b-a57ba3f5be23.jpeg)

**Comment by tagliala** [comment] 2015-02-14 23:06
duplicate of #2722 , please +1 that request

closing here

**Closed by tagliala** 2015-02-14 23:06 UTC
