### ISSUE TITLE
Icon request: icon-sum

### ISSUE THREAD

**Issue by naluoli** [FortAwesome/Font-Awesome#12463] opened 2018-02-26 23:42 UTC
### What can it be used for?

Math Icon for Sum, or count, used to show totals

### Example image (optional)

![image](https://user-images.githubusercontent.com/36716550/36702363-a7284d78-1b0b-11e8-99da-79b50a2e416d.png)

### Icon request checklist

- [ single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ yes] I have included at least one example image if it could be helpful (optional)
- [ yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-02-28 13:32
duplicate of #4834

**Closed by tagliala** 2018-02-28 13:32 UTC
