### ISSUE TITLE
Icon Request: fa-ram

### ISSUE THREAD

**Issue by Plasmmer** [FortAwesome/Font-Awesome#10964] opened 2017-04-19 14:13 UTC
RAM memory.

**Comment by tagliala** [comment] 2017-04-19 15:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3239 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-19 15:00 UTC
