### ISSUE TITLE
Icon request: umbraco-logo

### ISSUE THREAD

**Issue by nielslyngsoe** [FortAwesome/Font-Awesome#15203] opened 2019-06-27 09:50 UTC
**What can it be used for?**
The Umbraco logo, can be used to highlight that the presented content is regarding Umbraco.
The icon might be used to represent how a site is driven, if it's based on Umbraco CMS or running Umbraco Cloud.
This can also be used if a person or company wants to present experience or skills regarding Umbraco.
Umbraco has a wide range of products and a broad community, the community consists of Meetups and Festivals around the world, who would be interested in using the logo in their content.

**Example image (optional)**
![umbraco_logo_blue](https://user-images.githubusercontent.com/6791648/60256231-6e710c00-98d1-11e9-8120-06eecbdb858e.png)

SVG can be accessed here:
http://nielslyngsoe.com/files/umbraco/icon/umbraco_logo_blue.svg

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-06-27 09:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4637, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-06-27 09:58 UTC

**Comment by nielslyngsoe** [comment] 2019-06-27 10:37
Hi @tagliala 

I didn't find them similar since this one has the name in it as well. But I'm okay closing this one if you dont accept different appearances of the same logo.

The refereed issue is from 2014, quite some time ago.. What is needed for that request to gain attention and be approved?

**Comment by tagliala** [comment] 2019-06-27 11:03
Hi @nielslyngsoe 

> I didn't find them similar since this one has the name in it as well. 

Don't worry about that,  we respect brands and we use the latest official logo available. In this case, the one at https://umbraco.com/about-us/press/

> The refereed issue is from 2014, quite some time ago.. What is needed for that request to gain attention and be approved?

Sorry about that, we have [**a lot** of brand requests](https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aopen+label%3A%22brand+icon%22+sort%3Acomments-desc)

There is no need to open a new request, please take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), there are a lot of information on how requests work

**Comment by bjarnef** [comment] 2019-06-27 11:07
@nielslyngsoe I don't think it would work well with the name in the icon as well. An icon should ideally be able to use in a size of 16x16 px or 24x24 pixel, so a quite small icon size.
I feel the version is this issue will work better https://github.com/FortAwesome/Font-Awesome/issues/4637

**Comment by nielslyngsoe** [comment] 2019-06-27 14:03
@bjarnef the intention was to test wether we could get something approved, since the 2014 didn't. After having learned the reason for the slow adoption, we will not try to get multiple versions approve, but just stick to the original one. Making sure it gets approved.
