### ISSUE TITLE
Icon request: icon-android-back

### ISSUE THREAD

**Issue by capturewiz** [FortAwesome/Font-Awesome#6408] opened 2015-05-06 21:36 UTC
For referring to the Android hardware and software back buttons in help and tips.

![android_back](https://cloud.githubusercontent.com/assets/4781407/7504179/725c0010-f405-11e4-9c54-215ef19b2446.png)

**Comment by ShamanFromSiberia** [comment] 2015-07-01 07:44
+1

**Comment by tagliala** [comment] 2015-07-01 10:30
android's back is now a left oriented triangle

**Comment by capturewiz** [comment] 2015-07-01 22:22
I suspect you're confusing the back button with the left-chevron "up" button...

![android up](https://cloud.githubusercontent.com/assets/4781407/8466160/1abdb90a-200d-11e5-85c1-d0c83557de3a.png)

http://developer.android.com/design/patterns/navigation.html

**Comment by salarmehr** [comment] 2017-10-05 21:24
It's hard to believe awesomeness miss this icon.

**Comment by sensibleworld** [comment] 2024-07-10 21:43
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/10023)

**Closed by sensibleworld** 2024-07-10 21:43 UTC
Labels: new icon, web application icons (legacy category), Duplicate
