### ISSUE TITLE
Icon request: icon-triangle

### ISSUE THREAD

**Issue by sebashotte** [FortAwesome/Font-Awesome#11138] opened 2017-06-05 19:04 UTC
Hi,

I was searching for a triangle icon similar to the one with the exclamation mark but without it. I am working on a small project and I have some identification to make from good to error. I would like to have one without the exclamation mark. I got no image since it's very similar to the one you have.

Thanks

**Comment by ryankane** [comment] 2017-06-14 14:47
Duplicate of #3216

**Closed** 2017-06-14 15:00 UTC
