### ISSUE TITLE
Icon Request: fa-bathroom

### ISSUE THREAD

**Issue by Rovian-Henz** [FortAwesome/Font-Awesome#9128] opened 2016-05-05 12:28 UTC
Hi, i would like to use a bathroom icon in a real estate site. 
I think something like this would be very useful.

![bath2](https://cloud.githubusercontent.com/assets/16207747/15043475/ac5dfd78-12a3-11e6-83c4-b2bdaa88655b.png)
![bath1](https://cloud.githubusercontent.com/assets/16207747/15043476/ac61fe8c-12a3-11e6-9c98-fc2cc3772b7a.png)

**Comment by aethior** [comment] 2016-05-05 20:51
Hi @Rovian-Henz,

This request is duplicate of #708. Please +1 that.

Regards.

**Closed** 2016-05-05 23:04 UTC
