### ISSUE TITLE
Icon request: pistol / Icon request: rifle

### ISSUE THREAD

**Issue by jocelynduc** [FortAwesome/Font-Awesome#18262] opened 2021-09-11 22:00 UTC
**What can it be used for?**
Can be used for web-based games and shooting clubs websites.
Could complete the collection: sword, dagger, wand, bow-arrow, ...

**Example image (optional)**
Generic picture/make, not relative to a particular manufacturer.

**Icon request checklist**
- [x] This is a **single icon** or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate (Found https://github.com/FortAwesome/Font-Awesome/issues/15764)
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-09-12 06:32
Hi!

Thanks for being part of the Font Awesome Community.

Gun will be available in FA6 (and is a duplicate of #3888): https://fontawesome.com/v6.0/icons/gun?s=solid

Rifle is a duplicate of #3560, please add a 👍🏼 reaction to that request

**Closed by tagliala** 2021-09-12 06:32 UTC
