### ISSUE TITLE
Icon request: fa-mortar-and-pestle

### ISSUE THREAD

**Issue by frankdl98** [FortAwesome/Font-Awesome#8800] opened 2016-03-21 16:04 UTC
I'd like an "Rx" icon, mortar & pestle, and pills/capsules.

**Comment by tagliala** [comment] 2016-03-21 20:06
RX: #768 
pills: #4328  or #1778 

Leaving this open as `fa-mortar-and-pestle`

**Comment by tagliala** [comment] 2017-06-10 21:09
Nope, duplicate of #1709

**Closed by tagliala** 2017-06-10 21:09 UTC
Labels: medical icons, new icon
