### ISSUE TITLE
Icon request: coupon

### ISSUE THREAD

**Issue by mattroche** [FortAwesome/Font-Awesome#14222] opened 2018-11-05 04:03 UTC
### What can it be used for?

Commerce sites use a lot of coupons.  Would be helpful for apps that give rewards

### Example image (optional)

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHoAAAB6CAMAAABHh7fWAAAAaVBMVEX///8AAADp6eknJycXFxfR0dHs7OxYWFhycnL8/Pzy8vLLy8vv7+/Dw8P19fXHx8dHR0c3Nzfd3d2RkZFMTEylpaVTU1MMDAy3t7ciIiKZmZlgYGBCQkJpaWmtra3j4+MuLi5/f3+Hh4fo/wsxAAADV0lEQVRoge2a2xaiIBSGwbRUzNTKsrLT+z/kKKiIApLIOGsW/1W2xS9hHzgEgJWVlZWVlZWVlZWV1f8vh6+4uyEW3KGl6rnbZMNVkbbsbV7wb9FSEoE7FCkNMTk6Ce/QUgkkxkfNjh9myBDK0LDq8yA1RZajYfoyRyZo1wEBK+Axd3lDu5aA41L0dhxyHkNeVls5usdemjyJBuhiiDyNBsgQWQGN+zxbnqyCrtgmyEpoEIsM3Q0eQp6wuYeC2egJZT5OOZvdgWcNqvpwMoMOvjT0y2hszmvDcx46uJVHMTlmSpr7GtoT/P1tHtqvbL4QPShpRcgjc/10Gh1taiPXUSod266+u+TDnUdGvKbTaFwwNwJySB6Nh3JfDDFknCHkup9Kh+9deOE3BuDWpzk455aUvCPkPb+tioc7niOwkIlV54RP/BhFsmZwxRvWhzCqdfKTnKyJxkOd0mDGo91UmkQ2zguh37QdpOhJsm6Hp73XrOIQ0+rHyH1bHX39XEXNfSaUP7CJwykPU0XXWYOXCPGvgj0Xf7YXSmQFdPyujaJsRtLIDoWhh3sAXqpAzFXIymhR+wMc6KbiYYpocIb8okf0ZcllF89TZCU3y86yCdKxT/6ok5eYpaCkBRdXRQ9bCg0C5OdpmpTXmCWHkXRStwS6pjcYSn59d480ud+ElWcpdKOuYkR+N/xH0avru9mYfGBXqG/Bi2sH1yQZkqw+By1PKVRBl8PiARk+ZqJDaSKlZOphJMsUZyd0bmSyyO00zfLBI5Oq3ew8ka2DYiZaVjQ79SoGrmaX1rfIGnnePFxJ/XkYzqyfzoRz3dkYmpkB+vRjLTxfnrnw+ZFM0LR6nA2ihxXjy7J8nQ6XLAE4ZPKaaXsVXthO+AldLXxk1XdUJR18/W2uyMYvr6Hmco+7xiD1268D+7VjfsePaPkil7e6ych3MPHbSUTIa6q5tPc55MGcaWxWR0s2NELBo9m5oqDsLbHS5LzU0+3AqWijUTOuq3ztcrvTOT7qqHKTp3B+prtllx1EMR9kCKHRhtKP6PU2Ktfbnl1vU3q9rfj1DiD+1rHLeodNQpk/YhOSVztYNH2cWgpNxg+Ro3ydo/O83uTcrvGHAf0VvZWVlZWVlZWVlZWV1b+vP4cgMwlpj18mAAAAAElFTkSuQmCC
### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-11-05 11:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2760, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-11-05 11:38 UTC
