### ISSUE TITLE
Icon Request: fa-diploma

### ISSUE THREAD

**Issue by jiemushi** [FortAwesome/Font-Awesome#10977] opened 2017-04-22 21:27 UTC
Hi, I would like to request a diploma icon. I am using it for my for certificate/diploma courses in my website. Thank you very much!

https://d30y9cdsu7xlg0.cloudfront.net/png/66663-200.png

**Comment by tagliala** [comment] 2017-04-22 22:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1379, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-22 22:07 UTC
