### ISSUE TITLE
Icon Request: fa-lift-truck

### ISSUE THREAD

**Issue by sbasurtoj** [FortAwesome/Font-Awesome#9231] opened 2016-05-18 01:18 UTC
Hello Creative People,

Firs of all I want to congratulate you for the great job you are doing, really honor the name Awesome

I write today to request a new Icon that I think can be useful for others as will be for me.

The icon represent a Lift Truck will be used on a warehouse management system that I am developing.

[Lift Truck](https://soft-gator.com/eimg/system/Arrastre.png)

Also add a link to an inventory icon I know there are a couple of issues asking an inventory icon but I can see any images so:

[Invetory](https://soft-gator.com/eimg/system/Inventarios.png)

Kind Regards,

**Comment by Zaanmedia** [comment] 2016-05-18 12:16
+1

**Comment by tagliala** [comment] 2016-05-18 12:45
https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

Please split "inventory" out of this request and provide a better title and use case:

> * Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Include a few use cases for your requested icon. How do you plan on using it?
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by tagliala** [comment] 2016-05-18 12:46
Sorry, forklift is a duplicate of #692.

Closing here, please open a new (proper) request if you want to request inventory

**Closed by tagliala** 2016-05-18 12:46 UTC
Labels: new icon, web application icons
