### ISSUE TITLE
Icon request: fiber-optic

### ISSUE THREAD

**Issue by ilogus** [FortAwesome/Font-Awesome#16900] opened 2020-07-14 08:35 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.

- Can be used in many environments and technology websites

**Example image (optional)**
Insert the example image here if necessary.

![optic_example](https://user-images.githubusercontent.com/10232690/87403584-56902700-c5bd-11ea-9fa8-169a6d9b11bd.PNG)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`) (Maybe for connectors...)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by loucaslt** [comment] 2020-07-14 08:41
+1

**Comment by MichelBaie** [comment] 2020-07-14 09:38
+1

**Comment by Noliose** [comment] 2020-07-14 15:51
+1

**Comment by BL4CKR4VEN** [comment] 2020-07-15 07:30
+1

**Comment by Teodoro888** [comment] 2020-07-15 12:50
+1

**Comment by Rei-Tw** [comment] 2020-07-15 16:12
+1

**Comment by Bibadel** [comment] 2020-10-08 21:35
+1

**Comment by gdeyseLB** [comment] 2022-01-13 16:00
+1

**Comment by diazvictor** [comment] 2024-05-29 10:17
+1

**Comment by sensibleworld** [comment] 2024-07-11 16:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7838)

**Closed by sensibleworld** 2024-07-11 16:37 UTC
Labels: new icon, devices-hardware (category), Duplicate
