### ISSUE TITLE
Icon request: icon-money-bag

### ISSUE THREAD

**Issue by naisam** [FortAwesome/Font-Awesome#5791] opened 2015-02-26 12:56 UTC
please give me an idea for creating money bag icon in font awesome

**Comment by tagliala** [comment] 2015-02-26 14:00
duplicate of #1414, please +1 that request

edited #1414 to include money-bag in the title

closing here

**Comment by tagliala** [comment] 2015-02-26 14:00
ah sorry...

@naisam please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2015-02-26 14:00 UTC
