### ISSUE TITLE
Icon Request: filter-o

### ISSUE THREAD

**Issue by bc173** [FortAwesome/Font-Awesome#9824] opened 2016-08-26 21:43 UTC
An 'open' version of the already existing filter icon.

**Comment by tagliala** [comment] 2016-08-27 10:33
Duplicate of #4738, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-27 10:33 UTC
