### ISSUE TITLE
Icon Request: baidu

### ISSUE THREAD

**Issue by sirzdy** [FortAwesome/Font-Awesome#9903] opened 2016-09-12 00:58 UTC
[http://www.baidu.com/](url)
Baidu
![baidu](https://cloud.githubusercontent.com/assets/17188139/18421924/f747b1ba-78c6-11e6-8f04-d5f2a09d36a0.png)

**Comment by tagliala** [comment] 2016-09-12 10:51
Duplicate of #5380, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-12 10:51 UTC
