### ISSUE TITLE
Icon Request: fa-exchange-slash

### ISSUE THREAD

**Issue by zspitzer** [FortAwesome/Font-Awesome#7422] opened 2015-09-09 03:41 UTC
it would be nice to have online and offline icons

**Comment by kjodle** [comment] 2015-09-09 16:35
+1

**Comment by user-e** [comment] 2015-09-09 16:38
I saw this request and thought I would try and get an image that could represent zspitzer's idea
(it would be nice to make the Font Awesome team's job easier if they decide to make the icons).
<hr>
Perhaps an image like this would look good:
![windows xp wireless icons screenshot 9-9-2015](https://cloud.githubusercontent.com/assets/13541254/9767965/cb3b60d8-5718-11e5-877f-bea470477e13.png)
(the red line separates the two icons, fa-offline is left and fa-online is right).
<hr>
I hope this post and image are useful. 
<br><br>
Image source: Screenshot of internet connection status icons on Windows XP.

**Comment by zspitzer** [comment] 2015-09-11 00:52
perhaps fa-exchange this could be reused? http://fortawesome.github.io/Font-Awesome/icon/exchange/

**Comment by tagliala** [comment] 2015-09-11 11:11
Online could be represented by http://fontawesome.io/icon/circle-o/ and http://fontawesome.io/icon/circle/

I'm going to close this request, I will reconsider a new request named `fa-desktops and fa-desktops-o`

Duplicate of: #6647

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by zspitzer** [comment] 2015-09-13 23:57
May I ask what's the rationale for naming it desktop? it's mobile devices like tablets and phones which usually encounter being offline... btw I find the circles to be quite meaningless

**Comment by tagliala** [comment] 2015-09-14 06:14
The naming is about @user-e 's example

Green circles are used here and there to represent online status, e.g.: facebook chat

![image](https://cloud.githubusercontent.com/assets/556268/9843183/529e68e8-5ab8-11e5-9b09-3b4d2f3aa843.png)

If you have something different in mind, please provide an example of online and offline and I will reconsider reopening

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by zspitzer** [comment] 2015-09-15 00:12
that's why i suggested the exchange icon, online means a flow of data in two directions, the offline icons could simply be that icon with a slash of whitespace thru the middle representing no flow

**Comment by tagliala** [comment] 2015-09-15 08:32
reopening as `exchange-slash`

**Comment by clairestreb** [comment] 2016-03-22 22:03
Search the internet for common icons.  That way you'll use something most people are used to seeing.  In this case, [http://www.bestappstube.com/wp-content/uploads/2016/01/top-10-best-offline-androidios-games-no-wifi-1024x768.jpg](url) and [https://pixabay.com/p-525700/?no_redirect](url)

**Comment by sensibleworld** [comment] 2024-07-10 21:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-10 21:33 UTC
Labels: new icon, web application icons (legacy category), Declined
