### ISSUE TITLE
Icon request: icon-scooter

### ISSUE THREAD

**Issue by mikey186** [FortAwesome/Font-Awesome#13996] opened 2018-09-25 08:59 UTC
### What can it be used for?

This icon can be used for any scooter related stuff, especially from e-scooter companies 

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-09-25 18:32
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6897, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-25 18:32 UTC

**Comment by Chukstart** [comment] 2019-10-08 22:29
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> This request is a duplicate of #6897, please add a  reaction to that request.
> 
> Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones
> 
> Closing here

I still cannot find the icon on the website
