### ISSUE TITLE
Icon Request :  Engine

### ISSUE THREAD

**Issue by duncanellison** [FortAwesome/Font-Awesome#11881] opened 2017-12-08 20:58 UTC
Hi FA guys,

I would really like to have an 'engine' icon.  Like a car or truck engine.  Could be used to signify  some kind of inner workings, but I need it to signify an actual engine.

Thanks

**Comment by tagliala** [comment] 2017-12-09 00:54
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #4175 ?

Could you please provide a single color, 16px size suitable example?

**Comment by duncanellison** [comment] 2017-12-09 21:21
Hi it’s a very similar request,  looks like there have been a few, but I don’t see anything like this in current fa.

 

Like this : https://thenounproject.com/term/engine/17616/  is what I had in mind.

**Comment by tagliala** [comment] 2017-12-09 23:08
@duncanellison thanks.

please add a 👍 reaction to  #4175

Closing here

**Closed by tagliala** 2017-12-09 23:08 UTC
Labels: waiting for feedback
