### ISSUE TITLE
Icon request: plastic-surgery

### ISSUE THREAD

**Issue by jajaperson** [FortAwesome/Font-Awesome#13642] opened 2018-07-27 00:40 UTC
### What can it be used for?

A medical icon to represent plastic surgery

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-27 07:57
Hi!

Thanks for being part of the Font Awesome Community.

In FA 5.2.0 Pro we have
- https://fontawesome.com/icons/scalpel-path?style=solid
- https://fontawesome.com/icons/scalpel?style=solid

Do a scalpel fit your needs?

**Comment by jajaperson** [comment] 2018-07-27 09:15
Yep, thanks.

**Comment by tagliala** [comment] 2018-07-27 09:17
You're welcome

So this is a duplicate of #13288, please add a 👍  reaction to that request

**Closed by tagliala** 2018-07-27 09:17 UTC
Labels: waiting for feedback
