### ISSUE TITLE
please add new icon

### ISSUE THREAD

**Issue by Deament** [FortAwesome/Font-Awesome#9924] opened 2016-09-17 11:29 UTC
please add a new icon which name "baidu"
address: www.baidu.com   
I wish add this icon in this project

**Comment by tagliala** [comment] 2016-09-17 14:39
Duplicate of #5380 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-17 14:39 UTC
