### ISSUE TITLE
Icon request: beer tap

### ISSUE THREAD

**Issue by feeh27** [FortAwesome/Font-Awesome#12088] opened 2018-01-12 18:33 UTC
Please create a beer tap icon, similar to the image below:
![image](https://user-images.githubusercontent.com/13547485/34889706-28e0dfc0-f7b6-11e7-9ffa-8f38875aa95f.png)

**Comment by feeh27** [comment] 2018-01-12 18:37
#3678

**Comment by tagliala** [comment] 2018-01-13 10:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3678, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-13 10:46 UTC
