### ISSUE TITLE
All Icons Turned To Squares

### ISSUE THREAD

**Issue by riverdigger** [FortAwesome/Font-Awesome#16181] opened 2020-02-11 15:59 UTC
I've been using Font Awesome 5 for awhile now and everything has been working perfectly up until now. As of this morning all of my FA 5 icons have turned into squares, and no matter how many times I refresh they do not load in.

![image](https://user-images.githubusercontent.com/21346327/74253550-d3d50a00-4cb4-11ea-981f-0ac01c9d4f80.png)

In the network tab I can see that I am getting a 404 error from the FA5 javascript script tag

![image](https://user-images.githubusercontent.com/21346327/74253689-02eb7b80-4cb5-11ea-9043-9c13de578ad5.png)

Like I mentioned, I haven't changed anything recently, it seems that FA5 has simply stopped working. I have the free $0 plan, but even then it should last forever according to the site. Any ideas?

**Comment by joshuaajones** [comment] 2020-02-11 16:21
@riverdigger check here #16180

**Comment by tagliala** [comment] 2020-02-18 22:00
Maybea a duplicate of #16180

Closing here, but if this is still an issue please comment

**Closed by tagliala** 2020-02-18 22:00 UTC
