### ISSUE TITLE
Icon Request: fa-dino

### ISSUE THREAD

**Issue by andreluizweb** [FortAwesome/Font-Awesome#10344] opened 2016-12-09 19:59 UTC
an icon of a dinosaur!
tks

**Comment by tagliala** [comment] 2016-12-09 22:04
Duplicate of #1580, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-09 22:04 UTC
