### ISSUE TITLE
Icon request: chevron-double-*

### ISSUE THREAD

**Issue by lisivets** [FortAwesome/Font-Awesome#16437] opened 2020-04-08 10:49 UTC
These icons can improve the possibilities of creating navigation.

For example, I created page navigation with “forward/backward” and “first page/last page” navigation buttons using single and double arrow images as icons. 

There are similar icons in the “angle” set, but they are visually smaller and less recognizable. That's why “chevron” set is more usable for such cases, but it lacks all the necessary variations.

I know that similar requests have already been made by other users and they are all closed. But the task is still relevant. So please review the request one more time.

Thank you!

**Comment by tagliala** [comment] 2020-04-08 10:59
Hi!

Thanks for being part of the Font Awesome Community.

Chevron-double family is available in Font Awesome Pro: https://fontawesome.com/icons?d=gallery&q=chevron-double

Font Awesome free has an angle-double family: https://fontawesome.com/icons?d=gallery&q=angle%20double&m=free

You can create chevron double on Font Awesome Free by using the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/369/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Hope it helps

Closing here

**Comment by tagliala** [comment] 2020-04-08 10:59
Also, duplicate of #349

**Closed by tagliala** 2020-04-08 10:59 UTC

**Comment by lisivets** [comment] 2020-04-08 11:20
Thank you very much for the clarifications!

**Comment by tagliala** [comment] 2020-04-08 11:53
@lisivets you're welcome

You may be interested in why chevron-double is not part of the Free Set, and our [Icon Leaderboard FAQs](allow me to also add another link: https://fontawesome.com/community/leaderboard/new#faqs) contain a lot of information on how requests work

Quoting from there:

> **Why are some (highly requested) icons not available in Font Awesome Free?**
>
>Font Awesome began as a free resource and it’s important to us that there will always be a free version of it that is more-than-usable by anyone who needs icons. But we built a team to make sure we continue to add icons, features, and make Font Awesome, well, awesome. That team is full of great people who help make our icons and products - but they’re also folks with bills, kids, and dreams of their own that require a salary. Paid options like Font Awesome Pro help sustain those people and the company. Also, since we’ve introduced Font Awesome Pro, we’ve had the means to more than double the size of Font Awesome Free!
>
>With that all in mind, when planning out a category or release, we consider what icons can be added to Free to form a usable subset. If an icon doesn’t make that cut, it’s because it covers a deeper or more nuanced subject (e.g. toilet-paper-alt) or it isn’t essential to that focused subset of a category we included in Free (e.g. the range of tachometer-slowest to tachometer-fastest). If you find yourself really needing one of those icons, we hope you’d consider supporting the team and project.

**Comment by lisivets** [comment] 2020-04-08 12:04
@tagliala thank you again for the information.

Actually, a paid solution would be fine for me. I forgot to check for these icons in the Pro set when I created this request — my fault.

But now I know what to do :-)
