### ISSUE TITLE
Bug: React native project taking a long time to build the app, after updating fontawesome to V6

### ISSUE THREAD

**Issue by nearghale** [FortAwesome/Font-Awesome#19464] opened 2022-12-08 19:47 UTC
### Bug description

After updating fontawesome to version 6, the APK build time is taking a long time, reaching 45 minutes.

I tried updating all imports, for deep imports, but the elapsed time becomes the same, does anyone have a solution please?

### Font Awesome version

V6

### Application and Operating System

React Native

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2022-12-08 20:49
Hi, this is a duplicate of #19272

As far as I can tell, we do not have a solution and did not understood the issue behind this issue, sorry

**Closed as completed by tagliala** 2022-12-08 20:49 UTC
Labels: bug, needs-triage
