### ISSUE TITLE
icons stack not centered

### ISSUE THREAD

**Issue by radubr** [FortAwesome/Font-Awesome#11726] opened 2017-11-08 11:18 UTC
I've tried to stack a black circle inside a white square. But the circle is not centered as you can see in this link. 
https://codepen.io/radubraniscan/pen/pdNwZP

fa-circle on fa-square-o
```
<div class="container">
<span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-circle fa-stack-1x"></i>
</span>
</div>
```

**Comment by PeterShaggyNoble** [comment] 2017-11-08 11:48
The problem isn't with the stack, it's with `fa-square-o` - see #4649.

**Comment by tagliala** [comment] 2017-11-08 13:00
Hi!

Thanks for reporting this

#4649 has been fixed in FA5 

Here it is a screenshot of your example in FA5 rc4

![image](https://user-images.githubusercontent.com/556268/32550060-079dc88a-c48c-11e7-8b22-76e72ff94859.png)

It is much better, but it is still not perfectly centered (2pixel offset on the bottom).

So I've stacked individual SVGs in a vectorial tool, and they are properly centered:
![image](https://user-images.githubusercontent.com/556268/32550349-01b94e66-c48d-11e7-87da-3bc3afeb278d.png)

I think we cannot do much more than this and this is a side effect of webfonts. If you need pixel perfect stacking, please consider another solution.

I will label this as "cantfix"

**Closed by tagliala** 2017-11-08 13:00 UTC
Labels: waiting for feedback

**Comment by tagliala** [comment] 2017-11-08 13:12
The problem with FA5 is also in the `fa-lg` class, which adds a 1.333em multiplicator.

This is an example of

```css
<span class="fa-stack">
  <i class="far fa-square fa-stack-2x"></i>
  <i class="fa fa-circle fa-stack-1x"></i>
</span>
```

![image](https://user-images.githubusercontent.com/556268/32550795-b881e986-c48e-11e7-95bc-cdaa4005c445.png)

I should recommend the use of multiples of 14px (FA4) or 16px (FA5) for icon stacking
