### ISSUE TITLE
square and square-o are size different

### ISSUE THREAD

**Issue by Khrysller** [FortAwesome/Font-Awesome#6928] opened 2015-07-12 02:05 UTC
the square and square-o have different sizes. I notice while doing a rating system. So I tested with circle, circle-o and circle-thin, but in this case, they are the same size, the difference is inside the circle (this is correct). But the square and square-o, the difference is from outside.

Tho quick test this open a tab for each link bellow and swap between tabs:

Square:
http://fortawesome.github.io/Font-Awesome/icon/square/
http://fortawesome.github.io/Font-Awesome/icon/square-o/

Circle:
http://fortawesome.github.io/Font-Awesome/icon/circle-o/
http://fortawesome.github.io/Font-Awesome/icon/circle-thin/
http://fortawesome.github.io/Font-Awesome/icon/circle/

**Comment by tagliala** [comment] 2015-07-12 13:22
Duplicate of #6238, added to 5.0.0 milestone. I don't know for sure if this is a bug or not (e.g.: thumbs and thumbs-o have different size)

Closing here

**Closed by tagliala** 2015-07-12 13:22 UTC
