### ISSUE TITLE
Icon request: icon-draugiem

### ISSUE THREAD

**Issue by kristapswaits** [FortAwesome/Font-Awesome#6005] opened 2015-03-19 14:26 UTC
Thanks for great icons, but there is one special icon that I would like to see in the list. This is the logo of social site called www.draugiem.lv used by more than 1'000'000 users in the country. We have been making websites with WP and always find that some icons are still missing. But it could be great if you could include this icon and save us a bit of time. Of course there is more ways to put icons, but... :) 

Thanks in advance and keep up the good work.

![draugiem-icon](https://cloud.githubusercontent.com/assets/7715781/6732396/426ff14e-ce54-11e4-877b-1ecc64892d59.png)

![99811822](https://cloud.githubusercontent.com/assets/7715781/6732402/46d78c4c-ce54-11e4-84f6-4f385e626668.png)

**Comment by tagliala** [comment] 2015-03-22 13:41
duplicate of #3865, please +1 that request

closing here

**Closed by tagliala** 2015-03-22 13:41 UTC
