### ISSUE TITLE
Icon Request: fa-googleplay

### ISSUE THREAD

**Issue by Nicolasdu601** [FortAwesome/Font-Awesome#9711] opened 2016-08-06 17:13 UTC
Hello I love your site I would like to add the icon of google play because I find it missing on your site and it takes me to a project site thank you

![hfhzm06q](https://cloud.githubusercontent.com/assets/6660568/17458133/b4599b86-5c09-11e6-9305-0d4ff4de9493.jpg)

![plainicon com-42594-256px](https://cloud.githubusercontent.com/assets/6660568/17458137/bba9d8f6-5c09-11e6-9a8f-b1548c8fac9e.png)

**Comment by tagliala** [comment] 2016-08-06 20:45
Duplicate of #2272 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-06 20:45 UTC
