### ISSUE TITLE
Icon request:fa-flickr-i

### ISSUE THREAD

**Issue by HaydnTrigg** [FortAwesome/Font-Awesome#9317] opened 2016-06-02 07:20 UTC
Flickr icon but only the inside two circles

**Comment by tagliala** [comment] 2016-06-02 09:17
Duplicate of #9317, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-02 09:17 UTC

**Comment by HaydnTrigg** [comment] 2016-06-02 09:45
This is issue #9317 ...?!?!?

**Comment by tagliala** [comment] 2016-06-02 11:10
sorry, #4018
