### ISSUE TITLE
Icon request: icon-houzz

### ISSUE THREAD

**Issue by relish27** [FortAwesome/Font-Awesome#6649] opened 2015-06-03 15:10 UTC
I saw there is a temporary Houzz font here -- https://github.com/brandoncordell/houzz-icon-font  But would be nice to have this added officially to Font Awesome.

Thanks!

**Comment by tagliala** [comment] 2015-06-03 15:14
duplicate of #2039 , please +1 that request

closing here

**Closed by tagliala** 2015-06-03 15:14 UTC

**Comment by relish27** [comment] 2015-06-04 20:34
Done
