### ISSUE TITLE
Icon Request: fa-Biscuit

### ISSUE THREAD

**Issue by cloudi32003** [FortAwesome/Font-Awesome#11793] opened 2017-11-23 09:22 UTC
Hi Sir/Madam,

Greetings, would like to Icon Request: fa-Biscuit in the font awesome. Thank you so much

**Comment by tagliala** [comment] 2017-11-23 10:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2845 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-23 10:10 UTC
