### ISSUE TITLE
Icon Request: fa-tesla motors

### ISSUE THREAD

**Issue by qopel** [FortAwesome/Font-Awesome#5503] opened 2015-01-28 02:30 UTC
The Tesla Motors Icon for car websites

![tesla](https://cloud.githubusercontent.com/assets/8602426/5931412/be5467ba-a66b-11e4-97fa-eb09d30ebc03.png)

**Comment by tagliala** [comment] 2015-01-28 20:25
duplicate of #3643, please +1 that request

closing here

**Closed by tagliala** 2015-01-28 20:25 UTC
