### ISSUE TITLE
Icon Request: fa-wattpad

### ISSUE THREAD

**Issue by SorcererWatcher** [FortAwesome/Font-Awesome#12010] opened 2017-12-28 18:14 UTC
![media](https://user-images.githubusercontent.com/34921457/34419314-fd6d5bf0-ebfa-11e7-8102-5f9ca9d5fa79.png)

**Comment by tagliala** [comment] 2017-12-28 20:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3402, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-28 20:43 UTC
