### ISSUE TITLE
\cs_new:Nn should be \cs_new_protected:Nn

### ISSUE THREAD

**Issue by eg9** [FortAwesome/Font-Awesome#14363] opened 2018-12-05 23:41 UTC
The current version of `fontawesome5` has `\cs_new:Nn` where it should have `\cs_new_protected:Nn`.

Any function that does unexpandable things, such as setting variables, should be “protected”.

After examining the code, I believe that _every_ occurrence of `\cs_new` should be changed in `\cs_new_protected`.

Example where this goes wrong:
```latex
\documentclass{article}
\usepackage{fontawesome5}

\begin{document}

\MakeUppercase{\faHandsHelping\ abc}

\end{document}
```
This raises an error
```latex
! Package fontawesome5 Error: The requested icon HANDS-HELPING was not found.
```
because the macro is expanded prematurely.

If I change the code in `fontawesome5-generic-helper.sty` to
```latex
\cs_new_protected:Nn\__fontawesome_def_icon:nnnnn{
  \tl_if_empty:nF{#1}{
    \cs_new_protected:Npn#1{\faPreselectedIcon{#2}}
  }
  \tl_const:cn{c__fontawesome_slot_#2_tl}{{#3}{#4}}
}
```
the error disappears.

See https://tex.stackexchange.com/q/463397/4427

**Comment by tagliala** [comment] 2018-12-06 09:44
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

I'm not able to find `cs_new:Nn` in the source code of this repository

**Comment by eg9** [comment] 2018-12-06 09:46
Sorry, I thought that this was the place where to report issues also for the LaTeX support package.

**Comment by tagliala** [comment] 2018-12-15 08:35
No problem

Closing here

**Closed by tagliala** 2018-12-15 08:35 UTC

**Comment by jiaopjie** [comment] 2022-01-05 14:18
I test the example given by @eg9 . When using pdfLaTeX or LuaLaTeX, there is no problem. But, when using XeLaTeX, the error
```
! Package fontawesome5 Error: The requested icon HANDS-HELPING was not found.
```
still exists.

The version of `fontawesome5` is `5.15.3`.

**Comment by tagliala** [comment] 2022-01-05 15:03
@jiaopjie is this issue related to Font Awesome official repositories?

If yes, could you please clarify and provide a step by step guide to reproduce this issue (with an official asset or repository)?

**Comment by jiaopjie** [comment] 2022-01-06 03:07
@tagliala I am not very sure, because it is very strange. When compile the example given in this issue
```
\documentclass{article}
\usepackage{fontawesome5}
\begin{document}
\MakeUppercase{\faHandsHelping\ abc}
\end{document}
```
using xelatex, I get the same error 
```
! Package fontawesome5 Error: The requested icon HANDS-HELPING was not found.
```
as before.
But, when compile it with pdflatex or lualatex, this error indeed disappears.
This maybe due to `fontawesome5` or xelatex or just the program installed in my computer only.

If you get no error when compile it with xelatex, forget it. It may be the problem of my computer.

**Comment by tagliala** [comment] 2022-01-06 08:39
```
\usepackage{fontawesome5}
```

Could you please clarify this command? What `\usepackage` do? Where `fontawesome5` is downloaded/located/referenced?

As far as I can tell, this is related to https://www.ctan.org/pkg/fontawesome5, which is a third-party package.

We are thankful to the authors but we can't provide support to third-party packages, please get in touch with the author of the package

**Comment by jiaopjie** [comment] 2022-01-06 08:51
Oh, I know. I am sorry for this.
