### ISSUE TITLE
Icon request: fa-instagram-filled

### ISSUE THREAD

**Issue by VladLujerdeanu** [FortAwesome/Font-Awesome#14704] opened 2019-03-03 17:55 UTC
### What can it be used for?

It is better used with thicker icons such as the social media ones.

### Example image (optional)

JPG: https://imgur.com/1i7sU8M

SVG: https://svgshare.com/i/BYg.svg

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-03-03 18:33
Hi!

Thanks for being part of the Font Awesome Community.

I think that this request is a duplicate of #14526

If it is, please add a 👍 reaction to that request (and also read my comment there)

Closing here, but feel free to comment if this is not a duplicate.

**Closed by tagliala** 2019-03-03 18:33 UTC
