### ISSUE TITLE
Icon request: phpBB

### ISSUE THREAD

**Issue by sohailahmed160** [FortAwesome/Font-Awesome#17868] opened 2021-05-01 21:26 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
Its popular cms used for creating forums. Will help web hosting companies using it.

**Example image (optional)**
Insert the example image here if necessary.
https://upload.wikimedia.org/wikipedia/commons/8/8c/PhpBB_logo_cosmic.svg

**Icon request checklist**
- [ single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ yes] I have included at least one example image if it could be helpful (optional)
- [yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-05-01 21:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1883, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-05-01 21:51 UTC
