### ISSUE TITLE
Icon request: icon-new

### ISSUE THREAD

**Issue by AntonioMalatesta** [FortAwesome/Font-Awesome#5908] opened 2015-03-10 07:36 UTC
Should I use this icon to identify new elements just entered into the databas.
This icon may be similar to the icon fa-certificate but written with new inside:
![label_black_new](https://cloud.githubusercontent.com/assets/11273091/6570784/8a752690-c700-11e4-9e8e-2a7ce35d92f9.png)

**Comment by tagliala** [comment] 2015-03-10 11:57
Duplicate of #1331, please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-03-10 11:57 UTC
