### ISSUE TITLE
Icon-request:icon-sewing

### ISSUE THREAD

**Issue by dimoned** [FortAwesome/Font-Awesome#6916] opened 2015-07-09 21:25 UTC
I need an icon of sewing machine like this one https://d30y9cdsu7xlg0.cloudfront.net/png/2004-200.png
Thank you!

**Comment by tagliala** [comment] 2015-07-10 08:01
duplicate of #4598 , please +1 that request

closing here

**Closed by tagliala** 2015-07-10 08:01 UTC
