### ISSUE TITLE
FontAwesome free Repo not up to date with 5.0.1

### ISSUE THREAD

**Issue by lord-xeon** [FortAwesome/Font-Awesome#11908] opened 2017-12-11 14:30 UTC
The new version of FontAwesome on npm(v5)  - https://www.npmjs.com/package/@fortawesome/fontawesome has a github page that sends users to this project, which is the code for v4.7.0

This is confusing and should be updated.

**Comment by tagliala** [comment] 2017-12-11 22:11
> It looks like this is producing a side-effect of being unable to install v5 of FontAwesome

I think this is another issue, by the way the correct title should be "font awesome free repository is not up to date"

**Comment by robmadole** [comment] 2017-12-11 22:33
@lord-xeon that says that it can't resolve `@fortawesome/fontawesome-free-solid`. Have you installed this? Can you share the relevant section of your `yarn.lock`, `package.json`, or NPM lock file?

**Comment by lord-xeon** [comment] 2017-12-12 15:17
@robmadole I have since been able to fix my unresolved errors.  I think it was likely because I had missed installing the `free-solid` package.

@tagliala I will edit the title to reflect that.

**Comment by wolfy1339** [comment] 2017-12-12 16:11
#11913 Is a duplicate of this issue

**Comment by bkimminich** [comment] 2017-12-18 13:45
The fix for `npm` using the `free-*` repos does not work when using `bower` as it does not have its own project/repository conceptually but instead directly takes the releases from the corresponding GitHub repo https://github.com/FortAwesome/Font-Awesome.

**Comment by robmadole** [comment] 2017-12-20 21:50
We'll get the repositories switched over as soon as we can. We aren't going to officially support Bower however as even they are encouraging people to move to NPM or Yarn.

**Closed by robmadole** 2017-12-20 21:50 UTC
Labels: bug

**Comment by odahcam** [comment] 2018-01-03 14:47
Is there anyway to use v5 without have to download the files by hand?

**Comment by tagliala** [comment] 2018-01-03 15:11
@odahcam 

1. svg + js from cdn (https://fontawesome.com/get-started/svg-with-js)
2. css from cdn (https://fontawesome.com/get-started/web-fonts-with-css)
3. node.js packages (https://fontawesome.com/how-to-use/use-with-node-js#free)

**Comment by jefer94** [comment] 2018-01-09 02:59
https://stackoverflow.com/questions/11530090/adding-a-new-entry-to-the-path-variable-in-zsh

```bash
vim ~/.zshrc
```
```bash
export PATH=~/bin:$PATH
```

`:wq`

**Comment by tutuca** [comment] 2018-07-17 15:55
The docs are confusing as there is no end to end guide that includes installation and usage.

I've already installed `free`, `free-solid` and `free-brands`. But icons are not showing up because it seems like webpack (version 4.12.0) can't resolve the namespaced module for some reason:

```
Module not found: Error: Can't resolve '@fortawesome/fontawesome' in '/home/tutuca/Proyectos/potaje/assets/js'
```

Notice how it's trying to resolve inside my assets folder instead of node_modules.

I can correctly reference anything else:

```

**Comment by tagliala** [comment] 2018-07-17 16:14
@tutuca could you please open a new issue, having care to follow our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?
