### ISSUE TITLE
Octagonal Warning Icon 

### ISSUE THREAD

**Issue by JNJefferyDesign** [FortAwesome/Font-Awesome#3620] opened 2014-06-03 17:14 UTC
An octagonal version of the current triangle shaped warning icon.  Like a stop sign with an exclamation point inside it.

**Comment by grapho** [comment] 2015-03-25 21:38
+1 for this, actually just the octagon itself would be nice.

**Comment by jklingen** [comment] 2015-06-11 08:13
Seems to be a duplicate of #2277

**Comment by tagliala** [comment] 2015-06-11 15:45
@jklingen thanks!

closing here

**Closed by tagliala** 2015-06-11 15:45 UTC
