### ISSUE TITLE
Icon request: postnl

### ISSUE THREAD

**Issue by syndesiweb** [FortAwesome/Font-Awesome#18451] opened 2021-11-17 22:02 UTC
**What can it be used for?**
Postnl is a shipping carrier so the icon would be a brand. It's the leading shipment carrier in the Netherlands and a lot of webshops/wms-systems etc have some sort of integration with their api. Personally i see the most use for webshops indicating what carriers they use or as an icon in some sort of carrier select component.

**Example image**
![image](https://user-images.githubusercontent.com/65358781/142289599-40e82616-89e9-47a0-8043-b2fc09a580ee.png)

**Comment by tagliala** [comment] 2021-11-18 08:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15712, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-11-18 08:12 UTC
