### ISSUE TITLE
Icon request: icon-power-tools

### ISSUE THREAD

**Issue by batterymarket** [FortAwesome/Font-Awesome#15464] opened 2019-08-31 11:18 UTC
![power-tools](https://user-images.githubusercontent.com/47104265/64063229-3308fb80-cbfa-11e9-91ab-0e731380ae11.png)

**Comment by tagliala** [comment] 2019-08-31 11:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3139, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-08-31 11:22 UTC
