### ISSUE TITLE
Icon Request: fa-tuning-fork

### ISSUE THREAD

**Issue by itsonlycomputers** [FortAwesome/Font-Awesome#11033] opened 2017-05-08 15:02 UTC
Requesting a new icon for a tuning fork.  Example attached.
![tuning](https://cloud.githubusercontent.com/assets/11696791/25810311/fc7c223a-33cc-11e7-9cc1-dc55eaab7b51.jpg)

Would prefer examples 3-5 in the attached image.
Thanks!

**Comment by tagliala** [comment] 2017-05-08 15:05
Duplicate of #4474?

**Comment by joshstovall** [comment] 2020-03-09 03:38
I would also like to see a tuning fork icon!

**Comment by tagliala** [comment] 2020-03-09 07:51
No feedback

Closing here as a duplicate of #4474

**Closed by tagliala** 2020-03-09 07:51 UTC
Labels: waiting for feedback
