### ISSUE TITLE
Icon request: icon-furniture

### ISSUE THREAD

**Issue by evinkuraga** [FortAwesome/Font-Awesome#8419] opened 2016-01-26 23:01 UTC
Any of the following objects :
chair, sofa, recliner, chair, table, desk, etc. 
Useful for restaurants, furniture stores, seating areas, work areas, etc.

**Comment by tagliala** [comment] 2016-01-27 17:13
duplicate of #1998 or #759 or #4149

closing here, please +1 the proper request

**Closed by tagliala** 2016-01-27 17:13 UTC
