### ISSUE TITLE
IE9 over SSL , icon's do not showup

### ISSUE THREAD

**Issue by rupamroy** [FortAwesome/Font-Awesome#5785] opened 2015-02-25 18:35 UTC
When I use my application which is running on apache  using a secure SSL connection , ON IE 9 the icons are not visible. 

Can you please suggest what could be the issue ?

**Comment by tagliala** [comment] 2015-02-25 22:14
could you please provide a live example?

closing as a duplicate of #5343, let's continue the discussion there

**Closed by tagliala** 2015-02-25 22:14 UTC
