### ISSUE TITLE
Disqus Icon

### ISSUE THREAD

**Issue by DrGilberry** [FortAwesome/Font-Awesome#6838] opened 2015-06-29 01:14 UTC
fa fa-disqus : Would be great, and in geat need of Disqus icon, please!

![disqus](https://cloud.githubusercontent.com/assets/12837277/8399352/68ce5f3a-1dc1-11e5-9952-e5ff96857b9c.png)

**Comment by tagliala** [comment] 2015-06-30 18:37
duplicate of #6720 , but you know it :)

I should suggest you to consider a custom build, take a look at: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2015-06-30 18:37 UTC
