### ISSUE TITLE
Icon Request: fa-walk

### ISSUE THREAD

**Issue by aptly-io** [FortAwesome/Font-Awesome#6873] opened 2015-07-04 10:55 UTC
There's a class of transportation icons.
Might it possible to add a walking person (male/female)?

Use case: 
 - Fits among the other transportation icons
 - This icon might introduce a access map for walking people

(I should not request multiple icons unless related: fa-running for a running persion)

**Comment by tagliala** [comment] 2015-07-05 12:39
duplicate of #844 , please +1 that request

closing here

**Closed by tagliala** 2015-07-05 12:39 UTC
