### ISSUE TITLE
Icon Request: fa-blogger

### ISSUE THREAD

**Issue by Oanana** [FortAwesome/Font-Awesome#6115] opened 2015-03-31 03:43 UTC
Can we get a blogger Icon please? I've done a quick one up as a vector, if anyone wants I can even send it, I'd just like it added to the library. Email me on taunise@gmail.com and I can pass the vector file to whoever would be able to add it in.
![blogger_icon](https://cloud.githubusercontent.com/assets/11729362/6911965/05f539a2-d7c5-11e4-9688-266c55ae2dde.png)

**Comment by tagliala** [comment] 2015-03-31 09:15
duplicate of #1088 , please +1 that request

closing here

**Closed by tagliala** 2015-03-31 09:15 UTC
