### ISSUE TITLE
Icon request: toque-chefhat

### ISSUE THREAD

**Issue by HenryBotte** [FortAwesome/Font-Awesome#17931] opened 2021-05-25 11:05 UTC
**What can it be used for?**
To represent a chef/cook/restaurant staffs.

**Example image (optional)**
https://th.bing.com/th/id/R8892862a9b4476b6d86536a1fb50bf60?rik=bE3ExDFxdR40%2fg&pid=ImgRaw

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by RaptorInternals** [comment] 2021-05-25 11:12
Is this the same as [fa-hat-chef](https://fontawesome.com/icons/hat-chef)?

**Comment by HenryBotte** [comment] 2021-05-25 11:54
> Is this the same as [fa-hat-chef](https://fontawesome.com/icons/hat-chef)?

I swear that this didn't show up in my search: 'toque' 'chef' 'hat' 'chef hat' lol, thanks

**Comment by tagliala** [comment] 2021-05-25 12:03
> edit: I have the 'free' filter, so I still can't use it 'cause I don't want to go pro

Confirm, this is only available for Pro customers

I have to close this request, duplicate of #2598

[FAQs](https://fontawesome.com/community/leaderboard/new#faqs) "Why are some (highly requested) icons not available in Font Awesome Free?"

**Closed by tagliala** 2021-05-25 12:03 UTC
