### ISSUE TITLE
Icon request: Regex (dot-asterisk)

### ISSUE THREAD

**Issue by septatrix** [FortAwesome/Font-Awesome#19408] opened 2022-10-29 14:28 UTC
### Use case

This can be used for especially for search fields either as a toggle or to signal that the input is interpreted as a regex.

### Example image

E.g.: ![image](https://user-images.githubusercontent.com/24257556/198836791-507d0792-c022-426d-8bb1-76335e7ebf8f.png)

From Wikimedia: https://commons.wikimedia.org/w/index.php?title=File:OOjs_UI_icon_regular-expression.svg&oldid=691058365

Or: ![image](https://user-images.githubusercontent.com/24257556/198836861-9d974574-cdea-4075-8302-42e6c4d8cca4.png)

From the vscode icon set

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2022-10-29 16:56
Subset of #1098, I prefer to keep this open

**Comment by sensibleworld** [comment] 2024-07-11 15:10
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/1098)

**Closed as completed by sensibleworld** 2024-07-11 15:10 UTC
Labels: new icon, text-formatting (category), Duplicate
