### ISSUE TITLE
Icon Request: fa-photoshop fa-illustrator

### ISSUE THREAD

**Issue by ghettopony** [FortAwesome/Font-Awesome#9666] opened 2016-07-28 11:42 UTC
Hey,

I would like to use Adobe softwares icons (Photoshop, Illustrator, After Effects, Indesign...) to illustrate my skills on my personal website.

Thank you!

![photoshop](https://cloud.githubusercontent.com/assets/9021112/17211330/1404c648-54c9-11e6-8d69-0526f6dc7d59.png)
![illustrator](https://cloud.githubusercontent.com/assets/9021112/17211331/140525e8-54c9-11e6-8206-7527b644e4bc.png)

**Comment by FelixWatilah** [comment] 2016-07-30 18:01
I have also been searching for the same icons.

**Comment by tagliala** [comment] 2016-07-30 18:08
Duplicate of #1970, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-30 18:08 UTC
