### ISSUE TITLE
Icon Request: fa-meter

### ISSUE THREAD

**Issue by abdujuk** [FortAwesome/Font-Awesome#8237] opened 2015-12-30 11:56 UTC
hi,

i want a meter measurement ico

thnx

**Comment by tagliala** [comment] 2015-12-30 15:24
duplicate of #1096 , please +1 that request

closing here

**Closed by tagliala** 2015-12-30 15:24 UTC

**Comment by pitus** [comment] 2016-01-27 01:01
+1 Actually, it's NOT a duplicate of #1096 as we need an actual Meter as in a Voltmeter or similar, not a Ruler / tape measure... from #1096 so please keep this one separate

**Comment by tagliala** [comment] 2016-01-27 12:04
@pitus please provide an example and a better title

please also take a look at http://fortawesome.github.io/Font-Awesome/icon/tachometer/
