### ISSUE TITLE
Icon request: fa-discord

### ISSUE THREAD

**Issue by Stokykyle** [FortAwesome/Font-Awesome#10554] opened 2017-01-23 20:45 UTC
![687474703a2f2f692e696d6775722e636f6d2f65597779386c632e706e67](https://cloud.githubusercontent.com/assets/17954294/22221940/df325cac-e1ac-11e6-84be-771bbe455ab5.png)

**Comment by tagliala** [comment] 2017-01-23 21:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-23 21:03 UTC
