### ISSUE TITLE
Icon request: swift

### ISSUE THREAD

**Issue by daveverwer** [FortAwesome/Font-Awesome#15376] opened 2019-08-14 06:44 UTC
**What can it be used for?**
It's a brand logo, of sorts! The [Swift language](https://swift.org) logo.

**Example image (optional)**
[Example image which includes this icon can be found here](https://swift.org/assets/images/swift.svg) and the SVG can be [downloaded from Apple here](https://developer.apple.com/swift/downloads/swift-logo.zip).

**Additional information**
Obviously the icon above is copyright Apple, but they have been very permissive with the use of this icon specifically (not their other ones, just this one!). Of course permission will need to be obtained for this, and you can contact that department through [this form](https://www.apple.com/legal/contact/rights-permissions.html) or through permissions@apple.com.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-08-14 08:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6702, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-08-14 08:47 UTC
