### ISSUE TITLE
Icon request: curly braces

### ISSUE THREAD

**Issue by ygoe** [FortAwesome/Font-Awesome#12074] opened 2018-01-10 20:21 UTC
An icon that shows the curly braces that are often used in programming languages:

`{}`

It can be used to depict programming. It's related but not similar to the existing `</>` icon (`fa-code`) that actually doesn't really depict code but more HTML/XML markup, often used for the web.

So the name for this icon might be `curly-braces` or just `braces` or maybe `code-alt`.

The icon should be fairly easy to create. Some free font could be used as basis.

**Comment by tagliala** [comment] 2018-01-10 22:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1797, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-10 22:49 UTC

**Comment by ygoe** [comment] 2018-01-10 22:53
@tagliala Thanks for the direction. Oh and I did search, I just didn't consider that the correct name. Seems those names are more fuzzy than I thought.

**Comment by tagliala** [comment] 2018-01-10 23:14
@ygoe as a non English native speaker, I've found brackets on [wikipedia](https://en.wikipedia.org/wiki/Bracket#Curly_brackets).

Now I can read 

> Curly brackets { and } are also called braces in the United States

I will definitely add braces in #1797's title
