### ISSUE TITLE
Icon request: game-plan

### ISSUE THREAD

**Issue by jtoyfoglight** [FortAwesome/Font-Awesome#16300] opened 2020-03-10 19:30 UTC
**What can it be used for?**
This icon would be used to help illustrate a game plan, or planning a mission, or executing steps in a given order. In my use case, I'd like to use it in a business setting to help explain the management of a project or implementation.

**Example image (optional)**
Think football x's and o's.
Here's an example, but I'd prefer to see something without a clipboard to make it more generic.
https://www.iconfinder.com/icons/1421642/clipboard_coach_football_game_plan_playbook_strategy_team_icon

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`) **Single**
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`) **game-plan**
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate **Yes, I have searched existing icons**
- [x] I have included at least one example image if it could be helpful (optional) **Yes, see link**
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by boatfishski** [comment] 2020-04-09 17:21
I would also love a strategy Icon, I have a large site with lots of FA icons except for this one, I had to create this one and it works ok in some parts of my app but looks naff in others, I'd happily pay for a FA version to be created. 
![strategy_icon](https://user-images.githubusercontent.com/8460539/78922725-22ebbf80-7aeb-11ea-9bea-624db65031f7.png)

**Comment by aethior** [comment] 2022-03-12 21:25
Duplicate of #9659.

cc/ @tagliala

**Closed** 2022-03-12 22:27 UTC
Labels: new icon, sport (category)
