### ISSUE TITLE
Icon request: fa-math

### ISSUE THREAD

**Issue by mkingvhs** [FortAwesome/Font-Awesome#9766] opened 2016-08-17 19:26 UTC
It would be nice to have a font-awesome icon that would denote a mathematical function such as x square (x^2) (for a simple one).

**Comment by tagliala** [comment] 2016-08-17 20:40
maybe a duplicate of #2675 ?

**Comment by tagliala** [comment] 2016-08-18 08:49
Duplicate of #2675, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-18 08:49 UTC
Labels: waiting for feedback
