### ISSUE TITLE
centos can't display

### ISSUE THREAD

**Issue by Sunyson** [FortAwesome/Font-Awesome#6089] opened 2015-03-28 17:38 UTC
anybody konw that?help me

**Comment by tagliala** [comment] 2015-03-28 17:40
do you mean that FA doesn't work on CentOS? which version? which browser? which browser version? Does http://fontawesome.io/ work?

**Comment by Sunyson** [comment] 2015-03-29 05:54
in centos 6.5,I deployment  a nodejs  application,use fa.  In windows , everything is  ok. Did I should setting something?

**Comment by tagliala** [comment] 2015-03-29 11:22
sorry... I need also this answer: Does http://fontawesome.io/ work?

**Comment by Sunyson** [comment] 2015-03-29 11:32
it's work . the only different is run in windows or centos6.5 .can u understand ？      😔发自网易邮箱大师
            在2015年03月29日 19:22，Geremia Taglialatela 写道:sorry... I need also this answer: Does http://fontawesome.io/ work?

**Comment by tagliala** [comment] 2015-03-29 12:10
@Sunyson if fontawesome.io works then the issue is with your application so this is a support request, and you have to use stackoverflow.

Closing here, but feel free to comment

**Closed by tagliala** 2015-03-29 12:10 UTC
Labels: question, waiting for feedback

**Comment by Sunyson** [comment] 2015-03-29 12:38
ok,thank u发自网易邮箱大师
            在2015年03月29日 20:11，Geremia Taglialatela 写道:@Sunyson if fontawesome.io works then the issue is with your application so this is a support request, and you have to use stackoverflow.

Closing here, but feel free to comment
