### ISSUE TITLE
Icon Request: fa-wheelie-bin

### ISSUE THREAD

**Issue by htilburgs** [FortAwesome/Font-Awesome#11060] opened 2017-05-14 19:06 UTC
For use on Domoticz Dashboard (Dashticz) in Trashcan App, so no need for pictures.
Example:
[http://www.domoticz.com/wiki/File:Wheelie_bin.png](url)

**Comment by tagliala** [comment] 2017-05-14 19:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5803, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-14 19:26 UTC
