### ISSUE TITLE
Icon Request: icon-backspace

### ISSUE THREAD

**Issue by Klemen1337** [FortAwesome/Font-Awesome#7126] opened 2015-08-03 07:46 UTC
Hi,
could you please add a backspace icon? 
Like this ones https://www.iconfinder.com/search/?q=backspace.

Thank you for your time,
K

**Comment by tagliala** [comment] 2015-08-03 08:02
duplicate of #1980, please +1 that request

closing here

**Closed by tagliala** 2015-08-03 08:02 UTC
