### ISSUE TITLE
Icon Request: fa-close

### ISSUE THREAD

**Issue by hpyou** [FortAwesome/Font-Awesome#11373] opened 2017-08-08 07:12 UTC
I use `fa-times`,it likes
![image](https://user-images.githubusercontent.com/15992591/29060148-1f061f24-7c4b-11e7-84cd-a643da8c6016.png)
but i need  thin line likes
![image](https://user-images.githubusercontent.com/15992591/29060242-8bf69f3c-7c4b-11e7-9ac3-307bf5572b83.png)
I did't find it from font awesome lib.
Thinks.

**Comment by tagliala** [comment] 2017-08-08 07:26
Hi!

Thanks for being part of the Font Awesome Community.

Close thin is a duplicate of #1540, please 👍  that request

Please also keep in mind that you could use html `&times;` entity.

Closing here

**Closed by tagliala** 2017-08-08 07:26 UTC

**Comment by hpyou** [comment] 2017-08-08 07:39
@tagliala `&times;` is good. <img class="emoji" alt=":+1:" height="20" width="20" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png">
