### ISSUE TITLE
Icon Request: Weather

### ISSUE THREAD

**Issue by apinzon** [FortAwesome/Font-Awesome#2587] opened 2013-12-15 06:07 UTC
Please create an icon (or an icon set) for displaying general weather information. 

![climacons](https://f.cloud.github.com/assets/6188710/1749894/10719b94-654f-11e3-8e14-4d419e0a4168.gif)

**Comment by tagliala** [comment] 2015-01-28 14:31
this request doesn't meet our contributing guidelines. I'm keeping this open for reference

**Comment by rivulent** [comment] 2015-09-14 23:40
+1 for a "weather" icon that includes a cloud with rain, with sun peeking out from behind -- the universally recognized icon for "weather".

**Comment by Souldat** [comment] 2016-05-25 18:00
+1

**Comment by deepshah1993** [comment] 2016-07-14 04:16
+1

**Comment by Groman123** [comment] 2017-02-07 21:47
+1

**Comment by edprince** [comment] 2017-12-05 07:07
+1

**Comment by tagliala** [comment] 2018-03-14 12:06
Closing here because it is a duplicate of #155

**Closed by tagliala** 2018-03-14 12:06 UTC
Labels: waiting for feedback
