### ISSUE TITLE
Codewars

### ISSUE THREAD

**Issue by Edy1988** [FortAwesome/Font-Awesome#13324] opened 2018-06-14 12:36 UTC
Any chance we can have Codewars icon? That would be amazing. I know people have asked in the past, but still, I could really use one. 

x

**Comment by tagliala** [comment] 2018-06-14 13:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4809, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-14 13:33 UTC
