### ISSUE TITLE
Icon request: icon-rockylinux

### ISSUE THREAD

**Issue by Gheppy** [FortAwesome/Font-Awesome#19594] opened 2023-03-04 16:02 UTC
I use XCP-ng and it would be useful to include this linux distribution in icons
link https://rockylinux.org/

Thank you

**Comment by aethior** [comment] 2023-03-04 19:37
Hi @Gheppy!

This request is a duplicate of #19166.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed as completed** 2023-03-08 21:12 UTC
