### ISSUE TITLE
Icon Request: fa-cc-dinersclub

### ISSUE THREAD

**Issue by magna25** [FortAwesome/Font-Awesome#5697] opened 2015-02-17 04:57 UTC
I have a table where I show credit cards and while I have been able to use icons for the popular ones, dinners club is not on the icon list. I was hoping if you guys could make one

**Comment by tagliala** [comment] 2015-02-22 00:36
duplicate of #4760 , please +1 that request

renamed #4760 to include fa-cc-dinersclub in the title

closing here

**Closed by tagliala** 2015-02-22 00:36 UTC
