### ISSUE TITLE
Icon request: fa-goodreads

### ISSUE THREAD

**Issue by iamsmae** [FortAwesome/Font-Awesome#9614] opened 2016-07-21 18:15 UTC
Hello,

I am designing a site for an author and noticed that there is no Good Reads icon.  This would be useful for authors!

https://www.goodreads.com

**Comment by aethior** [comment] 2016-07-22 04:01
Duplicate of #1715. Please :+1: that.

**Closed** 2016-07-22 09:29 UTC
