### ISSUE TITLE
Icon request: icon-tyre

### ISSUE THREAD

**Issue by NikkiC123x** [FortAwesome/Font-Awesome#8990] opened 2016-04-15 13:40 UTC
I'm currently creating an automotive website, and would love a tyre / tire icon, please!  Something like this would be cool!
![tire-128](https://cloud.githubusercontent.com/assets/18484814/14563054/d6da44ee-0317-11e6-9dce-2ade5f68729a.png)

Thank you :-)

**Comment by PeterShaggyNoble** [comment] 2016-04-15 14:11
Possible dupe of [#4430](https://github.com/FortAwesome/Font-Awesome/issues/4430), you should +1 that one instead.

**Comment by tagliala** [comment] 2016-04-15 16:21
@PeterShaggyNoble thanks

**Closed** 2016-04-15 16:21 UTC

**Comment by SewHappy58** [comment] 2017-01-10 14:57
+1
