### ISSUE TITLE
Icon request: icon-sailing

### ISSUE THREAD

**Issue by yachtmakler** [FortAwesome/Font-Awesome#9187] opened 2016-05-12 11:30 UTC
Hello, it is possile to make a sailing boat icon? I need one for my homepage. Thanks in advance, Bernd

**Comment by tagliala** [comment] 2016-05-12 11:52
#sailing
Duplicate of #5079, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-12 11:52 UTC
