### ISSUE TITLE
Icon request: icon-bloglovin

### ISSUE THREAD

**Issue by DPK-GraphicDesign** [FortAwesome/Font-Awesome#8851] opened 2016-03-29 16:16 UTC
I have set up the Menu Social Icons plugin on a client site and it looks awesome.  You can see it here - http://spiritedandthensome.com  She has requested that I add her "Blogvertise" community link, but I am not sure how to do that.  I have attached the icon graphic.  If it can't be added to your repository, can you instruct me on what code I can add in the functions.php for this new icon?

I really appreciate it.

DAWN

![bloglovin_icon](https://cloud.githubusercontent.com/assets/18147483/14115157/d8390bc2-f5a7-11e5-91c7-a1b1d81b9f7b.png)

**Comment by tagliala** [comment] 2016-03-29 17:24
Duplicate of #2334, please +1 that request

closing here

**Closed by tagliala** 2016-03-29 17:24 UTC
