### ISSUE TITLE
Icon request: fa-presentation

### ISSUE THREAD

**Issue by 3Nex** [FortAwesome/Font-Awesome#5651] opened 2015-02-12 09:55 UTC
An icon that would represent presentations, demonstrations, public speeches, or webinars. It should like like a painting canvas on its own legs. Sample on the following link: 
http://png-1.findicons.com/files/icons/1598/di_black_folder/256/presentation.png 

Common usage would be something like - Would you like to know more about our product? Come see our presentation Tuesdays at 2 PM in our head offices.

**Comment by tagliala** [comment] 2015-02-13 00:18
duplicate of #994 , please +1 that request and post there your example

Closing here

**Closed by tagliala** 2015-02-13 00:18 UTC
