### ISSUE TITLE
Icon Request: fa-medication

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9985] opened 2016-09-29 18:13 UTC
Medication/Drug icon to be used within a healthcare data app
![medication](https://cloud.githubusercontent.com/assets/539719/18966351/e1b5e520-864e-11e6-82ec-72dc60a61ab1.png)

**Comment by tagliala** [comment] 2016-09-30 09:05
Duplicate of #4328 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 09:05 UTC
