### ISSUE TITLE
Icon Request: icon-rights

### ISSUE THREAD

**Issue by Robbert1947** [FortAwesome/Font-Awesome#6150] opened 2015-04-04 15:36 UTC
®

**Comment by aethior** [comment] 2022-03-09 00:31
Hi @Robbert1947,

This icon was added in v4.4.0.
Check https://fontawesome.com/icons/registered

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-09 15:57
Duplicate of #3276

**Closed by tagliala** 2022-03-09 15:57 UTC
