### ISSUE TITLE
Icon Request: fa-Flipboard

### ISSUE THREAD

**Issue by cotw** [FortAwesome/Font-Awesome#5779] opened 2015-02-25 09:36 UTC
It will be good if you provide flipboard icon as i m running site campaignsoftheworld.com and need this social platform very urgently.

Thanks Already!

**Comment by tagliala** [comment] 2015-02-26 14:09
duplicate of #1382 , please +1 that request

closing here

**Closed by tagliala** 2015-02-26 14:09 UTC
