### ISSUE TITLE
Icon request: fa-hanger

### ISSUE THREAD

**Issue by 9nix6** [FortAwesome/Font-Awesome#9543] opened 2016-07-09 09:26 UTC
Hi, Can you please consider adding a clothing hanger icon that can be used to indicate clothing sizes in an online shop? Something like the displayed results when querying for "clothing size hanger icon" in Google Images.

Thank you.

**Comment by tagliala** [comment] 2016-07-09 10:04
Duplicate of #1659, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-09 10:04 UTC
