### ISSUE TITLE
Icon request: fa-alipay

### ISSUE THREAD

**Issue by llqgit** [FortAwesome/Font-Awesome#9975] opened 2016-09-28 06:34 UTC
we need a font-icon of alipay and maybe alibaba would also need by someone else.

**Comment by tagliala** [comment] 2016-09-28 08:43
Duplicate of #3854  and #3855, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-28 08:43 UTC
