### ISSUE TITLE
Icon Request: fa-prize

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9995] opened 2016-09-29 18:18 UTC
Prize/Ribbon/Editors pick icon for use within a healthcare data app
![prize](https://cloud.githubusercontent.com/assets/539719/18966547/9d090960-864f-11e6-9275-773e9087b1e0.png)

**Comment by tagliala** [comment] 2016-09-30 09:04
Duplicate of #1898 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 09:04 UTC
