### ISSUE TITLE
 Icon request: icon-disco

### ISSUE THREAD

**Issue by RichardSimo** [FortAwesome/Font-Awesome#7717] opened 2015-10-19 15:00 UTC
Hi! I m looking for a "disco ball" icon any help will be appreciated.
Thanks in advance 
Richa

**Comment by TheChen5** [comment] 2015-10-20 02:48
#7715 this same request was made.
Both are dupes of #5050 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by RichardSimo** [comment] 2015-10-20 06:09
HI dude!
what does that mean +1!! please if you find "icon-disco" please let  me know!
kr
Richard

**Comment by TheChen5** [comment] 2015-10-20 06:13
Hello,
just click on the link that says "#5050" <<click here.
Then to support it, just comment on that request by posting "+1".

**Comment by TheChen5** [comment] 2015-10-20 06:13
I'm sorry but there is no milestone set for this icon yet.

**Comment by RichardSimo** [comment] 2015-10-20 06:53
Hi again!

it's urgent in my side I made svg file for disco to make the process
quicker!
Or there is another way ?!
Check the attachement!
KR
Richard

**Comment by RichardSimo** [comment] 2015-10-20 06:53
Please help

**Comment by TheChen5** [comment] 2015-10-20 07:03
Please don't send email attachments, they don't work...
For now, you can use customized icons such as  http://fontello.com/ ,  http://icomoon.io/app/#/select , and http://fontastic.me/ . I don't know if they have disco icon...

**Comment by TheChen5** [comment] 2015-10-20 07:09
Maybe some Google icons?
https://www.google.com/design/icons/#ic_album
https://www.google.com/design/icons/#ic_library_music
https://www.google.com/design/icons/#ic_radio

**Comment by RichardSimo** [comment] 2015-10-20 07:18
Hi!
NO those libraries has no disco icon, I prefer  to have inside fontawesome,
thanks

**Comment by TheChen5** [comment] 2015-10-20 23:15
I am *very* sorry.
There is no milestone set for this request yet. It may take years for it to become an icon.
There just isn't enough support for this request yet.
There are *no* more quick solutions right now I can think of except icon images.

**Comment by tagliala** [comment] 2015-10-21 13:28
@RichardSimo customization is the fastest way at the moment: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here as a duplicate of #5050

**Closed by tagliala** 2015-10-21 13:28 UTC
