### ISSUE TITLE
Icon request: icon-lawyer

### ISSUE THREAD

**Issue by nelashj** [FortAwesome/Font-Awesome#11800] opened 2017-11-25 11:09 UTC
Hello i need a lawyer icon for my website.

**Comment by PeterShaggyNoble** [comment] 2017-11-25 11:42
Possible duplicate of #3397.

**Comment by tagliala** [comment] 2017-11-25 12:18
Hi!

Thanks for being part of the Font Awesome Community.

Please provide a single color example of the icon you are requesting

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by nelashj** [comment] 2017-11-25 12:36
Something like below:-

![lawyer](https://user-images.githubusercontent.com/26557767/33230534-3db687a8-d220-11e7-8faa-d8f0789de198.png)

**Comment by sensibleworld** [comment] 2024-07-11 19:43
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 19:43 UTC
Labels: new icon, waiting for feedback, Declined
