### ISSUE TITLE
Icon request: water turbine

### ISSUE THREAD

**Issue by stoneeve415** [FortAwesome/Font-Awesome#15312] opened 2019-07-31 02:19 UTC
**What can it be used for?**
Indicates that the water turbine is working

**Example image (optional)**
![image](https://user-images.githubusercontent.com/16174923/62178455-b9bc8580-b37b-11e9-876f-0431af5764b8.png)

**Icon request checklist**
- [ ] I use the fa-cog now, so I want this icon similar to fa-cog

**Comment by sensibleworld** [comment] 2024-07-11 18:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/17075)

**Closed by sensibleworld** 2024-07-11 18:37 UTC
Labels: new icon, web application icons (legacy category), Duplicate
