### ISSUE TITLE
Missing Icon: fa-list-check

### ISSUE THREAD

**Issue by smith-rachael94** [FortAwesome/Font-Awesome#18812] opened 2022-03-14 17:58 UTC
Hello! it seems that the fa-list-check icon is missing from the pro npm packages can we please get this added - checked regular and pro packages and it was missing from both but didn't check the others? 
link to icon: https://fontawesome.com/icons/list-check?s=solid

**Comment by tagliala** [comment] 2022-04-20 18:14
Hi!

Thanks for being part of the Font Awesome Community and sorry for the late reply.

Is this still an issue?

**Comment by vectorjedi** [comment] 2022-08-25 10:15
Yes, it still seems to be an issue. I'm using the free "@fortawesome/free-solid-svg-icons" in Vue, and could ot import the faListCheck icon from this Library, it doesn't seem to exist.

**Comment by tagliala** [comment] 2022-08-25 10:25
Hi, I cannot replicate

Demo using Vue 2.0 and latest FA: https://codesandbox.io/s/elated-smoke-iuymr?file=/src/App.vue

I've followed instructions at https://fontawesome.com/docs/web/use-with/vue/add-icons

If you still have issues, please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+), a reproducible test case would help to debug

For anyone else affected: please fill out the above template with a reproducible test case

Closing here

**Closed as completed by tagliala** 2022-08-25 10:25 UTC
