### ISSUE TITLE
Icon request: european-union

### ISSUE THREAD

**Issue by FelixGaebler** [FortAwesome/Font-Awesome#16272] opened 2020-03-04 21:47 UTC
**What can it be used for?**
Obvious. This is not a flag. Its a symbol for a large politician union. (It is not out of scope!)

**Example image**
https://previews.123rf.com/images/blankstock/blankstock1608/blankstock160806301/61430756-european-union-icon-eu-stars-symbol-flat-icon-on-white-background-vector.jpg

**Comment by tagliala** [comment] 2020-03-04 23:10
Hi!

Thanks for being part of the Font Awesome Community.

I'm still going to consider this a duplicate of #9520 please 👍 that request

**Closed by tagliala** 2020-03-04 23:10 UTC
