### ISSUE TITLE
Icon Request: fa-compare

### ISSUE THREAD

**Issue by erfanio** [FortAwesome/Font-Awesome#5438] opened 2015-01-22 03:47 UTC
icon for compare
example from Google's material icon pack
![Example Logo](https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_compare_48px-128.png)

**Comment by kwendenarmo** [comment] 2015-02-06 22:59
+1

**Comment by bertoost** [comment] 2015-02-27 10:45
+1

**Comment by danniejpt** [comment] 2015-04-17 03:18
+ 1

**Comment by junkystu** [comment] 2015-06-14 12:15
+1

**Comment by MartinSeeler** [comment] 2015-08-24 12:57
+1

**Comment by bradlis7** [comment] 2015-09-11 19:10
+1

**Comment by LivePwndz** [comment] 2015-10-26 16:57
+1

**Comment by pisumathu** [comment] 2015-12-30 04:35
+1

**Comment by andrewrice** [comment] 2016-01-28 18:31
+1

**Comment by minhajkk** [comment] 2016-02-14 07:37
+1

**Comment by pwcueblocks** [comment] 2016-04-11 12:04
+1

**Comment by aethior** [comment] 2023-02-28 19:26
Duplicate or related? #7616

cc/ @tagliala

**Comment by tagliala** [comment] 2023-03-01 08:53
Related. Also, #7616 contains a bunch of different examples. "Compare" is too abstract and comparing different objects may require different icons

**Comment by aethior** [comment] 2023-03-01 11:40
> Relacionado. Además, #7616 contiene un montón de ejemplos diferentes. "Comparar" es demasiado abstracto y comparar diferentes objetos puede requerir iconos diferentes

Cheking the examples...

#7616 Could be called `files-compare` (the original post there are two files comparing)
`code-compare` already exits (is one of the proposed examples). https://fontawesome.com/icons/code-compare

This issue can be called only `compare` to prevent two issues with the same name.

**Comment by sensibleworld** [comment] 2024-07-11 13:32
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7616)

**Closed by sensibleworld** 2024-07-11 13:32 UTC
Labels: new icon, web application icons (legacy category), Duplicate
