### ISSUE TITLE
Icon request: fa-toilet

### ISSUE THREAD

**Issue by Robot2906** [FortAwesome/Font-Awesome#8889] opened 2016-04-04 19:30 UTC
Something like the below would be great! 
![34730](https://cloud.githubusercontent.com/assets/18270584/14260552/07f63230-faa4-11e5-8c4b-0066e847e7bf.png)

**Comment by aethior** [comment] 2022-03-09 01:14
Hi @Robot2906,

This icon was added in v5.6.0.
https://fontawesome.com/icons/toilet

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-09 17:08
duplicate of #6690

**Closed by tagliala** 2022-03-09 17:08 UTC
