### ISSUE TITLE
Icon Request: fa-coin/fa-coins

### ISSUE THREAD

**Issue by Bobsans** [FortAwesome/Font-Awesome#10715] opened 2017-02-28 12:07 UTC
Please add coin/coins icons. This icon can be used to refer to the virtual currency without a name.

![Coin Image](https://3.downloader.disk.yandex.ru/disk/d4bedb0cd9b9e4cdbb1489be5c6440dcfc7fab3693e26317d07644573c6d70e6/58b59fdf/CJqpd-2b7k3kgg60yI-6udg_03s8Ea1kCKMKOwWEs_mF3d0QWIiSnDI93mnrRuL3GmzHlfMu_oSqff-zvfv-pQ%3D%3D?uid=0&filename=215a871596b92451a1678e36960c0ab7-dollar-coin-icon.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=93446&hid=183d1599b85018385150d3f4216a0ebf&media_type=image&tknv=v2&etag=f52a7467cfae304b9c98a20609f5261d)

![Coins Image](https://1.downloader.disk.yandex.ru/disk/3a0aff956b962d939bcbb86630b99b998f79b26d1dc634bb76d0c22398b61747/58b5a012/CJqpd-2b7k3kgg60yI-6uTQhMB9iwGJ2hWs4zx-_xB3n5VajAJQ5XcgvrhO2sXtaHlmotS3Gi19TVuU-Jj0O0Q%3D%3D?uid=0&filename=33701.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=100861&hid=3b530651500d62eb0f1d4804cf2f7a9b&media_type=image&tknv=v2&etag=4b1523f9ec35341b455bc39c9a82e51c)

**Comment by Bobsans** [comment] 2017-02-28 12:11
#4350 #1400

**Comment by tagliala** [comment] 2017-02-28 12:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4350 #1400, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-28 12:29 UTC
