### ISSUE TITLE
Request: Change Font-Family 

### ISSUE THREAD

**Issue by irthos** [FortAwesome/Font-Awesome#9405] opened 2016-06-14 15:53 UTC
FA is an awesome resource. However, it would be much cleaner if the FontAwesome font inherited the font family of whatever element it is on.

For example, the right way to do a button today is,
`<button><i class="fa fa-check"></i> Save</button>`

I would prefer to do,
`<button class="fa fa-check"> Save</button>`

but this makes Save in the base (ugly) serif font.

What would it take to make this happen?

**Comment by tagliala** [comment] 2016-06-14 15:59
I'm going to consider this a duplicate of #2695.

Please take a look at that request.

Closing here

**Closed by tagliala** 2016-06-14 15:59 UTC
