### ISSUE TITLE
Icon Request: fa-camera-slate

### ISSUE THREAD

**Issue by jennylijo** [FortAwesome/Font-Awesome#12622] opened 2018-03-16 10:16 UTC
Hi! Love the work :)
We are in need of a Camera Slate icon. 

Something like this:
[link
](https://cdn2.iconfinder.com/data/icons/movie-8/500/slate_film-256.png)

**Comment by tagliala** [comment] 2018-03-16 18:25
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #3130?

**Comment by aethior** [comment] 2022-03-12 19:25
> Is this a duplicate of #3130?

Yes, this request is duplicate.

**Closed** 2022-03-12 20:11 UTC
Labels: waiting for feedback
