### ISSUE TITLE
Icon request: mining pick and copper bar

### ISSUE THREAD

**Issue by Pablo-Araya** [FortAwesome/Font-Awesome#13434] opened 2018-06-27 10:17 UTC
Hi may I ask to develop some sort of mining pick and a bunch of mineral (copper  or gold bar) for minery ?
Regards !
+1

**Comment by tagliala** [comment] 2018-06-27 10:33
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by aethior** [comment] 2022-03-15 00:49
Duplicate of #1680.

cc/ @tagliala

**Closed** 2022-03-15 18:16 UTC
