### ISSUE TITLE
Icon Request: fa-sharepoint

### ISSUE THREAD

**Issue by mswilson4040** [FortAwesome/Font-Awesome#9242] opened 2016-05-19 23:21 UTC
![usecase](https://cloud.githubusercontent.com/assets/19480392/15412593/b6f3ecc6-1ddd-11e6-9fd9-afc11653cac2.jpg)
I have a portfolio in which I'm trying to display some icons to which it represents. For example, I have a couple of SharePoint Apps that I have on my site and would like to show a SharePoint Icon on that app's tile to show it associates with SharePoint. I would also want to do the same with AngularJS, Node.JS and a couple others. I will open requests for those separately.
![sharepoint](https://cloud.githubusercontent.com/assets/19480392/15412547/42167108-1ddd-11e6-87c5-bac4f55811f4.jpg)

**Comment by tagliala** [comment] 2016-05-20 09:27
Duplicate of #2396, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-20 09:27 UTC
