### ISSUE TITLE
Icon Request: fa-sum (Greek uc sigma)

### ISSUE THREAD

**Issue by ufoczek** [FortAwesome/Font-Awesome#8598] opened 2016-02-17 14:00 UTC
It would be great to have a new icon. Use cases: sum everything (tables, etc).

https://en.wikipedia.org/wiki/File:Greek_uc_sigma.svg

**Comment by tagliala** [comment] 2016-02-17 14:17
duplicate of #4834 , please +1 that request

closing here

**Closed by tagliala** 2016-02-17 14:17 UTC

**Comment by peterdeak** [comment] 2017-02-22 12:59
.fa-sum:before {
    content: "\03a3";
    font-family: sans-serif;
}

**Comment by canperk** [comment] 2018-01-21 18:09
i agree with @peterdeak
