### ISSUE TITLE
Icon Request: fa-balance

### ISSUE THREAD

**Issue by AntoVasanth** [FortAwesome/Font-Awesome#5355] opened 2015-01-08 10:01 UTC
Balance to indicate stock availability
![764px-balanced_scale_of_justice_svg](https://cloud.githubusercontent.com/assets/6779115/5660909/722d19ce-974b-11e4-950f-cded037d0848.png)

**Comment by tagliala** [comment] 2015-01-08 10:05
duplicate of #2818 , please +1 that request

closing here

**Closed by tagliala** 2015-01-08 10:05 UTC
