### ISSUE TITLE
Icon Request: fa-wallet

### ISSUE THREAD

**Issue by UXDesignerNL** [FortAwesome/Font-Awesome#10341] opened 2016-12-09 13:32 UTC
I would like an wallet icon, something similar to this:
https://thenounproject.com/search/?q=wallet&i=587870

Btw, I ❤️  FontAwesome 😄

**Comment by Crissov** [comment] 2016-12-13 11:46
Related Unicode emoji: 👛 [U+1F45B Purse](http://emojipedia.org/purse/) #222

**Comment by tagliala** [comment] 2016-12-13 11:54
Duplicate of #2317, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-13 11:54 UTC
