### ISSUE TITLE
Icon Request: fa-drone

### ISSUE THREAD

**Issue by OnlyDrey** [FortAwesome/Font-Awesome#9948] opened 2016-09-22 12:11 UTC
Due to the popularity of drones I feel like that is needed

https://cdn4.iconfinder.com/data/icons/ahasoft-military-2/512/quadcopter-512.png

**Comment by tagliala** [comment] 2016-09-22 13:34
Duplicate of #5446 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-22 13:34 UTC
