### ISSUE TITLE
Icon request: Glassdoor

### ISSUE THREAD

**Issue by jessicamartindesign** [FortAwesome/Font-Awesome#13852] opened 2018-08-30 19:25 UTC
### What can it be used for?

This icon is used for recruiting purposes. The site is the main place that our company posts job listings.

### Example image (optional)

![glassdoor-social-icon](https://user-images.githubusercontent.com/6266319/44874256-358bea80-ac60-11e8-857d-16f743698eee.png)

![glassdoor-social-icon-2](https://user-images.githubusercontent.com/6266319/44874267-3c1a6200-ac60-11e8-9472-3385c2a70077.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-31 06:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6422, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-31 06:27 UTC
