### ISSUE TITLE
Icon Request: heart break

### ISSUE THREAD

**Issue by whr4726pv** [FortAwesome/Font-Awesome#10689] opened 2017-02-20 15:35 UTC
Could you make a new icon which is opposite of heart?
Thank you : )

**Comment by tagliala** [comment] 2017-02-20 20:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #751, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-20 20:38 UTC
