### ISSUE TITLE
Icon request: fa-party

### ISSUE THREAD

**Issue by andreamoehl** [FortAwesome/Font-Awesome#14001] opened 2018-09-25 14:14 UTC
A simple party Icon (like a Party Hat with confetti coming out :)) It could be used if anything succeeds.

**Comment by tagliala** [comment] 2018-09-25 18:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4039, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-25 18:29 UTC

**Comment by MrDariusAD** [comment] 2020-11-18 14:48
+1
