### ISSUE TITLE
Icon request: icon-fuel-station

### ISSUE THREAD

**Issue by okle4ka** [FortAwesome/Font-Awesome#10819] opened 2017-03-21 10:32 UTC
Hello! Please create new icon with name fuel-station and tag-code '<i class="fa fa-fuel-station" aria-hidden="true"></i>'. This icon need to use on projects of oil industry. 
Great Thanks, Olga.
![icon-fuel-station](https://cloud.githubusercontent.com/assets/26569529/24143474/326c766c-0e00-11e7-8f48-2a3bc6c69707.png)

**Comment by tagliala** [comment] 2017-03-21 10:42
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #1676 , please add a 👍  reaction to that request.

If you need a map-marker outside the icon, please find another solution, maybe an SVG shape behind the icon.

I'm telling this because I would like to avoid a huge number of requests like `fa-map-marker-cutlery`, `fa-map-marker-coffee`, `fa-map-marker-drink`, `fa-map-marker-university`, `fa-map-marker-*`. and whatever could be useful on a map

Closing here

**Closed by tagliala** 2017-03-21 10:42 UTC
