### ISSUE TITLE
Icon far fa-star not working

### ISSUE THREAD

**Issue by ShoeLace1291** [FortAwesome/Font-Awesome#12677] opened 2018-03-22 23:41 UTC
I am trying to use the star icons to make an article rating system.If an article has 3/5 star rating, it shows 3 "fas fa-star" icons and 2 "far fa-star" icons. I assume that fas means solid, far means regular. The regular star icon is not showing up. It just shows up as an empty square outline. The solid star works fine. I am using webfonts.

Update: Even after switching to JS SVGs this is not working. Am I missing something?

**Comment by aizazshahid** [comment] 2018-03-24 14:59
@ShoeLace1291  Actually in every font awesome icon there is a constant thing which is **"fa"**, so we can say that it's a short-form of **Font Awesome**.
Try  **"fa fa-star"**, surely it will work.

Regards,
Aizaz

**Comment by ShoeLace1291** [comment] 2018-03-24 22:02
@aizazshahid this is displaying the exact same icon as "fas fa-star" which is the solid and what I want is the "empty" star. From what I can remember, in v4.0, the class was fa-star-o for the empty star. This is what I want.

**Comment by aizazshahid** [comment] 2018-03-25 14:45
@ShoeLace1291 my mistake i didn't know that. But, may be, this will solve your problem [Upgrading from version 4](https://fontawesome.com/how-to-use/upgrading-from-4)

**Comment by Syed-Ibrahim** [comment] 2018-03-28 04:52
This issue is not fixed yet. Latest Version 5.0.9 also having same issue. I cant able to select empty star.

**Comment by julicamb** [comment] 2018-04-05 19:33
I have the same issue
This works perfect:
<font-awesome-icon size="2x" :icon="['fas', 'heart']" />
But this gives me an error "Check not find one or more icon(s) "
<font-awesome-icon size="2x" :icon="['far', 'heart']" />

**Comment by tagliala** [comment] 2018-04-06 07:43
Hi!

Thanks for being part of the Font Awesome Community.

Please provide all the information required by our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by DanijelH** [comment] 2018-10-29 08:38
I am having the same issue as @julicamb . Any solution or info so far?

**Comment by tagliala** [comment] 2018-10-29 13:03
No feedback, closing here.

Please provide all the information required by our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Closed by tagliala** 2018-10-29 13:03 UTC
Labels: waiting for feedback

**Comment by DanijelH** [comment] 2018-10-30 14:14
Yes, I figured it out. 
There are two packages, "@fortawesome/free-solid-svg-icons"(fas) and "@fortawesome/free-regular-svg-icons"(far). Import needs to be done correctly from those packages in order for icons to work. I wish only if this was documented better.

**Comment by tagliala** [comment] 2018-10-30 15:45
This is documented at https://fontawesome.com/how-to-use/with-the-api/setup/importing-icons, at the very bottom of the page

> *To import the same icon from different styles*

**Comment by DanijelH** [comment] 2018-10-30 15:57
@tagliala Thanks for the info! I wasn't able to find it but had to figure it out on my own. I am using this with Vue and was focusing on the Vue-Fontawesome part and searching something like that doesn't provide this info as plain. Just a suggestion, maybe if this were also added to https://github.com/FortAwesome/vue-fontawesome readme.

**Comment by mokhosh** [comment] 2018-11-17 11:15
I had the same issue, thanks to @julicamb I added this line to my sass and fixed my problem:

```sasss
@import "~@fortawesome/fontawesome-free/scss/regular";
```

**Comment by Bhonny** [comment] 2019-01-16 01:35
Just simply add "css/all.css" rather than "css/font-awesome.min.css"

If linking to your downloaded files from font awesome website, you may simply add this link inside <head></head> tag

<link href="project-folder-name/font-awesome-folder/css/all.css" rel="stylesheet">

Perfectly work from my end.

Happy New Year:)

**Comment by Bhonny** [comment] 2019-01-16 01:39
Just simply add "css/all.css" rather than "css/font-awesome.min.css"

If linking to your downloaded files from font awesome website, you may simply add
-----------> <link href="project-folder/font-awesome-folder/font-awesome/css/all.css" rel="stylesheet">

It perfectly work from my end:) 
Happy New Year:)

**Comment by Bhonny** [comment] 2019-01-16 01:40
Just simply add "project-folder/font-awesome-folder/css/all.css" rather than "project-folder/font-awesome-folder/css/font-awesome.min.css"

If linking to your downloaded files from font awesome website, you may simply add
----------->

It perfectly work from my end:)
Happy New Year:

**Comment by Bhonny** [comment] 2019-01-16 01:40
Just simply add "project-folder/font-awesome-folder/css/all.css" rather than "project-folder/font-awesome-folder/css/font-awesome.min.css"

It perfectly work from my end:)

Happy New Year:

**Comment by Bhonny** [comment] 2019-01-16 01:41
Just simply link the css file this way

**"project-folder/font-awesome-folder/css/all.css"** 

rather than

_"project-folder/font-awesome-folder/css/font-awesome.min.css"_

It perfectly work from my end:)

Happy New Year:

**Comment by assmabenmussa** [comment] 2020-11-01 09:06
I hope you solved your issue, but for anyone still looking, simple add 
```
 <script defer src="https://use.fontawesome.com/releases/v5.15.1/js/all.js"></script>
 <script defer src="https://use.fontawesome.com/releases/v5.15.1/js/v4-shims.js"></script>
```
to your head element in the html, this worked for me

**Comment by Ataberkuygur** [comment] 2021-03-15 04:26
> I hope you solved your issue, but for anyone still looking, simple add
> 
> ```
>  <script defer src="https://use.fontawesome.com/releases/v5.15.1/js/all.js"></script>
>  <script defer src="https://use.fontawesome.com/releases/v5.15.1/js/v4-shims.js"></script>
> ```
> 
> to your head element in the html, this worked for me

This works thanks

**Comment by dushyantsingh-dev** [comment] 2021-08-28 12:59
far fa-star is paid

**Comment by tagliala** [comment] 2021-08-28 15:35
> far fa-star is paid

Hi,

`far fa-star` (`fa-star` in regular style) is free in both FA5 and FA6

- https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=star&s=regular&m=free
- https://fontawesome.com/v5.15/icons/star?style=regular

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

If you still have issues in using `fa-star` regular with FA Free, feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case

**Comment by gopikrishnan7** [comment] 2022-08-10 03:44
> @ShoeLace1291 Actually in every font awesome icon there is a constant thing which is **"fa"**, so we can say that it's a short-form of **Font Awesome**. Try **"fa fa-star"**, surely it will work.
> 
> Regards, Aizaz

It's working

**Comment by imdataboy** [comment] 2024-01-25 22:06
seems like none of the solutions above worked for me maybe because of the versions provided are old here is the solution: worked perfectly fine for me.

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">

**Comment by imdataboy** [comment] 2024-01-25 22:06
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
