### ISSUE TITLE
Icon Request: fa-feedly

### ISSUE THREAD

**Issue by mcpe-yossi1114** [FortAwesome/Font-Awesome#9541] opened 2016-07-09 03:16 UTC

**Comment by tagliala** [comment] 2016-07-09 10:04
Duplicate of #2086, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-09 10:04 UTC
