### ISSUE TITLE
Icon Request: fa-skate

### ISSUE THREAD

**Issue by davethackeray** [FortAwesome/Font-Awesome#10677] opened 2017-02-17 12:34 UTC
Hi.
Love to have an icon representing skateboarding/skate parks.
I run digital for a health charity and we love fa. But some of our facilities need representing with fa, especially our skate parks, and this would be perfect for us and the thousands of other skate park protectors and managers across the world.

**Comment by tagliala** [comment] 2017-02-17 13:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5450, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-17 13:05 UTC
