### ISSUE TITLE
Icon Request: "Line Application icon"

### ISSUE THREAD

**Issue by maxkub123** [FortAwesome/Font-Awesome#10839] opened 2017-03-24 06:38 UTC
Dear dev.

you made an amazing job. I just got the know Elementor page builder 2 weeks ago from Udemy. He also taught how to create a website by using Elementor too. your product is an amazing job. I can see real hard work in there.

However, as I am Thai and most Thai people use Line application to mainly communicate with each other. Can you please add "Line logo" to social icon widget. It would be perfect for my website.

**Comment by tagliala** [comment] 2017-03-24 08:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2631 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-24 08:20 UTC

**Comment by maxkub123** [comment] 2017-03-24 11:26
wow Thank you very much.

Nuttavut
Jarukittikun
Address  39/10 - 11 Soi.Yommaraj Saladaeng Rd. Silom Bangrak Bangkok 10500
Phone  063-919-9197  <063-919-9197>

Email  maxkub123@gmail.com  <maxkub123@gmail.com> Website  www.nuttavutj.com
<http://www.nuttavutj.com>

<http://www.facebook.com/nuttavut.jarukittikun>
"Success is not the key to happiness. Happiness is the key to success. If
you love what you are doing, you will be successful." - Herman Cain
<https://www.quotesdaddy.com/quote/617825/herman-cain/success-is-not-the-key-to-happiness-happiness-is>
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=700918663147473>
