### ISSUE TITLE
Icon request: icon-gpu

### ISSUE THREAD

**Issue by othomasj** [FortAwesome/Font-Awesome#12990] opened 2018-05-01 00:21 UTC
Would be very useful to have for system dashboards.

![image](https://user-images.githubusercontent.com/23376185/39456356-ca884ca8-4c9a-11e8-8c94-9129323979c7.png)

**Comment by yovantichrist** [comment] 2018-05-05 09:05
+1

**Comment by TexasSwede** [comment] 2018-05-10 02:10
I agree, I would also like to see a motherboard icon, a processor icon (yes, I know there is a microchip icon https://fontawesome.com/icons/microchip?style=light , and a mouse icon.

**Comment by hsntngr** [comment] 2019-02-14 11:54
it have been a year.. :/

**Comment by raiguard** [comment] 2019-05-20 18:01
+1 from me. I would like to have a fontawesome version of the GPU Icon I am using, since almost absolutely every other icon I am using is fontawesome.

![image](https://user-images.githubusercontent.com/3515394/58041972-acbb2480-7af6-11e9-96b8-701567697803.png)

**Comment by TexasSwede** [comment] 2020-03-06 15:21
This icon would be useful to me as well.

**Comment by m0hamedessam** [comment] 2020-04-10 11:11
+1

**Comment by sicklybeans** [comment] 2020-07-29 14:22
+1 I know it's old but I would love this

**Comment by mario-gabriel-campos** [comment] 2020-08-31 11:58
definitely +1

**Comment by chiliwax** [comment] 2020-11-10 13:47
+1

**Comment by fopor** [comment] 2021-01-07 21:28
+1

**Comment by Atralb** [comment] 2021-02-20 14:04
Seems like the team @davegandy @tagliala @robmadole doesn't care.

What fonts are you guys using in the meantime for these kind of things ?

**Comment by enlznep** [comment] 2021-02-24 02:27
+1

**Comment by diademoff** [comment] 2021-03-19 17:35
+1

**Comment by pipin77** [comment] 2021-08-15 09:21
very useful +1

**Comment by CEbbinghaus** [comment] 2021-10-16 08:21
I can't believe this isn't in yet. I would be keen to see all parts of a PC represented, (GPU, CPU, RAM, Motherboard, Fans, Case, PSU)

+1

**Comment by aethior** [comment] 2022-05-07 18:56
@tagliala `devices-hardware (category)` label for this request?

**Comment by jmb05** [comment] 2022-07-21 10:29
+1

**Comment by ghost** [comment] 2022-08-14 03:32
100% +1

**Comment by Marks12520** [comment] 2022-08-16 17:01
Yes please

**Comment by Gandharikos** [comment] 2023-01-16 15:47
+1

**Comment by maxheyer** [comment] 2023-02-18 16:45
+1

**Comment by teomanofficial** [comment] 2023-02-19 18:11
We are waiting for years :D

**Comment by CHOWY0152** [comment] 2023-02-23 05:45
+1

**Comment by jherman** [comment] 2023-02-23 06:26
How is it that we have `child-combatant` but we can't even get a GPU icon?

**Comment by seanidzenga** [comment] 2023-02-23 20:09
+1

**Comment by IbolDev** [comment] 2023-03-10 12:45
+1

**Comment by NikilXYZ** [comment] 2023-03-21 21:12
+1 and also would like an Nvidia Icon.

**Comment by itsdevdom** [comment] 2023-06-20 08:47
We definitely need icons for all kinds of PC parts!

**Comment by crshqd** [comment] 2023-10-10 02:31
+1 could use this for a whole bunch of projects

**Comment by VehementHam** [comment] 2023-11-29 21:13
+1

**Comment by jeromeluciano** [comment] 2023-12-04 21:26
+1

**Comment by clsv** [comment] 2023-12-16 23:09
please add it :-)

**Comment by fourm1** [comment] 2023-12-29 15:41
Yep

**Comment by mrtx99** [comment] 2024-01-07 17:47
+1

**Comment by MarkSmersh** [comment] 2024-01-08 17:01
+1

**Comment by aristotaloss** [comment] 2024-01-27 13:52
What a joke. The irony that v6 brought `dumpster-fire` but the project still fails to add some of the most basic icons 😅

**Comment by TNTRedstone** [comment] 2024-02-17 23:32
+1 x infinity, this is my neofetch:
![20240217_18h31m47s_grim](https://github.com/FortAwesome/Font-Awesome/assets/73077470/d9cf9ccd-028f-4f22-a826-90125da54e8b)
it is uneven just because of this

**Comment by ghost** [comment] 2024-03-02 16:15
+1

**Comment by CelestialCrafter** [comment] 2024-04-20 03:37
+1

**Comment by bnanchen** [comment] 2024-04-22 13:07
+1

**Comment by VehementHam** [comment] 2024-04-25 19:43
Okay, someone should make a fork of this project that has this.

**Comment by bjsho** [comment] 2024-06-16 17:55
+1 we need this icon

**Comment by sensibleworld** [comment] 2024-07-11 19:39
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/9672)

**Closed by sensibleworld** 2024-07-11 19:39 UTC
Labels: new icon, devices-hardware (category), Duplicate

**Comment by matsydev** [comment] 2025-03-19 15:34
+1

**Comment by DreamyDuck** [comment] 2025-04-07 06:04
+1

**Comment by synden** [comment] 2025-05-22 08:38
It's been a few years now. How's it going?

**Comment by wanderduck** [comment] 2025-11-13 20:04
Is this ever going to happen???
