### ISSUE TITLE
Darts

### ISSUE THREAD

**Issue by zippy6** [FortAwesome/Font-Awesome#12400] opened 2018-02-20 19:02 UTC
Can we have a dart board or 3 darts as an icon ?

**Comment by tagliala** [comment] 2018-02-20 19:32
Hi!

Thanks for being part of the Font Awesome Community.

This could be a duplicate of #11567, but I'm not sure.

Could you please check?

If this isn't a duplicate, please fill our [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by tagliala** [comment] 2018-02-20 19:58
No problem, please add a 👍  reaction to #11567

**Closed by tagliala** 2018-02-20 19:58 UTC
Labels: waiting for feedback
