### ISSUE TITLE
Icon request: fa-box

### ISSUE THREAD

**Issue by kmcroft13** [FortAwesome/Font-Awesome#10103] opened 2016-10-22 03:22 UTC
When integrating with cloud storage providers, many of the major players have Font Awesome icons to use. Box is notably missing from icon support, however. This is especially difficult for Enterprise grade applications as Box focuses largely on the Enterprise.

Something similar to the below would be great:
![box](https://cloud.githubusercontent.com/assets/10491569/19616610/598930bc-97dd-11e6-978b-e29d2074147f.png)

**Comment by tagliala** [comment] 2016-10-22 09:54
Duplicate of #1745, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-22 09:54 UTC
