### ISSUE TITLE
Icon Request: fab fa-smashcast

### ISSUE THREAD

**Issue by VMAJSTER** [FortAwesome/Font-Awesome#13883] opened 2018-09-03 10:53 UTC
Sorry, if i create this request bad, but this is my 1st time!

Mixer svg white: https://github.com/mixer/branding-kit/blob/master/svg/MixerMerge_White.svg

Smashcast (png&svg)
png: http://www.koolthings.com/pics/images/smashcastlogo_262d8e03.png
1st svg https://en.wikipedia.org/wiki/Smashcast.tv#/media/File:Smashcast.tv_logo.svg
2nd svg https://upload.wikimedia.org/wikipedia/en/4/49/Smashcast.tv_logo.svg
ps. (idk if png are allow. they had svg icon on web (in header), but i dont know how to download, but i find two others

If someone before, create similar post, please, delete this request
sorry for my bad english :|

**Comment by tagliala** [comment] 2018-09-03 11:12
mixer is a duplicate of #11242, please add a 👍  reaction to that request

Leaving this open as fa-smashcat

**Comment by aethior** [comment] 2022-04-10 23:54
The domain is down since 2020.
>Smashcast.tv failed to load on all attempts after November 20, 2020. ([more info](https://en.wikipedia.org/wiki/Smashcast))

cc/ @tagliala

**Closed** 2022-04-11 15:51 UTC
Labels: brand icon
