### ISSUE TITLE
icon request: icon-forklift

### ISSUE THREAD

**Issue by ivanlori** [FortAwesome/Font-Awesome#3472] opened 2014-05-19 09:31 UTC
Hello,
this icon -> 
![13-128](https://cloud.githubusercontent.com/assets/7620920/3012293/0a4d8116-df38-11e3-9f3d-c2f3c238bb28.png)
would be useful to symbolize warehouse, I need it for my website to list buildings.
thank you!

**Comment by raufaamir** [comment] 2015-07-16 08:58
I also required something like this for warehouse.

**Comment by alinearielo** [comment] 2015-08-24 14:46
Or some kind of boxes!

**Comment by tagliala** [comment] 2016-03-04 16:56
Renamed as `icon-forklift`

**Comment by tagliala** [comment] 2016-03-04 16:59
...which is a duplicate of #692, please +1 that request

**Closed by tagliala** 2016-03-04 16:59 UTC
Labels: new icon, web application icons

**Comment by jbwl** [comment] 2016-11-28 15:40
+1
