### ISSUE TITLE
Icon Request: fa-php

### ISSUE THREAD

**Issue by uomopalese** [FortAwesome/Font-Awesome#6796] opened 2015-06-21 09:45 UTC
![php-4096-black](https://cloud.githubusercontent.com/assets/1730448/8271196/fee2f524-180a-11e5-9836-6646b2d8681c.png)

**Comment by tagliala** [comment] 2015-06-21 10:32
duplicate of #1420 , please +1 that request

closing here

**Closed by tagliala** 2015-06-21 10:32 UTC
