### ISSUE TITLE
Icon request: icon-zodiac-*

### ISSUE THREAD

**Issue by peroosh-gattkins** [FortAwesome/Font-Awesome#12889] opened 2018-04-18 08:19 UTC
### What can it be used for?

Really, this would be 12 icons (sorry, breaking the rules already!) eg:

- icon-zodiac-aquarius
- icon-zodiac-pisces
- icon-zodiac-aries
- icon-zodiac-taurus
- icon-zodiac-gemini
- icon-zodiac-cancer
- icon-zodiac-leo
- icon-zodiac-virgo
- icon-zodiac-libra
- icon-zodiac-scorpio
- icon-zodiac-sagittarius
- icon-zodiac-capricorn

This suite of icons would be useful for a number of reasons including sites where you have members who share birthday details, daily horoscopes etc.

**Comment by tagliala** [comment] 2018-04-18 09:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2831, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-18 09:28 UTC
