### ISSUE TITLE
Icon swimming

### ISSUE THREAD

**Issue by otoman** [FortAwesome/Font-Awesome#13246] opened 2018-05-31 16:01 UTC
Please add icon for swimming

**Comment by tagliala** [comment] 2018-05-31 18:32
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5771 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-31 18:32 UTC
