### ISSUE TITLE
Icon request: fa-money-box

### ISSUE THREAD

**Issue by ssoulless** [FortAwesome/Font-Awesome#5614] opened 2015-02-08 05:07 UTC
Hi an use case for the money-box icon is for example in cases where you want to say you are saving money, or when you are obtaining a discount in a product, I would like to get that money-box (pork) in front of the price of the product

Thank you!

**Comment by tagliala** [comment] 2015-02-08 15:05
duplicate of #1413 , please +1 that request

closing here

**Closed by tagliala** 2015-02-08 15:05 UTC
