### ISSUE TITLE
Icon request: Bancontact (European Payment Icon)

### ISSUE THREAD

**Issue by larsjarred9** [FortAwesome/Font-Awesome#16563] opened 2020-05-01 14:02 UTC
**What can it be used for?**
It can be used to mark the payment provider Bancontant.

**Example image (optional)**
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Bancontact_logo.svg/1200px-Bancontact_logo.svg.png

**Icon request checklist**
- [X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X ] I have included at least one example image if it could be helpful (optional)
- [X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-01 14:35
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #4817?

**Comment by larsjarred9** [comment] 2020-05-01 15:48
This is indeed a duplicate. But it is rebranded to Bancontact and is no longer mr cash. (This is why I could not find it in icon requestions).

**Comment by tagliala** [comment] 2020-05-01 15:57
Thanks, will edit #4817

**Closed by tagliala** 2020-05-01 15:57 UTC
Labels: waiting for feedback
