### ISSUE TITLE
Icon Request: fa-nonprofit (heart in hand)

### ISSUE THREAD

**Issue by EBonar** [FortAwesome/Font-Awesome#6991] opened 2015-07-20 14:00 UTC
I would like to use it on an Industries Served page in a website, http://dev.colormixgraphics.com/industries-served/
![nonprofiticon_proof1](https://cloud.githubusercontent.com/assets/11934450/8777477/d44337ec-2ebd-11e5-804f-1f390fd3ebe6.png)

Thank you for your consideration.
Ebonar

**Comment by tuxy** [comment] 2015-07-23 00:38
alternative fa-nonprofit icon:

![Alt NonProfit](http://i.imgur.com/Sl0MB0l.png)
Source: http://www.flaticon.com/free-icon/give-love_67410

**Comment by tagliala** [comment] 2015-07-23 10:00
almost a duplicate of #2224

**Comment by tuxy** [comment] 2015-07-24 04:13
@tagliala, No because #2224 is only fa-open-hand and does not include a heart. Which can be assosiated with non-profit organizations. It can also be a fa-heart-dove "bird in the heart" icon.

More examples; https://encrypted.google.com/search?q=non+profit+organization+symbol+hand+heart&source=lnms&tbm=isch

**Comment by EBonar** [comment] 2015-07-24 13:22
@tuxy Thank you!

**Comment by tagliala** [comment] 2015-07-26 13:33
@tuxy thanks for the clarification

**Comment by chtay1** [comment] 2016-01-18 05:16
+1

**Comment by bennyp123** [comment] 2016-05-07 20:39
+1

**Comment by alexdahlmandrm** [comment] 2016-12-29 20:39
+1. Any work on this?

**Comment by sensibleworld** [comment] 2018-03-28 17:30
Released in 5.0.9

**Closed by sensibleworld** 2018-03-28 17:30 UTC
Labels: coming soon, new icon, web application icons
