### ISSUE TITLE
Icon request: icon-infinity

### ISSUE THREAD

**Issue by GustelDE** [FortAwesome/Font-Awesome#10805] opened 2017-03-18 10:53 UTC
Hi, the - mathematical - infinty symbol is missing.
A well used and well known symbol - as well in the photography community.

For reference:
https://www.google.com/search?q=aperture+icon&client=firefox-b&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiB3qT08N_SAhXDuRQKHSdgBroQ_AUIBigB&biw=1920&bih=1059#tbm=isch&q=infinity+symbol&*

**Comment by tagliala** [comment] 2017-03-18 10:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1647 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-18 10:56 UTC
