### ISSUE TITLE
Icon request: fa-ref-no

### ISSUE THREAD

**Issue by ivantcholakov** [FortAwesome/Font-Awesome#6598] opened 2015-05-29 23:18 UTC
An icon for reference number. I could use #-sign for example, but the style would not be identical to an icon.

**Comment by tagliala** [comment] 2015-06-07 12:31
probably a duplicate of #1123 , please +1 that request

closing here

feel free to comment if I didn't get the request

**Closed by tagliala** 2015-06-07 12:31 UTC
