### ISSUE TITLE
Icon Request: fa-export

### ISSUE THREAD

**Issue by spyter** [FortAwesome/Font-Awesome#8773] opened 2016-03-17 12:53 UTC
There are a lot of ways to represent exporting so the icon to me really doesn't matter as long as it conveys the message. 

You might have a better idea in mind, but here is an example of an export icon I found on the web.

http://uxrepo.com/static/icon-sets/typicons/svg/export.svg

Awesome job on your icon pack by the way! Absolutely love it :)

**Comment by tagliala** [comment] 2016-03-17 13:04
duplicate of #1020 , planned for 5.0.0 but please +1 that request

closing here

**Closed by tagliala** 2016-03-17 13:04 UTC
