### ISSUE TITLE
Icon request: icon-milk-bottle

### ISSUE THREAD

**Issue by jevijevi** [FortAwesome/Font-Awesome#20363] opened 2024-09-23 08:36 UTC
Hallo i would like to request an icon of a milk bottle like the one in the image i attached

thanx!

![milk-bottle](https://github.com/user-attachments/assets/e3da7f02-3c18-4c08-8ea7-081008410146)

**Comment by alexdgs** [comment] 2024-11-01 18:48
I think a half-filled [bottle-droplet](https://fontawesome.com/icons/bottle-droplet?f=classic&s=solid) could do the job, but I must admit that a milk bottle has a very particular shape though.

**Comment by tagliala** [comment] 2024-11-01 19:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3663, which has been accepted, so no need to add a 👍 reaction to that request.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2024-11-01 19:12 UTC
