### ISSUE TITLE
Icon Request: fa-robot

### ISSUE THREAD

**Issue by samiles** [FortAwesome/Font-Awesome#9425] opened 2016-06-20 10:19 UTC
Hi! I'd love to see a robot, or something that can represent automation and/or AI.

Right now, there is fa-android, but he is of course the Android logo - and is really more alien looking that robotic, and probably best not to use him unless it's specifically Android.

A lot of web apps have automatic functions, processes which run in the background etc, and these can be represented by robots. One possible alternative is the magic wand icon, which is a good way of showing automatic/'automagic' processes.

Thanks!

**Comment by leecollings** [comment] 2016-06-20 10:54
You could try using `fa-cogs` for an automation type icon? http://fontawesome.io/icon/cogs/

**Comment by tagliala** [comment] 2016-06-20 12:18
Duplicate of #519, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-20 12:18 UTC

**Comment by YelloW22** [comment] 2016-06-27 15:14
+1

**Comment by mcfaith9** [comment] 2018-01-03 06:40
recommended

**Comment by SimiCode** [comment] 2018-05-02 15:02
Needed
