### ISSUE TITLE
Icon request: wheelie_chair

### ISSUE THREAD

**Issue by alicemp1** [FortAwesome/Font-Awesome#11148] opened 2017-06-08 11:54 UTC

**Comment by tagliala** [comment] 2017-06-08 13:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3984, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-08 13:11 UTC
