### ISSUE TITLE
Icon request : fa-php

### ISSUE THREAD

**Issue by SSGhost63** [FortAwesome/Font-Awesome#9182] opened 2016-05-12 08:35 UTC
Used to display PHP logo
![php-med-trans-light](https://cloud.githubusercontent.com/assets/2691392/15208688/36011acc-182d-11e6-8858-cc8329a6040d.gif)

**Comment by tagliala** [comment] 2016-05-12 08:41
Duplicate of #1420 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-12 08:41 UTC
