### ISSUE TITLE
Icon Request: fa-support

### ISSUE THREAD

**Issue by saguiitay** [FortAwesome/Font-Awesome#6062] opened 2015-03-26 09:21 UTC
Something like this one: https://cdn1.iconfinder.com/data/icons/windows-8-metro-style/512/online_support.png

Useful for linking to a support page

**Comment by dngunraj** [comment] 2015-03-26 19:29
+1

**Comment by tagliala** [comment] 2015-03-28 17:43
duplicate of #5586 or #1146  , please +1 those requests

closing here

**Closed by tagliala** 2015-03-28 17:43 UTC
