### ISSUE TITLE
Icon Request: syringe

### ISSUE THREAD

**Issue by pl21** [FortAwesome/Font-Awesome#9201] opened 2016-05-13 10:38 UTC
I plan to use this icon for the tab in the pharma application with my drugs.
It will be the info for the user, that he/she takes the injection of the medication.

**Comment by tagliala** [comment] 2016-05-13 11:20
Duplicate of #1779 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-13 11:20 UTC
