### ISSUE TITLE
Icon request: fa-gameplan

### ISSUE THREAD

**Issue by aidenguinnip** [FortAwesome/Font-Awesome#19065] opened 2022-05-23 18:52 UTC
### Use case

Description/Background: The X and O drawings used to depict the play that is being planned, usually for a sports game, such as football or soccer.

Sports use-case: The offensive or defensive game plan/play
Business/other use-case: The plan of action for a scenario

Example keywords: planning, plan, scenario, strategy

### Example image

![image](https://user-images.githubusercontent.com/9369962/169885989-44cf4384-6910-4776-ae0d-2cb7b99f8bde.png)   ![image](https://user-images.githubusercontent.com/9369962/169886097-889df330-4473-42dd-b74a-1ae76be0a1fc.png)   ![image](https://user-images.githubusercontent.com/9369962/169886119-81452798-d79f-4145-be94-a138e5c06d42.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2022-05-23 19:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9659, please add a 👍 reaction to that request.

Closing here

**Closed as completed by tagliala** 2022-05-23 19:58 UTC
Labels: new icon
