### ISSUE TITLE
Icon Request: fa-brain

### ISSUE THREAD

**Issue by mehooman** [FortAwesome/Font-Awesome#12379] opened 2018-02-16 21:32 UTC
brain, thinking, imagining...
Thanks :)

**Comment by tagliala** [comment] 2018-02-17 09:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2075 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-17 09:48 UTC
