### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by rousemw** [FortAwesome/Font-Awesome#12912] opened 2018-04-19 12:17 UTC
### What can it be used for?

University websites
### Example image (optional)

![image](https://user-images.githubusercontent.com/38332336/38990934-14dc45ce-43aa-11e8-8425-8bf4f9166874.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-19 12:24
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1379, please add a 👍  reaction to that request.

>   I have searched for existing issues and to the best of my knowledge this is not a duplicate

No problem 👍 


Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-19 12:24 UTC
