### ISSUE TITLE
Icon request : nodes and links in a tree

### ISSUE THREAD

**Issue by fluidlog** [FortAwesome/Font-Awesome#7047] opened 2015-07-26 16:06 UTC
Hi,

I use "selected radio" to represent "focus+context" representation of a graph in a tree, but I search a more appropriate icon for that.
It's near to that : http://cdn.flaticon.com/png/256/26051.png
But more like this one : https://cdn1.iconfinder.com/data/icons/dotted-charts/512/links_diagram-128.png
With on node on the center and three or four nodes linked to the center node around.

Is it possible ?

Thank you very much !

Yannick

(I use Semantic UI)

**Comment by tagliala** [comment] 2015-07-26 20:07
I would like a better title for this request

**Comment by fluidlog** [comment] 2015-07-27 07:11
ok, do you have an exemple ? More short ? more details ?
Thanks

**Comment by tvirelli** [comment] 2015-08-05 17:08
How about fa-nodes or fa-hub

**Comment by tagliala** [comment] 2015-08-05 17:19
maybe a duplicate of #5944 ?

**Comment by tvirelli** [comment] 2015-08-05 17:47
@tagliala Yep! I think that icon would work perfect!

**Comment by tagliala** [comment] 2022-03-13 14:38
Cleaning up some old issues

Duplicate of #5944 (closed in 5.4.0)

**Closed by tagliala** 2022-03-13 14:38 UTC
Labels: new icon, web application icons, waiting for feedback
