### ISSUE TITLE
Icon Request: fa-coins

### ISSUE THREAD

**Issue by maartenvsp** [FortAwesome/Font-Awesome#10279] opened 2016-11-25 15:01 UTC
since, all money related icons (except for currency's) refer to bank notes, coins would be nice

![image](https://cloud.githubusercontent.com/assets/23741998/20628781/53663dc2-b328-11e6-9158-ae37187464c9.png)

**Comment by tagliala** [comment] 2016-11-25 17:27
Duplicate of #1400 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-25 17:27 UTC
