### ISSUE TITLE
Icon Request: fa-crime

### ISSUE THREAD

**Issue by JeffShaffer** [FortAwesome/Font-Awesome#6094] opened 2015-03-29 06:18 UTC
I would like to request a series of icons to represent crime. Specifically, "shotgun", "knife", "handcuffs", "pistol", "burglar". I am working on integrating a Javascript UI with Tableau for a cool user interface for a crime dashboard. This would be part of a presentation at the next Tableau Customer Conference.

An example of the icons would be something like this dashboard.
http://public.tableausoftware.com/views/ACincinnatiCrimeVisualization/KeyStatistics?:embed=y&:showTabs=y&:display_count=yes

Thank you in advance for time and consideration.

Jeff

**Comment by tagliala** [comment] 2015-03-29 18:26
Hi,

gun is a duplicate of #3888 , please +1 that request

Sorry but I can't keep this request open. As per our [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons) you should split in individual requests, even if in your use case you need all of them

I should also advise you to consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2015-03-29 18:26 UTC
