### ISSUE TITLE
Icon Request: fa-pill/fa-syringe

### ISSUE THREAD

**Issue by JohnDelmar** [FortAwesome/Font-Awesome#11000] opened 2017-04-27 15:10 UTC
Hi.
My request is related with "Medical Icons", i'm working on a medical web application and I need some icons related with "prescriptions", something like a "Pill" and a "Syringe" and even another third icon to represent a physical "prescription", something like a "list" or "clipboard" with a "pill" or a "syringe".

Thanks

**Comment by tagliala** [comment] 2017-04-27 15:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1778 and #1779 , please add a 👍  reaction to those requests.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-27 15:52 UTC
