### ISSUE TITLE
Icon Request: fa-gold

### ISSUE THREAD

**Issue by dchara01** [FortAwesome/Font-Awesome#8141] opened 2015-12-10 23:49 UTC
It will be useful for financial websites.
![gold-128](https://cloud.githubusercontent.com/assets/10142016/11732064/5a789012-9fa9-11e5-93e1-7c12195cf034.png)
![gold-129](https://cloud.githubusercontent.com/assets/10142016/11732065/5a81ebc6-9fa9-11e5-86ac-21739d754efc.png)

**Comment by tagliala** [comment] 2015-12-11 09:14
duplicate of #7729 , please +1 that request

closing here

**Closed by tagliala** 2015-12-11 09:14 UTC

**Comment by dchara01** [comment] 2015-12-11 09:37
sorry to bother, but how do i 1+ it?

**Comment by tagliala** [comment] 2015-12-11 11:59
@dchara01 simply leave a comment there :)

**Comment by dchara01** [comment] 2015-12-11 12:17
thank you :)

**Comment by butchero** [comment] 2016-03-11 09:39
I need it also for an exchange rates website. + 1 also :)

**Comment by irsh5** [comment] 2016-03-23 06:10
Please Add this in your library...

**Comment by khasky** [comment] 2016-04-24 14:02
+1

**Comment by tagliala** [comment] 2016-04-24 14:15
locking here because this is a duplicate of #7729
