### ISSUE TITLE
Icon request: icon-car

### ISSUE THREAD

**Issue by AmitP88** [FortAwesome/Font-Awesome#9839] opened 2016-08-30 22:45 UTC
Hello,

I would like to request an icon character for Udacity. I have an image of the logo
below:

![udacity](https://cloud.githubusercontent.com/assets/12392775/18109622/5fd8b8c8-6ec7-11e6-8545-b8f2a042d97b.png)

I would like to have the icon be similar in style to the github icon you guys created here: http://fontawesome.io/icon/github/

in that there's no box around it, it's just the U letter in the same style as the logo above. 

I know that there's already a "U" icon found here: http://fontawesome.io/icon/underline/

but I would really like a U icon that matches the logo above, as it represents Udacity.

I mainly want to use this icon for my portfolio site (as well as other projects that I'll link to my Udacity profile), and I also think that other students/graduates from the Udacity program can also benefit from this icon as well for their projects. If you make this icon, I will be more than happy to post on the Udacity forums and refer more people to using your icons, as they are awesome :)

Anyways, thank you so much for providing excellent content, I greatly appreciate it.

Sincerely,

Amit

**Comment by lucanos** [comment] 2016-08-31 09:06
Why is this request tagged as "icon-car" when it is for an online educational facility?

Also, here is a bigger/better version of the Logo image.
![image](https://cloud.githubusercontent.com/assets/126774/18122690/f549a656-6fad-11e6-92c6-75bbe0662e30.png)

**Comment by tagliala** [comment] 2016-08-31 10:57
Duplicate of #8477?

**Comment by AmitP88** [comment] 2016-08-31 13:02
Sorry, I thought "icon-car" meant icon character. I miss interpreted it.

As for the duplicate of #8477, I meant that it was also a "U" icon on font awesome, but just a different style, if that makes sense.

**Comment by tagliala** [comment] 2016-08-31 14:01
Closing here as a duplicate, please 👍  #8477

**Closed by tagliala** 2016-08-31 14:01 UTC
Labels: waiting for feedback
