### ISSUE TITLE
excessive padding around fa-angle-up and fa-angle-down

### ISSUE THREAD

**Issue by Howon** [FortAwesome/Font-Awesome#6752] opened 2015-06-14 14:38 UTC
Not sure if why this is so but excessive padding above and below angled arrow up and down causes inconvenience when these are used withevent handlers in javascript.

![screen shot 2015-06-14 at 11 34 18 pm](https://cloud.githubusercontent.com/assets/8075728/8148950/052ce8ee-12ee-11e5-8c9f-a60af541bd86.png)
![screen shot 2015-06-14 at 11 34 28 pm](https://cloud.githubusercontent.com/assets/8075728/8148951/068f35e8-12ee-11e5-8f4d-6937c535c8f0.png)
compared to
![screen shot 2015-06-14 at 11 34 58 pm](https://cloud.githubusercontent.com/assets/8075728/8148955/0a5e80d4-12ee-11e5-8ef8-a67fd42b50b1.png)
![screen shot 2015-06-14 at 11 35 06 pm](https://cloud.githubusercontent.com/assets/8075728/8148956/0b7d9586-12ee-11e5-8810-7a0787eeb3f8.png)
when same css properties were applied (vertical padding around angled arrows cannot be adjusted).

Is there any fix, and if not can this be adjusted?

Thank you!

**Comment by tagliala** [comment] 2015-06-14 16:30
there might be issues in the horizontal padding, since fontawesome does not use same width icons by default (you should add `fa-fw` class)

I can't confirm your issue: http://jsfiddle.net/tagliala/exj79ry2/

Could you please provide a fiddle that reproduces your issue?

**Comment by Howon** [comment] 2015-06-14 16:53
well my concern was more with angled arrows occupying more space than their actual graphics
for example
http://jsfiddle.net/tagliala/exj79ry2/
![screen shot 2015-06-15 at 1 50 50 am](https://cloud.githubusercontent.com/assets/8075728/8149533/fa9075c8-1300-11e5-8c01-c6dddacb05fc.png)
these two type arrows occupy same width/height, which agrees with your jfiddle and makes sense.
But when a user sees these two icons wouldn't it be a bit weird that there are extra spaces above and below the angled arrow whereas the normal ones do not?

**Comment by tagliala** [comment] 2015-06-14 19:05
what is your suggestion?

**Comment by Howon** [comment] 2015-06-18 05:55
I am not sure how each font is designed and implemented in fortawesome, but I guess some of the excess vertical space could be trimmed a bit?

**Comment by tagliala** [comment] 2015-06-18 08:12
maybe I got your point.

You should play with `line-height` css property

**Comment by tagliala** [comment] 2018-05-14 15:49
Hi,

now that FA 5.0 is out, I can confirm that icons have all the same height also in their original SVG version by design choice.

You need custom css rules in both versions (SVG and CSS) to avoid extra white spaces above and below icons.

Otherwise, you could process the [individual .svg files](https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/raw-svg/solid/angle-up.svg) to get rid of space: 

Hope it helps

Closing here

**Closed by tagliala** 2018-05-14 15:49 UTC
Labels: css, question
