### ISSUE TITLE
Icon request: Calendar-dollar

### ISSUE THREAD

**Issue by blalan05** [FortAwesome/Font-Awesome#19073] opened 2022-05-25 16:12 UTC
### Use case

icon for bill due date. 

### Example image

![calendar-dollar](https://user-images.githubusercontent.com/42892508/170308579-de497eb8-38b0-4cab-a353-7a9854789450.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by aethior** [comment] 2023-03-11 12:46
Duplicate of #15047

cc/ @tagliala

**Closed as completed** 2023-03-11 13:18 UTC
Labels: new icon, business (category)
