### ISSUE TITLE
Icon Request: icon-television icon-radio

### ISSUE THREAD

**Issue by benosey** [FortAwesome/Font-Awesome#7021] opened 2015-07-23 10:17 UTC
be fantastic if these could be created, we already use a selection of font awesome icons.....

Old style tv  old style radio
![tv](https://cloud.githubusercontent.com/assets/2742094/8848077/69a0dcc0-312c-11e5-8aad-797b4d871d5d.png)
![radio](https://cloud.githubusercontent.com/assets/2742094/8848080/6d693c62-312c-11e5-9e34-c82c7c286af1.png)

**Comment by tagliala** [comment] 2015-07-23 10:19
tv is a duplicate of #368 , please +1 that request
radio is a duplicate of #892, please +1 that request

all dups, closing here

**Closed by tagliala** 2015-07-23 10:19 UTC

**Comment by benosey** [comment] 2015-07-23 10:21
Hi   that was 3 years ago though,  was hoping a developer could create one  :-)

**Comment by tagliala** [comment] 2015-07-23 10:24
@benosey icon-tv is scheduled for 5.0.0 but I haven't a deadline, sorry

if you need the above icons you should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by benosey** [comment] 2015-07-23 10:25
?Ok great I'll keep a look out.......  :-)


lee@nextofkin.com

M: 07581 778899  T: 0207 1 75 75 75

www.nextofkin.com<http://www.nextofkin.com>



[https://1.exchange2013.livemail.co.uk/owa/service.svc/s/GetPersonaPhoto?email=lee%40nextofkin.com&personId=AAQkADMzMWQ3NjM1LTcyMWEtNDY4MS1iYjAzLTc4NzMxNGZkODVhMAAQAJMvK00Z%2FsJEqjtiWej%2BZT0%3D&UA=0&adObjectId=c86cc41d-0e2a-4210-98b7-143d9e8a7197&size=HR96x96&sc=1431077945364]

________________________________
