### ISSUE TITLE
Icon request: icon-freelancer

### ISSUE THREAD

**Issue by larryjam** [FortAwesome/Font-Awesome#9397] opened 2016-06-13 03:42 UTC
Would like to have a Freelancer ( https://www.freelancer.com/ ) brand 
![freelancer](https://cloud.githubusercontent.com/assets/19762047/15996592/5f97b82c-30f7-11e6-9368-d00f1ec72574.jpg)
icon to use on my website as a link to my Freelancer account. I think that this would be a useful icon for the FontAwesome community.

**Comment by tagliala** [comment] 2016-06-13 12:53
Duplicate of #6426, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-13 12:53 UTC
