### ISSUE TITLE
Icon request: Alignable Brand Icon

### ISSUE THREAD

**Issue by angelabatterson** [FortAwesome/Font-Awesome#19392] opened 2022-10-20 15:22 UTC
### Use case

Alignable is a new social networking platform for individuals and businesses. This would be like a social media icon for use on websites for potential customers to connect. 

<img width="56" alt="Screen Shot 2022-10-20 at 11 21 30 AM" src="https://user-images.githubusercontent.com/116292821/196990348-44c87532-bd7d-4335-9154-752347da339f.png">

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2022-10-20 15:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11602, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-10-20 15:30 UTC
Labels: new icon
