### ISSUE TITLE
Icon Request: fa-markdown

### ISSUE THREAD

**Issue by ericrovtar** [FortAwesome/Font-Awesome#11762] opened 2017-11-15 14:20 UTC
I'd love to see a Markdown icon, similar to what we see here on GitHub.

<img width="236" alt="screen shot 2017-11-15 at 9 18 06 am" src="https://user-images.githubusercontent.com/3474545/32840543-f5730bf2-c9e5-11e7-8129-dfe0ad58137a.png">

More info: https://github.com/dcurtis/markdown-mark

**Comment by tagliala** [comment] 2017-11-15 16:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1557, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-15 16:30 UTC
