### ISSUE TITLE
Icon Request: fa-spice

### ISSUE THREAD

**Issue by tarunaggarwal54** [FortAwesome/Font-Awesome#9211] opened 2016-05-14 08:52 UTC
I am developing a online grocery store in which I need icons related to grocery.
![spices](https://cloud.githubusercontent.com/assets/19358761/15267414/4aa3586a-19df-11e6-84e2-01dbe543022e.png)

**Comment by tagliala** [comment] 2016-05-14 10:17
Duplicate of #1684, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-14 10:17 UTC
