### ISSUE TITLE
Icon Request: fa-vip

### ISSUE THREAD

**Issue by elmcherqui** [FortAwesome/Font-Awesome#11914] opened 2017-12-12 09:10 UTC
hello,
Thank you for your awesome library !
We kindly request a new icon to show VIP Members ( Very Important Personnality )

Few Cases (our cases :p ) : 
1- Differentiate between Executives (VIP) and employees with an icon near the image profile.
2- In case of health insurance , mark the medical record  as VIP , so it can be repayed without any check.

here is the icon we are using until there is an equivalent on font-awesome : 

![vip](https://user-images.githubusercontent.com/12566542/33876020-1e2f120c-df1c-11e7-9a24-855e98c2c2fd.jpg)

Thank you in advance for your efforts !

**Comment by tagliala** [comment] 2017-12-12 10:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2862, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-12 10:19 UTC
