### ISSUE TITLE
Icon request: fa-wineglass

### ISSUE THREAD

**Issue by JJ69** [FortAwesome/Font-Awesome#7735] opened 2015-10-21 08:42 UTC
I have 3 new sites under development for 2 x Vineyards & 1 x Wine seller. The current glass icon is more like a cocktail glass and doesn't really work. Is it possible to get a glass more like this one please?
Thank you.
![wine2](https://cloud.githubusercontent.com/assets/15228089/10631764/82405ec0-783c-11e5-8ba1-de49388b6cf2.jpg)

**Comment by webappdesigner** [comment] 2015-10-21 11:07
+1

a wine glass is far more universal than the current 'martini glass' that is in use

**Comment by tagliala** [comment] 2015-10-21 13:16
duplicate of #370, please +1 that request

closing here

**Closed by tagliala** 2015-10-21 13:16 UTC
