### ISSUE TITLE
Icon request: fa-webmoney

### ISSUE THREAD

**Issue by dillix** [FortAwesome/Font-Awesome#8794] opened 2016-03-20 13:30 UTC
It would be nice if you will add WebMoney ball symbol. Vector .EPS can be downloaded here: http://www.webmoney.ru/eng/developers/logos.shtml

WebMoney is a largest Russian online payment system.

**Comment by tagliala** [comment] 2016-03-20 14:35
duplicate of #4494, please +1 that request

closing here

**Closed by tagliala** 2016-03-20 14:35 UTC
