### ISSUE TITLE
Back Camera icon

### ISSUE THREAD

**Issue by rcvangemert** [FortAwesome/Font-Awesome#6546] opened 2015-05-24 07:11 UTC
love your work,

A camera back icon would be nice. A duplicate pointing left will be fine.

-rvg

**Comment by tagliala** [comment] 2015-05-24 10:51
sorry I didn't get this request

It may be a duplicate of #3956

**Comment by rcvangemert** [comment] 2015-05-24 11:29
#3956 could be used to switch between front and back cams, which could be very usefull.
But, my need is to select front or back directly. A simple mirror of fa-video-camera would be ok. 
seperate icons are desirable for speed, may not have back caera eg slate 21 and on newer devices both camera can be used (so i am told!)
Currently i use:
  { "\uf060", "", "\uf061", "\uf00d" },  // cam
  
    
On 24/05/2015 8:51 PM, Geremia Taglialatela <notifications@github.com> wrote:sorry I didn't get this request

It may be a duplicate of #3956

**Comment by sensibleworld** [comment] 2021-09-29 15:14
https://fontawesome.com/v6.0/icons/camera-rotate?s=solid

For the video camera facing the other direction, that can be accomplished using our fa-flip-h class. https://fontawesome.com/v6.0/docs/web/style/power-transform#rotating-and-flipping

**Closed by sensibleworld** 2021-09-29 15:14 UTC
Labels: waiting for feedback
