### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by kajoomla** [FortAwesome/Font-Awesome#8827] opened 2016-03-25 08:04 UTC
Icon request: icon-blab 

To be used in social media icon set similar to twitter, facebook, etc.

![blab25](https://cloud.githubusercontent.com/assets/12817396/14040522/59a78926-f225-11e5-9ca6-2d866898d167.png)
![blab250bw](https://cloud.githubusercontent.com/assets/12817396/14040523/59abf038-f225-11e5-97f8-313cd85d40cb.png)

**Comment by kajoomla** [comment] 2016-03-25 08:05
Blab is new social community merging live video, conferencing and twitter.  www.blab.im

thanks

**Comment by tagliala** [comment] 2016-03-25 11:39
Duplicate of #7841, please +1 that request

closing here

**Closed by tagliala** 2016-03-25 11:39 UTC
