### ISSUE TITLE
Icons not showing on iOS Safari

### ISSUE THREAD

**Issue by anquinn** [FortAwesome/Font-Awesome#7861] opened 2015-11-10 00:24 UTC
Yet another squares issue, but I've tried self hosting, the CDN and the Sass gem. They display fine on all other browsers but iOS continues to display squares. Even the iOS simulator shows squares.

Icons display fine in all other browsers.

**Comment by tagliala** [comment] 2015-11-13 20:56
as you know, this is a duplicate of #7770

**Closed by tagliala** 2015-11-13 20:56 UTC

**Comment by wendelsodres** [comment] 2017-07-16 19:02
Utilize onde conter a font aplicada.
text-rendering: optimizeLegibility;

ex: 
.icone a:before{
		font-family: 'FontAwesome';
		content: '\f0c9';
		margin-right: 10px;
		font-size: 1.2rem;
		font-weight: 600;
		**text-rendering: optimizeLegibility;**
	}
