### ISSUE TITLE
Icon request: weight

### ISSUE THREAD

**Issue by szymsza** [FortAwesome/Font-Awesome#11311] opened 2017-07-19 21:25 UTC
It would be great to have something that represents weight of an object. This could be used for example as weight of a product in e-shops or even weight of a person in some kind of database.

This is something that I'm looking for
![Weight image](https://s18.postimg.org/fpclaf9fd/black-weight-512.png)

I was really surprised when I couldn't find anything like this in FA since this is one of the most basic icons for creating e-shops.

Thank you for considering my request!

**Comment by tagliala** [comment] 2017-07-20 08:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2735 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-20 08:33 UTC
