### ISSUE TITLE
icon request: icon-collaboration

### ISSUE THREAD

**Issue by eX00r** [FortAwesome/Font-Awesome#9930] opened 2016-09-18 14:18 UTC
Could be two shaking hands like the ones attached

[handshakemini](https://cloud.githubusercontent.com/assets/10723825/18616414/79e74dbc-7dbb-11e6-98db-29ab4684681c.jpg)

**Comment by tagliala** [comment] 2016-09-18 14:32
Duplicate of  #878, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-18 14:32 UTC
