### ISSUE TITLE
Icon request: Parler.com 

### ISSUE THREAD

**Issue by durangod** [FortAwesome/Font-Awesome#17415] opened 2020-11-18 17:38 UTC
**What can it be used for?**
Parler.com is supposed to be the alternative to twitter.  The news said it is growling leaps and bounds. 
They have a cool icon. 

**Example image (optional)**
you can see it at parler.com

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
Single

- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
yes

- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
i searched parler and found nothing

- [ ] I have included at least one example image if it could be helpful (optional)
no

- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
you lost me, i have no clue what this has to do with a concrete object lol 

I assume you need to get their permission which is why i am submitting this so you can start the process.

**Comment by tagliala** [comment] 2020-11-18 17:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16275, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-11-18 17:57 UTC
