### ISSUE TITLE
Icon request: gmail

### ISSUE THREAD

**Issue by mkollarc** [FortAwesome/Font-Awesome#15444] opened 2019-08-28 09:53 UTC
This icon is for Gmail references and integrations. 

Example image 
![image](https://user-images.githubusercontent.com/54618801/63845533-ac1b0f80-c9bc-11e9-9d37-e2e03e4d2aee.png)

**Comment by tagliala** [comment] 2019-08-28 11:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4655, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-08-28 11:33 UTC
