### ISSUE TITLE
Icon request: icon-firefox-browser, icon-ie-browser, icon-chrome-browser, icon-opera-browser, icon-safari-browser

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [FortAwesome/Font-Awesome#6602] opened 2015-05-30 22:16 UTC
Common Browser Icons would be nice. :) 

Usage: Use them in tables that display which browsers are supported for example or other browser-specific info on a webpage etc.

![browser-icons](https://cloud.githubusercontent.com/assets/3524165/7899607/3ca5d7d8-072a-11e5-8eff-63b1d5ac2bfd.jpeg)

Thanks!

**Comment by tagliala** [comment] 2015-05-31 12:32
duplicate of #219 , please +1 that request

closing here

**Closed by tagliala** 2015-05-31 12:32 UTC
