### ISSUE TITLE
Icon Request: fa-tunein

### ISSUE THREAD

**Issue by Shad0wGeneral** [FortAwesome/Font-Awesome#5367] opened 2015-01-09 21:36 UTC
Hi there just hoping to get a icon for the Service Tunein it would come in handy for my website based for a radio station.
Here is there logo.
![](http://www.altsportstalk.com/wp-content/uploads/2014/06/TuneIn_logo_teal_1024.png)

**Comment by tagliala** [comment] 2015-01-09 21:41
duplicate of #3159, please +1 that request

closing here

**Closed by tagliala** 2015-01-09 21:41 UTC
