### ISSUE TITLE
Icon Request: fa-check-undetermined

### ISSUE THREAD

**Issue by JD-Robbs** [FortAwesome/Font-Awesome#6840] opened 2015-06-29 10:45 UTC
Howdy lovely people,

I wonder if an additional icon called, `check-undetermined` (or similar), would be useful.

Essentially, it is `square-o`, but with a solid square inside (a small transparent border around that, and then the outer border of `square-o`). It would simply be `square-o` with `square` in the center.

This may be useful for, for instance, tree views where some (but not all) nodes of a parent  are checked. The parent node would make use of `check-undetermined`, unless all/no children are selected.

The same could be used in tables with batch-processing checkboxes. Where some, but not all, rows are selected, `check-undetermined` comes to play in the header.

What'cha think? :smiley:

**Comment by tagliala** [comment] 2015-06-29 21:13
Like the one in the middle?

https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Checkbox_States.svg/2000px-Checkbox_States.svg.png

**Comment by JD-Robbs** [comment] 2015-06-29 22:37
Hi tagliala, 

Yes — like the one in the middle. Apologies, I meant to attach an example.

**Comment by tagliala** [comment] 2016-12-13 10:01
Duplicate of #2055 🔒

**Closed by tagliala** 2016-12-13 10:01 UTC
Labels: form control icons, new icon
