### ISSUE TITLE
Icon Request: fa-bilibili

### ISSUE THREAD

**Issue by Yaerin** [FortAwesome/Font-Awesome#11358] opened 2017-08-05 15:49 UTC
[Bilibili](Bilibili) is a video site like [niconico.jp](niconico.jp)
Logo can be found on [https://www.bilibili.com/favicon.ico](https://www.bilibili.com/favicon.ico)
Thanks!

**Comment by tagliala** [comment] 2017-08-05 19:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9789, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-05 19:52 UTC
