### ISSUE TITLE
Icon Request: fa-ski-centre

### ISSUE THREAD

**Issue by monikazam** [FortAwesome/Font-Awesome#10764] opened 2017-03-09 08:17 UTC
Hi Font-Awesome,
I would like to request new icon for my web project. Icon for ski center. (see attachment). I am going to use the map with different icons and just ski center is missing on font-awesome. 
[ski-centre.zip](https://github.com/FortAwesome/Font-Awesome/files/830147/ski-centre.zip)

In attachment you can find vector of icon map.ai and example of using.

Thank you for help. I appreciate your work.
Monika

**Comment by monikazam** [comment] 2017-03-09 08:22
![ski-center](https://cloud.githubusercontent.com/assets/26296585/23741668/ecea5dde-04a9-11e7-8fb0-9b4e82e1c543.png)

**Comment by tagliala** [comment] 2017-03-09 10:36
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #6878, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-09 10:36 UTC

**Comment by futureweb** [comment] 2018-03-16 16:35
+1
