### ISSUE TITLE
Icon Request: fa-donation

### ISSUE THREAD

**Issue by jasoncsking** [FortAwesome/Font-Awesome#10170] opened 2016-11-04 21:44 UTC
A donation icon. Would be appreciated for non-profits' websites.

**Comment by tagliala** [comment] 2016-11-05 14:44
Duplicate of #2224, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-05 14:44 UTC
