### ISSUE TITLE
Spring Boot

### ISSUE THREAD

**Issue by iamsde836869** [FortAwesome/Font-Awesome#18422] opened 2021-11-08 19:19 UTC
Spring Boot icon
Django Icon
all the other tools, Frameworks icon not available.

**Comment by tagliala** [comment] 2021-11-08 19:25
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If Spring Boot is a single icon, please provide an example and more information about this brand

If Spring is a request for spring.io, then it is a duplicate of #7397, please add a 👍🏼 reaction to that request

Django is a duplicate of #3805, please add a 👍🏼 reaction to that request

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2021-11-08 19:25 UTC
