### ISSUE TITLE
Icon request: icon-pool

### ISSUE THREAD

**Issue by fleurdr** [FortAwesome/Font-Awesome#11709] opened 2017-11-03 13:58 UTC
An icon for the presence of a swimming pool would be really useful for all websites related to tourism like hotels, vacation rentals and holiday homes but also comunal services etc

**Comment by PeterShaggyNoble** [comment] 2017-11-03 14:06
This is a duplicate of #3285, you should give that a 👍 instead.

**Comment by tagliala** [comment] 2017-11-03 14:42
@PeterShaggyNoble thanks, really appreciate

**Closed by tagliala** 2017-11-03 14:42 UTC
