### ISSUE TITLE
Icon request: tailwindcss icon

### ISSUE THREAD

**Issue by Sanket-Gawande** [FortAwesome/Font-Awesome#19323] opened 2022-09-07 17:43 UTC
tailwindcss is on peak nowdays  , while searching icons for react nodejs i found that there isn't this one .

**Comment by Sanket-Gawande** [comment] 2022-09-07 17:43
-

**Comment by tagliala** [comment] 2022-09-08 08:40
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15389, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-09-08 08:40 UTC
