### ISSUE TITLE
Icon Request: fa-logical-and, fa-logical-nand, fa-logical-or, fa-logical-not

### ISSUE THREAD

**Issue by victorsoliveira** [FortAwesome/Font-Awesome#4983] opened 2014-11-14 13:37 UTC
Hi,

I have a project that i use font awesome and i need logical port icons, first 4 icons resolve for me.

I've attached an image below to show u what i need.

![gates](https://cloud.githubusercontent.com/assets/1494145/5046485/65818202-6bf2-11e4-99ed-12da1cdb704d.gif)

Tanks a lot!

**Comment by ThePhoenixRiseth** [comment] 2016-07-14 19:58
+1

**Comment by sensibleworld** [comment] 2024-07-11 13:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/9437)

**Closed by sensibleworld** 2024-07-11 13:33 UTC
Labels: new icon, web application icons (legacy category), Duplicate
