### ISSUE TITLE
Icon request: icon-eye-of-providence

### ISSUE THREAD

**Issue by esotericast** [FortAwesome/Font-Awesome#8546] opened 2016-02-12 04:50 UTC
Would be cool to get this symbol made into an icon!

![eye of providence](https://cloud.githubusercontent.com/assets/12773556/12999169/2e96360a-d11a-11e5-8b2d-119e39392cc1.png)

**Comment by tagliala** [comment] 2016-02-12 10:47
is this a duplicate of #5713?

**Comment by ktoump** [comment] 2016-02-13 21:29
nope
https://en.wikipedia.org/wiki/Eye_of_Providence
https://en.wikipedia.org/wiki/Eye_of_Horus

**Closed** 2022-03-13 15:07 UTC
Labels: waiting for feedback
