### ISSUE TITLE
Icon request: icon-tape-recorder

### ISSUE THREAD

**Issue by renebigot** [FortAwesome/Font-Awesome#8186] opened 2015-12-19 22:15 UTC
Hello,

I've search a tape recorder icon in the icons list and in the github requests and haven't found something like this.

In an application I'm developing, users stream audio from their microphone (fa-microphone as icon) or from a pre-saved sound file. It could be great if I could use a tape recorder icon for this use-case. 

Below, an example from iconfinder.com:
<img src="https://cdn3.iconfinder.com/data/icons/pyconic-icons-2-1/512/recorder-512.png">

Cheers,

René

**Comment by richardtallent** [comment] 2015-12-20 02:21
Hmm... off the top of my head, it seems like `toggle-right`, `play`, `play-circle`, or `play-circle-o` would be more useful than such an obscure skeuomorph.

I'd say a cassette tape would make more sense, but I'm not sure that translates well either to anyone under 40.

**Comment by renebigot** [comment] 2015-12-20 05:35
Ouch ! I feel so old right now.. (I'm 33)
:)

The list icon would be better in my case. I'll try to integrate it.

Thanks for your help.

**Comment by tagliala** [comment] 2015-12-20 11:05
cassette tape: #1736 

but this one is a duplicate of: #2637, please +1 that request

closing here

**Closed by tagliala** 2015-12-20 11:05 UTC
