### ISSUE TITLE
Icon-request: fa-card

### ISSUE THREAD

**Issue by richardtallent** [FortAwesome/Font-Awesome#8189] opened 2015-12-20 03:06 UTC
I'm an artist, and my web site allows viewing my work as thumbnails or in a "news feed" view (similar to Instagram or Facebook). I'm using `fa-th` for thumbnails, but there's no good icon for the "feed" view. `fa-bars`, `fa-photo`, and `th-list` aren't a good match. The one I ended up using is `fa-square`, but it's pretty generic.

So I'd like to propose a new icon, `fa-card`, that somewhat resembles a Polaroid photograph -- a square-ish rectangle outline, with a filled rectangle inside, vertically aligned close to the top.

![example-fa-card](https://cloud.githubusercontent.com/assets/2041718/11916252/15d189e0-a694-11e5-9317-30c695105a0a.png)

Both Semantic UI and Google's Material Design refer to this UI convention as a "card," and that seems like a good name since `fa-feed` is already taken for RSS/Atom feeds.

https://www.google.com/design/spec/components/cards.html
http://semantic-ui.com/views/card.html

I suspect this could be useful for many web applications where data are represented as a box with a photograph at the top and text below.

To see my web site in action, go to one of the galleries (http://www.tallent.us/) and look in the "Galleries" drop-down menu. **Please note that my site is NSFW** (nude photography).

**Comment by richardtallent** [comment] 2015-12-20 03:16
I just noticed that this somewhat duplicates #367... apologies, I searched for "polaroid" but missed it somehow.

**Comment by tagliala** [comment] 2015-12-20 11:08
considering this as a duplicate of #367

**Closed by tagliala** 2015-12-20 11:08 UTC
