### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by nagaraju291990** [FortAwesome/Font-Awesome#10737] opened 2017-03-03 10:28 UTC
Requesting an icon for search and replace. This Icon would serve as a resemblance of search and replace.
![screenshot](https://cloud.githubusercontent.com/assets/7310254/23547680/28734930-002a-11e7-8869-12077d975274.png)

**Comment by tagliala** [comment] 2017-03-03 12:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1191, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-03 12:58 UTC
