### ISSUE TITLE
Icon Request: fa-fa rings

### ISSUE THREAD

**Issue by blenki101** [FortAwesome/Font-Awesome#9560] opened 2016-07-13 14:13 UTC
Hi - I need a new icon for rings to represent marriage please !
![rings](https://cloud.githubusercontent.com/assets/14123751/16806431/630dbd80-490c-11e6-98ae-fb2b3949a25e.jpg)

**Comment by tagliala** [comment] 2016-07-13 16:54
duplicate of #3025 , please +1 that request

closing here

**Closed by tagliala** 2016-07-13 16:54 UTC
