### ISSUE TITLE
Icon Request: fa-oil Icon

### ISSUE THREAD

**Issue by travcannon** [FortAwesome/Font-Awesome#11451] opened 2017-08-28 20:33 UTC
I am looking for an Oil Well, Oil Barrel/drum. I am going to use the tint for now.

**Comment by tagliala** [comment] 2017-08-28 20:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8142, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-28 20:59 UTC
