### ISSUE TITLE
new icons

### ISSUE THREAD

**Issue by patrickbaier** [FortAwesome/Font-Awesome#15380] opened 2019-08-15 16:18 UTC
can you make a couple new icons?

-police
-party (celebration) 
-donut
-bakery

**Comment by tagliala** [comment] 2019-08-15 16:34
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

- Police is a duplicate of #3372, please add a 👍 reaction to that request
- Party is probably a duplicate of one of those: https://github.com/FortAwesome/Font-Awesome/search?q=party&type=Issues
- Donut is a duplicate of #10148, please add a 👍 reaction to that request
- Bakery could be already here (in FA Pro https://fontawesome.com/icons?d=gallery&q=bakery)

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2019-08-15 16:34 UTC

**Comment by patrickbaier** [comment] 2019-08-15 17:21
thank you for getting back. how often do you upload new icons?

**Comment by tagliala** [comment] 2019-08-15 17:27
You're welcome!

Please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), there is a lot of information on how requests work
