### ISSUE TITLE
Icon request: icon-hot_dog

### ISSUE THREAD

**Issue by mrStenvik** [FortAwesome/Font-Awesome#10982] opened 2017-04-24 07:16 UTC
Something like this: 

![hot_dog](https://cloud.githubusercontent.com/assets/27947303/25326041/9a3661de-28ce-11e7-96b7-af865cc58b05.JPG)

**Comment by PeterShaggyNoble** [comment] 2017-04-24 08:44
This is a duplicate of #4291, you should give that a 👍 instead.

See #1895 also.

**Closed** 2017-04-24 09:35 UTC
