### ISSUE TITLE
Icon request : fa-elevator

### ISSUE THREAD

**Issue by stefankellens** [FortAwesome/Font-Awesome#8455] opened 2016-01-29 15:26 UTC
Hello

I would like to request a new icon for an elevator.

Example : https://upload.wikimedia.org/wikipedia/commons/3/3e/Elevator_icon.png

Thanks

**Comment by tagliala** [comment] 2016-01-29 16:48
duplicate of #6047, please +1 that request

closing here

**Closed by tagliala** 2016-01-29 16:48 UTC
