### ISSUE TITLE
Icon Request: fa-friends

### ISSUE THREAD

**Issue by pedrohls94** [FortAwesome/Font-Awesome#10973] opened 2017-04-21 13:37 UTC
An icon for "friends" in a social network context.

I imagine something like the icon fa-users, but with only 2 people.
![image](https://cloud.githubusercontent.com/assets/6087076/25279895/60eac138-267e-11e7-9536-e42200fbab8c.png)
For example, facebook's icon:
![image](https://cloud.githubusercontent.com/assets/6087076/25279916/73b95ee6-267e-11e7-8fc0-fa7d29f0d17f.png)

**Comment by tagliala** [comment] 2017-04-21 14:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2883 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-21 14:37 UTC
