### ISSUE TITLE
Icon request: circle-half

### ISSUE THREAD

**Issue by Garconis** [FortAwesome/Font-Awesome#17110] opened 2020-09-02 16:18 UTC
**What can it be used for?**
Similar to the half-star icon, it could be used for "half" of a circle, for ratings, pies, charts, etc. Could also be considered half-moon.

**Example image (optional)**
![768px-U+25D6 svg](https://user-images.githubusercontent.com/8608632/92008983-d1500580-ed15-11ea-9cdd-5e46129936f9.png)

Ideally there would be 4 versions of this:

1. circle-half-top
1. cirle-half-right
1. circle-half-bottom
1. circle-half-left

**Comment by tagliala** [comment] 2020-09-02 20:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #528, please add a 👍 reaction to that request.

We have https://fontawesome.com/icons/adjust?style=solid that may fit this use case

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-02 20:10 UTC
