### ISSUE TITLE
Icon request: icon-target

### ISSUE THREAD

**Issue by BjH14** [FortAwesome/Font-Awesome#12091] opened 2018-01-13 16:00 UTC
Hello !

Would it be possible to have an icon showing an arrow on a target ?
It could represent the idea of "this action aims at..."

Thanks !

**Comment by PeterShaggyNoble** [comment] 2018-01-16 12:47
Duplicate of #5444; you should give that a 👍 instead. And don't forget to search before posting requests.

**Closed** 2018-01-16 13:30 UTC
