### ISSUE TITLE
Icon Request: fa-save-as

### ISSUE THREAD

**Issue by ozgursahin** [FortAwesome/Font-Awesome#7609] opened 2015-10-05 12:00 UTC
Save as icon needed :) Will be used in entity save as scenarios.
![save_all](https://cloud.githubusercontent.com/assets/14977381/10279879/c4ce7d4e-6b71-11e5-9377-490d5154dcaa.png)

**Comment by caduvieira** [comment] 2015-10-05 12:47
dupe of #433
related to #512 #5550
please +1 one of those

**Comment by ozgursahin** [comment] 2015-10-05 12:51
Thank you for your response. Keep up the good work! :)

---- Açık Pzt, 05 Eki 2015 15:47:49 +0300 caduvieira &lt;notifications@github.com&gt; yazıldı ---- 

dupe of #433
 related to #512 #5550
 please +1 one of those

**Comment by tagliala** [comment] 2015-10-05 16:10
closing here

**Closed by tagliala** 2015-10-05 16:10 UTC
