### ISSUE TITLE
Icon Request: Cisco (Brand)

### ISSUE THREAD

**Issue by bhubbard** [FortAwesome/Font-Awesome#14977] opened 2019-05-01 18:46 UTC
Request for Cisco Brand Icon

https://www.google.com/search?q=cisco+logo&pws=0&gl=us&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj9js_q_vrhAhXCIDQIHXdDBo4Q_AUIDigB&biw=2010&bih=1293

**Comment by tagliala** [comment] 2019-05-01 19:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6149, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-05-01 19:12 UTC
