### ISSUE TITLE
Icon request: - ATC tower

### ISSUE THREAD

**Issue by ondrej2004** [FortAwesome/Font-Awesome#15297] opened 2019-07-27 19:22 UTC
Hello,
The ATC tower would be useful for people like me who have an aviation website that relates to Air Traffic Control but there is not an icon for it

here is a icon picture to work off if you want (optianal)
![image](https://user-images.githubusercontent.com/49593101/61998714-0ec27800-b0ac-11e9-86c3-df5c6e5b8475.png)

Thanks in advance if this could be possible

**Comment by tagliala** [comment] 2019-07-27 23:31
Hi!

Thanks for being part of the Font Awesome Community.

I'm pretty confident that this request is a duplicate of #8687, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

Feel free to comment if I'm wrong

**Closed by tagliala** 2019-07-27 23:31 UTC
