### ISSUE TITLE
World Icon?

### ISSUE THREAD

**Issue by Cliffsuss** [FortAwesome/Font-Awesome#11190] opened 2017-06-16 14:54 UTC
Sorry if I do this wrongly, as I am new to this, but is there a similar icon to the WWW icon?
https://image.freepik.com/free-icon/internet-world_318-30029.jpg

**Comment by tagliala** [comment] 2017-06-16 15:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2655 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-16 15:26 UTC
