### ISSUE TITLE
Icon request: Support / Telephone support

### ISSUE THREAD

**Issue by ChristofferFurnes** [FortAwesome/Font-Awesome#9038] opened 2016-04-22 07:39 UTC
I really miss an icon for support / telephone support. Perhaps something like this?

Also, +1 on the post box requsest!

![image](https://cloud.githubusercontent.com/assets/18610413/14734897/d9a39076-086d-11e6-8d14-e104ced8f493.png)

**Comment by tagliala** [comment] 2016-04-22 09:01
duplicate of #1146 , please +1 that request

closing here

**Closed by tagliala** 2016-04-22 09:01 UTC
