### ISSUE TITLE
fa-youtube offcenter when using fa-layers

### ISSUE THREAD

**Issue by danielmarkavis** [FortAwesome/Font-Awesome#12332] opened 2018-02-12 10:28 UTC
Using FA5 via "SVG with JS"

`<span class="fa-layers fa-3x">
<i class="fas fa-circle"></i>
<i class="fab fa-youtube fa-inverse" data-fa-transform="shrink-8"></i>
</span>`

This displays the icon off center to the right, only on fa-youtube so far.

**Comment by tagliala** [comment] 2018-02-12 11:35
Hi!

Thanks for being part of the Font Awesome Community.

Please note that icons have not the same width by design choice, so you need `fa-fw` on the layer

https://jsfiddle.net/tagliala/vLae8ted/8/

Docs: https://fontawesome.com/how-to-use/svg-with-js#layering

Hope it helps

closing here

**Closed by tagliala** 2018-02-12 11:35 UTC
