### ISSUE TITLE
Icon Request : Bootstrap Logo

### ISSUE THREAD

**Issue by Ash69911** [FortAwesome/Font-Awesome#13832] opened 2018-08-29 10:10 UTC
There is no bootstrap logo

**Comment by tagliala** [comment] 2018-08-29 12:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1828 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-29 12:06 UTC
