### ISSUE TITLE
Window icon request

### ISSUE THREAD

**Issue by hex0gen** [FortAwesome/Font-Awesome#6298] opened 2015-04-23 08:49 UTC
Take my absolutely greeting. 

Dear developers, please add a "window" or "browser window" icon in next releases.

http://iconshow.me/browser

Thx & cheers, from hex0gen

**Comment by tagliala** [comment] 2015-04-23 11:05
Duplicate of #3585, please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-04-23 11:05 UTC
