### ISSUE TITLE
icon-request: icon-bike

### ISSUE THREAD

**Issue by sidtechno** [FortAwesome/Font-Awesome#12892] opened 2018-04-18 13:48 UTC
Icon for road biking
Good for Triathlon site, road biking club

**Comment by aethior** [comment] 2022-05-07 17:00
Hi @nick,

Duplicate of #6204.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed** 2022-05-07 17:52 UTC
