### ISSUE TITLE
Icon request: metamask

### ISSUE THREAD

**Issue by debugme** [FortAwesome/Font-Awesome#18750] opened 2022-02-24 11:58 UTC
As Web3 apps become more common and people start using wallets such as Metamask to authenticate themselves, it might be nice to actually have a set of icons that are suitable for building Web3 applications. The Metamask icon is one option that comes to mind.

**Comment by tagliala** [comment] 2022-02-24 12:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13773, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-02-24 12:16 UTC
