### ISSUE TITLE
Icon request: fa-tunein

### ISSUE THREAD

**Issue by 14sprouj** [FortAwesome/Font-Awesome#18054] opened 2021-07-06 09:49 UTC
**What can it be used for?**
A link for the TuneIn website

**Example image (optional)**
https://cdn-web.tunein.com/assets/img/footer/tunein-logo-tsharp.svg

This would be under the brand category

**Comment by tagliala** [comment] 2021-07-06 11:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3159, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-07-06 11:01 UTC
