### ISSUE TITLE
Battlelog icon

### ISSUE THREAD

**Issue by Evstigneev** [FortAwesome/Font-Awesome#8772] opened 2016-03-17 08:16 UTC
I would like to use Battlelog (logo) icon. [Battlelog](http://battlelog.battlefield.com/) is crossplatform social network for Battlefield gamers. It counts more than 100k users. Maybe like abbreviation 'BL'

Thanks!

**Comment by tagliala** [comment] 2016-03-17 10:19
Duplicate of #5187, please +1 that request

closing here

**Closed by tagliala** 2016-03-17 10:19 UTC
