### ISSUE TITLE
Icon request: fa-impactstory

### ISSUE THREAD

**Issue by arcaravaggi** [FortAwesome/Font-Awesome#11318] opened 2017-07-21 21:18 UTC
Increasingly used by academics, as are GitHub Pages.

![new-impactstory-logo-no-type1](https://user-images.githubusercontent.com/25013748/28482889-79b1cb68-6e62-11e7-869c-a7cd593210c7.png)

**Comment by tagliala** [comment] 2017-07-22 09:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4180, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-22 09:44 UTC
