### ISSUE TITLE
Icon Request: fa-resume

### ISSUE THREAD

**Issue by nknotts** [FortAwesome/Font-Awesome#8649] opened 2016-02-24 11:38 UTC
There are several [Video Player](https://fortawesome.github.io/Font-Awesome/icons/#video-player) icons. For completeness, it would be nice to have a resume icon.
![](https://cdn4.iconfinder.com/data/icons/defaulticon/icons/png/256x256/media-play-pause-resume.png)

**Comment by tagliala** [comment] 2016-02-24 12:38
Duplicate of #4215, please +1 that request

closing here

**Closed by tagliala** 2016-02-24 12:38 UTC
Labels: new icon, video player icons
