### ISSUE TITLE
Icon Request: fa-icon-saatchi-art

### ISSUE THREAD

**Issue by BenZpod** [FortAwesome/Font-Awesome#11179] opened 2017-06-15 07:20 UTC
Hi
I need Saatchi art logo for my website to link to saatchiart.com 
Here is a jpeg and a pdf vector file
Thx
Ben
![saatchiart](https://user-images.githubusercontent.com/29424602/27169747-6f9d0d5a-51ab-11e7-8ead-ebe061a6bcdf.jpg)
[saatchiart.pdf](https://github.com/FortAwesome/Font-Awesome/files/1076861/saatchiart.pdf)

**Comment by tagliala** [comment] 2017-06-15 08:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9389, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-15 08:39 UTC
