### ISSUE TITLE
Icon Request : fa-quora & fa-quora-square (Quora)

### ISSUE THREAD

**Issue by saurav12** [FortAwesome/Font-Awesome#6828] opened 2015-06-26 06:22 UTC
![fa-quora-square](https://cloud.githubusercontent.com/assets/4298450/8371728/ecd22dcc-1bf8-11e5-8449-17983e36af59.png)
fa-quora-square
![fa-quora](https://cloud.githubusercontent.com/assets/4298450/8371729/ecdf4ffc-1bf8-11e5-8d4d-ad2a3799a981.png)
fa-quora

**Comment by RajeebTheGreat** [comment] 2015-06-28 20:44
+1

**Comment by tagliala** [comment] 2015-06-30 17:00
duplicate of #510 , please +1 that request

closing here

**Closed by tagliala** 2015-06-30 17:00 UTC
