### ISSUE TITLE
Icon Request: We need barcode reader icon

### ISSUE THREAD

**Issue by peon501** [FortAwesome/Font-Awesome#9792] opened 2016-08-23 12:35 UTC

**Comment by tagliala** [comment] 2016-08-23 13:05
Duplicate of #7356, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-23 13:05 UTC
