### ISSUE TITLE
Icon request: bento / dots

### ISSUE THREAD

**Issue by sofiepett91** [FortAwesome/Font-Awesome#18605] opened 2022-01-25 10:32 UTC
**What can it be used for?**
It can be used to display a menu / app menu, showing related websites etc. 

**Example image (optional)**  
Examples from google:
![image](https://user-images.githubusercontent.com/31986988/150960058-0b565d2a-48d9-44ed-b044-9cf351959a75.png)
![image](https://user-images.githubusercontent.com/31986988/150960127-c4e0e7fa-f5ff-4f23-8a06-134270991ac5.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Merethee** [comment] 2022-01-25 10:39
Yes, I need this! :D

**Comment by xec** [comment] 2022-01-25 15:01
The closest current icon i can find is [grid](https://fontawesome.com/v6.0/icons/grid?s=solid) (called [th in v5](https://fontawesome.com/v5.15/icons/th?style=solid)) but I too would love to see one made of circles instead of (rounded) squares.

[grip-dots](https://fontawesome.com/v6.0/icons/grip-dots?s=solid) is also very close, with circles but only two rows - i need 3x3 dots! :)

**Comment by tagliala** [comment] 2022-01-25 21:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15452, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-01-25 21:54 UTC
