### ISSUE TITLE
Icon Request: vine-square

### ISSUE THREAD

**Issue by DiamondPigman** [FortAwesome/Font-Awesome#8974] opened 2016-04-13 17:01 UTC
Basically a square version of the Vine logo like all the other social media icons seems to have, so no example needed

**Comment by PeterShaggyNoble** [comment] 2016-04-13 17:03
Dupe of [#7669](https://github.com/FortAwesome/Font-Awesome/issues/7669), you should +1 that.

**Comment by tagliala** [comment] 2016-04-13 22:00
@PeterShaggyNoble thanks

**Closed by tagliala** 2016-04-13 22:00 UTC
