### ISSUE TITLE
Icon Request: fa-record_voice_over

### ISSUE THREAD

**Issue by AnnikaEriksson** [FortAwesome/Font-Awesome#10708] opened 2017-02-27 12:20 UTC
[tala.pdf](https://github.com/FortAwesome/Font-Awesome/files/803631/tala.pdf)

Our users sometimes need to have the content read out loud, and I'm missing an icon for that. Found this "record_voice_over &#xe91f; 
![image](https://cloud.githubusercontent.com/assets/26061422/23361461/154d772c-fcf1-11e6-9875-0456e7e539c6.png)
" at https://www.w3schools.com/icons/icons_reference.asp, but I don't want to add another icon font as I'm happy with FA.
(I have seen the volume-up icon been used for this, but we use the volum-up for... volume-up :) )

**Comment by tagliala** [comment] 2017-02-27 14:24
I'm going to consider this a duplicate of #2096, please 👍 that request

Closing here

**Closed by tagliala** 2017-02-27 14:24 UTC
