### ISSUE TITLE
Icon request: icon-blackberry 

### ISSUE THREAD

**Issue by RamanJeetSingh** [FortAwesome/Font-Awesome#5174] opened 2014-12-10 10:38 UTC

**Comment by efixdent** [comment] 2016-01-21 03:15
we need fontawesome to provide blackberry icon, thank you very much.

**Comment by daveliao** [comment] 2016-06-22 17:07
Hey there Font Awesome bug reviewer(s), I recommend closing this issue since it's a duplicate of issue #1537 .

**Comment by tagliala** [comment] 2016-06-22 21:04
@daveliao thanks, didn't see this one

**Closed by tagliala** 2016-06-22 21:04 UTC
