### ISSUE TITLE
Icon request: fa-face-palm

### ISSUE THREAD

**Issue by dylan7778** [FortAwesome/Font-Awesome#18774] opened 2022-03-04 19:14 UTC
I run a social media network and we use FA icons for our reactions. For some reason, there's not currently a facepalm emoji, despite the fact that this is one of the most common reactions used across the web. Definitely need this!

**Comment by aethior** [comment] 2022-03-06 22:57
Hi @dylan7778,

Duplicate of #17355.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed as completed** 2022-03-06 23:17 UTC
