### ISSUE TITLE
Icon Request: fa-users-2

### ISSUE THREAD

**Issue by ngoral** [FortAwesome/Font-Awesome#10025] opened 2016-10-05 21:14 UTC
I'd like to have an ico, that represents two people's heads. Like this:
![image](https://cloud.githubusercontent.com/assets/9076531/19131691/1b1e85a6-8b59-11e6-9cda-83ff04fa29df.png)
I know, you already have one and three "heads". I need that for showing privacy of objects that means 'Friends can access' when already existing icon `fa-users` that has three "heads" is being used for showing 'Friends and their friends can access'. I thought of another icons you have, but still has no idea how to do it in other way.
I think it could be done by just deleting left head from your `fa-users` icon.
![image](https://cloud.githubusercontent.com/assets/9076531/19131882/e7546b40-8b59-11e6-9a5c-7a1c05f3e096.png)

Oh! Or it could be combination of `users` and `user-plus` icons (to have multiple "heads" and plus near them). In that case I could use it for show "friends' friends" and `users` just to show "friends".

Thanx in advance!

**Comment by tagliala** [comment] 2016-10-06 11:46
Duplicate of #2883 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-06 11:46 UTC
