### ISSUE TITLE
Icon request: high-five

### ISSUE THREAD

**Issue by LarsFlieger** [FortAwesome/Font-Awesome#16139] opened 2020-02-02 13:28 UTC
**What can it be used for?**
A high five is a modern way to agree to something, to share an idea, to accept a plan, to work together. It can be used from portfolio, agency, pricing pages to accept buttons, plan overviews and much more. 

**Example image (optional)**
https://previews.123rf.com/images/flynt/flynt1401/flynt140100160/24930958-high-five-konzept-f%C3%BCr-erfolg-teamwork-gratulieren-und-feiern.jpg

**Comment by tagliala** [comment] 2020-02-09 19:57
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/praying-hands?style=solid fit your use case?

**Comment by aethior** [comment] 2022-03-18 00:06
Duplicate of #7491.

cc/ @tagliala

**Comment by LarsFlieger** [comment] 2022-03-18 10:34
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Does https://fontawesome.com/icons/praying-hands?style=solid fit your use case?

Not really more something like this in #7491

**Comment by tagliala** [comment] 2022-03-18 10:53
Thanks, please upvote #7491

**Closed by tagliala** 2022-03-18 10:53 UTC
Labels: waiting for feedback
