### ISSUE TITLE
Icon request: fa-fish

### ISSUE THREAD

**Issue by MarvDann** [FortAwesome/Font-Awesome#11043] opened 2017-05-09 17:52 UTC

**Comment by MarvDann** [comment] 2017-05-09 17:55
Use case is a travel site that wants to have a 'Things to Do' section with fishing as an option.

**Comment by tagliala** [comment] 2017-05-09 17:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2722, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-09 17:55 UTC
