### ISSUE TITLE
Icon request: fa-quill

### ISSUE THREAD

**Issue by narcisusse** [FortAwesome/Font-Awesome#11493] opened 2017-09-06 00:56 UTC
include  fa-quill-o  and  fa-quill

**Comment by tagliala** [comment] 2017-09-06 08:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9082, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-06 08:26 UTC
