### ISSUE TITLE
Icon Request: fa-python

### ISSUE THREAD

**Issue by micahbyte** [FortAwesome/Font-Awesome#11280] opened 2017-07-12 07:38 UTC
Hello Font Awesome community! I would like to request a Python icon. This icon would be the logo of the Python programming language.
The primary use case of this icon:
1. To represent the Python programming language

Here are a few colored and non-colored examples of this icon.
![python-icon](https://user-images.githubusercontent.com/8687283/28106889-994604d2-66b3-11e7-9aa9-ded3972a7869.png)
![python1600](https://user-images.githubusercontent.com/8687283/28107089-5cbfe928-66b4-11e7-8320-cb19dd83acb6.png)

**Comment by tagliala** [comment] 2017-07-12 07:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3016 , please add a 👍  reaction to that request.

Please also give a try to mfizz icon font: http://fizzed.com/oss/font-mfizz

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-12 07:50 UTC
