### ISSUE TITLE
Icon Request: icon-ruler

### ISSUE THREAD

**Issue by VicCebedo** [FortAwesome/Font-Awesome#6850] opened 2015-07-01 03:31 UTC
I would like to request a font that would represent units of measures. I think the most appropriate icon would be a ruler. Thank you.

**Comment by tagliala** [comment] 2015-07-01 10:35
duplicate of #1096 , please +1 that request

closing here

**Closed by tagliala** 2015-07-01 10:35 UTC

**Comment by VicCebedo** [comment] 2015-07-02 05:31
Thank you @tagliala.
