### ISSUE TITLE
Bug in fontawesome site

### ISSUE THREAD

**Issue by Priyaraval** [FortAwesome/Font-Awesome#15844] opened 2019-11-25 07:11 UTC
Hello Team,

Please check this image. CDN issue found in font-awesome.
https://fontawesome.com/v4.7.0/icon/filter/

![issue](https://user-images.githubusercontent.com/58162611/69519798-e9257c80-0f80-11ea-938c-e53acf0d7652.jpg)

Thanks
Priya Raval

**Comment by tagliala** [comment] 2019-11-25 07:27
Hi!

Thanks for being part of the Font Awesome Community.

I can confirm

@robmadole it happens on icon details page on the old documentation

![image](https://user-images.githubusercontent.com/556268/69520572-50c9d080-0f5d-11ea-8f33-0350762c1f68.png)

**Comment by robmadole** [comment] 2019-11-25 15:17
Shoot, missed that! Thank you for submitting this report. I'll have it fixed in a bit.

**Comment by robmadole** [comment] 2019-11-25 17:28
Should be fixed now.

**Comment by tagliala** [comment] 2019-11-27 09:28
@robmadole reopening because the download link is not working yet

![image](https://user-images.githubusercontent.com/556268/69711056-aee2e900-1100-11ea-839b-b6dfd37ecb19.png)

**Comment by robmadole** [comment] 2019-12-02 18:23
Got a fix for this. Thanks @tagliala

**Comment by robmadole** [comment] 2019-12-02 20:31
Should be all fixed up now. Closing again.

**Closed by robmadole** 2019-12-02 20:31 UTC
Labels: bug, fontawesome.com
