### ISSUE TITLE
Icon request: chaos (D&D Alignment System)

### ISSUE THREAD

**Issue by jbnv** [FortAwesome/Font-Awesome#16650] opened 2020-05-16 20:38 UTC
**What can it be used for?**
Roleplaying games and character development. Indicates characters that are chaotic as opposed to lawful (`gavel`).

**Example image**
The eight-way arrow popularized by [Michael Moorcock](https://en.wikipedia.org/wiki/Symbol_of_Chaos
):
![Star of Chaos](https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Chaos_star.svg/1280px-Chaos_star.svg.png)

**Comment by sensibleworld** [comment] 2024-07-11 16:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/9324)

**Closed by sensibleworld** 2024-07-11 16:37 UTC
Labels: new icon, tabletop gaming (category), Duplicate
