### ISSUE TITLE
Icon request: hand-holding-ge

### ISSUE THREAD

**Issue by mheidebrecht** [FortAwesome/Font-Awesome#19735] opened 2023-05-25 20:16 UTC
### Use case

Use case: Users would have the ability to graphically represent the idea of a service provider.

### Example image

![hand-holding-gear](https://github.com/FortAwesome/Font-Awesome/assets/17099726/a161b484-d42f-44ab-948c-add98a7b1606)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by aethior** [comment] 2023-05-25 21:07
Duplicate of #19719.
_Although this suggestion has an example image that helps to understand it better (the title needs to be fixed)._

**Closed as completed** 2023-05-26 07:07 UTC
Labels: new icon, hands (category)
