### ISSUE TITLE
Icon Request: Pedestal

### ISSUE THREAD

**Issue by roman1479** [FortAwesome/Font-Awesome#17113] opened 2020-09-03 11:38 UTC
![130222](https://user-images.githubusercontent.com/27253489/92110223-0da56380-edf3-11ea-9c03-c4846998516c.png)

**Comment by tagliala** [comment] 2020-09-03 12:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4467 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-03 12:25 UTC
