### ISSUE TITLE
Icon request: Sound Stores

### ISSUE THREAD

**Issue by Magnetarman** [FortAwesome/Font-Awesome#15022] opened 2019-05-13 17:26 UTC
Hello Guys,

is possible request this icon ?

- https://www.beatport.com
- https://www.traxsource.com/
- https://www.residentadvisor.net/

i think that are very useful icon for Web-Designers Like that work with Artist website everyday.

Anyway Many Thanks for your awesome work.

**Comment by tagliala** [comment] 2019-05-13 17:34
Hi!

Thanks for being part of the Font Awesome Community.

beatport is a duplicate of #2890, please add a 👍 reaction to that request.
traxsource is a duplicate of #7919, please add a 👍 reaction to that request.
residentadvisor is a duplicate of #4687, please add a 👍 reaction to that request.

All duplicates, closing here

The nex time, please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

**Closed by tagliala** 2019-05-13 17:34 UTC

**Comment by Magnetarman** [comment] 2019-05-14 11:05
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> beatport is a duplicate of #2890, please add a 👍 reaction to that request.
> traxsource is a duplicate of #7919, please add a 👍 reaction to that request.
> residentadvisor is a duplicate of #4687, please add a 👍 reaction to that request.
> 
> All duplicates, closing here
> 
> The nex time, please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Sorry for duplicated Issue.

**Comment by tagliala** [comment] 2019-05-14 12:00
@Magnetarman don't worry, no problem 👍
