### ISSUE TITLE
brand icons are too small

### ISSUE THREAD

**Issue by nikanjuri** [FortAwesome/Font-Awesome#15488] opened 2019-09-06 09:57 UTC
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
The brand icons are too small in size compared to the rest. 

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.
nikhilanjuri.com -> skills section

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?
same size as the rest of the icons.

**Screenshots**

**Version and implementation**
Version:5.10.2
Browser and version: Google Chrome Version 76.0.3809.132

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by nikanjuri** [comment] 2019-09-06 23:00
There's a problem with only the brand icons, not the other ones.

**Comment by tagliala** [comment] 2019-09-07 11:20
Hi again @nikanjuri 

The issue is the following css rule: 

```
.service-icon .fa {
    font-size: 44px;
    line-height: 70px;
}
```

It is applied only to `fa`-prefixd icons. That should be applied to `fab` icons too

Please keep in mind that Font Awesome 5 is different from FA4 and comes with three different prefixes, so your css should take this into account.

We have some helper classes, like `fa-3x` that could be useful for your use case

Docs: https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons

Hope it helps

PS: I'm happy to help if I have time, but please note that this is not a support forum: double check your stylesheets and inspect elements with developer console before opening new issues

Closing here

**Closed by tagliala** 2019-09-07 11:20 UTC
