### ISSUE TITLE
Icon Request: fa-gscholar

### ISSUE THREAD

**Issue by karliwalti** [FortAwesome/Font-Awesome#11443] opened 2017-08-25 08:38 UTC
Would be great to have a series of icons to academic sites. use case would be on CV's and profile pages of academics. Example here is goggle scholar: https://scholar.google.com/
Will open other suggestions for OCID, but also mendeley or researcherID would be useful.

![image](https://user-images.githubusercontent.com/4565568/29706177-1b3f8d24-8981-11e7-94dd-f561724011ab.png)

**Comment by tagliala** [comment] 2017-08-25 08:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #541, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-25 08:44 UTC
