### ISSUE TITLE
Icon request: far-globe-americas far-globe-europe far-globe-australasia

### ISSUE THREAD

**Issue by dropspace-io** [FortAwesome/Font-Awesome#12168] opened 2018-01-28 00:20 UTC
Requesting 3 globe fonts, similar to the current FA "fa fa-globe", but with a focus on the 3 main areas, Americas, Europe & Australasia - with the focus on the globe of that particular area. Similar to how facebook has their notification icons set for each global area

**Comment by tagliala** [comment] 2018-01-28 12:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #281 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-28 12:09 UTC

**Comment by dropspace-io** [comment] 2018-01-28 22:37
👍
