### ISSUE TITLE
Icon request: fa-drive2

### ISSUE THREAD

**Issue by FlipWho** [FortAwesome/Font-Awesome#13556] opened 2018-07-16 21:25 UTC
Quite popular social network about cars DRIVE2.COM. The icon can be made simply by the letter D or D2.

![image](https://user-images.githubusercontent.com/20239814/42784452-f5188164-8957-11e8-80bc-cea1a2b33e70.png)

**Comment by tagliala** [comment] 2018-07-17 09:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8571, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-17 09:05 UTC
