### ISSUE TITLE
Icon Request: fa-drum

### ISSUE THREAD

**Issue by aprilccaballero** [FortAwesome/Font-Awesome#5786] opened 2015-02-25 22:26 UTC
Building a site for a music-instructor.  Would love icons with instruments: drumset , guitar , etc.

**Comment by chiccorosso** [comment] 2015-02-26 09:27
+1

**Comment by Raphoka** [comment] 2016-01-01 14:18
+1

**Comment by tagliala** [comment] 2016-01-01 17:48
duplicate of #5056, please +1 that request

**Closed by tagliala** 2016-01-01 17:48 UTC
Labels: waiting for feedback
