### ISSUE TITLE
Icon Request: fa-theatre or fa-entertainment

### ISSUE THREAD

**Issue by ivanasetiawan** [FortAwesome/Font-Awesome#9749] opened 2016-08-13 08:29 UTC
It'd be nice to have an `entertainment` or `theatre icon`

**Comment by tagliala** [comment] 2016-08-13 10:17
maybe a duplicate of #153 or #1270

**Comment by aethior** [comment] 2016-10-01 07:05
@tagliala I think you can close here.

**Closed** 2016-10-01 12:06 UTC
Labels: waiting for feedback
