### ISSUE TITLE
Icon Request: icon-old-mobile

### ISSUE THREAD

**Issue by nusoft** [FortAwesome/Font-Awesome#3735] opened 2014-06-18 10:19 UTC
The current icon-mobile is not very clear when it's displayed small (looks like a square). Maybe something like this would be a good alternative:

![image](https://cloud.githubusercontent.com/assets/3862791/3312423/dc3caa84-f6d1-11e3-9426-0e6423cc05cb.png)

**Comment by aethior** [comment] 2022-03-24 01:55
Duplicate of #1670

cc/ @tagliala

**Closed** 2022-03-24 10:53 UTC
Labels: new icon, web application icons
