### ISSUE TITLE
icon fa-phone-alt not working

### ISSUE THREAD

**Issue by s-gupta05** [FortAwesome/Font-Awesome#16953] opened 2020-07-24 14:00 UTC
The free icon `<i class="fas fa-phone-alt"></i>` is not working in the code. I am having no issues in using other icons in the same code line. The icon is not showing up at all.
In the debug screen, when I select the icon tag, the size of the icon is showing 0x0.

![phone_alt_icon_error](https://user-images.githubusercontent.com/48992606/88399152-0b0f2180-cde4-11ea-8a0e-3ec59fde2c24.png)

Thanks & Regards,
Sneha

**Comment by tagliala** [comment] 2020-07-24 14:37
Hi!

Thanks for being part of the Font Awesome Community.

This is most probably due to an outdated version of font awesome used.

[fa-phone-alt](https://fontawesome.com/icons/phone-alt?style=solid) has been introduced in Font Awesome 5.10.2, so please double check that you are using Font Awesome 5.10.2 or newer versions

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Hope it helps

Closing here

**Closed by tagliala** 2020-07-24 14:37 UTC
