### ISSUE TITLE
dev.to

### ISSUE THREAD

**Issue by sirinath** [FortAwesome/Font-Awesome#13775] opened 2018-08-16 07:10 UTC
Can we have a https://dev.to/ icon?

**Comment by tagliala** [comment] 2018-08-16 09:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12589, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-16 09:47 UTC
