### ISSUE TITLE
Icon Request: fa-warehouse

### ISSUE THREAD

**Issue by buerogummi** [FortAwesome/Font-Awesome#8702] opened 2016-03-04 15:20 UTC
![images](https://cloud.githubusercontent.com/assets/17646901/13531096/fd7b8d6a-e224-11e5-9b93-135e5fe09855.png)

**Comment by tagliala** [comment] 2016-03-04 16:58
Duplicate of #4560, please +1 that request

closing here

**Closed by tagliala** 2016-03-04 16:58 UTC
