### ISSUE TITLE
Icon Request: fa-icon-cheque

### ISSUE THREAD

**Issue by demiscient** [FortAwesome/Font-Awesome#8948] opened 2016-04-11 22:55 UTC
You have several payment methods including cash and card, why not cheque too? If you'll believe, it's still in use on many websites..

**Comment by tagliala** [comment] 2016-04-12 09:16
Duplicate of #2603 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-12 09:16 UTC
