### ISSUE TITLE
Icon Request: fa-telegram

### ISSUE THREAD

**Issue by tareq-halaby** [FortAwesome/Font-Awesome#8570] opened 2016-02-14 20:00 UTC
It's great if you provide an icon for telegram so we can use it for telegram channels.

https://telegram.me

LOGO: https://telegram.org/img/t_logo.png

**Comment by aethior** [comment] 2016-02-15 01:13
Hi @tareq-halaby,

This suggestion is duplicate of #3034. Please +1 that.

Regards.

**Closed** 2016-02-15 10:00 UTC

**Comment by sibche2013** [comment] 2016-06-28 19:22
+1
