### ISSUE TITLE
Icon request: Sketchfab Logo

### ISSUE THREAD

**Issue by virtualmakes** [FortAwesome/Font-Awesome#10679] opened 2017-02-17 16:41 UTC
Hello, great designers and developers!
It would be really cool to have an icon for sketchfab logo, as the website is one of the best sources of sharing 3D contents and such. For me, I'm a 3D modeler and want this icon to be linked in the blog. It would also help more people.
BTW, you guys are doing a great job! Thanks :3

![image](https://cloud.githubusercontent.com/assets/25849210/23074153/fad841aa-f55d-11e6-851e-157f41972a4b.png)

**Comment by tagliala** [comment] 2017-02-17 17:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2757, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-17 17:13 UTC
