### ISSUE TITLE
Icon Request: fa-fish

### ISSUE THREAD

**Issue by erosdet** [FortAwesome/Font-Awesome#11732] opened 2017-11-09 12:57 UTC
Icon Request: fa-fish

**Comment by tagliala** [comment] 2017-11-09 13:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2722 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-09 13:15 UTC
