### ISSUE TITLE
Icon Request: fa-file-html-o

### ISSUE THREAD

**Issue by runisy** [FortAwesome/Font-Awesome#11084] opened 2017-05-18 02:54 UTC
just like fa-file-text-o or fa-file-word-o
file type html

**Comment by tagliala** [comment] 2017-05-18 08:31
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7712, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-18 08:31 UTC
