### ISSUE TITLE
Icon request: Gatsby-Framework

### ISSUE THREAD

**Issue by allanandresch** [FortAwesome/Font-Awesome#15996] opened 2019-12-28 06:11 UTC
**What can it be used for?**
Gatsby its the new trend in the programming word, its the best hot skill to learn so everyoen is using it, so we need it for a lot of stuff

**Example image (optional)**
https://www.drupalcampchattanooga.com/sites/default/files/styles/medium/public/gatsby.png?itok=gd5-C1Wa

**Icon request checklist**
- [Single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X] I have included at least one example image if it could be helpful (optional)
- [ X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-12-28 09:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12510, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-12-28 09:55 UTC
