### ISSUE TITLE
Icon Request: icon-continent-xx, icon-country-xx

### ISSUE THREAD

**Issue by waszabi** [FortAwesome/Font-Awesome#7741] opened 2015-10-22 11:04 UTC
Could you please create icons with shapes representing areas of our continents?

icon-continent-af  Africa
icon-continent-an  Antarctica
icon-continent-as  Asia
icon-continent-eu  Europe
icon-continent-na  North America
icon-continent-oc  Oceania
icon-continent-sa  South America

And if you have a lot of time, could you do it also for countries? :)

**Comment by hebbet** [comment] 2015-10-22 17:52
:mag: before filing :bug: 

duplicate of  #281

**Comment by tagliala** [comment] 2015-10-23 18:58
Sorry, I have to close this one

Reason here: https://github.com/FortAwesome/Font-Awesome/issues/3992#issuecomment-73022665

**Closed by tagliala** 2015-10-23 18:58 UTC
