### ISSUE TITLE
Icon request: badge-times

### ISSUE THREAD

**Issue by DarthBilly** [FortAwesome/Font-Awesome#16689] opened 2020-05-21 08:12 UTC
**What can it be used for?**
Used as a list icon to be the opposite of the already available badge-check.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [y ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [y] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [y] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [y] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-21 08:38
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve that icon with the power transforms, masking, and layering features of the SVG Pro Framework.

Demo: https://jsfiddle.net/tagliala/zrcxo5d8/13/

Q: _Why [badge-check](https://fontawesome.com/icons/badge-check) variation is present?_
A: It has been implemented thanks to a sponsor. Sponsored icons are indicated in the documentation page, under the icon itself

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by DarthBilly** [comment] 2020-05-21 08:43
Hey @tagliala , thanks for getting back to me.

I had intended for the layering method to be used when implementing this on the site I've designed, but the developers are telling me that the system that they're using for the site, Contentful, doesn't support it :(

**Comment by sensibleworld** [comment] 2024-07-11 16:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/19083)

**Closed by sensibleworld** 2024-07-11 16:37 UTC
Labels: new icon, status (category), Duplicate
