### ISSUE TITLE
Icon Request: fa-footprints

### ISSUE THREAD

**Issue by gcorderoflorin** [FortAwesome/Font-Awesome#9237] opened 2016-05-18 19:45 UTC
I'm developing an application with a log module. This module will manage the information related to what has been done by the users. I'd love to use an icon like any of these images to represent this module.
Thanks in advance.

![footprints-151189_960_720](https://cloud.githubusercontent.com/assets/8943399/15372494/a881f54a-1d0e-11e6-8f76-717d1f138fcc.png)
![footprint-silhouette_318-39252 png](https://cloud.githubusercontent.com/assets/8943399/15372496/a8e36e88-1d0e-11e6-87ac-70634462ad25.jpeg)

**Comment by tagliala** [comment] 2016-05-18 21:05
Duplicate of #2140 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-18 21:05 UTC
