### ISSUE TITLE
Icon Request: fa-xbox & fa-playstation

### ISSUE THREAD

**Issue by elavender** [FortAwesome/Font-Awesome#5742] opened 2015-02-21 18:26 UTC
I would like to request an icon for the Xbox logo. This would fit well with the existing Brand Icons already in the set. I plan on using this icon to indicate when a user has an Xbox Live Gamertag so I can link to it from their user profile on my site. 

#### fa-xbox
Here's an example of what the logo looks like:
![xbox](https://cloud.githubusercontent.com/assets/1189616/6315306/de852e0a-b9c3-11e4-84af-7831bde3c09d.png)

#### fa-playstation (or fa-psn)
Oh, and a Playstation Network logo would be pretty sweet too. I've attached an example of that logo too:
![playstation](https://cloud.githubusercontent.com/assets/1189616/6315327/35ab3fd0-b9c4-11e4-9cec-9fdd9642cc17.png)

Just thought I'd throw this out there. Thanks! <3 FontAwesome <3

**Comment by tagliala** [comment] 2015-02-22 00:04
duplicate of #1006 , please +1 that request

closing here

**Closed by tagliala** 2015-02-22 00:04 UTC

**Comment by dalfaand** [comment] 2017-04-15 02:47
stiil waiting for these icons 👍
