### ISSUE TITLE
Github tags and npm package is not in sync with the website release

### ISSUE THREAD

**Issue by asfernandes** [FortAwesome/Font-Awesome#11949] opened 2017-12-16 14:41 UTC
Website says latest version is 5.0.1 but github tags and the npm package (font-awesome) are in 4.7.0.

**Comment by tagliala** [comment] 2017-12-16 15:43
Duplicate of #11908

**Closed by tagliala** 2017-12-16 15:43 UTC

**Comment by wolfy1339** [comment] 2017-12-16 16:34
npm package has been updated under a new name: @fortawesome/fontawesome
