### ISSUE TITLE
Icon Request: fa-uber

### ISSUE THREAD

**Issue by 4khil** [FortAwesome/Font-Awesome#7182] opened 2015-08-09 15:55 UTC
It'll be great to have an fa-uber for platforms which use Uber as a service or committment value, with Uber opening up it's API's for apps this would be an easy thing and highly used icon :)

**Comment by tagliala** [comment] 2015-08-09 15:58
duplicate of #4826, please +1 that request

closing here

**Closed by tagliala** 2015-08-09 15:58 UTC
