### ISSUE TITLE
Icon request: leetcode and geeksforgeeks

### ISSUE THREAD

**Issue by Razorquake** [FortAwesome/Font-Awesome#20091] opened 2024-01-30 13:06 UTC
I want to add leetcode and geeksforgeeks icons in my project. Therefore I request you to please add the same

**Comment by tagliala** [comment] 2024-01-30 13:19
Hi!

Thanks for being part of the Font Awesome Community.

leetcode request is a duplicate of #15337, please add a 👍 reaction to that request.
geeksforgeeks request is a duplicate of #19533, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-01-30 13:19 UTC
