### ISSUE TITLE
Thumbtack throwing a prefix js error

### ISSUE THREAD

**Issue by craiggeil** [FortAwesome/Font-Awesome#18712] opened 2022-02-17 05:27 UTC
Trying to use the fas fa-thumbtack icon and it's throwing a js error. Works fine in v5, fails in v6.0

**Comment by tagliala** [comment] 2022-02-17 08:30
Hi!

Thanks for reporting this

we are aware of the issue and it will be fixed in the next release

Duplicate of #18661

Closing here

**Closed as completed by tagliala** 2022-02-17 08:30 UTC
