### ISSUE TITLE
#bug fa-upload and fa-download have not identical height

### ISSUE THREAD

**Issue by cyberkatze** [FortAwesome/Font-Awesome#9407] opened 2016-06-15 13:23 UTC
```
<button type="button" class="btn btn-primary">                
    <span class="fa fa-upload fa-fw"></span> / <span class="fa fa-download fa-fw"></span>
</button>
```

<img width="65" alt="bildschirmfoto 2016-06-15 um 15 21 20" src="https://cloud.githubusercontent.com/assets/2271337/16081223/ef0d3060-330c-11e6-9bc0-5ad9c3b05234.png">

**Comment by tagliala** [comment] 2016-06-15 13:43
Thanks for reporting this

There is an issue in vertical alignment of some icons #1624

The issue is planned for 5.0.0, closing here

**Closed by tagliala** 2016-06-15 13:43 UTC
