### ISSUE TITLE
Icon request: fa-scooter / fa-moped

### ISSUE THREAD

**Issue by Zaanmedia** [FortAwesome/Font-Awesome#9239] opened 2016-05-19 08:27 UTC
Icon request: fa-scooter / fa-moped

Like to see the following Icon request: fa-scooter / fa-moped

[image 1](https://www.google.nl/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwi63KKv2-XMAhUmK8AKHV7HBV8QjRwIBw&url=https%3A%2F%2Fthenounproject.com%2Fterm%2Fmoped%2F24338%2F&psig=AFQjCNFYdQnn8pOp_StnklwSdlhEC3AvHg&ust=1463732686163947)

[image 2](https://www.google.nl/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwj78pDx2-XMAhXHLMAKHa1bBCwQjRwIBw&url=https%3A%2F%2Fthenounproject.com%2Fterm%2Fscooter%2F199508%2F&psig=AFQjCNFYdQnn8pOp_StnklwSdlhEC3AvHg&ust=1463732686163947)

**Comment by aethior** [comment] 2016-07-08 01:18
Duplicate of #6897.

cc @tagliala

**Closed** 2016-07-08 10:41 UTC
