### ISSUE TITLE
Author Friendly Icons

### ISSUE THREAD

**Issue by nickigreenwood** [FortAwesome/Font-Awesome#7049] opened 2015-07-27 01:53 UTC
It would be amazing to have icons for Amazon, Blogger, Goodreads, and Shelfari. Currently having to plug generic icons in those spots on my page. Thanks!

**Comment by tagliala** [comment] 2015-07-27 09:39
amazon is a duplicate of #471 , please +1 that request

blogger: #1088 
goodreads: #1715 
shelfari: #3647

All duplicates, closing here!

**Closed by tagliala** 2015-07-27 09:39 UTC
