### ISSUE TITLE
Icon request: comment-question

### ISSUE THREAD

**Issue by wisercoder** [FortAwesome/Font-Awesome#17565] opened 2021-01-17 01:52 UTC
**What can it be used for?**
Icon to indicate "ask a question"
Or my use case, which is a database query.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/17690993/104828950-8564af80-5823-11eb-9f21-cdfd9a95eb2a.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by wisercoder** [comment] 2021-01-17 01:54
Currently I am layering fa-comment-alt and fa-question to get this icon. But layering is hard and doesn't work well in my application. This is such a common use case that this deserves its own icon.

**Comment by tagliala** [comment] 2021-01-17 10:35
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of both #15985 or #14617

I agree that for icon parity we should have the ? version, let's see what we can do

**Closed by tagliala** 2021-01-17 10:35 UTC
