### ISSUE TITLE
Icon Request: ltc

### ISSUE THREAD

**Issue by aspect** [FortAwesome/Font-Awesome#5578] opened 2015-02-03 22:16 UTC
Request to add Litecoin symbol to Font Awesome.
http://en.wikipedia.org/wiki/Litecoin

There is an increasing number of software that relies on Font Awesome and lack of the Litecoin symbol is presenting a problem when trying to integrate Litecoin support.

The character looks like this:
![ltc](https://cloud.githubusercontent.com/assets/7544020/6030184/a28284c4-abc3-11e4-8486-3f0d0722d52b.png)

Following are the vector files:
http://litecointools.com/font-awesome/ltc.svg
http://litecointools.com/font-awesome/ltc.eps

Integration test:
http://litecointools.com/font-awesome/FontAwesomeWithLitecoin-4.2.0.ttf

Thank you.

**Comment by tagliala** [comment] 2015-02-04 23:33
duplicate of #1768 , please +1 that request

closing here

**Closed by tagliala** 2015-02-04 23:33 UTC
