### ISSUE TITLE
Tiktok icon

### ISSUE THREAD

**Issue by xuanfei** [FortAwesome/Font-Awesome#16189] opened 2020-02-12 23:43 UTC
Please! Thanks!

**Comment by tagliala** [comment] 2020-02-18 21:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14340 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-02-18 21:42 UTC
