### ISSUE TITLE
Icon request: icon-casino-chip

### ISSUE THREAD

**Issue by uducharm** [FortAwesome/Font-Awesome#7114] opened 2015-08-01 12:19 UTC
I would like to use a casino chip icon for a menu item that is used to buy tokens. Our site does not use money directly, people buys tokens and spend them on the site.

**Comment by tagliala** [comment] 2015-08-01 12:34
duplicate of #1004 , please +1 that request

closing here

**Closed by tagliala** 2015-08-01 12:34 UTC
