### ISSUE TITLE
Icon request: Hair Dryer

### ISSUE THREAD

**Issue by STiiTii** [FortAwesome/Font-Awesome#19908] opened 2023-09-27 10:07 UTC
### Use case

This icon could be used for hotel room equipment.

### Example image

![hair-dryer](https://github.com/FortAwesome/Font-Awesome/assets/97702213/4cdacea0-bd34-4df4-b366-8526164d3886)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by aethior** [comment] 2023-09-28 20:48
Hi @STiiTii,

This request is duplicate of #10951.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed as completed** 2023-09-29 09:36 UTC
Labels: new icon
