### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by Robby-apt** [FortAwesome/Font-Awesome#18884] opened 2022-04-06 10:31 UTC
Hello. I would like to request icons for mysql and mongo database. Thanks for all you do.

**Comment by aethior** [comment] 2022-04-09 00:15
Hi @Robby-apt,

This request is duplicate of #2725 `fa-mogodb` and #6052 `fa-mysql`.
Please add a 👍 reaction to those requests.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-04-09 09:57
Hi!

Thanks for being part of the Font Awesome Community.


> This request is duplicate of #2725 `fa-mogodb` and #6052 `fa-mysql`.
> Please add a 👍 reaction to those requests.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-04-09 09:57 UTC
