### ISSUE TITLE
fab fa-free-code-camp

### ISSUE THREAD

**Issue by codecory** [FortAwesome/Font-Awesome#16872] opened 2020-07-04 03:45 UTC
The freecodecamp icon is showing with an underscore after it. Checked my code and I have no hyphens or underscores around the HTML there. Shows in Chrome and Firefox. Link to my personal portfolio page where I noticed the issue occurring here: https://codepen.io/codecory/pen/jOWLKGG?editors=1100

**Comment by tagliala** [comment] 2020-07-04 09:12
Hi!

Thanks for being part of the Font Awesome Community.

The problem is in the extra white space char in the `<a>` tag after the `<i>` icon at line 49, and since the default style for links include a `text-decoration: underline`, you can see the underline.

Ref: https://jsfiddle.net/tagliala/pw94dbvc/6/

Hope it helps

Closing here

**Closed by tagliala** 2020-07-04 09:12 UTC
