### ISSUE TITLE
Icon Request: fa-teamspeak

### ISSUE THREAD

**Issue by Humanoiidd** [FortAwesome/Font-Awesome#10242] opened 2016-11-18 08:23 UTC
Possible to add an icon for this website https://www.teamspeak.com/teamspeak3 ?

**Comment by tagliala** [comment] 2016-11-18 10:52
Duplicate of #1474 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-18 10:52 UTC
