### ISSUE TITLE
Icon request: font-size-up font-size-down

### ISSUE THREAD

**Issue by dado4497** [FortAwesome/Font-Awesome#9812] opened 2016-08-25 09:54 UTC
Hi
I think that font-size-up and font-size-down are important in a text editing application to increase it's usability. So I hope that will be included in font awesome icon.
There I attach a mock-up of these icons:
![font_up](https://cloud.githubusercontent.com/assets/10551912/17964586/47a25a0e-6aba-11e6-8eb7-c1910d4a7500.png)
![font_down](https://cloud.githubusercontent.com/assets/10551912/17964599/55aa82e8-6aba-11e6-9345-47d5b03b3ccf.png)

Thanks

**Comment by tagliala** [comment] 2016-08-25 10:18
Duplicate of #1469, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-25 10:18 UTC
