### ISSUE TITLE
Icon Request: fa-wine

### ISSUE THREAD

**Issue by paulvanderhoeven** [FortAwesome/Font-Awesome#6449] opened 2015-05-11 14:25 UTC
The world is a better place with font-awesome!
Thanks for considering this.

**Comment by simonfranz** [comment] 2015-05-11 19:59
This is simlar to #3614

**Comment by tagliala** [comment] 2015-05-12 22:46
@simonfranz thanks

This is a duplicate of one of those three

grapes is a dup of #5691 , please +1 that request
wine bottle is a dup of #1762 , please +1 that request
wine glass is a dup of #3614 , please +1 that request

**Closed by tagliala** 2015-05-12 22:46 UTC
