### ISSUE TITLE
Icon request: icon-skull

### ISSUE THREAD

**Issue by noelietrex** [FortAwesome/Font-Awesome#11349] opened 2017-08-02 22:03 UTC
I would like to request a skull and cross bones icon.

**Comment by tagliala** [comment] 2017-08-02 22:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #918 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-02 22:07 UTC
