### ISSUE TITLE
Icon request: Dinosour

### ISSUE THREAD

**Issue by Soft-Bred** [FortAwesome/Font-Awesome#17566] opened 2021-01-17 10:21 UTC
**What can it be used for?**
Having a dinosaur icon
Personally, I need it as an icon for a question labelled "what is your favourite dinosaur?"

**Comment by tagliala** [comment] 2021-01-17 10:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1580, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-01-17 10:23 UTC
