### ISSUE TITLE
Icon request: unsplash.com

### ISSUE THREAD

**Issue by abaney** [FortAwesome/Font-Awesome#16560] opened 2020-04-30 16:56 UTC
**What can it be used for?**
Used as a social media type icon. I'd like to use it alongside the social icons on my website to link to my Unsplash photography page. Like the 500px logo.

**Example image (optional)**
You can see the logo on their website at [unsplash.com](https://unsplash.com/)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-04-30 17:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11508, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-04-30 17:02 UTC
