### ISSUE TITLE
Brand request: replit

### ISSUE THREAD

**Issue by itsRealMarshall** [FortAwesome/Font-Awesome#19204] opened 2022-07-22 20:50 UTC
### Official website

https://replit.com

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2022-07-23 09:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14758 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-07-23 09:02 UTC
Labels: brand icon
