### ISSUE TITLE
Icon request: TypeScript

### ISSUE THREAD

**Issue by DevidCIC** [FortAwesome/Font-Awesome#12120] opened 2018-01-17 14:12 UTC
You already have the JavaScript icon, TypeScript would be very similar. Instead of JS just TS. We have a program that is implemented in three different languages, the customer wants to distinguish between those that is why a icon for each would be really practical.

**Comment by tagliala** [comment] 2018-01-17 14:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11890, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-17 14:30 UTC
