### ISSUE TITLE
Icon Request: fa-mail-box

### ISSUE THREAD

**Issue by michaelpaps** [FortAwesome/Font-Awesome#11500] opened 2017-09-08 05:28 UTC
I think it would be great to have access to a letterbox or mailbox icon for clients who use PO Boxes.

Thanks!
Michael

![screen shot 2017-09-08 at 3 27 25 pm](https://user-images.githubusercontent.com/31756912/30197308-3ebac866-94aa-11e7-8976-4af5c42b5c81.png) ![screen shot 2017-09-08 at 3 27 09 pm](https://user-images.githubusercontent.com/31756912/30197309-3ebd2f48-94aa-11e7-9202-9a7b38e53d72.png) ![screen shot 2017-09-08 at 3 26 55 pm](https://user-images.githubusercontent.com/31756912/30197310-3ebe4fcc-94aa-11e7-955a-c294d4977d87.png) ![screen shot 2017-09-08 at 3 26 47 pm](https://user-images.githubusercontent.com/31756912/30197311-3ec02a54-94aa-11e7-8b12-9ddd5613152c.png)

Usage Example:
![screen shot 2017-09-08 at 3 28 11 pm](https://user-images.githubusercontent.com/31756912/30197335-5ea7be90-94aa-11e7-8038-abe4f4b77b49.png)

**Comment by tagliala** [comment] 2017-09-08 08:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4849 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-08 08:23 UTC
