### ISSUE TITLE
Icon request: icon-policecar

### ISSUE THREAD

**Issue by allor** [FortAwesome/Font-Awesome#13224] opened 2018-05-27 10:31 UTC
Need police car icon for emergency service application
![police_car-512](https://user-images.githubusercontent.com/6686310/40584910-ee2b5cb0-61ec-11e8-8764-5a24025de870.png)

**Comment by tagliala** [comment] 2018-05-27 11:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10135, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-27 11:17 UTC
