### ISSUE TITLE
Icon Request: fa-handshake

### ISSUE THREAD

**Issue by brianpagan** [FortAwesome/Font-Awesome#9580] opened 2016-07-15 14:46 UTC
Hello! I'm loving FontAwesome and hoping I can request an additional icon.

I'm looking for something like a handshake, which I would like to use to represent things like:

- A deal
- Agreement
- Friends
- Cooperation
- Teamwork

I had something in mind like these icons at The Noun Project:
https://thenounproject.com/search/?q=handshake

Thanks and have a great weekend!
Brian

<img width="464" alt="screen shot 2016-07-15 at 16 46 01" src="https://cloud.githubusercontent.com/assets/18679257/16878144/b244e28e-4aab-11e6-8f5c-7aea11f92aa1.png">

**Comment by tagliala** [comment] 2016-07-15 15:07
Duplicate of #878 , planned for 5.0.0

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-15 15:07 UTC
