### ISSUE TITLE
Icon Request: fa-chess

### ISSUE THREAD

**Issue by EdytaKulaga** [FortAwesome/Font-Awesome#11139] opened 2017-06-06 08:51 UTC
Maybe you could add chess paws icons fa-king, fa-queen etc.
I think that would be (font)awesome :)
Thanks!
Edyta

**Comment by tagliala** [comment] 2017-06-06 09:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1815 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-06 09:10 UTC
