### ISSUE TITLE
Icon request: TikTok

### ISSUE THREAD

**Issue by robariis** [FortAwesome/Font-Awesome#16447] opened 2020-04-10 01:56 UTC

**Comment by tagliala** [comment] 2020-04-10 07:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14340 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-04-10 07:50 UTC
