### ISSUE TITLE
Icon Request: fa-xmpp & fa-infinity

### ISSUE THREAD

**Issue by daniel-hyuuga** [FortAwesome/Font-Awesome#6727] opened 2015-06-11 15:41 UTC
XMPP / Jabber is quite popular open source messaging service and for fa-infinity can be used by webhosts and etc. that provides something "unlimited"

fa-xmpp: http://medicine.ucsf.edu/domit/images/xmpp-logo-100.png (without "XMPP" word)
fa-infinity: https://yaalli.files.wordpress.com/2014/07/the-destination.png?w=141

**Comment by Baker** [comment] 2015-06-14 19:40
+1

**Comment by TheChen5** [comment] 2015-07-26 17:50
fa-infinity seems to be a dupe of #1647

**Comment by tagliala** [comment] 2015-07-26 20:06
and fa-xmpp is here #549 

all dups, closing here

**Closed by tagliala** 2015-07-26 20:06 UTC
