### ISSUE TITLE
Icon Request: fa-python

### ISSUE THREAD

**Issue by OnlyDrey** [FortAwesome/Font-Awesome#9947] opened 2016-09-22 12:09 UTC
Python also needs an icon :D

https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1024px-Python-logo-notext.svg.png

**Comment by tagliala** [comment] 2016-09-22 13:35
Duplicate of #3016 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-22 13:35 UTC
