### ISSUE TITLE
Icon Request: fa-lips

### ISSUE THREAD

**Issue by Scobee** [FortAwesome/Font-Awesome#9171] opened 2016-05-11 09:46 UTC
Right now I have to implement a custom food taste, like spicy, salty, and this icon would be very useful.
It can also stand for kisses, love, and so on
I have attached multiple icons, just select the one that you think it's best

![adobestock_74799090](https://cloud.githubusercontent.com/assets/5129107/15176967/541295d4-1776-11e6-9ea1-3f975d9ac7a0.png)

**Comment by tagliala** [comment] 2016-05-11 10:12
Duplicate of #3592, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-11 10:13 UTC

**Comment by Scobee** [comment] 2016-05-11 10:26
@tagliala - But that request is 2 years old. That's how long it takes for a font to be created ? I have the .ai files for these lips and I can provide them to shorten the time.

**Comment by tagliala** [comment] 2016-05-11 15:18
@Scobee please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
