### ISSUE TITLE
can FA add any class such as fa-rotate-45,fa-rotate-135,fa-rotate-225?

### ISSUE THREAD

**Issue by karlew** [FortAwesome/Font-Awesome#9042] opened 2016-04-22 17:01 UTC
although it need to compatible with IE9-,can FortAwesome add any class such as fa-rotate-45,fa-rotate-135,fa-rotate-225 into font-awesome.css?some icon I use need to rotate at some angle,but I do not want to add the class into this file every time when it update.

`.fa-rotate-45 {
  -webkit-transform: rotate(45deg);
  -ms-transform: rotate(45deg);
  transform: rotate(45deg);
}`

thank you

**Comment by tagliala** [comment] 2016-04-22 17:25
duplicate of #8515, please +1 that request

closing here

**Closed by tagliala** 2016-04-22 17:25 UTC
