### ISSUE TITLE
Icon Request: fa-IMDb

### ISSUE THREAD

**Issue by jdavis2458** [FortAwesome/Font-Awesome#6973] opened 2015-07-17 16:15 UTC
I need this as soon as possible, I am willing to pay someone
![imdb](https://cloud.githubusercontent.com/assets/13383604/8751797/0c4a31b8-2c75-11e5-8b2c-0e26b54e5396.jpg)

**Comment by tagliala** [comment] 2015-07-18 12:49
duplicate of #998 , please +1 that request

closing here

**Closed by tagliala** 2015-07-18 12:49 UTC
