### ISSUE TITLE
Icon request: fa fa-www

### ISSUE THREAD

**Issue by davidmoremad** [FortAwesome/Font-Awesome#14029] opened 2018-09-28 10:11 UTC
Icon to refer to a domain or a website.

In some situations you could use the globe icon, but this icon has multiple meanings and it can be confusing to use it for different purposes like "country select", "language select" or even to talk about the scope of a global service.

So I think an icon with "www" (world wide web) could avoid this problem and help give each element its correct meaning.

**Comment by tagliala** [comment] 2018-09-28 10:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6763 or #1192, please add a 👍 reaction to the proper request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-28 10:16 UTC
