### ISSUE TITLE
Icon Request: fa-json fa-amp-html

### ISSUE THREAD

**Issue by ashrafpro** [FortAwesome/Font-Awesome#11527] opened 2017-09-14 13:19 UTC
json
https://www.google.com/search?q=json+icon&oq=json+icon

also google AMP (accelerate mobile pages)
it is quite close to the bolt
https://www.google.com/search?q=amp+icon&oq=amp+icon

**Comment by tagliala** [comment] 2017-09-14 16:19
Hi!

Thanks for being part of the Font Awesome Community.

JSON may be a duplicate of #1797

Please split this request into two separate requests, having care of providing an example for json

**Closed by tagliala** 2017-09-14 16:19 UTC
