### ISSUE TITLE
Icon Request: fa-theatre

### ISSUE THREAD

**Issue by muhammetbalci** [FortAwesome/Font-Awesome#12197] opened 2018-01-31 16:10 UTC

**Comment by tagliala** [comment] 2018-01-31 16:45
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #1270 , please add a 👍  reaction to that request.

If you have something different in mind, please take a look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-31 16:45 UTC
