### ISSUE TITLE
Icon Request: fa-text-scroll

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7938] opened 2015-11-20 06:37 UTC
Request for fa-text-scroll icon (can also be called fa-old-scroll)

![fa-text-scroll](http://i.imgur.com/HaygAyP.png)

**Comment by caduvieira** [comment] 2015-11-20 12:58
dupe of #5805
please +1 that one
Also put your example there

**Closed** 2015-11-20 14:57 UTC
