### ISSUE TITLE
Icon request: tradingview logo icon

### ISSUE THREAD

**Issue by dpuleo3** [FortAwesome/Font-Awesome#17627] opened 2021-02-11 22:18 UTC
**What can it be used for?**
Like a social media icon

**Example image (optional)**
![image](https://user-images.githubusercontent.com/64212967/107705549-3180a580-6cbf-11eb-9875-bbeee4fdf674.png)

https://www.google.com/search?q=tradingview+logo&sxsrf=ALeKk00rJc12h1jgHwSxOHUPZ53nJoDVbg:1613081790318&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi7x-v47eLuAhXTilwKHRojBuoQ_AUoAXoECA8QAw&biw=1366&bih=625

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [ X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-02-12 08:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11968, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-02-12 08:54 UTC
