### ISSUE TITLE
Icon Request: fa-football

### ISSUE THREAD

**Issue by ChrisKlinglmayr** [FortAwesome/Font-Awesome#10738] opened 2017-03-04 11:30 UTC
Using it for a website for a Sports chapter

![5b057d8b3606c284cf3b381f23b7a770_football-clipart-2014-dr-odd-football-png-clipart_600-570](https://cloud.githubusercontent.com/assets/26183566/23578400/50c0d4d2-00d6-11e7-907a-5e5b48ebac62.png)

**Comment by tagliala** [comment] 2017-03-04 12:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4602 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-04 12:46 UTC
