### ISSUE TITLE
Icon request: parler

### ISSUE THREAD

**Issue by DivineDesignKS** [FortAwesome/Font-Awesome#17408] opened 2020-11-17 14:58 UTC
**What can it be used for?**
New social media app, used to include social icons for social networks.

**Example image (optional)**
![Parler-Logo](https://user-images.githubusercontent.com/68382339/99405831-3057fc00-28bb-11eb-923d-e1ab1c58004e.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-11-18 17:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16275, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-11-18 17:57 UTC
