### ISSUE TITLE
Add ability to bundle only used icons .

### ISSUE THREAD

**Issue by almgwary** [FortAwesome/Font-Awesome#10974] opened 2017-04-22 12:24 UTC
i notice that Fontawesome size is more than 1M,
why not add feature to bundle used icons only

**Comment by tagliala** [comment] 2017-04-22 12:47
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look here: [Customize Font Awesome](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome)

This request is also a duplicate of #1133, please share your thoughts there.

PS: the browser will load only the supported font format (ex: woff2 for chrome) and the minified css version, so the actual downloaded size depend on browsers and varies from 100kb (woff2) to 470kb (svg). You should also take into consideration gzip compression, caching and cdn

Actual download size on Chrome 57
![image](https://cloud.githubusercontent.com/assets/556268/25304587/95e8b29a-276a-11e7-95f0-f77da3baddc5.png)

PS2: I'm not saying that customizing font awesome is a bad idea, you can shrink the css and font file to 1/10th of the original one :)

**Closed by tagliala** 2017-04-22 12:47 UTC

**Comment by BorntraegerMarc** [comment] 2017-10-06 10:48
@tagliala the linked issue is something about mathematical icons. Not sure what it has to do with bundles...

**Comment by tagliala** [comment] 2017-10-06 10:56
@BorntraegerMarc thanks. Sometimes I mess up with autocompletion, in this specific case I've picked the wrong "divide" :)

The proper issue is #1322, I've edited my answer
