### ISSUE TITLE
Icon request: fa-rupiah

### ISSUE THREAD

**Issue by dwikodit** [FortAwesome/Font-Awesome#11816] opened 2017-11-30 04:20 UTC
Please add icon of Indonesian Locale currency symbol : Rupiah
![rupiah](https://user-images.githubusercontent.com/7536887/33412903-f6215ca2-d5c0-11e7-8cbd-817f3f8b761d.jpg)

**Comment by PeterShaggyNoble** [comment] 2017-11-30 09:19
Duplicate of #1683 (which you +1ed *before* posting this!).

**Closed** 2017-11-30 09:29 UTC
