### ISSUE TITLE
request: Google Play

### ISSUE THREAD

**Issue by pete-varga** [FortAwesome/Font-Awesome#9825] opened 2016-08-27 12:08 UTC
Hi, is there a possibility for a Google Play icon to be made? Thank you.

**Comment by tagliala** [comment] 2016-08-27 18:24
Duplicate of #2272  (as you know), please add a 👍  reaction to that request (as you did)

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-27 18:24 UTC

**Comment by pete-varga** [comment] 2016-08-27 19:03
The request has been up since Oct 28, 2013 (!!!). Will this icon ever be created? When Instagram updated their icon recently, it was available on Font Awesome the day after... Or shall we look for a different solution? This is honestly very unprofessional.
