### ISSUE TITLE
[Feature-Request] Icons for linux distributions

### ISSUE THREAD

**Issue by shibumi** [FortAwesome/Font-Awesome#9584] opened 2016-07-17 23:28 UTC
Hey,
I would do it my self, but I am not very talented in graphic design. It would be nice if Awesome font would have icons for the bigger linux distributions:

* Arch Linux
* Debian
* Ubuntu
* Gentoo
* Opensuse
* Slackware
* Fedora
* CentOS

**Comment by aethior** [comment] 2016-07-18 08:02
Duplicate of #980 (ubuntu, centos, redhat, fedora, suse) and #1125 (debian).

**Comment by tagliala** [comment] 2016-07-18 09:44
Closing here, please open individual requests for other missing distros

**Closed by tagliala** 2016-07-18 09:44 UTC
