### ISSUE TITLE
Icon request: fa-forward / fa-backward (for pagination)

### ISSUE THREAD

**Issue by quasipickle** [FortAwesome/Font-Awesome#2833] opened 2014-02-03 19:09 UTC
I use fa-[forward / backward]-step as icons in pagination to go to the first and last pages.  To me, the current fa-forward and fa-backward don't communicate moving only one page, when compared with fa-forward-step and fa-backward-step.

A single triangle as used in fa-[forward / backward]-step without the line would, I think, be useful as it looks very similar to the fa-[forward / backward]-step icons, so it's purpose can be inferred.

**Comment by ecommunities** [comment] 2015-04-03 17:11
+1

**Comment by Crissov** [comment] 2016-02-04 13:55
This seems to be a duplicate of issue #6495 graphically, not semantically. (Or vice versa.)

**Comment by sensibleworld** [comment] 2024-07-11 13:56
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 13:56 UTC
Labels: new icon, video player icons, Declined
