### ISSUE TITLE
Icon Request: fa fa-oscommerce

### ISSUE THREAD

**Issue by Narayan1214** [FortAwesome/Font-Awesome#7477] opened 2015-09-17 12:36 UTC
hello,
i need a oscommerce icon to add it in my website

**Comment by caduvieira** [comment] 2015-09-17 12:49
dupe of #4885 ?

**Comment by Googlecloud12** [comment] 2015-09-17 12:53
http://www.magentocommerce.com/

**Comment by Narayan1214** [comment] 2015-09-17 12:54
what you mean by dupe of #4885 ??

**Comment by Googlecloud12** [comment] 2015-09-17 12:56
Not yet Still has to know wht is this ??

**Comment by caduvieira** [comment] 2015-09-17 12:56
Is it the same request of #4885 ?

**Comment by Narayan1214** [comment] 2015-09-17 12:58
this is the same request of #4885 so what i do??
i need this icon so give me correct solution

**Comment by caduvieira** [comment] 2015-09-17 13:05
+1 that issue and wait for it to be done or customize FontAwesome

Read more in:
https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md
https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by tagliala** [comment] 2015-09-17 13:05
@Narayan1214 please +1 #4885

Closing here

**Comment by tagliala** [comment] 2015-09-17 13:05
@caduvieira thanks

**Closed by tagliala** 2015-09-17 13:05 UTC
