### ISSUE TITLE
Icon request: fa fa-shark

### ISSUE THREAD

**Issue by Molly-Scott** [FortAwesome/Font-Awesome#16584] opened 2020-05-06 22:55 UTC
Hi there, I am a shark biologist using leaflet to make interactive maps of their movements. It would be amazing to have a shark icon for me to make icons with on my map. Please let me know if this is possible.

**Comment by tagliala** [comment] 2020-05-07 07:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4468, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-07 07:26 UTC
