### ISSUE TITLE
Icon Request: fa-mixer-light | fa-mixer-dark

### ISSUE THREAD

**Issue by KensonPlays** [FortAwesome/Font-Awesome#13005] opened 2018-05-02 19:00 UTC
Mixer is an amazing new streaming site, already becoming a competitor to Twitch.

They have a ultra-low latency (less than half a second on average), interactive buttons, and a super friendly and happy community.

Here's a link to their branding kit:
https://github.com/mixer/branding-kit

And 2 of their more popular icons:
https://github.com/mixer/branding-kit/blob/master/png/MixerMerge_Dark.png (for use on dark backgrounds)
https://github.com/mixer/branding-kit/blob/master/png/MixerMerge_Light.png (for use on light backgrounds)

And I know of at least 30 or so other streamers (if not more) who would love to use this! (The site has only existed for 2 years, but is growing fast every day!)

**Comment by tagliala** [comment] 2018-05-02 22:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11242, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-02 22:05 UTC
