### ISSUE TITLE
Icon request: currency-idr

### ISSUE THREAD

**Issue by timpamungkas** [FortAwesome/Font-Awesome#9268] opened 2016-05-24 10:31 UTC
Can you please add icon for Indonesian Rupiah (IDR)?
This will be used for e-commerce cash payment icons. Also maybe for other site that requires indonesian currency

IDR logo is basically consists of 2 letters : **Rp**
No special character or image required, only capital "R" and smallcap "p" joined together

Thank you

**Comment by tagliala** [comment] 2016-05-24 11:30
Duplicate of #1683, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-24 11:30 UTC
