### ISSUE TITLE
Icon request:  fa-brands fa-openai,fab fa-openai

### ISSUE THREAD

**Issue by hasanmerkit** [FortAwesome/Font-Awesome#20290] opened 2024-07-13 05:58 UTC
Please add OpenAI brand logo.

![openai-svgrepo-com](https://github.com/user-attachments/assets/753d4346-15c5-41f0-98a8-1fa124b4383e)

**Comment by tagliala** [comment] 2024-07-15 06:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19503 , please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-07-15 06:33 UTC
