### ISSUE TITLE
Icon request: icon-plus-minus

### ISSUE THREAD

**Issue by benji014628** [FortAwesome/Font-Awesome#14264] opened 2018-11-12 13:56 UTC
I want this to be used for a Calcalculator

This icon as many uses:
In mathematics, it generally indicates a choice of exactly two possible values, one of which is the negation of the other.
In experimental sciences, the sign commonly indicates the confidence interval or error in a measurement, often the standard deviation or standard error.[1] The sign may also represent an inclusive range of values that a reading might have.
In engineering the sign indicates the tolerance, which is the range of values that are considered to be acceptable, safe, or which comply with some standard, or with a contract.[2]
In botany it is used in morphological descriptions to notate "more or less".
In chemistry the sign is used to indicate a racemic mixture.
In chess, the sign indicates a clear advantage for the white player; the complementary sign ∓ indicates the same advantage for the black player.[3]

![image](https://user-images.githubusercontent.com/44789941/48351532-5947b580-e63f-11e8-9af7-4b8d37ee9500.png)

This is a duplicate.

**Comment by tagliala** [comment] 2018-11-12 21:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6885, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-11-12 21:08 UTC
