### ISSUE TITLE
[Website] Single Icon view page throws error

### ISSUE THREAD

**Issue by vishnu-dev** [FortAwesome/Font-Awesome#16403] opened 2020-04-01 15:08 UTC
**Describe the bug**
This page throws an error and crashes the whole website. Not able to access the icons list.
Throws a chunk load failed error (mostly because of vue build issues).

**To Reproduce**
Go to https://fontawesome.com/icons/trash-alt?style=regular
Go to https://fontawesome.com/icons and click on any icon. Page crashes.

**Expected behavior**
Should be able to access the single font view page.

**Screenshots**
![image](https://user-images.githubusercontent.com/21088161/78152980-30080f00-7458-11ea-8691-4be2f7b9f11e.png)

**Bug report checklist**
- [*] I have filled out as much of the above information as I can
- [*] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [*] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2020-04-01 15:21
Hi!

Thanks for being part of the Font Awesome Community.

I cannot confirm, but I've go another errror:

```
Failed to load resource: the server responded with a status of 404 ()
``

@robmadole could you please check if you have any report from javascript?

**Comment by vishnu-dev** [comment] 2020-04-01 15:45
Weird. It seems to be working now. I think it might be either because of the server or because of large chunks that might not have been loaded due to internet connectivity. 
Still, I get below errors, Is it known?
Also, notice the chuck 12.something.js is huge.
![image](https://user-images.githubusercontent.com/21088161/78157667-dc98bf80-745d-11ea-8d05-4a9fc33ad7df.png)

**Comment by robmadole** [comment] 2020-04-01 16:40
The missing `/css/fa4.css` is certainly a bug. That file used to exist but it looks like it's vanished. We'll track it down and get it fixed.

**Comment by tagliala** [comment] 2020-06-18 21:16
No more 404, can't reproduce the initial issue, closing here

Feel free to comment if you get it again

**Closed by tagliala** 2020-06-18 21:16 UTC
Labels: bug, fontawesome.com
