### ISSUE TITLE
Bug:  v6.5.0 "Free For Web" zip download link no longer working

### ISSUE THREAD

**Issue by kprajapatii** [FortAwesome/Font-Awesome#20022] opened 2023-11-29 08:12 UTC
### Bug description

Latest Font Awesome v6.5.0 "Free For Web" zip download link no longer working at https://fontawesome.com/v6/download.
CSS file url https://use.fontawesome.com/releases/v6.5.0/css/all.css?wpfas=true is also not working.

It shows 404 not found error for above both pages.

### Font Awesome version

v6.5.0

### Serving

Other (as specified in the bug description)

### Implementation

CSS

### Browser and Operating System

Any browser

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2023-11-29 08:14
Hi!

Thanks for being part of the Font Awesome Community and thanks for the report.

Confirmed error 404, I've assigned @talbs and @robmadole

**Comment by tagliala** [comment] 2023-11-29 08:25
Duplicate of #20018

**Closed as completed by tagliala** 2023-11-29 08:25 UTC
Labels: bug, fontawesome.com
