### ISSUE TITLE
v4.5.0 not showing in Packagist

### ISSUE THREAD

**Issue by PHLAK** [FortAwesome/Font-Awesome#7972] opened 2015-11-24 16:23 UTC
The `fortawesome/font-awesome` package is stuck at v4.4.0 on [Packagist](https://packagist.org/packages/fortawesome/font-awesome).

**Comment by LKay** [comment] 2015-11-25 02:27
I suppose `package.json`, `component.json` and bower file need to bump the version up.

**Comment by ackernaut** [comment] 2015-11-25 05:36
Yeah, I was not able to upgrade to 4.5.0 using npm.

**Comment by tagliala** [comment] 2015-11-25 11:57
I suppose this is caused by #7971

I'm trying to address this asap

**Comment by tagliala** [comment] 2015-11-25 11:58
Sorry, reopening here

**Comment by tagliala** [comment] 2015-11-30 17:39
Closing here, let me know if it was fixed

**Closed by tagliala** 2015-11-30 17:39 UTC
Labels: bug

**Comment by thedevsaddam** [comment] 2015-12-21 10:46
After version 4.4.0 the fonts are not showing, what's the problem in fa-4.5.0?
