### ISSUE TITLE
Icon request: icon-hellocoton

### ISSUE THREAD

**Issue by AntoineSoetewey** [FortAwesome/Font-Awesome#8778] opened 2016-03-17 17:07 UTC
Hi,

First of all, thank you for all the icons available. 

I was wondering whether it would be possible to have a similar icon for Hellocoton. In case you do not know what I am talking about, here is [a link of the icon I am looking for](http://onthego.rainbowsandpotsofgold.com/static/design/hellocoton_logo.png). If available in the future, I would use it in my blog to have a direct link to my page on Hellocoton, so the visitors would easily see my page.

Thanks in advance.

Best regards,
Antoine Soetewey

**Comment by tagliala** [comment] 2016-03-17 20:00
duplicate of #5008, please +1 that request

closing here

**Closed by tagliala** 2016-03-17 20:00 UTC
