### ISSUE TITLE
Icon request: alexa-o

### ISSUE THREAD

**Issue by benkopf20** [FortAwesome/Font-Awesome#12869] opened 2018-04-16 17:45 UTC
### What can it be used for?

In places where we are representing input methods to a system such as tablet, pc, phone, etc.

### Example image (optional)

![alexa-o](https://user-images.githubusercontent.com/16151729/38825940-48522a7a-417c-11e8-80e9-15d68861eeec.png)

### Icon request checklist

- [x ] single (for original alexa only; need dedicated Dot, Show, etc. icons)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-16 17:55
Hi!

Thanks for being part of the Font Awesome Community.

This is not a duplicate of #7803, am I right?

#7803 is Alexa brand, this is actually the alexa object, right?

**Comment by damianfok** [comment] 2019-03-22 10:39
+1

**Comment by tagliala** [comment] 2019-03-22 11:04
No feedback, closing here

**Closed by tagliala** 2019-03-22 11:04 UTC
Labels: waiting for feedback
