### ISSUE TITLE
Icon Request : Parking icon

### ISSUE THREAD

**Issue by You85** [FortAwesome/Font-Awesome#11364] opened 2017-08-06 12:06 UTC
![parking-icon-png-2](https://user-images.githubusercontent.com/30325749/29003077-6438da06-7ab0-11e7-97d8-c9eff6ff1dcf.png)

**Comment by tagliala** [comment] 2017-08-06 12:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1559 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-06 12:27 UTC
