### ISSUE TITLE
Icon Request: fa-upload-arrow

### ISSUE THREAD

**Issue by ShubhamKushwah** [FortAwesome/Font-Awesome#11827] opened 2017-12-03 09:56 UTC
![upload-upload-icon-73240](https://user-images.githubusercontent.com/24874033/33524225-4ed3895e-d83e-11e7-8549-066c96bbab6c.png)

There is no 'upload' icon like that, and I need one like this.

**Comment by tagliala** [comment] 2017-12-03 13:17
Hi!

Thanks for being part of the Font Awesome Community.

We already have a couple of upload icons: There is http://fontawesome.io/icon/upload/ http://fontawesome.io/icon/cloud-upload/

If you need exactly this design, I should suggest you to consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

I would consider this as a possibly duplicate of #1020 (export) and I'm closing here for the moment

**Closed by tagliala** 2017-12-03 13:17 UTC

**Comment by waylan100** [comment] 2019-08-29 01:15
https://gist.github.com/waylan100/8f15c682972123ba6197191c76d3fad2/ebe9a5a63dc11550df620f1cc2438a6129a33ac0
