### ISSUE TITLE
Icon request: fa-threema

### ISSUE THREAD

**Issue by kevinbazira** [FortAwesome/Font-Awesome#13800] opened 2018-08-22 08:58 UTC
### What can it be used for?

Any website or mobile application that would like to add the threema icon in reference to the [threema app](https://threema.ch/en). Case in point: We would like to add a share button with the threema icon on our web page.

### Example image (optional)

[![Threema Square](https://upload.wikimedia.org/wikipedia/commons/4/42/Threema.png)](https://upload.wikimedia.org/wikipedia/commons/4/42/Threema.png)

[![Threema Circlet](https://images-fe.ssl-images-amazon.com/images/I/51bOWAwTvTL.png)](https://images-fe.ssl-images-amazon.com/images/I/51bOWAwTvTL.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-22 14:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7057, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-22 14:39 UTC
