### ISSUE TITLE
Icon request: data-room

### ISSUE THREAD

**Issue by mkollarc** [FortAwesome/Font-Awesome#15441] opened 2019-08-28 07:36 UTC
This icon can be used for representing data rooms, securely files stored online or vaults.

Example image
![image](https://user-images.githubusercontent.com/54618801/63835071-4cffcf80-c9a9-11e9-8834-52103a9a418e.png)

**Comment by aethior** [comment] 2022-03-11 12:12
Hi @mkollarc,

This icon has ben added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/vault

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-11 12:25
Duplicate of #1813

**Closed by tagliala** 2022-03-11 12:25 UTC
