### ISSUE TITLE
Candy

### ISSUE THREAD

**Issue by iamsfs** [FortAwesome/Font-Awesome#11856] opened 2017-12-07 15:10 UTC
Need icons related to food items, such as CANDY !

Thnx

**Comment by tagliala** [comment] 2017-12-07 15:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6015, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-12-07 15:14 UTC

**Comment by iamsfs** [comment] 2017-12-07 15:18
Plz see this, 
![screenshot 2017-12-07 20 16 19](https://user-images.githubusercontent.com/3155371/33722421-b4fd2d5c-db8b-11e7-9c91-b9c539a913a0.png)

**Comment by tagliala** [comment] 2017-12-07 15:24
@iamsfs 

Sorry, I mean "search existing requests", as in "search existing issues first" in the screenshot you've posted:

![image](https://user-images.githubusercontent.com/556268/33722704-035fed7a-db6b-11e7-956c-fcd0b2748002.png)


I will edit my saved reply to be more clear
