### ISSUE TITLE
Icon Request: Discord

### ISSUE THREAD

**Issue by n8-sd** [FortAwesome/Font-Awesome#10827] opened 2017-03-22 20:09 UTC

**Comment by tagliala** [comment] 2017-03-22 22:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10827, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-22 22:59 UTC
