### ISSUE TITLE
Icon Request: fa-multi-flame

### ISSUE THREAD

**Issue by JosephSKh** [FortAwesome/Font-Awesome#11323] opened 2017-07-25 13:33 UTC
We need a more realistic fire icon like the fire in fa-free-code-camp but without the brackets, the fa-fire is more like a flame
Thanks !

**Comment by tagliala** [comment] 2017-07-25 13:51
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #3577, please 👍  that request

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-25 13:51 UTC
