### ISSUE TITLE
Cannot compile .less in FA6 

### ISSUE THREAD

**Issue by fpurser** [FortAwesome/Font-Awesome#18867] opened 2022-03-29 19:00 UTC
When compiling .less FA6 code I am getting:

`>> ParseError: Missing closing ')' in _sizing.less on line 15, column 16:`

Looking at the _sizing.less I see a new 'each' method that was not previously used in FA5. 

```
// step-based scale (with alignment)
each(.fa-sizes(), {
.@{fa-css-prefix}-@{key} {
.fa-size(@value);
}
});
```

It appears similar 'each' methods exist in:

```
_icons.less
brands.less
```

Looking at `_list.less` does not have the each function mentioned above, is also throwing error with the element `.@{fa-css-prefix}-li` with `Missing closing ')`

`left: calc(~'var(--@{fa-css-prefix}-li-width, @{fa-li-width})' * -1);`

These changes seem to be a result of new code from FA5 -> FA6 when comparing versions. 

Thank you,

**Comment by tagliala** [comment] 2022-03-29 19:13
Hi,

thanks for reporting this.

Unfortunately it is an issue we are aware of but we didn't make for 6.1.1

It will be fixed in the next version of FA

Closing as a duplicate of #18835

**Closed as completed by tagliala** 2022-03-29 19:13 UTC

**Comment by fpurser** [comment] 2022-03-29 19:22
> Hi,
> 
> thanks for reporting this.
> 
> Unfortunately it is an issue we are aware of but we didn't make for 6.1.1
> 
> It will be fixed in the next version of FA
> 
> Closing as a duplicate of #18835

Thank you @tagliala. Almost seems like this may be related: https://github.com/less/less.js/issues/3339#issuecomment-443835247
