### ISSUE TITLE
Icon Request: fa-newgrounds

### ISSUE THREAD

**Issue by nitram** [FortAwesome/Font-Awesome#8083] opened 2015-12-04 11:43 UTC
![newgrounds](https://cloud.githubusercontent.com/assets/2828767/11588936/9977de14-9a84-11e5-9033-2e631ae989cb.png)

**Comment by tagliala** [comment] 2015-12-04 13:16
duplicate of #5569, please +1 that request

closing here

**Closed by tagliala** 2015-12-04 13:16 UTC
