### ISSUE TITLE
Icon request: pregnant

### ISSUE THREAD

**Issue by ruindano** [FortAwesome/Font-Awesome#15984] opened 2019-12-23 03:21 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-12-23 07:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1819, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-12-23 07:45 UTC

**Comment by ruindano** [comment] 2020-01-12 19:12
![Screenshot_2020-01-13-02-09-22-52](https://user-images.githubusercontent.com/41555496/72224177-c2132080-35a9-11ea-8320-86aa549c60c4.png)

I am sorry, can you add an icon of a pregnant woman like the one in material design

**Comment by tagliala** [comment] 2020-01-12 20:43
@ruindano please add a 👍 reaction to #1819

If you want to know how requests work, please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs)
