### ISSUE TITLE
Icon request: icon-cash-register

### ISSUE THREAD

**Issue by ivanlori** [FortAwesome/Font-Awesome#3467] opened 2014-05-18 18:54 UTC
Hello!
I need this icon for my website ->
![11-128](https://cloud.githubusercontent.com/assets/7620920/3008458/9b90fd22-debd-11e3-818c-1f086479aa8a.png)

I think that this one is useful to represent merchant's job

thank you!

**Comment by rocwang** [comment] 2015-01-25 22:20
+1

**Comment by sunburntkamel** [comment] 2015-02-02 19:53
+1

**Comment by krisdahl** [comment] 2015-02-20 01:29
+1.

But this is a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/1489

**Comment by stijnvanbael** [comment] 2015-03-30 07:53
+1

**Comment by lowerends** [comment] 2015-05-04 11:27
+1

**Comment by grizzm0** [comment] 2015-05-20 09:09
+1

**Comment by rtroncoso** [comment] 2015-05-22 18:24
+1

**Comment by ssouris** [comment] 2015-06-10 21:11
+1

**Comment by JorisH** [comment] 2015-06-12 14:27
+1

**Comment by damirojo** [comment] 2015-07-16 15:07
+1

**Comment by E-P1983** [comment] 2015-08-03 20:12
+1

**Comment by ivanjaros** [comment] 2015-08-07 14:16
+1 :D

**Comment by nxlevel** [comment] 2015-08-14 01:41
+1

**Comment by Dan-Brantze** [comment] 2015-08-27 05:40
+1

**Comment by MirandaBrazil** [comment] 2015-09-16 08:34
+10

**Comment by RubenDjOn** [comment] 2015-09-25 19:34
+1

**Comment by Wilbertvn** [comment] 2015-11-24 10:09
+9000

**Comment by KimTranjan** [comment] 2015-11-27 13:13
:+1: please. :)

**Comment by smithandre** [comment] 2015-11-29 14:14
+1

**Comment by MVcodeartbr** [comment] 2015-11-29 22:40
+1

**Comment by ptcampos** [comment] 2015-12-07 21:07
+1

**Comment by andreaslarssen** [comment] 2015-12-09 16:53
+1

**Comment by einewton** [comment] 2015-12-22 01:23
+1

**Comment by rachellji** [comment] 2016-01-22 23:45
+1

**Comment by colinceo** [comment] 2016-02-11 20:44
+1

**Comment by GuerrillaCoder** [comment] 2016-03-11 16:57
+1

**Comment by sblackstone** [comment] 2016-03-16 15:54
+1

**Comment by Wilbertvn** [comment] 2016-03-16 23:47
Gonna hate it when you auto subscribe to stuff like this and get every "+1".

**Comment by demiscient** [comment] 2016-04-15 04:57
+1

**Comment by PeterShaggyNoble** [comment] 2016-04-15 08:53
+1

**Comment by wakasann** [comment] 2016-04-30 03:40
+1

**Comment by ccrichter** [comment] 2016-05-24 08:12
+1

**Comment by nxlevel** [comment] 2016-05-25 17:19
+100

**Comment by Melloyell** [comment] 2016-06-08 15:35
+1

**Comment by buccfer** [comment] 2016-06-19 21:25
+1

**Comment by diego123456789** [comment] 2016-06-20 22:22
+1

**Comment by enatividad** [comment] 2016-06-24 03:59
+1

**Comment by matijaabicic** [comment] 2016-07-07 17:55
+1

**Comment by davidwillianx** [comment] 2016-07-14 18:22
+1

**Comment by sblackstone** [comment] 2016-07-14 19:35
This is a terrible ticket to be subscribed to =)

**Comment by ronnyp07** [comment] 2016-09-05 22:11
+1

**Comment by Aquaj** [comment] 2016-09-19 15:12
+1

**Comment by hardy2defy** [comment] 2016-09-21 23:09
+1

**Comment by oucil** [comment] 2016-09-22 01:19
+1

**Comment by adbarrett** [comment] 2016-12-20 16:39
+1

**Comment by guzinski** [comment] 2017-01-22 17:05
+1

**Comment by TedManowar** [comment] 2017-02-22 11:52
+1 can't believe this isn't included yet...

**Comment by Deno028** [comment] 2017-02-28 01:53
+1

**Comment by casanovaexposito** [comment] 2017-03-13 16:59
+1

**Comment by tatterdemalion** [comment] 2017-03-19 13:52
+1

**Comment by EduardoLuzzi** [comment] 2017-03-24 14:12
+1

**Comment by canky** [comment] 2017-04-19 17:13
+1

**Comment by FerBonfim** [comment] 2017-05-22 19:10
+1

**Comment by codibit** [comment] 2017-05-31 06:38
+1

**Comment by bochom** [comment] 2017-06-01 04:54
+1

**Comment by filipemendespi** [comment] 2017-07-20 12:56
+1

**Comment by sblackstone** [comment] 2017-07-20 14:44
I enjoy every 3 weeks, a +1 pops into my mailbox.... #thedreamisreal

**Comment by Rainzart** [comment] 2017-07-25 19:13
+1

**Comment by thechairman007** [comment] 2017-07-27 19:32
+1

**Comment by prputnam-sv** [comment] 2017-10-04 15:10
+1

**Comment by dexolutions** [comment] 2017-10-05 08:04
+1

**Comment by SuperUserNameMan** [comment] 2017-10-23 13:23
so we have a shower and a bath-tube, but not yet a cash-register ?

**Comment by timtjtim** [comment] 2017-10-23 13:28
Those seem rather unrelated 😂

**Comment by dbmedia** [comment] 2017-11-05 14:11
+1

**Comment by aswinehart** [comment] 2017-11-07 21:23
+1

**Comment by shimbala** [comment] 2017-11-21 06:34
+1

**Comment by mrjleo198901** [comment] 2017-12-11 20:06
almost 2018, +1 XD
pls FA

**Comment by danielone** [comment] 2017-12-21 09:31
+1

**Comment by sblackstone** [comment] 2017-12-21 17:14
Happy Holidays all you +1ers.

Member since March 2016 :-)

**Comment by tonietonia** [comment] 2018-01-31 15:26
+1

**Comment by luisgjb** [comment] 2018-02-20 18:35
3 years ..... and nothing +1111

**Comment by nimeshabuddhika** [comment] 2018-03-05 14:13
+1

**Comment by ayazhussein** [comment] 2018-03-19 22:43
+1

**Comment by diegolucena** [comment] 2018-04-18 00:29
+1

**Comment by babak-deghat** [comment] 2018-04-18 11:54
+1

**Comment by gersonhoyle** [comment] 2018-04-26 22:11
+1

**Comment by wazzu3000** [comment] 2018-04-27 14:30
+1

**Comment by olivierFr** [comment] 2018-05-11 14:37
+1

**Comment by iFlash** [comment] 2018-05-15 10:05
Wow. Four years, lots of +1 and still you do not even bother to comment as to why this is ignored?

**Comment by olivierFr** [comment] 2018-05-15 10:38
I'm happy with the fontawesome 5 and I bought a pro license:-) 

But it's true that it would be very useful to have additional icons about the professional environment, especially shops: cash register and POS terminal, open cash drawer, closed cash drawer, client display, X and Z reports, label printer, receipt printer, barcode reader, Euro currency in square and round version.

**Comment by sensibleworld** [comment] 2018-05-15 11:37
Hey folks! We’re getting back on track with requested icons. You can follow along with progress and recent releases here: https://fontawesome.com/community/leaderboard/released

**Comment by davidbogdan** [comment] 2018-06-01 04:40
+1

**Comment by lusvelt** [comment] 2018-06-06 19:36
+1

**Comment by felipefdl** [comment] 2018-06-14 01:15
+1

**Comment by AlfredoSolisFrausto** [comment] 2018-09-05 05:35
+1

**Comment by r-man** [comment] 2018-09-06 19:39
+1

**Comment by JoeriTheGreat** [comment] 2018-10-02 06:16
+1

**Comment by ivanlori** [comment] 2018-10-09 08:10
How many years to approve this icon?

**Comment by leovogel** [comment] 2018-11-12 18:34
+1

**Comment by sensibleworld** [comment] 2018-12-12 13:13
This icon checks out: 
https://fontawesome.com/icons/cash-register?style=solid

**Closed by sensibleworld** 2018-12-12 13:13 UTC
Labels: new icon, payment (category), released, web application icons
