### ISSUE TITLE
Icon Request: fa-ongoing-call

### ISSUE THREAD

**Issue by staniox** [FortAwesome/Font-Awesome#8774] opened 2016-03-17 13:45 UTC
![plainicon com-40268-512px 1](https://cloud.githubusercontent.com/assets/17677934/13847742/fad43918-ec24-11e5-9117-260d1954e783.png)

**Comment by tagliala** [comment] 2016-03-17 13:54
is this a brand?

**Comment by staniox** [comment] 2016-03-17 14:02
not just an icon that we use in our system we would like to share

2016-03-17 9:55 GMT-04:00 Geremia Taglialatela <notifications@github.com>:

**Comment by tagliala** [comment] 2016-03-17 14:28
does this icon represent a call in progress?

**Comment by staniox** [comment] 2016-03-17 14:49
yes ^^

2016-03-17 10:29 GMT-04:00 Geremia Taglialatela <notifications@github.com>:

**Comment by tagliala** [comment] 2016-03-17 15:37
could this be considered a duplicate of #3701 (outgoing call)?

**Comment by staniox** [comment] 2016-03-17 15:54
not because the # 3701 are icons of receiving and making calls my icon
is ongoing call


2016-03-17 11:38 GMT-04:00 Geremia Taglialatela <notifications@github.com>:

**Comment by staniox** [comment] 2016-03-21 18:45
hello, do you have news?

2016-03-17 11:54 GMT-04:00 Bruno Santos Gomes <brunogomes1958@gmail.com>:

**Comment by staniox** [comment] 2016-04-11 18:51
hello, do you have news?

2016-03-21 14:45 GMT-04:00 Bruno Santos Gomes <brunogomes1958@gmail.com>:

**Comment by tagliala** [comment] 2016-04-11 19:15
@staniox please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by sensibleworld** [comment] 2024-07-10 15:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/phone-volume?f=classic&s=solid)

**Closed by sensibleworld** 2024-07-10 15:23 UTC
Labels: new icon, web application icons (legacy category), FA Pro
