### ISSUE TITLE
Icon Request: 扫一扫 scan-it

### ISSUE THREAD

**Issue by Licoren** [FortAwesome/Font-Awesome#12127] opened 2018-01-18 03:05 UTC

**Comment by Licoren** [comment] 2018-01-18 03:10
![image](https://user-images.githubusercontent.com/35551330/35079037-262a94ea-fc40-11e7-8dac-4d32bd62b78e.png)

**Comment by Licoren** [comment] 2018-01-18 03:12
![image](https://user-images.githubusercontent.com/35551330/35079101-69044270-fc40-11e7-9a85-fb219b4d4db7.png)

**Comment by Licoren** [comment] 2018-01-18 03:13
![image](https://user-images.githubusercontent.com/35551330/35079135-9ea0f7c0-fc40-11e7-8a62-ad8e71b2ae6b.png)

**Comment by tagliala** [comment] 2018-01-18 10:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9485, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-18 10:07 UTC
