### ISSUE TITLE
Request Icon Line

### ISSUE THREAD

**Issue by bylinggha** [FortAwesome/Font-Awesome#11078] opened 2017-05-17 02:30 UTC
Hello! Could you please add an icon line?
Thank you!
![unnamed](https://cloud.githubusercontent.com/assets/10545136/26135988/69af20c4-3ae3-11e7-8aff-4b95fa84be18.png)

**Comment by tagliala** [comment] 2017-05-17 08:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2631 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-17 08:03 UTC
