### ISSUE TITLE
Icon Request: fa-stocktwits

### ISSUE THREAD

**Issue by PoornaNayak** [FortAwesome/Font-Awesome#10220] opened 2016-11-14 12:40 UTC
StockTwits is a social media platform designed for sharing ideas between investors, traders, and entrepreneurs. (similar to twitter)

Attached an image. Looking for a square image with rounded corners like http://fontawesome.io/icon/linkedin-square/ 
![stocktwits](https://cloud.githubusercontent.com/assets/3336235/20265165/848ac9c2-aa95-11e6-8ffd-c29a6a3ad5a6.png)

**Comment by tagliala** [comment] 2019-04-22 16:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3593, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-22 16:38 UTC
Labels: brand icon
