### ISSUE TITLE
Icon Request: icon-x-chart

### ISSUE THREAD

**Issue by krilllind** [FortAwesome/Font-Awesome#11117] opened 2017-05-26 22:08 UTC
Hello fellow members of the FontAwesome community.

I was scrolling through the icon lib trying to find icons sutable for displaying data visualization components, but I could only find five icons (and bar-char/bar-chart-o is the same icon), so I though maybe I could request some more icons to use.

If we take for example Microsoft Power BI, they use about 24 visualization components, and they have an icon for each and every one of them, maybe we can take some inspiration from them and build icons with much more AWESOMENESS then theirs ;)

I post some links to images for clarification.
[https://powerbi.microsoft.com/en-us/documentation/powerbi-service-change-the-type-of-visualization-in-a-report/](https://powerbi.microsoft.com/en-us/documentation/powerbi-service-change-the-type-of-visualization-in-a-report/)

[https://powerbicdn.azureedge.net/mediahandler/blog/legacymedia/5545.5_5F00_ByMonth.png](https://powerbicdn.azureedge.net/mediahandler/blog/legacymedia/5545.5_5F00_ByMonth.png)

**Comment by TotomInc** [comment] 2017-05-27 00:39
Please fix your links, they redirect to `https://github.com/FortAwesome/Font-Awesome/issues/url` which is a 404.

**Comment by krilllind** [comment] 2017-05-27 08:45
@TotomInc I have fixed the URL:s now! Thank you for reporting my misstake! :)

**Comment by tagliala** [comment] 2017-05-27 08:50
Hi!

Thanks for being part of the Font Awesome Community.

How many icons you are requesting?

**Comment by krilllind** [comment] 2017-05-27 09:14
@tagliala Thank you for your reply.

Right now FontAwesome only has the [Area](http://fontawesome.io/icon/area-chart/), [bar](http://fontawesome.io/icon/bar-chart/), [line](http://fontawesome.io/icon/line-chart/) and the [pie](http://fontawesome.io/icon/pie-chart/) chart. But I would like to see some more well used chart icons, such as:

- Grid icon
- Pivot (grid) icon
- Treemap icon
- Gauges icon (could be something like a [thermometer](http://fontawesome.io/icon/thermometer-full/), but there are lots of them)
- Textbox icon

I found this page from DevExtreme that has an demo page using icons for visualization components. Check out the [link](https://demos.devexpress.com/Dashboard/?mode=designer&dashboardId=SalesOverview) and hover the icons to see what they correspond to.

So to answer your question, I would like to see 3-5 new ones in priority order (top to bottom) :)

**Comment by tagliala** [comment] 2017-05-27 09:22
Thanks, got it.

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

This request does not meet the following points:
> * Please search to see if your icon request already exists. If a request is found, please add a 👍 reaction to that one.
> * Please do not request comprehensive sets of icons related to a very specific field.
> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> * Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

Treemap is a duplicate of #1461, there could be others

Please also take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application) our suggestion is to customize Font Awesome.

*(replace weather icons with chart icons)*

Closing here, hope it helps

**Closed by tagliala** 2017-05-27 09:22 UTC

**Comment by krilllind** [comment] 2017-05-27 09:31
The treemap request [#1461](https://github.com/FortAwesome/Font-Awesome/issues/1461) is only one out of five icons I feel that the FontAwesome lib is in need of. I feel like this issue could stay open for community users to post more chart icons to. 

I am stíll requesting both the grid and pivot grid icons, which both fall under the same "chart" title.

![image](https://cloud.githubusercontent.com/assets/14158744/26520295/e7c8bfda-42cf-11e7-91a4-e1fd22a7da44.png)
![image](https://cloud.githubusercontent.com/assets/14158744/26520302/fae135fc-42cf-11e7-928c-5a280dc9c55e.png)

**Comment by tagliala** [comment] 2017-05-27 10:07
> I am stíll requesting both the grid and pivot grid icons, which both fall under the same "chart" title.

Please open new, individual requests and provide a single color example of the icon you need

we already have a grid icon: http://fontawesome.io/icon/th/
