### ISSUE TITLE
Icon Request: icon-flip

### ISSUE THREAD

**Issue by mainIine** [FortAwesome/Font-Awesome#2531] opened 2013-12-04 13:22 UTC
Needed for an WYSIWYG-Editor to flipping an Image.
![object-flip-horizontal-icon](https://f.cloud.github.com/assets/834814/1673390/1550f86e-5ce7-11e3-94e8-e75b6ecfdf3c.png)

Regards, Daniel

**Comment by sensibleworld** [comment] 2024-07-11 14:12
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/3955)

**Closed by sensibleworld** 2024-07-11 14:12 UTC
Labels: new icon, web application icons (legacy category), Duplicate
