### ISSUE TITLE
Icon request: fa-plane-departure & fa-plane-arrival

### ISSUE THREAD

**Issue by sjacq** [FortAwesome/Font-Awesome#10074] opened 2016-10-16 15:57 UTC
Hi,

Would be great to have a couple of icons like these for departures and arrivals:

https://www.iconfinder.com/icons/175097/airplane_takeoff_icon#size=128
https://www.iconfinder.com/icons/175663/airplane_landing_icon#size=128

Rgds

**Comment by tagliala** [comment] 2016-10-16 20:04
Duplicate of #326, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-16 20:04 UTC
