### ISSUE TITLE
req new icon

### ISSUE THREAD

**Issue by joserizal99** [FortAwesome/Font-Awesome#11005] opened 2017-04-28 11:47 UTC
blackberry
line

**Comment by tagliala** [comment] 2017-04-28 11:49
Hi!

Thanks for being part of the Font Awesome Community.

Blackberry is a duplicate of #1537, please add a 👍  reaction to that request.
Line is a duplicate of #2631 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-28 11:49 UTC
