### ISSUE TITLE
Icon request: icon-eho

### ISSUE THREAD

**Issue by StevenCrocker** [FortAwesome/Font-Awesome#13033] opened 2018-05-03 23:56 UTC
### What can it be used for?

Can be used as a badge on any website dealing with real estate sale or rental.

### Example image (optional)

https://www.hud.gov/library/bookshelf11/hudgraphics/fheologo

### Icon request checklist

- [ X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-05-04 08:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3574, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-04 08:45 UTC
