### ISSUE TITLE
Icon Request: fa-javascript

### ISSUE THREAD

**Issue by bmiddha99** [FortAwesome/Font-Awesome#6671] opened 2015-06-05 14:52 UTC
I would really like you you guys added icons for web technologies like javascript,php,jquery,mysql,and others.
Thanks for the awesome vector icons.
Love them.

**Comment by bomb-on** [comment] 2015-06-05 15:04
+1!!
[There is something similar already](http://fizzed.com/oss/font-mfizz), although it is not maintained anymore... Nevertheless, it would be AWESOME to have them all in one package, rather than including few more other CSS...

**Comment by tagliala** [comment] 2015-06-05 15:46
duplicate of #1711 , please +1 that request

please also consider using mfizz for technology icons

Closing here

**Closed by tagliala** 2015-06-05 15:46 UTC

**Comment by bmiddha99** [comment] 2015-06-11 07:40
Thanks
