### ISSUE TITLE
Icon request: TeamViewer

### ISSUE THREAD

**Issue by cyripton** [FortAwesome/Font-Awesome#18187] opened 2021-08-19 23:26 UTC
**What can it be used for?**
If teamviewer is used in a project, it can be displayed with an icon / image

**Example image (optional)**
![TeamViewer_icon_2](https://user-images.githubusercontent.com/86688773/130156608-55d1cfef-cf65-40d7-abc7-0714a441f63a.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-08-20 06:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5383, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-08-20 06:54 UTC
