### ISSUE TITLE
Icon request: Cricket

### ISSUE THREAD

**Issue by Sudhindra21** [FortAwesome/Font-Awesome#15467] opened 2019-09-01 08:30 UTC
**What can it be used for?**
Cricket Objects

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-09-01 09:35
Hi!

Thanks for being part of the Font Awesome Community.

This request may be a duplicate of 
- #5706 cricket bat
- #7200 cricket ball
- #7201 cricket glove

Please add a 👍 reaction to the request you want.

If this is not a duplicate, please fix the title. Please also keep in mind that the contributing guidelines for the free repository does not allow requests for icon sets (eg: cricket objects)

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-01 09:35 UTC
