### ISSUE TITLE
Icon request: slideshow

### ISSUE THREAD

**Issue by hejmsdz** [FortAwesome/Font-Awesome#994] opened 2013-05-01 21:25 UTC
Something similar to:
![slideshow-icon](https://cloud.githubusercontent.com/assets/7750325/3137117/b289497e-e84c-11e3-9a8b-381be8d63a82.png)
![download](https://cloud.githubusercontent.com/assets/7750325/3137124/d53e3a24-e84c-11e3-9cb8-0690250cbc75.jpg)

**Comment by AlexVanDamn** [comment] 2015-01-14 13:53
+1

**Comment by 3Nex** [comment] 2015-02-18 15:19
+1 
One more example: http://png-1.findicons.com/files/icons/1598/di_black_folder/256/presentation.png

**Comment by AlexVanDamn** [comment] 2015-03-05 03:47
![slideshow](https://cloud.githubusercontent.com/assets/2526545/6498928/19fb7cba-c2fb-11e4-9db8-c80124312ef6.png)

**Comment by kranthilakum** [comment] 2015-04-16 11:27
+1

**Comment by gagetaylor** [comment] 2015-05-01 19:47
+1

**Comment by thetron** [comment] 2015-05-07 03:52
+1

**Comment by WispProxy** [comment] 2015-05-07 05:50
+1

**Comment by doc-cb** [comment] 2015-05-07 22:24
+1

**Comment by igorlino** [comment] 2015-06-11 20:55
+1

**Comment by TabeebOsama** [comment] 2015-07-02 17:04
+1

**Comment by HunterJoe** [comment] 2015-07-20 12:27
+1

**Comment by bluemanos** [comment] 2015-08-24 16:06
+1

**Comment by jwegner** [comment] 2015-09-02 09:30
+1

**Comment by hnmcc** [comment] 2015-09-09 13:22
+1

**Comment by newgrounds** [comment] 2015-09-19 02:18
+1

Maybe something like this one:
![137-presentation 2x](https://cloud.githubusercontent.com/assets/667311/9974206/2662fb7e-5e53-11e5-8677-b66415f050a7.png)

**Comment by We-St** [comment] 2015-10-21 14:20
+1

**Comment by jesselpalmer** [comment] 2015-12-08 01:56
+1

**Comment by integrasistemas** [comment] 2015-12-09 18:55
+1

**Comment by jackycute** [comment] 2015-12-17 07:34
+1

**Comment by Crissov** [comment] 2016-02-04 14:21
Related standard icon, confusingly named “strobe”, but its description reads “display a succession of still pictures on a screen”:

[![IEC 60417-5318](https://www.iso.org/iobp/graphics/grs/ISO263473_200.png)](https://gnbs.isolutions.iso.org/obp/ui#iec:grs:60417:0:5318)

**Comment by matthiku** [comment] 2016-03-03 10:22
+

**Comment by ttseng** [comment] 2016-05-18 22:00
+1

**Comment by madkiss** [comment] 2016-10-18 12:14
+1

**Comment by isiryder** [comment] 2016-11-03 15:00
+1

**Comment by git-emil** [comment] 2016-11-17 10:56
+1

**Comment by chrisma** [comment] 2017-01-23 22:28
+1

**Comment by sebastian-raubach** [comment] 2017-03-22 16:32
+1

**Comment by kasparsklavins** [comment] 2017-04-29 16:32
I like the newgrounds suggestion.

**Comment by balping** [comment] 2017-08-14 19:52
+1

**Comment by luishmelo** [comment] 2017-11-27 11:18
+1

**Comment by sliceofbytes** [comment] 2018-02-08 22:52
+1

**Comment by ErickChacon** [comment] 2018-03-18 20:34
+1

**Comment by bitstorm** [comment] 2018-04-04 11:06
+1

**Comment by garretwilson** [comment] 2018-04-14 22:42
+1

Note that this seems to be a duplicate of #866.

**Comment by sensibleworld** [comment] 2020-11-04 15:08
<img width="1047" alt="Screen Shot 2020-11-04 at 10 07 00 AM" src="https://user-images.githubusercontent.com/529604/98128115-7d80aa80-1e85-11eb-9dbd-0092160ca24c.png">

We have a "presentation-screen" icon, along with some podium icons. Do these satisfy this request?

**Closed** 2020-11-12 13:50 UTC
Labels: new icon, released, video player icons
