### ISSUE TITLE
Icon request: Terrain / Mountain / Elevation

### ISSUE THREAD

**Issue by photogsy** [FortAwesome/Font-Awesome#12948] opened 2018-04-25 11:00 UTC
### What can it be used for?

It would be great to have some way to express terrain, elevation gain / loss, mountains, scenery, I think all of these could potentially be expressed with a mountain icon.

### Example image (optional)

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Mountain-Icon.svg/128px-Mountain-Icon.svg.png">
<img src="https://images.vexels.com/media/users/3/137476/isolated/lists/d89adf16dc6fce8b9abe54aec3af2546-four-peak-mountain-icon.png">

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-25 11:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4109, please add a 👍  reaction to that request.

> I have searched for existing issues and to the best of my knowledge this is not a duplicate

No problem 👍 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-25 11:52 UTC
