### ISSUE TITLE
Icon Request: fa-fish

### ISSUE THREAD

**Issue by arvind-iyer** [FortAwesome/Font-Awesome#9049] opened 2016-04-23 23:18 UTC
Just fish really. Spread some love to the seabiscuits

**Comment by tagliala** [comment] 2016-04-24 09:37
Duplicate of #2965 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-24 09:37 UTC
