### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by adaddayos** [FortAwesome/Font-Awesome#12692] opened 2018-03-24 16:49 UTC
Hi, It seems you have a typo for the class for this icon:

https://fontawesome.com/icons/paper-plane?style=solid

In the &lt;i&gt; tag, the leading class is "fas". Should this be "fa"?

Cheers,
Adam

**Comment by wolfy1339** [comment] 2018-03-27 14:26
This is a duplicate of #12710

**Closed** 2018-04-02 22:27 UTC
