### ISSUE TITLE
Icon Request: fa-empty-table-cell

### ISSUE THREAD

**Issue by jls2933** [FortAwesome/Font-Awesome#7411] opened 2015-09-08 06:42 UTC
This icon should be drawn using a dashed square.
Thank you ! :)

**Comment by caduvieira** [comment] 2015-09-10 16:08
dupe of #/2002 ?

**Comment by tagliala** [comment] 2015-09-11 11:15
any example?

**Comment by jls2933** [comment] 2015-09-11 18:03
I was thinking about table cell.
![fa-empty-table-cell](https://cloud.githubusercontent.com/assets/4441828/9822328/1c11b2b6-58c0-11e5-800f-1e2696b2f311.png)

**Comment by user-e** [comment] 2015-09-12 12:14
@tagliala 
**I am not part of this conversation or this request**,
but I noticed the *waiting for feedback* tag and that
*jls2933* has responded. You could remove the *waiting for feedback* tag.
**I understand that you may be busy though
so you may not currently have the time to do this task.**

**Comment by caduvieira** [comment] 2015-09-12 18:48
Like this? https://jsfiddle.net/sjtucr55/1/

**Comment by tagliala** [comment] 2015-09-12 20:25
I would call this a dashed square, but I'm almost fine with the title

**Comment by sensibleworld** [comment] 2024-07-10 21:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/square-dashed?f=classic&s=solid)

**Closed by sensibleworld** 2024-07-10 21:33 UTC
Labels: new icon, web application icons (legacy category), FA Pro
