### ISSUE TITLE
Icon Request: fa-user-with-graduation-cap

### ISSUE THREAD

**Issue by ceweb** [FortAwesome/Font-Awesome#9702] opened 2016-08-04 14:19 UTC
please see the following images. Need a students icon to be placed at many places. I need something for staff / teachers also but could not understand what kind of icon to take.

![scholar004](https://cloud.githubusercontent.com/assets/20840973/17405255/7af35f50-5a7c-11e6-82d5-cf7e408a4703.jpeg)
![scholar001](https://cloud.githubusercontent.com/assets/20840973/17405256/7af7261c-5a7c-11e6-98a2-88772de827bb.jpg)
![scholar002](https://cloud.githubusercontent.com/assets/20840973/17405258/7b09324e-5a7c-11e6-9e22-7ba5e601f917.jpg)
![scholar003](https://cloud.githubusercontent.com/assets/20840973/17405257/7aff7998-5a7c-11e6-9df4-14a448edda29.png)

**Comment by tagliala** [comment] 2016-08-04 16:08
IIRC this is a duplicate, but I'm not able to find the original request

Please also consider mortar-board: http://fontawesome.io/icon/graduation-cap/

**Comment by tagliala** [comment] 2016-08-04 16:09
Here it is: #4987

Duplicate of #4987, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-04 16:09 UTC
Labels: new icon, web application icons
