### ISSUE TITLE
Icon Request: fa-sport/fa-muscle

### ISSUE THREAD

**Issue by alexonbalangue** [FortAwesome/Font-Awesome#4331] opened 2014-09-04 14:50 UTC
icon request interested maybe....
fa-sport/fa-muscle/fa-footbal/fa-etc...
I found a lot free icon
http://www.flaticon.com/categories/sports
http://www.shutterstock.com/pic.mhtml?id=119069173&pl=13700-43068
http://www.shutterstock.com/pic.mhtml?id=2273275&pl=13700-43068

**Comment by tagliala** [comment] 2017-09-29 10:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2076, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-29 10:33 UTC
Labels: waiting for feedback
