### ISSUE TITLE
Size consistency

### ISSUE THREAD

**Issue by stof** [FortAwesome/Font-Awesome#1281] opened 2013-06-13 13:37 UTC
It would be great if all icons in the font were consistent in size. Currently, to have consistent icons in our menu, we need to add the `icon-large` class on some icons because they are smaller when applying the same font size.

**Comment by flq** [comment] 2015-04-21 07:13
trash and calendar do not seem to be of the same size...

**Comment by patie** [comment] 2015-08-20 19:19
the same font size.. looks ugly when each height is another :/
![snimka obrazovky 2015-08-20 o 21 18 05](https://cloud.githubusercontent.com/assets/760932/9393192/fd2aa128-4780-11e5-8c07-68e6e6904508.png)

**Comment by taivu** [comment] 2016-09-09 17:15
im also having this issue of icons being too different in height.

**Comment by fabionapodano** [comment] 2016-12-20 09:47
expecially the user icon, which is often used near to users icon, is way smaller

**Comment by tagliala** [comment] 2016-12-20 11:14
this problem should be addressed in the upcoming 5.0

**Comment by charlesr1971** [comment] 2017-02-08 13:33
As well as fa-fw, how about a fixed height class fa-fh. This would be so cool for icons that are positioned along a horizontal axis. For instance fa-list-alt & fa-picture-o are different heights at the same font size...

**Comment by tagliala** [comment] 2017-02-09 12:48
@charlesr1971 icons have the same height but some of them are wrongly centered (#1624) and others does not play well each other. FA 5.0.0 is supposed to fix all this issues.

**Comment by charlesr1971** [comment] 2017-02-09 14:14
Geremia. Thanks for the reply but I cannot see how all the icons are the same height. Some icons are rectangular in the x-axis, some are square & some are rectangular in the y-axis.  It will be interesting to see how FA5.0 handles this issue. A class like fa-fh would be great for lining up icons that have small height differences, like fa-list-alt & fa-picture-o. In FA4.3, these 2 icons have a height differential of about 2px at font-size:38px. And you are correct about the centering issue. This creates a further problem.

**Comment by tagliala** [comment] 2017-02-09 14:29
> Geremia. Thanks for the reply but I cannot see how all the icons are the same height

`fa-fw` sets a fixed width of 20/14 em and centers the icon in that space (and yes, odd-widthed icons have antialiasing issues) because icons have different width.

The vertical space used by icons, instead, is the same. It does not mean that all icons have the same height but that they already fill the same space.

> It will be interesting to see how FA5.0 handles this issue

Thanks to all FA backers, all icons will be redesigned from scratch 😄 

![image](https://cloud.githubusercontent.com/assets/556268/22787239/f138d052-eedb-11e6-8821-53da24ab115e.png)

More information @ https://www.kickstarter.com/projects/232193852/font-awesome-5

**Comment by rodchenkov** [comment] 2017-02-24 10:10
I have same issue with font awesome icons
![0](https://cloud.githubusercontent.com/assets/7562752/23299430/9c6309a4-fa92-11e6-9300-9057a9640edd.png)

**Comment by charlesr1971** [comment] 2017-02-24 13:28
Geremia. What I mean by fa-fh, is that I would like this class to alter the height so that the icons line up horizontally. Visually, all the icons would align. But, thanks for the diagram. That is very useful. Essentially, the icons currently have the same bounding box height. And, it is fine to keep this, but maybe fa-fh could just make minor height adjustments when different icons are aligned horizontally.

**Comment by charlesr1971** [comment] 2017-02-24 13:33
Let me clarify. I understand that the icons currently align through their centre line, as you diagram suggests. I would like the icons to align visually along the top, middle & bottom. I think this might look neater, even though some icons would occupy more pixel space. But, maybe this is a subjective issue.

**Comment by tagliala** [comment] 2017-02-24 13:50
@rodchenkov if you think there is an issue with font awesome, provide a working example showing the issue. You can use this one as a base: https://jsfiddle.net/tagliala/s3msxtbe/

@charlesr1971 the problem is that the vertical space used by icon is already the same, so you cannot change alignment or vertical size via css. If you need minor tweaks, you should use specific css classes.

Take a look at this: https://jsfiddle.net/tagliala/s3msxtbe/13/

**Comment by charlesr1971** [comment] 2017-02-24 17:25
I am not trying to change the alignment or vertical size, I want fa-fh to change the font-size per icon, so that we get:

![fa-icon-alignment](https://cloud.githubusercontent.com/assets/827046/23313590/43a4a7e0-fab6-11e6-85d5-41e02e117154.jpg)

**Comment by tagliala** [comment] 2017-02-24 17:38
@charlesr1971 what you are asking for requires a redesign, you cannot do this with a single css class.

**Comment by charlesr1971** [comment] 2017-02-24 17:59
OK. Thanks. I wasn't sure whether this could be implemented or not. I guess it would require FA to create adjustments for every icon in relation to every other icon, which would be a bit of headache, not to mention creating file bloat. So, I can understand why this is a problem...

**Comment by tagliala** [comment] 2017-12-17 20:15
This is still an issue

https://jsfiddle.net/tagliala/tgzouajm/39/

as @charlesr1971 said, this is quite hard to implement but the new grid should help.

I think that one of fa-image or fa-list-alt is not respecting the grid, because they have the same width but different height

**Comment by Xuuu111** [comment] 2019-03-11 15:24
The issue is still there.
https://fontawesome.com/icons/ellipsis-v?style=light
This icon is extremely small compare to others.

**Comment by tagliala** [comment] 2019-03-11 16:11
@Xuuu111 I'm going to close this one, because:

- Most of the size inconsistencies have been addressed
- It is hard to track a single thread like this one
- It is hard to make each couple of icons in the set to play well one against other

Please open a new individual request. Please use https://jsfiddle.net/tagliala/1o7sevju/ as a base for a fiddle showing the issue, I did the same for my comment before, or take a look at #14734

**Closed by tagliala** 2019-03-11 16:11 UTC
Labels: enhancement

**Comment by NicolasDionB** [comment] 2019-05-29 17:20
Would it be possible to get an option on a specific icon to resize/adjust it? An option to standardize the size of all the icons in a set would be even better but still, having a way to fix it somewhere would be a must. I understand you can fix all this, per icon, in css but I think the generated font files should include all the icons at the same size. I don't understand why it is not the case already.

**Comment by tagliala** [comment] 2019-05-30 07:23
Hi @NicolasDionB

Do you mean the same horizontal size? If you do, then you can use `fa-fw` cass

Otherwise, we are trying our best to keep icons visually uniform, but it is hard with such a huge set and combination of icons

If you spotted a size inconsistency, please open a new individual request using  https://jsfiddle.net/tagliala/1o7sevju/  as a base to show the issue

**Comment by davidhellmann** [comment] 2020-04-28 21:37
Why not have the same Bounding Box for each Icon? looked into the SVGs and each Icon has another width. Would be nice the Icons are squared.

**Comment by NicolasDionB** [comment] 2020-04-29 12:04
@tagliala Better late than never (for my late answer!!), I was talking about the general size of an icon, horizontal and vertical. I understand that CSS fix exist (the use of `fa-fw` beeing one) but when you try to use the icons in other situation such as in Flutter for instance, you can't rely on CSS for that. So I was just suggesting that some per-icon tweeking would be appreciated.

The solution I found was to create a size template in Illustrator and fit in my icons, export them individually to svg and then import them in Fort Awesome. It sure works but it's harder to maintain. Having some guidance and tweeking possibilities within Fort Awesome itself would be great. Thanks!
