### ISSUE TITLE
Icon Request: fa-researchgate

### ISSUE THREAD

**Issue by picchiri** [FortAwesome/Font-Awesome#10736] opened 2017-03-03 09:58 UTC
![researchgate icon](https://cloud.githubusercontent.com/assets/11457647/23546525/30982a2e-0000-11e7-9503-2cdbd1a6c2d8.png)

Research Gate is a social network for researchers

**Comment by tagliala** [comment] 2017-03-03 10:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3634 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-03 10:02 UTC
