### ISSUE TITLE
Icon request: gameloft

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#14948] opened 2019-04-26 10:42 UTC
#### I have posted this issue earlier
![gameloft](https://cdn.worldvectorlogo.com/logos/gameloft-3.svg)
### What can it be used for?

This may be a standard game developer's icon.

This is an icon of Iconic game company i.e., Gameloft.

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by verbose8** [comment] 2019-04-29 09:40
I've also posted this request earlier but as different user. This time I request Font Awesome to accept this request. It's tag must be
```html
<i class="fab fa-gmaeloft"><i>
```

**Comment by verbose8** [comment] 2019-04-29 09:42
Please review and give a reply
My email:
` verbose8.developers@outlook.com `

**Comment by tagliala** [comment] 2019-04-29 09:46
@verbose8 I was not able to find the old request, is it still there?

If you want to know how requests work, please take a look at https://fontawesome.com/community/leaderboard/brands#faqs

**Comment by verbose8** [comment] 2019-04-29 11:00
No sir, I closed that. But please accept my request for <i class=”fab fa-gameloft”></i>



Sent from Mail for Windows 10

**Comment by tagliala** [comment] 2019-04-29 11:24
@verbose8 your request has been accepted, but please take a look at https://fontawesome.com/community/leaderboard/brands#faqs if you need information on how requests work

If you are in hurry for this icon, please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome, you will find information on how to customize font awesome

**Comment by aethior** [comment] 2022-04-11 01:23
Duplicate of #14334.

cc/ @tagliala

**Closed** 2022-04-11 15:49 UTC
Labels: brand icon
