### ISSUE TITLE
Icon request: closed van

### ISSUE THREAD

**Issue by iang0ld** [FortAwesome/Font-Awesome#14372] opened 2018-12-08 02:52 UTC
Just a mod of shuttle-van with windows filled solid so only the front window shows.

**Comment by tagliala** [comment] 2018-12-08 08:33
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a use case to clarify why there is the need of both designs?

**Comment by sensibleworld** [comment] 2024-07-11 19:11
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/19198)

**Closed by sensibleworld** 2024-07-11 19:11 UTC
Labels: new icon, waiting for feedback, transportation (category), Duplicate
