### ISSUE TITLE
Icon Request: fa-retailer / fa-merchant

### ISSUE THREAD

**Issue by afalz** [FortAwesome/Font-Awesome#10339] opened 2016-12-09 04:45 UTC
I think there should be an icon for expressing a shop/cafe/merchant.

Something like:
[http://www.amyhissom.com/ELGT/wp-content/uploads/2015/05/vendor_icon.png](http://www.amyhissom.com/ELGT/wp-content/uploads/2015/05/vendor_icon.png)

**Comment by tagliala** [comment] 2016-12-09 12:07
Duplicate of #1958 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-09 12:07 UTC
