### ISSUE TITLE
my_mail

### ISSUE THREAD

**Issue by Julia1401** [FortAwesome/Font-Awesome#8845] opened 2016-03-28 10:28 UTC
The icon of a social network of my world of https://my.mail.ru is necessary. Code: fa fa-my_mail. It can be made?
![_avatar40](https://cloud.githubusercontent.com/assets/18113503/14076261/06903140-f502-11e5-97a1-d2f57b6e05d4.jpg)
![bg_container](https://cloud.githubusercontent.com/assets/18113503/14076262/0698c0e4-f502-11e5-9ac9-1e7eaaf9a3f3.png)

**Comment by tagliala** [comment] 2016-03-28 10:40
Duplicate of #2716, please +1 that request

closing here

**Closed by tagliala** 2016-03-28 10:40 UTC
