### ISSUE TITLE
Icon request: Hatena-Blog

### ISSUE THREAD

**Issue by yaminoma** [FortAwesome/Font-Awesome#13907] opened 2018-09-07 06:17 UTC
### What can it be used for?
[Hatena Blog](http://hatenablog.com/) is Japan's largest blog service,  it would be very helpful to have this icon available in Font Awesome.

### Example image (optional)
Icon viewable on their website.

**Comment by tagliala** [comment] 2018-09-07 10:40
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2892, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-07 10:40 UTC
