### ISSUE TITLE
Icon request: icon-new

### ISSUE THREAD

**Issue by Rayka** [FortAwesome/Font-Awesome#13967] opened 2018-09-19 07:46 UTC
### What can it be used for?
Hi there, 
We are missing an icon with the general meaning of "New" or something more abstract for a new item.

### Example image

![image](https://user-images.githubusercontent.com/3439028/45738269-a471b900-bbf8-11e8-891b-8aa2cad8487a.png)

Thank you!

**Comment by tagliala** [comment] 2018-09-19 08:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2865, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-19 08:33 UTC

**Comment by Rayka** [comment] 2018-09-19 09:29
Ok, thank you! I tried to find that but couldn't find it.

**Comment by tagliala** [comment] 2018-09-19 13:28
@Rayka no problem 👍
