### ISSUE TITLE
Icon Request: fa-deafness

### ISSUE THREAD

**Issue by AndreLGava** [FortAwesome/Font-Awesome#8248] opened 2015-12-30 16:30 UTC
acessibility on the web is very important, so we need an icon like this
https://kuhne1.files.wordpress.com/2010/06/surdez.jpg

**Comment by tagliala** [comment] 2015-12-31 21:29
duplicate of #5409, please +1 that request

closing here

**Closed by tagliala** 2015-12-31 21:29 UTC
