### ISSUE TITLE
Icon request: "Misskey" and "throne" (brand icon)

### ISSUE THREAD

**Issue by sdgrf** [FortAwesome/Font-Awesome#19819] opened 2023-07-17 19:01 UTC
Please add these icons!

**Comment by tagliala** [comment] 2023-07-17 19:11
Hi!

Thanks for being part of the Font Awesome Community.

I guess that Misskey is a duplicate of #14754, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

---

As per throne, I do not know this brand. I may guess it is a duplicate of #19207, but I may be wrong

If it is not a duplicate, please fill out our [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

Closing here, but feel free to comment if I've missed something

**Closed as completed by tagliala** 2023-07-17 19:11 UTC

**Comment by sdgrf** [comment] 2023-07-17 19:19
I'm sorry for the missing confirmation, thank you so much!
