### ISSUE TITLE
Icon Request: fa-blender

### ISSUE THREAD

**Issue by sonance2** [FortAwesome/Font-Awesome#11588] opened 2017-10-04 11:39 UTC
![logo](https://user-images.githubusercontent.com/17828134/31174324-0abc094a-a903-11e7-895a-ef7c602e14e1.png)

Blender 3D icon - https://www.blender.org/

This 3D software is very popular, it would be nice to have an icon.

**Comment by tagliala** [comment] 2017-10-04 12:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8273, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-04 12:17 UTC
