### ISSUE TITLE
fa-syringe

### ISSUE THREAD

**Issue by nxtdesigns** [FortAwesome/Font-Awesome#7924] opened 2015-11-19 14:05 UTC
I need some medical icons like syringe, x-ray, tablets, capsules, thermometer

Thx

**Comment by tagliala** [comment] 2015-11-19 14:06
syringe is a duplicate of #1779 , please +1 that request

about other requests, please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

**Closed by tagliala** 2015-11-19 14:06 UTC

**Comment by nxtdesigns** [comment] 2015-11-19 14:09
thx
