### ISSUE TITLE
Tidal brand icon

### ISSUE THREAD

**Issue by ocrankb** [FortAwesome/Font-Awesome#15572] opened 2019-09-20 01:42 UTC
You guys need to add the Tidal music streaming service icon on font awesome. It would be much appreciated for this website I'm working on.

**Comment by tagliala** [comment] 2019-09-20 07:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8850, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-20 07:06 UTC
