### ISSUE TITLE
Icon Request: fa-angle-times

### ISSUE THREAD

**Issue by minhkidong** [FortAwesome/Font-Awesome#7941] opened 2015-11-20 07:50 UTC
fa-times is so weight, i like it thin as  fa-angle-right,  fa-angle-left ...etc....

**Comment by gurisko** [comment] 2015-11-20 09:45
Duplicate of #1540. Feel free to add +1 there.

**Comment by tagliala** [comment] 2015-11-20 14:49
@gurisko thanks

closing here

**Closed by tagliala** 2015-11-20 14:49 UTC
