### ISSUE TITLE
Brand request: e-toro

### ISSUE THREAD

**Issue by shazCodes532** [FortAwesome/Font-Awesome#20088] opened 2024-01-28 23:20 UTC
It would be really great to have brand logos for trading platforms such as e-toro or trading212 :) 
Thank you in advance!!

Official website
https://www.etoro.com/

Brand guidelines
No response

Icon request checklist

- [Y]  The title starts with "Brand request: ", is followed by the requested brand name
- [Y]  I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Y]  I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by aethior** [comment] 2024-01-31 17:31
Hi @shams9324,

This request is a duplicate of #14529.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed as completed** 2024-01-31 17:42 UTC
Labels: brand icon
