### ISSUE TITLE
Icon request: fa-instagram-square

### ISSUE THREAD

**Issue by ShubhamKushwah** [FortAwesome/Font-Awesome#13053] opened 2018-05-06 15:37 UTC
### What can it be used for?
Many people including me, want a common icon base for all the social links. I am able to find all the square icons for it but not Instagram.

### Example image (optional)
![instagram](https://user-images.githubusercontent.com/24874033/39674914-011fd850-5171-11e8-82b5-01e8613114cf.png)

### Icon request checklist

- [x] This is a matched pair (Ex: `facebook` / `linkedIn` / `twitter`).
- [x] `Icon request: fa-instagram-square`.
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge, this is not a duplicate.
- [x] I have included at least one example image if it could be helpful.
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺).

PS: I know it looks a little weird having those curves in that Instagram matching with the curves in dark background. But it's nice to have an option if someone wants it.

**Comment by tagliala** [comment] 2018-05-06 16:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9223 , please add a 👍  reaction to that request.

> I have searched for existing issues and to the best of my knowledge, this is not a duplicate.

No problem 👍 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-06 16:27 UTC

**Comment by tagliala** [comment] 2018-05-06 17:33
> But when will we get the icon?

Please take a look here https://github.com/FortAwesome/Font-Awesome/issues/9223#issuecomment-361659108 and here https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by janvitos** [comment] 2019-01-20 19:14
I saw this post and decided to create an SVG instagram-square icon that I imported in icomoon. Here's the link: https://file.io/worU4x

Hope this helps anyone who needs it.
