### ISSUE TITLE
Icon request: fa-artstation (ArtStation)

### ISSUE THREAD

**Issue by leonardteo** [FortAwesome/Font-Awesome#9325] opened 2016-06-03 02:16 UTC
Hi,

I was wondering if it's appropriate to request for an `fa-artstation` icon to be added, for people to add icons/links to their [ArtStation](https://www.artstation.com) accounts. ArtStation has gotten very big as a social network for professional artists and is now ranked 3500 on Alexa.

Their logo is available here: https://www.artstation.com/about/logo

Thanks!

Leo

**Comment by tagliala** [comment] 2016-06-03 11:37
Duplicate of #5354, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-03 11:37 UTC

**Comment by leonardteo** [comment] 2016-06-03 11:52
My bad sorry! Thanks
