### ISSUE TITLE
Icon Request: Diameter symbol

### ISSUE THREAD

**Issue by strictly4U** [FortAwesome/Font-Awesome#8585] opened 2016-02-16 09:11 UTC
In Unicode it is defined as U+2300 ⌀ diameter sign (HTML &#8960;).

https://en.wikipedia.org/wiki/Diameter#Diameter_symbol

**Comment by tagliala** [comment] 2016-02-16 10:04
Duplicate of #5852, please +1 that request

closing here

**Closed by tagliala** 2016-02-16 10:04 UTC
