### ISSUE TITLE
Icon request: fa-alarm-clock

### ISSUE THREAD

**Issue by kaisummers** [FortAwesome/Font-Awesome#7657] opened 2015-10-11 07:32 UTC
![fa-alarm-clock](https://cloud.githubusercontent.com/assets/6847150/10415637/2c581348-702d-11e5-80a9-85f9be1b7128.PNG)

This icon would be a useful alternative for reminders, similar usage cases would be those of the fa-bell icon.

**Comment by tagliala** [comment] 2015-10-11 16:21
duplicate of #1926 , please +1 that request

closing here

**Closed by tagliala** 2015-10-11 16:21 UTC
