### ISSUE TITLE
Icon Request: fa-path

### ISSUE THREAD

**Issue by natanelia** [FortAwesome/Font-Awesome#7246] opened 2015-08-17 06:45 UTC
Reason:
Path is a popular social media in some countries and is not currently available in font-awesome.

Use case:
A link to post moment (and share it to close friends), to promote our company product.

Visit: https://path.com

Note: Please create the Path icon without the square background.

**Comment by tagliala** [comment] 2015-08-17 08:09
Duplicate of #2703, please +1 that request

closing here

**Closed by tagliala** 2015-08-17 08:09 UTC
