### ISSUE TITLE
Icon request: fa-geek

### ISSUE THREAD

**Issue by kenshiwara** [FortAwesome/Font-Awesome#9900] opened 2016-09-10 15:56 UTC
It would be very nice to have a geek icon or a glass icon which can be represented as:
![glass_b-512](https://cloud.githubusercontent.com/assets/12446892/18411802/2df31738-77b2-11e6-96a1-3bef65aa4772.png)

**Comment by tagliala** [comment] 2016-09-10 17:28
Duplicate of #1043 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-10 17:28 UTC

**Comment by shababhsiddique** [comment] 2018-02-08 06:56
I my opinion this could be a glass icon. The geek icon should be like material face icon but with glasses instead of eyes
https://www.materialui.co/materialIcons/action/face_black_192x192.png
