### ISSUE TITLE
ICON-REQUEST-->CODECHEF AND CODEFORCES

### ISSUE THREAD

**Issue by tushar1003** [FortAwesome/Font-Awesome#18749] opened 2022-02-24 01:50 UTC

**Comment by theseus-alt** [comment] 2022-02-25 12:04
Also, Leetcode

**Comment by tagliala** [comment] 2022-02-25 12:09
Hi!

Thanks for being part of the Font Awesome Community.

Codechef is a duplicate of #14268, please add a 👍 reaction to that request.
Codeforces is a duplicate of #14584, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

@theseus-alt Leetcode is a duplicate of #15337 , please add a 👍 reaction to that request.

**Closed as completed by tagliala** 2022-02-25 12:09 UTC
