### ISSUE TITLE
Icon Request: ( fa-coin ) + ( fa-coins )

### ISSUE THREAD

**Issue by iamwillow** [FortAwesome/Font-Awesome#9609] opened 2016-07-21 02:52 UTC
Some cases in which user can use this icon:
- For unique currency apps
- For point/coin collecting sites

Design Ideas:

![screen shot 2016-07-21 at 11 42 53 am](https://cloud.githubusercontent.com/assets/3923914/17009711/70a1923c-4f38-11e6-88b0-d853cf5e5b49.png)

![coin](https://cloud.githubusercontent.com/assets/3923914/17009828/8338ec0a-4f39-11e6-903e-4e06b7ac0c58.jpg)

**Comment by iamwillow** [comment] 2016-07-21 02:58
( for now I am using fa-circle with a gold color as a temporary solution )

**Comment by tagliala** [comment] 2016-07-21 08:25
Duplicate of #1400 and #4350, please add a 👍  reaction to those requests

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-21 08:25 UTC

**Comment by fernandobonfimandrade** [comment] 2017-12-29 18:53
+1
