### ISSUE TITLE
Icon request: diaper, baby bottle

### ISSUE THREAD

**Issue by bhpatel26** [FortAwesome/Font-Awesome#18900] opened 2022-04-12 17:01 UTC
Icon request: 
1. diaper
2. baby bottle

**What can it be used for?**
For health monitoring/telemedicine apps and websites.

**Example Image (optional)**
-  https://uxwing.com/diaper-icon/
- https://uxwing.com/feeding-bottle-icon/

**Comment by tagliala** [comment] 2022-04-12 19:08
Hi!

Thanks for being part of the Font Awesome Community.

Diaper is a duplicate of #5070, please add a 👍 reaction to that request.
baby-bottle is a duplicate of #12752, please add a 👍 reaction to that request.


Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-04-12 19:08 UTC
