### ISSUE TITLE
Icon request: baby-pacifier

### ISSUE THREAD

**Issue by ajunior** [FortAwesome/Font-Awesome#10542] opened 2017-01-21 19:45 UTC
Something like it.

![image](https://cloud.githubusercontent.com/assets/398263/22177256/e47d7166-dff8-11e6-8e20-85ac395f8624.png)

**Comment by tagliala** [comment] 2017-01-21 20:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2030, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-21 20:53 UTC
