### ISSUE TITLE
Icon Request: Strava

### ISSUE THREAD

**Issue by pdohmen91** [FortAwesome/Font-Awesome#9477] opened 2016-06-25 21:24 UTC
Would be really nice to have this icon available. I`ve seen that this was requested some time ago but did not find a reason why it was closed.

**Comment by tagliala** [comment] 2016-06-25 21:26
Duplicate of #3313 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-25 21:26 UTC
