### ISSUE TITLE
Icon request: mongodb

### ISSUE THREAD

**Issue by devadathprabhu** [FortAwesome/Font-Awesome#17915] opened 2021-05-20 17:52 UTC
**What can it be used for?**
Mongodb is one of the widely used database. Font-Awesome just has database logo in generic. Supporting mongodb logo would be useful

**Example image **
![mongodb](https://user-images.githubusercontent.com/10599752/119025825-26c26480-b9c2-11eb-8c20-0650aab54947.jpeg)

**Comment by tagliala** [comment] 2021-05-20 18:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2725 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-05-20 18:34 UTC
