### ISSUE TITLE
Icon request: fa-user-couple

### ISSUE THREAD

**Issue by SimplicityGuy** [FortAwesome/Font-Awesome#5993] opened 2015-03-18 19:48 UTC
Basically a version of fa-users but with only 2 users shown. Something to resemble a couple, so perhaps 2 fa-user icons next to one another.

Such an icon can be used on sites or links reflecting relationship advice, dating, etc.

**Comment by tagliala** [comment] 2015-03-20 15:41
I'm going to consider this a duplicate of #2883 

Please +1 that request

Closing here

**Closed by tagliala** 2015-03-20 15:41 UTC
