### ISSUE TITLE
Icon request: codeigniter

### ISSUE THREAD

**Issue by jim-parry** [FortAwesome/Font-Awesome#8087] opened 2015-12-04 15:05 UTC
CodeIgniter is an open source PHP web framework.
The CodeIgniter logo is a registered trademark owned by the British Columbia Institute of Technology, and made available to developers under the MIT license for use in their projects.
A font-awesome icon would make it easier to use.
![ci-logo-big](https://cloud.githubusercontent.com/assets/3203951/11592764/587f5dc6-9a55-11e5-8b4d-d64457e0c00a.png)
![ci-logo](https://cloud.githubusercontent.com/assets/3203951/11592768/5f46bec4-9a55-11e5-925f-1179b1268b7d.png)

**Comment by tagliala** [comment] 2015-12-04 15:53
duplicate of #4316, please +1 that request

closing here

**Closed by tagliala** 2015-12-04 15:53 UTC

**Comment by InsiteFX** [comment] 2015-12-05 13:00
I have made a request for the new FontAwesome icon on their site.

**Comment by riwakawebsitedesigns** [comment] 2015-12-06 10:21
+1 

Much need icon

fa fa-codeigniter I would think better name.

**Comment by SunDi3yansyah** [comment] 2015-12-07 19:13
+1

**Comment by wh04mi** [comment] 2015-12-07 19:13
+1

**Comment by InsiteFX** [comment] 2016-06-29 02:58
Yes I think it should be fa-codeigniter to be consistent.

**Comment by tagliala** [comment] 2016-06-29 08:42
duplicate of #4316 :lock:
