### ISSUE TITLE
Icon request: fa-firefox (brand)

### ISSUE THREAD

**Issue by tojonmz** [FortAwesome/Font-Awesome#6965] opened 2015-07-16 16:56 UTC
It would be nice in addition to all the existing amazing Brand icons (Google, Google+, Chrome, Trello, Apple, etc) there was an (`fa-firefox`) font awesome icon for webdev use.
http://fortawesome.github.io/Font-Awesome/icons/#brand

I'm not sure about the exact mechanism to help make this happen but happy to provide a few start points:

Contact: Sean Martell
https://mozillians.org/en-US/u/mart3ll/
IRC: irc://moznet/fistbump

Branding Page: (firefox section below)
https://www.mozilla.org/en-US/styleguide/identity/firefox/branding/

Brand Engagement Form: (I'm happy to fill this out on your behalf if it's required)
https://bugzilla.mozilla.org/form.creative

Let me know if there's anything I can do to help :)

**Comment by tagliala** [comment] 2015-07-16 19:00
Hi,

this is a duplicate of #219 , you can only +1 that request since we are not accepting PRs containing icons

hope it helps

Closing here

**Closed by tagliala** 2015-07-16 19:00 UTC
