### ISSUE TITLE
Icon Request: Flipboard

### ISSUE THREAD

**Issue by cjbatson** [FortAwesome/Font-Awesome#11532] opened 2017-09-18 01:45 UTC
Dear Font-Awesome,

Could you please add the icon for Flipboard to Font-Awesome?

You can see the icon here (https://flipboard.com/@charlottebatson/charlotte%27s-oil-%26-gas-news-s9f59jeky) in the upper left-hand corner.

I would use it with the other social icons. I have an online publication on Flipboard and the icon would help people follow me on Flipboard. (here's my publication: https://flipboard.com/@charlottebatson/charlotte%27s-oil-%26-gas-news-s9f59jeky).

I did a search and noticed that several others have requested this icon - some of the requests have been closed while others are still pending. Is this icon underway?

Thank you very much, and have a great day,

Charlotte

**Comment by tagliala** [comment] 2017-09-18 08:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1382, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-18 08:17 UTC
