### ISSUE TITLE
Icon request: icon-store-front

### ISSUE THREAD

**Issue by naluoli** [FortAwesome/Font-Awesome#12462] opened 2018-02-26 23:37 UTC
### What can it be used for?

location, retail, small business, store front, vendor, different building type

### Example image (optional)

two examples below.

![image](https://user-images.githubusercontent.com/36716550/36702179-dc9e35c2-1b0a-11e8-8389-ac2482a52257.png)
![image](https://user-images.githubusercontent.com/36716550/36702210-f4ea2046-1b0a-11e8-8168-918c6c6174a7.png)

### Icon request checklist

- [ single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [yes ] I have included at least one example image if it could be helpful (optional)
- [yes ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-02-28 13:33
duplicate of #1958

**Closed by tagliala** 2018-02-28 13:33 UTC
