### ISSUE TITLE
Icon request: aparat

### ISSUE THREAD

**Issue by HazhirGhafoori** [FortAwesome/Font-Awesome#15621] opened 2019-09-29 20:00 UTC
**What can it be used for?**
aparat.com is a video uploading site similar YouTube in iran.

**Example image (optional)**

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-09-29 20:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5204, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-29 20:16 UTC

**Comment by HazhirGhafoori** [comment] 2019-10-04 07:42
Hi, I try but can't use fa-aparat. It's not work.

**Comment by tagliala** [comment] 2019-10-04 07:45
Hi, #5204 is a request, you should upvote that request so it has more chances of being included in a future release of Font Awesome

If you want more information on how requests work, please take a look at [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by HazhirGhafoori** [comment] 2019-10-04 08:15
How I can customise It, and add aparat icon?

**Comment by tagliala** [comment] 2019-10-04 08:17
Yes, you can!

Please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

If you are using the .svg framework, it will be easy
