### ISSUE TITLE
Icon Request: fa-gitter

### ISSUE THREAD

**Issue by RaghuAllTheTime** [FortAwesome/Font-Awesome#6985] opened 2015-07-19 12:01 UTC
I'd like to ask for a brand icon for gitter.im.
I'm planning on using it for chatting about my repos.
Here's what it needs to look like:
<img src="https://d1qb2nb5cznatu.cloudfront.net/startups/i/368944-d81438d134dc6c5567ffaab69861cb34-medium_jpg.jpg?buster=1404125976" />

**Comment by tagliala** [comment] 2015-07-23 12:44
duplicate of #6535, please +1 that request

closing here

**Closed by tagliala** 2015-07-23 12:44 UTC
