### ISSUE TITLE
Icon request: ñ (spanish letter)

### ISSUE THREAD

**Issue by djkeltxo** [FortAwesome/Font-Awesome#18831] opened 2022-03-18 10:33 UTC

**Comment by aethior** [comment] 2022-03-18 10:57
>Ñ, or ñ ([Spanish](https://en.wikipedia.org/wiki/Spanish_language): eñe, [[ˈeɲe]])), is a letter of the modern [Latin alphabet](https://en.wikipedia.org/wiki/Latin_alphabet), formed by placing a [tilde](https://en.wikipedia.org/wiki/Tilde) (also referred to as a virgulilla in Spanish) on top of an upper- or lower-case N.[[1]](https://en.wikipedia.org/wiki/%C3%91#cite_note-1) It became part of the [Spanish alphabet](https://en.wikipedia.org/wiki/Spanish_alphabet) in the eighteenth century when it was first formally defined, but it has subsequently been used in other languages, such as [Galician](https://en.wikipedia.org/wiki/Galician_alphabet), [Asturian](https://en.wikipedia.org/wiki/Asturian_alphabet), the [Aragonese](https://en.wikipedia.org/wiki/Aragonese_language) [Grafía de Uesca](https://en.wikipedia.org/wiki/Graf%C3%ADa_de_Uesca), [Basque](https://en.wikipedia.org/wiki/Basque_language), [Chavacano](https://en.wikipedia.org/wiki/Chavacano), some [Philippine languages](https://en.wikipedia.org/wiki/Languages_of_the_Philippines) (especially [Filipino](https://en.wikipedia.org/wiki/Filipino_language) and [Bisayan](https://en.wikipedia.org/wiki/Bisayan_languages)), [Chamorro](https://en.wikipedia.org/wiki/Chamorro_language), [Guarani](https://en.wikipedia.org/wiki/Guarani_language), [Quechua](https://en.wikipedia.org/wiki/Quechua_alphabet), [Mapudungun](https://en.wikipedia.org/wiki/Mapudungun_alphabet), [Mandinka](https://en.wikipedia.org/wiki/Mandinka_language), and [Tetum](https://en.wikipedia.org/wiki/Tetum_alphabet) alphabets, as well as in Latin transliteration of [Tocharian](https://en.wikipedia.org/wiki/Tocharian_languages) and many [Indian languages](https://en.wikipedia.org/wiki/Languages_of_India), where it represents [[ɲ](https://en.wikipedia.org/wiki/Voiced_palatal_nasal)] or [nʲ]. It represents [[ŋ](https://en.wikipedia.org/wiki/Voiced_velar_nasal)] in [Crimean Tatar](https://en.wikipedia.org/wiki/Crimean_Tatar_language), [Kazakh](https://en.wikipedia.org/wiki/Kazakh_language), [ALA-LC romanization for Turkic languages](https://en.wikipedia.org/wiki/ALA-LC_romanization), the [Common Turkic Alphabet](https://en.wikipedia.org/wiki/Common_Turkic_Alphabet), [Nauruan](https://en.wikipedia.org/wiki/Nauruan_language) and romanized [Quenya](https://en.wikipedia.org/wiki/Quenya). In [Breton](https://en.wikipedia.org/wiki/Breton_language) and in [Rohingya](https://en.wikipedia.org/wiki/Rohingya_language), it denotes [nasalization](https://en.wikipedia.org/wiki/Nasalization) of the preceding vowel. Many [Portuguese](https://en.wikipedia.org/wiki/Portuguese_language) speakers use this letter in informal internet language to represent the word não (no).
**More info:** https://en.wikipedia.org/wiki/%C3%91

@tagliala `alphabet (category)` label for this request?

**Comment by tagliala** [comment] 2022-03-18 17:31
Hi,

I think this request is legit and omitting letters is something that I would avoid, but having individual requests for a single letter outside the latin alphabet could easily end up in hundred of separate requests, so I'm going to ask @sensibleworld some thoughts. 

Should we allow them in groups of letters, like Accented `a`s, Accented `e`s? In groups of "language-specific letters"?

As a reference, we have a request for the greek alphabet at #2828, open and **temporarily** labeled as wontfix back in 2016 (I would remove that label now)

**Comment by aethior** [comment] 2022-03-21 01:49
Duplicate of #16958.

**Comment by sensibleworld** [comment] 2024-07-11 15:14
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed as not planned by sensibleworld** 2024-07-11 15:14 UTC
Labels: new icon, waiting for feedback, Declined
