### ISSUE TITLE
Icon request: fa-waffle and fa-waffle-square

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#8466] opened 2016-01-31 08:50 UTC
Can you please include [Waffle](https://waffle.io/)'s logo? Please also make a square one. I plan on using it in a website for a project which uses GitHub for source code hosting and Waffle for project management...

**Comment by leosa83** [comment] 2016-02-11 22:27
+1

**Comment by PeterShaggyNoble** [comment] 2017-12-07 09:32
Duplicate of #4319.

**Comment by aethior** [comment] 2022-04-10 04:10
> Duplicate of #4319.

You're right. In all case the project seems discontinued.

cc/ @tagliala

**Closed** 2022-04-10 08:33 UTC
Labels: brand icon
