### ISSUE TITLE
Icon request: icon-swim

### ISSUE THREAD

**Issue by sidtechno** [FortAwesome/Font-Awesome#12891] opened 2018-04-18 13:48 UTC
Icon for swimming
Good for Triathlon site, swimming club

**Comment by tagliala** [comment] 2018-04-18 13:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5771 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-18 13:50 UTC
