### ISSUE TITLE
Icon request: no smoking, no pets, 2 beds, Large Bed

### ISSUE THREAD

**Issue by hotelriovista** [FortAwesome/Font-Awesome#6396] opened 2015-05-06 03:48 UTC
We are re-designing our hotel's website, and would like to include more icons on the amenities pages. 

I would like to request 4 icons:

No-smoking (entypo-block with a cigarette)
No Pets (entypo-block with a dog)
2 Beds- (fa-bed icon, but with 2 beds- to represent a room with 2 beds in it)
Large Bed (fa-bed icon, but with a larger bed- to represent King Sized Mattress)

If these are requests you can fulfill I would be very happy, please let me know.

Thanks so much,

-- 
Melissa Peterson, Owner | Hotel Rio Vista
285 Riverside Ave | Winthrop, WA 98862
Phone 509.996.3535
Email: melissa@hotelriovista.com
Webpage: www.hotelriovista.com

**Comment by rmagnum2002** [comment] 2015-07-17 07:53
+1 for no smoking
also one that represents pool, something like:
http://www.melondistrict.com/content/imgsxml/en/servicios/ico-piscina.png

**Comment by tagliala** [comment] 2015-07-17 09:27
Sorry, can't leave this open, it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

smoking/no smoking is a duplicate of #726 , please +1 that request

for other requests, please open new individual requests

if you need a comprehensive set of icons for hotel, please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

closing here

**Closed by tagliala** 2015-07-17 09:27 UTC
