### ISSUE TITLE
Icon request: fa-kakao-story

### ISSUE THREAD

**Issue by parksunghoons** [FortAwesome/Font-Awesome#10369] opened 2016-12-14 16:00 UTC
https://developers.kakao.com/assets/img/about/buttons/kakaostory/brand_assets/digital/story_symbol.png

**Comment by tagliala** [comment] 2016-12-14 17:07
Duplicate of #3688, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-14 17:07 UTC
