### ISSUE TITLE
WebToon Icon

### ISSUE THREAD

**Issue by MelodyDrawz** [FortAwesome/Font-Awesome#16531] opened 2020-04-26 23:02 UTC

**Comment by tagliala** [comment] 2020-04-27 08:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12423, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-04-27 08:12 UTC
