### ISSUE TITLE
Icon Request: icon-waze

### ISSUE THREAD

**Issue by PolloCR** [FortAwesome/Font-Awesome#10303] opened 2016-12-01 03:54 UTC

**Comment by tagliala** [comment] 2016-12-01 09:46
(probably a) Duplicate of #4367, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-01 09:46 UTC
