### ISSUE TITLE
Missing Brand Icons (Adblock Plus related issue)

### ISSUE THREAD

**Issue by eridal** [FortAwesome/Font-Awesome#1799] opened 2013-08-18 09:18 UTC
Hi all,
I've noted that some [brand icons](http://fontawesome.io/icons/#brand) are missing: fb, g+, linkedin, pinterest, and twitter specially.

Here is how it looks like in my browser.
![screenshot from 2013-08-18 06 15 47](https://f.cloud.github.com/assets/95427/982348/02d4792c-07e7-11e3-8549-0ce7031f9c76.png)

**Comment by jarv** [comment] 2015-01-16 18:43
Here is a gist that defines classes to workaround the ublock/adblock issue if anyone wants the full list
https://gist.github.com/jarv/ec34057d8e8138c8b921

**Comment by davegandy** [comment] 2015-02-10 15:31
I'm re-opening this for 5.0. I have some ideas for a fix.

**Comment by lepipele** [comment] 2015-03-07 07:38
@davegandy Thanks for deciding to fix this.

**Comment by gameguy43** [comment] 2015-05-19 22:50
@ThomasGreiner Thanks for the clarification.

But FWIW, I disagree slightly that ABP is completely neutral on this issue.

This blog post:
https://adblockplus.org/blog/about-that-facebook-tracking-thing
and this page:
https://adblockplus.org/en/features#socialmedia

Contain /descriptions/ of what fanboy-social will do for you. Those descriptions focus on sharing buttons that track you even when you don't engage with them. They /don't/ make it clear that e.g. social LOGIN buttons will be effected.

(yes, whole login buttons disappear: https://github.com/lipis/bootstrap-social/issues/50)

I'd suggest ABP ought to adjust its /descriptions/ of fanboy-social to be more clear. OR, if they'd rather remain neutral, to stop endorsing it at all.

As things stand, I claim that from the perspective of an average ABP user who reads one of those pages, agrees that she doesn't like being tracked by Facebook share buttons she doesn't engage with, and installs the filter...it's a BUG that icons and indeed /whole login buttons/ suddenly disappear. I know anecdotally I've had a few users who were confused and frustrated that in some browsers they couldn't log in to my website.

(I've also emailed the fanboy-social maintainer at easylist.subscription@gmail.com directly. If people agree this is a bug in fanboy-social, they might consider doing the same.)

I don't intend to point fingers here. There are probably people who /want/ to block social login buttons, and it makes sense to me for ABP, with some customization, to provide that functionality. I think we just need to tighten up the the messaging so users don't get unexpected behavior and these projects don't have to play cat and mouse :)

IMO the first step there is drawing some distinctions in what /kinds/ of social things you might want to block. My first guess at that is something like (1) only things that track you without you even clicking (2) all share buttons ('I never want to share so don't even ask me'), but not login buttons (3) anything having anything to do with social, including sharing and logging in.

**Comment by My1** [comment] 2015-09-29 08:19
I think if this will be fixed the title should be changed as well...
but the question is that this is probably the good old "cat and mouse game" as we Germans like to say since that Fanbox-whatever may update the list again if we made new classes for the buttons. but it shouldnt be this way, true, removing tracing buttons (or at least making them 2-click) is clearly okay but not removing all icons and stuff of facebook where you just wanna make a nicely illustrated link to your PB site or whatever.

**Comment by tagliala** [comment] 2015-09-29 08:29
@My1 

thanks for reporting this, title fixed.

**Comment by My1** [comment] 2015-09-29 08:32
no problem.

**Comment by haydenk** [comment] 2015-10-10 18:36
The simplest solution, if you're using font awesome sass files, you can change the `$fa-css-prefix` variable to something other than `fa`.

**Before:** `$fa-css-prefix:       fa !default;`
**After:** `$fa-css-prefix:       fu !default;`

So, now all the Font Awesome icons will be available at `.fu.fu-twitter`, `.fu.fu-facebook`, etc.

**Comment by tagliala** [comment] 2015-10-10 18:40
@haydenk best prefix ever :)

**Comment by cydrobolt** [comment] 2016-02-27 18:55
Disabling "fanboy's annoyances" fixed the issue for me.

**Comment by EmilMoe** [comment] 2016-08-09 07:57
Sorry for picking it up again, but this is still not fixed. It's a simple matter of a renaming, so could we get an alias for all the social icons?

**Comment by rinopo** [comment] 2016-08-09 08:13
@EmilMoe 
Any aliases can be systematically blocked once they are systematically provided.
I'd recommend defining your own aliases as suggested in the previous comments:

https://github.com/FortAwesome/Font-Awesome/issues/1799#issuecomment-50438859
https://github.com/FortAwesome/Font-Awesome/issues/1799#issuecomment-147115123

**Comment by EmilMoe** [comment] 2016-08-09 08:20
Perfect - Thanks, @rinopo

**Comment by rhanajoy** [comment] 2016-09-09 15:25
Hi! I'm the Community Manager for AdBlock. For the record, Adblock Plus (ABP), our friendly rival, is the company that maintains the Acceptable Ads program, not us. ([Why the names are so similar](https://help.getadblock.com/solution/articles/6000087894-what-s-the-difference-between-adblock-and-adblock-plus-abp-) is an interesting bit of Internet history trivia.)

I've written an article for our Knowledge Base that attempts to summarize the workarounds suggested here: [AdBlock blocks Font Awesome social media icons](https://help.getadblock.com/solution/articles/6000148708-adblock-blocks-font-awesome-social-media-icons).

Rhana
AdBlock Community Manager

**Comment by Akronix** [comment] 2016-09-13 13:32
Hi!
I'm experiencing this issue using [bulma](bulma.io). Is there any way to show an alternative text in case adblock blocks the icon?
For example, we could use the unicode for the icons in case adBlock is blocking the font-awesome code.

**Comment by Paulmicha** [comment] 2016-09-14 15:11
@rhanajoy How about fixing the defaults of the extension itself, instead of having everyone to fix it via settings ?

Because, arguably, things like external links to sites' facebook pages, often using these icons, do not qualify as ads. Same goes for the icons themselves (CSS or SVG) - different than typical ad techs like iframes or JS tracking.

This looks like an AdBlock issue, which could perhaps consider not including these particular lists in the first place.

**Comment by rhanajoy** [comment] 2016-09-14 19:34
@Paulmicha AdBlock currently subscribes users to four filter lists by default: EasyList, the primary list of ad-blocking filters that all ad blockers use; AdBlock Custom, which cleans up a few troublesome filters from EasyList and other filters that break specific sites, and adds blocks for ad providers EasyList doesn't care about; Acceptable Ads, which blocks intrusive, annoying ads while allowing ads that promise to be good (how faithfully some ads adhere to the AA guidelines is up for debate); and the Adblock Warning Removal list, which prevents you from seeing warnings to disable your ad blocker on some sites.

We also include some lists that are available by selection but are not enabled by default. Among them is Fanboy's Annoyances, which includes Fanboy's Social list. That's the one that's causing trouble with Font Awesome's social media icons.

Finally, users can subscribe to any list they like if they know its URL.

All of the above is true for ABP as well, with some slight differences.

So you see there really isn't any way we can prevent this on the extension side. It's a filter list issue, and we don't maintain the filter lists. I wish we _could_ help! It would make things easier for our users, which is my chief concern.

**Comment by ThomasGreiner** [comment] 2016-09-14 19:59
> This looks like an AdBlock issue, which could perhaps consider not including these particular lists in the first place.

As @rhanajoy pointed out, such lists are not included by default in AdBlock or Adblock Plus. Also, as mentioned in my previous comment, I'd suggest discussing the scope of this particular filter list with the [EasyList](https://easylist.to/) team or alternatively reporting individual issues using the issue reporter in Adblock Plus for Firefox.

What Adblock Plus does is recommend certain filter lists by providing its users the ability to easily enable popular features. So if there's a well-maintained filter list that blocks social media elements without breaking unrelated stuff, feel free to suggest it to be used for the "Remove social media buttons" feature.

**Comment by Paulmicha** [comment] 2016-09-14 20:39
> such lists are not included by default in AdBlock or Adblock Plus

Then I must have added them in the past (though I don't remember doing that, but it's possible, as I've been using this extension for years now).

So by default, this issue shouldn't happen for users who haven't touched the extension settings then.
Thanks for the feedback !

**Comment by tagliala** [comment] 2016-09-15 09:53
> > such lists are not included by default in AdBlock or Adblock Plus
>
Then I must have added them in the past (though I don't remember doing that, but it's possible, as I've been using this extension for years now).

Not a default, but IIRC it was extremely easy to enable that option: https://github.com/FortAwesome/Font-Awesome/issues/1799#issuecomment-24030031

**Comment by ThomasGreiner** [comment] 2016-09-15 11:22
> Not a default, but IIRC it was extremely easy to enable that option: #1799 (comment)

Adblock Plus exposes that option only on the page that comes up right after successful installation. Recently, we removed that section from that page though (see https://issues.adblockplus.org/ticket/4294).

The plan is, however, to reintroduce it later on as part of the extension's settings page. For that we're planning to use the following text:

> **Disable Social Media Buttons**
> 
> Adblock Plus can disable social media buttons on websites, ensuring that social networks can’t create a profile based on the websites you visit.
> 
> Buttons used to share content on social media platforms such as Facebook, Twitter, Google Plus and others are placed on almost every website that you visit. Even if you don't click them, these buttons send requests to the servers of the social network which use information to create a profile based on your browsing habits.

If you think that this text should be changed, I created an issue on our issue tracker for discussing those (see https://issues.adblockplus.org/ticket/4434).

**Comment by rhanajoy** [comment] 2016-09-15 13:51
Wow. I blush to admit that I never knew those buttons did that. Now it makes more sense to me why the Social list would block them.

**Comment by gameguy43** [comment] 2016-09-15 15:34
@ThomasGreiner replying in that ticket now

**Comment by gameguy43** [comment] 2016-09-15 15:48
@rhanajoy, they _don't_ do that, necessarily. Only the official widgets that use JS/iframes track you.

Which if you're using fontawesome, you're probably building your own buttons, which don't track people. But you're blocked anyway.

And _that's_ the whole issue here. Non-tracking buttons are being broken by a block list that sells itself as blocking tracking buttons _only_.

Worse: it's blocking _login_ buttons. Which are not tracking. And are not social sharing buttons. So they're entirely out of the scope of what the block list sells.

For a website like mine, where social login is the _only_ way to log in, this block list _fundamentally breaks the entire website_.

The current copy and @ThomasGreiner's new copy do not make it clear to users that enabling this list may disable their ability to log in to websites. Log in is not mentioned.

**Comment by rhanajoy** [comment] 2016-09-16 16:17
@gameguy43 Thanks for clarifying that. Well, we can at least revise our descriptions of the Social list to mention this. I'll do that now in our KB and will create an issue to see whether we can change the description in the extension, too.

**Comment by ryanbr** [comment] 2016-09-19 23:40
Okay, didn't relise there was another open ticket..

From: ​https://lipis.github.io/bootstrap-social/
```

  <a class="btn btn-social-icon btn-twitter">
    <span class="fa fa-twitter"></span>
  </a>

  <a class="btn btn-block btn-social btn-twitter">
    <span class="fa fa-twitter"></span> Sign in with Twitter
  </a>
```

Might be happier if Font-Awesome removed the class social suggestion's of using the

```
btn-twitter
btn-facebook
btn-[....]
btn-social-icon
```

Then we can simply remove the specific fa-[elements] from the social list.

**Comment by ryanbr** [comment] 2016-09-22 08:06
No response?

**Comment by david-w** [comment] 2016-09-26 18:31
@ryanbr   THANK YOU for removing the generic Font Awesome social icons from the Fanboy Social List!

**Comment by rhanajoy** [comment] 2016-09-28 11:34
I've updated our KB article accordingly (https://help.getadblock.com/solution/articles/6000148708-adblock-blocks-font-awesome-social-media-icons).

**Comment by waltermesser** [comment] 2016-10-26 04:25
I'm finding Fanboy's List is still affecting Firefox - after disabling that filter and refreshing the page, the icons appear. Firefox and AB are updated to latest versions. Perhaps I'm missing something?

**Comment by MrSlawa** [comment] 2016-10-28 03:51
Fri, 23 Sep 2016 M: Remove font-awesome generic filters 
https://hg.adblockplus.org/easylist/rev/3164f12b604f

Issue can be closed?

**Comment by tagliala** [comment] 2016-10-28 09:13
@MrSlawa I can confirm it is not an issue for me, let's wait some other feedback

**Comment by s1awa** [comment] 2017-04-14 07:15
@eridal https://github.com/FortAwesome/Font-Awesome/issues/1799#issuecomment-256830065

**Closed** 2017-06-28 19:15 UTC
Labels: bug

**Comment by ExpertUser** [comment] 2018-08-23 11:29
Today I got css files of stackoverflow.com blocked by adblock :(
Moreover, few other sites have similar problem of loading.
Fontawesome are being blocked too

**Comment by smqumberrizvi** [comment] 2018-09-13 07:35
I have seen instances of googlefontapi being blocked by AdGuard. As soon as AdGuard detects any third-party CSS being used on a webpage, the adblocker blocks it.
![screenshot 19](https://user-images.githubusercontent.com/12488086/45473823-af8a9c00-b755-11e8-8602-b2e2df314388.png)
![screenshot 20](https://user-images.githubusercontent.com/12488086/45473824-b0233280-b755-11e8-81b6-8f328dc59c99.png)

**Comment by GiacomoLaw** [comment] 2019-01-26 21:41
How can I stop them from being blocked? Just redefine the names?

**Comment by tagliala** [comment] 2019-03-19 18:40
> How can I stop them from being blocked? Just redefine the names?

That would work

**Comment by jessuppi** [comment] 2019-05-09 15:57
+1 that [linkedin-in icon](https://fontawesome.com/icons/linkedin-in) is currently being blocked again by Adblock (Chrome extension)

For some reason, most other social icons seem fine at this time.

Why are non-tracking icons still being blocked by Adblock? No relation to social tracking... millions of users can't be expected to install custom lists just to make icons appear properly.

**Comment by tagliala** [comment] 2019-05-09 16:27
> Why are non-tracking icons still being blocked by Adblock?

Please report the issue to the offending list, explaining that the icon itself has no impact on user's privacy.

> millions of users can't be expected to install custom lists just to make icons appear properly.

In a broader sense, if "no social" lists are supposed to block "any social network related content" and the user deliberately opted-in for this feature, blocking lists are working as intended

**Comment by Burnett01** [comment] 2020-01-16 17:19
Renaming seems to be the only option for now. At least this is what we end up doing.
We don't want to rely on AdBlock's list.

**Comment by Berok67** [comment] 2020-10-10 11:47
Social media roles are often autonomous and can be unstructured and fluid due to the ever-changing nature of technology. If you are looking for a stable job without surprises, a career in social media may not be the best choice for you. Explore all popular and niche social media channels and explore the full history of Instagram stats and analytics with https://sharemyinsights.com . Learn what other types of programs and applications can add value to your skill set (basic HTML knowledge, such as how to work with a CMS). Also familiarize yourself with the terms and language specific to the sector.

**Comment by jruiz94** [comment] 2022-09-13 22:08
> Renaming seems to be the only option for now. At least this is what we end up doing. We don't want to rely on AdBlock's list.

I'm having the same issue, how does the renaming work? Thanks in advance

**Comment by Burnett01** [comment] 2022-09-16 21:10
> > Renaming seems to be the only option for now. At least this is what we end up doing. We don't want to rely on AdBlock's list.
> 
> 
> 
> I'm having the same issue, how does the renaming work? Thanks in advance

You can rename the icon class name in the css and html
