### ISSUE TITLE
Icon request: fa-bone

### ISSUE THREAD

**Issue by leon486** [FortAwesome/Font-Awesome#11433] opened 2017-08-23 17:42 UTC
I would like to request an [icon that depicts a bone](
http://www.iconcraze.com/wp-content/uploads/2016/11/ICONCRAZE-COM-Bone-Icon-PNG.png), It will be used for an app that deals with many materials for antiques, wood, clay, stone, bone, etc. It can be used for medical apps.

**Comment by tagliala** [comment] 2017-08-23 18:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10593, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-23 18:56 UTC
