### ISSUE TITLE
Icon Request: fa-line (brand icons, new icon)

### ISSUE THREAD

**Issue by ceefour** [FortAwesome/Font-Awesome#11404] opened 2017-08-15 01:44 UTC
Example:

![image](https://user-images.githubusercontent.com/24123/29299012-f6111236-8195-11e7-869b-2d5c4b66b21a.png)

Source: https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/LINE_logo.svg/2000px-LINE_logo.svg.png

**Comment by tagliala** [comment] 2017-08-15 08:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2631 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-15 08:49 UTC
