### ISSUE TITLE
Icon Request: fa-pendrive (usb-dongle)

### ISSUE THREAD

**Issue by melanochaita** [FortAwesome/Font-Awesome#10216] opened 2016-11-13 11:31 UTC
Basic pen drive, usually rotated at 45 degree to represent the use of a portable storage device.

**Comment by aethior** [comment] 2022-03-07 15:49
Hi @melanochaita,

This icon was added in v5.11.0.
Check https://fontawesome.com/icons/usb-drive

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-07 15:56
Also a duplicate of #7532

**Closed by tagliala** 2022-03-07 15:56 UTC
Labels: new icon, web application icons
