### ISSUE TITLE
Icon request: fa-file-certified

### ISSUE THREAD

**Issue by schoutenzekerheid** [FortAwesome/Font-Awesome#8818] opened 2016-03-24 09:57 UTC
Hi All,

We need an icon for a certified file, like:
![image](https://cloud.githubusercontent.com/assets/17614935/14013840/0e249d2a-f1af-11e5-8d1c-c8de1d92804d.png)
![image](https://cloud.githubusercontent.com/assets/17614935/14013848/218637ac-f1af-11e5-829c-cfb2ea09add2.png)

**Comment by tagliala** [comment] 2016-03-24 12:00
duplicate of #7687, please +1 that request

please also search for duplicates before opening a new request

**Closed by tagliala** 2016-03-24 12:00 UTC
