### ISSUE TITLE
Icon Request: Freezer

### ISSUE THREAD

**Issue by xmuskrat** [FortAwesome/Font-Awesome#14946] opened 2019-04-25 18:35 UTC
An icon of a freezer.

<img width="155" alt="Screen Shot 2019-04-25 at 11 34 43 AM" src="https://user-images.githubusercontent.com/59917/56759594-28bb8a00-674e-11e9-9023-fbc0f34d39b5.png">

**Comment by tagliala** [comment] 2019-04-25 18:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14028, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-25 18:41 UTC
