### ISSUE TITLE
Icon request: icon-aperture

### ISSUE THREAD

**Issue by GustelDE** [FortAwesome/Font-Awesome#10804] opened 2017-03-18 10:50 UTC
Hi, missing an aperture icon for the photography/videography community.
I think this is a well know symbol.

For reference:
https://www.google.com/search?q=aperture+icon&client=firefox-b&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiB3qT08N_SAhXDuRQKHSdgBroQ_AUIBigB&biw=1920&bih=1059

**Comment by tagliala** [comment] 2017-03-18 10:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1033 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-18 10:56 UTC
