### ISSUE TITLE
Icons can't be loaded

### ISSUE THREAD

**Issue by kalinazheleva** [FortAwesome/Font-Awesome#13400] opened 2018-06-23 14:14 UTC
### Describe the problem

When I choose an icon, it loads slow and then it doesn't load the icon, it loads the www.fontawesome.com website. 

The website is today too slow. Is this a popular problem and what can I do or you're fixing something on the website? 

Thank you. 

### What version and implementation are you using?

Version: 

Browser and version: 

I use Google Chrome, last version. 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Bug report checklist

- [ x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2018-06-23 15:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13399, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-23 15:59 UTC
