### ISSUE TITLE
qzone

### ISSUE THREAD

**Issue by YiShengYouNi** [FortAwesome/Font-Awesome#9161] opened 2016-05-10 06:54 UTC
font awesome4.4 not has fa-qzone

**Comment by tagliala** [comment] 2016-05-10 16:53
Duplicate of #3993, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-10 16:53 UTC
