### ISSUE TITLE
Icon Request: fa-handshake

### ISSUE THREAD

**Issue by borayilmaz** [FortAwesome/Font-Awesome#5802] opened 2015-02-27 10:49 UTC
Dear Friends, 

As a proposal I attach the handshake icon, I am working for Pharma Industry and business wants to use this icon for interactions with customers.

Best,

Bora

![handshake](https://cloud.githubusercontent.com/assets/11228002/6411199/8aba976c-be76-11e4-9a49-9158ea2bfe23.png)

**Comment by tagliala** [comment] 2015-02-27 16:46
duplicate of #878 , please +1 that request

closing here

**Closed by tagliala** 2015-02-27 16:46 UTC

**Comment by mzweh** [comment] 2016-04-26 10:01
+1

**Comment by pyaehein** [comment] 2016-08-22 08:37
+1
