### ISSUE TITLE
Icon Request: fa-store

### ISSUE THREAD

**Issue by Jay-Arr** [FortAwesome/Font-Awesome#10941] opened 2017-04-13 16:28 UTC
I didn't see any kind of icon that looks like a small store.  One that has a striped window awning would be nice.  I've seen them before for other icon collections.  Surprised this one doesn't have one.

**Comment by tagliala** [comment] 2017-04-13 16:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1958 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-13 16:38 UTC
