### ISSUE TITLE
Icon Request: icon-brain

### ISSUE THREAD

**Issue by bekatama** [FortAwesome/Font-Awesome#7263] opened 2015-08-20 03:12 UTC
I need an icon that related with psychology

**Comment by TheChen5** [comment] 2015-08-20 05:16
Dupe of #2075 
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-20 07:02
thanks.

closing here

**Closed by tagliala** 2015-08-20 07:02 UTC

**Comment by bekatama** [comment] 2015-08-24 17:08
Thanks, I have Voted
