### ISSUE TITLE
FA icons encrypted wrong on initial page load, sometimes on some machines

### ISSUE THREAD

**Issue by DanOrdant** [FortAwesome/Font-Awesome#20213] opened 2024-05-06 16:59 UTC
As you can see in the images, I am getting such bug reports from co-workers and users.
The issue is fixed if they refresh the page.
I have added woff and woff2 to the amplify redirects as per some solutions say, therefor the errors in the console are not there anymore but the issue persists.

Seems to be happaning only in aws amplify for now.
Anyone has some clue what can be causing this ?

![image](https://github.com/FortAwesome/Font-Awesome/assets/116738124/1269f11a-5424-47e0-9546-b3f97509914c)
![image](https://github.com/FortAwesome/Font-Awesome/assets/116738124/ec150921-e4cc-4cf6-8528-cb9e07bb4ce1)

**Comment by tagliala** [comment] 2024-05-06 17:16
Hi!

Thanks for being part of the Font Awesome Community.

I guess this is being caused by #17644 (self-host + scss)

#17644 is a pretty long thread with several workarounds, even at nginx or webpack level

Hope it helps

Closing here, but feel free to comment

**Closed as completed by tagliala** 2024-05-06 17:16 UTC
