### ISSUE TITLE
Icon Request: photovoltaic

### ISSUE THREAD

**Issue by SteffenMangold** [FortAwesome/Font-Awesome#12905] opened 2018-04-19 09:50 UTC
### What can it be used for?

Visualize a photovoltaic plant in a web portal.

### Example image

icon set *-freefield
<img src="https://user-images.githubusercontent.com/20702171/38988485-9c4efb18-43d3-11e8-9741-a69206f73ede.png" width="64">

icon set *-residential
<img src="https://user-images.githubusercontent.com/20702171/38988460-852d79a0-43d3-11e8-88b6-79485cf2a27f.png" width="64">

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by SteffenMangold** [comment] 2018-04-19 11:54
Please close, I have created a pro repository request.

**Comment by tagliala** [comment] 2018-04-19 12:09
Also, this is a duplicate of #3326

**Closed by tagliala** 2018-04-19 12:09 UTC

**Comment by SteffenMangold** [comment] 2018-04-19 12:19
Sorry but a single soalr-panel is not the same liek a free fiel or a residential photovoltaic system.
Its like house != city
