### ISSUE TITLE
Icon Request: fa-4x4

### ISSUE THREAD

**Issue by Eldry** [FortAwesome/Font-Awesome#10721] opened 2017-02-28 20:45 UTC
All terrain car, other SUV, adventure car.
Use for a specialist car and mechanic repair.
See on Freepik :
![Uploading 4x4.png…]()

**Comment by tagliala** [comment] 2017-02-28 23:44
Could you please fix the example?

**Comment by Eldry** [comment] 2017-03-01 00:18
![4x4](https://cloud.githubusercontent.com/assets/26096851/23440564/f97aa8a0-fdf2-11e6-853b-511157a30850.jpg)

**Comment by tagliala** [comment] 2017-03-01 11:51
This could be a duplicate of #6509 or #3642, please +1 the proper request

closing here

**Closed by tagliala** 2017-03-01 11:51 UTC
Labels: waiting for feedback

**Comment by Eldry** [comment] 2017-03-01 15:15
Thank you. Have a nice day

**Comment by Eldry** [comment] 2017-03-01 15:50
I'm sorry, but it's a emoji and not an icon for a web site. I search a font awesome icon to place it with the <i> tag.
I speak French and my English is perhaps not very comprehensible, excuse me for it.

**Comment by tagliala** [comment] 2017-03-01 17:14
Hi, I mean that this is a duplicate request. If you want to request an SUV please add a 👍 reaction to  #6509. You may be also interested in 👍  #3642.

You could also post there your example.

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
