### ISSUE TITLE
Icon Request: fa-authy

### ISSUE THREAD

**Issue by aosgo** [FortAwesome/Font-Awesome#6921] opened 2015-07-10 11:45 UTC
Please can you add an icon for Authy - It's a 2FA Provider
![authy_symbol](https://cloud.githubusercontent.com/assets/9867956/8617998/7d08299c-2701-11e5-8958-fe5d1cd0db48.png)

https://www.authy.com

**Comment by tagliala** [comment] 2015-07-16 12:17
duplicate of #1907, please +1 that request

closing here

**Closed by tagliala** 2015-07-16 12:17 UTC
