### ISSUE TITLE
Icon Request: fa-user-search

### ISSUE THREAD

**Issue by micdech** [FortAwesome/Font-Awesome#7005] opened 2015-07-22 08:47 UTC
Can be useful to have a new icon relate to user with a small search icon into.

Useful to inficate a button or input to search user in your site/app

**Comment by tuxy** [comment] 2015-07-22 23:23
+1 User Search Icon:

Male User Search Outline:
![Male User Search](http://i.imgur.com/zj3rGSG.png)
Source: http://www.iconarchive.com/show/silky-line-user-icons-by-custom-icon-design/user-man-search-icon.html

Female User Search Outline:
![Female User Search](http://i.imgur.com/vPaJVNl.png)
Source: http://www.iconarchive.com/show/silky-line-user-icons-by-custom-icon-design/user-woman-search-icon.html

**Comment by micdech** [comment] 2015-07-22 23:39
Many thanks for your plus tuxy. Unfrotunately, your icon advice are not following with the graphic of other icons fa. 

We need to wait for other suggest... :D

**Comment by tagliala** [comment] 2015-07-23 10:33
duplicate of #6760 , please +1 that request

#1181 provides a solution for this

**Closed by tagliala** 2015-07-23 10:33 UTC

**Comment by tuxy** [comment] 2015-07-24 03:56
@ tagliala, done. Thank You!
