### ISSUE TITLE
Icon Request: fa-rial

### ISSUE THREAD

**Issue by EhsanKarimiP** [FortAwesome/Font-Awesome#5541] opened 2015-01-31 10:26 UTC
it would be great to have a Rial Currency icon...
I wonder why it isn't there already because all other currency types has an icon in font-awesome...
thanks.

**Comment by tagliala** [comment] 2015-01-31 11:39
Duplicate of #4423, please +1 that request

closing here

**Closed by tagliala** 2015-01-31 11:39 UTC
