### ISSUE TITLE
Icon Request: fa-services

### ISSUE THREAD

**Issue by kirankumaras1** [FortAwesome/Font-Awesome#6331] opened 2015-04-27 10:03 UTC
Hi I am looking for a new icon, It would be of great help.

Thanks :)
![services](https://cloud.githubusercontent.com/assets/12134644/7345412/f31fe86c-ecf1-11e4-82e2-b5f9db32b0fe.png)

**Comment by kirankumaras1** [comment] 2015-04-27 10:04
![services](https://cloud.githubusercontent.com/assets/12134644/7345502/d230abf4-ecf2-11e4-9d58-884dc96ff7f3.png)

**Comment by tagliala** [comment] 2015-04-30 23:11
duplicate of #736 , please +1 that request

closing here

**Closed by tagliala** 2015-04-30 23:11 UTC
