### ISSUE TITLE
Icon request: icon-playstation

### ISSUE THREAD

**Issue by vsential** [FortAwesome/Font-Awesome#10562] opened 2017-01-24 18:40 UTC
Use case is for addition into a few Jekyll themes.

![playstation-icon](https://cloud.githubusercontent.com/assets/4664215/22261384/5442ba66-e232-11e6-8712-159ed2534284.png)

**Comment by tagliala** [comment] 2017-01-24 19:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1006 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-24 19:35 UTC
