### ISSUE TITLE
Icon request: Kotlin Language

### ISSUE THREAD

**Issue by AdityaSelvakumar** [FortAwesome/Font-Awesome#17425] opened 2020-11-21 12:57 UTC
**What can it be used for?**
It is used for developers who are making web-tutorial website

**Example image (optional)**
![kt](https://user-images.githubusercontent.com/74132293/99877850-13a72580-2c27-11eb-8fb3-d1ebc7e6842d.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by AdityaSelvakumar** [comment] 2020-11-21 12:58
Please Make This Icon For Web-Developers

**Comment by tagliala** [comment] 2020-11-21 14:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13450, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-11-21 14:04 UTC
