### ISSUE TITLE
social media icons not shown ..only squares.

### ISSUE THREAD

**Issue by 12IRUNI** [FortAwesome/Font-Awesome#15208] opened 2019-06-29 17:29 UTC
```
<!doctype html>
<html>
<head>
<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">	
	<link href="https://fonts.googleapis.com/css?family=Source+Serif+Pro&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="css/fontawesome.min.css">
	<link rel = "stylesheet" href="css/bootstrap.min.css">
	<link rel = "stylesheet" href="css/style.css">
	
<title>SWEET TOOTH</title>
</head>
<body>
	<div id="bottom_area" ></div>
		<div class="container"></div>
          <div class ="row"></div>
	        <div class = "col-md-3"></div>
				<div class = "social area"></div>
						<ul>
							<li><a href=""><i class="fab fa-facebook-square"></i></a></li>
							<li><a href=""><i class="fab fa-twitter"></i></a></li>
							<li><a href=""><i class="fab fa-instagram"></i></a></li>
									
							</ul>	  
	
	


	
	
	
	
	
	
	
	
	
	
	
<script src="js/jquery-3.4.1.min.js" type="text/javascript"></script>
<script src="js/bootstrap.min.js" type ="text/javascript"></script>
<script src="js/fontawesome.min.js" type="text/javascript"></script>
									   
									   
									   
									   </body>
</html>
```
help

**Comment by tagliala** [comment] 2019-06-29 19:58
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot confirm.
SVG: https://jsfiddle.net/tagliala/7hod8jy3/12/
CSS: https://jsfiddle.net/tagliala/c9rxutqe/23/
Kit (CSS): https://jsfiddle.net/tagliala/n4dhqjcv/9/
Kit (SVG): https://jsfiddle.net/tagliala/0r5L9dfz/3/

Also:
- you are serving font awesome from your application server, and you didn't provide details about your configuration (version, etc.). You are using markup for version 5, but I'm not sure that the css is actually
- your application seems to be using both css and js version: pick just one of them, according to your needs
- please make sure that there isn't a third-party ad-blocker which blocks social icons on your website 
Ref: #1799 

If you still think there issues with font awesome, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case

Meanwhile, closing here

**Closed by tagliala** 2019-06-29 19:58 UTC
