### ISSUE TITLE
Icon Request: fa-swipe-gesture

### ISSUE THREAD

**Issue by lluisandreu** [FortAwesome/Font-Awesome#10792] opened 2017-03-15 15:09 UTC
Hi there!

Thanks for your work. It will be great to have some icons for mobile gestures like swipe, touch, slice, etc. 

Thanks.

**Comment by tagliala** [comment] 2017-03-15 15:31
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

swipe: duplicate of #393, please add a 👍  reaction to that request

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Closed by tagliala** 2017-03-15 15:31 UTC
