### ISSUE TITLE
fa-plus is not centered

### ISSUE THREAD

**Issue by smaspe** [FortAwesome/Font-Awesome#7351] opened 2015-08-31 21:08 UTC
`fa-plus` contains more padding on the bottom than on the top, as evidenced by this screenshot: 
<img width="285" alt="screen shot 2015-08-31 at 5 07 09 pm" src="https://cloud.githubusercontent.com/assets/4571256/9590464/c4ac6612-5002-11e5-8f20-5e5e2dd1ea80.png">

I use that icon in a disc, the icon appears offset toward the top.

**Comment by tagliala** [comment] 2015-09-13 19:01
Could you please create a fiddle showing the issue? You can use this one as a base: http://jsfiddle.net/tagliala/4ya23yjL/

btw screensot is broken

**Comment by smaspe** [comment] 2015-09-14 13:45
@tagliala I am not quite sure how to create a fiddle as the issue appears in a native android app. I don't see that the screenshot is broken, are you sure?

**Comment by tagliala** [comment] 2015-09-14 15:23
@smaspe now it works, it probably was a temporary issue

**Comment by tagliala** [comment] 2015-09-14 15:28
@smaspe I can confirm. This happens because the plus sign has an odd height (11 units), so it can't be centered in a 14x14 grid without losing pixel perfection. I'm going to assign this to Dave but you should know that icons in font awesome have different height and width by design

**Comment by smaspe** [comment] 2015-09-14 15:33
@tagliala ok, thanks for the explanation. I managed to find a metric in the Font object that allows the icon to be centered. Requesting the bounds from the Paint object apparently can give you the actual size of the drawn area, while measures such as descent and ascent are more generic and would only work for centered icons.

**Comment by tagliala** [comment] 2017-12-17 19:35
I think this is not an issue anymore

https://jsfiddle.net/tagliala/tgzouajm/34/

![image](https://user-images.githubusercontent.com/556268/34083045-cb7e232a-e369-11e7-9962-50d7db644488.png)

**Closed by tagliala** 2017-12-17 19:35 UTC
Labels: enhancement, web application icons
