### ISSUE TITLE
Icon Request: fa-ideal

### ISSUE THREAD

**Issue by Scarmaster** [FortAwesome/Font-Awesome#9859] opened 2016-09-05 10:22 UTC
iDeal is a widely used payment method in the Netherlands, and therefore pretty popular. Big sites use it already. I would love to see this icon in the font!

**Comment by tagliala** [comment] 2016-09-05 10:56
Duplicate of #4330, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-05 10:56 UTC
