### ISSUE TITLE
Icon Request: fa-hike

### ISSUE THREAD

**Issue by vankowski** [FortAwesome/Font-Awesome#10882] opened 2017-04-03 18:53 UTC
just looking for your run-of-the-mill hiking icon
like this
![image](https://cloud.githubusercontent.com/assets/26880704/24625383/e2280f2c-187c-11e7-9561-6353c357fa5b.png)
or this
![image](https://cloud.githubusercontent.com/assets/26880704/24625426/fccb78aa-187c-11e7-8fbc-2ed4a2410fd3.png)

and I will add separately, but most outdoor-type icons are lacking in FA.  things that would be great:
tent
lean-to
a fish or hook (fish)
a rifle or deer head (hunt)
something to do with paddling 

thanks!

**Comment by tagliala** [comment] 2017-04-03 19:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2178 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-03 19:01 UTC
