### ISSUE TITLE
Icon request: indeed

### ISSUE THREAD

**Issue by ethandede** [FortAwesome/Font-Awesome#15737] opened 2019-10-25 21:12 UTC
What can it be used for?
For businesses, to link to import of profile data via API for talent management platforms et al. For the individual to link to their indeed online profile as an alternative to a stand-alone resume file.

![icon_indeed](https://user-images.githubusercontent.com/23087690/67604687-19cf8780-f731-11e9-9217-9e8fccac3b69.jpg)

**Comment by tagliala** [comment] 2019-10-25 21:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7261, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-10-25 21:17 UTC
