### ISSUE TITLE
Icon request: icon-name - Table

### ISSUE THREAD

**Issue by katebroooks** [FortAwesome/Font-Awesome#18865] opened 2022-03-29 08:40 UTC
There's currently a bench icon in Font Awesome but I can't seem to find an icon that would resemble a cafe table that looks like this:

<img width="481" alt="Screenshot 2022-03-29 at 09 39 42" src="https://user-images.githubusercontent.com/26815948/160570436-9b34c940-b603-4a64-86e3-f840e81967eb.png">

**Comment by tagliala** [comment] 2022-03-29 16:14
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #4149, please add a 👍 reaction to that request.

It is also related to #3519

Closing here

**Closed as completed by tagliala** 2022-03-29 16:14 UTC
