### ISSUE TITLE
Icon Request: fa-pill

### ISSUE THREAD

**Issue by chmoder** [FortAwesome/Font-Awesome#8388] opened 2016-01-21 21:22 UTC
Prescription Drug Lookup Button

![image](https://cloud.githubusercontent.com/assets/82629/12495006/d801c6d8-c052-11e5-8a92-bffa916059c8.png)

**Comment by tagliala** [comment] 2016-01-22 09:30
duplicate of #1778, please +1 that request

closing here

**Closed by tagliala** 2016-01-22 09:30 UTC
