### ISSUE TITLE
Icon request: icon-coin

### ISSUE THREAD

**Issue by dekonkwehonwe** [FortAwesome/Font-Awesome#12334] opened 2018-02-12 14:25 UTC
![image](https://user-images.githubusercontent.com/31400131/36101098-07f66cc6-1011-11e8-87dd-d0f9370f8a47.png)
![image](https://user-images.githubusercontent.com/31400131/36101132-1c42ca80-1011-11e8-809f-b8870081b9f2.png)
![image](https://user-images.githubusercontent.com/31400131/36101146-26192e96-1011-11e8-9074-088ea9d05436.png)

**Comment by tagliala** [comment] 2018-02-12 19:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4350 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-12 19:49 UTC
