### ISSUE TITLE
Icon Request: fa-paint-brush

### ISSUE THREAD

**Issue by Cyntique** [FortAwesome/Font-Awesome#10523] opened 2017-01-16 03:53 UTC

**Comment by tagliala** [comment] 2017-01-16 13:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1551 or #7327, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-16 13:05 UTC
