### ISSUE TITLE
Icon request: whisk

### ISSUE THREAD

**Issue by macwinnie** [FortAwesome/Font-Awesome#12768] opened 2018-04-03 21:08 UTC
### What can it be used for?

I'm totally missing kitchen utensils (except fork, knife and spoon in  `utensil*` Icons) – especially a whisk would be a good object to start with =)
Thank you!

### Icon request checklist

- [ ok ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ok ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ok ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ no ] I have included at least one example image if it could be helpful (optional)
- [ ok ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-06 14:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9302, please add a 👍  reaction to that request.

#9302 was previously closed by mistake

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 14:50 UTC
