### ISSUE TITLE
Icon Request: Music Off / Sound Off (with slash) / Sound Off (with X)

### ISSUE THREAD

**Issue by Stexe** [FortAwesome/Font-Awesome#5817] opened 2015-02-28 18:05 UTC
Looking for two icons that match the ones already in the set for Music and Sound. But specifically versions of those with either a slash going through them (to indicate off) or a circle and slash ("no" symbol). Also, a "sound off" icon with an "X" coming out instead of waves that matches the same size would be great too.

**Comment by tagliala** [comment] 2015-03-09 15:21
duplicate of #288, please +1 that request

closing here

**Closed by tagliala** 2015-03-09 15:21 UTC

**Comment by Stexe** [comment] 2015-03-09 17:03
Only one of the requests is a duplicate of #288 Shouldn't the others still be fine?
