### ISSUE TITLE
Icon request: fa-ubuntu

### ISSUE THREAD

**Issue by Kippinn** [FortAwesome/Font-Awesome#13992] opened 2018-09-23 20:25 UTC
The Ubuntu logo. Ubuntu is a well-known Debian based linux distribution.

![telecharge 1](https://user-images.githubusercontent.com/11349337/45932637-64576100-bf7f-11e8-997d-26dcae3a87aa.png)

And can have an alternate:
![telecharge 2](https://user-images.githubusercontent.com/11349337/45932648-8b159780-bf7f-11e8-878b-3c7fa119a843.png)

**Comment by wolfy1339** [comment] 2018-09-23 20:49
I think this was already requested

**Comment by tagliala** [comment] 2018-09-23 20:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #980 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-23 20:51 UTC
