### ISSUE TITLE
Icon Request: fa-library

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#10002] opened 2016-09-29 18:23 UTC
Library for depicting a library, books with authority, knowledge of a topic for use within a healthcare data app
![library](https://cloud.githubusercontent.com/assets/539719/18966705/43cddb68-8650-11e6-9ecd-b93833bddaff.png)

**Comment by tagliala** [comment] 2016-09-30 09:01
Duplicate of #5098, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 09:01 UTC
