### ISSUE TITLE
Icon Request: fa-orcid

### ISSUE THREAD

**Issue by rjagad** [FortAwesome/Font-Awesome#10124] opened 2016-10-27 02:21 UTC
Hi,
ORCID is an organisation that provides an identifier for individuals to use with their name as they engage in research, scholarship, and innovation activities (https://orcid.org/about/what-is-orcid/mission). They are now very widely used within the research community. They have a logo, which I would like to include in my website as as Font-Awesome icon. 
16x16: 
![orcid_16x16](https://cloud.githubusercontent.com/assets/23089739/19752328/314a074c-9c48-11e6-8e0d-a64f346c595f.png)
32x32:
![orcid](https://cloud.githubusercontent.com/assets/23089739/19752306/0cf86212-9c48-11e6-9454-d7391276bb8a.png)
Thanks for your help!
Regards,
Ravi

**Comment by tagliala** [comment] 2016-10-27 07:46
Duplicate of #4401, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-27 07:46 UTC

**Comment by rjagad** [comment] 2016-10-28 03:45
Thanks for your email…I did search for “orcid”, but didn’t find it. 

Regards,

Ravi
