### ISSUE TITLE
Icon request: icon-shower / icon-toilet

### ISSUE THREAD

**Issue by mactedder** [FortAwesome/Font-Awesome#7209] opened 2015-08-12 13:47 UTC

**Comment by TheChen5** [comment] 2015-08-12 23:00
Shower dupe of #708 
+1 that
Remember to :mag:!
*Maybe have at least some example next time.*

**Comment by tagliala** [comment] 2015-08-15 09:28
@TheChen5 thanks

closing here

**Closed by tagliala** 2015-08-15 09:28 UTC
