### ISSUE TITLE
Icon Request：zhihu（知乎）

### ISSUE THREAD

**Issue by taylortaurus** [FortAwesome/Font-Awesome#12781] opened 2018-04-05 11:43 UTC

**Comment by tagliala** [comment] 2018-04-06 08:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4439, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 08:05 UTC

**Comment by taylortaurus** [comment] 2018-04-07 11:08
thx
