### ISSUE TITLE
icon missing

### ISSUE THREAD

**Issue by hashir429** [FortAwesome/Font-Awesome#17597] opened 2021-01-31 11:24 UTC
I'm here for the feedback that I searching for a friend-request icon on font awesome but I did find

**Comment by tagliala** [comment] 2021-01-31 12:02
Hi!

Thanks for being part of the Font Awesome Community.

This request may be a duplicate of #15369, please add a 👍 reaction to that request if this is the case.

Also, we have some icons that may fit the use case
- https://fontawesome.com/icons/user-friends?style=solid
- https://fontawesome.com/icons/user-plus?style=solid

If none of the above fits your use case, feel free to fill our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md). Please provide a better title and an example of the icon you are looking for

Closing here

**Closed by tagliala** 2021-01-31 12:02 UTC
