### ISSUE TITLE
Icon request: Auto-Rikshaw

### ISSUE THREAD

**Issue by Baboon12** [FortAwesome/Font-Awesome#18252] opened 2021-09-06 10:01 UTC
**What can it be used for?**
This icon can be used in travel/adventure blogs or websites and in car pooling or booking web apps.

**Example image (optional)**
https://www.google.com/search?q=auto+icon&tbm=isch&sxsrf=AOaemvI29POJbRHXR6xCZt9_EUz71sMKlA:1630922407330&source=lnms&sa=X&ved=2ahUKEwjHzPq1i-ryAhXWMd4KHb5dCS4Q_AUoAXoECAcQAw&biw=1280&bih=605&dpr=1.5#imgrc=v_qX-lGn_ySHgM

**Icon request checklist**
- [ Single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [Yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ Yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Yes ] I have included at least one example image if it could be helpful (optional)
- [ Yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-09-06 10:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14928, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here, but feel free to comment if it is not a duplicate

**Closed by tagliala** 2021-09-06 10:30 UTC
