### ISSUE TITLE
Icon Request: fa-meat

### ISSUE THREAD

**Issue by direcactx1** [FortAwesome/Font-Awesome#9598] opened 2016-07-20 01:00 UTC
Good evening!
I need a icon to supermarket app!
![plainicon com-39727-256px](https://cloud.githubusercontent.com/assets/20547929/16971663/11e4c526-4dfc-11e6-9665-6158de0a2d3d.png)

Thanks for attention!
Best regards,
Rafael Medeiros

**Comment by aethior** [comment] 2016-07-20 03:57
Duplicate of #6510. Please :+1: that.

**Closed** 2016-07-20 08:53 UTC
