### ISSUE TITLE
Parachute icon - to represent when a product is drop shipped to an address?

### ISSUE THREAD

**Issue by iang0ld** [FortAwesome/Font-Awesome#12633] opened 2018-03-17 06:03 UTC

**Comment by tagliala** [comment] 2018-03-17 07:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9606, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-17 07:53 UTC
