### ISSUE TITLE
fa-birth, fa-death

### ISSUE THREAD

**Issue by jbnv** [FortAwesome/Font-Awesome#8480] opened 2016-02-02 18:49 UTC
I have a current application for icons representing birth and death. I searched the issues for both "death" and "birth." "Death" returns #918, which is specifically for skull and crossbones. "Birth" returned just one issue, #5968 for zodiac signs. Neither of these really work for my application (a list of characters for a creative project). 

I'm not really sure what icons denoting birth and death would look like. Maybe a baby (#691) and a scythe or a gravestone (see #1149, which was rejected for #918)? I would much prefer a gravestone or a scythe over the skull and crossbones. (So this ticket is _not_ a duplicate of #918. Maybe #1149 but not not #918.)

**Comment by tagliala** [comment] 2016-02-02 23:10
In my country, Birth and Death are respectively represented by `•` and `†`, both in the standard unicode set

cross is a duplicate of #1611 

Sorry but I'm going to close this request, if you need a baby to represent birth, please +1 #691 

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Closed by tagliala** 2016-02-02 23:10 UTC
