### ISSUE TITLE
Icon Request: fa-search

### ISSUE THREAD

**Issue by janicerant** [FortAwesome/Font-Awesome#12202] opened 2018-02-01 03:57 UTC
[icon-search.zip](https://github.com/FortAwesome/Font-Awesome/files/1684134/icon-search.zip)

**Comment by tagliala** [comment] 2018-02-01 09:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6190, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-01 09:11 UTC
