### ISSUE TITLE
Icon request: icon-shopping-basket

### ISSUE THREAD

**Issue by noveweb** [FortAwesome/Font-Awesome#5788] opened 2015-02-25 23:36 UTC
Hi Guys,

Some e-commerces use the word basket(cesta in portuguese) or bag(sacola in portuguese) and not cart(carrinho in portuguese).

You are doing a great job in favor of a better internet. Congratulations and thank you in advance!

**Comment by tagliala** [comment] 2015-02-26 14:03
duplicate of #962 , please +1 that request

closing here

**Closed by tagliala** 2015-02-26 14:03 UTC
