### ISSUE TITLE
Icon request: physical shop

### ISSUE THREAD

**Issue by Rwthwyn** [FortAwesome/Font-Awesome#9847] opened 2016-09-01 08:33 UTC
Hi there,

I've been using font awesome for around a year and am very thankful for the time it has saved me in generating images for websites.

What I'm looking for at present is an icon that represents a shop. Not a shopping basket or a cart, but a physical shop. The attached represents the sort of thing I am after, and is what I will be using as a compromise. The reason for this request is that I am working on a new design for a site that has a link to the shopping basket in the header, with a shopping basket icon. Near the footer, there is a link to the online shop, which also needs an accompanying icon. To avoid any possible confusion, I think this second icon should be different.

At present, there doesn't seem to be a font awesome icon to represent a physical shop - there is a building - so I would like to see one.

Thanks for taking the time to read my request,

Mark

![shop-icon-23328](https://cloud.githubusercontent.com/assets/9024589/18160428/602a0192-7025-11e6-8f55-d72946419862.png)

**Comment by tagliala** [comment] 2016-09-01 10:58
Duplicate of #1958 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-01 10:58 UTC
