### ISSUE TITLE
Icon Request: icon-govdelivery

### ISSUE THREAD

**Issue by mallanest** [FortAwesome/Font-Awesome#1846] opened 2013-08-23 20:35 UTC
We have been asked by one of our clients (King County, Washington) to request that our GovDelivery icon email bubble be added to Font Awesome since they are using you guys with their new website design.
Below is an example of the icon.

![govbubble_flat_rgb](https://f.cloud.github.com/assets/1615841/1018865/5a65ed9c-0c33-11e3-89c4-896d7223211e.png)

Thanks!

**Comment by aragonwa** [comment] 2016-08-10 21:23
:+1:

**Comment by tagliala** [comment] 2022-04-02 13:51
Duplicate of #1433

**Closed by tagliala** 2022-04-02 13:51 UTC
Labels: brand icon
