### ISSUE TITLE
Icon Request: fa-rose

### ISSUE THREAD

**Issue by tizata** [FortAwesome/Font-Awesome#6321] opened 2015-04-25 19:03 UTC
![icon1_2](https://cloud.githubusercontent.com/assets/12114927/7334231/73d67834-eb96-11e4-9535-0a637dd71458.png)

Hi, need a few custom icons for my new website : http://denivaroseoil.com/new/?page_id=84

Please , help me if it possible! 

have a good one :)

**Comment by tagliala** [comment] 2015-04-25 19:53
duplicate of #4666 , please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-04-25 19:53 UTC
