### ISSUE TITLE
Icon Request: `icon-walking`

### ISSUE THREAD

**Issue by designermonkey** [FortAwesome/Font-Awesome#5689] opened 2015-02-16 15:29 UTC
A bit of a weird use case, but could an icon be created for walking in the transport section?

Two feet on a diagonal, one in front of the other...

All forms of transport are accounted for apart from walking.

**Comment by kkirsche** [comment] 2015-02-17 20:08
Per [CONTRIBUTING.md](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md) — Please title your new issue Icon request: `icon-name` (e.g., Icon request: `icon-car`).

**Comment by jmcopeland** [comment] 2015-02-18 07:55
+1

**Comment by tagliala** [comment] 2015-02-22 00:26
duplicate of #844 , please +1 that request

@kkirsche thanks

**Closed by tagliala** 2015-02-22 00:26 UTC

**Comment by kkirsche** [comment] 2015-02-22 00:27
Yep. Thanks for the project.
