### ISSUE TITLE
Icon request: Lawn mower

### ISSUE THREAD

**Issue by jpross-prx** [FortAwesome/Font-Awesome#16261] opened 2020-03-02 19:03 UTC
**What can it be used for?**
Used to represent a lawn mower or a person using a lawn mower

**Example image (optional)**
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.popicon.com%2Fproducts%2Fperson-pushing-a-lawn-mower-icon&psig=AOvVaw1W4IV1CvaI5UmA9tGAevdD&ust=1583262055633000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCOjE-_S8_OcCFQAAAAAdAAAAABAh

**Comment by tagliala** [comment] 2020-03-02 19:08
Hi!

Thanks for being part of the Font Awesome Community.

Can this be considered a duplicate of #14925 ?

**Comment by jpross-prx** [comment] 2020-03-02 19:21
Ho! Yes absolutely... Sorry for duplicate.

**Comment by tagliala** [comment] 2020-03-02 21:14
No problem

**Closed by tagliala** 2020-03-02 21:14 UTC
Labels: waiting for feedback
