### ISSUE TITLE
Icon request: Sim-icon

### ISSUE THREAD

**Issue by lucajick** [FortAwesome/Font-Awesome#10602] opened 2017-02-01 14:50 UTC
Very useful
![mobile-03-512](https://cloud.githubusercontent.com/assets/25476335/22511444/04c9adea-e896-11e6-815c-9ac5cdd24c46.png)

**Comment by tagliala** [comment] 2017-02-01 14:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2445, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-01 14:51 UTC
