### ISSUE TITLE
Icon Request: fa-dinner-service

### ISSUE THREAD

**Issue by mrBeardyhead** [FortAwesome/Font-Awesome#11229] opened 2017-06-26 16:32 UTC
We need some hotel service and restaurant icons. fa-cutlery and spoon are great but I can't keep using them over and over on a site when doing hotel, catering and restaurant work. Either a dinner plate or a dinner served icon would be useful. See my attached.
Please consider. Thanks! 
:Dale
![dinner-service-icon-example1](https://user-images.githubusercontent.com/13010016/27549815-eae68990-5a62-11e7-9391-afa43b5be41d.png)
![plate-cutlery-myexample2](https://user-images.githubusercontent.com/13010016/27549848-0a63e808-5a63-11e7-900b-6e284193438c.png)

**Comment by tagliala** [comment] 2017-06-26 16:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3453 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-26 16:35 UTC

**Comment by mrBeardyhead** [comment] 2017-06-26 16:43
Sorry, I did not search GitHub first. I get what to do now. I appreciate your help. Thanks. :) 👍
