### ISSUE TITLE
Icon Request: fa-rx

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9982] opened 2016-09-29 17:29 UTC
Prescription - To be used for Health Data Apps
![rx](https://cloud.githubusercontent.com/assets/539719/18964873/c8b124c8-8648-11e6-8ca9-82cfdf612012.png)

**Comment by tagliala** [comment] 2016-09-30 08:58
Duplicate of #768 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 08:58 UTC
