### ISSUE TITLE
Icon request : scene-clipping

### ISSUE THREAD

**Issue by Dhana-plantsight3d** [FortAwesome/Font-Awesome#14875] opened 2019-04-10 15:30 UTC
### What can it be used for?

we are making model and capturing by camera in three.js
### Example image (optional)
![image](https://user-images.githubusercontent.com/42356692/55892114-549a1580-5b7b-11e9-90a1-abf90b96b6f4.png)

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
single icon
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
Icon request : scene-clipping
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
yes
- [ ] I have included at least one example image if it could be helpful (optional)
yes

- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-04-10 15:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3130, please add a 👍 reaction to that request.

Closing here

**Closed by tagliala** 2019-04-10 15:34 UTC
