### ISSUE TITLE
Icon request: icon-parking

### ISSUE THREAD

**Issue by irene1234567** [FortAwesome/Font-Awesome#10064] opened 2016-10-13 10:26 UTC
Hello!

I'd like to have a parking icon (P), as I am involved in tourism and I'd like to find hotel services icon.

Thank you!

**Comment by tagliala** [comment] 2016-10-13 13:12
Duplicate of #1559 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-13 13:12 UTC

**Comment by irene1234567** [comment] 2016-10-13 13:25
Yes I saw the 2013 request...... Can you do something about it?

**Comment by tagliala** [comment] 2016-10-13 13:59
@irene1234567 nope, the best you can do is upvote an existing request so votes would not be dispersed, [consider a custom build](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome), or try [stacking text with icons](http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/)
