### ISSUE TITLE
Icon request: icon-blogger

### ISSUE THREAD

**Issue by amplifysk** [FortAwesome/Font-Awesome#10906] opened 2017-04-07 09:06 UTC
I found fa fa icons for all social media except blogger....currently i'm using a image for that...
![blogger-icon](https://cloud.githubusercontent.com/assets/25700668/24793395/7fc6938c-1b9f-11e7-8cbd-965802018268.jpg)

Please go ahead and design a icon for this too...
thank you

**Comment by PeterShaggyNoble** [comment] 2017-04-07 09:10
Dupe of #1088, you should 👍 that.

**Comment by amplifysk** [comment] 2017-04-07 09:18
please share i tag code here...
as in <i class="fa fa-facebook-official" aria-hidden="true"></i>

**Comment by PeterShaggyNoble** [comment] 2017-04-07 09:46
It doesn't exist yet. If you follow the link above, you'll see that it's a request for the Blogger icon. Adding your 👍 to that request will help push it up the queue of icons to be added.

**Comment by tagliala** [comment] 2017-04-07 10:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1088, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-07 10:39 UTC
