### ISSUE TITLE
Strong arm icon requested

### ISSUE THREAD

**Issue by madsrolsen** [FortAwesome/Font-Awesome#11569] opened 2017-09-29 09:50 UTC
![29606-200](https://user-images.githubusercontent.com/32387588/31010778-4b2b76c8-a50c-11e7-9bd4-b2c377236b2d.png)

**Comment by tagliala** [comment] 2017-09-29 10:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2076, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-29 10:34 UTC
