### ISSUE TITLE
Issue in Prestashop using Font Awesome

### ISSUE THREAD

**Issue by elisseee** [FortAwesome/Font-Awesome#6638] opened 2015-06-03 02:48 UTC
I have been trying to resolve this issue here https://www.prestashop.com/forums/topic/317230-prestashop-blog-module/page-98
but without success. I have a site astridorganics.com and Font Awesome worked with all icons they way it supposed to. However, I have installed a smartblog to my Prestashop v.1.6.0.14 and now instead of home I can see f015 and instead of user in the blog f007. That is happening all around the site. I should pointed out that I am pretty sure that error with a smartblog but that has not been resolved on their side and they have no idea how. You can take a look at my posting from May 21st but I never got a resolution for this problem. I am trying to figure out how to resolve this issue and leaning towards to delete the blog but I am not sure that rolling database back will resolve the problem. Your assistance is greatly appreciated. thank you

**Comment by tagliala** [comment] 2015-06-03 09:07
maybe that plugin is loading an old/modified version of fontawesome. Take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Closing here but feel free to comment

**Closed by tagliala** 2015-06-03 09:07 UTC

**Comment by elisseee** [comment] 2015-06-03 22:03
Dear Geremia,

None of the described problem I have encountered. First of all, my version
is new installation and FontAwesome is v.4.0.3. Second of all, it worked
without problems before I have installed a smartblog. I understand that you
dont have neither time or desire to dig into why smartblog created this
problem in a first place, but I point this out for a reason that someone
else could encounter a similar problem and resolution could be there
already.

In any case, I am open to suggestions.

Thank you
Stan

**Comment by tagliala** [comment] 2015-06-04 11:50
if you can point me to a webpage showing the issue I can take a look

**Comment by elisseee** [comment] 2015-06-04 14:32
Thank you Geremia. For example, this page
http://astridorganics.com/en/16-special-blending-oils
see attachment. On ANY page it does not showing Go Home anymore just code
f015..

**Comment by tagliala** [comment] 2015-06-04 14:38
Hi, it seems that css files are being "corrupted" during the process.

![image](https://cloud.githubusercontent.com/assets/556268/7986440/dba8cfec-0ad7-11e5-8dd9-0bbe150d5132.png)

As you can see, there is a missing backslash here (it should be "\f015")

I don't know what could be the cause. It seems just for icon-home. 

You could add `.icon-home:before{content:"\f015"}` to your stylesheet to workaround this issue

**Comment by elisseee** [comment] 2015-06-04 14:41
this is not an issue - i actually played with that myself to see if it is
going to resolve my issue. i will put it back this slash right now but it
is not a resolution unfortunately

**Comment by elisseee** [comment] 2015-06-04 15:13
that is funny, it seems when i put it back, the slash i mean, it started to
work again. i guess the whole issue was in caching the icon and code. thank
you so much for your help

**Comment by tagliala** [comment] 2015-06-04 16:19
you're welcome, glad you solved
