### ISSUE TITLE
Icon request: fa-pull-request

### ISSUE THREAD

**Issue by aensley** [FortAwesome/Font-Awesome#15229] opened 2019-07-03 12:52 UTC
**What can it be used for?**
To identify Pull Requests in Git/GitHub source control.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/95717/60592969-5da81680-9d67-11e9-92a3-8664ee0e2eda.png)
[Source](https://octicons.github.com/icon/git-pull-request/)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-07-03 13:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2497, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-07-03 13:58 UTC

**Comment by aensley** [comment] 2019-07-05 16:43
Thanks, @tagliala. I did search, but unfortunately every pull request on the repo matched the search "pull request"

**Comment by tagliala** [comment] 2019-07-05 18:58
@aensley you're welcome, don't worry 👍
