### ISSUE TITLE
Icon request: fa-passkey

### ISSUE THREAD

**Issue by martijnvdwal** [FortAwesome/Font-Awesome#19715] opened 2023-05-06 18:27 UTC
A passkey is new method of online authentication. It's fast and really secure, even more secure than an account with a password and 2FA. Having an icon for passkey is crutial to help it's growth.

The FIDO Alliance has published [guidelines](https://fidoalliance.org/passkeys/) to follow for creating a passkey icon.

**Comment by tagliala** [comment] 2023-05-06 18:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19405, please add a 👍 reaction to that request.

Please also add there a comment with the brand guidelines

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-05-06 18:35 UTC
