### ISSUE TITLE
scout fleur-de-lis

### ISSUE THREAD

**Issue by jkgarner** [FortAwesome/Font-Awesome#19050] opened 2022-05-18 12:03 UTC
Some of the symbols of the world-wide scouting movement have been requested, like the scout hand sign. 
The scout fleur-de-lis should also be included as an icon sa_scout_fleur would be a good name
![fleur-de-lis](https://user-images.githubusercontent.com/3368943/169034202-0a45af7b-5535-4654-83a2-b1f153020c62.svg)

**Comment by tagliala** [comment] 2022-05-18 12:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6843, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-05-18 12:07 UTC
