### ISSUE TITLE
Copy Glyph not working on main search view

### ISSUE THREAD

**Issue by n8allen** [FortAwesome/Font-Awesome#16799] opened 2020-06-15 21:31 UTC
After the recent update to your site the "Copy Glyph" option no longer works from the main search pages. Still working on the detail pages. 

![image](https://user-images.githubusercontent.com/5325608/84708099-b6d76e80-af14-11ea-8369-23e1784c2761.png)

**Comment by tagliala** [comment] 2020-06-16 07:33
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm

```
instrument.js:110 TypeError: Cannot read property 'copyUnicode' of undefined
    at click (IconResult.vue?c549:2)
    at Be (vue.common.prod.js:6)
    at SVGSVGElement.n (vue.common.prod.js:6)
    at SVGSVGElement.Zi.a._wrapper (vue.common.prod.js:6)
    at SVGSVGElement.i (helpers.js:71)
```

Let's assign @talbs

**Comment by tagliala** [comment] 2020-06-18 21:15
@n8allen looks like it's fixed

Let me know, meanwhile closing here

**Closed by tagliala** 2020-06-18 21:15 UTC
Labels: bug, doc, fontawesome.com
