### ISSUE TITLE
Icon Request: fa-ethereum

### ISSUE THREAD

**Issue by CraigglesO** [FortAwesome/Font-Awesome#10614] opened 2017-02-05 01:32 UTC
You have bitcoin, but not Ethereum which is also a very popular currency.

Thanks for font-awesome 👍  ^_^

**Comment by tagliala** [comment] 2017-02-05 11:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8754, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-05 11:23 UTC
