### ISSUE TITLE
Icon Request: fa-salesforce

### ISSUE THREAD

**Issue by SwapnaNethi** [FortAwesome/Font-Awesome#10728] opened 2017-03-01 19:40 UTC
I would like to initially thank fontawesome for coming with such fantastic icons which we use exhaustively to design our landing Pages and Home Pages in our Sharepoint portal.

Now i have a requirement to create a tile for salesforce which is going to be a very big project in our organization. I tried to see all icons under the Brands category but unfortunately don't find one for salesforce.

if possible, can you please create one for this? Also may i know how long does it take for start using?

**Comment by tagliala** [comment] 2017-03-01 20:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1744, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-01 20:05 UTC
