### ISSUE TITLE
Icon request: Snowflake

### ISSUE THREAD

**Issue by kwando** [FortAwesome/Font-Awesome#1739] opened 2013-08-08 14:59 UTC
A snowflake icon, like this one http://www.clker.com/cliparts/r/h/A/0/V/q/snow-flake.svg

It should probably be filled in order to fit as an icon.

**Comment by byrock** [comment] 2015-01-02 17:12
+1

**Comment by gimpyeyes** [comment] 2015-01-03 20:29
+1

**Comment by kuzin** [comment] 2015-01-06 18:25
+1

**Comment by henleywc** [comment] 2015-01-15 08:18
+1

**Comment by itsmeroger** [comment] 2015-01-16 00:38
+1

**Comment by CarterLiebman** [comment] 2015-02-16 23:01
+1

**Comment by cloudinspector** [comment] 2015-02-23 18:06
+1
HVAC websites discussing air conditioning services. Would go great with fire!

**Comment by lawrencecushman** [comment] 2015-02-25 09:39
+1

**Comment by JoshWeb** [comment] 2015-02-26 15:05
+1

**Comment by G-Driver** [comment] 2015-03-03 14:17
+1

**Comment by Hates** [comment] 2015-03-05 23:02
+1

**Comment by skyepn** [comment] 2015-03-09 23:10
+1 thanks

**Comment by codyn329** [comment] 2015-03-10 18:32
+1

**Comment by julkiewicz** [comment] 2015-03-18 18:01
+1

**Comment by iseeyou911** [comment] 2015-03-20 11:47
+1

**Comment by ClearEdgeConsulting** [comment] 2015-03-20 18:59
+1

**Comment by lepetitoeuf** [comment] 2015-03-22 09:34
+1

If you are able to add a snowflake it would be fantastic and get immediate use here!

**Comment by thehavknots** [comment] 2015-03-22 19:58
+1

**Comment by AncientToaster** [comment] 2015-04-01 23:04
+1

**Comment by lviverit** [comment] 2015-04-02 10:03
+1

**Comment by gillespieza** [comment] 2015-04-10 09:19
+1 for a site about air-conditioning and refrigeration repairs

**Comment by coffeelady** [comment] 2015-04-13 14:24
+1

**Comment by welligton1993** [comment] 2015-04-20 19:31
+1

**Comment by thmsmtylr** [comment] 2015-05-05 05:29
+1

**Comment by perfectsquircle** [comment] 2015-05-11 23:38
+1

**Comment by DigitalBella** [comment] 2015-05-20 20:50
+1

**Comment by migmolrod** [comment] 2015-05-27 23:49
+1

**Comment by HFBGL** [comment] 2015-06-03 02:25
+1

**Comment by kashifnawaz77** [comment] 2015-06-04 13:54
+1

**Comment by esotericast** [comment] 2015-06-06 09:52
+1

**Comment by pd1808** [comment] 2015-07-05 20:14
+1

**Comment by OliverDashiell** [comment] 2015-07-24 10:53
+1

**Comment by lopezb** [comment] 2015-07-30 00:17
+1

**Comment by ogunm** [comment] 2015-08-06 12:16
+1

**Comment by annaenya** [comment] 2015-08-07 08:22
+1

**Comment by veritascs** [comment] 2015-08-19 20:18
+1

**Comment by aquerrec** [comment] 2015-08-25 15:41
+1

**Comment by stevekr** [comment] 2015-08-27 07:13
+1

**Comment by jlr7245** [comment] 2015-08-28 15:43
+1

**Comment by neeasade** [comment] 2015-09-22 03:15
+1

**Comment by brentdeacon** [comment] 2015-09-23 06:52
+1

**Comment by Saltallica** [comment] 2015-09-23 12:45
+1 for the action of "freezing" an account.

**Comment by iselena** [comment] 2015-10-02 16:53
+1

**Comment by Marc-pi** [comment] 2015-10-05 08:00
+1

**Comment by xabispacebiker** [comment] 2015-10-18 23:28
+1

**Comment by nikkiroylance** [comment] 2015-10-19 12:07
+1

**Comment by TimKlein87** [comment] 2015-10-24 00:42
+1, maybe something like:
![](https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Snow_flake.svg/232px-Snow_flake.svg.png)
https://commons.wikimedia.org/wiki/File:Snow_flake.svg

**Comment by mfurlend** [comment] 2015-11-03 19:13
+1

**Comment by G-Driver** [comment] 2015-11-03 20:28
+1

**Comment by paullaros** [comment] 2015-11-08 14:18
+1

**Comment by MVcodeartbr** [comment] 2015-11-27 14:40
+1

**Comment by tribulant** [comment] 2015-11-28 22:28
+1

**Comment by kpingel** [comment] 2015-12-02 14:34
:+1:

**Comment by bradInside** [comment] 2015-12-03 10:55
+1

**Comment by Xalbi** [comment] 2015-12-03 13:45
+1

**Comment by roxyavgfli** [comment] 2015-12-07 12:58
+1

**Comment by MrZach** [comment] 2015-12-09 04:16
+1

**Comment by HenryLamorski** [comment] 2015-12-15 14:58
+1

**Comment by iivannov** [comment] 2015-12-17 13:41
+1

**Comment by matiasgualino** [comment] 2015-12-29 13:14
+1

**Comment by gcluley** [comment] 2016-01-03 17:01
+1

**Comment by skyepn** [comment] 2016-01-06 18:40
This request is 3 years old now, hoping we can get a snowflake before this winter is over again?

**Comment by simonepri** [comment] 2016-01-07 19:12
+1

**Comment by G-Driver** [comment] 2016-01-08 14:13
+1

**Comment by vincentp** [comment] 2016-01-10 17:57
+1

**Comment by once94** [comment] 2016-01-12 13:02
+1

**Comment by Kyttias** [comment] 2016-01-14 19:27
+1

**Comment by ShellyTan** [comment] 2016-01-21 19:00
+1

**Comment by ottk3** [comment] 2016-01-23 09:44
+1

**Comment by christinekatz** [comment] 2016-01-26 17:09
+1

**Comment by belugame** [comment] 2016-01-29 10:25
+1

**Comment by Jusas** [comment] 2016-01-30 11:32
+1

**Comment by poblabs** [comment] 2016-02-03 00:39
+1

**Comment by jasonbio** [comment] 2016-02-06 09:54
+1

**Comment by pasci84** [comment] 2016-02-10 08:13
+1

**Comment by jpsantos7** [comment] 2016-02-19 17:50
+1

**Comment by chicagomom** [comment] 2016-02-21 02:41
+1 municipal snow removal and winter programming

**Comment by krypsin** [comment] 2016-02-22 20:47
+1

**Comment by bensampaio** [comment] 2016-03-02 09:43
+1

**Comment by JennyWren** [comment] 2016-03-07 18:49
+1

**Comment by LukeBillington** [comment] 2016-03-09 19:13
+1

**Comment by RebeccaCotton** [comment] 2016-03-11 10:33
+1 indicate cooling of things, coolingbags or similar

**Comment by nnneerajjj** [comment] 2016-03-12 06:18
+1

**Comment by mikemike396** [comment] 2016-03-30 15:36
+1

**Comment by george-christopoulos** [comment] 2016-04-07 10:38
+1

**Comment by erikmellum** [comment] 2016-04-12 01:11
+1

**Comment by pete7863** [comment] 2016-04-14 03:46
+1

**Comment by AndreLGava** [comment] 2016-04-16 13:29
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-snow-flake was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by Marc-pi** [comment] 2016-04-16 13:45
good. 
NB : the problem is the competition between FA and Fortawesome...

**Comment by twohumans** [comment] 2016-05-20 13:28
+1

**Comment by wouterMostard** [comment] 2016-06-04 11:24
+1

**Comment by ekizo** [comment] 2016-06-13 21:15
+1

**Comment by karladidas** [comment] 2016-06-14 09:02
+1

**Comment by elvarsteinn** [comment] 2016-06-15 17:21
+1

**Comment by she-dev** [comment] 2016-06-30 12:38
+1

**Comment by edusig** [comment] 2016-06-30 12:39
+1

**Comment by Daibushi** [comment] 2016-07-01 19:13
+1

**Comment by tryton-vanmeer** [comment] 2016-07-02 20:05
+1

**Comment by nocnyduch** [comment] 2016-07-06 10:32
+1

**Comment by poblabs** [comment] 2016-07-06 11:54
@tagliala @davegandy Hey guys, just curious how many more +1's are needed to make this official? It's pushing 3 years old. Thanks!

**Comment by mikemike396** [comment] 2016-07-06 11:56
+1

**Comment by tagliala** [comment] 2016-07-06 12:03
@poblabs this icon is very popular and it is planned for milestone 5.0.0

I don't have a deadline, sorry

**Comment by imperat0r** [comment] 2016-07-22 11:52
+1

**Comment by flyingboy007** [comment] 2016-07-28 02:55
+1

**Comment by alexbalser** [comment] 2016-08-01 05:45
+1
winter is coming!

**Comment by pranjal-goswami** [comment] 2016-08-22 10:11
👍

**Comment by weatherbell** [comment] 2016-08-23 16:34
+1

**Comment by panips** [comment] 2016-08-26 07:46
+1

**Comment by e-magine** [comment] 2016-08-26 10:15
+1 Could really do with an A/C icon in the form of a snowflake for hotel amenities. Thanks

**Comment by krienow** [comment] 2016-08-29 09:50
+1

**Comment by gautamsharma108del** [comment] 2016-09-28 10:01
+1

**Comment by rybex** [comment] 2016-10-01 20:57
+1

**Comment by yaldaomm** [comment] 2016-10-22 22:19
+1

**Comment by davegandy** [comment] 2016-10-22 22:49
Added to 4.7.0 branch. Closing.

**Closed by davegandy** 2016-10-22 22:49 UTC
Labels: new icon, web application icons
