### ISSUE TITLE
Icon Request: fa-clean

### ISSUE THREAD

**Issue by 888Plugin8COM** [FortAwesome/Font-Awesome#9046] opened 2016-04-23 13:45 UTC
![1492787-0-recleanguaranteeicon](https://cloud.githubusercontent.com/assets/18630685/14761796/a42dc412-092f-11e6-9878-3bcbd73acd5f.png)

image for personal website at www.ecospiritcleaners.com

Thank you in advance

**Comment by tagliala** [comment] 2016-04-23 13:58
Duplicate of #239 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-23 13:58 UTC
