### ISSUE TITLE
Icon request: icon-hard-hat

### ISSUE THREAD

**Issue by CountZachula** [FortAwesome/Font-Awesome#6704] opened 2015-06-09 16:31 UTC
Use Case
* As a manager, you are viewing a list of employees for a construction company. It is difficult to distinguish specific employee types. You would like a visual cue for those that are on-site workers (roughnecks).

![horrible-hard-hat-drawing](https://cloud.githubusercontent.com/assets/2559507/8063561/01777a90-0e9b-11e5-8afb-dbfc9970c95a.jpg)

**Comment by tagliala** [comment] 2015-06-10 10:04
duplicate of #5790, please +1 that request

closing here

**Closed by tagliala** 2015-06-10 10:04 UTC
