### ISSUE TITLE
Icon Request - torn sheet

### ISSUE THREAD

**Issue by Plavozont** [FortAwesome/Font-Awesome#11548] opened 2017-09-22 05:33 UTC
This is for the case if something is broken on a web-site. Maybe some other icons that could be found by "broken", "fault", "error", "not found", "restricted" or "access denied" keywords.

![tornsheet](https://user-images.githubusercontent.com/7393355/30730576-46ece526-9f92-11e7-8540-5bf0cf493655.png)

**Comment by aethior** [comment] 2022-03-10 11:16
Duplicate of #12408. (_the title of the other request is more clear and has more upvotes_)

cc/ @tagliala

**Closed** 2022-03-10 11:42 UTC
Labels: new icon, web application icons
