### ISSUE TITLE
New icon for Flutter

### ISSUE THREAD

**Issue by rvndsngwn** [FortAwesome/Font-Awesome#17343] opened 2020-10-31 22:34 UTC
**What can it be used for?**
Flutter is Google’s UI toolkit for building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase.
Icon request for flutter icon(logo)

**Example image (optional)**
https://flutter.dev/images/flutter-mono-81x100.png,
https://flutter.dev/assets/flutter-lockup-1caf6476beed76adec3c477586da54de6b552b2f42108ec5bc68dc63bae2df75.png

**Comment by tagliala** [comment] 2020-10-31 22:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14878 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-10-31 22:38 UTC

**Comment by rvndsngwn** [comment] 2020-10-31 22:40
@tagliala thanks for the response.
