### ISSUE TITLE
Icon Request: fa-Raspberry

### ISSUE THREAD

**Issue by EdKo66** [FortAwesome/Font-Awesome#12184] opened 2018-01-30 08:57 UTC
![rpi](https://user-images.githubusercontent.com/7892897/35556887-d6068768-05a3-11e8-96f6-259d62cf3c9c.png)

Would use them to display on wal-mounted tablets

**Comment by tagliala** [comment] 2018-01-30 09:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2944, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-30 09:07 UTC
