### ISSUE TITLE
New Icon Request : fa-zero-percent

### ISSUE THREAD

**Issue by apsaraaruna** [FortAwesome/Font-Awesome#9328] opened 2016-06-03 09:57 UTC
I would like to request new icon to 0% (zero-percent) sign. please consider this icon :)

![0](https://cloud.githubusercontent.com/assets/567196/15775423/727337aa-299f-11e6-8fb9-819aee27bced.png)

**Comment by apsaraaruna** [comment] 2016-06-03 10:30
as well as add this one too.. fa-zero-percent-o
![0 -o](https://cloud.githubusercontent.com/assets/567196/15776253/1e1bc6c2-29a4-11e6-952f-f458dc2bb97e.png)

**Comment by apsaraaruna** [comment] 2016-06-03 10:31
here the PSD file of that two icons.
[0%.zip](https://github.com/FortAwesome/Font-Awesome/files/297399/0.zip)

**Comment by tagliala** [comment] 2016-06-03 11:25
Asked feedback to Dave. Could you please provide a use case and why 0% is important instead of, let's say, 1%, 2% and so on?

**Comment by apsaraaruna** [comment] 2016-06-03 11:40
we want to show '0%' 
there is icon to replace with font awesome icon.so there is no icon of it.. 
![precent icon](https://cloud.githubusercontent.com/assets/567196/15777509/7fc044e4-29ad-11e6-86af-894ceab5232a.PNG)

**Comment by apsaraaruna** [comment] 2016-06-03 11:43
if there is problem can you add 'free' icon like this..?  ( fa-free )

here is the PSD file.and also there is black icon and white icon.. 

![free-512](https://cloud.githubusercontent.com/assets/567196/15777592/3fd01de0-29ae-11e6-9196-fb09fbaaf3bb.png)
[free-512.zip](https://github.com/FortAwesome/Font-Awesome/files/297480/free-512.zip)

**Comment by tagliala** [comment] 2016-06-03 11:44
Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Free is a duplicate of #9221 , please +1 that request

**Comment by apsaraaruna** [comment] 2016-06-03 11:49
Ok .. sorry for disturbing you.. :(

**Comment by tagliala** [comment] 2016-06-03 11:50
@apsaraaruna don't worry, no problem

**Closed** 2016-06-03 11:56 UTC
Labels: waiting for feedback
