### ISSUE TITLE
Icon Request: fa-router

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7146] opened 2015-08-05 13:50 UTC
fa-router icon example:
![Router](http://i.imgur.com/CzxGX2v.png)

It does not have to look exactly like this.

**Comment by tagliala** [comment] 2015-08-08 11:11
duplicate of #6025, please +1 that request and post there your example

editing #6025 to include router in the title

closing here

**Closed by tagliala** 2015-08-08 11:11 UTC

**Comment by tuxy** [comment] 2015-08-11 14:13
Done, thank you!
