### ISSUE TITLE
Icon request: degrees

### ISSUE THREAD

**Issue by joshkordek3** [FortAwesome/Font-Awesome#17804] opened 2021-04-09 03:16 UTC
**What can it be used for?**
If you wanted to create a sprite on scratch with the degree symbol and were too lazy to make your own, or if you wanted to create an extension on https://makecode.microbit.org

**Example image (optional)**
(don't use these, they don't have a transparent background, its just an example)
Fahrenheit: 
![symbol-number-degree-text](https://user-images.githubusercontent.com/79750252/114123096-327f2d80-9924-11eb-9d24-f046f5320280.jpg)
Celsius:
![png-transparent-degree-symbol-celsius-temperature-symbol](https://user-images.githubusercontent.com/79750252/114123255-8427b800-9924-11eb-8005-0448308df0b6.png)
Kelvin:
![grey-kelvin-icon-isolated-on-260nw-1582314625](https://user-images.githubusercontent.com/79750252/114123744-8a6a6400-9925-11eb-9420-971d9154d91d.png)

**Icon request checklist**
- [set of 3] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-04-09 08:04
Hi!

Thanks for being part of the Font Awesome Community.

Celsius and Fahrenheit This request is a duplicate of #10241, please add a 👍 reaction to that request.

[Kelvin should not be preceded by the degree symbol](https://web.archive.org/web/20070421013852/http://www.bipm.fr/en/CGPM/db/13/3/), so it will be part of FA6 as letter K

Closing here

**Closed by tagliala** 2021-04-09 08:04 UTC
