### ISSUE TITLE
Icon Request: fa-opensource-o

### ISSUE THREAD

**Issue by jesseflorig** [FortAwesome/Font-Awesome#6756] opened 2015-06-15 04:22 UTC
I'd like to request icons for the open source logo as seen here: 
![open source logo](http://opensource.org/files/garland_logo.png)

It would be great to use in open source projects as a pixel-perfect badge of openness!

I searched the Issues for this submission since I assumed it would have been requested already, but to my surprise I couldn't find anything. my apologies in advance if I  missed it.

Cheers!

**Comment by hebbet** [comment] 2015-06-15 11:47
Duplicate of #6200

**Comment by tagliala** [comment] 2015-06-21 19:48
which is a duplicate of #1283

Leaving this open as open-source-o

**Comment by tagliala** [comment] 2018-01-13 17:43
Can't remember why I left this open...

BTW this is a duplicate of #1283 and icon-osi is available on FA5 https://fontawesome.com/icons/osi?style=brands

**Closed by tagliala** 2018-01-13 17:43 UTC
Labels: brand icons, new icon
