### ISSUE TITLE
Icon Request: fa-wattpad

### ISSUE THREAD

**Issue by MileAcero** [FortAwesome/Font-Awesome#7064] opened 2015-07-29 00:25 UTC
hello, my name is michelle and i'd like to make a request for a wattpad icon. Wattpad is a webpage where independent writers share their work such as novels, short histories, etc. And everybody can see their work free.
i want this icon to attach it to my blog, where i write and comment reviews from books, and i would like the people to see the work from independent writers rather than the best sellers.
sincerely thank you :) 

![pr_source 175x175-75](https://cloud.githubusercontent.com/assets/13545072/8943624/455ead60-3541-11e5-9aaf-7c2e00a426f0.png)

**Comment by TheChen5** [comment] 2015-07-29 01:31
Dupe of #3402
+1 that
:mag_right:before:heavy_plus_sign:

**Comment by DennaGherlyn** [comment] 2015-07-29 06:47
+1

**Comment by tagliala** [comment] 2015-07-29 08:34
@TheChen5 thanks :+1:  :)

**Closed by tagliala** 2015-07-29 08:34 UTC

**Comment by DANHAN63** [comment] 2016-09-04 22:23
Yes, we need a Wattpad Icon. +1

**Comment by carrieloves** [comment] 2019-03-07 14:00
Wattpad has a new icon for 2019.
 
![wattpad](https://user-images.githubusercontent.com/6716583/53961767-5faee100-40b7-11e9-9187-a7acf415af58.jpg)

**Comment by Jadesolax** [comment] 2022-06-13 18:23
Hi Community!
is there now an icon for wattpad?
