### ISSUE TITLE
Icon request: fa-snapchat

### ISSUE THREAD

**Issue by JoshRiser** [FortAwesome/Font-Awesome#8888] opened 2016-04-04 18:38 UTC
Actually pretty surprised that there isn't a Snapchat icon yet!

I think an outline, filled, and "-square" version would be nice.

![image](https://cloud.githubusercontent.com/assets/1509348/14258976/d8d67e5a-fa72-11e5-8702-98777a3ef824.png)

**Comment by tagliala** [comment] 2016-04-04 22:16
Duplicate of #3906 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-04 22:16 UTC
