### ISSUE TITLE
Icon Request: Alipay

### ISSUE THREAD

**Issue by Airkro** [FortAwesome/Font-Awesome#10277] opened 2016-11-25 09:21 UTC
Alipay is a major Chinese payment platform , like Paypal.

we need it in FontAwesome

**Comment by tagliala** [comment] 2016-11-25 09:44
Duplicate of #3854, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-25 09:44 UTC
