### ISSUE TITLE
Icon Request: High Five

### ISSUE THREAD

**Issue by wilsonography** [FortAwesome/Font-Awesome#18906] opened 2022-04-13 16:49 UTC
Like the current set of hand icons, but a high five...I think it would be super useful to have a more laid back / emphatic icon option in addition to thumbs-up and things like that.

**Comment by tagliala** [comment] 2022-04-13 17:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7491, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-04-13 17:07 UTC
