### ISSUE TITLE
Icon request: fa-integrated-circuit

### ISSUE THREAD

**Issue by kyakan** [FortAwesome/Font-Awesome#5319] opened 2015-01-02 10:59 UTC
IC = Integrated Circuit

Useful for hardware representation, like this:
http://www.iconsdb.com/icons/download/black/integrated-circuit-256.png

**Comment by tagliala** [comment] 2015-01-02 12:38
maybe a duplicate of #1840

**Comment by hightekjonathan** [comment] 2015-03-23 02:54
+1

**Comment by stijnvanbael** [comment] 2015-04-10 06:54
+1

**Comment by tagliala** [comment] 2020-06-24 16:59
Let's use #5319

**Comment by tagliala** [comment] 2020-06-24 16:59
Let's use #16820

**Closed by tagliala** 2020-06-24 16:59 UTC
Labels: waiting for feedback
