### ISSUE TITLE
icon request: fa-case

### ISSUE THREAD

**Issue by saydax** [FortAwesome/Font-Awesome#14865] opened 2019-04-08 10:05 UTC
Hello,
can you add money safe icon?
Thanks.

![case-big](https://user-images.githubusercontent.com/3241658/55716204-07913480-59ff-11e9-8192-fd599af4f138.png)

**Comment by tagliala** [comment] 2019-04-08 10:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12611, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-08 10:38 UTC
