### ISSUE TITLE
Icon Request: GovDelivery

### ISSUE THREAD

**Issue by kristiekbauer** [FortAwesome/Font-Awesome#1433] opened 2013-06-27 16:02 UTC
We have been asked by one of our clients (King County, Washington) to request that our GovDelivery icon email bubble be added to Font Awesome since they are using you guys with their new website design.

Let me know what needs to be done to make this happen for them along with the requirements.

**Comment by aethior** [comment] 2022-04-02 13:43
Duplicate of #1846.

cc/ @tagliala

**Comment by aethior** [comment] 2022-04-14 17:24
@tagliala `brand (category)` label for this request?

**Comment by aethior** [comment] 2022-07-25 10:45
>Denver, CO, St. Paul, MN and Washington, D.C. – [Granicus](https://granicus.com/), the leading provider of software solutions to improve government efficiency and transparency, and GovDelivery, the leading cloud-based digital communication platform for government, today announced that the two companies will merge effective immediately. ([more info](https://granicus.com/blog/granicus-govdelivery-announce-merger/))

GovDelivery was adquired by Granicus. After the merge, their social profiles were removed ([twitter](https://twitter.com/GovDelivery) and [facebook](https://www.facebook.com/govdelivery/)).

cc/ @tagliala

**Closed** 2022-07-25 10:58 UTC
Labels: brand icon
