### ISSUE TITLE
Icon request: fa-biceps

### ISSUE THREAD

**Issue by frensuren** [FortAwesome/Font-Awesome#5505] opened 2015-01-28 07:39 UTC
I would like to request the icon fa-biceps to signify/ denote strength.
It could be used to signify the strength or power.
![image](https://cloud.githubusercontent.com/assets/5062925/5933987/8d0110a2-a6f0-11e4-9ed3-648857dc4ce5.png)

It can be other icons like this 
![image](https://cloud.githubusercontent.com/assets/5062925/5933994/bdd99992-a6f0-11e4-8f8c-d791123611ce.png)

<div>Icon made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div>

Possible use cases where icon can be used to signify:
1. Powerful software
2. Strong Build
3. Strong architecture
etc.

**Comment by tagliala** [comment] 2015-01-28 20:31
:muscle:

**Comment by GKolmerer** [comment] 2015-05-16 08:44
+1

**Comment by danirios93** [comment] 2016-04-05 06:21
+1 for this please

**Comment by LordPrettyFlacko** [comment] 2016-08-08 11:00
+1

**Comment by Reltik** [comment] 2016-08-10 04:27
+1

**Comment by SimonSomlai** [comment] 2017-02-07 16:21
+ 2

**Comment by gitzrulz** [comment] 2017-06-16 14:02
+1

**Comment by tagliala** [comment] 2017-09-29 10:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2076, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-29 10:33 UTC
Labels: new icon, web application icons
