### ISSUE TITLE
Icon request: fa-spa (spa/wellness)

### ISSUE THREAD

**Issue by dgrothaus-ku** [FortAwesome/Font-Awesome#12361] opened 2018-02-15 07:01 UTC
### What can it be used for?

Map markers for spa/wellness businesses, hotel services.

### Example image (optional)

[Material Icons Spa](https://material.io/icons/#ic_spa)
![materialicons](https://user-images.githubusercontent.com/22188636/36244911-9d001bc8-1228-11e8-8242-22707671f221.png)

[Looma Spa](http://www.loomaspa.com/)
![loomaspa](https://user-images.githubusercontent.com/22188636/36244883-83c3f2ba-1228-11e8-80a9-15902253dbef.png)

[Adara Medical Spa](https://twitter.com/adaramedicalspa)
![adaramedicalspa](https://user-images.githubusercontent.com/22188636/36244892-87423d7a-1228-11e8-86b6-776bb04c5d4a.jpeg)

### Icon request checklist

- [X] This is a single icon
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is a duplicate of #5789 but with focus of a more general and recognizable icon.
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

### Disclaimer

As stated in the disclaimer, I'm aware of  #5789. But while #5789 has a focus on the wellness/massage part, I'd like an icon that's usable in a more general way.

The [Lotus Blossom](https://www.google.de/search?q=lotus+blossom&tbm=isch) is a recognized symbol for spa and wellness businesses.

**Comment by tagliala** [comment] 2018-02-15 09:58
Hi!

Thanks for being part of the Font Awesome Community.

So you are basically requesting a lotus blossom icon?

If yes, this is a duplicate of #6757

**Comment by dgrothaus-ku** [comment] 2018-02-15 10:27
Well, yes. That's the exact request. While searching for existing requests I only searched for the intended usage of the icon (spa, wellness), not the actual thing it symbolizes.

**Comment by tagliala** [comment] 2018-02-15 10:32
Ok, thanks.

Please 👍 #6757

This should follow under

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

(replace "wellness" with "happiness" and "lotus" with "smiley face" 😄)

Closing here

**Closed by tagliala** 2018-02-15 10:32 UTC
Labels: waiting for feedback
