### ISSUE TITLE
Icon request: icon-fingerprint

### ISSUE THREAD

**Issue by mooseywilson** [FortAwesome/Font-Awesome#5447] opened 2015-01-22 19:46 UTC
I'm a visual designer and looking for an icon that would represent "identity" - as in branding and corporate identity. Despite this need, I think that a fingerprint could represent a whole bunch of things and would be pretty useful to a lot of people!

Cheers.

Potential inspiration here: http://3.bp.blogspot.com/-Ljnu868Ug14/UlHEm864jmI/AAAAAAAAZ6A/7bQvDdaMcxY/s1600/Fingerprint.png

**Comment by tagliala** [comment] 2015-01-22 22:45
duplicate of #4431 , please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-01-22 22:45 UTC

**Comment by mooseywilson** [comment] 2015-01-22 22:48
Cheers. Searched but didn't find it. New to Github so might of missed something.

**Comment by tagliala** [comment] 2015-01-22 22:52
@mooseywilson don't worry
