### ISSUE TITLE
Icon Request: fa-pharma

### ISSUE THREAD

**Issue by Benqzq** [FortAwesome/Font-Awesome#11158] opened 2017-06-10 20:18 UTC
Hey guys! I don't have a firm idea on the icon's nature but I suggest creating a pharma icons. Maybe pills or capsules or (if it's allowed) something combined like a leaf with 2 pills or maybe even a [Mortar and pestle](https://he.wikipedia.org/wiki/%D7%A2%D7%9C%D7%99_%D7%95%D7%9E%D7%9B%D7%AA%D7%A9#/media/File:Lao_cuisine_khok.jpg).

**Comment by tagliala** [comment] 2017-06-10 21:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1709, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-10 21:09 UTC

**Comment by Benqzq** [comment] 2017-06-10 21:15
The linked issue deals with Mortar and Pastle alone, but I do intend to have a broad discussion and some opinions on a "pharma" icon. I think that Mortar and Pastle should have an icon anyway, wether tagged as "Pharma" or not, but for Pharma we could indeed consider pills or tablets or something including them.
