### ISSUE TITLE
Icon Request: fa-marketing

### ISSUE THREAD

**Issue by kevspadilla** [FortAwesome/Font-Awesome#8319] opened 2016-01-13 06:48 UTC
Hi all, may request for an icon which will be used for navigation for marketing links.

Heres a sample image: 
http://hourglass-studios.com/wp-content/uploads/2014/04/VisualMarketing_Icon.png

Thanks!

**Comment by JeroenCollier** [comment] 2016-01-13 08:32
+1

**Comment by scottux** [comment] 2016-01-14 19:05
looks a lot like http://fontawesome.io/icon/line-chart/

**Comment by kevspadilla** [comment] 2016-01-14 23:55
yeah @scottux, but maybe its better to have the bar graph. :smile:

**Comment by scottux** [comment] 2016-01-15 00:49
i wonder what they look like stacked, maybe a tweak or two and the line
graph stacked on the bar graph could provide this appearance.

**Comment by kevspadilla** [comment] 2016-01-16 05:18
oh thanks! let me try.. :+1:

**Comment by tagliala** [comment] 2016-01-16 09:48
we need a better title for this request and a single color example

**Comment by tagliala** [comment] 2016-01-16 09:49
duplicate of #6881, please +1 that request

closing here

**Closed by tagliala** 2016-01-16 09:49 UTC
Labels: waiting for feedback
