### ISSUE TITLE
Brand request: cdnjs

### ISSUE THREAD

**Issue by Emiliano26-lang** [FortAwesome/Font-Awesome#20514] opened 2024-12-30 15:57 UTC
### Description

An cdnjs.com brand icon.
<img width="143" alt="Captura de pantalla 2024-12-30 a la(s) 12 56 58 p  m" src="https://github.com/user-attachments/assets/e8bd22e4-8210-41a7-8304-7debf669d99d" />

### Official website

https://cdnjs.com/

### Brand guidelines

https://about.twitter.com/en/who-we-are/brand-toolkit

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2024-12-30 18:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14466, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-12-30 18:20 UTC
Labels: brand icon
