### ISSUE TITLE
Icon request: icon-measure

### ISSUE THREAD

**Issue by naluoli** [FortAwesome/Font-Awesome#12452] opened 2018-02-26 23:21 UTC
### What can it be used for?

Different form of measuring for clothes.  

### Example image (optional)

![image](https://user-images.githubusercontent.com/36716550/36701545-ab8ac434-1b08-11e8-83ba-d195293585ef.png)

### Icon request checklist

- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [yes ] I have included at least one example image if it could be helpful (optional)
- [ yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-02-28 13:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8437, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-28 13:30 UTC

**Comment by tagliala** [comment] 2018-02-28 13:37
May also be a duplicate of #1096

**Comment by gregschwartz** [comment] 2018-03-09 01:17
@tagliala since #8437 has been open for 2+ years, and #1096 has been open for just shy of 5 years, when is one of them going to get done?

**Comment by tagliala** [comment] 2018-03-09 09:43
@gregschwartz stay tuned, #1096 is coming 😉
