### ISSUE TITLE
Icon request: fa-measuring-tape

### ISSUE THREAD

**Issue by bclair85** [FortAwesome/Font-Awesome#9640] opened 2016-07-25 20:12 UTC
I need to see if you have a couch and measuring tape icon.  I have provided both in the attachment as pdf files I created in illustrator.  How can I make these work without bothering you? (File type and code)  Or can we add these to the library or something very similar.  Thanks Brent 

[extra icons.pdf](https://github.com/FortAwesome/Font-Awesome/files/382374/extra.icons.pdf)

**Comment by tagliala** [comment] 2016-07-25 21:40
Couch is a duplicate of #759 , please :+1: that request

Renaming and leaving this open as `fa-measuring-tape`

**Comment by aethior** [comment] 2016-07-26 01:34
@tagliala check: #8437

**Comment by tagliala** [comment] 2016-07-26 09:20
All dups, closing here.

Adding measuring-tape to #8437

**Closed by tagliala** 2016-07-26 09:20 UTC
Labels: new icon, web application icons
