### ISSUE TITLE
Icon Request: myspace

### ISSUE THREAD

**Issue by shefik** [FortAwesome/Font-Awesome#10967] opened 2017-04-19 21:14 UTC
Requesting icon for `myspace`.

**Comment by tagliala** [comment] 2017-04-19 21:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #831, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-19 21:51 UTC
