### ISSUE TITLE
Icon request: Pakistani Rupee (PKR)

### ISSUE THREAD

**Issue by ayoubkhan558** [FortAwesome/Font-Awesome#17759] opened 2021-03-22 13:31 UTC
**What can it be used for?**
We need this icon, I am developer, I have to use this in my projects. i can be used in finance apps. 

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/20210961/111996344-29463200-8ad7-11eb-802e-d78763e4ceca.png)
![image](https://user-images.githubusercontent.com/20210961/111996523-572b7680-8ad7-11eb-9a21-c13e4a1f1ec6.png)
![image](https://user-images.githubusercontent.com/20210961/111996565-627ea200-8ad7-11eb-8802-b7ff98a5daae.png)
![image](https://user-images.githubusercontent.com/20210961/111996589-6ca0a080-8ad7-11eb-8d40-7069e3875608.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-03-22 13:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16651. No need to +1 that request, PKR is already part of Font Awesome 6 (at the moment in private alpha)

**Closed by tagliala** 2021-03-22 13:54 UTC
