### ISSUE TITLE
Icon Request: fa-mouse

### ISSUE THREAD

**Issue by tsjerry** [FortAwesome/Font-Awesome#6904] opened 2015-07-09 11:42 UTC
Hi,

I'd like to see an icon of a mouse. I was searching for it but couldn't find it. I needed this in multiple projects.

Something like this:
![image](https://cloud.githubusercontent.com/assets/6928370/8594355/49b5d0ce-2640-11e5-8220-daa9f323c1cc.png)

Thanks

**Comment by tagliala** [comment] 2015-07-09 19:28
duplicate of #2376 , please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-07-09 19:28 UTC
