### ISSUE TITLE
Icon Request: icon-3d

### ISSUE THREAD

**Issue by claudiamnt** [FortAwesome/Font-Awesome#1637] opened 2013-07-23 16:28 UTC
Hi,
I'm working on a website for a company that creates app. Beside all the major social network and branded icons, there is no 3d logo icon. 
Is it possible to create one or it violates some copyright restrictions? 

Thank you

![i-card-features-3d-modelz](https://f.cloud.github.com/assets/5074533/842887/b637ef14-f3b3-11e2-915d-4054bb9df782.png)

**Comment by CurtisBelt** [comment] 2018-06-04 21:09
+1 to this, here is another use case where cube wouldn't be as intuitive
![image](https://user-images.githubusercontent.com/4251760/40941761-93b03712-6811-11e8-9ad8-020ce3b130e7.png)

**Comment by sensibleworld** [comment] 2024-07-11 16:46
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.]()

**Closed by sensibleworld** 2024-07-11 16:46 UTC
Labels: new icon, web application icons (legacy category), Duplicate
