### ISSUE TITLE
Icon Request: fa-handshake

### ISSUE THREAD

**Issue by kripotos** [FortAwesome/Font-Awesome#7900] opened 2015-11-17 16:28 UTC
represents agreements, closed deals or partners.
http://icons.iconarchive.com/icons/iconsmind/outline/512/Handshake-icon.png

**Comment by tagliala** [comment] 2015-11-17 18:15
duplicate of #878 , please +1 that request

please also search for duplicates before opening new requests

closing here

**Closed by tagliala** 2015-11-17 18:15 UTC
