### ISSUE TITLE
Icon request: fa fa-drive2

### ISSUE THREAD

**Issue by hailstrike1988** [FortAwesome/Font-Awesome#11182] opened 2017-06-15 12:12 UTC
Hello! 

Please could you add the icon for Russian/international car social network
www.drive2.ru
www.drive2.com

![2017-06-15_140442](https://user-images.githubusercontent.com/13962135/27180581-687669da-51d4-11e7-8de0-3e3f381d9f74.png)

I need to use it in my web site - www.maxtopdriver.com in Russian language section, currently icon on the button is blank...

Kind regards.

**Comment by tagliala** [comment] 2017-06-15 13:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8571, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-15 13:14 UTC
