### ISSUE TITLE
Icon request: circle-quadrant-{0-4}

### ISSUE THREAD

**Issue by RichardNeill** [FortAwesome/Font-Awesome#13075] opened 2018-05-08 19:58 UTC
### What can it be used for?

This is a circle with variously 0,1,2,3,4 quarters filled. 
It's useful for showing anything that can be divided into quarters, for example the progress of resolving a problem. 

The zeroth one could also be used for the "Earth" symbol:
 https://en.wikipedia.org/wiki/Earth_symbol
 https://en.wikipedia.org/wiki/Sun_cross#/media/File:Simple_crossed_circle.svg

[Although I am only requesting the set of 5 (or 4, if you consider that "circle" already exists), there might also be a good case to make some other variants, notably both with and without the crossed lines; a 2/4 filled in opposing quadrants, and maybe a version with 1/3 or 1/8s.]

### Example image (optional)

Here are some examples - we already use these as svgs, but it would be great if they were part of F-A. Please feel free to use or modify these images themselves - we made them, and I release them into the public domain.  

I've uploaded 5 previews as PNG, as well as a zip file that contains SVGs 
[circles.zip](https://github.com/FortAwesome/Font-Awesome/files/1985419/circles.zip)
![three-quarters](https://user-images.githubusercontent.com/556337/39779334-d39d8f3a-5300-11e8-9485-ef74e7ea9df1.png)
![one-quarter](https://user-images.githubusercontent.com/556337/39779335-d3c58b98-5300-11e8-85af-c16895613b4c.png)
![half](https://user-images.githubusercontent.com/556337/39779336-d3e60594-5300-11e8-9af6-3d51bd70f6eb.png)
![full](https://user-images.githubusercontent.com/556337/39779337-d4058874-5300-11e8-96db-5d5f5d75f7ad.png)
![empty](https://user-images.githubusercontent.com/556337/39779339-d43acf98-5300-11e8-85b9-834287d0c6a6.png)

### Icon request checklist

* This is a matched set of 5.
* Yes, to the remaining checklist items.

Thank you very much :-)

**Comment by tagliala** [comment] 2018-05-09 09:50
Hi!

Thanks for being part of the Font Awesome Community.

I thinks this is a possible duplicate of #1789

**Comment by RichardNeill** [comment] 2018-05-09 18:42
Thanks. This is _almost_  a duplicate. #1789 is asking for the circle sectors; I'm looking for ones with the quadrants drawn in. Thank you :-)

**Comment by sensibleworld** [comment] 2022-03-15 00:49
https://fontawesome.com/icons/circle-half?s=solid
https://fontawesome.com/icons/circle-quarter?s=solid
https://fontawesome.com/icons/circle-three-quarters?s=solid
https://fontawesome.com/icons/circle?s=solid

**Closed by sensibleworld** 2022-03-15 00:49 UTC
Labels: new icon, web application icons
