### ISSUE TITLE
Icon request: fab fa-bootstrap

### ISSUE THREAD

**Issue by ratajs** [FortAwesome/Font-Awesome#13059] opened 2018-05-07 18:03 UTC
Please, can you add a Bootstrap icon to brands icons.
Here is original icon:

![](http://getbootstrap.com/docs/4.1/assets/img/favicons/apple-touch-icon.png)

Thank you

**Comment by tagliala** [comment] 2018-05-07 18:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1828, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-07 18:27 UTC
