### ISSUE TITLE
Icon Request: fa-acorn

### ISSUE THREAD

**Issue by mfrntic** [FortAwesome/Font-Awesome#7642] opened 2015-10-08 21:24 UTC
Please if you can add icon of acorn (oak nut)...

Something like this:
![icon](https://cloud.githubusercontent.com/assets/6986779/10380313/6b35759a-6e13-11e5-831d-2b53b5608dbc.png)
![25960-200](https://cloud.githubusercontent.com/assets/6986779/10380317/6f8210a4-6e13-11e5-9a76-92b2c81a986b.png)
![34981-200](https://cloud.githubusercontent.com/assets/6986779/10380319/72a2724c-6e13-11e5-84ba-e31df0a5998a.png)
![18092-200](https://cloud.githubusercontent.com/assets/6986779/10380327/81a8a19e-6e13-11e5-8d18-97ab176549f1.png)

Thanks for Font-Awsome

**Comment by caduvieira** [comment] 2015-10-09 17:18
dupe of #7493 
please +1 that one

**Comment by tagliala** [comment] 2015-10-10 19:06
edited #7493 to include acorn in the title

**Closed** 2015-10-10 19:05 UTC
