### ISSUE TITLE
Icon Request: Wikipedia

### ISSUE THREAD

**Issue by wmsrichard** [FortAwesome/Font-Awesome#6924] opened 2015-07-10 15:36 UTC
A Wikipedia icon would be awesome! For us people who still reference Wikipedia in our existing sites.

**Comment by QuincyLarson** [comment] 2015-07-11 17:44
+1

**Comment by tagliala** [comment] 2015-07-12 19:12
duplicate of #388 , please +1 that request

closing here

**Closed by tagliala** 2015-07-12 19:12 UTC
