### ISSUE TITLE
Icon request: icon-storify

### ISSUE THREAD

**Issue by MarieLSJ** [FortAwesome/Font-Awesome#11643] opened 2017-10-18 04:09 UTC
Hi! I was wondering if there could be a Storify icon to link to our Storify accounts on websites designed with Hugo? It could be also used in news articles to link to a Storify story.

Here's the icon: 
![image](https://user-images.githubusercontent.com/32890656/31700602-82d6d384-b398-11e7-8b38-a329331b6a65.png)

Here's my [Storify account](https://storify.com/Marie_LSJ).

Thanks!

**Comment by tagliala** [comment] 2017-10-18 08:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1235 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-18 08:25 UTC
