### ISSUE TITLE
Icon request: icon-sf

### ISSUE THREAD

**Issue by ili-codes** [FortAwesome/Font-Awesome#9348] opened 2016-06-06 13:27 UTC
Brand Icons: SourceForge

model after:
![sf](http://ili-codes.github.io/assets/css/images/sf_icon.png)
http://ili-codes.github.io/assets/css/images/sf_icon.png

**Comment by aethior** [comment] 2016-06-06 13:52
Hi @ili-codes,

This request is duplicate of #1178. Please +1 that.

Regards.

**Comment by ili-codes** [comment] 2016-06-06 18:28
No problem.

**Comment by tagliala** [comment] 2016-06-06 19:39
closing here

**Closed by tagliala** 2016-06-06 19:39 UTC
