### ISSUE TITLE
Icon request: fa-flask

### ISSUE THREAD

**Issue by DogukanUrker** [FortAwesome/Font-Awesome#19567] opened 2023-02-17 18:07 UTC
Why not make a Flask logo? (web framework)
![png-transparent-flask-python-bottle-web-framework-web-application-flask-white-monochrome-shoe](https://user-images.githubusercontent.com/62756402/219742406-3705ec7a-8fb5-43cf-906e-1d59f5db93c6.png)

**Comment by tagliala** [comment] 2023-02-17 19:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15092, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-02-17 19:00 UTC
