### ISSUE TITLE
Icon Request: fa-degree

### ISSUE THREAD

**Issue by madhanan** [FortAwesome/Font-Awesome#9292] opened 2016-05-28 20:17 UTC
A Degree is like a Graduation Degree Certificate, Technical Certifications Etc,

I plan on using them for my Portfolio, where i have a list of certification like Windows Certification, Redhat Certification, College Degree etc..

It would be Helpful if u guys could develop some

![icon](https://cloud.githubusercontent.com/assets/19624958/15629768/4cf46ac6-253f-11e6-8f50-4fee6f1b0580.png)

**Comment by tagliala** [comment] 2016-05-28 23:12
I'm going to consider this a duplicate of #4420 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-28 23:12 UTC
