### ISSUE TITLE
Icon request: TypeScript

### ISSUE THREAD

**Issue by Abhi1234-tech** [FortAwesome/Font-Awesome#19877] opened 2023-08-27 09:02 UTC
### Use case

**Description:**
TypeScript is an open-source programming language developed by Microsoft. It is a strict syntactical superset of JavaScript, which means that any valid JavaScript code is also valid TypeScript code.

**Official website:**
[https://www.typescriptlang.org/](https://www.typescriptlang.org/)

### Example image

![image](https://github.com/FortAwesome/Font-Awesome/assets/64825778/52b2eec7-8516-427b-9b4f-cf0e56448c05)

**Figma link:**
[https://www.figma.com/file/Klc428B0DjubAlmu2GbR32/Untitled?type=design&node-id=0%3A1&mode=design&t=6MynGjZygpmjd4Kq-1](https://www.figma.com/file/Klc428B0DjubAlmu2GbR32/Untitled?type=design&node-id=0%3A1&mode=design&t=6MynGjZygpmjd4Kq-1)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2023-08-27 09:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11890, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-08-27 09:16 UTC
Labels: new icon
