### ISSUE TITLE
Icon request: icon-unpinned

### ISSUE THREAD

**Issue by pingouin-creation** [FortAwesome/Font-Awesome#7831] opened 2015-11-05 15:40 UTC
I think an unpinned icon cool be useful to delete pinned font in an application. As a done icon for those icon a join ta jpg...

I just took thing that already existed to create these...I think that the X version is better

![unpinned](https://cloud.githubusercontent.com/assets/11234064/10972946/7cb651ee-83a9-11e5-9dc7-cadbeef3555b.jpg)

**Comment by tagliala** [comment] 2015-11-13 21:13
refers to #1181, you will find a solution there

**Comment by sensibleworld** [comment] 2024-07-10 21:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/10749)

**Closed by sensibleworld** 2024-07-10 21:33 UTC
Labels: new icon, web application icons (legacy category), Duplicate
