### ISSUE TITLE
Icon request: fa-kakaostory

### ISSUE THREAD

**Issue by parksunghoons** [FortAwesome/Font-Awesome#10370] opened 2016-12-15 03:34 UTC
https://developers.kakao.com/assets/img/about/buttons/kakaostory/icon/flat/kakaostory_icon_flat_512x512.png

I need it desperately.

**Comment by tagliala** [comment] 2016-12-15 10:52
Duplicate of #6669, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

@parksunghoons that request has very few upvotes, I should advise you to consider a [custom build](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome) if you need this icon in a short while

Closing here

**Closed by tagliala** 2016-12-15 10:52 UTC
