### ISSUE TITLE
Icon request: scoop.it

### ISSUE THREAD

**Issue by CelebxxCom** [FortAwesome/Font-Awesome#16016] opened 2020-01-04 17:40 UTC
https://www.scoop.it site icon

**Comment by tagliala** [comment] 2020-01-04 20:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1603, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-04 20:06 UTC
