### ISSUE TITLE
Icon request: sneaker

### ISSUE THREAD

**Issue by Schokobecher** [FortAwesome/Font-Awesome#15765] opened 2019-11-02 07:28 UTC
**What can it be used for?**
A great addition to sites, where the 'boot' is not relevant.
Examples would be eCommerce sites, fashion blogs or similar cloth-oriented sites.

**Example image (optional)**
An example would be [this - credits @ Gadeno Team](https://thenounproject.com/search/?q=sneaker&i=438888)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-11-05 20:50
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #6031 , please add a 👍 reaction to that request.

When a generic shoe will be added to the set, feel free to open a new request if that design does not fit the sneaker use case

May also refer to #3704 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-11-05 20:50 UTC
