### ISSUE TITLE
Icon Request: fa-trakt

### ISSUE THREAD

**Issue by ilumire** [FortAwesome/Font-Awesome#10514] opened 2017-01-12 02:04 UTC
Hello,

I would like to see the icon for [Trakt](trakt.tv) which tracks the TV series and movies you watch. On the website users have their own profile page and I think it would be lovely if one could add the Trakt icon to link to their page from a blog or the like as a social network link.

Thank you!

**Comment by tagliala** [comment] 2017-01-12 10:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2480, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-12 10:15 UTC
