### ISSUE TITLE
Icon Request: fa-bar-line

### ISSUE THREAD

**Issue by matet91** [FortAwesome/Font-Awesome#9714] opened 2016-08-08 02:30 UTC
Hi Fontawesome team,

First of all I'd like to introduce myself, I'm matet from philippines a web developer.

 I'd like to request for a new icon to be added, below is the svg of the bar-line icon: (I do not own this svg. Just got it from my colleague). 
`<svg width="32px" height="32px" viewBox="0 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
    <title>chart-bar-line</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Icons" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
        <g id="chart-bar-line" sketch:type="MSArtboardGroup">
            <rect id="Rectangle-18" fill="#333333" sketch:type="MSShapeGroup" x="5" y="22" width="4" height="5"></rect>
            <rect id="Rectangle-19" fill="#333333" sketch:type="MSShapeGroup" x="11" y="18" width="4" height="9"></rect>
            <rect id="Rectangle-20" fill="#333333" sketch:type="MSShapeGroup" x="17" y="21" width="4" height="6"></rect>
            <rect id="Rectangle-21" fill="#333333" sketch:type="MSShapeGroup" x="23" y="14" width="4" height="13"></rect>
            <path d="M5,17 L9.48480008,13.5239296 C10.3556354,12.8489642 11.8249452,12.7700046 12.7699011,13.3495961 L14.5267085,14.4271392 C15.4701844,15.0058229 16.9228239,14.9106131 17.7804648,14.2069379 L27.783098,6" id="Path-404" stroke="#333333" stroke-width="2" stroke-linecap="round" sketch:type="MSShapeGroup"></path>
        </g>
    </g>
</svg>`

Thank you!
P.S. I'm an avid fan of your font-awesome icons project. I've been using it more than a year now. 

Best Regards,

Matet

**Comment by tagliala** [comment] 2016-08-08 09:13
Duplicate of #6881, please add a 👍  reaction to that request

Please post your svg there

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-08 09:13 UTC
