### ISSUE TITLE
Icon Request: fa-breakfast

### ISSUE THREAD

**Issue by tzeller** [FortAwesome/Font-Awesome#11596] opened 2017-10-07 12:41 UTC
there is hardly anything for the restaurant industry in the icon set.[
[fa-breakfast.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364613/fa-breakfast.pdf)

](url)

**Comment by tagliala** [comment] 2017-10-07 12:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5304 , please add a 👍  reaction to that request.

Also: breakfast is culture-dependent. The icon actually represents an egg, please make sure to request concrete objects

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-07 12:53 UTC
