### ISSUE TITLE
Mailchimp icon

### ISSUE THREAD

**Issue by argoncobalt** [FortAwesome/Font-Awesome#12737] opened 2018-03-29 19:51 UTC
Putting in a request for a Mailchimp icon; would definitely use if you had it. Thanks!

**Comment by tagliala** [comment] 2018-04-06 09:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3379, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 09:38 UTC
