### ISSUE TITLE
Icon request: icon-call-center

### ISSUE THREAD

**Issue by lucasroselli** [FortAwesome/Font-Awesome#7282] opened 2015-08-21 19:24 UTC
![images 1](https://cloud.githubusercontent.com/assets/10927890/9417321/ac1aabb0-4821-11e5-9928-00cb71326e51.png)
![Uploading images.png…]()

First: Congrats for the awesome work!

Second: Is it possible to create a icon for call center ?

Thank you!!

**Comment by TheChen5** [comment] 2015-08-21 22:04
Dupe of #5586 
+1 that

**Comment by tagliala** [comment] 2015-08-22 09:30
Closing here

**Comment by tagliala** [comment] 2015-08-22 09:30
@lucasroselli please also post there your example

**Closed by tagliala** 2015-08-22 09:30 UTC
