### ISSUE TITLE
Icon request: Icon-square-compass

### ISSUE THREAD

**Issue by ogre14t** [FortAwesome/Font-Awesome#10555] opened 2017-01-24 02:05 UTC
I am working on a couple different masonic projects and it would be awesome to have a g-square-compass icon. something similar to: http://www.masonicexchange.com/assets/images/TME-EMB-D-01049.jpg

**Comment by tagliala** [comment] 2017-01-24 11:22
Is this a duplicate of #6264?

**Comment by ogre14t** [comment] 2017-01-24 13:41
No

**Comment by tagliala** [comment] 2017-01-24 13:52
@ogre14t could upu please elaborate why?

The other issue says: "I'd like to suggest that we create an icon for the masonic symbol of the square and compasses.", this one has `Icon request: Icon-square-compass` title.

I would like to understand why they are different and the different use cases, so I can properly manage this request

Thanks

**Comment by tagliala** [comment] 2017-03-01 11:56
No feedback, closing here

**Closed by tagliala** 2017-03-01 11:56 UTC

**Comment by T3chnician** [comment] 2018-11-06 21:31
It is the same @tagliala
