### ISSUE TITLE
Icon request: icon-viadeo

### ISSUE THREAD

**Issue by R-Cal1** [FortAwesome/Font-Awesome#8710] opened 2016-03-07 16:49 UTC
Dear Font awesome community,

I would like to request the adding of the professional social media "Viadeo" icon.
Viadeo is a french professionnal social media like Linkedin. It could be used asother social media icons for example on a CV or websites.

Link : http://www.viadeo.com/

You will find below the logo of viadeo found on the net.

![picto_viadeo](https://cloud.githubusercontent.com/assets/17707525/13576161/9142b816-e48c-11e5-92d8-716490bf21f0.png)

Thank you in advance for your time

Best regards

**Comment by tagliala** [comment] 2016-03-07 18:02
duplicate of #886 , please +1 that request

closing here

**Closed by tagliala** 2016-03-07 18:02 UTC
