### ISSUE TITLE
Icon Request: Market Stall

### ISSUE THREAD

**Issue by woisme** [FortAwesome/Font-Awesome#5981] opened 2015-03-16 17:58 UTC
Creating a festival site. Would love a market stall. Would also be good for business sites.

**Comment by dngunraj** [comment] 2015-03-26 20:26
+1

**Comment by wael101** [comment] 2015-08-07 20:36
+1

**Comment by rwb196884** [comment] 2017-07-13 10:35
+1

e.g.,
![market](https://user-images.githubusercontent.com/12090617/28162531-5063b338-67bf-11e7-86b7-f32607c3752d.PNG)

**Comment by aethior** [comment] 2022-02-28 02:17
Hi @woisme,

This icon was added in v5.0.13.
Check https://fontawesome.com/icons/store

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-02-28 09:58
Ok thanks, this was a duplicate of #1958

**Closed by tagliala** 2022-02-28 09:58 UTC
Labels: new icon, web application icons
