### ISSUE TITLE
Icon-request: icon-brain

### ISSUE THREAD

**Issue by adibalcan** [FortAwesome/Font-Awesome#12234] opened 2018-02-03 10:15 UTC
Hello,
I am searching for a brain icon, I think it's a good opportunity for FA to include such icon. @

**Comment by tagliala** [comment] 2018-02-03 11:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2075 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-03 11:38 UTC
