### ISSUE TITLE
Icon request: square-half-stroke & square-half-stroke-diagonal

### ISSUE THREAD

**Issue by 1-0-1** [FortAwesome/Font-Awesome#19196] opened 2022-07-18 14:23 UTC
### Use case

As a developer I want some way to show that there is a mixture of available values in a group.  If all values are available I can use the solid square.  If no values are selected I can use the empty square.  If there are a mix, I would like a "half-stroke" square to use similar to the "circle-half-stroke".  Since the circle I can rotate to 45deg, there would need to also be a diagonal half-stroke for the square.

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by Pukimaa** [comment] 2022-07-21 09:13
That would be nice to see. Some people maybe have a more square-ish look instead of a cicular one so it would make sense to use a square there too.

**Comment by sensibleworld** [comment] 2024-07-11 15:10
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7961)

**Closed as completed by sensibleworld** 2024-07-11 15:10 UTC
Labels: new icon, shapes (category), Duplicate
