### ISSUE TITLE
Icon request: icon-houses

### ISSUE THREAD

**Issue by justindra** [FortAwesome/Font-Awesome#9506] opened 2016-07-01 05:07 UTC
Just like `fa-home` but multiples of it?

Similar to how `fa-users` is to `fa-user`

**Comment by tagliala** [comment] 2016-07-01 08:55
Duplicate of #9367, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-01 08:55 UTC
