### ISSUE TITLE
Icon Request: fa-icon-certificate

### ISSUE THREAD

**Issue by ydamani** [FortAwesome/Font-Awesome#12296] opened 2018-02-08 19:47 UTC
Thank you for the awesome library.

I am in need of this icon since long time. I work on an app where people renew their certificates. Current certificate icon available in font-awesome looks more like a seal (seal on a certificate or a letter). I would really like to see a certificate icon that has a page with text and seal (as provided below).

Please let me know if I can help on it.

![certificate](https://user-images.githubusercontent.com/27693441/35994458-5df55d02-0cc5-11e8-8a01-0fe21516b7d1.png)

**Comment by tagliala** [comment] 2018-02-09 10:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4420 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-09 10:56 UTC
