### ISSUE TITLE
horizontal scrollbar is shown on the icon pages for free users

### ISSUE THREAD

**Issue by harindersinghpanesar** [FortAwesome/Font-Awesome#12362] opened 2018-02-15 08:18 UTC
your website have scroll that is not good

**Comment by tagliala** [comment] 2018-02-15 09:58
Hi!

Thanks for being part of the Font Awesome Community.

You mean that the website is slow?

**Comment by C-Lodder** [comment] 2018-02-15 15:39
@tagliala I think he means the infinite scroll on the Icons page (https://fontawesome.com/icons?d=gallery)

Meaning you cannot access the footer on this page until you've scrolled through all icons

**Comment by harindersinghpanesar** [comment] 2018-02-16 05:57
when we going to icon page bottom have scroll

**Comment by harindersinghpanesar** [comment] 2018-02-16 05:58
that is another issue
my mean to say icon page desktop view bottom scroll

**Comment by tagliala** [comment] 2018-02-16 10:01
@harindersinghpanesar sorry, I'm still having troubles to understand the issue

Are you able to provide a screencast?

**Comment by C-Lodder** [comment] 2018-02-16 10:04
@tagliala I explained here: https://github.com/FortAwesome/Font-Awesome/issues/12362#issuecomment-365965289

1. Go to the link
2. Scroll to the footer
3. Notice you cannot access anything on the footer because it's an infinite scroll

**Comment by tagliala** [comment] 2018-02-16 10:08
thanks @C-Lodder , I just want to make sure about that. In that case, the issue is related to just one page and I will fix the title and the description of the issue. Also, I need another label (enhanchement, rather than bug)

@harindersinghpanesar could you please confirm that the issue explained by @C-Lodder is your issue?

**Comment by harindersinghpanesar** [comment] 2018-02-19 05:02
plz see bottom scrool
[image: Inline image 1]

**Comment by tagliala** [comment] 2018-02-19 11:36
@harindersinghpanesar please post images at https://github.com/FortAwesome/Font-Awesome/issues/12362, email attachment don't work

**Comment by harindersinghpanesar** [comment] 2018-02-19 11:39
![image](https://user-images.githubusercontent.com/36499928/36376001-9896ce98-1597-11e8-86db-d0275433fb97.png)

**Comment by tagliala** [comment] 2018-02-19 11:46
Ok.

@harindersinghpanesar you mean that you see a horizontal scrollbar on the bottom of the page?

If yes, I was finally able to understand and replicate.

I couldn't reproduce because it is caused by the advertisement

**Comment by tagliala** [comment] 2018-02-19 12:18
@talbs please take a look here.

I'm able to reproduce on Chrome 64 / Win 10

I'm pretty confident the issue is the "PRO" label added on the top right corner of the icons:

![image](https://user-images.githubusercontent.com/556268/36376772-aa6bd7e4-1574-11e8-9fc8-7cab4ad065a5.png)

**Comment by harindersinghpanesar** [comment] 2018-02-19 13:00
but this page no advertisement

**Comment by tagliala** [comment] 2018-02-19 14:20
@harindersinghpanesar yes, I've found the issue and edited my comment but you can't see edits via e-mail.

Thanks for reporting.

**Comment by harindersinghpanesar** [comment] 2018-02-20 05:35
welcome no problem

**Comment by tagliala** [comment] 2018-02-20 11:44
@talbs more information:

the issue is caused by the tooltip attached to the PRO label. You can see the scrollbar disappear by running

```js
document.styleSheets[0].insertRule('span[data-balloon="Pro license required"] { display: none !important; }')
```

on the development console.

I don't know if there is a fast fix for this, the library used for tooltips doesn't seem to allow an `auto` position

A workaround is to set `overflow: hidden` on the `#search-results` `main` tag. Of course, this will cut tooltips

Hope it helps

**Comment by harindersinghpanesar** [comment] 2018-02-21 07:39
hey bro Give the css to the body tag
overflow:hidden;
and thats fix the issue

**Comment by harindersinghpanesar** [comment] 2018-02-21 07:41
.static-l {
overflow:hidden;
}
and fix the issue

**Comment by robmadole** [comment] 2018-02-26 15:30
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/FortAwesome/Font-Awesome/issues/12362](https://trello.com/c/zVu59F28/40-https-githubcom-fortawesome-font-awesome-issues-12362)

**Comment by talbs** [comment] 2018-06-21 20:22
Sorry for the radio silence, gang. This was fixed a while back and there should be no horizontal scrollbars rendered while viewing our icons listing (https://fontawesome.com/icons?d=gallery).

**Closed by talbs** 2018-06-21 20:22 UTC
Labels: bug, doc
