### ISSUE TITLE
Icon Request: fa-photobucket

### ISSUE THREAD

**Issue by oil4lessllc** [FortAwesome/Font-Awesome#10232] opened 2016-11-16 06:42 UTC
Thanks!

**Comment by tagliala** [comment] 2016-11-16 10:23
Duplicate of #5144, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-16 10:23 UTC
