### ISSUE TITLE
Ditch the "CDN" approach using JavaScript

### ISSUE THREAD

**Issue by spdustin** [FortAwesome/Font-Awesome#9332] opened 2016-06-03 17:42 UTC
This feels like a really dirty trick, getting rid of the CSS-only version. There's *no* reason users should run arbitrary JavaScript just for some CSS, but you're almost forcing them to by making less-experienced developers go down the path of using JavaScript to use Font Awesome. And let's be honest here - it's not to serve the users, it's to associate e-mail addresses with web sites, that's what you get when you generate unique embed codes and require an e-mail address to do so.

The original CSS should be the first option. THEN the "custom build" JS option. Maybe. But that option feels like a dirty, dirty trick to me, and you just lost my trust by dropping the change with no fanfare and a hand-wavy "hey buddy, this is better".

**Comment by walchko** [comment] 2016-06-04 17:13
Not sure I understand why you did this ... I liked the ability to call a CDN and get the fonts. Why should I give you an email address to get the same thing I use to get without an email address? If you are just trying to make money or track usage or something else, then be honest and say so. Your statement about it being easier doesn't make sense to me. Upgrading without changing code isn't a big selling point, when I have to change my code just to use new icons in the upgrade.

**Comment by tagliala** [comment] 2016-06-04 20:15
I do agree. But this is a duplicate of #9245, please share there your thoughts

**Closed by tagliala** 2016-06-04 20:15 UTC
