### ISSUE TITLE
Icon request: browser

### ISSUE THREAD

**Issue by om19** [FortAwesome/Font-Awesome#5381] opened 2015-01-13 03:56 UTC
A browser icon can represent: browser , website
![image](https://cloud.githubusercontent.com/assets/10509620/5715829/2dc98cc6-9b1b-11e4-831e-8e6a4e7eb596.png)

**Comment by tagliala** [comment] 2015-01-13 11:58
this is a duplicate of #1192

But I think icon-globe or #2655 are better to represent a website

closing here

**Closed by tagliala** 2015-01-13 11:58 UTC
