### ISSUE TITLE
Icon Request: fa-taobao

### ISSUE THREAD

**Issue by refugeesidhar** [FortAwesome/Font-Awesome#12407] opened 2018-02-21 08:45 UTC
I'd like to make a formal request for an icon depticting the Taobao logo.  It's the major Chinese e-sales platform.  I've attached an image of their logo/icon to help.  Thanks for making such an amazing product.  We love it!

![taobao](https://user-images.githubusercontent.com/13744887/36470571-4001c5c2-1726-11e8-8de0-b845838840b5.png)

**Comment by tagliala** [comment] 2018-02-21 19:18
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3856 and/or #4600, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-21 19:18 UTC
