### ISSUE TITLE
Icon Request: fa-color

### ISSUE THREAD

**Issue by Denni007** [FortAwesome/Font-Awesome#6624] opened 2015-06-02 11:39 UTC
e. g.
![image](https://cloud.githubusercontent.com/assets/6861243/7934973/ce1cac06-092c-11e5-8acb-364b3406d3ac.png)

**Comment by kwendenarmo** [comment] 2015-06-03 17:56
+1

**Comment by tagliala** [comment] 2015-06-03 20:56
duplicate of #244 , please +1 that request

closing here

**Closed by tagliala** 2015-06-03 20:56 UTC
