### ISSUE TITLE
Icon request: icon-bridge

### ISSUE THREAD

**Issue by iRonMrx** [FortAwesome/Font-Awesome#11061] opened 2017-05-14 21:20 UTC
In the real world, bridges that span water and chasms abound. So too in the digital world, especially as navigational cues and, as an instructional course designer, for some of our b-r-i-d-g-e related acronyms for pedagogical strategies.

I'm hoping that several icons with a bridge theme can be created, especially ones that have received attention from engineers and architects around the world.

Examples:
Arched: https://en.wikipedia.org/wiki/List_of_longest_arch_bridge_spans
Suspension: https://en.wikipedia.org/wiki/List_of_longest_suspension_bridge_spans
Tallest in world: https://en.wikipedia.org/wiki/Millau_Viaduct
Sources of national pride: https://www.europeanbestdestinations.com/top/most-beautiful-bridges-in-europe/

**Comment by tagliala** [comment] 2017-05-14 22:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4053, please add a 👍 reaction to that request.

If you are requesting landmarks, they are out of scope (ref: #2661).
If you are request different type of bridges, please make a new request but make sure it meets our [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

Please also make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-14 22:27 UTC

**Comment by iRonMrx** [comment] 2017-05-15 04:00
Thank you, Geremia, for the quick response. I did search for "bridge" before posting, but received a null response. I particularly like the landmark reference too. Maybe we'll see a few of these landmark/geographic icons in FontAwesome in the near future?
