### ISSUE TITLE
 Icon request: Viber Icon

### ISSUE THREAD

**Issue by ShellyViber** [FortAwesome/Font-Awesome#11525] opened 2017-09-14 09:03 UTC
Hello,

I was hoping that you can add a Viber Messenger icon for Font Awesome. We use your font in our new site (still not released) and the only icon we're missing is actually our own company's.

The icon will also be used by us in web designs and client designs, by our bot and Public Account partners and will save our partners and developers a lot of time :)

Btw, I found support in your font for the old Viber icon:
https://github.com/kukac7/fa-viber
http://kukac7.github.io/fa-viber/

attaching our icon. Please let me know if you need another file to make this happen.
[Viber.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/1302418/Viber.svg.zip)

**Comment by tagliala** [comment] 2017-09-14 09:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3554 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-14 09:44 UTC
