### ISSUE TITLE
Icon request: troll-face

### ISSUE THREAD

**Issue by hopeiessdespair** [FortAwesome/Font-Awesome#18594] opened 2022-01-17 16:51 UTC
i think this icon could be used for fun or gaming, like the awesomeface icon!

i mean... it's the trollface. 
![image](https://user-images.githubusercontent.com/89989086/149809638-e90ccbad-00fd-4002-a391-d33e68c5ea5e.png)

**Comment by tagliala** [comment] 2022-01-17 16:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7937, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-01-17 16:55 UTC
