### ISSUE TITLE
Icon Request: fa-infinity

### ISSUE THREAD

**Issue by sweettimes** [FortAwesome/Font-Awesome#7139] opened 2015-08-05 00:17 UTC
Hey FontAwesome, I need an icon infinity but its not have in list.
I use it for "Unlimited" in hosting space / bandwidth properties
Here its icon of infinity
![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313937393038372f3835353734332f36393834636230322d663532652d313165322d393736622d3062386637633565656464362e6a7067](https://cloud.githubusercontent.com/assets/566289/9075693/00116dd6-3b42-11e5-8a4c-2bf9400b1419.jpg)

**Comment by TheChen5** [comment] 2015-08-05 01:18
Dupe of #1647
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-05 07:45
@TheChen5 thanks

**Closed by tagliala** 2015-08-05 07:45 UTC
