### ISSUE TITLE
Icon request: icon-imdb

### ISSUE THREAD

**Issue by bilski** [FortAwesome/Font-Awesome#9378] opened 2016-06-09 11:31 UTC
Hi,

Would it be possible for somebody to add an imdb icon to the set please?
I use it to link to my imdb page.

Cheers,

Bilski

Example:

![imdb-128-black](https://cloud.githubusercontent.com/assets/19836761/15928296/74023d16-2e89-11e6-8f4d-b753bf87bd31.png)

**Comment by tagliala** [comment] 2016-06-09 12:43
Duplicate of #998 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-09 12:43 UTC
