### ISSUE TITLE
Icon Request: fa-hierarchical-tree

### ISSUE THREAD

**Issue by thiazzz** [FortAwesome/Font-Awesome#7647] opened 2015-10-09 15:29 UTC
Useful for tree structures on websites or apps

**Comment by thiazzz** [comment] 2015-10-09 17:26
Something like:
https://www.iconfinder.com/search/?q=tree%20structure

Or 
http://thumb1.shutterstock.com/display_pic_with_logo/1510835/244518214/stock-vector-tree-structure-hierarchy-icon-simple-flat-style-vector-illustration-244518214.jpg

**Comment by thiazzz** [comment] 2015-10-09 17:27
First one like this
https://cdn4.iconfinder.com/data/icons/line-system/512/file_system-512.png

**Comment by tagliala** [comment] 2015-10-10 19:02
almost a duplicate of #1343 , duplicate of #2752

closing here, please +1 the above requests

**Closed by tagliala** 2015-10-10 19:02 UTC
