### ISSUE TITLE
Icon request: configuration-document

### ISSUE THREAD

**Issue by hoeneste** [FortAwesome/Font-Awesome#15541] opened 2019-09-16 13:14 UTC
**What can it be used for?**
To access document configuration in an app.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/3438198/64960669-04468280-d894-11e9-8791-abffd9f020de.png)

**Icon request checklist**
- [x] single
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-09-16 19:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14764, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Please also take a look here: https://github.com/FortAwesome/Font-Awesome/issues/14764#issuecomment-473466206


Closing here

**Closed by tagliala** 2019-09-16 19:38 UTC
