### ISSUE TITLE
Icon Request: flutter

### ISSUE THREAD

**Issue by craftedcodes** [FortAwesome/Font-Awesome#17827] opened 2021-04-18 12:46 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
It can be used for app developers (and in the future web developers) to represent the coding framework they know and can code.

**Example image (optional)**
Insert the example image here if necessary.
Here is a link to the example image: https://alexisvt.gallerycdn.vsassets.io/extensions/alexisvt/flutter-snippets/0.0.2/1529817162825/Microsoft.VisualStudio.Services.Icons.Default

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-04-18 14:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14878, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-04-18 14:00 UTC
