### ISSUE TITLE
Icon Request: fa-iframe

### ISSUE THREAD

**Issue by Denni007** [FortAwesome/Font-Awesome#6615] opened 2015-06-01 13:10 UTC
To show an iframe or external webpage

**Comment by tagliala** [comment] 2015-06-01 20:05
any example?

**Comment by Denni007** [comment] 2015-06-02 06:48
Something like 
![icon-iframe](https://cloud.githubusercontent.com/assets/6861243/7929963/1b779ade-0904-11e5-8174-1b1f7cb1d2d9.png)

**Comment by Denni007** [comment] 2015-06-08 07:59
https://www.iconfinder.com/icons/413478/webpage_icon#size=512

**Comment by ShamanFromSiberia** [comment] 2015-07-01 07:48
+1

**Comment by tagliala** [comment] 2015-07-01 10:28
so this is a duplicate of #3585, please +1 that request

closing here

**Closed by tagliala** 2015-07-01 10:28 UTC
Labels: waiting for feedback
