### ISSUE TITLE
Icon request: fa-profile-card

### ISSUE THREAD

**Issue by udarts** [FortAwesome/Font-Awesome#7581] opened 2015-10-01 07:46 UTC
Would be nice to have the following as icon :)
![laat-u-beoordelen-tippen-en-contacten](https://cloud.githubusercontent.com/assets/11528890/10215372/3fb9001e-6821-11e5-8990-8d12bd18aef0.png)

**Comment by caduvieira** [comment] 2015-10-01 11:50
dupe of  #825 or #7157?

**Closed** 2015-10-01 11:53 UTC
