### ISSUE TITLE
Icons on http://fontawesome.io/icons/ website too small

### ISSUE THREAD

**Issue by COLABORATI** [FortAwesome/Font-Awesome#9790] opened 2016-08-23 09:37 UTC
I do not get it - why are the icons on the main presentation website so extremely small? I have to zoom up to bizarr 200% to see some details. Why?

**Comment by tagliala** [comment] 2016-08-23 09:45
Duplicate of #1793 

IIRC, dave prefers this layout

**Closed by tagliala** 2016-08-23 09:45 UTC
