### ISSUE TITLE
Icon request: fa-hashnode

### ISSUE THREAD

**Issue by BharatKammakatla** [FortAwesome/Font-Awesome#17070] opened 2020-08-24 03:49 UTC
**What can it be used for?**
Hashnode([https://hashnode.com](https://hashnode.com)) is a fastly developing blogging website in recent times. This icon can be used in portfolio websites, social networking sites, and in other various development areas.

**Example image (optional)**
![scHk9tTaA](https://user-images.githubusercontent.com/28840761/91001948-c9021700-e5ff-11ea-8d9e-0a00ab6d66a9.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-08-25 19:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10437, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-08-25 19:43 UTC
