### ISSUE TITLE
Icon request: icon-sunglasses

### ISSUE THREAD

**Issue by pepperstreet** [FortAwesome/Font-Awesome#2133] opened 2013-10-10 22:09 UTC
Hello, here is a gently request for a **new icon** that may represent the following attributes and statuses:
- **hidden**
- **not seen/invisible**
- **private**

It might also serve as an alternative for the "closed eye" icon. IMHO, its strike-through style is hard to read and distinguish from the normal eye icon. Especially in smaller sizes. I did a closer request with ideas over here #2132 

Suggestions / Design:
**A.) sun glasses** (filled binocular, rounded or squared?)
**B.) regular glasses** (binocular clear/contour as a direct counterpart: visible, public)

Thanks for listening.
If there is any free-time, I would really like to contribute something on my own! Cross my finders... otherwise, any help is much appreciated.

**Comment by mariegithub** [comment] 2015-09-08 08:57
+1

**Comment by mike-stumpf** [comment] 2015-12-23 17:42
+1

**Comment by irthos** [comment] 2016-01-02 21:57
+1

**Comment by codynguyen1116** [comment] 2016-01-02 22:07
+1

**Comment by frostbitten** [comment] 2016-05-18 10:30
+1
## Sunglasses = Cool
Nothing signifys **cool** better than a pair of sunglasses. :sunglasses:
That is, at least in the world of _visual metaphors_.

Re: visibility/privacy, I'm satisfied with the `eye` and `eye-slash` and the `lock`'s. These work best in conjunction with additional visual ques, such as a lighter color for disabled text.

**Comment by jennyanthony** [comment] 2016-06-14 19:00
+1

**Comment by tagliala** [comment] 2017-03-24 14:31
Duplicate of #13

**Closed by tagliala** 2017-03-24 14:31 UTC
Labels: new icon, web application icons
