### ISSUE TITLE
Icon request: opentable

### ISSUE THREAD

**Issue by nurispark** [FortAwesome/Font-Awesome#20396] opened 2024-10-25 21:55 UTC
[OpenTable](https://www.opentable.com/) is one of the most widely used online reservation platforms for restaurants worldwide. Incorporating an OpenTable icon in FontAwesome would allow businesses to provide instant recognition of reservation functionality, improving user experience and navigation. Its presence is critical for restaurants aiming to streamline their online booking processes and attract diners through a globally trusted platform. Adding the brand’s icon to the FontAwesome brand library would significantly benefit the hospitality industry.
![OpenTable](https://github.com/user-attachments/assets/a059eb36-b7d8-4a86-9d74-86caa815dfab)

**Comment by tagliala** [comment] 2024-10-26 06:40
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #792, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-10-26 06:40 UTC
