### ISSUE TITLE
Icon Request: fa-arduino

### ISSUE THREAD

**Issue by Shz-Coders** [FortAwesome/Font-Awesome#17204] opened 2020-09-28 11:23 UTC
![img_153269](https://user-images.githubusercontent.com/63282193/94426341-4a6a3d80-019a-11eb-9d0b-cc5e6cae8f1d.png)

**Comment by tagliala** [comment] 2020-09-28 11:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2530, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-28 11:30 UTC
