### ISSUE TITLE
Icon request: icon-messages

### ISSUE THREAD

**Issue by amitait** [FortAwesome/Font-Awesome#5126] opened 2014-12-03 18:54 UTC
Hey!

I've noticed that although there is a "comment" icon (fa-comment for example), there isn't talk bubble that represent messages. You can see it on Facebook. It's like a comment bubble, but..."square-er".

I'm currently using the envelope icon, but it's more email than message :)

I can see myself stacking it with numbers icon (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9+) to indicate new messages. But maybe that's another issue.

Thanks!

**Comment by tagliala** [comment] 2015-08-07 14:10
this should be a duplicate of #2790

**Closed by tagliala** 2015-08-07 14:10 UTC
