### ISSUE TITLE
Icon request: Solidity

### ISSUE THREAD

**Issue by lakshh07** [FortAwesome/Font-Awesome#17726] opened 2021-03-13 06:33 UTC
[**What](url) can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
![image](https://user-images.githubusercontent.com/62194911/111021683-2753e300-83f4-11eb-8988-08e46f1b4e73.png)

**Comment by tagliala** [comment] 2021-03-13 09:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14515, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-13 09:38 UTC
