### ISSUE TITLE
Icon request: 3PMSF (three peak mountain snowflake / winter tires)

### ISSUE THREAD

**Issue by brsnik** [FortAwesome/Font-Awesome#16458] opened 2020-04-11 18:04 UTC
**What can it be used for?**
The Winter Certified symbol is important for Winter Tires because it shows that the minimum winter requirements are met by the manufacturer.

Heres more from Pirelli: https://www.pirelli.com/tyre/ww/en/news/2015/09/24/the-3pmsf-marking-a-symbol-of-winter-excellence/

**Example image (optional)**
https://www.pirelli.com/tyre/ww/en/news/files/2015/09/snowflakes-symbol.png

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-04-11 18:28
Hi!

Thanks for being part of the Font Awesome Community.

Do you know if that symbol is a registered trademark?

**Comment by brsnik** [comment] 2020-05-08 08:47
Don't think it is. And there is a variation in the design between different manufacturers.

Whats important is that it's a 3 peak mountain with a snowflake inside.

**Comment by stevekr** [comment] 2020-08-19 11:43
Duplicate of #15601

**Comment by tagliala** [comment] 2020-08-19 12:16
@stevekr thanks

**Closed by tagliala** 2020-08-19 12:16 UTC
Labels: automotive (category), new icon
