### ISSUE TITLE
Icon Request: fa-google-drive

### ISSUE THREAD

**Issue by wackamole** [FortAwesome/Font-Awesome#7072] opened 2015-07-29 09:53 UTC
Google Drive icon, I plan on using it for upload-button that allows the user to upload from Google Drive to my site.
![2015-07-29 11_52_01-min disk google disk](https://cloud.githubusercontent.com/assets/3738128/8954805/65200926-35e8-11e5-8132-a2611b0e8858.png)

**Comment by tagliala** [comment] 2015-07-29 12:13
duplicate of #835 , please +1 that request

closing here

**Closed by tagliala** 2015-07-29 12:13 UTC
