### ISSUE TITLE
Icon request: fa-handshake

### ISSUE THREAD

**Issue by mirorac** [FortAwesome/Font-Awesome#9646] opened 2016-07-26 09:51 UTC
Hello,
I would appreciate handshake icon. It could represent an agreement or icon for a client (person paying for my services).

Let's say in my admin dashboard I have menu item for _Users_ and also for _Clients_. The only idea I have is to use _fa-users_ for both.

[http://www.freeiconspng.com/uploads/handshake-icon-23.png](http://www.freeiconspng.com/uploads/handshake-icon-23.png)

**Comment by tagliala** [comment] 2016-07-26 10:09
Duplicate of #878 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-26 10:09 UTC
