### ISSUE TITLE
Icon Request: fa-dailymotion

### ISSUE THREAD

**Issue by chris19752** [FortAwesome/Font-Awesome#11171] opened 2017-06-14 09:48 UTC
Hello,
I use a Dailymotion page and I would like to use an icon "make awesome" to have a concordance with the other icons of youtube and soundcloud that I already use. You think this will be possible? Dailymotion is just a "d" http://www.dailymotion.fr
Thank you very much !

**Comment by tagliala** [comment] 2017-06-14 10:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3890, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-14 10:01 UTC
