### ISSUE TITLE
FA5: Sync-Alt Not Working

### ISSUE THREAD

**Issue by teamayu** [FortAwesome/Font-Awesome#11884] opened 2017-12-09 09:12 UTC
Ok, this is a strange one. I've just upgraded to v5.0, but the following doesn't work for me in any browser:

`<i class="fas fa-sync-alt"></i>`

This works fine:

`<i class="fas fa-sync"></i>`

Could it be a bug with FA? Or is the first not supposed to be in the free icons? Not sure. For now I can use fa-sync. :)

**Comment by tagliala** [comment] 2017-12-09 14:57
Hi!

Thanks for being part of the Font Awesome Community.

sync-alt appears to be available in FA5 Free, as per: https://fontawesome.com/icons?d=gallery&q=sync&m=free

Don't know if this is an issue in the docs or in the free font

Let's wait for @robmadole 's feedack

**Comment by teamayu** [comment] 2017-12-09 15:16
Thanks tagliali. It`s working on the FA website, so makes me think it`s something to do with me. I`ll wait for the next reply.

**Comment by tagliala** [comment] 2017-12-09 15:29
you're welcome @teamayu 

You are not the problem, I can replicate your issue: https://jsfiddle.net/tagliala/cq9rdny4/2/ and the `fa-sync-alt` class is not available in the css

Since `undo-alt` is also not available on FA5 Free, I suppose that `-alt` "arrows" are not available in FA5 Free, but let's wait

**Comment by robmadole** [comment] 2017-12-09 15:39
@tagliala @teamayu we released this in 5.0.1. Can you double-check the version that you are using?

I just realized that this is super confusing because the icon version says 5.0.0. The issue here is that we included it in the free subset in 5.0.1 but it didn't have any visual changes to it. We'll have to think about how to handle this little issue.

**Comment by tagliala** [comment] 2017-12-09 17:36
Thanks @robmadole I can confirm I was using 5.0.0 and this has been fixed in 5.0.1

https://jsfiddle.net/tagliala/tgzouajm/

**Closed by tagliala** 2017-12-09 17:36 UTC
Labels: new icon, waiting for feedback, web application icons
