### ISSUE TITLE
Icon request: c-sharp

### ISSUE THREAD

**Issue by Vedbhagat** [FortAwesome/Font-Awesome#18948] opened 2022-04-24 03:34 UTC
c-sharp is a programing language.
#18805

**Comment by aethior** [comment] 2022-04-24 04:40
Hi @nick,

Duplicate of #8365.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Comment by aethior** [comment] 2022-04-24 04:40
Hi @Vedbhagat,

Duplicate of #8365.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed as completed** 2022-04-24 07:41 UTC
