### ISSUE TITLE
Icon request: manual-transmission

### ISSUE THREAD

**Issue by tmas** [FortAwesome/Font-Awesome#12722] opened 2018-03-28 16:30 UTC
### What can it be used for?

Indicating that a person can drive a stick shift car on a profile page, indicating that a car has a manual transmission.

Could optionally have both 6-speed and 5-speed icons, which would allow differentiation between 6-speed and 5-speed vehicles.

### Example image (optional)

6 speed example:
![image](https://user-images.githubusercontent.com/271652/38042847-6d825426-3283-11e8-8b37-bb58514c3a2f.png)

5 speed example:
![image](https://user-images.githubusercontent.com/271652/38042904-977f01f2-3283-11e8-954d-16dd49cb5d7d.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-06 15:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3141 or #10130, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 15:46 UTC
