### ISSUE TITLE
Request icon: Firewall

### ISSUE THREAD

**Issue by dtouzeau** [FortAwesome/Font-Awesome#13368] opened 2018-06-21 19:42 UTC
Example:
![31490](https://user-images.githubusercontent.com/280586/41741661-02607ef0-759c-11e8-87fd-eaa773a688cd.png)

**Comment by tagliala** [comment] 2018-06-22 08:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4519, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-22 08:19 UTC
