### ISSUE TITLE
Icon Request: icon-party-balloons

### ISSUE THREAD

**Issue by luisbatista000** [FortAwesome/Font-Awesome#10494] opened 2017-01-08 16:36 UTC
I need some icons for my web.Is like a forum where posts receive scores from users.And i need some icons ballons for others plans in the same site.
![sin titulo](https://cloud.githubusercontent.com/assets/11902662/21751524/156d4db4-d59f-11e6-963d-69531d6e8cb8.png)

**Comment by tagliala** [comment] 2017-01-08 16:42
Hi!

Thanks for being part of the Font Awesome Community.

Balloon is a duplicate of #3398, please add a 👍  reaction to that request.

Leavint this open as `Icon Request: icon-party-balloons`

**Comment by luisbatista000** [comment] 2017-01-08 16:47
but i don't fine the icon

**Comment by tagliala** [comment] 2017-01-08 16:48
@luisbatista000 #3398 is a request to add a balloon icon, unfortunately it is not available at the moment in the set

**Comment by sensibleworld** [comment] 2024-07-11 20:08
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/balloons?f=classic&s=solid)

**Closed by sensibleworld** 2024-07-11 20:08 UTC
Labels: new icon, web application icons (legacy category), FA Pro
