### ISSUE TITLE
Icon Request: fa-membership

### ISSUE THREAD

**Issue by roxanajula** [FortAwesome/Font-Awesome#9312] opened 2016-06-01 11:38 UTC
Hello,

I have a case where I would need to use a membership icon for a Tab Bar. After searching and trying your available icons none of them where really what I was looking for. 
So I would like kindly ask if you can add a membership icon.

What it will be used for: memberships like for gyms or organizations, * the credit-card icons are too financial so they won't work, as some memberships can be for free.
I have also attached an example.

Thank you and best regards,
Roxana Jula

![76-512](https://cloud.githubusercontent.com/assets/5189246/15708267/01d33f1a-27fe-11e6-80bb-79c0e9dd8404.png)

**Comment by tagliala** [comment] 2016-06-01 11:52
I'm going to consider this a duplicate of #825, planned for 5.0.0, but please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-01 11:52 UTC
