### ISSUE TITLE
Icon request: icon-sms

### ISSUE THREAD

**Issue by TheoTuvna** [FortAwesome/Font-Awesome#11641] opened 2017-10-17 21:55 UTC
Here is a good example: http://www.iconarchive.com/show/windows-8-icons-by-icons8/Mobile-Sms-icon.html

**Comment by tagliala** [comment] 2017-10-17 22:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1440 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-17 22:13 UTC
