### ISSUE TITLE
Icon Request: fa-golang

### ISSUE THREAD

**Issue by lzt1226** [FortAwesome/Font-Awesome#10507] opened 2017-01-11 08:12 UTC
My own blog site need golang icon.Can help me?
Thanks！

**Comment by tagliala** [comment] 2017-01-11 12:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9431, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-11 12:55 UTC
