### ISSUE TITLE
Icon request: beta-icon

### ISSUE THREAD

**Issue by Kingtona123** [FortAwesome/Font-Awesome#14128] opened 2018-10-17 19:36 UTC
### What can it be used for?

The purpose of this icon would be for use of web developers to mark if applications are in beta.

### Example image (optional)

![image](https://user-images.githubusercontent.com/34285291/47111721-31398200-d24c-11e8-92dd-4063ab2b8efe.png)

### Icon request checklist

[Single] This is a single icon or matched pair (Ex: lock / unlock)
[Beta] The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
[ Yes ] I have searched for existing issues and to the best of my knowledge this is not a duplicate
[Yes ] I have included at least one example image if it could be helpful (optional)
[Yes ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-10-17 20:37
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #2085

If you are interested in the word `BETA`, please use plain CSS

Closing here

**Closed by tagliala** 2018-10-17 20:37 UTC
