### ISSUE TITLE
Icon request: icon-biohazard sign

### ISSUE THREAD

**Issue by cata92sv** [FortAwesome/Font-Awesome#11513] opened 2017-09-11 19:59 UTC
Hi guys,

We are developing some websites regarding to crime scene cleaners and a biohazard icon would be a really good help for us. 

Thank you so much
![566842](https://user-images.githubusercontent.com/31865087/30294148-c93bd448-9744-11e7-9f4e-c5354209c0fa.gif)

**Comment by tagliala** [comment] 2017-09-12 08:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #255, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-12 08:22 UTC

**Comment by tagliala** [comment] 2017-09-12 12:55
@cata92sv please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by timtjtim** [comment] 2017-09-12 20:09
I’m not an admin here, but I think this icon hasn’t been added because of the complexity. There’s no point increasing the package size by 1 or 2 KB just for a niche icon.

In addition, the designers have to work on a) Font Awesome Pro otherwise they can’t buy coffee or pizza and b) they just finished redesigning *all* the icons for Font Awesome 5, and added almost 400 new ones in the free version, and will have over 3000 in the Pro version. The people who design these icons allow us to use them for *anything* for *free* - the time it would take for me to design 5 of these icons (probably the average number I use per project) makes this worth over $15 per project.

If you need these icons that urgently, rather than getting angsty on this forum, why not just design it yourself - you’ve got a sample icon to start with!

**Comment by cata92sv** [comment] 2017-09-12 20:17
I'm sorry for that, really. I just got annoyed because I've been searching
for some time and my employer got stucked on it. Also, I didn't know that I
can design them myself and I didn't check the PRO Version. Do you think
there is a chance to get something similar on the Pro version?

I know that I sounded like an asshole and I apologize for that!

**Comment by timtjtim** [comment] 2017-09-12 20:33
I don’t have the Pro version I’m afraid, so I can’t check. You can pay $200 to have an icon added, though.

**Comment by tagliala** [comment] 2017-09-12 20:51
@timtjtim thanks for your thoughts and your support.

@cata92sv you just need a proper formatted .svg file and you can customize font awesome with an online tool, as described on the link I gave you before: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#the-easy-way

**Comment by cata92sv** [comment] 2017-09-12 20:54
Thank you guys, you've been awesome and I'll do that. I'm sorry again for
my behavior! I really know how much work is involved in these things and
it's really not nice of me asking smth because we have some free here.
