### ISSUE TITLE
Icon Request: fa-dumbbell

### ISSUE THREAD

**Issue by melanchton** [FortAwesome/Font-Awesome#10840] opened 2017-03-24 13:34 UTC
Representing Fitness & Sports
![icon_fitness](https://cloud.githubusercontent.com/assets/26652409/24296288/d2ca954e-109e-11e7-8849-f437995720ec.png)

**Comment by melanchton** [comment] 2017-03-24 13:34
Representing Healty Food
![icon_healthy_food](https://cloud.githubusercontent.com/assets/26652409/24296336/03140438-109f-11e7-90d6-66c22a0dc03c.png)

**Comment by melanchton** [comment] 2017-03-24 13:35
Representing Lifestyle
![icon_lifestyle](https://cloud.githubusercontent.com/assets/26652409/24296362/1c457a36-109f-11e7-8ab1-72abba83bbdf.png)

**Comment by tagliala** [comment] 2017-03-24 14:31
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #dumbbell #10533 #13, please add a 👍  reaction to that requests.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-24 14:31 UTC

**Comment by melanchton** [comment] 2017-03-24 14:50
How do i get the thumb up – to react. I don’t see any button or something like

to ad thumb up.

 

Von: Geremia Taglialatela [mailto:notifications@github.com] 
Gesendet: Freitag, 24. März 2017 15:32
An: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com>
Cc: melanchton <sillich@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [FortAwesome/Font-Awesome] Icon Request: fa-dumbbell (#10840)

 

Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #dumbbell #10533 <https://github.com/FortAwesome/Font-Awesome/issues/10533>  #13 <https://github.com/FortAwesome/Font-Awesome/issues/13> , please add a 👍 reaction to that requests.

Please make sure you search <https://github.com/FortAwesome/Font-Awesome/search?type=Issues>  before opening new requests

Closing here

**Comment by tagliala** [comment] 2017-03-24 14:56
Use the following links:  #1500 #2979 #13

Add a reaction: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

If links are not working, please use the GitHub website

**Comment by melanchton** [comment] 2017-03-24 15:25
Why can’t I find these Icons on:

 

http://fontawesome.io/icons/  ?

 

If I try to look up for “dumbbell” for example, I get the message: “Oops! No icons matched your query.”

 

 

Von: Geremia Taglialatela [mailto:notifications@github.com] 
Gesendet: Freitag, 24. März 2017 15:57
An: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com>
Cc: melanchton <sillich@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [FortAwesome/Font-Awesome] Icon Request: fa-dumbbell (#10840)

 

Use the following links: #1500 <https://github.com/FortAwesome/Font-Awesome/issues/1500>  #2979 <https://github.com/FortAwesome/Font-Awesome/issues/2979>  #13 <https://github.com/FortAwesome/Font-Awesome/issues/13> 

Add a reaction: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

If links are not working, please use the GitHub website

**Comment by tagliala** [comment] 2017-03-24 16:19
Unfortunately those icons are not available.

#1500 #2979 #13 are requests, and with a thumbs up you can upvote them

If you want to know how upvotes work or if you need the above icons in a short while, please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by melanchton** [comment] 2017-03-24 16:49
Is there a possibility to get those (requested) icons in my menu-bar? I have the Wordpress Font Awsome Plugin. 

 

Von: Geremia Taglialatela [mailto:notifications@github.com] 
Gesendet: Freitag, 24. März 2017 17:20
An: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com>
Cc: melanchton <sillich@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [FortAwesome/Font-Awesome] Icon Request: fa-dumbbell (#10840)

 

Unfortunately those icons are not available.

#1500 <https://github.com/FortAwesome/Font-Awesome/issues/1500>  #2979 <https://github.com/FortAwesome/Font-Awesome/issues/2979>  #13 <https://github.com/FortAwesome/Font-Awesome/issues/13>  are requests, and with a thumbs up you can upvote them

If you want to know how upvotes work or if you need the above icons in a short while, please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by tagliala** [comment] 2017-03-24 21:35
> Is there a possibility to get those (requested) icons in my menu-bar? I have the Wordpress Font Awsome Plugin.

You should customize font awesome, as explained here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#the-easy-way
