### ISSUE TITLE
Icon Request: fa-javascript

### ISSUE THREAD

**Issue by Trackhe** [FortAwesome/Font-Awesome#5608] opened 2015-02-06 21:47 UTC
![js](https://cloud.githubusercontent.com/assets/1494328/6088011/6c7e42c8-ae52-11e4-8cb4-284aee5cd062.png)
This is the perfect complement to html5 and css3

**Comment by tagliala** [comment] 2015-02-06 23:40
duplicate of #1711 , please +1 that request

closing here

**Closed by tagliala** 2015-02-06 23:40 UTC

**Comment by Trackhe** [comment] 2015-02-07 07:39
but this is not an exact desired icon.

**Comment by tagliala** [comment] 2015-02-07 11:25
post your example there, but afaik there is no official javascript logo

**Comment by Trackhe** [comment] 2015-02-07 18:00
wikipedia.org/wiki/JavaScript almost official

**Comment by tagliala** [comment] 2015-02-07 18:03
it's the same logo in the first post of #1711

**Comment by Trackhe** [comment] 2015-02-07 21:27
yes that nice :D

**Comment by tagliala** [comment] 2015-02-07 21:34
@Trackhe take a look at this fontawesome extension: http://fizzed.com/oss/font-mfizz

**Comment by Trackhe** [comment] 2015-02-25 20:58
http://de.wikipedia.org/wiki/JavaScript
