### ISSUE TITLE
Icon Request: fa-invoice

### ISSUE THREAD

**Issue by douglasdeodato** [FortAwesome/Font-Awesome#9448] opened 2016-06-22 11:44 UTC
Hello,

Use case: Bill, invoice, purchase, receipt icon

![basic3-017_invoice_bill-128](https://cloud.githubusercontent.com/assets/993318/16265413/19d78be6-3877-11e6-867a-6dd153ba23b4.png)

**Comment by tagliala** [comment] 2016-06-22 12:03
Duplicate of #1624 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-22 12:03 UTC

**Comment by douglasdeodato** [comment] 2016-06-22 12:45
i think refers for this link: https://github.com/FortAwesome/Font-Awesome/issues/477
