### ISSUE TITLE
Icon Request: fa-chair / fa-furniture

### ISSUE THREAD

**Issue by Cabsorx** [FortAwesome/Font-Awesome#9735] opened 2016-08-11 08:30 UTC
Hi there

I am in need of an icon that represents furniture, eq. a chair, a desk or a bookshelf. I have attached a few "brainstorm" ideas for the icon(s).

best of all
Christian
BTW: FontAwesome is a GREAT tool !
 
![furniture](https://cloud.githubusercontent.com/assets/11043545/17582913/7cf154ec-5fae-11e6-89d4-c0d24c8286ee.jpg)

**Comment by tagliala** [comment] 2016-08-11 08:55
Duplicate of #9495 and #1998 or #3984 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-11 08:55 UTC
