### ISSUE TITLE
Icon request: fa-unionpay

### ISSUE THREAD

**Issue by weihongyu12** [FortAwesome/Font-Awesome#11068] opened 2017-05-16 06:29 UTC
![unionpay](https://cloud.githubusercontent.com/assets/19792747/26092534/fb9309ce-3a43-11e7-81e6-791a039ab3b4.png)

UnionPay is China's largest bank card issuer, and I hope to add this icon and payments icon to use it together.

**Comment by tagliala** [comment] 2017-05-16 17:18
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4561 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-16 17:18 UTC
