### ISSUE TITLE
Icon request: text-colour, Icon request: text-background

### ISSUE THREAD

**Issue by jacobcxdev** [FortAwesome/Font-Awesome#13831] opened 2018-08-29 04:45 UTC
### What can it be used for?

It can be used for text colour/background buttons in text editors.

### Example image (optional)

![Text Colour](https://user-images.githubusercontent.com/27970288/44765808-65e36400-ab4e-11e8-8414-30918942d531.png)
![Text Background](https://user-images.githubusercontent.com/27970288/44765760-26b51300-ab4e-11e8-8896-8e493c8bbc26.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-04-15 04:03
Hi @jacobcxdev,

This request is duplicate of #4689 (text-colour) and #5570 (text-background).
Please add a 👍 reaction to those requests.

Regards.

cc/ @tagliala

**Closed** 2022-04-15 07:27 UTC
