### ISSUE TITLE
Icon request: icon-thermometer

### ISSUE THREAD

**Issue by vgonzalez07** [FortAwesome/Font-Awesome#8916] opened 2016-04-07 15:56 UTC
Hello there, thanks for develop Font Icons, it is a really help full tool. I would like to suggest to add a termomether icon. I'm develop a home automation system, and one of my sensors measure the temperature. The idea could be like this:

![thermometericon](https://cloud.githubusercontent.com/assets/8059246/14357630/13e6f9a0-fcaf-11e5-910a-0030f353d756.png)

I found that icon in typicons but i like more your icons set, :)
Thanks, have a good day
Victor Gonzalez

**Comment by aethior** [comment] 2016-04-07 18:56
Hi @vgonzalez07,

This request is duplicate of #720. `fa-thermometer` is planned for v5.0.0.

**Comment by tagliala** [comment] 2016-04-07 21:56
@aethior thanks

**Closed by tagliala** 2016-04-07 21:56 UTC
