### ISSUE TITLE
Icon request: Scanner Icon

### ISSUE THREAD

**Issue by Welchen** [FortAwesome/Font-Awesome#13767] opened 2018-08-14 13:15 UTC
There is a print and fax icon but no scan type of icon.

**Comment by tagliala** [comment] 2018-08-14 13:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5985, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-14 13:51 UTC

**Comment by Welchen** [comment] 2018-08-14 13:55
@tagliala I did do a +1 there but curious on how long it takes for an idea to be accepted? That post is from 2015 and seems odd that it hasn't been added yet.  There are icons in that device family but not one for that.

**Comment by tagliala** [comment] 2018-08-14 14:12
@Welchen take a look here https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome and here https://fontawesome.com/community/leaderboard/new
