### ISSUE TITLE
Icon request: gameplan

### ISSUE THREAD

**Issue by Greed-McTavish** [FortAwesome/Font-Awesome#20130] opened 2024-02-23 17:57 UTC
a clipboard or whiteboard with a "play" that a sports team learns to use on the field (commonly showing X's and O's that represent players and opponents with arrows and lines illustrating movement or changes in position.

This is common in football/soccer, rugby, american football, hockey, and other team-based sports. It is also useful for illustrating business strategies and plans. (keywords: Strategy, Plan, Playbook, gameplan, etc.)

**Comment by tagliala** [comment] 2024-02-23 19:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9659, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-02-23 19:17 UTC
