### ISSUE TITLE
Icon request: spotlight

### ISSUE THREAD

**Issue by JeffH21** [FortAwesome/Font-Awesome#18703] opened 2022-02-15 19:44 UTC
FlatIcon has some good ones.
![image](https://user-images.githubusercontent.com/25444649/154136778-977d33a4-4f93-4ca5-aad1-e1ddc8f6baba.png)
![image](https://user-images.githubusercontent.com/25444649/154136941-baef06b2-6c21-4b96-a5b2-d6e3e1501139.png)

**Comment by tagliala** [comment] 2022-02-15 19:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14651, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-02-15 19:46 UTC
