### ISSUE TITLE
Icon request: clear-text-format

### ISSUE THREAD

**Issue by sovetsch** [FortAwesome/Font-Awesome#14099] opened 2018-10-11 23:30 UTC
### What can it be used for?

Can be used for creating text editing menu items. This icon would indicate clearing any existing text formatting. fa already has bold, italics, etc. however no clear format icon or anything that could be clearly used as such.

### Example image (optional)

https://www.google.ca/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwjwwpqJxf_dAhUQ84MKHZayAqgQjRx6BAgBEAU&url=https%3A%2F%2Fwww.onlinewebfonts.com%2Ficon%2F139725&psig=AOvVaw0BHQS8jFu9BGZJpk8-EsPh&ust=1539386857873364

### Icon request checklist

- Single icon

**Comment by tagliala** [comment] 2018-10-12 08:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9288, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-12 08:17 UTC
