### ISSUE TITLE
Icon request: water-bottle

### ISSUE THREAD

**Issue by slm04c** [FortAwesome/Font-Awesome#15201] opened 2019-06-26 21:32 UTC
**What can it be used for?**
This would describe beverage containers like a water bottle

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [Single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [Plastic Water Bottle] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [No] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-06-26 22:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10741, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-06-26 22:06 UTC
