### ISSUE TITLE
Icon Request: fa-dashed-square-o

### ISSUE THREAD

**Issue by jfoo** [FortAwesome/Font-Awesome#8402] opened 2016-01-24 23:51 UTC
Hello Font Awesome team! 
Thanks for the great work! Loves all the icon! 

I would like to request some new icons if possible. We have planned to use two of the icons on multiple grouping scenarios. We are currently using "Plus" and "Delete" icon for it but doesn't work if there's more then three groups in a scenarios. So my idea with line-stroke around will indicate inner groupings. Please see 1 and 2 image attached. 
1. Add new group icon
   ![new-fa-icon](https://cloud.githubusercontent.com/assets/16870074/12539880/37ef0600-c350-11e5-8193-c1e3887b36cc.jpg)
2. Delete group icon 
   ![new-faicon-deletegroup](https://cloud.githubusercontent.com/assets/16870074/12539882/42e7e310-c350-11e5-948d-2976383ef2dc.jpg)

Also we would love to have an admin icon to differentiate from normal user icon.
3. Admin user icon - Perhaps replicate "fa-user" icon and add a tie? 

Please contact me (jfoo@assetic.com) if you need more info or assistant. I can make up eps or svg files if it is easier. 
Thank you

James

**Comment by cherrador** [comment] 2016-01-25 03:10
This could do it with some extra border style:

<i class="fa fa-times" style="padding:.2em .25em;border:dotted .2em #000;border-radius:.3em;"></i>
<i class="fa fa-plus" style="padding:.2em .25em;border:dotted .2em #000;border-radius:.3em;"></i>

You could move the style definition to a stylesheet:

**Comment by tagliala** [comment] 2016-01-25 12:46
user admin is a duplicate of #3397 , please +1 that request

I will rename this as fa-dashed-square-o, so it could be used for stacking purposes

**Comment by jfoo** [comment] 2016-01-26 22:25
thanks guys

**Comment by sensibleworld** [comment] 2022-03-15 01:06
https://fontawesome.com/icons/square-dashed?s=solid

**Closed by sensibleworld** 2022-03-15 01:06 UTC
Labels: new icon, web application icons
