### ISSUE TITLE
Icon Request: fa-pan

### ISSUE THREAD

**Issue by polive31** [FortAwesome/Font-Awesome#10526] opened 2017-01-17 00:13 UTC
Usage : cooking website

![image](https://cloud.githubusercontent.com/assets/20874297/22003205/102b8a0a-dc52-11e6-8cab-a0eb32eac384.png)

**Comment by tagliala** [comment] 2017-01-17 12:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10076, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-17 12:57 UTC
