### ISSUE TITLE
Artstation Icon

### ISSUE THREAD

**Issue by Niclas3er** [FortAwesome/Font-Awesome#14035] opened 2018-09-29 08:17 UTC
A Artstation icon would be nice

**Comment by tagliala** [comment] 2018-10-02 19:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5354, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-02 19:34 UTC
