### ISSUE TITLE
Icon Request: fa-support

### ISSUE THREAD

**Issue by GerritP** [FortAwesome/Font-Awesome#11469] opened 2017-08-31 00:10 UTC
Hi there,

an icon for customer support would be very useful:

![image](https://user-images.githubusercontent.com/31493266/29900311-ad357aca-8db6-11e7-8c9c-dc2574952bbd.png)
![image](https://user-images.githubusercontent.com/31493266/29900336-db4ffa34-8db6-11e7-8017-053125231cd6.png)

Greetings

**Comment by tagliala** [comment] 2017-08-31 09:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1146 or #5586, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-31 09:19 UTC
