### ISSUE TITLE
Icon request: "Segway" or any self balancing electrical scooter

### ISSUE THREAD

**Issue by eco4drive** [FortAwesome/Font-Awesome#16218] opened 2020-02-19 09:45 UTC
**What can it be used for?**
i like to ue the icon in open street maps as a marker.

**Example image (optional)**
done ;-)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
![segway verkehrsschild](https://user-images.githubusercontent.com/61229006/74822035-cea33b00-5304-11ea-8a4d-c1332bdb0498.png)
![P1120681_bearb](https://user-images.githubusercontent.com/61229006/74822084-debb1a80-5304-11ea-9187-543e17f9a2dd.jpg)
![MG_8391-2](https://user-images.githubusercontent.com/61229006/74822105-e5499200-5304-11ea-8130-a65e6392a272.jpg)

**Comment by tagliala** [comment] 2020-02-19 11:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10243, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-02-19 11:59 UTC
