### ISSUE TITLE
Icon Request: Houzz

### ISSUE THREAD

**Issue by SabrinaBrand** [FortAwesome/Font-Awesome#6548] opened 2015-05-24 12:15 UTC
Hi,

could you plz add
http://st.houzz.com/static_fr-FR/badge20_20.png
and
http://st.houzz.com/static_fr-FR/badge36_36.png

Tank you,
Sabrina Brand
brand-conception.com

**Comment by tagliala** [comment] 2015-05-24 13:51
duplicate of #2039 , please +1 that request

closing here

**Closed by tagliala** 2015-05-24 13:51 UTC

**Comment by markream** [comment] 2015-05-27 19:13
+ 1 for a houzz icon
