### ISSUE TITLE
Icon request: fa-user-o and the families of users with o

### ISSUE THREAD

**Issue by hansyulian** [FortAwesome/Font-Awesome#9186] opened 2016-05-12 11:28 UTC
the only outline for user icon

**Comment by rwsansom** [comment] 2016-05-26 17:18
+1

**Comment by tagliala** [comment] 2016-05-26 21:06
Duplicate of #3671, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-26 21:06 UTC
