### ISSUE TITLE
Icon request: fa-thumb-tack-slash

### ISSUE THREAD

**Issue by capricarun** [FortAwesome/Font-Awesome#9355] opened 2016-06-07 11:00 UTC
Requesting an slashed pin icon.

**Comment by tagliala** [comment] 2016-06-07 13:27
Refers to #1181

**Comment by sensibleworld** [comment] 2024-07-10 21:18
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/10749)

**Closed by sensibleworld** 2024-07-10 21:18 UTC
Labels: new icon, web application icons (legacy category), Duplicate
