### ISSUE TITLE
icon request: icon-strava

### ISSUE THREAD

**Issue by mavit2** [FortAwesome/Font-Awesome#10175] opened 2016-11-05 10:20 UTC
Helo,

could you please add icon for social athlet network STRAVA.COM. Thank you.

**Comment by tagliala** [comment] 2016-11-05 14:44
Duplicate of #3313 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-05 14:44 UTC
