### ISSUE TITLE
Icon request: Mendeleev Chemical Table

### ISSUE THREAD

**Issue by SuchMuch** [FortAwesome/Font-Awesome#9020] opened 2016-04-19 14:40 UTC
Should these icons be created I would use them as forum glyphs
E.g.: "Fe", "Cu", "Ag"
Pls find Mendeleev chemical table attached

![dozenal_periodic_table](https://cloud.githubusercontent.com/assets/18555194/14642924/22b7130c-0655-11e6-83a9-448051e121d3.png)

**Comment by tagliala** [comment] 2016-04-19 17:45
Sorry, I didn't get this request

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by SuchMuch** [comment] 2016-04-19 17:50
Re: [FortAwesome/Font-Awesome] Icon request: Mendeleev Chemical Table (#9020)



Geremia,
Should I create a separate request per each icon?
____________________
С уважением / Brgds,
Rodion (SuchMuch)

Email: suchmuch@list.ru

Вы писали 19 апреля 2016 г., 20:46:30:





Sorry, I didn't get this request
Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by tagliala** [comment] 2016-04-19 18:55
> Should I create a separate request per each icon?

how many icon you are going to request?

**Comment by SuchMuch** [comment] 2016-04-19 19:03
Re: [FortAwesome/Font-Awesome] Icon request: Mendeleev Chemical Table (#9020)



Geremia,
5 at least (Silver, Copper, Lead, Zinc, Iron), but I believe different chemical abbreviation 
could be under demand, so it's worth to make them all...  
____________________
С уважением / Brgds,
Rodion (SuchMuch)

Email: suchmuch@list.ru

Вы писали 19 апреля 2016 г., 21:56:34:





Should I create a separate request per each icon?
how many icon you are going to request?

**Comment by tagliala** [comment] 2016-04-19 20:02
@SuchMuch sorry, chemical elements are out of scope. Please do not open individual request.

You can use plain css:

```css
.fa-au::before {
  content: "Au";
}
```
https://jsfiddle.net/tagliala/72fd5vcr/2/

**Closed by tagliala** 2016-04-19 20:02 UTC
Labels: waiting for feedback

**Comment by My1** [comment] 2016-04-20 10:30
well the problem is that this will be heavily influenced by user fonts and a lot of other stuff.
I think chemistry icons arent a bad Idea but the should be split apart from main fa, similarly as the brand icons should (#1322)

**Comment by tagliala** [comment] 2022-08-22 20:51
Hi @sensibleworld, this has been requested again in #19280, and at the time I've labeled as wontfix since it was a request for at least 100 icons (now 400+, if we don't count duotone or sharp)

Do you want to keep this open for tracking reasons?

**Comment by pixiekat** [comment] 2022-08-22 20:56
There are a bunch of fonts that offer this same thing here, instead of putting them in FA.

https://www.flaticon.com/free-icons/periodic-elements

https://www.cufonfonts.com/font/periodic-table-of-elements

https://www.onlinewebfonts.com/icon/532467

https://www.myfunstudio.com/font/
