### ISSUE TITLE
Icon Request: fa-send-box

### ISSUE THREAD

**Issue by tatof** [FortAwesome/Font-Awesome#7667] opened 2015-10-13 08:43 UTC
A simple carton box with open flaps for a "send pakkage" symbol.

**Comment by tagliala** [comment] 2015-10-31 20:35
duplicate of #908 ?

**Comment by tatof** [comment] 2015-10-31 22:10
Jup and I mis an shopping basket icon. But I found out how to add icons to
awesome font so don't really need it anymore.

Thank you
Op 31 okt. 2015 21:35 schreef "Geremia Taglialatela" <
notifications@github.com>:

**Comment by tagliala** [comment] 2015-10-31 23:19
Please +1 #908 and #962 

Closing here

**Closed by tagliala** 2015-10-31 23:19 UTC
Labels: waiting for feedback
