### ISSUE TITLE
fa-university has extra space on the right

### ISSUE THREAD

**Issue by murzilla** [FortAwesome/Font-Awesome#9439] opened 2016-06-22 02:59 UTC
Really evident on bigger sizes.
![icon-bug](https://cloud.githubusercontent.com/assets/136747/16253329/54ad2a78-3868-11e6-9191-5b5e5ff0386f.png)

**Comment by tagliala** [comment] 2016-06-22 10:01
Yes, this is a known issue. Duplicate of #8628

**Closed by tagliala** 2016-06-22 10:01 UTC
