### ISSUE TITLE
wrong link for the old version

### ISSUE THREAD

**Issue by eKatsarski** [FortAwesome/Font-Awesome#15105] opened 2019-06-04 18:38 UTC
![Selection_440](https://user-images.githubusercontent.com/2194954/58904786-e43de980-8710-11e9-876d-7c039ef83e65.png)
the link for the old version open 404 page
at the moment is leading to https://origin.fontawesome.com/v4.7.0
and it should be https://fontawesome.com/v4.7.0/

**Comment by tagliala** [comment] 2019-06-04 18:43
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm the issue, but I don't know if it is correct the https://origin.fontawesome.com/ should be a working alias for the documentation website 🤔 

@talbs could you please take a look?

**Comment by robmadole** [comment] 2019-06-05 13:59
@tagliala I can't replicate this. What am I missing? The link is going to `/v4.7.0`.

**Comment by tagliala** [comment] 2019-06-05 14:56
@robmadole 

1. Go to https://origin.fontawesome.com/
2. Click on `Old Version 4.7` at the bottom of the page

**Comment by robmadole** [comment] 2019-06-11 13:18
So origin.fontawesome.com is not really a public address. It’s the origin server that our caching engine looks at to grab the source. Are we leaking this somewhere?

**Comment by eKatsarski** [comment] 2019-06-11 13:54
Yes, I think I ended up there from some search engine, not from the navigation of the site. Sorry if I have just created noise ...

**Comment by eKatsarski** [comment] 2019-06-11 13:56
The link on the https://fontawesome.com/ works fine

**Comment by talbs** [comment] 2019-10-10 01:32
Thanks for the extra info, @eKatsarski and sorry for the delay in responding here. I'll close this issue since the site is working as intended. If this pops up again, let us know.

Thanks again for getting in touch to give us this feedback. 😄

**Closed by talbs** 2019-10-10 01:32 UTC
Labels: fontawesome.com, waiting for feedback
