### ISSUE TITLE
Icon Request: fa-meetup

### ISSUE THREAD

**Issue by shonlb** [FortAwesome/Font-Awesome#6947] opened 2015-07-14 04:03 UTC
Nice to have an icon for meetup.com

![image](https://cloud.githubusercontent.com/assets/901311/8666188/4d1dd5f6-29b3-11e5-8d7c-c8613316013b.png)

**Comment by tagliala** [comment] 2015-07-16 12:15
duplicate of #1588 , please +1 that request

closing here

**Closed by tagliala** 2015-07-16 12:15 UTC
