### ISSUE TITLE
[Request] New Icon (Unity3D)

### ISSUE THREAD

**Issue by plinio-jrm** [FortAwesome/Font-Awesome#11951] opened 2017-12-16 21:26 UTC
Hi. Would be nice to have the Unity3D icon!
Thanks!

**Comment by tagliala** [comment] 2017-12-16 21:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2888, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-16 21:47 UTC
