### ISSUE TITLE
Icon request: scatter-plot

### ISSUE THREAD

**Issue by deandevl** [FortAwesome/Font-Awesome#10517] opened 2017-01-13 11:13 UTC
This would be a simple icon with an 'L' shaped x-y axis' and dots scattered and enclosed within the 'L'.  I create all types of bar, line charts including scatter plots for scientific applications and your icons have been helpful in differentiating the offerings.
Thanks for your work

**Comment by tagliala** [comment] 2017-01-13 13:44
Duplicate of #4240?

**Comment by sensibleworld** [comment] 2019-12-06 18:27
Playing some catch-up on older icon requests. We now have an icon that should fit this use case: https://fontawesome.com/icons/chart-scatter?style=solid

**Closed by sensibleworld** 2019-12-06 18:27 UTC
Labels: waiting for feedback
