### ISSUE TITLE
Icon Request: fa-tooth

### ISSUE THREAD

**Issue by danielpikl** [FortAwesome/Font-Awesome#10560] opened 2017-01-24 14:35 UTC
I'm working in dental office and we need some dental icons for our websites. 
I'm sure that all dentist around the world would appreciated it.

There can be many different icon variations, tooth, teeth, dental implant, dental crown, dental bridge, dentures, etc ...

**Comment by tagliala** [comment] 2017-01-24 14:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1289 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-24 14:37 UTC
