### ISSUE TITLE
Icon request: codecademy

### ISSUE THREAD

**Issue by WilliamGeo** [FortAwesome/Font-Awesome#18986] opened 2022-05-01 14:03 UTC
I request this to be added to the index.

![Codecademy](https://upload.wikimedia.org/wikipedia/commons/6/6c/Codecademy.svg)
![Alt](https://avatars.githubusercontent.com/u/1463944)

**Comment by tagliala** [comment] 2022-05-01 14:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3320, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-05-01 14:23 UTC
