### ISSUE TITLE
Icon request: icon-deaf/icon-mental

### ISSUE THREAD

**Issue by m1k3hu** [FortAwesome/Font-Awesome#8875] opened 2016-04-02 16:18 UTC
hi!
my website is about people with disabilities. i found an icon for blindness (fa-eye-slash) and for wheelchair (fa-wheelchair), but it would be nice it there could be an icon for deaf people (fa-deaf or fa-ear-slash) and for mental illnesses (fa-mental) as well.
the signs are as follows:
![ico-hallasserult](https://cloud.githubusercontent.com/assets/18233259/14227483/3d145632-f8ff-11e5-8556-2728664baab1.png)
![ico-mentalis](https://cloud.githubusercontent.com/assets/18233259/14227484/3d15481c-f8ff-11e5-81e6-1f2b4acc5010.png)

**Comment by tagliala** [comment] 2016-04-02 16:55
Duplicate of #8863 and #2075 / #8443 please +1 those requests

closing here

**Closed by tagliala** 2016-04-02 16:55 UTC
