### ISSUE TITLE
Icon Request: fa-family

### ISSUE THREAD

**Issue by sairam2188** [FortAwesome/Font-Awesome#8440] opened 2016-01-28 14:21 UTC
Hi,

I request a **family icon**. For use in life insurance company.
Examples: 
![image](https://cloud.githubusercontent.com/assets/9343561/12646824/44c6730c-c5a0-11e5-980d-5c7bebd3a9f3.png)
![image](https://cloud.githubusercontent.com/assets/9343561/12646833/50a7a8ee-c5a0-11e5-8062-75190d6b8d46.png)

Thanks in advance.

**Comment by tagliala** [comment] 2016-01-28 15:38
duplicate of #3277 , please +1 that request

closing here

**Closed by tagliala** 2016-01-28 15:38 UTC
