### ISSUE TITLE
Icon jogging

### ISSUE THREAD

**Issue by otoman** [FortAwesome/Font-Awesome#13245] opened 2018-05-31 16:00 UTC
Please add icon for jogging

**Comment by tagliala** [comment] 2018-05-31 18:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1156 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-31 18:33 UTC

**Comment by otoman** [comment] 2018-05-31 19:15
Oh sorry for duplicate :)
