### ISSUE TITLE
Icon Request: fa-Fit To Window

### ISSUE THREAD

**Issue by derryTWMP** [FortAwesome/Font-Awesome#7957] opened 2015-11-22 19:56 UTC
need an icon to zoom in / zoom out of a picture from its actual size to have the entire image in the standard sizesd window, same functionality as in Windows Photo Viewer . Icon is a rectangle with triangles at the 4 corners, with the points pointing out from the rectangle
![fit to window](https://cloud.githubusercontent.com/assets/15970386/11325936/20e6305c-9153-11e5-9823-c2843a4dc3f6.PNG)

**Comment by derryTWMP** [comment] 2015-11-23 10:55
better mock up 
![fit to window](https://cloud.githubusercontent.com/assets/15970386/11334994/a250e092-91d0-11e5-9064-ab7c095a15c9.png)

**Comment by caduvieira** [comment] 2015-11-23 11:26
dupe of #7198 ?

**Comment by tagliala** [comment] 2015-11-23 11:46
Confirmed duplicate, closing here

**Closed by tagliala** 2015-11-23 11:46 UTC
