### ISSUE TITLE
Icon request: icon-instagram-square

### ISSUE THREAD

**Issue by emilylordahl** [FortAwesome/Font-Awesome#9565] opened 2016-07-13 19:54 UTC
There already exists a square version of many of the popular social channels, ie Facebook, Twitter, YouTube, etc. Think it would be nice to have for the sake of consistency of people using the square versions for social media promotion given the popularity of Instagram.

Thank you!

**Comment by tagliala** [comment] 2016-07-13 20:58
Duplicate of #9223, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-13 20:58 UTC
