### ISSUE TITLE
Icon request: crate

### ISSUE THREAD

**Issue by a-hulman** [FortAwesome/Font-Awesome#11731] opened 2017-11-09 11:44 UTC
Hello there,
I am implementing API for sending packages using a parcel service and I was looking for an icon of a crate
e.g.
https://cdn0.iconfinder.com/data/icons/shipping-icons/100/11-512.png
or (second row, first)
https://cmkt-image-prd.global.ssl.fastly.net/0.1.0/ps/1809636/300/200/m1/fpnw/wm0/1605.m10.i307.n001.p.c25.181578149-package-line-thin-icons-vector-set.-boxes-crates-containers-.jpg?1477557564&s=5719dc2b17efb5f57eb3563c1359542b

This icon can be used for any references to cargo, packages, boxes, storage etc.

I would even draw this myself if there is a way to contribute?

thanks,
Alexander

**Comment by tagliala** [comment] 2017-11-09 13:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #908 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-09 13:14 UTC

**Comment by a-hulman** [comment] 2017-11-09 13:19
Hello,
thanks for the quick response, I searched "crate" instead of "package" 
:)

Thumbs up added!

thanks,
Alexander

------ Original Message ------

**Comment by tagliala** [comment] 2017-11-09 14:04
@a-hulman you're welcome. I've just added "crate" to #908's title for searching purposes
