### ISSUE TITLE
Icon Request: fa-castle fa-sword fa-crown

### ISSUE THREAD

**Issue by telefoontoestel** [FortAwesome/Font-Awesome#10476] opened 2017-01-05 19:08 UTC
Hi there.
I normally use font awesome for work related issues, but now I want to make a invitation card for a childrens party with a kings and castles theme. Is it possible to create three related icons called fa-castle, fa-sword and fa-crown? That would very much make the creation of the invitations and maps a whole lot better.

Thanks very much.
A happy font awesome user.

**Comment by tagliala** [comment] 2017-01-05 20:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1449 #486 , please add a 👍  reaction to that request.

Castle: http://fontawesome.io/icon/fort-awesome/

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-05 20:36 UTC

**Comment by L-Pop** [comment] 2017-09-08 15:58
+1
