### ISSUE TITLE
Icon Request: fa-ballot

### ISSUE THREAD

**Issue by sodevious** [FortAwesome/Font-Awesome#8350] opened 2016-01-15 16:58 UTC
Going to be used around the term "vote" and "voting" – could be great for elections and stuff.

[For example](https://thenounproject.com/term/voting/188134/): 
<img width="376" alt="screen shot 2016-01-15 at 11 58 19 am" src="https://cloud.githubusercontent.com/assets/915966/12359238/547ab324-bb7f-11e5-80de-6a1911732607.png">

**Comment by aethior** [comment] 2016-01-15 17:46
Hi @sodevious,

This suggestion is duplicate of #7839. Please +1 that.

Regards.

**Closed** 2016-01-15 17:52 UTC
