### ISSUE TITLE
Icon Request: fa-windmill

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9999] opened 2016-09-29 18:20 UTC
Windmill icon to depict Clearn Energy for use within a healthcare data app
![windmill](https://cloud.githubusercontent.com/assets/539719/18966626/ea5f84b4-864f-11e6-8539-07012468e5f6.png)

**Comment by tagliala** [comment] 2016-09-30 09:02
Duplicate of #1300, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 09:02 UTC
