### ISSUE TITLE
Icon request: Jesus Fish

### ISSUE THREAD

**Issue by qopel** [FortAwesome/Font-Awesome#5502] opened 2015-01-28 02:18 UTC
For Religious Websites
![imagesj39rkkyu](https://cloud.githubusercontent.com/assets/8602426/5931305/017d15ac-a66a-11e4-86e2-5fd0fa1f7025.jpg)

**Comment by tagliala** [comment] 2015-01-28 20:26
duplicate of #3360, please +1 that request

closing here

**Closed by tagliala** 2015-01-28 20:26 UTC
Labels: new icon, web application icons
