### ISSUE TITLE
Icon Request: icon-medicine

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [FortAwesome/Font-Awesome#11983] opened 2017-12-22 07:02 UTC
I think it would be great if you can add a medicine icon as shown below.

![screen shot 2017-12-22 at 12 29 25 pm](https://user-images.githubusercontent.com/9896335/34288533-c8f1f7dc-e713-11e7-8902-d6c7ac937120.png)

**Comment by tagliala** [comment] 2017-12-25 13:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9986 or #1778, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-25 13:16 UTC
