### ISSUE TITLE
Icon request: ballet-slippers

### ISSUE THREAD

**Issue by amrartist2009** [FortAwesome/Font-Awesome#17685] opened 2021-03-03 04:42 UTC
**What can it be used for?**
This can be used for dance and performing arts centers. There is an entire ski/snow sports set, but there is nothing for ballerina, tap shoes, dance, yoga (person meditating), Lotus flower, etc. I think these icons could be very useful to dance studios and gyms who offer these services.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon - but could be a full set of 5-10 icons depending on how far your team takes it.
- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] I have [searched for existing issues] They are closed with no new icons added: #7563, #7564, #7565
- [X] The request is for a concrete object

**Comment by aethior** [comment] 2022-03-12 18:12
Duplicate of #7563.

cc/ @tagliala

**Closed** 2022-03-12 18:32 UTC
