### ISSUE TITLE
Icon request: icon-scroll

### ISSUE THREAD

**Issue by nilvalls** [FortAwesome/Font-Awesome#8225] opened 2015-12-27 04:20 UTC
To complement academic icons such as fa-university, fa-book, fa-graduation-cap.
![42771636-blank-antique-scroll](https://cloud.githubusercontent.com/assets/4990026/12008839/de361006-ac1e-11e5-8d37-2f5168fd3ee7.jpg)
![ancient_scroll_1600_clr](https://cloud.githubusercontent.com/assets/4990026/12008840/de381c48-ac1e-11e5-8a15-dd7b10ff79eb.png)

**Comment by tagliala** [comment] 2015-12-27 10:23
Duplicate of #1173, please +1 that request

closing here

**Closed by tagliala** 2015-12-27 10:23 UTC
