### ISSUE TITLE
Icon request: office table or office tables with furnitures on it

### ISSUE THREAD

**Issue by jeremydDutel** [FortAwesome/Font-Awesome#17498] opened 2020-12-18 22:21 UTC
**What can it be used for?**
I've been looking every single icon, and didn't see office tables or office tables with furniture on it.
It can be reallu usefull for websites who sell office tables, like the one i'm doing.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/51119269/102666363-01b59580-4187-11eb-9df9-ea5ee38e2e29.png)
![image](https://user-images.githubusercontent.com/51119269/102666382-0d08c100-4187-11eb-9dd6-3379206259a4.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-12-19 13:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3519, please add a 👍 reaction to that request and post your example there.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-12-19 13:34 UTC
