### ISSUE TITLE
Icon Request: fa-gas / fa-petrol

### ISSUE THREAD

**Issue by stud3nt3** [FortAwesome/Font-Awesome#9022] opened 2016-04-19 14:49 UTC
<a href="http://it.tinypic.com?ref=xmjxco" target="_blank"><img src="http://i64.tinypic.com/xmjxco.png" border="0" alt="Image and video hosting by TinyPic"></a>

<a href="http://it.tinypic.com?ref=24b6x6o" target="_blank"><img src="http://i66.tinypic.com/24b6x6o.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by PeterShaggyNoble** [comment] 2016-04-19 15:18
Dupe of [#1676](https://github.com/FortAwesome/Font-Awesome/issues/1676), you should +1 that one instead.

**Closed** 2016-04-19 16:36 UTC
