### ISSUE TITLE
Icon Request: fa-rename

### ISSUE THREAD

**Issue by leonkladnitsky** [FortAwesome/Font-Awesome#6643] opened 2015-06-03 08:03 UTC
General use icon for renaming files, items etc. Examples can be found by googling "rename icon".

Here are a couple:

![image](https://cloud.githubusercontent.com/assets/12727607/7955295/cab345f8-09df-11e5-93b1-26471bb30b25.png)

![image](https://cloud.githubusercontent.com/assets/12727607/7955301/dcd9ea5c-09df-11e5-88e0-41a07e81fc13.png)

Thank you,
Leon.

**Comment by tagliala** [comment] 2015-06-07 09:42
duplicate of #1334, please +1 that request and post there your examples

closing here

**Closed by tagliala** 2015-06-07 09:42 UTC
