### ISSUE TITLE
Weather icons?

### ISSUE THREAD

**Issue by kikidesignnet** [FortAwesome/Font-Awesome#10699] opened 2017-02-24 00:24 UTC
It would be nice if you add weather icons such as Rain, Cloud with outline, Snowflake with Cloud, Fog, among other weather icons. For the rain, I would like for it to look like a cloud with raindrops. 

Rain = fa-rain-cloud-o
Cloud w/ outline = fa-cloud-o
Snow = fa-snow-cloud-o
Fog = fa-fog

They would be perfect for building a local weather app or any weather-related content. 

You can check out the examples at [http://adamwhitcroft.com/climacons/](http://adamwhitcroft.com/climacons/). Those are weather icons.

**Comment by tagliala** [comment] 2017-02-24 08:32
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #155 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Please also take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application) our suggestion is to customize Font Awesome.

Closing here

**Closed by tagliala** 2017-02-24 08:32 UTC
