### ISSUE TITLE
Icon request: Linktree

### ISSUE THREAD

**Issue by theAnshulGupta** [FortAwesome/Font-Awesome#17515] opened 2020-12-28 21:45 UTC
**What can it be used for?**
Linktree is a website (https://linktr.ee) where you can add multiple links for various other websites. A linktree icon can be used as a link to a preexisting linktree, similar to other social media icons. 

**Example image (optional)**
[Linktree Logo
](https://blog-api.linktr.ee/app/uploads/2019/04/lsp_linktree_100419-113346.png)
![](https://blog-api.linktr.ee/app/uploads/2019/04/lsp_linktree_100419-113346.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-12-30 16:40
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17069, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-12-30 16:40 UTC
