### ISSUE TITLE
Icon Request: arrow-right-arrow-left-alt (smaller arrowheads)

### ISSUE THREAD

**Issue by babakfp** [FortAwesome/Font-Awesome#18979] opened 2022-04-30 11:56 UTC
![Screenshot 2022-04-30 045205](https://user-images.githubusercontent.com/44144724/166104446-e51f075f-7b4a-45e1-b4ca-d29b92bf8750.png)

Currently, there are similar icons but I like these more.

**Comment by tagliala** [comment] 2022-05-02 11:21
Hi!

We cannot use the same names of existing icons.

I think that `arrow-right-arrow-left` is a request for `right-long-left-long`

Demo: https://jsfiddle.net/tagliala/bfa6uhse/133/

As per the "time saving icon", I'm going to consider it a duplicate of #18870

**Comment by babakfp** [comment] 2022-05-02 13:17
Hi
Thank you for your response.

The shape of the arrow isn't actually like the [`caret` icon](https://fontawesome.com/icons/caret-right?s=solid). It's the same as the `arrow-right-arrow-left` **but shorter**. Name suggestion: `arrow-right-arrow-left-short`

![166104446-e51f075f-7b4a-45e1d-b4ca-d29b92bf8750](https://user-images.githubusercontent.com/44144724/166239885-21e5bea9-89e1-49a5-af19-733935797640.png)

![Screenshot 2022-05-02 062333](https://user-images.githubusercontent.com/44144724/166240956-e757d484-ed20-44bc-814d-d228bb9b9fb4.png)

---

> I think that arrow-right-arrow-left is a request for right-long-left-long
> Demo: https://jsfiddle.net/tagliala/bfa6uhse/133/

About this name: `right-long-left-long`. Can we use `caret-right-caret-left` instead? Because the head of the arrow looks like [the caret icon](https://fontawesome.com/icons/caret-right?s=solid)

---

> As per the "time saving icon", I'm going to consider it a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/18870

It's actually not the same because `clock-rotate-left` means times go back and `clock-rotate-right` means times go forward. But this icon kinda means `time-fast` or `time-saving` or something like that:

![166104446-e51f075f-7b4a-45e1-b4ca-d29b92bf87f50](https://user-images.githubusercontent.com/44144724/166239913-3a1a5adb-3c1c-4fef-8592-0b898320bbe8.png)

**Comment by tagliala** [comment] 2022-05-02 14:17
Hi,

> The shape of the arrow isn't actually like the [`caret` icon](https://fontawesome.com/icons/caret-right?s=solid). It's the same as the `arrow-right-arrow-left` **but shorter**. Name suggestion: `arrow-right-arrow-left-short`

Hi, so it is exactly the same as https://fontawesome.com/icons/arrow-right-arrow-left?s=solid but with smaller arrowheads. Will add an `alt`.

Preferring a style over another is legit of course, but this could apply to every existing icon in Font Awesome. Is there any reason why this could be a more objective criticism? Like "arrow heads are too big", or "the dashed circled line adds context" ?

> It's actually not the same because `clock-rotate-left` means times go back and `clock-rotate-right` means times go forward. But this icon kinda means `time-fast` or `time-saving` or something like that:

The represented icon is the same as the one in #18870, with exception of the dashed circle: https://jsfiddle.net/tagliala/bfa6uhse/125/

Feel free to open a new request, but according to font awesome naming scheme it is  `clock-rotate-right` with some addition

Since those icons are separated and unrelated, we should have two different requests

**Comment by babakfp** [comment] 2022-05-03 20:54
> Hi, so it is exactly the same as https://fontawesome.com/icons/arrow-right-arrow-left?s=solid but with smaller arrowheads. Will add an alt.

Yes.

> Preferring a style over another is legit of course, but this could apply to every existing icon in Font Awesome.

True.

> Is there any reason why this could be a more objective criticism? Like "arrow heads are too big", or "the dashed circled line adds context" ?

I never really liked `arrow-right-arrow-left` because the head of the arrows is too big (in my opinion) and I tried to find another icon to use instead. I guess it will be nice to have a smaller version too.

> The represented icon is the same as the one in https://github.com/FortAwesome/Font-Awesome/issues/18870, with exception of the dashed circle: https://jsfiddle.net/tagliala/bfa6uhse/125/

> Feel free to open a new request, but according to font awesome naming scheme it is clock-rotate-right with some addition

Cool, it makes sense.

> Since those icons are separated and unrelated, we should have two different requests

Sure. Thank you so much

**Comment by sensibleworld** [comment] 2024-07-11 15:14
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed as not planned by sensibleworld** 2024-07-11 15:14 UTC
Labels: new icon, arrows (category), Declined
