### ISSUE TITLE
Icon Request: fa-draugiem

### ISSUE THREAD

**Issue by Jalbertino** [FortAwesome/Font-Awesome#11405] opened 2017-08-15 06:51 UTC
Here in Latvia we have a social network called Draugiem.lv (similar to Facebook.com). So we need an brand icon, as almost every webpage in Latvia has Share/Follow icons for Draugiem.lv
Here you have icon in SVG format:
https://simpleicons.org/icons/draugiemlv.svg

**Comment by tagliala** [comment] 2017-08-15 08:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3865, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-15 08:49 UTC
