### ISSUE TITLE
Icon request:creative commons protocol

### ISSUE THREAD

**Issue by huoxingdawang** [FortAwesome/Font-Awesome#14078] opened 2018-10-08 02:29 UTC
cc-by:![](http://dev.juruoyun.top/data/cc/by.png)
cc-nc:![](http://dev.juruoyun.top/data/cc/nc.png)
cc-nd:![](http://dev.juruoyun.top/data/cc/nd.png)
cc-sa:![](http://dev.juruoyun.top/data/cc/sa.png)

**Comment by MikeWhelan** [comment] 2019-04-21 08:11
I second the request for Creative Commons icons. For reference, they are currently available as SVGs on the CC website: https://creativecommons.org/about/downloads

**Comment by aethior** [comment] 2022-04-15 03:56
These icons were added in v5.0.11. (dupe of #544)

`fa-creative-commons-by`: https://fontawesome.com/icons/creative-commons-by
`fa-creative-commons-nc`: https://fontawesome.com/icons/creative-commons-nc
`fa-creative-commons-nd`: https://fontawesome.com/icons/creative-commons-nd
`fa-creative-commons-sa`: https://fontawesome.com/icons/creative-commons-sa

Regards.

cc/ @tagliala

**Closed** 2022-04-15 07:27 UTC
