### ISSUE TITLE
Icon Request: fa-icecream

### ISSUE THREAD

**Issue by sdf1992** [FortAwesome/Font-Awesome#11780] opened 2017-11-21 17:51 UTC
Hello i need a icecream icon for my website

**Comment by tagliala** [comment] 2017-11-21 19:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1988, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-21 19:25 UTC
