### ISSUE TITLE
Icon request: offline/no-internet

### ISSUE THREAD

**Issue by denizduncan** [FortAwesome/Font-Awesome#10626] opened 2017-02-06 18:21 UTC

**Comment by tagliala** [comment] 2017-02-06 19:07
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #5555, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-06 19:07 UTC
