### ISSUE TITLE
Icon request: shower

### ISSUE THREAD

**Issue by MarGraz** [FortAwesome/Font-Awesome#9144] opened 2016-05-07 17:12 UTC
I'm creating a website for a B&B, and I saw that in fontawesome there isn't an icon to indicate shower.
It's possible to add this new icon to font awesome?

Thank you again

![shower](https://cloud.githubusercontent.com/assets/19241483/15093423/a21785d8-1487-11e6-8cd5-fc5d054e8ef6.png)

**Comment by tagliala** [comment] 2016-05-07 17:17
Duplicate of #708 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-07 17:17 UTC

**Comment by MarGraz** [comment] 2016-05-07 17:23
I'm sorry. 
I only cheked here http://fontawesome.io/icons/ and not for another request. 

Sorry :'(
