### ISSUE TITLE
Icon request: icon-burger

### ISSUE THREAD

**Issue by mrStenvik** [FortAwesome/Font-Awesome#10983] opened 2017-04-24 07:16 UTC
something in this area:

![burger](https://cloud.githubusercontent.com/assets/27947303/25326061/b3566470-28ce-11e7-8f1a-097a0ddf3313.JPG)

**Comment by PeterShaggyNoble** [comment] 2017-04-24 08:42
This is a duplicate of #1961, you should give that a 👍 instead.

**Closed** 2017-04-24 09:35 UTC
