### ISSUE TITLE
Icon request: floorplan

### ISSUE THREAD

**Issue by russrobertsnshare** [FortAwesome/Font-Awesome#20410] opened 2024-11-11 11:53 UTC
A layout or floorplan

This has many use cases amongst business applications from real estate to professional services such as property surveying.

Example from Icons8:

![floor-plan-80](https://github.com/user-attachments/assets/e99d8b07-9373-484d-ab96-d8f0dc2e7f5b)

**Comment by tagliala** [comment] 2024-11-11 15:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12064. No need to +1 that request, it has been accepted and it will be eventually be released 

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-11-11 15:17 UTC

**Comment by iMoshi** [comment] 2024-12-20 16:27
Been waiting since 2018.
