### ISSUE TITLE
Icon Request: fa-viber

### ISSUE THREAD

**Issue by khalildelavaran** [FortAwesome/Font-Awesome#3554] opened 2014-05-27 15:06 UTC

**Comment by YankoPetroff** [comment] 2015-01-13 13:06
+1

**Comment by camorazrushimoe** [comment] 2015-02-09 08:41
+1

**Comment by ojtibi** [comment] 2015-02-24 05:34
+1

**Comment by webkod3r** [comment] 2015-03-13 12:30
+1

**Comment by nazartokar** [comment] 2015-03-23 17:39
Thanks!

**Comment by sohrabtaee** [comment] 2015-04-13 08:36
+1

**Comment by zazoley** [comment] 2015-06-11 14:14
+1

**Comment by abbynucup** [comment] 2015-06-21 16:44
+1 please include viber in your next update :)

![51-ateybibl](https://cloud.githubusercontent.com/assets/9055708/8272510/cc53eff6-1877-11e5-9027-be2c57e802bd.png)

**Comment by PoshtibanHa** [comment] 2015-06-22 05:31
+1

**Comment by fobo66** [comment] 2015-06-27 08:51
+1

**Comment by igormukhingmailcom** [comment] 2015-07-06 13:49
+1

**Comment by nir0** [comment] 2015-07-09 06:47
+1

**Comment by cowabunga1** [comment] 2015-07-16 12:57
+1

**Comment by Genexys** [comment] 2015-07-31 08:15
+1

**Comment by davidapple** [comment] 2015-09-09 05:41
+1

**Comment by kukac7** [comment] 2015-09-09 16:48
temporarily to see if ... https://github.com/kukac7/fa-viber

**Comment by sebbio** [comment] 2015-09-14 14:35
+1

**Comment by kraymond70** [comment] 2015-09-14 21:52
+1

**Comment by dmitrue** [comment] 2015-09-30 06:00
+1

**Comment by lial** [comment] 2015-10-01 02:03
+1

**Comment by sundaycreative** [comment] 2015-10-01 17:43
+1

**Comment by wizardist** [comment] 2015-10-12 10:05
+1

**Comment by rahst12** [comment] 2015-10-20 16:13
+1

**Comment by AndrewLosev** [comment] 2015-10-30 07:22
Please, add a viber icon)

**Comment by isfak** [comment] 2015-11-05 08:34
+1

**Comment by hayatbiralem** [comment] 2015-11-09 00:02
+1

**Comment by njxqlus** [comment] 2015-11-10 06:35
+1

**Comment by oneumyvakin** [comment] 2015-11-14 14:56
+1

**Comment by ChezRD** [comment] 2015-11-19 04:32
+1

**Comment by G-Driver** [comment] 2015-11-19 15:00
+1

**Comment by lockz** [comment] 2015-11-26 04:54
+1

**Comment by infronte** [comment] 2015-12-07 09:01
+1

**Comment by cyberomulus** [comment] 2016-01-03 20:51
+1

**Comment by shilka** [comment] 2016-01-06 16:45
+1

**Comment by gEndelf** [comment] 2016-01-08 14:03
+1

**Comment by THPubs** [comment] 2016-01-10 06:23
+1 Viber is a very popular service :-) I was surprised to see you don't have support for it!

**Comment by jeanfredrik** [comment] 2016-01-11 10:24
+1

**Comment by Smile42RU** [comment] 2016-01-13 11:11
+1

**Comment by Kokil** [comment] 2016-01-14 11:21
+1

**Comment by xakpc** [comment] 2016-01-19 22:47
+1

**Comment by AndreiMotinga** [comment] 2016-01-24 21:33
+1

**Comment by SidiGi** [comment] 2016-01-27 09:21
+1

**Comment by Realnmn** [comment] 2016-02-17 17:39
+1

**Comment by designia** [comment] 2016-03-02 16:48
+1

**Comment by shov** [comment] 2016-03-07 15:42
+100500

**Comment by pcdro** [comment] 2016-03-17 13:43
+ 1

**Comment by xaben** [comment] 2016-03-19 15:21
+1

**Comment by ToBeCode** [comment] 2016-03-20 12:03
+1

**Comment by G-Driver** [comment] 2016-03-21 10:47
+1

**Comment by 3x14159265** [comment] 2016-03-22 17:36
+1

**Comment by OriksDesign** [comment] 2016-03-26 21:33
+1

**Comment by sanek4life** [comment] 2016-04-11 14:16
+1

**Comment by romapad** [comment] 2016-04-11 17:04
+1

**Comment by densenator** [comment] 2016-04-20 09:44
+1

**Comment by vadimpaj** [comment] 2016-05-29 14:02
+1

**Comment by vadimpaj** [comment] 2016-06-26 18:44
+1

**Comment by MOBECO** [comment] 2016-06-26 20:06
+1

**Comment by Bearberryy** [comment] 2016-06-29 09:47
+1

**Comment by mepoohsta** [comment] 2016-07-22 11:39
+1

**Comment by ratzxx** [comment] 2016-07-25 14:35
+1

**Comment by AndrewKiri** [comment] 2016-08-02 21:01
+1, a very needed icon

**Comment by glazkovan** [comment] 2016-08-16 12:22
+1

**Comment by uager** [comment] 2016-08-18 12:46
+1

**Comment by ArtMik** [comment] 2016-08-20 21:56
+1

**Comment by Shakil-Shahadat** [comment] 2016-08-24 23:29
+1

**Comment by gNesh01** [comment] 2016-08-30 10:33
+1

**Comment by citypeople** [comment] 2016-09-02 09:56
+1

**Comment by ChrisGalliano** [comment] 2016-10-04 15:00
+1

**Comment by serjsv87** [comment] 2016-10-07 20:24
+1

**Comment by DmytroLavryk** [comment] 2016-10-09 04:58
+1

**Comment by stereodenis** [comment] 2016-10-14 09:53
+1

**Comment by cyberlex404** [comment] 2016-10-31 01:49
+1

**Comment by 1gory** [comment] 2016-11-04 11:50
Why still not added?

**Comment by AlexandrKharchenko** [comment] 2016-11-23 12:26
++++

**Comment by Magic03** [comment] 2016-12-05 14:41
+1

**Comment by wblabs** [comment] 2016-12-14 23:43
+100

**Comment by muyassarov** [comment] 2017-01-09 14:25
+1

**Comment by KellerPT** [comment] 2017-01-11 12:37
+1000

**Comment by yeahga** [comment] 2017-01-20 05:46
+1

**Comment by vasilychapaev** [comment] 2017-01-23 12:00
+1

**Comment by xikarx** [comment] 2017-01-25 14:07
+1

**Comment by hotrush** [comment] 2017-01-27 16:11
3 years, hello...

**Comment by olgashavrina** [comment] 2017-01-31 10:56
+1 please!!!

**Comment by kironet** [comment] 2017-01-31 11:00
hmm...

**Comment by ShamanFromSiberia** [comment] 2017-02-02 21:49
+1 please please please!!!!!!!!!!!!

**Comment by ShamanFromSiberia** [comment] 2017-02-02 21:54
How many years should people wait? I feel deep gratitude for you guys for your awesome job, but please, please listen to what people ask for so many years. We have WhatsApp icon and Telegram, but Viber is needed no less by many of us. Thank you in advance

**Comment by Balya** [comment] 2017-02-03 14:10
+1

**Comment by Magic03** [comment] 2017-02-06 03:48
+++++++++++++++1

**Comment by bitrixlviv** [comment] 2017-02-10 08:21
+111

**Comment by Ilya-Valasiuk** [comment] 2017-02-11 15:17
+1

**Comment by vbogdana** [comment] 2017-02-17 14:14
+1

**Comment by asbeseda** [comment] 2017-02-25 16:48
+1

**Comment by obykoo** [comment] 2017-02-27 13:17
+1

**Comment by gitkv** [comment] 2017-03-01 14:05
+1

**Comment by maciejszpyra** [comment] 2017-03-06 13:59
+1

**Comment by kironet** [comment] 2017-03-09 09:30
looks like they are joking, 3 years waiting for viber icon lol.

**Comment by glebkema** [comment] 2017-03-24 11:58
+1

**Comment by manix** [comment] 2017-03-31 14:52
+1

**Comment by sedrakpc** [comment] 2017-04-05 16:26
+1

**Comment by qwq-qwq** [comment] 2017-04-07 20:06
Somebody does not like Viber

**Comment by Matvik** [comment] 2017-04-08 17:06
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by aralex** [comment] 2017-04-12 08:17
+1

**Comment by olehpratsko** [comment] 2017-04-15 20:31
+1

**Comment by fewdji** [comment] 2017-05-16 11:28
+100500

**Comment by Kila14** [comment] 2017-05-24 06:08
+1

**Comment by visualpharm** [comment] 2017-06-03 19:08
I've started a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

[The Viber icon is here](https://icons8.com/icon/44468/viber).

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Xbox](https://icons8.com/icon/12473/xbox), [Nintendo Wii U](https://icons8.com/icon/16297/nintendo-wii-u), [Nintendo](https://icons8.com/icon/16294/nintendo), [PlayStation](https://icons8.com/icon/12461/playstation), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830), [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534), [clean](https://github.com/FortAwesome/Font-Awesome/issues/239#issuecomment-304473340) and [math](https://github.com/FortAwesome/Font-Awesome/issues/1133#issuecomment-304470923) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file.

**Comment by juniorV** [comment] 2017-06-14 15:09
+1

**Comment by mr-pavlenko** [comment] 2017-06-18 16:28
+

**Comment by amsokol** [comment] 2017-06-21 17:53
+1

**Comment by vvnab** [comment] 2017-06-29 13:12
+1

**Comment by gtomas41** [comment] 2017-07-03 16:29
+1

**Comment by MrHidalgo** [comment] 2017-07-04 16:39
+1

**Comment by Develtomas** [comment] 2017-07-08 08:33
Please, add the viber icon.

**Comment by AlexxStrelka** [comment] 2017-07-10 19:40
+1

**Comment by gre4aniy** [comment] 2017-07-17 10:23
+1

**Comment by AmaranthLIS** [comment] 2017-08-22 13:22
+1

**Comment by vpotap** [comment] 2017-09-05 16:41
+1

**Comment by ShellyViber** [comment] 2017-09-14 09:55
+1

**Comment by ShellyViber** [comment] 2017-09-14 09:56
Hi, I actually work for Viber and can provide the relevant and updates icon. Please talk to me.
[Viber.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/1302547/Viber.svg.zip)

**Comment by ozradiano** [comment] 2017-09-14 10:05
+999

**Comment by shocher1** [comment] 2017-09-14 10:09
+1

**Comment by user1402** [comment] 2017-09-14 10:10
+1

**Comment by morpanda** [comment] 2017-09-14 10:17
+1

**Comment by tagliala** [comment] 2017-09-22 16:45
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Closed by tagliala** 2017-09-22 16:45 UTC
Labels: brand icons, new icon

**Comment by ShellyViber** [comment] 2017-09-24 08:05
Hi @tagliala, thank you!! Please make sure that you are using the updated version of the icon. Attached. 
[Viber.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/1327121/Viber.svg.zip)

**Comment by tagliala** [comment] 2017-09-24 08:27
@ShellyViber I can confirm that the icon checked in the FA5 Pro repo (and also available in FA5 Free) is the one you posted.

Thanks for the heads-up

**Comment by ShamanFromSiberia** [comment] 2017-10-10 17:47
Oh I found it! Thank you, waiting for v.5!!

**Comment by parfilov** [comment] 2017-11-16 14:32
+1

**Comment by mokhin-denis** [comment] 2017-11-30 12:47
+1

**Comment by alex21** [comment] 2017-12-26 09:24
They will not add this icon. Don't waste your time.
Thread was started 2014 but now is almost 2018 and nothing was changed.

**Comment by parfilov** [comment] 2017-12-26 09:27
@alex21 They already did it but in FA5

**Comment by tagliala** [comment] 2017-12-26 12:09
Viber is available in FA5 for Free and Pro users

https://fontawesome.com/icons/viber?style=brands

Webfont (FREE): https://jsfiddle.net/tagliala/tgzouajm/45/
SVG (FREE): https://jsfiddle.net/tagliala/f019sa7v/9/

Locking here 🔒
