### ISSUE TITLE
Icon Request: fa-cd

### ISSUE THREAD

**Issue by n0krashy** [FortAwesome/Font-Awesome#11639] opened 2017-10-17 17:46 UTC
CD player icon to use for songs
![image](https://user-images.githubusercontent.com/20645481/31680185-39c6a65e-b37c-11e7-9872-69fec80f33cf.png)

**Comment by tagliala** [comment] 2017-10-17 21:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #702 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-17 21:10 UTC
