### ISSUE TITLE
Icon Request: fa-messenger

### ISSUE THREAD

**Issue by oli7** [FortAwesome/Font-Awesome#11305] opened 2017-07-18 10:27 UTC
Please, it would be possible to create a new facebook - messenger icon? I like to use FA. Thank you very much. Olga.

**Comment by tagliala** [comment] 2017-07-18 10:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6912 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-18 10:28 UTC
