### ISSUE TITLE
Origin

### ISSUE THREAD

**Issue by falconnz** [FortAwesome/Font-Awesome#17880] opened 2021-05-06 10:21 UTC
a origin platform icon, at least we have steam, xbox and playstation.
:)
![image](https://user-images.githubusercontent.com/56550873/117282756-02607700-ae5d-11eb-920c-d2fa2fc5e6df.png)

**Comment by tagliala** [comment] 2021-05-06 10:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1290, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-05-06 10:27 UTC
