### ISSUE TITLE
Icon Request: fa-coursera

### ISSUE THREAD

**Issue by RalphRezendeLarsen** [FortAwesome/Font-Awesome#7218] opened 2015-08-13 01:41 UTC
I am the co owner of Prodii.com wich logo Im requesting you to add. Im using awesome fonts because they are awesome.
We are using awesome fonts for all our brand icons on Prodii.
Please keep up the good work.

Thanx in advance,
Ralph Rezende Larsen/Prodii

![logo-facebook](https://cloud.githubusercontent.com/assets/2788038/9241125/8c2163b8-4145-11e5-88ad-a627312fc9aa.png)

**Comment by RalphRezendeLarsen** [comment] 2015-08-13 01:42
![logo-facebook](https://cloud.githubusercontent.com/assets/2788038/9240976/6be7015e-4143-11e5-92a9-0d671a684299.png)

**Comment by RalphRezendeLarsen** [comment] 2015-08-13 01:51
Hi Im the co-owner at Prodii.com, and I think that a brand icon for Coursera are badly missing.

**Comment by TheChen5** [comment] 2015-08-13 02:30
So is this a request for *both* Coursera and Prodii?
Coursera is already a dupe of #2609 
+1 that
Remember to :mag:
If you want a request for Prodii, you should create a new issue

**Closed** 2015-08-13 10:18 UTC
