### ISSUE TITLE
Icon Request: fa-blogspot

### ISSUE THREAD

**Issue by hiseka** [FortAwesome/Font-Awesome#8587] opened 2016-02-16 11:49 UTC
I hope I add the icon.

![images](https://cloud.githubusercontent.com/assets/8023404/13075470/b951554a-d4ee-11e5-875f-52e8b64f72ae.jpg)

**Comment by tagliala** [comment] 2016-02-16 12:00
duplicate of #1088, please +1 that request

closing here

**Closed by tagliala** 2016-02-16 12:00 UTC
