### ISSUE TITLE
Brand request: Gumroad

### ISSUE THREAD

**Issue by not-available-username** [FortAwesome/Font-Awesome#20043] opened 2023-12-12 10:09 UTC
### Description

One well-known online marketplace for creators is Gumroad. For independent artists or anyone launching their own Gumroad marketplace and wanting a direct connection to their profile, an icon can be useful.

Official SVG: https://assets-global.website-files.com/6171b265e5c8aa59b42c3472/618f28a89e94524552a002cb_g-icon.svg

### Official website

https://gumroad.com/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2023-12-12 10:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16066, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-12-12 10:17 UTC
Labels: brand icon

**Comment by not-available-username** [comment] 2023-12-12 10:29
@tagliala why? https://github.com/FortAwesome/Font-Awesome/issues/16066 it's marked as closed, but the icon wasn't added. Why marking this task as closed?

**Comment by tagliala** [comment] 2023-12-12 10:37
@not-available-username it's correctly open. But I guess that in the history there is a referenced duplicate marked as closed that may be confusing
