### ISSUE TITLE
Icon request: Scroll-paper

### ISSUE THREAD

**Issue by giufalab** [FortAwesome/Font-Awesome#10292] opened 2016-11-28 19:01 UTC
I need this icon for a company web site in the section "our Mission".

![scroll-paper](https://cloud.githubusercontent.com/assets/24232291/20681772/5eea7684-b5a5-11e6-8813-b862466302b4.png)

Thanks

**Comment by tagliala** [comment] 2016-11-28 20:18
Duplicate of #1173, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-28 20:18 UTC
