### ISSUE TITLE
styles.css is missing in sideEffects in package.json, prevents inclusion of CSS

### ISSUE THREAD

**Issue by hpohl** [FortAwesome/Font-Awesome#18773] opened 2022-03-04 16:05 UTC
styles.css is missing in the `sideEffects` in `package.json` in `@fortawesome/fontawesome-svg-core` since v1.3.0. It does not get included when using css-loader.

**Comment by tagliala** [comment] 2022-03-04 16:12
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I believe this is a duplicate of #18654

Closing here, but feel free to comment and provide more information if I didn't get this request

**Closed as completed by tagliala** 2022-03-04 16:12 UTC
