### ISSUE TITLE
Icon Request: fa-door-closed

### ISSUE THREAD

**Issue by viewpoint** [FortAwesome/Font-Awesome#8743] opened 2016-03-12 14:27 UTC
I want to give the idea of a meeting room icon. I thought a closed door would be good. Useful for all sorts of things too. I submitted another issue for an open door as well. So, open and closed doors.

**Comment by tagliala** [comment] 2016-03-13 13:55
Duplicate of #2921, please +1 that request

closing here

**Closed by tagliala** 2016-03-13 13:55 UTC
