### ISSUE TITLE
Icon Request: fa-sqft

### ISSUE THREAD

**Issue by FastEddie8888** [FortAwesome/Font-Awesome#6532] opened 2015-05-21 23:36 UTC
Something like a ruler with a square
![image](https://cloud.githubusercontent.com/assets/6530213/7761165/3c8df6f4-ffd7-11e4-855a-cd30b21ea166.png)

or house with arrows
![image](https://cloud.githubusercontent.com/assets/6530213/7761171/77fa6e66-ffd7-11e4-93f4-8fb0b6aa4963.png)

**Comment by tagliala** [comment] 2015-06-06 14:57
duplicate of #1096 , please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-06-06 14:57 UTC
