### ISSUE TITLE
Icon request: icon-new

### ISSUE THREAD

**Issue by madhotshoe** [FortAwesome/Font-Awesome#16165] opened 2020-02-08 14:37 UTC
I would like an icon that is an oval with the word New inside.  I plan on using this on my photos and products that I posted on my website as new within a certain time period and only for a certain time period which is controlled by my code.  I currently use a fa-flag for this but have to add wording on the webpage to let people know what it means.  BTW, My website is keylightphotography.net if you want to look at the galleries and photos to see what I mean.  Thanks!!!!

**Comment by tagliala** [comment] 2020-02-08 16:23
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #11002, please upvote that request

At the moment we are trying our best to avoid words in icons. I can suggest you to use an alternate approach, by layering text and icons, as suggested here: https://fontawesome.com/how-to-use/on-the-web/styling/layering

Closing here

**Closed by tagliala** 2020-02-08 16:23 UTC
