### ISSUE TITLE
Icon Request: fa-waves

### ISSUE THREAD

**Issue by idox61** [FortAwesome/Font-Awesome#11296] opened 2017-07-16 14:14 UTC
![waves](https://user-images.githubusercontent.com/8151160/28248250-d448c1fa-6a41-11e7-81b2-331a80c82396.png)

**Comment by tagliala** [comment] 2017-07-16 16:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2266, please add a 👍  reaction to that request and post there your example.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-16 16:00 UTC
