### ISSUE TITLE
Icon request: icon-checklist

### ISSUE THREAD

**Issue by webbushka** [FortAwesome/Font-Awesome#1230] opened 2013-06-06 14:15 UTC
It would be very useful to have a checklist icon similar to:

[this](http://cdn3.iconfinder.com/data/icons/files/100/237035-file_document_checklist_todo-128.png) or [this](http://cdn2.iconfinder.com/data/icons/picons-essentials/57/checklist-128.png)

if you went with the clipboard one it could use the same clipboard that you do for #773

**Comment by QueenMerla** [comment] 2015-10-07 22:30
+1

**Comment by jeffhuys** [comment] 2016-01-26 10:27
+1

**Comment by pablo-meyer** [comment] 2016-03-14 18:37
+1

**Comment by nukulb** [comment] 2016-03-26 20:29
+1

**Comment by AndreLGava** [comment] 2016-04-16 13:40
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-checklist was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by JosMarRivera** [comment] 2016-04-22 09:42
+1

**Comment by argonautical** [comment] 2016-05-28 14:58
+1

**Comment by tagliala** [comment] 2016-06-19 17:46
This is probably a duplicate of #896

I'm going to close this one and add "checklist" to #896's title

**Closed by tagliala** 2016-06-19 17:46 UTC
Labels: new icon, web application icons
