### ISSUE TITLE
Icon Request: fa-goodreads

### ISSUE THREAD

**Issue by MileAcero** [FortAwesome/Font-Awesome#7065] opened 2015-07-29 00:26 UTC
hi my name is michelle and i'd like to request an icon for the page goodreads, this is a page where people can look up for books information and authors then people can do reviews and stuff about the books.
i'd like to have this icon in my blog where i write reviews of books i've read , and i want people to read and know more about the books i review so they can click the icon and search, read more opinions, etc.
sincerelly thank you :) 

<img width="256" alt="goodreads_socialnetwork_19977" src="https://cloud.githubusercontent.com/assets/13545072/8943809/47d31d32-3542-11e5-948e-9868953ff4be.png">

**Comment by TheChen5** [comment] 2015-07-29 01:27
Dupe of #1715 
+1 that

**Comment by tagliala** [comment] 2015-07-29 08:38
@TheChen5 thanks

**Closed by tagliala** 2015-07-29 08:38 UTC
