### ISSUE TITLE
Request for new icon

### ISSUE THREAD

**Issue by quaisar** [FortAwesome/Font-Awesome#10117] opened 2016-10-26 08:29 UTC
Hello sir can you please add a new icon in Font-Awesome 
That is "Blog" icon see the link below
http://www.logospike.com/wp-content/uploads/2014/11/Blogger_logo-4.png

**Comment by tagliala** [comment] 2016-10-26 10:13
Duplicate of #1088 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-26 10:13 UTC
