### ISSUE TITLE
Icon-Request: fa-tracks

### ISSUE THREAD

**Issue by agrafix** [FortAwesome/Font-Awesome#5801] opened 2015-02-27 10:46 UTC
Would it be possible to provide icons for train tracks? Maybe a straight one, a turnover and a crossing?

**Comment by tagliala** [comment] 2015-03-11 10:07
could you please post single color examples suitable for 14px icon size?

**Comment by purplelady105** [comment] 2019-08-02 15:25
It could be something as simple as this...
![image](https://user-images.githubusercontent.com/28715727/62380905-1bf1c380-b4ff-11e9-829a-52460647a27e.png)

**Comment by tagliala** [comment] 2019-08-02 15:48
Hi, 

this is probably a duplicate of #5099

An example is available at https://github.com/FortAwesome/Font-Awesome/issues/5099#issuecomment-466988827

Please add a 👍 to that request

**Closed by tagliala** 2019-08-02 15:48 UTC
Labels: waiting for feedback
