### ISSUE TITLE
Icon request: fa-door-open, fa-door-closed

### ISSUE THREAD

**Issue by hegemoon** [FortAwesome/Font-Awesome#10603] opened 2017-02-01 19:12 UTC
![room-door-closed](https://cloud.githubusercontent.com/assets/967355/22522117/7639bf0a-e888-11e6-84f0-dbc47243c226.png)
![room-door-open](https://cloud.githubusercontent.com/assets/967355/22522118/763b9e38-e888-11e6-9ee1-68c014cac12b.png)

**Comment by tagliala** [comment] 2017-02-01 19:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2921 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-01 19:27 UTC
