### ISSUE TITLE
social icons request 

### ISSUE THREAD

**Issue by gabriellaortiz** [FortAwesome/Font-Awesome#17169] opened 2020-09-17 21:39 UTC
Hi! Would it be possible to request WeChat and Little Red Book (Xiaohongshu) social icons? I'd love to continue using Font Awesome but need these icons available. 

![XiaohongshuLOGO-1](https://user-images.githubusercontent.com/19807999/93531098-aae0bb80-f90c-11ea-9adf-77ee1e790469.png)

![wechat](https://user-images.githubusercontent.com/19807999/93531123-b633e700-f90c-11ea-83d6-2d00e57ebc1d.png)

**Comment by tagliala** [comment] 2020-09-18 07:09
Hi!

Thanks for being part of the Font Awesome Community.

Little Red Book is a duplicate of #16569, please add a 👍 reaction to that request.

WeChat is a duplicate of #1505, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-18 07:09 UTC

**Comment by ferujhossain01777-prog** [comment] 2026-03-28 05:37
> Hi! Would it be possible to request WeChat and Little Red Book (Xiaohongshu) social icons? I'd love to continue using Font Awesome but need these icons available. 
> 
> ![XiaohongshuLOGO-1](https://user-images.githubusercontent.com/19807999/93531098-aae0bb80-f90c-11ea-9adf-77ee1e790469.png)
> 
> ![wechat](https://user-images.githubusercontent.com/19807999/93531123-b633e700-f90c-11ea-83d6-2d00e57ebc1d.png)
>

**Comment by ferujhossain01777-prog** [comment] 2026-03-28 05:37
> > Hi! Would it be possible to request WeChat and Little Red Book (Xiaohongshu) social icons? I'd love to continue using Font Awesome but need these icons available. 
> > 
> > ![XiaohongshuLOGO-1](https://user-images.githubusercontent.com/19807999/93531098-aae0bb80-f90c-11ea-9adf-77ee1e790469.png)
> > 
> > ![wechat](https://user-images.githubusercontent.com/19807999/93531123-b633e700-f90c-11ea-83d6-2d00e57ebc1d.png)
> > 
> 
>
