### ISSUE TITLE
Inconsistent icon alignment

### ISSUE THREAD

**Issue by odan** [FortAwesome/Font-Awesome#14478] opened 2019-01-07 09:54 UTC
When stacked in a Bootstrap Navbar dropdown, the icons don't align very well (see screenshot for example)

![image](https://user-images.githubusercontent.com/781074/50761253-31a15200-126a-11e9-9033-25cfe4665234.png)

In version 3.x this was never a problem. I'm using Font-Awesome version 5.6.3 now.

**Comment by tagliala** [comment] 2019-01-07 12:42
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome icons have not the same width by design choice.

Please add `fa-fw` class to your icons

Hope it helps

Closing here

**Closed by tagliala** 2019-01-07 12:42 UTC
