### ISSUE TITLE
Icon request: fa-chair

### ISSUE THREAD

**Issue by viewpoint** [FortAwesome/Font-Awesome#10567] opened 2017-01-25 12:54 UTC
Can you add a sofa icon to represent a reception room for estate agent websites.

**Comment by tagliala** [comment] 2017-01-25 13:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1998 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-25 13:05 UTC
