### ISSUE TITLE
Clapping Hand Icons

### ISSUE THREAD

**Issue by fajarsiddiqfs** [FortAwesome/Font-Awesome#16970] opened 2020-08-01 12:49 UTC
Hey FontAwesome - Will you add "clap" 👏 Clapping hands icon?

![Group 1](https://user-images.githubusercontent.com/20717334/89102080-5e165380-d438-11ea-848e-339774c6ee7b.png)

**Comment by tagliala** [comment] 2020-08-01 12:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1258, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-08-01 12:50 UTC
