### ISSUE TITLE
Add cup filter to fa-trophy

### ISSUE THREAD

**Issue by Zhouxing-Su** [FortAwesome/Font-Awesome#9778] opened 2016-08-19 08:45 UTC
Please add medal or cup which may be used in CV for items of honors and awards.

**Comment by tagliala** [comment] 2016-08-19 09:32
medal: #1898 

Leaving this open as `fa-cup`

**Comment by tagliala** [comment] 2016-08-19 09:33
Ref: #4601

**Comment by aethior** [comment] 2016-10-01 07:29
@tagliala Duplicate of `fa-trophy` (http://fontawesome.io/icon/trophy/) icon?

**Comment by tagliala** [comment] 2016-10-01 11:39
fff, sure.

**Closed** 2016-10-01 15:14 UTC
Labels: doc
