### ISSUE TITLE
Icon request: icon-cabinet

### ISSUE THREAD

**Issue by Tuutje** [FortAwesome/Font-Awesome#14719] opened 2019-03-06 13:39 UTC
### What can it be used for?
icon table and cabinet for wordpress

### Example image (optional)
https://www.iconfinder.com/icons/318393/dinning_room_dinning_table_furniture_table_icon
https://www.iconfinder.com/icons/3954590/books_cabinet_furniture_library_shelf_icon

### Icon request checklist

- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-03-06 14:52
Hi!

Thanks for being part of the Font Awesome Community.

Table is possibly a duplicate of #4149, please add a 👍 reaction to that request.

Leaving this open as fa-cabinet

PS: coukd you please clarify what "for wordpress" meant?

**Comment by Tuutje** [comment] 2019-03-06 15:09
Hello,
No, i want no restaurant table...i want a blank table.
And i want to use it on my wordpress website...

Op wo 6 mrt. 2019 16:03 schreef Geremia Taglialatela <
notifications@github.com>:

**Comment by Tuutje** [comment] 2019-03-06 15:13
Plus #4149 is 4 years old... And there still no icon

**Comment by tagliala** [comment] 2019-03-06 15:48
@Tuutje please take a look [Icon Leaderbord](https://fontawesome.com/community/leaderboard/new), it provides a lot of information on how requests work

**Comment by sensibleworld** [comment] 2024-07-11 19:07
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 19:07 UTC
Labels: new icon, web application icons (legacy category), Declined
