### ISSUE TITLE
Icon Request: icon-table (forniture)

### ISSUE THREAD

**Issue by Lukino2000** [FortAwesome/Font-Awesome#3519] opened 2014-05-23 01:10 UTC
You can use it for a forniture category in an ecommerce site
![house-and-appliances-table-icon](https://cloud.githubusercontent.com/assets/4662268/3062122/0da77934-e217-11e3-8c0a-c38d51bc9447.png)
![houseware-table-icon](https://cloud.githubusercontent.com/assets/4662268/3062123/0da7c100-e217-11e3-80bc-273c294b0968.png)

**Comment by geskill** [comment] 2022-01-06 17:38
I use `fa-solid fa-tv-alt fa-flip-vertical` as a workaround.
![image](https://user-images.githubusercontent.com/6826752/148425865-2ef5fbb3-e355-4722-9c61-70d0c10b5f41.png)

**Comment by aethior** [comment] 2022-05-20 13:33
@tagliala `household (category)` label for this request?

**Comment by lucajung** [comment] 2023-10-03 17:23
+1

**Comment by sensibleworld** [comment] 2024-07-11 13:56
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/4149)

**Closed by sensibleworld** 2024-07-11 13:56 UTC
Labels: new icon, household (category), Duplicate
