### ISSUE TITLE
Icon request: icon-desks / icon-tables

### ISSUE THREAD

**Issue by seniorpreacher** [FortAwesome/Font-Awesome#15910] opened 2019-12-05 21:17 UTC
I'm currently working on a restaurant POS system, and noticed the absence of desks in FA.
I made one to represent tables in the restaurant:

<img width="121" alt="Screenshot 2019-12-05 at 22 04 19" src="https://user-images.githubusercontent.com/496380/70274604-bb280f80-17ac-11ea-9b75-a90d86efff87.png">

(I made it from the bottom part of the light chair icon 😄)

It would be great to see a professional version of this in FA.

**Comment by tagliala** [comment] 2019-12-06 07:44
IIRC this is a duplicate

**Comment by seniorpreacher** [comment] 2019-12-06 08:54
> IIRC this is a duplicate

Sorry, I couldn't find any similar request. Could you link it, so I can give it a 👍 ?

**Comment by jobjen02** [comment] 2020-11-18 20:07
+1
I'am also working on a restaurant POS system, and I have the same problem. No icon

**Comment by sensibleworld** [comment] 2024-07-11 18:22
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.]()

**Closed by sensibleworld** 2024-07-11 18:22 UTC
Labels: new icon, web application icons (legacy category), Duplicate

**Comment by seniorpreacher** [comment] 2024-07-12 11:57
@sensibleworld It's great to see some activity on this old issue. However you just linked this very same issue as the source of duplication. 
Yet, I still can not find any desks or tables in Font Awesome. (checked on the website, as I'm not an active user anymore)

Okay, there is the picnic table icon, which is weird to have instead of a simple table.

**Comment by sensibleworld** [comment] 2024-07-12 12:38
Sorry about that! We were sorting through a LOT of icon requests and may have gotten few wires crossed. We have a few other open icon requests for tables, and are going to be tracking this request there.

**Comment by seniorpreacher** [comment] 2024-07-12 13:06
Thanks! No worries, I see you are making some huge house cleaning :)

For anyone finding this issue, I believe [this is](https://github.com/FortAwesome/Font-Awesome/issues/4149) the successor.
