### ISSUE TITLE
Icon Request: fa-moneybag

### ISSUE THREAD

**Issue by mnemonik23** [FortAwesome/Font-Awesome#6783] opened 2015-06-18 18:35 UTC
New icon with money bag / dollar sign on it. Will be used on websites.
Similar to 
https://www.colourbox.com/preview/11522172-money-bag-icon-on-black-background-vector.jpg

**Comment by jlr7245** [comment] 2015-06-25 21:00
+1

**Comment by tagliala** [comment] 2015-06-30 18:40
duplicate of #1414 , please +1 that request

closing here

**Closed by tagliala** 2015-06-30 18:40 UTC
