### ISSUE TITLE
Icon Request: fa-disc

### ISSUE THREAD

**Issue by therese-william** [FortAwesome/Font-Awesome#6887] opened 2015-07-07 02:54 UTC
![music](https://cloud.githubusercontent.com/assets/6394655/8537798/40dca9ae-24a7-11e5-8d80-c204a3378f97.png)

please include an icon for CD

**Comment by tagliala** [comment] 2015-07-07 08:56
duplicate of #702 , please +1 that request

closing here

**Closed by tagliala** 2015-07-07 08:56 UTC
