### ISSUE TITLE
Icon Request: fa-calendar-week

### ISSUE THREAD

**Issue by imjaypatel** [FortAwesome/Font-Awesome#9484] opened 2016-06-28 06:17 UTC
Open this [link](http://i.stack.imgur.com/2HN7V.png), view the first icon. That icon represent calendar display in weekly (week wise).

Same as Icon Request following:
fa-calendar-month : represent calendar display in monthly.
fa-calendar-one : represent calendar display only today date.

Thanks

**Comment by aethior** [comment] 2016-06-28 08:12
Duplicate of #3609. Please comment the original request (#3609) adding your example to avoid duplicate requests.

**Closed** 2016-06-28 11:59 UTC
