### ISSUE TITLE
i need icq icon

### ISSUE THREAD

**Issue by lucky66** [FortAwesome/Font-Awesome#8984] opened 2016-04-14 14:03 UTC
i need icq icon

**Comment by PeterShaggyNoble** [comment] 2016-04-14 15:10
Dupe of [#1272](https://github.com/FortAwesome/Font-Awesome/issues/1272), you should +1 that instead.

**Closed** 2016-04-14 15:43 UTC

**Comment by AlexMcowkin** [comment] 2016-12-13 15:15
+1
we still need it
