### ISSUE TITLE
Icon Request: fa-globe-xxx

### ISSUE THREAD

**Issue by dejudicibus** [FortAwesome/Font-Awesome#12102] opened 2018-01-15 12:11 UTC
Currently there is only one globe icon, showing the North America continent.
I propose to extend globe icons to:
fa-globe-na-sa (Americas)
![image](https://user-images.githubusercontent.com/1431440/34941613-c74a1d76-f9f4-11e7-95e3-eff6769c7c73.png)
fa-globe-eu-af (Europe & Africa)
![image](https://user-images.githubusercontent.com/1431440/34941628-d98efa9c-f9f4-11e7-8bc1-0db672bb3c08.png)
fa-globe-as-oc (Asia and Oceania)
![image](https://user-images.githubusercontent.com/1431440/34941650-ea1b3a38-f9f4-11e7-84f8-14e01a48ccd2.png)
fa-globe-ao (Atlantic Ocean)
![image](https://user-images.githubusercontent.com/1431440/34941667-fd1c5fea-f9f4-11e7-954c-d2ad661dbce9.png)
fa-globe-po (Pacific Ocean)
![image](https://user-images.githubusercontent.com/1431440/34942008-55a14ea4-f9f6-11e7-977d-4e7a09b0fd47.png)
fa-globe-an (Antarctic)
![image](https://user-images.githubusercontent.com/1431440/34942286-60f635ac-f9f7-11e7-8dbf-6cdc7719d800.png)
fa-globe-wired (Wireframe)
![image](https://user-images.githubusercontent.com/1431440/34941746-599c9550-f9f5-11e7-9764-b4564dff6b42.png)
Thank you in advance.

**Comment by tagliala** [comment] 2018-01-15 12:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #281 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-15 12:28 UTC
