### ISSUE TITLE
Icon request: Periodic table of the elements

### ISSUE THREAD

**Issue by PibbzTV** [FortAwesome/Font-Awesome#19280] opened 2022-08-22 20:41 UTC
Hey! Would love icons for each symbol of the elements in the periodic table.

![U](https://user-images.githubusercontent.com/51060651/186015306-d7d7e072-d261-486a-8c91-25a0bde92487.png)

![Li](https://user-images.githubusercontent.com/51060651/186015462-63184531-04b8-43c9-b0f0-c14cad84d690.png)

**Comment by tagliala** [comment] 2022-08-22 20:49
Hi!

Thanks for being part of the Font Awesome Community.

This is actually a request for more than 400 icons and is a duplicate of #9020, labeled with wontfix at the time

I'm going to post a comment there

**Closed as completed by tagliala** 2022-08-22 20:49 UTC
