### ISSUE TITLE
Icon request: Fa-mushroom

### ISSUE THREAD

**Issue by keys101** [FortAwesome/Font-Awesome#11134] opened 2017-06-04 10:07 UTC
I run a business selling Grow your own Mushroom Kits, would be handy to have a mushroom icon and if possible two size of icons of the mushroom to signify growth, and a spray icon to signify watering would be amazing

**Comment by keys101** [comment] 2017-06-04 10:08
![105-512](https://cloud.githubusercontent.com/assets/29174449/26760636/15baacae-4916-11e7-83de-20d26391182d.png)

Something like this

**Comment by tagliala** [comment] 2017-06-04 10:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4127, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-04 10:16 UTC
