### ISSUE TITLE
Bug: fa-circle-o-notch

### ISSUE THREAD

**Issue by JayHoltslander** [FortAwesome/Font-Awesome#7055] opened 2015-07-27 19:20 UTC
There is an irregular "dent" in the icon fa-circle-o-notch that is clearly visible directly opposite of the notch if you also use the classes .fa-spin and fa-5x

**Comment by tagliala** [comment] 2015-07-27 20:11
sorry I didn't get this bug.

Could you please provide a screenshot or a fiddle showing the issue?

**Comment by tvirelli** [comment] 2015-08-06 04:14
@JayHoltslander & @tagliala , I can confirm this. Here is a JSFIddle I created: http://jsfiddle.net/jo9qjbw4/

I also attache a screen shot of the "Dent". It is almost a "flat spot".

![notch](https://cloud.githubusercontent.com/assets/1253043/9103748/9bfc95c4-3bc7-11e5-9aa0-334924fdf3c0.jpg)

**Comment by JayHoltslander** [comment] 2015-08-06 18:08
@tvirelli Thanks. Yup that's it.
@tagliala Sorry I missed seeing your request earlier.

**Comment by tagliala** [comment] 2015-08-07 14:34
@tvirelli thanks

Adding to 4.4.1 milestone, so Dave will eventually take a look

I'm not 100% that this is a bug

**Comment by davegandy** [comment] 2015-11-19 20:38
Such excellent bug reporting. Thank you @tvirelli for the jsFiddle and screenshot.

Looks like this is not happening on retina for Chrome or Firefox in downsampled mode on retina. But it does show up on Safari. Investigating. Have some ideas.

**Comment by davegandy** [comment] 2015-11-19 20:40
@tvirelli Specifically what browser/OS/retina were those screenshots taken with?

**Comment by davegandy** [comment] 2015-11-19 20:45
Okay, think I have it fixed in 4.4.1-wip branch. If not, let me know. Closing for now.

**Closed by davegandy** 2015-11-19 20:45 UTC
Labels: bug, web application icons
