### ISSUE TITLE
Icon Request: icon-clothes / icon-hanger

### ISSUE THREAD

**Issue by powmedia** [FortAwesome/Font-Awesome#8487] opened 2016-02-03 17:19 UTC
This would be great for referencing clothes in general.  Example:

<img width="21" alt="screen shot 2016-02-03 at 17 19 02" src="https://cloud.githubusercontent.com/assets/347176/12790452/3e4cecd2-ca9a-11e5-9e2d-726aecc8af8c.png">

**Comment by tagliala** [comment] 2016-02-03 19:15
duplicate of #1659, please +1 that request

closing here

**Closed by tagliala** 2016-02-03 19:15 UTC
