### ISSUE TITLE
Icon Request: fa-signlanguage

### ISSUE THREAD

**Issue by mmaak** [FortAwesome/Font-Awesome#8052] opened 2015-12-01 15:02 UTC
An icon showing that an organization, knows or is able to communicate in sign language (churches, businesses, etc)
![signlanguage](https://cloud.githubusercontent.com/assets/16102674/11504259/03850f8e-980a-11e5-8d1b-60ec01de3f68.png)
![sign2](https://cloud.githubusercontent.com/assets/16102674/11504298/3c5ba8e0-980a-11e5-93dd-f27a5f9dfb26.png)

**Comment by tagliala** [comment] 2015-12-02 15:32
duplicate of #2026 , please +1 that request

closing here

**Closed by tagliala** 2015-12-02 15:32 UTC
