### ISSUE TITLE
Duplication of css selector #id

### ISSUE THREAD

**Issue by AlexPaterson** [FortAwesome/Font-Awesome#16149] opened 2020-02-04 11:45 UTC
Hello, I am an extremely Keen Protagonist of clean code, so I regularly ensure my own code is semantically correct.

I run my sites through the Google Audit console, and I note I'm getting a less than perfect score on my accessibility.

it says [id] attributes on the page are not unique.

Hope you can do something about this soon.

ps, Im using your javascript code like this

<script src="https://kit.fontawesome.com/xxxxxxxx.js" crossorigin="anonymous"></script>

Thanks

Alex 

-

**Comment by tagliala** [comment] 2020-02-09 19:56
Hi!

Thanks for being part of the Font Awesome Community.

I'm using a kit here: https://tagliala.github.io/fa15167-kit but I cannot see any offence in the audits

Could you please provide a reproducible test case as well as steps to reproduce this?

**Comment by cschweda** [comment] 2020-02-27 16:24
Yes, I can verify this.

Google's Lighthouse audit flags fontawesome for duplicated ids.

## Steps to reproduce

- Go here: https://icjia.illinois.gov/r3/faqs
- Open Chrome dev console.
- Click on ```audit``` tab.

## Error

```
Failing Elements
link#font-awesome-5-kit-css
```

## Reason

```
<link href="https://kit-pro.fontawesome.com/releases/latest/css/pro.min.css" media="all" rel="stylesheet" id="font-awesome-5-kit-css">
```
and
```
<link href="https://kit-pro.fontawesome.com/releases/latest/css/pro-v4-shims.min.css" media="all" rel="stylesheet" id="font-awesome-5-kit-css">
```

Both have the same id.

Any chance for a fix?

**Comment by tagliala** [comment] 2020-02-27 16:45
Thanks

I can see that there are two elements with the same ID, but this does not come from our docs: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#manually

Where did you find the instructions to install Font Awesome? Is there an official plugin or extension adding those `id` attributes?

Please remove `id="font-awesome-5-kit-css"` from the html and you should be fine

**Comment by cschweda** [comment] 2020-02-27 17:11
I'm installing it via:

```
 <script
      src="https://kit.fontawesome.com/xxxxxx.js"
      crossorigin="anonymous"
    ></script>
```

Is that not the right way to install? I assume it's from that .js script that it's embedding all the links. I'm able to see the links when I view the page via the 'Elements' view in the dev console.

I'm using Vue -- standard SPA -- with a single index.html where I'm using the script tag above.

**Comment by tagliala** [comment] 2020-02-27 17:27
Hi, could you please disclose your pro kit id?

I cannot replicate

Demo: https://jsfiddle.net/tagliala/9w3c1ud5/
Configuration: Pro kit CSS

Output (no ids):
```
      <script type="text/javascript" src="https://kit.fontawesome.com/01d926b69c.js"></script><link rel="stylesheet" href="https://kit-pro.fontawesome.com/releases/v5.10.1/css/pro.min.css" media="all"><link rel="stylesheet" href="https://kit-pro.fontawesome.com/releases/v5.10.1/css/pro-v4-shims.min.css" media="all">
```

**Comment by cschweda** [comment] 2020-02-27 18:13
Sure:

```
<script
      src="https://kit.fontawesome.com/36a3d7fc0d.js"
      crossorigin="anonymous"
    ></script> 
```

**Comment by tagliala** [comment] 2020-02-27 18:25
https://jsfiddle.net/tagliala/3ncykg50/

I've placed your kit code here, I'm not getting the IDs

Also, in the source page of https://icjia.illinois.gov/r3/faqs, I cannot find the code relative to the kit

![image](https://user-images.githubusercontent.com/556268/75474176-d020d300-5996-11ea-8fc4-5ab20fb55e0a.png)

I don't what exactly is going on, but it seems related to a third-party plugin/application

**Comment by cschweda** [comment] 2020-02-27 18:34
Yep -- that's the url.

I re-enabled the pro kit and ... now it works?! Wow!

I have no idea where those IDs were coming from -- but now they're not there -- and the URL is passing the Lighthouse accessibility audit.

Thanks for looking into this. Not sure what happened -- or where the dupe'd ids came from (or where the IDs came from in the front place) -- but, hey, it's all good now. :)

**Comment by atsolberg** [comment] 2020-03-02 21:28
I'm also experiencing this issue, with a pro version kit.  

![image](https://user-images.githubusercontent.com/2157412/75719324-2d1fd000-5c9a-11ea-8def-e4350ec904a7.png)

I experienced the same issue with this free version kit: https://kit.fontawesome.com/fe766b0f79.js and upgraded to pro hoping that would fix it.

**Comment by tagliala** [comment] 2020-03-02 22:46
Thanks!

I was eventually able to replicate.

Demo: https://jsfiddle.net/tagliala/e3n2Lws4/

### Kit Configuration:

- Free
- Web Font
- Enable Version 4 Compatibility

### Option is causing the issue

- Enable Version 4 Compatibility

Let's assign @robmadole 

@robmadole I don't know if there are some other pieces of code using that ID to replace or detect font awesome in other places, we should double check

**Comment by robmadole** [comment] 2020-03-03 17:05
I don't see if used anywhere else. So we should be able to remove it without an issue.

**Comment by robmadole** [comment] 2020-03-03 17:28
Got a fix for this and it should be deployed later today.

**Comment by robmadole** [comment] 2020-03-04 14:52
Ok all, this has been fixed and deployed.

You will need to re-save your kits to get the changes. Head to https://fontawesome.com/kits, choose your Kit, go to the Settings and click "Save Changes" (even though there are no changes).

Please let me know if this fixes things up for you.

**Comment by atsolberg** [comment] 2020-03-05 15:17
All fixed, thanks for the quick turn-around!

**Comment by tagliala** [comment] 2020-03-05 15:21
Closing here

**Closed by tagliala** 2020-03-05 15:21 UTC
Labels: bug, kits
