### ISSUE TITLE
Icon Request: New Icon, fa-thought bubble

### ISSUE THREAD

**Issue by arnoldjd** [FortAwesome/Font-Awesome#9503] opened 2016-06-30 18:57 UTC
![image](https://cloud.githubusercontent.com/assets/20130439/16500389/eac4e264-3ec9-11e6-8569-ec519f2e5155.png)

A thought bubble could be used for Ideas (especially when I am using FA-Lightbulb for TIPS), thoughts, things to think about, send us your thoughts, reflection.

Keywords:
thought
think
reflection
bubble
idea
wonder
ponder

Thanks for great icons!

**Comment by aethior** [comment] 2016-06-30 19:59
Duplicate of #1863. Please :+1: that.

**Closed** 2016-06-30 21:53 UTC

**Comment by kangwritescode** [comment] 2019-12-30 16:10
yes please
