### ISSUE TITLE
Icon request: medals

### ISSUE THREAD

**Issue by zsaffir** [FortAwesome/Font-Awesome#7293] opened 2015-08-24 15:01 UTC
For websites that do ranking for competitions it would be nice to have an icon for medals.  An open medal icon could allow 1, 2, or 3 to be placed inside to signify 1st, 2nd, or 3rd place.

**Comment by tagliala** [comment] 2015-08-24 22:27
duplicate of #1898 , please +1 that request

**Closed by tagliala** 2015-08-24 22:27 UTC
