### ISSUE TITLE
Icon Request: Exercise Icon

### ISSUE THREAD

**Issue by iamshipon1988** [FortAwesome/Font-Awesome#12569] opened 2018-03-11 22:45 UTC
It would be nice to have a fitness icon. Maybe a dumbbell or a muscle icon would do. `fa-muscle`

Examples: 
https://www.flaticon.com/free-icon/muscles_639284#term=muscle&page=1&position=2

https://www.flaticon.com/free-icon/dumbbell_679306#term=dumbbell&page=1&position=34

**Comment by tagliala** [comment] 2018-03-11 23:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1500, please add a 👍  reaction to that request.

#1500 will be soon added to the FA5 Free set

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-11 23:49 UTC
