### ISSUE TITLE
Icon Request: fa-venn-diagram

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9996] opened 2016-09-29 18:19 UTC
Venn diagram icon for use within a healthcare app
![venn-diagram](https://cloud.githubusercontent.com/assets/539719/18966567/b1158ec4-864f-11e6-8372-1f908c63f31d.png)

**Comment by tagliala** [comment] 2016-09-30 09:05
Duplicate of #2164, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 09:05 UTC
