### ISSUE TITLE
Loading font-awesome with webpack, wrong content attribute

### ISSUE THREAD

**Issue by stevewillard** [FortAwesome/Font-Awesome#6552] opened 2015-05-25 17:42 UTC
Anyone know why when I load font-awesome into my site via webpack, all the content attributes of my icons are wrong? Maybe it's an encoding issue? Here's my config:

```
require("font-awesome/scss/font-awesome.scss");
```

```
module: {
        loaders: [
            { test: /\.jsx?$/, exclude: /node_modules|bower_components/, loader: "6to5-loader"},
            { test: /\.scss$/, loader: "style!css!sass?includePaths[]=" + bourbon },
            { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&minetype=application/font-woff" },
            { 
                test: /\.jpe?g$|\.gif$|\.png$/,
                loader: "url-loader" 
            },
            { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }
        ]
    }
```

If you inspect the DOM, the stylesheet gets added but but the content attributes look like this:
![screen shot 2015-05-25 at 1 41 43 pm](https://cloud.githubusercontent.com/assets/11420/7800474/dcb2d5fa-02e3-11e5-9bca-9fddd5be57d0.png)

But, they look correct in my node_modules folder. Any ideas?

**Comment by johnbendi** [comment] 2015-05-25 17:47
Did I just see minetype?‎ Instead of mimetype.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Steve WillardSent: Monday, May 25, 2015 6:42 PMTo: FortAwesome/Font-AwesomeReply To: FortAwesome/Font-AwesomeSubject: [Font-Awesome] Loading font-awesome with webpack, wrong content attribute (#6552)Anyone know why when I load font-awesome into my site via webpack, all the content attributes of my icons are wrong? Maybe it's an encoding issue? Here's my config:

require("font-awesome/scss/font-awesome.scss");


module: {
        loaders: [
            { test: /\.jsx?$/, exclude: /node_modules|bower_components/, loader: "6to5-loader"},
            { test: /\.scss$/, loader: "style!css!sass?includePaths[]=" + bourbon },
            { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&minetype=application/font-woff" },
            { 
                test: /\.jpe?g$|\.gif$|\.png$/,
                loader: "url-loader" 
            },
            { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }
        ]
    }


If you inspect the DOM, the stylesheet gets added but but the content attributes look like this:


But, they look correct in my node_modules folder. Any ideas?

—Reply to this email directly or view it on GitHub.

**Comment by stevewillard** [comment] 2015-05-25 17:54
Yeah, I copied it from an example. I looked at the source of url-loader and it looks like it doesn't matter -- I tried mimetype and minetype, and they work the same.

**Comment by tagliala** [comment] 2015-05-25 22:37
Sorry, I can't help

Leaving this open but I don't know if we need to do something on our side

**Comment by stevewillard** [comment] 2015-06-01 15:22
I ended up using:
https://www.npmjs.com/package/font-awesome-webpack
And it's working well (although it pulls in a lot of dependencies I would rather not use).

I haven't really dug through their configuration, so I'm not sure exactly how they get things to work, but figured it's a good reference.

**Comment by bsara** [comment] 2015-06-10 22:09
The reason is how they are referencing the characters in the SCSS code. I have a fix for this that will create a pull request for in a minute, in the mean time, here is a sample of what I'm referring to (it's easier to see the code rather than explaining it): http://sassmeister.com/gist/3bfad69a4ca6e34909cf

**Comment by stevewillard** [comment] 2015-06-10 22:32
Awesome! Makes a lot more sense now. Thanks for digging this up.

**Comment by bsara** [comment] 2015-06-10 23:28
No problem, glad that I could help.

**Comment by davegandy** [comment] 2015-07-28 05:10
Going to move this into 5.0 for now.

**Comment by davewallace** [comment] 2017-04-28 04:17
Am seeing this same outcome with:
```
    "gulp-sass": "~3.1",
    "node-sass": "~4.5",
```
Not using webpack, and the issue is highly intermittent, but majorly degrading. Any other ideas/suggestions? I've not had the chance to dig too deep as it has mostly happened while performing remote browser testing.

**Comment by tagliala** [comment] 2017-12-17 19:47
I'm pretty sure this has been fixed in FA5.

Could you please check?

**Comment by tagliala** [comment] 2018-02-18 14:47
No feedback, closing here

Please comment if this is still an issue

**Closed by tagliala** 2018-02-18 14:47 UTC
Labels: bug, css, waiting for feedback
