### ISSUE TITLE
Icon Request: fa-redmine

### ISSUE THREAD

**Issue by Discostewart** [FortAwesome/Font-Awesome#13312] opened 2018-06-13 08:42 UTC
http://www.redmine.org/projects/redmine/wiki/Logo

**Comment by tagliala** [comment] 2018-06-13 08:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1787, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-13 08:45 UTC
