### ISSUE TITLE
Icon Request: fa-360-view

### ISSUE THREAD

**Issue by zachbordeau** [FortAwesome/Font-Awesome#10919] opened 2017-04-10 21:08 UTC
I work for The Toro Company and we implement font awesome for many of our icon needs. We are looking for a 360* rotation view icon that lets people know that when pressing a button with the 360* icon, they will be taken to a rotational product demo.  It is critical that the term 360* is somewhere in the icon. 
Here's an example:
![360-fa-icon-70x70](https://cloud.githubusercontent.com/assets/27240116/24882766/daaa4194-1e07-11e7-8e43-095eb4d47e2b.png)
OR a simple google of what I'm talking about: https://www.google.com/search?q=360*+view+icon&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiFgOiH4JrTAhWl34MKHRtPDqkQ_AUIBigB&biw=1920&bih=950

**Comment by tagliala** [comment] 2017-04-11 08:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5820 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-11 08:46 UTC
