### ISSUE TITLE
Icon request: blood-tube

### ISSUE THREAD

**Issue by chodaboy14** [FortAwesome/Font-Awesome#10112] opened 2016-10-24 20:58 UTC
I work in the health industry and are building a specimen collection guide.  The tops of the tubes are colour coded to easily identify the tube(s) required for collection.
![bloodtube](https://cloud.githubusercontent.com/assets/23040452/19663684/8649033e-9a99-11e6-9455-eb35c545e9c4.jpg)

**Comment by tagliala** [comment] 2016-10-24 21:55
Duplicate of #1353, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-24 21:55 UTC
