### ISSUE TITLE
Icon Request: Line.me

### ISSUE THREAD

**Issue by nevagency** [FortAwesome/Font-Awesome#11423] opened 2017-08-21 06:37 UTC
Hey Team,

Could you please consider adding **Line.me** icon to fontawesome.io? I would be so much grateful :)
This is now as popular social chatting app, especially in asia.

[https://line.me/en/logo](https://line.me/en/logo)

![line_icon](https://user-images.githubusercontent.com/30569057/29506381-a09519d2-864b-11e7-97e5-f2a13d055893.png)

**Comment by tagliala** [comment] 2017-08-21 07:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2631 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-21 07:39 UTC
