### ISSUE TITLE
Icon Request: fa-vbulletin

### ISSUE THREAD

**Issue by DrCustUmz** [FortAwesome/Font-Awesome#9155] opened 2016-05-09 19:44 UTC
http://i.imgur.com/ECoWQbz.png

vBulletin is one of the biggest online forum softwares, this icon could be used
- next to links to forums
- in footers to give credit
- anywhere you feel like having the icon ;)

**Comment by anshulsahni** [comment] 2016-05-09 20:11
+1

**Comment by tagliala** [comment] 2016-05-09 20:39
Duplicate of #7678, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-09 20:39 UTC
