### ISSUE TITLE
fas fa-comment-alt is giving me fa-comment-dots

### ISSUE THREAD

**Issue by robjac** [FortAwesome/Font-Awesome#13620] opened 2018-07-25 16:04 UTC
My web font markup:
```
<i className={`fa fa-comment-alt`} />
```

![screen shot 2018-07-25 at 12 02 39 pm](https://user-images.githubusercontent.com/1988220/43212691-ae174d48-9002-11e8-90a8-d599cfecab4b.png)

expected behavior:
this icon : https://fontawesome.com/icons/comment-alt?style=solid 

using CDN: 
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

```

**Comment by tagliala** [comment] 2018-07-25 19:58
Hi!

Thanks for being part of the Font Awesome Community.

Cannot confirm: https://jsfiddle.net/tagliala/m6a4ot01/1/

Please make sure that there isn't a plugin loading an old version of font awesome.

This icon has been changed in fa 5.0.9, here it is how looks like in FA 5.0.8: https://jsfiddle.net/tagliala/fnuuz8cf/17/ 

If you still think there is an issue with Font Awesome, please provide a reproducible test case

Hope it helps

Closing here

**Closed by tagliala** 2018-07-25 19:58 UTC

**Comment by robjac** [comment] 2018-07-25 20:16
thanks -- I have found the culprit in an esoteric component. I appreciate the quick reply.
