### ISSUE TITLE
Icon request: icon-broadband (icon-internet, icon-modem, icon-router, icon-wireless)

### ISSUE THREAD

**Issue by harnishdesign** [FortAwesome/Font-Awesome#12756] opened 2018-04-02 12:37 UTC
Something Like This :

<img src="https://cdn0.iconfinder.com/data/icons/technology-business-and-people/1000/file_light-50-128.png">

**Comment by tagliala** [comment] 2018-04-06 09:48
I'm going to consider this a duplicate of #6025, please +1 that request and post there your example

**Closed by tagliala** 2018-04-06 09:48 UTC
