### ISSUE TITLE
Icon request: duckduckgo

### ISSUE THREAD

**Issue by GhexterCortes** [FortAwesome/Font-Awesome#17091] opened 2020-08-28 07:53 UTC
**What can it be used for?**
it can be used by recognizing the duckduckgo search engine and for buttons

**Example image (optional)**
https://duckduckgo.com/assets/logo_homepage.normal.v108.svg

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by drothmaler** [comment] 2021-07-07 07:24
This is a duplicate of #6731 
You can vote there, so that it gets more attention…

**Comment by tagliala** [comment] 2021-07-07 07:26
@drothmaler thanks

@GhexterCortes Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6731, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-07-07 07:26 UTC
