### ISSUE TITLE
Icon request: Crowdin

### ISSUE THREAD

**Issue by acsy** [FortAwesome/Font-Awesome#16296] opened 2020-03-10 07:59 UTC
**What can it be used for?**
This is a brand icon for @crowdin.
Crowdin is a cloud-based solution that streamlines localization management for your team. It's the perfect place to effectively manage all of your multilingual content.

**Example image (optional)**
*Full logo:*
![crowdin-logo](https://user-images.githubusercontent.com/3395748/76290665-433e1980-62b4-11ea-9ff5-35fc66742a64.png)
*Single symbol:*
![filled@1x](https://user-images.githubusercontent.com/3395748/76290534-08d47c80-62b4-11ea-8cd6-fb45c0138fd8.png)
*Favicon*
![favicon-white@48](https://user-images.githubusercontent.com/3395748/76290817-8c8e6900-62b4-11ea-8fad-e735fa6f598e.png)
*SVG icon 24x24px code:*
`<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M15.7767 17.1592C15.1961 17.1592 14.6777 16.9851 14.2491 16.6446C13.7376 16.2436 13.3298 15.6458 13.316 14.9421C13.3091 14.5864 13.6962 14.5864 13.6962 14.5864C13.6962 14.5864 14.3252 14.5789 14.6293 14.5789C14.9334 14.5864 15.0233 15.0102 15.0371 15.1161C15.1546 16.0695 15.6937 16.4857 16.1085 16.6749C16.3573 16.7884 16.2951 17.144 15.7767 17.1592Z" fill="black"/>
<path d="M10.558 12.3143C10.0467 12.2541 9.28662 12.2015 8.79601 12.0812C8.00136 11.8857 8.02209 11.1714 8.05664 10.9383C8.15338 10.2391 8.40905 9.59247 8.80292 8.99096C9.29353 8.25412 9.99834 7.60751 10.9035 7.08119C12.6034 6.09623 14.9804 5.54736 17.5924 5.54736C19.5064 5.54736 21.5034 5.79548 21.5241 5.79548C21.7038 5.81804 21.8351 5.99097 21.8282 6.18646C21.8213 6.38195 21.6831 6.53232 21.5034 6.54736C21.2132 6.53984 20.9299 6.53984 20.6604 6.53984C18.0001 6.53984 16.1067 6.90074 14.6971 7.6827C13.3082 8.44961 12.3408 9.62254 11.6844 11.3594C11.6153 11.5098 11.3872 12.4045 10.558 12.3143Z" fill="black"/>
<path d="M12.8796 19.4831C11.5598 19.4831 10.3156 18.9133 9.3739 17.8724C8.57653 16.991 8.09535 16.1021 8.00599 14.9624C7.951 14.2178 8.28095 13.9595 8.72776 14.0051C9.03708 14.0354 9.99943 14.081 10.5493 14.195C10.9618 14.2786 11.2367 14.5065 11.3055 14.9776C11.6698 17.4849 13.2508 18.4726 14.1925 18.6854C14.3575 18.7233 14.4606 18.8297 14.4537 19.0197C14.4469 19.202 14.3231 19.354 14.1582 19.3844C13.7388 19.4527 13.2989 19.4831 12.8796 19.4831Z" fill="black"/>
<path d="M9.11852 21.7085C8.18202 21.7085 7.26617 21.5595 7.0045 21.5125C5.90274 21.3164 4.98001 20.9793 4.18812 20.4774C2.29446 19.2777 1.15137 17.1605 1.01365 14.6513C0.979223 14.0554 0.903477 12.9184 2.322 13.0046C2.90731 13.036 3.83693 13.3183 4.4911 13.5065C5.30365 13.7339 5.69616 14.3612 5.69616 14.9807C5.69616 18.5171 8.89816 20.8538 10.296 20.8538C10.8951 20.8538 10.6748 21.4968 10.4131 21.5674C9.95173 21.6928 9.35953 21.7085 9.11852 21.7085Z" fill="black"/>
<path d="M4.23394 11.3175C3.67999 11.2182 3.1399 10.9891 2.61365 10.8593C0.986442 10.4546 1.26341 8.81289 1.41575 8.36237C2.89755 4.00227 7.59915 2.54382 11.3937 2.15438C14.9666 1.78786 18.7057 2.07039 22.1886 3.04015C22.4725 3.11651 23.3519 3.33031 22.8465 3.85719C22.5279 4.18553 21.2885 3.84192 20.9561 3.81901C18.9134 3.66629 16.8916 3.64338 14.8558 3.95646C12.7024 4.2848 10.4866 4.9644 8.70703 6.39995C7.84842 7.09481 7.09367 7.98058 6.5882 9.0267C6.45664 9.30159 6.35277 9.57648 6.26276 9.85137C6.17274 10.1415 5.83345 11.6 4.23394 11.3175Z" fill="black"/>
<path d="M13.3446 12.1584C13.6495 10.794 15.0044 8.63164 19.198 8.78076C20.16 8.81059 19.7196 9.46674 19.2454 9.45182C16.8743 9.36981 15.7497 10.8983 15.1603 12.4492C14.9706 12.9488 14.537 13.0234 13.995 12.9339C13.6156 12.8668 13.2024 12.8221 13.3446 12.1584Z" fill="black"/>
</svg>`

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-03-10 11:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5421, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-10 11:04 UTC
