### ISSUE TITLE
Icon request: google-play music

### ISSUE THREAD

**Issue by JAicewizard** [FortAwesome/Font-Awesome#16611] opened 2020-05-11 12:17 UTC
**What can it be used for?**
the same use-case as the spotify icon, eg: indicator that song X is playing on GPM

**Example image (optional)**
See google-play music logo

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-23 12:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2074, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-23 12:46 UTC

**Comment by JAicewizard** [comment] 2020-05-23 12:58
Thank, I was not able to find it using the github search, I do now I dont know why I wasnt before.

**Comment by tagliala** [comment] 2020-05-23 13:14
@JAicewizard welcome, and don't worry 👍
