### ISSUE TITLE
Icon-Request: Element

### ISSUE THREAD

**Issue by LaroTayoGaming** [FortAwesome/Font-Awesome#17315] opened 2020-10-25 17:25 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.

This can be used in multiple ways. As a community room selector, A Social links for different communities, and more.

https://github.com/vector-im/logos/tree/master/element

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-10-25 17:54
Hi!

Thanks for being part of the Font Awesome Community.

Apologies, I do not know what `element` is and Google does not help

Could you please provide more details? Is it a brand? Does it have an official website?

**Comment by LaroTayoGaming** [comment] 2020-10-26 10:03
The official website is element.io

**Comment by LaroTayoGaming** [comment] 2020-10-26 10:03
It is the new name of riot.im

**Comment by LaroTayoGaming** [comment] 2021-01-27 14:28
@tagliala element.io is the new name of riot.im

From riot to element on a matrix server

**Comment by tagliala** [comment] 2021-01-27 15:14
Hi @LaroTayoGaming please help me clarify this

If this is the new name of `riot.im`, then we should switch to #11270

But https://github.com/FortAwesome/Font-Awesome/issues/11270#issuecomment-669222945, mentions that #11270 is a duplicate of #12808

So I would like to understand the differences between

- #11270
- #12808
- #17315 (this request)

And manage issues accordingly

**Comment by LaroTayoGaming** [comment] 2021-01-28 01:37
@tagliala Okay. Riot.im is an old name of Element.io

Matrix on the other hand is the server itself and it is seperated.

**Comment by tagliala** [comment] 2021-01-28 08:53
Ok Thanks. I'm going to close this and rename #11270, which has a lot of more +1s

**Closed by tagliala** 2021-01-28 08:53 UTC
Labels: waiting for feedback
