### ISSUE TITLE
Icon Request: fa-scoop-it

### ISSUE THREAD

**Issue by chenox** [FortAwesome/Font-Awesome#9858] opened 2016-09-05 09:03 UTC
![scoop-it](https://cloud.githubusercontent.com/assets/22001352/18242787/fd5789a8-734f-11e6-89c8-6934b303835d.png)

**Comment by aethior** [comment] 2016-09-05 09:25
Duplicate of #1603. Please :+1: that request.

**Closed** 2016-09-05 10:55 UTC

**Comment by ligne13** [comment] 2016-10-17 14:36
+1 scoop it

**Comment by tagliala** [comment] 2016-10-17 15:24
🔒
