### ISSUE TITLE
Phone/Call/Mobile Icon

### ISSUE THREAD

**Issue by Pauldic** [FortAwesome/Font-Awesome#8469] opened 2016-01-31 19:07 UTC
Just like fa-phone which can be use as a telephone/mobile phone number/Calling as in call centers or other applications. It will be nice if you include:
- hangup call
- incoming call
- outgoing call
- on-phone/active call

**Comment by tagliala** [comment] 2016-03-17 15:36
duplicate of #3701, please +1 that request

closing here

**Closed by tagliala** 2016-03-17 15:36 UTC
