### ISSUE TITLE
Icon Request: fa-repair

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7013] opened 2015-07-23 00:20 UTC
fa-repair icon:

![Repair](http://i.imgur.com/JG818nK.png)
Source: http://www.flaticon.com/free-icon/double-wrench-tool-and-hammer-forming-a-cross-of-outlines_25718

**Comment by tagliala** [comment] 2015-07-23 10:28
duplicate of #736 , please +1 that request

closing here

**Closed by tagliala** 2015-07-23 10:28 UTC

**Comment by tuxy** [comment] 2015-07-24 03:57
@tagliala, done. Thank You!
