### ISSUE TITLE
Icon Request: Hashnode

### ISSUE THREAD

**Issue by mchilson** [FortAwesome/Font-Awesome#11216] opened 2017-06-22 15:30 UTC
Maybe a icon of the hashnode social site logo?
https://hashnode.com/

Thank you for your consideration.
Mike

**Comment by tagliala** [comment] 2017-06-22 15:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10437, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-22 15:51 UTC
