### ISSUE TITLE
Icon request: computer network icons

### ISSUE THREAD

**Issue by schreiyarai** [FortAwesome/Font-Awesome#7237] opened 2015-08-14 14:55 UTC
Hello!
I'm a FontAwesome user and I'd like to suggest some new icons about computer network.
I am currently working on a project to a client who's an Internet provider and they'd like to highligh internet plans and other stuff about the service. Some FontAwesome icons like the following would be great:
- LAN port & WAN port (these two would work perfect it they were the same little icons that point to these ports in a simple wi-fi router);
- Optical fiber transmission (maybe a little cable with an RJ45 tip? I don't understand about it...)
- Internet radio (oh yes, believe it or not, here where I live it's still the main form of Internet distribution, but the optical fiber is growing), (maybe a little antenna with wi-fi waves?)
- Home & corporate network (a little house/building with wi-fi waves too?)

(As the main part of the site is for the public and clients, I'm currently using the code-fork icon to illustrate the optical fiber... sounds a stupid thing to do, but we believe the final audience won't know the difference! ~the client didn't~ Haha)
I hope I'm posting the request the right way. :)

**Comment by tagliala** [comment] 2015-08-14 15:55
Hi,

I think there are already duplicate requests you could +1

rj45 or lan: #2565. There is an example for both an rj45 cable and a port. We can improve #2565 and open a new request for an rj45 port 

internet radio: #2125 or #2581 

home and corporate network should be splitted in two new separate requests. May refer to #1181 

If you need all the above icons in a short while, my suggestion is to consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here but feel free to comment if you need more information

**Closed by tagliala** 2015-08-14 15:55 UTC

**Comment by caduvieira** [comment] 2015-08-14 15:56
I dont think that RJ45 represents a good optical fiber cable.
I think this is better:
![fiber-optics](https://cloud.githubusercontent.com/assets/3831408/9277843/08664d74-4283-11e5-9be7-9b681f06deb8.png)

For internet radio something like #2125?
Dupe of fa-modem fa-router: #6025 

For home / corporate network something like this would work? This is not aligned.
http://jsfiddle.net/mpddhbym/1/

Related to #3090

**Comment by schreiyarai** [comment] 2015-08-17 16:46
@caduvieira I had no idea of how an optical fiber cable should look. Good suggestion, but I think this would be hard to achieve to something that must look good and comprehensive even in a small size.
And thanks also for the idea of combining two icons for the home network :}

@tagliala I've given +1 in some of them, thanks. I like the antenna example for the internet radio :)

Thanks for feedback, guys!

**Comment by caduvieira** [comment] 2015-08-17 17:15
@schreiyarai 
![fiber_optic_icon](https://cloud.githubusercontent.com/assets/3831408/9311080/6ded058e-44ea-11e5-99e5-f11bfa13cfc9.png)
