### ISSUE TITLE
https://use.fontawesome.com/releases/v5.3.1/css/all.css

### ISSUE THREAD

**Issue by akkii922** [FortAwesome/Font-Awesome#14084] opened 2018-10-09 09:06 UTC
### What version and implementation are you using?

Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2018-10-09 10:44
Duplicate of #14085

**Closed by tagliala** 2018-10-09 10:44 UTC
