### ISSUE TITLE
Icon-request: fa-windmill

### ISSUE THREAD

**Issue by Rear-Window** [FortAwesome/Font-Awesome#8203] opened 2015-12-22 11:17 UTC
Hello FontAwesome team,

I need a windmill icon for a green energy company website. Something like this:

https://cdn3.iconfinder.com/data/icons/eco-friendly-icons/512/Wind_Turbine-512.png

Thank you very much. Best Regards. Paolo

**Comment by caduvieira** [comment] 2015-12-22 12:26
dupe of #1300
please +1 that one

**Closed** 2015-12-22 12:32 UTC
