### ISSUE TITLE
Icon Request: fa-nurse

### ISSUE THREAD

**Issue by kirant33** [FortAwesome/Font-Awesome#10398] opened 2016-12-20 06:54 UTC
An icon for a Nurse in a Hospital

**Comment by tagliala** [comment] 2016-12-20 11:50
Duplicate of #4326, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-20 11:50 UTC
