### ISSUE TITLE
Icon request: MeWe

### ISSUE THREAD

**Issue by GrocExp** [FortAwesome/Font-Awesome#17793] opened 2021-04-04 15:10 UTC
**What can it be used for?**
I have a TemplateMonster template with the 5 evil social media links.  I want to replace Facebook with a MeWe icon

**Example image (optional)**
![MeWe-Fluid-Icon (1)](https://user-images.githubusercontent.com/28729736/113513163-3c74eb00-9536-11eb-87d3-97c6ddb4f632.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-04-04 16:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8415, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-04-04 16:06 UTC
