### ISSUE TITLE
Icon Request: fa-users OR fa-people

### ISSUE THREAD

**Issue by erichonkanen** [FortAwesome/Font-Awesome#11021] opened 2017-05-04 09:07 UTC
Hello,

Wondering if we could get a better "users" icon or a new alternate one called "people" (outline version would be cool too).

The current `users` icon looks odd and doesn't work very well in my humble opinion, and it could be improved by doing something to the effect of:

https://image.freepik.com/free-icon/two-users-silhouette_318-34675.jpg
http://imgur.com/a/eSFXd

Basically take the single user icon and add a smaller 2nd silhouette behind it..

Use case is anywhere you want to represent multiple users such as a friend list icon.

Outline version would be nice like the new single user outline one which I like :D 

That is all!

**Comment by tagliala** [comment] 2017-05-04 09:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2883, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-04 09:46 UTC
