### ISSUE TITLE
Icon request: icon-ruler

### ISSUE THREAD

**Issue by arnoldjd** [FortAwesome/Font-Awesome#9470] opened 2016-06-24 18:06 UTC
I would love to see a ruler icon (tags: measure, ruler, size) 

We do research based work and so frequently I find myself looking for a "measure". 
http://sustainablybuilt.com/wp/wp-content/uploads/2013/09/Very-Basic-Ruler-icon.png

thanks, 
Jodi

**Comment by tagliala** [comment] 2016-06-25 01:27
Duplicate of #1096 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-25 01:27 UTC
