### ISSUE TITLE
Icon request: icon-flame

### ISSUE THREAD

**Issue by esatk** [FortAwesome/Font-Awesome#7164] opened 2015-08-07 00:59 UTC
Could you please add an icon for a gas flame, I know there is already a flame icon but the current icon could be more flame like please see

![image](https://cloud.githubusercontent.com/assets/13686769/9126641/d3984a10-3ca7-11e5-9f11-a74ce555344a.png)

or 

![image](https://cloud.githubusercontent.com/assets/13686769/9126650/f627cf74-3ca7-11e5-9842-6e1098b0ae5d.png)

**Comment by lvv83** [comment] 2015-08-07 07:44
+1

**Comment by tagliala** [comment] 2015-08-07 11:40
duplicate of #3577, please +1 that request

closing here

**Closed by tagliala** 2015-08-07 11:40 UTC
