### ISSUE TITLE
icon request: fa-elder

### ISSUE THREAD

**Issue by MVcodeartbr** [FortAwesome/Font-Awesome#8008] opened 2015-11-27 13:49 UTC
for attend heuristics

![32836597-elder-black-graphic-symbol-vector-illustration-stock-vector-icon](https://cloud.githubusercontent.com/assets/3662026/11442484/e4d13d34-94fc-11e5-9e62-a2182d701570.jpg)
![elderly-people-294088](https://cloud.githubusercontent.com/assets/3662026/11442483/e4cfc774-94fc-11e5-8edc-7e046d621c32.png)
![elderly-512](https://cloud.githubusercontent.com/assets/3662026/11442485/e4d5f126-94fc-11e5-8fdf-a77f65df305f.png)

**Comment by caduvieira** [comment] 2015-11-27 14:15
dupe of #7183
please +1 that issue

**Closed** 2015-11-27 14:21 UTC
