### ISSUE TITLE
Icon request: Teamspeak icon

### ISSUE THREAD

**Issue by preterive** [FortAwesome/Font-Awesome#11464] opened 2017-08-30 16:16 UTC
Hello,
i'd like to request the teamspeak-icon because i think Communitys need this icon.
Example: https://cdn.worldvectorlogo.com/logos/teamspeak-2.svg

Thank you!

**Comment by tagliala** [comment] 2017-08-30 16:24
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1474 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-30 16:24 UTC
