### ISSUE TITLE
icon request: fa-aesculap

### ISSUE THREAD

**Issue by Hirbod** [FortAwesome/Font-Awesome#8047] opened 2015-11-30 22:16 UTC
For pharmacy 

http://www.clker.com/cliparts/6/k/e/Z/W/v/aesculap-black.svg

https://en.wikipedia.org/wiki/Rod_of_Asclepius
https://en.wikipedia.org/wiki/Pharmacy#Symbols

But https://en.wikipedia.org/wiki/Bowl_of_Hygieia would be also fine. At least something, that is recognized "pharmacy" worldwide. As far as I know, the snake is the right path to pick!

**Comment by tagliala** [comment] 2015-12-02 15:31
duplicate of #2009, please +1 that request

closing here

**Closed by tagliala** 2015-12-02 15:31 UTC
