### ISSUE TITLE
fas fa-history

### ISSUE THREAD

**Issue by amadrocky** [FortAwesome/Font-Awesome#15834] opened 2019-11-21 15:24 UTC
hello, 

when i want to se the page for to copy the icon "history clock" (<i class="fas fa_history"></i>), the website rediret to the homepage.

Thanks !

**Comment by sensibleworld** [comment] 2019-11-22 14:33
@amadrocky Thanks for the report! I believe this issue has been fixed. Can you let me know if you're still experiencing it?

**Comment by tagliala** [comment] 2019-11-22 14:34
@sensibleworld may this be a duplicate of #15834 ?

**Closed** 2019-12-06 18:49 UTC
Labels: waiting for feedback
