### ISSUE TITLE
Better shield icons (beyond fa-shield)

### ISSUE THREAD

**Issue by GuardianMajor** [FortAwesome/Font-Awesome#9882] opened 2016-09-07 21:09 UTC
Current shield icon is very limited and the two tone nature of it makes it display horribly in smaller sizes (more like a shield with a hole in it as-is), so can we have some added shield styles that are for example white (aka outline) so basically inherits the color of its background and can be foreground colored in css (like the current HOLE portion of the icon). A solid black one, which can be styled to any color using css (aka like the side of the current shield that is not a hole). And a more realistic shield icon with black/white lines on the front ala 
![image](https://cloud.githubusercontent.com/assets/5274181/18328568/2d663f6c-7504-11e6-8e65-c35182fe79b2.png)
where basically the "black" parts will inherit the css color specified and the "white" parts will show the background color stemming through. Just think it would add more value, given we have TONS of icons that serve little to no niche purpose but we have so limited of options with things that often need a variety of implications. Thanks.

**Comment by tagliala** [comment] 2016-09-08 09:42
maybe a duplicate of #3443 ?

**Comment by GuardianMajor** [comment] 2016-09-09 02:17
Yes it appears to be along the same line of request.

**Comment by tagliala** [comment] 2016-09-09 09:06
Let's use #3443

**Closed by tagliala** 2016-09-09 09:06 UTC
Labels: waiting for feedback

**Comment by GuardianMajor** [comment] 2016-09-09 19:36
Ok if that is necessary, but seeing that there has been no traction on the other one either, doesn't seem like it will be much of a loss :)
