### ISSUE TITLE
Icon request: icon-website

### ISSUE THREAD

**Issue by dieulinh** [FortAwesome/Font-Awesome#4422] opened 2014-09-13 08:13 UTC
I need a website icon some how like this icon https://cdn2.iconfinder.com/data/icons/picons-essentials/57/website-512.png

**Comment by aethior** [comment] 2016-06-09 00:50
Duplicate of #1192.

cc @tagliala

**Comment by tagliala** [comment] 2016-06-09 09:28
Maybe at that time I wasn't able to find the original request

Closing here

**Closed by tagliala** 2016-06-09 09:28 UTC
