### ISSUE TITLE
Icon request: middle-finger

### ISSUE THREAD

**Issue by popisms** [FortAwesome/Font-Awesome#13648] opened 2018-07-28 03:52 UTC
### What can it be used for?

Humor, ratings, anger, satire

### Example image (optional)

It could look like "fa-hand-rock" with a finger up, or "fa-hand-peace" with one finger down, or fa-hand-point-up with a different finger up. Solid and outline versions.

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional) _(No, but suggested similar existing icons included)_
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-28 08:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2402, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-28 08:38 UTC

**Comment by popisms** [comment] 2018-07-28 12:45
Sorry, I guess I searched in the top search box rather than the filter search box.

**Comment by tagliala** [comment] 2018-07-28 13:13
@popisms don't worry 👍
