### ISSUE TITLE
Icon Request: fa-shopify

### ISSUE THREAD

**Issue by doprdele** [FortAwesome/Font-Awesome#11022] opened 2017-05-04 16:36 UTC
I would like an icon to represent the shopify brand of ecommerce software, as represented here:
https://cdn.shopify.com/assets/images/logos/shopify-bag.png

This would be for text or chrome extensions that determine whether a site is a shopify ecommerce site

**Comment by tagliala** [comment] 2017-05-04 17:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3850, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-04 17:23 UTC
