### ISSUE TITLE
Icon request: fa-gravestone

### ISSUE THREAD

**Issue by TheMouster** [FortAwesome/Font-Awesome#13609] opened 2018-07-24 04:21 UTC
It would be helpful to have an icon to represent deceased entities. Something along the lines of these;

![gravestone-003](https://user-images.githubusercontent.com/4576167/43116604-2d6cd6b2-8f3b-11e8-945e-c397313809b9.jpg)
![gravestone-002](https://user-images.githubusercontent.com/4576167/43116605-2f0467d8-8f3b-11e8-89ec-fec3a1a1921f.jpg)
![gravestone-005](https://user-images.githubusercontent.com/4576167/43116606-3089cad0-8f3b-11e8-95b1-6fb3cc717472.jpg)

**Comment by tagliala** [comment] 2018-07-24 10:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9558, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-24 10:36 UTC
