### ISSUE TITLE
Icon request: Fediverse

### ISSUE THREAD

**Issue by orowith2os** [FortAwesome/Font-Awesome#19765] opened 2023-06-16 01:20 UTC
### Use case

There's been a ton of controversy over Twitter, and not everyone uses alternatives like Cohost and Tumblr.

Instead, many may prefer to use something like Mastodon, which connects with something larger, called the "Fediverse".

Using just the Mastodon (or one of the many compatible alternatives) logo might not be desired, and instead, the Fediverse icon can be used instead. I intend to use this on my Socials page on my website, for example.

These aren't official, as in general official logos for something as large and diverse as the Fediverse are hard to sort out. But it's generally accepted that these can be used to represent the Fediverse.

### Example image

![Colored Fediverse logo](https://github.com/FortAwesome/Font-Awesome/assets/93224879/302492c4-7e38-47d4-be36-7b845db1589d)

![Monochrome Fediverse logo](https://github.com/FortAwesome/Font-Awesome/assets/93224879/bf93cf7a-57d9-4767-bdf5-e127e0f2a502)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2023-06-16 06:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16252, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-06-16 06:16 UTC
Labels: new icon
