### ISSUE TITLE
Icon request: arrow-split / arrow-merge

### ISSUE THREAD

**Issue by adswayne** [FortAwesome/Font-Awesome#15453] opened 2019-08-29 12:40 UTC
**What can it be used for?**
For use in representing a choice, split, merge, different paths, routes.

**Example image (optional)**
Split:
![split](https://user-images.githubusercontent.com/52738127/63940917-64e75a00-ca62-11e9-8ce7-ae5f09697265.png)
Merge:
![merge](https://user-images.githubusercontent.com/52738127/63940924-67e24a80-ca62-11e9-99f4-14128ecf56e7.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-08-29 13:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14500, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-08-29 13:22 UTC
