### ISSUE TITLE
Icon Request: fa-weight

### ISSUE THREAD

**Issue by uxitten** [FortAwesome/Font-Awesome#7850] opened 2015-11-08 11:06 UTC
weight
![weight](https://cloud.githubusercontent.com/assets/1549069/11019996/b7ba640e-8608-11e5-94c4-0bc9e1a32541.jpg)

**Comment by caduvieira** [comment] 2015-11-09 10:28
dupe of #2735
please +1 that one

**Closed** 2015-11-09 11:14 UTC

**Comment by smigh** [comment] 2016-05-04 17:27
Just suggesting [this one](http://fortawesome.github.io/Font-Awesome/icon/balance-scale/), which is closer to your example than the new weight icon on the new issue.
