### ISSUE TITLE
Icon request: MCH

### ISSUE THREAD

**Issue by MakeItReaal** [FortAwesome/Font-Awesome#16478] opened 2020-04-15 18:35 UTC
What can it be used for?
This could be used in social situations to represent Minecraft Servers. That are having an online website.

Example image (optional)
![image](https://user-images.githubusercontent.com/24211237/79375221-9745b900-7f58-11ea-9a6c-f882406dead3.png)

Icon request checklist
- [x ] This is a single icon or matched pair (Ex: lock / unlock)
- [x ]  The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
- [ x]  I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [x ]  I have included at least one example image if it could be helpful (optional)
- [x ]  The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by MakeItReaal** [comment] 2020-04-15 18:37
+1

**Comment by MakeItReaal** [comment] 2020-04-21 16:47
@tagliala  When do we get the icon how much likes we need?

**Comment by tagliala** [comment] 2020-04-21 16:57
@MakeItReaal please take a look at our [Brand Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), they contain a lot of information about how requests work

**Comment by MakeItReaal** [comment] 2020-04-23 18:28
@tagliala  Thank you for the reply. But is there a limit you need to recieve on links ect? 
because there is alot of people who made kind of the same request back in 2012/2013 and there was no icon added for it.

**Comment by tagliala** [comment] 2020-04-23 19:04
> because there is alot of people who made kind of the same request back in 2012/2013 and there was no icon added for it.

I couldn't find a duplicate for this, can you point me to the issue?

**Comment by MakeItReaal** [comment] 2020-04-24 15:23
@tagliala  https://github.com/FortAwesome/Font-Awesome/issues/1776

**Comment by tagliala** [comment] 2020-04-24 15:58
@MakeItReaal I do not play minecraft.

Are minecraft logo and MCH the same thing?

**Comment by MakeItReaal** [comment] 2020-04-28 03:09
@tagliala  yes People also replyed with in that ticket. For the Icon since 2013!

**Comment by tagliala** [comment] 2020-04-28 07:36
Ok, thanks

So this request is a duplicate of #1776, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-04-28 07:36 UTC
