### ISSUE TITLE
Icon Request: fa-finger-print

### ISSUE THREAD

**Issue by fixmyphones** [FortAwesome/Font-Awesome#9427] opened 2016-06-20 18:04 UTC
Hi 
im building a website for one app that im working on .
that aplicaion will have support for touch id .
in the website i will need a touch id icon and i could not find it on font awesome website 
can you please make one ? :)
i would be very thankfull.
the icon should look like a finger print -
thank you in advance

**Comment by tagliala** [comment] 2016-06-20 19:39
Duplicate of #4431 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-20 19:39 UTC
