### ISSUE TITLE
Icon request: icon-xero

### ISSUE THREAD

**Issue by 5tevenca5e** [FortAwesome/Font-Awesome#7329] opened 2015-08-28 13:21 UTC
Xero is an online accounting software offered by a number of people. I'd like a Xero brand icon for my site please. There's an example on http://ihorizon.co.uk under services.
Thanks

**Comment by caduvieira** [comment] 2015-09-02 17:42
dupe of #4574
+1 that one

**Closed** 2015-09-14 06:20 UTC
