### ISSUE TITLE
Icon request: airbnb

### ISSUE THREAD

**Issue by SeanFmcdonnell** [FortAwesome/Font-Awesome#12376] opened 2018-02-16 17:34 UTC
### What can it be used for?

I have an airbnb experience I would like to share on my personal site with an airbnb logo.

### Example image (optional)

https://press.atairbnb.com/app/uploads/2017/07/airbnb-newsroom-twitter-card-default-2000x1050.png

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-02-16 19:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7650, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-16 19:28 UTC
