### ISSUE TITLE
Icon request: fa-tractor and fa-driver

### ISSUE THREAD

**Issue by henriquev16** [FortAwesome/Font-Awesome#9833] opened 2016-08-29 17:06 UTC
Hi everyone and thank you for the great icons that you create, I use it in every project !

I am doing an agricultural monitoring system and I saw that there is no icons for a tractor or a driver, the most close I got to a tractor was `fa fa-truck` and for the driver it would be nice to have a steering wheel but I didn't find that!

The goal is to track tractor locations and I want the icon to display on my left side bar menu, here is a picture of my system: 

![test](https://cloud.githubusercontent.com/assets/4320695/18059880/0ae3b0ca-6e13-11e6-9a24-406b293689e5.png)

It would be nice to have thoose to icons so I cand replace "Condutores" (Drivers) to a steering wheel or something close and Tractors to a real tractor.

The icon that I used to create the Tractor marker for the map:
https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/tractor-.png

And for the driver it would be nice one of this:
https://cdn2.iconfinder.com/data/icons/gears-wheels-blades/512/steering_wheel-512.png
https://d30y9cdsu7xlg0.cloudfront.net/png/48705-200.png
http://icons.iconarchive.com/icons/icons8/windows-8/512/Transport-Driver-icon.png

Thank you!!

**Comment by tagliala** [comment] 2016-08-29 21:34
Duplicate of #5052 and #3581 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-29 21:34 UTC

**Comment by henriquev16** [comment] 2016-08-29 23:59
Sorry, I searched on fontawesome.io and didn't find!

Thank you.

**Comment by henriquev16** [comment] 2016-08-30 00:40
So, since 2014 without the icon?
