### ISSUE TITLE
Some more Icons about car

### ISSUE THREAD

**Issue by flaviohlm** [FortAwesome/Font-Awesome#12217] opened 2018-02-01 16:35 UTC
gas pump
multiples cars

**Comment by tagliala** [comment] 2018-02-01 16:41
Hi!

Thanks for being part of the Font Awesome Community.

gas pump is a duplicate of #1676, please add a 👍  reaction to that request.

Please clarify "multiple cars": if you are going to request a single icon (fa-cars), please 👍 #7596

If you want to request multiple cars, please take a look at our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-01 16:41 UTC
