### ISSUE TITLE
Icon request: icon-sniper

### ISSUE THREAD

**Issue by flolep2607** [FortAwesome/Font-Awesome#15764] opened 2019-11-01 19:45 UTC
**What can it be used for?**
For game like krunker.io or other

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/24566964/68051764-7cec8b80-fce8-11e9-9544-b53567316683.png)

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Zaczero** [comment] 2019-11-01 20:59
I think a better name for this icon would be fa-gun-rifle _(also create fa-gun for a normal pistol)_. It's a little violent though o.o

**Comment by aethior** [comment] 2022-04-21 23:00
Duplicate of #3560.
Please add a 👍 reaction to that request.

cc/ @tagliala

**Closed** 2022-04-22 11:34 UTC
Labels: new icon, web application icons
