### ISSUE TITLE
Icon request: Kubernetes

### ISSUE THREAD

**Issue by adbusa67** [FortAwesome/Font-Awesome#17189] opened 2020-09-23 09:24 UTC
**What can it be used for?**
It can be used to represent the Kubernetes cluster in UML diagrams

**Example image (optional)**
![image](https://user-images.githubusercontent.com/28667983/93993428-5c1f9f80-fdac-11ea-94c6-f95387685bee.png)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: kubernetes" 
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-09-23 09:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13331, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?q=kubernetes&state=open&type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-23 09:37 UTC
