### ISSUE TITLE
Icon Request: fa-fancy

### ISSUE THREAD

**Issue by tommygebru** [FortAwesome/Font-Awesome#8231] opened 2015-12-29 19:22 UTC
Please consider making an icon for Fancy, many thanks!

**Comment by tommygebru** [comment] 2015-12-29 22:23
Also one for Gitter!

**Comment by aethior** [comment] 2015-12-30 02:50
Hi @tommygebru,

`fa-fancy` is duplicate of #2955 and `fa-gitter` is duplicate of #6535.

Regards.

**Comment by tagliala** [comment] 2015-12-30 10:03
@aethior thanks

**Closed by tagliala** 2015-12-30 10:03 UTC
