### ISSUE TITLE
Icon Request: fa-pinboard

### ISSUE THREAD

**Issue by heyrm** [FortAwesome/Font-Awesome#11580] opened 2017-10-03 11:36 UTC
Hey, it would be great to make an icon for pinboard 

https://pinboard.in/

**Comment by tagliala** [comment] 2017-10-03 12:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #261, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-03 12:45 UTC
