### ISSUE TITLE
Icon Request: fa-disqus

### ISSUE THREAD

**Issue by DrGilberry** [FortAwesome/Font-Awesome#6720] opened 2015-06-10 23:38 UTC
Would be great to have a Disqus social media icon, to go with the others, i.e., Facebook, Twitter, etc.

![disqus](https://cloud.githubusercontent.com/assets/12837277/8096738/1d69b0d4-0f8f-11e5-8a01-5f6a760a63c0.png)

**Comment by ShamanFromSiberia** [comment] 2015-07-01 07:53
+1

**Comment by TheChen5** [comment] 2015-07-26 00:44
Dupe of #2690
"+1" that.
*Search before creating.*

**Comment by tagliala** [comment] 2015-07-26 13:09
@TheChen5 thanks

missed this one too

**Closed by tagliala** 2015-07-26 13:09 UTC
