### ISSUE TITLE
Icon request: Google Scholar and ArXiv

### ISSUE THREAD

**Issue by dsitnik** [FortAwesome/Font-Awesome#18910] opened 2022-04-14 14:12 UTC
Thank you in advance!

**Comment by aethior** [comment] 2022-04-15 02:03
Hi @dsitnik,

This request is duplicate of #541 (Google Scholar) and #3633 (ArXiv).
Please add a 👍 reaction to those requests.

Regards.

cc/ @tagliala

**Closed as completed** 2022-04-15 07:37 UTC
