### ISSUE TITLE
Icon request: Bluesky

### ISSUE THREAD

**Issue by jazzmosax** [FortAwesome/Font-Awesome#20063] opened 2024-01-03 15:09 UTC
### Use case

Social Media links on any website.

### Example image

![bluesky logo2](https://github.com/FortAwesome/Font-Awesome/assets/155250288/9dda8ba1-ebf7-4b3d-8f48-6cd3302ff804)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2024-01-03 15:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19810 , please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-01-03 15:37 UTC
Labels: new icon

**Comment by jazzmosax** [comment] 2024-01-03 15:55
I searched and did not find, but I did not think it would
be a brand icon, so I may have searched in the wrong
place. Upped a thumb on #19810, thanks.

kind regards,
MartinKlein
