### ISSUE TITLE
Icon Request: origin

### ISSUE THREAD

**Issue by Radzio1615** [FortAwesome/Font-Awesome#18708] opened 2022-02-16 10:24 UTC
**What can it be used for?**
Icon can be used as a link to the offer on the Origin website.

**Example image**
![image](https://user-images.githubusercontent.com/40895581/154230916-72b7d968-f1a6-42eb-a35f-2d3fc011f22f.png)

**Comment by tagliala** [comment] 2022-02-17 19:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1290, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-02-17 19:41 UTC
