### ISSUE TITLE
Icon Request: icon-thin-close-o

### ISSUE THREAD

**Issue by dtab428** [FortAwesome/Font-Awesome#9623] opened 2016-07-22 20:50 UTC
Currently, FontAwesome has fa-times, which is a "thick X" icon. Could we get a thinner variant (something similar to https://d13yacurqjgara.cloudfront.net/users/4577/screenshots/1251171/saussy-3.png)?

In addition, fa-times-thin-o would be excellent.

Regarding the name for this new icon: perhaps "fa-close" would do, as a "thin X" is often used for this purpose.

**Comment by tagliala** [comment] 2016-07-22 22:37
close-thin is a duplicate of #1540 , leaving this open as `Icon Request: icon-thin-close-o`

**Comment by sensibleworld** [comment] 2024-07-10 21:18
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/xmark?f=classic&s=thin)

**Closed by sensibleworld** 2024-07-10 21:18 UTC
Labels: new icon, web application icons (legacy category), light, FA Pro
