### ISSUE TITLE
Icon request: icon-shoe

### ISSUE THREAD

**Issue by keshav1829** [FortAwesome/Font-Awesome#13749] opened 2018-08-11 11:02 UTC
I am working on a project of laundry website & i really nead a Shoe Icon.  Please help me out , please.
![soccer48-88776](https://user-images.githubusercontent.com/42294816/43991153-11423c28-9d84-11e8-9f1d-712303a7254c.png)

**Comment by tagliala** [comment] 2018-08-11 11:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3704 or #6031 or #9219 or #3473, please add a 👍  reaction to the proper request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-11 11:06 UTC
