### ISSUE TITLE
Icon request: icon-Boss

### ISSUE THREAD

**Issue by Christiannn** [FortAwesome/Font-Awesome#10717] opened 2017-02-28 15:45 UTC
Hi,
we need a Boss/Leader/Approver Icon... 
you can't get around those kind of people anymore :)

maybe like this? 
https://www.screencast.com/t/KEDOHpJVDzN
(i cant upload to this site for some reason, therefore the link)

**Comment by tagliala** [comment] 2017-02-28 17:52
Please fix the example

**Comment by tagliala** [comment] 2017-02-28 23:44
Maybe this is a duplicate of #3397

**Comment by tagliala** [comment] 2022-03-13 16:28
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2022-03-13 16:28 UTC
Labels: waiting for feedback
