### ISSUE TITLE
Icon Request: fa-beach

### ISSUE THREAD

**Issue by vnelis** [FortAwesome/Font-Awesome#10587] opened 2017-01-30 14:30 UTC
Beaches are iconic images for representing holiday time, days off, etc.
What I have in mind is a simple representation of a beach (with or without a palm tree or umbrella on it) like the one in the attached picture.

![beach-umbrella-512](https://cloud.githubusercontent.com/assets/18003292/22426761/667c9452-e6f8-11e6-9f5a-70021991d79b.png)

I'm developing a website and I need an icon for holidays.

I now take the opportunity to warmly thank you for the nice work you have done with FontAwesome! This package is truly awesome!

Thanks and regards,

Vincent

**Comment by caduvieira** [comment] 2017-01-30 14:43
This is a dupe of #1145 please react to that issue.

**Closed** 2018-08-10 22:53 UTC
