### ISSUE TITLE
Icon request: OLX

### ISSUE THREAD

**Issue by jpgsg** [FortAwesome/Font-Awesome#17925] opened 2021-05-24 08:03 UTC
![23_OLX-512](https://user-images.githubusercontent.com/84705671/119316360-c86dde00-bc6e-11eb-92fe-bd8e17c8eb25.png)
**What can it be used for?**
Classified Ads

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-05-24 08:10
Hi!

Thanks for being part of the Font Awesome Community. Is this a duplicate of #15933

**Comment by aethior** [comment] 2022-04-18 20:46
>Is this a duplicate of #15933?

Yes, the attached logo is the new logo for `www.olx.com`.

Regards.

![OLX-Logo-historia](https://user-images.githubusercontent.com/1769227/163875375-5d8519e5-3c35-418b-8a8e-6fea43749ee9.jpg)
Source: https://1000marcas.net/olx-logo/

**Closed** 2022-04-19 08:37 UTC
Labels: waiting for feedback
