### ISSUE TITLE
Icon request: text-input

### ISSUE THREAD

**Issue by aaflatooni** [FortAwesome/Font-Awesome#17592] opened 2021-01-29 16:42 UTC
**What can it be used for?**
Text input icon would be used for the tool to allow for the input text field.

**Example image (optional)**
Form designer would require an icon for text input field. This icon could help create visual designer that provides an icon to allow for the text input field.

**Icon request checklist**
- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ text-input ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ Yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ Yes ] I have included at least one example image if it could be helpful (optional)
![input-icon](https://user-images.githubusercontent.com/42128476/106302439-fbefad00-6226-11eb-8f68-2f5cc572d3c0.png)

- [ Yes ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-01-29 17:00
Hi!

Thanks for being part of the Font Awesome Community.

This could be a duplicate of:
- Text Area: #1334
- Rename: #1810
- Text Box: #8285

**Comment by sensibleworld** [comment] 2021-03-05 18:47
We've got this coming to the next v6 alpha.

**Closed** 2021-03-30 16:09 UTC
Labels: released, v6-pre
