### ISSUE TITLE
Icon request: icon-douban

### ISSUE THREAD

**Issue by bonjourcs** [FortAwesome/Font-Awesome#10878] opened 2017-04-01 09:52 UTC
Douban is a famous Chinese social network like Wechat, but I didn't find its icon on your website.

I was wondering if you could add this icon to your icon library.

Here is a icon for Douban, I'd appreciate it if you consider my advice.

![douban](https://cloud.githubusercontent.com/assets/18501114/24577494/61290722-1701-11e7-9f6d-5faef87526c4.png)

**Comment by tagliala** [comment] 2017-04-01 11:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1841 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-01 11:25 UTC
