### ISSUE TITLE
Icon request: icon-runningman

### ISSUE THREAD

**Issue by vtorres1976** [FortAwesome/Font-Awesome#7594] opened 2015-10-02 12:03 UTC
Hi,
   I miss more sport icons :(. I would like to make use of them in a web site for a triathlon team. 
![running_man](https://cloud.githubusercontent.com/assets/14940018/10246085/4c1e41f0-690e-11e5-9107-5ccfabd09ca5.png)

Thanks a lot! Love your project!
  Vicky.

**Comment by caduvieira** [comment] 2015-10-02 13:26
dupe of #1156
+1 that request

**Closed** 2015-10-02 16:30 UTC
