### ISSUE TITLE
Icon request: fa-meta

### ISSUE THREAD

**Issue by paulohbalmeida** [FortAwesome/Font-Awesome#9179] opened 2016-05-12 03:33 UTC
Used to symbolize a goal to be achieved .

http://pems.saude.gov.br

![fa-meta](https://cloud.githubusercontent.com/assets/11232884/15203336/f7ed8b8e-17d8-11e6-8977-3950f2de7965.jpg)

**Comment by tagliala** [comment] 2016-05-12 08:44
Duplicate of #5444, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-12 08:44 UTC
