### ISSUE TITLE
Icon request: Logs-file

### ISSUE THREAD

**Issue by julchen812** [FortAwesome/Font-Awesome#15232] opened 2019-07-03 13:24 UTC
**What can it be used for?**
view logs of a deployment

**Example image (optional)**
![log-512](https://user-images.githubusercontent.com/52497990/60594968-623fef80-9da6-11e9-8858-22c2f35539e0.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-07-03 14:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9689, please add a 👍 reaction to that request.

Please also note that the SVG framework offers the feature of stacking text on icons

Ref: https://jsfiddle.net/tagliala/7hod8jy3/15/
Docs: https://fontawesome.com/how-to-use/on-the-web/styling/layering

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-07-03 14:02 UTC
