### ISSUE TITLE
标志哪里，可否增加一个QQ空间的icon

### ISSUE THREAD

**Issue by feiyit** [FortAwesome/Font-Awesome#11442] opened 2017-08-25 07:01 UTC
标志哪里，可否增加一个QQ空间的icon

一个五角星，里面有个z字

**Comment by tagliala** [comment] 2017-08-25 08:45
Hi!

Thanks for being part of the Font Awesome Community.

Please use English

Closing here

**Closed by tagliala** 2017-08-25 08:45 UTC

**Comment by icai** [comment] 2017-08-25 13:03
@tagliala he said  add a icon for Qzone.com social website (Tencent)

**Comment by tagliala** [comment] 2017-08-25 14:00
@icai thanks

qzone is a duplicate of #3993
