### ISSUE TITLE
Icon Request: fa-research-gate

### ISSUE THREAD

**Issue by halirutan** [FortAwesome/Font-Awesome#11341] opened 2017-07-30 22:23 UTC
It would be nice to include the [Research Gate](https://www.researchgate.net) logo since it is one of the major platforms for scientists. The official logo can be downloaded [here](https://www.researchgate.net/press) and it includes a transparent, rectangular png image that should be easy to vectorize. 

![rg_square_green](https://user-images.githubusercontent.com/511683/28757557-f82cff1a-7585-11e7-9317-072a838dcca3.png)

It would be truly awesome if we had this in the fonts as it can be used on websites where *author information* typically include a list of social platforms with logos. Look, e.g. [here](https://mmistakes.github.io/minimal-mistakes/about/) for an example.

**Comment by tagliala** [comment] 2017-07-31 07:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3634, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-31 07:44 UTC
