### ISSUE TITLE
Icon request: yell

### ISSUE THREAD

**Issue by blackburnravers** [FortAwesome/Font-Awesome#16294] opened 2020-03-10 01:18 UTC
**What can it be used for?**
Place on my site with other reviewer icons
https://www.yell.com

**Example image (optional)**
 
![yell_icon_256x256](https://user-images.githubusercontent.com/2501790/76270385-00a51e80-626d-11ea-9435-026bd0020e4a.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-03-10 11:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8578, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-10 11:04 UTC
