### ISSUE TITLE
Icon request: icon-flipsetter

### ISSUE THREAD

**Issue by sabbythesage** [FortAwesome/Font-Awesome#12416] opened 2018-02-21 18:23 UTC
### Icon request checklist

- [  ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sabbythesage** [comment] 2018-02-21 19:29
How many votes do we need before it qualifies to be in Font Awesome?

**Comment by tagliala** [comment] 2018-02-21 20:42
@sabbythesage please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by aethior** [comment] 2022-05-07 00:20
Duplicate of #12415.

cc/ @tagliala

**Closed** 2022-05-07 09:26 UTC
Labels: brand icon
