### ISSUE TITLE
Icon Request: fa-www

### ISSUE THREAD

**Issue by gluleci** [FortAwesome/Font-Awesome#10497] opened 2017-01-09 12:53 UTC
I want to icon for "www" website.

like that
![world-wide-web](https://cloud.githubusercontent.com/assets/6782727/21767199/4b10b7ee-d67b-11e6-9f31-058f996cf009.jpg)

**Comment by tagliala** [comment] 2017-01-09 13:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6763, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-09 13:37 UTC
