### ISSUE TITLE
Icon Request: fa-sword-o

### ISSUE THREAD

**Issue by SacreDPamiR** [FortAwesome/Font-Awesome#7364] opened 2015-09-02 11:05 UTC

**Comment by caduvieira** [comment] 2015-09-02 17:30
dupe of #1449
+1 that one

**Comment by tagliala** [comment] 2015-09-14 06:22
Renaming as sword-o

**Comment by tagliala** [comment] 2019-07-04 17:27
Available in FA Pro 5.4

https://fontawesome.com/icons/sword?style=solid

**Closed by tagliala** 2019-07-04 17:27 UTC
Labels: Available in FA Pro, new icon, web application icons

**Comment by SacreDPamiR** [comment] 2019-07-08 10:04
Thank you @tagliala  😅
