### ISSUE TITLE
Icon request: cc-sofort

### ISSUE THREAD

**Issue by piet-loeffler** [FortAwesome/Font-Awesome#16714] opened 2020-05-25 18:27 UTC
**What can it be used for?**
Payment options, icons for Mastercard and Visa are available. (Addition: cc-Klarna, for the Klarna payment option)

**Example image (optional)**
![klarna_sofort](https://user-images.githubusercontent.com/52973457/82835977-d9520b00-9ec5-11ea-8880-642813c05f24.png)

**Comment by tagliala** [comment] 2020-05-25 18:32
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4342, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-25 18:32 UTC
