### ISSUE TITLE
Icon Request: fa-derrick

### ISSUE THREAD

**Issue by StavroMueller** [FortAwesome/Font-Awesome#10263] opened 2016-11-21 19:12 UTC
- Used in oil & gas industry 
- Also useful as an icon on maps
- Could have an alternate name `fa-well`
- Helps greatly when listing many different types of concepts on the same page - A lease, land, and a well

![welliconimage](https://cloud.githubusercontent.com/assets/3442610/20496654/eb5c4b72-afda-11e6-8e42-8dfe1d5d22d5.png)

**Comment by ryan-yyc** [comment] 2016-11-21 22:40
Quite the coincidence, came here looking for just this, and here it is. I would get an absolutely amazing amount of use out of this for map displays, business analytics, internal web apps, and so on.

The first thing would actually be in Microsoft Power BI. One of the data visualizations (Facet Key) can use FA icon codes, so this would be absolutely amazing in my Power BI dashboards.

**Comment by tagliala** [comment] 2016-11-21 22:57
Is this a duplicate of #3644?

**Comment by AntJanus** [comment] 2016-11-22 05:21
@tagliala Looks like it. The issue that you referenced  was opened over two years ago and seems to have a few positive responses but no official response.

How long does it take to get feedback on what will or won't be approved to be included? Just wondering because I could use this icon right away.

**Comment by tagliala** [comment] 2016-11-22 09:59
> How long does it take to get feedback on what will or won't be approved to be included? Just wondering because I could use this icon right away.

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Duplicate of #3644, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-22 09:59 UTC
Labels: waiting for feedback
