### ISSUE TITLE
Icon request: EyeEm

### ISSUE THREAD

**Issue by AntoniniP** [FortAwesome/Font-Awesome#12516] opened 2018-03-04 18:21 UTC
[https://www.eyeem.com](https://www.eyeem.com)

**Comment by tagliala** [comment] 2018-03-04 20:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2346, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-04 20:10 UTC
