### ISSUE TITLE
Icon request: fa-hand-holding-house-xmark (shelter in place sip cancel)

### ISSUE THREAD

**Issue by stirumala76** [FortAwesome/Font-Awesome#10018] opened 2016-10-04 13:29 UTC
Can you please provide icon set for shelter in place

Icon request: icon-sip
![sip](https://cloud.githubusercontent.com/assets/4968423/19075968/07ed64e2-8a15-11e6-8aac-9409233f9def.png)

Icon request: icon-sip-cancel
![sip_cancel](https://cloud.githubusercontent.com/assets/4968423/19075969/07ee74cc-8a15-11e6-846c-4d35a22d03cd.png)

**Comment by aethior** [comment] 2022-05-06 22:56
Related? Duplicate? #11845

cc/ @tagliala

**Comment by tagliala** [comment] 2022-05-07 11:01
I'm going to leave this open for the second request. I will not consider `fa-hand-holding-house` and `fa-hand-holding-house-xmark` strongly related,  because otherwise I should also consider `fa-hand-holding-house-check`, and maybe `fa-hand-holding-plus`, `fa-hand-holding-minus`...

**Comment by sensibleworld** [comment] 2024-07-11 20:18
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/11845)

**Closed by sensibleworld** 2024-07-11 20:18 UTC
Labels: new icon, hands (category), household (category), Duplicate
