### ISSUE TITLE
Icon request: fa-nfc

### ISSUE THREAD

**Issue by nocour** [FortAwesome/Font-Awesome#16440] opened 2020-04-09 01:08 UTC
**What can it be used for?**
Card Technology NFC

**Example image (optional)**
https://es.wikipedia.org/wiki/Near_field_communication

**Icon request checklist**
- as bluetooth icon

**Comment by tagliala** [comment] 2020-04-09 07:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1695, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-04-09 07:11 UTC
