### ISSUE TITLE
Icon Request: fa-id-card

### ISSUE THREAD

**Issue by abigby** [FortAwesome/Font-Awesome#9106] opened 2016-05-03 14:12 UTC
It would be nice to have an icon that represents a User's ID card.

**Comment by tagliala** [comment] 2016-05-03 14:20
Duplicate of #825 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-03 14:20 UTC
