### ISSUE TITLE
Need a flip camera icon

### ISSUE THREAD

**Issue by aniruddhashevle** [FortAwesome/Font-Awesome#13798] opened 2018-08-21 15:33 UTC
There isn't any flip camera icon, we need that!

**Comment by tagliala** [comment] 2018-08-21 15:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3956, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-21 15:38 UTC
