### ISSUE TITLE
Icon request: icon-lyft

### ISSUE THREAD

**Issue by slsmag** [FortAwesome/Font-Awesome#8526] opened 2016-02-10 15:13 UTC
Icon request: 
icon-lyft

Icons used for easy indentification of topics in bulletin boards, forums, etc. related to the those organizations
![](https://cloud.githubusercontent.com/assets/10437313/12951113/bedd5fa0-cfde-11e5-8be3-b0357675d5bd.gif)

**Comment by tagliala** [comment] 2016-02-11 12:28
uber is a duplicate of #4826, please +1 that request

leaving this open as fa-lyft

**Comment by vinniejames** [comment] 2016-03-16 04:26
:+1:

**Comment by dan-0** [comment] 2016-09-26 03:24
:+1:

**Comment by tagliala** [comment] 2017-09-25 09:02
Hi, thanks for your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Closed by tagliala** 2017-09-25 09:02 UTC
Labels: brand icons, new icon
