### ISSUE TITLE
New icon: Floorplan

### ISSUE THREAD

**Issue by jasonmitchell42** [FortAwesome/Font-Awesome#12124] opened 2018-01-17 23:29 UTC
Hi Team,

It would be great to have a floorplan icon to add to your ever-growing library of awesome fonts! (see what I did there:) )

Thanks & Keep up the great work!

Jason

**Comment by PeterShaggyNoble** [comment] 2018-01-18 09:24
Duplicate of #12064

**Closed** 2018-01-18 10:07 UTC
