### ISSUE TITLE
Icon Request: flower

### ISSUE THREAD

**Issue by daisylady** [FortAwesome/Font-Awesome#3103] opened 2014-03-19 13:12 UTC
I would like to request the addition of a daisy flower. My website daisyparadise is entirely dedicated to daisy flowers and the icons currently available lack sufficient icons for horticultural websites, apart from the icon called leaf. There are a lot of gardening websites and gardening related icons would be helpful, such as watering can, spade, seedling, greenhouse, shovel, hose pipe, etc. Thank you!

**Comment by tagliala** [comment] 2015-01-28 14:34
duplicate of #2037, please +1 that request

**Closed by tagliala** 2015-01-28 14:34 UTC
Labels: new icon, web application icons
