### ISSUE TITLE
Icon Request: stumbleupon-square

### ISSUE THREAD

**Issue by shefik** [FortAwesome/Font-Awesome#10966] opened 2017-04-19 21:13 UTC
You have have `stumbleupon` and `stumbleupon-circle`, but missing `stumbleupon-square` for consistency.

There are already `*-square` social media icons (such as `facebook-square`).

**Comment by tagliala** [comment] 2017-04-19 21:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3535, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-19 21:53 UTC
