### ISSUE TITLE
Icon request: Warehouse

### ISSUE THREAD

**Issue by Minikibber** [FortAwesome/Font-Awesome#10418] opened 2016-12-22 10:14 UTC
![warehouse_with_boxes-512](https://cloud.githubusercontent.com/assets/24714037/21422426/da1cbe62-c837-11e6-9c8b-1921bb3dc58f.png)

**Comment by tagliala** [comment] 2016-12-22 13:45
Duplicate of #4560, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-22 13:45 UTC
