### ISSUE TITLE
Icon Request: fa-dice

### ISSUE THREAD

**Issue by evydaemon** [FortAwesome/Font-Awesome#11802] opened 2017-11-25 15:11 UTC
Need for a dice icon
3-sided view
maybe dice sides SIX, THREE, ONE - something that looks nice
isometric perspective from x,y,z = degrees(45,45,45)

**Comment by tagliala** [comment] 2017-11-25 16:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2622 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-25 16:19 UTC
