### ISSUE TITLE
Icon request: fa-signalmsg

### ISSUE THREAD

**Issue by aldaw** [FortAwesome/Font-Awesome#16600] opened 2020-05-08 11:15 UTC
**What can it be used for?**
Signal Messanger share button, like WhatsApp, WeChat etc. 

**Example image (optional)**
![](https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/a7/08/8d/a7088ddb-8a4e-5cd6-e571-0735e24ca957/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1200x630wa.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-08 19:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7434, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-08 19:12 UTC
