### ISSUE TITLE
Icon Request - Chess Set

### ISSUE THREAD

**Issue by vladimirsolovey** [FortAwesome/Font-Awesome#9828] opened 2016-08-28 22:29 UTC
Chess set - which could be used for multiple applications. Chess symbols could be used for keywords like "strategy", "royal", "king", "queen", etc.

**Comment by tagliala** [comment] 2016-08-29 08:49
Duplicate of #1815 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-29 08:49 UTC
