### ISSUE TITLE
Ship (fa-ship-alt) 

### ISSUE THREAD

**Issue by xmuskrat** [FortAwesome/Font-Awesome#14945] opened 2019-04-25 18:22 UTC
Ship, but from the side.

Front view is really confusing to my users.

<img width="173" alt="Screen Shot 2019-04-25 at 11 21 30 AM" src="https://user-images.githubusercontent.com/59917/56758783-4e479400-674c-11e9-90fb-0b53e8a24848.png">

**Comment by tagliala** [comment] 2019-04-25 18:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13449, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-25 18:29 UTC
