### ISSUE TITLE
Please separate the brand icons into another font

### ISSUE THREAD

**Issue by mjolnic** [FortAwesome/Font-Awesome#5877] opened 2015-03-07 13:00 UTC
In every version more and more brand icons are added to the project, which increases the font size unnecessarily. Not all the brands are used in all projects. Please, consider splitting the brand icons into a new font file, or at least give the possibility to use a lightweight version of the main font file.
Thanks.

**Comment by tagliala** [comment] 2015-03-07 13:34
almost a duplicate of #1322

Font Awesome Black Tie is already following this approach

Meanwhile, here there are some suggestions: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here

**Closed by tagliala** 2015-03-07 13:34 UTC
