### ISSUE TITLE
icon request: icon-php

### ISSUE THREAD

**Issue by RichardNesbitt** [FortAwesome/Font-Awesome#10104] opened 2016-10-22 06:59 UTC
I'd love to see more icons for programming languages. This could go as far as jquery, java, php, c#, etc. But for now, I'd really love a php icon!
![php](https://cloud.githubusercontent.com/assets/9487517/19617627/748876cc-97ea-11e6-836e-970de0b699b5.png)

**Comment by tagliala** [comment] 2016-10-22 09:46
Duplicate of #1420 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-22 09:46 UTC
