### ISSUE TITLE
Icon request: Signal Messenger

### ISSUE THREAD

**Issue by ikmal-workspace** [FortAwesome/Font-Awesome#19494] opened 2022-12-27 07:57 UTC
My website use three medium of communications via text; WhatsApp, Telegram, and Signal. Font Awesome only got WhatsApp and Telegram, but not Signal. So, I would like to request Font Awesome to add new brands icon for Signal.

**Comment by tagliala** [comment] 2022-12-27 08:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7434, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-12-27 08:46 UTC
