### ISSUE TITLE
Icon for resume or cv

### ISSUE THREAD

**Issue by mohamedkhaledyousef** [FortAwesome/Font-Awesome#12656] opened 2018-03-21 07:43 UTC

**Comment by tagliala** [comment] 2018-04-06 12:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3533, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 12:58 UTC
