### ISSUE TITLE
fa-tooth or fa-dentist 

### ISSUE THREAD

**Issue by michealjroberts** [FortAwesome/Font-Awesome#12440] opened 2018-02-25 20:09 UTC
Pro license holder here - could I please have either a tooth or an icon representing a dentist done pretty quickly please :D

I need this for a community based website that is going live this coming Thursday...

**Comment by tagliala** [comment] 2018-02-25 20:26
Hi!

Thanks for being part of the Font Awesome Community.

tooth is a duplicate of #1289, please add a 👍 reaction to that request

> I need this for a community based website that is going live this coming Thursday...

I should advise you to consider a custom solution if you need this icon in a short while: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

I'm not sure if request from Pro backers are treated at the same way of free users, so please open this request on the Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro/issues, asking for clarifications

I have to close this

Hope it helps

**Closed by tagliala** 2018-02-25 20:26 UTC
