### ISSUE TITLE
Icon Request: fa-wine

### ISSUE THREAD

**Issue by tzeller** [FortAwesome/Font-Awesome#11599] opened 2017-10-07 12:43 UTC
hardly anything for the restaurant industry
[fa-wine.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364618/fa-wine.pdf)

**Comment by tagliala** [comment] 2017-10-07 12:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3614, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-07 12:52 UTC
