### ISSUE TITLE
Icon request: BBB (Better Business Bureau)

### ISSUE THREAD

**Issue by bbreines** [FortAwesome/Font-Awesome#12183] opened 2018-01-29 23:55 UTC

**Comment by tagliala** [comment] 2018-01-30 09:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5797, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-30 09:08 UTC
