### ISSUE TITLE
Icon request: mongodb

### ISSUE THREAD

**Issue by Berkmann18** [FortAwesome/Font-Awesome#13707] opened 2018-08-04 22:12 UTC
### What can it be used for?

MongoDB is a NoSQL language and possibly the most popular one, used in MEAN, MERN, MEN, ... stacks for the web, it's also good to have when listing skills as FA icons and for stacks description. 
### Example image (optional)

![MongoDB](https://upload.wikimedia.org/wikipedia/en/thumb/4/45/MongoDB-Logo.svg/250px-MongoDB-Logo.svg.png)
### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Petrouchka** [comment] 2018-08-05 06:54
No more need to vote here, see https://forkawesome.github.io/Fork-Awesome/

**Comment by Petrouchka** [comment] 2018-08-05 13:27
But you can ask one. On FontAwesome, you can wait for 100 years.
"Since Oct 22, 2016, Font Awesome has frozen all pull requests proposing new icons. With Fork Awesome, we are welcoming all your pull requests."

**Comment by itsmelion** [comment] 2018-10-19 03:11
dupe of #2725

**Closed** 2018-10-19 08:05 UTC
