### ISSUE TITLE
Icon Request: fa-teamviewer

### ISSUE THREAD

**Issue by Brilbroeder** [FortAwesome/Font-Awesome#6593] opened 2015-05-29 14:46 UTC
An icon representing a flat version of the teamviewer logo.

https://www.teamviewer.com/

**Comment by iuwan** [comment] 2015-05-30 19:56
+1, that would be awesome!

**Comment by tagliala** [comment] 2015-05-30 21:45
duplicate of ##5383, please +1 that request

closing here

**Closed by tagliala** 2015-05-30 21:45 UTC

**Comment by mennows** [comment] 2015-09-08 08:35
+1

**Comment by meggink** [comment] 2015-09-29 12:44
+1 That would be awesome

**Comment by tagliala** [comment] 2015-09-29 14:17
locking, this is a duplicate
