### ISSUE TITLE
 Icon Request: fa-caret-expand-left, fa-caret-expand-right 

### ISSUE THREAD

**Issue by mojtabakaviani** [FortAwesome/Font-Awesome#5123] opened 2014-12-03 13:53 UTC
![fa-caret-expand](https://cloud.githubusercontent.com/assets/1667525/5281311/2246d81a-7b11-11e4-92eb-56fab44a75a0.png)

**Comment by sensibleworld** [comment] 2024-07-11 13:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/16965)

**Closed by sensibleworld** 2024-07-11 13:33 UTC
Labels: new icon, arrows (category), Duplicate
