### ISSUE TITLE
Icon request: icon-swimming

### ISSUE THREAD

**Issue by declanhoward** [FortAwesome/Font-Awesome#12228] opened 2018-02-02 16:09 UTC
Hi all the happy folk at Font Awesome.
I maintain a swimming club website (www.fermoyswimmingclub.ie) and would love to be able to use icons for swimmers and for medals.
I have attached something like what I had in mind - obviously no need for the colour, just flat icons would be 'awesome' ;)

Regards,
Declan Howard
![gold medal](https://user-images.githubusercontent.com/36015678/35742759-6675b670-0833-11e8-9c6c-782c85581acb.jpg)
![swimming](https://user-images.githubusercontent.com/36015678/35742760-6696aeb6-0833-11e8-9c2c-2c23717e3bfc.png)

**Comment by PeterShaggyNoble** [comment] 2018-02-07 11:37
Medal is a duplicate of #1898 and swimming is a duplicate of #5771. See also #3285.

**Comment by tagliala** [comment] 2018-02-07 11:41
@PeterShaggyNoble thanks

Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of  #5771, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-07 11:41 UTC
