### ISSUE TITLE
Icon Request: fa-construction fa-contractor fa-hardhat

### ISSUE THREAD

**Issue by Row-Z** [FortAwesome/Font-Awesome#8373] opened 2016-01-19 22:03 UTC
Essentially this icon can be used for under construction, or to represent a contractor, or to represent a hard hat.  
![image](https://cloud.githubusercontent.com/assets/16786360/12433292/28546374-beb5-11e5-995d-91543560c5a7.png)
![image](https://cloud.githubusercontent.com/assets/16786360/12433310/4a89864a-beb5-11e5-8f11-bd9948844db7.png)
![image](https://cloud.githubusercontent.com/assets/16786360/12433322/5cb8e112-beb5-11e5-8e87-f46385d1e537.png)

**Comment by tagliala** [comment] 2016-01-20 10:13
duplicate of #5790 , please +1 that request

closing here

**Closed by tagliala** 2016-01-20 10:13 UTC
