### ISSUE TITLE
Icon Request: fa-swarm

### ISSUE THREAD

**Issue by AtknUludag** [FortAwesome/Font-Awesome#5640] opened 2015-02-10 21:03 UTC
Hello,
Could you put the icon in fontawesome the Swarm?

![](https://ss1.4sqi.net/img/press/swarm/mark/beemark_512x512-1198b82cbb0985850a045a62467dbfb2.png)

**Comment by AtknUludag** [comment] 2015-02-11 21:10
?

**Comment by tagliala** [comment] 2015-02-14 13:12
Duplicate of #3430. Please +1 that request and take a look at this wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here

**Closed by tagliala** 2015-02-14 13:12 UTC
