### ISSUE TITLE
Icon Request: fa-voice (or tongue)

### ISSUE THREAD

**Issue by eichgi** [FortAwesome/Font-Awesome#9784] opened 2016-08-21 14:04 UTC
This icon would be a person speaking, I mean with voice leaving his mouth for example.

**Comment by tagliala** [comment] 2016-08-21 19:10
Duplicate of #2096, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-21 19:10 UTC
