### ISSUE TITLE
Icon Request: fa-double-bracket

### ISSUE THREAD

**Issue by morgansmithh** [FortAwesome/Font-Awesome#11935] opened 2017-12-14 15:26 UTC
We have a brand that uses the [ ] brackets around the title. We have several reports in our database specifically for that brand, and it would be awesome to be able to use the [ ] emoji to indicate that the reports belong to it. 

I've included a picture, but the emoji wouldn't need the words between it. Just the brackets! 
![screen shot 2017-12-14 at 10 25 57 am](https://user-images.githubusercontent.com/22217299/33999723-3cbbfc46-e0b9-11e7-9901-c0f418e43ae8.png)

**Comment by tagliala** [comment] 2017-12-14 16:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6151, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-14 16:14 UTC
