### ISSUE TITLE
Icon request: fa-customer-details

### ISSUE THREAD

**Issue by schoutenzekerheid** [FortAwesome/Font-Awesome#8820] opened 2016-03-24 10:42 UTC
Hi all,

We need an icon for Customer or User Details, like:
![image](https://cloud.githubusercontent.com/assets/17614935/14014841/640726d0-f1b5-11e5-94c4-8afe88aec478.png)

Thnx in advance!

**Comment by tagliala** [comment] 2016-03-24 11:58
duplicate of #825 , please +1 that request

closing here

**Closed by tagliala** 2016-03-24 11:58 UTC

**Comment by bcosca** [comment] 2016-03-24 18:07
Why close both #8820 and #825 when they cross-reference each other and both issues are not addressed?
