### ISSUE TITLE
Icon request: moon-phase Phases of the moon

### ISSUE THREAD

**Issue by stevenkolstad** [FortAwesome/Font-Awesome#18886] opened 2022-04-07 17:19 UTC
Phases of the moon from New to Full. Could be named like utility class color shades.

moon-phase-light - Full Moon
moon-phase-50 - Waning Gibbous 
moon-phase-100 - Third Quarter
moon-phase-200 - Waning Crescent
moon-phase-dark - New Moon
moon-phase-500 - Waxing Crescent 
moon-phase-400 - Waxing Gibbous
moon-phase-300 - First Quarter

https://spaceplace.nasa.gov/moon-phases/en/

**Comment by tagliala** [comment] 2022-04-07 17:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13163, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-04-07 17:28 UTC
