### ISSUE TITLE
Tree hierarchy (icon request)

### ISSUE THREAD

**Issue by Rikijs** [FortAwesome/Font-Awesome#13922] opened 2018-09-08 10:20 UTC
Please add new `tree hierarchy` icon

_example 1_
![image](https://user-images.githubusercontent.com/18629166/45253039-17617100-b369-11e8-9063-fd5ed09e6309.png)

_example 2_
![image](https://user-images.githubusercontent.com/18629166/45253083-c605b180-b369-11e8-8b23-290734dfe71c.png)

**Comment by tagliala** [comment] 2018-09-08 10:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1343 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-08 10:46 UTC
