### ISSUE TITLE
Icon request:

### ISSUE THREAD

**Issue by tserenbud** [FortAwesome/Font-Awesome#13133] opened 2018-05-14 08:31 UTC
icon-kakao talk
![kakao2](https://user-images.githubusercontent.com/29880075/39986688-4ea42972-5717-11e8-8654-855db606d7fe.png)

**Comment by tagliala** [comment] 2018-05-14 09:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3688, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-14 09:07 UTC
