### ISSUE TITLE
icon-request : icon-running

### ISSUE THREAD

**Issue by sidtechno** [FortAwesome/Font-Awesome#12893] opened 2018-04-18 13:49 UTC
Icon for running, runner (male, female)
Good for Triathlon site, running club

**Comment by Ronyo** [comment] 2018-07-28 06:55
+1

**Comment by tagliala** [comment] 2018-07-28 08:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1156, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-28 08:39 UTC
