### ISSUE TITLE
Icon request: ko-fi

### ISSUE THREAD

**Issue by Matse2005** [FortAwesome/Font-Awesome#17542] opened 2021-01-10 17:52 UTC
**What can it be used for?**
It is the logo from te website ko-fi. 

**Example image (optional)**
https://www.dropbox.com/sh/am6zv113bbri2bu/AAD8cv2qpkGl0YFJz10pXpAOa/Most%20Used?dl=0&preview=Ko-fi_Icon_RGB_rounded.png&subfolder_nav_tracking=1

**Icon request checklist**
- [x] Single
- [x] Yes
- [x] Yes
- [x] Yes
- [x] Yes

**Comment by tagliala** [comment] 2021-01-10 18:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12607, please add a 👍 reaction to that request.

**I can confirm that this request does not appear in the Search at the moment, but there are 4 other duplicates pointing to the original one**

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-01-10 18:06 UTC
