### ISSUE TITLE
Icon Request: fa-washing

### ISSUE THREAD

**Issue by Hansjoerg2** [FortAwesome/Font-Awesome#7062] opened 2015-07-28 20:24 UTC
some label for washing instructions for textiles

**Comment by tvirelli** [comment] 2015-08-05 17:03
@Hansjoerg2 do you have an example image of what you are looking for?

**Comment by tagliala** [comment] 2015-08-05 17:24
maybe a duplicate of #6742, but I can't keep this open for the same reason

for a washing machine, please +1 #5914 

Feel free to comment if you are requesting something else

Closing here

**Closed by tagliala** 2015-08-05 17:24 UTC
