### ISSUE TITLE
Icon Request: fa-zhihu

### ISSUE THREAD

**Issue by swumqw** [FortAwesome/Font-Awesome#11562] opened 2017-09-26 14:44 UTC
Zhihu is a Chinese question-and-answer website where questions are created, answered, edited and organized by the community of its users. Its website, zhihu.com, was launched on January 26, 2011. The number of registered users of Zhihu had exceeded 10 millions by the end of 2013, and reached 17 millions as of May 2015 with 250 million monthly page views.
In Classical Chinese, "Zhīhū" (知乎) means "Do you know?". Chinese-language internet users nowadays increasingly resort to Zhihu for expert knowledge and insights into various topics.

**Comment by tagliala** [comment] 2017-09-26 15:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4439, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-26 15:37 UTC
