### ISSUE TITLE
Icon request: icon-squareinc

### ISSUE THREAD

**Issue by cdweldco** [FortAwesome/Font-Awesome#6091] opened 2015-03-28 21:02 UTC
https://squareup.com/  a square up icon would be great to add to credit card processing.
Plan on using it on our website when discussing payment options.
Icon: https://squareup.com/reader

**Comment by tagliala** [comment] 2015-03-28 23:05
duplicate of #2477, please +1 that request

Since this request is not popular, I should suggest you to consider a custom build of FA: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here

**Closed by tagliala** 2015-03-28 23:05 UTC
