### ISSUE TITLE
Scholar icon

### ISSUE THREAD

**Issue by Willtl** [FortAwesome/Font-Awesome#12901] opened 2018-04-18 20:10 UTC
Would be possible to add google scholar icon? 

https://scholar.google.com/

**Comment by tagliala** [comment] 2018-04-18 21:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #541, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-18 21:47 UTC
