### ISSUE TITLE
Icon Request: icon-ameblo

### ISSUE THREAD

**Issue by neylorstevo** [FortAwesome/Font-Awesome#5761] opened 2015-02-23 15:32 UTC
Japanese Blogging Website called Ameba or ameblo
http://ameblo.jp/

**Comment by tagliala** [comment] 2015-02-26 14:07
duplicate of #5441 , please +1 that request

closing here

**Closed by tagliala** 2015-02-26 14:07 UTC

**Comment by jimjam12321** [comment] 2015-09-20 22:58
i'd like the icon url too please
