### ISSUE TITLE
Pro Icons Not Found During Docker Install Step

### ISSUE THREAD

**Issue by BradChandler** [FortAwesome/Font-Awesome#18279] opened 2021-09-17 14:30 UTC
I am building a Vue single page application using the pro version of fontawesome. 
The below packages have been installed for this purpose:
    "@fortawesome/fontawesome-pro": "^5.15.4",
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/pro-duotone-svg-icons": "^5.15.4",
    "@fortawesome/pro-light-svg-icons": "^5.15.4",
    "@fortawesome/pro-regular-svg-icons": "^5.15.4",
    "@fortawesome/pro-solid-svg-icons": "^5.15.4",
    "@fortawesome/vue-fontawesome": "^2.0.2",

As suggested on the fontawesome site, I have placed a .npmrc file at the root of the project with applicable information inserted
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=NPM_TOKEN

When running the program locally, everything functions as expected, icons are displayed, and no errors occur. 

However, during the Docker build, npm install generates the following error and fails

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-light-svg-icons - Not found
npm ERR! 404
npm ERR! 404  '@fortawesome/pro-light-svg-icons@5.15.4' is not in the npm registry.

**Expected behavior**
npm install should completed successfully when doing Docker build

**Version and implementation**
node version 14.17.0
npm version 7.24.0

Other issues have suggested using the .npmrc file on a per-project basis and this has succeeded in the past but I was using a nuxt-fontawesome package and all functioned perfectly.

**Comment by tagliala** [comment] 2021-09-17 14:38
Hi!

Thanks for being part of the Font Awesome Community.

> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-light-svg-icons - Not found

This means that docker is not reading the `.npmrc` configuration, because it is trying to connect to the public `npm` repo at `https://registry.npmjs.org`. A successful attempt would have shown `https://npm.fontawesome.com/` instead

Please double check that your docker container is correctly reading `.npmrc`

As a Pro customer, you can request dedicated support at hello@fontawesome.com

Closing here because the issue is out of the scope of this repository, but feel free to comment and provide more information if I didn't get this request

**Closed by tagliala** 2021-09-17 14:38 UTC

**Comment by BradChandler** [comment] 2021-09-17 15:43
Thank you 
For anyone looking for assistance here, I found a couple of helpful posts on SO about configuring the Dockerfile to read from the .npmrc file. 

The first one: https://stackoverflow.com/questions/50851711/docker-and-private-packages-with-npmrc
Highly related and may work. 

Per this answer: https://stackoverflow.com/questions/51189701/use-private-npm-repo-in-docker
I had to do a little different...
FROM node:latest as build-stage
WORKDIR /app
COPY package*.json ./
COPY .npmrc ./
RUN echo "//registry.npmjs.org/:_authToken=YOUR_SECRET" > ~/.npmrc && \
   npm install && \
   rm -f /app/.npmrc
COPY ./ .
RUN npm run build

**Comment by tagliala** [comment] 2021-09-17 17:19
@BradChandler thanks for the feedback
