### ISSUE TITLE
Icon request: clothes-hanger

### ISSUE THREAD

**Issue by naomi789** [FortAwesome/Font-Awesome#16013] opened 2020-01-04 01:57 UTC
I'd like an icon that clearly represents clothes/fashion. It seems to me that a clothes hanger would be more universal than a hat/shirt/shoes/etc. I have users on my website who are fashion models (I want an icon to show which section of the website they should use) and it looks like the only icon that's related would be a shopping basket/bag/cart, but I don't want my users to think that they're checking out or making a purchase on my website. 

![image](https://user-images.githubusercontent.com/22847131/71758247-558e7800-2e6b-11ea-97cd-ceff3496733e.png)

**Comment by tagliala** [comment] 2020-01-04 09:09
Hi!

Thanks for being part of the Font Awesome Community.

I cannot see the example, just a black-ish square, but I think that this request is a duplicate of #1659, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-04 09:09 UTC
