### ISSUE TITLE
Icon Request: fa-salad fa-meat fa-dessert

### ISSUE THREAD

**Issue by projetphpsen** [FortAwesome/Font-Awesome#11337] opened 2017-07-28 20:49 UTC
Hi everyone, I am working on an app for a restaurant and it'd be great to have icons to represent different meals. At least, three, for the three parts of a meal.
I suggest a simple salad :green_salad: , a meat (steak or chicken leg) :poultry_leg: , and a cake :cake:  for the dessert.
Pizza could also be great ! :pizza: 

Thanks a lot !

**Comment by tagliala** [comment] 2017-07-28 21:22
Hi!

Thanks for being part of the Font Awesome Community.

Pizza: duplicate of #4493, please 👍 that request
Cake: duplicate of #8154, please 👍 that request
Salad: duplicate of #7272, please 👍 that request
Meat: duplicate of #6510, please 👍 that request

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Please also take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

All duplicates, closing here

**Closed by tagliala** 2017-07-28 21:22 UTC
