### ISSUE TITLE
Discord Icon

### ISSUE THREAD

**Issue by alex10455** [FortAwesome/Font-Awesome#11123] opened 2017-05-30 11:58 UTC
Hey guys, can you please add the discord icon?
https://discordapp.com/assets/f8389ca1a741a115313bede9ac02e2c0.svg
https://discordapp.com/assets/1c8a54f25d101bdc607cec7228247a9a.svg
Thank you.

**Comment by tagliala** [comment] 2017-05-30 13:31
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-30 13:31 UTC
