### ISSUE TITLE
Icon Request: fa-glasses

### ISSUE THREAD

**Issue by quiksillvr** [FortAwesome/Font-Awesome#11452] opened 2017-08-28 21:58 UTC
A pair of reading glasses would make a nice addition to your super awesome icon list.  These could be used to mark a list as "to be reviewed" or "under review".  This could be used for a "Reviewer" role in an application.

**Comment by tagliala** [comment] 2017-08-29 08:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1043 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-29 08:33 UTC
