### ISSUE TITLE
Icon Request: fa-bucket

### ISSUE THREAD

**Issue by patrick-collins-429** [FortAwesome/Font-Awesome#9921] opened 2016-09-16 20:34 UTC
would like a simple bucket icon

**Comment by tagliala** [comment] 2016-09-17 11:25
Duplicate of #788, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-17 11:25 UTC
