### ISSUE TITLE
Apply transform to pseudo-class

### ISSUE THREAD

**Issue by rykotovark** [FortAwesome/Font-Awesome#11393] opened 2017-08-13 13:08 UTC
I have a buttons group. First and last elements have rounded borders. If I use rotation, for example:

 `<button class="fa-level-down fa-rotate-90" />`

then `transform: rotate(90deg)` is applied to button tag and breaks my rounded borders.

Wouldn't it be more naturally to move transform out of `.fa-rotate-*` to `&::before` pseudo? 
I fixed it for myself, but it would be cool if it was a default behavior. Or will it break something in styling? Sorry, I'm new to CSS.

So, it's just a suggestion and you can close it if you wish.

**Comment by tagliala** [comment] 2017-08-13 16:20
Hi,

Thanks for being part of the Font Awesome Community.

I'm pretty sure this is a duplicate of an existing request. I've tried several keywords and synonyms but I'm not able to find the original one at the moment.

There are reasons for this being done on the base element, but I can't remember why. It should be related to browser compatibility.

If you have special needs, please use custom CSS transformations.

Also, please also note that `button` is not a [void element](https://www.w3.org/TR/html51/syntax.html#void-elements) and the recommended way of using font awesome is `<i class="fa fa-level-down fa-rotate-90"></i>`, so your example should be

```html
<button><i class="fa fa-level-down fa-rotate-90"></i></button>
```

Hope it helps

Closing here

**Closed by tagliala** 2017-08-13 16:20 UTC
