### ISSUE TITLE
Icon Request: fa-softdrink

### ISSUE THREAD

**Issue by tzeller** [FortAwesome/Font-Awesome#11600] opened 2017-10-07 12:44 UTC
hardly anything for the restaurant industry
[fa-softdrinks.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364619/fa-softdrinks.pdf)

**Comment by tagliala** [comment] 2017-10-07 12:58
Related to: #6122

**Comment by timtjtim** [comment] 2017-10-07 13:00
Pretty much a duplicate of that to be honest - at the small sizes these icons get to, a paper drinks cup is unlikely to be distinguishable.

**Comment by tagliala** [comment] 2018-08-09 07:30
Duplicate of #6122

**Closed by tagliala** 2018-08-09 07:30 UTC
Labels: food (category), new icon
