### ISSUE TITLE
Icon Request: houzz-icon

### ISSUE THREAD

**Issue by jasonbrueckner** [FortAwesome/Font-Awesome#5973] opened 2015-03-16 00:25 UTC
I need an icon for Houzz (Houzz.com). You will see similar icons in the footer of my site: www.pure-design-interiors.com (the Facebook icon is a placeholder right now). What else would you need from me? Thank you in advanced.

I have included links to examples of the logo:

https://www.google.com/search?q=houzz+icon&safe=off&es_sm=119&biw=1408&bih=753&source=lnms&tbm=isch&sa=X&ei=Sx4GVaHiJ4eggwSc2oPwBw&ved=0CAYQ_AUoAQ&dpr=0.9#imgdii=_

![houzz icon](https://cloud.githubusercontent.com/assets/11493628/6659011/d1834004-cb50-11e4-99d2-da208b189708.png)

**Comment by JenWillDesign** [comment] 2015-03-16 03:28
+1

**Comment by jasonbrueckner** [comment] 2015-03-21 16:28
I'm not sure how this works. Is there anything more I need to do? I'm not sure how to create this icon. Thank you so much!

**Comment by tagliala** [comment] 2015-03-21 17:06
duplicate of #2039, please +1 that request

@jasonbrueckner I should advise you to take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here

**Closed by tagliala** 2015-03-21 17:06 UTC

**Comment by jasonbrueckner** [comment] 2015-03-21 17:23
Thnx

**Comment by markream** [comment] 2015-03-24 16:57
+1
