### ISSUE TITLE
Icon Request: fa-art

### ISSUE THREAD

**Issue by flavianohonorato** [FortAwesome/Font-Awesome#5400] opened 2015-01-15 13:22 UTC
one icon related to art, or something that relates.
![ed_infantil](https://cloud.githubusercontent.com/assets/4780299/5758050/53e9a522-9ca0-11e4-884a-597ec5d7d340.png)

**Comment by tagliala** [comment] 2015-01-15 15:01
duplicate of #244 , please +1 that request

closing here

**Closed by tagliala** 2015-01-15 15:01 UTC
