### ISSUE TITLE
Icon Request: fa-metronome

### ISSUE THREAD

**Issue by maxsennin** [FortAwesome/Font-Awesome#7076] opened 2015-07-29 16:34 UTC
Hi,

I'd like an icon of metronome!

Something like this : ![metronome](https://cloud.githubusercontent.com/assets/13066669/8963435/5f97175a-3620-11e5-8460-9ee2373f6789.png)

Thanks a lot!

**Comment by TheChen5** [comment] 2015-07-29 16:46
Dupe of #6232
+1 that
:mag_right: before:heavy_plus_sign:

**Comment by maxsennin** [comment] 2015-07-30 07:02
Oups

**Comment by tagliala** [comment] 2015-07-30 18:36
@TheChen5 thanks

closing here

**Closed by tagliala** 2015-07-30 18:36 UTC
