### ISSUE TITLE
Icon request: star-sharp

### ISSUE THREAD

**Issue by markmeikle** [FortAwesome/Font-Awesome#14647] opened 2019-02-15 21:21 UTC
### What can it be used for?

displaying star ratings and reviews

### Example image (optional)

![my new star system adjusts top layer width to match star rating](https://user-images.githubusercontent.com/20950563/52884914-0d704500-3135-11e9-8be1-b6122b9da240.jpg)
![google s sharp stars allow for better precision in the display](https://user-images.githubusercontent.com/20950563/52884915-0d704500-3135-11e9-9d08-352bd665d878.jpg)

### Icon request checklist

- [single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [check] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [found a closed issue, but feel this deserves reconsideration] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [check] I have included at least one example image if it could be helpful (optional)
- [check] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by markmeikle** [comment] 2019-02-15 21:22
I am replicating Google's review stars and wish I had another option for my stars. Google's stars are sharper than font awesome's. This makes them better at handling precise display of ratings (such as 4.9 stars, for example). This issue was raised before and closed for style reasons, but I am raising it again because there are practical functionality reasons to do this. It's more precise.

**Comment by tagliala** [comment] 2019-08-01 09:58
Ops...

I've just noticed that this is a duplicate of #5848

Since there aren't upvotes here, please add a 👍 to #5848

**Closed by tagliala** 2019-08-01 09:58 UTC
Labels: new icon, web application icons
