### ISSUE TITLE
Icon Request: fa-bedroom and fa-bathroom

### ISSUE THREAD

**Issue by johnrossell** [FortAwesome/Font-Awesome#7968] opened 2015-11-24 05:34 UTC
Bedroom and bathroom icons. 
Bedroom count, bathroom count and car count icons are very commonly used on property data / listing websites

**Comment by caduvieira** [comment] 2015-11-24 12:25
bathroom dupe of #2670 
bed available in http://fontawesome.io/icon/bed/

please +1 that one

**Comment by skifan** [comment] 2015-11-24 21:13
+1 from me too! I would also use for property website. I can use fa-car and fa-bed for car & bed but can't find anything remotely related to bathroom. Eg shower, tub, toilet, drops of water, or combo of fa-female and fa-male as used in restaurant bathrooms?

**Comment by TheChen5** [comment] 2015-11-25 02:33
@skifan this is a duplicate of #2670.
To support it, please +1 *that* request.

**Comment by tagliala** [comment] 2015-11-25 12:58
@caduvieira @TheChen5 thanks

closing here

**Closed by tagliala** 2015-11-25 12:58 UTC

**Comment by johnrossell** [comment] 2016-03-15 11:00
Please re-open this request. 
#2670 is for a washroom icon with a male / female illustration. This icon is good for illustrating a commercial washroom in a airport, hotel etc. 

However, the 2670 icon is a poor fit in the context of a residential property (e.g. bathroom count of a "for sale" property listing). Residential properties do not have separate male and female bathrooms.

An icon of a bath, shower or toilet is commonly used for this purpose. 
In addition, the 2670 icon will not scale well to smaller icon dimensions.

**Comment by tagliala** [comment] 2016-03-15 11:12
>  the 2670 icon will not scale well to smaller icon dimensions.

I agree

Could you please post a single color example suitable for 14px icon size of the icon you are requesting?
