### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by kkarimi313** [FortAwesome/Font-Awesome#17659] opened 2021-02-23 23:56 UTC
![Aparat_icon_color_black_1024](https://user-images.githubusercontent.com/79549491/108924489-f6cc2500-764f-11eb-8ab8-c6685464caa4.png)

**What can it be used for?**
this is the icon of the Aparat website which is a social platform similar to youtube

**Example image (optional)**
![Aparat_icon_color_black_1024](https://user-images.githubusercontent.com/79549491/108924489-f6cc2500-764f-11eb-8ab8-c6685464caa4.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by kkarimi313** [comment] 2021-02-23 23:57
this is the icon of the Aparat website which is a social platform similar to youtube

**Comment by tagliala** [comment] 2021-02-24 08:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5204, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-02-24 08:42 UTC
