### ISSUE TITLE
Icons are not centered properly or they have different sizes

### ISSUE THREAD

**Issue by alvarotrigo** [FortAwesome/Font-Awesome#7409] opened 2015-09-07 11:59 UTC
Icons are not centered properly. Very noticeable when using different icons:

[Reproduction online](http://jsfiddle.net/6or8h5z0/)

I made a zoom over a `font-size: 14px;` list here:
![font-awesome](https://cloud.githubusercontent.com/assets/1706326/9716288/3d3a6482-5560-11e5-802b-0adc5a731805.gif)

**Comment by tagliala** [comment] 2015-09-13 09:55
comment has a problem described here #1624

icons have not the same height and width by design choice

**Comment by VitalyPankin** [comment] 2016-02-19 14:11
![image](https://cloud.githubusercontent.com/assets/2627271/13177635/6ee91cd8-d72b-11e5-8f77-10e7ccfbdc31.png)
It's fckn ridiculous, are u serious? Icons shouldn't have same height or width, they should have same VISUAL SIZE that's nothing about actual sizing. And they should be centered of course.

**Comment by catz** [comment] 2016-02-19 14:17
+1

**Comment by dzalozhnov** [comment] 2016-02-19 14:19
+

**Comment by tagliala** [comment] 2016-02-19 16:49
@VitalyPankin please be nice: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

mobile phone issue was reported here: #928 It's a design choice (wich not agree fwiw)

In order to center icons, please add `fa-fw` class. Note that odd-width icons could have issues on some browsers

**Comment by VitalyPankin** [comment] 2016-02-19 16:58
My bad, sorry. It's not only about fa-mobile icon. As you can see on my image many icons doesn't match. Not only mobile, fa-phone is not much bigger than fa-mobile in comparsion with fa-cubes for example. It's the first typographic rule, that font's glyphs can't have different weight. and we have a lot of them.

**Comment by tagliala** [comment] 2016-02-19 17:06
> It's the first typographic rule, that font's glyphs can't have different weight. and we have a lot of them.

I agree with you. There are many icons that are not visually consistent. If you could provide a list we can start a new issue, but `fa-mobile` is smaller by design, sorry

**Comment by timgavin** [comment] 2016-03-14 00:29
`fa-comment` drives me nuts because its height is shorter; it drops below other icons. My "everything has to be lined up" OCD is getting so antsy over this I'm actually looking at material icons - and I'm a big fan of Font Awesome. :(

**Comment by tagliala** [comment] 2016-03-14 10:44
@timgavin fa-comment is not centered, please take a look at #1624

**Comment by bugdanov** [comment] 2016-08-28 07:07
FontAwesome is really awesome thanks :-)  but yeah +1 for the normalization:  when using icons for buttons with nothing more than the icon centered in a container, I have (like everybody else) to resize/recenter every "non-normalized" icon using per-icon css rules and that's really boring to find the right scale and margins. ... ,

**Comment by sensibleworld** [comment] 2021-09-29 22:51
Closing this, as we've tried to standardize icons across version 5, and even more so across version 6.

**Closed by sensibleworld** 2021-09-29 22:51 UTC
Labels: enhancement
