### ISSUE TITLE
Icon request: icon-pluralsight

### ISSUE THREAD

**Issue by maitesin** [FortAwesome/Font-Awesome#12071] opened 2018-01-10 13:25 UTC
This would be a brand icon.

I use several of the brand icons in my website to link to my profile in their platform. With the pluralsight icon I would do that.

The following is their logo. So I guess it would need to be similar to it.
![pluralsight](https://user-images.githubusercontent.com/4683221/34775011-89bb46c2-f609-11e7-8bd1-d7a70d2277fd.jpg)

**Comment by PeterShaggyNoble** [comment] 2018-01-10 14:09
This is a duplicate of #6701; you should 👍 that instead.

**Closed** 2018-01-10 15:00 UTC

**Comment by maitesin** [comment] 2018-01-10 15:33
@PeterShaggyNoble Sorry about that. I searched for issues with `plural` on it or `sight` expecting it to find it, but it does not show up when you do that. However, it shows up when you search for `pluralsight`. Anyway, I just gave :+1: to the issue you mentioned. Thanks!
