### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by iabduul7** [FortAwesome/Font-Awesome#16589] opened 2020-05-07 09:07 UTC
I would like to have a new icon for Fiverr, as many of us use font-awesome in personal portfolio websites and hence many of us might want to add Fiverr link to their websites. So adding it with icon would be much much AWESOME

**Comment by tagliala** [comment] 2020-05-07 09:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5970 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-07 09:09 UTC

**Comment by iabduul7** [comment] 2020-05-07 10:59
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> This request is a duplicate of #5970 , please add a 👍 reaction to that request.
> 
> Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones
> 
> You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work
> 
> Closing here

its been five years since that issue was opened and still no progress?? great!
