### ISSUE TITLE
Icon Request: icon-douban

### ISSUE THREAD

**Issue by lanegg** [FortAwesome/Font-Awesome#8999] opened 2016-04-16 02:36 UTC
Douban is a Chinese SNS website, which has 1 billion registered users.

This is Douban's wiki.

I love fontAwesome, it has icons of Chinese SNS website, like icon-weibo and icon-weixin, I really want icon-douban as well, thank you ：）

**Comment by tagliala** [comment] 2016-04-16 09:42
Duplicate of #1841, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-16 09:42 UTC
