### ISSUE TITLE
Icon request: icon-codecademy

### ISSUE THREAD

**Issue by ericbutler555** [FortAwesome/Font-Awesome#9556] opened 2016-07-13 02:02 UTC
I'd love to see a few of the most popular "learn to code" websites included in Font Awesome's brand icon set:

- Codecademy
- Code School
- Treehouse
- Udacity, etc.

### Examples:

![codecademy-icon](https://cloud.githubusercontent.com/assets/10527805/16789250/ee0601e2-4879-11e6-840c-514983d9f24c.png)

![codeschool-icon](https://cloud.githubusercontent.com/assets/10527805/16789318/9b83469a-487a-11e6-9ce2-58c35858fb61.png)

![treehouse-icon](https://cloud.githubusercontent.com/assets/10527805/16789347/d81040f4-487a-11e6-959c-be0fe775f3c6.png)

### Use cases:

For web developers (like myself) who are making themselves an online resume and/or portfolio, a stack of graphical links to one's profiles (list of badges, achievements and course completions) on these coding sites is nearly as important as the stack of graphical links to one's social media profiles (Twitter, LinkedIn, etc, which Font Awesome already covers).

Thanks for considering it!

**Comment by wolfy1339** [comment] 2016-07-13 02:38
Codeacademy: duplicate of #3320

**Closed** 2016-07-13 09:29 UTC

**Comment by rdefa001** [comment] 2019-02-05 11:37
Unfortunately they didn't consider it. We are now on 2019 and I can't still find them.
