### ISSUE TITLE
Icon request: Unsplash

### ISSUE THREAD

**Issue by BAMsyme** [FortAwesome/Font-Awesome#16020] opened 2020-01-05 23:34 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
As a link to Unsplash accounts. In the footer or header of websites along with other social icons.
**Example image (optional)**
Insert the example image here if necessary.
<img width="373" alt="Screen Shot 2020-01-06 at 12 21 50 PM" src="https://user-images.githubusercontent.com/53142247/71787745-6ebc4200-3080-11ea-8ea4-e688a213c5e0.png">

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-01-06 08:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11508, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-06 08:51 UTC
