### ISSUE TITLE
Icon request: hand-ok

### ISSUE THREAD

**Issue by jamesdonn88** [FortAwesome/Font-Awesome#18771] opened 2022-03-03 14:17 UTC
It already exists as two "OK's" in the hands-asl-interpreting icon, would just be handy having as it's own icon :)

**Comment by aethior** [comment] 2022-03-06 22:56
Hi @jamesdonn88,

Duplicate of #8064.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed as completed** 2022-03-06 23:17 UTC
