### ISSUE TITLE
Icon Request: fa-shopify

### ISSUE THREAD

**Issue by unlockr** [FortAwesome/Font-Awesome#12923] opened 2018-04-20 14:20 UTC
Shopify icon :grin:

**Comment by tagliala** [comment] 2018-04-20 14:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3850, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-20 14:48 UTC

**Comment by unlockr** [comment] 2018-04-20 14:49
So sorry

**Comment by waltergammarota** [comment] 2018-11-08 21:34
Since I needed this I did it on my own font. 
In case it can be useful for someone, here it is: 
https://github.com/waltergammarota/wgicons
[wgicons](https://github.com/waltergammarota/wgicons
)
