### ISSUE TITLE
Icon request: fab fa-metacritic

### ISSUE THREAD

**Issue by yovantichrist** [FortAwesome/Font-Awesome#12951] opened 2018-04-25 16:56 UTC
It would be very useful to have a Metacritic brand icon.
Thanks for the awesome work.

**Comment by tagliala** [comment] 2018-04-25 17:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5129, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-25 17:54 UTC
