### ISSUE TITLE
Icon request: saw

### ISSUE THREAD

**Issue by storkweb** [FortAwesome/Font-Awesome#19502] opened 2023-01-01 14:43 UTC
Hi
I would very much like a saw (the tool to saw a piece of wood :-) icon for a project of mine.
I LOVE fontAWESOME icons !
Keep up the VERY good work !
And Happy new year by the way

**Comment by tagliala** [comment] 2023-01-01 14:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10938, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

> And Happy new year by the way

Happy New Year!

**Closed as completed by tagliala** 2023-01-01 14:49 UTC

**Comment by storkweb** [comment] 2023-01-01 23:04
Hi,

I ALSO can see that that request you mentionned is over 5 years old and DOESN'T seems to have been YET fullfilled... You probably have spend less time drawing that icon than closing all those duplicate requests, which, by the way seems to indicate a real shared interest.
Won't wait another 5 years and will find another solution, thanks for nothing

⁣Didier SZYLOWICZ - StorkWEB​

Le 1 janv. 2023, 15:49, à 15:49, Geremia Taglialatela ***@***.***> a écrit:

**Comment by tagliala** [comment] 2023-01-02 08:24
> I ALSO can see that that request you mentionned is over 5 years old and DOESN'T seems to have been YET fullfilled.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work
