### ISSUE TITLE
Icon Request: computer chip

### ISSUE THREAD

**Issue by gavinkalika** [FortAwesome/Font-Awesome#11154] opened 2017-06-09 15:22 UTC
can i have a computer chip icon? need and icon for emv 

http://www.creditcards.com/credit-card-news/emv-faq-chip-cards-answers-1264.php

**Comment by tagliala** [comment] 2017-06-23 20:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8630, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-23 20:47 UTC
