### ISSUE TITLE
Numbering Icons

### ISSUE THREAD

**Issue by cqbdesigns** [FortAwesome/Font-Awesome#16548] opened 2020-04-29 13:34 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
– This could simply be used as bullets or progress list.
– We had multiple features where user have to complete things in order. We would do the numbering and then when completed it would convert to check-circle.
– I can picture this have a filled and outline version for solid and light.
– 1,2,3,4,5,6,7,8,9,0 or could even go to 99.

**Example image (optional)**
Insert the example image here if necessary.
https://image.flaticon.com/icons/svg/61/61496.svg

**Icon request checklist**
- [Not sure what this means] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [one-circle, two-circle] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [Yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Yes] I have included at least one example image if it could be helpful (optional)
- [No] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-04-29 13:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15591, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Also:
- this is a request for **40** up to **400** new icon
- it is possible to stack icons and text with the current features of FA: https://github.com/FortAwesome/Font-Awesome/issues/15591#issuecomment-534210217
- refers to #15495 

Closing here

**Closed by tagliala** 2020-04-29 13:56 UTC
