### ISSUE TITLE
Icon request: icon-image-list

### ISSUE THREAD

**Issue by gonguinguen** [FortAwesome/Font-Awesome#7292] opened 2015-08-24 11:29 UTC
I'm awful with image editors, so I couldn't attach an image. But the idea would be to use the "fa-picture-o" icon, and duplicate it, to give the idea of a "pile" of images, that is, an image list. I'm thinking in the fa-picture-o icon with a thich shadow, to give the idea that behind the first picture there is another picture: an image list :)

I'm using FontAwesome to develop a set of magazine/media templates, using icons to help the visitor to differentiate between content that has audio, video, an image, or a list of images, a gallery.

Thanks in advance! FontAwesome. AwesomeWork!

**Comment by My1** [comment] 2015-09-04 12:26
the Idea isnt bad.

**Comment by tagliala** [comment] 2015-09-13 09:38
this should be a duplicate of #855 , please +1 that request

closing here

**Closed by tagliala** 2015-09-13 09:38 UTC
