### ISSUE TITLE
Icon-Request: fa-patreon

### ISSUE THREAD

**Issue by jjwedemyer** [FortAwesome/Font-Awesome#9564] opened 2016-07-13 19:39 UTC
![patreon-logo](https://www.patreon.com/images/patreon_navigation_logo_mini_orange.png)

**Comment by tagliala** [comment] 2016-07-13 20:58
Duplicate of #3257 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-13 20:58 UTC
