### ISSUE TITLE
Icon Request: fa-video-camera-slash

### ISSUE THREAD

**Issue by jpezninjo** [FortAwesome/Font-Awesome#11923] opened 2017-12-12 23:50 UTC
Use: Want to use it with a web app that will have an option to turn off the video camera, similar to how there is a microphone and a microphone-slash counterpart

**Comment by tagliala** [comment] 2017-12-13 09:24
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3765 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-13 09:24 UTC

**Comment by jpezninjo** [comment] 2017-12-13 21:13
ahh shoot. sorry about that! thanks!
