### ISSUE TITLE
Request: Increase icon size at page https://fortawesome.github.io/Font-Awesome/cheatsheet/

### ISSUE THREAD

**Issue by alexbreems** [FortAwesome/Font-Awesome#6217] opened 2015-04-13 14:44 UTC
Hi!

You could increase icon size at page https://fortawesome.github.io/Font-Awesome/cheatsheet/
from 14px to 30px. Very difficult to look for the 14px size icons on the page.

THIS
![image](https://cloud.githubusercontent.com/assets/11540427/7117924/9629d75a-e204-11e4-9e01-398ae60bdf49.png)
TO THIS
![2015-04-13 17-37-00 font awesome cheatsheet opera](https://cloud.githubusercontent.com/assets/11540427/7117871/4b752426-e204-11e4-91cf-dc1ace5a6046.png)

.fa {
  display: inline-block;
  font: normal normal normal 14px/1 FontAwesome;
  **font-size: 30px;**
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
}

Best regards,
Alex

**Comment by tagliala** [comment] 2015-04-13 15:32
Hi,

this is a duplicate of #1793

As I said, I like this feature but for some reason Dave prefers the actual size. Please share your thoughts in the above post

Closing here

**Closed by tagliala** 2015-04-13 15:32 UTC
