### ISSUE TITLE
Icon Request: fa-mot

### ISSUE THREAD

**Issue by stevegoossens** [FortAwesome/Font-Awesome#4450] opened 2014-09-16 14:58 UTC
Purpose: MOT testing at garages

![pitstop_johnstone_mot](https://cloud.githubusercontent.com/assets/2405344/4289228/eab5c0c4-3db1-11e4-99f5-e20c3cef0035.jpg)

**Comment by quickcalldave** [comment] 2015-04-28 17:09
Yes please, have a client I would love to use this on.

**Comment by sensibleworld** [comment] 2024-07-11 13:50
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/8722)

**Closed by sensibleworld** 2024-07-11 13:50 UTC
Labels: new icon, web application icons (legacy category), Duplicate
