### ISSUE TITLE
Icon Request - fa-psychology

### ISSUE THREAD

**Issue by alexmanini** [FortAwesome/Font-Awesome#8634] opened 2016-02-23 15:04 UTC
Hello everyone,
Should create the icon below please?
it is possible to use it on several pages on psychology.
Thank you and sorry for the bad english
![exemplo400](https://cloud.githubusercontent.com/assets/7672562/13255602/99a6c4c8-da25-11e5-9766-df8381e1f60f.png)

**Comment by tagliala** [comment] 2016-02-23 16:26
duplicate of #5836, please +1 that request and consider using the standard unicode point

**Closed by tagliala** 2016-02-23 16:26 UTC
