### ISSUE TITLE
Icon Request: fa-unity

### ISSUE THREAD

**Issue by dickeysingh** [FortAwesome/Font-Awesome#9708] opened 2016-08-05 22:51 UTC
see Unity3D.com

**Comment by dickeysingh** [comment] 2016-08-05 22:53
http://www.scribillpay.com/wp-content/uploads/2013/04/icon-unity3d.png

**Comment by aethior** [comment] 2016-08-06 01:58
Duplicate of #2888. Please :+1: that.

**Closed** 2016-08-06 10:00 UTC
