### ISSUE TITLE
Icon request: firefighter helmet

### ISSUE THREAD

**Issue by karen-lake** [FortAwesome/Font-Awesome#18266] opened 2021-09-13 04:19 UTC
**What can it be used for?**
Used on emergency communications and other information such as firefighter training requirements

**Icon request checklist**
- [ ] This is a single icon
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
Thankyou :)

**Comment by sensibleworld** [comment] 2024-07-11 15:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/4815)

**Closed** 2024-07-19 09:04 UTC
Labels: new icon, web application icons (legacy category), Duplicate
