### ISSUE TITLE
Brand request: yii2 framework logo

### ISSUE THREAD

**Issue by monta990** [FortAwesome/Font-Awesome#19558] opened 2023-02-13 21:52 UTC
### Description

its possible add it to the free version?

### Official website

https://www.yiiframework.com/

### Brand guidelines

https://www.yiiframework.com/logo

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2023-02-13 21:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8982, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

> its possible add it to the free version?

Brands are parts of the free version

Closing here

**Closed as completed by tagliala** 2023-02-13 21:56 UTC
Labels: brand icon
