### ISSUE TITLE
Icon Request: fa-self-Timer

### ISSUE THREAD

**Issue by ogawamasato** [FortAwesome/Font-Awesome#10995] opened 2017-04-25 19:24 UTC
common in camera button.  Self Timer to use when taking picture in some cases (as you know).
CAPA    DCG-003
![self-timer](https://cloud.githubusercontent.com/assets/17801068/25403699/28de4860-2a38-11e7-9746-f96170bc4b17.png)

**Comment by tagliala** [comment] 2017-04-25 22:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6869, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-25 22:03 UTC
