### ISSUE TITLE
Icon Request: fa-memory

### ISSUE THREAD

**Issue by ninwaya** [FortAwesome/Font-Awesome#7905] opened 2015-11-17 19:12 UTC
I didn't see in the list any icon that fit memory game.
Sincerely
ninwaya

**Comment by tagliala** [comment] 2015-11-17 23:09
any example?

**Comment by ninwaya** [comment] 2015-11-18 20:42
I am thinking about card memory play
you can to look on the left bar of my homepage there you can see a picture on http://www.nohadra.com

**Comment by tagliala** [comment] 2015-11-18 20:59
Sorry, could you please post here on github a single color example?

I need a better title

Contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by tagliala** [comment] 2015-11-19 10:21
@ninwaya sorry but I have to keep track of issues, so I need proper issues :)

I need a single color example, suitable for 14px icon size for this request.

Example:
Good title: `fa-car`

Good Example: 
![image](https://cloud.githubusercontent.com/assets/556268/11268120/95e6adf6-8eaf-11e5-8191-75b190e4e46f.png)

**Comment by MVcodeartbr** [comment] 2015-11-27 15:38
![can-stock-photo_csp11703876](https://cloud.githubusercontent.com/assets/3662026/11444405/10b2e65a-950c-11e5-993e-03ab1150cf0b.jpg)
![g0457795](https://cloud.githubusercontent.com/assets/3662026/11444406/10b56696-950c-11e5-9d7e-50ea3818d311.gif)
![can-stock-photo_csp8696594](https://cloud.githubusercontent.com/assets/3662026/11444407/10bddf4c-950c-11e5-9e41-ab9d28f8a036.jpg)
![screenshot 98](https://cloud.githubusercontent.com/assets/3662026/11444416/1a70b078-950c-11e5-9e7f-f1af7b05eef2.jpg)

**Comment by awreece** [comment] 2016-03-27 02:38
This is a dupe of https://github.com/FortAwesome/Font-Awesome/issues/3239

**Comment by aethior** [comment] 2016-10-01 06:59
@tagliala I think you can close here.

**Comment by tagliala** [comment] 2016-10-01 11:42
No feedback, closing here

**Closed by tagliala** 2016-10-01 11:42 UTC
