### ISSUE TITLE
itunes is now apple music

### ISSUE THREAD

**Issue by pixieaka** [FortAwesome/Font-Awesome#15149] opened 2019-06-13 08:23 UTC
`[ fa-itunes, fa-itunes-note ]` should replace with `[ fa-apple-music, fa-apple-music-note ]`

**Comment by tagliala** [comment] 2019-06-13 10:38
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #10500

I know that iTunes is going to be replaced by Apple Music / Apple TV / Apple Podcast, but AFAIK it is still a thing (on Windows and macOS < Catalina, at least).

Closing here, but feel free to comment if I'm missing something

**Closed by tagliala** 2019-06-13 10:38 UTC
