### ISSUE TITLE
Icon request: icon-browser

### ISSUE THREAD

**Issue by tomlutzenberger** [FortAwesome/Font-Awesome#11227] opened 2017-06-26 00:49 UTC
I'd love to see a "generic browser" icon, something like this:
![Generic Browser Icon](https://user-images.githubusercontent.com/5536910/27521179-0ac3c5a0-5a1a-11e7-83b8-a29d5033dfbe.jpg)

**Comment by tagliala** [comment] 2017-06-26 07:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2655 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-26 07:52 UTC
