### ISSUE TITLE
Brand request: Square

### ISSUE THREAD

**Issue by tbysctt** [FortAwesome/Font-Awesome#19154] opened 2022-06-29 07:12 UTC
### Description

I'd like to request the addition of the Square, Inc. logo please. It's a popular billing platform used by myself and millions of other merchants to sell to ~24 million monthly active customers.

![image](https://user-images.githubusercontent.com/45221333/176374551-1682676f-c9f3-429b-b685-ef608bc3ef8f.png)

### Official website

https://squareup.com/

### Brand guidelines

https://developer.squareup.com/built-with-square

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2022-06-29 07:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2477, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-06-29 07:39 UTC
Labels: brand icon
