### ISSUE TITLE
Apple Music: fa-apple-music

### ISSUE THREAD

**Issue by Pranshu258** [FortAwesome/Font-Awesome#16236] opened 2020-02-24 16:50 UTC
https://www.apple.com/itunes/marketing-on-music/identity-guidelines.html

**Comment by tagliala** [comment] 2020-02-24 16:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10500, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-02-24 16:58 UTC
