### ISSUE TITLE
Icon request: tooth

### ISSUE THREAD

**Issue by ActionableResearch** [FortAwesome/Font-Awesome#8997] opened 2016-04-15 19:14 UTC
We use icons to represent our specialties on our website. 

This icon would accompany information about how we interact with the Dental and Orthodontic industries.

![tooth](https://cloud.githubusercontent.com/assets/18489848/14572413/918041be-0303-11e6-8ca7-bb7fc28d498a.jpg)
![tooth2](https://cloud.githubusercontent.com/assets/18489848/14572415/91827b64-0303-11e6-92b1-d18c5d7df23e.jpg)
![dental and orthodontic icons](https://cloud.githubusercontent.com/assets/18489848/14572414/918086c4-0303-11e6-9690-fe46335fbc28.jpg)

**Comment by PeterShaggyNoble** [comment] 2016-04-15 20:01
Dupe of [#1289](https://github.com/FortAwesome/Font-Awesome/issues/1289), you should +1 that one instead.

**Closed** 2016-04-15 20:11 UTC
