### ISSUE TITLE
Icon request: fa-old-cellphone

### ISSUE THREAD

**Issue by nicolasvahidzein** [FortAwesome/Font-Awesome#13716] opened 2018-08-05 12:24 UTC
Hello there, 

i love your font set, truly wonderful.

Please consider the following:

satellite
cellphone with keypads (which is different than a smartphone)
antenna (like a parabola)

Thank you.

**Comment by tagliala** [comment] 2018-08-05 19:48
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Satellite is a duplicate of #2404, please +1 that request
Satellite dish / Radar dish is a duplicate of #5659, please +1 that request

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Leaving this open as fa-old-cellphone

**Comment by sensibleworld** [comment] 2024-07-11 19:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/mobile-retro?f=classic&s=solid)

**Closed by sensibleworld** 2024-07-11 19:23 UTC
Labels: new icon, web application icons (legacy category), FA Pro
