### ISSUE TITLE
Icon request: fa-signal-level-X

### ISSUE THREAD

**Issue by ntvsx193** [FortAwesome/Font-Awesome#7658] opened 2015-10-12 08:34 UTC
![Low signal](http://monosnap.zanozahost.ru/2015-10-12_01_3212d8.png) ![Half signal](http://monosnap.zanozahost.ru/2015-10-12_01_cdf556.png) ![Full signal](http://monosnap.zanozahost.ru/2015-10-12_01_c821d8.png)

**Comment by tagliala** [comment] 2015-10-12 09:35
duplicate of #1870 , please +1 that request

closing here

**Closed by tagliala** 2015-10-12 09:35 UTC

**Comment by DanielGrozdev** [comment] 2017-04-26 02:38
+1
That would make a lot of developers happy ;]
