### ISSUE TITLE
Icon Request: fa-youtube-play-square

### ISSUE THREAD

**Issue by veritoanimus** [FortAwesome/Font-Awesome#8452] opened 2016-01-29 14:02 UTC
The YouTube play icon is always problematic if you want to use it with a group of squared social icons.  You should also offer a YouTube play with square encapsulation to match sizing for the other icons as allowed per YouTube's logo usage policies: https://www.youtube.com/yt/brand/using-logo.html

**Comment by dnavarrojr** [comment] 2016-02-03 18:07
+1

**Comment by TheEssemCraft** [comment] 2017-04-20 23:43
I made a mockup SVG, what do you think?
[youtube-play-square.zip](https://github.com/FortAwesome/Font-Awesome/files/945737/youtube-play-square.zip)

**Comment by tagliala** [comment] 2017-04-21 11:37
Sorry but this is a duplicate of #7238 and I didn't notice

**Closed by tagliala** 2017-04-21 11:37 UTC
Labels: brand icons, new icon
