### ISSUE TITLE
Icon request: fa-smugmug

### ISSUE THREAD

**Issue by modeling** [FortAwesome/Font-Awesome#7239] opened 2015-08-14 20:07 UTC
An icon for www.smugmug.com please!

**Comment by TheChen5** [comment] 2015-08-14 22:37
Dupe of #2561 
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-14 23:27
thanks @TheChen5 , really appreciate

closing here

**Closed by tagliala** 2015-08-14 23:27 UTC
