### ISSUE TITLE
un-delete , restore icon

### ISSUE THREAD

**Issue by omer-sds** [FortAwesome/Font-Awesome#10490] opened 2017-01-08 00:23 UTC
can we have a restore icon for the deleted items with the name like fa-restore, or if there is one and i dont know about.

**Comment by tagliala** [comment] 2017-01-08 10:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4090, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-08 10:23 UTC
