### ISSUE TITLE
Icon Request: fa-flipchart, fa-teacher

### ISSUE THREAD

**Issue by jofran73** [FortAwesome/Font-Awesome#7226] opened 2015-08-13 14:28 UTC
Thanks for this great project.
I would be happy if there would be icons for a category "education", i.e.
- an icon representing a seminar or course (my idea would be a flipchart)
- an icon representing a teacher / trainer / instructor / mentor (my idea would be a person pointing to a chalkboard)

Joerg

**Comment by caduvieira** [comment] 2015-08-13 19:04
partially duplicate #4987 and #4079

**Comment by tagliala** [comment] 2015-08-15 09:22
flipchart should be a duplicate of #866

**Comment by kristingreen** [comment] 2016-02-12 14:05
+1 for this request.

It would be great if there were a section of icons devoted to education platforms. Systems like this typically track students, teachers, parents, lessons, classes/programs (i.e. Science, Music, Biology, etc...), report cards, administrative staff, etc...

**Comment by tagliala** [comment] 2017-01-05 20:05
Closing here in favor of #4079

**Closed by tagliala** 2017-01-05 20:05 UTC
Labels: waiting for feedback
