### ISSUE TITLE
Icon request: icon-logs

### ISSUE THREAD

**Issue by g3x0** [FortAwesome/Font-Awesome#5898] opened 2015-03-09 14:10 UTC
Hi,

I think many people might find useful an icon representing logs or logging pages. I was thinking of a foot (like in a footprint). I am currently using the fa-paw icon for this, but I think a footprint might work better.

Also, maybe you can add a fingerprint, too?

Thanks,

**Comment by tagliala** [comment] 2015-03-09 15:23
duplicate of #4431 , please +1 that request

closing here

**Comment by chrissharp80** [comment] 2018-02-15 12:06
It's not the same at all. https://github.com/FortAwesome/Font-Awesome/issues/4431 is about a fingerprint request and someone happened to mention that they would also like to see a logs icon, as would many people. This is a valid and totally separate issue. If you're not going to implement it then okay, but sending people to another DIFFERENT issue is just wasting their time.

**Comment by tagliala** [comment] 2018-02-15 12:17
@chrissharp80 thanks

wrong autocompletion: footprint is a duplicate of #2140

**Closed by tagliala** 2018-02-15 12:17 UTC

**Comment by chrissharp80** [comment] 2018-02-15 12:28
Now it's a foot?? This is a confusing issue. Hope you get it sorted :)

**Comment by tagliala** [comment] 2018-02-15 13:00
@chrissharp80 

quoting from the opening post (**emphasis** mine):
> I think many people might find useful an icon representing logs or logging pages. **I was thinking of a foot (like in a footprint)**. I am currently using the fa-paw icon for this, but I think a footprint might work better.

footprint is a duplicate of #2140

> Also, maybe you can add a **fingerprint**, too?

fingerprint is a duplicate of #4431 

If you have any other request or any other idea for a "logs" icon, please [open a new issue following our 
 contributing guidelines](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) 

Hope it helps

**Comment by chrissharp80** [comment] 2018-02-15 15:54
@tagliala - completely missed that. Thanks.
