### ISSUE TITLE
Icon request: icon-theatre

### ISSUE THREAD

**Issue by dheckler587** [FortAwesome/Font-Awesome#10838] opened 2017-03-23 19:04 UTC
Hello! I'm looking for something similar to below for symbolizing theatre.
![screen shot 2017-03-23 at 3 00 49 pm](https://cloud.githubusercontent.com/assets/26634066/24265445/fa13b218-0fd9-11e7-91db-b1c72c602596.jpg)

Thank you!

**Comment by tagliala** [comment] 2017-03-23 19:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1270, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-23 19:09 UTC
