### ISSUE TITLE
Icon request: Discord&bilibili

### ISSUE THREAD

**Issue by MiueAce** [FortAwesome/Font-Awesome#16253] opened 2020-02-28 22:35 UTC
提交两个图标:1.Discord 2.bilibili
这两个图标将在我的个人主页里使用

![QQ截图20200229063354](https://user-images.githubusercontent.com/44958546/75592586-9dbdc580-5abd-11ea-88de-ded1a8e1c68b.png)
![bilibili](https://user-images.githubusercontent.com/44958546/75592588-9e565c00-5abd-11ea-814c-22ef6d07e6c1.jpg)

**Comment by tagliala** [comment] 2020-02-29 08:26
Hi!

Thanks for being part of the Font Awesome Community.

Discord is already here, just make sure that you are using FA 5.0.0 or newer: https://fontawesome.com/icons/discord?style=brands

bilibili is a duplicate of #9789 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-02-29 08:26 UTC
