### ISSUE TITLE
Icon Request: fa-cigarette

### ISSUE THREAD

**Issue by umitemre** [FortAwesome/Font-Awesome#9728] opened 2016-08-09 15:04 UTC
Hello, 
As I was developing a project and I needed a cigarette icon but couldn't find any.

**Comment by tagliala** [comment] 2016-08-09 15:33
Duplicate of #726 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-09 15:33 UTC
