### ISSUE TITLE
Icon request: icon-evacuate

### ISSUE THREAD

**Issue by stirumala76** [FortAwesome/Font-Awesome#10016] opened 2016-10-04 13:27 UTC
Can you please provide icon set

Icon request: icon-evacuate
![evacuate](https://cloud.githubusercontent.com/assets/4968423/19075876/c7d5e424-8a14-11e6-82cc-3fd64c897acf.png)

Icon request: icon-evacuate-cancel
![evacuate_cancel](https://cloud.githubusercontent.com/assets/4968423/19075877/c7e028e4-8a14-11e6-915a-07969abe5d69.png)

**Comment by aethior** [comment] 2022-03-18 22:11
Duplicate of #4785.

cc/ @tagliala

**Closed** 2022-03-19 09:26 UTC
