### ISSUE TITLE
icon-request: icon-telegram

### ISSUE THREAD

**Issue by mbsmt** [FortAwesome/Font-Awesome#8957] opened 2016-04-12 10:35 UTC
Hi. As you know, Telegram is a a fast growing communication mobile app these days. But there is not any made icon in font-awesome.
Please add it to your valuable collection.

This is its icon :
https://telegram.org/img/t_logo.png

Thank you.

**Comment by PeterShaggyNoble** [comment] 2016-04-12 10:50
Dupe of [#3034](https://github.com/FortAwesome/Font-Awesome/issues/3034)

**Closed** 2016-04-12 15:55 UTC
