### ISSUE TITLE
Icon request: lung-heart

### ISSUE THREAD

**Issue by Persern** [FortAwesome/Font-Awesome#18795] opened 2022-03-08 13:43 UTC
Hi
There is couple of web-developer using your awesome icons. We deliver a integrated software to theirs platform for lung and heart examination. They need an lung icon with a small heart inside.

Regards
Hamid@spirare.com

**Comment by tagliala** [comment] 2022-03-10 16:35
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/67/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by mbomb007** [comment] 2022-03-18 14:19
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.
> 
> Demo: https://jsfiddle.net/tagliala/bfa6uhse/67/
> 
> Ref:
> 
> https://fontawesome.com/how-to-use/on-the-web/styling/power-transform 
> https://fontawesome.com/how-to-use/on-the-web/styling/masking 
> https://fontawesome.com/how-to-use/on-the-web/styling/layering

Just a note, the first "Power Transform" link just redirects to the FA versions page. (Perhaps the URL structure was changed and a redirect for this link was missed?) The link should actually be https://fontawesome.com/docs/web/style/power-transform

**Comment by tagliala** [comment] 2022-03-18 15:44
Yes thanks, I will fix those outdated links on my answer template

**Comment by aethior** [comment] 2022-03-24 22:31
Duplicate of #17462.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-25 16:46
Thanks

**Closed as completed by tagliala** 2022-03-25 16:46 UTC
Labels: new icon, medical / health (category)
