### ISSUE TITLE
Icon Request: icon-folder-move

### ISSUE THREAD

**Issue by aastrouski** [FortAwesome/Font-Awesome#14811] opened 2019-03-25 11:20 UTC
Something like this icon
- Move folder or
- Move to folder

![image](https://user-images.githubusercontent.com/576008/54915790-07763c80-4f09-11e9-9237-8ca281881d03.png)

**Comment by tagliala** [comment] 2019-03-25 12:13
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #3097, please +1 that request

Please also keep in mind that you can achieve this icon with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/33/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Closed by tagliala** 2019-03-25 12:13 UTC

**Comment by aastrouski** [comment] 2019-03-25 12:18
Thanks!
