### ISSUE TITLE
Icon Request: fa-october-cms

### ISSUE THREAD

**Issue by LaravelNick** [FortAwesome/Font-Awesome#9537] opened 2016-07-08 10:23 UTC
An icon for the October CMS platform - https://octobercms.com

**Comment by tagliala** [comment] 2016-07-08 10:40
Duplicate of #7102, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-08 10:40 UTC
