### ISSUE TITLE
Change request: improve fa-sun-o icon

### ISSUE THREAD

**Issue by lvv83** [FortAwesome/Font-Awesome#9321] opened 2016-06-02 11:40 UTC
Please, add icon for **sun** with filling [example](http://www.flaticon.com/free-icon/sun_66275)

Also, I think that **fa-sun-o** may be improved like [this](http://www.flaticon.com/free-icon/sun-sunny-day-weather-symbol_53565).

**Comment by tagliala** [comment] 2016-06-02 12:09
Duplicate of #5700, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Leaving this open as `Change request: improve fa-sun-o icon`

**Comment by tagliala** [comment] 2019-07-04 21:20
Sun has been improved in FA5: https://fontawesome.com/icons/sun?style=regular

If this still doesn't fit your needs, feel free to open a new request for `fa-sun-alt`

**Closed by tagliala** 2019-07-04 21:20 UTC
Labels: enhancement, web application icons
