### ISSUE TITLE
Book Shelf / Library

### ISSUE THREAD

**Issue by effipub** [FortAwesome/Font-Awesome#13244] opened 2018-05-31 15:55 UTC
We need quite often a simple set of books like in a book shelf as a symbol for a (personal) library. Since this is even part of the button set of the FireFox, it might be interesting for a larger user group.
[linde_books.pdf](https://github.com/FortAwesome/Font-Awesome/files/2058966/linde_books.pdf)

**Comment by tagliala** [comment] 2018-05-31 18:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5098, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-31 18:30 UTC
