### ISSUE TITLE
Icon request: equal sign

### ISSUE THREAD

**Issue by eg45** [FortAwesome/Font-Awesome#9270] opened 2016-05-24 11:10 UTC
Hey,
please add the equal sign to the font awesome library.
Thanks :)

**Comment by tagliala** [comment] 2016-05-24 11:31
Duplicate of #1133, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Please note that you can use the standard unicode point:

```css
.fa-equal:before {
  content: "=";
}
```

Closing here

**Closed by tagliala** 2016-05-24 11:31 UTC
