### ISSUE TITLE
Icon Request: female-wedding-dress

### ISSUE THREAD

**Issue by levarberry** [FortAwesome/Font-Awesome#17112] opened 2020-09-02 20:13 UTC
**What can it be used for?**
To show a female in a Wedding Dress.  This can used an any app that is related to the wedding industry or fashion.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/390791/92031695-04ef5780-ed37-11ea-9d84-38b12605b56a.png)

**Comment by aethior** [comment] 2022-03-12 17:36
~~Duplicate of #3852.~~

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-12 17:52
Reopening as female-wedding-dress

**Comment by sensibleworld** [comment] 2024-07-11 16:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/3852)

**Closed by sensibleworld** 2024-07-11 16:33 UTC
Labels: new icon, clothing-fashion (category), Duplicate
