### ISSUE TITLE
Icon request: fa-python

### ISSUE THREAD

**Issue by andela-bojengwa** [FortAwesome/Font-Awesome#6693] opened 2015-06-09 13:20 UTC
We are looking for an icon of the various programming languages. As programmers, we always work with different languages or might need to sort projects according to language, etc. I think having an icon that represents that will be an awesome idea. Here is one idea for the icon:

![Python Icon Black] (https://cdn4.iconfinder.com/data/icons/scripting-and-programming-languages/512/Python_logo-256.png)

or 

![Python Icon Black] (http://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/2000px-Python-logo-notext.svg.png)

It will be great if we can provide an icon for this as well as for other major programming languages.

Thanks!
:)

**Comment by ShamanFromSiberia** [comment] 2015-07-01 07:52
+1

**Comment by tagliala** [comment] 2015-07-01 10:26
duplicate of #3016, please +1 that request

please also consider mfizz for technology icons: http://fizzed.com/oss/font-mfizz

**Closed by tagliala** 2015-07-01 10:26 UTC
