### ISSUE TITLE
Icon request: Leetcode

### ISSUE THREAD

**Issue by jorjishasan** [FortAwesome/Font-Awesome#18643] opened 2022-02-04 12:45 UTC
**What can it be used for?**
This is the high time of having competitive programming skills. Leetcode is top of the mark in competitive programming and interview prep Platforms. You people doing great for making ease of using your's asset. So, why not leetcode? I can't wait to see the leetcode icon in font-awesome.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/63964149/152531278-5e01909d-0c2e-412a-8acc-4a06863c244d.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2022-02-04 12:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15337, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-02-04 12:50 UTC
