### ISSUE TITLE
could you add an icon for 'picasa'

### ISSUE THREAD

**Issue by 12d** [FortAwesome/Font-Awesome#9848] opened 2016-09-01 09:22 UTC
Could you add an icon for 'picasa', or logo for 'wechat timeline'

**Comment by tagliala** [comment] 2016-09-01 10:58
Duplicate of #1772 and #9835 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-01 10:58 UTC
