### ISSUE TITLE
Icon request: Scoop,it website icon

### ISSUE THREAD

**Issue by CelebxxCom** [FortAwesome/Font-Awesome#16018] opened 2020-01-05 14:53 UTC
I need to scoop.it website icon

**Comment by tagliala** [comment] 2020-01-05 15:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of and #1603, please add a 👍 reaction to that request.

@CelebxxCom since you have already open #16016, I think you may be also interested in how requests work. Please take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs)

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-05 15:01 UTC
