### ISSUE TITLE
Icon Request: fa-chest

### ISSUE THREAD

**Issue by 1mRAAAH** [FortAwesome/Font-Awesome#9388] opened 2016-06-11 08:43 UTC
In order to expand our website (regarding a Minecraft server) I'd like to use a few minecraft related fa-icons. 
These icons are most-likely going to be used by more websites that are subject to a minecraft server.
Examples:
fa-chest
fa-steve
fa-creeper

see http://i.imgur.com/YYW29nG.png

More options could be fa-sword, fa-pickaxe, fa-diamond etc.
Thanks.

**Comment by tagliala** [comment] 2016-06-11 09:24
Hi,

please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
Please search to see if your icon request already exists. If a request is found, please add a :+1: reaction to that one.
Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
Attach a single color image or two that represent the idea you're going for.
Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

if chest is a synonym of box, then this is a duplicate of #908, please add a :+1: reaction to that request, otherwise feel free to comment

Closing here

**Closed by tagliala** 2016-06-11 09:24 UTC
