### ISSUE TITLE
Icon Request: fa-medal

### ISSUE THREAD

**Issue by ezpabon** [FortAwesome/Font-Awesome#8346] opened 2016-01-15 10:29 UTC
I would suggest an icon that represents a medal

**Comment by aethior** [comment] 2016-01-15 10:40
Hi @ezpabon,

This suggestion is duplicate of #1898. Please +1 that.

Regards.

**Comment by tagliala** [comment] 2016-01-15 10:40
duplicate of #1898, please +1 that request

closing here

**Closed** 2016-01-15 10:40 UTC
