### ISSUE TITLE
Icon request: 360 view / panoramic view

### ISSUE THREAD

**Issue by NickNZ01** [FortAwesome/Font-Awesome#5820] opened 2015-03-01 03:18 UTC
Looking for a 360 view / panoramic view icon. Has been by requested her before by someone, unfortuante after the one post its gone cold. Someone wants to help me out? 

I have attached two excamples, the 360 view excample is my preferred one as it includes 'view'...

![360 view](https://cloud.githubusercontent.com/assets/7350375/6429311/12459b74-c02e-11e4-9b47-2fc0f23ea9ce.jpg)
![360 icon](https://cloud.githubusercontent.com/assets/7350375/6429312/13bb0994-c02e-11e4-93da-862e8c8d4cd5.jpg)

**Comment by LauritzT** [comment] 2015-03-04 09:09
```fa-street-view``` is a pretty good alternative.

**Comment by Souldat** [comment] 2015-10-07 01:46
+1

**Comment by web-style** [comment] 2015-11-10 08:34
+1

**Comment by togis** [comment] 2016-07-27 08:43
+1

**Comment by XmlmXmlmX** [comment] 2016-09-29 12:05
+1

**Comment by ccharlton** [comment] 2016-10-07 22:39
+1

**Comment by UXDesignerNL** [comment] 2017-01-31 13:35
+1

But without the 360º text in it

**Comment by Krxon** [comment] 2017-10-11 20:14
+1

**Comment by gmtju52** [comment] 2017-10-14 09:52
360 view is different to a panorama view
i like to have any like this:
https://goo.gl/images/hpaCgi
or try https://www.google.de/search?q=panorama+icon

**Comment by weinde** [comment] 2018-02-26 08:10
So still no 360° icon... this is just sad FA team... :(

**Comment by majestica** [comment] 2018-06-01 11:53
+

**Comment by Krxon** [comment] 2018-06-01 12:27
+100

**Comment by ChriStef** [comment] 2018-07-14 12:36
So to be clear on this does it plain to do it?

**Comment by XmlmXmlmX** [comment] 2018-07-16 12:41
> opened this issue on 1 Mar 2015

🤣

**Comment by tagliala** [comment] 2018-08-09 07:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #772, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-09 07:29 UTC
Labels: new icon, web application icons

**Comment by elimartin** [comment] 2018-08-28 12:36
+1
