### ISSUE TITLE
Signature icon is missing

### ISSUE THREAD

**Issue by ajstharsan-radus28** [FortAwesome/Font-Awesome#12069] opened 2018-01-10 12:15 UTC
Need an icon for signing or signature something like [this](https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn3.iconfinder.com%2Fdata%2Ficons%2Fbusiness-world-extras%2F512%2FPen_Signature-512.png&f=1)

**Comment by tagliala** [comment] 2018-01-10 12:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5663 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-10 12:42 UTC
