### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by essiele** [FortAwesome/Font-Awesome#2832] opened 2014-02-03 17:28 UTC
I would like to request the inclusion of an icon for Disqus. I would use it just like the other social icons - to link to my profile.

Disqus is widely used and I think it would be a great addition.

Regards,

Ess

**Comment by LauritzT** [comment] 2015-02-18 09:00
#2690

**Comment by tagliala** [comment] 2015-02-22 00:28
duplicate of #2690, please +1 that request

closing here

**Closed by tagliala** 2015-02-22 00:28 UTC
