### ISSUE TITLE
Icon request: fa-stitcher

### ISSUE THREAD

**Issue by killinski** [FortAwesome/Font-Awesome#9873] opened 2016-09-06 18:00 UTC
Hey guys,

After working on a recent podcast site, I realised there is no font icon for Stitcher, a commonly used podcast subscription service, where others like Apple, Soundcloud and Spotify exist. I think it would be a pretty neat addition to rounding out this aspect of the collection, to save using logo images and having to process them to all seem alike.

Just a wee idea.

Thanks!

**Comment by tagliala** [comment] 2016-09-06 18:00
Duplicate of #3403, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-06 18:00 UTC

**Comment by killinski** [comment] 2016-09-06 21:00
Sorry about that.
