### ISSUE TITLE
Icon Request: fa-New

### ISSUE THREAD

**Issue by mgee16** [FortAwesome/Font-Awesome#9615] opened 2016-07-21 22:07 UTC
An icon to draw attention to a newly posted item would be great.
Several varieties would be great also such as a Star with "New" inside etc.
I LOVE your icons.
Great Work!

**Comment by aethior** [comment] 2016-07-22 04:04
Hi @mgee16,

Remember that Font Awesome is an international project. The icons with words in any language break this condition.

**Comment by Roumed** [comment] 2016-07-22 07:32
+1

**Comment by tagliala** [comment] 2016-07-22 09:28
very same duplicate of #1331.

You can +1 that request, but @aethior is right, new is not an icon and it is not international

**Closed by tagliala** 2016-07-22 09:28 UTC

**Comment by mgee16** [comment] 2016-07-22 17:17
How about a placeholder for text inside the icon? Michael Gee18658 N. Rincon Ct.Surprise, Az. 85387

**Comment by aethior** [comment] 2016-07-22 17:46
Check: http://codepen.io/aethior/pen/XKqAdE

Related: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

**Comment by mgee16** [comment] 2016-07-22 18:00
Aethior:
This is exactly what I needed.Not sure how to resize the icon to be a little smaller though.Thanks a million!
 Michael Gee

**Comment by aethior** [comment] 2016-07-22 21:30
I just updated the file for do a little smaller (http://codepen.io/aethior/pen/XKqAdE). You can play with `fa-stack-2x` (3x, 2x, 1x...) and `font-size` attributes for ajust the size.

**Comment by mgee16** [comment] 2016-07-23 06:05
Wow, that is perfect!Thanks for your help with this. :) Michael Gee
