### ISSUE TITLE
Youpic icon missing

### ISSUE THREAD

**Issue by antra0497** [FortAwesome/Font-Awesome#12478] opened 2018-02-28 07:48 UTC
Youpic is a platfom for photographers ,  Its icon is missing the database

Link to the platform:
[https://youpic.com/](url)

This is what its icon look like:
[https://play.google.com/store/apps/details?id=com.youpic.youpicandroid](url)

**Comment by tagliala** [comment] 2018-02-28 12:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8056, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-28 12:10 UTC
