### ISSUE TITLE
email/search box combo request

### ISSUE THREAD

**Issue by kristopolous** [FortAwesome/Font-Awesome#8457] opened 2016-01-29 22:47 UTC
Hi

This is a rather silly request, but it would be awesome.

So my user experience is I go to https://fortawesome.github.io/Font-Awesome/ and then look for an icon I want. I see an input box, in the middle of the page, and think "ah that's the search".

Of course it's not, it's the email sign up.

Here's the request.

If someone types in a patently invalid email, say something that is a dictionary word or a phrase with spaces, no dots and no at sign, then just interpret it as a search and send them off to the search page on the assumption that they were not even *attempting* to enter an email address in, and instead thought it was the search box.

Furthermore, don't *tell* anyone about this double feature on the page (as it would be confusing to describe). Instead, leave the page identical in copy and look.  

Just if someone does the UX error that I want to do every time, accommodate what they obviously want to do by sending them off to the search page - perhaps even with a drop down toolbar at the top to say "hey, we have an email list, would you like to sign up for it" ... because they clearly didn't understand what they were doing with that first box.

That would be lovely.  I can even write the code for you if you want.

**Comment by tagliala** [comment] 2016-01-29 23:21
Duplicate of #7777, please share there your thoughts

This decision is up to dave, I'm also experiencing the same issue

**Closed by tagliala** 2016-01-29 23:21 UTC
