### ISSUE TITLE
Icon Request Running

### ISSUE THREAD

**Issue by jeremybritton** [FortAwesome/Font-Awesome#12794] opened 2018-04-06 13:27 UTC
A person runing

**Comment by tagliala** [comment] 2018-04-06 13:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1156 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 13:28 UTC
