### ISSUE TITLE
Icon Request: fa-trashopen-o

### ISSUE THREAD

**Issue by uxitten** [FortAwesome/Font-Awesome#7818] opened 2015-11-05 07:18 UTC
hi i Behnam Mohammadi a ux/ui designer
i change fa-tarsh-o with Adobe illustrator to trashopen concept
if this icon is apporve, please add to fontawesome

![trashopen-o](https://cloud.githubusercontent.com/assets/1549069/10962095/4336e8a0-838d-11e5-988d-1b5af1939806.png)

**Comment by mdolberg** [comment] 2015-11-05 10:03
nice work and nice idea

**Comment by tagliala** [comment] 2015-11-14 11:16
duplicate of #1245, please +1 that request

closing here

**Closed by tagliala** 2015-11-14 11:16 UTC
