### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by travisthieme** [FortAwesome/Font-Awesome#18736] opened 2022-02-22 05:42 UTC
Can we get a Google Scholar Icon?

**Comment by tagliala** [comment] 2022-02-22 20:24
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #541, feel free to +1 that request, but the problem is that

1. We do not have an official, single color icon for google-scholar
2. The favicon doesn't look good in single color

**Closed as completed by tagliala** 2022-02-22 20:24 UTC
