### ISSUE TITLE
Icon request: network-graph

### ISSUE THREAD

**Issue by peterclemenko** [FortAwesome/Font-Awesome#15519] opened 2019-09-11 23:50 UTC
**What can it be used for?**
Network graphs and force directed graphs. This is a single icon.

**Comment by tagliala** [comment] 2019-09-12 07:07
Hi!

Thanks for being part of the Font Awesome Community.

Do you have any single color, small icon size suitable example?

**Comment by aethior** [comment] 2022-04-18 22:02
Duplicate of #5944.
Check https://fontawesome.com/icons/chart-network

Regards.

cc/ @tagliala

**Closed** 2022-04-19 11:12 UTC
Labels: waiting for feedback
