### ISSUE TITLE
Icon Request: fa-virtual-assistance

### ISSUE THREAD

**Issue by fahim159** [FortAwesome/Font-Awesome#11850] opened 2017-12-06 18:44 UTC
Hi Community,

This is to request to issue following icon for web applications

![fa-virtual-assistance](https://user-images.githubusercontent.com/34315455/33679039-d00295a0-dae7-11e7-88c0-efd9f3e8be17.png)

**Comment by tagliala** [comment] 2017-12-06 19:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5586 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-12-06 19:42 UTC
