### ISSUE TITLE
Icon request: leetcode

### ISSUE THREAD

**Issue by Pikanshi** [FortAwesome/Font-Awesome#20334] opened 2024-08-16 22:15 UTC
Leetcode is a world top online platform for coding interview preparation. Many people wants to add their details to their portfolio/resume. It would be really great to have an icon for the same which will give many people the option to add their profile on their CV/Resume through this icon.

**Comment by tagliala** [comment] 2024-08-17 05:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15337, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-08-17 05:57 UTC
