### ISSUE TITLE
Icon request: fa-cookie / fa-cookie-o

### ISSUE THREAD

**Issue by cryocreations** [FortAwesome/Font-Awesome#11149] opened 2017-06-09 01:42 UTC
Useful for food and browser cookies.

**Comment by tagliala** [comment] 2017-06-09 08:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8158 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-09 08:29 UTC
