### ISSUE TITLE
icon request: flow

### ISSUE THREAD

**Issue by typehorror** [FortAwesome/Font-Awesome#18497] opened 2021-12-08 19:47 UTC
**What can it be used for?**
This can be used in a representation of flow movement (like workflows). It describe moving forward, backward, move past an step forward and back

- `flow-next` or `flow-move` 
- `flow-previous` (could also be `flow-move`  + `rotate-180`)
- `flow-jump-next` or `flow-jump`
- `flow-jump-previous` (could also be `flow-jump` + `flip-h`)

**Example image (optional)**

![flow-icons](https://user-images.githubusercontent.com/56964/145274840-f0f0c007-b5d4-45d1-be00-7c6622fa3d12.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment] 2024-07-11 15:22
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/5673)

**Closed** 2024-07-19 09:10 UTC
Labels: new icon, Duplicate
