### ISSUE TITLE
Icon Request: fa-handshake

### ISSUE THREAD

**Issue by guybanister** [FortAwesome/Font-Awesome#5480] opened 2015-01-26 15:24 UTC
To be used on a website for a services company to symbolise agreement / reliability.

![handshake](https://cloud.githubusercontent.com/assets/9447075/5902071/569221a0-a56f-11e4-9ab4-8ad96afeab89.png)
![handshake_icon](https://cloud.githubusercontent.com/assets/9447075/5902072/583d1e1a-a56f-11e4-8fd6-0ba096282613.jpg)

**Comment by tagliala** [comment] 2015-01-26 20:22
duplicate of #878 , please +1 that request and post there your examples

closing here

**Closed by tagliala** 2015-01-26 20:22 UTC
