### ISSUE TITLE
Icon Request: fa-tools

### ISSUE THREAD

**Issue by rickszyr** [FortAwesome/Font-Awesome#11173] opened 2017-06-14 14:53 UTC
First, thanks for the **awesome** work that you do. And thank you for allowing people to use these icons for free.

I imagine it as a screwdriver and a wrench in a cross

Something like the following:

![image](https://user-images.githubusercontent.com/10763102/27139021-48d2738a-50f8-11e7-86ad-ef2cfeb8c6d3.png)

Use cases are for Tools menus

**Comment by tagliala** [comment] 2017-06-14 15:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #736 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-14 15:00 UTC
