### ISSUE TITLE
Icon Request: fa-strava

### ISSUE THREAD

**Issue by larrivee013** [FortAwesome/Font-Awesome#9616] opened 2016-07-21 22:35 UTC
Hi, it'd be awesome if you guys could add [Strava](https://www.strava.com/) to your list of icons for all the cycling / running / swimming lovers that use FA.

Thanks!

**Comment by aethior** [comment] 2016-07-22 03:54
Duplicate of #3313. Please :+1: that.

**Closed** 2016-07-22 09:29 UTC
