### ISSUE TITLE
Icon Request: fa-scoopit

### ISSUE THREAD

**Issue by Synnexus** [FortAwesome/Font-Awesome#11807] opened 2017-11-28 01:26 UTC
Would be great if you'd add an icon for Scoop.it!
Something like this:
![image](https://user-images.githubusercontent.com/34047274/33297784-3f069de0-d3e3-11e7-935a-c09e898dd206.png)
I would use it add it as a social icon to my website to link to my curated content on scoop.it.
Thanks for all the awesome fonts & work!

**Comment by PeterShaggyNoble** [comment] 2017-11-28 09:35
Duplicate of #1603.

**Closed** 2017-11-28 10:34 UTC
