### ISSUE TITLE
Icon request: car-engine

### ISSUE THREAD

**Issue by abdullahhafizh** [FortAwesome/Font-Awesome#14147] opened 2018-10-21 12:51 UTC
### What can it be used for?

to show engine power of car

### Icon request checklist

- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-10-21 15:01
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #4175?

**Comment by tagliala** [comment] 2019-05-16 07:23
No feedback, closing here

**Closed by tagliala** 2019-05-16 07:23 UTC
Labels: waiting for feedback
