### ISSUE TITLE
Icon request: fa-handbag

### ISSUE THREAD

**Issue by DSwissK** [FortAwesome/Font-Awesome#14446] opened 2018-12-26 16:08 UTC
handbag icon

Thanks :)

**Comment by Crissov** [comment] 2018-12-29 14:09
Related Unicode emoji #222:

- [👜](https://emojipedia.org/handbag/) U+1F45C HANDBAG

**Comment by aethior** [comment] 2022-04-16 08:59
@tagliala `clothing-fashion (category)` label for this request?

**Comment by sensibleworld** [comment] 2024-07-11 19:08
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7176)

**Closed by sensibleworld** 2024-07-11 19:08 UTC
Labels: new icon, clothing-fashion (category), Duplicate
