### ISSUE TITLE
Burger menu button on the font awesome website is not working on Firefox/Chrome

### ISSUE THREAD

**Issue by SamStonehouse** [FortAwesome/Font-Awesome#14661] opened 2019-02-20 12:23 UTC
### Describe the problem

Burger Menu button on the font awesome website is not working on Firefox/Chrome (https://fontawesome.com)

### What version and implementation are you using?

Browser and version: Latest versions of both browsers

Apologies if this isn't the right place for this issue, as it's regarding the website and not font awesome itself.

**Comment by tagliala** [comment] 2019-02-21 09:13
Hi!

Thanks for this bug report, I can confirm and it is the right place.

Let's assign both @robmadole and @talbs

**Comment by talbs** [comment] 2019-03-06 15:06
Hi, there.

Apologies for the delay and thanks for bringing this to our attention, @SamStonehouse. I just checked our site's main navigation menu toggle (in smaller viewports) and all seems to be working as intended (I can click/select the menu icon and then have the site nav display) in Firefox and Chrome. 

Would you mind checking this again and letting me know if you're still having the error? If its still sticking around, we'll get it fixed in a jiffy.

**Comment by tagliala** [comment] 2019-03-06 15:10
Works for mee too 🤔

**Comment by SamStonehouse** [comment] 2019-03-06 15:28
Seems to be working fine for me now too

**Comment by talbs** [comment] 2019-03-06 17:41
Thanks for double-checking, gang. I'll close this issue now that things seem to be working as intended. Let us know if that hamburger menu loses a bun or gets moldy in the future. 😄

**Closed by talbs** 2019-03-06 17:41 UTC
Labels: bug, doc, fontawesome.com, in progress
