### ISSUE TITLE
Icon Request: fa-outlook

### ISSUE THREAD

**Issue by SashaRudolf** [FortAwesome/Font-Awesome#9247] opened 2016-05-21 00:36 UTC
The outlook icon.

**Comment by ADoebeling** [comment] 2016-06-05 22:41
Are you sure that non of these meets your requirements?

![image](https://cloud.githubusercontent.com/assets/10674780/15808718/3ae266f8-2b7f-11e6-840a-5fdd3fd16c61.png)

If not we probably need icons for

* Outlook
* Thunderbird
* Mac Mail

**Comment by tagliala** [comment] 2016-06-06 08:56
I'm going to consider this a duplicate of #2884, please add a 👍  reaction to that request

Closing here

**Closed by tagliala** 2016-06-06 08:56 UTC
