### ISSUE TITLE
Brand Youtube redesign - Icon request: fa-youtube-*

### ISSUE THREAD

**Issue by danieluyo** [FortAwesome/Font-Awesome#11459] opened 2017-08-29 22:44 UTC
Today Youtube announces a new brand logo; I think the fa-yotube-* should be released too.

Reference:
- https://youtube.googleblog.com/2017/08/a-new-youtube-look-that-works-for-you.html
- https://www.youtube.com/yt/about/brand-resources

**Comment by tagliala** [comment] 2017-08-30 07:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11457 

This issue will be addressed in the upcoming 5.0 release

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-30 07:34 UTC
