### ISSUE TITLE
Icon request: icon-autorickshaw

### ISSUE THREAD

**Issue by eldhoshaji** [FortAwesome/Font-Awesome#16710] opened 2020-05-23 19:45 UTC
**What can it be used for?**
It can be used to represent 3 wheeler icons. Among the vehicle icons, there is no icon to represent a three-wheeler.

**Example image (optional)**
![sample](https://user-images.githubusercontent.com/14539774/82739259-d804cf00-9d5b-11ea-98c1-ff65953e754b.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`) - Single Icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-23 19:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14928, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-23 19:48 UTC
