### ISSUE TITLE
Icon Request: fa-package

### ISSUE THREAD

**Issue by mdolberg** [FortAwesome/Font-Awesome#7828] opened 2015-11-05 12:40 UTC
I'd like to see a font of a package, just like the dropbox one (only their icon is registered...) or some box with a stamp on it or something.

Could be useful for transport or shipping pages I have

![472361015](https://cloud.githubusercontent.com/assets/11992836/10968600/10e15f50-83cb-11e5-8854-25710a2f4106.jpg)

![box](https://cloud.githubusercontent.com/assets/11992836/10968683/82fe557a-83cb-11e5-934d-e8540e69c145.JPG)

**Comment by JordanReiter** [comment] 2015-11-05 18:00
Would fa-cube work?
http://fontawesome.io/icon/cube/

**Comment by mdolberg** [comment] 2015-11-06 10:40
Hello. Thanks for you reply.
No, a cube doesn't naturally mean a package

**Comment by Rodrigo54** [comment] 2015-11-06 16:42
-1

**Comment by tagliala** [comment] 2015-11-14 00:18
Duplicate of #908 , please +1 that request

closing here

**Closed by tagliala** 2015-11-14 00:18 UTC
