### ISSUE TITLE
Icon request: fa-scatterplot

### ISSUE THREAD

**Issue by andreaphsz** [FortAwesome/Font-Awesome#10694] opened 2017-02-21 15:32 UTC
Would be nice to have an icon for a (2d) [Scatter_plot](https://en.wikipedia.org/wiki/Scatter_plot).

**Comment by aethior** [comment] 2022-03-09 02:16
Hi @andreaphsz,

This icon was added in v5.7.0.
Check https://fontawesome.com/icons/chart-scatter

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-09 16:27
Duplicate of #4240

**Closed by tagliala** 2022-03-09 16:27 UTC
