### ISSUE TITLE
Icon request: Box

### ISSUE THREAD

**Issue by jalechowicz** [FortAwesome/Font-Awesome#19109] opened 2022-06-08 16:56 UTC
Hi - our organization using Box.com for file sharing and storage. We would love a specific icon to use.

**Comment by tagliala** [comment] 2022-06-08 18:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1745, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-06-08 18:08 UTC
