### ISSUE TITLE
Icon Request: fa-the-knot

### ISSUE THREAD

**Issue by kjanko89** [FortAwesome/Font-Awesome#11750] opened 2017-11-13 16:20 UTC
social media icon for the knot

![tk-favicon-300x300](https://user-images.githubusercontent.com/33093898/32736069-2f074684-c85c-11e7-9d25-83c6a2c72ab1.png)

**Comment by tagliala** [comment] 2017-11-13 16:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5957, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-13 16:56 UTC
