### ISSUE TITLE
Icon Request: fa-microscope

### ISSUE THREAD

**Issue by Maui21** [FortAwesome/Font-Awesome#10270] opened 2016-11-23 00:17 UTC
Use cases: Icon for a "view data" button or an "analyze results" button.

![microscope icon](https://cloud.githubusercontent.com/assets/21348088/20547135/1f1a49ec-b0e8-11e6-8bfe-a809fc4d78c3.png)

Thanks so much!

**Comment by tagliala** [comment] 2016-11-23 09:08
Duplicate of #515, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-23 09:08 UTC
