### ISSUE TITLE
Icon request: fa-stitcher

### ISSUE THREAD

**Issue by MikeWriting** [FortAwesome/Font-Awesome#13511] opened 2018-07-09 18:21 UTC
### What can it be used for?

Stitcher Radio hosts radio shows and podcasts. Show creators and podcasters could use a Stitcher brand icon on their websites and in email newsletters. Ref: https://www.stitcher.com/. Similar to Spotify

### Example image (optional)

![stitcher-logo](https://user-images.githubusercontent.com/38844304/42468544-346a3608-8383-11e8-99dc-e8a16ce7b5f9.jpeg)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-09 21:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3403, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-09 21:13 UTC
