### ISSUE TITLE
smoking icons

### ISSUE THREAD

**Issue by monxas** [FortAwesome/Font-Awesome#12187] opened 2018-01-30 11:21 UTC
I'm surprised there's no smoking icon. Also a no-smoking, but that can be done combining icons, so no big deal.

**Comment by tagliala** [comment] 2018-01-30 16:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #726 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-30 16:36 UTC

**Comment by monxas** [comment] 2018-01-30 16:38
That’s a 5 year old issue...

**Comment by tagliala** [comment] 2018-01-30 16:50
@monxas 

I need that icon too, as you can see the first comment there is my upvote (first comment)

If you need this icon in a short while, please consider a custom version of Font Awesome, as I did: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
