### ISSUE TITLE
Icon request: ResearchGate

### ISSUE THREAD

**Issue by catarinavp** [FortAwesome/Font-Awesome#8907] opened 2016-04-07 02:27 UTC
Hi,

I would love to have the icon of ResearchGate (https://www.researchgate.net) in your awesome font! They have a fairly plain logo that fits the style of your font.

Thanks heaps!

**Comment by tagliala** [comment] 2016-04-07 11:10
Duplicate of #3634 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-07 11:10 UTC
