### ISSUE TITLE
Font-Awesome Kakaotalk please... 

### ISSUE THREAD

**Issue by Jerfri6** [FortAwesome/Font-Awesome#10856] opened 2017-03-29 03:31 UTC
dave, please help me to make the font "**fa fa-kakaotalk**"

**Comment by tagliala** [comment] 2017-03-29 08:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3688 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-29 08:55 UTC
