### ISSUE TITLE
Icon Request: fa-speech

### ISSUE THREAD

**Issue by alvordr** [FortAwesome/Font-Awesome#5956] opened 2015-03-13 16:58 UTC
I noticed there isn't really a speech icon. There's a mega-phone, a group icon, a two-way arrow, but none really say speech.  I work as a web designer and IT support specialist for a non-profit health care organization, at which we have some counselors that speak multiple languages.  Having an icon that looks like a person's head (mouth) with audible signs emitting from the mouth would be helpful.

An example of what I'm talking about is this draft I created:

http://screenpresso.com/=xQWIg

**Comment by dngunraj** [comment] 2015-03-26 20:27
+1

**Comment by gestudio** [comment] 2015-11-04 18:57
+1

**Comment by tagliala** [comment] 2015-11-04 22:36
Duplicate of #2096, please +1 that request

if you find an open duplicate, please mention me

closing here

**Closed by tagliala** 2015-11-04 22:36 UTC
Labels: waiting for feedback
