### ISSUE TITLE
Mental Health Icon

### ISSUE THREAD

**Issue by brynhowlett** [FortAwesome/Font-Awesome#12301] opened 2018-02-09 07:40 UTC
http://serviciosdelaraza.org/wp-content/uploads/2016/01/Mental-Health-Icon-e1452576482162.png

**Comment by tagliala** [comment] 2018-02-09 10:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8443, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-09 10:42 UTC
