### ISSUE TITLE
Icon Request: fa-chair

### ISSUE THREAD

**Issue by Jidulal** [FortAwesome/Font-Awesome#9432] opened 2016-06-21 07:47 UTC
Hi Team,

Here I request you to create new icon for chair. I hope you will reply to my request

**Comment by tagliala** [comment] 2016-06-21 08:15
Duplicate of #1998 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-21 08:15 UTC
