### ISSUE TITLE
Icons produce weird transparent left overlay when touched on (some) android devices (native browser)

### ISSUE THREAD

**Issue by BraveKenny** [FortAwesome/Font-Awesome#5796] opened 2015-02-26 20:57 UTC
When running [this jsfiddle](http://jsfiddle.net/1bjbyqxb/30/) on your android phone's native browser, and touching around the produced icons at the bottom right, you may get this bug:

![screenshot from 2015-02-26 21 55 22](https://cloud.githubusercontent.com/assets/3440721/6401655/31aefdee-be02-11e4-8d42-d2249fe383db.png)

It only happens on some android phones, with their native browser. (no problem on chrome) So far I have confirmed it happening on LG G2, and Galaxy Note 2. The issue does not appear on Sony Xperia Z, Galaxy Edge, or Google Nexus.

I tried different values for `font-size`, and the bug seems to start appearing at any value that amounts to 23px font size. (x-large, 1.5em...) Under this size, I have not been able to produce that bug.

It actually happens on the front page of Font-Awesome (right part of the flag cut off):

![screenshot from 2015-02-26 22 36 24](https://cloud.githubusercontent.com/assets/3440721/6402448/fc89cd82-be07-11e4-9e02-f4bea9c90c82.png)

**Comment by tagliala** [comment] 2015-02-26 22:46
thanks for reporting this

this is a duplicate of a known issue and it does not depend on fontawesome.

You can reproduce this with a standard font.

Please take a look at #3209 

closing here

**Closed by tagliala** 2015-02-26 22:46 UTC
