### ISSUE TITLE
icon-request : fa-(tv classifications)

### ISSUE THREAD

**Issue by Kikidy-cam** [FortAwesome/Font-Awesome#10256] opened 2016-11-21 15:18 UTC
Requesting an icon for each of the American and Australian TV classifications.
I would use the icon as a identifier of such, both in a table and in the upper right corner of a information box. The icon only needs to have the letters for its respective classification in a dark rectangle, like git-square or cc-visa.
American: TV-Y, TV-Y7, TV-G, TV-PG, TV-14, TV-MA
Australian: G, PG, M, MA 15+, R 18+, X 18+
P.S. please ensure all icons boxes are the same width.

**Comment by tagliala** [comment] 2016-11-21 15:32
Duplicate of #6951, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-21 15:32 UTC

**Comment by Kikidy-cam** [comment] 2016-11-22 03:33
This is not a duplicate, as #6951 is only asking for American tv classifications, whereas I am asking for American and Australian classifications.
