### ISSUE TITLE
Icon request: icon-calligraphy

### ISSUE THREAD

**Issue by pixelnourish** [FortAwesome/Font-Awesome#13024] opened 2018-05-03 16:42 UTC
Detonating separate sections of a crafter's website/shop, used for navigation purposes, show graphically that a worksheet is for download/purchase and is for practising calligraphy

![image](https://user-images.githubusercontent.com/182633/39590526-03033cb0-4eb6-11e8-9863-7ebea0c52313.png)

The only thing I could think of is a hand holding a pen. Either a brush pen or an oblique pen with a nib.

**Comment by tagliala** [comment] 2018-05-03 19:11
Hi!

Thanks for being part of the Font Awesome Community.

I'm likely to consider this a duplicate of #5663 

I would like to see a single color, 16px size suitable example

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by pixelnourish** [comment] 2018-05-07 19:33
I guess it could be - I personally would be hoping for something that clearly identifies it's hand lettering (which is more than just writing).

A traditional nib is probably the ideal way to go. Things like this? 

![image](https://user-images.githubusercontent.com/182633/39720949-c1e590a8-51f2-11e8-82a9-beecef9e00d4.png)
![image](https://user-images.githubusercontent.com/182633/39720952-c9d13e48-51f2-11e8-9a42-4cd43dd57a53.png)
![image](https://user-images.githubusercontent.com/182633/39720960-cea8a9a6-51f2-11e8-9cd3-0aed26cc0fd4.png)

**Comment by sensibleworld** [comment] 2024-07-15 15:12
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-15 15:12 UTC
Labels: waiting for feedback
