### ISSUE TITLE
Icon Request: fa-align-top, fa-align-bottom, fa-align-middle

### ISSUE THREAD

**Issue by djvergel** [FortAwesome/Font-Awesome#11408] opened 2017-08-15 14:49 UTC
These would be similar to the existing icons for [align-center](http://fontawesome.io/icon/align-center), [align-left](http://fontawesome.io/icon/align-left) and [align-right](http://fontawesome.io/icon/align-right). In fact, they could be made by simply rotating those icons 90°.

**Comment by tagliala** [comment] 2017-08-15 15:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2772, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-15 15:29 UTC
