### ISSUE TITLE
Icon Request: fa-LINE

### ISSUE THREAD

**Issue by JohnFrank** [FortAwesome/Font-Awesome#5745] opened 2015-02-22 03:06 UTC
Line is an app like Skype in heavy use in Asia...Japan in particular. I see you already have icons for Skype and Facebook...this one useful in Asia
already available but using font awesome on my website 
see link below
http://theorthodoxworks.com/web-design/sns-logo-icon-svg-down-load/
![image](https://cloud.githubusercontent.com/assets/394338/6317218/c07cf7a0-baac-11e4-90c6-dcec4e1bbe40.png)

**Comment by CRS-ECHO51** [comment] 2015-02-22 15:07
:+1:  LINE is most popular chat app in Indonesia!

**Comment by tagliala** [comment] 2015-02-25 22:52
duplicate of #2631, please +1 that request

closing here

**Closed by tagliala** 2015-02-25 22:52 UTC
