### ISSUE TITLE
Icon request: icon-flipsetter

### ISSUE THREAD

**Issue by sabbythesage** [FortAwesome/Font-Awesome#12413] opened 2018-02-21 17:11 UTC
Hi there to all of our freelancers, developers and business owners! When was the last time you tried explaining a project to your clients, and they just don't get it or totally underestimate the work involved? 
We've learned that 1000's of freelancers and their clients don't speak the same language when it comes to the technical aspects of a project. While the client may feel that it wouldn't take a long time to finish a project, the freelancer knows that there are many different ways to code the project. Our **FlipSetter portfolio** gives clients a visual representation of what the freelancer can do because you can upload videos of your projects. People, companies, clients, etc. videos and most effectively relate to them. To this day, we are giving freelancers the tools that they've always been looking for, but didn't know how to properly communicate their skills to clients. What better way than a video?

Now, freelancers and developers can interact with their current and future clients a lot more effectively because everyone is all about presentation. With your help in voting for us, we can increase our advertising clout, as well as make it easier for you to apply to more jobs in one-click and beautify your portfolio with projects you feel very proud of!

![flipsetter logo](https://user-images.githubusercontent.com/19477046/36494003-e7090ba0-16fe-11e8-85d5-999803e22745.png)
![jobbox](https://user-images.githubusercontent.com/19477046/36494011-ea525c62-16fe-11e8-8034-0e3f30a77b97.png)

[https://www.flipsetter.com](url)

**Comment by sabbythesage** [comment] 2018-02-21 17:13
One example of how it would like is like so...(see attached)

As you can see, this legal office has our icon posted. However, it is not uniform to the other FontAwesome icons, so with your support in voting Font Awesome can add our icons to their list!

Many thanks!

![fs social media](https://user-images.githubusercontent.com/19477046/36494629-91046acc-1700-11e8-9b71-b84508afc62b.png)

**Comment by tagliala** [comment] 2018-02-21 17:55
Hi!

Thanks for being part of the Font Awesome Community.

Are you are requesting an icon for flipsetter.com?

If yes, please edit your message and make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by sabbythesage** [comment] 2018-02-21 18:16
Hello,

Yes, I am requesting for both icons to be added to your Font Awesome Community.


### What can it be used for?



### Example image (optional)



### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-02-21 18:59
Closing as a duplicate of #12416

**Closed by tagliala** 2018-02-21 18:59 UTC
Labels: waiting for feedback
