### ISSUE TITLE
Why not UNICODE

### ISSUE THREAD

**Issue by ezequias** [FortAwesome/Font-Awesome#6559] opened 2015-05-26 13:32 UTC
Hi everyone

I would like to know why fontawesome is not based on the old standard unicode. They have many thousands of characters and many symbols.

What do you think about it? There is any reason?

**Comment by tagliala** [comment] 2015-05-26 15:33
Sorry I don't get this question. Font Awesome uses the [Private Use Areas](http://en.wikipedia.org/wiki/Private_Use_Areas) of Unicode by design choice

If you mean that some symbols are also present in unicode, then this request is a duplicate of #222 and is planned for 5.0.0

**Comment by tagliala** [comment] 2016-01-22 09:26
Duplicate of #222, planned for 5.0.0

**Closed by tagliala** 2016-01-22 09:26 UTC
