### ISSUE TITLE
Icon request: phish-hook

### ISSUE THREAD

**Issue by mheidebrecht** [FortAwesome/Font-Awesome#19666] opened 2023-04-13 15:24 UTC
a fishing hook to represent phishing

**Comment by tagliala** [comment] 2023-04-13 15:37
Does https://fontawesome.com/icons/fishing-rod?f=classic&s=solid fit this use case?

**Comment by aethior** [comment] 2023-04-13 20:01
Duplicate of #19666?

**Comment by aethior** [comment] 2023-04-13 20:02
Duplicate of #9771?

**Comment by mheidebrecht** [comment] 2023-05-10 22:34
> Does https://fontawesome.com/icons/fishing-rod?f=classic&s=solid fit this use case?

Thanks, but I think it is not a concrete as the suggested ideas.

**Comment by sensibleworld** [comment] 2024-07-12 17:24
Closing in favor of: https://github.com/FortAwesome/Font-Awesome/issues/9771

**Closed as completed by sensibleworld** 2024-07-12 17:24 UTC
Labels: waiting for feedback
