### ISSUE TITLE
New Icons: Icon-Medical staff, Icon-human brain, Icon-dove

### ISSUE THREAD

**Issue by lstrovas** [FortAwesome/Font-Awesome#11511] opened 2017-09-10 23:32 UTC
Here are some examples:

![naturalmedical-symbol-copy-285x300](https://user-images.githubusercontent.com/31832355/30253958-0be6664e-964d-11e7-9f67-f773e00bf71b.png)

![bluedove](https://user-images.githubusercontent.com/31832355/30253981-f0d864fa-964d-11e7-9a38-379a04b128d0.jpg)

![humanbrainicon](https://user-images.githubusercontent.com/31832355/30253984-f98e015e-964d-11e7-8a89-8d7426537736.png)

**Comment by tagliala** [comment] 2017-09-11 07:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2009, #2075, #1612, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-11 07:52 UTC
