### ISSUE TITLE
Icon request: scratch

### ISSUE THREAD

**Issue by BrightWaters-Ami** [FortAwesome/Font-Awesome#18157] opened 2021-08-10 23:57 UTC
Would you mind adding the website icon for [Scratch](https://scratch.mit.edu/)?

I am planning on using it for an HTML social link, as well as a page reference link and a small demonstration.

Like this, but the yellow part is transparent.
![Example](https://user-images.githubusercontent.com/88749699/128949637-115b0a5f-e705-4646-90b7-6ae2fb45450a.png)

I'll be requesting two other icons as well!
(icon-amino, icon-pear)

**Comment by tagliala** [comment] 2021-08-11 05:59
Hi!

This request is a duplicate of #9336, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-08-11 05:59 UTC
