### ISSUE TITLE
Numbers : number-one, number-two ... number-nine

### ISSUE THREAD

**Issue by Psyster8** [FortAwesome/Font-Awesome#15527] opened 2019-09-13 08:48 UTC
**What can it be used for?**
Basicaly we are using a shinydashboardplus timeline component and instead of using it as a timeline we want to use it as a step by step process (1, 2 , 3 etc)
matched icons from one to nine

**Example image (optional)**
![1](https://user-images.githubusercontent.com/55275480/64849429-a4da3f80-d613-11e9-9e6c-11f239d70cc5.jpg)

**Comment by hpvd** [comment] 2020-04-14 10:55
+1

**Comment by groovybluedog** [comment] 2020-04-22 00:59
Having numbers is so under rated, surprised Font Awesome can be called awesome with so many icons but NO NUMBERS?!

**Comment by tagliala** [comment] 2020-04-29 13:51
Duplicate of #15495, sorry, missed this one

**Closed by tagliala** 2020-04-29 13:51 UTC
