### ISSUE TITLE
Bizarre characters showing instead of icons

### ISSUE THREAD

**Issue by andycorm** [FortAwesome/Font-Awesome#10872] opened 2017-03-31 18:38 UTC
So this issue is (unfortunately) quite intermittent, and only occurs on probably every 1 of 1000 page loads, so it's been a doozy to diagnose.

Basically every once in a while, I'll reload my page without making any changes, and all of my font-awesome icons are replaced with strange characters. My developer tools don't report any issues, and it looks like all resources are loaded. Has anyone dealt with this issue before?

Normal page load:
![screen shot 2017-03-31 at 11 32 36 am](https://cloud.githubusercontent.com/assets/2769725/24564295/40016c48-1606-11e7-8d37-76beea964240.png)

Buggy page load:
![screen shot 2017-03-31 at 11 38 43 am](https://cloud.githubusercontent.com/assets/2769725/24564409/a69adf70-1606-11e7-87d9-364ed4fb298e.png)

I'm using chrome on the latest production version of OS X, and we always install the latest version of font awesome locally via bower. I'm starting to wonder if font-awesome just isn't playing nicely with another library, but I figured I'd see if anyone has any insight before I continue on my wild goose chase.

Thanks!

EDIT: Fixed buggy screenshot

**Comment by jeffgrove** [comment] 2017-03-31 18:43
@andycorm , good writeup! I've seen the same thing. I got it twice in fairly quick succession and then not again. I really noticed on the Booking Manager page where there are 5 icons on the side when at the Contract tab.

**Comment by tagliala** [comment] 2017-03-31 18:49
Probably a duplicate of #10842

Please give us all the information you could provide

1. How are you loading font awesome, in detail. self-hosted (compiled from scss/less), webserver, webserver version or cdn.
2. Browser and browser version affected by the issue
3. OS

**Comment by tagliala** [comment] 2019-01-31 22:20
I'm pretty confident that this has been fixed in version 5.0.0

**Closed by tagliala** 2019-01-31 22:20 UTC
Labels: waiting for feedback
