### ISSUE TITLE
Icon request: icon-commit

### ISSUE THREAD

**Issue by peinorim** [FortAwesome/Font-Awesome#8513] opened 2016-02-09 14:04 UTC
Hi, it would be great if you could create a new icon based on github's vector asset for commits :
For example i would use it to illustrate my github timeline.
```
<svg width="14" viewBox="0 0 14 16" version="1.1" role="img" height="16" aria-hidden="true">
<path d="M10.86 7c-0.45-1.72-2-3-3.86-3s-3.41 1.28-3.86 3H0v2h3.14c0.45 1.72 2 3 3.86 3s3.41-1.28 3.86-3h3.14V7H10.86zM7 10.2c-1.22 0-2.2-0.98-2.2-2.2s0.98-2.2 2.2-2.2 2.2 0.98 2.2 2.2-0.98 2.2-2.2 2.2z">
</svg>
```

**Comment by tagliala** [comment] 2016-02-09 21:16
Duplicate of #5602, please +1 that request

closing here

**Closed by tagliala** 2016-02-09 21:16 UTC
