### ISSUE TITLE
Icon Request: fa-note

### ISSUE THREAD

**Issue by shemani** [FortAwesome/Font-Awesome#5546] opened 2015-02-01 02:06 UTC
Use Case 1: Use icon to indicate sticky note
![notes_entry](https://cloud.githubusercontent.com/assets/5160083/5990715/0c760f06-a98d-11e4-8a3b-1d68d212f81f.png)

**Comment by tagliala** [comment] 2015-02-01 18:13
duplicate of #1986, please +1 that requesst

closing here

**Closed by tagliala** 2015-02-01 18:13 UTC
