### ISSUE TITLE
Icon request: icon-raspberrypi

### ISSUE THREAD

**Issue by realnitinkapoor** [FortAwesome/Font-Awesome#8198] opened 2015-12-21 11:43 UTC
Hi FontAwesome,

Frist of all ,I want to congratulate you on your initiative. Its...as the name suggest "Awesome" . 

As you might be aware of IOT is exponentially increasing and a lot many projecta are based on small 5-10$ circuit PC . 
The popular one is Raspberry Pi. If we can get an icon for it .It would be AWESOME.

Thanks And Regards
--Nitin

**Comment by tagliala** [comment] 2015-12-21 12:06
duplicate of #2944 , please +1 that request

closing here

**Closed by tagliala** 2015-12-21 12:06 UTC
