### ISSUE TITLE
Icon Request: fa-bucket

### ISSUE THREAD

**Issue by smorecraft** [FortAwesome/Font-Awesome#6684] opened 2015-06-08 11:41 UTC
We would really like an icon which is a bucket but not bit-bucket (without the circular symbol).  If it was 2d without the perspective and with stacking capabilities then the horizontal lines would appear a little better 

We would use style to colour the background using CSS to show how full the "bucket" is - we would add all the numbers etc ourselves. We have done this with the bit-bucket

![screen shot 2015-05-18 at 3 46 16 pm](https://cloud.githubusercontent.com/assets/12796629/8033963/249bad68-0ddb-11e5-9368-71a9488c44ce.png)

![image](https://cloud.githubusercontent.com/assets/12796629/8033989/8017f944-0ddb-11e5-97ce-e6454546bc7c.png)

**Comment by tagliala** [comment] 2015-06-08 11:58
duplicate of #788, please +1 that request

closing here

**Closed by tagliala** 2015-06-08 11:58 UTC
