### ISSUE TITLE
Icon request: Unsplash

### ISSUE THREAD

**Issue by kirillzakharov** [FortAwesome/Font-Awesome#15554] opened 2019-09-17 05:11 UTC
**What can it be used for?**
[Unsplash](https://unsplash.com) (brand) powers the internet's visuals by offering free, high-quality images.

**Example image (optional)**
![Unsplash_Symbol_128x128](https://user-images.githubusercontent.com/1811107/65013109-b0658900-d8e7-11e9-9c42-0bd8245c58fd.png)

[Symbol brand folder](https://www.dropbox.com/sh/pyp2iplfyy1pfjx/AADneK7IkJjUassZxAf8Oabea?dl=0)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-09-17 07:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11508, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-17 07:00 UTC
