### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by drebori** [FortAwesome/Font-Awesome#14075] opened 2018-10-07 02:35 UTC
A person running

**Comment by tagliala** [comment] 2018-10-07 09:53
#
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1156 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-07 09:53 UTC
