### ISSUE TITLE
New brand icon - linktree

### ISSUE THREAD

**Issue by dweuste** [FortAwesome/Font-Awesome#17253] opened 2020-10-07 22:38 UTC
This would be a request for the linktree icon. Seen here https://linktr.ee/

**Comment by tagliala** [comment] 2020-10-08 07:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17069, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-10-08 07:44 UTC

**Comment by dweuste** [comment] 2020-10-08 14:58
Great - thanks, apologies, searched a few times and didn't see that request, but I may have only been searching open issues.

**Comment by tagliala** [comment] 2020-10-08 15:13
@dweuste no problem, it happens for some reason that the search doesn't work
