### ISSUE TITLE
Icon Request: fa-chilli

### ISSUE THREAD

**Issue by ninikene** [FortAwesome/Font-Awesome#5432] opened 2015-01-20 16:49 UTC
Hi there, I have come across so many restaurant websites who could really do with this icon indicating how hot their dishes are.. Any chance?? Cheers!

**Comment by tagliala** [comment] 2015-01-20 18:15
duplicate of #1684, please +1 that request

closing here

**Closed by tagliala** 2015-01-20 18:15 UTC
