### ISSUE TITLE
Icon Request: Walking human, google walking directions

### ISSUE THREAD

**Issue by Pubudu-Basnayaka-COS** [FortAwesome/Font-Awesome#11906] opened 2017-12-11 14:12 UTC
Looking for a human, man or woman, preferably both, walking icon. Something like fa-male but with a walking silhouette.

**Comment by PeterShaggyNoble** [comment] 2017-12-11 15:03
Duplicate of #844.

**Closed** 2017-12-11 20:41 UTC
