### ISSUE TITLE
MeteorJS Icon

### ISSUE THREAD

**Issue by KidzIdeaz** [FortAwesome/Font-Awesome#11077] opened 2017-05-16 19:40 UTC
www.meteor.com

**Comment by tagliala** [comment] 2017-05-16 19:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4913, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-16 19:57 UTC
