### ISSUE TITLE
Icon Request: fa-moodle

### ISSUE THREAD

**Issue by bry54** [FortAwesome/Font-Awesome#10975] opened 2017-04-22 20:11 UTC
![install-moodle-on-an-ubuntu-14-04-vps-with-mariadb-php-fpm-and-nginx](https://cloud.githubusercontent.com/assets/5229851/25307814/86d61a18-27b0-11e7-8724-3d617f484ad4.png)

I am developing a learning platform that based on moodle, I thought it would be great to have the icon as font-awesome as well :-)

**Comment by tagliala** [comment] 2017-04-22 21:18
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2167, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-22 21:18 UTC
