### ISSUE TITLE
Icon request: fa-vk-square

### ISSUE THREAD

**Issue by koorgoo** [FortAwesome/Font-Awesome#7188] opened 2015-08-10 07:14 UTC
Most social network icons have a _*-square_ version. But the VK icon do not.

**Comment by tagliala** [comment] 2015-08-10 08:05
Duplicate of #1515, please +1 that request

closing here

**Closed by tagliala** 2015-08-10 08:05 UTC

**Comment by koorgoo** [comment] 2015-08-10 08:07
@tagliala sorry. Thanks.
