### ISSUE TITLE
Icon Request: fa-hammer

### ISSUE THREAD

**Issue by AllPlayed** [FortAwesome/Font-Awesome#11851] opened 2017-12-06 18:58 UTC
Add a Hammer as an Icon
Only that

**Comment by WulfGamesYT** [comment] 2017-12-07 16:09
There is `fa-gavel` if that helps you?

**Comment by PeterShaggyNoble** [comment] 2017-12-07 16:11
Duplicate of #1214.

**Comment by Tirzahe** [comment] 2018-01-27 18:16
Construction or remodel website would be better with a hammer than a gavel. likethis set of tools icons. https://www.freepik.com/premium-vector/tool-icons-collection_1056122.htm#term=hammer&page=1&position=32

**Comment by tagliala** [comment] 2018-08-08 22:06
Closing here as a duplicate of #1214

**Closed by tagliala** 2018-08-08 22:06 UTC
