### ISSUE TITLE
Icon request: ethernet-port

### ISSUE THREAD

**Issue by cloudtrov** [FortAwesome/Font-Awesome#14073] opened 2018-10-06 05:04 UTC
### What can it be used for?
It would be helpful to have representation of network icon (single icon) like ethernet port.

### Example image (optional)

NA
### Icon request checklist

- [ *] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ *] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ *] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ *] I have included at least one example image if it could be helpful (optional)
- [ *] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-10-06 10:36
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #2565

If this is not a duplicate or it has a different use case, please clarify this request and I will reopen

**Closed by tagliala** 2018-10-06 10:36 UTC
