### ISSUE TITLE
Connected // Disconnected Icon Requested

### ISSUE THREAD

**Issue by cgers** [FortAwesome/Font-Awesome#19172] opened 2022-07-06 09:37 UTC
Please could you look into creating an icon that shows if something is connected / disconnected. 

An example can be found here: https://icon-library.com/icon/icon-connected-8.html 

Kind regards

**Comment by tagliala** [comment] 2022-07-17 09:36
Hi!

Thanks for being part of the Font Awesome Community.

I'm pretty confident that this is a duplicate, but at the moment I'm not able to find the original  one

Partial duplicate of #10440

**Comment by sensibleworld** [comment] 2024-07-11 15:10
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/19420)

**Closed as completed by sensibleworld** 2024-07-11 15:10 UTC
Labels: new icon, waiting for feedback, Duplicate
