### ISSUE TITLE
Upgrade to Font Awesome 5.0.1 icon issue

### ISSUE THREAD

**Issue by ravihariharan** [FortAwesome/Font-Awesome#11891] opened 2017-12-09 21:25 UTC
The below icons seems to have some issue. shown as blank.
fas fa-redo-alt 
fas fa-sync-alt 
fas fa-lock-open
fab fa-stripe-s

Upgrade to Font Awesome 5.0.1 #3056 - https://github.com/primefaces/primefaces/issues/3056
https://github.com/ravihariharan/primefaces/tree/master/src/main/resources/META-INF/resources/primefaces/fa

e.g.

![image](https://user-images.githubusercontent.com/15189434/33799605-0f7c1712-dcfd-11e7-8795-c9fd994095b3.png)

![image](https://user-images.githubusercontent.com/15189434/33799610-1a99c3ce-dcfd-11e7-886e-19cf17500c24.png)

**Comment by tagliala** [comment] 2017-12-09 23:06
Hi!

Thanks for being part of the Font Awesome community.

The icons you have listed are not present in FA 5.0.0, so the issue was not caused by the upgrade itself

FA 5.0.0: https://jsfiddle.net/tagliala/cq9rdny4/3/
FA 5.0.1: https://jsfiddle.net/tagliala/tgzouajm/2/

I've also:
- tested locally, by manually downloading the zip file of FA 5.0.1
- checked sha1 of released files

Could you please check that there are no caching issue on your side? I suspect that you are serving the old version of the font, even if the files checked in your repository are up to date

Meanwhile, closing here but feel free to comment and I will reopen if there is an issue on our side

**Closed by tagliala** 2017-12-09 23:06 UTC
