### ISSUE TITLE
Brand request: Pixelfed

### ISSUE THREAD

**Issue by zcraber** [FortAwesome/Font-Awesome#19454] opened 2022-11-30 14:39 UTC
### Description

Pixelfed is an open-source federated image-sharing social network which is considered an alternative to Instagram.

![symbolic](https://user-images.githubusercontent.com/61133303/204825074-b41cea83-216c-4cb2-ae40-dcf7eb1ae84e.svg)
![pixelfed](https://user-images.githubusercontent.com/61133303/204911729-d04950a5-08d2-4676-891e-0677692678ba.svg)

### Official website

https://pixelfed.org/

### Brand guidelines

https://github.com/pixelfed/brand-assets

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2022-11-30 15:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14220, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-11-30 15:43 UTC
Labels: brand icon

**Comment by zcraber** [comment] 2022-11-30 15:51
Sorry about the duplicate post. For some reason, that request didn't show up when I searched before posting.

**Comment by tagliala** [comment] 2022-11-30 16:02
No problem, it happens. I will improve my answer template because sometimes search may not work
