### ISSUE TITLE
Resources with a "?" in the URL are not cached by some proxy caching servers

### ISSUE THREAD

**Issue by danger89** [FortAwesome/Font-Awesome#10153] opened 2016-11-01 13:37 UTC
Hi,

About your _font-awesome.min.css_ file:
`font-face{font-family:'FontAwesome';
src:url('../fonts/fontawesome-webfont.eot?v=4.7.0');
src:url('../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0') format('embedded-opentype'),
url('../fonts/fontawesome-webfont.woff2?v=4.7.0') format('woff2'),
url('../fonts/fontawesome-webfont.woff?v=4.7.0')
`

Speedtest website Pingdom.com explain that the lines with ?v=4.7.0 should be removed if possible. Since these links may not be cached by some proxies servers:

> Resources with a "?" in the URL are not cached by some proxy caching servers. Remove the query string and encode the parameters into the URL for the following resources:
> 
>     https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0
> 

Do you agree with this remark? If so, you may want to fix this.

Kind regards,
Melroy

**Comment by danger89** [comment] 2016-11-01 13:39
Maybe it's already fixed, but not yet in 4.7?

https://github.com/bokmann/font-awesome-rails/pull/175/commits/5739eb1e20be69f3ba0584ce1d61568a7df16fac

**Comment by tagliala** [comment] 2017-01-28 21:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3286, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-28 21:44 UTC
