### ISSUE TITLE
Icon request: fa-stage-light

### ISSUE THREAD

**Issue by creature7** [FortAwesome/Font-Awesome#14651] opened 2019-02-16 23:01 UTC
### What can it be used for?

I believe a spotlight/light fixture icon could be used on many websites and in marketing material, especially those related to stage/entertainment/venues/shows. Because...SHOW BIZ!

### Example image (optional)

![spot-light-icon](https://miserybay-software.com/img/fa-spot-light.png "fa-spot-light")

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-02-17 12:11
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #153?

It looks like it isn't, so I need a different title for this one

**Comment by creature7** [comment] 2019-02-17 13:24
I renamed to 'fa-light-fixture' as an alternative.

**Comment by tagliala** [comment] 2019-02-17 18:51
thanks!

**Comment by Lucmia** [comment] 2019-02-27 01:46
Is this icon limited to the paid accounts for font awesome?  I tried "fa fa-stage-light" and got nothing.  Tried a free icon and it worked fine.  Pretty new to font awesome (and github - created an account to be able to ask this question).  Thanks in advance!

**Comment by sensibleworld** [comment] 2024-07-11 19:07
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/153)

**Closed by sensibleworld** 2024-07-11 19:07 UTC
Labels: new icon, web application icons (legacy category), Duplicate
