### ISSUE TITLE
Icon request: Numbers 0-9;  fa-num-1, ..., fa-num-9

### ISSUE THREAD

**Issue by Soliaonline** [FortAwesome/Font-Awesome#14629] opened 2019-02-12 03:13 UTC
**Uses**
Telephone, tabs, frames, all kinds of things.

Also useful for displaying mathematics as the symbols already exist.  (Root, Times, Plus, ect)

**Creation**
Use existing created numbers, work would be extremely minimal.

fa-num-0
fa-num-1
fa-num-2
fa-num-3
fa-num-4
fa-num-5
fa-num-6
fa-num-7
fa-num-8
fa-num-9

With that simple set everything else could be made. 

**Other Thoughts**
(Another cute idea would be Roman Numerals, but that's far more work)

Thank you for taking the time to even read my suggestion.  I hope you have a wonderful work day.

**Comment by tagliala** [comment] 2019-02-12 09:17
Hi!

Thanks for being part of the Font Awesome Community.

At the moment, I'm considering these requests as a duplicate of #5019, which is labeled as won't fix

Numbers and letters are out of the scope now, but they can come in the future

Hope it helps

Closing here

**Closed by tagliala** 2019-02-12 09:17 UTC

**Comment by tagliala** [comment] 2021-04-01 16:44
> but they can come in the future

They will be part of FA6 🥳
