### ISSUE TITLE
Icon request: mongo

### ISSUE THREAD

**Issue by chana987** [FortAwesome/Font-Awesome#16179] opened 2020-02-11 15:06 UTC
**What can it be used for?**
For referencing the company.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/50216349/74248780-cb022980-4cf0-11ea-93fb-724342358f0f.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-02-18 22:02
Hi!

Thanks for being part of the Font Awesome Community.

is this a duplicate of #2725?

**Comment by chana987** [comment] 2020-02-19 12:55
Apparently it is :)
I didn't know where to look for existing requests.
Thanks!

**Comment by tagliala** [comment] 2020-02-19 14:55
No problem, closing here

please 👍 #2725

**Closed by tagliala** 2020-02-19 14:55 UTC
