### ISSUE TITLE
Icon request: fa-layer

### ISSUE THREAD

**Issue by NielsHolt** [FortAwesome/Font-Awesome#13251] opened 2018-06-01 11:52 UTC
![image](https://user-images.githubusercontent.com/11357972/40839481-11c904e2-65a3-11e8-899e-69c666f41aac.png)

**Comment by tagliala** [comment] 2018-06-01 13:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1179, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-01 13:54 UTC
