### ISSUE TITLE
Icon Request: fa-sketchfab

### ISSUE THREAD

**Issue by ArchT0** [FortAwesome/Font-Awesome#9481] opened 2016-06-26 16:53 UTC
Please it will be nice to add a sketchfab.com icon. Thank you !

**Comment by tagliala** [comment] 2016-06-26 18:44
Duplicate of #2757, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-26 18:44 UTC
