### ISSUE TITLE
Icon request: pear

### ISSUE THREAD

**Issue by BrightWaters-Ami** [FortAwesome/Font-Awesome#18158] opened 2021-08-11 00:01 UTC
Would you mind adding a pear icon?

I am planning on using it for an HTML social/contact link for the website [Wajas](https://www.wajas.com/home_landing.php), as well as a page reference link and a small demonstration.

It should look like this, but tilted slightly towards the right.
![Example](https://user-images.githubusercontent.com/88749699/128949918-70714d96-b732-4c94-8993-78ed0f91433a.png)

I'll be requesting two other icons as well!
(icon-amino, icon-scratch)

**Comment by tagliala** [comment] 2021-08-11 05:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6012, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-08-11 05:58 UTC
