### ISSUE TITLE
Feature request: Döner menu

### ISSUE THREAD

**Issue by dvbeek** [FortAwesome/Font-Awesome#16435] opened 2020-04-08 07:32 UTC
**Is your feature request related to a problem? Please describe.**
Some menu icons are currently not available, like the icons for the döner (/ strawberry) menu and the bento (/ chocolate) menu icons (but there is already an issue for Bento menu: #15452).

**Describe the solution you'd like**
It would be nice if the Döner / Strawberry menu icons were also available in the font-awesome collection.

**Describe alternatives you've considered**
Using icons from other resources

**Additional context**
Some of the other menus are available (under different names):
hamburger = bars
kebab = ellipsis-v
meatballs = ellipsis-h

**Feature request checklist**
- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2020-04-08 07:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14485 , called "filter-alt", please add a 👍 reaction to that request.

Please also paste your comment there, I'm going to edit the title and include `doner menu`

Closing here

**Closed by tagliala** 2020-04-08 07:42 UTC
