### ISSUE TITLE
Brand Icon request: fa-woltlab fa-jts3mod fa-sinusbot

### ISSUE THREAD

**Issue by LalaSatalinDeviluke** [FortAwesome/Font-Awesome#13069] opened 2018-05-08 17:08 UTC
### What can it be used for?
For Websites with Links to the control sites

### Example images
Woltlab: [https://www.woltlab.com/images/favicon/default.apple-touch-icon.png](https://www.woltlab.com/images/favicon/default.apple-touch-icon.png)
JTS3Mod: it does not have an icon yet
SinusBot: [https://forum.sinusbot.com/sinusbot-logo.png](https://forum.sinusbot.com/sinusbot-logo.png) the "N" of the Logo

### Site Links

- Woltlab: https://woltlab.com
- JTS3Mod: https://www.stefan1200.de/forum/index.php
- Sinusbot: https://sinusbot.com

#### Woltlab 
WoltLab is a leading Developer in Community Software (Forukm, Filebase ...)

#### JTS3Mod
JTS3Mod is a Java Control Bot for TeamSpeak 3 from the developer Stefan1200

#### SinusBot
SinusBot is an brand for a TeamSpeak 3 and Discord MusicBot from the Developer Michael Friese

### Info
There is already a request from 2015 for fa-woltlab [#7719](https://github.com/FortAwesome/Font-Awesome/issues/7719)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Would be nice if someone could add it.

**Comment by tagliala** [comment] 2018-05-08 17:42
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

> This is a single icon or matched pair (Ex: lock / unlock)

Brands ar not related

> I have searched for existing issues and to the best of my knowledge this is not a duplicate

> There is already a request from 2015 for fa-woltlab #7719

wotlab is a duplicate of #7719, you should upvote that request



Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2018-05-08 17:42 UTC
