### ISSUE TITLE
Icon Request: fa-responsive

### ISSUE THREAD

**Issue by iamjagannathr** [FortAwesome/Font-Awesome#11575] opened 2017-09-30 10:03 UTC
Dear fontawesome team,
         Please add an icon for responsive. I always had to use images for this. Please add this.

**Comment by tagliala** [comment] 2017-09-30 10:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1446, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-30 10:07 UTC
