### ISSUE TITLE
Icon Request: fa-sketchfab

### ISSUE THREAD

**Issue by sonance2** [FortAwesome/Font-Awesome#11589] opened 2017-10-04 11:51 UTC
![sketchfab-logo-8bc6696c7ed7369e1acaee4ec5168169](https://user-images.githubusercontent.com/17828134/31174219-9912af9c-a902-11e7-92ec-ca40c9e28884.png)

Sketchfab - A community to create awesome 3D objects runs in the browser (webgl).

**Comment by tagliala** [comment] 2017-10-04 12:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2757, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-04 12:45 UTC
