### ISSUE TITLE
pugjs

### ISSUE THREAD

**Issue by jrazap** [FortAwesome/Font-Awesome#18150] opened 2021-08-09 16:06 UTC
**What can it be used for?**
pugjs is a web tech.

**Example image (optional)**
![pug-icon](https://user-images.githubusercontent.com/55711330/128737452-51a3130e-4a4f-432d-986b-31e36c7fc6d4.png)

**Icon request checklist**
- [x] This is a single icon 
- [x]  `Icon request: pugjs`
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-08-09 17:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13706, please add a 👍 reaction to that request.

**Closed by tagliala** 2021-08-09 17:30 UTC
