### ISSUE TITLE
Icon Request: Mushroom Cloud

### ISSUE THREAD

**Issue by Oceanswave** [FortAwesome/Font-Awesome#5584] opened 2015-02-04 17:15 UTC
Occasionally, we find ourselves wanting to implement a button or indicating an activity that describes a very drastic option.
Often, we refer to this as "The Nuclear Option" or possibly "Nuke it"

Thus, it would be wonderful, just stellar, I mean completely radical, if font awesome had an icon to support such functionality -- e.g. a mushroom cloud icon such as the following:

![image](https://cloud.githubusercontent.com/assets/760674/6045309/25e2405e-ac67-11e4-96f6-db78e302dd87.png)

Thanks!

**Comment by tagliala** [comment] 2015-02-04 23:32
duplicate of #1967, please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-02-04 23:32 UTC
