### ISSUE TITLE
Icon Request: IMDB

### ISSUE THREAD

**Issue by wot4** [FortAwesome/Font-Awesome#5849] opened 2015-03-04 21:52 UTC
The Internet Movie Database (abbreviated IMDb) is an online database of information related to films, television programs, and video games.

As of March 2, 2015, IMDb had 3,213,327 titles (includes episodes) and 6,411,964 personalities in its database,[2] as well as 59 million registered users and is an Alexa Top 50 site.

Please can you add IMDB as an icon for a social profile link. 

https://www.google.co.uk/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0CAcQjRw&url=http%3A%2F%2Fthelibrarians.wikia.com%2Fwiki%2FFile%3AIMDb_icon.png&ei=Z3_3VJGzGdLbaoPvgKAN&bvm=bv.87519884,d.d2s&psig=AFQjCNFsPjpTpjzyP36a9H5mQfLnkkcdRw&ust=1425592590211443

**Comment by tagliala** [comment] 2015-03-04 22:15
duplicate of #998 , please +1 that request

closing here

**Closed by tagliala** 2015-03-04 22:15 UTC
