### ISSUE TITLE
Icon request: car-door

### ISSUE THREAD

**Issue by kaloxri** [FortAwesome/Font-Awesome#16147] opened 2020-02-04 11:19 UTC
It could be used for an open-source project for car booking.

![68747470733a2f2f64333079396364737537786c67302e636c6f756466726f6e742e6e65742f706e672f3132323432342d3230302e706e67](https://user-images.githubusercontent.com/10146094/73740509-029d2e80-4751-11ea-92af-29ff6f226412.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-02-04 11:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10551, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-02-04 11:22 UTC
