### ISSUE TITLE
Icon Request: fa-full-screen

### ISSUE THREAD

**Issue by mahendra-alladi** [FortAwesome/Font-Awesome#7000] opened 2015-07-21 04:13 UTC
Request for icons for "full screen" and "exit full screen"

Thanks
Mahendra

**Comment by sanderdekkers** [comment] 2015-07-21 13:37
isn't http://fontawesome.io/icon/arrows-alt/ a valid full-screen icon ?
exit full screen could be a new one, with arrows pointing inwards

**Comment by mahendra-alladi** [comment] 2015-07-22 03:48
Sure, but when I used it on a draggable modal, this icon looks very close to drag pointer. Thanks for considering the request.

Regards

Mahendra

**Comment by tagliala** [comment] 2015-07-22 12:10
maybe a duplicate of #4576 ?

**Comment by mahendra-alladi** [comment] 2015-07-22 12:12
Yes, thank you

**Comment by tagliala** [comment] 2015-07-22 12:14
you're welcome. please +1 #4576 

closing here

**Closed by tagliala** 2015-07-22 12:14 UTC
Labels: waiting for feedback
