### ISSUE TITLE
Icon request: icon-blog

### ISSUE THREAD

**Issue by swosu-karen** [FortAwesome/Font-Awesome#7241] opened 2015-08-15 22:14 UTC
I did a search for a "blog" icon and it returned the rss one. I'd like something a  little more detailed to use along where all of my other social media icons are displayed throughout the website. The attached image is what I have used in the past but want to use font icons like I do with my social media links. It uses the word "blog" but even a "b" along with the rss symbol would be great. Thank you!
![blog-icon](https://cloud.githubusercontent.com/assets/6200636/9291052/cd6dc8aa-4368-11e5-84e9-2ace82bd33cd.png)

**Comment by TheChen5** [comment] 2015-08-16 02:46
Dupe of #455 
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-16 11:40
closing here

**Closed by tagliala** 2015-08-16 11:40 UTC
