### ISSUE TITLE
Icon Request: Rename Fork and Create Decision

### ISSUE THREAD

**Issue by no1youknowz** [FortAwesome/Font-Awesome#9710] opened 2016-08-06 13:12 UTC
Change the current fork to fa-decision.

Have this one as the fork: https://octicons.github.com/icon/repo-forked/

**Comment by tagliala** [comment] 2016-08-06 16:21
Duplicate of #3431, planned for 5.0.0

**Closed by tagliala** 2016-08-06 16:21 UTC
