### ISSUE TITLE
svg fa-layers count positioning not working as intended

### ISSUE THREAD

**Issue by chrishough** [FortAwesome/Font-Awesome#17818] opened 2021-04-14 14:54 UTC
**Describe the bug**
When I try to use fa-layers-top-right in my svg icons the position never changes, in fact it does not change for any of them. The documentation discusses `Adds a counter to the top right of your icons. Can be positioned with fa-layers-bottom-left, fa-layers-bottom-right, fa-layers-top-left and the default fa-layers-top-right. Overflow text is truncated with an ellipsis.` https://fontawesome.com/how-to-use/on-the-web/styling/layering however it does not show how this works in the example.

**To Reproduce**
Code included.

**Expected behavior**
Example Code via Slim-Lang
```slim
    div[class="icon-wrapper"]
      span[class="fa-layers fa-fw"]
        i[class="fas fa-sms"]
        span[class="fa-layers-counter fa-layers-top-right"]
          |750
```
Sample CSS
```css
  .icon-wrapper {
    padding-right: 1.5rem;

    .fa-envelope-square,
    .fa-phone-square-alt,
    .fa-sms {
      font-size: 2.5rem;
    }

    .fa-layers-counter {
      background: Tomato;
      font-size: 2rem;
    }
```

**Screenshots**
<img width="155" alt="Screen Shot 2021-04-14 at 7 38 42 AM" src="https://user-images.githubusercontent.com/744056/114729148-f4578480-9cfc-11eb-8804-cfa5edcbac11.png">

**Version and implementation**
Version: SVG with JS
Browser and version: Chrome Latest

*Thank you for your help and all the work you do*

**Comment by tagliala** [comment] 2021-04-14 16:11
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

Sorry, can't reproduce.

Demo: https://jsfiddle.net/tagliala/cf4mL7n5/3/

If you are still experiencing this issue, please provide a reproducible test case

Hope it helps

Closing here

**Closed by tagliala** 2021-04-14 16:11 UTC

**Comment by chrishough** [comment] 2021-04-15 12:45
@tagliala while yours worked I have to point out what the cause was for others, and the differences between our code. 

First, mine looks like this and does not have the `fa-3x` class...
<img width="175" alt="Screen Shot 2021-04-15 at 5 42 36 AM" src="https://user-images.githubusercontent.com/744056/114871019-119c5980-9db6-11eb-9b64-de72b984f36b.png">

With your code and the `fa-3x` class...
```slim
%div.icon-wrapper.fa-3x
  %span.fa-layers.fa-fw
    %i.fas.fa-sms
    %span.fa-layers-counter.fa-layers-top-right
      750
```
<img width="270" alt="Screen Shot 2021-04-15 at 5 42 51 AM" src="https://user-images.githubusercontent.com/744056/114871086-25e05680-9db6-11eb-9c59-cdc7e7dbb09e.png">

It looks like that class fixes the situation.

**Comment by tagliala** [comment] 2021-04-15 12:50
> First, mine looks like this and does not have the fa-3x class...

Hi, I've used `fa-3x` only to make the icon visible

You should not use `fa-3x` to make it work, and the text should scale accordingly:

https://jsfiddle.net/tagliala/cf4mL7n5/6/

I think there is a rule applying the font-size in the wrong place

> It looks like that class fixes the situation.

Nope, this is not fixed yet, the text should look bigger with that icon size

**Comment by chrishough** [comment] 2021-04-15 12:58
I hadn't adjusted the css I had for the bubble which is...
```css
.fa-layers-counter {
    background: Tomato;
    font-size: 3rem;
}```

I adjusted that up and now it looks like... 
<img width="303" alt="Screen Shot 2021-04-15 at 5 57 54 AM" src="https://user-images.githubusercontent.com/744056/114872874-f4688a80-9db7-11eb-82ed-15e19ada1884.png">

Somehow those wrapper classes are making this work, but they are not in the example

**Comment by chrishough** [comment] 2021-04-15 13:09
@tagliala one last thing I am seeing is this adjust the spacing, and will not align-left
<img width="249" alt="Screen Shot 2021-04-15 at 6 08 43 AM" src="https://user-images.githubusercontent.com/744056/114874382-845b0400-9db9-11eb-938a-6214ce26d007.png">
 now. Thoughts?

**Comment by tagliala** [comment] 2021-04-15 14:24
> and will not align-left now. Thoughts?

`fa-layers` sets width to 1em. Removing `fa-fw` will help.

Since Font Awesome icons do not have the same width by design choice, you may need custom css

Example (the gamepad icon): https://jsfiddle.net/tagliala/cf4mL7n5/17/
