### ISSUE TITLE
Icon request: icon-ladder

### ISSUE THREAD

**Issue by Gingrposh** [FortAwesome/Font-Awesome#18109] opened 2021-07-27 07:16 UTC
**What can it be used for?**
To symbolize a climber or climbing in general

**Icon request checklist**
- [x] This is a single icon or matched pair  `lock`
- [x] The title starts with "Icon request: " and is followed by the requested icon name 
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate y
- [x] The request is for a concrete object

**Comment by tagliala** [comment] 2021-07-27 07:32
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2479, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-07-27 07:32 UTC
