### ISSUE TITLE
Icon request: itch-io + epic games

### ISSUE THREAD

**Issue by mackreese** [FortAwesome/Font-Awesome#19250] opened 2022-08-09 01:40 UTC
would be nice to have itch.io and epic games icons to match the square-steam icon

**Comment by tagliala** [comment] 2022-08-09 06:27
Hi!

Thanks for being part of the Font Awesome Community.

itch-io icon has been added to FontAwesome in version 5.8.0:
- https://fontawesome.com/icons/itch-io?s=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

epic games is a duplicate of #13724, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-08-09 06:27 UTC
