### ISSUE TITLE
No icons JQuery

### ISSUE THREAD

**Issue by 8DZ8** [FortAwesome/Font-Awesome#16594] opened 2020-05-07 19:07 UTC
Hello! Please, i want to use JQuery icons, add it, then i have more happy)))

**Comment by tagliala** [comment] 2020-05-07 19:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1665 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-07 19:20 UTC
