### ISSUE TITLE
Icon request: diagonal arrows

### ISSUE THREAD

**Issue by oscarklink** [FortAwesome/Font-Awesome#11432] opened 2017-08-23 10:53 UTC
I would very much like to see diagonal arrows in font-awesome, it would be great to display as a increase indicator. Imagine a economic dashboard where you display stock market changes over time, and you use the different arrows as indicators for when a stock has increased/decreased, using diagonal arrows in a case like this to show a slower increase/decrease would be optimal.

![109607](https://user-images.githubusercontent.com/5614761/29612461-b6c38254-8801-11e7-9805-eef026fea21e.png)

**Comment by tagliala** [comment] 2017-08-23 11:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #937, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-23 11:35 UTC
