### ISSUE TITLE
Icon Request: fa-discord

### ISSUE THREAD

**Issue by PliCx** [FortAwesome/Font-Awesome#11252] opened 2017-07-05 09:33 UTC
To link people's servers with a nice button with a fa-discord icon !

[https://discordapp.com/branding](https://discordapp.com/branding)

![Discord Logo](https://discordapp.com/assets/41484d92c876f76b20c7f746221e8151.svg)

**Comment by tagliala** [comment] 2017-07-05 09:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-05 09:46 UTC
