### ISSUE TITLE
Icon Request: fa-new

### ISSUE THREAD

**Issue by nickzuck** [FortAwesome/Font-Awesome#9815] opened 2016-08-25 20:50 UTC
I think font-awesome must have icon for showing new stuffs in a website. Some of the ideas are:

- New inside a start
- New inside a red rectangle with circular edges

**Comment by tagliala** [comment] 2016-08-25 23:50
Duplicate of #1331 , please add a 👍  reaction to that request

Please check this comment: https://github.com/FortAwesome/Font-Awesome/issues/9762#issuecomment-240363578

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-25 23:50 UTC
