### ISSUE TITLE
fa-signal with progression

### ISSUE THREAD

**Issue by lgm42** [FortAwesome/Font-Awesome#8050] opened 2015-12-01 13:41 UTC
Is it possible to have a fa-signal-0 until fa-signal-5 like fa-battery-0 .. -5 ?
![image](https://cloud.githubusercontent.com/assets/6039130/11502173/889bc382-9839-11e5-9ee2-b6763a1d24f2.png)

![image](https://cloud.githubusercontent.com/assets/6039130/11502178/92d07dca-9839-11e5-939e-9931181056a3.png)

![image](https://cloud.githubusercontent.com/assets/6039130/11502183/9953bafe-9839-11e5-8568-25bbde661f0c.png)

**Comment by lgm42** [comment] 2015-12-01 13:45
Or something like that for example :

![image](https://cloud.githubusercontent.com/assets/6039130/11502261/f935581a-9839-11e5-9562-d148ea4889f0.png)

**Comment by tagliala** [comment] 2015-12-02 13:30
duplicate of #437, please +1 that request

closing here

**Closed by tagliala** 2015-12-02 13:30 UTC
