### ISSUE TITLE
Icon request: icon-circleci

### ISSUE THREAD

**Issue by felicianotech** [FortAwesome/Font-Awesome#10613] opened 2017-02-04 19:02 UTC
EPS version of logo: https://github.com/circleci/media/blob/master/presskit/logos/badge/logo-badge-grey.eps
SVG version of logo: https://github.com/circleci/media/blob/master/presskit/logos/badge/logo-badge-grey.svg

I'd like to use this on [CircleCI Docs](https://circleci.com/docs) and [CircleCI Discuss](https://discuss.circleci.com) (my domains) and potentially in cooperation with other companies and tooling in the greater devops space. Think GitLab, Docker, Yarn communities, etc.

Dupe: https://github.com/FortAwesome/Font-Awesome/issues/4351

I'm keeping this open, at least for now, since this is an official request plus this includes the official media files. Let me know how to proceed. Thank you.

**Comment by tagliala** [comment] 2017-02-04 19:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4351, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-04 19:23 UTC
