### ISSUE TITLE
Icon request: fa-netflix

### ISSUE THREAD

**Issue by OdarGM** [FortAwesome/Font-Awesome#13750] opened 2018-08-11 21:08 UTC
### What can it be used for?

Netflix's N icon

I know there is request about this #1395 but it's from `23 Jun 2013` and it's still not added so i am requesting again 😄 

### Example image (optional)

![Netflix logo](https://cdn.iconverticons.com/files/ico/d893c93854b4532a.ico?download=true)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-12 10:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1395, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-12 10:11 UTC

**Comment by tagliala** [comment] 2018-08-12 11:40
@OdarGM please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome and here: https://fontawesome.com/community/leaderboard/brands

**Comment by OdarGM** [comment] 2018-08-12 13:06
kk thanks
