### ISSUE TITLE
Icon request: fa-hiker

### ISSUE THREAD

**Issue by ddhines16** [FortAwesome/Font-Awesome#8603] opened 2016-02-18 09:10 UTC
Hi, 

I'm hoping for an icon of a hiker. I'm creating a webpage that will link to hiking trails in my town. Here is an example:
![hiker](https://cloud.githubusercontent.com/assets/17311698/13138479/5e97bfb0-d5dc-11e5-8b49-106eab47e7c8.jpg)

Thanks!

**Comment by tagliala** [comment] 2016-02-18 11:05
Duplicate of #2178, please +1 that request

closing here

**Closed by tagliala** 2016-02-18 11:05 UTC
