### ISSUE TITLE
New icon : Interac'

### ISSUE THREAD

**Issue by AlexandreBouille** [FortAwesome/Font-Awesome#12803] opened 2018-04-07 16:28 UTC
Interac payment 
http://interac.ca/en/

**Comment by tagliala** [comment] 2018-04-07 17:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4445, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-07 17:28 UTC
