### ISSUE TITLE
Icon request: icon-sandwich

### ISSUE THREAD

**Issue by jonpasquier** [FortAwesome/Font-Awesome#13488] opened 2018-07-06 10:06 UTC
### What can it be used for?

Could be used to indicate some place where you can buy some snacks

### Example image (optional)

![image](https://user-images.githubusercontent.com/4568003/42373339-e9d8c43a-8114-11e8-924e-02df1363e1f8.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-06 11:32
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9874, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-06 11:32 UTC
