### ISSUE TITLE
Brand request: add typescript brand icon.

### ISSUE THREAD

**Issue by Yasir-Khan22** [FortAwesome/Font-Awesome#19568] opened 2023-02-19 09:21 UTC
### Description

- We can use TypeScript icon in our personal or for building portfolio projects, whether it's a website, application, or other digital product. The TypeScript icon can be used to represent the TypeScript language or any TypeScript-related features or tools, which is helpful for communicating the use of TypeScript to other developers or users. 
- By including the TypeScript icon in the core of Font Awesome, it becomes a standard icon that is easily accessible and consistent across different projects, making it easier for developers to use and recognize.

### Official website

https://www.typescriptlang.org/

### Brand guidelines

https://en.wikipedia.org/wiki/TypeScript#/media/File:Typescript.svg

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2023-02-19 09:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11890, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-02-19 09:26 UTC
Labels: brand icon

**Comment by Yasir-Khan22** [comment] 2023-02-19 14:46
I searched for it on the font awesome website, but I didn't find anyone.
Can you tell me how to see all the issues before raising a PR or creating a new issue, I mean a specific PR or ISSUE has been resolved or not?

**Comment by tagliala** [comment] 2023-02-19 18:05
> Can you tell me how to see all the issues before raising a PR or creating a new issue,

Sure, just check the status

Open means that the request has not been fulfilled

![image](https://user-images.githubusercontent.com/556268/219966492-5a414fb8-423b-4714-8da2-df0c5b06d7f7.png)

If a request is closed, please check the comments and the label to see the reason
