### ISSUE TITLE
Icon Request: fa-pokeball

### ISSUE THREAD

**Issue by lambasoft** [FortAwesome/Font-Awesome#9685] opened 2016-08-01 07:36 UTC
I think it would be Awesome if you guys could add Pokemon related icons.
I would really rather use yours than custom made icons.

Thanks

**Comment by ryankane** [comment] 2016-08-01 12:05
Here are two raster images that I exported from vectors that were created based on the Pokémon GO game files.

Enjoy. :smile: 

# fa-pokeball

| Small  | Medium | Large | X-Large |
| :---: | :---: | :---: | :---: |
| ![fa-pokeball-16][] | ![fa-pokeball-32][] | ![fa-pokeball-64][] | ![fa-pokeball-128][]
| 16px | 32px | 64px | 128px |

![fa-pokeball][]

## Source

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     width="14.2222in" height="14.2222in"
     viewBox="0 0 1024 1024">
  <path id="pkmn-go-teamless"
        fill="#000000" stroke="none" stroke-width="1"
        d="M 923.54,448.05
           C 841.00,-21.00 193.00,-19.00 100.86,448.00
             100.86,448.00 312.00,448.00 312.00,448.00
             379.33,252.67 646.67,254.00 712.00,448.00
             712.00,448.00 923.54,448.05 923.54,448.05 Z
           M -648.00,-608.00M 516.00,380.21
           C 531.86,380.02 551.43,384.48 566.00,390.72
             582.32,397.71 596.09,406.87 608.83,419.28
             661.48,470.59 661.87,555.09 613.16,609.00
             602.28,621.04 588.54,631.46 574.00,638.73
             552.58,649.44 530.73,653.27 507.00,653.00
             495.22,652.86 480.20,649.70 469.00,646.00
             390.10,619.93 353.34,528.85 390.27,455.00
             405.22,425.10 431.73,400.92 463.00,389.06
             477.11,383.71 486.43,382.50 501.00,380.21
             501.00,380.21 516.00,380.21 516.00,380.21 Z
           M 923.54,575.95
           C 841.00,1045.00 193.00,1043.00 100.86,576.00
             100.86,576.00 312.00,576.00 312.00,576.00
             380.67,772.67 646.67,770.00 712.00,576.00
             712.00,576.00 923.54,575.95 923.54,575.95 Z
           M -648.00,1632.00" />
</svg>
```

# fa-pokemon-gym

| Small  | Medium | Large | X-Large |
| :---: | :---: | :---: | :---: |
| ![fa-pokemon-gym-16][] | ![fa-pokemon-gym-32][] | ![fa-pokemon-gym-64][] | ![fa-pokemon-gym-128][]
| 16px | 32px | 64px | 128px |

![fa-pokemon-gym][]

## Source

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     width="14.2222in" height="14.2222in"
     viewBox="0 0 1024 1024">
  <path id="pkmn-go-gym-arena"
        fill="#000000" stroke="none" stroke-width="1"
        d="M 123.33,411.01
           C 161.00,264.50 285.00,127.50 488.00,114.25
             488.00,114.25 488.00,138.81 488.00,138.81
             333.00,148.50 188.50,254.50 151.92,410.98
             151.92,410.98 123.33,411.01 123.33,411.01 Z
           M 900.67,411.01
           C 863.00,264.50 739.00,127.50 536.00,114.25
             536.00,114.25 536.00,138.81 536.00,138.81
             691.00,148.50 835.50,254.50 872.08,410.98
             872.08,410.98 900.67,411.01 900.67,411.01 Z
           M 514.00,416.21
           C 525.50,416.02 540.54,419.00 551.00,423.77
             566.40,430.80 579.76,440.40 590.10,454.00
             619.35,492.46 616.21,547.68 582.00,582.00
             573.13,590.90 566.36,595.96 555.00,601.36
             539.67,608.66 525.89,611.19 509.00,611.00
             502.08,610.92 494.70,609.56 488.00,607.87
             431.94,593.80 400.66,532.83 421.06,479.00
             431.03,452.71 452.43,431.18 479.00,421.70
             486.89,418.88 494.78,417.62 503.00,416.21
             503.00,416.21 514.00,416.21 514.00,416.21 Z
           M 113.00,499.00
           C 113.00,499.00 112.99,475.00 112.99,475.00
             123.98,475.00 342.06,475.00 342.06,475.00
             370.00,379.68 441.49,340.19 510.36,339.82
             588.59,339.40 664.40,389.74 680.72,474.99
             680.72,474.99 911.02,474.98 911.02,474.98
             911.02,474.98 911.02,499.00 911.02,499.00
             911.02,499.00 658.00,499.00 658.00,499.00
             652.79,418.79 583.25,366.33 512.00,366.33
             448.69,366.34 383.55,410.80 369.52,474.59
             367.22,482.96 365.74,490.75 365.00,499.00
             365.00,499.00 113.00,499.00 113.00,499.00 Z
           M 373.61,561.96
           C 392.76,620.35 451.15,658.63 510.50,659.50
             570.11,660.38 630.68,623.58 650.46,561.88
             650.46,561.88 908.44,561.99 908.44,561.99
             886.44,723.60 769.26,870.98 586.81,905.19
             332.89,952.80 144.95,770.26 115.41,562.04
             115.41,562.04 373.61,561.96 373.61,561.96 Z" />
</svg>
```

  [fa-pokeball-16]: https://cloud.githubusercontent.com/assets/1094151/17293399/12e231b8-57be-11e6-8f5f-f58d5c6729a8.png
  [fa-pokeball-32]: https://cloud.githubusercontent.com/assets/1094151/17293406/18598a6a-57be-11e6-9ccf-aa54009b1b5c.png
  [fa-pokeball-64]: https://cloud.githubusercontent.com/assets/1094151/17293408/1ae62356-57be-11e6-88d3-c0d6c421b1bb.png
  [fa-pokeball-128]: https://cloud.githubusercontent.com/assets/1094151/17293412/1d222a2a-57be-11e6-9055-87e4e9aed96d.png
  [fa-pokeball]: https://cloud.githubusercontent.com/assets/1094151/17293250/366eade2-57bd-11e6-99e9-237913b2d758.png

  [fa-pokemon-gym-16]: https://cloud.githubusercontent.com/assets/1094151/17293417/2286dd3a-57be-11e6-9ca7-25bc5ff3f509.png
  [fa-pokemon-gym-32]: https://cloud.githubusercontent.com/assets/1094151/17293420/251dc4b4-57be-11e6-8476-a2b525cf68d6.png
  [fa-pokemon-gym-64]: https://cloud.githubusercontent.com/assets/1094151/17293421/27d0181a-57be-11e6-87d5-8c908cccb991.png
  [fa-pokemon-gym-128]: https://cloud.githubusercontent.com/assets/1094151/17293424/299096ac-57be-11e6-9789-72210a138178.png
  [fa-pokemon-gym]: https://cloud.githubusercontent.com/assets/1094151/17292806/2bc642a4-57ba-11e6-88ff-52e425db9de6.png

**Comment by ryankane** [comment] 2016-08-01 13:23
I created this from scratch referencing the menu icon in the game.

# fa-pokeball-alt

| Small  | Medium | Large | X-Large |
| :---: | :---: | :---: | :---: |
| ![fa-pokeball-alt-16][] | ![fa-pokeball-alt-32][] | ![fa-pokeball-alt-64][] | ![fa-pokeball-alt-128][]
| 16px | 32px | 64px | 128px |

![fa-pokeball-alt][]

## Source

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     width="14.2222in" height="14.2222in"
     viewBox="0 0 1024 1024">
  <path id="pkmn-go-menu"
        fill="#000000" stroke="none" stroke-width="1"
        d="M 512.00,359.18
           C 512.00,359.18 512.00,359.18 512.00,359.18
             596.40,359.18 664.81,427.60 664.82,512.00
             664.82,512.00 664.82,512.00 664.82,512.00
             664.82,596.40 596.40,664.81 512.00,664.82
             512.00,664.82 512.00,664.82 512.00,664.82
             427.60,664.82 359.19,596.40 359.18,512.00
             359.18,512.00 359.18,512.00 359.18,512.00
             359.18,427.60 427.60,359.18 512.00,359.18
             512.00,359.18 512.00,359.18 512.00,359.18
             512.00,359.18 512.00,359.18 512.00,359.18 Z
           M 512.00,410.12
           C 455.73,410.12 410.12,455.73 410.12,512.00
             410.12,568.27 455.73,613.88 512.00,613.88
             568.27,613.88 613.88,568.27 613.88,512.00
             613.88,455.73 568.27,410.12 512.00,410.12
             512.00,410.12 512.00,410.12 512.00,410.12 Z
           M 806.16,217.84
           C 884.17,295.86 928.00,401.67 928.00,512.00
             928.00,622.33 884.17,728.14 806.16,806.16
             728.14,884.17 622.33,928.00 512.00,928.00
             401.67,928.00 295.86,884.17 217.84,806.16
             139.83,728.14 96.00,622.33 96.00,512.00
             96.00,401.67 139.83,295.86 217.84,217.84
             295.86,139.83 401.67,96.00 512.00,96.00
             622.33,96.00 728.14,139.83 806.16,217.84 Z
           M 332.02,512.00
           C 332.02,512.00 138.45,512.00 138.45,512.00
             138.45,611.07 177.81,706.09 247.86,776.14
             317.91,846.19 412.93,885.55 512.00,885.55
             611.07,885.55 706.09,846.19 776.14,776.14
             846.19,706.09 885.55,611.07 885.55,512.00
             885.55,512.00 885.55,512.00 885.55,512.00
             885.55,512.00 691.98,512.00 691.98,512.00
             691.98,412.60 611.40,332.02 512.00,332.02
             412.60,332.02 332.02,412.60 332.02,512.00 Z" />
</svg>
```

  [fa-pokeball-alt-16]: https://cloud.githubusercontent.com/assets/1094151/17295231/1f9863ae-57c9-11e6-9250-d4cbfe806c0e.png
  [fa-pokeball-alt-32]: https://cloud.githubusercontent.com/assets/1094151/17295233/2106553e-57c9-11e6-8af5-01f25baa3276.png
  [fa-pokeball-alt-64]: https://cloud.githubusercontent.com/assets/1094151/17295235/2447ef96-57c9-11e6-98b0-b6284f65abed.png
  [fa-pokeball-alt-128]: https://cloud.githubusercontent.com/assets/1094151/17295239/25b8fd02-57c9-11e6-9f5a-8791d3428e7b.png
  [fa-pokeball-alt]: https://cloud.githubusercontent.com/assets/1094151/17295242/2748a582-57c9-11e6-9fa7-91a8c8956645.png

**Comment by tryton-vanmeer** [comment] 2016-08-01 19:20
+1

**Comment by apsaraaruna** [comment] 2016-08-03 13:16
good idea.. thanks

**Comment by achillesrasquinha** [comment] 2016-08-06 07:56
+1

**Comment by DoktorJ** [comment] 2016-08-10 21:35
I like this one; specifically, I like @ryankane 's "fa-pokeball-alt". Gyms actually have a different icon:

![PokeGym](http://ih0.redbubble.net/image.50411477.7401/sticker,375x360.u3.png)

If someone doesn't beat me to it, I'll try to make an SVG of this in the next day or so

**Comment by ryankane** [comment] 2016-08-11 17:54
@DoktorJ That gym logo that I created was based on the Gym "Arena Glass" in the game files.

![t_gym_arena_glass](https://cloud.githubusercontent.com/assets/1094151/17598069/c82961bc-5fc6-11e6-874f-dd37ca517870.png)

Also, I have created some vectors for all three gyms.

|Instict|Mystic|Valor|
|---|---|---|
|![gym_marker_yellow_sm](https://cloud.githubusercontent.com/assets/1094151/17598216/6c780764-5fc7-11e6-9419-4775b9cf0704.png)|![gym_marker_blue_sm](https://cloud.githubusercontent.com/assets/1094151/17598215/6c7762be-5fc7-11e6-93cc-d31777ef9d79.png)|![gym_marker_red_sm](https://cloud.githubusercontent.com/assets/1094151/17598217/6c7801d8-5fc7-11e6-9874-fa1f57e46a6d.png)

Here is my SVG data:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     width="500" height="500" viewBox="0 0 500 500">
  <g id="pokemon-gym">
    <path id="main-outline"
          fill="#FFFFFF" stroke="#000000" stroke-width="0.5"
          d="M 436.23,45.87
             C 368.38,181.94 300.54,318.02 232.70,454.09
               220.22,407.49 207.73,360.90 195.25,314.31
               195.25,314.31 193.58,308.11 193.58,308.11
               193.58,308.11 186.21,307.90 181.55,307.39
               123.78,303.42 71.85,256.86 64.28,199.53
               52.97,141.73 89.52,81.34 143.38,59.74
               201.12,35.14 273.40,61.81 303.38,116.46
               343.34,95.59 383.52,73.83 423.57,52.62
               423.57,52.62 436.23,45.87 436.23,45.87 Z" />
    <g id="ball-outline">
      <path id="ball-outline-top"
            fill="#f71208" stroke="none"
            d="M 286.17,115.42
               C 286.17,115.42 226.76,147.01 226.76,147.01
                 217.65,136.88 204.68,131.08 191.06,131.05
                 164.45,131.05 142.89,152.62 142.89,179.22
                 142.91,183.13 143.40,187.03 144.36,190.82
                 144.36,190.82 84.91,222.44 84.91,222.44
                 79.30,208.72 76.40,194.04 76.38,179.22
                 76.38,115.88 127.72,64.54 191.06,64.54
                 229.26,64.60 264.92,83.67 286.17,115.42 Z" />
      <path id="ball-outline-bottom"
            fill="#f71208" stroke="none"
            d="M 236.60,415.44
               C 236.60,415.44 203.82,293.13 203.82,293.13
                 199.58,293.62 195.32,293.88 191.06,293.90
                 152.71,293.84 116.92,274.61 95.71,242.67
                 95.71,242.67 155.06,211.11 155.06,211.11
                 164.18,221.43 177.28,227.36 191.06,227.38
                 217.66,227.38 239.22,205.82 239.22,179.22
                 239.20,175.16 238.67,171.12 237.64,167.20
                 237.64,167.20 297.06,135.60 297.06,135.60
                 297.06,135.60 404.70,78.26 404.70,78.26
                 404.70,78.26 236.60,415.44 236.60,415.44 Z
               M 247.66,172.36
               C 253.14,210.38 212.71,247.20 175.39,234.40
                 167.33,232.08 159.76,228.01 153.47,222.44
                 138.82,230.27 123.94,238.06 109.43,245.92
                 133.08,275.48 173.50,290.22 210.66,283.11
                 220.18,318.66 229.72,354.21 239.24,389.75
                 239.24,389.75 383.75,99.91 383.75,99.91
                 383.75,99.91 247.66,172.36 247.66,172.36 Z" />
      <path id="ball-outline-center"
            fill="#f71208" stroke="none"
            d="M 191.06,144.82
               C 210.06,144.82 225.46,160.22 225.46,179.22
                 225.46,198.22 210.06,213.62 191.06,213.62
                 172.05,213.62 156.65,198.22 156.65,179.22
                 156.65,160.22 172.05,144.82 191.06,144.82
                 191.06,144.82 191.06,144.82 191.06,144.82 Z
               M 191.06,153.99
               C 177.12,153.99 165.83,165.29 165.83,179.22
                 165.83,193.15 177.12,204.45 191.06,204.45
                 204.99,204.45 216.28,193.15 216.28,179.22
                 216.28,165.29 204.99,153.99 191.06,153.99
                 191.06,153.99 191.06,153.99 191.06,153.99 Z" />
    </g>
  </g>
</svg>
```

**Comment by tagliala** [comment] 2016-08-17 09:36
Sorry, closing here

Duplicate of #6799 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-17 09:36 UTC
Labels: new icon, web application icons

**Comment by tagliala** [comment] 2016-08-17 09:55
@ryankane please post your `.svg`s on #6799
