### ISSUE TITLE
Icon request: icon-currency-uah

### ISSUE THREAD

**Issue by webknjaz** [FortAwesome/Font-Awesome#13212] opened 2018-05-25 11:57 UTC
### What can it be used for?

* Ukrainian Hryvnia currency.
* It's sign is: `₴`.
* The code is .`UAH.
* It will be used to show the currency sign for money value in hryvnia.

### Example image (optional)

![](https://image.flaticon.com/icons/svg/66/66230.svg)
<details>
<summary>More UAH ₴ sign examples</summary>
<a href="https://commons.wikimedia.org/wiki/%D0%93%D1%80%D0%B8%D0%B2%D0%BD%D1%8F"><img src="https://upload.wikimedia.org/wikipedia/commons/4/46/Hryvnia_symbol.svg" title="UAH ₴" alt="UAH ₴ sign"></a>
<img src="https://poohitan.com/stuff/uah/uahsign.png" title="UAH ₴" alt="UAH ₴ signs">
</details>

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate, which is open: authors of previous requests gave up waiting, while having **lots of endorsements**, e.g. #1451 (115 comments), #7690 (+1), #8341 (+1), #8341 (+1), #4549 (+4), #9827 (+1), #4197 (+1), #3210 (+1)
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-05-25 12:35
@webknjaz #1451 reopened, but if the author is going to close again that request, we have no other choice of starting a new one

Meanwhile, closing here as a duplicate of #1451

**Closed by tagliala** 2018-05-25 12:35 UTC
