### ISSUE TITLE
Icon Request: fa-pregnant

### ISSUE THREAD

**Issue by LysOot** [FortAwesome/Font-Awesome#12145] opened 2018-01-22 11:54 UTC
Can be used for:

Photography page, maternity shoot
Medical website
![pregnant_woman-512](https://user-images.githubusercontent.com/35690066/35219527-4d8dad48-ff73-11e7-9578-638b46387683.png)
![010_-_pregnancy_gestation_childbearing-512](https://user-images.githubusercontent.com/35690066/35219532-4ee08288-ff73-11e7-9f9c-0e874ea31ec5.png)

**Comment by tagliala** [comment] 2018-01-22 12:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1819, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-22 12:55 UTC

**Comment by Chris-Flash** [comment] 2020-06-04 10:08
Hello, how do i add just the pregnancy icon into my fa-icon list on my offline web page..would like to add it using the fa-<icon name> line not img tag

Thanks

**Comment by tagliala** [comment] 2020-06-04 10:33
Hi @Chris-Flash , please take a look at our customization guide: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
