### ISSUE TITLE
Icon request: icon-steemit

### ISSUE THREAD

**Issue by gabchik** [FortAwesome/Font-Awesome#11510] opened 2017-09-10 11:27 UTC
Steemit is a wonderful decentralized social network, which works with a steem crypto currency. The authors are rewarded for their original content with an upvote, which is worth a certain amount of steem, depending on the power of the voting user. I really want to put a social icon for steemit in my site, so it will be appreciated. 
https://pbs.twimg.com/profile_images/730961175182073860/AY9SsNuk.jpg
This is how the logo looks like. 

It will be appreciated to have it done :)
Thanks~

**Comment by tagliala** [comment] 2017-09-10 11:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10703, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-10 11:39 UTC
