### ISSUE TITLE
Icon request: icon-hydrant

### ISSUE THREAD

**Issue by MimisK13** [FortAwesome/Font-Awesome#7192] opened 2015-08-10 15:02 UTC
Water hydrant 
![kiknaonat](https://cloud.githubusercontent.com/assets/10620005/9174653/e2c005e8-3f89-11e5-9d36-9e4b9ce83f23.jpg)

**Comment by tagliala** [comment] 2015-08-10 16:43
duplicate of #4810, please +1 that request

closing here

**Closed by tagliala** 2015-08-10 16:43 UTC
