### ISSUE TITLE
Icon Request: fa-whistle

### ISSUE THREAD

**Issue by AlphaMAB** [FortAwesome/Font-Awesome#11041] opened 2017-05-09 11:41 UTC
I have a project that records games and there score and we want to place a whistle icon.
Now we are using an image but it is annoying and difficult to manipulate (ex: color) 

![whistle_icon](https://cloud.githubusercontent.com/assets/28563703/25849058/9631f492-34c5-11e7-8155-30b930c71a93.png)

Thank you.

**Comment by tagliala** [comment] 2017-05-09 11:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #984, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-09 11:47 UTC
