### ISSUE TITLE
Icon Request: fa-juice

### ISSUE THREAD

**Issue by sdf1992** [FortAwesome/Font-Awesome#11781] opened 2017-11-21 17:51 UTC
Hello i need a juice/smoothies/milkshake icon for my website

**Comment by sdf1992** [comment] 2017-12-06 15:48
i post you my handmade icon
![juice](https://user-images.githubusercontent.com/33875709/33670431-5572400c-daa5-11e7-82a9-35a50ff32a8b.jpg)

**Comment by tagliala** [comment] 2017-12-06 18:36
@sdf1992 thanks for the example

I think this is a duplicate of #3068

**Comment by tagliala** [comment] 2019-03-20 15:21
paper cup: #3068

for juice box, please use #14782

**Closed by tagliala** 2019-03-20 15:21 UTC
