### ISSUE TITLE
Icon Request: partially filled signal

### ISSUE THREAD

**Issue by romain-garby** [FortAwesome/Font-Awesome#12678] opened 2018-03-23 00:25 UTC
It could be good to have differently variation of current `fa-signal` icons with different filling like this:
<img src="https://user-images.githubusercontent.com/6855347/37805050-bbf38e94-2e9c-11e8-8e2f-3c4e08609f5d.png" width="200" />
with all different level of filling (none, 1 bar, 2 bars, 3 bars, 4 bars, full).

Could also be nice to have a 3 bars version.

**Use for:**
- progress
- gradation

**Comment by tagliala** [comment] 2018-04-06 14:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1870 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 14:54 UTC
