### ISSUE TITLE
Icon Request: Orbiting Satellite

### ISSUE THREAD

**Issue by schowes** [FortAwesome/Font-Awesome#11104] opened 2017-05-22 22:14 UTC
Thank you so much for all your work!

I'd like to specifically request an orbiting satellite icon. Many of the existing requests for "satellite" seem to be more for a dish-style icon, while I need an orbiting style. 

See: 
![satellite-icon-8](https://cloud.githubusercontent.com/assets/4838357/26330545/7000332e-3f1a-11e7-9481-a1cc5c0b0368.png)

**Comment by tagliala** [comment] 2017-05-23 10:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2404, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-23 10:37 UTC
