### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by jstaffeld** [FortAwesome/Font-Awesome#9252] opened 2016-05-22 03:08 UTC
Icon request: Javascript - J5

**Comment by tagliala** [comment] 2016-05-22 11:05
Duplicate of #1711 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-22 11:05 UTC
