### ISSUE TITLE
Icon request: fa-devpost

### ISSUE THREAD

**Issue by xTEddie** [FortAwesome/Font-Awesome#7904] opened 2015-11-17 19:07 UTC
http://edwardtran.noip.me/img/devpost.jpg

This icon can be used for all participants of hackathons. It is the website where hackers submit their projects.

**Comment by tagliala** [comment] 2015-11-17 23:10
duplicate of #5003, please +1 that request

closing here

**Closed by tagliala** 2015-11-17 23:10 UTC
