### ISSUE TITLE
Icon request: stackblitz & codesandbox

### ISSUE THREAD

**Issue by sabine-xuaitsep** [FortAwesome/Font-Awesome#18716] opened 2022-02-18 00:05 UTC
### Usage
- _Same way as 'f1cb' fa-brands fa-codepen_
- _To illustrate links to accounts, etc._

### Example
- <img src="https://user-images.githubusercontent.com/77670450/154588639-1ca1cbda-6253-49dc-87b9-f5537ecade92.png" width="25" height="25" /><img src="https://user-images.githubusercontent.com/77670450/154588635-41dceaf5-0c75-4fd6-b49c-67d3d82dcc53.png" width="25" height="25" /> _PNG [found on the web]_ 
- <img src="https://user-images.githubusercontent.com/77670450/154588886-3725596d-aece-49f5-b25d-d6bb6081e3f8.svg" width="25" height="25" /><img src="https://user-images.githubusercontent.com/77670450/154588889-7a08232e-abbc-424c-ba71-0283562c323d.svg" width="25" height="25" /> _SVG [made online, am not skilled in design]_

### Checklist
- [x] _No entry found, unless I make a mistake_

**Comment by tagliala** [comment] 2022-02-19 18:34
Hi!

Thanks for being part of the Font Awesome Community.

Stackblitz is a duplicate of #14966, please add a 👍 reaction to that request.
Codesandbox is a duplicate of #14949, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

All duplicates, closing here

**Closed as completed by tagliala** 2022-02-19 18:34 UTC
