### ISSUE TITLE
Icon Request: Line.en Icon

### ISSUE THREAD

**Issue by kamijoutouma** [FortAwesome/Font-Awesome#6496] opened 2015-05-17 09:41 UTC
http://line.me/logo/en

I can't really do this for you since they have guidelines.

Would like to use this icon as a way to list anything related to line.

@tagliala @davegandy

**Comment by tagliala** [comment] 2015-05-17 11:38
dupe of #2631, please +1 that request

closing here

**Closed by tagliala** 2015-05-17 11:38 UTC
