### ISSUE TITLE
icon-request : fa-dub

### ISSUE THREAD

**Issue by Kikidy-cam** [FortAwesome/Font-Awesome#10255] opened 2016-11-21 15:13 UTC
Requesting an icon for each of Dub and Sub.
I would use the icon as a identifier of whether an anime has been dubbed or subbed, both in a table and in the upper right corner of a information box for said anime.
The icon only needs to have the letters DUB or SUB in a dark rectangle, like git-square or cc-visa.

**Comment by tagliala** [comment] 2016-11-21 15:37
Subtitles is a duplicate of #5754, please 👍 that request and post there your idea

Leaving this open as `icon-dub`

**Comment by Crissov** [comment] 2016-12-15 22:21
Related Unicode/ARIB characters:

- 🈑 U+1F211 SQUARED CJK UNIFIED IDEOGRAPH-5B57 = close-captioned broadcasting
- 🈥 U+1F225 SQUARED CJK UNIFIED IDEOGRAPH-5439 = dubbed version

**Comment by sensibleworld** [comment] 2024-07-11 20:18
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 20:18 UTC
Labels: new icon, web application icons (legacy category), Declined
