### ISSUE TITLE
Icon request: icon-line-app

### ISSUE THREAD

**Issue by mcparrish** [FortAwesome/Font-Awesome#9131] opened 2016-05-05 18:28 UTC
Looking to get the logo for the LINE app
![line](https://cloud.githubusercontent.com/assets/1039589/15052839/7e1d1c8a-12b4-11e6-9d4e-06c53951cf3c.png)

**Comment by aethior** [comment] 2016-05-05 20:49
Hi @mcparrish,

This request is duplicate of #2631. Please +1 that.

Regards.

**Closed** 2016-05-05 23:04 UTC
