### ISSUE TITLE
Icon request: icon-diameter

### ISSUE THREAD

**Issue by r-man** [FortAwesome/Font-Awesome#13841] opened 2018-08-29 19:26 UTC
### What can it be used for?

The icon can be used to display measurement results

### Example image

![default](https://user-images.githubusercontent.com/1829702/44810483-7ccf9800-abda-11e8-84e3-2ae34a28e577.png)

### Icon request checklist

- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name
- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image
- [x] The request is for a concrete object

**Comment by tagliala** [comment] 2018-08-29 19:30
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #5852?

**Comment by r-man** [comment] 2018-08-29 19:38
Yes, these symbols are identical

**Comment by tagliala** [comment] 2018-08-29 19:56
Please add a 👍 reaction to #5852

**Closed by tagliala** 2018-08-29 19:56 UTC
Labels: waiting for feedback
