### ISSUE TITLE
Icon request: cracked-egg

### ISSUE THREAD

**Issue by ChristiaanDev** [FortAwesome/Font-Awesome#14817] opened 2019-03-26 09:47 UTC
### What can it be used for?

As we have fa-egg, it only would make sense to also have an icon that is visibly cracked.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by MrUpsidown** [comment] 2022-09-27 13:26
Maybe take this icon request as an opportunity to redesign the fa-egg icon that **really** doesn't look like an egg...

**Comment by tagliala** [comment] 2022-09-27 13:47
Hi @MrUpsidown feel free to open a new request, you can use our [bug report template for any other issue](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=101_other_bug_report.yml&title=Bug%3A+)

Please also provide feedback on why do you think the current design is wrong and how it could be implemented (I guess it's the upper part that should be slightly more rounded)

**Comment by MrUpsidown** [comment] 2022-09-28 11:10
Indeed, it's the upper part or say, the overall shape that is IMO too _triangular_. Thanks.

**Comment by sensibleworld** [comment] 2024-07-11 19:07
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/19996)

**Closed by sensibleworld** 2024-07-11 19:07 UTC
Labels: new icon, food-beverage (category), Duplicate
