### ISSUE TITLE
Icon request: fa-replit

### ISSUE THREAD

**Issue by newtontriumphant** [FortAwesome/Font-Awesome#17380] opened 2020-11-08 23:10 UTC
**USES:**
I am requesting the (brand) icon **fa-replit**.This Icon would be the brand image of [repl.it](https://repl.it). Replit is a major coding connection network with thousands of users.

**Example images:**
![Image of repl.it](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTHLcgTtRwuHZveaMlFnKHWpA7RGxU_N7stUA&usqp=CAU)
![Alternative image of repl.it](https://lh3.googleusercontent.com/egU5ENhlpxatRHQUQ1xG6oM55ZCQttXcg-RuuXXjsUwOdeE2kAQDsnaEClJdznI-0sEGSLV5=w128-h128-e365-rj-sc0x00ffffff)

I would really appreciate it's publishing!

-@newtontriumphant

**Comment by tagliala** [comment] 2020-11-09 08:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14758, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-11-09 08:39 UTC

**Comment by newtontriumphant** [comment] 2020-11-09 20:31
Dear @tagliala,

Thanks so much! I upvoted it!

-@newtontriumphant
