### ISSUE TITLE
fa-temperature

### ISSUE THREAD

**Issue by RedderKaz** [FortAwesome/Font-Awesome#7555] opened 2015-09-28 12:05 UTC
I didnt find anythig to attach to a temperature.

my suggestion:

![fa-temperature](https://cloud.githubusercontent.com/assets/14872043/10134897/f04ba420-65e9-11e5-8624-271c94e1d425.png)

**Comment by tagliala** [comment] 2015-09-28 13:46
duplicate of #720 , scheduled for 5.0.0 but please +1 that request

closing here

**Closed by tagliala** 2015-09-28 13:46 UTC
