### ISSUE TITLE
Icon request: airport

### ISSUE THREAD

**Issue by GordonWerner** [FortAwesome/Font-Awesome#17076] opened 2020-08-24 19:19 UTC
**What can it be used for?**
An airport with a control tower is an important icon to have but is missing here.

**Example image (optional)**
![678687_building_512x512](https://user-images.githubusercontent.com/5200015/91086564-f18c1000-e603-11ea-8fa6-9b72d9bdacba.png)

**Icon request checklist**
- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-08-25 19:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1976, please add a 👍 reaction to that request and post there your example.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-08-25 19:41 UTC
