### ISSUE TITLE
Icon request: lacrosse

### ISSUE THREAD

**Issue by dletter** [FortAwesome/Font-Awesome#17881] opened 2021-05-06 15:44 UTC
**What can it be used for?**
Use for icons to represent the sport of lacrosse

**Example image (optional)**
https://iconscout.com/icon/lacrosse-stick-2
Could also have a lacrosse player with stick type of icon.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

NOTE: This is part of a "broad" request to have a more "full" representation of all sports... many sports are represented in font awesome, but, there are some somewhat glaring holes...
(A) Lacrosse (the major one missing I can see that doesn't fall in the other two more broad categories below)
(B) "Olympic sport" icons (various specific winter/summer sports missing, looking up existing lists of Olympic sport icons that are commonly out there would be a good starting point on what FA should be including)
(C) "X-Games" type sports (Skateboarding, surfing, snowboarding, roller skating/blading, etc)

**Comment by tagliala** [comment] 2021-05-06 16:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14106, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-05-06 16:37 UTC

**Comment by tagliala** [comment] 2021-05-06 18:46
> although can you address the more "broad" "missing sports" issue I brought up.
> 
> I mean, one could make a request for 20-30 different sports, but, it is more of a broad "project" of an area that should be added.

Our contributing guidelines do not allow requests for a set in the free repo. They are hard to manage and a single request can easily include hundred of icons, so we prefer individual requests

Said so, **a lot** of sports icon are coming with FA6, available in private alpha for our Pro Customers and soon to be released in public beta. I don't know how many icons will be part of the free repo.

`lacrosse-stick` and `lacrosse-stick-ball` are two of those

![image](https://user-images.githubusercontent.com/556268/117349712-010a6b00-aeac-11eb-9f1c-cd18797f65c5.png)
