### ISSUE TITLE
Request: power pole icon

### ISSUE THREAD

**Issue by andig** [FortAwesome/Font-Awesome#16634] opened 2020-05-14 16:29 UTC
Something like this:

<img width="60" alt="Screenshot 2020-05-14 at 18 28 36" src="https://user-images.githubusercontent.com/184815/81960118-c1020680-9610-11ea-9df2-1d0bc6383066.png">

**Comment by tagliala** [comment] 2020-05-14 16:40
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2766, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-14 16:40 UTC
