### ISSUE TITLE
Icon Request: fa-aparat

### ISSUE THREAD

**Issue by masudafsar** [FortAwesome/Font-Awesome#5331] opened 2015-01-03 22:01 UTC
Aparat.com is a video sharing service like youtube for perisan.
LOGO file is here: http://www.aparat.com/logo

**Comment by masudafsar** [comment] 2015-01-03 22:05
add this logo:
![](http://static.aparat.com/public/images/logo/aparat_logo_color_black_64.png)

**Comment by mikethedj4** [comment] 2015-01-04 01:44
After reading a few of the icon requests on here I know Dave is not accepting pull requests containing icons.

If you need this icon, you should consider a custom build of fontawesome

Take a look at:
https://fonticons.com/ (by Dave - adding custom icons is not possible in the free tier)
http://fontello.com/
http://icomoon.io/app/#/select (My personal favorite)
http://fontastic.me/

**Comment by tagliala** [comment] 2015-01-04 10:04
duplicate of #5204, please +1 that request

closing here

@mikethedj4 thanks

**Closed by tagliala** 2015-01-04 10:04 UTC

**Comment by keshvarifar** [comment] 2016-05-15 11:44
@tagliala : hi dear
You close this request and we have open request in #5204 , please done our req.
thanks

**Comment by tagliala** [comment] 2016-05-15 21:24
@keshvarifar please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by se7en-team** [comment] 2023-08-15 11:50
add this logo please
http://www.aparat.com/logo
fab fa-aparat

**Comment by MahdiAhazan** [comment] 2024-01-06 13:08
add please!

**Comment by abbasEbadian** [comment] 2025-01-09 05:58
Add please!
