### ISSUE TITLE
Icon Request: fa-icon-Emacs

### ISSUE THREAD

**Issue by ekadhanda** [FortAwesome/Font-Awesome#8658] opened 2016-02-26 09:28 UTC
I use a window manager and keep my text editor on the 2nd desktop at all times. I would like to rice it with an Emacs icon. I have already assigned font awesome icons for my Chrome desktop and Terminal desktop. 
![2000px-emacsicon svg](https://cloud.githubusercontent.com/assets/12080372/13348405/9cc83cf4-dc73-11e5-8050-e1d5ed69bcb8.png)

**Comment by tagliala** [comment] 2016-02-26 10:09
duplicate of #7907, please +1 that request

closing here

**Closed by tagliala** 2016-02-26 10:09 UTC
