### ISSUE TITLE
Icon request: fa-sun-full / fa-bacon

### ISSUE THREAD

**Issue by marlonluft** [FortAwesome/Font-Awesome#10096] opened 2016-10-20 18:34 UTC
Hello, i'm looking for two specific icons, can you create a sun icon and a bacon icon?

![bacon](https://cloud.githubusercontent.com/assets/10707753/19572888/cef8f5ae-96e2-11e6-8611-3820107cd88b.png)
![sun](https://cloud.githubusercontent.com/assets/10707753/19572889/ceffcd16-96e2-11e6-9f1c-ffa58d559463.PNG)

**Comment by tagliala** [comment] 2016-10-21 09:50
Duplicate of #8263 and #5700, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-21 09:50 UTC
