### ISSUE TITLE
Icon request: customs

### ISSUE THREAD

**Issue by schulzrinne** [FortAwesome/Font-Awesome#18758] opened 2022-02-27 16:52 UTC
Customs officer or location, commonly found in airports or border crossings. See, for example, https://www.symbols.com/symbol/customs.

**Comment by tagliala** [comment] 2022-02-27 16:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2353, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-02-27 16:56 UTC
