### ISSUE TITLE
fa-islamic

### ISSUE THREAD

**Issue by waelr29** [FortAwesome/Font-Awesome#12599] opened 2018-03-14 08:44 UTC
### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-03-14 09:18
Hi!

Thanks for being part of the Font Awesome Community.

Please provide an example, because this could be a duplicate of #9371

We are discussing about religions here: #2088

**Comment by vedranmiletic** [comment] 2018-09-20 10:46
Is this solved now? https://fontawesome.com/icons?d=gallery&c=religion

**Comment by tagliala** [comment] 2018-09-20 10:49
I think it is

Anyway... no feedback, closing here

**Closed by tagliala** 2018-09-20 10:49 UTC
Labels: waiting for feedback
