### ISSUE TITLE
Icon Request: fa-java

### ISSUE THREAD

**Issue by RichardAlan** [FortAwesome/Font-Awesome#2726] opened 2014-01-11 10:57 UTC
Would love to have available an icon for the Java languge. Something similar to the one here:

https://weblogs.java.net/blog/kcpeppe/archive/2013/12/11/case-study-jvm-hotspot-flags

or 

http://www.oracle.com/us/technologies/java/overview/index.html

**Comment by admix** [comment] 2015-07-14 16:13
+1

**Comment by TheChen5** [comment] 2015-07-31 17:33
Dupe of #386 
:mag:before:heavy_plus_sign:
@tagliala this should be closed

**Comment by tagliala** [comment] 2015-09-14 06:28
closing here as a duplicate of #386

**Closed by tagliala** 2015-09-14 06:28 UTC
Labels: brand icons, new icon

**Comment by rodrigorrch** [comment] 2017-08-03 20:14
+1
