### ISSUE TITLE
Icon request: icon-crown

### ISSUE THREAD

**Issue by dekonkwehonwe** [FortAwesome/Font-Awesome#12333] opened 2018-02-12 14:03 UTC
Crown icon - use for Royalty programs etc.

![image](https://user-images.githubusercontent.com/31400131/36100123-da5c9a22-100d-11e8-9d50-ecb36337475c.png)
![image](https://user-images.githubusercontent.com/31400131/36100169-06d75ccc-100e-11e8-9f69-9e97b22a8c5e.png)

**Comment by tagliala** [comment] 2018-02-12 20:18
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #486 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-12 20:18 UTC
