### ISSUE TITLE
Icon request: ghost.js

### ISSUE THREAD

**Issue by ewliang** [FortAwesome/Font-Awesome#18435] opened 2021-11-12 18:54 UTC
**What can it be used for?**
Ghost.js is a javascript-based blogging platform. It can be used as an alternative to Wordpress. Ghost.js supports creating themes just like Wordpress themes so I think it is worth considering as part of your icon list. I also really need this. It would be great if you included it in your next update. Thank you.

Here is a link to their official logos page. [https://ghost.org/docs/logos/](https://ghost.org/docs/logos/)

**Comment by tagliala** [comment] 2021-11-12 19:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2554, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-11-12 19:28 UTC
