### ISSUE TITLE
New icon for eID-card 

### ISSUE THREAD

**Issue by stefankellens** [FortAwesome/Font-Awesome#8450] opened 2016-01-29 13:35 UTC
Hello,

I would like to request a new icon for an eID-card.

eID = electronic ID

Thanks

**Comment by stefankellens** [comment] 2016-01-29 13:40
Now we are using : 
![2016-01-29_11h55_26_grey](https://cloud.githubusercontent.com/assets/16957489/12676966/11e09408-c696-11e5-8c70-8ebf56fd9845.png)

Maybe this can be used as example

Greetings
Stefan

**Comment by tagliala** [comment] 2016-01-29 15:11
duplicate of #825 , please +1 that request

closing here

**Closed by tagliala** 2016-01-29 15:11 UTC
