### ISSUE TITLE
icon request - fire department

### ISSUE THREAD

**Issue by adriandquilang** [FortAwesome/Font-Awesome#8278] opened 2016-01-06 16:38 UTC
may i request for the following icons:
![firemansymbol](https://cloud.githubusercontent.com/assets/12716989/12147989/def031aa-b4d6-11e5-8d25-550907af5149.jpg)
![firetools](https://cloud.githubusercontent.com/assets/12716989/12147986/deebab8a-b4d6-11e5-9937-27260b72dd59.jpg)
![fire-truck4](https://cloud.githubusercontent.com/assets/12716989/12147987/deebbada-b4d6-11e5-91fe-3845d7a04163.png)
![gear_tools](https://cloud.githubusercontent.com/assets/12716989/12147985/deeaad7a-b4d6-11e5-96d9-aa04a04947ec.png)
![seashell-clipart-seashell](https://cloud.githubusercontent.com/assets/12716989/12147988/deeee2a0-b4d6-11e5-8f5a-f69607fb773b.png)

thank you

**Comment by CarlosHAraujo** [comment] 2016-01-08 13:22
+1

**Comment by caduvieira** [comment] 2016-01-08 20:59
Firetruck #5738

**Comment by tagliala** [comment] 2016-01-09 12:13
I'm going to consider this a duplicate of #5738

**Closed by tagliala** 2016-01-09 12:13 UTC

**Comment by dpfem** [comment] 2016-05-13 01:37
+1
