### ISSUE TITLE
Icon request: epub icon

### ISSUE THREAD

**Issue by AnnikaEriksson** [FortAwesome/Font-Awesome#10724] opened 2017-03-01 09:49 UTC
Hi, I would like an icon for the epub format please :)
https://en.wikipedia.org/wiki/File:EPUB_logo.svg

**Comment by tagliala** [comment] 2017-03-01 11:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1808, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-01 11:53 UTC
