### ISSUE TITLE
Icon request: icon-vr

### ISSUE THREAD

**Issue by Gustavo72s** [FortAwesome/Font-Awesome#12022] opened 2018-01-01 11:10 UTC
I suggest the creation of an icon for virtual reality glasses:

https://d30y9cdsu7xlg0.cloudfront.net/png/147354-200.png

**Comment by tagliala** [comment] 2018-01-01 12:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6590, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-01 12:02 UTC
