### ISSUE TITLE
Icons using fa-fw have different widths

### ISSUE THREAD

**Issue by jcano** [FortAwesome/Font-Awesome#6587] opened 2015-05-29 09:32 UTC
I'm trying to surround fixed-width icons with a circle, using border-radius and text-align center. The results are quite dissimilar, even adding some padding to let the icons grow. Shouldn't fixed-width icons share the same width?

This is my SCSS
```sass
    .event-mark {
            display: inline-block;

            width: 32px;

            padding: 3px;

            border: solid 2px $gray-dark;
            @include border-radius(50%);

            color: $gray-dark;
            font-size: 22px;
            text-align: center;

            background-color: #fff;
        }
```

This it the HTML for each icon
```html
<i class="fa fa-motorcycle fa-fw event-mark" style="color: #86B95D"></i>
```

And I'm using `box-sizing: border-box`. The results are quite irregular

![icons](https://cloud.githubusercontent.com/assets/592884/7879817/a8f0f502-05eb-11e5-81b8-a9da5c1a5d9a.png)

Chrome DevTools believes that all icons are the same width, but you can see bits of the icon extending outside of the box

![icons-box](https://cloud.githubusercontent.com/assets/592884/7879897/6dfd8bbc-05ec-11e5-9787-b3818193000f.png)

I tried reducing the font size and increasing the padding and although the icons stay within the borders, the alignment is still irregular.

**Comment by tagliala** [comment] 2015-05-29 19:19
if you could provide me a fiddle showing the issue I would be glad to help.

You can start with this one: http://jsfiddle.net/tagliala/e9yfxsfj/

**Comment by jcano** [comment] 2015-05-30 15:07
Updated the fiddle here: http://jsfiddle.net/jcano/e9yfxsfj/16/

I added two stylings, the original one and one with smaller fonts and bigger padding. In both cases the icons are off-center and large icons are drawn outside the box.

I think the issue here is that I'm setting the width to be the same as the height (I need them to be circles of the same size) and being a font it doesn't care for the width I'm setting. Or in other words, I just realized it's my problem and not an issue with the font.

Thanks in any case, and if you have any tips on how to do it, it would be greatly appreciated.

**Comment by tagliala** [comment] 2015-05-31 13:38
The problem is that you can't assume that 1em is enough for any icon. That's why `fa-fw` sets width to 1.28em (18/14em). If you override this setting, you will have issues. In other words: the issue is not related to `fa-fw` class.

You should use a different layout (http://jsfiddle.net/tagliala/UY9vQ/20/, refers to #1553 or take advantage of stack feature http://fontawesome.io/examples/#stacked or think about a slighter complex layout (add a container with `display: table` and add `display: table-cell` to icon)

Please also remeber that FA is not a silver bullet: icons have different width by design and some icons with odd height can't be vertically centered. Maybe that fontawesome is not the right solution for your specific use case.

Closing here, hope it helps

**Closed by tagliala** 2015-05-31 13:38 UTC
Labels: waiting for feedback
