### ISSUE TITLE
icon request: user-minus

### ISSUE THREAD

**Issue by gregveres** [FortAwesome/Font-Awesome#12736] opened 2018-03-29 19:40 UTC
There is a user-plus and a user-times. I understand that in a lot of cases user-times works for indicating deleting a user, but in that case where you are talking about quantity rather than a specific user, a user-minus would be a much better complement to user-plus. 

So I am requesting a user-minus icon. 

Thanks

**Comment by tagliala** [comment] 2018-04-06 15:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2893, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 15:19 UTC
