### ISSUE TITLE
Icon Request: fa-baseball

### ISSUE THREAD

**Issue by paulvanderhoeven** [FortAwesome/Font-Awesome#6438] opened 2015-05-11 14:18 UTC
The world is a better place with font-awesome!

**Comment by tagliala** [comment] 2015-05-18 08:11
any example?

**Comment by Fatbat** [comment] 2015-07-28 05:58
I think this is a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/714

Essentially we'd like to see a comprehensive selection of sports icons, usually represented by the balls used: baseball, football, basketball, tennis ball, soccer ball (already included), hockey puck, golf ball, rugby ball, cricket ball, badminton shuttlecock, etc. etc.

**Comment by dnavarrojr** [comment] 2015-08-28 18:38
+1

I am working on a sports related plugin for WordPress and I'd love to use FA icons with it.

**Comment by iatkinson** [comment] 2016-02-17 04:33
+1 would be a great addition.

**Comment by ozkary** [comment] 2016-02-17 17:28
any updates. This would be a great add for these icons.

**Comment by asila96** [comment] 2017-05-02 23:47
Yes, would love to see some sports icons. Working on a site for sports travel, and it would be "Awesome" to be able to use fontAwesome icons on it! In addition to what has already been listed, an icon for Cheerleading (maybe a Pom-Pom?) would be nice.

**Comment by adnanboz** [comment] 2017-07-15 22:59
+1

**Comment by josepena0409** [comment] 2017-09-01 09:08
+1

**Comment by lickmydesign** [comment] 2018-01-02 17:54
+1

**Comment by davegandy** [comment] 2018-01-30 17:21
Added `fa-baseball-ball` in 5.0.5 in 3 different styles. The Solid style is a part of Free. https://fontawesome.com/icons/baseball-ball?style=solid

We've also added `fa-baseball` in 3 different styles as a part of Pro:
https://fontawesome.com/icons/baseball?style=solid

**Closed by davegandy** 2018-01-30 17:21 UTC
Labels: waiting for feedback
