### ISSUE TITLE
Icon Request: fa-discord, fa-discord-o

### ISSUE THREAD

**Issue by atillabyte** [FortAwesome/Font-Awesome#10719] opened 2017-02-28 17:20 UTC
[Discord](https://en.wikipedia.org/wiki/Discord_(software)) is a free proprietary VoIP application designed for gaming communities

https://discordapp.com/branding
![Discord](https://discordapp.com/assets/1c8a54f25d101bdc607cec7228247a9a.svg)
![Discord](https://discordapp.com/assets/41484d92c876f76b20c7f746221e8151.svg)

**Comment by tagliala** [comment] 2017-02-28 17:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-28 17:46 UTC
