### ISSUE TITLE
Icon request: Icon-codeacademy

### ISSUE THREAD

**Issue by codyn329** [FortAwesome/Font-Awesome#5892] opened 2015-03-09 05:34 UTC
* http://cdn-production.codecademy.com/favicon.ico
* https://d1qb2nb5cznatu.cloudfront.net/startups/i/57028-75249c08760cc9b8331013724066c538-medium_jpg.jpg

**Comment by kwendenarmo** [comment] 2015-03-23 22:41
+1

**Comment by TheChen5** [comment] 2015-07-31 05:11
Dupe of #3320
+1 that
:mag:before:heavy_plus_sign:
@tagliala This should be closed

**Comment by tagliala** [comment] 2015-07-31 07:23
@TheChen5 thanks

**Closed by tagliala** 2015-07-31 07:23 UTC
Labels: brand icons, new icon
