### ISSUE TITLE
Icon request: icon-mountain

### ISSUE THREAD

**Issue by jerodgibson** [FortAwesome/Font-Awesome#12885] opened 2018-04-18 00:38 UTC
### What can it be used for?

Map and location services, natural resources.

### Example image (optional)

![image](https://user-images.githubusercontent.com/12631224/38905530-d9ad5f12-4276-11e8-84d5-076b72e108a5.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X] I have included at least one example image if it could be helpful (optional)
- [X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-18 09:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4109, please add a 👍  reaction to that request.

> [ X] I have searched for existing issues and to the best of my knowledge this is not a duplicate

Don't worry

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-18 09:33 UTC
