### ISSUE TITLE
Icon Request:  Sextant:  fa-sextant

### ISSUE THREAD

**Issue by kevin8479** [FortAwesome/Font-Awesome#13103] opened 2018-05-11 01:52 UTC
Sextant -- sextant has a lot of symbolic meaning.  For example, it might be used to represent navigation, travel, directions, surveying, a guide, astronomy...

**Comment by tagliala** [comment] 2018-05-11 10:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8616, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-11 10:34 UTC
