### ISSUE TITLE
Icon request: fa-mysql

### ISSUE THREAD

**Issue by sarojkumar007** [FortAwesome/Font-Awesome#15103] opened 2019-06-03 20:28 UTC
MySQL icon, database or any other database icon is not there. So, you can help bringing MongoDB or MySQL.

**Comment by tagliala** [comment] 2019-06-03 20:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6052, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-06-03 20:35 UTC
