### ISSUE TITLE
Astrological Signs

### ISSUE THREAD

**Issue by flexcom** [FortAwesome/Font-Awesome#13786] opened 2018-08-18 12:03 UTC
Would be great if you could add zodiac signs. I needed them multiple times and had to go another way. Thanks!

**Comment by tagliala** [comment] 2018-08-18 12:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2831, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-18 12:56 UTC
