### ISSUE TITLE
Icon request: icon-moustache

### ISSUE THREAD

**Issue by thewillyhuman** [FortAwesome/Font-Awesome#5312] opened 2015-01-01 14:14 UTC
![1420142819_mustache-](https://cloud.githubusercontent.com/assets/10364506/5592318/eb7f5900-91c8-11e4-8eff-6cbb20d2eb4a.png)

**Comment by nathraQ** [comment] 2015-01-27 12:34
+1

**Comment by tagliala** [comment] 2021-08-02 07:36
Duplicate of #3356

**Closed by tagliala** 2021-08-02 07:36 UTC
Labels: new icon, web application icons
