### ISSUE TITLE
Icon request: mongodb

### ISSUE THREAD

**Issue by PrerakGada** [FortAwesome/Font-Awesome#19761] opened 2023-06-10 18:50 UTC
I would like to request an icon for the MongoDB brand to be added to Font Awesome. The icon should be a simple, stylized representation of the MongoDB logo. It should be available in all of the same styles as other Font Awesome icons, such as solid, regular, light, and duotone.

The MongoDB brand is a registered trademark of MongoDB, Inc., so any icon that is created must be approved by MongoDB, Inc. before it can be added to Font Awesome. I have already contacted MongoDB, Inc. and they have approved the request.

I believe that adding a MongoDB icon to Font Awesome would be a valuable addition to the library. MongoDB is a popular NoSQL database, and many developers use Font Awesome to add icons to their apps. An official MongoDB icon would make it easier for developers to use the MongoDB brand in their apps.

Thank you for your consideration.

**Comment by tagliala** [comment] 2023-06-10 19:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2725 , please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-06-10 19:00 UTC
