### ISSUE TITLE
Icon request: pin-note

### ISSUE THREAD

**Issue by heziw** [FortAwesome/Font-Awesome#18315] opened 2021-09-29 14:53 UTC
**What can it be used for?**
Single Icon: An option for adding sticky notes.

**Example image (optional)**
https://www.iconfinder.com/icons/4743537/note_office_push%20pin_sticky_icon

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-09-29 14:59
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/v6.0/icons?q=thumbtack&s=solid%2Cbrands or https://fontawesome.com/v6.0/icons/note-sticky fit your use case?

**Comment by aethior** [comment] 2022-03-21 22:51
> Does https://fontawesome.com/v6.0/icons?q=thumbtack&s=solid%2Cbrands or https://fontawesome.com/v6.0/icons/note-sticky fit your use case?

I would say yes. 

`fa-note`: https://fontawesome.com/icons/note
`fa-note-sticky`: https://fontawesome.com/icons/note-sticky

Edit. Sticky note with pin icon (pinned document) is duplicate of #14908.

**Closed** 2022-03-22 17:34 UTC
Labels: waiting for feedback
