### ISSUE TITLE
Icon Request: fa-pool

### ISSUE THREAD

**Issue by gvizziello** [FortAwesome/Font-Awesome#11187] opened 2017-06-15 16:10 UTC
I need an Icon for swimming-pool, I need to describe services of a wellness center.
Thanks a lot!

**Comment by tagliala** [comment] 2017-06-15 16:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3285 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-15 16:27 UTC
