### ISSUE TITLE
Icon request: dlive

### ISSUE THREAD

**Issue by Wizastudios** [FortAwesome/Font-Awesome#18130] opened 2021-08-03 04:06 UTC
**What can it be used for?**
The icon would be for the blockchain streaming service [dlive.tv](https://dlive.tv/). As a service offered by other products, it would be beneficial to expand on live streaming brands like this as Twitch alternatives.

**Example image (optional)**
<img src="https://play-lh.googleusercontent.com/YPHg7Z7LtGSiW9HHwtWZNTGHgsT4AzA29N2v757gdi66vEwoVf6pzHVvN7ke5XniHQ=s360-rw" width="350" title="dlive logo">

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-08-03 07:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14439, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-08-03 07:11 UTC
