### ISSUE TITLE
Icon request: Booking.com

### ISSUE THREAD

**Issue by Blueball79** [FortAwesome/Font-Awesome#8876] opened 2016-04-02 18:07 UTC

**Comment by tagliala** [comment] 2016-04-02 18:13
Duplicate of #5257, please +1 that request

Please also search before opening new requests

Closing here

**Closed by tagliala** 2016-04-02 18:13 UTC

**Comment by hudri** [comment] 2016-04-27 12:36
+1
Useful for any tourism related site, in Europe booking.com has a much stronger market presence than Expedia or Kayak
