### ISSUE TITLE
Icon Request: fa-raspberry-pi

### ISSUE THREAD

**Issue by OnlyDrey** [FortAwesome/Font-Awesome#9946] opened 2016-09-22 12:08 UTC
We need a Raspberry Pi icon as well! :)

https://rasplapse.files.wordpress.com/2012/06/pi_white.jpg

**Comment by tagliala** [comment] 2016-09-22 13:35
Duplicate of #2944, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-22 13:35 UTC
