### ISSUE TITLE
Tiktok icon displaying "糧" instead?

### ISSUE THREAD

**Issue by CameronWhyte** [FortAwesome/Font-Awesome#19642] opened 2023-04-03 14:25 UTC
### Bug description

The Tiktok icon is not displaying correctly, and is instead displaying the following symbol "糧".

Other social media icons are working correctly, and the Tiktok icon is available with my license, version etc.

I am using the latest version of the Font Awesome plugin, as well as the latest version of Wordpress.

For avoidance of doubt, this is the html for the icon: <i class="fa-brands fa-tiktok"></i>

### Font Awesome version

6.3.0

### Application and Operating System

- Wordpress
- Font Awesome plugin

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2023-04-03 19:59
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to close this report because it is a known issue fixed in version 5.14

> Font Awesome version
> 6.3.0

It is possible that a different plugin is overriding your application's font awesome version with an older one

Please use the conflict detection script to find this kind of problems

Docs: https://fontawesome.com/v6/docs/web/dig-deeper/conflict-detection

If you still think there is an issue with Font Awesome, please provide a reproducible test case and I will take a look

**Closed as completed by tagliala** 2023-04-03 19:59 UTC
Labels: bug, needs-triage
