### ISSUE TITLE
please add ko-fi logo!

### ISSUE THREAD

**Issue by juunichiro** [FortAwesome/Font-Awesome#16510] opened 2020-04-23 02:10 UTC
it would be a lot easier to code the icon and link to my donation page!

thankyou :)

**Comment by tagliala** [comment] 2020-04-23 09:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12607 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-04-23 09:09 UTC
