### ISSUE TITLE
Icon request: fa-users-two

### ISSUE THREAD

**Issue by anirvan** [FortAwesome/Font-Awesome#8870] opened 2016-04-01 00:12 UTC
I need a simple icon to indicate multiple users, but the existing `users` icon is busy and unclear. At small sizes, my co-workers think it looks like a skull and crossbones.

I'd like to suggest adding a simpler users icon with just two heads.

Here's an example of what that looks like in Google's Material design icon set (source: https://design.google.com/icons/#ic_people), vs. the current `users` icon in FontAwesome.

![image](https://cloud.githubusercontent.com/assets/57606/14194466/b052d2a6-f763-11e5-8b8d-7813b29fe542.png)

Here are some icons from the Noun Project of two abstracted overlapping heads:

* https://thenounproject.com/term/people/192946/
* https://thenounproject.com/term/people/192945/
* https://thenounproject.com/term/community/8943/
* https://thenounproject.com/term/people/209155/
* https://thenounproject.com/term/people/15060/
* https://thenounproject.com/term/people/29029/

**Comment by tagliala** [comment] 2016-04-01 09:45
Duplicate of #2883, please +1 that request

Please also search before opening new requests

Closing here

**Closed by tagliala** 2016-04-01 09:45 UTC

**Comment by MikiSoft** [comment] 2016-05-22 12:03
+1

**Comment by tagliala** [comment] 2016-05-22 12:35
locking here :lock:
