### ISSUE TITLE
Icon request: score

### ISSUE THREAD

**Issue by mgbecker** [FortAwesome/Font-Awesome#17485] opened 2020-12-15 17:02 UTC
**What can it be used for?**
This would be used for anything that has scores (basketball, football, ping-pong, etc.)

**Example image (optional)**
Flip Scoreboard
![image](https://user-images.githubusercontent.com/4459193/102246548-e7509300-3ecc-11eb-9ae0-1f502b8259c7.png)

Judge Scores
![image](https://user-images.githubusercontent.com/4459193/102246969-5928dc80-3ecd-11eb-8a38-a370623c9cfe.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-12-19 13:42
Hi!

Thanks for being part of the Font Awesome Community.

Any simpler, single color design that can fit 16px icon size?

**Comment by aethior** [comment] 2022-05-21 01:22
Duplicate of #5392?

cc/ @tagliala

**Comment by tagliala** [comment] 2022-05-21 07:50
Yes, I think this is a duplicate

**Closed by tagliala** 2022-05-21 07:50 UTC
Labels: waiting for feedback
