### ISSUE TITLE
Icon request: fa-hand-metal-o

### ISSUE THREAD

**Issue by imagnetcz** [FortAwesome/Font-Awesome#7348] opened 2015-08-31 11:44 UTC
Something like this will be great :) https://cdn2.iconfinder.com/data/icons/interactions-and-gestures-flat-bold-rounded/100/Metal-512.png

Thanks!

**Comment by valioDOTch** [comment] 2015-09-07 09:27
Dupe of #3077

**Comment by tagliala** [comment] 2015-09-13 11:59
closing here

**Closed by tagliala** 2015-09-13 11:59 UTC
