### ISSUE TITLE
4.7.0 icons preview on https://fontawesome.com/v4.7.0/examples/#animated not showing

### ISSUE THREAD

**Issue by joomlabeat** [FortAwesome/Font-Awesome#14120] opened 2018-10-16 14:57 UTC
Hi all,

is it me only, or the icons on https://fontawesome.com/v4.7.0/examples/#animated are not showing? 

This is what I see in both Safari and Chrome: 
![screen shot 2018-10-16 at 17 55 15](https://user-images.githubusercontent.com/6756053/47025806-d9781980-d16c-11e8-8170-c44f10bd9132.jpg)

**Comment by tagliala** [comment] 2018-10-16 18:17
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

I can confirm (chrome / windows 10)

I've also assigned @robmadole because the browser is loading the .ttf, but it shouldn't.

There is an issue with the MIME type of the woff2 file, ref: #13864 https://github.com/FortAwesome/Font-Awesome/issues/13864#issuecomment-417836961

**Comment by talbs** [comment] 2018-12-03 14:40
Thanks for bringing this to our attention. The version 4 docs seem to be behaving themselves for quite some time now. Also, I believe we've corrected the issue with the `.ttf` version of the font loading, and the docs are using the `woff2` and `woff` web font versions now.

 I'll close this with that in mind, but please let us know those docs have any further issues.

**Closed by talbs** 2018-12-03 14:40 UTC
Labels: bug, doc
