### ISSUE TITLE
Icon Request: fa-googleplay, fa-itunes & fa-tidal

### ISSUE THREAD

**Issue by RASK901** [FortAwesome/Font-Awesome#9029] opened 2016-04-20 22:02 UTC
![googleplay](https://cloud.githubusercontent.com/assets/18583587/14691982/9220899e-0754-11e6-854b-0f459404c3f3.png)
[googleplay.zip](https://github.com/FortAwesome/Font-Awesome/files/228890/googleplay.zip) (SVG File)

![itunes](https://cloud.githubusercontent.com/assets/18583587/14691984/9224bd52-0754-11e6-82e6-d480a19c222b.png)
[itunes.zip](https://github.com/FortAwesome/Font-Awesome/files/228889/itunes.zip) (SVG File)

![tidal](https://cloud.githubusercontent.com/assets/18583587/14691983/92235048-0754-11e6-883e-cd24648ee93e.png)
[tidal.zip](https://github.com/FortAwesome/Font-Awesome/files/228891/tidal.zip) (SVG File)

**Comment by tagliala** [comment] 2016-04-20 22:29
Duplicate of #2272 #919 #8850 , please +1 those requests

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-20 22:29 UTC
