### ISSUE TITLE
Inconsistent icons between CDN and Kit

### ISSUE THREAD

**Issue by rhydev** [FortAwesome/Font-Awesome#17871] opened 2021-05-03 20:59 UTC
**Describe the bug**
Icons are not positioned the same between CDN and Kit of the exact same FontAwesome version. As shown in screenshot example, the `::before` selector of `<i class="fas fa-check" />` has the icon positioned in the center with 2px of space above and below the icon, whereas the exact same element with the Kit has 1px of space above and 3px of space below.

P.S. The link to the bug report template is broken in CONTRIBUTING.md, it points to bug-report.md instead of bug_report.md

**To Reproduce**
Kit CodePen: https://codepen.io/rhydev/pen/abpexML
CDN CodePen: https://codepen.io/rhydev/pen/NWdQmVW

Kit link: https://kit.fontawesome.com/4a8e2c796c.js
CDN link: https://pro.fontawesome.com/releases/v5.15.2/css/all.css

**Expected behavior**
Kit and CDN icons should be positioned the same.

**Screenshots**
![2021-05-03 08_35_28-Window](https://user-images.githubusercontent.com/34504863/116931195-917b4e00-ac15-11eb-9973-1f6a7e0adbe5.png)

**Version and implementation**
Version: v5.15.2

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2021-05-03 21:16
Hi!

Thanks for being part of the Font Awesome Community and thanks for this report.

This is a know issue and is related to the Pro Kit incremental font file.

Duplicate of #16495

**Closed by tagliala** 2021-05-03 21:16 UTC

**Comment by jirkadev** [comment] 2022-04-26 19:50
alright this is known issue for two years..
