### ISSUE TITLE
Icon request: icon-mixcloud brand-icon

### ISSUE THREAD

**Issue by sundsx** [FortAwesome/Font-Awesome#7920] opened 2015-11-19 10:35 UTC
Hi, i need icon for musician/dj who have their page on traxsource. So the icon with logo brand will put direcly in their page like teitter and others.

**Comment by tagliala** [comment] 2015-11-19 10:37
Duplicate of #2753, please +1 that request

closing here

**Closed by tagliala** 2015-11-19 10:37 UTC
