### ISSUE TITLE
Icon request: icon-camper

### ISSUE THREAD

**Issue by campkids** [FortAwesome/Font-Awesome#8463] opened 2016-01-30 20:46 UTC
Wondering if there could be a camper logo.  Attaching icon for consideration. Thank you much.
![camper](https://cloud.githubusercontent.com/assets/16978617/12698343/799b750e-c768-11e5-8fd5-8fca2a3df382.png)

**Comment by tagliala** [comment] 2016-01-30 20:49
Duplicate of #5429 , please +1 that request

closing here

**Closed by tagliala** 2016-01-30 20:49 UTC
