### ISSUE TITLE
Icon request: tailwind, firebase and mongoDB

### ISSUE THREAD

**Issue by devruhul** [FortAwesome/Font-Awesome#18871] opened 2022-03-30 16:08 UTC
I need this icon on my website but I don't find those icons in fontawesome, so I would **request** the team to add **these icons** in font awesome so that **developer** can easily find this and add this.

**Comment by tagliala** [comment] 2022-03-30 16:36
Hi!

Thanks for being part of the Font Awesome Community.

firebase is a duplicate of #12284 , please add a 👍 reaction to that request
tailwind is a duplicate of #17012 , please add a 👍 reaction to that request
mongodb is a duplicate of #2725, please add a 👍 reaction to that request

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-03-30 16:36 UTC
