### ISSUE TITLE
Icon Request: fa-party

### ISSUE THREAD

**Issue by rolmo71** [FortAwesome/Font-Awesome#11887] opened 2017-12-09 12:58 UTC
![party](https://user-images.githubusercontent.com/34396568/33795831-0182681e-dce9-11e7-948b-599709724df9.png)

**Comment by radubr** [comment] 2017-12-13 10:16
+1

**Comment by tagliala** [comment] 2017-12-13 11:02
Hi!

Thanks for being part of the Font Awesome Community.

Since this icon represents a dancing couple, I'm going to consider this a duplicate of #1082

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-13 11:02 UTC
