### ISSUE TITLE
Icon Request: broken heart

### ISSUE THREAD

**Issue by MelOcho** [FortAwesome/Font-Awesome#5301] opened 2014-12-28 23:20 UTC
Hi,
Looking for a broken heart icon to go with the fa-heart icon. 

Cheers :-)

**Comment by davidklebanoff** [comment] 2015-01-22 08:38
This appears to be a duplicate of #751.

**Comment by tagliala** [comment] 2015-01-22 13:30
@davidklebanoff thanks

closing here, please +1 #751 and post there examples, workarounds

**Closed by tagliala** 2015-01-22 13:30 UTC

**Comment by UAEpro** [comment] 2016-10-18 12:30
@LegoStormtroopr i have transform: scaled the bolt to the end of the heart,
http://jsfiddle.net/kaowm9dq/28/
css:
`.fa-bolt {
    top:0%;
    left:2%;
    font-size:70%;
    transform: scale(0.8, 1.25);
}`

**Comment by msgoussi** [comment] 2021-01-08 10:22
How to include it in the the flexdaasboard valueBox function  
valueBox(value = 1000,  caption = "Death Cases",  icon = "fas fa-heart-broken", color = "red")

**Comment by tagliala** [comment] 2021-01-08 10:26
Hi @msgoussi 

> How to include it in the the flexdaasboard valueBox function

Sorry, we do not provide support for third-party software

**Comment by msgoussi** [comment] 2021-01-08 10:27
@tagliala FYI, other icons are working fine, except this icon
