### ISSUE TITLE
Icon request: icon-ubuntu

### ISSUE THREAD

**Issue by souldanger** [FortAwesome/Font-Awesome#10467] opened 2017-01-05 09:24 UTC
it would be fantastic if you add an icon for Ubuntu as below.
Thanks

![ubuntu-icon](https://cloud.githubusercontent.com/assets/10036776/21675168/0fdccbb0-d331-11e6-97e5-a3f63245555c.png)

**Comment by tagliala** [comment] 2017-01-05 11:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #980, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-05 11:35 UTC
