### ISSUE TITLE
Icon Request: Discord

### ISSUE THREAD

**Issue by theanidox** [FortAwesome/Font-Awesome#10936] opened 2017-04-13 09:53 UTC
I'd plan on using it on my website (and I know a few other people who would too)
![This is what I'd be wanting](https://cloud.githubusercontent.com/assets/24899167/24999937/56f78e7e-2037-11e7-8b4a-0c3441da0bce.png)
EDIT: By the way, the image is white and transparent :S. I'll attach one in purple (but I'd prefer the icon in black or white)
![One in purple](https://cloud.githubusercontent.com/assets/24899167/25000013/9ea7e426-2037-11e7-997d-ce4f0c07b02d.png)

**Comment by PeterShaggyNoble** [comment] 2017-04-13 10:10
Dupe of #7574.

Note that the icon without the "speech bubble" behind it, is not allowed by Discord's [brand guidelines](https://discordapp.com/branding).

**Comment by tagliala** [comment] 2017-04-13 10:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of  #7574, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-13 10:19 UTC

**Comment by tagliala** [comment] 2017-04-13 11:27
@PeterShaggyNoble thanks for the help, as usual.

**Comment by PeterShaggyNoble** [comment] 2017-04-13 12:05
No problem, @tagliala 👍
