### ISSUE TITLE
Icon request: Autodesk

### ISSUE THREAD

**Issue by ManuelRomer** [FortAwesome/Font-Awesome#18383] opened 2021-10-22 15:53 UTC
**What can it be used for?**
Needed to refer to Autodesk products from third-party sites that uses their APIs. Autodesk is one of the biggest platforms at applied Industry Graphic Design.

**Example image (optional)**
Short while ago, Autodesk has worked on rebranding their mark image, so this is a great chance to offer users this updated resource.

![image](https://user-images.githubusercontent.com/74239475/138485609-68862b14-44e5-4660-8de7-885eac9b5fa8.png)

![image](https://user-images.githubusercontent.com/74239475/138485666-2a09ae3b-bd7a-46de-8d3b-f56e07b6a788.png)

The request is about the second (the 'a' logo). Thank You

**Icon request checklist**
- [single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [*] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [*] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [*] I have included at least one example image if it could be helpful (optional)
- [*] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-11-04 19:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2198, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-11-04 19:53 UTC

**Comment by ManuelRomer** [comment] 2021-11-08 08:01
Thank you so much!!
