### ISSUE TITLE
Icon Request: fa-unchecked-video-camera

### ISSUE THREAD

**Issue by freegov** [FortAwesome/Font-Awesome#9849] opened 2016-09-02 05:05 UTC
There is a fa-video-camera, but no video off icon. Can you please create that as well?

Thank you

**Comment by aethior** [comment] 2016-09-02 12:09
Hi @freegov,

I think you are requesting ´fa-video-camera-slash´ icon (duplicate of #3765). :)

**Closed** 2016-09-02 13:39 UTC
