### ISSUE TITLE
Icon Request: fa-knight

### ISSUE THREAD

**Issue by faeb187** [FortAwesome/Font-Awesome#6801] opened 2015-06-22 09:16 UTC
World needs chess icons:

fa-rook
fa-knight
fa-bishop
fa-queen
fa-king
fa-pawn

**Comment by Garrcomm** [comment] 2015-06-22 17:25
:+1:

**Comment by ShamanFromSiberia** [comment] 2015-07-01 08:09
+1

**Comment by tagliala** [comment] 2015-07-01 09:47
duplicate of #1815 , please +1 that request

closing here

**Closed by tagliala** 2015-07-01 09:47 UTC

**Comment by fellowgeek** [comment] 2015-07-01 14:32
+1000000
