### ISSUE TITLE
Icon request: Bullet point // fa-dot

### ISSUE THREAD

**Issue by Miserlou** [FortAwesome/Font-Awesome#3237] opened 2014-04-11 18:32 UTC
Hey all!

Here's a quick and easy icon request: fa-bullet-point, for using with bulleted lists.

Currently, the only option for this is fa-circle, which is too large for lists. Fa-circle is about 110% of the text height, fa-bullet-point should be about 30%, vertical-aligned to the middle.

Any chance of making this happen? I think this would be useful for a lot of people.

Thanks!
Rich

(PS - I love you. I use your project every day on sites used by hundreds of thousands of people. You rock.)

**Comment by cherrador** [comment] 2015-09-24 01:26
+1

Why? fa-circle cannot be reduced on Firefox when the font size is already 10px (i.e. font-size:0.5em). In fact any font will do this on Firefox, there is a workaround using font-size-adjust CSS to reduce it, but this a hack and will not work in the future.

Surprising reducing the size below the 10px works fine on IE and Chrome. According sources StackOverflow this is a bug and it could be fixed on the future. http://stackoverflow.com/questions/2421056/how-can-i-override-the-minimum-font-size-in-firefox

Here is sample of the problem:
Chrome:
![sample2](https://cloud.githubusercontent.com/assets/12229855/10063095/e0669fe8-6237-11e5-98c2-55b26ccffd2b.png)
Firefox:
![sample1](https://cloud.githubusercontent.com/assets/12229855/10063098/ef16ce00-6237-11e5-9c75-301c789bb1c0.png)

An icon already at the correct size and centered will be awesome. Perfection will be like the center dot from fa-dot-circle-o, so also it could be used for CSS stacks and animations.

**Comment by knireis** [comment] 2019-05-27 10:48
+1

**Comment by cherrador** [comment] 2019-05-28 23:31
Woo... this was 4 years ago and browsers advance and quirks get fixed. @knireis, I can tell you, this is not an issue any more, Firefox behaves nicely these days. In my case, I end up creating a new class named "fa-required" on my CSS, it looks like this:
```css
.fa-required::before {
    content: "\f111";
}
.fa-required {
    font-size: 0.5em;
    vertical-align: middle;
    color: #B00;
    padding: 0.5em;
}
```

**Comment by sensibleworld** [comment] 2024-07-11 13:56
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/5732)

**Closed by sensibleworld** 2024-07-11 13:56 UTC
Labels: new icon, web application icons (legacy category), Duplicate
