### ISSUE TITLE
Icon request: shake-hands

### ISSUE THREAD

**Issue by steffenvogdrup** [FortAwesome/Font-Awesome#7762] opened 2015-10-27 08:28 UTC
For use when signed a contract or similar
![shake hands google sogning](https://cloud.githubusercontent.com/assets/4906868/10752826/02176716-7c8d-11e5-9d8b-a904151e02f9.png)

**Comment by tagliala** [comment] 2015-10-27 11:46
Duplicate of #878 , planned for 5.0.0, but please +1 that request 

Closing here

**Closed by tagliala** 2015-10-27 11:46 UTC
