### ISSUE TITLE
Icon alignment of fa-gas-pump and fa-charging-station

### ISSUE THREAD

**Issue by DripFixer** [FortAwesome/Font-Awesome#15526] opened 2019-09-13 08:24 UTC
I'm using these two icons as alternating images to signify the swap between internal combustion engines and electric powered cars.

However, when the icons switch using Javascript they aren't aligned precisely, despite being positioned in the same place.

This makes the gas pump body and the charging station body jump from side to side in the swap.

I think it's because the actual images are drawn slightly out of alignment.

You can see the effect at the bottom of this page:

https://www.drivesmart.uk/fuelstartguide.aspx

Is there any way to get the bodies aligned so just the gas pump hose and the electric charge cable have different finishing positions?

**Comment by tagliala** [comment] 2019-09-13 08:32
Hi!

Thanks for being part of the Font Awesome Community.

gas pump is already available starting from FA 5.0.13: https://fontawesome.com/icons/gas-pump?style=solid

charging station is available in 5.10.1 https://fontawesome.com/icons/charging-station?style=solid

Please update to the latest version of Font Awesome (5.10.2) to use both

**Comment by DripFixer** [comment] 2019-09-13 08:38
Hi tagliala

Yes, I know they are available but they don't align.

So, when you alternate between them the images jump.

My question was, can these icons be re-aligned?

**Comment by tagliala** [comment] 2019-09-13 08:39
Hi!

Thanks for being part of the Font Awesome Community.

Sorry if you got an email, I didn't get the issue at the beginning

I'm responding, please give me some time 😅

**Comment by tagliala** [comment] 2019-09-13 08:59
Hi again,

I've got the point

I'm asking @sensibleworld if this is the case of change the icon design, but meanwhile you can use a custom css rule: https://jsfiddle.net/tagliala/q2oa94hv/13/

Icons have not the same width on Font Awesome by design choice. You can definitely add your css rules to fit your needs

If you check the grid, `charging-station` is 18 units wide and `gas-pump` is 16 units wide, so you want that the smallest icon to have the same width of the largest one. `1.125em` is a magic number for 18/16

**Comment by DripFixer** [comment] 2019-09-13 09:11
Thanks tagliala, I'll give that a try!

**Comment by sensibleworld** [comment] 2019-09-13 20:06
Thanks for bringing this to my attention! So... the simple answer is that the icons are different widths because there needed to be room for the "plug" at the end of the `charging-station` icon. That said, the main body of the icon shapes are the same.

So, a couple ways to accomplish they effect you're looking for would be to have the icons left-aligned. Alternately, you could add a small amount of padding to the left of the `charging-station` icon

**Comment by tagliala** [comment] 2019-09-13 21:48
Ok, let's close this one

@DripFixer this is a third-alterntive (2/16 padding-right to gas-pump): https://jsfiddle.net/tagliala/q2oa94hv/16/

**Closed by tagliala** 2019-09-13 21:48 UTC
Labels: css, question

**Comment by DripFixer** [comment] 2019-10-19 01:53
Finally got around to implementing the suggested fix at: https://jsfiddle.net/tagliala/q2oa94hv/13/ and it worked perfectly.  Thanks tagliala and sensibleworld!
