### ISSUE TITLE
Icon request: icon-website

### ISSUE THREAD

**Issue by wolv47** [FortAwesome/Font-Awesome#6097] opened 2015-03-29 23:35 UTC
Hello, 
first of all thanks a lot for your awesome work.
As for the icon request I would like to have some website or webpage icon I could use in menu in CMS/CMR (like list of pages etc).
For now I stick with file-text-o but would like something more representing a website.
Here's my idea
![icon-website](https://cloud.githubusercontent.com/assets/10781563/6888424/cea423bc-d67c-11e4-96e9-7e7e2b368871.png)

**Comment by aethior** [comment] 2016-06-09 00:46
Duplicate of #4422.

cc @tagliala

**Comment by tagliala** [comment] 2016-06-09 09:30
This could be a duplicate of #6613 or #8277. #8277 needs some feedback

Since the above icon does not represent in any case a website I'm going to close this one

**Closed by tagliala** 2016-06-09 09:30 UTC
Labels: waiting for feedback
