### ISSUE TITLE
Icon Request: Passport

### ISSUE THREAD

**Issue by sawmyaseshamany** [FortAwesome/Font-Awesome#8909] opened 2016-04-07 05:27 UTC
Hi we need an icon that can be used to replicate a passport.

**Comment by tagliala** [comment] 2016-04-07 11:23
Duplicate of #3695, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-07 11:23 UTC
