### ISSUE TITLE
Icon request: fa-hourglass

### ISSUE THREAD

**Issue by ienea** [FortAwesome/Font-Awesome#6952] opened 2015-07-15 09:08 UTC
I would like an hourglass icon to represent "pending" or "waiting" in an app I'm working on. There is currently no font-awesome icon that can represent "waiting" or "pending".

**Comment by dorothyjane** [comment] 2015-07-15 09:24
+1

**Comment by tagliala** [comment] 2015-07-16 12:00
duplicate of #492 , scheduled for 5.0.0 release, please +1 that request

closing here

**Closed by tagliala** 2015-07-16 12:00 UTC
