### ISSUE TITLE
Word & Icon Not Both Highlighting

### ISSUE THREAD

**Issue by sides2sport** [FortAwesome/Font-Awesome#16682] opened 2020-05-20 13:46 UTC
Hi,

I have added icons to my navigation menu, when you hover over the word next to the icon, this doesn't change colour.

Can you confirm how to resolve this?

Thanks.

**Comment by tagliala** [comment] 2020-05-20 15:54
Hi!

Thanks for being part of the Font Awesome Community.

> I have added icons to my navigation menu, when you hover over the word next to the icon, this doesn't change colour.

Could you please share a reproducible test case?

Cannot reproduce here: https://jsfiddle.net/tagliala/y693z45a/25/

**Comment by sides2sport** [comment] 2020-05-21 23:18
Hi,

See image attached.  I'm hovered over the word and the logo is not highlighting.

Can you confirm why and how I can change this?

Thanks,
Amy

________________________________

**Comment by tagliala** [comment] 2020-05-22 07:54
> See image attached.  I'm hovered over the word and the logo is not highlighting.

Hi, email attachments don't work, please use the GitHub website to attach media

But in this case, please avoid screenshot and provide a reproducible test case: it will be hard to check if there is a css rule which prevents icon to change color from a screenshot

**Comment by sides2sport** [comment] 2020-05-22 08:38
Hi,

This is the html example -

<i class="far fa-futbol fa-fw"></I> [Ball](url)

Thanks,
Amy

**Comment by sides2sport** [comment] 2020-05-22 16:49
Hi,
Can you help?
Thanks,
Amy

**Comment by tagliala** [comment] 2020-05-22 17:12
Hi sides2sport

Sorry, let me clarify what I've asked for before

![image](https://user-images.githubusercontent.com/556268/82692324-d48c1d80-9c5f-11ea-9bee-66aec79b5bde.png)

This is all I can see from your above post.

I need a reproducible test case to check if this is an issue. Please provide a working example (a link to the website experiencing the issue is fine) where I can hover with the mouse on the title and see that the icon does not change color as you expected

We also have a [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md), but in this specific case I really need a reproducible test case

**Comment by sides2sport** [comment] 2020-05-22 17:21
Hi,

Apologies, here is the website - sides2sport.co.uk

Thanks,
Amy

**Comment by sides2sport** [comment] 2020-05-22 17:27
Sorry, i am very new to all this!

**Comment by tagliala** [comment] 2020-05-22 18:19
Hi,

If the problem is in the icons inside the hover menu, then there is a css rule that is preventing Font Awesome Icon to inherit the color 

![image](https://user-images.githubusercontent.com/556268/82696115-ae1db080-9c66-11ea-9dc7-d0984b84e5c9.png)

This is the rule and it does not come from the css but it is in the HTML:

```
#main-nav a, #main-nav .svg-inline--fa, #main-nav #s {
    color: #666666;
}
```

![image](https://user-images.githubusercontent.com/556268/82696217-e0c7a900-9c66-11ea-8f3d-19c9a6cf059d.png)


Sorry but this is not a support forum, closing here

**Closed by tagliala** 2020-05-22 18:19 UTC
Labels: waiting for feedback

**Comment by sides2sport** [comment] 2020-05-22 18:21
Ok, do you knw how I resolve?

**Comment by sides2sport** [comment] 2020-05-22 18:27
It’s on the hover, I want it to be yellow

**Comment by tagliala** [comment] 2020-05-22 18:45
Apologies, but this is not a support forum, I just had to be sure that there wasn't issues with Font Awesome itself 😅

For generic CSS questions, please try [stackoverflow](https://stackoverflow.com)
