### ISSUE TITLE
Icon Request: fa-fan

### ISSUE THREAD

**Issue by dkeefe95** [FortAwesome/Font-Awesome#9673] opened 2016-07-28 16:55 UTC
Just like a standard desktop fan

**Comment by tagliala** [comment] 2016-07-28 18:53
Duplicate of #3684, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-28 18:53 UTC
