### ISSUE TITLE
Request Icon : fa-path

### ISSUE THREAD

**Issue by zrfikry** [FortAwesome/Font-Awesome#10956] opened 2017-04-17 06:12 UTC
It would be great if there's a Path social media icon

![path-logo-vector](https://cloud.githubusercontent.com/assets/19262307/25080600/901ac1ea-236f-11e7-8a8b-699925400637.png)

**Comment by tagliala** [comment] 2017-04-17 08:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2703, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-17 08:26 UTC
