### ISSUE TITLE
Icon request: rfid

### ISSUE THREAD

**Issue by DaniyyelMattay** [FortAwesome/Font-Awesome#12920] opened 2018-04-20 11:55 UTC
### What can it be used for?

Wherever RFID technology is used.

### Example image (optional)

![RFID Symbol 1](https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX20444672.jpg) ![RFID Symbol 2](https://www.datenschutzbeauftragter-info.de/wp-content/uploads/2014/08/rfid-logo.jpg)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-20 11:58
Hi!

Thanks for being part of the Font Awesome Community.

I have to consider this a duplicate of #6111

If your logo is an official registerd trademark, or if there is any official icon for the RFID technlogy, could you please provide a website or a wikipedia page about this topic?

Meanwhile, closing here

**Closed by tagliala** 2018-04-20 11:58 UTC

**Comment by tagliala** [comment] 2018-04-20 12:37
@DaniyyelMattay thanks. I will post your link at #6111
