### ISSUE TITLE
Icon Request: Flipboard

### ISSUE THREAD

**Issue by beethedude** [FortAwesome/Font-Awesome#10647] opened 2017-02-10 20:28 UTC
Please add Flipboard to your icons.

**Comment by tagliala** [comment] 2017-02-10 23:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1382, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-10 23:43 UTC

**Comment by beethedude** [comment] 2017-02-11 01:56
That looks like a 3+ year old request. Do you anticipate that this will be added at all?
