### ISSUE TITLE
Icon request: Codewars

### ISSUE THREAD

**Issue by BayB33** [FortAwesome/Font-Awesome#18897] opened 2022-04-12 11:55 UTC
I haven't found any codewars icon, I think it could be useful to add a link to one's codewars account for a potential recruiter or anyone interested in someone's work to see. 

Thank you.

**Comment by tagliala** [comment] 2022-04-12 19:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4809, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-04-12 19:08 UTC
