### ISSUE TITLE
Icon request: fa-gulden

### ISSUE THREAD

**Issue by rijkplasman** [FortAwesome/Font-Awesome#7587] opened 2015-10-01 17:10 UTC
Hi,

Could you add a Gulden icon, it's a digital currency used in the Netherlands.
At the moment we use this: https://nlgcdn.com/guldensign/1/guldensign.css, but we prefer using Font Awesome.

![gulden](https://cloud.githubusercontent.com/assets/6540064/10227868/16de0d2a-6870-11e5-910b-d76ad54bd9a3.png)

Here is a link to the Ai file: https://s3-eu-west-1.amazonaws.com/guldencoin.com/images/gblue.ai

More info: https://guldenpay.com

**Comment by caduvieira** [comment] 2015-10-02 13:27
dupe of #1622 ?

**Comment by rijkplasman** [comment] 2015-10-02 16:03
https://github.com/FortAwesome/Font-Awesome/issues/1622 is the old Guilder, which isn't used anymore in the Netherlands. Gulden is a new digital currency and accepted by many companies.

**Comment by caduvieira** [comment] 2015-10-02 16:33
Is this the same G in google's logo?

**Comment by rijkplasman** [comment] 2015-10-02 16:45
Well unfortunately they look quite similar, Google used almost the same design process as us, however we were first (april 2014).

**Comment by sensibleworld** [comment] 2024-07-10 21:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-10 21:33 UTC
Labels: new icon, currency (category), Declined
