### ISSUE TITLE
Icon Request: fa-percent

### ISSUE THREAD

**Issue by dudapasquali** [FortAwesome/Font-Awesome#5932] opened 2015-03-11 19:34 UTC
A percent sign (%) would very useful for me as an icon for a tx representing.

Thanks and congratulation for your wonderful work!!

**Comment by tagliala** [comment] 2015-03-11 19:56
duplicate of #1292 . Please +1 that request and please note that standard unicode points could easily be include in FA with a couple of lines of css

closing here

**Closed by tagliala** 2015-03-11 19:56 UTC
