### ISSUE TITLE
Icon request: hammer-and-pick

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6087] opened 2015-03-28 14:13 UTC
<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Schlaegel_und_Eisen_nach_DIN_21800.svg/354px-Schlaegel_und_Eisen_nach_DIN_21800.svg.png">

**Comment by G-Driver** [comment] 2015-03-28 18:42
@tagliala .... so whats the question? ;)

**Comment by tagliala** [comment] 2015-03-28 19:02
I don't know if I can consider this a duplicate of #736

**Comment by G-Driver** [comment] 2015-03-29 18:08
That one is different its a screwdriver with a wrench the only thing they have commin it's they're crossed.

Hammer and pick is a common symbol for mining

**Comment by tagliala** [comment] 2015-03-29 18:11
closing as a duplicate of #2442, please +1 that request and post there your example

Renaming #2442 to hammer-and-pick

**Closed by tagliala** 2015-03-29 18:11 UTC
Labels: waiting for feedback

**Comment by G-Driver** [comment] 2015-03-29 18:19
;) tnx didn't find that one

**Comment by tagliala** [comment] 2015-03-29 18:21
:+1:
