### ISSUE TITLE
fa-home

### ISSUE THREAD

**Issue by j-degreef** [FortAwesome/Font-Awesome#10642] opened 2017-02-09 12:34 UTC
Hi

I'm using FontAwesome with i3wm and a few characters are not displaying (fa-home, fa-heart, fa-gear,...)
Even in Character Map, I see the glyph but when I double click to copy it nothing is displayed in the "Text to copy" box.
I see them when I go to the CheatSheet but if I copy and try to paste in Vim, same thing, I don't see them.
Most of the characters are ok, only a few of them don't work.
![fontawesome](https://cloud.githubusercontent.com/assets/6998555/22783493/595b07aa-eecc-11e6-8c0f-bbafafb3edb6.jpg)

Any help would be appreciated as I've spend hours searching the net without success.
Forgive me if it is not the right place to ask.

Best regards

**Comment by tagliala** [comment] 2018-02-20 11:21
Sorry, I've completely missed this issue

This is a duplicate of #10102, please take a look there.

We have several issues about i3 and I'm personally not able to provide any help. I'm still waiting for community feedback there

Hope it helps,

closing here

**Closed by tagliala** 2018-02-20 11:21 UTC
