### ISSUE TITLE
Feature request: individual SVG source icons

### ISSUE THREAD

**Issue by synapticism** [FortAwesome/Font-Awesome#5800] opened 2015-02-27 08:25 UTC
Related to #3203 but slightly different: would it be possible to include individual SVG source icons in the repo somewhere? This way we could integrate the project into build processes and produce our own custom sprite sheets (or whatever else). I have found a project by the name of [Font-Awesome-SVG-PNG](https://github.com/encharm/Font-Awesome-SVG-PNG) that does something similar but it'd be cool to have a canonical set of icon source files available via Bower. Anyway, keep up the nice work!

**Comment by tagliala** [comment] 2015-02-27 17:02
@synapticism the problem is that at the moment Font Awesome is not developed starting from .svg files. There is a request to open the build process here: #3065 

Font-Awesome-SVG-PNG's creator reads here and he is very open to new requests. Maybe he could add support for bower.

/cc @Rush

**Comment by synapticism** [comment] 2015-02-27 17:15
@tagliala Thanks for the explanation! Yes, that other issue is pretty close to what I was thinking of... and now I understand the problem.

I already put a PR through to the owner of the other repo so we'll see how that goes :) feel free to close this if it helps keep things organized.

**Comment by synapticism** [comment] 2015-02-28 18:03
This is now working fine with [Font-Awesome-SVG-PNG](https://github.com/encharm/Font-Awesome-SVG-PNG). Just `bower install font-awesome-svg-png`!

**Comment by tagliala** [comment] 2015-02-28 21:16
@synapticism thanks, I will close this one for the moment

**Closed by tagliala** 2015-02-28 21:16 UTC
Labels: question
