### ISSUE TITLE
Icon Request: fa-vnd

### ISSUE THREAD

**Issue by thucnguyenit35** [FortAwesome/Font-Awesome#10962] opened 2017-04-18 07:23 UTC
I want icon vietnam dong

**Comment by tagliala** [comment] 2017-04-18 08:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6526, please add a 👍  reaction to that request.

Adding fa-dng to #6526's title

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-18 08:22 UTC
