### ISSUE TITLE
Icon request: vegetarian label

### ISSUE THREAD

**Issue by Pragyan14** [FortAwesome/Font-Awesome#19190] opened 2022-07-16 05:33 UTC
### Use case

To show restaurant in veg or non veg 

### Example image

![2560px-India_vegetarian_labels svg](https://user-images.githubusercontent.com/108871827/179341316-fcbdcab1-7016-485d-b45d-a91378d34a8f.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2022-07-16 08:39
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #17404, please add a 👍🏼 to that request

**Closed as completed by tagliala** 2022-07-16 08:39 UTC
Labels: new icon
