### ISSUE TITLE
Icon request: icon-category

### ISSUE THREAD

**Issue by xWenChen** [FortAwesome/Font-Awesome#19949] opened 2023-10-13 12:39 UTC
the tag icon is exist, but a category icon is not exist

**Comment by tagliala** [comment] 2023-10-13 15:47
Hi!

Thanks for being part of the Font Awesome Community.

I've just closed [#13523](https://github.com/FortAwesome/Font-Awesome/issues/13523) which is a duplicate of this request

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) by providing a single color, 16px icon size suitable example of how a "category" should look like

Closing here

**Closed as completed by tagliala** 2023-10-13 15:47 UTC
