### ISSUE TITLE
icon request: user-pencil

### ISSUE THREAD

**Issue by dandanknight** [FortAwesome/Font-Awesome#7925] opened 2015-11-19 14:25 UTC
Hi there, I came looking for a user-pencil type of icon, to go alongside user-plus and user-times, for editing of user accounts/profiles. I didn't find one, but I made (very badly) one from user and pencil.

It would be very helpful indeed to have this in your collection.

Well done on the amazing work BTW.

Here's a PNG, I have a PSD if you wish.
<img width="250" alt="user-pencil-compressed" src="https://cloud.githubusercontent.com/assets/1822840/11273076/3a429036-8ec9-11e5-848e-ca11e52ec48b.png">

Cheers,

Dan

**Comment by tagliala** [comment] 2015-11-19 17:49
Duplicate of #5951, please +1 that request

 refers to #1181 

closing here

**Closed by tagliala** 2015-11-19 17:49 UTC
