### ISSUE TITLE
Icon Request: fa-cv2 (cvv / cvc / cvv2 / cvc2)

### ISSUE THREAD

**Issue by bbmatt** [FortAwesome/Font-Awesome#4373] opened 2014-09-08 16:22 UTC
Back of credit card 3 digit icon - as seen on payment forms usually in image form. https://www.google.co.uk/search?q=cv2+credit+card+number&source=lnms&tbm=isch

**Comment by gregsaxton** [comment] 2020-12-22 03:28
![image](https://user-images.githubusercontent.com/659467/102845522-d7ebbf80-4461-11eb-8087-d04900212148.png)
Image from request #17501

**Comment by aethior** [comment] 2022-04-15 01:09
Duplicate of #8600. *(the other request has many more upvotes)*

cc/ @tagliala

**Comment by tagliala** [comment] 2022-04-15 07:47
Yes, let's move to the request with more upvotes

**Closed by tagliala** 2022-04-15 07:47 UTC
Labels: new icon, payments & shopping (category)
