### ISSUE TITLE
Simple category icon - for users to choose a category on a website

### ISSUE THREAD

**Issue by un33k** [FortAwesome/Font-Awesome#9002] opened 2016-04-16 23:38 UTC
It would be cool to have a category icon which looks similar to the `sitemap` icon but smaller in size or have lesser nodes.

Something like:

![category_318-30744](https://cloud.githubusercontent.com/assets/407537/14584232/a05e6816-040a-11e6-9d96-9fe29556a2bb.jpg)

**Comment by tagliala** [comment] 2016-04-17 10:09
duplicate of #1343 , please +1 that request

closing here

**Closed by tagliala** 2016-04-17 10:09 UTC
