### ISSUE TITLE
icon request: icon-trainer

### ISSUE THREAD

**Issue by AlisonAHarmeny** [FortAwesome/Font-Awesome#15264] opened 2019-07-15 10:35 UTC
**What can it be used for?**
Icon for representing running activities/events. We would use this on our charity website to promote these types of events

**Example image **
![89988-200](https://user-images.githubusercontent.com/52916318/61210435-664c0580-a6f4-11e9-9b76-2040a66f355e.png)

Ideally the side of a trainer, simple form and at an angle as if it is in motion.

Thank you!

**Comment by tagliala** [comment] 2019-07-15 13:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3704 or #6031, please add a 👍  reaction to the proper request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-07-15 13:33 UTC
