### ISSUE TITLE
Icon request: train-wagon

### ISSUE THREAD

**Issue by Tommuh** [FortAwesome/Font-Awesome#18603] opened 2022-01-23 09:09 UTC
There are a few train icons but there aren't any wagon icons. This will make the set more complete.

Can help with showing different type actions regarding train loading/unloading etcetera.

- Empty wagon (no load) - only the bed few axes.
- Loaded wagon (load) - combination with container/tank icon
- Loaded wagon (load) - multiple containers/tank, fully loaded, half loaded ... 
- Carriage 

There are 2 topics about this already opened in 2016, both seem 'dead'. 
- #8924
- #8867

Examples
- https://image.made-in-china.com/2f0j00eylQLCrhCZuV/Railway-Flat-Freight-Wagon-with-a-Loading-Capacity-of-2-Containers.jpg
- https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Railroad_car_with_container_loads.jpg/250px-Railroad_car_with_container_loads.jpg
-https://sc04.alicdn.com/kf/H0d88f6d1470842baa405cc7c500f5c76b.png
- https://www.railtech.com/wp-content/uploads/2019/02/Type-61-4462-passenger-car.jpg
- https://m.media-amazon.com/images/I/71giVcCwXpL._AC_SX425_.jpg

**Comment by tagliala** [comment] 2022-01-23 09:31
Hi!

Thanks for being part of the Font Awesome Community.

> both seem 'dead'.

They are not dead, they exist as a request and are open for upvotes

Please add a 👍🏼 reaction to the relevant request

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here as a duplicate of #8867

**Closed as completed by tagliala** 2022-01-23 09:31 UTC
