### ISSUE TITLE
Icon request: google-scholar

### ISSUE THREAD

**Issue by mansourweb** [FortAwesome/Font-Awesome#5682] opened 2015-02-15 18:06 UTC
![gs](https://cloud.githubusercontent.com/assets/10654684/6204281/7ba8c18e-b545-11e4-877b-af02e7ca5cd2.png)

Google Scholar provides a simple way to broadly search for scholarly literature. From one place, you can search across many disciplines and sources: articles, theses, books, abstracts and court opinions, from academic publishers, professional societies, online repositories, universities and other web sites. Google Scholar helps you find relevant work across the world of scholarly research.

Thanks.

**Comment by Dehli** [comment] 2015-02-19 15:25
Isn't this a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/541?

**Comment by tagliala** [comment] 2015-02-22 00:23
@Dehli thanks

this is a better duplicate of #541 but that request is very old and has a good number of +1s, so closing here

**Closed by tagliala** 2015-02-22 00:23 UTC
