### ISSUE TITLE
Icon Request: fa-government-building

### ISSUE THREAD

**Issue by dkvbabu** [FortAwesome/Font-Awesome#6010] opened 2015-03-20 07:17 UTC
can you please create icon for 'Governance' which I am planning to use in goverment related services via our video communication platform. I have attached sample image below.

regards
dk venkatesh babu
![whiteboard-icons-government](https://cloud.githubusercontent.com/assets/10416710/6747421/1ac319ea-ceff-11e4-975a-e4cd6e7d73cc.png)

**Comment by G-Driver** [comment] 2015-03-20 11:34
How about this one: http://fortawesome.github.io/Font-Awesome/icon/university/

**Comment by dkvbabu** [comment] 2015-03-22 13:47
hi,

I am already using university icon for Education based applications. So I need something different for Governance theme.

regards
dk venkatesh babu

**Comment by G-Driver** [comment] 2015-03-22 17:18
+

**Comment by kwendenarmo** [comment] 2015-03-23 22:16
+1

**Comment by caduvieira** [comment] 2015-03-26 13:38
+1

**Comment by sahrosa** [comment] 2015-03-26 13:43
+1

**Comment by dngunraj** [comment] 2015-03-26 20:24
+1

**Comment by G-Driver** [comment] 2015-03-27 22:39
Another example

<img src="https://cdn3.iconfinder.com/data/icons/landmark-icons/60/berlin_gate-512.png">

**Comment by dkvbabu** [comment] 2015-03-30 06:54
Hi,
This should be fine. can you please include in font-awesome icon list and its usage.

regards
dk venkatesh babu

**Comment by solid2core** [comment] 2015-06-10 20:33
+1

**Comment by yukoff** [comment] 2016-03-19 04:27
+1
I'm not sure if #2440 is related to this one, but there are few svg provided within comments, like [this](2440#issuecomment-62653026) and [this](2440#issuecomment-198631535)

**Comment by tagliala** [comment] 2016-09-30 09:03
Duplicate of #2440

**Closed by tagliala** 2016-09-30 09:03 UTC
Labels: new icon, web application icons
