### ISSUE TITLE
Icon Request: fa-pool

### ISSUE THREAD

**Issue by ydelgado** [FortAwesome/Font-Awesome#10511] opened 2017-01-11 16:04 UTC
Icon to be used as information in a hotel, to meake to know to clients that the hotel have a swimming pool as included service.

**Comment by ryankane** [comment] 2017-01-12 15:38
You need to provide an image.

A pool might be too complex, maybe a swimmer might work better. It is also universal. For no swimming allowed, you can combine this with the `fa-ban` (cancel) glyph.

> http://images.google.com/search?tbm=isch&q=swimming+pool+icon

# fa-swim

![swimming](https://cloud.githubusercontent.com/assets/1094151/21895980/ae9bf3e4-d8b2-11e6-859d-fec4bc6688b5.png)

Here is the source SVG code that I produced for the raster above. It can be further tweaked and modified as needed.

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
  <g fill="#000000">
    <circle id="head" cx="424" cy="168" r="58" />
    <circle id="hand" cx="163.84" cy="221.56" r="29.789" />
    <path   id="body" d="M 280.17,227.14 143.29,315.18 C 256.56,345.95 254.93731,269.34 372.36,253.21 356.06,179.01 237.63,113.3 142.78,200.49 L 184.9,242.62 C 216.78,213.1 248.29,211.58 280.17,227.14 Z" />
  </g>
  <path id="water" d="M 50,326 C 89.775,356.23 160.41,403.48 255.69,367.26 324.40515,340.69006 343.22206,285.74445 459.12,317.54"
        fill="none" stroke="#000000" stroke-linejoin="round" stroke-linecap="round" stroke-width="38" />
</svg>
```

**Comment by tagliala** [comment] 2017-01-12 16:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3285 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-12 16:04 UTC
