### ISSUE TITLE
Proposed a changing with an introduction of .fa::before pseudo-class

### ISSUE THREAD

**Issue by leoyli** [FortAwesome/Font-Awesome#11670] opened 2017-10-24 17:59 UTC
Hi,

I'm currently using Font Awesome 4.7.0.  I hope the maintaining team can consider the following change:

## **Proposed changing**
Current:
```css
.fa {
  (...)
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

Modified:
```css
.fa {
  (...)
}

.fa::before {
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

## **Reason**
I'm using it on \<a\> html tags.  And as you may know, those properties will also affect on my content which wrapped by the tag with `.fa` class; therefore, I have to overwrite with extra, unnecessary codes.

I know I can customize by using SCSS... however, I don't think Font Awesome should affect anything other than the icons.

Any thought?

**Comment by tagliala** [comment] 2017-10-24 23:59
Hi,

Thanks for being part of the Font Awesome Community.

This was discussed several times: in example #2695 (please read https://github.com/FortAwesome/Font-Awesome/issues/2695#issuecomment-31656200)

I still think that we should stick with one suggested way of using Font Awesome ( `<span class="fa fa-icon"></span>`) and all other use cases should be achieved with custom css. We provide mixins and variables for the latter

Closing here as a duplicate of #2695

**Closed by tagliala** 2017-10-24 23:59 UTC

**Comment by leoyli** [comment] 2017-10-25 03:07
Yes, I understood that point.  The users can always customized to their need.  And FA should be used as it was suggested to be.

However, I just want to rise this issue discussed in #6557 again for people's attention.  FA is a lib for icon by introducing a font that displays it.  And that's why I think it should do it only on it own jobs, not even change the whole style of `<span class="fa fa-icon"></span>` but only `before` (since that is where the icon as content sit in). Or just my personal designing philosophy anyway.

I know the FA team won't change it, I respect and understand.  So at least, or in other way, does anyone can call my attention if I customize FA by changing `.fa` to `.fa::before`.  Will I break anything?

Thanks!

**Comment by tagliala** [comment] 2017-10-25 10:42
> Does anyone can call my attention if I customize FA by changing .fa to .fa::before. Will I break anything?

I remember of some issues in fa-spin and other utility class: https://github.com/FortAwesome/Font-Awesome/issues/2695#issuecomment-31656200

**Comment by leoyli** [comment] 2017-10-25 14:01
Thanks!  I will dive into that part.
