### ISSUE TITLE
fa-mobile size too small

### ISSUE THREAD

**Issue by omrie** [FortAwesome/Font-Awesome#5311] opened 2015-01-01 08:34 UTC
fa-mobile and fa-mobile-phone looks too small when placed beside other icons.
While using it (a lot) I always hack a special CSS treatment. Thanks!

![image](https://cloud.githubusercontent.com/assets/7118470/5591898/b1bb7040-91a1-11e4-919f-82bef1baebab.png)

**Comment by tagliala** [comment] 2015-01-01 09:49
duplicate of #928 .

This is intended by design but you could share your thoughts in the above thread and maybe dave will reconsider

closing here

**Closed by tagliala** 2015-01-01 09:49 UTC

**Comment by gorio** [comment] 2015-07-10 11:52
use fa-tablet instead fa-mobile
