### ISSUE TITLE
Icon request: gatsby

### ISSUE THREAD

**Issue by amazingrando** [FortAwesome/Font-Awesome#15666] opened 2019-10-09 15:27 UTC
**What can it be used for?**
[Gatsby JS](https://www.gatsbyjs.org) is a project that is exploding in popularity.

**Example image (optional)**
<img width="797" alt="Screenshot 2019-10-09 11 26 07" src="https://user-images.githubusercontent.com/409903/66495662-9c94e900-ea87-11e9-9714-af1bc4a0a81a.png">

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-10-09 18:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12510, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-10-09 18:09 UTC
