### ISSUE TITLE
new icon request

### ISSUE THREAD

**Issue by Sarah1777** [FortAwesome/Font-Awesome#10244] opened 2016-11-18 13:18 UTC
Hey! You have a lot of icons for social platform but I would appreciate if you could add: HelloCoton, a major blogging directory and platform for French Bloggers

http://www.hellocoton.fr/

![capture d ecran 2016-11-18 a 08 16 32](https://cloud.githubusercontent.com/assets/23555005/20431336/8198977e-ad67-11e6-9f51-acba79b5aba7.png)
![capture d ecran 2016-11-18 a 08 16 54](https://cloud.githubusercontent.com/assets/23555005/20431337/81995c18-ad67-11e6-9cbe-01868801c2a4.png)
![capture d ecran 2016-11-18 a 08 17 20](https://cloud.githubusercontent.com/assets/23555005/20431338/8199ff24-ad67-11e6-97a6-407427b665b7.png)

**Comment by tagliala** [comment] 2016-11-18 13:49
Duplicate of #5008, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-18 13:49 UTC

**Comment by Sarah1777** [comment] 2016-11-18 14:09
sorry about that! thank you
