### ISSUE TITLE
Icon Request: fa-uber

### ISSUE THREAD

**Issue by joshuaNathaniel** [FortAwesome/Font-Awesome#6042] opened 2015-03-22 21:36 UTC
With the release of the Uber Request Endpoint I think this would be a highly beneficial icon to consider adding. Thanks much!

**Comment by tagliala** [comment] 2015-03-23 00:29
duplicate of #4826, please +1 that request

I should suggest you a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here

**Closed by tagliala** 2015-03-23 00:29 UTC
