### ISSUE TITLE
Icon request: fa-houzz

### ISSUE THREAD

**Issue by sebastiansulinski** [FortAwesome/Font-Awesome#5374] opened 2015-01-12 10:49 UTC
I had a client recently asking for a button linking to their houzz profile (http://www.houzz.com) - would you be able to design the icon for it please?

**Comment by tagliala** [comment] 2015-01-12 12:09
duplicate of #2039 , please +1 that request

closing here

**Closed by tagliala** 2015-01-12 12:09 UTC

**Comment by markream** [comment] 2015-06-25 19:42
+1
