### ISSUE TITLE
Icon Request: soccer (futbol) field

### ISSUE THREAD

**Issue by gpientka** [FortAwesome/Font-Awesome#16007] opened 2019-12-30 23:46 UTC
**What can it be used for?**
On a soccer (futbol) website to indicate a field

**Example image (optional)**
![image](https://user-images.githubusercontent.com/5750834/71605107-31116380-2b2c-11ea-9ab6-a5283276825a.png)

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-12-31 10:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1415, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-12-31 10:05 UTC
