### ISSUE TITLE
Icon Request: fa-report-generic

### ISSUE THREAD

**Issue by EddieFromFA** [FortAwesome/Font-Awesome#6634] opened 2015-06-02 23:41 UTC
An icon to allow the users to bring up an on-screen report of any kind. The icon should be generic enough so it can be associated to any on-screen report created for the page.

**Comment by tagliala** [comment] 2015-06-07 13:20
could you please provide an example?

**Comment by EddieFromFA** [comment] 2015-06-08 17:43
Sure, but do you mean an example of the icon I may be able to find elsewhere or an example of the use case?

**Comment by tagliala** [comment] 2015-06-08 21:55
example of the icon, you can use google image

**Comment by EddieFromFA** [comment] 2015-06-08 22:44
Thanks for the tips. Here are some of the candidates I found:

![86260-200](https://cloud.githubusercontent.com/assets/12718588/8046983/abf910a2-0df4-11e5-8412-b9d6a5630047.png)
![analytics-512](https://cloud.githubusercontent.com/assets/12718588/8046984/ac06df66-0df4-11e5-875c-2945bcc6558e.png)
![icat 20annual 20report_icon](https://cloud.githubusercontent.com/assets/12718588/8046985/ac0e2ff0-0df4-11e5-8809-07a29cff6c1b.png)
![imagesjcgn0z69](https://cloud.githubusercontent.com/assets/12718588/8046986/ac0e594e-0df4-11e5-8297-8d0d801fb1af.jpg)
![reports](https://cloud.githubusercontent.com/assets/12718588/8046987/ac10a2a8-0df4-11e5-9a36-fcdf4d5db5b0.png)

**Comment by EddieFromFA** [comment] 2015-06-08 23:06
Using the technique you showed me, I was able to create one that resembles the third icon in the sample icons I found:

<a href="#">
<span class="fa-stack fa-sm">
  <i class="fa fa-file-o fa-stack-2x"></i>
  <i class="fa fa-bar-chart fa-stack-1x"></i>
</span>
</a>

While it is not perfect, it is good enough for my purpose. That being said, I think both the Generic Report icon and the Financial Recovery icon (I requested in the other ticket) are common enough that they can use some polishing for everyone to utilize. Do you think I should submit a formal request through https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome?

**Comment by tagliala** [comment] 2015-06-09 11:23
ok, this is a duplicate of #6366 , please +1 that request

closing here

**Closed by tagliala** 2015-06-09 11:23 UTC
Labels: waiting for feedback

**Comment by tagliala** [comment] 2015-06-09 11:27
@EddieFromFA 

I agree with that the report icon and you are free to reopen the financial recovery request because it is a legit request

Actually these are formal requests :)

**Comment by EddieFromFA** [comment] 2015-06-09 16:22
Will do, thanks for all your help!
