### ISSUE TITLE
Icon request: icon-accessible

### ISSUE THREAD

**Issue by KevKoz** [FortAwesome/Font-Awesome#7168] opened 2015-08-07 16:19 UTC
One group, the Accessible Icon Project, has created a new logo that they hope will ultimately replace ISO standard. New York City has recently adopted this revised wheelchair logo.
http://99percentinvisible.org/episode/icon-for-access/
![image](https://cloud.githubusercontent.com/assets/13696875/9140347/1ab881e6-3cf6-11e5-8d85-9df7088d968c.png)

1. Head is forward to indicate the forward motion of the person through space. Here the person is the “driver” or decision maker about her mobility.

2. Arm angle is  pointing backward to suggest the dynamic mobility of a chair user, regardless of whether or not she uses her arms. Depicting the body in motion represents the symbolically active status of navigating the world.

3. By including white angled knockouts the symbol presents the wheel as being in motion. These knockouts also work for creating stencils used in spray paint application of the icon. Having just one version of the logo keeps things more consistent and allows viewers to more clearly understand intended message.

4. The human depiction in this icon is consistent with other body representations found in the ISO 7001 – DOT Pictograms. Using a different portrayal of the human body would clash with these established and widely used icons and could lead to confusion.

5. The leg has been moved forward to allow for more space between it and the wheel which allows for better readability and cleaner application of icon as a stencil.

–Accessible Icon Project

**Comment by tagliala** [comment] 2015-08-08 11:09
Duplicate of #2746, please +1 that request

Closing here

**Closed by tagliala** 2015-08-08 11:09 UTC
