### ISSUE TITLE
Icon request: windmill

### ISSUE THREAD

**Issue by amrocs** [FortAwesome/Font-Awesome#9074] opened 2016-04-28 07:04 UTC
Icon Request: Windmill for renewable energy
like this:

![icon_wind](https://cloud.githubusercontent.com/assets/2367923/14877883/e90ff102-0d5a-11e6-8ea3-8320fe130628.png)

[https://en.wikipedia.org/wiki/Wind_power](https://en.wikipedia.org/wiki/Wind_power)

**Comment by tagliala** [comment] 2016-04-28 08:23
Duplicate of #1300, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-28 08:23 UTC
