### ISSUE TITLE
Icon Request: Icon-Aparat

### ISSUE THREAD

**Issue by amv1989** [FortAwesome/Font-Awesome#10808] opened 2017-03-19 20:23 UTC
![aparat_icon_color_black_512](https://cloud.githubusercontent.com/assets/26528441/24084405/103718e2-0cff-11e7-8fa3-7db95cce65e1.png)

I plan to add this to my website, Aparat is very similar to YouTube but it is for Farsi language people only. 

Thank You :)

**Comment by tagliala** [comment] 2017-03-19 22:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5204 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-19 22:43 UTC
