### ISSUE TITLE
Icon request: fa fa-flutter

### ISSUE THREAD

**Issue by bhattashivaram** [FortAwesome/Font-Awesome#18035] opened 2021-06-28 07:04 UTC
**What can it be used for?**
flutter icon which is used in maximum design of in web design as well as other similar IT field.
![flutter](https://user-images.githubusercontent.com/40063269/123592899-97547080-d80d-11eb-985a-e1bd51b9fbd1.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "fa fa-flutter: " and is followed by the requested icon name (Ex: `Icon request: fa fa-flutter`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-06-28 07:40
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14878, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-06-28 07:40 UTC
