### ISSUE TITLE
Icon Request: fa-survey

### ISSUE THREAD

**Issue by uxitten** [FortAwesome/Font-Awesome#7846] opened 2015-11-08 08:40 UTC
i designing this logo
if this icon is approve please add to font awsome
![survey](https://cloud.githubusercontent.com/assets/1549069/11019521/45db8c82-85f4-11e5-857a-b2c4ac22fa66.jpg)

**Comment by tagliala** [comment] 2015-11-14 11:21
way too complicated to fit in 14px icon size

I'm going to consider this a duplicate of #2965

**Closed by tagliala** 2015-11-14 11:21 UTC
