### ISSUE TITLE
Icon Request: fa-blog

### ISSUE THREAD

**Issue by nirooj56** [FortAwesome/Font-Awesome#9826] opened 2016-08-28 08:01 UTC
I am trying to create a link in navigation bar with the company blog site. I could not find a suitable icon for it. please help.

**Comment by tagliala** [comment] 2016-08-28 08:57
Duplicate of #455 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-28 08:57 UTC
