### ISSUE TITLE
Icon Request: icon-issuu

### ISSUE THREAD

**Issue by hazelevans** [FortAwesome/Font-Awesome#5681] opened 2015-02-15 15:22 UTC
![logo-part1](https://cloud.githubusercontent.com/assets/11017291/6203688/ba73621e-b52e-11e4-886d-d3ed73593a24.png)

Issuu logo, http://issuu.com/, for people wishing to link to their stack of publications.

**Comment by tagliala** [comment] 2015-02-22 00:52
duplicate of #1993, please +1 that request

closing here

**Closed by tagliala** 2015-02-22 00:52 UTC
