### ISSUE TITLE
Icon request:  fa-palette

### ISSUE THREAD

**Issue by remacg** [FortAwesome/Font-Awesome#5600] opened 2015-02-06 12:09 UTC
Would be great to have a color palette icon, which would be a nice add to the Text Editor group of icons.  It could be used as an icon for changing font, fill, border, etc. colors.  Thanks!
![palette](https://cloud.githubusercontent.com/assets/4512138/6079100/e71c69ee-adce-11e4-9c67-3e553fc4287c.jpeg)

**Comment by tagliala** [comment] 2015-02-06 17:37
Duplicate of #244 , please +1 that request

closing here

**Closed by tagliala** 2015-02-06 17:37 UTC
