### ISSUE TITLE
Icon Request: fa-unity

### ISSUE THREAD

**Issue by YanPes** [FortAwesome/Font-Awesome#10409] opened 2016-12-21 11:24 UTC
It would be really nice if you could add a icon for Unity 3D. 
I would like to link the community forum in my website and I would love to work with Font-Awesome 
since I already use it.

[Reference Image](https://picload.org/image/racrpwaa/unity-logo.png)

Thank you so much!

**Comment by tagliala** [comment] 2016-12-21 12:37
Duplicate of #2888, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-21 12:37 UTC
