### ISSUE TITLE
Icon request: slash

### ISSUE THREAD

**Issue by AidanNichol** [FortAwesome/Font-Awesome#13422] opened 2018-06-26 09:34 UTC
Currently you have many icons combined with slash (e.g. bell, microphone) as well as the basic icon.

Publishing slash with as an icon in it's own right would allow it to be combined, via stacking, with any icon of our choice.

**Comment by tagliala** [comment] 2018-06-26 09:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3691, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-26 09:56 UTC
