### ISSUE TITLE
Google Classroom Icon

### ISSUE THREAD

**Issue by vsalguero** [FortAwesome/Font-Awesome#10820] opened 2017-03-21 17:11 UTC
It would be good a Google Classroom icon in Fontawesome, it is a very popular platform. [icon preview](https://icons8.com/web-app/32840/google-classroom) We use fontawesome in the web site [www.itcha.edu.sv](http://www.itcha.edu.sv/)

**Comment by PeterShaggyNoble** [comment] 2017-03-21 17:32
Dupe of #8836.

**Closed** 2017-03-21 17:33 UTC

**Comment by vsalguero** [comment] 2017-03-21 17:49
Ok, thank you!
