### ISSUE TITLE
Icon Request - ETZY

### ISSUE THREAD

**Issue by MarcButeau** [FortAwesome/Font-Awesome#6781] opened 2015-06-18 15:35 UTC
I could use this on the website I'm creating.
I currently have in the footer Facebook, Twitter, Instagram, Deviantart, Pinterest.

I would like to add ETZY (etzy.com) to my footer to direct browsers to my ETZY account.

Thanks.

**Comment by tagliala** [comment] 2015-06-20 11:02
etzy is not etsy?

**Comment by RRorg** [comment] 2015-06-21 18:56
He means etsy.

**Comment by Garrcomm** [comment] 2015-06-21 19:06
+1

**Comment by tagliala** [comment] 2015-06-21 19:46
duplicate of #1962 , please +1 that request

closing here

**Closed by tagliala** 2015-06-21 19:46 UTC
