### ISSUE TITLE
Icon Request: fa-soccer-pitch

### ISSUE THREAD

**Issue by aakash-cr7** [FortAwesome/Font-Awesome#4607] opened 2014-09-30 18:35 UTC
![sport-football-pitch-icon](https://cloud.githubusercontent.com/assets/7534680/4464052/683cadf4-48d0-11e4-90ec-b73a1b1a4213.png)

**Comment by aethior** [comment] 2022-03-17 22:37
Duplicate of #1415.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-17 22:40
Good catch, thanks

**Closed by tagliala** 2022-03-17 22:40 UTC
Labels: new icon, web application icons
