### ISSUE TITLE
Icon request: icon-withdrawal

### ISSUE THREAD

**Issue by darshanj** [FortAwesome/Font-Awesome#6902] opened 2015-07-08 12:18 UTC
I would like to use this icon for withdrawing money to bank.

**Comment by tagliala** [comment] 2015-07-09 19:24
any example?

**Comment by darshanj** [comment] 2015-07-10 04:33
like: https://www.iconfinder.com/icons/415358/atm_cashout_machine_withdrawal_icon

**Comment by tagliala** [comment] 2015-07-10 07:56
duplicate of #5103, please +1 that request

closing here

**Closed by tagliala** 2015-07-10 07:56 UTC
Labels: waiting for feedback
