### ISSUE TITLE
Icon request: flag-usa

### ISSUE THREAD

**Issue by nodesocket** [FortAwesome/Font-Awesome#10544] opened 2017-01-22 07:41 UTC
Don't need every country, and I know it's being American biased, but having the US flag would be super useful for lots of cases.

**Comment by tagliala** [comment] 2017-01-22 11:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1336, which is labeled as wontfix

Please note that the Font Awesome team could decide to implement the USA flag or other flags.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-22 11:29 UTC
