### ISSUE TITLE
font awesome pro 5.3.1 <i class="fab fa-creative-commons-zero"></i> svg not show

### ISSUE THREAD

**Issue by zabubakar** [FortAwesome/Font-Awesome#13851] opened 2018-08-30 18:59 UTC
See here: https://fontawesome.com/icons/creative-commons-zero?style=brands

**Comment by tagliala** [comment] 2018-08-30 19:02
closing here because this is a duplicate of #13851

**Closed by tagliala** 2018-08-30 19:02 UTC
