### ISSUE TITLE
Nuxtjs icons do not respect font-size

### ISSUE THREAD

**Issue by AlejandroMut** [FortAwesome/Font-Awesome#18729] opened 2022-02-21 00:51 UTC
On NuxtJs when in production mode, icons are completely out of scale. They do not scale based on the font-size CSS property. They look huge. Weirdly enough, this does not happen in DEV mode.

This occurred after updating to "@fortawesome/fontawesome-svg-core": "1.3.0". Had to revert to 1.2.36

**Comment by tagliala** [comment] 2022-02-21 08:25
I think this is a duplicate of #18666

**Comment by AlejandroMut** [comment] 2022-02-21 14:58
@tagliala yes, it seems to be the same problem.

**Comment by tagliala** [comment] 2022-02-21 15:13
Thanks for the heads-up

Closing here

I think this could also be related to #18654

**Closed as completed by tagliala** 2022-02-21 15:13 UTC
Labels: waiting for feedback
