### ISSUE TITLE
Icon Request: fa-spanner

### ISSUE THREAD

**Issue by pbowler** [FortAwesome/Font-Awesome#7605] opened 2015-10-04 10:28 UTC

**Comment by caduvieira** [comment] 2015-10-05 12:48
dupe of #6173 ?

**Comment by tagliala** [comment] 2015-10-05 20:37
@pbowler could you please clarify this request?

http://fontawesome.io/icon/wrench/ ?

**Comment by aethior** [comment] 2016-10-01 07:46
@tagliala I think you can close here and `spanner` alias for `fa-wrench` icon (check: #6173). 

> A wrench (or spanner outside of North America) is a tool used to provide grip and mechanical advantage in applying torque to turn objects—usually rotary fasteners, such as nuts and bolts—or keep them from turning.

(source: [en.wikipedia.org/wiki/Wrench](https://en.wikipedia.org/wiki/Wrench))

**Closed** 2016-10-01 11:36 UTC
