### ISSUE TITLE
Icon request: fa-trolleybus

### ISSUE THREAD

**Issue by denisbondar** [FortAwesome/Font-Awesome#9183] opened 2016-05-12 08:36 UTC
Icon need to indicate the type of public transport. You have already great icons that show transport. Suffice it to finish some missing elements.

<img src="http://blog.denisbondar.com/wp-content/uploads/2016/05/fa-trolleybus.png" />

**Comment by tagliala** [comment] 2016-05-12 08:41
Duplicate of #6318, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-12 08:41 UTC
