### ISSUE TITLE
Icon Request: fa-flower

### ISSUE THREAD

**Issue by HamilcarBarca** [FortAwesome/Font-Awesome#7149] opened 2015-08-05 16:55 UTC
In using the wonderful, beautiful and genius icons within FontAwesome, I required a flower icon to represent a florist menu item for a website.  I saw there was no such icon and I humbly request that there is one included in the next release.  I was thinking something similar to these basic images from a quick Google Images search (if you require that I come up with the artwork myself, please let me know and accept my apologies):
![flower](https://cloud.githubusercontent.com/assets/13663719/9091891/077375b0-3b60-11e5-9c57-ad2b93acdf2e.png)
![flower2](https://cloud.githubusercontent.com/assets/13663719/9091892/07789252-3b60-11e5-8833-8c3f3b2618db.png)
![flower3](https://cloud.githubusercontent.com/assets/13663719/9091893/0779bc72-3b60-11e5-8314-3aa4e3b5cbc7.jpg)

Thank you so much for your time in reading this request!  FontAwesome rocks my world!
-Lisa

**Comment by tagliala** [comment] 2015-08-05 17:26
duplicate of #2037 , please +1 that request and post there your examples

closing here

**Closed by tagliala** 2015-08-05 17:26 UTC

**Comment by johnnyshields** [comment] 2016-06-22 12:10
Flower is available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.
