### ISSUE TITLE
Icon request: icon-Bloglovin'

### ISSUE THREAD

**Issue by danaikou** [FortAwesome/Font-Awesome#11294] opened 2017-07-15 18:33 UTC
[Icon.zip](https://github.com/FortAwesome/Font-Awesome/files/1150529/Icon.zip)

**Comment by tagliala** [comment] 2017-07-15 18:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2334, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-15 18:59 UTC

**Comment by danaikou** [comment] 2017-07-16 07:30
thanks!
