### ISSUE TITLE
Icon-request: fa-globe / fa-globe-eu

### ISSUE THREAD

**Issue by caub** [FortAwesome/Font-Awesome#9416] opened 2016-06-18 18:25 UTC
The current fa-globe is USA-centric, when searching 'globe' on search engines, it's balanced between USA, Europe(+North Africa), and USA+Europe (
https://cloud.githubusercontent.com/assets/3134574/16172893/725aa2ea-3592-11e6-84a3-d61504b81ef8.png)

Would the last one be more representative? Another possibility could be http://findicons.com/files/icons/750/aquanox_mini/256/globe.png 
.

**Comment by tagliala** [comment] 2016-06-18 18:26
Duplicate of #281, please take a look at the comments there

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-18 18:26 UTC
