### ISSUE TITLE
Icon Request: fa-volume-mid

### ISSUE THREAD

**Issue by prcd** [FortAwesome/Font-Awesome#11066] opened 2017-05-15 20:34 UTC
An icon that fits in between `fa-volume-down` and `fa-volume-up`.

`fa-volume-off` has no sound waves
`fa-volume-down` has one sound wave
** `fa-volume-mid` would have two sound waves **
`fa-volume-up` has three sound waves

Could use aliases such as `fa-volume-0`, `fa-volume-1`, `fa-volume-2`, `fa-volume-3` and `fa-volume-mute`, `fa-volume-one-third`, `fa-volume-two-thirds`, `fa-volume-full`.

This would also suppliment the `fa-thermometer-*` and `fa-battery-*` groups nicely.

**Comment by tagliala** [comment] 2017-05-16 17:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1341, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-16 17:19 UTC

**Comment by prcd** [comment] 2017-05-16 22:42
Done, cheers. Will search in future - sorry!
