### ISSUE TITLE
Icon request: icon-mouth / icon-lips / icon-speaking

### ISSUE THREAD

**Issue by dondencker** [FortAwesome/Font-Awesome#7208] opened 2015-08-12 12:42 UTC
I was looking for something to symbolize someone speaking. Could easily be a mouth, perhaps with some kind of sound waves :o) 

![speak-2-512](https://cloud.githubusercontent.com/assets/4710999/9224107/436fdd60-4100-11e5-821f-4203e9eaf7dc.png)
![lips-2-512](https://cloud.githubusercontent.com/assets/4710999/9224108/4370ab28-4100-11e5-9d79-477c551aab8f.png)

**Comment by tagliala** [comment] 2015-08-15 09:32
probably a duplicate of #2096, please +1 that request

feel free to comment if I'm wrong

closing here

**Closed by tagliala** 2015-08-15 09:32 UTC
