### ISSUE TITLE
Icon Request: fa-warehouse

### ISSUE THREAD

**Issue by GerritP** [FortAwesome/Font-Awesome#11471] opened 2017-08-31 00:41 UTC
Hi there,

a warehouse icon would be very useful.

![image](https://user-images.githubusercontent.com/31493266/29901021-3c89af12-8dbb-11e7-81dc-187e6c580527.png)

Greetings

**Comment by tagliala** [comment] 2017-08-31 09:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4560 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-31 09:17 UTC
