### ISSUE TITLE
Icon Request: Pillar

### ISSUE THREAD

**Issue by Nazarah** [FortAwesome/Font-Awesome#15727] opened 2019-10-24 08:15 UTC
Can you please add a pillar / beam in font awesome collection?
This is specifically needed in construction category.
example: https://www.google.com/search?q=pillar+icon&rlz=1C5CHFA_enFI847FI847&sxsrf=ACYBGNRNSWf-JxxoNtfS1s20MroZJRpEiQ:1571904164279&tbm=isch&source=iu&ictx=1&fir=gIYzepSEeOBemM%253A%252CSqJ613LxcOEzZM%252C_&vet=1&usg=AI4_-kQcmxkWdqmYHzzGEh6EhWnHFdaZNg&sa=X&ved=2ahUKEwivrtSqt7TlAhVx_SoKHTiHCosQ9QEwAHoECAcQLA#imgrc=gIYzepSEeOBemM:

i-class name could be: fa-pillar, fa-beam, fa-pedestal, etc.

**Comment by tagliala** [comment] 2019-10-24 11:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8239, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-10-24 11:30 UTC
