### ISSUE TITLE
Icon Request: ingot

### ISSUE THREAD

**Issue by zengLH1981** [FortAwesome/Font-Awesome#13187] opened 2018-05-22 12:37 UTC
元宝(yuan bao)
they are made in the shape of the gold and silver ingots that were used as money in ancient China

![image](https://user-images.githubusercontent.com/16136238/40362603-94ec7f94-5dff-11e8-8f84-4291e756ecbe.png)

**Comment by tagliala** [comment] 2018-05-22 13:27
Hi!

Thanks for being part of the Font Awesome Community.

ingot is a duplicate of #7729, please add a 👍  reaction to that request.

If this is a different request or a brand, please provide more details

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-22 13:27 UTC

**Comment by zengLH1981** [comment] 2018-05-23 02:52
my ingot's shape is not same as  #7729
