### ISSUE TITLE
Problem with firefox

### ISSUE THREAD

**Issue by auryn111** [FortAwesome/Font-Awesome#5729] opened 2015-02-19 20:34 UTC
Hello,
I have a wordpress blog, with Evolve theme. Inside this theme, there is 3 Front Page Content Boxes, where I need to put some fortawesome icons.
But in Firefox, my first content boxe doesn't show up. I download the fortawesome 4.3.0 version in my server, but it's not changing. Can you help me ? 
Thank you.
![2](https://cloud.githubusercontent.com/assets/11080737/6275408/1d05547a-b87f-11e4-9e59-d01db3a265dd.jpg)

![1](https://cloud.githubusercontent.com/assets/11080737/6275393/f6fef3d0-b87e-11e4-87f9-04dc4c90c206.jpg)

**Comment by tagliala** [comment] 2015-02-19 23:39
Please check our troubleshooting guidelines, especially point 4: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Closing here but feel free to comment

**Closed by tagliala** 2015-02-19 23:39 UTC

**Comment by auryn111** [comment] 2015-02-20 07:26
Hi, I have already check those points, but I don't use any of this extensions ...

**Comment by tagliala** [comment] 2015-02-20 09:15
could you please provide me a link to your website?

**Comment by auryn111** [comment] 2015-02-20 09:22
acfvlb.equitherapie.fr
Thank you

Isabelle Chevrier

2015-02-20 10:16 GMT+01:00 Geremia Taglialatela <notifications@github.com>:

**Comment by tagliala** [comment] 2015-02-20 12:18
A plugin that you are using (or your theme is using) is loading an old version of fontawesome which have priority in firefox

![screen shot 2015-02-20 at 12 10 47](https://cloud.githubusercontent.com/assets/556268/6285918/9dcd12b2-b8f9-11e4-95e5-bbb74aa65eab.png)

**Comment by auryn111** [comment] 2015-02-20 12:37
The problem is that my visitors have the same problem...So I can't tell
them to check all the plugins... I need to put another favicon, fa-book is
working on firefox :(

Isabelle Chevrier

2015-02-20 13:18 GMT+01:00 Geremia Taglialatela <notifications@github.com>:

**Comment by tagliala** [comment] 2015-02-21 12:15
> The problem is that my visitors have the same problem...So I can't tell
them to check all the plugins... I need to put another favicon, fa-book is
working on firefox :(

The problem is not with your visitors. A theme you are using is using a plugin that loads an old version of fontawesome. You have to fix this or contact the plugin/theme author. Sorry I can't help more

**Comment by auryn111** [comment] 2015-02-21 12:20
ok thank you

Isabelle Chevrier

2015-02-21 13:16 GMT+01:00 Geremia Taglialatela <notifications@github.com>:
