### ISSUE TITLE
Icon request: mushroom

### ISSUE THREAD

**Issue by SchwabNicolas** [FortAwesome/Font-Awesome#18625] opened 2022-01-30 17:43 UTC
**What can it be used for?**
Fungi is one of the biggest life kingdoms existing on Earth. Now more than ever, many people realize their importance in ecosystems. It's also an important source of food in many parts of the the world.
Use cases could be websites or applications about environment, cooking, mushroom cultivation or scientific publishing on fungi.

**Example image (optional)**
[Example image](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRviaaxOU_8dlQgc4vrzPW412RUVE1Y9FfXZg&usqp=CAU).

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2022-01-30 18:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4127 and it has been implemented in FA6 Pro:
- https://fontawesome.com/v6.0/icons/mushroom?s=duotone

If you want to know why some icons are included in FA Pro, we have an answer in our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs)

Closing here

**Closed as completed by tagliala** 2022-01-30 18:12 UTC
