### ISSUE TITLE
Icon Request: fa-formula

### ISSUE THREAD

**Issue by twasyl** [FortAwesome/Font-Awesome#6241] opened 2015-04-16 21:17 UTC
Hello,

It would be really nice to have a formula icon like the icon present in Excel: [this one](http://www.online-tech-tips.com/wp-content/uploads/2011/04/Formula-Icon.png).
I plan to use this icon in [SlideshowFX](https://github.com/twasyl/SlideshowFX). I already have a [PNG icon](https://github.com/twasyl/SlideshowFX/blob/master/SlideshowFX-app/src/main/resources/com/twasyl/slideshowfx/images/function.png) but as I just decided to use [FontAwesomeFX](https://bitbucket.org/Jerady/fontawesomefx/) I would like to replace my old icon.

Many thanks in advance.

**Comment by tagliala** [comment] 2015-04-16 21:43
duplicate of #2675 , pleae +1 that request

closing here

**Closed by tagliala** 2015-04-16 21:43 UTC
