### ISSUE TITLE
Icon Request: fa-pray

### ISSUE THREAD

**Issue by gustavohellwig** [FortAwesome/Font-Awesome#8124] opened 2015-12-08 21:03 UTC
Please, many christians will be happy to use a icon like Pray, like this:<img src="http://www.wheatonbible.org/Content/10713/Icons/prayer-icon.png" width="24" height="24"> or <img src="https://cdn0.iconfinder.com/data/icons/man-poses/512/pray-512.png" width="24" height="24"> or <img src="https://cdn0.iconfinder.com/data/icons/dogma/500/pray-512.png" width="24" height="24">

**Comment by jnovack** [comment] 2015-12-09 00:02
How would one use this?  On a "Click to send Prayer" button?  I could definitely see 5, maybe 6 sites doing this. Definitely a priority.  +1

**Comment by MrZach** [comment] 2015-12-09 04:08
+1

**Comment by PeterShaggyNoble** [comment] 2015-12-09 15:40
-1 to any religious iconography.

**Comment by tagliala** [comment] 2015-12-09 15:50
Duplicate of #1855, please +1 that request

closing here

I'm not going to debate the use case, there are praying hands in emoji too :pray:

**Closed by tagliala** 2015-12-09 15:50 UTC
