### ISSUE TITLE
Icon request: Bench

### ISSUE THREAD

**Issue by JaHe-Facito** [FortAwesome/Font-Awesome#18067] opened 2021-07-12 09:30 UTC
**What can it be used for?**
You already have chair/couch but i'm missing a wooden bench / beach chair.

**Example image (optional)**
something like this 
![image](https://user-images.githubusercontent.com/87305034/125264803-7b1ffb80-e304-11eb-8209-6dfeed127c9d.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-07-12 09:48
Hi!

Thanks for being part of the Font Awesome Community.

I think this request is a duplicate of #16451, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-07-12 09:48 UTC
