### ISSUE TITLE
Icon request: icon-dice (or: icon-pawn)

### ISSUE THREAD

**Issue by top-jonathan** [FortAwesome/Font-Awesome#12103] opened 2018-01-15 12:35 UTC
Right now there is a nice gamepad icon to represent 'videogaming'.
I am looking for some symbol to represent board games. This could be a dice or a pawn.

**Comment by tagliala** [comment] 2018-01-15 12:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2622 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-15 12:41 UTC
