### ISSUE TITLE
Icon request: Prezi

### ISSUE THREAD

**Issue by katethegreat-coder** [FortAwesome/Font-Awesome#16604] opened 2020-05-09 11:30 UTC
**What can it be used for?**
It could be used to link to a prezi presentation

**Example image (optional)**
a logo in colour and a monochrome one : 
![kisspng-prezi-presentation-program-computer-software-micro-5b151380110d44 7590718415281079040699](https://user-images.githubusercontent.com/58825279/81472615-8c99df00-91f9-11ea-8610-8a97c87cb967.png)

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-09 12:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2089, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-09 12:35 UTC
