### ISSUE TITLE
Icon Request: fa-map

### ISSUE THREAD

**Issue by SmugWimp** [FortAwesome/Font-Awesome#6872] opened 2015-07-04 02:14 UTC
I would like to see a 'map' icon, similar to a family of one of these (the first icon is white):

![maps](https://cloud.githubusercontent.com/assets/1253764/8506085/20851d8e-2246-11e5-968c-73f0aeeb6d94.png)

![ic_menu_mapmode](https://cloud.githubusercontent.com/assets/1253764/8506091/8fbbf402-2246-11e5-8deb-0edf84505d6d.png)

![map_hybrid](https://cloud.githubusercontent.com/assets/1253764/8506094/9e333bf8-2246-11e5-9d0a-71ef2176aa1b.png)

![map-2-512](https://cloud.githubusercontent.com/assets/1253764/8506099/cbccd54c-2246-11e5-9ea2-0620a85816e3.png)

**Comment by tagliala** [comment] 2015-07-04 10:20
duplicate of #1023 , please +1 that request

closing here

**Closed by tagliala** 2015-07-04 10:20 UTC
