### ISSUE TITLE
Bear icon

### ISSUE THREAD

**Issue by Theolodewijk** [FortAwesome/Font-Awesome#16390] opened 2020-03-30 16:53 UTC
it would be nice if there would be a bear icon, related to the corona virus and action.

The children are now going around the neighborhoods looking for bears that are placed behind a window.

**Comment by tagliala** [comment] 2020-03-30 17:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1121, please add a 👍 reaction to that request.

> The children are now going around the neighborhoods looking for bears that are placed behind a window.

 😅

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-30 17:06 UTC

**Comment by Theolodewijk** [comment] 2020-03-30 19:57
Thansk but I mean somting like this image https://waadhoekevoorelkaar.nl/themes/waadhoekevoorelkaar/img/bear.png

**Comment by Theolodewijk** [comment] 2020-03-30 19:58
mebay an idea before closing something to wait a response waht somone means!

**Comment by tagliala** [comment] 2020-03-30 20:07
Hi

> mebay an idea before closing something to wait a response waht somone means!

Issues can be reopen, and there is already a request with the same name. Also, we provide an [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) to help creating requests.

If you can elaborate this request, how it is related to covid, and how it should look like I will be more than happy to reopen

**Comment by Theolodewijk** [comment] 2020-03-30 20:19
I tried it and even now with a link with example but if you don't want to then don't. I make something myself hoped that Fontawsome can think along these crazy times but unfortunately!

keeping close and have a nice evening.
