### ISSUE TITLE
Icon request: fa-remember

### ISSUE THREAD

**Issue by ruimelodev** [FortAwesome/Font-Awesome#9339] opened 2016-06-05 03:46 UTC
Today I needed to create a button where the user could click and active an option to "remember user preferences" in the application. I searched for an icon in the FontAwesome library that could resemblance something to be remembered but couldn't find anything.

I thought it would be useful to have an icon like the symbolic finger with a knot:

![image](https://cloud.githubusercontent.com/assets/16306125/15803488/f7ae849a-2ad7-11e6-971f-7a57a20b7e0c.png)

**Comment by tagliala** [comment] 2016-06-05 09:55
I'm going to consider this a duplicate of #1196, please +1 that request and post there your example

**Closed by tagliala** 2016-06-05 09:55 UTC
