### ISSUE TITLE
Icon request: fa-warning-o

### ISSUE THREAD

**Issue by tojonmz** [FortAwesome/Font-Awesome#6964] opened 2015-07-16 15:07 UTC
Apologies if I'm missing it, but it might be nice to have a variant "open" `fa-warning-o` (aka. fa-exclamation-triangle).
http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/

We've been using glyphicons' warning (which is an open style) for various Mozilla [work](https://github.com/mozilla/treeherder/pull/769) where otherwise we could have also considered fa.

Best wishes :)

**Comment by tagliala** [comment] 2015-07-16 19:04
duplicate of #5718, please +1 that request

closing here

**Closed by tagliala** 2015-07-16 19:04 UTC
