### ISSUE TITLE
Icon Request : fa-aparat

### ISSUE THREAD

**Issue by MehdiPiAr** [FortAwesome/Font-Awesome#9261] opened 2016-05-23 13:14 UTC
hi
this is a popular site's icon  and if u add it's icon to your collection , I'll be thankful
http://www.aparat.com/public/public/images/logo/v2/aparat_icon_color_black_1024.png

**Comment by aethior** [comment] 2016-07-08 01:16
@tagliala It's a brand icon: https://en.wikipedia.org/wiki/Aparat

**Comment by tagliala** [comment] 2016-07-08 10:42
Duplicate of #5204, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-08 10:42 UTC
