### ISSUE TITLE
Icon request: Smartcard

### ISSUE THREAD

**Issue by ganeshkhatri** [FortAwesome/Font-Awesome#16605] opened 2020-05-09 13:41 UTC
**What can it be used for?**
Need a smartcard icon as smartcards are getting common.

**Example image (optional)**
![contactless+pay+payment+icon-1320166083744286791_512](https://user-images.githubusercontent.com/56068793/81475285-d0580d00-9228-11ea-8a67-8516b66360da.png)

**Comment by tagliala** [comment] 2020-05-09 13:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1696, please add a 👍 reaction to that request and post there your example.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-09 13:46 UTC
