### ISSUE TITLE
Icon Request: fa-fuel

### ISSUE THREAD

**Issue by cotnals** [FortAwesome/Font-Awesome#8268] opened 2016-01-05 04:38 UTC
Hi, it would be great if there is an icon "Fuel".
I think the icon shape like fuel gas gun.
![stock-vector-icon-of-gun-for-fuel-pump-with-a-drop-of-fuel-stock-vector-353513507](https://cloud.githubusercontent.com/assets/16333061/12107890/556a91ce-b3b8-11e5-8dc7-457f4464d82a.jpg)
![stock-vector-vector-gas-station-icon-215224078](https://cloud.githubusercontent.com/assets/16333061/12107891/55736d3a-b3b8-11e5-9ace-0b199380657d.jpg)

**Comment by tagliala** [comment] 2016-01-05 11:49
duplicate of #1676 , please +1 that request

closing here

**Closed by tagliala** 2016-01-05 11:49 UTC
