### ISSUE TITLE
Icon request: stopwatch / timer?

### ISSUE THREAD

**Issue by morrow95** [FortAwesome/Font-Awesome#6572] opened 2015-05-27 22:31 UTC
Just came across the need for this today and was surprised there is nothing that can really be used.  Yes, there is the clock-o, but when you are using that for something actually time related then have the need for a timer it is not of much use.

**Comment by tagliala** [comment] 2015-05-29 19:20
duplicate of #1340, please +1 that request

closing here

**Closed by tagliala** 2015-05-29 19:21 UTC
