### ISSUE TITLE
Icon Request: fa-bandcamp

### ISSUE THREAD

**Issue by mgkii** [FortAwesome/Font-Awesome#9805] opened 2016-08-24 15:13 UTC
Hello,

I am in the works of creating a website for a local music festival. 
I am just reviewing assets before I make my final decision based up what I am using. 
Currently, I have a wordpress theme in mind that associates with Font Awesome.
I will be using some icons - ex: youtube, soundcloud, lastfm, etc. but I do not see an icon yet for bandcamp. Can it be possibly that your team can create an icon that I can use for bandcamp? A lot of musicians have this, and I think it would be a great icon to be apart of FA's archive.

If you are able to make this possible, how long would it take to be able to use live?
If it takes a while, is there any way I can speed up the process by providing my on .svg file or whatever you recommend? 

https://bandcamp.com/
Perhaps something like this: https://image.freepik.com/free-icon/bc-logo_318-38028.png

Please feel free to reach me at hello@mgkii.com

Thank you,
Mike

**Comment by tagliala** [comment] 2016-08-24 15:20
Duplicate of #1725, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-24 15:20 UTC
