### ISSUE TITLE
Icon request: mongodb-leaf

### ISSUE THREAD

**Issue by saivinaygondrala** [FortAwesome/Font-Awesome#18535] opened 2021-12-22 11:29 UTC
**What can it be used for?**
it will be used in my project and it is a popular database 

**Example image (optional)**

![mongo](https://user-images.githubusercontent.com/67357886/147085828-1978e8b5-caf1-48b4-9376-ed1183007566.png)

**Icon request checklist**
- [ `single icon`] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ✔] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✔ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ✔] I have included at least one example image if it could be helpful (optional)
- [ ✔] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-12-23 18:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2725, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-12-23 18:15 UTC
