### ISSUE TITLE
fontawesome home site rendering issue

### ISSUE THREAD

**Issue by mpouzko** [FortAwesome/Font-Awesome#9683] opened 2016-07-30 19:43 UTC
Hi. 
I've just mentioned, that when i add another slash at the end of url 
[http://fontawesome.io/icons//](http://fontawesome.io/icons//)
the page is not rendering properly - some resources like css and images cannot be found and loaded.
see here [https://snag.gy/s5gcIw.jpg](https://snag.gy/s5gcIw.jpg)
Pls, check it out. 
Best, Max

**Comment by tagliala** [comment] 2016-07-30 20:36
Duplicate of #6551

Why you should add another slash at the end of the url?

Btw I cannot fix this, font awesome is using relative paths to find assets to keep compatibility with local docs

```html
<link rel="stylesheet" href="../assets/css/site.css">
<link rel="stylesheet" href="../assets/css/pygments.css">
<link rel="stylesheet" href="../assets/font-awesome/css/font-awesome.css">
```

**Closed by tagliala** 2016-07-30 20:36 UTC
