### ISSUE TITLE
Icon Request for Outlook

### ISSUE THREAD

**Issue by 7vn** [FortAwesome/Font-Awesome#10405] opened 2016-12-20 23:53 UTC
Hi,
I would like to request an icon for Outlook, seeing how it is getting really popular.
fa-outlook

**Comment by tagliala** [comment] 2016-12-21 12:40
Duplicate of #2884, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-21 12:40 UTC
