### ISSUE TITLE
IE8 IFrame Icons appear in the first page, but the icons disappear in the rest pages

### ISSUE THREAD

**Issue by wonyun** [FortAwesome/Font-Awesome#8427] opened 2016-01-27 12:20 UTC
as the title saying，the icons appear in the first page of ie8 iframe, while icons disappear in the rest pages，but refresh the pages, icons  appear. who can help me? @tagliala

top frame:  meta content=IE=EmulateIE7
frame:  meta content=IE=edge

**Comment by tagliala** [comment] 2016-01-27 12:34
possible duplicate of #2717

**Comment by wonyun** [comment] 2016-01-28 05:32
@tagliala , the situation I encoutered is the opposite of [#2717](https://github.com/FortAwesome/Font-Awesome/issues/2717)，on IE8 iframe，icons appear in the frist page, while icons disappear in the rest pages, but icons appear when refresh, so I make a demo as follows:

 
![image](https://cloud.githubusercontent.com/assets/4994497/12635677/dd8066c8-c5c0-11e5-9bd2-13b3f710c51b.png)

![image](https://cloud.githubusercontent.com/assets/4994497/12635703/30e3394e-c5c1-11e5-94a5-e6c6c490ab16.png)

![image](https://cloud.githubusercontent.com/assets/4994497/12635731/68ae65e2-c5c1-11e5-9232-10bd3ca8f5bf.png)

my top frame code below:
`
  <!DOCTYPE html>
  <html>
  <head>
      <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
      <meta charset="utf-8">
      <title>ie8 frame icon test</title>
  </head>
  <body style="width:800px;height:800px;">
  <iframe src="./a.htm" width="400" height=200"></iframe>
  </body>
  </html>
`

and the first page a.htm of ie8 frame code  below:

`
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta charset="utf-8">
    <title>质检报告</title>
    <link rel="stylesheet" href="./css/font-awesome.css" />
</head>
<body>
<a href="./aa.htm"><i class="ui-icon">&#xf00c;</i>aa</a>
</body>
</html>
`

the secod page aa.htm of ie8 frame code below:

`
  <!DOCTYPE html>
  <html>
  <head>
      <title>xxx</title>
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <link rel="stylesheet" href="./css/font-awesome.css" />
  </head>
  <body>
   <i class="ui-icon">&#xf058;</i> fa-lg
  </body>
  </html>
`

**Comment by tagliala** [comment] 2016-01-28 09:05
Could you please try loading font awesome from the CDN?

**Comment by wonyun** [comment] 2016-01-28 10:47
@tagliala , above is just a demo, actually, my application loads font awesome from the CDN, they have the same problems

**Comment by drfreek** [comment] 2016-09-28 10:14
It's IE issue also under 11 version, i solved this removing headers:
Pragma: no-cache
Cache-Control: no-store, no-cache

**Comment by tagliala** [comment] 2022-03-13 13:46
Unfortunately we weren't able to fix this random issues with IE8

I'm going to close here because IE8 is not supported by FA6

**Closed by tagliala** 2022-03-13 13:46 UTC
Labels: IE8, cantfix
