### ISSUE TITLE
New Issue Icon request: icon-gym

### ISSUE THREAD

**Issue by bluebit27** [FortAwesome/Font-Awesome#6244] opened 2015-04-16 23:30 UTC
icon-gym or icon-dumbell or icon-bicep
Basically I have a blog about fitness and one of the categories if called exercise, I'm currently using the bike, but since it's a weight training blog, a bicycle isn't a good fit. Looking for an icon-dumbbell or icon-bicep, I need just a black dumbbell
https://www.google.com/search?q=gym+icon&biw=1288&bih=686&source=lnms&tbm=isch&sa=X&ei=zUQwVYDOC9froATfn4GIDw&ved=0CAYQ_AUoAQ#tbm=isch&q=gym+icon+dumbbell&spell=1

icon-supplement
Something that looks like a supplement bottle, like below but without the leaf in the middle, just a black bottle. 
http://drdeborahmd.com/sites/drdeborahmd.com/files/DGordon%201200%20px_icon-supplements.png

**Comment by tagliala** [comment] 2015-04-30 23:22
Dumbell is here: #1500 

 Supplements may be represented by #1778 or  #4328

Let me know, otherwise we need a better title for this issue

**Comment by bluebit27** [comment] 2015-05-01 00:53
how to I add it now? I typed: icon-dumbbell

in the custom icon class and it didn't work :(

**Comment by joelworsham** [comment] 2015-05-16 18:33
+1 I really want this too

**Comment by ShamanFromSiberia** [comment] 2015-07-01 07:44
+1

**Comment by tagliala** [comment] 2015-07-01 10:31
duplicate of #1500

**Closed by tagliala** 2015-07-01 10:31 UTC
Labels: waiting for feedback
