### ISSUE TITLE
Icon Request: fa-alipay

### ISSUE THREAD

**Issue by xcxnig** [FortAwesome/Font-Awesome#12834] opened 2018-04-11 09:13 UTC

**Comment by tagliala** [comment] 2018-04-11 10:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3854 or #4597, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-11 10:50 UTC
