### ISSUE TITLE
Icon request: table-row-insert-x, table-row-delete, table-column-insert-x, table-column-delete

### ISSUE THREAD

**Issue by gnasen** [FortAwesome/Font-Awesome#13814] opened 2018-08-24 08:54 UTC
### What can it be used for?

These are various icons for editing a table in text editor,
ex. Adding/deleting a table row or column (above/bellow or right/left), table-wizard-icon, character paint icon, foreground color icon, etc.

**Comment by tagliala** [comment] 2018-08-24 08:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4552, please add a 👍  reaction to that request.

I'm going to fix #4522's title to cover all four cases

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-24 08:58 UTC
