### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by Discover-Awesome** [FortAwesome/Font-Awesome#18420] opened 2021-11-07 20:27 UTC
Unreal Engine

**What can it be used for?**
Unreal Engine Logo. This will be used **for people like me who make and build assets and/or visual effects or models for EPIC's Unreal Engine video game maker.**

**Example image (optional)**
Image Link: 
https://epicgames.ent.box.com/s/c2m8idcyejqvg5mjf4e2q73b7jbaghft/file/809821474208

![image](https://user-images.githubusercontent.com/76115650/140660864-2911dff0-4659-4250-95d5-20c9a35fc9aa.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
![UE_Logo_icon-only_black](https://user-images.githubusercontent.com/76115650/140660893-a29fed92-4a36-4532-a67f-ac6c137dbac3.png)

**Comment by tagliala** [comment] 2021-11-07 20:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11420, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-11-07 20:44 UTC

**Comment by Discover-Awesome** [comment] 2021-11-08 12:45
I see this Unreal Engine request was back on Aug 20, 2017. If this was requested 4 years ago and still not delivered, then there is a zero percent chance this will be completed.
