### ISSUE TITLE
Icon Request: icon-blogger

### ISSUE THREAD

**Issue by moongod101** [FortAwesome/Font-Awesome#9469] opened 2016-06-24 14:51 UTC
Blogger
<a href='http://blogger.com'>blogger.com</a>

**Comment by tagliala** [comment] 2016-06-24 14:52
Duplicate of #1088 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-24 14:52 UTC
