### ISSUE TITLE
Repo updates and changelog

### ISSUE THREAD

**Issue by tomciopp** [FortAwesome/Font-Awesome#12076] opened 2018-01-11 03:46 UTC
I'm using font awesome through npm and have been trying to find the most recent changes to the project. (I like to take a look at changes before updating to most recent version in case anything breaks) Has development moved to another repository? It looks like code has changed recently but it is not reflected in this repo.

**Comment by PeterShaggyNoble** [comment] 2018-01-11 10:25
See #7908

**Comment by tagliala** [comment] 2018-01-11 12:33
Closing as a duplicate of #12035 and #11908 

FWIW, I would prefer to keep open unresolved issues but I respect the decision of closing them

**Closed by tagliala** 2018-01-11 12:33 UTC
