### ISSUE TITLE
Icon Request: fa-mouse-cursor

### ISSUE THREAD

**Issue by LukasDadej** [FortAwesome/Font-Awesome#5815] opened 2015-02-28 17:01 UTC
![mouse-cursor-icon](https://cloud.githubusercontent.com/assets/2370041/6426972/a3aee1c2-bf72-11e4-9cb7-03d1dcd77c23.jpg)

Hello everyone.

Many thanks to all of you for a such great tool as the Font-awesome!

We would like to add a classic mouse curson icon from Windows and used it in Photoshop to enhance the clickable area.

Another requirement is to hand-pointer, only these two.

Thank you for your response, Lukas Dadej - CEO of JoomLabs s.r.o.

**Comment by tagliala** [comment] 2015-03-11 20:02
duplicate of #1095, please +1 that request

closing here

**Closed by tagliala** 2015-03-11 20:02 UTC
