### ISSUE TITLE
Leetcode

### ISSUE THREAD

**Issue by SaiLikhith7** [FortAwesome/Font-Awesome#16505] opened 2020-04-22 01:08 UTC
**What can it be used for?**
This can be used as a favicon in our websites or blogs to redirect users to our social media profile

**Example image (optional)**
![image](https://user-images.githubusercontent.com/32040901/79929570-197c2480-8414-11ea-9358-c92a53916a7f.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by SaiLikhith7** [comment] 2020-04-22 01:09
There are existing issues with same request but till now, no reply came from developers, so I would like to ask for it by raising new issue.

**Comment by tagliala** [comment] 2020-04-22 07:35
Hi @SaiLikhith7 

Thanks for being part of the Font Awesome Community.

> There are existing issues with same request but till now, no reply came from developers, so I would like to ask for it by raising new issue.

As far as a request is open, it is valid. This is a duplicate of #15337, please 👍 that request

Please also take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), you will find a lot of information on how requests work

Closing here

**Closed by tagliala** 2020-04-22 07:35 UTC
