### ISSUE TITLE
Icon request: icon-engine

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#15704] opened 2019-10-17 23:54 UTC
**What can it be used for?**
Fo represent an car engine

**Example image (optional)**

**Icon request checklist**
- [ cob/piston/gas] This is a single icon or matched pair

**Comment by tagliala** [comment] 2019-10-18 06:24
Hi!

Thanks for being part of the Font Awesome Community.

Could this be considered a duplicate of #4175 ?

**Comment by lucasmantoani** [comment] 2019-10-18 07:54
No, the check-engine light is something different from the engine representation that he talk about IMO

**Comment by afroty** [comment] 2019-12-20 20:22
+1

**Comment by aethior** [comment] 2022-04-18 21:59
I think this request can be considered a duplicate of #15275.

cc/ @tagliala

**Closed** 2022-04-19 11:12 UTC
Labels: waiting for feedback
