### ISSUE TITLE
Icon request: fab fa-ivoox

### ISSUE THREAD

**Issue by yovantichrist** [FortAwesome/Font-Awesome#12958] opened 2018-04-27 07:20 UTC
iVoox it's a audio on-demand community where podcasts can upload their episodes.

![ivoox](https://user-images.githubusercontent.com/29682106/39349713-36bf7938-49fc-11e8-874f-a7c2a53030a4.png)

https://www.ivoox.com/en

**Comment by tagliala** [comment] 2018-04-27 08:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5875, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-27 08:30 UTC
