### ISSUE TITLE
Icon request: icon-google-mybusiness

### ISSUE THREAD

**Issue by Venmore** [FortAwesome/Font-Awesome#18941] opened 2022-04-22 15:10 UTC
As Google+ has gone, more and more businesses want to link to their Google 'My Business' account and it would be good to have an icon in Font-Awesome to do this.
Thanks

**Comment by Venmore** [comment] 2022-04-22 15:37
found example
https://ssl.gstatic.com/gb/images/a/ea554714e7.png
![ea554714e7](https://user-images.githubusercontent.com/19739442/164747835-320aebd4-89e0-465b-8dca-15da0e367bf2.png)

**Comment by tagliala** [comment] 2022-04-22 15:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2412, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-04-22 15:47 UTC
