### ISSUE TITLE
Icon Request: fa-podium

### ISSUE THREAD

**Issue by lsmpascal** [FortAwesome/Font-Awesome#10327] opened 2016-12-07 13:58 UTC
Hi !
I manage a web site of games and I will be happy to have a podium icon for the hiscores list and a lot of other usages.
![podium_icon](https://cloud.githubusercontent.com/assets/2376608/20970164/81a29a74-bc8c-11e6-8cbc-1eb042defefc.png)

and may be a -o version :
![podium-o_icon](https://cloud.githubusercontent.com/assets/2376608/20970366/906227ea-bc8d-11e6-8b65-5ef5c0d1fa85.png)

Thank you very much.

**Comment by tagliala** [comment] 2016-12-08 14:43
Duplicate of #4467, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-08 14:43 UTC
