### ISSUE TITLE
Icon Request: fa-crucifix

### ISSUE THREAD

**Issue by enovision** [FortAwesome/Font-Awesome#10322] opened 2016-12-06 13:10 UTC
A simple crucifix that can be used in front of a date that somebody is passed away (died). Usually an asterisk is used for a birth date and a crucifix for a passed away date.

I've added an image with all icons that are used to identify the personal states of people, but the crucifix is really missing.

![peoples_state](https://cloud.githubusercontent.com/assets/1536241/20926611/93826726-bbbd-11e6-91bd-78fafd75705d.png)

**Comment by tagliala** [comment] 2016-12-07 00:09
Duplicate of #1611, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-07 00:09 UTC
