### ISSUE TITLE
Icon request: fa-resp

### ISSUE THREAD

**Issue by mustafapiynirci** [FortAwesome/Font-Awesome#9402] opened 2016-06-13 17:43 UTC
Icon that represents responsive with mobile, tablet and desktop screen sizes.

https://gyazo.com/8337b7da1d109f2142c0621c0d5810a3

**Comment by tagliala** [comment] 2016-06-13 17:50
Duplicate of #1446, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-13 17:50 UTC

**Comment by mustafapiynirci** [comment] 2016-06-13 18:17
Yes im sorry, thankyou

**Comment by tagliala** [comment] 2016-06-13 19:41
no problem :+1:
