### ISSUE TITLE
Icon Request: fa-lineme

### ISSUE THREAD

**Issue by shihao316558512** [FortAwesome/Font-Awesome#9207] opened 2016-05-14 01:10 UTC
fa-line or fa-lineme
>a sns
>[Official website](http://line.me/en/)

**Comment by tagliala** [comment] 2016-05-14 10:19
Duplicate of #2631 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-14 10:19 UTC
