### ISSUE TITLE
Icon Request: fa-new

### ISSUE THREAD

**Issue by alexsxx** [FortAwesome/Font-Awesome#9762] opened 2016-08-17 09:10 UTC
Icon that represent something new, like fa-certificate with "new" written above
![image](https://cloud.githubusercontent.com/assets/20901061/17731043/c8e6299c-646b-11e6-85ab-8a55904d29a3.png)

Could be useful for indicate a new element
Thank you

**Comment by tagliala** [comment] 2016-08-17 09:39
Duplicate of #1331, please add a 👍  reaction to that request

Please note that icons should be "interantional" glyphs, and _new_ isn't

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-17 09:39 UTC
