### ISSUE TITLE
"Ever-Green" MaxCDN link without version info for Speed, Reliability, and Convenience !!

### ISSUE THREAD

**Issue by dabaliyan** [FortAwesome/Font-Awesome#7750] opened 2015-10-24 05:24 UTC
While requesting this change , I am assuming that the reasons behind using CDN links for FontAwesome are 
* To make use of already Cached fa-script from browsers
* To having one less thing to store and care about

The Issues I can think of, after making this change, and solutions, are
* Issue- Name change of Icon(s)
  Solution- Instead just add an alias

* Issue- Icon(s) Removal
  Solution- I am not aware of any removal so far ? so ,I think we are good ?

* Issue- Icon(s) Addition
  Solution- No Issue, no extra burden[CDN], just extra Icons

Is there anything else to consider or to know that I'm missing here ?
Please let me know If it's feasible or not ? and if not, then Why ?

**Comment by tagliala** [comment] 2015-10-24 09:23
I agree. Duplicate of #3286 , let's continue there

I hope this could be addressed in v5

**Closed by tagliala** 2015-10-24 09:23 UTC
