### ISSUE TITLE
Icon request: calendar-arrow-to-right and calendar-arrow-to-left

### ISSUE THREAD

**Issue by carlbradwell17** [FortAwesome/Font-Awesome#14745] opened 2019-03-13 13:31 UTC
### What can it be used for?

This would be used when there a two date fields on a page, start date and end date.

### Example image (optional)

![image](https://user-images.githubusercontent.com/45626972/54282616-48c72d80-4594-11e9-9c54-a3836f06d116.png)

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by InsanityMeetsHH** [comment] 2019-03-14 07:40
See #14724

**Comment by tagliala** [comment] 2019-03-14 09:30
Hi!

Thanks for being part of the Font Awesome Community.

Closing here as a duplicate of #14724. Even if it is not exactly the same request, the use case is the same.

Also, this could be easily implemented with the SVG framework: https://jsfiddle.net/tagliala/L17f528g/16/

**Closed by tagliala** 2019-03-14 09:30 UTC
