### ISSUE TITLE
safebox

### ISSUE THREAD

**Issue by mahdimortazavi** [FortAwesome/Font-Awesome#17215] opened 2020-09-30 08:59 UTC
please add safe box icon

![image](https://user-images.githubusercontent.com/10667180/94665017-81fef400-0318-11eb-87b0-370ba4959ea1.png)

**Comment by tagliala** [comment] 2020-09-30 09:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1813, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-30 09:12 UTC
