### ISSUE TITLE
Icon request: fa-triangle, fa-triangle-o

### ISSUE THREAD

**Issue by mokraemer** [FortAwesome/Font-Awesome#6710] opened 2015-06-10 14:28 UTC
basic forms should be available before specific forms created, stacking basic forms allows you to create the complex ones by yourself.

**Comment by TheChen5** [comment] 2015-07-26 00:50
Dupe of #3216 .
+1 that.
*Search before creating.*

**Comment by tagliala** [comment] 2015-07-26 13:16
I don't like #3216 because that request contains 8 icons and an improper title

btw... closing here as a duplicate

**Closed by tagliala** 2015-07-26 13:16 UTC

**Comment by brevilo** [comment] 2015-09-15 12:14
Well, most comments on #3216 do actually refer to the title give +1's for the triangle...
