### ISSUE TITLE
Icon request: Microsoft Store Icon

### ISSUE THREAD

**Issue by jigneshdesai** [FortAwesome/Font-Awesome#18225] opened 2021-09-01 04:44 UTC
**What can it be used for?**
Like Google Play Icon, Microsoft Store Icon Is used to represent that the downloadable item is available on Microsoft Store.

**Example image (optional)**
https://en.wikipedia.org/wiki/File:Microsoft_Store_app_icon.png

**Comment by tagliala** [comment] 2021-09-01 06:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13914, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-09-01 06:44 UTC
