### ISSUE TITLE
Icon Request: backround-color

### ISSUE THREAD

**Issue by robertleeplummerjr** [FortAwesome/Font-Awesome#4072] opened 2014-08-05 13:32 UTC
Will be used in a spreadsheet/text editor.
![background-color](https://cloud.githubusercontent.com/assets/679099/3811934/eea8e34c-1ca4-11e4-9694-78b30610da87.png)

**Comment by aethior** [comment] 2016-06-06 00:32
Duplicate of #3270.

cc @tagliala

**Comment by tagliala** [comment] 2016-06-06 08:50
@aethior thanks. I wasn't able at that time to find the original request

Duplicate of #3270, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-06 08:50 UTC
Labels: waiting for feedback
