### ISSUE TITLE
Icon Request: icon-uah (currency of Ukraine)

### ISSUE THREAD

**Issue by rizorko** [FortAwesome/Font-Awesome#9827] opened 2016-08-28 21:28 UTC
Hello,

I am writing to you from Ukraine. It would be great if UAH currency icon was added to FontAwesome. 

Thank you!

![UAH currency icon](https://cloud.githubusercontent.com/assets/1344107/18036882/fc08faae-6d7e-11e6-834b-64e17461d39b.png)

**Comment by tagliala** [comment] 2016-08-28 21:53
Duplicate of #1451, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-28 21:53 UTC

**Comment by rizorko** [comment] 2016-08-28 21:55
Oh, I'm sorry. That's my fault.
