### ISSUE TITLE
Icon request: TYPO3 CMS icon

### ISSUE THREAD

**Issue by tdeuling** [FortAwesome/Font-Awesome#7445] opened 2015-09-13 09:21 UTC
Hi,
we need the TYPO3-Icon in you font. Please add them.

Here you will find the resources:
http://typo3.org/about/the-brand/style-guide/downloads/
http://typo3.org/fileadmin/t3org/images/FM-styleguide/1_TYPO3_Logos/TYPO3-logos-2012.zip

Thanks!

**Comment by tagliala** [comment] 2015-09-13 09:23
duplicate of #1424 , please +1 that request

closing here

**Closed by tagliala** 2015-09-13 09:23 UTC
