### ISSUE TITLE
Icon request: icon-family

### ISSUE THREAD

**Issue by jonpasquier** [FortAwesome/Font-Awesome#13489] opened 2018-07-06 10:10 UTC
### What can it be used for?

Anywhere we need to convey that a service or a product is accessible to families.
Icon should be gender neutral (or there should be a category of icons representing different family types)

### Example image (optional)

![image](https://user-images.githubusercontent.com/4568003/42373481-4c4b04ac-8115-11e8-97de-d25181aeddfd.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-06 11:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3277, please add a 👍  reaction to that request.

### Please also post there your example, it looks very good

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-06 11:34 UTC
