### ISSUE TITLE
Icon request: mercado-libre

### ISSUE THREAD

**Issue by santiboselli** [FortAwesome/Font-Awesome#16380] opened 2020-03-29 07:05 UTC
**What can it be used for?**
For Latinoamerican customers, MercadoLibre (www.mercadolibre.com.ar) is a really big player within the e-commerce world. It would be very useful if we could have an FA icon with the official brand.

**Example image (optional)**
![MercadoLibre Icon](https://user-images.githubusercontent.com/21125579/77843325-83920880-718b-11ea-96af-4ab797403845.png)

**Icon request checklist**
- [ X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X ] I have included at least one example image if it could be helpful (optional)
- [ X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-23 13:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14846, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-23 13:28 UTC
