### ISSUE TITLE
icon request: fa-foootball

### ISSUE THREAD

**Issue by NewWorldMan** [FortAwesome/Font-Awesome#11842] opened 2017-12-06 15:35 UTC
I notice there are none at all for footballs, basketballs or baseballs. Only soccer as futbol. Any way in the near future we could get these added? i.e. fa-football, fa-basketball, fa-baseball
Many thanks!

Barry

**Comment by sdf1992** [comment] 2017-12-07 15:45
how many time do you need after a request?

**Comment by PeterShaggyNoble** [comment] 2017-12-07 15:51
Assuming you mean American football then that's a duplicate of #4602; baseball is a duplicate of #6438; and basketball is a duplicate of #6441. See also #325 & #714.

**Comment by NewWorldMan** [comment] 2017-12-07 15:51
How many times?

**Comment by NewWorldMan** [comment] 2017-12-07 15:54
Yes, I was searching for issues before I created that one, and none showed up. Then, I started cursoring through the requests and finally came to that link, with prior requests, citing #714.
And yes, plenty of requests over the last 5 years, but still no fonts for those created apparently.

But yes, I’d say a dupe of #714. Apologies for that.

**Comment by tagliala** [comment] 2017-12-07 15:55
> how many time do you need after a request?

Hi, it depends on a lot of things.

Please take a look here: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

I should advise you to consider a custom build if you need this icon in a short while

Closing here because it is a duplicate

**Closed by tagliala** 2017-12-07 15:55 UTC

**Comment by NewWorldMan** [comment] 2017-12-07 15:56
Ok, how /where do I make a custom build? At this link below?

**Comment by tagliala** [comment] 2017-12-07 15:57
@NewWorldMan sorry, this is the correct link: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by NewWorldMan** [comment] 2017-12-07 15:58
Thank you very much!
