### ISSUE TITLE
Icon Request: industry

### ISSUE THREAD

**Issue by Yannick86** [FortAwesome/Font-Awesome#6786] opened 2015-06-19 10:20 UTC
I'd like to request an icon which would represent an industry zone or factory: icon-industry, icon-factory, icon-plant.

The best example I could find: 
http://makesimp.ly/images/services_icon_03.png

What would I use it for?
You have many industry applications, just like you have admin applications ... hospital applications, airport applications, etc. However there aren't many icons yet in the Font Awesome set which apply to this sector.

I did find a nice truck icon, but could use more things such as a bridge,helmet, toolbox, worker with a helmet on, a fence, control panel,...but now I'm probably asking too much :)

**Comment by DaTebe** [comment] 2015-06-19 13:26
+1

**Comment by jlr7245** [comment] 2015-06-25 21:00
+1!!!

**Comment by ShamanFromSiberia** [comment] 2015-07-01 08:02
+1

**Comment by tagliala** [comment] 2015-07-01 10:16
duplicate of #1689 , please +1 that request

closing here

**Closed by tagliala** 2015-07-01 10:16 UTC
