### ISSUE TITLE
 design font for aparat website 

### ISSUE THREAD

**Issue by hadi-alizadeh** [FortAwesome/Font-Awesome#9751] opened 2016-08-14 06:06 UTC
please design a font for aparat website.
this website is very famous website 
aparat,com is video sharing website

thanks

**Comment by tagliala** [comment] 2016-08-14 12:16
Duplicate of #5204, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-14 12:16 UTC
