### ISSUE TITLE
Bug: Invalid CSS property

### ISSUE THREAD

**Issue by enzolp28** [FortAwesome/Font-Awesome#20145] opened 2024-03-01 14:08 UTC
### Bug description

On CSS Validator I got this error : 
.fa-rotate-by | var(--fa-rotate-angle, none) n'est pas une valeur de transform : rotate(var(--fa-rotate-angle, none))
-- | --

### Reproducible test case

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fenzolp28.github.io%2Fbooki%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=fr

### Screenshots

![Capture d’écran 2024-03-01 à 15 06 07](https://github.com/FortAwesome/Font-Awesome/assets/98584731/2fa3b780-1179-437b-ae7b-028aa2f5a79c)

### Font Awesome version

v6.2.1

### Serving

Font Awesome CDN

### Implementation

CSS

### Browser and Operating System

Chrome

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2024-03-01 14:23
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Pretty sure this is a duplicate of #19423, we should replace `none` with `0`

**Closed as completed by tagliala** 2024-03-01 14:23 UTC
Labels: bug, needs-triage
