### ISSUE TITLE
Icon request: express-js

### ISSUE THREAD

**Issue by abhijoshi2k** [FortAwesome/Font-Awesome#18586] opened 2022-01-14 17:08 UTC
**What can it be used for?**
Can be used to display icon of popular node.js based backend routing framework: Express.js

**Example image (optional)**

![download](https://user-images.githubusercontent.com/46530103/149555472-2e2ed369-9011-496e-9fe5-69facdf534e8.png)
![download](https://user-images.githubusercontent.com/46530103/149555718-00be7ed3-3c62-42e4-a9af-cf11845a4e4d.jpg)
![download](https://user-images.githubusercontent.com/46530103/149555737-e82a1492-7b53-49be-bbbe-9c0290791c8b.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2022-01-14 18:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13198, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-01-14 18:53 UTC
