### ISSUE TITLE
Icon Request: fa-molecule

### ISSUE THREAD

**Issue by vijay0056** [FortAwesome/Font-Awesome#6076] opened 2015-03-27 11:12 UTC
![dna-sign-in-white-and-black_318-1796](https://cloud.githubusercontent.com/assets/11678823/6866628/446c715a-d4a0-11e4-9e74-a070debdded2.jpg)

**Comment by G-Driver** [comment] 2015-03-27 12:24
The example you've provided is more a DNA, see a DNA request https://github.com/FortAwesome/Font-Awesome/issues/1195 could you +1 that one ?

But there's another request for an molecule, see https://github.com/FortAwesome/Font-Awesome/issues/5190 could you +1 that one ?

**Comment by tagliala** [comment] 2015-03-27 13:48
closing as duplicate of #1195 or #5190

**Closed by tagliala** 2015-03-27 13:48 UTC

**Comment by carlosacabrera** [comment] 2015-05-05 16:41
You closed this ticket as a duplicate of other tickets that have been closed as duplicate of this ticket.

**Comment by tagliala** [comment] 2015-05-05 16:49
#1195 and #5190 are opened :grin:

**Comment by tagliala** [comment] 2015-05-05 16:50
![screen shot 2015-05-05 at 18 49 49](https://cloud.githubusercontent.com/assets/556268/7477950/8b73c604-f357-11e4-8ce8-145619654a58.png)

This status update is sometimes confusing
