### ISSUE TITLE
icone request - driver 

### ISSUE THREAD

**Issue by ivantrouvetout** [FortAwesome/Font-Awesome#12547] opened 2018-03-08 14:03 UTC
it is possible to have e new icon driver please

**Comment by tagliala** [comment] 2018-09-18 08:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7743, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-18 08:45 UTC
