### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by flahol** [FortAwesome/Font-Awesome#13023] opened 2018-05-03 16:41 UTC
Hello

May be you could add 2 icons for phone calls : in and out phone calls,
and for emails too.

Thanks for your nice icons
Patrice

**Comment by tagliala** [comment] 2018-05-03 19:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3701, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-03 19:01 UTC
