### ISSUE TITLE
Icon Request:  fa-praying hands

### ISSUE THREAD

**Issue by anonymousabyss** [FortAwesome/Font-Awesome#9748] opened 2016-08-12 17:05 UTC
Greetings,

Please add this icon.  It is  very useful and much needed.

Thanks,

**Comment by tagliala** [comment] 2016-08-12 17:22
Duplicate of #1855, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-12 17:22 UTC
