### ISSUE TITLE
-moz-osx-font-smoothing no longer works for mozilla firefox

### ISSUE THREAD

**Issue by thevrajshah** [FortAwesome/Font-Awesome#16794] opened 2020-06-14 11:24 UTC

**Comment by tagliala** [comment] 2020-06-14 11:52
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information?

IE: "this custom prefix has been deprecated in Firefox X and removed in firefox Y"

**Comment by thevrajshah** [comment] 2020-06-25 17:43
Since Firefox supports 'box-shadow' so well, it has no reason to keep '-moz-box-shadow' around. It dropped support for the prefix in version 13 or maybe earlier.

**Comment by tagliala** [comment] 2020-06-25 17:49
@thevrajshah thanks for the clarification

Could you please indicate where Font Awesome is using `-moz-box-shadow`?

**Comment by thevrajshah** [comment] 2020-06-26 17:50
Well, I can't tell about other places but for my code it is showing in `free.scss`

**Comment by tagliala** [comment] 2020-06-26 19:12
> Well, I can't tell about other places but for my code it is showing in `free.scss`

Sorry, can't find `free.scss` in font awesome source. Could you please double check that it is a file from an official release of Font Awesome 5?

**Comment by thevrajshah** [comment] 2020-06-27 04:00
Then look for `free.min.css`

**Comment by tagliala** [comment] 2020-06-27 06:21
@thevrajshah there is no `free.min.css` also

This is our css folder: https://github.com/FortAwesome/Font-Awesome/tree/master/css

I'm going to close this issue, if you can point me to the file with the offending css rules I will reopen

**Closed by tagliala** 2020-06-27 06:21 UTC
Labels: waiting for feedback

**Comment by thevrajshah** [comment] 2020-06-28 03:20
@tagliala Thank you for you patience but for one last time can you look for it in `all.css` ?
![Screenshot_20200628_085024](https://user-images.githubusercontent.com/42384591/85936898-79171480-b91c-11ea-9222-93671ec7b163.png)

**Comment by tagliala** [comment] 2020-06-28 08:45
Welcome @thevrajshah 

So the issue is about `-moz-osx-font-smoothing` (as reported in the title) and not `-moz-box-shadow` as reported in your [follow up comment](https://github.com/FortAwesome/Font-Awesome/issues/16794#issuecomment-649725373)

`-moz-osx-font-smoothing` and `-moz-box-shadow` are unrelated

Could you please take another look at my comment: https://github.com/FortAwesome/Font-Awesome/issues/16794#issuecomment-643756130 ?

At the moment, I can see that `-moz-osx-font-smoothing` is working on Firefox 77.0.1 on maCOS and it also renders icons better on retina displays

![image](https://user-images.githubusercontent.com/556268/85942790-de263680-b92b-11ea-8793-16566d45981d.png)

![image](https://user-images.githubusercontent.com/556268/85942847-4bd26280-b92c-11ea-84a9-8346ae7d92d6.png)
![image](https://user-images.githubusercontent.com/556268/85942860-67d60400-b92c-11ea-9436-9335d94b0226.png)
