### ISSUE TITLE
ASK.fm icon

### ISSUE THREAD

**Issue by YAABITECH** [FortAwesome/Font-Awesome#13987] opened 2018-09-22 05:15 UTC
Please add ask.fm icon

**Comment by tagliala** [comment] 2018-09-22 08:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3762, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-22 08:12 UTC
