### ISSUE TITLE
Icon Request: fa-cobol y fa-ruby

### ISSUE THREAD

**Issue by Patriv06** [FortAwesome/Font-Awesome#19218] opened 2022-07-28 19:23 UTC
Hi!
I will be very greatfull if you can bring me an icoon for "cobol"  and an other for "ruby", I need them fon my curriculum, in the same type and color as fab fa-java.
If you do it, how I can get notice?

**Comment by tagliala** [comment] 2022-07-28 19:28
Hi!

Thanks for being part of the Font Awesome Community.

Ruby is a duplicate of #13553, please add a 👍 reaction to that request.

As per cobol, please fill out our [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

Closing here

**Closed as completed by tagliala** 2022-07-28 19:28 UTC
