### ISSUE TITLE
Icon request: icon-flame

### ISSUE THREAD

**Issue by mattyb6** [FortAwesome/Font-Awesome#11694] opened 2017-10-31 14:41 UTC
Please would it be possible to have a flame icon, similar to fa-free-code-camp, which is already in your icon library but without the brackets around the sides of the flame. This is for a scoring system I am working on and currently using fa-fire icon but would like a few more options.   

Many thanks.

**Comment by tagliala** [comment] 2017-10-31 15:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3577 , please add a 👍  reaction to that request.

#3577 is solved in 5.0.0, we have a different fire icon

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-31 15:33 UTC
