### ISSUE TITLE
Icon request: icon-postgres

### ISSUE THREAD

**Issue by asheshv** [FortAwesome/Font-Awesome#9369] opened 2016-06-08 07:29 UTC
Hi,

Can you please create a brand icon for open source community project for PostgreSQL?
Please take a look at this - https://wiki.postgresql.org/wiki/Logo.

Thanks.

**Comment by tagliala** [comment] 2016-06-08 07:52
Please consider using mfizz for technology icons

https://github.com/fizzed/font-mfizz

**Comment by asheshv** [comment] 2016-06-08 08:04
Thanks for the suggestions.

We're already using font-mfizz for the same purpose.
But - it does not make sense to use a separate font for one icon.

**Comment by axelfontaine** [comment] 2017-02-15 13:35
Duplicate of #6672

**Comment by aethior** [comment] 2022-07-28 16:16
> Duplicate of #6672

@tagliala check here please.

**Closed** 2022-07-28 19:40 UTC
Labels: new icon, web application icons (legacy category)
