### ISSUE TITLE
Icon Request: fa-greek-{here}

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7016] opened 2015-07-23 02:53 UTC
Request for Greek (0-9) numbers and (a-z) alphabet.
Example: https://en.wikipedia.org/wiki/Greek_alphabet
Example Names: fa-greek-alpha, fa-greek-omega

**Comment by tagliala** [comment] 2015-07-23 07:59
Duplicate of #2828

Please read https://github.com/FortAwesome/Font-Awesome/issues/2828#issuecomment-33898685

closing here

**Closed by tagliala** 2015-07-23 07:59 UTC

**Comment by tuxy** [comment] 2015-07-24 04:19
@tagliala, thank you for the comment on #2828 this makes sense.
