### ISSUE TITLE
Icon request: icon-facebook-messenger

### ISSUE THREAD

**Issue by mcparrish** [FortAwesome/Font-Awesome#9132] opened 2016-05-05 18:29 UTC
I would like to get the icon for the Facebook Messenger App
![image](https://cloud.githubusercontent.com/assets/1039589/15052880/adb0947c-12b4-11e6-9771-4329dac12860.png)

**Comment by aethior** [comment] 2016-05-05 20:47
Hi @mcparrish,

This request is duplicate of #6912. Please +1 that.

Regards.

**Closed** 2016-05-05 23:04 UTC
