### ISSUE TITLE
Icon request: user-search

### ISSUE THREAD

**Issue by jbernauer** [FortAwesome/Font-Awesome#12043] opened 2018-01-05 13:42 UTC
Hi,
Would it be possible to add a user icon while has a magnifying glass?  The user-times and user-plus are perfect.

Thanks so much.
Jacqueline

**Comment by PeterShaggyNoble** [comment] 2018-01-05 14:48
Duplicate of #10119

**Closed** 2018-01-05 16:55 UTC
