### ISSUE TITLE
Icon request: icon-stadium

### ISSUE THREAD

**Issue by stujames** [FortAwesome/Font-Awesome#20084] opened 2024-01-25 16:11 UTC
Hi, it would be great if you could create a stadium icon to represent sporting events as a whole. Rather than having event-specific icons such as footballs, tennis rackets etc

**Comment by aethior** [comment] 2024-01-31 17:17
Hi @stujames,

This request is a duplicate of #10540.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed as completed** 2024-01-31 17:44 UTC
