### ISSUE TITLE
Icon request: fa-google-scholar

### ISSUE THREAD

**Issue by onimh** [FortAwesome/Font-Awesome#17287] opened 2020-10-17 19:34 UTC
**What can it be used for?**
I want to use this icon for personal website. I think many people in academia would like to use this. So it would be really great if you could make one.

**Example image (optional)**
Insert the example image here if necessary.
![google_scholar_circular](https://user-images.githubusercontent.com/66117993/96351903-818a8b00-1084-11eb-96f6-3a931d66fff6.png)
![google_scholar_square](https://user-images.githubusercontent.com/66117993/96351906-8c452000-1084-11eb-926f-6536bd0c6d57.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-10-17 19:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #541, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Comment by onimh** [comment] 2020-10-17 20:06
Hi,

Is there a font awesome icon for google scholar yet? It would be really
helpful if you could let me know about it.

Best Regards,
Oni

**Comment by tagliala** [comment] 2020-10-17 20:16
> Is there a font awesome icon for google scholar yet? It would be really

At the moment there isn't. At the time we tried to implement it together with mendeley, we couldn't because there were no official svg icons. I've checked some time ago and it seems it is still the case. Do you have any official svg icon for google scholar?

**Comment by onimh** [comment] 2020-10-17 20:28
Thank you so much for your reply. Here is a link which includes google
scholar icon. I am not sure if these icons are in svg format. It would be
great if you can take a look.

Link: https://icons8.com/icons/set/google-scholar-logo

Best Regards,
Oni

**Comment by tagliala** [comment] 2020-10-17 20:53
Hi, thanks for the link. The best thing is to find the google scholar svg icons in a resource from google scholar itself

Also, google scholar is using a new icon that requires to be colored to be exactly represented:
![image](https://user-images.githubusercontent.com/556268/96353342-3f386c80-10cb-11eb-9865-0c40dfe6ab8b.png)

**Comment by onimh** [comment] 2020-10-17 20:59
Okay. Thank you.

**Comment by onimh** [comment] 2020-10-18 06:01
Hi,
The logo you have shown is available in vector form in this link: https://worldvectorlogo.com/logo/google-scholar. Hope this may work. Please let me know. Thank you.

**Comment by digantamisra98** [comment] 2020-11-26 19:41
@tagliala any updates on this?

**Comment by tagliala** [comment] 2020-11-26 20:10
@digantamisra98 please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Also please notice that we do not have an official, monochrome svg for this logo

Closing here

**Comment by tagliala** [comment] 2020-11-26 20:14
Apologies, please use #541

**Closed by tagliala** 2020-11-26 20:14 UTC
