### ISSUE TITLE
Icon Request: fa-circle-thinner

### ISSUE THREAD

**Issue by morrow95** [FortAwesome/Font-Awesome#7501] opened 2015-09-21 06:17 UTC
There is circle-o then circle-thin... how about circle-thinner which is about half the width/thickness of circle-thin?

Would be very useful for stacking when you don't want such a thick border.  I find circle-o to be way thick for this purpose (I don't believe it is supposed to be used for stacking anyways) and circle-thin is actually the same thickness as the inner icon (try stacking an fa-search inside a fa-circle-thin and you will see what I mean).  We need a third option which for a thinner border.

**Comment by caduvieira** [comment] 2015-09-21 12:25
dupe of #3932
+1 that one

**Comment by tagliala** [comment] 2015-09-21 13:12
@caduvieira this is not a duplicate, we already have a circle-thin, this one is circle-thinner.

I don't know if it is possible, circle thin seems to be 1px wide at 14px icon size, so anything below could not be pixel perfect

**Comment by caduvieira** [comment] 2015-09-21 13:35
OK. Thanks

**Comment by tagliala** [comment] 2015-09-21 13:39
@morrow95 you could consider a css based solution: http://jsfiddle.net/tagliala/4ya23yjL/6/

**Comment by morrow95** [comment] 2015-09-22 04:04
Yeah, css is the only solution right now for a thin border and I've done this in the past.  Having an fa method would be much easier though (both implementation and customizing).  As much as people use the circle and circle-thin background with stacking I'm sure a thinner option would get a lot of use (if it's even possible - I didn't think about the pixel sizing as noted in another post).

**Comment by imagina** [comment] 2016-10-28 23:39
+1

**Comment by TiagoSousa26** [comment] 2016-11-04 16:27
+1

I agree. I need one thinner too.

**Comment by sensibleworld** [comment] 2022-09-12 20:14
This is now a reality with our new thin icons: https://fontawesome.com/icons/circle?s=thin&f=classic

**Closed by sensibleworld** 2022-09-12 20:14 UTC
Labels: new icon
