### ISSUE TITLE
Icon request: flip or mirror horizontally and vertically

### ISSUE THREAD

**Issue by dcknight** [FortAwesome/Font-Awesome#17243] opened 2020-10-06 16:52 UTC
**What can it be used for?**
This icon is used for mirroring or flipping an object in a design tool. You can mirror horizontally or vertically.

**Example image (optional)**
![baseline_flip_black_18dp](https://user-images.githubusercontent.com/2085295/95232599-f8d93880-07c1-11eb-86ac-56d614f2785b.png)

**Icon request checklist**
- [ ] Matched pair (Ex: `horizontal` / `vertical`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-10-06 18:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14426, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-10-06 18:12 UTC
