### ISSUE TITLE
fa-nfc

### ISSUE THREAD

**Issue by 2ndGAB** [FortAwesome/Font-Awesome#10650] opened 2017-02-11 10:52 UTC
Hello,
We need an icon for NFC Tag.
A possibility could be to use this one from [Wikimedia](https://commons.wikimedia.org/wiki/File:Ic_nfc_48px.svg)
Or based on the logo of the [NFC Forum](http://nfc-forum.org/), I hope they will agree to see their logo widely used, and I hope they could understand that we need to alter a bit the graphism to use it as AwesomeFont, i.e. one in black on white and one in white on black maybe. [their guidelines](http://nfc-forum.org/our-work/nfc-branding/n-mark/guidelines-and-brand-assets/)

I contacted NFC Forum to suggest them to accept this enquiry and I hope they will directly participate to this thread.

**Comment by PeterShaggyNoble** [comment] 2017-03-14 21:35
This should probably be considered as a dupe of #1695.

**Comment by 2ndGAB** [comment] 2017-03-14 21:43
Yes it is. I unfortunately just made a search of fa-nfc before posting it.

**Closed** 2017-03-15 09:01 UTC
