### ISSUE TITLE
Icon request: icon-activity

### ISSUE THREAD

**Issue by mdestagnol** [FortAwesome/Font-Awesome#13310] opened 2018-06-12 18:07 UTC
### What can it be used for?

Used for feeds, activity pulse, dashboards, etc.

There could be a circle version and a non circle version

### Example image (optional)

![icon-activity-regular-circle](https://d30y9cdsu7xlg0.cloudfront.net/png/118540-200.png)
![icon-activity-solid-circle](https://d30y9cdsu7xlg0.cloudfront.net/png/118640-200.png)

(credits: the noun project for these 2 icons)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-06-12 19:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1059, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-12 19:05 UTC
