### ISSUE TITLE
Icon Request: fa-injection

### ISSUE THREAD

**Issue by alex21** [FortAwesome/Font-Awesome#7074] opened 2015-07-29 11:42 UTC
I need fa-injection icon
Thanks

**Comment by tagliala** [comment] 2015-07-29 12:16
duplicate of #1779 ?

**Comment by alex21** [comment] 2015-07-29 12:22
Yes, this is same icon.
But many people search with this name.

**Comment by tagliala** [comment] 2015-07-29 12:50
@alex21 thanks for the clarification

added `injection` to #1779 title, please +1 that request

closing here

**Closed by tagliala** 2015-07-29 12:50 UTC
Labels: waiting for feedback
