### ISSUE TITLE
Icon request: picarto

### ISSUE THREAD

**Issue by kelpiesummer** [FortAwesome/Font-Awesome#17187] opened 2020-09-22 16:25 UTC
**What can it be used for?**
Mostly usage for making user profile boxes that link to streaming sites. While most gamers use Twitch, Picarto is more towards Artists and is commonly used there.

**Example image**
http://prntscr.com/ulxhvr <-- Usage.
https://www.logolynx.com/images/logolynx/3f/3f690f27bcd93aaee95b69b7afe7d522.png <-- Logo for Picarto.

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-04-11 20:07
Duplicate of #9699.

cc/ @tagliala

**Closed** 2022-04-11 21:08 UTC
Labels: brand icon
