### ISSUE TITLE
Icon request: fa-fuel-pump

### ISSUE THREAD

**Issue by derekbtw** [FortAwesome/Font-Awesome#10438] opened 2016-12-27 21:19 UTC
Something like this would be awesome. Everyone in the auto industry would thank you.

![image](https://cloud.githubusercontent.com/assets/3450398/21508573/4cdd7058-cc3f-11e6-8c4d-dd9861c5dcd1.png)

**Comment by tagliala** [comment] 2016-12-27 21:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1676, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-27 21:22 UTC
