### ISSUE TITLE
Icon request: Tik-Tok

### ISSUE THREAD

**Issue by rutledgeismyname** [FortAwesome/Font-Awesome#16676] opened 2020-05-19 20:13 UTC
**What can it be used for?**
This will be used for people who want to promote their Tik Tok accounts via app or website. Similar to the other social network icons. 

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [Single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [Tik-Tok ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [True ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [Social Network ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-19 20:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14340 . No need to +1 that request, tiktok icon will be available with the next release of Font Awesome (no ETA, yet)

**Closed by tagliala** 2020-05-19 20:46 UTC
