### ISSUE TITLE
Icon Request: fa-cardboard or fa-vrheadset

### ISSUE THREAD

**Issue by Xaranta** [FortAwesome/Font-Awesome#10161] opened 2016-11-02 20:31 UTC
an icon for google cardboard or a standard looking vr headset would be dope!

**Comment by tagliala** [comment] 2016-11-03 00:07
Duplicate of #9785 and #6590 , please add a 👍  reaction to those requests

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-03 00:07 UTC
