### ISSUE TITLE
Icon Request: fa-divide

### ISSUE THREAD

**Issue by Script47** [FortAwesome/Font-Awesome#9901] opened 2016-09-10 22:55 UTC
You have the `fa-plus`, `fa-minus`, and `fa-times` icons. However, surprisingly, nothing for the division sign. 

# Could this please be added?

**Comment by tagliala** [comment] 2016-09-11 09:16
Duplicate of #1133 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-11 09:16 UTC

**Comment by rdeutsch** [comment] 2017-03-05 20:43
I also need a division icon to go with the set of plus, minus, times to represent simple math operations. 

#1133 doesn't exist to be able to +1 it - the link says 'page not found'

@tagliala - can you please reactive this issue, or link to an another duplicate issue that actually exists that we can +1?  Thanks!


[Also, note, to really complete the set, I also need an equals sign, which is covered by this issue: https://github.com/FortAwesome/Font-Awesome/issues/10328 ]
