### ISSUE TITLE
Icon Request: fa-MyAnimeList

### ISSUE THREAD

**Issue by tramppa34** [FortAwesome/Font-Awesome#10729] opened 2017-03-01 19:48 UTC
Brand icon for [https://myanimelist.net/](url) again for linking profile :)

![mal](https://cloud.githubusercontent.com/assets/5153750/23478030/a1e605a4-fec8-11e6-8f30-2a6077100e9c.jpg)

**Comment by tagliala** [comment] 2017-03-01 20:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4352, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-01 20:05 UTC
