### ISSUE TITLE
Icon request: icon-new

### ISSUE THREAD

**Issue by kenzo05** [FortAwesome/Font-Awesome#19465] opened 2022-12-08 23:15 UTC
I need an icon in v4 that has the words NEW. 
Scenario is when we have a list of documents (links) and we want an icon to indicate that one link is new.

**Comment by tagliala** [comment] 2022-12-09 09:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11002, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

> I need an icon in v4 that has the words NEW.

Please note that V4 is in EOL

> Scenario is when we have a list of documents (links) and we want an icon to indicate that one link is new

We tend to avoid texts in icons because they introduce internationalization issues

Closing here

**Closed as completed by tagliala** 2022-12-09 09:04 UTC
