### ISSUE TITLE
Icon request: icon-vs-code 

### ISSUE THREAD

**Issue by mmihalik** [FortAwesome/Font-Awesome#12956] opened 2018-04-26 19:58 UTC
Hello,

I'm using font awesome icons as labels for my desktops in i3wm. For example, I have desktop exclusively for firefox browser, so I have firefox icon associated with this desktop. I would like to label desktop with Visual Studio Code IDE with proper icon, instead of generic fa-code. VS code is quite popular, so I believe this icon would find its use.

Have a nice day.

**Comment by tagliala** [comment] 2018-04-28 07:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1940, please add a 👍  reaction to that request.

Don't worry if #1940 shows the old icon, we will implement the newest, official icon.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-28 07:10 UTC
