### ISSUE TITLE
Mathematical symbols

### ISSUE THREAD

**Issue by sheepsy90** [FortAwesome/Font-Awesome#10141] opened 2016-10-30 11:49 UTC
Hey, during recent work I figured that there is not much mathematical symbols like mean.
Something like fa-mean which could look like this. http://previews.123rf.com/images/prill/prill1304/prill130400048/18935067-crayon-painted-average-symbol-in-white-back-Stock-Photo.jpg

**Comment by mnm364** [comment] 2017-01-29 15:48
Latex is a powerful math formatting language. Quick Google search to see how to integrate Latex into Web development brought me to this: http://latex.userpage.fu-berlin.de/math.html. Good luck!

**Comment by tagliala** [comment] 2017-01-29 15:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1133  and #4834 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-29 15:50 UTC
