### ISSUE TITLE
Icon Request: fa-sweep

### ISSUE THREAD

**Issue by worldofsites** [FortAwesome/Font-Awesome#11230] opened 2017-06-27 02:24 UTC
https://www.1001freedownloads.com/free-clipart/sweep

**Comment by tagliala** [comment] 2017-06-27 09:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #239 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-27 09:05 UTC
