### ISSUE TITLE
Icon request: Unity icon

### ISSUE THREAD

**Issue by pychap** [FortAwesome/Font-Awesome#11646] opened 2017-10-18 23:20 UTC
Hi,

I'd like to request a FA icon for [Unity](https://unity3d.com/), the legendary game SDK. 

If granted, I will be using this in our menu revision of the [Vuforia Developer Library](https://library.vuforia.com/getting-started.html), in the left navigation, right below "Getting Started". We (Vuforia) provide Augmented Reality's most popular SDK. They provide a vector version of their logo if this is helpful, [it can be found here](https://unity3d.com/public-relations/brand).

I've provided an example of my menu where the logo will go.

Thank you for considering!!!
Regards,
Peter
![library-menu-r2](https://user-images.githubusercontent.com/1036335/31747169-2c5b0fba-b420-11e7-981e-dfe23a8dc9bc.jpg)

**Comment by tagliala** [comment] 2017-10-19 10:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2888, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-19 10:20 UTC
