### ISSUE TITLE
Icon Request: fa-bandcamp

### ISSUE THREAD

**Issue by pedromau** [FortAwesome/Font-Awesome#5528] opened 2015-01-29 20:49 UTC
Band websites will need that. I do :)
![bandcamp_logo](https://cloud.githubusercontent.com/assets/10763649/5965972/5342bb78-a7f8-11e4-95e9-4e603fe75962.png)

**Comment by tagliala** [comment] 2015-01-31 11:42
duplicate of #1725, please +1 that request

closing here

**Closed by tagliala** 2015-01-31 11:42 UTC
