### ISSUE TITLE
Icon request: fa-osf

### ISSUE THREAD

**Issue by aepinilla** [FortAwesome/Font-Awesome#19794] opened 2023-07-04 11:44 UTC
I'd like to ask for OSF (https://osf.io/) icon: https://osf.io/

This is the SVG:
![osf](https://github.com/FortAwesome/Font-Awesome/assets/3936015/c56cf2d2-b9f4-48d0-9b06-c08f33ceef23)

**Comment by tagliala** [comment] 2023-07-04 12:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13886, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-07-04 12:12 UTC
