### ISSUE TITLE
Icon request: plan

### ISSUE THREAD

**Issue by JoshIsOnIt** [FortAwesome/Font-Awesome#13512] opened 2018-07-09 20:20 UTC
### What can it be used for?
Used to show a plan (project plan, shipment plan, etc)

### Example image (optional)

https://www.google.ca/search?q=plan+icon&safe=off&tbm=isch&source=iu&ictx=1&fir=R5Vp8p-cI4CTeM%253A%252C6FH_u4Cb1HlCCM%252C_&usg=__2kiXNrDlCK3TyKLpPizhkgNA7tQ%3D&sa=X&ved=0ahUKEwjw8vWe6pLcAhWD3YMKHcu_AO8Q9QEILTAB#imgrc=R5Vp8p-cI4CTeM:

https://www.google.ca/search?q=plan+icon&safe=off&tbm=isch&source=iu&ictx=1&fir=R5Vp8p-cI4CTeM%253A%252C6FH_u4Cb1HlCCM%252C_&usg=__2kiXNrDlCK3TyKLpPizhkgNA7tQ%3D&sa=X&ved=0ahUKEwjw8vWe6pLcAhWD3YMKHcu_AO8Q9QEILTAB#imgrc=YJV_R2QBK15RjM:

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-03-22 00:34
Duplicate of #9659.

cc/ @tagliala

**Closed** 2022-03-22 17:34 UTC
Labels: new icon, web application icons, waiting for feedback
