### ISSUE TITLE
Icon request: fab fa-battlenet

### ISSUE THREAD

**Issue by alystair** [FortAwesome/Font-Awesome#13008] opened 2018-05-03 05:01 UTC
### What can it be used for?

You have already included the Steam logo so it only makes sense to include Battlenet and possibly others such as EA's Origin.

### Example image (optional)

![battlenet](https://user-images.githubusercontent.com/159109/39560568-202d0850-4e6d-11e8-98f7-011fa25b3927.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful
- [x] The request is for a concrete object

**Comment by alystair** [comment] 2018-05-03 05:02
As for Origin - the logo is available here: https://commons.wikimedia.org/wiki/File:Origin.svg

**Comment by tagliala** [comment] 2018-05-03 14:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8110, please add a 👍  reaction to that request.

>  I have searched for existing issues and to the best of my knowledge this is not a duplicate

Don't worry 👍 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-03 14:17 UTC
