### ISSUE TITLE
Icon request: fa-video-camera-slash

### ISSUE THREAD

**Issue by luton** [FortAwesome/Font-Awesome#9283] opened 2016-05-27 07:26 UTC
You can add "fa-video-camera-slash"  like " fa-microphone -> fa-microphone-slash"

**Comment by tagliala** [comment] 2016-05-27 09:00
Duplicate of #3765 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-27 09:00 UTC
