### ISSUE TITLE
Icon request: Youtube Shorts

### ISSUE THREAD

**Issue by jvojta** [FortAwesome/Font-Awesome#17842] opened 2021-04-22 15:20 UTC
**What can it be used for?**
Youtube shorts logo

**Example image (optional)**
![youtube-shorts](https://user-images.githubusercontent.com/62947698/115738980-d7225600-a38d-11eb-8fe2-034c512f869e.png)

**Icon request checklist**
This is matched pair (shorts/shorts with beta)

**Comment by tagliala** [comment] 2021-04-22 15:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17522, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-04-22 15:30 UTC
