### ISSUE TITLE
Icon Request: icon-grass-block

### ISSUE THREAD

**Issue by benaubin** [FortAwesome/Font-Awesome#5285] opened 2014-12-24 04:39 UTC
For anyone familiar to Minecraft, they know of the Grass block, which would be an amazing icon to add for Minecraft server owners across the web!

Here's I am thinking something like this:
![grass](https://cloud.githubusercontent.com/assets/7585353/5548978/7e4775f0-8b44-11e4-8a5a-b44850e53b92.png)
Where the grass block is shown at an angel, so that it shows more of a grass block.
The outline of the block, and the grass part should be inverted.

**Comment by Dooleylabs** [comment] 2016-01-11 14:30
Will this icon be added? I see the issue is closed, but there's no answer on it. Either way, +1

**Comment by JacquesMarais** [comment] 2016-03-31 09:12
+1

**Comment by jens1o** [comment] 2017-09-04 17:41
Could anyone of the team add the labels, please?

**Comment by Koohiisan** [comment] 2018-04-23 15:35
+1 2018 and we still need this!

**Comment by sensibleworld** [comment] 2024-07-11 13:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 13:33 UTC
Labels: new icon, Declined
