### ISSUE TITLE
Icon Request: dog and cat

### ISSUE THREAD

**Issue by ajunior** [FortAwesome/Font-Awesome#8780] opened 2016-03-17 21:33 UTC
Asking for a Animal category with at least dog and cat icons.

Thanks.

**Comment by aethior** [comment] 2016-03-18 11:58
Hi @ajunior,

`fa-dog` is duplicate of #1317 and `fa-cat` is duplicate of #2226.

Regards.

**Closed** 2016-03-18 15:04 UTC
