### ISSUE TITLE
Icon request: Banana

### ISSUE THREAD

**Issue by YLAG** [FortAwesome/Font-Awesome#11480] opened 2017-09-01 09:54 UTC
Please add more food and fruit icons.. specialy a banana would be awesome!

**Comment by tagliala** [comment] 2017-09-01 11:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6030, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-01 11:02 UTC
