### ISSUE TITLE
Icon request: icon-ear

### ISSUE THREAD

**Issue by gitnowlegal** [FortAwesome/Font-Awesome#5603] opened 2015-02-06 19:25 UTC
![ear](https://cloud.githubusercontent.com/assets/3269704/6085913/6ab60c0e-ae03-11e4-9e21-56c10ab17887.png)
![ear-512](https://cloud.githubusercontent.com/assets/3269704/6085943/8beb5b2c-ae03-11e4-98b8-bb692c3d5f02.png)

**Comment by tagliala** [comment] 2015-02-06 23:42
duplicate of #3726 , please +1 that request

closing here

**Closed by tagliala** 2015-02-06 23:42 UTC
