### ISSUE TITLE
Icon request: icon-lion

### ISSUE THREAD

**Issue by isifun** [FortAwesome/Font-Awesome#8334] opened 2016-01-13 14:55 UTC
Hi, it will be amazing to have some animals icon like dog, cat, giraffe, lion ...
Thanks to all
![lion7](https://cloud.githubusercontent.com/assets/6671049/12297570/19706052-ba0e-11e5-8db1-bb3f6f6acbba.png)

**Comment by lmget** [comment] 2016-06-18 12:47
Agreed!

**Comment by Crissov** [comment] 2016-10-20 20:54
Probable duplicate of #5403.

**Comment by tagliala** [comment] 2019-03-24 10:00
Sorry, I've missed this one. 

Duplicate of #5403

**Closed by tagliala** 2019-03-24 10:00 UTC
Labels: new icon, web application icons
