### ISSUE TITLE
Font awesome Blogger Icon request

### ISSUE THREAD

**Issue by roisindillon** [FortAwesome/Font-Awesome#9240] opened 2016-05-19 09:34 UTC
just looking for a font awesome blogger icon. has this happened yet?

**Comment by tagliala** [comment] 2016-05-19 09:58
Duplicate of #1088 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-19 09:58 UTC
