### ISSUE TITLE
Leaderboard: first item not visible

### ISSUE THREAD

**Issue by jmsche** [FortAwesome/Font-Awesome#14383] opened 2018-12-11 12:08 UTC
Hi, the first item of each leaderboard is not visible, eg. on page: https://fontawesome.com/community/leaderboard/brands

Here's a screenshot:

![screenshot_2018-12-11 icon leaderboard font awesome](https://user-images.githubusercontent.com/3929498/49799678-d309b680-fd45-11e8-8f3d-7924bc323add.png)

**Comment by InsanityMeetsHH** [comment] 2018-12-11 16:19
The problem is the `top--3` CSS class inside the `table` html tag.

**Comment by tagliala** [comment] 2018-12-12 08:04
Thanks!

**Comment by talbs** [comment] 2018-12-12 21:08
Thanks for the great heads up and help, all. We should have this bug squashed on the site shortly. 😄

**Comment by talbs** [comment] 2018-12-14 19:21
Hi, gang. This display issue is now fixed on https://fontawesome.com/community/leaderboard/new. Thanks again for bringing it to our attention.

**Closed by talbs** 2018-12-14 19:21 UTC
Labels: bug, doc
