### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by DouglasLoo** [FortAwesome/Font-Awesome#9807] opened 2016-08-24 16:01 UTC
SMS Icon
http://www.iconarchive.com/show/windows-8-icons-by-icons8/Mobile-Sms-icon.html

needed for responsive web publish of sms phone number with icon to start sms

**Comment by tagliala** [comment] 2016-08-24 23:06
Duplicate of #1440 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-24 23:06 UTC
