### ISSUE TITLE
Icon Request: fa-daily-motion

### ISSUE THREAD

**Issue by shefik** [FortAwesome/Font-Awesome#8494] opened 2016-02-05 06:58 UTC
Please add an icon for Daily Motion.

https://www.dailymotion.com

**Comment by aethior** [comment] 2016-02-05 13:53
Hi,

This request is duplicate of #3890. (cc @tagliala)

Regards.

**Comment by tagliala** [comment] 2016-02-05 14:47
@aethior thanks

**Closed by tagliala** 2016-02-05 14:47 UTC
Labels: brand icons, new icon
