### ISSUE TITLE
Icon Request: fa-tap

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#5091] opened 2014-11-29 11:35 UTC
Hello, it would be great if you could add new icon called "fa-tap" which looks like this:

http://i.imgur.com/mzJryEn.png
![faucet-309209_640](https://cloud.githubusercontent.com/assets/8902575/5234332/d0d3629e-77bb-11e4-8842-999821fe9b27.png)

**Comment by aethior** [comment] 2022-03-17 21:17
Duplicate of #10092.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-17 21:51
Thanks

**Closed by tagliala** 2022-03-17 21:51 UTC
Labels: new icon, web application icons
