### ISSUE TITLE
Icon Request: fa-church

### ISSUE THREAD

**Issue by werkmax** [FortAwesome/Font-Awesome#7992] opened 2015-11-26 12:40 UTC
Hello guys font awesome.

Congratulations for the incredible work you are developing.
You can also add the icons of temples and churches?

You are awesome!
Sorry my bad English! ;)

**Comment by tagliala** [comment] 2015-11-26 12:43
duplicate of #2088 , please +1 that request

closing here

**Closed by tagliala** 2015-11-26 12:43 UTC
