### ISSUE TITLE
The Cart-plus icon is missing and it has been used before.

### ISSUE THREAD

**Issue by Erasmus24** [FortAwesome/Font-Awesome#16988] opened 2020-08-04 20:31 UTC

**Comment by tagliala** [comment] 2020-08-05 21:18
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

Sorry, can't reproduce.

Demo: (SVG) https://jsfiddle.net/tagliala/7xb2e854/2/ (CSS) https://jsfiddle.net/tagliala/0x1qe4by/4/

Please double check that there aren't third-party plugins/themes/libraries loading an older version of Font Awesome that may have priority over yours

If you are still experiencing this issue, please open a new request, fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md), and provide a reproducible test case

Hope it helps

Closing here

Ref: 
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Closed by tagliala** 2020-08-05 21:18 UTC
