### ISSUE TITLE
Cannot select font weight in XCode Storyboards

### ISSUE THREAD

**Issue by nickdnk** [FortAwesome/Font-Awesome#13557] opened 2018-07-16 23:47 UTC
Hello

I cannot select font weight in iOS. I am using the latest version of FontAwesome. In XCode I get only the ability to choose the font type, but all three weights just state "Regular". If I toggle between the 3 regulars I can sometimes get it to select either light or solid, but it's very inconsistent.

I did add the fonts correctly - also to Info.plist - and they do work if I set the font directly in code, but it keeps bugging out in storyboards.

Please see attached screenshots. I can only select either Font Awesome 5 Brands or Font Awesome 5 Pro from the font selector. I am not sure if this is a bug with FA or with XCode, but something indicates that XCode gets confused about the available weights.

Fonts:
https://image.ibb.co/bVG5By/Screen_Shot_2018_07_17_at_01_54_19.png
Weights:
https://image.ibb.co/mc5tyd/Screen_Shot_2018_07_17_at_01_49_07.png
Info.plist
https://image.ibb.co/nNRiyd/Screen_Shot_2018_07_17_at_01_52_24.png

**Comment by tagliala** [comment] 2018-07-17 09:07
Hi!

Thanks for being part of the Font Awesome Community.

I think this could be an issue on our side.

Maybe it's the same as #13320

**Comment by nickdnk** [comment] 2018-07-17 11:13
Hello @tagliala 

As you can see from the Info.plist screendump, I am using the .otf files :)

I can fix it by manually editing the XML in Storyboards, but it's kind of tedious.

**Comment by antonjazz** [comment] 2018-07-24 14:20
I'm thinking that perhaps the problem is the way the fonts are named.
When I get the names via `UIFont.fontNames(forFamilyName: "Font Awesome 5 Pro")` I get this:

`FontAwesome5ProRegular`
`FontAwesome5ProSolid`
`FontAwesome5ProLight`

Of all the fonts available to my app in iOS, these are the only fonts I see that do not follow the standard naming convention that includes a dash. For instance:

`Helvetica-Oblique`
`Helvetica-BoldOblique`
`Helvetica`
`Helvetica-Light`
`Helvetica-Bold`
`Helvetica-LightOblique`

@tagliala, could this be the problem? Is there a reason why Font Awesome chose to depart from the standard naming convention?

thanks,
Anton

**Comment by tagliala** [comment] 2018-07-24 15:06
Hi @antonjazz thanks for the detailed feedback

> @tagliala, could this be the problem? Is there a reason why Font Awesome chose to depart from the standard naming convention?

it could be. 

If #13320 doesn't solve this issue, then we may take a look at the naming convention

@robmadole is there a reason for the font name?

**Comment by robmadole** [comment] 2018-07-24 15:13
@supercodepoet you've messed with XCode and this. Do you have any ideas?

**Comment by nickdnk** [comment] 2018-08-16 10:59
Any news here? This is very annoying when working with XCode.

**Comment by tagliala** [comment] 2018-08-29 20:33
>  you mentioned to be sure to use .otf. Is there a reason not to use the smaller .ttf files instead?

ttf is optimized for the web. It should be used only by ancient browsers that don't support `woff`, `woff2`, `eot`

For desktop usage, you are supposed to use the .otf file.

**Comment by antonjazz** [comment] 2018-08-29 21:03
> For desktop usage, you are supposed to use the .otf file. 

This is not for desktop usage; it's for use in an iOS app. Apple gives the option of ttf or otf in iOS and since I don't need any otf features, I thought using ttf would reduce the app's footprint.

**Comment by nickdnk** [comment] 2018-08-29 21:10
@Anton I think he means that web is optimised for speed where downloading the font on each visit plays a role. It doesn’t on iOS, as the number of bytes you have to download extra when downloading the app from App Store is irrelevant.

On 29 Aug 2018, at 23.04, Anton Schwartz <notifications@github.com<mailto:notifications@github.com>> wrote:


For desktop usage, you are supposed to use the .otf file.

This is not for desktop usage; it's for use in an iOS app. Apple gives the option of ttf or otf in iOS and since I don't need any otf features, I thought using ttf would reduce the app's footprint.

**Comment by tagliala** [comment] 2018-08-29 21:36
> I think he means that web is optimised for speed where downloading the font on each visit plays a role.

@nickdnk  Yes, that's correct. Does Font Awesome 5.3 fixes this issue for you?

> since I don't need any otf features

@antonjazz but you need a proper font-name. Apparently, the `ttf` file doesn't need to have that, and this is fine for us, because it is just a fallback for ancient web browsers.

I personally think that in th future we *could* provide better font files for iOS applications (maybe .otf without ligatures) but we should not encourage the use of `.ttf` fonts on the desktop (or, in other words, for anything but the web), because that would be an extra feature to maintain.

@robmadole any thoughts?

**Comment by antonjazz** [comment] 2018-08-29 21:55
> I think he means that web is optimised for speed where downloading the font on each visit plays a role.

Thanks. I just like the ttf files because together they're less than a third the size of the otf fonts. I always like to make my app small - quick to download/update and respectful of the user's memory. Not a big deal either way; I just won't use .otf unless there's a reason for me to.

> but you need a proper font-name. Apparently, the ttf file doesn't need to have that, and this is fine for us, because it is just a fallback for ancient web browsers.

For me, in 5.3 both .ttf and .otf versions show up in iOS named the same way, unchanged from 5.2:

    FontAwesome5ProRegular
    FontAwesome5ProSolid
    FontAwesome5ProLight

whereas standard iOS convention would have them named like other fonts:

    FontAwesome5Pro
    FontAwesome5Pro-Solid
    FontAwesome5Pro-Light

Perhaps this is still the cause of the problems in Xcode?

**Comment by nickdnk** [comment] 2019-01-22 00:50
@tagliala What feedback are you waiting for here (noticing the label)? It seems the obvious solution is to rename the font files. It's not fixed in the newest version because the font names remain the same. I just tested 5.6.

**Comment by tagliala** [comment] 2019-01-22 09:59
@nickdnk "waiting for feedback" is a generic label, I'm using it also when we are waiting for internal feedback.

Anyway, this should be fixed in the upcoming 5.7.0 release.

Could you please a look at https://github.com/FortAwesome/Font-Awesome/issues/13900#issuecomment-451515322 ?

**Comment by antonjazz** [comment] 2019-01-22 16:15
Fantastic, @tagliala - looking forward!

**Comment by nickdnk** [comment] 2019-01-23 00:38
@tagliala Great :)

**Comment by tagliala** [comment] 2019-01-23 10:18
@nickdnk do you think that change will solve this issue?

**Comment by nickdnk** [comment] 2019-01-23 23:45
@tagliala If only the .ttf files (which I don't use for desktop) are modified, then no. I can't really decipher from the other thread if that's the case. I'm not expert on this, so I can't really say for sure.

**Comment by tagliala** [comment] 2019-01-24 09:30
@nickdnk let's wait for 5.7.0 release and see what happens

**Comment by tagliala** [comment] 2019-01-28 23:08
@nickdnk Font Awesome 5.7.0 has been just released. Could you please take a look?

**Comment by nickdnk** [comment] 2019-01-28 23:44
@tagliala 

It has been fixed with regards to selecting the correct font. It now gives the option between Light, Regular and Solid instead of 3x Regular.

However, it's not a drop-in replacement. As we know, the fonts used to be called:

`FontAwesome5ProLight`

but are now instead called

`FontAwesome5Pro-Light`

So now your storyboards and .xib files reference the wrong font. This was somewhat expected, but causes more trouble than I had anticipated. Obviously every icon now has a question mark instead of the icon, and if you try to manually salvage the situation, your XML files will go from this:

```
<array key="Font Awesome 5 Pro-Light-300.otf">
            <string>FontAwesome5ProLight</string>
</array>
```
to this:

```
<array key="Font Awesome 5 Pro-Light-300.otf">
            <string>FontAwesome5Pro-Light</string>
            <string>FontAwesome5ProLight</string>
</array>
```

Which does not look promising. XCode crashed several times for me when I tried to fix this, so what I ended up doing was a git revert so every file was unchanged, then I replaced the font files (the file names have not been renamed, so not much trouble there) and did a search/replace in the root of my project for

`FontAwesome5ProLight` -> `FontAwesome5Pro-Light` (and the 4 other fonts)

Which finds this string in *a lot* of places. After I opened XCode I still had question marks, but when running the app everything looked good. I did a clean/build and restarted XCode again, and now I have my icons back - and I can select the weight correctly now.

So, procedure:

Don't open XCode
Replace the font files
Carefully search/replace all old incorrect strings (I just did a replace all because I'm pretty confident the string won't match anything it shouldn't)
Start XCode; clean build (perhaps clear derived data) and restart XCode

**Comment by tagliala** [comment] 2019-01-28 23:49
@nickdnk thanks for the feedback and for the step-by-step guide to fix this

**Comment by tagliala** [comment] 2019-01-28 23:53
Closing here, but feel free to comment if the original issue has not been fixed and I will reopen

**Closed by tagliala** 2019-01-28 23:53 UTC
Labels: bug

**Comment by nickdnk** [comment] 2019-01-29 00:00
@tagliala Sure, but you should probably include this explanation in your 5.7.0 release notes and warn people that they cannot seamlessly upgrade if using the icons in XCode. I suppose Android Studio will suffer from similar problems.

Your changelog states that it's been changed for TTF files, but it has also been fixed for OTF.

**Comment by tagliala** [comment] 2019-01-29 09:34
> but you should probably include this explanation in your 5.7.0 release notes and warn people that they cannot seamlessly upgrade if using the icons in XCode

Sure, we did that

https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#otf-and-ttf-files

**Comment by nickdnk** [comment] 2019-01-29 09:39
@tagliala Okay great :)
