### ISSUE TITLE
Icon Request: fa-c# or fa-csharp

### ISSUE THREAD

**Issue by OdarGM** [FortAwesome/Font-Awesome#12955] opened 2018-04-26 18:07 UTC
Can you add icon with the C# logo? :D

**Comment by tagliala** [comment] 2018-04-26 20:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8365, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-26 20:04 UTC
