### ISSUE TITLE
Icon Request: fa-lighthouse

### ISSUE THREAD

**Issue by nhbeachguy** [FortAwesome/Font-Awesome#11266] opened 2017-07-07 14:17 UTC
Would love to see a couple of different lighthouse options.

**Comment by tagliala** [comment] 2017-07-08 11:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5579, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-08 11:25 UTC
