### ISSUE TITLE
Icon request: PostgreSQL

### ISSUE THREAD

**Issue by Mgarzag** [FortAwesome/Font-Awesome#17166] opened 2020-09-17 17:39 UTC
This icon can be used to put on a portfolio. It can also be used as a link to a database.

**Example image (optional)**
![PostgreSQL logo](https://user-images.githubusercontent.com/64109968/93506978-a56e7b80-f8e2-11ea-9743-3890463a3229.png)

**Comment by tagliala** [comment] 2020-09-17 17:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6672, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-17 17:54 UTC
