### ISSUE TITLE
icon request: e-commerce products icon

### ISSUE THREAD

**Issue by alexmorbo** [FortAwesome/Font-Awesome#8525] opened 2016-02-10 15:08 UTC
Hi!

It will be great to add products catalog icon for admin area.

**Comment by tagliala** [comment] 2016-02-11 10:45
could you please provide a single color example suitable for 14px icon size?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by alexmorbo** [comment] 2016-02-11 10:54
[http://www.mirakstellar.com/Images/box.png](url)

**Comment by tagliala** [comment] 2016-02-11 11:31
maybe a duplicate of #908 or #6221

**Comment by alexmorbo** [comment] 2016-02-11 11:37
yes, agree

**Closed** 2016-02-11 11:37 UTC
Labels: waiting for feedback
