### ISSUE TITLE
New Icon : Facebook like friends request icon

### ISSUE THREAD

**Issue by Hemanth089** [FortAwesome/Font-Awesome#7251] opened 2015-08-18 07:12 UTC
Hi,

Can you pl add facebook like friends request icon to font awesome icon set.
![capture image](https://cloud.githubusercontent.com/assets/7092837/9324296/8d55ef78-45a6-11e5-8061-3c5141512dd1.png)

**Comment by tagliala** [comment] 2015-08-18 08:23
duplicate of #2883, please +1 that request

closing here

**Closed by tagliala** 2015-08-18 08:23 UTC
