### ISSUE TITLE
Icon Request: fa-lips

### ISSUE THREAD

**Issue by alex21** [FortAwesome/Font-Awesome#7511] opened 2015-09-22 09:37 UTC
I need lips icon. Can you add this?
Thanks

**Comment by caduvieira** [comment] 2015-09-22 12:24
dupe of #3592?

**Comment by alex21** [comment] 2015-09-22 14:44
Yes something like that.

**Comment by tagliala** [comment] 2015-09-23 08:59
closing here in favour of #3592

**Closed by tagliala** 2015-09-23 08:59 UTC
Labels: waiting for feedback

**Comment by j2studio** [comment] 2015-09-24 16:13
+1
