### ISSUE TITLE
Icon Request: fa-teacher, fa-school

### ISSUE THREAD

**Issue by AwaisKazi** [FortAwesome/Font-Awesome#10978] opened 2017-04-23 11:39 UTC
It would be nice to have an icon with a teacher's face.
I would like to use it on an Educational website, where I plan to put the number of teachers we have under the teacher's icon.

Also, it would be really awesome to have a school's icon, I could use it to display the number of schools we have.

I can use the graduation hat icon(already available) to display the number of students we already have studying.

Thanks!!

**Comment by tagliala** [comment] 2017-04-23 12:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4079 #7671, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-23 12:43 UTC
