### ISSUE TITLE
Icon Request: fa-protonmail

### ISSUE THREAD

**Issue by NightWorx** [FortAwesome/Font-Awesome#11603] opened 2017-10-08 03:46 UTC
An icon for the secure mail service Protonmail (CERN) would be great. Here's the (self-made) SVG:
(besed on https://de.wikipedia.org/wiki/Protonmail#/media/File:Protonmail_logo.svg)

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   id="svg13"
   viewBox="0 0 1024 1024"
   height="1024"
   width="1024"
   version="1.1"
   sodipodi:docname="protonmail_c.svg"
   inkscape:version="0.92.1 r15371">
  <sodipodi:namedview
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1"
     objecttolerance="10"
     gridtolerance="10"
     guidetolerance="10"
     inkscape:pageopacity="0"
     inkscape:pageshadow="2"
     inkscape:window-width="973"
     inkscape:window-height="480"
     id="namedview9"
     showgrid="false"
     inkscape:zoom="0.23046875"
     inkscape:cx="512"
     inkscape:cy="512"
     inkscape:window-x="0"
     inkscape:window-y="0"
     inkscape:window-maximized="0"
     inkscape:current-layer="svg13" />
  <metadata
     id="metadata19">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title />
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <defs
     id="defs17" />
  <g
     style="display:inline;fill:#000000;fill-opacity:1"
     id="g28"
     transform="matrix(1.4663494,0,0,1.4663494,162.00068,22.327839)">
    <path
       id="path24"
       d="M 238.688,0.021 C 153.14446,0.43684852 67.915743,48.34658 29.280014,125.79619 14.623243,155.71142 2.1292315,179.69293 0.25189085,213.17536 L 0,362.521 c 14.392537,30.80385 46.237789,47.81415 72.417752,67.48155 48.377318,36.34291 48.661008,35.77076 117.799858,82.95618 44.4138,28.72574 43.89353,28.786 97.45293,-0.15148 C 344.47412,472.84748 398.24135,435.48724 451.70681,394.47669 464.758,382.9064 480.81313,368.81734 477.376,349.61443 V 213.021 C 464.94877,137.902 422.23239,64.845192 353.00882,29.376972 317.95381,10.918252 278.35691,0.39135981 238.688,0.021 Z m 135.5,294.5 h -271 v -81.5 c -0.30757,-59.74911 57.30846,-110.57644 134.81895,-110.57644 77.28541,0 135.84885,50.33105 135.84885,110.7308 z"
       style="display:inline;fill:#000000;fill-opacity:1"
       inkscape:connector-curvature="0" />
    <path
       style="display:inline;fill:#000000;fill-opacity:1"
       id="path26"
       d="m 0,418.021 v 226.334 c 0,0 1.355,26.333 30.355,26.333 h 416.666 c 29,0 30.355,-26.333 30.355,-26.333 V 418.021 c 0,0 -160.022,114.334 -184.022,131 -52.93296,34.04963 -53.07124,34.53195 -109.333,0"
       inkscape:connector-curvature="0" />
  </g>
</svg>`

**Comment by tagliala** [comment] 2017-10-08 13:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11246, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-08 13:53 UTC

**Comment by NightWorx** [comment] 2017-10-08 20:37
I apologize.
Search for "fa-protonmail" didn't catched "request: protonmail [#11246](https://github.com/FortAwesome/Font-Awesome/issues/11246)"
copyed issue to 11246.
