### ISSUE TITLE
Icon request: icon-warehouse-storage

### ISSUE THREAD

**Issue by enovision** [FortAwesome/Font-Awesome#8280] opened 2016-01-06 22:51 UTC
![sh_014787](https://cloud.githubusercontent.com/assets/1536241/12157191/565dffa8-b4d0-11e5-8bc4-c44637dc463a.jpg)

**Comment by polkovnikov-ph** [comment] 2016-01-15 11:50
Storage is better depicted by the following pic, isn't it?
![image](https://cloud.githubusercontent.com/assets/2983969/12352453/16ca04ae-bb7e-11e5-80ba-fe2c568eb845.png)

**Comment by enovision** [comment] 2016-01-15 15:43
Thank you for your reply, but I meant stock as in warehouse, you're suggestion is for me similar to "database". What I mean is stock as: factory/store related to stock.

**Comment by tagliala** [comment] 2016-01-15 15:44
a more concrete title would be appreciated

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by enovision** [comment] 2016-01-15 16:37
@tagliala, what is not concrete about the request: stock and the sample icon?

**Comment by tagliala** [comment] 2016-03-04 16:56
Duplicate of #4560, please +1 that request

closing here

**Closed by tagliala** 2016-03-04 16:56 UTC
Labels: new icon, web application icons
