### ISSUE TITLE
expanding on fa-glass with fa-glass-wine

### ISSUE THREAD

**Issue by dbengston** [FortAwesome/Font-Awesome#8282] opened 2016-01-07 16:14 UTC
Hello,

Font Awesome is aptly named. These icons are fantastic and so easy to implement. Naturally, I would love to see more and more icons added.

The martini glass (fa-glass) is cool, but I would like to see fa-glass-wine and fa-bottle-wine as additions. Simple silhouettes like fa-glass would be great.

Thanks for all of this.

PS fa-beer is also great. Did I mention this is for a client that distributes alcohol...?

**Comment by floriansegginger** [comment] 2016-01-08 14:36
+1

**Comment by tagliala** [comment] 2016-01-08 18:35
Duplicate of #370 , please +1 that request

closing here

**Closed by tagliala** 2016-01-08 18:35 UTC
