### ISSUE TITLE
Icon Request: fa-o365

### ISSUE THREAD

**Issue by vmartea** [FortAwesome/Font-Awesome#11756] opened 2017-11-14 16:15 UTC
office365 icon neede please!

please see png below,
disregard orange :)
![fa-office-icon](https://user-images.githubusercontent.com/31444624/32790683-157b59ae-c92d-11e7-8218-7093585018fc.png)

I am new to the community, i don't know how things work here, therefore below is the vector file if anyone needs it

[fa-o365.zip](https://github.com/FortAwesome/Font-Awesome/files/1472000/fa-o365.zip)

**Comment by solersounds** [comment] 2017-11-14 17:56
+1

**Comment by wolfy1339** [comment] 2017-11-14 18:36
That's just the generic Office icon.

**Comment by vmartea** [comment] 2017-11-14 19:16
Exactly, I just need an fa icon version of it

Regards,

Vitalie Martea

Information Technology Manager
PA Health Management
Supports Coordination Group
2141 Oregon Pike<x-apple-data-detectors://1/1> |<x-apple-data-detectors://1/1> Lancaster, PA 17601<x-apple-data-detectors://1/1>
Phone: 717-617-2706<tel:717-617-2706> | Fax: 717-617-2534<tel:717-617-2534>
www.pahealthmanagement.org<http://www.pahealthmanagement.org/>
www.edu.pahealthmanagement.org<http://www.edu.pahealthmanagement.org/>

On Nov 14, 2017, at 1:36 PM, wolfy1339 <notifications@github.com<mailto:notifications@github.com>> wrote:


That's just the generic Office icon.

**Comment by tagliala** [comment] 2017-11-23 18:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1333, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-23 18:34 UTC
