### ISSUE TITLE
Icon Request: fa-issuu

### ISSUE THREAD

**Issue by ITSecMedia** [FortAwesome/Font-Awesome#10144] opened 2016-10-31 16:08 UTC
Dear Font-Awesome Team,

Please consider adding a simple brand icon for Issuu => ( https://issuu.com/ )
It would be a great addition to social icons for websites.

Best,
Norman

**Comment by tagliala** [comment] 2016-10-31 17:42
Duplicate of #1993 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-31 17:42 UTC
