### ISSUE TITLE
Icon request: icon-EPT (electronic payment terminal ) 

### ISSUE THREAD

**Issue by Chikeno01** [FortAwesome/Font-Awesome#19530] opened 2023-01-24 08:31 UTC
Hello,
After several searches I did not find the icon of electronic payment terminal.
Since the payment terminal manages money flows, I see it this way:
- Simple icon
- Icon On/Off
- Icon with an incoming arrow (for incoming money flows)
- Icon with an outgoing arrow (for outgoing money flows)

Here is what the EPT is:
![71W0OhBEQoL _AC_SY450_](https://user-images.githubusercontent.com/59655670/214244393-9799e11d-adc8-46da-b32c-a40c8e9c34f8.jpg)

After all there exsit many sort of EPT in the commerce so you can make many icon based on the models in the market.

**Comment by tagliala** [comment] 2023-01-24 08:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7326, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-01-24 08:38 UTC
