### ISSUE TITLE
Icon request: playing-card, deck-of-cards

### ISSUE THREAD

**Issue by kait85** [FortAwesome/Font-Awesome#2101] opened 2013-10-04 20:04 UTC
These could be useful for numerous sites or applications to suggest games or game related stuff.  I wanted to represent a deck of cards and was finding nothing overly suitable

**Comment by Fatbat** [comment] 2015-07-28 05:39
+1

**Comment by philipbkemp** [comment] 2015-08-04 13:40
:+1:

**Comment by dshchupak** [comment] 2015-08-26 17:25
+1

**Comment by mcbyte-it** [comment] 2015-12-29 08:56
+1

**Comment by actuallymab** [comment] 2016-01-03 20:59
+1

**Comment by adamwintle** [comment] 2016-02-21 05:47
+1 for this

**Comment by TheChrisNxt** [comment] 2016-07-11 18:06
also the icons for "clubs, spades, diamonds" would be nice to have. The heart is already implemented.

**Comment by hachesilva** [comment] 2016-08-19 19:05
Duplicate of #606 , that is not solved yet. I sent these icons before when icon submissions were available and they didn't make it to the library.

**Comment by Fatbat** [comment] 2016-08-19 20:27
Aside from corporate shills, has there ever been a user submitted icon accepted into this library?

**Comment by jmcvety** [comment] 2018-04-16 21:06
👍

**Comment by bitedgecom** [comment] 2018-06-02 11:31
+1

General playing card icon, can represent

* Gambling
* Casino
* Poker
* Las Vegas
* Macau

**Comment by pioz** [comment] 2018-09-06 16:00
+1

**Comment by pioz** [comment] 2018-09-06 16:00
Also Magic The Gathering cards!

**Comment by NikosEfthias** [comment] 2019-07-24 11:19
+1

**Comment by bitsboxscott** [comment] 2020-09-26 20:16
+1

**Comment by sensibleworld** [comment] 2021-09-24 17:56
Just released: https://fontawesome.com/v6.0/icons?q=playing%20card&s=solid%2Cbrands

**Comment by tooomm** [comment] 2021-09-25 13:19
@sensibleworld Unfortunately, still no general playing card icon to represent any type of card game.
Or a universal representation of cards in your hand or a stack/deck of cards.

**Comment by pioz** [comment] 2021-09-28 10:47
Yes, an icon for generic card games that can include MTG, Pokemon, Yugioh would be great. These icons are specific for Poker cards.

**Comment by sensibleworld** [comment] 2022-03-16 17:31
Just added in some blank cards: https://fontawesome.com/icons/cards-blank?s=solid

**Closed by sensibleworld** 2022-03-16 17:31 UTC
Labels: new icon, web application icons, Available in FA Pro, in progress
