### ISSUE TITLE
Icon request:fa-draw-line

### ISSUE THREAD

**Issue by jorgevinagre** [FortAwesome/Font-Awesome#3557] opened 2014-05-27 17:05 UTC
To be included in a GIS set of icons.
In GIS we draw geometries of several types: points, lines, polygons and rectangles.
![i_draw_line](https://cloud.githubusercontent.com/assets/3876637/3094870/1e3d2e8a-e5c1-11e3-9c54-21912617f457.png)

**Comment by vtforester** [comment] 2015-01-16 14:13
+1

**Comment by zverev** [comment] 2015-02-25 10:54
+1

**Comment by dbauszus** [comment] 2015-05-22 16:41
+1, I actually just requested the same before doing a more comprehensive search.

**Comment by ubahnverleih** [comment] 2015-06-17 08:24
+1

**Comment by yang3yen** [comment] 2016-01-15 07:24
+1

**Comment by MightyFo0l** [comment] 2016-03-01 12:13
+1

A more simple design
![line2p 1](https://cloud.githubusercontent.com/assets/16845714/13011556/9bad808a-d1a7-11e5-9245-08a993453917.png)

Made this myself (already using it in my app)
![untitled-1](https://cloud.githubusercontent.com/assets/16845714/13011598/ccc7676c-d1a7-11e5-84d0-7d440cdb018b.png)

**Comment by Fairwyn** [comment] 2016-05-10 22:46
+1

**Comment by brian428** [comment] 2016-05-17 16:10
+1

**Comment by redor85** [comment] 2018-07-27 05:35
+1

**Comment by chrismiddle10** [comment] 2024-01-12 19:00
+1

**Comment by sensibleworld** [comment] 2024-07-11 13:56
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/6538)

**Closed by sensibleworld** 2024-07-11 13:56 UTC
Labels: new icon, web application icons (legacy category), Duplicate
