### ISSUE TITLE
Icon Request: fa- faucet

### ISSUE THREAD

**Issue by Ripcurl99983** [FortAwesome/Font-Awesome#11031] opened 2017-05-07 19:26 UTC
Would like to see a faucet icon. Could be used for plumber links, utility companies might want them, symbolize distributing things in small amounts, Chinese water torture, etc. You have a shower and a tub, might as well add a sink and faucet.

![faucet](https://cloud.githubusercontent.com/assets/6563643/25784364/822750e2-3339-11e7-89c3-68234286eade.png)

**Comment by tagliala** [comment] 2017-05-07 22:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10092, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-07 22:08 UTC
