### ISSUE TITLE
Icon request: fa-letterboxd

### ISSUE THREAD

**Issue by plisker** [FortAwesome/Font-Awesome#13976] opened 2018-09-21 00:24 UTC
### What can it be used for?

[Letterboxd](https://letterboxd.com) is a social network to track movie watching, much like how last.fm tracks music listening. The use cases for this icon are, as such, analogous: by linking to one's profile, feed, etc. As an example, in my website I would use the logo to link to my page.

### Example image (optional)

The official logos off which one can base the icon are [here](https://letterboxd.com/about/logos/). The logo would be an outline of them, like for other social media sites. The L with the circle should be easy enough.

The SVG is there, so it'd be low effort to make it!

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-09-21 08:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3680, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-21 08:12 UTC
