### ISSUE TITLE
Bug: Icons not shown in Safari

### ISSUE THREAD

**Issue by VARGA-Peter** [FortAwesome/Font-Awesome#20401] opened 2024-11-03 12:39 UTC
### Bug description

When I load the fonts with my project URL, iOS Safari doesn't show the fonts. Loading it with this URL works.
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

According to several posts it looks like the integrity attribute should be added to the link. How do I get the value for my project?

### Reproducible test case

n/a

### Screenshots

![image](https://github.com/user-attachments/assets/1ab32c42-44f0-4882-8324-a7b1afbab8cb)

### Font Awesome version

latest from the kit

### Serving

Kit

### Implementation

CSS

### Browser and Operating System

iOS Safari

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2024-11-03 18:38
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a reproducible test case?

**Comment by VARGA-Peter** [comment] 2024-11-04 06:44
Hi,

I prepared for you the real page with the broken fonts in Safari. Chrome, FF and other browsers show it correctly.
https://skypex.io/awesome - scroll down to the footer.

When you check the HTML source you see which kit is loaded.

According to Internet, I should provide the integrity hash but I don’t know how to create it because when I access the kit directly it’s rejected due to “Not allowed when Origin missing”.

Can you tell me how to create the integrity hash? I didn’t find anything in the client area where I set up the kit.



Kind regards, Peter

**Comment by tagliala** [comment] 2024-11-04 08:19
Hello,

I can't replicate on macOS Sequoia 15.1 / latest Safari

after a first look, I've noticed that Font Awesome is loaded twice:

<img width="562" alt="image" src="https://github.com/user-attachments/assets/2b221333-3d9b-4615-9713-23ada5bad1f7">

As you can see there is a self-hosted css version and a JS kit

Loading it twice may lead to errors.

Please notice that there could be third parties loading their own version of Font Awesome and we can't provide support for third parties

Note: the kit ID is public. You must restrict allowed domains at `https://fontawesome.com/kits/YOUR-KIT-ID/settings`

**Comment by VARGA-Peter** [comment] 2024-11-04 08:24
I know it's public. I'll restrict it.
Please can you stop telling me that it's third party issue? When I download the fonts from the CDN link it works.

Check it on the iPhone or use any Safari emulator from Web. We have the issue.

Can you please answer my simply question how to get the integrity hash and stop writing stuff I am not asking for?

Kind regards, Peter



Sent from Samsung Fold 4



-------- Ursprüngliche Nachricht --------
Von: Geremia Taglialatela ***@***.***>
Datum: 04.11.24 09:20 (GMT+01:00)
An: FortAwesome/Font-Awesome ***@***.***>
Cc: "Office [FAF Software]" ***@***.***>, Author ***@***.***>
Betreff: Re: [FortAwesome/Font-Awesome] Bug: Icons not shown in Safari (Issue #20401)


Hello,

I can't replicate on macOS Sequoia 15.1 / latest Safari

after a first look, I've noticed that Font Awesome is loaded twice:

image.png (view on web)<https://github.com/user-attachments/assets/2b221333-3d9b-4615-9713-23ada5bad1f7>

Loading it twice may lead to errors.

Please notice that there could be third parties loading their own version of Font Awesome and we can't provide support for third parties

Note: the kit ID is public. You must restrict allowed domains at https://fontawesome.com/kits/YOUR-KIT-ID/settings

**Comment by tagliala** [comment] 2024-11-04 08:31
> Please can you stop telling me that it's third party issue?

Hello, please make sure that Font Awesome is loaded only once. 

According to your use case, you should select:
1. Self-hosted CSS
2. CSS CDN (third-party, no longer offered directly by Font Awesome)
3. Kit

At the moment, the website loads the CSS and the Kit version, this should be fixed

> Can you please answer my simply question how to get the integrity hash

The integrity hash depends on the implementation you are going to use. If you are self-hosting the CSS, I think it is not necessary. If you are going to use the CDN (third-party), then the integrity hash should be included in the copyable `<link>` tag. If you are using the Kit, I'm not sure whether if it is possible, due to the nature of the Kit /cc @robmadole

**Comment by VARGA-Peter** [comment] 2024-11-04 09:16
How can I download the CSS with my plan?
I think, then the issue will be solved.

**Comment by tagliala** [comment] 2024-11-04 09:28
> How can I download the CSS with my plan?

Do ytou have a Pro subscription? If you do, feel free to send an email to hello@fontawesome.com to get dedicated support

Anyway, you can download assets at https://fontawesome.com/download

Please also refer to instructions at: https://docs.fontawesome.com/web/setup/host-yourself/webfonts

You also need to copy webfonts together with the css

**Comment by VARGA-Peter** [comment] 2024-11-04 09:36
Hello, please make sure that Font Awesome is loaded only once.

At the moment, the website loads the CSS and the Kit version, this should be fixed

Where is it load twice? In your screenshot it’s clear that the one link is commented.

So, I repeat myself, the kit breaks Safari on iOS.

**Comment by tagliala** [comment] 2024-11-04 09:48
> At the moment, the website loads the CSS and the Kit version, this should be fixed

Sorry again, you should go for CSS _or_kit. At the moment it appears to only load the CSS, and it works on Safari iOS 18.1

![image](https://github.com/user-attachments/assets/e1835e3f-1446-40cc-8a12-85f2dac68adf)

> So, I repeat myself, the kit breaks Safari on iOS.

If you can provide a reproducible test case, only with the kit (without the css loaded), I will take another look

**Comment by robmadole** [comment] 2024-11-04 13:50
@VARGA-Peter I tried iOS 17 as well and can't reproduce the issue:

![yxRuZbMv@2x](https://github.com/user-attachments/assets/8234189e-afd9-44a7-b8dd-1b32dc62e13f)

We offer support for Pro account holders if you're interested in that. I'm going to go ahead and close since the original post title is not reproducible.

**Closed as completed by robmadole** 2024-11-04 13:50 UTC
Labels: bug, waiting for feedback, needs-triage

**Comment by VARGA-Peter** [comment] 2024-11-04 13:54
Guys, you are indeed very tiresome. You are **_not_** using the URL I told you which is the test case.
Did you see the Instagram icon isn't shown?
You check it in the fixed version. The kit still doesn't work. 
And, I am definitely not paying for a Pro plan because your product is buggy.

**Comment by robmadole** [comment] 2024-11-04 14:14
> I prepared for you the real page with the broken fonts in Safari. Chrome, FF and other browsers show it correctly.
https://skypex.io/awesome - scroll down to the footer.

`https://skypex.io/awesome`

This is the address I used. Is that not the test case?

Also, the tone in your messages is disrespectful. We are trying to help you, be kind or I will block you.

**Comment by tagliala** [comment] 2024-11-04 14:41
@robmadole my speculation is that the problem is still present in the homepage, but in the homepage I can still see both the kit and the link to the self-hosted css

I would like to see the kit working alone to provide helpful info

**Comment by VARGA-Peter** [comment] 2024-11-04 14:46
Guys,

The links are commented. Please have a look.
On the HP I am using now the embedded version.

**Comment by robmadole** [comment] 2024-11-04 15:10
![Rl9QaF3l@2x](https://github.com/user-attachments/assets/5f7eb100-8ab4-4f7b-a342-fa522f7759a5)

Your CSS class is incorrect. Try `fab fa-instagram` or `fa-brands fa-instagram`.

**Comment by VARGA-Peter** [comment] 2024-11-04 15:14
Thank you Rob, this worked.
However, the point is that embedded version works and kit version doesn’t.
In the end, I am happy, it works now. But when you check Internet there are posts which mentioned it’s because of missing integrity hash in the link.

**Comment by robmadole** [comment] 2024-11-04 15:30
> But when you check Internet there are posts which mentioned it’s because of missing integrity hash in the link.

What posts specifically?

> However, the point is that embedded version works and kit version doesn’t.

Have you re-tested now that you've fixed the root cause?
