### ISSUE TITLE
Icon Request: Opened email

### ISSUE THREAD

**Issue by ttamas7** [FortAwesome/Font-Awesome#7600] opened 2015-10-03 13:59 UTC
Hello,
first of all let me express you're doing a terrific job.

Would it be possible also to include an opened email.
See our bitmap.

Thank you so much for a consideration:)
Teodor
![ico_opened](https://cloud.githubusercontent.com/assets/14953866/10263262/b3b950be-69e7-11e5-8b11-27937e71944d.png)

**Comment by tagliala** [comment] 2015-10-04 19:46
duplicate of #897 , scheduled for 5.0.0 but please +1 that request

closing here

**Closed by tagliala** 2015-10-04 19:46 UTC

**Comment by ttamas7** [comment] 2015-10-05 06:53
thanks
