### ISSUE TITLE
Icon request: light-strip

### ISSUE THREAD

**Issue by MarkLyck** [FortAwesome/Font-Awesome#19126] opened 2022-06-13 19:28 UTC
### Use case

icon for a light strip. (LED light strip).

Great for smart home applications.

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2022-06-13 20:42
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #16755. I've asked for a single color example there, but I didn't get one. Could you please go to https://github.com/FortAwesome/Font-Awesome/issues/16755 and add a single color, 16px icon size suitable example of how a light strip / led strip should look like?

**Closed as completed by tagliala** 2022-06-13 20:42 UTC
Labels: new icon
