### ISSUE TITLE
Icon Pack request: Iot

### ISSUE THREAD

**Issue by ymirabalg** [FortAwesome/Font-Awesome#14271] opened 2018-11-13 16:47 UTC
It will be very useful to have icons related to Iot and IoT projects prototyping like raspberry and arduino in its different flavors, icons for sensors and most popular electronic components used in this kind of projects

**Comment by tagliala** [comment] 2018-11-13 17:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10463, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-11-13 17:11 UTC
