### ISSUE TITLE
Icon Request: fa-cricket

### ISSUE THREAD

**Issue by ankurvs** [FortAwesome/Font-Awesome#9372] opened 2016-06-08 13:37 UTC
we need cricket icon.

**Comment by tagliala** [comment] 2016-06-08 13:40
Duplicate of #5706, #7200 or #7201, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-08 13:40 UTC
