### ISSUE TITLE
Icon Request: fa-government

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9997] opened 2016-09-29 18:19 UTC
Icon needed to depict federal government or governance body for use within a healthcare app
![government](https://cloud.githubusercontent.com/assets/539719/18966586/c5644f5a-864f-11e6-89fe-b292c0b35f6b.png)

**Comment by tagliala** [comment] 2016-09-30 09:04
Duplicate of #2440 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 09:04 UTC
