### ISSUE TITLE
Icon Request: Color Palette

### ISSUE THREAD

**Issue by brainmaniac** [FortAwesome/Font-Awesome#11052] opened 2017-05-11 06:09 UTC
Hello

I would like to request an icon that looks like a color palette please.

Possibly something similar to this: https://thenounproject.com/term/color-palette/218734/

I am working on two projects where we let the user customize the workspace by for example change color of background.

Thanks in advance you are making life easier for us webdevs!

**Comment by tagliala** [comment] 2017-05-11 09:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1453 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-11 09:28 UTC

**Comment by brainmaniac** [comment] 2017-05-11 09:42
Hello Tagliala,

Thank you for your answer. I do not however fully agree that the referenced issue is the same as mine. I could find several issues for paint bucket which I do agree would be a useful addition. However I am looking for the color palette - icon referenced in my post.

**Comment by tagliala** [comment] 2017-05-11 09:46
@brainmaniac sorry, don't know what happened with auto completion: #244

**Comment by brainmaniac** [comment] 2017-05-11 09:51
LOL no worries! Just found that using search :)

I have added my +1

Thank you!
