### ISSUE TITLE
Icon request: dolphin

### ISSUE THREAD

**Issue by AldoKaizen** [FortAwesome/Font-Awesome#16675] opened 2020-05-19 20:13 UTC
**What can it be used for?**
We need to show general information about dolphins and the laws that protects them. 

I found kiwi-bird, dragons, unicorns, pegasus, the merge between unicons and pegasus: alicorn... and we don't have Dolphins? The arguably second most intelligent animal in the planet.

Please, make it happen.

**Comment by tagliala** [comment] 2020-05-19 20:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14820, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-19 20:59 UTC
