### ISSUE TITLE
Icon Request: fa-trending-up/down

### ISSUE THREAD

**Issue by kit246** [FortAwesome/Font-Awesome#12626] opened 2018-03-16 17:39 UTC
Hi,
It would be very appreciated if Font Awesome had an arrow icon for trending/growth up and down.
Something similar to what [Feather Icons](https://feathericons.com/) have already (trending-down or trending-up) or what Icomoon ultimate has (stats-growth2).
Thank you

**Comment by tagliala** [comment] 2018-03-16 19:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4397, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-16 19:07 UTC
