### ISSUE TITLE
Icon Request - Brand - Model Mayhem

### ISSUE THREAD

**Issue by joeytaft** [FortAwesome/Font-Awesome#17180] opened 2020-09-21 03:21 UTC
**What can it be used for?**
This icon can be used by photographers, models, artists, actors, etc.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/9851704/93730640-bc34fc80-fb86-11ea-976f-91b2298566a2.jpeg)

**Icon request checklist**
- [single icon ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-09-21 07:31
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8041, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-21 07:31 UTC
