### ISSUE TITLE
Icon Request: fa-builder

### ISSUE THREAD

**Issue by daniel152** [FortAwesome/Font-Awesome#12480] opened 2018-02-28 10:36 UTC
to represent a builder or tradesman

builder user login

https://www.iconfinder.com/icons/290400/builder_constructor_helmet_worker_icon

https://www.iconfinder.com/icons/2629998/builder_contractor_worker_icon#size=512

**Comment by tagliala** [comment] 2018-02-28 12:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9381, please add a 👍  reaction to that request.

It also refers to #5790 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-28 12:10 UTC
