### ISSUE TITLE
Icon request: Nextdoor

### ISSUE THREAD

**Issue by likethegoddess** [FortAwesome/Font-Awesome#16494] opened 2020-04-17 19:50 UTC
**What can it be used for?**
Icon can be used to link to groups on Nextdoor. 

**Example image (optional)**
https://www.iconfinder.com/icons/2613272/community_neighborhood_nextdoor_private_social_social_media_icon

**Icon request checklist**
- [ Single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ y ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ y ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ y ] I have included at least one example image if it could be helpful (optional)
- [ y ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Thanks you!

**Comment by tagliala** [comment] 2020-04-17 21:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3928, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-04-17 21:20 UTC
