### ISSUE TITLE
Icon request: icon-plain-language

### ISSUE THREAD

**Issue by 21cdb** [FortAwesome/Font-Awesome#6911] opened 2015-07-09 14:22 UTC
I would like to request an icon that represents areas of websites (text), which are written in (simple) plain language and are therefore are easily to understand for people with handicaps. In germany we call it "Leichte Sprache" which translates to "easy (German) language [language used in a simple manner]". 

There is an inofficially icon provided by a inclusion europe network for print products which dosn't transfer that well into (digital) web and certainly isn't created by a professionel designer as most of the work is done on a volunteer basis: https://de.wikipedia.org/wiki/Leichte_Sprache#/media/File:Leichte_sprache_logo.svg 

Another more professionel example: https://www.gruenderwoche.de/assets/bilder/90x62/leichte_sprache_icon_90__62.jpeg

We would like to use this icon to highlight those areas of our websites which provide content in plain language fo people with handicaps. 

It would be great if Font-Awesome could support our growing community by providing an icon-plain-language.

Thank you in advance!
Jan

**Comment by tagliala** [comment] 2015-07-09 19:27
I don't know if this could be considered a duplicate of #4808

**Comment by 21cdb** [comment] 2015-07-10 14:33
I guess #4808 couldn't be considered as duplicate but as a starter icon where one could add the "thumb up" on the left side of the book to build an own dedicated icon for plain-language. However i would understand and appreciate if you would build #4808 first since it resembles  https://de.wikipedia.org/wiki/Leichte_Sprache#/media/File:Leichte_sprache_logo.svg and therefore would be very helpful indeed!

**Comment by sensibleworld** [comment] 2024-07-10 21:43
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-10 21:43 UTC
Labels: new icon, web application icons (legacy category), waiting for feedback, Declined
