### ISSUE TITLE
Icon request: icon-angle-circle-* (4 icons)

### ISSUE THREAD

**Issue by qsefthukol** [FortAwesome/Font-Awesome#10615] opened 2017-02-05 04:09 UTC
Just add a circle to the exist icons( icon-angle-double-up,icon-angle-double-right,icon-angle-double-down,icon-angle-double-left,icon-angle-up,icon-angle-right,icon-angle-down,icon-angle-left).
Sometimes need to enhence the effect of the angle icons!

**Comment by tagliala** [comment] 2017-02-05 11:20
Hi!

Thanks for being part of the Font Awesome Community.

Please also consider stacking icons or a simple css border with 100% radius (if you don't need IE8)

**Comment by tagliala** [comment] 2017-02-05 11:21
angle-double-circle-* is a duplicate of #8651, please add a 👍 reaction to that request

**Comment by qsefthukol** [comment] 2017-02-05 15:27
oh, by css border method, it can't display perfect. in different browser, the border thickness can not be displayed as same as icon font, expecially with zoom effect!
I find icon-arrow-circle-* in the 4.7 version, why not icon-angle-circle-*? hope you can accept my request, I think many your fans like me need this circle style angle icon!

**Comment by sensibleworld** [comment] 2024-07-11 20:08
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()

**Closed by sensibleworld** 2024-07-11 20:08 UTC
Labels: new icon, arrows (category), FA Pro
