### ISSUE TITLE
Browse icons by version

### ISSUE THREAD

**Issue by rbirmann** [FortAwesome/Font-Awesome#13098] opened 2018-05-10 22:59 UTC
Would it be possible to make this version number clickable and leading to a subset of the icon gallery with only the icons released in that specific version??

![2018-05-10_1955](https://user-images.githubusercontent.com/39135342/39898246-5665f970-548c-11e8-96ee-421517f536bd.png)

I trying to find an easy way to browse through the icons introduced in 5.0.13, but can't find a way to do that...

Alternatively, maybe searching for the version number could work....

![image](https://user-images.githubusercontent.com/39135342/39898316-94c3eca4-548c-11e8-815b-f850a66a8325.png)

**Comment by tagliala** [comment] 2018-05-11 10:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12483, please post there your comment

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-11 10:25 UTC
