### ISSUE TITLE
Icon request: cargobike

### ISSUE THREAD

**Issue by Chrischmi** [FortAwesome/Font-Awesome#14388] opened 2018-12-11 21:42 UTC
### What can it be used for?

Bike parking spaces for specific bike
Bike rental for specific types

### Example image (optional)
https://thenounproject.com/term/cargo-bike/

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by rwolffgang** [comment] 2018-12-12 20:43
This would be a great addition!

**Comment by flegfleg** [comment] 2019-05-03 09:13
Cargo bikes are an important part of the mobility transition and we need an icon!

**Comment by michelri** [comment] 2022-01-02 21:09
Yes please!

**Comment by sensibleworld** [comment] 2024-07-11 19:11
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/5723)

**Closed by sensibleworld** 2024-07-11 19:11 UTC
Labels: new icon, transportation (category), Duplicate
