### ISSUE TITLE
Icon Request: fa-masquerade-mask

### ISSUE THREAD

**Issue by WebVeteran** [FortAwesome/Font-Awesome#11169] opened 2017-06-14 02:12 UTC
Use Cases:

- Denote a record as being private. Perhaps an image or file in a user based site.
- A utility that enables the user to masquerade as another's role. For example if you're an Admin in a CMS and you want to test out the CMS as an Editor, you can masquerade as so until logging out.

Example, Firefox's "private mode" icon:
![firefox](https://user-images.githubusercontent.com/40175/27112426-0409b498-5085-11e7-9080-927d39251c65.png)

Thank you in advance.

**Comment by aethior** [comment] 2017-06-14 08:06
Duplicate of #1562.

**Closed** 2017-06-14 08:29 UTC
