### ISSUE TITLE
Icon Request: fa-DNA

### ISSUE THREAD

**Issue by HaniehAzad** [FortAwesome/Font-Awesome#11584] opened 2017-10-04 01:01 UTC
Genome, DNA

**Comment by tagliala** [comment] 2017-10-04 08:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1195 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-04 08:49 UTC
