### ISSUE TITLE
Icon Request: fa-jet-ski

### ISSUE THREAD

**Issue by deepu05** [FortAwesome/Font-Awesome#10471] opened 2017-01-05 10:31 UTC
Most of travels websites includes things to do and this a common activity at beach side. So i was requesting  that if you could make this... it will be helpful for many websites..

**Comment by tagliala** [comment] 2017-01-05 11:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5714, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-05 11:36 UTC
