### ISSUE TITLE
fas-bone-break missing

### ISSUE THREAD

**Issue by cod3rshotout** [FortAwesome/Font-Awesome#18840] opened 2022-03-22 08:28 UTC
https://fontawesome.com/v5/icons/bone-break?s=solid

I'm using the version 5.15.4 but isn't showing, why?

**Comment by tagliala** [comment] 2022-03-22 08:58
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, can't reproduce.

Demo (5.15.14 Pro): https://jsfiddle.net/tagliala/vf0besm4/3/

Note: this is a Pro icon, so I suppose you are a Pro customer. As a pro customer, you can ask for dedicated support by sending an email to hello@fontawesome.com

Please also double check that there aren't third-party plugins/themes/libraries loading an older version of Font Awesome that may have priority over yours

If you are still experiencing this issue, please open a new request, fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md), and provide a reproducible test case

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

Ref: 
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Closed as completed by tagliala** 2022-03-22 08:58 UTC
