### ISSUE TITLE
Icon Request: fa-phone-slash

### ISSUE THREAD

**Issue by kolniy** [FortAwesome/Font-Awesome#17799] opened 2021-04-08 10:32 UTC
Need the phone call end icon or phone slash. thanks, looking forward to your reply

**Comment by tagliala** [comment] 2021-04-08 15:24
Hi!

Thanks for being part of the Font Awesome Community.

Phone slash is already available: https://fontawesome.com/icons/phone-slash?style=solid

phone call end is a duplicate of #4405, and it will be available in FA6

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2021-04-08 15:24 UTC
