### ISSUE TITLE
Icon request: fire-truck; fire-engine; fire-station

### ISSUE THREAD

**Issue by fireboy998** [FortAwesome/Font-Awesome#16695] opened 2020-05-21 19:24 UTC
Since there are a hostpital and ambulance icons it would be good to have fire truck/engine and fire station icons.
Usage the same as hospital and ambulance. Any kind of emergency website/projects. 

Police icons would be also appreciated :)

**Comment by tagliala** [comment] 2020-05-23 12:22
Hi!

Thanks for being part of the Font Awesome Community.

Fire engine is a duplicate of #4812, please add a 👍 reaction to that request.
Fire truck is a duplicate of #4813, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-23 12:22 UTC
