### ISSUE TITLE
Amazon music icon

### ISSUE THREAD

**Issue by Bodybyloud** [FortAwesome/Font-Awesome#13753] opened 2018-08-12 03:25 UTC
I just wanted to request the icon for amazon music.

**Comment by tagliala** [comment] 2018-08-12 10:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13403, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-12 10:10 UTC
