### ISSUE TITLE
Icon request: condom

### ISSUE THREAD

**Issue by lzzzzzzz** [FortAwesome/Font-Awesome#15832] opened 2019-11-20 23:41 UTC
**What can it be used for?**
A rolled out condom icon for use in sexual health promotion, sex education, and sale of sexual health products.

**Example image (optional)**
https://cdn.iconscout.com/icon/premium/png-256-thumb/condom-38-307437.png

**Comment by aethior** [comment] 2022-04-15 00:47
This request is duplicate of #6127.
Please add a 👍 reaction to that request.

cc/ @tagliala

**Closed** 2022-04-15 07:50 UTC
Labels: new icon, medical / health (category)
