### ISSUE TITLE
Icon Request : icon-viadeo

### ISSUE THREAD

**Issue by bertoul** [FortAwesome/Font-Awesome#5615] opened 2015-02-08 08:18 UTC
Icon for viadeo site : http://fr.viadeo.com/fr/

![521269_10151403172293833_1884277130_n](https://cloud.githubusercontent.com/assets/10906063/6095882/51f7dfe6-af73-11e4-95a3-8e18a613c297.png)
![safe_image](https://cloud.githubusercontent.com/assets/10906063/6095883/51f8a976-af73-11e4-9b65-7e9f5bc615af.png)

icon available in two versions : fa-viadeo / fa-viadeo-square

Thank you very much

**Comment by tagliala** [comment] 2015-02-08 15:05
duplicate of #886 , please +1 that request

**Closed by tagliala** 2015-02-08 15:05 UTC
