### ISSUE TITLE
Icon Request: fa-card

### ISSUE THREAD

**Issue by micheleangioni** [FortAwesome/Font-Awesome#7800] opened 2015-11-02 19:38 UTC
Hi!
First of all, let me tell you thanks for the Font-Awesome service, it's really useful!
Then, an incredibly simple and useful icon should be added to the set: a card.

Typical examples could be the football cards:
yellow card: https://en.wikipedia.org/wiki/File:Yellow_card.svg
red card: https://en.wikipedia.org/wiki/File:Red_card.svg

but I suppose use cases are many. It could also work great combined with other icons / fonts.

Realizing it should be straightforward: just raise a bit fa-square 's height.

Thanks.

**Comment by tagliala** [comment] 2015-11-14 11:25
Duplicate of #4621, please +1 that request

closing here

**Closed by tagliala** 2015-11-14 11:25 UTC
