### ISSUE TITLE
Icon request: fa-bush, fa-bush-rolling

### ISSUE THREAD

**Issue by Zaczero** [FortAwesome/Font-Awesome#15756] opened 2019-10-31 13:30 UTC
**What can it be used for?**
Everyone knows the lonely bush rolling on the desert. It would be a great icon for putting along with messages like "No data", "Not found", "Nothing here" etc.

**Example image (optional)**
![rolling desert bush](https://i.imgur.com/HrAAC6L.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-11-05 21:18
Hi!

Thanks for being part of the Font Awesome Community.

I would like a tumbleweed icon, have you any single color, 16px suitable example?

**Comment by Zaczero** [comment] 2019-11-07 15:01
@tagliala 
Here are some examples I've found on the web.
The selected ones are good representation of what I had in mind.
The top-left selected one looks a little better though.

![](https://i.imgur.com/1NHGLN6.png)

**Comment by aethior** [comment] 2022-03-11 21:21
Duplicate of #14207.

cc/ @tagliala

**Closed** 2022-03-11 21:25 UTC
Labels: waiting for feedback
