### ISSUE TITLE
icon-request: fa-vevo

### ISSUE THREAD

**Issue by steveseow** [FortAwesome/Font-Awesome#8996] opened 2016-04-15 18:25 UTC
Use: brand icon to signify links, etc. pointing to a Vevo resource

My Usage: I have a website that is already utilizing fa-youtube, fa-vimeo, etc. would love to add Vevo given the popularity of the media platform.

THANK YOU TEAM! KEEP UP THE GOOD WORK!

![vevo-5 0-for-ios-app-icon-small](https://cloud.githubusercontent.com/assets/1329015/14571204/c2fadddc-02fc-11e6-96d1-2a1f7a826264.png)

**Comment by PeterShaggyNoble** [comment] 2016-04-15 19:15
Dupe of [#3428](https://github.com/FortAwesome/Font-Awesome/issues/3428), you should +1 that one instead.

**Closed** 2016-04-15 20:34 UTC
