### ISSUE TITLE
Icon request: lactose / milk, lactose-slash / milk-slash

### ISSUE THREAD

**Issue by Radzio1615** [FortAwesome/Font-Awesome#18706] opened 2022-02-16 06:11 UTC
**What can it be used for?**
Icon can be used to mark recipes / products with milk and lactose-free recipes / products.

**Example image**
![image](https://user-images.githubusercontent.com/40895581/154206301-c3d7a3ea-adc4-41e5-8d54-c8db3c798ba1.png)

**Comment by aethior** [comment] 2023-03-13 19:38
@tagliala `food-beverage (category)` label for this request?

**Comment by sensibleworld** [comment] 2024-07-11 15:14
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/3663)

**Closed as completed by sensibleworld** 2024-07-11 15:14 UTC
Labels: new icon, Duplicate
