### ISSUE TITLE
Icon Request: fa-shopping-basket-o

### ISSUE THREAD

**Issue by KennethDanielsen** [FortAwesome/Font-Awesome#11079] opened 2017-05-17 08:54 UTC
Some of the most generic icons lack an outlined version. 
In my case I'm missing the shopping-bag, shopping-basket and shopping-cart.

Something you'll consider? :-)

**Comment by tagliala** [comment] 2017-05-17 09:03
Hi!

Thanks for being part of the Font Awesome Community.

shopping-cart-o is a duplicate of #10051, please 👍  that request
shopping-bag-o is a duplicate of #10321, please 👍  that request

Renaming this as `fa-shopping-basket-o`

**Comment by tagliala** [comment] 2019-07-04 21:12
This icon is available in FA5 Pro

https://fontawesome.com/icons/shopping-basket?style=regular

**Closed by tagliala** 2019-07-04 21:12 UTC
Labels: new icon, web application icons
