### ISSUE TITLE
Icon request: plus-circle-o

### ISSUE THREAD

**Issue by gianues** [FortAwesome/Font-Awesome#11244] opened 2017-07-01 09:04 UTC
Existing icon pairs with -o:

- plus-square / plus-square-o
- pause-circle / pause-circle-o
- ...
- plus-circle / ?

A plus-circle-o is missing...

**Comment by tagliala** [comment] 2017-07-01 09:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2417, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-01 09:27 UTC
