### ISSUE TITLE
Icon Request: fa-flipboard

### ISSUE THREAD

**Issue by jackcksn** [FortAwesome/Font-Awesome#5637] opened 2015-02-10 20:16 UTC
![flipboard-social](https://cloud.githubusercontent.com/assets/10945676/6135497/1ca9ef86-b1a4-11e4-8814-58a848274b6b.png)

How do my plan on using it? 
I will use for wordpress Social Network icon.

May i know how long will complete it ?Thank you very much.

**Comment by tagliala** [comment] 2015-02-13 00:20
@jackcksn duplicate of #1382 

Please read this wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#new-icons

closing here

**Closed by tagliala** 2015-02-13 00:20 UTC
