### ISSUE TITLE
Icon Request: U-Turn

### ISSUE THREAD

**Issue by dickysum** [FortAwesome/Font-Awesome#20394] opened 2024-10-23 21:25 UTC
### Checklist

- [X] The title of this issue starts with "Icon Request: " and is followed by the new icon name *(ex. "Icon Request: Proton Torpedo")*
- [X] This icon does not represent a brand
- [X] This request is for a single icon or a matched pair *(ex. `lock` and `unlock`)*
- [X] I've already [searched through existing issues](https://github.com/FortAwesome/Font-Awesome/issues), and to the best of my knowledge this request isn't a duplicate
- [X] I understand [how new icon requests work](https://fontawesome.com/support#requesting-icons)

### Request type

✨ New icon

### Use case

A navigation application that instructs the driver to do a U-turn at the upcoming intersection.

### Visual example

https://www.bing.com/images/search?q=u-turn%20symbol&form=IQFRBA&id=694461890371883AFB983B67A84F720BA99AF8BE&first=1&disoverlay=1

**Comment by tagliala** [comment] 2024-10-23 21:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10023, which has been accepted (so no need to +1). You can subscribe to that issue to receive updates

Hope it helps

Closing here

**Closed as completed by tagliala** 2024-10-23 21:41 UTC
Labels: new icon
