### ISSUE TITLE
Weird characters (5.4.1, Edge, Windows)

### ISSUE THREAD

**Issue by jarahn** [FortAwesome/Font-Awesome#17611] opened 2021-02-05 23:51 UTC
**Describe the bug**
Icons are rendering as strange characters. Related issues: #14660 #10842
Examining previous bug reports, it does not appear that there is an official workaround from Font Awesome.

**To Reproduce**
Seems to happen randomly across all of our sites. Occurs locally, in our beta build, and in production.
Unable to offer a reproducible scenario. No console errors on the browser.

**Expected behavior**
The icons to render appropriately.

**Screenshots**
Attached a screen shot. Also attached .txt file with relevant compiled css. Unsure of how to upload the compiled css file.
[FA-compiled-css-hieroglyphics.txt](https://github.com/FortAwesome/Font-Awesome/files/5935933/FA-compiled-css-hieroglyphics.txt)

![font-awesome-icon-bug](https://user-images.githubusercontent.com/56607728/107100131-19011e80-67d9-11eb-9f40-9afa8eb47ee6.png)

**Version and implementation**
Version: Font Awesome 5 Pro 5.4.1
Browser and version: Edge 88, Windows 10 OS

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2021-02-06 08:30
Hi!

Thanks for being part of the Font Awesome Community.

I think that this issue is generated by the preprocessor or uglifier that your application is using. Maybe an old version of Sass?

This has been fixed on our side: 

The following content taken from your attachment is not correct:

```css
.fa-home:before{content:"ï€•"}
```

You should see this:

```css
.fa-home:before {content:"\f015";}
```

Ref: https://github.com/FortAwesome/Font-Awesome/blob/5.15.2/css/fontawesome.css#L2190-L2191

Please make sure that your front-end module bundler produces a correct CSS

Closing here, but feel free to comment

Ref:
- #6552
- #6728
- #10842 
- https://github.com/FortAwesome/Font-Awesome/issues/10842#issuecomment-609702030

**Closed by tagliala** 2021-02-06 08:30 UTC

**Comment by ADNewsom09** [comment] 2021-02-09 19:51
Considering it doesn't get recompiled or redeployed between working/not working what other options are there, bad network?

**Comment by tagliala** [comment] 2021-02-09 20:06
> Considering it doesn't get recompiled or redeployed between working/not working what other options are there, bad network?

Without a reproducible test case it is hard to debug or help

Please make sure that the stylesheet served by your web application contains properly escaped unicode points (`"\f015"`)

**Comment by JiriZidek** [comment] 2021-02-25 11:56
Just to confirm, that this happens on Chrome (versions within last half year) and Windows 10. I'm almost sure it is chromium problem. Unfortunately the occurence is random and we have no repro. From the occurences we can cocnlude, it is not prolem of minifaction (happens on non-minified CSS as well, it is not problem of web server. It looks like the css is cached in some preprocessed state, and after some time some "metadata" get lost so only F5 helps.

**Comment by casyalex** [comment] 2021-04-16 03:31
> Just to confirm, that this happens on Chrome (versions within last half year) and Windows 10. I'm almost sure it is chromium problem. Unfortunately the occurence is random and we have no repro. From the occurences we can cocnlude, it is not prolem of minification (happens on non-minified CSS as well, it is not problem of web server. It looks like the css is cached in some preprocessed state, and after some time some "metadata" get lost so only F5 helps.

It also happens on Mac, I am trying to fix it by upgrade Sass lib.

**Comment by tagliala** [comment] 2021-04-16 07:26
> It also happens on Mac, I am trying to fix it by upgrade Sass lib.

There are several reasons for this issue, so maybe the output is the same, but the reason is different

The problem is in the combination of FA + New Dart Sass / Ruby Sass libraries.

A breaking change introduced in Dart Sass 1.10.4 and 1.11.0 and Ruby Sass 3.6.0 to 3.7.0, does not allow our escaping function to keep working anymore, anyway...


If your output css looks like `.fa-home:before{content:"ï€•"}`, then there is definitely an issue. If it instead looks like `.fa-home:before { content: ""; }`, then it is ok but please make sure that:

1. The served CSS file starts with `@charset "UTF-8";`; OR
2. The HTML file including your CSS has the `<meta charset="utf-8">` meta tag
