### ISSUE TITLE
Icon Request: icon-opensource

### ISSUE THREAD

**Issue by cedricve** [FortAwesome/Font-Awesome#6200] opened 2015-04-11 12:21 UTC
https://www.google.be/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=open%20source%20icon

**Comment by sekjal** [comment] 2015-04-13 14:40
Would be good for comparing different software solutions in a list.  +1

**Comment by caduvieira** [comment] 2015-04-14 18:04
+1

**Comment by Grimdari** [comment] 2015-06-04 21:06
Definitely a +1.

**Comment by abbynucup** [comment] 2015-06-21 16:48
+1

**Comment by tagliala** [comment] 2015-06-21 19:48
duplicate of #1283, please +1 that request

closing here

**Closed by tagliala** 2015-06-21 19:48 UTC
