### ISSUE TITLE
Icon Request: user-executive

### ISSUE THREAD

**Issue by racerx777** [FortAwesome/Font-Awesome#7280] opened 2015-08-21 18:39 UTC
Some areas of web applications are only available to executives, such as a "Executive Dashboard" instead of a "User Dashboard". I'm not finding any icons you offer to handle this. Here's an example: 
![user-exec](https://cloud.githubusercontent.com/assets/13908032/9416229/37d838c6-47f9-11e5-999b-82b078f89be6.png)

**Comment by tagliala** [comment] 2015-08-22 09:34
duplicate of #3397

please +1 that request and post there your example

Closing here

**Closed by tagliala** 2015-08-22 09:34 UTC
