### ISSUE TITLE
Icon request: HOT 

### ISSUE THREAD

**Issue by jonnyshocko** [FortAwesome/Font-Awesome#8605] opened 2016-02-18 18:05 UTC
My team needs the ability to mark deal as HOT in our crm software. The "fire" icon is currently too vague and doesn't connect with the user in a way I was hoping. 

I would love to have something like this if possible :)

<img width="61" alt="screen_shot_2015-08-27_at_1 13 51_pm" src="https://cloud.githubusercontent.com/assets/16492115/13153079/3a425b7a-d640-11e5-962b-aa616610614e.png">

**Comment by tagliala** [comment] 2016-02-18 19:03
considering this a duplicate of #3577

**Closed by tagliala** 2016-02-18 19:03 UTC
