### ISSUE TITLE
Icon Request: fa-discogs

### ISSUE THREAD

**Issue by h3lge** [FortAwesome/Font-Awesome#11445] opened 2017-08-25 09:37 UTC
Maybe their favicon could already do? -> ![](https://s.discogs.com/images/favicon.ico)

**Comment by tagliala** [comment] 2017-08-25 12:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5111 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-25 12:17 UTC
