### ISSUE TITLE
Icon request: bento-menu (circle-grid)

### ISSUE THREAD

**Issue by j0lir0uge** [FortAwesome/Font-Awesome#15452] opened 2019-08-29 10:43 UTC
**What can it be used for?**

It's well known that designers don't have the time to go to the restaurant and bring their own bento at work. Tho, in this very topic, it's more about another browsing icon that is used for cross-apps navigation. The bento-menu icon — named this way by other people in the same idea of the hamburger menu — is made of 9 little dots (or squares) organised in a perfect square. It symbolises the apps displayed as a grid of icons. It's **different** from other grids (for example the "th" icon) because every dot is clearly separated from each other, especially in a Light usage.

**Example image (optional)**

![image](https://user-images.githubusercontent.com/48244834/63933566-c8b95500-ca59-11e9-8f2c-d8d48d7eeda4.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-08-29 19:47
Hi!

Thanks for being part of the Font Awesome Community.

If I recall correctly, this is a duplicate of another request but at the moment I'm not able to find the original request (probably it has a different name or I'm simply wrong), so I'm going to keep this open

**Comment by sofiepett91** [comment] 2022-01-25 22:15
I would love for this icon to be made. It seems to be used more and more for complex services.

**Comment by sensibleworld** [comment] 2024-07-11 18:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/grid-round?f=classic&s=solid)

**Closed by sensibleworld** 2024-07-11 18:23 UTC
Labels: new icon, web application icons (legacy category), FA Pro
