### ISSUE TITLE
Icon Request: icon-ruler

### ISSUE THREAD

**Issue by SteveJordanKW** [FortAwesome/Font-Awesome#8639] opened 2016-02-23 22:17 UTC
Useful to describe/toggle metrics
![ruler](https://cloud.githubusercontent.com/assets/1433903/13268569/3f1519fc-da51-11e5-9b56-7e6ce774b54b.png)

**Comment by tagliala** [comment] 2016-02-24 10:29
duplicate of #1096 , please +1 that request

closing here

**Closed by tagliala** 2016-02-24 10:29 UTC
