### ISSUE TITLE
Icon request: icon-equals

### ISSUE THREAD

**Issue by GustavoSjcBr** [FortAwesome/Font-Awesome#10328] opened 2016-12-07 14:54 UTC
Hello guys,

You have icon-munis and icon-plus, would be a nice idea to have icon-equals.

Regards,

Gustavo Cursino

**Comment by rdeutsch** [comment] 2017-03-05 20:37
I also need an equal sign (to represent basic math functions, and to go along with the plus, minus and times icons that already exist).


Please note that this request for the same was already closed by citing a duplicate request:
https://github.com/FortAwesome/Font-Awesome/issues/9270

However, the duplicate issue linked to (#1133) does not exist! I tried to go to that issue to +1 but got an error that this page does not exist: https://github.com/FortAwesome/Font-Awesome/issues/1133

**Comment by tagliala** [comment] 2017-10-28 21:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1133, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-28 21:35 UTC
