### ISSUE TITLE
Icon Request: snow

### ISSUE THREAD

**Issue by luansemensatoribeiro** [FortAwesome/Font-Awesome#6774] opened 2015-06-17 14:23 UTC

**Comment by ShamanFromSiberia** [comment] 2015-07-01 08:00
I would suggest weather icons, something of this type: https://www.google.ru/search?q=weather+icons&newwindow=1&safe=off&rlz=1C1GGGE_ruRU550RU554&espv=2&biw=1536&bih=814&tbm=isch&imgil=60FQYEvf-_MKDM%253A%253B38O8E4UbMSbW7M%253Bhttp%25253A%25252F%25252Fdepositphotos.com%25252F34338603%25252Fstock-illustration-flat-weather-icons.html&source=iu&pf=m&fir=60FQYEvf-_MKDM%253A%252C38O8E4UbMSbW7M%252C_&usg=__4gls9Amwo4U3fY9UwW7ylKKZcnU%3D&ved=0CDUQyjc&ei=hZ2TVYnqFMTnygPiyp84#newwindow=1&safe=off&tbm=isch&q=weather+icons+vector&imgrc=O1MWJ2di38KU1M%3A

**Comment by tagliala** [comment] 2015-07-01 10:17
I'm going to consider this as a duplicate of #1739 , please +1 that request

Closing here

**Closed by tagliala** 2015-07-01 10:17 UTC
