### ISSUE TITLE
Icon Request: fa-cc-visa-debit

### ISSUE THREAD

**Issue by sbekman** [FortAwesome/Font-Awesome#12670] opened 2018-03-22 05:40 UTC
Visa Debit has become a pretty popular payment method and an icon for this would be superb

![image](https://user-images.githubusercontent.com/4348138/37753174-f39bd698-2d71-11e8-8650-f7743dc645d2.png)
![image](https://user-images.githubusercontent.com/4348138/37753181-f76cfd42-2d71-11e8-8c25-5facec18eddd.png)

**Comment by tagliala** [comment] 2018-04-06 12:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11702, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 12:57 UTC
