### ISSUE TITLE
Icon request: VMware

### ISSUE THREAD

**Issue by CurtFarley** [FortAwesome/Font-Awesome#19115] opened 2022-06-09 20:08 UTC
A brand icon for VMware would be great. 

Thanks.
Curtis

**Comment by tagliala** [comment] 2022-06-09 20:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8137, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-06-09 20:11 UTC

**Comment by CurtFarley** [comment] 2022-06-09 22:09
Ok, thanks.  I did look for it, but I couldn't find it.  I also didn't see it in any of the existing, free libraries.
