### ISSUE TITLE
Icon Request: cPanel

### ISSUE THREAD

**Issue by OfficerZentro** [FortAwesome/Font-Awesome#9256] opened 2016-05-22 21:40 UTC
Please create a cPanel icon. Thank you.

**Comment by tagliala** [comment] 2016-05-23 07:46
Duplicate of #2846 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-23 07:46 UTC
