### ISSUE TITLE
Icon Request: icon-invoice

### ISSUE THREAD

**Issue by Treandlit** [FortAwesome/Font-Awesome#10981] opened 2017-04-24 03:20 UTC
Hi Good day, I would like to request if it's possible to create an invoice icon, which I could use for my sidebar menu and mini navbar. I would be very grateful.

![203819-200](https://cloud.githubusercontent.com/assets/27939452/25321306/0269cb4a-28e0-11e7-9c61-db692d1eed6a.png)

Thanks alot :)

**Comment by PeterShaggyNoble** [comment] 2017-04-24 08:47
This is a duplicate of #477, you should give that a 👍 instead.

**Closed** 2017-04-24 09:35 UTC
