### ISSUE TITLE
Icon request: LQ / HQ / FHD / 4K

### ISSUE THREAD

**Issue by TheGuy2003** [FortAwesome/Font-Awesome#19565] opened 2023-02-17 00:19 UTC
### Use case

With it being 2023 and this package being in version six i find it amazing that it was missing sd / hd icons untill recently and i find it even more amazing that FHD and 4K where not included as well.

being an application developer android / web it amazes me that in this day and age we do not cover all standard used quality options considering these quality options have now been the norm for a few years.

There for i would ask for the consideration to include the following icons

LQ - Low Quality Used For smaller devices
HQ -  High Quality used for low end Mobile Devices
FHD - Full High Definition common broadcast 1080 format
4K - Full 2160 resolution media

This would go along way to kitting out this package for use with most multi media projects considering we now have 8k tvs and devices on the market this package is rather behind the times

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment] 2024-07-11 14:36
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7660)

**Closed as completed by sensibleworld** 2024-07-11 14:36 UTC
Labels: new icon, Duplicate
