### ISSUE TITLE
Icon Request: icon-cv

### ISSUE THREAD

**Issue by mrafeeq** [FortAwesome/Font-Awesome#11332] opened 2017-07-27 16:28 UTC
Please create a icon to represent CV / resume / job application

**Comment by tagliala** [comment] 2017-07-27 18:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3533 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-27 18:55 UTC
