### ISSUE TITLE
Icon Request: icon-medicine

### ISSUE THREAD

**Issue by chandnan** [FortAwesome/Font-Awesome#10558] opened 2017-01-24 12:58 UTC
I am working on a healthcare project. It would be awesome if you can make an icon for medicine/ medication. 

 
![black-rx](https://cloud.githubusercontent.com/assets/25322193/22248060/e1c2de54-e262-11e6-9d1e-d7f2a4912ff5.jpg)

**Comment by tagliala** [comment] 2017-01-24 13:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #768 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-24 13:13 UTC
