### ISSUE TITLE
Icon request: icon-poker-chips

### ISSUE THREAD

**Issue by SkyBadPT** [FortAwesome/Font-Awesome#9088] opened 2016-04-30 13:15 UTC
Well this can be used for anything with casino relation, or anything because in my opinion can be used for many things.

![casino_chip svg](https://cloud.githubusercontent.com/assets/18751649/14935992/f5c74d44-0edd-11e6-9563-b34cedad9163.png)

**Comment by tagliala** [comment] 2016-04-30 16:25
Duplicate of #1004, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-30 16:25 UTC
