### ISSUE TITLE
Icon Request: fa-office365

### ISSUE THREAD

**Issue by aseelq** [FortAwesome/Font-Awesome#11798] opened 2017-11-24 16:28 UTC
Hi, 

Thanks for your effort and make fonts awesome like yours.

Please could you make a new icon for brand Microsoft Office 365, its icon will be same as link below:
https://news.microsoft.com/ofc365_msnews/

At our case, we'll add this icon through our website for any employee who has an email with our company and need him/her to open it in easy step.

Best Regards,

**Comment by tagliala** [comment] 2017-11-24 19:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1333 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-24 19:54 UTC
