### ISSUE TITLE
icon request: icon-quora

### ISSUE THREAD

**Issue by 4evermaat** [FortAwesome/Font-Awesome#8881] opened 2016-04-03 09:08 UTC
I am requesting an icon for the social interaction platform [Quora](http://www.Quora.com)

It would mainly be used to either link to Quora profile, or link to a question on Quora.

![quora_q](https://cloud.githubusercontent.com/assets/830306/14222866/82c5b478-f8a0-11e5-8f7e-d89a109f0cc3.png)

**Comment by tagliala** [comment] 2016-04-03 09:39
Duplicate of #510 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-03 09:39 UTC

**Comment by 4evermaat** [comment] 2016-04-04 11:47
I did do a search (where it says 'this repository' and I was surprised no one else made the request.  It is possible that I did the search incorrectly.  Github's search feature is certainly not as straightforward as google :(

**Comment by tagliala** [comment] 2016-04-04 12:12
@4evermaat no problem
