### ISSUE TITLE
Bug: animation-delay should have always the value in seconds units, no a simple 0

### ISSUE THREAD

**Issue by thepra** [FortAwesome/Font-Awesome#19074] opened 2022-05-26 14:55 UTC
### Bug description

Instead of `animation-delay:var(--fa-animation-delay,0)` it should be `animation-delay:var(--fa-animation-delay,0s)`

### Font Awesome version

v6.0.0

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

Firefox 101

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2022-05-26 16:04
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more details about this issue?

Is there a linter that reports an issue? Is this related to some calculations? Is this to adhere to the standard https://www.w3.org/TR/css-animations-1/#animation-duration initial value ?

**Comment by thepra** [comment] 2022-05-29 00:39
Yep, just to adhere and have linters not complain about it

**Comment by tagliala** [comment] 2022-06-02 10:37
> Yep, just to adhere and have linters not complain about it

Apologies for the late reply

Could you please provide a reproducible test case or the linters reporting this issue?

I'm not able to reproduce with stylelint. Also, stylelint has a rule to omit unit on length unit when the length is 0. It clearly states that `seconds` is a dimension unit, so `0s` will not be marked as an offence, but I would like to know which linter is causing this issue before escalating the bug

Ref: https://stylelint.io/user-guide/rules/list/length-zero-no-unit/

**Comment by tagliala** [comment] 2022-06-08 19:16
@thepra any update?

**Comment by thepra** [comment] 2022-07-13 17:55
Unfortunately other bundling tools see that as an error, making the bundling of the font-awesome.css impossible. Nothing to add here other than to replace that `0` with `0s`.

**Comment by tagliala** [comment] 2022-07-13 19:51
> Unfortunately other bundling tools see that as an error

Could you please clarify which bundling tool?

**Comment by thepra** [comment] 2022-07-14 09:50
https://github.com/failwyn/BundlerMinifier

**Comment by yaaax** [comment] 2022-08-25 14:21
Hi there,
The [W3C validator](thttps://validator.w3.org/) also complains :

> CSS: animation-delay: var(--fa-animation-delay, 0) is not a animation-delay value.

You should (I think) replace this code by `animation-delay: var(--fa-animation-delay, 0s)`

Initial value is actually 0s.
(see [The animation-delay property](https://drafts.csswg.org/css-animations-1/#animation-delay))

**Comment by tagliala** [comment] 2022-08-25 14:24
@yaaax thanks!

**Comment by tagliala** [comment] 2022-08-25 14:27
So I assume that there is some plugin making a CSS validation on the W3C service and that is triggering the issue.

It was not clear before, @robmadole I think this should be fixed

**Comment by robmadole** [comment] 2022-08-25 14:29
@tagliala agreed. We'll take a look!

**Comment by talbs** [comment] 2022-09-06 15:37
Thanks for the heads up on this issue, folks. We've added units to our `animation-delay` default values in v6.2.0.

**Closed as completed by talbs** 2022-09-06 15:37 UTC
Labels: bug, css
