### ISSUE TITLE
Icon request: icon-bootstrap

### ISSUE THREAD

**Issue by xxxdepy** [FortAwesome/Font-Awesome#5469] opened 2015-01-25 06:05 UTC
An icon of the Twitter Bootstrap. I am looking to use it a website-template site where I want to use it on a link that says "Bootstrap" along with other categories like "HTML5", "Wordpress" etc. 

It can be under the "Brand Icon" section :)
![bootstrap-logo-example](https://cloud.githubusercontent.com/assets/1390526/5890545/af4bbc78-a486-11e4-9940-b5667f67492b.jpg)

Thanks!

**Comment by tagliala** [comment] 2015-01-25 12:08
duplicate of #1828 , please +1 that request

closing here

**Closed by tagliala** 2015-01-25 12:08 UTC
