### ISSUE TITLE
Cannot be used with urxvt

### ISSUE THREAD

**Issue by Mikaela** [FortAwesome/Font-Awesome#3681] opened 2014-06-10 19:57 UTC
Related config:

```
URxvt*font: xft:DejaVu Sans Mono:pixelsize=11, xft:unifont:pixelsize=11, xft:Andale Mono:pixelsize=11, xft:Inconsolata:pixelsize=11, xft:FontAwesome:pixelsize=11
```

Error:

```
urxvt: unable to calculate font width for 'FontAwesome:slant=0:weight=100:pixels
ize=11:minspace=True', ignoring.
```

Version: 4.0.0~dfsg-1

**Comment by andornaut** [comment] 2015-01-08 16:00
I'm also hitting this issue. You might find it easier to reproduce by starting urxvt with:
```
urxvt -fn "xft:Font Awesome"
```

**Comment by rebasar** [comment] 2015-02-09 21:57
Can confirm. On Debian Wheezy with backports repo enabled. Relevant package versions:

```
fontconfig: 2.9.0-7.1
libxft2: 2.3.1-1
rxvt-unicode: 9.15-2+deb7u1
```

```
reb@terra:~% fc-list| grep Awesome
/home/reb/.fonts/fontawesome-regular.ttf: FontAwesome:style=Regular
reb@terra:~%
```

If you need any other information, I will be happy to provide.

**Comment by tagliala** [comment] 2015-02-10 00:30
check other icon fonts (like glyphicons) and let us know if you experience the same issue

**Comment by rebasar** [comment] 2015-02-10 22:28
Hi,

I don't have glyphicons installed (due to licensing issues) but I do have Pomodoro, Trellicons and Octicons installed and I get the same issue with those too.

**Comment by tagliala** [comment] 2015-02-10 23:33
@rebasar thanks for the feedback. Maybe there are issues with the PUA?

Since this is not related to fontawesome I need  to close this request but feel free to comment

**Closed by tagliala** 2015-02-10 23:33 UTC
Labels: waiting for feedback

**Comment by Anachron** [comment] 2016-01-06 09:15
@tagliala I also have this issue and would like it to be resolved. =)
What information do you need further to dig into it?

**Comment by tagliala** [comment] 2016-01-06 15:14
@Anachron sorry but I have no hint on how to solve this.

Please try the .otf version of fontawesome or other webfonts (glyphicons, material design icons, elusive icons, octicons, ionicons...).

If also other webfonts have the same issue so this is probably something that does not depend on fontawesome

**Comment by Anachron** [comment] 2016-01-06 16:25
It works with powerline symbols for example. :+1:

**Comment by binaryplease** [comment] 2016-02-15 17:03
I'm still having this exact issue. Has there been found a solution somewhere?
Using the rxvt-unicode-patched version from the AUR (Arch linux)

**Comment by shellkr** [comment] 2016-04-30 21:42
I have it working when using `xft:SauceCodePro NF:pixelsize=9` as a fallback in ~/.Xresources. The font can be found at https://github.com/ryanoasis/nerd-fonts.

![FontAwesome working](https://ptpb.pw/E3Vl.png)

    rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
    options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr
    +zh+zh- ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,
    pointerBlank,scrollbars=plain+rxvt+NeXT+xterm

**Comment by blueyed** [comment] 2016-10-20 15:50
This is a bug in rxvt-unicode, which only looks at chars that are not included in the font when determining its width.  The fix is to also consider spaces in this process: http://lists.schmorp.de/pipermail/rxvt-unicode/2016q4/002308.html.

**Comment by blueyed** [comment] 2016-10-20 15:52
But rxvt-unicode will still have problems with wide glyphs, with a width of 1 cell according to `wcwidth`.
Check out https://github.com/ryanoasis/nerd-fonts/issues/92#issuecomment-255049262 and the comments around it.

**Comment by blueyed** [comment] 2016-10-20 15:54
This issue will show itself when starting rxvt-unicode from another terminal, where you should then see a message like the following when a glyph from the font is attempted to be used:

> urxvt: unable to calculate font width for 'FontAwesome-4:slant=0:weight=200:minspace=True', ignoring.

**Comment by poisonby** [comment] 2017-02-07 19:10
@blueyed What is that patch supposed to fix? I have FontAwesome as a fallback font in urxvt and I applied that patch (successfully) to `rxvtfont.C`, but I still can't get it to work.

**Comment by blueyed** [comment] 2017-02-07 19:16
@poisonby 
There are other issues you might run into now, e.g. that urxvt considers the glyphs to be too wide.
Try some glyphs that are narrow, and more likely to fit into a cell.

**Comment by poisonby** [comment] 2017-02-08 00:30
@blueyed 

You're right, some characters seem to work (like `\uf07d`), though most doesn't work. Is there no way to get all characters to work, or is the only option to switch to another terminal emulator?

Thanks.

**Comment by blueyed** [comment] 2017-02-08 00:36
I have two hacks in this regard (see my fork). Not much love for this by default.. ;)

**Comment by poisonby** [comment] 2017-02-08 01:22
@blueyed 

I built your fork and installed it, but now no characters from FontAwesome seems to work. Maybe I did something wrong?

**Comment by poisonby** [comment] 2017-02-08 01:24
@blueyed 

I actually compiled and installed it by messing with ABS, didn't see that you had a README there so it appears I missed a few build options. I'm running Arch though so I'll try your PKGBUILD. =) I'll update if it works.

**Comment by poisonby** [comment] 2017-02-08 01:32
@blueyed 

It worked! Thanks for the help. An effect from this though is that I had to switch `URxvt.letterSpace` from -1 to -2 to set the correct spacing. The characters seem to show up regardless though. =)

**Comment by guest73** [comment] 2017-06-22 16:35
Hi @blueyed, I tried your hack and it kind of worked for me. The only problem is, I am used to rxvt-unicode-256color. With your patched version I cannot make it to use 256 colors. Can we have the patch for 256color version?

**Comment by blueyed** [comment] 2017-06-22 17:29
@guest73 
Which one have you tried?
I recommend my first approach: https://github.com/blueyed/PKGBUILD-rxvt-unicode-wide.
It is available in AUR: https://aur.archlinux.org/packages/rxvt-unicode-cvs-patched-wideglyphs/

**Comment by guest73** [comment] 2017-06-22 20:54
@blueyed 
Thanks for responding. I used the one from here https://github.com/blueyed/rxvt-unicode/blob/wcwidth-hack/README.md. But the problem is I am on Debian and I am not so skilled in all this mumbo-jumbo. Debian has 2 packages rxvt-unicode and rxvt-unicode-256color. I think your patch was for the first one. I think the first one has something like max_colors#88, max_pairs#7744 and the second one max_colors#256, max_pairs#32767 according to terminfo but I am really not sure what it is all about.

**Comment by blueyed** [comment] 2017-06-22 22:04
So you are building your own .deb then?
You should use the patch(es) from https://github.com/blueyed/PKGBUILD-rxvt-unicode-wide then.
When building from source (or in general), the PKGBUILD might come in handy for guidance: https://github.com/blueyed/PKGBUILD-rxvt-unicode-wide/blob/master/PKGBUILD

**Comment by dhruvinsh** [comment] 2019-03-30 18:57
well if anyone still looking for solution, Nerd patched font did work for me without any issue.
![20190330_145338](https://user-images.githubusercontent.com/33428164/55280411-ae891880-52fb-11e9-84b7-a35ae87b546a.png)

my .Xresources file has this config:
```
URxvt.font: xft:SF Mono:size=12,xft:Inconsolata Nerd Font Mono:size=11 
URxvt.letterSpace: -1 
```
main font is SF Mono and fallbacks to Nerd patched font.


*System*
Ubuntu 18.04
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
