### ISSUE TITLE
Icon request: fa-python

### ISSUE THREAD

**Issue by coler706** [FortAwesome/Font-Awesome#6050] opened 2015-03-24 10:39 UTC
![image](https://cloud.githubusercontent.com/assets/9607290/6799945/52f760ca-d1d7-11e4-8536-7cb5c70df9ce.png)
ADD it please

**Comment by tagliala** [comment] 2015-03-24 10:54
duplicate of #1391 , please +1 that request

take also a look here: http://fizzed.com/oss/font-mfizz

closing here

**Closed by tagliala** 2015-03-24 10:54 UTC
