### ISSUE TITLE
Icon request: icon-co-working space

### ISSUE THREAD

**Issue by kristabelq** [FortAwesome/Font-Awesome#12078] opened 2018-01-11 14:40 UTC
Hi, I am wondering do you have icons for the following?

- icon-co-working space
- icon-co-working space
- icon-co-working space
- icon-co-working space

**Comment by kristabelq** [comment] 2018-01-11 14:45
Sorry had some error earlier - here's the list of icons i need:
- co-working space
- accelerator
- incubator
- investor
- startup 
- online course
- tool

Thanks!

**Comment by tagliala** [comment] 2018-01-11 17:16
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

This request does not meet:

> * Please do not request comprehensive sets of icons related to a very specific field.
> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

1 icon per request, unless they are strictly related

> * Please search to see if your icon request already exists. If a request is found, please add a 👍 reaction to that one.

Tool should be already [here](https://fontawesome.com/icons/wrench?style=solid), or it is a duplicate of #736 

> * Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
> * Attach a single color image or two that represent the idea you're going for.
> * Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Closed by tagliala** 2018-01-11 17:16 UTC
