### ISSUE TITLE
Icon Request: Kubernetes

### ISSUE THREAD

**Issue by Majoros** [FortAwesome/Font-Awesome#14567] opened 2019-01-29 16:16 UTC
### What can it be used for?

Brand Icon for [Kubernetes](https://kubernetes.io/)

### Example image (optional)

![Image of kubernetes](https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png?raw=true)

SVG: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.svg

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's ea

**Comment by tagliala** [comment] 2019-01-29 19:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13331, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-01-29 19:19 UTC
