### ISSUE TITLE
Icon request: Tableau 

### ISSUE THREAD

**Issue by yidaw123** [FortAwesome/Font-Awesome#17962] opened 2021-06-01 05:10 UTC
**What can it be used for?**
Used for the popular data visualization software Tableau. Can be used to represent Tableau, Tableau Prep, Tableau Public, and all related content.

**Example image (optional)**
![tableau](https://user-images.githubusercontent.com/57473810/120269504-f312f480-c275-11eb-9c0a-46255b2dc752.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-06-01 07:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8942, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-06-01 07:38 UTC
