### ISSUE TITLE
Icon request:Pipe_Line

### ISSUE THREAD

**Issue by jorgechoypernia** [FortAwesome/Font-Awesome#13849] opened 2018-08-30 17:52 UTC
Useful for Engineering web sites. Others could be instruments, valve, pump, etc

![exmple](https://user-images.githubusercontent.com/8151529/44869556-cd4fff80-ac85-11e8-963c-43b7fa508f6b.PNG)

Note this image is copied from a different site so i believe cannot be the same. It is just an example.

Thanks.

**Comment by tagliala** [comment] 2018-08-30 18:15
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #7837?

**Comment by aethior** [comment] 2022-04-15 03:58
@tagliala I think you can close here. :)

**Closed** 2022-04-15 07:27 UTC
