### ISSUE TITLE
Icon Request: fa-xero

### ISSUE THREAD

**Issue by viewpoint** [FortAwesome/Font-Awesome#5490] opened 2015-01-27 09:25 UTC
Hi,
First, thank you for your fonts. They really are awesome.

Further to my previous icon request.
I am programming the FAB crm platform and Font-Awesome is being used 
in their new release. FAB is a Xero partner and is exhibiting at Xerocon in Feb 2015.
In addition to the FAB icon request, a Xero font awesome icon would also be really useful.
I am not sure how their logo is constructed.
Here is a link to their media page:
https://www.xero.com/uk/about/media/
![image](https://cloud.githubusercontent.com/assets/5955353/5916174/28e3d0d6-a606-11e4-94a7-67dcfb638d2a.png)

**Comment by tagliala** [comment] 2015-01-27 19:12
duplicate of #4574, please +1 that request

since February is just round the corner, please give a look at this wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#new-icons

closing here

**Closed by tagliala** 2015-01-27 19:12 UTC
