### ISSUE TITLE
icon-request: speakerdeck

### ISSUE THREAD

**Issue by tugberkugurlu** [FortAwesome/Font-Awesome#6568] opened 2015-05-27 09:37 UTC
https://speakerdeck.com/

**Comment by quarterback** [comment] 2015-06-17 18:36
+1

**Comment by FerPerales** [comment] 2015-10-22 17:23
:+1:

**Comment by gatespace** [comment] 2016-05-13 01:57
+1

**Comment by vg** [comment] 2016-05-31 18:09
+1

**Comment by stkent** [comment] 2016-11-04 23:18
Dupe of https://github.com/FortAwesome/Font-Awesome/issues/1688?

**Comment by nmicht** [comment] 2018-04-08 08:07
There is already an issue opened for this since 2013
https://github.com/FortAwesome/Font-Awesome/issues/1688

**Comment by tagliala** [comment] 2018-04-08 08:38
@nmicht thanks

Let's use #1688

**Closed by tagliala** 2018-04-08 08:38 UTC
