### ISSUE TITLE
Icon request: aparat website logo

### ISSUE THREAD

**Issue by Pamirsalar** [FortAwesome/Font-Awesome#12580] opened 2018-03-12 13:43 UTC
"www.aparat.com" is a video sharing website, just like Youtube, which is very popular in the middle east region.

![aparat_icon_color_black_1024_mono_color](https://user-images.githubusercontent.com/37299075/37286923-a77f5448-2618-11e8-9282-50a85a53c935.png)

I kindly request adding this logo to your awesome website.

**Comment by tagliala** [comment] 2019-09-03 14:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5204, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-03 14:36 UTC
