### ISSUE TITLE
Free version "far fa-eye" doesnt render, only "fas fa-eye"

### ISSUE THREAD

**Issue by in-session** [FortAwesome/Font-Awesome#17883] opened 2021-05-08 08:10 UTC
far fa-eye icon is not rendered with the current version 5.15.3 via javascript

```
<i class="far fa-eye"></i>

<svg class="svg-inline--fa fa-eye fa-w-18" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="eye" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M572.52 241.4C518.29 135.59 410.93 64 288 64S57.68 135.64 3.48 241.41a32.35 32.35 0 0 0 0 29.19C57.71 376.41 165.07 448 288 448s230.32-71.64 284.52-177.41a32.35 32.35 0 0 0 0-29.19zM288 400a144 144 0 1 1 144-144 143.93 143.93 0 0 1-144 144zm0-240a95.31 95.31 0 0 0-25.31 3.79 47.85 47.85 0 0 1-66.9 66.9A95.78 95.78 0 1 0 288 160z"></path></svg><!-- <i class="fas fa-eye"></i> Font Awesome fontawesome.com -->

```

**Comment by tagliala** [comment] 2021-05-08 09:58
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

Sorry, can't reproduce.

Demo: https://jsfiddle.net/tagliala/cf4mL7n5/19/

If you are still experiencing this issue, please open a new request, fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md), and provide a reproducible test case

Hope it helps

Closing here

Ref: 
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Closed by tagliala** 2021-05-08 09:58 UTC

**Comment by in-session** [comment] 2021-05-08 10:19
@tagliala 

Thanks I just did a test and found the error in the documentation, Regular I think is not pro?
https://fontawesome.com/how-to-use/on-the-web/using-with/requirejs (Section: Adding More Styles (For Miles) 

```
require.config({
  paths: {
    'fontawesome': 'vendor/fontawesome/fontawesome.min',
    'fontawesome/solid': 'vendor/fontawesome/solid.min',
    'fontawesome/brands': 'vendor/fontawesome/brands.min'
    // Pro files can be added like this:
    // 'fontawesome/regular': 'vendor/fontawesome/regular.min',
    // 'fontawesome/light': 'vendor/fontawesome/light.min',
    // 'fontawesome/duotone': 'vendor/fontawesome/duotone.min'
  },
  shim: {
    'fontawesome': {
      deps: ['fontawesome/solid', 'fontawesome/brands']
    }
  }
})

require(['fontawesome'], function (fontawesome) {
  console.log('Congrats, Font Awesome is installed using Require.js')
})
```

Should be

```
require.config({
  paths: {
    'fontawesome': 'vendor/fontawesome/fontawesome.min',
    'fontawesome/solid': 'vendor/fontawesome/solid.min',
    'fontawesome/regular': 'vendor/fontawesome/regular.min',
    'fontawesome/brands': 'vendor/fontawesome/brands.min'
    // Pro files can be added like this:
    // 'fontawesome/light': 'vendor/fontawesome/light.min',
    // 'fontawesome/duotone': 'vendor/fontawesome/duotone.min'
  },
  shim: {
    'fontawesome': {
      deps: ['fontawesome/solid', 'fontawesome/regular', 'fontawesome/brands']
    }
  }
})

require(['fontawesome'], function (fontawesome) {
  console.log('Congrats, Font Awesome is installed using Require.js')
})
```

test on: https://jsfiddle.net/ae4otsrm/

**Comment by tagliala** [comment] 2021-05-08 10:39
> Regular I think is not only pro?

Some regular icons are also part of the free set, they are the old outlined icons in FA4 plus more

I can see `far fa-eye` on your fiddle, did you solve the issue?

**Comment by in-session** [comment] 2021-05-08 10:42
Yes is solved because regular should always be inserted so that it runs correctly.
