### ISSUE TITLE
Icon request: icon-brand-flutter

### ISSUE THREAD

**Issue by uc-noack** [FortAwesome/Font-Awesome#19610] opened 2023-03-14 13:12 UTC
Flutter is an open-source UI software development kit created by Google. It is used to develop cross-platform applications for Android, iOS, Linux, macOS, Windows, Google Fuchsia, and the web from a single codebase. First described in 2015, Flutter was released in May 2017.

**Comment by tagliala** [comment] 2023-03-14 13:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14878, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-03-14 13:54 UTC
