### ISSUE TITLE
Icon request: kubernetes

### ISSUE THREAD

**Issue by 0x2b3bfa0** [FortAwesome/Font-Awesome#17867] opened 2021-05-01 19:20 UTC
**What can it be used for?**
[Kubernetes](kubernetes.io) is a widely adopted container orchestrator with an overwhelming popularity. Font Awesome already has the [`docker`](https://fontawesome.com/icons/docker) icon, so adding this one could be a good move.

**Example image**
<br><img width="64px" src="https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg">

**Comment by aethior** [comment] 2022-03-07 02:17
Hi @0x2b3bfa0,

Duplicate of #13331.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed** 2022-03-07 08:55 UTC
