### ISSUE TITLE
Icon Request: fa-store

### ISSUE THREAD

**Issue by MaheshTavethiya** [FortAwesome/Font-Awesome#12563] opened 2018-03-10 12:54 UTC

**Comment by tagliala** [comment] 2018-03-10 13:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1958, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-10 13:37 UTC
