### ISSUE TITLE
Request: MySQL and IntelliJ Icons

### ISSUE THREAD

**Issue by kjanjuha** [FortAwesome/Font-Awesome#12243] opened 2018-02-04 12:08 UTC
Icons for MySQL and IntelliJ

**Comment by tagliala** [comment] 2018-02-04 13:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6052 and #3284, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-04 13:02 UTC
