### ISSUE TITLE
Icon request: Icon Clean

### ISSUE THREAD

**Issue by Jarvanux** [FortAwesome/Font-Awesome#7535] opened 2015-09-24 17:24 UTC
I'd love to have a icon for 
actions and / or systems cleaning.

Beforehand thank you very much.

some examples:

![clean_brush-512](https://cloud.githubusercontent.com/assets/8753665/10080580/022b224c-62b6-11e5-8306-d3a70f2645f2.png)

![sweep](https://cloud.githubusercontent.com/assets/8753665/10080582/077fb622-62b6-11e5-9048-eb83279e192d.png)

**Comment by tagliala** [comment] 2015-09-24 19:54
duplicate of #239, please +1 that request

closing here

**Closed by tagliala** 2015-09-24 19:54 UTC
