### ISSUE TITLE
Icon Request: fa-atomic

### ISSUE THREAD

**Issue by stdunbar** [FortAwesome/Font-Awesome#11224] opened 2017-06-25 02:29 UTC
Would like to request an "atom" symbol.  Just do a GIS for "atomic symbol" and you'll get an idea of what I'm looking for.  Thanks!

**Comment by tagliala** [comment] 2017-06-25 14:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #664 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-25 14:20 UTC
