### ISSUE TITLE
Icon request: fa-kik

### ISSUE THREAD

**Issue by austinhuang0131** [FortAwesome/Font-Awesome#10231] opened 2016-11-16 01:47 UTC
A free-use icon for reference: http://www.fancyicons.com/free-icon/222/simple-icon-set/free-kik-icon-png/

**Case:** I am using Kik icon for a bot that I made. Also since there is Telegram icon, why not kik?

**Comment by tagliala** [comment] 2016-11-16 10:22
Duplicate of #3526, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-16 10:22 UTC
