### ISSUE TITLE
Icon request: purse or handbag

### ISSUE THREAD

**Issue by Chikeno01** [FortAwesome/Font-Awesome#16037] opened 2020-01-08 15:21 UTC
**What can it be used for?**
This icon can be used for designer who create a interface pour travel company (step where you choose your cabin luggage option)
Opt 1 -  purse
Opt 2 - purse and cabin luggage
Etc...  

**Example image (optional)**
-** is in French**-
![cabin luggage option](https://user-images.githubusercontent.com/59655670/71989420-ebdae900-3231-11ea-904d-d4fd2c1aad95.jpg)

**Icon request checklist**
- [ok] This is a single icon 
- [ok] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ok] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ok] I have included at least one example image if it could be helpful (optional)
- [ok] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-01-08 16:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14446, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-08 16:51 UTC
