### ISSUE TITLE
Icon request: icon-craftsy

### ISSUE THREAD

**Issue by gracye216** [FortAwesome/Font-Awesome#13119] opened 2018-05-11 16:27 UTC
To show your profile on craftsy.com 

### Example image (optional)

![craftsy](https://user-images.githubusercontent.com/39197439/39935312-76e893da-54fd-11e8-9114-f77c66c1db0e.png)

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-05-21 01:46
>Craftsy, previously named Bluprint, is an American subscription video on demand service owned by TN Marketing. The service features online courses and other forms of video content surrounding crafts, hobbies, and lifestyle topics, as well as an online store that sells craft supplies and project kits that tie into the service's video content. ([more info](https://en.wikipedia.org/wiki/Craftsy))
https://www.craftsy.com/

@tagliala `brand (category)` label for this request?

**Comment by tagliala** [comment] 2022-05-21 07:41
This request is a duplicate of #10685, please add a 👍 reaction to that request.

**Closed by tagliala** 2022-05-21 07:41 UTC
