### ISSUE TITLE
Icon Request: fa-reverbnation

### ISSUE THREAD

**Issue by gioslv** [FortAwesome/Font-Awesome#5740] opened 2015-02-21 17:59 UTC
Hi guys, 

for first congratulations for the site and its features.
By this I'm asking you to create an icon that represents the star of the site reverbernation.
Use case: site for musicians who want a link to their profile in reverbernation.

Example image:
![star_example](https://cloud.githubusercontent.com/assets/11137390/6315228/84f29b74-b9fb-11e4-9f3a-22e4578215c9.png)

Thanks in advance.

Giovanni

**Comment by dineshraj** [comment] 2015-12-26 19:21
+1

**Comment by tagliala** [comment] 2015-12-26 19:55
duplicate of #2632 , please +1 that request

closing here

**Closed by tagliala** 2015-12-26 19:55 UTC
