### ISSUE TITLE
fa-caret-right and fa-caret-down button are not of same width or what??

### ISSUE THREAD

**Issue by chitru** [FortAwesome/Font-Awesome#9169] opened 2016-05-11 07:16 UTC
I wanted to have bootstrap's navbar anchor items fa-caret-right at its end. so i added them and after that i wanted to have the fa-caret-right to change to fa-caret-down on hover. It was usual to see links were moving to left on hover(like padding was applied on hover). First i thought it was bootstrap overriding of something. I did trial and error and finally then i replaced font-awesome fa-caret-right with glyphicon-chevron-right. Guess what, it worked. there was no issue with bootstrap's glyphicon. 

Is there any issue with width of fa-caret-right and fa-caret-down? Cause it seemed to me.

**Comment by My1** [comment] 2016-05-11 08:04
use fa-fw  as extra class.

**Comment by tagliala** [comment] 2016-05-11 08:26
Hi,

Font Awesome icons have not the same width by design choice

Use `fa-fw` ad @My1  pointed out or css transforms for your use case

Hope it helps, closing here

**Closed by tagliala** 2016-05-11 08:26 UTC
