### ISSUE TITLE
fa-*-chart without axes

### ISSUE THREAD

**Issue by grssnbchr** [FortAwesome/Font-Awesome#7140] opened 2015-08-05 08:29 UTC
I really like the chart icons, e.g. http://fortawesome.github.io/Font-Awesome/icon/bar-chart/

But I think they should also be available without axes as they add (imho) unnecessary visual clutter.

**Comment by tagliala** [comment] 2015-08-05 08:48
This should be a duplicate of #2794, please +1 that request

closing here

**Closed by tagliala** 2015-08-05 08:48 UTC

**Comment by grssnbchr** [comment] 2015-08-06 11:42
You think so? Well ok. Thanks!
