### ISSUE TITLE
Icon request: Netflix

### ISSUE THREAD

**Issue by msabrishami** [FortAwesome/Font-Awesome#15983] opened 2019-12-23 02:45 UTC
**What can it be used for?**
The logo of many other companies are available but not Netflix. For example, people can use the logo when they want to list the name of their preferred shows.  

**Example image (optional)**
![Netflix_Logo_RGB](https://user-images.githubusercontent.com/14100652/71332484-34cd3680-24eb-11ea-91de-fa7001a08ef8.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-12-23 07:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1395, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-12-23 07:44 UTC
