### ISSUE TITLE
Icon Request: driver

### ISSUE THREAD

**Issue by el-duderino5** [FortAwesome/Font-Awesome#13959] opened 2018-09-17 22:38 UTC
Would love to have an icon that represents a driver. Maybe something like this? 
![image](https://user-images.githubusercontent.com/6808300/45654249-e55ab800-baa8-11e8-8f0f-6b6078b8735a.png)

**Comment by tagliala** [comment] 2018-09-18 08:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7743, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-18 08:45 UTC
