### ISSUE TITLE
Icon Request: fa-beme

### ISSUE THREAD

**Issue by Donzella** [FortAwesome/Font-Awesome#9238] opened 2016-05-18 20:56 UTC
just hoping to see the social app Beme added.

**Comment by tagliala** [comment] 2016-05-18 21:15
Duplicate of #7268 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-18 21:15 UTC
