### ISSUE TITLE
Icon request: Disqus

### ISSUE THREAD

**Issue by zehrer00** [FortAwesome/Font-Awesome#13626] opened 2018-07-25 18:33 UTC
Disqus Brand Logo would be „nice“

**Comment by tagliala** [comment] 2018-07-25 20:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2690, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-25 20:22 UTC
