### ISSUE TITLE
Icon request: plus(minus)-circle-o

### ISSUE THREAD

**Issue by lifecom** [FortAwesome/Font-Awesome#8316] opened 2016-01-12 18:23 UTC
fa-plus

fa-plus-square
fa-plus-square-o

fa-plus-circle
fa-plus-circe-o ???

**Comment by smajl** [comment] 2016-01-28 16:15
http://fortawesome.github.io/Font-Awesome/examples/#stacked ???

**Comment by djibarian** [comment] 2016-07-28 09:22
Looking at the `-circle-o` group of symbols I also think `fa-plus-circle-o` and `fa-minus-circle-o` would be a consistent and welcome addition.

**Comment by tagliala** [comment] 2017-07-01 09:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2417, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-01 09:26 UTC
