### ISSUE TITLE
Icon request: Signal (messaging app)

### ISSUE THREAD

**Issue by Jack-Toulouse** [FortAwesome/Font-Awesome#19689] opened 2023-04-24 07:59 UTC
### Use case

Enable people to look at your Signal contact in a web page

### Example image

![logo-signal](https://user-images.githubusercontent.com/88853903/233934649-023cf651-ddbf-4284-9449-46ed85aebf9a.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by Jack-Toulouse** [comment] 2023-04-24 08:01
I checked "This icon does not represent a brand", not sure of that... but there are others which are brand... (FB, Whats'app etc...)

**Comment by tagliala** [comment] 2023-04-24 09:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7434, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

> I checked "This icon does not represent a brand"

Signal is considered a brand

Closing here

**Closed as completed by tagliala** 2023-04-24 09:12 UTC
Labels: new icon
