### ISSUE TITLE
Icon Request: Kaggle 

### ISSUE THREAD

**Issue by devanshdalal** [FortAwesome/Font-Awesome#11010] opened 2017-04-30 11:32 UTC
`Icon request: icon-kaggle`

It can be used on the top of the page where user shows linkedin, github icons in contacts section etc.

It can be similar to

![kaggle-log_black_and_white](https://cloud.githubusercontent.com/assets/5080310/25563998/a4958158-2dc6-11e7-8388-2cfc33b9c41f.png)

**Comment by tagliala** [comment] 2017-04-30 12:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4363, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-30 12:09 UTC

**Comment by devanshdalal** [comment] 2017-05-01 09:39
ohh , apology for the garbage here. @tagliala . Thanks for the feedback.
