### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by dominik-wbz** [FortAwesome/Font-Awesome#12968] opened 2018-04-28 18:42 UTC
### What can it be used for?

Many uses for palm/ holiday

### Example image (optional)

![108-512](https://user-images.githubusercontent.com/8103258/39399785-944e9bfa-4b24-11e8-9397-c96b91716a19.png)

**Comment by tagliala** [comment] 2018-04-28 19:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7640, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-28 19:56 UTC
