### ISSUE TITLE
Icon request: filter-slash

### ISSUE THREAD

**Issue by dsmmcken** [FortAwesome/Font-Awesome#16694] opened 2020-05-21 15:29 UTC
**What can it be used for?**
To clear or cancel a filter. Follow same styling as other -slash variants.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-21 17:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5309, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Please also keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/415/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Closed by tagliala** 2020-05-21 17:51 UTC

**Comment by dsmmcken** [comment] 2020-05-21 18:04
Sorry that was silly of me, I searched "cancel filter" instead of the more obvious "filter slash", that I even used in my own ticket name. Doh.

That use of layering+masking+transform to get the slash knockout is really cool thanks.

**Comment by tagliala** [comment] 2020-05-21 18:58
Welcome, don't worry about the search 👍
