### ISSUE TITLE
Icon Request: fa-home-o

### ISSUE THREAD

**Issue by ChiTownDev** [FortAwesome/Font-Awesome#2449] opened 2013-11-20 17:58 UTC
Please add Outlined version of Home icon.

Thank you for your outstanding work!

Cheers

**Comment by ShaunR** [comment] 2015-11-03 21:11
+1

**Comment by tagliala** [comment] 2015-11-03 23:21
Closing here as a duplicate of #2210

**Closed by tagliala** 2015-11-03 23:21 UTC
