### ISSUE TITLE
Icon request: fa-formula-1

### ISSUE THREAD

**Issue by delijah** [FortAwesome/Font-Awesome#19645] opened 2023-04-03 14:41 UTC
### Use case

An icon that describes the sport "formula 1".

### Example image

<img width="62" alt="Screenshot 2023-04-03 at 16 40 55" src="https://user-images.githubusercontent.com/237739/229543667-23dbced7-d36f-495a-b9b7-f2cda3324c5c.png">

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2023-04-03 19:55
Hi!

Thanks for being part of the Font Awesome Community.

I understand that there are several kind of race cars, but for the moment I will consider this request is a duplicate of #12846, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-04-03 19:55 UTC
Labels: new icon
