### ISSUE TITLE
Icon Request: fa-gantt-chart

### ISSUE THREAD

**Issue by fjanon** [FortAwesome/Font-Awesome#6871] opened 2015-07-03 22:27 UTC
I am looking for a Gantt chart icon like the one attached.

![gantt-chart](https://cloud.githubusercontent.com/assets/43575/8505334/458781a2-21e3-11e5-8bf1-7137928e714f.png)

Thanks

**Comment by tagliala** [comment] 2015-07-04 10:20
duplicate of #3915, please +1 that request

closing here

**Closed by tagliala** 2015-07-04 10:20 UTC
