### ISSUE TITLE
Request for Follower and following icon

### ISSUE THREAD

**Issue by abhinavpathak14** [FortAwesome/Font-Awesome#13129] opened 2018-05-13 23:49 UTC
Hi there,

One of my project, I need to show an icon for both follower and following. Can you please add it in font-awesome or suggest me name of icon if it is already their.

**Comment by tagliala** [comment] 2018-05-14 09:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11571, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-14 09:06 UTC
