### ISSUE TITLE
Icon Request: fa-certificate-alt

### ISSUE THREAD

**Issue by wesleycho** [FortAwesome/Font-Awesome#9737] opened 2016-08-11 12:14 UTC
The current fa-certificate icon is confusing for the purposes of certificates we find at my company (our product is an LMS, so we issue certificates). We would ideally like an icon that is essentially a genericized version of something like

<img src="https://www.edrawsoft.com/templates/images/student-certificate.png">

**Comment by tagliala** [comment] 2016-08-11 12:31
Duplicate of #4420, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-11 12:31 UTC
