### ISSUE TITLE
Icon Request: fa-music-queue

### ISSUE THREAD

**Issue by liuk997** [FortAwesome/Font-Awesome#13334] opened 2018-06-16 18:38 UTC
It would be great if you could insert music queue for a web player. I mean something like this:

![](https://cdn4.iconfinder.com/data/icons/music-is-my-city-glyph/100/music_glyph-07-512.png)

Thanks for all!

**Comment by tagliala** [comment] 2018-06-16 18:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #639 or #7740, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-16 18:53 UTC
