### ISSUE TITLE
Icon request: icon-submit

### ISSUE THREAD

**Issue by Lioness612** [FortAwesome/Font-Awesome#9619] opened 2016-07-22 05:45 UTC
Hi

I am looking for an icon that we can have on our "Submit" button... In our case, it is to do with submitting your application when you have finished it But you could use it on the submit button on the bottom of this screen right here! :)

There are so many choices already - I can't believe I can't find something. Maybe it is just a lack of imagination on my part.

Maybe something like a document going into a box?? It would also be useful for a vote icon I am thinking...

Thanks! 

![submiticon](https://cloud.githubusercontent.com/assets/20591400/17047605/21567382-5023-11e6-9a11-0f1009ce6e33.PNG)

**Comment by aethior** [comment] 2016-07-22 06:24
#7839 Duplicate? Related?

**Comment by Lioness612** [comment] 2016-07-22 06:29
UNOFFICIAL
Ahh yes! I missed this one when I was looking...

Leonie Casey
Business Analyst
Client Digital Systems Section
Visa, Citizenship and Digital Systems Branch|ICT Division
Intelligence and Capability Group
Department of Immigration and Border Protection
P: (02) 6196 0842|M: 0413 314 227
Email: leonie.casey@border.gov.au<mailto:leonie.casey@border.gov.au>

**Comment by Roumed** [comment] 2016-07-22 07:31
+1

**Comment by tagliala** [comment] 2016-07-22 09:29
Duplicate of #7839, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-22 09:29 UTC
