### ISSUE TITLE
Icon request: google-my-business

### ISSUE THREAD

**Issue by saskiabp** [FortAwesome/Font-Awesome#15352] opened 2019-08-07 14:18 UTC
**What can it be used for?**
This  can be use to add a link to a Google My Business page like we do for other social medias. Google My Business page getting more and more popular.

**Example image (optional)**
<img width="299" alt="icon" src="https://user-images.githubusercontent.com/22058835/62630087-4dea9780-b8fc-11e9-90ac-bb081c0bcb55.png">

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-08-07 16:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2412, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-08-07 16:23 UTC
