### ISSUE TITLE
Icon Request: icon-researchgate

### ISSUE THREAD

**Issue by mscipio** [FortAwesome/Font-Awesome#9018] opened 2016-04-19 13:32 UTC
Please add an icon for the reasearchgate website!!

https://www.researchgate.net/

**Comment by tagliala** [comment] 2016-04-19 13:44
Duplicate of #3634, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-19 13:44 UTC
