### ISSUE TITLE
Icon Request: fa-customs/police/lawenforcement

### ISSUE THREAD

**Issue by GerritP** [FortAwesome/Font-Awesome#11467] opened 2017-08-31 00:04 UTC
Hi there,

an icon for some kind of law enforcement, for example customs or police, would be very useful.

![image](https://user-images.githubusercontent.com/31493266/29900209-e298a102-8db5-11e7-95c1-0cfcb7869ade.png)
![image](https://user-images.githubusercontent.com/31493266/29900232-137a9e4c-8db6-11e7-8471-a6bea64077ad.png)

Greetings

**Comment by tagliala** [comment] 2017-08-31 09:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4056 or #3372, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-31 09:25 UTC
