### ISSUE TITLE
Icon request: fa-ram-o

### ISSUE THREAD

**Issue by JacobRocks12** [FortAwesome/Font-Awesome#8568] opened 2016-02-14 16:51 UTC
For fa-ram, make it look like this: http://a4.mzstatic.com/us/r30/Purple69/v4/8c/ee/30/8cee3070-9e88-004c-eea2-080286e37396/icon128-2x.png with it just being black.

For fa-ram-o, make it look like the one above but everything is clear except the border.

**Comment by tagliala** [comment] 2016-02-14 19:49
why having both version is important?

ram is a duplicate of #3239

**Comment by 1DC** [comment] 2017-03-03 10:53
I would like an outline one since it can fit some designs better than a filled one.

**Comment by tagliala** [comment] 2018-02-20 12:41
Hi,

I'm going to close this request.

Since Font Awesome is now supporting multiple styles for each icon, this is going to be implemented via #3239.

Of course, the outlined version of the ram icon could be part of the Pro icons and I undestand that the solid version does not fit your design.

But in that case, we will open again this request, because at the moment it doesn't have upvotes

Closing here

**Closed by tagliala** 2018-02-20 12:41 UTC
Labels: new icon, web application icons
