### ISSUE TITLE
Icon Request: fa-php

### ISSUE THREAD

**Issue by KillerSquid** [FortAwesome/Font-Awesome#8615] opened 2016-02-19 22:10 UTC
The PHP 'logo' as seen in the upper left corner on the home page:   http://php.net/
And/or maybe the old oval logo: http://vigesimalsoft.com/wp-content/uploads/2012/12/PHP_Logo_Oval.png

On my developer site I have a listing of all the various libraries and languages I use and all my accounts (like visit me on github, jsfiddle, etc).

**Comment by tagliala** [comment] 2016-02-19 22:57
duplicate of #1420 , please +1 that request

closing here

**Closed by tagliala** 2016-02-19 22:57 UTC
