### ISSUE TITLE
Icon Request: fa-wave

### ISSUE THREAD

**Issue by nhbeachguy** [FortAwesome/Font-Awesome#11267] opened 2017-07-07 14:19 UTC
Not a hand wave, but an ocean wave would be great.

**Comment by tagliala** [comment] 2017-07-08 11:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2266, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-08 11:25 UTC
