### ISSUE TITLE
Icon request: Scoop.it website icon

### ISSUE THREAD

**Issue by CelebxxCom** [FortAwesome/Font-Awesome#16027] opened 2020-01-06 18:19 UTC

**Comment by tagliala** [comment] 2020-01-06 18:28
Hi again @CelebxxCom 

Since you have already open #16016 and #16018, I think that you are not seeing my messages or that you don't want to reply to closed issues, so I'm leaving this open for a while.

This request is a duplicate of and #1603, you should add a 👍 reaction to that request.

1. Go to 
2. In the opening message title bar, click on the 😄  emoji and then click on the 👍emoji

![image](https://user-images.githubusercontent.com/556268/71839049-94663d00-30ba-11ea-8314-c4cda90efeb2.png)

you may be also interested in how requests work. Please take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs)

Leaving this open temporarily

**Comment by aethior** [comment] 2022-04-11 02:43
@tagliala I think you can close here.

**Closed** 2022-04-11 13:27 UTC
Labels: waiting for feedback
