### ISSUE TITLE
Icon request: icon-name : "new"

### ISSUE THREAD

**Issue by GayathriNagarajan18** [FortAwesome/Font-Awesome#16320] opened 2020-03-15 09:58 UTC
**What can it be used for?**
To highlight or indicate something that is newly added.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon 
- [ ] The title starts with "Icon request: icon-name " and is followed by the requested icon name (Ex: `Icon request: icon-name : "new"`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] Although we have an alternative to put a png image of "new" beside a newly added item, it would be better if there was a handy icon. 
- [ ] It would be nicer if the icon had characters in different colours

**Comment by tagliala** [comment] 2020-03-15 10:49
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #11002, please +1 that request

Anyway, we tend to avoid icons containing words, and we have an example of how this icon can be implemented right now with the SVG framework: https://fontawesome.com/how-to-use/svg-with-js#layering

**Closed by tagliala** 2020-03-15 10:50 UTC
