### ISSUE TITLE
fa fa mywed

### ISSUE THREAD

**Issue by lenkavanickova** [FortAwesome/Font-Awesome#16347] opened 2020-03-22 20:42 UTC
an icon which represenst the websites identity: https://mywed.com
would advice to use an icon like the fa fa on the site.
Icon could be found here: https://mywed.com/cs/logotypes/

Thanks!

**Comment by tagliala** [comment] 2020-03-22 21:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8063, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-22 21:11 UTC
