### ISSUE TITLE
Icon request: shake-hands

### ISSUE THREAD

**Issue by jose-pepe** [FortAwesome/Font-Awesome#7036] opened 2015-07-24 15:23 UTC
cases: interview, sealing a deal, first meeting.

Thank you

**Comment by TheChen5** [comment] 2015-07-26 00:30
Dupe of #878
"+1" that.
*Search before creating.*

**Comment by tagliala** [comment] 2015-07-26 13:09
@TheChen5 thanks

**Closed by tagliala** 2015-07-26 13:09 UTC
