### ISSUE TITLE
Icon request: peanut

### ISSUE THREAD

**Issue by ilu002** [FortAwesome/Font-Awesome#18413] opened 2021-11-03 19:36 UTC
**What can it be used for?**
Use case is medical allergies -where we'd use the icon to indicate patients' allergies; a common allergy is nuts, and common nut is peanut.

**Example image (optional)**
![2021-11-03 12_34_00-Window](https://user-images.githubusercontent.com/3085096/140180360-558d6180-b731-434e-850c-7849da529ae5.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-11-03 19:38
Hi!

Thanks for being part of the Font Awesome Community.

Peanut is available in FA6 Pro: https://fontawesome.com/v6.0/icons?q=peanut%20&s=solid

This is also a duplicate of #16502

**Closed by tagliala** 2021-11-03 19:38 UTC

**Comment by ilu002** [comment] 2021-11-03 19:49
Thank you :) Did not know about the beta site.
