### ISSUE TITLE
Icon Request: bookshelf/library

### ISSUE THREAD

**Issue by PeterWone** [FortAwesome/Font-Awesome#10851] opened 2017-03-28 02:36 UTC
I already created a glyph for representing online-line reference material but it would be more convenient as part of FA rather than an SVG file. It looks okay at small sizes now but I'm sure you can finesse it if you decide to incorporate it.

![image](https://cloud.githubusercontent.com/assets/5498936/24386386/a88bb652-13b2-11e7-9174-a02d79f304cc.png)
[Bookshelf-svg.zip](https://github.com/FortAwesome/Font-Awesome/files/874333/Bookshelf-svg.zip)

**Comment by tagliala** [comment] 2017-03-28 08:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5098, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-28 08:43 UTC

**Comment by PeterWone** [comment] 2017-03-28 11:01
I _did_ do a search. Specifically, I checked for "bookshelf", "library" and "reference". The duplicate is five thousand issues ago. Does this mean you don't plan to add this symbol?
