### ISSUE TITLE
icon request: icon-scratch

### ISSUE THREAD

**Issue by sobreira** [FortAwesome/Font-Awesome#9845] opened 2016-08-31 16:26 UTC
I would like to know if is possible to include the Scratch icon, from MIT. (The cat face)
The website is: https://scratch.mit.edu

By this website it's possible to share coding.

**Comment by tagliala** [comment] 2016-08-31 17:54
Duplicate of #9336, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-31 17:54 UTC
