### ISSUE TITLE
Icon Request: fa-ukflag

### ISSUE THREAD

**Issue by martinkearn** [FortAwesome/Font-Awesome#7321] opened 2015-08-27 14:14 UTC
Icons for the various major country flags. For example fa-ukflag, fa-franceflag, fa-usaflag.

Flags themselves should be flat, simple renditions of the flag's pattern. Clearly colour is not really possible other than simply setting the colour of the whole icon via CSS 'color' property.

Useful for selecting language or currency or filling out addresses.

**Comment by caduvieira** [comment] 2015-08-27 19:53
Dupe of #4735
+1 that issue

**Comment by tagliala** [comment] 2015-09-14 15:55
this is ok for usa flag and the union jack, but we cannot implement (i.e.) france and italy flags

**Closed by tagliala** 2015-09-14 15:55 UTC
