### ISSUE TITLE
Icon request: Table / Desk

### ISSUE THREAD

**Issue by Zaffer** [FortAwesome/Font-Awesome#17240] opened 2020-10-05 19:59 UTC
**What can it be used for?**
Very common every day house hold item missing is table. We have chairs but no tables?
I am building a service that manages office desks. Need at least one icon for this please!

**Example image (optional)**
https://www.flaticon.com/search?word=table

**Icon request checklist**
- [ yes] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ yes] I have included at least one example image if it could be helpful (optional)
- [ yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-10-15 13:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3519, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-10-15 13:11 UTC
