### ISSUE TITLE
Icon Request: Google+ (new look)

### ISSUE THREAD

**Issue by ronitf** [FortAwesome/Font-Awesome#7468] opened 2015-09-16 21:26 UTC
Google+ has updated their icon. Attached is an example.
![image](https://cloud.githubusercontent.com/assets/4553723/9918944/b40ca528-5c7e-11e5-8e6f-736a01cc5a3e.png)
Thanks!

**Comment by wolfy1339** [comment] 2015-09-16 21:42
dupe of #7357

**Comment by TheChen5** [comment] 2015-09-16 23:34
To prevent more dupes
Please :mag:before:heavy_plus_sign:

**Closed** 2015-09-17 06:59 UTC
