### ISSUE TITLE
New Web Icons

### ISSUE THREAD

**Issue by NenadObradovic** [FortAwesome/Font-Awesome#9531] opened 2016-07-07 12:34 UTC
Hi,

Is it possible to create new icons in future for arrows / close mark / global web icons to be more tiny. At this moment if you increase icons size you will get "fat" icon. 
Angle arrow Icons are ok when size is small but if you increase font size to 60px for example then that icons are "fat".

Maybe this will be good feature to have very tiny icons where font size will not affect the thickness of the icons

Best Regards,
Nenad

**Comment by tagliala** [comment] 2016-07-07 12:57
Hi,

tickness is a design choice. Dave is trying to keep alle the icons in the set visually consistent, so a 

There are requests for a thin close (#1540) or for an ultralight version of Font Awesome (#1733), but I would definitely recommend another set if you need a lighter design.

You can take a look at [fontawesome black tie - light](http://blacktie.io/products/light) (**note**: this set is not free and I'm not involved in that project) but there are many other sets of thin icons, you can take a look here: https://icomoon.io/app/#/select/library

Considering this a duplicate of #1733 and a superset of #1540 and #5166 

If you want to request single, individual thin icons please open new requests following our contributing guidelines:

Refs:
* https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
* https://github.com/FortAwesome/Font-Awesome/labels/thin%20icon

**Closed by tagliala** 2016-07-07 12:57 UTC
