### ISSUE TITLE
Icon request: tailwind-css

### ISSUE THREAD

**Issue by kanyshaiosmonova** [FortAwesome/Font-Awesome#19335] opened 2022-09-15 06:32 UTC
I wanted to add the icon of Tailwind CSS to my portfolio page but I couldn't find it. Could you make one, please? I really need it

**Comment by tagliala** [comment] 2022-09-15 07:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17012, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-09-15 07:23 UTC
