### ISSUE TITLE
Icon request: icon-Scoopit

### ISSUE THREAD

**Issue by R-Cal1** [FortAwesome/Font-Awesome#8711] opened 2016-03-07 16:55 UTC
Dear Fontawesome community,

I would like to know if it would be possibel to request the icon of the curation platform "Scoopit!"
It is a very well know plateform for marketers for microblogging, and i think it would be usefull to add the icon for the use of blogs, websites etc...

link : http://www.scoop.it/

You will find below two examples of the Scoop it icon: 

![scoop-it-logo](https://cloud.githubusercontent.com/assets/17707525/13576393/cb879b62-e48d-11e5-9835-2487888453b6.png)

![scoop-it-logo_318-65396 png](https://cloud.githubusercontent.com/assets/17707525/13576395/cdb789b0-e48d-11e5-953d-58fe7a180a19.jpg)

Thank you for your time,
Best regards,

**Comment by tagliala** [comment] 2016-03-07 18:02
duplicate of #1603, please +1 that request

closing here

**Closed by tagliala** 2016-03-07 18:02 UTC
