### ISSUE TITLE
Icon request: fa-currency (universal currency ¤)

### ISSUE THREAD

**Issue by saidbakr** [FortAwesome/Font-Awesome#11649] opened 2017-10-19 21:30 UTC
According to the [Wikipedia](https://en.wikipedia.org/wiki/Currency_sign_(typography)), the universal currency or currency sign is defined as:

> The currency sign (¤) is a character used to denote an unspecified currency. It is sometimes called scarab

This sign is not found in the Fontawesome and I suggest to add it to the **Currency Icons** section as a class named: `fa-currency`, because of being many currencies found around the world that has no demo symbol.

**Comment by hpvd** [comment] 2020-05-18 10:59
+1

**Comment by saidbakr** [comment] 2020-05-18 23:57
About three years ago and the issue had not be closed nor adopted in a new versions of Fontawesome!

**Comment by LizziePrimer** [comment] 2022-09-13 10:54
+1

**Comment by sensibleworld** [comment] 2024-07-11 19:43
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/4274)

**Closed by sensibleworld** 2024-07-11 19:43 UTC
Labels: new icon, currency (category), Duplicate
