### ISSUE TITLE
Icon request: icon-name cat & Icon request: icon-name dog

### ISSUE THREAD

**Issue by sfindley** [FortAwesome/Font-Awesome#12298] opened 2018-02-08 21:52 UTC
### What can it be used for? Veterinary Websites 

icons for canine and feline specific package buttons or used as bullet icons

### Example image (optional)
Feline Essential Care Plan
Canine Essential Care Plan 

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`) Matched pair
- [icon-cat] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [icon-dog] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)

- [true ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ no] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-02-09 10:51
Hi!

Thanks for being part of the Font Awesome Community.

Dog is a duplicate of #1317, please add a 👍  reaction to that request.
Cat is a duplicate of #2226 please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

> [true ] I have searched for existing issues and to the best of my knowledge this is not a duplicate

Don't worry 👍 

Closing here

**Closed by tagliala** 2018-02-09 10:51 UTC
