### ISSUE TITLE
Icon request: icon-excavator

### ISSUE THREAD

**Issue by YlloNieR** [FortAwesome/Font-Awesome#12504] opened 2018-03-03 13:27 UTC
### What can it be used for?
**On websites or webapps which deal with construction buildings/ building sites, logistics & management of that.**  
For example:
_As a user, I need to find easily where I can order excavator._ 

### Example image 
![icon-excavator](https://user-images.githubusercontent.com/30906472/36934787-d2dab500-1eee-11e8-9593-2465d4a745c2.png)

### Icon request checklist
> This is a single icon or matched
	**single**

> The title starts with "Icon request: " and is followed by the requested icon name 	
	**Yes**

> I have [searched for existing issues] and to the best of my knowledge this is not a duplicate
	**Yes, 
	#4084, #9380, #5305
	wasn’t a right way request** 

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ?)	
	**Yes**

**Comment by tagliala** [comment] 2018-03-03 13:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5303, please add a 👍  reaction to that request.

> wasn’t a right way request

I understand, but those are old requests and the request  template wasn't still available. Using #5303 will take advantage of +1s and comments

Closing here

**Closed by tagliala** 2018-03-03 13:48 UTC

**Comment by willidh** [comment] 2018-03-05 09:53
+1

**Comment by larssielaff** [comment] 2018-03-05 17:17
+1

**Comment by YlloNieR** [comment] 2018-03-05 17:41
@tagliala 
Would you be so nice & explain why the [fa-patreon #5303] icon request issue has been linked with this issue? 
![asd](https://user-images.githubusercontent.com/30906472/36990354-c2d4b64e-20a4-11e8-884a-c1f14b69bd4a.png)

**Comment by tagliala** [comment] 2018-03-05 22:18
@YlloNieR ahah thanks

#5303 instead of #5305 😅
