### ISSUE TITLE
Icon request: Instagram square

### ISSUE THREAD

**Issue by brandonmcconnell** [FortAwesome/Font-Awesome#13473] opened 2018-07-02 17:55 UTC
Most social media icons have a native square version, but there isn't one for Instagram

**Comment by tagliala** [comment] 2018-07-02 20:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9223, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-02 20:01 UTC
