### ISSUE TITLE
Icon request: Passenger / seat

### ISSUE THREAD

**Issue by olematon** [FortAwesome/Font-Awesome#10151] opened 2016-11-01 11:11 UTC
I would use it to express how many passenger seats there are in a vehicle.
Thanks.

**Comment by tagliala** [comment] 2016-11-01 13:10
maybe a duplicate of #2903 or #5658

**Comment by mareklexuan** [comment] 2020-03-25 11:43
Something like this

![icon-passenger-car](https://user-images.githubusercontent.com/25111994/77532973-429da980-6e96-11ea-82c0-b2e14044de7f.png)

**Comment by sensibleworld** [comment] 2024-07-12 13:36
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-12 13:36 UTC
Labels: Declined
