### ISSUE TITLE
Icon Request: fa-eyeem

### ISSUE THREAD

**Issue by vishna** [FortAwesome/Font-Awesome#5427] opened 2015-01-20 10:47 UTC
This is a request for an icon of EyeEm social media service.

> EyeEm is your creative community for photography. Distinct filters & editing tools to take your photos to > the next level.
> -- <cite>https://www.eyeem.com</cite>

EyeEm counts 10M+ users worldwide and is constantly growing.

Use cases:
- basically any use case that applies to `fa-instagram` or `fa-flickr`

EyeEm icon:

![eyeem_spotlight_100](https://cloud.githubusercontent.com/assets/121164/5815818/c0128f14-a099-11e4-9ccd-814da6e68f90.png)

**Comment by sublines** [comment] 2015-07-18 14:26
For anyone still interested in this: I use an ugly workaround to have this icon on my website: I simply stack the square icon (fa-square) with a bold "E". You can see it right here on my <a href='http://jaschagoltermann.de'>page</a>. 
You can see how to stack icons with text <a href='http://codepen.io/davegandy/pen/dlCuq/'>here</a></p>. Unfortunately the square icon has round corners, but it still looks very good.

**Comment by tagliala** [comment] 2015-07-18 19:15
duplicate of #2346 

closing here

**Closed by tagliala** 2015-07-18 19:15 UTC
