### ISSUE TITLE
icon-brazilian-real (R$) - fa-real

### ISSUE THREAD

**Issue by dfvascao** [FortAwesome/Font-Awesome#18325] opened 2021-10-02 10:20 UTC
Friend,

Have you seen how many orders from the Brazilian currency source have been ordered since 2016 and until today, 5 years have passed and it has not been created until today?

Link: https://github.com/FortAwesome/Font-Awesome/issues/4916

Link currency icon: https://cdn-icons-png.flaticon.com/512/32/32665.png

**Comment by tagliala** [comment] 2021-10-02 12:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4916, please add a 👍 reaction to that request, that's the best thing you can do

> 5 years have passed and it has not been created until today?

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-10-02 12:04 UTC
