### ISSUE TITLE
Icon request: fa-bon-bon

### ISSUE THREAD

**Issue by Bellah** [FortAwesome/Font-Awesome#11285] opened 2017-07-13 08:48 UTC
Hello!

Please add a bon bon / sweet to the set. 

![img2](https://user-images.githubusercontent.com/4134199/28158105-ec62cc62-67b8-11e7-8897-0e2331d6f9f6.jpg)

I am currently building a website and for the references I'd like symbols that match them. There is nothing suitable for a sweet shop, so I'd like that very much :)

Thank you,
Isabella

**Comment by tagliala** [comment] 2017-07-13 09:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6015, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-13 09:01 UTC
