### ISSUE TITLE
Intersection icon

### ISSUE THREAD

**Issue by Aliuken** [FortAwesome/Font-Awesome#8798] opened 2016-03-21 09:22 UTC
Could you add an icon of a circle intersecting with another circle? Like this:
https://en.wikipedia.org/wiki/Intersection_%28set_theory%29#/media/File:Venn0001.svg

Thanks.

**Comment by tagliala** [comment] 2016-03-21 09:29
Duplicate of #1544, please +1 that request

closing here

**Comment by tagliala** [comment] 2016-03-21 09:30
duplicate of #2164, please +1 that request

closing here

**Comment by Aliuken** [comment] 2016-03-21 10:04
I don't know how to do a +1

**Comment by tagliala** [comment] 2016-03-21 10:13
leave a comment with "+1" :)

**Closed by tagliala** 2016-03-21 10:13 UTC
