### ISSUE TITLE
Icon Request: fa-customs

### ISSUE THREAD

**Issue by shranac** [FortAwesome/Font-Awesome#7929] opened 2015-11-19 21:05 UTC
I would dearly love an icon representing a customs checkpoint. Often this is a customs officer with an open case. Something like this...
![customs](https://cloud.githubusercontent.com/assets/15932346/11284349/16c5ff90-8ebe-11e5-8bf9-86225b71f45b.gif)

**Comment by tuxy** [comment] 2015-11-20 06:48
+1 for **fa-customs** ![fa-customs](http://i.imgur.com/t0A8siH.png)

**Comment by lroal** [comment] 2016-03-18 13:01
+ 1

**Comment by lroal** [comment] 2017-05-29 11:13
Any news on this one ?

**Comment by shranac** [comment] 2017-06-01 16:22
Nothing new so far. Let's keep the faith.

**Comment by tagliala** [comment] 2022-02-27 16:56
Just noticed this is a duplicate of #2353, please add a 👍🏼 reaction to that request

**Closed by tagliala** 2022-02-27 16:56 UTC
Labels: new icon, web application icons
