### ISSUE TITLE
Icon request: fa-aparat

### ISSUE THREAD

**Issue by noorhoda** [FortAwesome/Font-Awesome#16881] opened 2020-07-06 14:00 UTC
**What can it be used for?**
Aparat.com is a video sharing service like youtube for perisan.
LOGO file is here: http://www.aparat.com/logo

**Example image (optional)**
LOGO file is here: http://www.aparat.com/logo
This is a single icon

![icon--color-black@16px](https://user-images.githubusercontent.com/33067942/86601593-c3e8fa00-bfb6-11ea-96e3-8b307fcb4f3e.png)
![icon--color-black@32px](https://user-images.githubusercontent.com/33067942/86601595-c51a2700-bfb6-11ea-88e3-8392d60e5cc3.png)
![icon--color-black@64px](https://user-images.githubusercontent.com/33067942/86601598-c5b2bd80-bfb6-11ea-99ff-967a12c4f095.png)
![icon--color-black@128px](https://user-images.githubusercontent.com/33067942/86601600-c5b2bd80-bfb6-11ea-9fb3-e669c263a335.png)
![icon--color-black@256px](https://user-images.githubusercontent.com/33067942/86601601-c64b5400-bfb6-11ea-819e-e6bda646f668.png)
![icon--color-black@512px](https://user-images.githubusercontent.com/33067942/86601604-c64b5400-bfb6-11ea-87ff-b29ae2f640ce.png)
![icon--color-black@1024px](https://user-images.githubusercontent.com/33067942/86601606-c6e3ea80-bfb6-11ea-8e0d-ad698f64e824.png)

**Comment by tagliala** [comment] 2020-07-06 20:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5204, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-07-06 20:54 UTC
