### ISSUE TITLE
Icon request: placeholder

### ISSUE THREAD

**Issue by yianni-ververis** [FortAwesome/Font-Awesome#8315] opened 2016-01-12 16:43 UTC

**Comment by tagliala** [comment] 2016-01-12 17:27
could you please provide an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by yianni-ververis** [comment] 2016-01-12 17:33
there are times that designers add a trsansparent spacer.gif or a placeholder image of 1x1, just to hold the space.

I am creating a ul dynamically and I would like to add on each li an icon. Based on a condition, I would like to have placeholder or the specific icon. I could do this with css of course but, it would be much easier if I had a transparent placeholder to keep the height and width of the div.

I hope I make any sense!!!!

**Comment by tagliala** [comment] 2016-01-12 18:45
got it.

Since fontawesome icons have not the same width by default, you should use the `fa-fw` class as a placeholder. 

Duplicate of #1606, labeled as wontfix

How to get a blank icon: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#need-a-blankempty-icon

**Closed by tagliala** 2016-01-12 18:45 UTC
Labels: waiting for feedback

**Comment by yianni-ververis** [comment] 2016-01-12 18:47
Thank you


Yianni Ververis
Qlik Sense Web Developer

Email:  Yianni.Ververis@qlik.com

Qlik
150 N. Radnor Chester Road
Suite E-120
Radnor Pennsylvania 19087

qlik.com<http://www.qlik.com/>
<http://qlik.com/>

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.
