### ISSUE TITLE
Icon request: fa-php

### ISSUE THREAD

**Issue by kenshiwara** [FortAwesome/Font-Awesome#9899] opened 2016-09-10 15:51 UTC
It would be nice to have the brand icon of PHP.

**Comment by timmyrs** [comment] 2016-09-10 16:00
+1

**Comment by tagliala** [comment] 2016-09-10 17:28
Duplicate of #1420 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-10 17:28 UTC
