### ISSUE TITLE
Icon request: Moodle icon

### ISSUE THREAD

**Issue by tigusigalpa** [FortAwesome/Font-Awesome#3736] opened 2014-06-18 12:20 UTC
Hi, guys!
is it possible to make a Moodle LMS icon?

**Comment by aethior** [comment] 2016-02-05 22:59
Duplicate of #2167. (cc @tagliala)

**Comment by tagliala** [comment] 2016-02-05 23:41
@aethior thanks

**Closed by tagliala** 2016-02-05 23:41 UTC
Labels: brand icons, new icon
