### ISSUE TITLE
Icon request: stop-sign

### ISSUE THREAD

**Issue by RHOPKINS13** [FortAwesome/Font-Awesome#6404] opened 2015-05-06 19:03 UTC
Hi,

I thought a stop sign icon would be useful under transportation. Maybe even two icons? One with the word "STOP" and one without. Perhaps the one without could just be called octagon?
![145px-vienna_convention_road_sign_b2a svg](https://cloud.githubusercontent.com/assets/4227237/7501291/f8288902-f400-11e4-9296-1aaf6a85b943.png)

**Comment by tagliala** [comment] 2015-05-06 20:20
duplicate of #1872 , please +1 that request

closing here

**Closed by tagliala** 2015-05-06 20:20 UTC
