### ISSUE TITLE
Icon request: TikTok icon

### ISSUE THREAD

**Issue by kparsapour** [FortAwesome/Font-Awesome#16631] opened 2020-05-14 12:06 UTC
**What can it be used for?**
TikTok is a very popular and fast-growing site

**Example image (optional)**
<img width="37" alt="Screen Shot 2020-05-14 at 5 04 20 AM" src="https://user-images.githubusercontent.com/10100681/81932311-75177900-95a0-11ea-93f5-3a665dec9a87.png">

**Icon request checklist**
- [x ] This is a single icon
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-14 13:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14340 

You can also avoid to 👍 that request, Tik Tok is coming soon :)

Closing here

**Closed by tagliala** 2020-05-14 13:01 UTC
