### ISSUE TITLE
Icon Request: fa-pkr

### ISSUE THREAD

**Issue by areebirfan** [FortAwesome/Font-Awesome#17497] opened 2020-12-18 14:12 UTC
I want to request to add an icon of pkr(Pakistani Rupee).I want to use it in my website.
Thankyou.

**Comment by tagliala** [comment] 2020-12-18 15:51
Hi!

Thanks for being part of the Font Awesome Community.

This will be part of FA6

Duplicate of #16651

**Closed by tagliala** 2020-12-18 15:51 UTC
