### ISSUE TITLE
Icon Request: fa-globe-alt

### ISSUE THREAD

**Issue by redoper1** [FortAwesome/Font-Awesome#11880] opened 2017-12-08 19:28 UTC
I would like to ask, if you are planning  to add "globe" icon from [the old versions](http://fontawesome.io/icon/globe/) of font for example as a fa-globe-alt.

I know many people doesn't like it, because there was only America. But in my opinion the old one looked a lot better and I think I'm not the only one who has that opinion.

**Comment by will-stone** [comment] 2017-12-15 11:32
Focus by continent would be great:
- fa-globe-alt-asia
- fa-globe-alt-africa
- fa-globe-alt-antartica
- fa-globe-alt-australia
- fa-globe-alt-europe
- fa-globe-alt-north-america
- fa-globe-alt-south-america

**Comment by tagliala** [comment] 2017-12-15 11:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #281 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-15 11:42 UTC
