### ISSUE TITLE
problem with icon address-book

### ISSUE THREAD

**Issue by jutho-agentur** [FortAwesome/Font-Awesome#12782] opened 2018-04-05 11:51 UTC
Hello,
I'm trying to use the icon address-book via CSS. But I can't get it working.

That's my code:

```
li.address a::before {
    content: "\f2b9";
    font-family: FontAwesome;
    font-size: 100%;
}
```

What am I doing wrong? Or is there a problem?

Thanks.

**Comment by jutho-agentur** [comment] 2018-04-05 12:09
I found a solution by myself:
`font-family: "Font Awesome 5 Free", FontAwesome;`

The new address-book icon needs the "Font Awesome 5 Free". But all the other icons I have in use need the "FontAwesome".
It's a bit weird...

**Comment by tagliala** [comment] 2018-04-06 08:05
Hi!

Thanks for being part of the Font Awesome Community.

> font-family: "Font Awesome 5 Free", FontAwesome;

Please do not use that and refer to the documentation, the issue is in font name and font weight: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

Hope it helps

Closing here

**Closed by tagliala** 2018-04-06 08:05 UTC
