### ISSUE TITLE
Icon request: mixer

### ISSUE THREAD

**Issue by DerBraky** [FortAwesome/Font-Awesome#15463] opened 2019-08-31 10:44 UTC
**What can it be used for?**
Linking Mixer profiles.

**Example image (optional)**

![MixerMerge_Black](https://user-images.githubusercontent.com/53004544/64062876-b91e4580-cbec-11e9-9de7-d8f11e7a157f.png)

[Official Mixer Branding Kit](https://github.com/mixer/branding-kit)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-08-31 11:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11242, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-08-31 11:11 UTC
