### ISSUE TITLE
Icon Request: fa-chemical

### ISSUE THREAD

**Issue by niyazpoyilan** [FortAwesome/Font-Awesome#9553] opened 2016-07-12 21:58 UTC
A chemical in a lab tube

**Comment by tagliala** [comment] 2016-07-12 22:38
Duplicate of #1353 ?

**Comment by JoeKonst** [comment] 2016-07-13 16:30
![chemical-blue](https://cloud.githubusercontent.com/assets/12752154/16811287/75a8d944-491f-11e6-99ff-8d8494ffe285.png)

What about something like this?

**Comment by tagliala** [comment] 2016-07-13 16:51
We already have a flask: http://fontawesome.io/icon/flask/

**Comment by JoeKonst** [comment] 2016-07-13 18:30
Ah yeah, my bad!

Maybe this then:

![testtube](https://cloud.githubusercontent.com/assets/12752154/16815020/3579a2b6-4930-11e6-9041-a619e7f199db.png)

**Comment by tagliala** [comment] 2016-07-13 18:38
So can I consider this a duplicate of #1353?

**Comment by kanalumaddela** [comment] 2016-07-13 23:56
yeah^

**Comment by tagliala** [comment] 2016-07-14 09:31
Duplicate of #1353, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-14 09:31 UTC
Labels: waiting for feedback
