### ISSUE TITLE
Icon request: fa-project

### ISSUE THREAD

**Issue by adius** [FortAwesome/Font-Awesome#10407] opened 2016-12-21 10:12 UTC
Open iconic has a project icon which I found quite useful as an icon for listing all projects in a webapp.
They use a gantt chart as the symbol.

![gantt chart](https://raw.githubusercontent.com/iconic/open-iconic/master/png/project-8x.png)

GitHub also has a "Projects" tab with a kanban board as the logo:

<img width="90" alt="kanban-board" src="https://cloud.githubusercontent.com/assets/969983/21385173/728ec70e-c765-11e6-9798-3d81a4e6d1df.png">

I think I'd prefer the gantt chart

**Comment by tagliala** [comment] 2016-12-21 12:44
I suppose this is a duplicate of #3915

**Comment by MaklaCof** [comment] 2019-03-04 13:13
Maybe something like this:

![image](https://user-images.githubusercontent.com/1589573/53735579-9d2d2780-3e87-11e9-87f2-e31825ef9884.png)

**Comment by sensibleworld** [comment] 2024-07-12 17:44
We have a few issues that should work for this:

https://fontawesome.com/icons/chart-gantt?f=classic&s=solid

https://fontawesome.com/icons/square-kanban?f=classic&s=solid

**Closed by sensibleworld** 2024-07-12 17:44 UTC
Labels: waiting for feedback
