### ISSUE TITLE
Icon Request: fa-palette

### ISSUE THREAD

**Issue by crevete** [FortAwesome/Font-Awesome#7191] opened 2015-08-10 13:48 UTC
Please add an color palette icon (something like the icon below) in your project. The use case is to represent a theme customization page. Currently, the only icon we could use is : http://fortawesome.github.io/Font-Awesome/icon/paint-brush/. But we really need the palette icon (ideally with the brush) that make sens for our use case. Thanks!

<img width="64" alt="color_palette" src="https://cloud.githubusercontent.com/assets/6795189/9172859/9425f3c4-3f76-11e5-81c8-3a3660f300ec.png">

PS: the icon name could also be ```fa-palette-brush```.

**Comment by tagliala** [comment] 2015-08-10 14:50
duplicate of #244 , please +1 that request

closing here

**Closed by tagliala** 2015-08-10 14:50 UTC
