### ISSUE TITLE
Icon Request: icon-viadeo

### ISSUE THREAD

**Issue by W4cko** [FortAwesome/Font-Awesome#5387] opened 2015-01-14 10:41 UTC
Viadeo is like a French "Linkedin" 

fr.viadeo.com

![image](https://cloud.githubusercontent.com/assets/5968951/5737532/3855a68a-9be2-11e4-9b46-b87078a11b49.png)

**Comment by tagliala** [comment] 2015-01-14 11:28
duplicate of #886 , please +1 that request

closing here

**Closed by tagliala** 2015-01-14 11:28 UTC
