### ISSUE TITLE
No metadata yaml's?

### ISSUE THREAD

**Issue by patriceckhart** [FortAwesome/Font-Awesome#18722] opened 2022-02-19 16:49 UTC
Are there no metadata yamls in 6.0.0? icons.yml etc?

**Comment by tagliala** [comment] 2022-02-19 16:50
Hi!

Thanks for being part of the Font Awesome Community.

Metadata have been intentionally removed in v6, but they will come back

Duplicate of the pinned issue #18662, let's continue there

**Closed as completed by tagliala** 2022-02-19 16:50 UTC

**Comment by sensibleworld** [comment] 2023-02-07 20:46
@patriceckhart Wanted to give a quick update that, as of our [6.3.0 release](https://fontawesome.com/docs/changelog/), we've added back the search terms to our metadata files, where they'll stay. Apologies for the poor communication and frustration we caused around this matter.
