### ISSUE TITLE
Icon request: Open-Access

### ISSUE THREAD

**Issue by DesignLots** [FortAwesome/Font-Awesome#14153] opened 2018-10-22 01:11 UTC
### What can it be used for?
Open access (OA) refers to research outputs which are distributed online and free of cost or other barriers. See more: https://en.wikipedia.org/wiki/Open_access

### Example image (optional)
<img width="214" alt="screen shot 2018-10-22 at 11 10 17 am" src="https://user-images.githubusercontent.com/998120/47274687-26d00d00-d5eb-11e8-8230-10fc1a2614b1.png">

**Comment by tagliala** [comment] 2018-10-22 11:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5587, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-22 11:16 UTC
