### ISSUE TITLE
Icon Request: fa-kinopoisk

### ISSUE THREAD

**Issue by Wodooo** [FortAwesome/Font-Awesome#10807] opened 2017-03-18 17:21 UTC
Hello. Can I ask for the icon of the site "kinoposk.ru". I will use it on my website about the movie. You have a rating of imdb. There is also a kinopoisk rating. Thank you in advance.

![image](https://cloud.githubusercontent.com/assets/26508378/24074366/e47840b8-0c0f-11e7-9d7d-f7e0ec56cd1e.png)

![image](https://cloud.githubusercontent.com/assets/26508378/24074375/05b38a3a-0c10-11e7-835c-106628dced36.png)

**Comment by tagliala** [comment] 2017-03-18 17:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9770, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-18 17:22 UTC
