### ISSUE TITLE
Icon request: Waiter/host

### ISSUE THREAD

**Issue by nickdnk** [FortAwesome/Font-Awesome#13779] opened 2018-08-16 17:09 UTC
### What can it be used for?

Describe personnel assigned as host/hostess/waiter for table reservations/booking systems. This should be plausible considering you have an astronaut.

### Example image (optional)

I suggest a user holding a tray with a drink or bottle on. I'm thinking something along the lines of https://previews.123rf.com/images/olegbabich/olegbabich1501/olegbabich150100050/35382079-waiter-icon.jpg - but perhaps more focused on the head/upper torso as the other user-icons you have.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-16 19:39
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color example, suitable for 16px icon size?

Could this be considered a duplicate of #3453?

**Comment by nickdnk** [comment] 2018-08-16 20:07
Hello

I'm thinking something along the lines of https://previews.123rf.com/images/olegbabich/olegbabich1501/olegbabich150100050/35382079-waiter-icon.jpg - but perhaps more focused on the upper torso as the other user-icons you have.

I don't consider this a duplicate of dinner plate, no.

**Comment by danielfroz** [comment] 2020-09-24 13:10
Any update on this one guys?

**Comment by sensibleworld** [comment] 2024-07-11 19:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 19:23 UTC
Labels: new icon, food-beverage (category), Declined
