### ISSUE TITLE
Icon request: icon-klarna

### ISSUE THREAD

**Issue by daniel-eriksson** [FortAwesome/Font-Awesome#17813] opened 2021-04-13 08:03 UTC
**What can it be used for?**
A payment provider widely used in Scandinavia. Can be used in all types of e-commerce solutions.

**Example image (optional)**
[https://www.google.com/search?q=klarna+logo&sxsrf=ALeKk00lV7lcpi0dudmbHMs1T8trhwSB0Q:1618300832584&source=lnms&tbm=isch&sa=X&ved=2ahUKEwil8I-y4PrvAhVQx4sKHVicBXgQ_AUoAXoECAEQAw&biw=2349&bih=1210](url)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-04-13 08:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4340, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-04-13 08:16 UTC
