### ISSUE TITLE
Icon request: icon-origin

### ISSUE THREAD

**Issue by vsential** [FortAwesome/Font-Awesome#10561] opened 2017-01-24 18:37 UTC
Use case is for addition to social media links in multiple Jekyll templates.

![origins-symbol-icon-65768](https://cloud.githubusercontent.com/assets/4664215/22261230/c2524fd6-e231-11e6-9758-bbfc34ce291b.png)

**Comment by tagliala** [comment] 2017-01-24 19:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1290, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-24 19:35 UTC
