### ISSUE TITLE
Icon Request: fa-Bubble-Chart

### ISSUE THREAD

**Issue by amayd** [FortAwesome/Font-Awesome#7519] opened 2015-09-23 09:12 UTC
for bubble chart please create icon.please find attached cope of icon I found in www.IconFinder.com

![bubble](https://cloud.githubusercontent.com/assets/5735968/10041343/457603ba-6201-11e5-814c-67e83afb3943.png)

**Comment by tagliala** [comment] 2015-09-23 13:50
this should be a duplicate of #4240

**Comment by amayd** [comment] 2015-09-29 08:44
I am not able to find that icon.  I have downloaded 3.2.1 but not able to found that fa-scatter-chart class
Please suggest something

**Comment by ITPrism** [comment] 2015-10-01 20:42
+1

**Comment by tagliala** [comment] 2015-10-02 16:34
@amayd #4240 is a request, not an icon of the set. If you confirm that it is a duplicate I will close this one

**Comment by amayd** [comment] 2015-10-03 14:05
Yes this is the duplicate one. you can close this incident .Please if
possible redirect me to the source or that icon.

On Fri, Oct 2, 2015 at 10:04 PM, Geremia Taglialatela <
notifications@github.com> wrote:

> @amayd <https://github.com/amayd> #4240
> <https://github.com/FortAwesome/Font-Awesome/issues/4240> is a request,
> not an icon of the set. If you confirm that it is a duplicate I will close
> this one
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/7519#issuecomment-145080479>
> .
>



-- 




*Regards,Ameya A. Deshpande+91-9730970030*
*"Stay committed to your Dreams but be flexible in approach !!!"*

**Comment by tagliala** [comment] 2015-10-03 16:19
@amayd #4240 is a request, please +1 that one

Contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

If you need this icon in a short while, you can customize fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2015-10-03 16:19 UTC
Labels: waiting for feedback
