### ISSUE TITLE
Missing brand icon for the CMS TYPO3!?

### ISSUE THREAD

**Issue by kurtkk** [FortAwesome/Font-Awesome#9857] opened 2016-09-05 08:31 UTC
Hi all,
I found Wordpress, Joomla amd Drupal as CMS brand icons but I am missing the brand icon for TYPO3:
![typo3_logo_orange_free](https://cloud.githubusercontent.com/assets/8299389/18241872/c46a3a60-7353-11e6-8e9f-9b4c1d3f91ae.png)

If you want, I can send you a SVG-file with this brand?
Is it possible to create one for the next version of the brand icons?

Kind regards from Jülich, Germany

Kurt Kunig
kupix webdesign

**Comment by tagliala** [comment] 2016-09-05 08:51
Duplicate of #1424, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-05 08:51 UTC
