### ISSUE TITLE
Icon request: tower-crane

### ISSUE THREAD

**Issue by scottpilgrimltd** [FortAwesome/Font-Awesome#17205] opened 2020-09-28 13:44 UTC
**What can it be used for?**
Used as an icon for a construction project and/or company.

**Example image (optional)**
https://www.flaticon.com/free-icon/tower-crane-with-container_75828

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`) SINGLE
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
![tower crane](https://user-images.githubusercontent.com/72026465/94439875-de3b0a00-0198-11eb-81b1-11a1cbd0cbdc.png)

**Comment by tagliala** [comment] 2020-09-28 16:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12499, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-28 16:38 UTC
