### ISSUE TITLE
Icon request: icon-mixer

### ISSUE THREAD

**Issue by The-Scro-MX** [FortAwesome/Font-Awesome#12728] opened 2018-03-29 00:59 UTC
Hello, I contact you because I would like to know if it would be possible to have an Icon for the Site Mixer: www.mixer.com.

I thank you in advance

**Comment by tagliala** [comment] 2018-04-06 15:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11242, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 15:45 UTC
