### ISSUE TITLE
Icon request: clube-da-voz

### ISSUE THREAD

**Issue by ductba** [FortAwesome/Font-Awesome#13140] opened 2018-05-14 19:28 UTC
### What can it be used for?

Olá, adoraria ter um ícone do Clube da Voz for Font-Awesome. o Clube da Voz é uma associação de locutores profissionais que atuam no mercado de publicidade.

Site oficial da associação : http://www.clubedavoz.com.br

Gostaria de poder usar este icone em um theme (wordpress) http://www.vipreseller.net/~ericsant/ cujo icones vem de Font-Awesome. isso é possível ?

### Example image (optional)

![icon](https://user-images.githubusercontent.com/39117010/40018778-a1a72274-5793-11e8-8924-1083c637fc14.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-05-14 19:35
Hi!

Thanks for being part of the Font Awesome Community.

Duplicate of #13117, with a different title

Please fix #13117's title if it is wrong

**Closed by tagliala** 2018-05-14 19:35 UTC

**Comment by ductba** [comment] 2018-05-14 19:43
OK. Corrigido
