### ISSUE TITLE
Icon request: icon-scroll

### ISSUE THREAD

**Issue by razor-rich** [FortAwesome/Font-Awesome#8599] opened 2016-02-17 14:27 UTC
I was looking for a mouse scroll icon which i've seen on quite a lot of sites.

![image](https://cloud.githubusercontent.com/assets/5901199/13112439/91853614-d582-11e5-93e0-f9bad240daed.png)

**Comment by tagliala** [comment] 2016-02-17 14:43
duplicate of #5308
please +1 that request

closing here

**Closed by tagliala** 2016-02-17 14:43 UTC
