### ISSUE TITLE
Icon request: bracket-left

### ISSUE THREAD

**Issue by oarguedas77** [FortAwesome/Font-Awesome#16095] opened 2020-01-20 16:39 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.

Bracket icon from special event of basketball

**Example image (optional)**
http://suplitodomedia.com/download/osvaldo/icon.jpg

**Icon request checklist**
- [Single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [Ok] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [Done] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Done] I have included at least one example image if it could be helpful (optional)
- [Ok] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-01-20 21:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3819 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-20 21:14 UTC
Labels: new icon, sport (category)
