### ISSUE TITLE
Icon request: icon-yammer

### ISSUE THREAD

**Issue by Rabia-Ahmed92** [FortAwesome/Font-Awesome#10378] opened 2016-12-16 06:00 UTC

**Comment by tagliala** [comment] 2016-12-16 10:18
Duplicate of #2707, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-16 10:18 UTC
