### ISSUE TITLE
Icon request: comment-question

### ISSUE THREAD

**Issue by jwilliams-hsi** [FortAwesome/Font-Awesome#18323] opened 2021-10-01 18:01 UTC
I need a comment bubble icon with a question mark in it. This would be used to spark discussion questions for training programs.

Use https://fontawesome.com/v5.15/icons/comment-medical?style=solid as a baseline.

**Comment by tagliala** [comment] 2021-10-01 18:09
Hi!

Thanks for being part of the Font Awesome Community.

This icon will be available in FA6 Pro: https://fontawesome.com/v6.0/icons?q=comment%20question&s=solid%2Cbrands

**in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/589/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Closing here as duplicate of #14617

**Closed by tagliala** 2021-10-01 18:09 UTC
