### ISSUE TITLE
Icon request: C#

### ISSUE THREAD

**Issue by cohejh** [FortAwesome/Font-Awesome#19227] opened 2022-08-02 12:36 UTC
### Use case

This could be used in portfolios for example.

### Example image

![773626-removebg](https://user-images.githubusercontent.com/87650074/182376186-b09b1ac6-7cc7-4ffa-964a-dce0a65db2f6.svg)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2022-08-02 12:40
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8365 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**NOTE:** there is not an official icon for C#

**Closed as completed by tagliala** 2022-08-02 12:40 UTC
Labels: new icon
