### ISSUE TITLE
New icons not included in TTF?

### ISSUE THREAD

**Issue by harunalikadic** [FortAwesome/Font-Awesome#6288] opened 2015-04-22 11:05 UTC
Cannot find "bed" or "hotel" icon available within the TTF font installed on my PC.
I have downloaded latest package from the website, but when I try to copy "bed" icon from cheatsheet in Illustrator it doesn't show up (I get crossed rectangle indicating character not found). Am I doing something wrong?

H

**Comment by tagliala** [comment] 2015-04-22 14:12
Since the ttf is automatically generated by font squirrel, I doubt the above icons are not included...

Please uninstall the old .ttf, download a new copy from fontawesome.io and install again.

Let me know

**Comment by haligaliharun** [comment] 2015-04-23 07:55
I do not know why this happens, but it still occurs.

  1. I have downloaded the latest version:

![screen shot 2015-04-23 at 09 42 11](https://cloud.githubusercontent.com/assets/4660587/7292544/39d64c4a-e99d-11e4-9bb3-dcaf2da00244.png)

  2. deleted the previous version from Font Book and installed the new one:

![screen shot 2015-04-23 at 09 46 28](https://cloud.githubusercontent.com/assets/4660587/7292590/9af6002e-e99d-11e4-98a2-97d260877814.png)

  3. Opened FontAwesomeCheatsheet.PDF in Illustrator and this is what comes out, icon "bed" is not available:

![screen shot 2015-04-23 at 09 38 55](https://cloud.githubusercontent.com/assets/4660587/7292612/c1ef75c0-e99d-11e4-974d-af82741ee512.png)

  4. I have opened Glyph library for FontAwesome in Illustrator, this is the result, some new icons from 4.3 are there, like "connectdevelop" or "dashcube" but others like "medium" or "bed" are not.

![screen shot 2015-04-23 at 09 48 08](https://cloud.githubusercontent.com/assets/4660587/7292734/972410de-e99e-11e4-9c4b-10a5f42a3099.png)

**Comment by tagliala** [comment] 2015-04-27 08:52
Could you please try the .otf file?

**Comment by mattsnowky** [comment] 2015-04-27 18:23
The OTF does contain the new characters; I found that out last night. Don't know if it helps, but OSX Font Book is complaining about a 'name' table structure having errors... I have to OK the problems and continue the install.

**Comment by haligaliharun** [comment] 2015-04-27 19:53
Thanks, installing .OTF worked for me. I confirm that FontBook gives me the same warning reported by @mattsnowky

**Comment by tagliala** [comment] 2015-04-27 21:21
@mattsnowky the ttf is automatically generated by Font Squirrel here: http://www.fontsquirrel.com/tools/webfont-generator

maybe you could drop them a line, pointing to this issue.

I don't know if they are interested to solve this, the purpose of their file is to provide a .ttf file working for the web

**Comment by mattsnowky** [comment] 2015-04-28 14:29
I've reached out to Font Squirrel via their contact form. I'll let you know if I hear something.

**Comment by mattsnowky** [comment] 2015-04-28 15:29
Well that was quick. I spoke with Joe Manbeck at Font Squirrel. He was able to take the 4.3.0 OTF and create working TTF with no errors and all the new icons.

Here's what he wrote:
"What are the settings being used to convert on the webfont generator? I just uploaded FontAwesome.otf, and got a TTF with the bed icon. I used the expert settings and no subsetting to get it.

I’ve attached my InDesign screenshot and the Webfont kit with the TTF included. Let me know if I can help with anything else."

I can confirm that thing are right as rain with this TTF:
![screenshot-1430234858](https://cloud.githubusercontent.com/assets/5940862/7373306/9f05ca96-ed99-11e4-8643-83ca8ef9a75b.png)

Seeing that there is an issue that can be resolved with the help of the folks at Font Squirrel, is that something you all can look in to for an udpate?

**Comment by mattsnowky** [comment] 2015-04-28 15:30
I asked Joe if there are any 'usual suspects' and he wrote back again: "Literally the only thing I changed was turning off language subsetting. That glyph must fall in a range outside of our default, western Latin, language subset and so was not included in their conversion. If they want every glyph in the original OTF included, they should use the no subsetting option."

Hope this is helpful!

**Comment by tagliala** [comment] 2015-04-29 14:54
@mattsnowky thanks!

I don't know if Dave turned off that thing, I would say he didn't. Adding to 4.3.1 milestone and assigning to Dave

**Comment by tagliala** [comment] 2015-04-29 14:55
@davegandy https://github.com/FortAwesome/Font-Awesome/issues/6288#issuecomment-97106253

**Comment by techdragon** [comment] 2015-06-03 07:17
I just encountered the issue. 
Installing the TTF reports an issue with the```'name' table structure```
Installing the PostScript version works fine.

**Comment by socialblogsite** [comment] 2015-06-09 00:25
It seems the issue is somewhere else. It has to be something IN the browser, when you have the font installed. This is why:

I have my illustrator file open, with most icons ok, but the area-chart showing a crossed square, and I de-activated the font (.otf) in the OS. Now all the icons show as squares as well. 

Then I installed the TTF font (Font book crashes) and the second time it complains "table" name is corrupt, or something like that. (the .otf version was ok though).  I hit ok, and Illustrator STILL shows the character as a crossed square.

I was suspecting the browser copying something bad, because the chances of me choosing TWO icons and both being broken are to low… I suspected the act of copying it was breaking something in AI… so I copied the area chart again, and IT WORKED. 

So whatever I copied before (as the area chart) had NOT the code of the area chart, or was somehow different than the second time. 

Illustrator should have SHOWN the icon as soon as the working font (yet corrupt) was loaded.
Or am I missing something?

AFAK the only thing Chrome sends to the clipboard is the character code, not the formatting… and if it is, there should not affect the character code.

**Comment by tagliala** [comment] 2015-06-09 10:19
@socialblogsite thanks for sharing this

**Comment by davegandy** [comment] 2015-07-28 05:34
I always turn off font subsetting when using Font Squirrel. This could be part of the reason why a lot of time folks will change the font name in the version installed on the desktop vs the web. Then you know you're getting the right version. Not exactly sure how to handle this for 4.4, but I suspect anything will be a breaking change. Might have to wait until 5.0.

**Comment by davegandy** [comment] 2015-07-28 14:39
Moving into 5.0 milestone.

**Closed** 2019-04-11 14:04 UTC
Labels: bug
