### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dl748** [FortAwesome/Font-Awesome#8390] opened 2016-01-22 06:56 UTC
If you are creating the font in the Unicode space, why did you not put the Glyphs under the correct Unicode characters?

i.e.
Font Awesome U-F295 = Percent, but Unicode has them at U-0025 for standard percent and U-FF05 for full width percent

Font Awesome U-F185 = Sun with rays, Unicode is set to U-263C

Font Awesome U-F186 = Crescent Moon, Unicode is set to U-1F319

**Comment by tagliala** [comment] 2016-01-22 09:26
Duplicate of #222, planned for 5.0.0

**Closed by tagliala** 2016-01-22 09:26 UTC

**Comment by dl748** [comment] 2016-01-22 17:46
Also, I don't see any step for glyph contributions.  You have steps for ASKING for new glyphs, but no steps for someone to contribute new ones to the set.

**Comment by tagliala** [comment] 2016-01-22 18:35
@dl748 sorry, that is not possible

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests

> At the moment we are not accepting pull requests containing icons

if you need an icon right now please consider a custom build https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
