### ISSUE TITLE
Issue with stacked icons

### ISSUE THREAD

**Issue by leecollings-sb** [FortAwesome/Font-Awesome#18271] opened 2021-09-15 13:47 UTC
**Describe the bug**
When copying and pasting one of the examples of stacked icons, the initial load seems OK but then jumps to a very enlarged and off-centred circle div behind the icon

**To Reproduce**
https://staging.thepsychicreview.com/psychics/michele-knight/
When inspecting the large circle, it appears to be the `svg-inline--fa.fa-stack-2x` CSS rule causing this. Disabling both of these rules seems to make it appear correctly.

**Expected behavior**
I expect the stack alignment and sizing to be correct.

**Screenshots**
Current behaviour:
![Screenshot 2021-09-15 at 14 45 29](https://user-images.githubusercontent.com/12139008/133445041-e0808e97-fed0-415a-810a-cfec0ce7ab8e.png)

Expected behaviour:
![Screenshot 2021-09-15 at 14 45 38](https://user-images.githubusercontent.com/12139008/133445093-7ec55344-8f2c-47b4-8bd0-02ce2b11c079.png)

**Version and implementation**
Version: 5.15.4
Browser and version: Google Chrome 93.0.4577.82 (Official Build) (arm64) (Mac OS 11.5.2)

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2021-09-15 14:30
Hi!

Thanks for being part of the Font Awesome Community.

We do not provide support for third-parties. The theme is using both webfont (CSS) and SVG (JS) implementation at the same time. As you can see from the network panel of the browser or in the source code, it loads both

```
https://staging.thepsychicreview.com/wp-content/themes/thepsychicreview/assets/css/fontawesome.min.css?ver=5.8.1
```

and

```
https://staging.thepsychicreview.com/wp-content/themes/thepsychicreview/assets/js/fontawesome.min.js?ver=5.8.1
```

If you can, please pick up the one that best fits your use case, JS and CSS implementation are not complementary. Otherwise, contact the author of the theme to get support

We also have an official WordPress plugin https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/wordpress which helps with conflict detections

Other thoughts

1. `stack` is a feature that for this specific use case would work better for CSS
2. We have an official [fab fa-facebook](https://fontawesome.com/v5.15/icons/facebook?style=brands) icon in a circle
3. With SVG, you can use [power transform](https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms) and [masking](https://fontawesome.com/how-to-use/on-the-web/styling/masking) to achieve uniform appearance and preserve transparency: [demo](https://jsfiddle.net/tagliala/L17f528g/575/)

Hope it helps

Closing here

**Closed by tagliala** 2021-09-15 14:30 UTC

**Comment by leecollings-sb** [comment] 2021-09-15 14:40
Woah, hold on.

Why close this? I've given you proof that it's not loading correctly.

You mention third parties, what are you referring to here? I am the author of the theme, so what are you saying? I shouldn't be using both the CSS and JS inclusions together?

I will take your recommendation of dropping the JS call and using CSS instead if that's what you're saying?

But I think you've knee-jerk closed this ticket without allowing it to go through a proper process (like my reply here - which might require additional info).

**Comment by tagliala** [comment] 2021-09-15 15:07
> I shouldn't be using both the CSS and JS inclusions together?

Correct, they are not complementary. According to your use case you may go for CSS or SVG, but not both together on the same page

Ref: https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/hosting-font-awesome-yourself

> But I think you've knee-jerk closed this ticket without allowing it to go through a proper process (like my reply here - which might require additional info).

Thanks for the feedback, I have an idea to improve this

Feel free to keep commenting even if the issue is closed. And if I've missed something, I will be happy to reopen

> #16526

Will answer there

**Comment by leecollings-sb** [comment] 2021-11-10 16:47
Hi there,

I'd like to come back to this issue because there's still an issue with the alignment of stacked icons in the sense that I'm getting inconsistent results with two different locations of stacked icons on the page.

The URL in question is https://staging.thepsychicreview.com/psychics/michele-knight/. The first instance of the icons is near the top of the page:

![Screenshot 2021-11-10 at 16 43 27](https://user-images.githubusercontent.com/12139008/141155418-7e1881e1-d409-4aa4-ae58-6178c9fa8d08.png)

You can see the white icons are aligned just very slightly underneath the vertical centre of the circle. The next instance is down in the footer:

![Screenshot 2021-11-10 at 16 44 18](https://user-images.githubusercontent.com/12139008/141155564-c71722e7-451f-487b-84d4-eca18273426f.png)

Here the opposite is happening, the white icons are aligned slightly above the vertical centre of the circle.

Is this something that could be explained or investigated? Currently, I don't know why they are appearing like this, but would like to know if possible. I still feel as though there's something not quite right with the current default styling or instructions of use.

**Comment by tagliala** [comment] 2021-11-10 17:01
Hi, yes

The problem is that the CSS implementation may lead to issues with vertical alignment by design, due by 
1. the font [descender](https://en.wikipedia.org/wiki/Descender)
2. How browsers render the font

[I've answered on the other thread](https://github.com/FortAwesome/Font-Awesome/issues/16526#issuecomment-920149193) with an explanation on what's happening and it covers the above cases. Will copy & paste here

> So what you're saying is, if anyone sets the font size of body, your icons are not aligned properly...?

Nope. I'm referring to the `fa-stack` element and perfect vertical alignment of webfonts (especially at small sizes and non multiples of the base font size). As said before, there are things to keep in mind. `font-size` is one of them

Demo: http://jsfiddle.net/tagliala/vbhdn9te/14/

### Retina

![image](https://user-images.githubusercontent.com/556268/133467164-a5c98a7a-4607-40d8-8d4a-67e9eafb92f7.png)

### 1080p

![image](https://user-images.githubusercontent.com/556268/133467232-8ef298c7-d1f5-494a-9936-ac57a9d9f63b.png)


As you can see, according to the font size, the vertical alignment changes. The effect is minimal at 16px and almost non-existent at 32px, but you may notice that 18px does not play well on 1080p displays. Please also keep in mind that OSes have their own font rendering and anti aliasing libraries. Browser may display fonts differently. Font Awesome CSS uses a webfont, so font-size applies to icons

If your use case needs the best rendering results and perfect vertical alignment, especially at small sizes or non-multiples of 16px, you should opt for the SVG framework and ad-hoc transformations.

Example: https://jsfiddle.net/tagliala/L17f528g/581/

### Retina
![image](https://user-images.githubusercontent.com/556268/133467935-51d5c3b0-bbfb-42b9-a82e-178c5c1067bb.png)

### 1080p
![image](https://user-images.githubusercontent.com/556268/133467976-d0f056e3-2733-4436-9d61-847d19e2784c.png)
