### ISSUE TITLE
Apache icon

### ISSUE THREAD

**Issue by dexterrules** [FortAwesome/Font-Awesome#12593] opened 2018-03-13 15:20 UTC
Please get an Apache icon!

**Comment by tagliala** [comment] 2018-03-13 19:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1639, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-13 19:19 UTC
