### ISSUE TITLE
Icon Request: fa-cleaning 

### ISSUE THREAD

**Issue by GaryChen** [FortAwesome/Font-Awesome#5338] opened 2015-01-05 03:07 UTC
I like the awesome icon very much.  My project needs one more icon, could you please take a look?
This is used for indicate the room is cleaning required.

![site view with cleaning icon](https://cloud.githubusercontent.com/assets/440525/5608847/1727cd12-94cb-11e4-8b33-09e8e16a9f2c.png)

**Comment by tagliala** [comment] 2015-01-05 10:55
duplicate of #239  , please +1 that request

closing here

**Closed by tagliala** 2015-01-05 10:55 UTC
