### ISSUE TITLE
Icon Request: fa-researchgate

### ISSUE THREAD

**Issue by eimimue** [FortAwesome/Font-Awesome#9698] opened 2016-08-04 09:04 UTC
I plan to use the researchgate icon for my personal resume on my website.

It could be a monocolor version of the original logo:

![ResearchGate logo](https://lh4.googleusercontent.com/-28pFvL53uvU/AAAAAAAAAAI/AAAAAAAAAcE/eDj2uG7PWKs/s0-c-k-no-ns/photo.jpg)

**Comment by tagliala** [comment] 2016-08-04 09:38
Duplicate of #3634, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-04 09:38 UTC
