### ISSUE TITLE
Icon Request: justice-scales

### ISSUE THREAD

**Issue by cwood28** [FortAwesome/Font-Awesome#2818] opened 2014-01-29 19:12 UTC
Please create a new icon that represents the scales of justice.  Example attached.
![image](https://f.cloud.github.com/assets/6537887/2033187/4d68a2d4-8919-11e3-92ac-23855170b7f0.png)

**Comment by AntoVasanth** [comment] 2015-01-08 11:04
+1

**Comment by henleywc** [comment] 2015-01-15 08:19
+1

**Comment by khoshrou** [comment] 2015-01-17 12:13
+1 but give it a better icon coz this is more related to law concepts

**Comment by happyloha** [comment] 2015-01-28 22:28
+1

**Comment by mm-habibi** [comment] 2015-02-05 05:13
+1

**Comment by noedlm** [comment] 2015-02-20 22:32
+1

**Comment by nd2s** [comment] 2015-05-17 12:56
+1

**Comment by rwtrwt** [comment] 2015-06-02 16:15
+1

The mobile website CMS "dudamobile" has an icon for the scales named justice. I wish I could figure a way to add it to my local font awesome folder

source code shows the following div controlled by font-pack.css
HTML
<div class="navIcon dm-icon-justice hasFontIcon" id="dm_navGroup010101882910icon" style=""
::before
</div>

CSS
.dm-icon-justice:before {
  content: "\e6ed"

you can look at my mobile site http://m.danielstaylor.com to see the icon in action (it works in desktop browsers as well)

If anyone could help thanks in advance

**Comment by EddieFromFA** [comment] 2015-06-02 23:52
+1

**Comment by ksleyko** [comment] 2015-06-15 14:43
Isn't this a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/276?

**Comment by tagliala** [comment] 2015-06-15 14:53
@ksleyko thanks

yes it is, but I was thinking that the other one was a weight scale. :\

I should merge +1s

**Comment by ymoreiratiti** [comment] 2015-06-23 13:21
+1

**Comment by tagliala** [comment] 2015-06-23 14:42
closing here as a duplicate of #276

**Closed by tagliala** 2015-06-23 14:42 UTC
Labels: new icon, web application icons

**Comment by alexbreems** [comment] 2015-06-23 15:18
+1

**Comment by tagliala** [comment] 2015-06-23 15:25
locking here
