### ISSUE TITLE
Icon Request: fa-kangaroo

### ISSUE THREAD

**Issue by ThatTonybo** [FortAwesome/Font-Awesome#14943] opened 2019-04-25 04:42 UTC
### What can it be used for?
For things that represent Australia, or animals, or both.

### Example image (optional)
![image](https://user-images.githubusercontent.com/28176227/56710165-249c6600-6768-11e9-80ba-35591178118f.png)

### Icon request checklist
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Just an additional note, I made this because the older one was totally ignored and never added, and it'd be a really useful icon.

**Comment by tagliala** [comment] 2019-04-25 07:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10150, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-25 07:33 UTC
