### ISSUE TITLE
icon request: place of worship

### ISSUE THREAD

**Issue by Dsign** [FortAwesome/Font-Awesome#9838] opened 2016-08-30 17:47 UTC
We would like to have an icon to depict a place of worship but we don't want it to be a church due to sensitivities to other religions. 

something like this (without a cross could work):

![worship](https://cloud.githubusercontent.com/assets/20301719/18100257/2fade010-6eb8-11e6-953f-cadba2b319f3.jpg)

**Comment by ijakic** [comment] 2016-09-06 18:48
And something with recognition of the church (cathedral) as religious symbols would be nice

**Comment by GermanKiwi** [comment] 2016-10-30 16:55
FYI, we already have an open issue for a church icon here: #2088

**Comment by tagliala** [comment] 2016-10-30 17:13
Quoting from the first post:

> We would like to have an icon to depict a place of worship but we don't want it to be a church due to sensitivities to other religions.

Due to sensitivity of the matter, I cannot consider this a duplicate of #2088

**Comment by GermanKiwi** [comment] 2016-10-30 17:17
I agree - I wasn't meaning to suggest this request is a dup of #2088, as the OP mentioned that "we don't want it to be a church". I was replying to @ijakic's post as it sounded like he/she was asking for a church-like icon. I should have made that more clear. :)

**Comment by tagliala** [comment] 2016-10-30 18:35
@GermanKiwi sorry, got it 👍 

@ijakic please +1 #2088 for a christian church

**Comment by Mediaversal** [comment] 2017-02-02 20:30
Yes, a place of worship, not a Christian Crossed Church would be good..

**Comment by sensibleworld** [comment] 2018-08-29 17:46
https://fontawesome.com/icons/place-of-worship?style=solid

**Closed by sensibleworld** 2018-08-29 17:46 UTC
Labels: new icon, released, web application icons
