### ISSUE TITLE
Icon request: icon-realtor

### ISSUE THREAD

**Issue by seanford** [FortAwesome/Font-Awesome#13027] opened 2018-05-03 18:37 UTC
### What can it be used for?

Standard REALTOR logo icon.

### Example image (optional)

https://auroraassociationofrealtors.com/wp-content/uploads/realtor-logo-275x300.png

### Icon request checklist

- [ X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X ] I have included at least one example image if it could be helpful (optional)
- [ X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-05-03 19:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4630, please add a 👍  reaction to that request.

> I have searched for existing issues and to the best of my knowledge this is not a duplicate

No problem 👍 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-03 19:09 UTC
