### ISSUE TITLE
Icon request: fa-untappd

### ISSUE THREAD

**Issue by LotteNoteboom** [FortAwesome/Font-Awesome#9981] opened 2016-09-29 16:39 UTC
I'd like to use the untappd icon in the same way as the facebook and/or twitter logo. It is like a social media icon. For more info about untappd: https://untappd.com/home

For some inspiration:
![image](https://cloud.githubusercontent.com/assets/8779650/18963113/df209f6a-8673-11e6-9ab5-c6a34cb771d9.png)
![image](https://cloud.githubusercontent.com/assets/8779650/18963116/e60f52f8-8673-11e6-8a39-74117c5c9bca.png)
![image](https://cloud.githubusercontent.com/assets/8779650/18963127/f31dbe58-8673-11e6-908f-b7b8e9237c68.png)

**Comment by tagliala** [comment] 2016-09-30 08:57
Duplicate of #1971 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 08:57 UTC

**Comment by LotteNoteboom** [comment] 2016-09-30 10:20
My apologies! I did multiple searches but was unable to find the request.
Thanks for your reply.

Op vr 30 sep. 2016 10:58 schreef Geremia Taglialatela <
notifications@github.com>:
