### ISSUE TITLE
Icon Request: fa-video-camera-slash

### ISSUE THREAD

**Issue by benjamin-b** [FortAwesome/Font-Awesome#6884] opened 2015-07-06 14:52 UTC
The video camera icon with a slash as we have in microphone-slah would be helpful to sue in a video call kinda of application. Thanks

**Comment by tagliala** [comment] 2015-07-07 14:12
duplicate of #3765, please +1 that request

closing here

refers to #1181

**Closed by tagliala** 2015-07-07 14:12 UTC
