### ISSUE TITLE
Icon request: fa-skull and cross bones

### ISSUE THREAD

**Issue by ckisker** [FortAwesome/Font-Awesome#6813] opened 2015-06-23 17:53 UTC
I would love to have the skull and cross bones icon to represent a section of our site that deals with chemical cleaning and spilled material clean up.  Thank you!

![220px-skull_and_crossbones](https://cloud.githubusercontent.com/assets/13021444/8313177/2dd832fe-19af-11e5-8267-db1756174709.png)

**Comment by kwaaui** [comment] 2015-06-24 02:44
+1
It would be a nice pirate icon.
single fa-skull and fa-bone would be nice too

**Comment by tagliala** [comment] 2015-06-24 21:41
duplicate of #918, please +1 that request

closing here

**Closed by tagliala** 2015-06-24 21:41 UTC
