### ISSUE TITLE
Icon request: tailless arrow versions of arrow-to series of icons

### ISSUE THREAD

**Issue by terryschwarz** [FortAwesome/Font-Awesome#15172] opened 2019-06-18 14:06 UTC
**What can it be used for?**
Primarily as a more modern looking version goto last/first/top/bottom icons. 

Would suggest names such as arrow-to-right-alt

**Example image (optional)**
Something like ...  
![image](https://user-images.githubusercontent.com/47600614/59691122-87324100-91b0-11e9-9fdc-83f5019b68f7.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment] 2024-07-11 18:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/16660)

**Closed by sensibleworld** 2024-07-11 18:37 UTC
Labels: new icon, arrows (category), Duplicate
