### ISSUE TITLE
Icon Request: fa-home-o

### ISSUE THREAD

**Issue by Chovanec** [FortAwesome/Font-Awesome#3481] opened 2014-05-20 09:39 UTC
I think outlined home icon would be great.

**Comment by nicolasnoakes** [comment] 2015-09-23 09:51
+1 please. The solid existing solid home icon is too heavy compared when used in conjunction with some of the other icons e.g. files-o

**Comment by ShaunR** [comment] 2015-11-03 21:10
+1

**Comment by tagliala** [comment] 2015-11-03 23:21
Closing here as a duplicate of #2210

**Closed by tagliala** 2015-11-03 23:21 UTC
Labels: new icon, web application icons
