### ISSUE TITLE
Icon request: fa-fingerprint

### ISSUE THREAD

**Issue by nzcoward** [FortAwesome/Font-Awesome#10446] opened 2016-12-29 15:50 UTC
Heya, not sure if there is a request for this anywhere, but I would love a finger print icon.

The noun project has plenty of examples, but I like the idea of something similar to the Google Material finger print @ https://material.io/guidelines/patterns/fingerprint.html#fingerprint-fingerprint-icon:

![image](https://cloud.githubusercontent.com/assets/10462479/21547524/88b588b8-cdde-11e6-9106-ef22a1e3af9d.png)

Thanks!

**Comment by tagliala** [comment] 2016-12-29 17:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4431 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-29 17:48 UTC
