### ISSUE TITLE
Icon request: icon-layout

### ISSUE THREAD

**Issue by siangboon** [FortAwesome/Font-Awesome#13527] opened 2018-07-11 09:59 UTC
### What can it be used for?

for admin page, indicate website layout

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-11 10:21
> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Could you please provide a single color example?

**Comment by tagliala** [comment] 2018-07-11 10:48
Duplicate of #6100, please 👍 that request

**Closed by tagliala** 2018-07-11 10:48 UTC
Labels: waiting for feedback
