### ISSUE TITLE
Icon request: fa-disc

### ISSUE THREAD

**Issue by Entwanderer** [FortAwesome/Font-Awesome#7531] opened 2015-09-24 17:01 UTC
I request just a plain data disc icon, usable for CD/DVD/Blue-Ray.

Mainly consisting of 3 circles, may including some effect.

**Comment by caduvieira** [comment] 2015-09-24 17:07
dupe of https://github.com/FortAwesome/Font-Awesome/issues/702

**Closed** 2015-09-24 17:11 UTC
