### ISSUE TITLE
Icon request: icon-cookie

### ISSUE THREAD

**Issue by reedvoid** [FortAwesome/Font-Awesome#7611] opened 2015-10-05 14:27 UTC
Please consider adding an icon that's the representation of a cookie. 

I am developing a snack site that needs a snack-related icon to represent a section of the site that's a collection of snacks the user has eaten before. The closest thing I could find right now in the font-awesome 4.4 library is a birthday cake, which isn't nearly as great at conveying the concept of "snack" as a cookie would. 

In addition, the cookie icon could also conceivably be used to represent website cookies as another use case. 

The cookie should probably have some kind of a crumbling look to it, since a simple circle or square won't look like a cookie. Maybe it should also have some tiny holes in it like saltines so it looks more like a cookie. 

I've attached an image of something pretty close to what I think would be appropriate. 

Many thanks for your consideration!! 

![200858011791085152](https://cloud.githubusercontent.com/assets/14979636/10282958/059bb6b4-6bb0-11e5-80fd-2f043ae14c55.jpg)

**Comment by tagliala** [comment] 2015-10-05 20:36
duplicate of #2845 , please +1 that request and share your thoughts there

closing here

**Closed by tagliala** 2015-10-05 20:36 UTC
