### ISSUE TITLE
Icon request: lingerie bra-panty

### ISSUE THREAD

**Issue by STRANGEPOOL** [FortAwesome/Font-Awesome#17410] opened 2020-11-17 15:37 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-11-17 17:00
Hi!

Thanks for being part of the Font Awesome Community.

I know that they are different and they look different, but we also need to take in account the rendering with single color at small pixel size

Can this be considered a duplicate of #4964 (bikini 👙 emoji)

If not, do you have a single color example that may work at small icon size (16px)?

**Comment by aethior** [comment] 2022-03-18 22:28
> Can this be considered a duplicate of #4964 (bikini 👙 emoji)

I think you can close here.

**Comment by tagliala** [comment] 2022-03-19 09:24
Closing here for the moment

**Closed by tagliala** 2022-03-19 09:24 UTC
