### ISSUE TITLE
Icon request - dog-tag

### ISSUE THREAD

**Issue by swanhaven** [FortAwesome/Font-Awesome#15788] opened 2019-11-08 15:03 UTC
It's veterans day!  Well close enough, I wanted to make a discount for veterans and I couldn't find a user icon for veterans in any shape or form.  I would love to see an user icon for those who have served

**What can it be used for?**
Discounts or special accounts for veterans or to show our support!

**Example image (optional)**
I don't have an image but I do have some ideas.  A user with a soldiers helmet, class A uniform cap, or wearing fatigues (camouflage).  A set for each branch of the military would be great.  Another option would be a set of id tags (dog tags) connected by a chain.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X ] I have included at least one example image if it could be helpful (optional)
- [ X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-11-09 19:59
Hi!

Thanks for being part of the Font Awesome Community.

Soldier helmet is a duplicate of #3657, please +1 that reuqest

I'm going to leave this open as dog-tag

**Comment by sensibleworld** [comment] 2024-07-11 18:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 18:23 UTC
Labels: new icon, web application icons (legacy category), Declined
