### ISSUE TITLE
Icon Request: fa-pandora

### ISSUE THREAD

**Issue by samirrayani** [FortAwesome/Font-Awesome#12101] opened 2018-01-15 09:19 UTC
![pandora_logo_black](https://user-images.githubusercontent.com/179782/34935252-39ce9330-f9ab-11e7-8cc1-488f854e7e32.png)

**Comment by tagliala** [comment] 2018-01-15 10:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of ##5676, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-15 10:38 UTC
