### ISSUE TITLE
Icon request: icon-handshake

### ISSUE THREAD

**Issue by juniorb** [FortAwesome/Font-Awesome#878] opened 2013-03-24 07:56 UTC
[Google image example](http://www.google.com/imgres?um=1&hl=en&sa=N&biw=1440&bih=779&tbm=isch&tbnid=UJcCBFnEni-UeM:&imgrefurl=http://allthingsd.com/20120520/yahoo-and-alibaba-officially-shake-on-7-billion-stock-sale-deal/interview-handshake/&docid=C2caiYHpUW3AaM&imgurl=http://allthingsd.com/files/2012/05/interview-handshake.jpeg&w=900&h=803&ei=NbBOUYP2EI-g8QTdlwE&zoom=1&ved=1t:3588,r:8,s:0,i:188)

Useful for:
- Agreement
- Interview
- Service (#658)

**Comment by BarisJKaraali** [comment] 2015-01-03 18:28
+1

**Comment by seinecle** [comment] 2015-01-06 10:20
+1

**Comment by dangnelson** [comment] 2015-01-13 15:52
+1

**Comment by c00lz3r0** [comment] 2015-01-19 19:10
+1

**Comment by peterbirlem** [comment] 2015-01-19 23:48
+1 Would love to get this handshake icon back.  Wondering what happened to it.  Any ideas when this might be re-implememted?  Thanks in advance for any info.

**Comment by johnjarrard** [comment] 2015-01-22 16:13
+1

**Comment by gmarziou** [comment] 2015-01-23 09:36
+1

**Comment by guybanister** [comment] 2015-01-26 21:02
+1

**Comment by londondrifting** [comment] 2015-01-29 09:22
+1

**Comment by ReessKennedy** [comment] 2015-02-03 22:55
+1

**Comment by shmuel613** [comment] 2015-02-05 10:19
+1

**Comment by tahmina8765** [comment] 2015-02-09 17:48
+1

**Comment by troygnichols** [comment] 2015-02-13 17:55
:+1:

**Comment by troygnichols** [comment] 2015-02-13 17:55
+1

**Comment by borayilmaz** [comment] 2015-02-27 17:07
+1

**Comment by jeancarlos** [comment] 2015-03-02 12:29
+1

**Comment by vottens** [comment] 2015-03-03 10:09
+1

**Comment by Maado** [comment] 2015-03-10 08:00
+1

**Comment by joaorocha** [comment] 2015-03-10 12:36
+1

**Comment by kevinyuliawan** [comment] 2015-03-11 02:23
+1

**Comment by olets** [comment] 2015-03-11 13:39
+1

**Comment by bgarrison25** [comment] 2015-03-11 17:39
+1

**Comment by G-Driver** [comment] 2015-03-11 20:57
+1

**Comment by timsly** [comment] 2015-03-12 09:00
+1

**Comment by PedroHLC** [comment] 2015-03-13 19:41
+1

**Comment by gbergere** [comment] 2015-03-15 18:48
+1

**Comment by p1n5u** [comment] 2015-03-16 10:25
+1
does anyone know when it will be added?

**Comment by tagliala** [comment] 2015-03-16 10:46
@p1n5u this icon is one of the most requested in the "web application" category.

It **should** be added in the next release (5.0.0) but I don't know when it will be released

If you need this in a short while, my advise is to consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by p1n5u** [comment] 2015-03-16 10:51
@tagliala thanks for this answer :smiley:

**Comment by MMokhtari** [comment] 2015-03-16 20:20
+1

**Comment by dngunraj** [comment] 2015-03-27 13:16
+1

**Comment by saguiitay** [comment] 2015-03-28 18:16
+1

**Comment by 10for2** [comment] 2015-04-02 17:54
+1

**Comment by flippya** [comment] 2015-04-02 21:39
+1

**Comment by sbrichards** [comment] 2015-04-03 00:42
+1

**Comment by agh1** [comment] 2015-04-10 21:48
+1

**Comment by nshahpazov** [comment] 2015-04-14 14:40
+1

**Comment by bjornte** [comment] 2015-04-17 11:58
+1

**Comment by GeekTantra** [comment] 2015-04-24 08:09
+1

**Comment by GKRavabe** [comment] 2015-05-03 11:46
+1

**Comment by teknovision** [comment] 2015-05-04 17:49
+1

**Comment by inspiredunease** [comment] 2015-05-07 09:34
+1

**Comment by LoopKarma** [comment] 2015-05-22 12:41
+1

**Comment by alessandropellegrini** [comment] 2015-05-24 18:22
+1 Definitely needed

**Comment by liptonbeer** [comment] 2015-05-26 08:51
+1 very needed

**Comment by jakubstrama** [comment] 2015-06-03 12:57
:+1:

**Comment by KarthikDev81** [comment] 2015-06-07 09:42
+1

**Comment by thisispiers** [comment] 2015-06-16 14:47
+1 this has so much support. when is it coming?

**Comment by cheekygit** [comment] 2015-06-24 22:25
+1

**Comment by lichtamberg** [comment] 2015-07-01 08:41
+1

**Comment by user453584** [comment] 2015-07-06 01:04
+:100: — It has been over two years since this issue was opened, and this feature has been independently requested many, many times (even in multiple separate issues).

What on earth is the hold up?

**Comment by rothfuchs-bs** [comment] 2015-07-07 16:29
+1

**Comment by gabthefencer** [comment] 2015-07-12 01:17
+1

**Comment by stenwessel** [comment] 2015-07-12 11:12
+1

**Comment by lpld** [comment] 2015-07-14 08:18
+1

**Comment by Aksyonenko** [comment] 2015-07-14 08:20
+1

**Comment by Taminoful** [comment] 2015-07-14 14:12
+1

**Comment by Fusix** [comment] 2015-07-15 17:49
+1

**Comment by meggle** [comment] 2015-07-16 15:23
+1

**Comment by lebiru** [comment] 2015-07-16 20:37
+1

**Comment by redayoub** [comment] 2015-07-20 22:13
+1

**Comment by tuxy** [comment] 2015-07-23 00:29
+1 fa-handshake

![Handshake](http://i.imgur.com/ikItxw1.png)
Source: https://www.iconfinder.com/icons/473798/agreement_business_contract_deal_greeting_handshake_partnership_icon#size=128

**Comment by dwcdev** [comment] 2015-07-24 20:36
+1

**Comment by elubin** [comment] 2015-07-31 13:45
+1 in version 4.4.0 or above

**Comment by uducharm** [comment] 2015-08-01 17:48
+1

**Comment by JefSilvaNH** [comment] 2015-08-04 02:13
+1

**Comment by grotonic** [comment] 2015-08-04 18:38
+1

**Comment by oxeno** [comment] 2015-08-05 13:03
+1

**Comment by nshahpazov** [comment] 2015-08-05 15:34
+1

**Comment by vigneshv59** [comment] 2015-08-06 21:49
+1

**Comment by steamsynthetic** [comment] 2015-08-07 17:05
+1

**Comment by dshirazi** [comment] 2015-08-08 13:17
+1

**Comment by isabellerichard** [comment] 2015-08-17 09:48
+1

**Comment by wearelogik** [comment] 2015-08-17 10:23
+1

**Comment by ServicePal** [comment] 2015-08-18 01:20
+1

**Comment by TheWaWaR** [comment] 2015-08-18 08:24
+1

**Comment by migig** [comment] 2015-08-18 12:13
+2

**Comment by G-Driver** [comment] 2015-08-28 11:55
+1

**Comment by Skwerl** [comment] 2015-08-31 09:26
+1

**Comment by joksin** [comment] 2015-09-04 13:36
+1

**Comment by renanCaraujo** [comment] 2015-09-04 17:49
+1

**Comment by jflavan** [comment] 2015-09-04 21:43
+1

**Comment by Sherif-Ahmed** [comment] 2015-09-07 09:01
+1

**Comment by valioDOTch** [comment] 2015-09-07 09:21
+1

**Comment by alejandro-fiore** [comment] 2015-09-08 14:40
+1

**Comment by nzgrover** [comment] 2015-09-09 20:50
+1

**Comment by herrherrmann** [comment] 2015-09-13 14:00
+1

**Comment by vonrussel** [comment] 2015-09-14 01:43
+1

**Comment by acazsouza** [comment] 2015-09-17 17:32
+1

**Comment by anirudh14** [comment] 2015-09-23 09:41
+1

**Comment by serchavalos** [comment] 2015-09-23 10:53
+1

**Comment by nicklaros** [comment] 2015-09-26 14:44
+1

**Comment by meliborn** [comment] 2015-09-28 22:25
since 2013...are you kidding...+1

**Comment by otherholli** [comment] 2015-09-30 13:37
+1

**Comment by TimHolahan** [comment] 2015-09-30 19:59
+1

**Comment by bartocc** [comment] 2015-10-01 14:20
+1

**Comment by myriacl** [comment] 2015-10-05 22:46
+1

**Comment by Subtletree** [comment] 2015-10-12 23:02
+1

**Comment by croconoster** [comment] 2015-10-12 23:19
+1

**Comment by FrBillyD** [comment] 2015-10-13 12:25
:+1:

**Comment by scasic** [comment] 2015-10-13 21:28
+1

**Comment by NeoRyu777** [comment] 2015-10-13 21:47
+1

**Comment by 360fun** [comment] 2015-10-16 11:02
we have 2 icons for "pied-piper" and any handshake?!? O___o that's crazy! come on guys...
**+1**

**Comment by PeterShaggyNoble** [comment] 2015-10-16 16:50
+1

**Comment by steffenvogdrup** [comment] 2015-10-27 11:55
+1

**Comment by ashelest** [comment] 2015-11-05 08:32
+1

**Comment by tchoulihan** [comment] 2015-11-13 15:46
+1

**Comment by leojh** [comment] 2015-11-13 19:11
+1

**Comment by rotherfuchs** [comment] 2015-11-15 16:04
+1 ..

**Comment by wearelogik** [comment] 2015-11-15 16:09
Unsubscribing from this! It's been 3 years, time to find an alternative solution for all my projects.

**Comment by SteelBlue** [comment] 2015-11-17 20:20
+1

**Comment by KatherineGShaw** [comment] 2015-11-20 18:29
+1

**Comment by Zeitwaechter** [comment] 2015-11-21 20:42
+1

Will be using an acceptable SVG as temporary substitude though - as it seems that there is no development in this.

**Comment by valioDOTch** [comment] 2015-11-23 14:46
@davegandy Could you elaborate why this was not included so far?

**Comment by krishnasrikanth** [comment] 2015-11-27 06:59
+1

**Comment by MVcodeartbr** [comment] 2015-11-27 15:12
+1

**Comment by chalda-pnuzig** [comment] 2015-12-03 13:49
+1

**Comment by rokuehne** [comment] 2015-12-04 10:58
+1

**Comment by safetyservices** [comment] 2015-12-08 12:09
+1

**Comment by mst80** [comment] 2015-12-09 09:47
+1 Would be nice to have it in solid and outlined like the thumbs icons.

![handshake](https://cloud.githubusercontent.com/assets/16221476/11681934/3975b0b8-9e62-11e5-845c-cbe590e8fa41.png)

**Comment by coclav** [comment] 2015-12-12 13:06
+1

**Comment by dhewer** [comment] 2015-12-15 16:19
+1

**Comment by cblaze22** [comment] 2015-12-17 14:05
+ 1

**Comment by jorisvanw** [comment] 2015-12-18 10:14
+1

**Comment by nicholas-evans** [comment] 2015-12-29 22:37
+1

**Comment by irman** [comment] 2016-01-05 02:30
+3 years

**Comment by G-Driver** [comment] 2016-01-05 15:22
+1

**Comment by mariocatch** [comment] 2016-01-07 13:35
+1

This was confirmed by @davegandy almost 3 years ago. Is this still on the radar @davegandy ?

**Comment by CarlosHAraujo** [comment] 2016-01-08 14:30
+1

**Comment by Kalizo** [comment] 2016-01-13 10:37
+1

**Comment by monika-aashe** [comment] 2016-01-13 19:26
+1

**Comment by devnomad** [comment] 2016-01-13 21:56
+1, @davegandy could you let us know your plans about this one? Thanks!

**Comment by rjcristy** [comment] 2016-01-19 12:44
Any updates? Pretty please..

**Comment by pinkchocobo** [comment] 2016-01-19 20:01
+1

**Comment by atomicframeworks** [comment] 2016-01-19 20:06
:+1:

**Comment by ajbates93** [comment] 2016-01-20 11:01
+1

**Comment by ilianiv** [comment] 2016-01-21 07:09
unsubscribing :disappointed:

**Comment by ralexrdz** [comment] 2016-01-21 19:03
+1

**Comment by sbhaigh** [comment] 2016-01-21 19:21
I'm assuming this is now a dead project.

**Comment by G-Driver** [comment] 2016-01-22 08:07
@sbhaigh no just ceep calm :+1:

**Comment by renanCaraujo** [comment] 2016-01-22 12:38
@sbhaigh yes, it is

**Comment by JFachetti** [comment] 2016-01-23 13:34
+1

**Comment by arturmuhamediev** [comment] 2016-01-25 12:55
+1

**Comment by dw2** [comment] 2016-01-26 19:47
+1 <3

**Comment by mgralikowski** [comment] 2016-02-02 15:05
+1

**Comment by DelBianco** [comment] 2016-02-04 19:52
+1

**Comment by himanshu-u-crest** [comment] 2016-02-09 07:19
+1 
Its better to have it.

**Comment by Vioner** [comment] 2016-02-11 11:14
+1 Cmon guys, add this finally! This issue is almost 3 years old and has tons of +1s...

**Comment by renanCaraujo** [comment] 2016-02-11 11:48
Unsubscribing, this is dead!

**Comment by AndrewBucklin** [comment] 2016-02-14 15:27
+1

**Comment by fariasvp** [comment] 2016-02-16 18:27
+1

**Comment by edinchev** [comment] 2016-02-17 14:26
+1

**Comment by vclteam** [comment] 2016-02-18 18:04
+1

**Comment by jongravois** [comment] 2016-02-23 01:05
+1

**Comment by heyrm** [comment] 2016-02-23 15:42
+1

**Comment by luukhartsema** [comment] 2016-02-26 15:50
Hey guys totally agree +1! I designed one myself now that I'd like to share. 

https://wearespindle.com/articles/font-awesome-would-be-truly-awesome-with-a-handshake-icon

**Comment by clkr** [comment] 2016-02-26 16:39
+1

**Comment by mvletter** [comment] 2016-02-26 17:21
Nice work @luukhartsema! I love the design and the facts that's open source!

**Comment by mgralikowski** [comment] 2016-02-26 20:52
How add this manually to FA (as css class)?

**Comment by luukhartsema** [comment] 2016-02-27 08:50
I use [icomoon](https://icomoon.io/app/) to create my own custom icon font. It's really easy but let me know if you need more help.

**Comment by hectao** [comment] 2016-03-05 03:26
+1

**Comment by revof11** [comment] 2016-03-05 20:48
+1

**Comment by mcleenders** [comment] 2016-03-07 12:49
Love the design @luukhartsema made. Please add it!
https://wearespindle.com/articles/font-awesome-would-be-truly-awesome-with-a-handshake-icon

**Comment by choppnutts** [comment] 2016-03-07 17:22
+1, please make this happen.

**Comment by sara-mansouri** [comment] 2016-03-07 23:43
+1

**Comment by melino** [comment] 2016-03-12 22:19
+1

**Comment by onrea** [comment] 2016-03-16 09:07
+1

![handshaking](https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/handshake.png)

**Comment by fisruk** [comment] 2016-03-16 13:52
+1

**Comment by aslamnaik** [comment] 2016-03-24 04:18
+1

**Comment by hpvd** [comment] 2016-03-24 14:57
+1

**Comment by dlichten** [comment] 2016-03-29 01:32
+1

**Comment by felgharb** [comment] 2016-04-01 09:57
+1

**Comment by nofxx** [comment] 2016-04-02 05:06
+1 ... same semantics... "agreement"

**Comment by vclteam** [comment] 2016-04-05 16:00
+1

**Comment by Startouf** [comment] 2016-04-10 17:31
+1, guys don't forget to directly upvote the first post, now that it's supported by github.

**Comment by kpingel** [comment] 2016-04-11 13:03
👍

**Comment by lucianomarqueto** [comment] 2016-04-19 17:09
+1

**Comment by vitoravale** [comment] 2016-04-19 21:21
+1

**Comment by semanticdreamer** [comment] 2016-04-20 07:49
+1

**Comment by My1** [comment] 2016-04-22 08:53
is this a bad joke?
a lot of weird brands that are close to unknown are implemented here quickly and issues with more than hundred +1 posts (firefox stops counting from 100, chrome shows 211) doesnt get implemented for MORE THAN THREE YEARS?
this is just weird.
anway +1

**Comment by ikourfaln** [comment] 2016-04-26 09:53
unbelievable !!!!!! Im looking for the icon, but when I find this issue - 3 years old and no update - I let it down !!
anyway +1

**Comment by mzweh** [comment] 2016-04-26 10:02
+1

**Comment by Cobra86** [comment] 2016-04-26 10:33
+1

**Comment by ikourfaln** [comment] 2016-04-26 16:25
Guys, as you can see this issue is affected to 5.0.0 milestone !!
So it will not be available until Font Awesome version 5.0 !! Who knows, it will be out after 3 or 5 years.

I dont understand !!

**Comment by petyappetrov** [comment] 2016-04-28 03:36
+1

**Comment by My1** [comment] 2016-04-28 07:10
nobody says that they have to go through 4.7,4.8 and 4.9 to get to 5.0 they COULD make 5.0 the next version (according to some posts in the issues it was seemingly planned often enough to be the "next" release)

**Comment by arnoldbm** [comment] 2016-04-28 17:26
+1.

**Comment by cbezares** [comment] 2016-05-06 15:12
+1

**Comment by matheusjardimb** [comment] 2016-05-09 16:58
+1

**Comment by lenamtl** [comment] 2016-05-19 15:40
+1

**Comment by kasperhartwich** [comment] 2016-05-27 07:56
+1

**Comment by argonautical** [comment] 2016-05-28 14:52
+1

**Comment by Siada-Apius** [comment] 2016-05-30 08:53
+1

**Comment by pctin** [comment] 2016-05-31 09:14
+1

**Comment by wini-ash** [comment] 2016-06-03 20:50
+1

**Comment by VeeK727** [comment] 2016-06-06 07:33
+1

**Comment by YelloW22** [comment] 2016-06-15 15:45
+1

**Comment by stimcon-dev** [comment] 2016-06-16 10:55
+1

**Comment by odupont** [comment] 2016-06-21 08:37
+1

**Comment by yosemai** [comment] 2016-06-21 08:46
+1

**Comment by georgetrad** [comment] 2016-06-26 08:32
+1

**Comment by Robys915** [comment] 2016-06-27 07:18
+1

**Comment by loanlaux** [comment] 2016-06-28 09:57
More than three years later, still nothing. Wtf. Didn't take that much time to integrate the Pied Piper logo, which is known to be used by sooooo many people in their projects!

**Comment by adhorrig** [comment] 2016-07-08 11:22
+1

**Comment by ImJustToNy** [comment] 2016-07-09 11:38
Bump

**Comment by YoussF** [comment] 2016-07-12 15:02
+1

**Comment by matheusjardimb** [comment] 2016-07-12 15:06
It's been a looong time github is alerting me about people +1ing this issue and nothing happens. 
I wonder if we'll need to wait more 3 years to get this solved.

**Comment by andr3y1p** [comment] 2016-07-22 20:58
i need it! +1

**Comment by Black-Star** [comment] 2016-07-24 06:39
SVG code for handshake
http://pastebin.com/sRYnFcke

**Comment by alsoknownasdrew** [comment] 2016-07-26 07:42
+1

**Comment by mirorac** [comment] 2016-07-26 13:20
big +1

**Comment by VizuaaLOG** [comment] 2016-08-04 14:25
+1

**Comment by veuncent** [comment] 2016-08-05 13:42
+1

**Comment by stanica** [comment] 2016-08-05 14:46
+1

**Comment by tryton-vanmeer** [comment] 2016-08-05 16:06
+1

**Comment by destyl12** [comment] 2016-08-16 08:24
+1

**Comment by meinharrd** [comment] 2016-08-16 14:25
+1

**Comment by igordelorenzi** [comment] 2016-08-16 18:00
+1

**Comment by fusion27** [comment] 2016-08-17 12:22
👍

**Comment by salexkidd** [comment] 2016-08-22 08:11
+1

**Comment by pyaehein** [comment] 2016-08-22 08:39
+1

**Comment by TomHeatwole** [comment] 2016-08-24 04:28
+ 1

**Comment by TomHeatwole** [comment] 2016-08-24 04:28
+1

**Comment by kamrava** [comment] 2016-08-25 07:26
+1

**Comment by aifrim** [comment] 2016-08-25 14:19
+1

**Comment by MazeFX** [comment] 2016-08-29 06:41
+1

**Comment by alexjeen** [comment] 2016-09-01 19:03
+1

**Comment by JefMari** [comment] 2016-09-02 07:22
+1

**Comment by markmeikle** [comment] 2016-09-12 16:27
+1

**Comment by BernabeFelix** [comment] 2016-09-14 15:54
+1

**Comment by fatmuemoo** [comment] 2016-09-14 20:37
+1

**Comment by jabarnes** [comment] 2016-09-14 21:22
+1

**Comment by eX00r** [comment] 2016-09-18 17:27
+1

**Comment by JustinMcDonald** [comment] 2016-09-21 17:16
+1

**Comment by Marvelxy** [comment] 2016-09-21 22:00
+1

**Comment by responsive-muse** [comment] 2016-09-25 14:12
:+1:   +1, still waiting :(

**Comment by Poofy83** [comment] 2016-09-28 08:30
What's taking so long? +1

**Comment by mikewagz** [comment] 2016-09-28 21:21
+1

**Comment by darkonarancic** [comment] 2016-09-30 12:48
+1

**Comment by brunoew** [comment] 2016-10-01 06:44
+1

**Comment by KennedyIhe** [comment] 2016-10-02 17:45
+1

**Comment by davegandy** [comment] 2016-10-03 20:11
Honestly, I avoided this one for so long because I knew it was going to be really tricky. It's been checked into the 4.7.0-wip branch and will be a part of the release:

<img width="991" alt="screenshot 2016-10-03 15 45 59" src="https://cloud.githubusercontent.com/assets/1076721/19052229/0527b4c4-8984-11e6-8535-ece5a36ae345.png">

Huge thanks to Linode for sponsoring the top 5 most requested icons being added to Font Awesome!

**Closed** 2016-10-03 20:12 UTC
Labels: new icon, web application icons

**Comment by elubin** [comment] 2016-10-03 21:50
THANK YOU Linode!!

**Comment by fusion27** [comment] 2016-10-04 14:37
Thank you Linode!

**Comment by frizadiga** [comment] 2016-12-12 10:48
+1

**Comment by My1** [comment] 2016-12-12 12:22
I have no Idea who Linode is but thanks.

**Comment by igordelorenzi** [comment] 2016-12-13 16:14
Thank you Linode!!

**Comment by inetvirtual** [comment] 2018-04-10 09:37
Thanks Linode!
