### ISSUE TITLE
Icon Request: fa-idcard

### ISSUE THREAD

**Issue by andrewchernow** [FortAwesome/Font-Awesome#7167] opened 2015-08-07 15:05 UTC
A generic ID card is something I need for a new service. This service distributes ID cards to its members; via regular mail. An example would be a driver's  license, university ID or membership card as in my case. These normally have a photo on the card so it would be "awesome" if the icon reflected that somehow. Right now, I am using the newspaper-o icon, which is a stretch.

I can barely draw stick figures so I am the wrong person to provide an example image. Just look at your driver's license, employee ID card, etc...

Thank you so much for font awesome! Keep up the good work. Version 4.4 has some great additions.

Thank you,
Andrew

**Comment by tagliala** [comment] 2015-08-07 15:09
duplicate of #825 , please +1 that request

closing here

**Closed by tagliala** 2015-08-07 15:09 UTC
