### ISSUE TITLE
Icon Request : Icon-Wallet 

### ISSUE THREAD

**Issue by Babien** [FortAwesome/Font-Awesome#9203] opened 2016-05-13 13:07 UTC
Hie every one!
I would like to try on your web-site a wallet Icon. I need one to offer to my clients a button to pay their payment. It would be awesome if you can reply at my request.
Thank you! 

PS: Sorry for my very bad english.

**Comment by tagliala** [comment] 2016-05-13 17:53
Duplicate of #2317, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-13 17:53 UTC
