### ISSUE TITLE
Icon request: icon-podium

### ISSUE THREAD

**Issue by monika-aashe** [FortAwesome/Font-Awesome#8337] opened 2016-01-13 18:35 UTC
Hello,
We'd like to request a new icon that shows an image of a lecturn or podium, representing conference presentations. This would be used in our new Resource Center Hub, where we're identifying an icon for each type of resource. In this case, all "Conference Presentations" would be identified with this type of icon. Here is an image from the web that is similar to what we're looking for.

Thank you in advance for your help!
![podium-512](https://cloud.githubusercontent.com/assets/15214797/12303802/65cb504c-b9fa-11e5-8afb-3e9965aaa66e.png)

**Comment by tagliala** [comment] 2016-01-13 19:12
duplicate of #1688 , please +1 that request

closing here

**Closed by tagliala** 2016-01-13 19:12 UTC

**Comment by monika-aashe** [comment] 2016-01-13 19:16
Sorry but I disagree that this is a duplicate. This icon represents standing in front of an audience, whereas the other represents digital playback. Any chance you can revisit?

**Comment by tagliala** [comment] 2016-01-13 19:19
@monika-aashe sorry!

dup of #472
