### ISSUE TITLE
Icon request: Analysis

### ISSUE THREAD

**Issue by Minikibber** [FortAwesome/Font-Awesome#10420] opened 2016-12-22 10:50 UTC
![2196-512](https://cloud.githubusercontent.com/assets/24714037/21423317/adcdd120-c83c-11e6-82fb-c58bc4ef7e79.png)
![4187-200](https://cloud.githubusercontent.com/assets/24714037/21423316/adcd3b8e-c83c-11e6-89df-136e4f77a456.png)
![46946-200](https://cloud.githubusercontent.com/assets/24714037/21423318/adcf4136-c83c-11e6-816d-249f30ac02ee.png)

**Comment by tagliala** [comment] 2016-12-22 13:44
Duplicate of #7523, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-22 13:44 UTC
