### ISSUE TITLE
Icon request: icon-door

### ISSUE THREAD

**Issue by Vieshanis** [FortAwesome/Font-Awesome#10631] opened 2017-02-07 11:54 UTC
This should be used for home, apartment icon 

https://image.flaticon.com/icons/png/128/59/59805.png

**Comment by tagliala** [comment] 2017-02-07 11:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2921 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-07 11:58 UTC
