### ISSUE TITLE
podcast icon?

### ISSUE THREAD

**Issue by marlex** [FortAwesome/Font-Awesome#8160] opened 2015-12-16 12:16 UTC
Hi everybody!

I love fontawesome. Just some requests. How's the working progress of these icon? It would be great! :) (and also gmail, ivoox icon...)

Infinite thanks!!!!

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313033303234322f313839323939382f32353262376262612d376136352d313165332d396632322d6535353263306337346433652e706e67](https://cloud.githubusercontent.com/assets/1155574/11840502/ab0c9c8e-a3f6-11e5-8dd0-3f93069223d7.png)

**Comment by tagliala** [comment] 2015-12-16 12:55
Duplicate of #2125, which you already up-voted

If you need this icon in a short while, please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here

**Closed by tagliala** 2015-12-16 12:55 UTC
