### ISSUE TITLE
Icon request: Google Maps

### ISSUE THREAD

**Issue by 2ne** [FortAwesome/Font-Awesome#17718] opened 2021-03-11 09:54 UTC
**What can it be used for?**
Used when linking to Google Maps with an icon-only button.

**Example image (optional)**
https://www.google.co.uk/search?q=google+maps+icon&tbm=isch&chips=q:google+maps+icon,g_1:android:5ueirHc3Fok%3D&hl=en-GB&sa=X&ved=2ahUKEwirxrfw-6fvAhVP0RoKHZ6YDTgQ4lYoAXoECAEQGw&biw=1903&bih=937

**Comment by tagliala** [comment] 2021-03-11 11:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13295, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-11 11:19 UTC
