### ISSUE TITLE
Icon Request: fa-bath

### ISSUE THREAD

**Issue by Jo7j** [FortAwesome/Font-Awesome#6855] opened 2015-07-01 15:35 UTC
For an estate agency website, alongside the fa-bed icon it would be useful to have a fa-bath icon.

**Comment by jahka** [comment] 2015-07-03 05:30
+1

**Comment by tagliala** [comment] 2015-07-03 08:08
duplicate of #708, please +1 that request

closing here

**Closed by tagliala** 2015-07-03 08:08 UTC
