### ISSUE TITLE
fa-instagram-square

### ISSUE THREAD

**Issue by andrea-86** [FortAwesome/Font-Awesome#11814] opened 2017-11-29 16:12 UTC
PLease, make a fa-instagram-square for make a istragram social icon in the same stile of other social-quare icon

**Comment by tagliala** [comment] 2017-11-29 16:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9223 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-29 16:16 UTC
