### ISSUE TITLE
Icon Request | fa-toyhouse

### ISSUE THREAD

**Issue by ImaTimekeeperReadingRaptor** [FortAwesome/Font-Awesome#18538] opened 2021-12-25 18:43 UTC
### **What can it be used for?**
This icon can allow users of the site to promote their Toyhou.se profiles, can also be used as a portfolio

Toyhou.se is a place where artists can store their characters/original creations to show them off or to just store them. Users can also write literature to tell stories about their characters. 

------

### **Logo**
![image](https://user-images.githubusercontent.com/65588483/147391485-7deebeeb-9e0b-4331-8470-e1d8682a0f56.png)
*Source of Image* -> https://logos.fandom.com/wiki/Toyhouse

------

**Icon request checklist**
- [✔️] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [✔️] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✔️] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✔️] I have included at least one example image if it could be helpful (optional)
- [✔️] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-12-25 19:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10205, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-12-25 19:17 UTC
