### ISSUE TITLE
Icon Request: Shop Icon

### ISSUE THREAD

**Issue by mikiamit** [FortAwesome/Font-Awesome#7736] opened 2015-10-21 09:34 UTC
Hi There,

Really happy to have font-awasome in my day to day life :)

Would love to have a shop icon, one that describes a business selling goods.

Best,
Michael

**Comment by webappdesigner** [comment] 2015-10-21 11:05
+1

**Comment by tagliala** [comment] 2015-10-21 13:25
duplicate of #1958 ? If yes, please +1 that request and close this one. If not, please clarify with an example

**Comment by sensibleworld** [comment] 2019-04-11 12:58
https://fontawesome.com/icons/store?style=solid
https://fontawesome.com/icons/store-alt?style=solid

**Closed by sensibleworld** 2019-04-11 12:58 UTC
Labels: waiting for feedback
