### ISSUE TITLE
Bug: FontAwsome issue when upgrading changes behavior of form-fields

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#20433] opened 2024-11-23 16:14 UTC
### Bug description

So the background story is we are using fontAwsome version 5.15.3 -- it is self hosted and works perfectly...

However we are trying to upgrade to the latest version of fontAwsome v6.7.1 and have run into an issue ...

The reason for the upgrade is we need the Twitter/X icon to show correctly and the new icons that have been added.

The error is all form fields on our website switch to all CAPS when using the new fontAwsome v6.7.1 hosted or the CDN version of FontAwsome to the point that users cant login etc... so we had to switch back to the old verion...

Anyone else having this issue? As we hope to get this working with your help!

We are also using bootstrap so not sure where the error could be but as mentioned it only happens when we switch to the new version of fontawsome

We await your reply

### Screenshots

When we use the hosted version of the new fontawsome or the cdn version all our form-fields type in capitals..
![Screenshot 2024-11-23 110806](https://github.com/user-attachments/assets/0f9ed3f8-6bc1-4c96-8565-1e41ae8dfadf)

### Font Awesome version

6.7.1 - 6.5.2

### Serving

Font Awesome CDN, Self-hosted

### Implementation

CSS

### Browser and Operating System

Windows 10 and 11 using the following browsers edge, Firefox and Brave browsers

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2024-11-23 16:48
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome 6 is actually a Font, so it can be used also to write text, and in fact the text you are seeing is using Font Awesome as the font family

The solution is to use to the application font in that field, and leave font awesome to its own tags

If you need more details, please provide a reproducible test case

**Comment by ghost** [comment] 2024-11-23 16:54
That's not the problem though, every form-field stays as CAPS in all the form fields you can not type in lowercase at all so you cant even login that's why we had to switch back to the old verion of fontawsome but we need the new version(s) for the new icons

**Comment by tagliala** [comment] 2024-11-23 18:46
If you can provide a reproducible test case I will take a look

**Comment by ghost** [comment] 2024-11-23 19:43
I can post the url to the website if that helps? Or message you the url?

**Comment by tagliala** [comment] 2024-11-23 20:19
feel free to post the url if it is public

**Comment by ghost** [comment] 2024-11-23 20:30
Ok thank you for your expertise if you type in any form-field on any page its always capital

https://www.seoprogurus.com

**Comment by tagliala** [comment] 2024-11-23 23:42
Hello,

as I mentioned, the `input` is not using the proper font-family. It should use application's font-family

![image](https://github.com/user-attachments/assets/de5edf60-6124-4f4e-8a5c-8b38049d953f)

NOTE: if that change is intended as a workaround to show Font Awesome icons in an input / select box, please notice that this use case was never supported and it is not supported in all browsers. If you need to show icons in an input or select, it is strongly suggested to go for a javascript solution

Ref: #996

Closing here, but feel free to comment

**Closed as completed by tagliala** 2024-11-23 23:42 UTC
Labels: question
