### ISSUE TITLE
Icon Request: fa-burger

### ISSUE THREAD

**Issue by jenevedube** [FortAwesome/Font-Awesome#8119] opened 2015-12-08 15:14 UTC
I've been using existing icons to denote restaurant styles for a search function. Diamond = upscale, Star = diner, Child = family-style. Just need a burger for burger joints. :) 

Thank you!

**Comment by tagliala** [comment] 2015-12-08 15:17
duplicate of #1961,please +1 that request

related to #1895 

closing here

**Comment by jenevedube** [comment] 2015-12-08 15:18
Sorry!

**Closed by tagliala** 2015-12-08 15:17 UTC
