### ISSUE TITLE
Icon Request: fa-zoom

### ISSUE THREAD

**Issue by agarzon25** [FortAwesome/Font-Awesome#16834] opened 2020-06-25 04:29 UTC
With the increase in popularity of Zoom's video conferencing, I think people will try to incorporate the zoom logo icon in their Web UIs especially businesses that benefit from social distancing.

**Comment by tagliala** [comment] 2020-09-16 17:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16079, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-16 17:48 UTC
