### ISSUE TITLE
Icon not correctly display in select tag with Firefox 56

### ISSUE THREAD

**Issue by TimotheBarbe** [FortAwesome/Font-Awesome#11616] opened 2017-10-12 09:28 UTC
Icons in a drop down are not correctly display using Firefox 56 (linux), but it work with Firefox 54 and Chrome

```
<select>
  <option>Hi, &#xf042;</option>
  <option>Hi, &#xf043;</option>
  <option>Hi, &#xf044;</option>
  <option>Hi, &#xf045;</option>
  <option>Hi, &#xf046;</option>
</select>
```

See this fiddle : https://jsfiddle.net/zcagvgfn/1/

Give me this result

![bug](https://user-images.githubusercontent.com/7836346/31489206-4053c6d6-af40-11e7-9de7-f7bc97fa3422.png)

**Comment by tagliala** [comment] 2017-10-12 16:33
Closing here as a duplicate of #996

**Closed by tagliala** 2017-10-12 16:33 UTC
