### ISSUE TITLE
Icon request: icon-mac

### ISSUE THREAD

**Issue by ediweissmann** [FortAwesome/Font-Awesome#8185] opened 2015-12-19 21:03 UTC
Would complement nicely the existing `icon-windows` and `icon-linux`.
One use case is building download pages for multi-platform software.

Thanks

**Comment by wolfy1339** [comment] 2015-12-19 22:10
Wouldn't icon-osx be better than icon-mac? Because Mac is not the OS name

**Comment by tagliala** [comment] 2015-12-19 22:18
osx is a duplicate of #4936, please +1 that request

**Closed by tagliala** 2015-12-19 22:18 UTC
