### ISSUE TITLE
Icon Request: fa-javascript,Icon Request: fa-jquery,Icon Request: fa-angular

### ISSUE THREAD

**Issue by keyur22** [FortAwesome/Font-Awesome#11687] opened 2017-10-29 15:12 UTC
Hey, it would be awesome if you could make an icon for javascript, jquery and angular.
I hope you take this request into consideration

**Comment by tagliala** [comment] 2017-10-29 18:00
Hi!

Thanks for being part of the Font Awesome Community.

Javascript will be available in FA5 #1711 

jquery is a duplicate of #1665, please add a 👍  reaction to that request.

angular is a duplicate of #10439, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-29 18:00 UTC
