### ISSUE TITLE
Icon Request: fa-filter-slash

### ISSUE THREAD

**Issue by robertppn** [FortAwesome/Font-Awesome#10368] opened 2016-12-14 14:49 UTC
Hi there, would be great to have a remove filter icon. So just the fa-filter icon with a stripe running through.

**Comment by tagliala** [comment] 2016-12-14 15:04
Duplicate of #5309, please add a 👍  reaction to that request

Also related to: #650

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-14 15:04 UTC
