### ISSUE TITLE
Icon Request: fab-tmdb

### ISSUE THREAD

**Issue by TheOldMan2000** [FortAwesome/Font-Awesome#17780] opened 2021-03-29 02:58 UTC
**What can it be used for?**
(N.B. Not to be confused with the icon fab-mdb for Material Design Bootstrap)

Same usage case as for the existing IMDB icon, The Move Database (TMDb) at https://www.themoviedb.org/ is a popular, publicly available resource for TV and Film, Cast and Crew information available on their website and also via their free API for third party integration. It is an alternative to the Amazon owned IMDB. 

Can be used next to profile links on web pages linking to people profile entries and/or films and TV entries at TMDb.

From the TMDb About page:
The Movie Database (TMDb) is a community built movie and TV database. Every piece of data has been added by our amazing community dating back to 2008. TMDb's strong international focus and breadth of data is largely unmatched and something we're incredibly proud of. Put simply, we live and breathe community and that's precisely what makes us different.
https://www.themoviedb.org/about

Please note that I am not associated with TMDb in anyway. Just needing an FA5 icon to use along with IMDB and others. Thank you.

**Example image (optional)**
Link to SVG logos (2 styles):
[https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_2-d537fb228cf3ded904ef09b136fe3fec72548ebc1fea3fbbd1ad9e36364db38b.svg](https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_2-d537fb228cf3ded904ef09b136fe3fec72548ebc1fea3fbbd1ad9e36364db38b.svg)

https://www.themoviedb.org/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg

**Icon request checklist**
- [*] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [*] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [*] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [*] I have included at least one example image if it could be helpful (optional)
- [*] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-03-29 07:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11105, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-29 07:26 UTC

**Comment by TheOldMan2000** [comment] 2022-02-12 08:13
The icon request you linked to is admittedly there but it lacks the information you ask us to provide when requesting an icon (no offence intended) and the icon example displayed is now outdated.

https://www.themoviedb.org/about/logos-attribution
