### ISSUE TITLE
Icon Request: fa-jackpot

### ISSUE THREAD

**Issue by dwhaas82** [FortAwesome/Font-Awesome#12524] opened 2018-03-06 02:58 UTC
could use an icon to signify a prize, such as a pot of gold or a sack of coins.

**Comment by tagliala** [comment] 2018-03-06 11:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1414 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-06 11:06 UTC
