### ISSUE TITLE
Icon Request: fa-angieslist

### ISSUE THREAD

**Issue by thestrag** [FortAwesome/Font-Awesome#8946] opened 2016-04-11 16:33 UTC
Angie's List - review site that many businesses are listed on.  Would be useful for company sites that are looking to link.

![Image of Angie's List Logo](http://www.hitmanadvertising.com/blog/wp-content/uploads/2016/03/angies-list-logo-white-295x300.jpg)

[http://www.hitmanadvertising.com/blog/wp-content/uploads/2016/03/angies-list-logo-white-295x300.jpg](url)

**Comment by tagliala** [comment] 2017-01-17 12:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6716, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-17 12:58 UTC
Labels: brand icons, new icon
