### ISSUE TITLE
Icon Request: fa-radar

### ISSUE THREAD

**Issue by douglasdeodato** [FortAwesome/Font-Awesome#9444] opened 2016-06-22 11:30 UTC
Hello,

Use case: tracking objets, Communication, monitor, navigation, network.

![061-512](https://cloud.githubusercontent.com/assets/993318/16265049/1554a92a-3875-11e6-8381-1656a3a4cceb.png)

**Comment by tagliala** [comment] 2016-06-22 12:03
Duplicate of #5659, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-22 12:03 UTC
