### ISSUE TITLE
Redesign: fa-check-square-o

### ISSUE THREAD

**Issue by tfmontague** [FortAwesome/Font-Awesome#5017] opened 2014-11-21 22:00 UTC
Why isn't the design of "fa-check-square-o" like "fa-square-o" or "fa-check-square"? Having the checkmark extend outside the box produces an alignment issue, when trying to use as a checkbox (on: "fa-check-square-o", off: "fa-square-o"). It should be like "fa-check-square".

![screen shot 2014-11-21 at 1 51 01 pm](https://cloud.githubusercontent.com/assets/1149793/5150248/77961d20-7185-11e4-85cd-22a2f3537e44.png)

**Comment by tagliala** [comment] 2015-11-21 12:32
Please use `text-align: left` for this use case

Closing here

**Comment by tfmontague** [comment] 2015-11-21 21:13
@tagliala - that's not a fix - that's a code hack to compensate for bad design. The "fa-check-square" and "fa-check-square-o" icons don't match - they should be redesigned.

**Comment by tagliala** [comment] 2015-11-21 23:09
This is a duplicate of #3595, which was closed for the same reason

I'm going to add this to 5.0.0 milestone, so Dave will eventually take a look at this issue

**Comment by tagliala** [comment] 2015-11-21 23:10
Refers to #5156

**Comment by tagliala** [comment] 2015-11-21 23:14
Sorry, let's use #5156 

I grouped all forms related issues into one issue

**Closed by tagliala** 2015-11-21 23:14 UTC
Labels: enhancement, form control icons
