### ISSUE TITLE
Icon request: icon-xray

### ISSUE THREAD

**Issue by tesnep** [FortAwesome/Font-Awesome#9406] opened 2016-06-14 23:29 UTC
Can we have an xray icon with radioactive symbol? This can go under the category "medical".

**Comment by tagliala** [comment] 2016-06-15 09:40
maybe this is a duplicate.

Did you try to [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before using different keywords ?

Could you please provide an example?

**Comment by aethior** [comment] 2016-06-15 14:22
Duplicate of #681 and planned for v5.0. ;)

cc @tagliala

**Comment by tagliala** [comment] 2016-06-15 21:00
@aethior thanks. I wasn't able to find the original request

**Closed by tagliala** 2016-06-15 21:00 UTC
Labels: waiting for feedback
