### ISSUE TITLE
Icon Request: fa-EU

### ISSUE THREAD

**Issue by leribol** [FortAwesome/Font-Awesome#9006] opened 2016-04-18 08:42 UTC
I would like to request "European Union" flag. 

I will use it on EU button on my website to navigate user to EU related pages.

Best regards,

![eu](https://cloud.githubusercontent.com/assets/18526989/14598378/94880096-055a-11e6-9ae6-6ad8f50c539b.jpg)

**Comment by jeremyVignelles** [comment] 2016-05-04 14:59
isn't this the same as #5831 ?

**Comment by tagliala** [comment] 2016-05-04 15:43
@jeremyVignelles thanks!

Duplicate of #5831, please +1 that request

closing here

**Closed by tagliala** 2016-05-04 15:43 UTC
