### ISSUE TITLE
Icon Request: fa-section-sign

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7940] opened 2015-11-20 06:53 UTC
Request for fa-section as in (Unicode U+00A7) ``&sect;``

![fa-section-sign](http://i.imgur.com/Jlvj6ve.png)

Wikipedia: https://en.wikipedia.org/wiki/Section_sign

**Comment by tagliala** [comment] 2015-11-20 17:37
duplicate of #1706 , please +1 that request

editing #1706 to include section in the title

closing here

**Closed by tagliala** 2015-11-20 17:37 UTC

**Comment by Syr3L** [comment] 2018-08-15 07:04
any chance this will be added?
