### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by yockster** [FortAwesome/Font-Awesome#10428] opened 2016-12-24 19:28 UTC
Hello, 

I would like to see about adding an icon for car or truck engine. Like the one that displays on a cars dash board (check engine lite)

![download](https://cloud.githubusercontent.com/assets/24757061/21468549/f7301806-c9cb-11e6-8cc3-1844dfb6a6a2.png)

**Comment by tagliala** [comment] 2016-12-24 19:53
Duplicate of #4175, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-24 19:53 UTC
