### ISSUE TITLE
Icon request: qzone&douban

### ISSUE THREAD

**Issue by pucqx** [FortAwesome/Font-Awesome#17591] opened 2021-01-29 04:57 UTC
for qzone, like this https://qzonestyle.gtimg.cn/qzone/v8/img/Qzone.svg;

for douban, it's code like this:<svg id="wi-douban" viewBox="0 0 1024 1024"><path d="M696.064 816.554667h173.44a26.453333 26.453333 0 0 1 26.496 26.453333v26.496a26.453333 26.453333 0 0 1-26.453333 26.496H154.453333a26.453333 26.453333 0 0 1-26.453333-26.453333v-26.496a26.453333 26.453333 0 0 1 26.453333-26.496h160.170667l-40.96-132.437334h93.44a26.453333 26.453333 0 0 1 25.173333 18.133334l38.058667 114.304H580.266667l52.266666-172.16H220.672a26.453333 26.453333 0 0 1-26.453333-26.453334V313.386667a26.453333 26.453333 0 0 1 26.453333-26.453334h582.656a26.453333 26.453333 0 0 1 26.453333 26.453334v304.554666a26.453333 26.453333 0 0 1-26.453333 26.453334h-54.997333l-52.266667 172.16zM167.722667 128h688.554666a26.453333 26.453333 0 0 1 26.453334 26.453333v26.496a26.453333 26.453333 0 0 1-26.453334 26.496H167.722667a26.453333 26.453333 0 0 1-26.453334-26.453333V154.453333A26.453333 26.453333 0 0 1 167.68 128zM306.773333 366.336a6.613333 6.613333 0 0 0-6.656 6.613333v172.16c0 3.669333 2.986667 6.613333 6.656 6.613334h410.453334c3.669333 0 6.656-2.986667 6.656-6.613334V372.906667a6.613333 6.613333 0 0 0-6.656-6.613334H306.773333z"></path></svg>

**Comment by pucqx** [comment] 2021-01-29 04:59
for douban, it's code like this https://www.douban.com/favicon.ico

**Comment by tagliala** [comment] 2021-01-29 08:41
Hi!

Thanks for being part of the Font Awesome Community.

qzone is a duplicate of #3993, please add a 👍 reaction to that request.
douban is a duplicate of #1841, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-01-29 08:41 UTC
