### ISSUE TITLE
Icon Request: fa-morning 

### ISSUE THREAD

**Issue by sdhp** [FortAwesome/Font-Awesome#6135] opened 2015-04-02 05:32 UTC
As we could use "fa-moon-o" and "fa-sun-o" as indicatiors for daytime and nighttime I miss an icon that indicates "morning time". Could be a sun rising behind a mountain or a cloud?
By the way if you consider to do two icons sun and moon without -o i would love to see a change of the design at least of the sun to more friendly.

**Comment by tagliala** [comment] 2015-04-04 17:09
Could you please post a single color example? It's hard to distinguish if it is rising or setting

http://www.iemoji.com/view/emoji/135/places/sunrise

Please +1 #5700 for filled in versions of sun and moon

**Comment by sdhp** [comment] 2015-04-04 18:36
I would go with the perception most of us have with a timeline. Left is earlier than right.

Something like 
![proposalmorning fw](https://cloud.githubusercontent.com/assets/10001889/6994021/6decb746-db09-11e4-8a33-e66fb2cbefe5.png)

Maybe adding a moon at the evening-version could help as well...

**Comment by wilkmit** [comment] 2015-05-29 19:13
What about something like this for fa-sunrise and the opposite for fa-sunset. It follows the simplicity of font awesome. ![sunrise](https://cloud.githubusercontent.com/assets/6516828/7890624/0381379c-0615-11e5-8de3-3b46c2e600fc.png)

**Comment by sdhp** [comment] 2015-05-29 19:37
hm i do like the sun with that rounded rays very much -  not so much the mountain. 
but if you would change this to a house or barn - maybe? I dont know if people would recognize is very easy. You wrote sunset - from looking at it but now reading I first thought this is for morning...

I still would appreciate this set to be in next update because I am still convinced that daytime is used widely, I think.

**Comment by stephanebruckert** [comment] 2015-06-24 22:39
This is super needed! Any progress? 
Rather than the ones with the mountains, I like the fa-sunrise from @wilkmit a lot.

**Comment by tagliala** [comment] 2015-07-01 10:40
You should consider this: http://erikflowers.github.io/weather-icons/

**Comment by stephanebruckert** [comment] 2015-07-01 11:41
Excellent, thanks!

**Comment by Crissov** [comment] 2016-10-27 21:00
* [🌃 U+1F303 Night with Stars](http://emojipedia.org/night-with-stars/)
* [🌄 U+1F304 Sunrise over Mountains](http://emojipedia.org/sunrise-over-mountains/)
* **[🌅 U+1F305 Sunrise](http://emojipedia.org/sunrise/)**
* [🌆 U+1F306 Cityscape at Dusk](http://emojipedia.org/cityscape-at-dusk/)
* [🌇 U+1F307 Sunset over Buildings](http://emojipedia.org/sunset-over-buildings/)
* [🏙 U+1F3D9 Cityscape](http://emojipedia.org/cityscape/)
* [🔆 U+1F506 High Brightness Symbol](http://emojipedia.org/high-brightness-symbol/)

**Comment by tagliala** [comment] 2022-03-13 15:45
I'm going to consider this closed by https://fontawesome.com/icons/sunrise?s=solid

Duplicate of #5200

**Closed by tagliala** 2022-03-13 15:45 UTC
Labels: waiting for feedback
