### ISSUE TITLE
Icon request: icon-clapboard

### ISSUE THREAD

**Issue by mcrbtco** [FortAwesome/Font-Awesome#13362] opened 2018-06-21 18:27 UTC
### What can it be used for?

Video Editing, video production, Director/Producer/Editor descriptions

### Example image (optional)

![img_426695](https://user-images.githubusercontent.com/30812779/41738084-1e0e2b08-755f-11e8-9428-c5acbc1a83ee.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-06-21 18:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of ##3130, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-21 18:52 UTC
