### ISSUE TITLE
Icon request: vehicle-axles

### ISSUE THREAD

**Issue by evsar3** [FortAwesome/Font-Awesome#15730] opened 2019-10-25 12:47 UTC
**What can it be used for?**
This icon could be very useful in any vehicle-related applications. In my application for example, it would be nice to use it in a "vehicle axles settings" section.

**Example image (optional)**
![Axle Icon Example 1](https://cdn0.iconfinder.com/data/icons/cars-and-transportation-glyph/96/24-512.png)  
![Axle Icon Example 2](https://image.shutterstock.com/image-photo/image-450w-1196074339.jpg)  
![Axle Icon Example 3](https://image.shutterstock.com/image-vector/car-axle-icon-trendy-logo-260nw-1255573600.jpg)  

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment] 2024-07-11 18:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/17889)

**Closed by sensibleworld** 2024-07-11 18:23 UTC
Labels: new icon, automotive (category), Duplicate
