### ISSUE TITLE
Icon Request: fa-handshake

### ISSUE THREAD

**Issue by andreiiuga** [FortAwesome/Font-Awesome#9842] opened 2016-08-31 09:26 UTC
![handshake-icon-23](https://cloud.githubusercontent.com/assets/20061438/18123087/fd452e68-6f74-11e6-906a-e7ae2afaa044.png)

I plan on using this icon to represent an agreement between two person or entities.
I'm in a situation where I have two parties and I need to put a symbol between these to represent a collaboration.
So the key word here is Collaboration.

This would be so useful for me .

Thank you

**Comment by tagliala** [comment] 2016-08-31 10:58
Duplicate of #878 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-31 10:58 UTC
