### ISSUE TITLE
Icon request: Drama Mask

### ISSUE THREAD

**Issue by upace** [FortAwesome/Font-Awesome#11790] opened 2017-11-22 18:12 UTC
Use for a mobile app for a drama program. 

<img width="527" alt="screen shot 2017-11-22 at 1 12 13 pm" src="https://user-images.githubusercontent.com/10821656/33143109-c7e0b1ca-cf86-11e7-99d4-b3977e783325.png">

**Comment by tagliala** [comment] 2017-11-22 18:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1270, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-22 18:17 UTC
