### ISSUE TITLE
Icon request: Medium

### ISSUE THREAD

**Issue by biild** [FortAwesome/Font-Awesome#18008] opened 2021-06-14 21:10 UTC
**What can it be used for?**
It would be an update to the latest Medium icon.  The older one is available, but they have a new one now.

**Example image (optional)**

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
![download](https://user-images.githubusercontent.com/60325643/121959942-4bd49980-cd1a-11eb-8473-8a16c9f5eec0.png)

Cheers!

**Comment by tagliala** [comment] 2021-06-15 07:05
Hi!

Thanks for being part of the Font Awesome Community.

This has been already fixed in FA6 beta and it will be released in the next FA5 version

Duplicate of #17281 , closing here

**Closed by tagliala** 2021-06-15 07:05 UTC
