### ISSUE TITLE
Icon Request: icon-network

### ISSUE THREAD

**Issue by matjasw** [FortAwesome/Font-Awesome#9277] opened 2016-05-26 10:01 UTC
Dear,

Is it possible to create an icon to indicate a network?

Kind regards,

M.
![business-affiliate-network](https://cloud.githubusercontent.com/assets/19588593/15571135/8947624c-2339-11e6-8b47-329db9b894fc.png)

**Comment by tagliala** [comment] 2016-05-26 10:28
Duplicate of #5944, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-26 10:28 UTC
