### ISSUE TITLE
Icon Request: Nextdoor

### ISSUE THREAD

**Issue by ramoroso1** [FortAwesome/Font-Awesome#17368] opened 2020-11-04 23:39 UTC
Hello, I need the Nextdoor social media icon for my website, to be alongside Facebook and others. My website is a Wordpress site and only allows icons from GitHub. Nextdoor uses both the "storefront" icon, and their fancy letter "n."

Please and thank you!

![Nextdoor](https://user-images.githubusercontent.com/73971111/98179502-847add80-1ec4-11eb-8388-ec49ee2b2cdc.png)

**Comment by tagliala** [comment] 2020-11-05 08:24
Duplicate of #3928

**Closed by tagliala** 2020-11-05 08:24 UTC
