### ISSUE TITLE
Icon Request: fa-books

### ISSUE THREAD

**Issue by cpx-daniel** [FortAwesome/Font-Awesome#8535] opened 2016-02-11 00:38 UTC
Please add an icon for a few books on a shelf
icomoon has this: 
![image](https://cloud.githubusercontent.com/assets/3173104/12966606/813135f0-d0ab-11e5-9e99-25adb869f6f8.png)

**Comment by tagliala** [comment] 2016-02-14 12:48
duplicate of #5098, please +1 that request

closing here

**Closed by tagliala** 2016-02-14 12:48 UTC
Labels: new icon, web application icons
