### ISSUE TITLE
Icon request: icon-hang-loose

### ISSUE THREAD

**Issue by KANTA8Y** [FortAwesome/Font-Awesome#11839] opened 2017-12-06 02:29 UTC
Hi, I want to use hang-loose icon in my web service which uses surfing motif. Could you make it?
Thank you for your help.

**Comment by PeterShaggyNoble** [comment] 2017-12-06 09:23
You mean #8093?

**Comment by elenanelmes** [comment] 2018-04-19 16:00
I was about to log a request for a shaka/hang loose icon.

**Comment by chryssajones** [comment] 2019-03-14 19:16
My organization builds apps for Hawaiian culture-based educational initiatives.  We would also like to use a shaka icon in our applications, as that gesture originated here in Hawaii and is universally recognized here.

**Comment by tagliala** [comment] 2019-03-14 21:12
@chryssajones is this request a duplicate of #8093?

**Comment by chryssajones** [comment] 2019-03-14 22:39
Yes.  I did not make a new request, but I added comments and thumbs-ups to the three existing requests for this icon.  I hope to see it added!

**Comment by tagliala** [comment] 2019-03-14 22:43
Thanks, closing here as a duplicate of #8093, please upvote that one

**Closed by tagliala** 2019-03-14 22:43 UTC
Labels: waiting for feedback
