### ISSUE TITLE
Icon Request: fa-jquery

### ISSUE THREAD

**Issue by uomopalese** [FortAwesome/Font-Awesome#6797] opened 2015-06-21 09:47 UTC
![jquery-4096-black](https://cloud.githubusercontent.com/assets/1730448/8271207/4d5f48b0-180b-11e5-9743-3738c0c8bc94.png)

**Comment by tagliala** [comment] 2015-06-21 10:32
duplicate of #1665, please +1 that request

closing here

**Closed by tagliala** 2015-06-21 10:32 UTC
