### ISSUE TITLE
OTF file appears to install in Font Book but character preview displays only question marks

### ISSUE THREAD

**Issue by rubyflick** [FortAwesome/Font-Awesome#10222] opened 2016-11-14 18:06 UTC
And the font doesn't work in Ai or Id, etc... OSX El Capitan 10.11.6
![screen shot 2016-11-14 at 1 05 44 pm](https://cloud.githubusercontent.com/assets/3966976/20276641/1715a616-aa6b-11e6-84c9-d2c9bab10195.png)

**Comment by Crissov** [comment] 2016-11-14 22:51
probably a duplicate of #222

**Comment by tagliala** [comment] 2016-11-14 23:00
It's the same with other icon fonts using PUA, it should not be a problem of Font Awesome

Duplicate of #10068

**Closed by tagliala** 2016-11-14 23:00 UTC
