### ISSUE TITLE
Icon request: icon-flower

### ISSUE THREAD

**Issue by sunlyear** [FortAwesome/Font-Awesome#10265] opened 2016-11-22 07:09 UTC
- Use for a flower shop website.
![bouquet](https://cloud.githubusercontent.com/assets/6761980/20514217/4ef01064-b0bd-11e6-9d15-5ae74ffbb960.png)

**Comment by Crissov** [comment] 2016-11-22 09:19
That’s a bouquet or flower**s**.

Unicode characters
------------------
#222 

- 💐 **[U+1F490 Bouquet](http://emojipedia.org/bouquet/)**
- 🎕 U+1F490 Bouquet of Flowers (no emoji yet)
- ⚘ U+2698 Flower (no emoji yet)
- 🌷 [U+1F337 Tulip](http://emojipedia.org/tulip/)
- 🌹 [U+1F339 Rose](http://emojipedia.org/rose/)
- 🌻 [U+1F33B Sunflower](http://emojipedia.org/sunflower/)
- 🌼 [U+1F33C Blossom](http://emojipedia.org/blossom/)
- 💮 [U+1F4AE White Flower](http://emojipedia.org/white-flower/)
- 🥀 [U+1F940 Wilted Flower](http://emojipedia.org/wilted-flower/)

**Comment by tagliala** [comment] 2017-05-16 17:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2037, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed** 2017-05-16 17:12 UTC
