### ISSUE TITLE
Icon Request: fa-Golf

### ISSUE THREAD

**Issue by tamisandoval** [FortAwesome/Font-Awesome#6877] opened 2015-07-05 12:08 UTC
Hi! thanks for let us ask for new icons... im building my web with Hotel Master Theme and i noticed there are not so many "hotel, resort" icons. For example a need to indicate that my hotel is close to a golf course and a ski resort, would you help me? Thanks! Greetings from Argentina.

Tami

**Comment by tagliala** [comment] 2015-07-05 12:37
duplicate of #5348, please +1 that request

closing here

**Closed by tagliala** 2015-07-05 12:37 UTC
