### ISSUE TITLE
Icon Request: icon-fheo

### ISSUE THREAD

**Issue by rwilsond** [FortAwesome/Font-Awesome#10795] opened 2017-03-15 19:59 UTC
Use Cases: Any real estate property website (apartments and most condominiums) that follow federal fair housing policies and laws. It usually would accompany the wheelchair/wheelchair-alt icons, in the footer of a website or on a contact page.

fheo = Fair Housing Equal Opportunity

The 'home' FontAwesome icon does not qualify and is not a substitute.

![fheo300](https://cloud.githubusercontent.com/assets/12199142/23968023/9d53ba7a-0997-11e7-8528-2fb840fe6fa4.gif)

An EPS and a TIF for the official logo can be found on the HUD website.
[https://portal.hud.gov/hudportal/HUD?src=/library/bookshelf11/hudgraphics/fheologo](url)

**Comment by tagliala** [comment] 2017-03-15 22:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3574 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-15 22:49 UTC
