### ISSUE TITLE
Icon request: icon-kakaotolk

### ISSUE THREAD

**Issue by choongki-kim** [FortAwesome/Font-Awesome#10350] opened 2016-12-12 06:58 UTC
Almost everyone in South Korea is using the "kakao talk".
![unnamed](https://cloud.githubusercontent.com/assets/24518319/21090528/bd0b6726-c083-11e6-8403-8a1a8ce01590.png)

**Comment by tagliala** [comment] 2016-12-12 12:32
Duplicate of #3688, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-12 12:32 UTC
