### ISSUE TITLE
Bug: can't import an icon from a kit

### ISSUE THREAD

**Issue by bchoubert** [FortAwesome/Font-Awesome#20146] opened 2024-03-02 13:04 UTC
### Bug description

Hello, pretty new to Kits  😊

I created a kit only selecting the solid style.
Using it in a NextJS project, I installed it creating a .npmrc file and Yarn v1, I can see it in my node_modules folder :

![image](https://github.com/FortAwesome/Font-Awesome/assets/9991093/197b67c5-4900-4b94-9d24-0a3ca22438db)

But using this [doc](https://fontawesome.com/docs/web/use-with/react/add-icons), I can't import a single icon.

![image](https://github.com/FortAwesome/Font-Awesome/assets/9991093/7d8e0a18-b984-4c06-8a45-ba2c38a385d9)

![image](https://github.com/FortAwesome/Font-Awesome/assets/9991093/f6b4337d-a999-44ff-ae9b-dcdb672860a6)

Regarding the structure of the installed package, it seems there's no JS file inside the icons/ directory, nor a classic folder inside it:

![image](https://github.com/FortAwesome/Font-Awesome/assets/9991093/7484db7b-5381-41db-865d-e7e85063392a)

Not sure if that was clear!

My TS config:

![image](https://github.com/FortAwesome/Font-Awesome/assets/9991093/b6499d62-0d2d-4515-b1fa-33f4ebfdfbac)

### Font Awesome version

v6.0.0

### Serving

Kit

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

- VSCode 1.74.3
- Chrome 121.0.6167.185
- Yarn v1.22.21

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by hagealex** [comment] 2024-03-07 14:43
Hello! I have a smiliar issue!

Just created my first kit, installed it via NPM and wanted to import it so my Angular project:

`import { all } from '@awesome.me/kit-{my_kit_id}/icons'` and then I get this error both in my IDE and during the build:


`TS2307: Cannot find module @awesome.me/kit-{my_kit_id}/icons or its corresponding type declarations.`


This is what the `package.json` of the NPM module looks like:

```
{
  "description": "Kit {my_kit_id}",
  "keywords": [],
  "engines": {
    "node": ">=16"
  },
  "dependencies": {
    "@fortawesome/fontawesome-common-types": "^6.5.1"
  },
  "version": "1.0.13",
  "name": "@awesome.me/kit-{my_kit_id}",
  "main": "index.js",
  "types": "./index.d.ts",
  "license": "UNLICENSED",
  "private": true,
  "publishConfig": {
    "access": "public"
  },
  "sideEffects": false,
  "exports": {
    ".": {
      "types": "./index.d.ts",
      "import": "./index.mjs",
      "require": "./index.js",
      "default": "./index.js"
    },
    "./icons": {
      "types": "./icons/modules/index.d.ts",
      "import": "./icons/modules/index.mjs",
      "require": "./icons/modules/index.js",
      "default": "./icons/modules/index.js"
    },
    
    "./icons/classic/light": {
      "types": "./icons/modules/classic/light.d.ts",
      "import": "./icons/modules/classic/light.mjs",
      "require": "./icons/modules/classic/light.js",
      "default": "./icons/modules/classic/light.js"
    },
    
    "./icons/classic/solid": {
      "types": "./icons/modules/classic/solid.d.ts",
      "import": "./icons/modules/classic/solid.mjs",
      "require": "./icons/modules/classic/solid.js",
      "default": "./icons/modules/classic/solid.js"
    },
    
    
    "./icons/css/*.css": {
      "default": "./icons/css/*.css"
    },
    "./icons/less/*.less": {
      "default": "./icons/less/*.less"
    },
    "./icons/scss/*.scss": {
      "default": "./icons/scss/*.scss"
    },
    "./icons/webfonts/*.woff2": {
      "default": "./icons/webfonts/*.woff2"
    },
    "./icons/webfonts/*.ttf": {
      "default": "./icons/webfonts/*.ttf"
    },
    "./package.json": "./package.json"
  }
}
```

**Comment by hagealex** [comment] 2024-03-12 09:47
Hello everyone! Can anyone supporte here? This is kind of a blocking problem for my project right now and I appreciaty any help :) @tagliala  @robmadole

**Comment by robmadole** [comment] 2024-03-12 17:24
:wave: Hi all. So we are getting some other reports of this and the issue is Typescript `moduleResolution`. This needs to be set to `node16` to support the newer `exports` feature of package.json.

Give this a try and see if it "resolves" the problem. (Pun intended.)

**Comment by hagealex** [comment] 2024-03-12 18:55
@robmadole Thanks for your support here! Setting the value to `node16` fixes the import error. But as I'm working with Angular 17 this setting causes other problems. For example this error: 

```
TS1479: The current file is a CommonJS module whose imports will produce require calls; however, the referenced file is an ECMAScript module and cannot be imported with require. Consider writing a dynamic import(@angular/core)' call instead.
```

**Comment by robmadole** [comment] 2024-03-12 20:09
@devoto13 have you ran into problems with Angular 17 and packages that use the newish "exports" feature of package.json? Off the top of your head am I missing something here?

**Comment by devoto13** [comment] 2024-03-12 20:21
Haven't tested, but I don't think moduleResolution=node16 is a good choice for Angular as it is bundled and I am not sure node16 would work correctly in this scenario. Perhaps one should use moduleResolution=bundler as suggested in https://github.com/angular/angular/issues/46181#issuecomment-1823003344?

**Comment by robmadole** [comment] 2024-03-12 20:28
@devoto13 good to know! Thank you. @hagealex can you try `bundler`?

**Comment by hagealex** [comment] 2024-03-12 20:47
@robmadole Using `bundler` seems to work. No issues so far! Will make a further test tomorrow but for the moment it looks like it's solved. Thank you so much!

**Comment by robmadole** [comment] 2024-03-12 20:49
Awesome. Let us know if you find something else.

**Comment by bchoubert** [comment] 2024-03-12 21:11
On my side, I consider it solved too!
I needed, for my NextJS Project, to set module=esnext and modulerResolution=Node16.

Thanks a lot @robmadole ! Should I mark this as solved?

**Comment by robmadole** [comment] 2024-03-12 21:47
@bchoubert I'll close it. If something else pops back up we can always reopen. I have a feeling this is not the last packaging + Typescript issue we'll run across.

**Closed as completed by robmadole** 2024-03-12 21:47 UTC
Labels: bug, needs-triage
