### ISSUE TITLE
Icon request: icon-bear, icon-bull (financial)

### ISSUE THREAD

**Issue by hellsing71** [FortAwesome/Font-Awesome#6913] opened 2015-07-09 17:27 UTC
I'd like to request some icons: 

a 'factory' symbol like this:

http://wedesignblog.com/wp-content/uploads/2014/03/factory-Icon.jpg

stock-related icons: bull and bear:

http://www.sodafish.com/wp-content/uploads/2013/12/bear-bull-icon-design4.png

...and that cross sign (sometimes it's called a dagger), which is often seen in obituaries (I don't know if it's religion-related or widely used):

Steve Jobs ( † October 5, 2011)

I wouldn't need these in the same project :)

**Comment by tagliala** [comment] 2015-07-09 19:18
factory: #1330 , please +1 that request
cross: #1611, please +1 that request

please also remember that you can use the standard unicode point, e.g:
```css
.fa-cross {
  content: "†";
}
```

I don't know if I consider bear and bull strictly related and if they need to be implemented exactly like that. Could you please give me more details on the financial meaning of the above icons?

**Comment by hellsing71** [comment] 2015-07-09 21:38
Investors who believe that a stock price will increase over time (and they wait to sell or buy ASAP) are said to be bullish and the ones who expect the price to decline (so they wait to buy or sell ASAP) are said to be bearish. These are very widely used notions. This is why the Charging Bull statue is in New York, near Wall street and the Stock Exchange.

I would use these icons in a forum engine on an investment related website that would have 'mood voting'.

Sorry for not searching before posting :) I added my +1s and thanks fro the trick.

**Comment by tagliala** [comment] 2015-07-10 08:00
could this be considered a good bull icon for your use case: #1122?

**Comment by hellsing71** [comment] 2015-07-10 10:42
Not really. That bull seems to be the Toro de Osborne, logo of a very old company and a famous installation in Spain that I wouldn't use in financial, especially not in food-related environment.:

https://en.wikipedia.org/wiki/Osborne_bull

Otherwise it's possibly copyrighted. I think a full bull would have too many detail, it could look like a splash of paint in small size.

For me, it would be better on to have a silhouette of a head like the one I linked before or any of these examples:

http://i.istockimg.com/file_thumbview_approve/13357781/6/stock-illustration-13357781-bull-and-bear-icons.jpg
https://www.colourbox.com/preview/7970930-stock-exchange-icons-set.jpg
http://i.istockimg.com/file_thumbview_approve/12631480/6/stock-illustration-12631480-wall-street-royalty-free-vector-icon-set-stickers.jpg

Thanks of dealing with it.

**Comment by jcham83** [comment] 2015-10-13 17:37
+1 Bull and Bear Head

**Comment by earthcomedy** [comment] 2016-02-21 15:52
+1

**Comment by LuisJoseSanchez** [comment] 2016-05-17 20:51
+1

**Comment by syamsulalam** [comment] 2016-05-22 18:08
+1

**Comment by coolneo85** [comment] 2016-08-26 22:30
+1

**Comment by mayeromain** [comment] 2016-10-14 15:09
+1

**Comment by andrefaria** [comment] 2017-01-12 17:53
+1

**Comment by gouyou** [comment] 2017-04-20 19:39
+1

**Comment by Wqrld** [comment] 2017-11-28 19:21
+1 for the bear

**Comment by earthcomedy** [comment] 2018-05-26 05:41
+1

**Comment by lukahooka420** [comment] 2018-06-30 12:39
+1

**Comment by chinchan** [comment] 2019-07-24 07:08
+1 for the bearish and +1 for bullish

**Comment by sensibleworld** [comment] 2024-07-10 21:43
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/1122)

**Closed by sensibleworld** 2024-07-10 21:43 UTC
Labels: new icon, web application icons (legacy category), Duplicate
