### ISSUE TITLE
Please make a Codeigniter logo

### ISSUE THREAD

**Issue by raflidev** [FortAwesome/Font-Awesome#15987] opened 2019-12-23 15:26 UTC
Hello Team Font-Awesome.

Firstly thanks for reading this issue, you have create codeigniter logo. I sure most people will helped if you do that.

Thanks Font-Awesome, your are the best. 😄

**Comment by tagliala** [comment] 2019-12-23 15:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4316, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

> Firstly thanks for reading this issue, you have create codeigniter logo. I sure most people will helped if you do that.

Sure it will be useful for our community, but the best we can do is to upvote the existing request.

If you want to know how requests work, please take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), they contain a lot of information

Closing here

**Closed by tagliala** 2019-12-23 15:38 UTC
