### ISSUE TITLE
Icon Request: icon-smile-huge

### ISSUE THREAD

**Issue by mariusa** [FortAwesome/Font-Awesome#1920] opened 2013-09-04 13:12 UTC
Hi there,

Thanks for the smiley icons (frown, meh, smile).

Would you please consider adding one more, representing a very, very happy person? (but not laughing)
Consider offering a compliment to a girl (response: smile) vs. compliment + flowers + desert + bubble bath (super happy!)

Here's what I was having in mind:
http://findicons.com/icon/38342/smile_7
http://cdn.vectorstock.com/i/composite/98,37/smiley-icon-vector-19837.jpg (no blinking eye though)
 
Thanks!

**Comment by tagliala** [comment] 2016-06-15 21:22
Duplicate of #1417

**Closed by tagliala** 2016-06-15 21:22 UTC
Labels: new icon, web application icons
