### ISSUE TITLE
Icon request: icon-moto-delivery

### ISSUE THREAD

**Issue by bunnberry** [FortAwesome/Font-Awesome#5218] opened 2014-12-15 14:11 UTC
HI! It would be amazing to have an icon for delivery motorcycles. It would be great to communicate that sites such as restaurants, clothing or gifting shops, have a delivery option. 
Thank you!! :smile: 

![01](https://cloud.githubusercontent.com/assets/9891149/5436836/93f9e0e2-8449-11e4-8268-8a118f652f1b.jpg)

![02](https://cloud.githubusercontent.com/assets/9891149/5436842/a50002a4-8449-11e4-88f9-338e08ea0539.png)

![03](https://cloud.githubusercontent.com/assets/9891149/5436913/476ec73c-844a-11e4-9d07-10384293840a.jpg)

**Comment by aethior** [comment] 2022-03-08 16:53
Duplicate of #17559.

**Comment by aethior** [comment] 2022-03-08 16:55
Duplicate of #17559. (_The other request has more upvotes_)

cc/ @tagliala

**Closed** 2022-03-08 17:43 UTC
