### ISSUE TITLE
Button Clips Contained Icons

### ISSUE THREAD

**Issue by mikebronner** [FortAwesome/Font-Awesome#12280] opened 2018-02-08 01:50 UTC
Is there a way to prevent buttons from clipping icons they contain?

```
                <button id="watchVideo">
                    <i class="fas fa-play-circle" data-fa-transform="grow-6"></i>
                    Watch the Introductory Video
                </button>
```

![screen shot 2018-02-07 at 5 48 28 pm](https://user-images.githubusercontent.com/1791050/35951187-25b6118e-0c2f-11e8-989c-0b86c106b550.png)

Here are the CSS rules that are applied (I did try with overflow:visible, but that had no effect):
![screen shot 2018-02-07 at 5 49 38 pm](https://user-images.githubusercontent.com/1791050/35951224-4c75bdb0-0c2f-11e8-8465-90c43c2f5011.png)

**Comment by cambraca** [comment] 2018-02-15 23:42
I can't reproduce this: https://jsfiddle.net/cambraca/n7zb8vp0/6/ (added a dashed red outline on the button for clarity).

**Comment by mikebronner** [comment] 2018-02-15 23:50
Looks the same there for me as well. This is probably a browser compatibility issue.

![screen shot 2018-02-15 at 3 49 17 pm](https://user-images.githubusercontent.com/1791050/36287136-db1d472a-1267-11e8-9437-f04ea774a040.png)

**Comment by tagliala** [comment] 2018-02-15 23:51
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a reproducible test case and specify which browser/os is affected?

Please make sure that your request follows our [bug report request template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by cambraca** [comment] 2018-02-16 16:01
I can confirm this happens in Safari 11.0.3 on macOS 10.13.3 (my previous test was in Chrome).

Apparently, adding "position:relative" to the svg element makes it show. I'm not sure this is the way to go, though, since <button>s just seem to be treated differently in Safari (the same thing happens to the button label, it looks fine in Chrome but gets cut in Safari, even if you add "overflow:visible" to the button element). I'd even argue that this is not something Font Awesome needs to deal with, but I could be convinced either way.

**Comment by tagliala** [comment] 2018-02-16 16:10
> I'd even argue that this is not something Font Awesome needs to deal with

I think the same.

This could be reproduced without FA: https://jsfiddle.net/n7zb8vp0/11/

I also doubt this is a browser issue.

I mean, if I need a 40 px icon in a 13px tall button, I should also take care of button's height and make sure it fits the content

Closing here, hope it helps

**Closed by tagliala** 2018-02-16 16:10 UTC
Labels: waiting for feedback

**Comment by mikebronner** [comment] 2018-02-16 16:20
I disagree a little on this. I think that a button should expand to fit its content if its height is not specifically set, which is the problem here.

**Comment by tagliala** [comment] 2018-02-16 16:35
@mikebronner I agree on that and that is the browser should do.

I would like to see a reproducible test case with your code, so I can better understand this issue.

By the way, if you remove line-height and height properties, the button in the example provided by @cambraca showing fine: https://jsfiddle.net/n7zb8vp0/20/

![image](https://user-images.githubusercontent.com/556268/36318333-d33ab582-133f-11e8-9462-5d8c2ab017fb.png)

Anyway, if you will keep `line-height`, this is at best a browser issue, because I can reproduce clipping without font awesome

https://jsfiddle.net/n7zb8vp0/22/

![image](https://user-images.githubusercontent.com/556268/36318324-ca981bea-133f-11e8-8aaa-de43398f0339.png)
