### ISSUE TITLE
MongoDB icon

### ISSUE THREAD

**Issue by Ibarasan** [FortAwesome/Font-Awesome#13464] opened 2018-06-30 18:49 UTC
Still missing it

**Comment by tagliala** [comment] 2018-06-30 19:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2725, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-30 19:02 UTC
