### ISSUE TITLE
Icon Request: fa-fan

### ISSUE THREAD

**Issue by RynoIT** [FortAwesome/Font-Awesome#12107] opened 2018-01-15 17:26 UTC
Can we please create a new font awesome icon that is a fan? Like this one below...

![image](https://user-images.githubusercontent.com/21248963/34954681-9117aedc-f9de-11e7-8930-7624aa94cb27.png)

**Comment by tagliala** [comment] 2018-01-15 18:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3684, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-15 18:17 UTC
