### ISSUE TITLE
Icon Request: fa-elderly

### ISSUE THREAD

**Issue by 3liee** [FortAwesome/Font-Awesome#8955] opened 2016-04-12 07:01 UTC
Hi, would it be possible to create an icon for old aged people? 
It could be quite similar to fa-blind but with a stoop and a walking stick instead of a white cane. 
We would use it for marking/tagging some entities as specific. 

Thank you!

**Comment by tagliala** [comment] 2016-04-12 09:15
Duplicate of #7183, please +1 that request

Added elderly to #7183's title

**Closed by tagliala** 2016-04-12 09:15 UTC
