### ISSUE TITLE
Icon Request: fa-barrel

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#4318] opened 2014-09-03 21:35 UTC
<img src="https://cdn0.iconfinder.com/data/icons/mobile-development-svg-icons/60/metal_barrel-512.png">

**Comment by kjacob76** [comment] 2016-02-17 17:48
+1

**Comment by otitov** [comment] 2016-03-02 09:42
+1

**Comment by bdegraaf** [comment] 2016-07-26 07:07
+1 need it

**Comment by kubikb** [comment] 2017-01-31 15:12
+1

**Comment by zsombor9** [comment] 2017-01-31 15:12
+1 
definitely need it!

**Comment by lephleg** [comment] 2018-01-12 09:56
+1 need it

**Comment by feeh27** [comment] 2018-01-12 18:34
+1

**Comment by rusttv-com** [comment] 2019-03-22 22:26
+1

**Comment by DaveC49853** [comment] 2019-04-26 14:55
+1 need it

**Comment by aethior** [comment] 2022-03-17 22:29
*Related Unicode Emoji* #222
🛢 [U+1F6E2](https://emojipedia.org/emoji/%F0%9F%9B%A2/) Oil Drum

**Comment by sensibleworld** [comment] 2024-07-11 13:50
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/14544)

**Closed by sensibleworld** 2024-07-11 13:50 UTC
Labels: new icon, energy (category), Duplicate
