### ISSUE TITLE
Icon request: icon-ban-filter

### ISSUE THREAD

**Issue by lautarobock** [FortAwesome/Font-Awesome#12083] opened 2018-01-12 14:33 UTC
I need this icon for reset filters. 
We are using a `icon-filter` to show filter options to users, but once the filter is filled we need a icon to clear it.
Here you have a graphic example
![ban-filter](https://user-images.githubusercontent.com/3920831/34879467-193fed2e-f78c-11e7-8815-4685e9cab40d.png)

Thanks!

PS: Could be named `icon-ban-funnel`

**Comment by tagliala** [comment] 2018-01-12 15:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5309, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-12 15:42 UTC

**Comment by lautarobock** [comment] 2018-01-12 15:50
ups, I didn't find with "slash". Thanks!
