### ISSUE TITLE
Icon Request: Carriage Return (Unicode 23CE)

### ISSUE THREAD

**Issue by secarica** [FortAwesome/Font-Awesome#9542] opened 2016-07-09 07:39 UTC

**Comment by tagliala** [comment] 2016-07-09 10:03
Duplicate of #1293, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Please also consider using the standard unicode point

Closing here

**Closed by tagliala** 2016-07-09 10:03 UTC
