### ISSUE TITLE
Icon Request: fa-user-tie and fa-notes

### ISSUE THREAD

**Issue by mify702** [FortAwesome/Font-Awesome#6045] opened 2015-03-23 10:59 UTC
hi, can you please make an icon user-tie and notes. please see attached sample. thanks so much.

**Comment by tagliala** [comment] 2015-03-23 11:37
user-tie: #3397

notes is a duplicate of #773  or #1986 (it depends on what you need)

Please +1 the above requests, closing here

If notes in not one of the above, feel free to comment and provide an example

**Closed by tagliala** 2015-03-23 11:37 UTC

**Comment by mify702** [comment] 2015-03-24 01:01
thank you so much for the quick reply :)

**Comment by hainguyen81** [comment] 2015-09-23 06:34
+1
