### ISSUE TITLE
Icon Request: fa-bee

### ISSUE THREAD

**Issue by joostdb** [FortAwesome/Font-Awesome#8130] opened 2015-12-09 12:57 UTC
Hi there!
Code and bees fit well together. In my spare time I'm a beekeeper and want to promote these animals as such.
I think, the icon below would serve.
So, save the bees! :-)

Thanks!

![environment_ecology_eco-03-128](https://cloud.githubusercontent.com/assets/1881777/11685852/7aeb5254-9e7c-11e5-8a9d-84a07faa4e3b.png)

**Comment by tagliala** [comment] 2015-12-09 16:18
Duplicate of #6456, please +1 that request and post there your example

**Closed by tagliala** 2015-12-09 16:18 UTC
