### ISSUE TITLE
Icon request: TYPO3

### ISSUE THREAD

**Issue by criwe** [FortAwesome/Font-Awesome#10039] opened 2016-10-08 21:17 UTC
Hi!
Would be nice to have an TYPO3-Icon: https://typo3.org/about/the-brand/style-guide/the-typo3-logo/ <- just the orange thing.
Best,
Chris

**Comment by aethior** [comment] 2016-10-09 03:51
Duplicate of #1424. Please 👍 that.

**Closed** 2016-10-09 10:57 UTC
