### ISSUE TITLE
Icon request: check-outline

### ISSUE THREAD

**Issue by sgladney** [FortAwesome/Font-Awesome#17745] opened 2021-03-17 02:57 UTC
**What can it be used for?**
when a checkmark outline is desired instead of the full checkmark

**Example image (optional)**
![image](https://user-images.githubusercontent.com/80801957/111407949-df121a80-86aa-11eb-805e-1dd1e1971469.png)
![image](https://user-images.githubusercontent.com/80801957/111407953-e2a5a180-86aa-11eb-9f6a-45ce8a63fd50.png)

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-03-17 08:51
Hi!

Thanks for being part of the Font Awesome Community.

This can be considered an edge case, but I think that this is request for a new style (outline?), since the example icon does not match existing Font Awesome style.

Also, this style should apply at least to a small subset of icons related to check (e.g., `fa-times`) and I can't figure out how `check-outline` could look like in solid state

@sensibleworld any thoughts?

**Comment by sensibleworld** [comment] 2021-04-01 16:52
I could see a check-outline in solid, but it would be a bit chunky :)

**Comment by aethior** [comment] 2022-04-18 20:58
Duplicate of #3059?

**Comment by tagliala** [comment] 2022-04-19 11:10
yes, closing here

**Closed by tagliala** 2022-04-19 11:10 UTC
Labels: waiting for feedback
