### ISSUE TITLE
Icon request: icon-harp

### ISSUE THREAD

**Issue by WebdeveloperPY** [FortAwesome/Font-Awesome#17715] opened 2021-03-10 16:06 UTC
For a new music website it would be very nice to have a **"harp" fontawesome icon**, like already exists for: guitar, piano, etc.

**Comment by tagliala** [comment] 2021-03-10 16:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5057, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-10 16:16 UTC
