### ISSUE TITLE
Icon request: icon-glasses

### ISSUE THREAD

**Issue by 4bdulll4** [FortAwesome/Font-Awesome#6092] opened 2015-03-29 00:15 UTC
new icon for glasses 

![rig6zg9bt](https://cloud.githubusercontent.com/assets/10366571/6883520/d3604842-d5c1-11e4-8dd2-525cf3010e40.png)

**Comment by tagliala** [comment] 2015-03-29 18:28
duplicate of #1043 , please +1 that request

closing here

**Closed by tagliala** 2015-03-29 18:28 UTC
