### ISSUE TITLE
The file-pdf icons are PNG

### ISSUE THREAD

**Issue by dlcohengithub** [FortAwesome/Font-Awesome#20021] opened 2023-11-29 03:28 UTC
Look at the PDF icons. They all have 'PNG' showing, even tho they are file-pdf

**Comment by Bamuel** [comment] 2023-11-29 04:39
Amazing Typo, Hopefully it gets fixed soon.

https://fontawesome.com/v6/icons/file-pdf?f=classic&s=regular
![image](https://github.com/FortAwesome/Font-Awesome/assets/6744113/a7d26424-8f4c-4cc8-b6a4-d70bb91ffbca)

**Comment by tagliala** [comment] 2023-11-29 08:13
Thanks for the report, I've assigned @sensibleworld

**Comment by tagliala** [comment] 2023-11-29 08:14
Duplicate of #20017

**Closed as completed by tagliala** 2023-11-29 08:14 UTC
Labels: bug

**Comment by Neustradamus** [comment] 2023-12-01 03:50
@sensibleworld: Thanks!
- https://fontawesome.com/icons/file-pdf
- https://fontawesome.com/icons/file-png
