### ISSUE TITLE
Icon request: flowchart 

### ISSUE THREAD

**Issue by srittau** [FortAwesome/Font-Awesome#18036] opened 2021-06-28 10:35 UTC
**What can it be used for?**
Viewing, linking to, or editing flow charts.

This was already requested in #3525, but was closed with a reference to the "sitemap" icon, which is not a good representation of a flowchart.

**Example image (optional)**

![flowchart](https://user-images.githubusercontent.com/52799/123622943-2ca33500-d80d-11eb-816f-b85555b4e137.png)

**Icon request checklist**
- [X] This is a single icon
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues), see above
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-06-28 11:31
Hi!

Thanks for being part of the Font Awesome Community.

We understand that sitemap may be not ideal to represent a flow chart, but we also would like to have examples that work in single color at small icon sizes (16px)

Anyway, this request is a duplicate of #7549, please add a 👍 reaction to that request and post there your example

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-06-28 11:31 UTC
