### ISSUE TITLE
Icon Request: fa-compare

### ISSUE THREAD

**Issue by devcorrelator** [FortAwesome/Font-Awesome#8109] opened 2015-12-07 22:05 UTC
Looking for an icon that shows we're comparing to items/records/users/etc to each other.
something similar to this:
https://www.iconfinder.com/icons/175463/compare_icon#size=128

**Comment by tagliala** [comment] 2015-12-08 10:19
Duplicate of #7616, please +1 that request

closing here

**Closed by tagliala** 2015-12-08 10:19 UTC
