### ISSUE TITLE
Icon request: icon-drill

### ISSUE THREAD

**Issue by 1mihkel** [FortAwesome/Font-Awesome#5715] opened 2015-02-19 07:57 UTC
Drill icon is quite universal and can represent all power tools or building company etc. I need it for new B2B company (for equipment tracking module).

Something like this would be perfect:
![screen shot 2015-02-19 at 9 56 29](https://cloud.githubusercontent.com/assets/11071387/6263282/9fd92d5c-b81d-11e4-8619-f4d2e20a275b.png)

**Comment by dhaupin** [comment] 2015-12-30 19:18
+1

**Comment by CarlosHAraujo** [comment] 2016-01-08 14:50
+1

**Comment by tagliala** [comment] 2016-12-02 22:06
Duplicate of #3139, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-02 22:06 UTC

**Comment by tenznhok** [comment] 2016-12-13 22:02
Is the drill-icon done? I cant find it

**Comment by tagliala** [comment] 2016-12-14 12:58
@tenznhok nope, #3139 is a request

**Comment by shanipreempt** [comment] 2019-03-25 08:53
+1
