### ISSUE TITLE
Icon request: refund-{currency}

### ISSUE THREAD

**Issue by abidingotter** [FortAwesome/Font-Awesome#14005] opened 2018-09-26 05:30 UTC
### What can it be used for?

Return money for a transaction

### Example image (optional)

Plenty of example images on Google Images.  Most involve a circular arrow around some sort of currency sign. 
[Google Image Search for 'refund icon'](https://www.google.com.au/search?q=refund+icon&safe=strict&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjwofeD99fdAhWFdd4KHaDnBW4Q_AUIDigB&biw=1920&bih=974)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-09-26 08:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10786, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-26 08:38 UTC
