### ISSUE TITLE
Icon Request: fa-discord

### ISSUE THREAD

**Issue by davidvkimball** [FortAwesome/Font-Awesome#11297] opened 2017-07-16 15:39 UTC
Hey Font Awesome! 

I'd love for you to include a Discord icon. The intend would be to link to personal or public Discord servers. Here's the Discord icon for reference: https://discordapp.com/branding 

Thanks in advance! 

Cheers,

David

**Comment by tagliala** [comment] 2017-07-16 16:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-16 16:00 UTC
