### ISSUE TITLE
Icon Request: horoscope

### ISSUE THREAD

**Issue by Predoklesec** [FortAwesome/Font-Awesome#1760] opened 2013-08-13 09:41 UTC
Hi awesome people :D
I think it would be cool if there were horoscope icons :) I would use them ;)

Cheers, K

**Comment by lsmoura** [comment] 2016-03-16 13:10
+1 on this - I could use the icons...

**Comment by Cow258** [comment] 2019-02-15 04:27
+1 on this - I could use the icons...

**Comment by sensibleworld** [comment] 2024-07-11 15:55
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/2831)

**Closed by sensibleworld** 2024-07-11 15:55 UTC
Labels: new icon, web application icons (legacy category), Duplicate
