### ISSUE TITLE
Icon request: icon-circle-half

### ISSUE THREAD

**Issue by sri-omg** [FortAwesome/Font-Awesome#1532] opened 2013-07-09 23:45 UTC
I need a half empty circle to match the half empty star. icon-adjust is _almost_ exactly what I'm looking for, except the wrong half of the circle is filled in.

I want to use the circles (full, half, empty) for podcast episode play status. Favorite podcasts would then have a full/half/empty star to match.

**Comment by tagliala** [comment] 2020-09-02 20:09
Duplicate of #528

**Closed by tagliala** 2020-09-02 20:09 UTC
Labels: new icon, web application icons
