### ISSUE TITLE
Icon request: fa-cc-union-pay

### ISSUE THREAD

**Issue by kirazhy** [FortAwesome/Font-Awesome#11048] opened 2017-05-10 09:40 UTC
my website needs to show some payments,thx

**Comment by tagliala** [comment] 2017-05-10 09:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4561, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-10 09:51 UTC
