### ISSUE TITLE
Icon request: icon-simcard

### ISSUE THREAD

**Issue by dominion666** [FortAwesome/Font-Awesome#8363] opened 2016-01-18 14:32 UTC
Hello,

I need an icon which represent a simcard like this one
![100782-200](https://cloud.githubusercontent.com/assets/16760632/12393836/98c9f168-bdf8-11e5-9abc-2ba27e370b47.png)
Thank you !

**Comment by tagliala** [comment] 2016-01-18 14:59
duplicate of #2445, please +1 that request and post there your example

closing here

**Closed by tagliala** 2016-01-18 14:59 UTC
