### ISSUE TITLE
Icon Request: fa-podcast

### ISSUE THREAD

**Issue by ericrovtar** [FortAwesome/Font-Awesome#9912] opened 2016-09-13 17:59 UTC
## Use Cases
This icon would be used along other social media icons like Facebook, Twitter, etc, to link to our podcast channel in iTunes.

The icon would be great to have variants similar to other social media icons with inverses and shapes surrounding the image.

## Icon
![512x512bb](https://cloud.githubusercontent.com/assets/3474545/18485224/ffe9b996-79b9-11e6-840b-cd3f93644925.jpg)

**Comment by aethior** [comment] 2016-09-13 22:39
Duplicate of #2125. Please :+1:  that request.

**Closed** 2016-09-14 09:56 UTC
