### ISSUE TITLE
Create a font only for Brand Icons

### ISSUE THREAD

**Issue by alejonext** [FortAwesome/Font-Awesome#8756] opened 2016-03-15 07:02 UTC
I think it's time to divide, font awesome. 

* Icons  awesome
* Brands Icons

There are already many brands in font. To use the icons, they really are necessary, even to website or an app. I am proposing to create a single comprehensive source for brands. 

Of course, that is a subproject of font awesome!!!

**Comment by tagliala** [comment] 2016-03-15 09:50
This was already done in Font Awesome Black Tie, please take a look at #7598

Duplicate of #1322

Closing here

**Closed by tagliala** 2016-03-15 09:50 UTC
