### ISSUE TITLE
Icon request: icon-smiley-filled

### ISSUE THREAD

**Issue by hugomiura** [FortAwesome/Font-Awesome#9612] opened 2016-07-21 14:13 UTC
I am sending you the SVG for a smiley (in negative perspective).

Here is an example: 

`<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="143.422px" height="143.426px" viewBox="0 0 143.422 143.426" enable-background="new 0 0 143.422 143.426"
	 xml:space="preserve">
<g id="background">
</g>
<g id="objects">
	<path fill-rule="evenodd" clip-rule="evenodd" fill="#FFD400" d="M143.422,71.712c0,39.606-32.1,71.714-71.709,71.714
		S0,111.319,0,71.712C0,32.105,32.104,0,71.713,0S143.422,32.105,143.422,71.712z"/>
	<g>
		<path fill="#FFF" d="M71.713,109.561c-17.047,0-32.63-10.051-39.703-25.605c-0.635-1.396-0.018-3.044,1.378-3.679
			c1.395-0.636,3.043-0.016,3.678,1.378c6.174,13.578,19.774,22.351,34.647,22.351c14.867,0,28.465-8.773,34.643-22.351
			c0.636-1.395,2.289-2.011,3.678-1.378c1.396,0.635,2.013,2.282,1.378,3.679C104.335,99.51,88.752,109.561,71.713,109.561z"/>
	</g>
	<g>
		<circle fill-rule="evenodd" clip-rule="evenodd" fill="#FFF" cx="49.301" cy="56.024" r="7.174"/>
		<path fill-rule="evenodd" clip-rule="evenodd" fill="#FFF" d="M101.295,56.024c0,3.96-3.208,7.172-7.172,7.172
			c-3.964,0-7.172-3.212-7.172-7.172s3.208-7.172,7.172-7.172C98.087,48.852,101.295,52.063,101.295,56.024z"/>
	</g>
</g>
</svg>`

**Comment by tagliala** [comment] 2016-07-21 14:29
Duplicate of #1681, please add a 👍  reaction to that request

Please post there your svg example

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-21 14:29 UTC
