### ISSUE TITLE
Icon-request: apple-tv

### ISSUE THREAD

**Issue by jeremyhardwick** [FortAwesome/Font-Awesome#16941] opened 2020-07-21 14:04 UTC
**What can it be used for?**
Brand category

**Example image (optional)**
![AppleTV-iOS](https://user-images.githubusercontent.com/68600110/88064591-1a1a7900-cb31-11ea-87fe-0212831c3660.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-07-21 15:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7407, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-07-21 15:28 UTC
