### ISSUE TITLE
Icon request: Glassdoor logo

### ISSUE THREAD

**Issue by corriespondent** [FortAwesome/Font-Awesome#14202] opened 2018-10-31 13:42 UTC
### What can it be used for?

Similar to LinkedIn and Facebook and other brand logos, to use the Glassdoor logo in applications and websites.

### Example image (optional)

https://www.glassdoor.com/about-us/press/media-assets/

**Comment by tagliala** [comment] 2018-10-31 22:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6422, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-31 22:09 UTC
