### ISSUE TITLE
fa-teacher

### ISSUE THREAD

**Issue by orjanb-ne** [FortAwesome/Font-Awesome#10816] opened 2017-03-21 08:45 UTC
I'd like an icon for teachers (both male and female so neutral would be best).
Something like this:
![e9d28a05b39b987cc740738346615d59](https://cloud.githubusercontent.com/assets/22000464/24139093/0f1b0aa0-0e1b-11e7-9aa9-dfd9f75a1077.png)

**Comment by tagliala** [comment] 2017-03-21 09:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4079, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-21 09:52 UTC
