### ISSUE TITLE
Icon Request: fa-rural car

### ISSUE THREAD

**Issue by 13sotos** [FortAwesome/Font-Awesome#11587] opened 2017-10-04 11:34 UTC
if you can add this icon ty very much

**Comment by tagliala** [comment] 2017-10-04 12:45
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example? (single color, suitable for 16px icon size)

**Comment by 13sotos** [comment] 2017-10-22 20:15
![93126_car_512x512](https://user-images.githubusercontent.com/32513049/31865881-f2ad93d4-b77e-11e7-90c0-1d085b5c77b5.png)

**Comment by tagliala** [comment] 2017-10-22 23:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11376 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-22 23:00 UTC
Labels: waiting for feedback
