### ISSUE TITLE
Icon Request: fa-shopify

### ISSUE THREAD

**Issue by andregomars** [FortAwesome/Font-Awesome#10968] opened 2017-04-19 21:17 UTC

**Comment by tagliala** [comment] 2017-04-19 21:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3850, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-19 21:29 UTC
