### ISSUE TITLE
Icon Request: fa-peso psd

### ISSUE THREAD

**Issue by ChardPogs** [FortAwesome/Font-Awesome#10325] opened 2016-12-07 10:54 UTC
Peso please!! :)

**Comment by tagliala** [comment] 2016-12-08 13:21
Duplicate of #1267 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-08 13:21 UTC
