### ISSUE TITLE
autoReplaceSvg: 'nest' causes infinite replacement (SVG+JS, FontAwesome 6 beta)

### ISSUE THREAD

**Issue by TimFL** [FortAwesome/Font-Awesome#18143] opened 2021-08-05 09:17 UTC
**Describe the bug**
autoReplaceSvg: 'nest' causes infinite replacement of i Tag content. autoReplaceSvg: true works like a charm.

**To Reproduce**
Use the latest FA6 Beta SVG+JS and change your configuration to autoReplaceSvg:'nest'.
This basic vanilla site reproduces the issue on all of my browsers. Changing to FA5 (latest) does not produce the issue (works as intended, don't forget to switch to `fas` from `fa-solid`).
```
<html lang="en">
  <head>
    <meta http-equiv="expires" content="0">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>test</title>
  </head>
  <body>
    <i class="fa-solid fa-user"></i>
    <script>
      FontAwesomeConfig = { autoReplaceSvg: 'nest' }
    </script>
    <script defer src="../fa6/js/all.min.js"></script>
  </body>
</html>
```

**Expected behavior**
It should only replace when the watched attributes change.

**Screenshots**
![renderbug](https://user-images.githubusercontent.com/5175033/128323089-31cc54ba-a47f-4aa7-a9e8-cd5ccdefd0c6.png)
(Screen from our beta build of a React Application, but the above vanilla page reproduction code does also have the issue)
The highlighted `i` signals that the Tag is constantly being updated. The `svg` nested within is constantly being replaced by a new svg Tag.

**Version and implementation**
Version: 6.0.0-beta1
Browser and version: 
Reproduced on the following (all 64-Bit):
- Microsoft Edge 92.0.902.62
- Firefox 90.0.2
- Google Chrome 92.0.4515.131

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by TimFL** [comment] 2021-08-05 09:52
I just noticed there is a similar issue in the Pro repository (and this seems to be the wrong place). Will leave it up due to reproduction code and notes.

**Comment by tagliala** [comment] 2021-08-05 10:20
Hi @TimFL, let's leave this open also here for tracking purposes

**Comment by justinkruit** [comment] 2021-08-05 10:44
I indeed posted my issue on the Pro version on GitHub, as I associated the beta with Pro. But maybe here I can ask for a progress update on this bug, as I'd love to start using the beta in new products, but the nested is required for some items

**Comment by Gonzo2O28** [comment] 2021-08-12 11:29
Same for me. "Nest" does not work.
i had to use "nest" or rewrite my css from targeting "i" to "svg".

**Comment by Gonzo2O28** [comment] 2021-08-18 11:11
Any news on this?

**Comment by Gonzo2O28** [comment] 2021-09-03 16:45
Does anyone of the officials read this stuff here?

**Comment by tagliala** [comment] 2021-09-03 18:29
Hi, this has been fixed in beta 2, no ETA yet for release

**Comment by Gonzo2O28** [comment] 2021-09-03 20:15
Thank you.
Can you tell mich which lines to fix anyway?
Otherwise i cannot test this out in my project without rewriting all my css.

Thanks!

**Comment by tagliala** [comment] 2021-09-04 08:30
Welcome. Unfortunately the fix is not a one line and it needs to be applied to a couple of source files that are not part of the final `.js`

Let's ask @robmadole

**Comment by Gonzo2O28** [comment] 2021-09-16 19:58
News?

**Comment by stap123** [comment] 2022-02-24 17:27
Upgrading to 6.0.0 breaks this functionality for us (currently working on 5.15.4

**Comment by tagliala** [comment] 2022-02-24 17:44
@stap123 could you please clarify?

**Comment by stap123** [comment] 2022-02-24 19:16
Yeah, sorry, the `autoReplaceSvg: 'nest'` option just isn't working for us after we upgrade. We use the below with v5x and the icons update as expected but after upgrading to v6x the icons are no longer updated. The only thing we are doing is changing the all.min.js file from the 5x version to the 6x one and it stops working. If you need more info, let me know. 

```
<script>
    FontAwesomeConfig = { autoReplaceSvg: 'nest' }
</script>
```

*NB: Pretty sure it's not relevant here because the old one works and no other are changes being made but we are running it in a Blazor WASM project*

**Comment by tagliala** [comment] 2022-02-24 19:34
> NB: Pretty sure it's not relevant here

If this is not relevant here, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md). Please also provide a reproducible test case

I cannot reproduce here: https://jsfiddle.net/tagliala/bfa6uhse/25/

PS: note that order matters, so the configuration should be set before you load Font Awesome. Also, you can use data attribute to avoid inline script by adding `data-auto-replace-svg="nest"`

docs: https://fontawesome.com/v5/docs/apis/javascript/configuration#setting-the-configuration

**Comment by tagliala** [comment] 2022-02-25 08:00
Closing here

**Closed by tagliala** 2022-02-25 08:00 UTC
Labels: bug, svg, 6.x
