### ISSUE TITLE
Icon Request: fa-sail-boat

### ISSUE THREAD

**Issue by developius** [FortAwesome/Font-Awesome#7583] opened 2015-10-01 12:02 UTC
Firstly, thank you for such an awesome job with FA!
Would it be possible to have a sailing boat like icon?
Something like this but `Awesome`!
![image](https://cloud.githubusercontent.com/assets/5836587/10220048/1640d426-683c-11e5-82b0-1e29501f7638.png)
Credit http://images.clipartpanda.com/sailboat-silhouette-sailboatlarge-500x500.jpg

**Comment by caduvieira** [comment] 2015-10-01 12:35
dupe of #5079?

**Closed** 2015-10-01 13:39 UTC

**Comment by developius** [comment] 2015-10-01 15:20
Sorry, didn't see that one @caduvieira
