### ISSUE TITLE
Icon request: viking-helmet

### ISSUE THREAD

**Issue by ginolatilla123** [FortAwesome/Font-Awesome#15574] opened 2019-09-20 07:59 UTC
**What can it be used for?**
Hello!
I'd like have the Viking Helmet as new icon, it could be... Awesome! :-)

**Example image (optional)**
I found an example of helmet online but feel free to make it as you prefer!
![viking](https://user-images.githubusercontent.com/50326692/65309811-23dbf480-db8d-11e9-8366-1e9f5b604566.jpg)

**Comment by tagliala** [comment] 2019-09-20 08:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15165, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-20 08:05 UTC
