### ISSUE TITLE
ERR_INSECURE_RESPONSE error when going to https://use.fontawesome.com/c9f66ac4f1.js

### ISSUE THREAD

**Issue by hshroff** [FortAwesome/Font-Awesome#11185] opened 2017-06-15 12:50 UTC
We're getting ERR_INSECURE_RESPONSE error when going to https://use.fontawesome.com/c9f66ac4f1.js

This worked fine up until this morning arount 8:00am EST.

Looks like the SSL certificate is invalid or expired.

**Comment by tagliala** [comment] 2017-06-15 13:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11183. It should be resolved.

If it isn't for you please comment on the above issue

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-15 13:13 UTC

**Comment by hshroff** [comment] 2017-06-15 14:10
Confirmed this is working again.  Thanks for the quick response and resolution.
