### ISSUE TITLE
Icon Request: fa-baseball

### ISSUE THREAD

**Issue by hansenhouse** [FortAwesome/Font-Awesome#11830] opened 2017-12-04 01:12 UTC
Would like to see an icon of a baseball created. I would like to use it on a baseball travel team site.

You guys do a great job and your efforts are really appreciated. 

Thanks!

**Comment by tagliala** [comment] 2017-12-04 11:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6438 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-12-04 11:57 UTC
