### ISSUE TITLE
Icon Request: fa-conspiracy

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7939] opened 2015-11-20 06:39 UTC
Request for fa-conspiracy (can alias to fa-cons)

![fa-conspiracy](http://i.imgur.com/bD7hSDN.png)

**Comment by caduvieira** [comment] 2015-11-20 10:30
Dupe of #5713
please +1 that one

**Comment by tagliala** [comment] 2015-11-20 10:44
Please also post there your example

**Closed by tagliala** 2015-11-20 10:44 UTC
