### ISSUE TITLE
Icon Request: fa-redmine

### ISSUE THREAD

**Issue by maicoamachado** [FortAwesome/Font-Awesome#9488] opened 2016-06-28 18:07 UTC
Hello, I have a suggestion to create an icon in Redmine format. :)

http://www.redmine.org/projects/redmine/wiki/Logo

**Comment by tagliala** [comment] 2016-06-28 18:34
Duplicate of #1787, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-28 18:34 UTC
