### ISSUE TITLE
Icon request: 3d SLA printer icon 

### ISSUE THREAD

**Issue by LeeOtts** [FortAwesome/Font-Awesome#19183] opened 2022-07-10 23:57 UTC
### Use case

3d SLA printing has become cheaper and gaining attention. But you need a specific use case.. I need one for the menu on my react portfolio page showing off 3d SLA printed designs. Currently using <i class="fa-solid fa-chart-scatter-3d"> but would love to use a <i class="fa-solid fa-3dprinter-sla"></i> that could convey the message easier

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2022-07-11 07:27
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #7625? If it isn't could you please provide an example and clarify why it is different?

**Comment by NikilXYZ** [comment] 2023-03-21 21:11
SLA printers don't extrude like more common 3D printers do. 

More common 3D printers are basically a moving hot glue gun. 
![image](https://user-images.githubusercontent.com/65924881/226741720-5a681e35-fd1d-4a2b-a6ff-00bf5a5112e5.png)


SLA printers shine a (UV) light into a goopy resin, so the part comes out solidified kind of terminator style.
![image](https://user-images.githubusercontent.com/65924881/226741444-26f3bcc6-a99a-4850-acdf-73da83a5dca2.png)
 
SLA printers typically look like a base with a translucent lid so that the UV rays don't escape out.

Usually parts in SLA printers are pulled out of the vat, so they are hung upside down.
In FDM, there's no vat, so the part is grown on the bed

**Comment by sensibleworld** [comment] 2024-07-11 15:10
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed as not planned by sensibleworld** 2024-07-11 15:10 UTC
Labels: new icon, waiting for feedback, Declined
