### ISSUE TITLE
Icon request: Mixer Brand Icon

### ISSUE THREAD

**Issue by twittv** [FortAwesome/Font-Awesome#13624] opened 2018-07-25 17:53 UTC
Mixer is Microsoft's competition for Twitch.tv and is at https://mixer.com/

On our internal systems, I use the Twitch icon when I link to our TWiT.tv stream on Twitch, but I'd like to be able to use the Mixer icon (it's a stylized "X") for the link to Mixer rather than having to settle for a generic "Play" icon.  Mixer's platform seems to be growing fast as a Twitch alternative, so I can only imagine that more folks will find this useful in the near future.

Their icon: https://mixer.com/_latest/assets/images/main/logos/merge.svg  (Part is white, so it won't show up great on a white background.)

**Comment by tagliala** [comment] 2018-07-25 19:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11242, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-25 19:54 UTC
