### ISSUE TITLE
Icon Request: fa-file-search-o

### ISSUE THREAD

**Issue by ajones4** [FortAwesome/Font-Awesome#6777] opened 2015-06-18 00:33 UTC
Firstly - thank you for this service, it is great :)

I've gathered a set of icons to use in online course development but struggle to find one to indicate assessment items, so have developed my own (attached).

Cases:
- to flag online course materials that are assessment items
- also to be used in supplementary course material developed in MS Office using fontawsome

Thanks for considering my request. I look forward to hearing if it is a valid inclusion. 

Cheers Anita
  
![assessment](https://cloud.githubusercontent.com/assets/12944329/8221668/7f18cc00-15a4-11e5-90be-f7c1b02bc00e.png)

**Comment by nyon** [comment] 2015-06-19 14:07
fa-file-search is part of my github project: https://github.com/nyon/fontawesome-actions

**Comment by tagliala** [comment] 2015-06-21 10:35
@nyon thanks

refers to #1181

**Comment by tagliala** [comment] 2015-07-01 09:46
just noticed that this is a duplicate of #6190

I'm closing here and edit #6190 title to include fa-file-search-o

**Closed by tagliala** 2015-07-01 09:46 UTC
Labels: new icon, web application icons
