### ISSUE TITLE
Icon Request: fa-rollerskate

### ISSUE THREAD

**Issue by LKian** [FortAwesome/Font-Awesome#12391] opened 2018-02-19 23:06 UTC
Rollerskates!  Because we're bringing the 90s back!

**Comment by tagliala** [comment] 2018-02-20 11:26
Hi!

Thanks for being part of the Font Awesome Community.

I think this is a duplicate of #5450. Could you please confirm?

If it is, please 👍  that request

**Closed** 2019-12-17 06:13 UTC
Labels: waiting for feedback
