### ISSUE TITLE
Icon request: Flatbed Truck (Towing Truck)

### ISSUE THREAD

**Issue by sbshara** [FortAwesome/Font-Awesome#9755] opened 2016-08-15 07:16 UTC
Dears,

Could you please advise if you can add an icon that represents a flatbed truck into your library.

I'm providing below two links showing a vectors representing the two kinds of towing trucks:

1) https://d30y9cdsu7xlg0.cloudfront.net/png/50002-200.png
2) http://www.clipartkid.com/images/224/tow-truck-clip-art-tow-truck-2-gregory-s-den-art-tow-tow-truck-jFzCe1-clipart.jpg

We're planning to use these icons in our company website, and it would be great help if we had these icons.

Thank you.

**Comment by tagliala** [comment] 2016-08-15 08:49
Duplicate of #543 and #4972, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-15 08:49 UTC
