### ISSUE TITLE
Icon Request: icon-wagon

### ISSUE THREAD

**Issue by bbolcsa** [FortAwesome/Font-Awesome#19022] opened 2022-05-09 08:14 UTC
Please create this icon for us!
We would like to use it on csempe-shop.hu as a material icon for our tiles.

![noun-wagon-2373643](https://user-images.githubusercontent.com/105200693/167368516-c6ee728e-9d1f-4b98-a69a-475e93f375e3.svg)

**Comment by aethior** [comment] 2022-05-09 17:53
Hi @bbolcsa,

Duplicate of #8867.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed as completed** 2022-05-28 15:25 UTC
