### ISSUE TITLE
Icon Request: fa-ecus

### ISSUE THREAD

**Issue by KermadecI** [FortAwesome/Font-Awesome#6167] opened 2015-04-06 10:12 UTC
Hi,
I need this web icon too.
Sorry for the hard work, I'm looking to do a electronic site and I need it.
Thanks miles for all the work.
Regards
Matteo Andreatta
P.s.: If you need the vector images I have them (speaking of the other two issue i send first)
![ecus](https://cloud.githubusercontent.com/assets/11716776/7003139/32efaede-dc56-11e4-98da-3e4ab0146513.jpg)

**Comment by tagliala** [comment] 2015-04-09 12:47
is this an integrated circuit? #5319

**Comment by tagliala** [comment] 2022-03-13 14:01
I'm going to consider this a duplicate of #16820, which has more +1s

If this is not correct, feel free to fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2022-03-13 14:01 UTC
Labels: waiting for feedback
