### ISSUE TITLE
Icon Request: fa-DataVisual

### ISSUE THREAD

**Issue by mmaharaja** [FortAwesome/Font-Awesome#10905] opened 2017-04-07 05:16 UTC
could you please add below icon immediate 

![image](https://cloud.githubusercontent.com/assets/26995114/24786421/f1c38056-1b7e-11e7-8383-634acca77b0b.png)

**Comment by tagliala** [comment] 2017-04-07 07:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7523, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-07 07:06 UTC
