### ISSUE TITLE
Icon request: map-layers

### ISSUE THREAD

**Issue by Conrad777** [FortAwesome/Font-Awesome#13271] opened 2018-06-04 08:09 UTC
Hi,

Maybe I am just overlooking this icon, but I can't seem to find it. It is pretty common for a map to have  layers in which case an icon like this https://material.io/tools/icons/?search=layers&icon=layers&style=baseline would be very handy.

**Comment by tagliala** [comment] 2018-06-04 08:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1179 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-04 08:51 UTC
