### ISSUE TITLE
Icon request: baby-bottle

### ISSUE THREAD

**Issue by ccappella-bcbsma** [FortAwesome/Font-Awesome#16011] opened 2020-01-02 17:59 UTC
Single icon for use on healthcare sites for new mothers when discussing nursing/pumping.

Example:
![baby-botle](https://user-images.githubusercontent.com/59449052/71683127-aca72680-2d5f-11ea-86b5-33e7c0b16ce8.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-01-02 18:18
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12752, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-02 18:18 UTC
