### ISSUE TITLE
Icon Request: Balloon(s)

### ISSUE THREAD

**Issue by Gnate** [FortAwesome/Font-Awesome#4211] opened 2014-08-24 02:08 UTC
For, you know, parties.  One, Two, Three would be nice.

**Comment by felipefrancisco** [comment] 2015-06-26 16:54
+1

**Comment by MVcodeartbr** [comment] 2015-11-27 14:55
+1

**Comment by MVcodeartbr** [comment] 2015-11-27 14:55
releted or dupe of #3398 ?

**Comment by tagliala** [comment] 2015-11-27 15:38
@MVcodeartbr thanks

Closing here as a duplicate of #3398

**Closed by tagliala** 2015-11-27 15:38 UTC
Labels: new icon, web application icons
