### ISSUE TITLE
FontAwesome 6 BETA - Animations do not function on iOS 14.6

### ISSUE THREAD

**Issue by jledgett** [FortAwesome/Font-Awesome#17943] opened 2021-05-26 20:48 UTC
**Describe the bug**
In FontAwesome 6, the animations do not function on iOS 14.6

**To Reproduce**
https://fontawesome.com/v6.0/docs/web/style/animate

This was experienced on an iPhone 12 Pro

**Expected behavior**
Animations should work on iOS too.  :-)

**Screenshots**

**Version and implementation**
Version: 6 Beta
Browser and version: Safari on iOS 14.6

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x ] I have filled out as much of the above information as I can
- [ x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2021-05-26 21:37
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Can't confirm

iOS 14.6 / iPhone 12 Pro / Safari (and Chrome, fwiw)

**Comment by jledgett** [comment] 2021-05-26 21:50
Tested Chrome and Edge on it to -- same behavior, no animation.    I believe all use the same rendering engine on iOS.  I also tried turning off "Prefer Reduced Motion" in iOS and still same issue.

**Comment by tagliala** [comment] 2021-05-27 11:01
> I also tried turning off "Prefer Reduced Motion" in iOS and still same issue.

Thanks. I confirm that after enabling "Reduce Motion" under Settings => Accessibility => Motion, the animations don't work. But this is expected behavior, since it is a user preference for accessibility.

Switching back the feature 

Closing here, but feel free to comment if you can provide a reproducible bug

Recorded on iPhone 12 Pro / 14.6 / Safari

(15 fps low quality gif)

![RPReplay_Final1622112908 MP4](https://user-images.githubusercontent.com/556268/119815187-90270380-beeb-11eb-8090-f8ae2eb7feb0.gif)

**Closed by tagliala** 2021-05-27 11:01 UTC
Labels: waiting for feedback
