### ISSUE TITLE
Icon Request: fa-bbm

### ISSUE THREAD

**Issue by ezil91** [FortAwesome/Font-Awesome#10110] opened 2016-10-24 08:37 UTC
icon for blackberry messenger

**Comment by tagliala** [comment] 2016-10-24 09:03
Duplicate of #2189 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-24 09:03 UTC
