### ISSUE TITLE
Icon Request: Yammer Social Media Network

### ISSUE THREAD

**Issue by lucanos** [FortAwesome/Font-Awesome#9841] opened 2016-08-31 08:57 UTC
Had a recent job where the owner wanted to have Social Media sharing to Yammer (Microsoft's Enterprise Social Media Network). Attached are a grey version of the logo in PNG and SVG (in ZIP due to Github file restrictions).

![yammar_grey_large](https://cloud.githubusercontent.com/assets/126774/18122389/921fe384-6fac-11e6-9621-9ad231ee4f3b.png)

[yammar_grey_large.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/446779/yammar_grey_large.svg.zip)

**Comment by tagliala** [comment] 2016-08-31 10:59
Duplicate of #2707, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-31 10:59 UTC
