### ISSUE TITLE
Icon Request: fa-digitalocean

### ISSUE THREAD

**Issue by iatpatelishan** [FortAwesome/Font-Awesome#10806] opened 2017-03-18 14:17 UTC
DigitalOcean.com's icon

**Comment by tagliala** [comment] 2017-03-18 14:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5419, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-18 14:37 UTC
