### ISSUE TITLE
Icon Request: icon-mobile-notification (apple style)

### ISSUE THREAD

**Issue by alexrada** [FortAwesome/Font-Awesome#2865] opened 2014-02-10 12:10 UTC
Similar with the icons that appear on mobile apps when you have a notification.

![image](https://user-images.githubusercontent.com/556268/37396911-8da867cc-277a-11e8-816c-03d4f8ebfbfc.png)

**Comment by sensibleworld** [comment] 2024-07-11 13:56
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/6609)

**Closed by sensibleworld** 2024-07-11 13:56 UTC
Labels: new icon, web application icons (legacy category), Duplicate
