### ISSUE TITLE
Icon Request: fa-finance-save (fa-finance-piggy)

### ISSUE THREAD

**Issue by ITPrism** [FortAwesome/Font-Awesome#7582] opened 2015-10-01 08:11 UTC
Hi friends,
Thank you very much for the great icons. They are really useful for me.
I would like to ask you to include an icon that presents saving ( a small pig ).

![piggy](https://cloud.githubusercontent.com/assets/1272206/10215688/650e56b0-682c-11e5-9f32-4908c47988d3.png)

Thank you in advance,
Todor

P.S.
It could be part of set with [financial icons] (https://www.iconfinder.com/iconsets/finance-16) that we can use in crowdfunding applications or other financial applications.

**Comment by caduvieira** [comment] 2015-10-01 11:47
dupe of #1413
+1 that request

**Closed** 2015-10-01 11:53 UTC

**Comment by ElielBarone** [comment] 2016-03-07 18:29
+1

**Comment by Webinsane** [comment] 2016-07-19 17:09
+1

**Comment by fr1ts** [comment] 2017-10-17 11:26
+1 :-)
