### ISSUE TITLE
icon request: icon-schedule

### ISSUE THREAD

**Issue by admstr** [FortAwesome/Font-Awesome#18918] opened 2022-04-18 16:50 UTC
icon request: icon-schedule
![image](https://user-images.githubusercontent.com/103953390/163842555-924b283c-0ec9-4771-bf2d-f6e3e7cc8827.png)

**Comment by tagliala** [comment] 2022-04-18 17:08
Hi!

Thanks for being part of the Font Awesome Community.

Duplicate of #8158, available in FA 6.0 Pro

Ref for FA Free: https://github.com/FortAwesome/Font-Awesome/issues/8158#issuecomment-1061704578

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed as completed by tagliala** 2022-04-18 17:08 UTC
