### ISSUE TITLE
Strava Icon

### ISSUE THREAD

**Issue by tylerqford** [FortAwesome/Font-Awesome#9079] opened 2016-04-28 22:35 UTC
Can you add the Strava icon to your images?

https://www.google.com/search?q=strava+website&espv=2&biw=1920&bih=979&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi5_qOLsrLMAhVJ6WMKHTwrA5QQ_AUIBigB#tbm=isch&q=strava+images

**Comment by tagliala** [comment] 2016-04-28 22:50
Duplicate of #3313 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-28 22:50 UTC
