### ISSUE TITLE
Icon request: icon-read or icon-seen (as in whatsapp)

### ISSUE THREAD

**Issue by tuia** [FortAwesome/Font-Awesome#6514] opened 2015-05-19 15:06 UTC
![Image of icon](http://kuwaitiful.com/wp-content/uploads/2014/11/whats-app-new-notification-system.jpg)

**Comment by tagliala** [comment] 2015-05-19 15:14
duplicate of #3975, please +1 that request

you will also find a workaround

closing here

**Closed by tagliala** 2015-05-19 15:14 UTC
