### ISSUE TITLE
Icon request: fa-reorder

### ISSUE THREAD

**Issue by rsshilli** [FortAwesome/Font-Awesome#18477] opened 2021-11-30 20:39 UTC
**What can it be used for?**
Our users are a little clumsy and leaving grips lying around means people accidentally re-order things sometimes. So we're making re-ordering a little more explicit. The user needs to click a button to enter "re-ordering" mode.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/2487045/144124239-4e5845cb-6c59-4454-a8c5-bfb7116aa35a.png)

**Icon request checklist**
- [ X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X ] I have included at least one example image if it could be helpful (optional)
- [ X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-11-30 22:23
Hi!

Thanks for being part of the Font Awesome Community.

Maybe [fa-sort](https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=arrows&s=solid&m=free) fits this use case

This is a vertical version of the existing [fa-exchange-alt](https://fontawesome.com/v5.15/icons/exchange-alt?style=solid), so I'm going to consider this a duplicate of #8586, please add a 👍 reaction to that request.

By using `fa-rotate-90`, it is also possible to achieve that icon right now: https://jsfiddle.net/tagliala/vf0besm4/1/

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here, but feel free to comment if I've missed something

**Closed by tagliala** 2021-11-30 22:23 UTC
