### ISSUE TITLE
Icon Request: fa-hand

### ISSUE THREAD

**Issue by MMokhtari** [FortAwesome/Font-Awesome#5922] opened 2015-03-10 21:34 UTC

**Comment by tagliala** [comment] 2015-03-11 10:15
Could you please provide an example?

**Comment by MMokhtari** [comment] 2015-03-16 20:29
Here is one : 
![hand_cursor](https://cloud.githubusercontent.com/assets/9805952/6675801/877a3066-cc23-11e4-9c5c-0a023b4877b9.png)

**Comment by tagliala** [comment] 2015-03-16 20:34
duplicate of #1651 , please +1 that request

closing here

**Comment by tagliala** [comment] 2015-03-16 20:34
please also post there your example

**Closed by tagliala** 2015-03-16 20:34 UTC
Labels: waiting for feedback
