### ISSUE TITLE
Icon request: fab-google-recaptcha

### ISSUE THREAD

**Issue by JustinObm** [FortAwesome/Font-Awesome#16270] opened 2020-03-04 14:47 UTC
**What can it be used for?**
Recaptcha is Google's "I'm not a robot" validation tool.

This could be used as an inline icon when displaying error messages to users.
Used in training and help guides about how to use an application.
Administrative pages to enable or disable recaptcha on a form.

**Example image (optional)**
https://upload.wikimedia.org/wikipedia/commons/a/ad/RecaptchaLogo.svg

**Comment by tagliala** [comment] 2020-03-04 17:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14235, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-04 17:23 UTC
Labels: brand icon
