### ISSUE TITLE
Icon request: icon-partners

### ISSUE THREAD

**Issue by 4rtuu** [FortAwesome/Font-Awesome#8757] opened 2016-03-15 13:48 UTC
A 'partners' icon would be nice.
`<img src="http://www.blumidia.com/images/parceria.jpg" />`
Something like this.

Regards,
Me.

**Comment by tagliala** [comment] 2016-03-15 18:55
duplicate of #878 , planned for 5.0.0 release but please +1 that request the same

closing here

**Closed by tagliala** 2016-03-15 18:55 UTC
