### ISSUE TITLE
Icon Request: fa-new

### ISSUE THREAD

**Issue by Chahat08** [FortAwesome/Font-Awesome#17760] opened 2021-03-22 15:08 UTC
An icon with the word "NEW" written on it.

Use cases: We can simply put the icon at places where we have to display new items on our website as a means of catching the users' attention.

![new-icon](https://user-images.githubusercontent.com/44064355/112011443-4833db00-8b4e-11eb-8f1e-cc672e40b02b.png)

**Comment by tagliala** [comment] 2021-03-22 15:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11002, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Also, we try to avoid icons with text, and we provide an official example to create an icon with "New" text stacked on top of it: https://fontawesome.com/how-to-use/on-the-web/styling/layering

Closing here

**Closed by tagliala** 2021-03-22 15:20 UTC
