### ISSUE TITLE
Icon Request: fa-pregnant

### ISSUE THREAD

**Issue by LindaStern** [FortAwesome/Font-Awesome#9913] opened 2016-09-14 09:07 UTC
It would be nice to have an icon: woman with pregnant belly :) Thank you.

**Comment by tagliala** [comment] 2016-09-14 09:57
Duplicate of #1819, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-14 09:57 UTC
