### ISSUE TITLE
icon request: fa-num-0 to fa-num-9

### ISSUE THREAD

**Issue by sarbudeenmca** [FortAwesome/Font-Awesome#11767] opened 2017-11-17 19:16 UTC
![188233-numbers](https://user-images.githubusercontent.com/22979292/32964639-df0f9022-cbf9-11e7-83ac-686fed23a9f9.png)

**Comment by tagliala** [comment] 2017-11-17 19:50
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this as a duplicate of #5019, which has the wontfix label at the moment. Please read throughout the other issue

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-17 19:50 UTC
