### ISSUE TITLE
Icon request: icon-snwo-flake

### ISSUE THREAD

**Issue by isifun** [FortAwesome/Font-Awesome#8333] opened 2016-01-13 14:48 UTC
Hi, It will be very usefull to add an icon for the winter ... like this .
Thanks
![snow42](https://cloud.githubusercontent.com/assets/6671049/12297377/23010fd2-ba0d-11e5-98e2-0e6cbf90b87c.png)

**Comment by aethior** [comment] 2016-01-13 15:39
Duplicate of #1739. Please +1 that.

Regards.

**Closed** 2016-01-13 15:44 UTC
