### ISSUE TITLE
Icon request: ansible

### ISSUE THREAD

**Issue by Jonyx4** [FortAwesome/Font-Awesome#17053] opened 2020-08-18 22:15 UTC
**What can it be used for?**
Ansible integrations, reference.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/9699827/90570917-18bb8b00-e187-11ea-8f5c-d6364d4afac3.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-08-19 07:10
Duplicate of #5938

**Closed by tagliala** 2020-08-19 07:10 UTC

**Comment by iDustbin** [comment] 2022-06-24 05:11
when do you plan to include it ?
