### ISSUE TITLE
IconDefinition is not assignable to type IconProp

### ISSUE THREAD

**Issue by kjkeefe** [FortAwesome/Font-Awesome#18678] opened 2022-02-10 23:04 UTC
I'm getting this error: 

<pre>TypeScript error in /Users/kjkeefe/work/learning/reactnode/chap15/super-forum-client/src/components/areas/main/ThreadCard.tsx(33,13):
Type 'IconDefinition' is not assignable to type 'IconProp'.
  Type 'IconDefinition' is not assignable to type 'IconLookup'.  TS2322

    31 |           {thread && thread.threadItems && thread.threadItems.length}
    32 |           <FontAwesomeIcon> 
    33 |             icon={faReplyAll}
       |             ^
    34 |             className="points-icon"
    35 |             style={{
    36 |               marginLeft: ".25em",</pre>

I'm importing these: 

<pre>import { faEye, faReplyAll } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";</pre>

These are my dependencies:

<pre>"@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@fortawesome/react-fontawesome": "^0.1.16",</pre>

**Comment by EtienneBruines** [comment] 2022-02-15 12:58
Same issue when adding to the library:

![Screenshot_20220215_135805](https://user-images.githubusercontent.com/3962174/154066788-7dfe0711-fa7e-46c5-b9fd-f46d5247be04.png)

**Comment by NickSchudloProdigy** [comment] 2022-02-15 15:40
Looks like with the release of 6.0.0 `@fortawesome/fontawesome-svg-core` was updated to 1.3.0. Unfortunately 1.3.0 breaks with 5.X but because you have `^1.2.36` it uses 1.3.0.

A quick work around is to pin your version of svg-core to 1.2.36 (remove the ^).

**Comment by EtienneBruines** [comment] 2022-02-15 15:44
@NickSchudloProdigy That is useful information. 

Sounds like 5.X and the 1.3.0 version are seen as "compatible" by npm, which is why the update was "allowed" in the first place. I'm not quite sure how one would specify the incompatibility (since they do not directly depend on each other) in the `package.json` files of any of those projects.

**Comment by NickSchudloProdigy** [comment] 2022-02-15 16:03
I'm not sure. I think the core problem is that `fontawesome-common-types` changed the definition of `IconName` and so that package should have been a major version change, and that would have made svg-core also have a major version update too?

**Comment by AntonyF-Andreani** [comment] 2022-02-17 15:37
Same case, the problem breaks build (checking validity of types) in NextJs:

![image](https://user-images.githubusercontent.com/84329129/154511938-9b9f8daa-3f6e-493e-b7b8-b441d38bd7f1.png)

my deps:

```json
    "@fortawesome/free-brands-svg-icons": "6.0.0",
    "@fortawesome/pro-light-svg-icons": "6.0.0",
    "@fortawesome/pro-regular-svg-icons": "6.0.0",
    "@fortawesome/pro-solid-svg-icons": "6.0.0",
    "@fortawesome/react-fontawesome": "0.1.16",
    "@fortawesome/fontawesome-svg-core": "1.2.36",

```
-------

#### workarround: 

downgrade all deps:
```json
    "@fortawesome/free-brands-svg-icons": "5.15.4",
    "@fortawesome/pro-light-svg-icons": "5.15.4",
    "@fortawesome/pro-regular-svg-icons": "5.15.4",
    "@fortawesome/pro-solid-svg-icons": "5.15.4",
    "@fortawesome/react-fontawesome": "0.1.16",
    "@fortawesome/fontawesome-svg-core": "1.2.36",
```

**Comment by tagliala** [comment] 2022-02-17 19:43
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

@robmadole could you please take a look?

**Comment by scott-lc** [comment] 2022-02-21 02:55
These lines (there may be more), should be pinned to "0.2.36". 

```
  "dependencies": {
    "@fortawesome/fontawesome-common-types": "0.2.36"
  },
```

https://github.com/FortAwesome/Font-Awesome/blob/afecf2af5d897b763e5e8e28d46aad2f710ccad6/js-packages/%40fortawesome/fontawesome-svg-core/package.json#L50

https://github.com/FortAwesome/Font-Awesome/blob/afecf2af5d897b763e5e8e28d46aad2f710ccad6/js-packages/%40fortawesome/free-regular-svg-icons/package.json#L50

https://github.com/FortAwesome/Font-Awesome/blob/afecf2af5d897b763e5e8e28d46aad2f710ccad6/js-packages/%40fortawesome/free-brands-svg-icons/package.json#L50

https://github.com/FortAwesome/Font-Awesome/blob/afecf2af5d897b763e5e8e28d46aad2f710ccad6/js-packages/%40fortawesome/free-regular-svg-icons/package.json#L50

https://github.com/FortAwesome/Font-Awesome/blob/afecf2af5d897b763e5e8e28d46aad2f710ccad6/js-packages/%40fortawesome/free-solid-svg-icons/package.json#L50

**Comment by robmadole** [comment] 2022-02-23 18:19
Yuck. Ok. Reviewing this now. Sorry folks for the hassle.

I'm working on this one. For now pinning in your own `package.json` files to the correct version will be required:

- If you are using version 6 use `@fortawesome/fontawesome-common-types@0.3.0`
- If you are using version 5 use `@fortawesome/fontawesome-common-types@0.2.6`

The aggravating part is that I thought the `^` with a leading zero like `0.2.6` would not upgrade to a `0.3`. Looks like that's biting us here.

**Comment by scott-lc** [comment] 2022-02-23 18:32
> The aggravating part is that I thought the ^ with a leading zero like 0.2.6 would not upgrade to a 0.3.

This surprised me too.  I actually think NPM should not have upgraded to 0.3, at least according to this cheatsheet that I've always used:

https://devhints.io/semver

**Comment by scott-lc** [comment] 2022-02-23 18:49
NPM bug maybe?  According to https://semver.npmjs.com `@fortawesome/fontawesome-common-types` `^0.2.36` should not match `0.3.0`

I am using NPM 8.5 personally.

**Comment by jasonlundien** [comment] 2022-03-18 13:42
The packages for `@fortawesome/fontawesome-common-types` and `@fortawesome/fontawesome-svg-core` have been updated to use the actual release version number.  So you should be able to `npm install` these packages again and the `package.json` file will show:

`"@fortawesome/fontawesome-common-types": "^6.1.0"`
`"@fortawesome/fontawesome-svg-core": "^6.1.0",`

Please let us know if you are seeing other or additional issues.

**Comment by PatrickRose** [comment] 2022-08-21 22:25
I was having this issue when letting Dependabot upgrade, because Dependabot upgraded `@fortawesome/free-solid-svg-icons` to 6.1.2 but didn't upgrade `@fortawesome/fontawesome-svg-core` to `6.1.2`

Just including this here in case anyone else has this issue - _hopefully_ it won't be a regular occurrence but it should help if so!

**Comment by acelaya** [comment] 2022-09-24 09:36
This issue was fixed with v6.1.1, but it's back again on v6.2.0

**Comment by tagliala** [comment] 2022-09-24 09:38
@robmadole could you please take a look? Apparently there was a regression

**Comment by robmadole** [comment] 2022-10-03 15:53
@acelaya can you provide a reproduction? I set up a quick project locally with 6.2.0 and didn't have any issues.

**Comment by acelaya** [comment] 2022-10-03 18:12
Sure! You can see it in this build https://github.com/shlinkio/shlink-web-client/actions/runs/3176381181/jobs/5175609430

I was trying to update from `@fortawesome/fontawesome` 6.0 and `@fortawesome/react-fontawesome` 0.1.17 to `@fortawesome/fontawesome` 6.2 and `@fortawesome/react-fontawesome` 0.2, and then the error occured.

I faced the same error some time ago on a different project, when trying to update from 6.0 to 6.1, but 6.1.1 solved it back then.

This is the PR that triggered the build above https://github.com/shlinkio/shlink-web-client/pull/712/files

**Comment by robmadole** [comment] 2022-10-04 20:50
@acelaya try upgrade `@fortawesome/fontawesome-svg-core` to 6.2.0 as well!

Ref: https://github.com/shlinkio/shlink-web-client/commit/755ae23fdb1f6c2c0825b6925312b4caf816a167#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R11

**Comment by acelaya** [comment] 2022-10-04 21:03
That did the trick. Thanks!

**Closed as completed** 2022-10-04 21:25 UTC
Labels: waiting for feedback
