### ISSUE TITLE
fa-edit has some weird height issue

### ISSUE THREAD

**Issue by luisrudge** [FortAwesome/Font-Awesome#5882] opened 2015-03-08 04:17 UTC
Image:

![image](https://cloud.githubusercontent.com/assets/941075/6544486/fe76034c-c530-11e4-8c38-594d2c90dec7.png)

Repro:

http://codepen.io/luisrudge/pen/XJPaqX

**Comment by tagliala** [comment] 2015-03-08 12:09
It seems that there is work to do with some icons.

But I don't know if this could be considered a "design choice"... I don't know if FA is designed in a way that "given *n* icons, they will appear all in the same height in a row"

@davegandy ?

**Comment by luisrudge** [comment] 2015-03-08 12:56
Well. One can only hope, right? I mean, you don't want developers to start thinking and measuring icons before every time they'll use an icon, right? They don't need to be the same height, but should be aligned bottom by default

**Comment by tagliala** [comment] 2015-03-08 14:07
@luisrudge the problem is that some icons have a different height by design (take a look at [`fa-gamepad`](http://fontawesome.io/icon/gamepad/)), and imho they should be aligned to the center.

Refers to #1624

**Comment by luisrudge** [comment] 2015-03-09 18:35
No problem with gamepad, since it's wider than the other icons. But that edit icon clearly has a problem. Maybe the huge scale makes it hard to notice that, but look at using a real scale:

![image](https://cloud.githubusercontent.com/assets/941075/6561688/f2b0c79e-c671-11e4-86ab-b6bf3109d7e0.png)


It clearly looks misaligned.

**Comment by tagliala** [comment] 2015-03-09 19:50
@luisrudge sorry but I just remembered that this is a duplicate of #1007. I will close this one and add #1007 to 5.0.0 milestone so dave will eventually take a look (it doesn't mean that it will fix this icon but at least he will probably share his thoughts)

Do you mind to post there your screenshots?

**Comment by tagliala** [comment] 2018-02-18 15:07
https://jsfiddle.net/tagliala/qq2eLxo1/18/

**Closed by tagliala** 2018-02-18 15:07 UTC
