### ISSUE TITLE
Icon Request: icon-telephone @ fa-telephone

### ISSUE THREAD

**Issue by aspradeep** [FortAwesome/Font-Awesome#9800] opened 2016-08-24 07:40 UTC
![telephone](https://cloud.githubusercontent.com/assets/20511551/17922170/4a28b18e-69fb-11e6-853b-6a63cbde24bc.png)

Use Cases:
1. Can be used as a Web Icon to represent Landline telephone numbers.
2. Also used in form's input along with Bootstrap.

Thanks,
Pradeep.S

**Comment by tagliala** [comment] 2016-08-24 09:09
Duplicate of #1578, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-24 09:09 UTC
