### ISSUE TITLE
Icon request: NFC

### ISSUE THREAD

**Issue by raugaral** [FortAwesome/Font-Awesome#7773] opened 2015-10-28 15:32 UTC
Something like:
http://icons.iconarchive.com/icons/icons8/windows-8/256/Mobile-Nfc-Logo-icon.png

**Comment by tagliala** [comment] 2015-10-31 20:25
Duplicate of #1695? Related to #1692?

**Comment by picoundici** [comment] 2016-02-10 14:05
+1
It would be very useful. 
I think the best choice is 1 icon for both nfc and rfid. The google material icon "nfc" would be ok.
https://design.google.com/icons/#ic_nfc

**Comment by tagliala** [comment] 2016-09-08 18:24
No feedback, closing here

**Closed by tagliala** 2016-09-08 18:24 UTC
Labels: waiting for feedback
