### ISSUE TITLE
Icon request: fa-sewing

### ISSUE THREAD

**Issue by chelseywilson** [FortAwesome/Font-Awesome#9970] opened 2016-09-27 19:00 UTC
I would like to see an icon that represents sewing. I am building a portfolio website where I have different icons representing different areas of my art, and I can use something from Font Awesome in all the areas but one - sewing, etc. I think that this would be a good icon for many as this can be used to represent tailoring, embroidery, and any other form of sewing.
Here are a couple examples of what I had in mind.
![needle_artboard 1](https://cloud.githubusercontent.com/assets/22480983/18887543/2016b902-84ba-11e6-9a0d-3dc4c3e3c6e0.png)
![istock_000019446108xsmall](https://cloud.githubusercontent.com/assets/22480983/18887564/2eaf43b2-84ba-11e6-85bf-d472654d2bdf.jpg)

Thanks so much, you guys are awesome.

Best,
Chelsey Wilson
chelseydwilson@gmail.com

**Comment by tagliala** [comment] 2016-09-28 08:45
Duplicate of #5825, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-28 08:45 UTC
