### ISSUE TITLE
Icon Request: fa-hexagon

### ISSUE THREAD

**Issue by lotter1001** [FortAwesome/Font-Awesome#11795] opened 2017-11-24 04:05 UTC
Would like to have a hexagon to indicate that something stopped. 

<img width="69" alt="screen shot 2017-11-23 at 11 04 02 pm" src="https://user-images.githubusercontent.com/33947574/33195095-a3a35516-d0a2-11e7-956a-08a4529e78b3.png">

The example here is an electrical fault that caused a machine to stop that layers "fa-bolt" on top of "fa-hexagon"

<img width="67" alt="screen shot 2017-11-23 at 11 02 22 pm" src="https://user-images.githubusercontent.com/33947574/33195081-8094b358-d0a2-11e7-82ba-f7087f77a5cf.png">

**Comment by tagliala** [comment] 2017-11-24 09:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1302 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-24 09:50 UTC
