### ISSUE TITLE
Icon request: icon-viadeo

### ISSUE THREAD

**Issue by K-rip** [FortAwesome/Font-Awesome#7058] opened 2015-07-28 12:40 UTC
Hello! Sorry for my english, i'm French.

I think it lacks a Viadeo icon. It is a professional social network widely used in France. I work in a digital agency and we use Font Awesome for all sites to display social links of our customers. But for Viadeo, we must always create ourselves an icon using a background.

Full logo : https://upload.wikimedia.org/wikipedia/fr/thumb/4/49/Viadeo_Full_Logo.svg/640px-Viadeo_Full_Logo.svg.png
Icon : http://www.logic-id.fr/ressources/img/icons/viadeo/viadeo-2048-black.png

Viadeo : http://www.viadeo.com/

Thank you very much to the person who can do it!

**Comment by tagliala** [comment] 2015-07-28 12:50
duplicate of #886 , please +1 that request

closing here

**Closed by tagliala** 2015-07-28 12:50 UTC
