### ISSUE TITLE
Icon Request: fa-project

### ISSUE THREAD

**Issue by behnammodi** [FortAwesome/Font-Awesome#7852] opened 2015-11-08 12:12 UTC
project icon
![project](https://cloud.githubusercontent.com/assets/1549069/11020157/5a3c02e6-860e-11e5-860e-8e86eec4c06d.jpg)

**Comment by aethior** [comment] 2015-11-10 01:22
Hi @uxitten,

There is a `fa-tasks` icon (http://fontawesome.io/icon/tasks/). It is not identical, but show tasks in different status. Maybe you can use this icon.

Regards.

**Comment by tagliala** [comment] 2015-11-13 21:02
this could also be a duplicate of #3915

**Comment by tagliala** [comment] 2022-03-13 14:52
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

https://fontawesome.com/icons/chart-gantt?s=solid

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2022-03-13 14:52 UTC
Labels: waiting for feedback
