### ISSUE TITLE
Icon request: fa-workflow

### ISSUE THREAD

**Issue by hw121693** [FortAwesome/Font-Awesome#8656] opened 2016-02-26 05:25 UTC
I've been using the Font-Awesome icon and the icons are made very well, but now, I would need a new icon to represent "Workflow", something like this:

![bubble_6](https://cloud.githubusercontent.com/assets/15042485/13343921/401f2e4a-dc8c-11e5-85e0-be9ae617c165.png)

Can you add this logo?

**Comment by tagliala** [comment] 2016-02-26 10:11
Duplicate of #3576, please +1 that request and post there your example

Please also consider using http://fontawesome.io/icon/sitemap/, it is not the same but it could suit your needs

**Closed by tagliala** 2016-02-26 10:11 UTC
