### ISSUE TITLE
Icon Request: fa-user-pencil

### ISSUE THREAD

**Issue by markalanevans** [FortAwesome/Font-Awesome#11436] opened 2017-08-23 21:51 UTC
## UseCase
An icon that represents editing your profile/user account info.

## Design Suggestions
Similar to how you do fa-user-plus , replace the plus symbol with a pencil. You might also consider using the user-o and a pencil or the user-circle.

**Comment by tagliala** [comment] 2017-08-23 22:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5951, please add a 👍  reaction to that request.

Refers to #1181, you will find a solution there

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-23 22:28 UTC
