### ISSUE TITLE
Icon request: fa-dog-ban

### ISSUE THREAD

**Issue by buzza1961** [FortAwesome/Font-Awesome#15087] opened 2019-05-30 06:50 UTC
### What can it be used for?

This can be used in accommodation related websites and associated material to signify no pets

### Example image (optional)

<img width="215" alt="image" src="https://user-images.githubusercontent.com/51189391/58614058-adc03300-82fa-11e9-9535-5cb4534a65b7.png">

### Icon request checklist

- [ yes] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ yes] I have included at least one example image if it could be helpful (optional)
- [yes ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-05-30 07:25
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/87/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by ninjaval** [comment] 2019-10-28 20:53
I would like this too, because I am having the issue where a website builder relies on one icon name in order to work. Please consider adding it.

**Comment by sensibleworld** [comment] 2024-07-11 18:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](add "ban" mod to Wizard)

**Closed by sensibleworld** 2024-07-11 18:37 UTC
Labels: new icon, web application icons (legacy category), Duplicate

**Comment by tagliala** [comment] 2024-07-19 06:46
@sensibleworld there is a missing feature request here I guess
