### ISSUE TITLE
SyntaxError thrown by InternetExplorer on detached nodes

### ISSUE THREAD

**Issue by InnosoftDeveloper** [FortAwesome/Font-Awesome#12471] opened 2018-02-27 11:37 UTC
### Describe the problem

We have several cases when Internet Explorer 11 throws a "SyntaxError" on some elements, inside the _fontawesome-all.js_ in the _onTree_ function at ` var candidates = toArray(root.querySelectorAll(prefixesDomQuery));`. More precisely, the error is thrown by `querySelectorAll` function. After some investigation we found that the specific nodes for which the error is thrown are not part of the DOM anymore:  `document.body.contains(root)` returns `false`, i.e. nodes that have been apparently removed.

The actual problem is that Internet Explorer does not accept pseudo selectors inside `querySelectorAll` on elements which are not part of the DOM. This IE11 behavior can be tested with the following snippet (I'm using `:not()` here as it's the pseudo element using by `prefixesDomQuery`, although any pseudo selector will trigger the exception): 

```
const el = document.createElement("div");
el.querySelectorAll(".x:not(.y)");
```

Here's a [live example on JSFiddle](https://jsfiddle.net/vvLpfym8/). Please open the developer tools first.

### What did you expect?

Since this seems to be an IE11 bug, we'd expect that (mutated) elements that are not attached to the DOM to not be processed. A possible fix would be to add a check (`DOCUMENT.body.contains(mutationRecord.target)`) inside the `forEach` in the MutationObserver callback (`observe` function).

### What version and implementation are you using?

Version: 5.0.6
Browser and version: Internet Explorer, tested on 11.850.15063 & 11.125.16299

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

It's complicated... The nodes being affected are mutated by 3rd party libraries (e.g. Kendo UI) and we haven't been able to separately reproduce the problem in a lightweight example. Please note that the problem appears in at least two separate places, with the exact same symptoms: the DOM node being processed inside the MutationObserver callback is not attached to the DOM (parent node is null and `document.body.contains` returns false) and it is different from the "actual" node present in the DOM (different references). I don't know if it's normal behavior or not, but the mutation record target does not list children, although they are present in the "actual" DOM node.

However, what we can reproduce is the "SyntaxError" thrown by InternetExplorer, as described above.

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by UltraMed** [comment] 2018-03-22 23:12
I am experiencing the same problem. Using the minimized version of 5.0.6 the error reports at column  1575926 using Internet Explorer 11 on Windows 10.
--

**Comment by joepinner** [comment] 2018-03-25 21:55
I get the same issue using version 5.0.8, Windows 10 and Internet Explorer 11 (11.2125.14393.0). 

Error is on line 2663 in svg-with-js/js/fontawesome-all.js

I can confirm that wrapping the code within the foreach block on line 2208 with:

if (DOCUMENT.body.contains(mutationRecord.target))  {
// existing code within foreach
}

Seems to remedy the problem, for me at least.

**Comment by UltraMed** [comment] 2018-03-26 14:49
The line numbers in your fix don't look right when I look at the code, unless I'm not looking at it correctly. What is the first line of code you are wrapping with your "if" statement?

**Comment by tagliala** [comment] 2018-04-06 11:30
Hi!

Thanks for being part of the Font Awesome Community.

@robmadole could you please take a look?

**Comment by aykay82** [comment] 2018-05-04 12:18
Hi,

I have the same issue. The sugested fix helps.

**Comment by JeroenMoonen** [comment] 2018-09-12 12:15
This issue is still not fixed

**Comment by boraxhacker** [comment] 2019-03-06 22:36
Hi - We discovered/ran into this issue as well today. The suggested fix does help though we decided to turn off autoReplaceSvg instead. Our app uses quilljs and the pages with quill were the ones that revealed this bug in IE. Other pages were not affected.

**Comment by giarico** [comment] 2019-03-22 12:15
Hi, I have ran into this issue as well.
The suggested solution works also for me.

Do you have any plan to officially release the fix?

**Comment by tagliala** [comment] 2019-03-22 12:54
@giarico any chance to provide a reproducible test case?

Ref: https://github.com/FortAwesome/Font-Awesome/issues/12471#issuecomment-380094347

Quote from the first post: 

> ### Reproducible test case
> It's complicated... The nodes being affected are mutated by 3rd party libraries (e.g. Kendo UI) and we haven't been able to separately reproduce the problem in a lightweight example. Please note that the problem appears in at least two separate places, with the exact same symptoms: the DOM node being processed inside the MutationObserver callback is not attached to the DOM (parent node is null and document.body.contains returns false) and it is different from the "actual" node present in the DOM (different references). I don't know if it's normal behavior or not, but the mutation record target does not list children, although they are present in the "actual" DOM node.

**Comment by giarico** [comment] 2019-03-25 10:45
> @giarico any chance to provide a reproducible test case?
> 
> Ref: [#12471 (comment)](https://github.com/FortAwesome/Font-Awesome/issues/12471#issuecomment-380094347)
> 
> Quote from the first post:
> 
> > ### Reproducible test case
> > It's complicated... The nodes being affected are mutated by 3rd party libraries (e.g. Kendo UI) and we haven't been able to separately reproduce the problem in a lightweight example. Please note that the problem appears in at least two separate places, with the exact same symptoms: the DOM node being processed inside the MutationObserver callback is not attached to the DOM (parent node is null and document.body.contains returns false) and it is different from the "actual" node present in the DOM (different references). I don't know if it's normal behavior or not, but the mutation record target does not list children, although they are present in the "actual" DOM node.

Here you are!
[testcase.zip](https://github.com/FortAwesome/Font-Awesome/files/3002864/testcase.zip)

**Comment by tagliala** [comment] 2019-03-25 10:58
@giarico could you please host the test case on github or on jsfiddle / codepen / other services?

**Comment by giarico** [comment] 2019-03-25 12:54
Hello, try this:
http://jsfiddle.net/Girottif/3vy8dnux

**Comment by InnosoftDeveloper** [comment] 2019-03-25 13:04
@giarico JSFiddle does not support IE11 anymore. Here's the correct (readonly) link for the fiddle: [http://jsfiddle.net/Girottif/3vy8dnux/embedded/result,css,html,js](url).

**Comment by tagliala** [comment] 2019-03-25 14:23
I can confirm that the test case is throwing an issue in Font Awesome.

Even if it includes a third-party library, I think that we could improve to code to avoid that error

**Comment by giarico** [comment] 2019-03-25 14:41
Thank you very much for your feedback

**Comment by robmadole** [comment] 2019-03-25 20:51
Ok @InnosoftDeveloper that reproduction helped a ton. I think there is some deep IE11 thing going on here and it's opaque enough that we aren't going to fix the root cause. So I've basically just handled the error so that it doesn't make it to the console. That's the best I can do now.

We have a PR up in our build system to get this addressed. It should go out in the next version of Font Awesome.

**Comment by tagliala** [comment] 2019-07-30 12:04
Is this still an issue?

**Comment by InnosoftDeveloper** [comment] 2019-07-30 14:04
Ich bin bis 01.01.2028 abwesend




Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FortAwesome/Font-Awesome] SyntaxError thrown by InternetExplorer on
detached nodes (#12471)" gesendet am 07/30/2019 2:05:18 PM.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by Hypfer** [comment] 2019-09-19 11:25
@tagliala Seems to be fixed in 5.11.1
Maybe even earlier.

**Comment by tagliala** [comment] 2019-09-19 11:44
@Hypfer thanks for the heads-up

**Closed by tagliala** 2019-09-19 11:44 UTC
Labels: bug

**Comment by InnosoftDeveloper** [comment] 2019-09-19 12:02
Ich kehre zurück am 09.10.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten. / I will reply
to your mail after my return.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FortAwesome/Font-Awesome] SyntaxError thrown by InternetExplorer on
detached nodes (#12471)" gesendet am 09/19/2019 1:45:44 PM.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by InnosoftDeveloper** [comment] 2019-09-19 12:02
Ich kehre zurück am 09.10.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten. / I will reply
to your mail after my return.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FortAwesome/Font-Awesome] SyntaxError thrown by InternetExplorer on
detached nodes (#12471)" gesendet am 09/19/2019 1:45:39 PM.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by InnosoftDeveloper** [comment] 2019-09-19 12:02
Ich kehre zurück am 09.10.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten. / I will reply
to your mail after my return.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FortAwesome/Font-Awesome] SyntaxError thrown by InternetExplorer on
detached nodes (#12471)" gesendet am 09/19/2019 1:26:27 PM.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
