### ISSUE TITLE
Icon request: icon-theatre-mask

### ISSUE THREAD

**Issue by jorgedelcampo** [FortAwesome/Font-Awesome#11097] opened 2017-05-20 21:57 UTC
![theatre-mask-icon](https://cloud.githubusercontent.com/assets/28831483/26279572/4400240a-3d85-11e7-8392-9205a602303a.png)
Hi Awesome team! I ask you if is possible that you create an artistic icons family, for example theatrical mask 
icons.
I hope your answer. Great project!!

**Comment by tagliala** [comment] 2017-05-21 10:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1270 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-21 10:57 UTC

**Comment by jorgedelcampo** [comment] 2017-05-21 15:18
Thanks! I will :)
