### ISSUE TITLE
fab fa-bing

### ISSUE THREAD

**Issue by unstructuredprogrammer** [FortAwesome/Font-Awesome#14184] opened 2018-10-28 12:59 UTC
It's nice to have the Bing icon among other icons
please create it! i really need it

**Comment by unstructuredprogrammer** [comment] 2018-10-28 13:01
black and white <3

**Comment by tagliala** [comment] 2018-10-28 15:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2499, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-28 15:43 UTC
