### ISSUE TITLE
Icon Request: process

### ISSUE THREAD

**Issue by viskel** [FortAwesome/Font-Awesome#4129] opened 2014-08-13 14:39 UTC
Need to represent a process. The standard representation is the one from the BPMN standard, shown here (rectangle with small + within a box)

![image](https://cloud.githubusercontent.com/assets/8439320/3906933/5f0935c6-22f7-11e4-87e8-700cd07d0802.png)

**Comment by ekkis** [comment] 2015-07-29 01:04
I would favour this because it transmits clearly the notion of something in motion, which is what a process is.

![business-process-icon](https://cloud.githubusercontent.com/assets/274980/8947709/0f516cd2-3553-11e5-92c5-70bc0c41bd8a.png)

**Comment by ekkis** [comment] 2015-07-29 01:09
maybe even this, because it depicts a decision (which most processes rely on)
![images](https://cloud.githubusercontent.com/assets/274980/8947758/c4307c2e-3553-11e5-98db-e702a90c74d8.jpeg)

**Comment by tagliala** [comment] 2015-07-29 08:42
is this a duplicate of #1541 ?

**Comment by viskel** [comment] 2015-07-29 14:35
Yes it looks like the same request as #1541.

Since BPMN has an icon for process (which I included in my original post), I would think that this would be the obvious choice.

**Comment by tagliala** [comment] 2015-07-30 18:35
if it is the same request, I need to close this one

if you think that the icon showed on #1541 is not the proper representation of a bpmn process, feel free to discuss there

**Closed by tagliala** 2015-07-30 18:35 UTC
Labels: new icon, waiting for feedback, web application icons
