### ISSUE TITLE
Zodiac sign icons

### ISSUE THREAD

**Issue by gitumen** [FortAwesome/Font-Awesome#16251] opened 2020-02-27 20:25 UTC
I'm surprised there are no zodiac sign icons at all. An icon to represent zodiac signs in general would be useful as well.

**Comment by tagliala** [comment] 2020-02-27 20:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2831, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-02-27 20:33 UTC
