### ISSUE TITLE
Icon Request: fa-line-chart-down

### ISSUE THREAD

**Issue by jasper502** [FortAwesome/Font-Awesome#8903] opened 2016-04-06 14:44 UTC
A simple alternate to `line-chart`: http://fontawesome.io/icon/line-chart/

The premise is that line-chart represents a trend `up` and line-chart-down `down`

![line-chart-down](https://cloud.githubusercontent.com/assets/1505829/14320777/9022d05c-fbd3-11e5-9460-54e902833911.png)

**Comment by tagliala** [comment] 2016-04-06 21:47
Duplicate of #5193, please +1 that request

Closely related to #4397 

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-06 21:47 UTC

**Comment by jasper502** [comment] 2016-04-06 22:06
My bad - will search next time.
