### ISSUE TITLE
Search-minus and search-plus have non-intuitive names

### ISSUE THREAD

**Issue by eliasbaixas** [FortAwesome/Font-Awesome#11064] opened 2017-05-15 16:34 UTC
The lens, with a plus or a minus inside, is widely related to zoom in and zoom out, that is pricisely what the plus and minus imply. 
On the other hand, the relation between the lens and "search" is more coincidental, and usually not associated with the lens with the inner sign.

Thus I would suggest to change the name or create an alias for the lens to zoom-in or zoom-out, or an alias to "lens". I always have a very hard time to find the lens under the name of "search", I will usually try to find it by "lens", then "zoom", maybe "glass", "scale", and after a long while scanning through the icons, i finally find-it under "search".

Thanks

**Comment by tagliala** [comment] 2017-05-15 17:38
Hi!

Thanks for being part of the Font Awesome Community.

I agree that `search-plus` and `search-minus` have no sense.

There is already a `zoom` filter in the docs, so you should be able to search for zoom and get the related icons

![image](https://cloud.githubusercontent.com/assets/556268/26070768/1b24585e-39a6-11e7-9e45-44d8fea755e9.png)

**Comment by tagliala** [comment] 2019-07-04 22:16
Duplicate of #3222

**Closed by tagliala** 2019-07-04 22:16 UTC
