### ISSUE TITLE
Icon request: wind-turbine

### ISSUE THREAD

**Issue by SteffenMangold** [FortAwesome/Font-Awesome#12904] opened 2018-04-19 09:48 UTC
### What can it be used for?

Visualize a wind turbine in a web portal.

### Example image

<img src="https://user-images.githubusercontent.com/20702171/38988329-173f67aa-43d3-11e8-94e9-066cf561c613.png" width="64">

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-19 11:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1300 , please add a 👍  reaction to that request.

>  I have searched for existing issues and to the best of my knowledge this is not a duplicate

No problem 👍 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-19 11:48 UTC

**Comment by SteffenMangold** [comment] 2018-04-19 11:56
Sorry it would never come to my mind to search for "windmill".
Because this is a windmill for me:

![image](https://user-images.githubusercontent.com/20702171/38990163-73cbd61a-43d9-11e8-9bfb-3986378242c1.png)

**Comment by tagliala** [comment] 2018-04-19 12:05
@SteffenMangold thanks. I'm not an English native speaker. I can see both images on google images, I will fix #1300's title by including `wind-turbine`
