### ISSUE TITLE
Icon request: icon-envelope-open

### ISSUE THREAD

**Issue by top8843** [FortAwesome/Font-Awesome#9804] opened 2016-08-24 14:41 UTC
opened envelope means mail which have been read

**Comment by tagliala** [comment] 2016-08-24 15:02
Duplicate of #897 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-24 15:02 UTC

**Comment by top8843** [comment] 2016-08-24 15:46
![999](https://cloud.githubusercontent.com/assets/2032385/17937510/f0079652-6a54-11e6-9608-792e4a6795b1.jpg)
