### ISSUE TITLE
Icon Request: fa-rumble

### ISSUE THREAD

**Issue by GETTTA** [FortAwesome/Font-Awesome#19322] opened 2022-09-07 15:53 UTC
an icon for rumble.com, act similar to youtube icon.
![rumble](https://user-images.githubusercontent.com/113046787/188923484-660560b0-b816-422a-91a3-f4364eb913f3.jpg)

**Comment by tagliala** [comment] 2022-09-07 15:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17327, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-09-07 15:56 UTC
