### ISSUE TITLE
Icon request: fa-mushroom, fa-toadstool

### ISSUE THREAD

**Issue by sle1306** [FortAwesome/Font-Awesome#16541] opened 2020-04-28 10:21 UTC
**What can it be used for?**
I am writing an application for nature lovers how collect wild plants and mushrooms.
This kind of icons could be used in all food related applications as well.

Thank you.

**Comment by tagliala** [comment] 2020-04-28 17:24
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4127, please add a 👍 reaction to that request.

I'm going to add `toadstool` to that request, so we can implement both at the same time

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-04-28 17:24 UTC
