### ISSUE TITLE
Icon Request: fa-Teeth

### ISSUE THREAD

**Issue by CharlestonPetResort** [FortAwesome/Font-Awesome#10485] opened 2017-01-06 21:55 UTC
![dental_icons-04-512](https://cloud.githubusercontent.com/assets/24966728/21734310/c465ddd8-d430-11e6-957c-763c5d735ce6.png)

We would love to see teeth, or toothbrush to use for those clients who always get their teeth brushed!

**Comment by caduvieira** [comment] 2017-01-13 11:33
Dupe of #1289?

**Comment by tagliala** [comment] 2017-01-13 13:43
This looks like a shining tooth :\

**Comment by sensibleworld** [comment] 2019-12-06 18:27
We now have a few tooth-related icons: https://fontawesome.com/icons?d=gallery&q=teeth

**Closed by sensibleworld** 2019-12-06 18:27 UTC
Labels: waiting for feedback
