### ISSUE TITLE
Icon Request: fa-user-change

### ISSUE THREAD

**Issue by emkosz** [FortAwesome/Font-Awesome#9387] opened 2016-06-10 22:56 UTC
Hi there,
could you add an icon for changing user (reassigning user).
A regular user with an arrow around it would work great. 

Thanks!

**Comment by tagliala** [comment] 2016-06-11 09:20
Duplicate of #7184 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-11 09:20 UTC
