### ISSUE TITLE
webpack icon?

### ISSUE THREAD

**Issue by ayoubkhan558** [FortAwesome/Font-Awesome#17758] opened 2021-03-22 13:19 UTC
If html,, css, gulp, grunt, js, npm icons are there why not webpack icon?

![image](https://user-images.githubusercontent.com/20210961/111995489-36165600-8ad6-11eb-80b9-cd24bd168f98.png)
![image](https://user-images.githubusercontent.com/20210961/111995540-47f7f900-8ad6-11eb-85b4-87c7f2e9912d.png)

**Comment by tagliala** [comment] 2021-03-22 13:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13714, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-22 13:53 UTC
