### ISSUE TITLE
Font Awesome 5 Pro JS - Including Solid overrides Font Awesome 4 CSS

### ISSUE THREAD

**Issue by GedMarc** [FortAwesome/Font-Awesome#13657] opened 2018-07-29 11:46 UTC
Hi There,

If I include the solid.js file, the font awesome 4 icons no longer render.
This isn't the (what I hope is expected) case with light and regular.

5.2.0 Web Pro

Thanks

**Comment by tagliala** [comment] 2018-07-29 12:00
Hi!

Thanks for being part of the Font Awesome Community.

I think this is the correct behaviour.

Font Awesome 5 solid.js is going to detect `fa fa-icon` elements and replace them with their svg c ounterpart

If you want both FA4 and FA5, please customize the prefix of FA4 icons

Ref: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#changes

Hope it helps

Closing here

**Closed by tagliala** 2018-07-29 12:00 UTC

**Comment by tagliala** [comment] 2018-07-29 12:03
Example: http://jsfiddle.net/tagliala/9tercwpy/13/

Note: I do not recommend the above solution, it is just a way to show a workaround. I would rather use Scss/LESS and customize the whole prefix to avoid conflicts

**Comment by GedMarc** [comment] 2018-07-31 09:58
A lot of the FA4 icons are missing in the solid set, 
Should I include the v4Shim.js so all the icons highlight?

**Comment by tagliala** [comment] 2018-07-31 13:14
@GedMarc sorry, maybe I didn't get this issue correctly

> If solid overwrites the fa4 icons, what is the purpose of the v4shim?

v4shims are intended to update Font Awesome 4 to Font Awesome 5. It is not intended to make FA4 and FA5 work side by side. You should remove FA4's stylesheet and use FA5's ones

Take another look at the docs: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Could you please fill up a bug request that follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

A reproducible test would help us in understand the issue.

**Comment by tagliala** [comment] 2018-08-01 19:35
@GedMarc you're welcome

> Is this a bug? It definitely sounds intentional, doesn't make much sense, but intentional.

This isn't a bug and it makes sense to me.

v4 shims are mentioned in the upgrading guide. The title of the page is "Upgrading from Version 4". If you upgrade from , let's say, Windowss 7 o Windows 10, you can't use them side by side at the same time. That's how I intend "upgrade".

The documentation does not mention how to use FA4 and FA5 side by side and we do not support this use case, but it is defnitely possible.

The fastest way is to customize FA4's css something like `fa4 fa4-home`. If this is a breaking change, then you should customize FA5's css. If you need the SVG version, then you should hack with the javascript file and change the occurrences of the `fa` class.
