### ISSUE TITLE
Icon Request: icon-box

### ISSUE THREAD

**Issue by amevellec** [FortAwesome/Font-Awesome#1693] opened 2013-08-01 12:55 UTC
A simple cardboard box, useful for ecommerce.

Example :

![image](https://f.cloud.github.com/assets/2614857/893628/99bf20c6-faa9-11e2-86b0-b4c9a2983c49.png)

Thanks!

**Comment by tagliala** [comment] 2016-02-11 11:32
Closing as a duplicate of #908

**Closed by tagliala** 2016-02-11 11:32 UTC
