### ISSUE TITLE
icon request: copyleft

### ISSUE THREAD

**Issue by mlibre** [FortAwesome/Font-Awesome#10548] opened 2017-01-23 13:43 UTC
hi. you have copyright icon. this is copyleft.
https://en.wikipedia.org/wiki/Copyleft

**Comment by AntonRand** [comment] 2017-01-23 14:22
Would flipping the Copyright horizontally give you what you want?

`<i class="fa fa-copyright fa-6 fa-flip-horizontal" aria-hidden="true"></i>`

**Comment by tagliala** [comment] 2017-01-23 14:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2934, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-23 14:53 UTC

**Comment by mlibre** [comment] 2017-01-23 15:26
Ah. yes. sr.
