### ISSUE TITLE
Icon Request: fa-oil-drum

### ISSUE THREAD

**Issue by dscharalampidis** [FortAwesome/Font-Awesome#8142] opened 2015-12-10 23:50 UTC
It will be useful for financial websites.
![oil-256](https://cloud.githubusercontent.com/assets/10142016/11732082/88d68c98-9fa9-11e5-8f19-4071442e1e2f.png)

**Comment by MrZach** [comment] 2015-12-11 02:17
+1

Could also be used on oil and fuel related websites.

**Comment by tagliala** [comment] 2015-12-11 08:54
Is there a better title for this?

**Comment by dchara01** [comment] 2015-12-11 09:05
probably fa-crude-oil ?

**Comment by richardtallent** [comment] 2015-12-20 01:18
I would suggest expanding the scope of this slightly to being simply a so-called ISO drum (ISO 15750-1/2, aka "55 gallon drum"). It would simplify the design and open it up to some additional use cases, including transportation.

https://en.wikipedia.org/wiki/Drum_(container)

Crude as a commodity is priced using 42-gallon "barrel" units, but wouldn't be transported in them. However, petroleum-based products (other than crude) are often shipped in 55 gallon / 200 liter drums, so it's a reasonable enough icon to use for crude.

**Comment by tagliala** [comment] 2015-12-20 11:07
@richardtallent should I rename to icon-oil-drum ?

**Comment by richardtallent** [comment] 2015-12-20 15:44
Since they are rarely used to store crude oil, maybe `fa-drum-container` or `fa-iso-drum` would be better?

**Comment by kjacob76** [comment] 2016-02-17 17:48
+1

**Comment by otitov** [comment] 2016-03-02 09:45
+1

**Comment by lalabili** [comment] 2017-08-27 07:11
+1

**Comment by tagliala** [comment] 2019-04-26 15:14
Is this a duplicate of #4318 ?

**Comment by JaiDoubleU** [comment] 2019-06-19 16:50
+1

**Comment by dawaltconley** [comment] 2019-07-19 23:58
+1, looking for something to represent barrels of oil. would vote for a plain barrel icon (minus the droplet) since that can be added with fa-tint and it makes it more flexible. could also add fa-biohazard or something to represent waste, etc.

or all the above? (:

**Comment by tagliala** [comment] 2020-05-28 15:51
Is this a duplicate of #4318 ?

**Comment by aethior** [comment] 2022-03-12 21:21
> Is there a better title for this?

🛢 [U+1F6E2](https://emojipedia.org/emoji/%F0%9F%9B%A2/) Oil Drum

**Comment by aethior** [comment] 2022-03-17 22:26
> Is this a duplicate of #4318 ?

I think so. What do you think about closing the other request and changing this to `fa-oil-drum (barrel)` (to avoid duplicate votes)?

**Comment by tagliala** [comment] 2022-03-17 22:28
Let's use #4318

**Closed by tagliala** 2022-03-17 22:28 UTC
Labels: new icon, energy (category)
