### ISSUE TITLE
Icon request: radiator

### ISSUE THREAD

**Issue by KonradDeskiewicz** [FortAwesome/Font-Awesome#17467] opened 2020-12-09 18:18 UTC
**What can it be used for?**
For example: To indicate central heating availibility in offered flat.
Currently, there is an icon for Air Conditioning or Fireplace but nothing that can support such meaning. 
"faHeath" icon is so... vague that is hard to use.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/17060750/101669555-5ef86b00-3a52-11eb-9fd1-7bcd394a245d.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-04-14 18:10
This request is duplicate of https://github.com/FortAwesome/Font-Awesome/issues/3253.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed** 2022-04-14 19:17 UTC
