### ISSUE TITLE
Icon Request: fa-ResearchGate

### ISSUE THREAD

**Issue by Science-Fan** [FortAwesome/Font-Awesome#6945] opened 2015-07-13 16:58 UTC
An icon to link directly to a specific profile on Research Gate:

![image](https://cloud.githubusercontent.com/assets/13318609/8655405/b70310e4-2945-11e5-93ed-51a62b585177.png)

**Comment by tagliala** [comment] 2015-07-16 19:05
duplicate of #3634, please +1 that request

closing here

**Closed by tagliala** 2015-07-16 19:05 UTC
