### ISSUE TITLE
Linkedin Page

### ISSUE THREAD

**Issue by SeanCreagh89** [FortAwesome/Font-Awesome#13740] opened 2018-08-09 14:47 UTC
Not an issue with FontAwesome. Working as intended.

There's an issue with the following page on your site:

https://fontawesome.com/icons/linkedin?style=brands

"fab fa-linkedin" should be "fab fa-linkedin-square" as the former shows no square.

**Comment by tagliala** [comment] 2018-08-09 14:57
Hi!

Thanks for being part of the Font Awesome Community.

This is not a bug

[Brand guidelines of LinkedIn](https://brand.linkedin.com/) demands a squadre around "in"

Please open the following in two tabs and try to switch fastly between them 
https://fontawesome.com/icons/linkedin?style=brands
https://fontawesome.com/icons/square?style=solid

Then try the same with
https://fontawesome.com/icons/facebook-square?style=brands
https://fontawesome.com/icons/square?style=solid

Also, facebook have two different icons just because of the border radius:
https://fontawesome.com/icons/facebook?style=brands
https://fontawesome.com/icons/facebook-square?style=brands

Hope it helps

Closing here

**Closed by tagliala** 2018-08-09 14:57 UTC
