### ISSUE TITLE
Icon Request: fa-patreon

### ISSUE THREAD

**Issue by matiboux** [FortAwesome/Font-Awesome#8994] opened 2016-04-15 16:01 UTC
A Patreon icon, with alternative icons would be nice!

**Comment by tagliala** [comment] 2016-04-15 16:20
Duplicate of #3257, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-15 16:20 UTC
