### ISSUE TITLE
Icon Request: fa-django

### ISSUE THREAD

**Issue by rseeley** [FortAwesome/Font-Awesome#12496] opened 2018-03-03 01:04 UTC
Use cases
* I would personally use this for my small business's "Services" section, since I use Django when developing my websites
* Portfolio sites showing projects you've worked on

[Django icon](https://cdn.worldvectorlogo.com/logos/django.svg)

**Comment by tagliala** [comment] 2018-03-03 11:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3805, please add a 👍  reaction to that request.

Anyway, #3805 is labeled as wontfix because at the time django didn't have an official logo.

As far as I can see, the favicon is still the only thing we can use as a logo, so I should ask you to keep 👍 #3805 and post your comment here

Closing here

**Closed by tagliala** 2018-03-03 11:38 UTC
