### ISSUE TITLE
Icon Request: icon-hair

### ISSUE THREAD

**Issue by modul3** [FortAwesome/Font-Awesome#10342] opened 2016-12-09 16:47 UTC
Thanks!
![42055](https://cloud.githubusercontent.com/assets/15873580/21056809/db629776-be3f-11e6-8497-43904f45ba98.png)

**Comment by aethior** [comment] 2022-03-18 22:14
Duplicate of #15344.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-19 09:30
https://fontawesome.com/icons/user-hair?s=solid

more at #15344

**Closed by tagliala** 2022-03-19 09:30 UTC
