### ISSUE TITLE
Icon request: replit

### ISSUE THREAD

**Issue by wsgdandy** [FortAwesome/Font-Awesome#19026] opened 2022-05-09 18:39 UTC
https://www.google.com/search?q=replit&sxsrf=ALiCzsbpXiimtq4VHVzrJKb0Xu8wp4EHQQ:1652121496425&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjZ762XiNP3AhURkmoFHW1HChsQ_AUoBHoECAIQBg&biw=1366&bih=649&dpr=1

heres some examples. i've been waiting for this for a while, it makes sense to add this,

**Comment by tagliala** [comment] 2022-05-12 19:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14758, please add a 👍 reaction to that request.

Will add replit to the title to simplify search

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-05-12 19:59 UTC
