### ISSUE TITLE
icon will only show in safari

### ISSUE THREAD

**Issue by Ghost108** [FortAwesome/Font-Awesome#17970] opened 2021-06-02 12:43 UTC
**Describe the bug**
I am using the version 5.15.3 and this icon: <i class="far fa-times"></i>
Safari works finde.

![Bildschirmfoto 2021-06-02 um 14 41 20](https://user-images.githubusercontent.com/17011498/120481769-bc8dc480-c3b0-11eb-9ab8-f1013cd0479c.png)

MS Edge, Google Chrome and Firefox doesn't show this icon (empty) or this instead of the icon:
![Bildschirmfoto 2021-06-02 um 14 41 25](https://user-images.githubusercontent.com/17011498/120481737-b697e380-c3b0-11eb-80c1-41bd49d5b144.png)

**Version and implementation**
Version: 5.15.3
Browser and version: Safari 14.1.1 ; Firefox 89.0

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2021-06-02 13:17
Hi!

Thanks for being part of the Font Awesome Community.

I can't confirm: https://jsfiddle.net/tagliala/ajLpzuf8/

Could you please check the above link with your browser?

If it works, please check all the dependencies of your applications, there may be a conflict

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Feel free to comment, but meanwhile closing here

**Closed by tagliala** 2021-06-02 13:17 UTC

**Comment by Ghost108** [comment] 2021-06-02 13:20
You tried the wrong icon.
https://jsfiddle.net/rm01daz8/#&togetherjs=hePbBbjMTz

Same issue with firefox

**Comment by tagliala** [comment] 2021-06-02 13:25
Hi, [far fa-times](https://fontawesome.com/v5.15/icons/times?style=regular) is only available for Font Awesome Pro. Is this a Font Awesome Pro related issue?

If it is, then can't reproduce either: https://jsfiddle.net/tagliala/8fktzj4h/1/

Please check that there aren't third parties that are replacing FA Pro with FA Free

**Comment by Ghost108** [comment] 2021-06-02 13:27
I am only using the free version.
your website told me hat this icon is free:

![Uploading Bildschirmfoto 2021-06-02 um 15.26.26.png…]()

**Comment by tagliala** [comment] 2021-06-02 13:44
Yes, that is correct!

Screenshot from your fiddle:

![image](https://user-images.githubusercontent.com/556268/120491196-522d5200-c3b9-11eb-90a1-5ddffa264602.png)

Please replace it with `fas`

**Comment by Ghost108** [comment] 2021-06-02 19:49
oh my god .  my mistake ! I am sorry :(
Thank you. !!

**Comment by tagliala** [comment] 2021-06-02 19:51
Welcome, glad you've solved
