### ISSUE TITLE
Icon Request: fa-un-delete

### ISSUE THREAD

**Issue by Shyamalangan** [FortAwesome/Font-Awesome#7359] opened 2015-09-02 04:33 UTC
Hi,

I'm writing to seek if you have a un-delete or un-trash icon coming up?

Thanks,
Sri

**Comment by TheChen5** [comment] 2015-09-02 04:37
Dupe of #4090 
+1 that
Please :mag:before:heavy_plus_sign:

**Closed** 2015-09-14 06:16 UTC
