### ISSUE TITLE
Icon Request: fa-double-check

### ISSUE THREAD

**Issue by josotoru** [FortAwesome/Font-Awesome#9787] opened 2016-08-22 18:58 UTC
Hi!

Maybe a interesting suggest with a new icon: double check (like WhatsApp). Thanks!

**Comment by tagliala** [comment] 2016-08-22 19:20
Duplicate of #3975 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-22 19:20 UTC
