### ISSUE TITLE
Icon Request: fa-beach

### ISSUE THREAD

**Issue by alsii** [FortAwesome/Font-Awesome#9950] opened 2016-09-22 16:15 UTC
An image of a beach umbrella.
Possible аlternative names: fa-beach-umbrella, fa-sea, fa-vacation
I need this icon to represent a vacation day in a work calender.

**Comment by tagliala** [comment] 2016-09-22 17:42
Duplicate of #1145 or #3787, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-22 17:42 UTC
