### ISSUE TITLE
Icon Request: fa-chart-trend

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#7832] opened 2015-11-05 21:05 UTC
Very useful to use with charts.

![image](https://cloud.githubusercontent.com/assets/1769227/10986973/150edf08-842f-11e5-9b51-9a84027a67f2.jpg)

Example:
![example](https://cloud.githubusercontent.com/assets/1769227/10987057/d413b680-842f-11e5-9e84-fa0f01ac2991.jpg)

**Comment by dennym** [comment] 2015-11-06 10:43
+1

**Comment by tagliala** [comment] 2015-11-14 00:27
Duplicate of #4397 , please +1 that request

closing here

**Closed by tagliala** 2015-11-14 00:27 UTC
