### ISSUE TITLE
net::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by Osademe-e** [FortAwesome/Font-Awesome#16488] opened 2020-04-17 16:07 UTC
Icons are not loading

**Comment by tagliala** [comment] 2020-04-17 16:24
Thanks for reporting this, we are aware of the situation and sorry for the inconvenience

More information: https://status.fortawesome.com/

Duplicate of: #16482

**Closed by tagliala** 2020-04-17 16:24 UTC
