### ISSUE TITLE
Question: Node caching documentation incorrect, exceeding package bandwidth

### ISSUE THREAD

**Issue by kateEcobb** [FortAwesome/Font-Awesome#20489] opened 2024-12-04 17:03 UTC
### Bug description

In your [package](https://docs.fontawesome.com/web/setup/packages) setup documentation, step 4 specifies to "Cache your [CI Dependencies](https://docs.fontawesome.com/web/dig-deeper/continuous-integration)." We're using [actions/setup-node](https://github.com/actions/setup-node) to cache our npm dependencies, but we consistently exceed our allotted bandwidth. 

There's an [open issue](https://github.com/actions/setup-node/issues/835) on the setup-node repo to investigate this issue (explicitly using FontAwesome as an example), but ultimately setup-node doesn't cache node_modules or external CDN dependencies, and the only workaround is to cache the entirety of node_modules, which isn't recommended ([source](https://github.com/actions/cache/blob/main/examples.md#node---npm)): 

> Note It is not recommended to cache node_modules, as it can break across Node versions and won't work with npm ci

Short of caching node_modules, is there another recommended solution? We'd love to not pay for overages each month just due to our CI/CD.

### Font Awesome version

v6.7.1

### Serving

Kit

### Implementation

SVG+JS

### Browser and Operating System

Github Actions

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by MarcEspiard** [comment] 2024-12-06 02:26
Hi,

We have the exact same issue, using Gitlab CI here. It also happens locally on WSL2 / Ubuntu, so I'm guessing it's not environment specific.
We are paying for extra bandwidth even though everything should be cached, following your docs and Gitlab's docs (we've been using FA + Gitlab for years).

### Steps to reproduce:
In our project, our package.json includes these dependencies:
```json
"@fortawesome/fontawesome": "^1.2.0-6",
"@fortawesome/fontawesome-pro": "^6.7.1",
"@fortawesome/fontawesome-svg-core": "^6.6.0",
"@fortawesome/free-brands-svg-icons": "^6.6.0",
"@fortawesome/pro-duotone-svg-icons": "^6.6.0",
"@fortawesome/pro-light-svg-icons": "^6.6.0",
"@fortawesome/pro-regular-svg-icons": "^6.6.0",
"@fortawesome/pro-solid-svg-icons": "^6.6.0",
"@fortawesome/pro-thin-svg-icons": "^6.6.0",
"@fortawesome/react-fontawesome": "^0.2.2",
```
1. Run `npm install`
2. Check which fontawesome packages are cached with `npm cache ls | grep fontawesome`
In our case we get:
```
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome-common-types/0.2.36/fortawesome-fontawesome-common-types-0.2.36.tgz?created=1733435291&expires=1733521691&source=t-Ini1vLhQwATM&signature=gAAAAABnUh-bnvtagGmHVD-BHm76ucgXjCsYFZW1HNoy9GiW33MG0nvCtizyHWQGUbGl84-JN28SRrwEOBYmstvk7Kj4QZS7xy6I6d5mNO2kr9u_dYxjvH1uxrKPuRaZ1O5cIF2JQFbv
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome-common-types/0.2.36/fortawesome-fontawesome-common-types-0.2.36.tgz?created=1733450601&expires=1733537001&source=t-Ini1vLhQwATM&signature=gAAAAABnUltp3apEXpZR8ZBxl7XskPxbTmr1W2BqgO6Zu9Y3g1tA49j0erCeh4puNRqfRSXMIiM0WHkWDpvCwK_4CEPUfr0eCbfGfoxHnG-Gch-wxUlWxMVBz96RxXElvew3OrxAacaz
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome-common-types/6.6.0/fortawesome-fontawesome-common-types-6.6.0.tgz?created=1733435739&expires=1733522139&source=t-Ini1vLhQwATM&signature=gAAAAABnUiFbxyf26xMO4KIMr5f5l4TPeBaQIBMYMygmlATFsDwrYUmfGmlNKLm8EbjeSW8kC0fq6Sle05XHYXS0ondtMO7TQ4Wy49lbnCH6I84Ai6b_pwrSU34V_D2w9GWPIo8hOiU3
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome-pro/6.6.0/fortawesome-fontawesome-pro-6.6.0.tgz?created=1733435739&expires=1733522139&source=t-Ini1vLhQwATM&signature=gAAAAABnUiFbyj2WVf7WeVqEC0dBIZd-rZ3SGSHeIprQDEDacOqIyIFn8OHv_BPl_59i-jwubumAfVRLvVDyyN2u8O6YIcmWoOUmOwQC_xeINnjmYMJ7bR4NRABNra13IH_U_rgeUoPk
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome-pro/6.7.1/fortawesome-fontawesome-pro-6.7.1.tgz?created=1733450850&expires=1733537250&source=t-Ini1vLhQwATM&signature=gAAAAABnUlxiigmIIdmGa9GuXbIVhHpq5Q8JeTnnNh-o1dXxQ9HvbNNx_4Q_GIZjwcLP91rxta7O50JHwRQaEJyHXKWTXBkG_jNxDvHQmnFrBDsQIc-vCjOGtbiv4YbzMjlPsmOlD0Hp
⠴make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome-svg-core/6.6.0/fortawesome-fontawesome-svg-core-6.6.0.tgz?created=1733435739&expires=1733522139&source=t-Ini1vLhQwATM&signature=gAAAAABnUiFbh6TvSuRhcGED7tyd9bVxVVdtIxakIBIeDhL3rhMA5iv9KsFi6WWqIfPgdOMt-MNiGcB7mLkh5sbIwXVJUqGHr22DxjIBevq0oqD_T3ImxUXuxpemNC-HzZU-6CGBoj2L
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome/1.2.0-6/fortawesome-fontawesome-1.2.0-6.tgz?created=1733435291&expires=1733521691&source=t-Ini1vLhQwATM&signature=gAAAAABnUh-b0o1t-KvN_DvXIatzqNRHIQ2yQx60bYAX10LnbJ8VipInqp8WYoDXOj7jSwEFF6IFqup8aLrQdx7FYAYziRlUte6JJThJuDH9fsKGJeopoT4Q1iGINEHQ7AmC8cp7D13b
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome/1.2.0-6/fortawesome-fontawesome-1.2.0-6.tgz?created=1733450601&expires=1733537001&source=t-Ini1vLhQwATM&signature=gAAAAABnUltpY3tC7L2csDbk5sXq80SZqu0JtzTDSUdnnpWbnHN7cL5KTINKINvkni_wMGnMeXaKbdE0-oN7R99dHwvorFnv5Omp6qmWq4vqdHxUyQ_gzUAdsIUH_T4SUd9MhG5RFAqL
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/free-brands-svg-icons/6.6.0/fortawesome-free-brands-svg-icons-6.6.0.tgz?created=1733435739&expires=1733522139&source=t-Ini1vLhQwATM&signature=gAAAAABnUiFbmjk1vJXpBDXTKKLn0yaZ1LX24GLzvRcLKYPE1QGAwrj5dcWz6maxo2hw1ki8WSv0-pa7PMmXNRLcugkuaXqMBgPKls0o4K9tp58rLdXHb9oriqYExi_itATWPQ9_4NN2
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/pro-duotone-svg-icons/6.6.0/fortawesome-pro-duotone-svg-icons-6.6.0.tgz?created=1733435739&expires=1733522139&source=t-Ini1vLhQwATM&signature=gAAAAABnUiFbGynztNyIDQJmehLOmxIGR6NnjYCaMb3KH9zx1ai0vuU0MR2T_Fj6IG-U4yrQPEejkdwkI0gE6aheyW0RKVKQSoTiqkdSnrrb3Bxq4qz64wq-kFNwCtXmAZlv7lgoeXuC
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/pro-light-svg-icons/6.6.0/fortawesome-pro-light-svg-icons-6.6.0.tgz?created=1733435739&expires=1733522139&source=t-Ini1vLhQwATM&signature=gAAAAABnUiFbM-iO2uUO9KhqeNSatRP3sSEs8tlriJQbW1tjAO6P_5lJSO1Xixzudd4CBtpBUlhafSpSBSzGkx--ivKbHvxPqnDeV7QOkdzLspblsfLupbFa_VuvpvCyXXdRCgTU8B4P
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/pro-regular-svg-icons/6.6.0/fortawesome-pro-regular-svg-icons-6.6.0.tgz?created=1733435739&expires=1733522139&source=t-Ini1vLhQwATM&signature=gAAAAABnUiFbFF8dAwWRxfTpnSRWqE8igclMnZMOUVQJFFdQiOQRrCL_FTMQ0H7tewq2R8yZ30cDAr2AhaSATUySaXm84rTlJIiJoiELXEBOzdYdA5GZeDZgU0HKxSvWhvyvJVv8jagS
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/pro-solid-svg-icons/6.6.0/fortawesome-pro-solid-svg-icons-6.6.0.tgz?created=1733435739&expires=1733522139&source=t-Ini1vLhQwATM&signature=gAAAAABnUiFbWhvA86qAs6s6CvCc67dUEWzvk5JOTgmoDEdwdTgeit2kPn01Kaj2W0JSACQQScm4MJMp91yF5lvpJcuVEYLrZ43dtkTd6rEkIDFYLTaz8_Lz-6FaE7kFD2yBU50e3PbC
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/pro-thin-svg-icons/6.6.0/fortawesome-pro-thin-svg-icons-6.6.0.tgz?created=1733435739&expires=1733522139&source=t-Ini1vLhQwATM&signature=gAAAAABnUiFbWTfxQzkVVAlfM_zrNgSzZludqXHFMk5Z2jnfRyJyZEAGrQ9JrGgk7tAIifPQWEfukHkgoksTVdwHy_VvOcsdgJLrY_tN5n4X2KoOFC-uincY8ZiO3-Mn-cX68Bgq4GIn
make-fetch-happen:request-cache:https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/react-fontawesome/0.2.2/react-fontawesome-0.2.2.tgz?created=1733435739&expires=1733522139&source=t-Ini1vLhQwATM&signature=gAAAAABnUiFb0hcQmRQo8AVSLqrHFA70HRR395zkL6AN4usnxr6IKqPbQf4h22YxG-mHS5BF7A-QCONlfkuGxRqJtXY7PsWSjE3VU-guKajaMOZwymlntOTkbdtXRAFq-OwtRyOxXjJy
make-fetch-happen:request-cache:https://npm.fontawesome.com/@fortawesome%2ffontawesome
make-fetch-happen:request-cache:https://npm.fontawesome.com/@fortawesome%2ffontawesome-common-types
make-fetch-happen:request-cache:https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro
pacote:tarball:@fortawesome/fontawesome-common-types@0.2.36
pacote:tarball:@fortawesome/fontawesome@1.2.0-6
```
3. Run `rm -rf node_modules` (to force an install in the next command)
--> This point in time is equivalent to the start of the CI job, cache is restored and accessible, node_modules is not present, about to install.
4. Run `npm i --offline --verbose` (--offline to force cache use, and detect any packages not cached)
Note: we actually use --prefer-offline in our CI, so the command completes. But it does call FA's registry, which is the problem here.
You'll get this error, complaining one of FA packages is not found in cache, even though we have a very recent cache of all packages from command in 1.
```
npm verbose stack Error: request to https://npm.fontawesome.com/@fortawesome/fontawesome-common-types/-/0.2.36/fontawesome-common-types-0.2.36.tgz failed: cache mode is 'only-if-cached' but no cached response is available.
npm verbose stack     at cacheFetch (/home/marc/.asdf/installs/nodejs/18.20.4/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:12:13)
npm verbose stack     at async fetch (/home/marc/.asdf/installs/nodejs/18.20.4/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
npm verbose cwd /var/www/gethomesafe-server
npm verbose Linux 5.15.133.1-microsoft-standard-WSL2
npm verbose node v18.20.4
npm verbose npm  v10.7.0
npm error code ENOTCACHED
npm error request to https://npm.fontawesome.com/@fortawesome/fontawesome-common-types/-/0.2.36/fontawesome-common-types-0.2.36.tgz failed: cache mode is 'only-if-cached' but no cached response is available.
npm verbose exit 1
npm verbose code 1

npm error A complete log of this run can be found in:
```

I don't know where the blame lies but it's the only package that's happening with. 
If I remove the fontawesome dependencies I can install the packages offline without issue if I have a fresh cache.

Hope this helps.
Happy to contact support if that helps?

**Comment by tagliala** [comment] 2024-12-06 08:29
> Happy to contact support if that helps?

Yes please, send an email to hello@fontawesome.com with your findings and a link to this issue

**Comment by kateEcobb** [comment] 2024-12-06 23:18
@tagliala could you please update the thread here with what support says? Since this is a documentation/implementation issue and not necessarily a support issue, it'd be helpful for other developers to have the context.

**Comment by MarcEspiard** [comment] 2024-12-08 20:44
> > Happy to contact support if that helps?
> 
> Yes please, send an email to [hello@fontawesome.com](mailto:hello@fontawesome.com) with your findings and a link to this issue

@tagliala Sent an email with details and link to this issue to support email, I've used my pro email (same name as Github account).

**Comment by deathnfudge** [comment] 2024-12-09 15:10
I'm looking into this but @MarcEspiard one thing I spot right off is we no longer recommend installing the `@fortawesome/fontawesome-pro` package because it includes all files for all technologies and just keeps getting bigger as we release more and more icons. We recommend using the specific package files for the styles you need in conjunction with our `fontawesome-svg-core` package. For a full list of available packages see this. https://docs.fontawesome.com/web/setup/packages#svg-icon-packages

I'm not sure why the cache isn't working so I don't have specific guidelines around that yet but for anyone seeing this, double check if you are installing the full `@fortawesome/fontawesome-pro` package and remove it from your installs and that should decrease your bandwidth usage significantly.

**Comment by deathnfudge** [comment] 2024-12-09 20:34
We think the issue is caused by older packages. Check to see if you're using `@fortawesome/fontawesome` or `@fortawesome/fontawesome-pro` and remove those dependencies. Also, we locked `@fortawesome/fontawesome-common-types` to the current version of Font Awesome you're using awhile ago so if you're installing `6.6.0` icon packages the `common-types` package should also be version `6.6.0` so if you spot an older version of the `common-types` package, look at what is using it and remove that package. That should allow the cache to work. I'm closing this but please reach out to hello@fontawesome.com if you are still having issues.

I am also going to get this added to the docs so in the future other folks will know how to fix the issue. Thanks @MarcEspiard for helping confirm the fix.

**Closed as completed by deathnfudge** 2024-12-09 20:34 UTC
Labels: question, needs-triage
