### ISSUE TITLE
Icon Request: chat & chat-o

### ISSUE THREAD

**Issue by orrsiloni** [FortAwesome/Font-Awesome#4929] opened 2014-11-10 15:36 UTC
First of all thank you for the awesome Font Awesome.

Can you please add icons for chat (outline and full).
There are already oval icons for comments, but chat icons usually take a rectangular form as in Gmail, Facebook etc.
Examples:
1. In this gmail sprite (second from the left): https://ssl.gstatic.com/s2/oz/images/hovercard/com-sprite-v3-0d55aaae23118541311f5cff1cf1be87.png
2. In github's octicons: https://octicons.github.com/icon/comment/

**Comment by steven10172** [comment] 2016-04-18 05:17
+1 I would love to have square chat icons

**Comment by tagliala** [comment] 2016-04-18 09:18
Duplicate of #2790, please +1 that request

**Closed by tagliala** 2016-04-18 09:18 UTC
