### ISSUE TITLE
Icon Request: fa-creativecommons

### ISSUE THREAD

**Issue by frax75** [FortAwesome/Font-Awesome#5626] opened 2015-02-10 08:34 UTC
![cc](https://cloud.githubusercontent.com/assets/876902/6123874/fed60914-b107-11e4-907d-d0a545a0397f.png)

**Comment by ryanknutson** [comment] 2015-02-18 15:57
+1

**Comment by tagliala** [comment] 2015-02-19 15:21
duplicate of #544 , please +1 that request

closing here

**Closed by tagliala** 2015-02-19 15:21 UTC
