### ISSUE TITLE
Icon request: container-crane

### ISSUE THREAD

**Issue by 6Hau** [FortAwesome/Font-Awesome#18480] opened 2021-12-02 11:30 UTC
**What can it be used for?**
Used as a process indicator for a logistic shipment.

**Example image (optional)**
![crane 4](https://user-images.githubusercontent.com/95412401/144413542-ce1fbf59-c8cb-42fe-a5f1-61f8995a859d.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-12-02 11:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17205, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-12-02 11:47 UTC
