### ISSUE TITLE
Icon Request: fa-500px

### ISSUE THREAD

**Issue by micahcowell** [FortAwesome/Font-Awesome#7027] opened 2015-07-23 18:28 UTC
I have quite a bit of clients I make websites for who use 500px and it would be nice to have one with the rest of their social icons.

**Comment by TheChen5** [comment] 2015-07-26 00:03
Dupe of #599 .
" +1" that.
*Search before creating issue.*

**Comment by tagliala** [comment] 2015-07-26 13:10
@TheChen5 thanks

**Closed by tagliala** 2015-07-26 13:10 UTC
