### ISSUE TITLE
Icon request: icon-js

### ISSUE THREAD

**Issue by Bamuel** [FortAwesome/Font-Awesome#8233] opened 2015-12-30 01:52 UTC
Javascript Icon would make my portfolio look better
![](http://people.apache.org/~matzew/Confess_2013/assets/img/html5_css_javascript.png)

**Comment by aethior** [comment] 2015-12-30 02:47
Hi @Bamuel,

This suggestion is duplicate of #1711. Please +1 that.

**Closed** 2015-12-30 02:49 UTC
