### ISSUE TITLE
Icon request: fa-fan-blades

### ISSUE THREAD

**Issue by rotogro** [FortAwesome/Font-Awesome#13600] opened 2018-07-22 20:49 UTC
### What can it be used for?
showing fan blades

used when descibing boating, cooling, etc. 
### Example image (optional)
![image](https://user-images.githubusercontent.com/36603101/43049960-cad232e4-8dce-11e8-9eb5-42456fab29ac.png)

### Icon request checklist

- [ single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ fa-fan-blades] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X] I have included at least one example image if it could be helpful (optional)
- [X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-24 11:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3684, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-24 11:06 UTC
