### ISSUE TITLE
Icons for Salesforce, Jira, and Confluence are not working.

### ISSUE THREAD

**Issue by camerojo** [FortAwesome/Font-Awesome#16207] opened 2020-02-16 02:33 UTC
This is a reopening of issue #14858 which I believe was closed in error.

The Salesforce icon does not display

The easiest way to demonstrate this is using Stackblitz.

For example go here [https://stackblitz.com/edit/angular-font-awesome-starter](https://stackblitz.com/edit/angular-font-awesome-starter)

Change/add code to display the salesforce icon, eg

```
  <fa-icon [icon]="['fab', 'salesforce']"></fa-icon>
```

You will see that it does not display. As reported in the original issue, you will also see that the icons for jira and confluence also do not display

Here is the modified code to the app.component.html
```
`  <h2>Using Brand Icons</h2>`
`  <fa-icon [icon]="['fab', 'stack-overflow']"></fa-icon>`
  <br>
`  <fa-icon [icon]="['fab', 'github']"></fa-icon>`
  <br>
`  <fa-icon [icon]="['fab', 'medium']"></fa-icon>`
  <br>
//New lines here for the three icons that should display but don't.
`  <fa-icon [icon]="['fab', 'salesforce']"></fa-icon>`
  <br>
`  <fa-icon [icon]="['fab', 'jira']"></fa-icon>`
  <br>
`  <fa-icon [icon]="['fab', 'confluence']"></fa-icon>`
  <br>
//Display the Medium icon again to mark the end
`  <fa-icon [icon]="['fab', 'medium']"></fa-icon>`
```

**Comment by tagliala** [comment] 2020-02-18 20:13
Hi!

Thanks for being part of the Font Awesome Community.

Please notice the following:

- the above reproducible test case is loading FA 5.5.0, but Salesforce has been added in 5.8, and Jira and Confluence in 5.6, so that example needs to update FA dependencies
- Modifying `app.component.html` is not enough, because icons should be defined and loaded via `app.module.ts`

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';

import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faSquare, faCheckSquare } from '@fortawesome/free-solid-svg-icons';
import { faSquare as farSquare, faCheckSquare as farCheckSquare } from '@fortawesome/free-regular-svg-icons';
import { faSalesforce, faJira, faConfluence } from '@fortawesome/free-brands-svg-icons';

import { AppComponent } from './app.component';
import { HelloComponent } from './hello.component';

@NgModule({
  imports:      [ BrowserModule, FormsModule, FontAwesomeModule ],
  declarations: [ AppComponent, HelloComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule {
  constructor() {
    library.add(faSquare, faCheckSquare, farSquare, farCheckSquare, faSalesforce, faJira, faConfluence);
  }
}
```

Demo: https://stackblitz.com/edit/angular-font-awesome-starter-vp5ak3?file=package.json

Docs: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

Hope it helps

Closing here

**Closed by tagliala** 2020-02-18 20:13 UTC
