### ISSUE TITLE
Icon request: razor-electric shaving machine

### ISSUE THREAD

**Issue by sera-e** [FortAwesome/Font-Awesome#15871] opened 2019-11-26 15:14 UTC
**What can it be used for?**
Bathroom related products, categories, & shops.
Hygiene related products, categories, & promos.
Beauty related products, categories, and shops.
Salon related products, categories, and shops.

**Example image (optional)**
![razor-electric](https://user-images.githubusercontent.com/53708595/69646304-8f32be80-1035-11ea-8f17-729a79916781.png)

**Icon request checklist**
- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-03-17 21:54
Related (not duplicated):

`razor`: #15869
`barber-razor`: #18128
`electrick-razor`: #15871

**Comment by aethior** [comment] 2022-03-18 00:48
Also know as `shaving machine`?

**Comment by tagliala** [comment] 2022-03-18 17:10
Duplicate of #13407

**Closed by tagliala** 2022-03-18 17:10 UTC
Labels: new icon, web application icons
