### ISSUE TITLE
Icon Request: fa-dishwasher

### ISSUE THREAD

**Issue by jeroenst** [FortAwesome/Font-Awesome#16861] opened 2020-07-01 06:53 UTC
I would like to have a dishwasher icon

https://cdn1.iconfinder.com/data/icons/ios-edge-line-3/25/Dishwasher-512.png

**Comment by tagliala** [comment] 2020-07-01 15:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9577, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-07-01 15:44 UTC
