### ISSUE TITLE
Icon Request: Strength

### ISSUE THREAD

**Issue by notman** [FortAwesome/Font-Awesome#3345] opened 2014-05-02 19:27 UTC
I could really use an icon to represent the strength of a result/prediction. I think this is also an icon that many others would find useful too.

As an example, I found this image:
![icon_feats-of-strength](https://cloud.githubusercontent.com/assets/7469737/2867003/cd7eaf2c-d22f-11e3-9a2b-9ec69a07ba64.png)

**Comment by GKolmerer** [comment] 2015-05-16 08:44
+1

**Comment by jhartling** [comment] 2015-10-04 19:42
+1

**Comment by christoval** [comment] 2015-10-04 19:43
+1

**Comment by bull-xu-stride** [comment] 2016-06-26 13:17
+ 1

**Comment by kimimilawinyan** [comment] 2017-02-02 06:11
PLEASE!

**Comment by tagliala** [comment] 2017-09-29 10:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2076, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-29 10:33 UTC
