### ISSUE TITLE
fa-parler

### ISSUE THREAD

**Issue by BlockSpeed03** [FortAwesome/Font-Awesome#16892] opened 2020-07-10 21:34 UTC
I am wanting the parler icon
(Its white)
![parler-icon](https://user-images.githubusercontent.com/55367040/87204737-31ed3400-c2cb-11ea-883e-c936fc1c465e.png)

**Comment by tagliala** [comment] 2020-07-11 00:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16275, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-07-11 00:07 UTC
