### ISSUE TITLE
Icon Request: fa-survey

### ISSUE THREAD

**Issue by GestQual** [FortAwesome/Font-Awesome#11476] opened 2017-08-31 17:19 UTC
Hello!

I'm missing a survey Icon. I think it would be a good addition:

![image](https://user-images.githubusercontent.com/31516304/30030816-4bb52eaa-9165-11e7-907a-7d995b61cf60.png)

**Comment by hiddewie** [comment] 2017-09-01 10:19
I think such an icon has far too much detail for the small font size it may be rendered at. Is the checkbox icon not sufficient?

**Comment by GestQual** [comment] 2017-09-04 14:37
Thanks for the answer, hiddewie!

Unfortunatly, for what i need, the checkbox isn't sufficient.
I updated the icon, is it possible do to something with that?
I would really appreciate!

**Comment by tagliala** [comment] 2017-09-04 14:48
Hi!

Thanks for being part of the Font Awesome Community.

IMHO @hiddewie has a right point and the example is too complex for the base size (16px)

Also, this could be a duplicate of #2965

**Comment by hamidhasanih** [comment] 2018-03-07 15:39
hi !!!
I need an icon for Survey 
please add new item to your icons collection

**Comment by sensibleworld** [comment] 2024-07-11 19:43
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](Add "survey" search term to checklist, ballot, poll icons)

**Closed by sensibleworld** 2024-07-11 19:43 UTC
Labels: new icon, FA Pro

**Comment by tagliala** [comment] 2024-07-15 10:53
@sensibleworld I guess this icon is https://fontawesome.com/icons/ballot-check?f=classic&s=solid

**Comment by sensibleworld** [comment] 2024-07-15 12:19
Yup! Another case of a wonky script (and seeing some of our internal notes... oops!).
