### ISSUE TITLE
Icon Request: fa-drafting-compass

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#10001] opened 2016-09-29 18:22 UTC
Drafting Compass to depict the drafting of new courses or drawing of new guidelines 
![drafting-compass](https://cloud.githubusercontent.com/assets/539719/18966674/1d4ad220-8650-11e6-931e-fd212649bb3a.png)
for use wihin a healthcare data app

**Comment by tagliala** [comment] 2016-09-30 09:02
Duplicate of #1378, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 09:02 UTC
