### ISSUE TITLE
Harvey Balls

### ISSUE THREAD

**Issue by mario-cristiani** [FortAwesome/Font-Awesome#16334] opened 2020-03-18 16:21 UTC
**What can it be used for?**
https://en.wikipedia.org/wiki/Harvey_balls

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/14909651/76982933-d0f3b780-68f9-11ea-8ae6-2cbf5da72ae2.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-03-18 17:20
Hi!

Thanks for being part of the Font Awesome Community.

Since we already have:
- circle
- half-circle (adjust)
- empty circle (far fa-circle)

The only missing icons are circle-quarter and circle-three-quarters, so this is a duplicate of #1357

Please +1 that request

Closing here

**Closed by tagliala** 2020-03-18 17:20 UTC
