### ISSUE TITLE
Icon request: icon-square-in-square ?

### ISSUE THREAD

**Issue by Michael-Oxygen** [FortAwesome/Font-Awesome#19174] opened 2022-07-07 08:02 UTC
Hey 
Can it be possible to add a icon related to a picture in picture mode ?
Thx 🙏

**Comment by tagliala** [comment] 2022-07-07 08:12
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #10991, but I can see that you already commented there and for the moment it is the best thing you can do to express interest in the request

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-07-07 08:12 UTC
