### ISSUE TITLE
Icon request : fa-washing-machine

### ISSUE THREAD

**Issue by bencagri** [FortAwesome/Font-Awesome#6605] opened 2015-05-31 15:13 UTC
Everything is ok but those three...

![autocaravanas_servicios-01](https://cloud.githubusercontent.com/assets/823521/7902373/a78dc1a0-07c0-11e5-855b-eef5235bdc3b.jpg)

**Comment by tagliala** [comment] 2015-06-07 14:18
shower/bath is a duplicate of #708 

wc is a duplicate of #2670 

leaving this open as washing-machine

**Comment by tagliala** [comment] 2015-06-07 14:19
nope :grin: 

washing machine is a dup of #5914, please +1 that request

all dups, closing here

**Closed by tagliala** 2015-06-07 14:19 UTC

**Comment by alexptbg** [comment] 2017-11-02 06:54
+1
