### ISSUE TITLE
Ion request: TypeScript

### ISSUE THREAD

**Issue by Bradlcoulson** [FortAwesome/Font-Awesome#16098] opened 2020-01-21 19:20 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
one use case involves using this icon along with other web development logos, such as JavaScript, to promote a developer portfolio. 

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/53833680/72835656-0629b380-3c83-11ea-919e-82c7aad75e4e.png)

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-01-21 20:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11890, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-21 20:01 UTC
