### ISSUE TITLE
Icon Request: Store/Shop

### ISSUE THREAD

**Issue by AshSpera** [FortAwesome/Font-Awesome#11963] opened 2017-12-18 19:44 UTC
Can you make a "**Store**" or "**Shop**" icon please? Something like:

[https://iconmonstr.com/?s=shop](https://iconmonstr.com/?s=shop)

**Comment by tagliala** [comment] 2017-12-18 21:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1958 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-18 21:53 UTC

**Comment by nerobdms** [comment] 2018-02-20 23:42
Store not found.
