### ISSUE TITLE
Icon Request: icon- food building icon 

### ISSUE THREAD

**Issue by abidin13** [FortAwesome/Font-Awesome#6677] opened 2015-06-06 16:56 UTC
hi fontawesome,
please create a new icon like a food building icon or burger, pizza icon.
beacause this icon is a very identic for a web about food event or food place

i really hope this be done, for better fontawesome
thanks

**Comment by tagliala** [comment] 2015-06-07 09:32
refers to #1895 

pizza is a duplicate of #4493, please +1 that request
hamburger is a duplicate of #1961 , please +1 that request

closing here

**Closed by tagliala** 2015-06-07 09:32 UTC
