### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by WSHClan** [FortAwesome/Font-Awesome#11264] opened 2017-07-06 20:31 UTC
Hello,

can you make this Icon?

https://blog.mixer.com/content/images/2017/05/MixerAv.png

It´s a streaming plattform for Online Gaming on Microsofts Xbox One.

https://mixer.com

Thank you

**Comment by tagliala** [comment] 2017-07-07 08:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11242, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-07 08:13 UTC
