### ISSUE TITLE
Fontawesome Crashing Indesign on Export

### ISSUE THREAD

**Issue by jhubb-io** [FortAwesome/Font-Awesome#3960] opened 2014-07-22 13:22 UTC
I have found a strange little bug and narrowed it down to Fontawesome.

Create a new paragraph style in Indesign and add a Fontawesome character as a bullet. Assign this to some text and then export the document.

I have tested characters in body text and other fonts including icons fonts both in the body and bullets and this combination of Fontawesome in a bullet is the only one that causes a crash (and I think only on the latest version although I haven't tested this).

I'm hoping that I won't need a fresh install, so if someone can confirm the bug it would be great!

John

**Comment by blackdaw** [comment] 2015-05-22 11:14
Same here ... InDesign crashes when exporting to PDF files (for print). Sometimes it works, when I export it site by site. But this can't be the way. If you have an file with over 10+ sites it's inconvenient. Only those sites are affected where I used the font.

**Comment by pietrogregorini** [comment] 2015-07-27 07:33
I experience the same bug on InDesign CC 2015, using the checkmark as bullet point and OTF file.
No crash using the TTF webfont.

**Comment by marklanhamhc** [comment] 2016-11-14 16:16
I'm getting the same issue using FontAwesome v4.7.0 when exporting a page in InDesign that contains bullets made with the check symbol. If I change the symbol to something different it seems to work. Don't understand what the issue is!

**Comment by tagliala** [comment] 2016-11-14 17:44
Could you please try another icon font using PUA, like glyphicons?

**Comment by marklanhamhc** [comment] 2016-11-15 09:26
Yes, have tried switching to Glyphicons, same checkmark and it exports fine. But then when you change it back to FontAwesomes checkmark and export it crashes.

**Comment by tagliala** [comment] 2016-11-15 15:58
@marklanhamhc thanks. Does it happen with other icons or check is the only culprit?

**Comment by marklanhamhc** [comment] 2016-11-15 17:41
So far its only the fa-check that seems to do it. I've not noticed it on anything else.

**Comment by tagliala** [comment] 2016-11-15 18:23
@marklanhamhc since I don't have InDesign, I need to ask you other 2 tests.

1. Could you please try to start a new InDesign project without Font Awesome and use this char `` (you should see a square) as a bullet point?

2. [If InDesign didn't crash before] Could you please to install try [Material Design Icons](https://materialdesignicons.com/) and use [account-location](https://materialdesignicons.com/icon/account-location) as a bullet point?

**Comment by marklanhamhc** [comment] 2016-11-17 08:58
@tagliala Ok, I've tried creating a new project without FontAwesome and exported a document using the requested character and it exported ok. I can see a small rectangle with a question mark.

I have also tried exporting using Material Design Icons with the account-location as a bullet, this has also exported just fine.

**Comment by tagliala** [comment] 2016-11-18 13:47
Thanks, I don't know if changing the unicode point will help but I will assign this to 5.0.0 so Dave will eventually take a look

**Comment by marklanhamhc** [comment] 2016-11-20 18:52
Ok thanks, hopefully you guys can fix it for the next release.

**Comment by jonasskafte** [comment] 2017-02-08 18:23
The TTF webfont didn't work for me. I'm using InDesign CC 11.1.0.122 – don't know if that has anything to do with it..? For anyone in the same situation, here's how I'm working around the issue whilst waiting/hoping for a fix:

Convert the bullets to text – select some text, right click and "Convert bullets to text".

This worked and I could again export my work as PDFs for print. Just make sure you don't overwrite your original InDesign file when saving as you might want to go back and edit the lists. Also, it's a bit time consuming if you have many lists to do it to – but at least it works!

**Comment by tagliala** [comment] 2018-02-18 14:54
Is this still an issue?

**Comment by tagliala** [comment] 2018-03-14 10:31
No feedback, closing here.

If this is still an issue please let me know

**Closed by tagliala** 2018-03-14 10:31 UTC
Labels: bug, waiting for feedback
