### ISSUE TITLE
Icon Request: fa-train-side

### ISSUE THREAD

**Issue by anusreemn** [FortAwesome/Font-Awesome#16758] opened 2020-06-02 12:32 UTC
Hi,

I want to show direction on fa-train icon. Hence request for fa-train-side that shows a sideview of train, so that I can rotate it as required on the Map to point to the direction flow.

Similarly for *fa-ship* icon as well.

**Comment by tagliala** [comment] 2020-06-12 17:06
Hi!

Thanks for being part of the Font Awesome Community.

> Similarly for fa-ship icon as well.

Please open a new request or check #5628

**Comment by anusreemn** [comment] 2020-06-15 05:33
Hi @tagliala ,

Most welcome!

Sure, thanks will refer to the other issue for ship side icon. Please provide a train side icon here.

**Comment by sensibleworld** [comment] 2024-07-11 16:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/6287)

**Closed by sensibleworld** 2024-07-11 16:37 UTC
Labels: new icon, vehicles (category), Duplicate
