### ISSUE TITLE
Icon Request: sushi (🍣 nigiri)

### ISSUE THREAD

**Issue by stevensacks** [FortAwesome/Font-Awesome#18313] opened 2021-09-29 13:16 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.

Sushi 🍣 
Restaurant sites
Menus
Japanese related content

**Example image (optional)**

![image](https://user-images.githubusercontent.com/162252/135275491-bee41b73-219a-4430-8a84-6199b025e7c0.jpeg)

**Icon request checklist**
- [single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [yes] I have included at least one example image if it could be helpful (optional)
- [yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-09-29 14:29
Hi!

Thanks for being part of the Font Awesome Community.

Can this be considered a duplicate of #4985 ? I would like to add sushi there also in the title

**Comment by stevensacks** [comment] 2021-09-30 08:29
Alright time to get specific! 😀

Sushi is technically a category with multiple types.

This one that I am requesting is called nigiri. A slice of fish on top of a ball of rice. This is (arguably) the most common type.

The one in #4985 is called makizushi. Outside of Japan, it’s often called a sushi roll.

I think having both would be a good idea. I think including chopsticks should be a separate icon.

If you were going to make aliases for them, you could go with:

sushi and nigiri

sushi-roll and makazushi

**Comment by tagliala** [comment] 2021-09-30 08:33
Thanks for the clarification

> If you were going to make aliases for them, you could go with:

Yes, just want to improve titles for searching and managing purposes

**Comment by stevensacks** [comment] 2021-09-30 08:35
Sorry for the typo. It’s makizushi with an i not makazushi. I corrected it.

**Comment by sensibleworld** [comment] 2021-10-13 10:39
Hoping to add another batch of food-related icons soon. I'll get this on the list!

**Comment by sensibleworld** [comment] 2021-11-29 13:13
https://fontawesome.com/v6.0/icons/sushi?s=solid

**Closed by sensibleworld** 2021-11-29 13:13 UTC
Labels: new icon, food (category), released

**Comment by stevensacks** [comment] 2021-12-01 03:23
I think it needs to be angled like the emoji is, instead of head-on. 🍣
