### ISSUE TITLE
Icon request: icon-quora

### ISSUE THREAD

**Issue by vaxo** [FortAwesome/Font-Awesome#9000] opened 2016-04-16 14:54 UTC
Can you add [Quora](https://www.quora.com) icon? ^_^

Thanks

**Comment by tagliala** [comment] 2016-04-16 15:03
Duplicate of #510 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-16 15:03 UTC
