### ISSUE TITLE
Icon Request: fa-twilio

### ISSUE THREAD

**Issue by nbogol** [FortAwesome/Font-Awesome#5964] opened 2015-03-14 16:43 UTC
Very serious organization. Must have a Font-Awesome icon, please.
http://www.twilio.com

**Comment by tagliala** [comment] 2015-03-15 21:14
duplicate of #1849, please +1 that request

I should also suggest you to take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

closing here

**Closed by tagliala** 2015-03-15 21:14 UTC
