### ISSUE TITLE
Icon Request: fa-grains

### ISSUE THREAD

**Issue by tarunaggarwal54** [FortAwesome/Font-Awesome#9212] opened 2016-05-14 08:52 UTC
I am developing a online grocery store in which I need icons related to grocery.
![grain](https://cloud.githubusercontent.com/assets/19358761/15267417/5945c060-19df-11e6-963f-12fdc83800ea.png)

**Comment by tagliala** [comment] 2016-05-14 10:15
Duplicate of #2405 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-14 10:15 UTC
