### ISSUE TITLE
Font-weight: is possible in future?

### ISSUE THREAD

**Issue by vldbrb** [FortAwesome/Font-Awesome#8367] opened 2016-01-18 23:01 UTC
Hi all,

It is possible for future any font-weight feature for fontawesome? It will be a nice thing to provide a light (300), normal (400) and bold (700) or semibold (600) font-weight...

If it's possible, of course.

I'm using the fontawesome from last november and i love it!! The only thing that's missing is the weight control...

Thank you in both cases ;)

**Comment by tagliala** [comment] 2016-01-19 10:06
Hi, I'm going to consider this a duplicate of #1733

You should not expect this happening soon because it needs a full rewrite of all icons

You could consider to buy a license of [Font Awesome Black Tie](http://blacktie.io/) which is a multi-weight icon font from Dave

You can also look for other icon sets at https://icomoon.io/#icons

**Closed by tagliala** 2016-01-19 10:06 UTC
