### ISSUE TITLE
Icon request: icons for all alphabets

### ISSUE THREAD

**Issue by ksmonisha22** [FortAwesome/Font-Awesome#14122] opened 2018-10-16 15:32 UTC
### What can it be used for?

It will be useful for all the projects. If we are not finding appropriate icons, we can just use the first letter of that term.

**Comment by tagliala** [comment] 2018-10-16 18:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2828, which is out of scope at the moment

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-16 18:13 UTC
