### ISSUE TITLE
Icon request: icon-police

### ISSUE THREAD

**Issue by khojasahil** [FortAwesome/Font-Awesome#17471] opened 2020-12-10 17:01 UTC
Hello,

Can we please have a police icon ?

Thanks for all those great icons :)

**Comment by tagliala** [comment] 2020-12-10 17:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3372 or #10135, please add a 👍 reaction to those requests.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-12-10 17:23 UTC
