### ISSUE TITLE
Icon Request: fa-cookie

### ISSUE THREAD

**Issue by PanKlipcio** [FortAwesome/Font-Awesome#11834] opened 2017-12-04 21:35 UTC
**I would like a cookie icon to be added**
_Example  ~Freepik:_
![cookie_image](https://user-images.githubusercontent.com/21959209/33577387-1cbf93d0-d943-11e7-8c67-c4c81eeae969.png)

**Comment by tagliala** [comment] 2017-12-04 21:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2845 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-12-04 21:47 UTC
