### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by rivers488** [FortAwesome/Font-Awesome#13420] opened 2018-06-25 21:12 UTC
Requesting a new icon please. Icon request: **icon-parenthesis**.
My desire is to use this to represent the 'script' file-type. So, maybe you want to name it...
Icon request: **icon-script** - ? Don't know.

This is my first request, so I'm probably not doing it right. I tried to attach a vector (Adobe Illustrator) file of a parenthesis I created but it was not accepted, so I attach a PNG here.

Thank you, Kay
![parenthesisvector_02](https://user-images.githubusercontent.com/40579030/41876122-113ca0b6-788a-11e8-8325-1c1a513d047a.png)

**Comment by tagliala** [comment] 2018-06-25 21:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1797, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-25 21:13 UTC
