### ISSUE TITLE
Icon request: CarSeatEmpty

### ISSUE THREAD

**Issue by rajnish93** [FortAwesome/Font-Awesome#18058] opened 2021-07-08 22:08 UTC
**What can it be used for?**
It can be used in Car Specification like Seating Capacity.

**Example image (optional)**
![seat](https://user-images.githubusercontent.com/10815566/124996642-eea4dd00-e066-11eb-8980-b64773fdff85.png)

**Icon request checklist**
- [&#9745; ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [&#9745; ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ &#9745;] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [&#9745; ] I have included at least one example image if it could be helpful (optional)
- [&#9745; ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-07-08 22:39
Hi!

Thanks for being part of the Font Awesome Community.

I think this could be considered a duplicate of #2903

**Comment by sensibleworld** [comment] 2024-07-11 15:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 15:23 UTC
Labels: new icon, waiting for feedback, Declined
