### ISSUE TITLE
Icon request: web-form

### ISSUE THREAD

**Issue by mheidebrecht** [FortAwesome/Font-Awesome#15548] opened 2019-09-16 20:36 UTC
Use case: represent an individual web form

![image](https://user-images.githubusercontent.com/17099726/64991542-ec1c3680-d886-11e9-8a2e-bf84abfd2143.png)

**Comment by tagliala** [comment] 2019-09-17 07:02
duplicate of #15545

**Closed by tagliala** 2019-09-17 07:02 UTC

**Comment by mheidebrecht** [comment] 2019-09-17 17:17
Thx :)
