### ISSUE TITLE
Icon request: icon-ubuntu, icon-centos, icon-redhat, icon-fedora, icon-suse

### ISSUE THREAD

**Issue by otisg** [FortAwesome/Font-Awesome#980] opened 2013-04-23 14:04 UTC
These icons would be very popular and it would be great to have them.

**Comment by blade1989** [comment] 2015-01-12 11:01
+1

**Comment by MoonMaker** [comment] 2015-01-18 01:11
+1

**Comment by e2jk** [comment] 2015-01-28 22:39
+1

**Comment by AesenV** [comment] 2015-01-29 22:36
+1

**Comment by frensuren** [comment] 2015-02-03 03:55
+1

**Comment by cassidyjames** [comment] 2015-02-05 21:28
:+1: This would be handy, especially since we have the `apple` and `windows` icons. A lot of software, especially indie games, are available for one distro or another.

**Comment by Arisae** [comment] 2015-02-17 17:00
+1

**Comment by phavx** [comment] 2015-02-17 20:02
+1

**Comment by nathan-osman** [comment] 2015-02-20 22:02
:+1:

**Comment by LauritzT** [comment] 2015-02-27 23:14
+1
If you really need this, you could use Font Mfizz, wich "was designed as an extension to Font Awesome" and includes the most of these and others: http://fizzed.com/oss/font-mfizz

**Comment by pietroalbini** [comment] 2015-03-04 19:58
+1

**Comment by ReoDeveloper** [comment] 2015-03-06 21:08
+1

**Comment by Darkhogg** [comment] 2015-03-11 19:17
+1, and please also `fa-arch` or `fa-arch-linux`. Logo can be found [here](https://www.archlinux.org/art/).

**Comment by makcyd** [comment] 2015-03-11 19:19
+1

**Comment by Lukas-W** [comment] 2015-03-20 10:11
@tagliala 
Would it make sense to edit the first post to include links to [`font-linux`](https://github.com/Lukas-W/font-linux) and Font Mfizz (http://fizzed.com/oss/font-mfizz) for those who land here looking for an immediate solution?

**Comment by Ksiencha** [comment] 2015-04-14 14:08
:+1: 
I would really love to see `icon-arch-linux` :)

**Comment by Cysioland** [comment] 2015-04-14 14:10
@Ksenia Dylova :+1:

**Comment by RamzyVirani** [comment] 2015-04-21 13:18
+1

**Comment by ecksteing** [comment] 2015-08-03 10:59
+1

**Comment by qenchi** [comment] 2015-08-11 08:44
+1

**Comment by Cydrobolt** [comment] 2015-09-11 21:39
+1

**Comment by TwistedNL** [comment] 2015-09-11 22:18
+1

**Comment by mariogrip** [comment] 2015-09-28 12:23
+1

**Comment by kandaurov** [comment] 2015-11-26 13:11
+1

**Comment by mkg20001** [comment] 2016-01-10 11:37
+1

**Comment by codynguyen1116** [comment] 2016-01-10 15:33
+1

**Comment by bochecha** [comment] 2016-01-15 16:17
+1

Also, having the icons in the `fa-*-square` variants would be great.

**Comment by dzimine** [comment] 2016-02-02 02:55
+1

**Comment by Saboteur777** [comment] 2016-02-06 07:57
+1

**Comment by vinyanalista** [comment] 2016-02-19 13:02
+1

**Comment by tiferrei** [comment] 2016-02-19 21:25
+1

**Comment by Fale** [comment] 2016-03-13 23:01
+1

**Comment by slyscorpion** [comment] 2016-03-17 19:23
+1 and please add fa-antergos, if possible. Icon attached.

![antergos_icon](https://cloud.githubusercontent.com/assets/12873013/13858242/0ae896ec-ec7e-11e5-88cc-e4e711089913.png)

**Comment by dhanvi** [comment] 2016-03-21 16:27
+1

please make them as quickly as possible :smile: as you can see many people are waiting for them.

**Comment by DistantParadox** [comment] 2016-04-13 00:40
+1

Please add an Arch Linux logo

https://images.duckduckgo.com/iu/?u=http%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.Mca1e3cbffbdb38fad2f932b9b83827a8o0%26pid%3D15.1&f=1

**Comment by walchko** [comment] 2016-06-04 16:57
+1

Arch Linux too!

**Comment by tryton-vanmeer** [comment] 2016-06-06 09:47
+1

**Comment by schinzelh** [comment] 2016-07-04 12:08
+1

**Comment by cassidyjames** [comment] 2016-07-05 16:36
# Please do not `+1` comment on issues
Github has the handy reactions feature where you can put a :+1: on the original issue rather than continuing to flood the comments and everyone's emails.

_...Sorry for bothering anyone who's email-subscribed to this, hopefully it can cut down on noise for the future, though._

**Comment by souldanger** [comment] 2017-01-05 12:03
+1

**Comment by dischord01** [comment] 2017-04-21 15:49
Is there any plan to incorporate Red Hat brand icons into FA? 

Similar to this repo: http://lukas-w.github.io/font-linux/

**Comment by mattdm** [comment] 2017-12-11 21:06
Hi all. The Fedora symbol here loses the "infinity" aspect. I know this is a single-color font, and our preference is to use the wordmark when only one color is available, but we were experimenting with using checks or hashes and might be open to a special exception for this case. See some design work here: https://pagure.io/design/issue/539. What do you think?

**Comment by mairin** [comment] 2018-01-30 18:49
any thoughts on the above comment by @mattdm ?

**Comment by AngusP** [comment] 2018-05-03 15:54
+1

**Comment by maxxcrawford** [comment] 2018-05-10 22:02
+1

**Comment by professorchen06** [comment] 2018-06-05 10:21
pls make an arch brand too

**Comment by iredmail** [comment] 2018-07-19 14:37
+1 Please also add BSD distributions: OpenBSD, FreeBSD, NetBSD, DragonFly BSD.

**Comment by MarcHarrisscoding** [comment] 2018-07-25 16:23
+1

**Comment by PowerJESUS** [comment] 2018-08-03 10:15
+1

**Comment by Amolith** [comment] 2018-08-14 23:31
:+1:
Don't forget Arch! :wink:

**Comment by Sijisu** [comment] 2018-08-19 18:38
+1

**Comment by xulongwu4** [comment] 2018-09-28 20:38
Can you please also make one for Solus?

**Comment by riginoommen** [comment] 2018-12-11 13:57
#980 Love to see the red hat icon

**Comment by riginoommen** [comment] 2018-12-11 13:57
+1

**Comment by mairin** [comment] 2018-12-12 00:09
I'm sorry, the Fedora one is not in accordance with our logo usage guidelines. Can you please remove it?

**Comment by mattdm** [comment] 2018-12-12 15:05
@talbs Please see above comment. We recognize that the Fedora logo does not work in two colors and has challenges at small-icon sizes. We're working on a refresh of the logo (and associated guidelines) that we intend to address this. In the meantime, can you please remove the ad-hoc icon you've created? We really don't want that to proliferate. Thank you!

**Comment by tagliala** [comment] 2018-12-12 19:03
@mairin @mattdm thanks for the heads up, we will remove the logo asap

**Comment by davegandy** [comment] 2018-12-12 19:30
First up, hi Boston folks! Did you know Font Awesome was created in Kendall Square?

Second, I just wanted to mention that we work really hard to respect brand guidelines and keep things as up to date as possible. Last time Instagram had a new logo, we had a new version of Font Awesome within a day. We've also worked with companies directly around making minor tweaks where we'd missed something. We care deeply about this.

As far as the Fedora logo goes, we'll do whatever Red Hat / Fedora deems best. We'd really prefer not to remove the logo entirely, as this would be a breaking change. Not to mention that we've never had to remove a logo from Font Awesome ever before, so there'd be a good bit of development work needed to take care of this.

Is there any chance there's ax single-color version of the Fedora logo that works for you all in the meantime?

**Comment by davegandy** [comment] 2018-12-13 14:39
@mairin & @mattdm Apologies for forgetting to mention you directly in the thread above. ☝️ Any thoughts?

**Comment by mairin** [comment] 2018-12-13 15:18
@davegandy maybe you could use a blank glpyh in the meanwhile? we are working on a logo refresh that is able to be used one-color. the only other thing i can think, can you do grayscale? i have other font icon libraries that do grayscale so i think its technically possible.

**Comment by mattdm** [comment] 2018-12-13 16:00
My best idea is "Fedora wordmark squished really tiny", so I'll defer to @mairin as the actual design expert :)

**Comment by davegandy** [comment] 2018-12-13 16:48
@mairin A blank logo is a no-go for us, as we'll start getting bug reports and support issues.

@mattdm We could definitely do a squished wordmark in the meantime. We hate those due to all the points, but it's definitely something we'd be happy to do in the meantime.

**Comment by mairin** [comment] 2018-12-13 18:13
anything squished is a no-go. can you use the checkered mark we propose some time ago, understanding its temporary until our new logo design is available?

**Comment by rdebeasi** [comment] 2018-12-13 20:40
For more context, see the [Fedora Logo refresh issue](https://pagure.io/design/issue/620), the [Usage Guidelines](https://fedoraproject.org/wiki/Logo/UsageGuidelines) for the current logo, and the [Instagram icon update](https://github.com/FortAwesome/Font-Awesome/issues/9175).

Would it be acceptable to temporarily alias the Fedora icon to the [Linux icon](https://fontawesome.com/icons/linux?style=brands) so that `<i class="fab fa-fedora"></i>` displays a penguin? Once the Fedora logo redesign is done, Font Awesome could replace the penguin with a new brand-compliant logo. That way, there are no breaking changes, and no wonky Fedora logo.

Disclaimer: I'm not involved in these efforts; I just like both Fedora and Font Awesome. :smile:

**Comment by davegandy** [comment] 2018-12-13 21:47
@mairin By "squished" (that was a bad term for me to use) I meant just the full 'fedora' wordmark. Didn't mean changing aspect ratio of it at all. By squished, I meant that Font Awesome has a max width of 20 to a height of 16. So we could make the logo 20 wide by whatever height the logo turned out to be at that width. Then it would get vertically centered. Again, sorry for the strangely imprecise description of what I meant.

We could definitely go with the checkered mark you all mentioned a while back, especially given that it's temporary. Probably fewer points than the wordmark too. If that works, can you attach the final version here you'd like to use (I seem to remember a couple of possible implementations of the checkered mark.

**Comment by sensibleworld** [comment] 2018-12-14 17:42
@mairin I worked up a few quick alternate versions of the mark that *might* work better than the checkered version.

<img width="1182" alt="screenshot 2018-12-14 12 29 35" src="https://user-images.githubusercontent.com/529604/50018413-3f322780-ff9d-11e8-96a8-e0bdd5a714e2.png">

We can, of course, add the checkered version (or the Fedora wordmark) instead, but I wanted you to have some options :)

**Comment by mairin** [comment] 2018-12-14 20:58
Hi, unfortunately those wont work but thanks. Sorry for the slow replies here I'm actually on vacation atm. I will try to get a finalized version of the checkered one done this weekend.

**Comment by mairin** [comment] 2018-12-14 21:12
Why is this issue closed?

**Comment by davegandy** [comment] 2018-12-14 21:15
@mairin Understood that none of those will work. No sweat at all, just trying to see if there was anything we could do to help. (Personally, I think that last one of his there is super creative, a way to de-emphasize the secondary part of the infinity sign.)

The issue was closed because all the other linux icons were added. I'll go ahead an re-open it for tracking, then we'll close it again when it gets all fixed up.

**Comment by mairin** [comment] 2018-12-17 21:20
here is the svg for one-color. i've zipped it bc github doesn't allow for svg attachments. this took a few days because i have been on vacation. i appreciate your attention to this issue and your updating this ASAP to help us limit exposure of the incorrect artwork.
[fedora_infinity_one-color_1path.zip](https://github.com/FortAwesome/Font-Awesome/files/2687862/fedora_infinity_one-color_1path.zip)
![fedora_infinity_one-color_1path svg](https://user-images.githubusercontent.com/799683/50116237-9e9b6c00-0217-11e9-9a04-de70812bf7c9.png)

**Comment by goyney** [comment] 2018-12-17 22:23
@mairin I'm sorry, but I need to be the bag guy here. That icon is really not acceptable. I respectfully request you go back to your design team and have them take another pass.

The purpose of an icon is to distinguish something in the simplest form possible that can be recognized at a magnitude of different sizes. The most common favicon size is 16px x 16px, which all those diagonal lines get completely lost at. In Material Design, the icon needs to be recognizable at 24dp, which this icon simply cannot satisfy. In fact, in can't even satisfy 48dp.

Here is an example:
![image](https://user-images.githubusercontent.com/1015040/50119303-5f254d80-0220-11e9-92c8-d632a52a9146.png)

---

Please reconsider this.

**Comment by mairin** [comment] 2018-12-17 23:58
@goyney are you part of upstream or just "chiming" in?

is there a private place I can converse with upstream, please?

**Comment by davegandy** [comment] 2018-12-18 15:03
@mairin: @sensibleworld and I are official Font Awesome folks. We'd prefer to keep the discussion in the repo, but you can drop me an email at dave@fontawesome.com if you need to.

**Comment by lukas-w** [comment] 2018-12-18 16:43
I'd kindly ask you to keep this discussion public as it is of interest for my icon font as well, see https://github.com/lukas-w/font-logos/issues/38, where @mattdm also requested the Fedora icon to be removed. I'd like to follow whatever decision is reached here as it appears I'm in the same situation as the Font Awesome team.

**Comment by mattdm** [comment] 2018-12-18 16:58
@goyney Please see the above discussion. We really don't want an unofficial, incorrect version of our logo to proliferate. The hatched-lines version is meant as a stopgap. We are in the process of designing a new logo, in part to address this very issue.

In the meantime, I think your example actually shows the stopgap design working as intended at 48×48 and even 16×16. The goal isn't to have distinct lines, but instead to hint at another shade. We know it's not perfect, but it retains the three design elements of the logo ("freedom, infinity, voice").

@sensibleworld I like your ideas, but they're too big of changes to serve the temporary purpose. If you'd like to join the Fedora design team in working on the new design, your input would be welcome there. (Off-topic for this so please contact me directly if you're interested, or join the Fedora Design list.)

**Comment by coderguy12** [comment] 2018-12-18 17:04
@mattdm Is it possible to join anyone to join your design team? I've been doing graphic design for over 20 years and all you are doing right now is hurting your brand. I have to agree with @goyney here.

**Comment by mattdm** [comment] 2018-12-18 17:39
The design team is open to anyone who wants to contribute. I don't think accusations of hurting our brand are very helpful, though. (And a bunch of people showing up with that accusation as their "contribution" certainly wouldn't be.)

"Please don't spread mangled versions of our trademark" doesn't seem like an unreasonable request. I really, really wish this had waited until our logo refresh work was completed. As it is, can you please help us make the best of the situation?

**Comment by rdebeasi** [comment] 2018-12-18 17:41
I'd like to ask for patience and kindness from fellow members of the community. Managing an open source project is hard. Designing a logo that everyone can be happy with is hard. Doing both of those things at the same time is an expert-level challenge.

Mo, Matt, and the rest of the Fedora community are doing awesome work on a difficult problem. The Font Awesome folks have absolutely stepped up to make things right with this icon. Design is iterative, and nobody gets it 100% right on the first try. If you're interested in this helping out with this stuff, you can [join the Fedora design team](https://fedoraproject.org/wiki/Join_the_Design_Team).

Please please please let's keep this thread focused on fixing a specific issue with the Fedora logo within Font Awesome, and let's trust that both project teams want to do right by each other.

**Comment by davegandy** [comment] 2018-12-18 17:55
@rdebeasi Much agreed. Let's try to keep our opinions phrased in the politest way we can possibly imagine. As a nice side effect, it makes it easier for other folks to listen.

**Comment by davegandy** [comment] 2018-12-18 20:56
@mairin Yep, we've got the work underway, and it should be in the next version.

**Comment by mairin** [comment] 2018-12-18 21:07
@davegrandy great, thank you! as you can understand we're concerned about the current one proliferating. What is the timeline for the next version?

**Comment by sensibleworld** [comment] 2018-12-20 20:31
@mairin Updated icon is now live in 5.6.3: https://fontawesome.com/icons/fedora?style=brands

**Closed by sensibleworld** 2018-12-20 20:31 UTC
Labels: brand icon, released

**Comment by anarchodin** [comment] 2018-12-31 00:40
Am I the only one who finds it weird that the Debian logo wasn't included in this request?

**Comment by mattdm** [comment] 2019-01-10 13:35
For those following along: next step in Fedora logo redesign process: https://blog.linuxgrrl.com/2019/01/09/which-new-fedora-logo-design-do-you-prefer/

**Comment by JohnMH** [comment] 2019-01-10 17:17
@mattdm You do mean *potential* logo redesign, right?

**Comment by archusr** [comment] 2019-01-10 20:53
Just playing around, not affiliated, enjoying the discussions, cheers. // @mairin 
 ` `

![fedora_logo_mono](https://user-images.githubusercontent.com/14299209/50996230-a3ef8c00-1521-11e9-9220-e0e7d7752dde.png)

**Comment by AlecsFerra** [comment] 2020-07-25 16:04
No archlinux icon?
