### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by gulamjilanikhan** [FortAwesome/Font-Awesome#11272] opened 2017-07-09 12:10 UTC
I want to length icon but is there no one length icon.

**Comment by tagliala** [comment] 2017-07-09 15:47
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this request is a duplicate of #1096 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-09 15:47 UTC
