### ISSUE TITLE
Icon request: fa-veg

### ISSUE THREAD

**Issue by akimsullec** [FortAwesome/Font-Awesome#9854] opened 2016-09-04 07:59 UTC
Hi guys!
Thank you for great awesome and very useful icon set!!!

Could you please add an icon for vegetarians products? This is very popular now.
![image](https://cloud.githubusercontent.com/assets/5579173/18229806/a238e678-728e-11e6-8908-79596865b3e9.png)

There are vector http://vegetarianmark.net/

Thank you!

**Comment by tagliala** [comment] 2016-09-04 09:11
Duplicate of #4950, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-04 09:11 UTC
