### ISSUE TITLE
Icon request: icon-monsters

### ISSUE THREAD

**Issue by tinwe** [FortAwesome/Font-Awesome#14348] opened 2018-12-04 01:37 UTC
The previous requests for a dinosaur icon has been closed, and they mostly related to a dedicated 8bit version resembling the Chrome connection issue icon.
I'd would love a plain simple dinosaur icon, and a complete monster set would be awesome, with minimalistic Monster, Werewolf, Godzilla, Vampire, Skeleton, Giant, Ork or even Cthulhu.
Would be perfect for gaming/nerd/horror sites.
At least a tentacle icon, an ankh icon and a minimalistic vampire fangs icon?

**Comment by tagliala** [comment] 2018-12-04 21:08
Hi!

Thanks for being part of the Font Awesome Community.

> I'd would love a plain simple dinosaur icon, and a complete monster set would be awesome, with minimalistic Monster, Werewolf, Godzilla, Vampire, Skeleton, Giant, Ork or even Cthulhu.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Cthulhu is a duplicate of #9351

If you are a Pro backer, you can request a set of inons the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Closed by tagliala** 2018-12-04 21:08 UTC

**Comment by StoneCypher** [comment] 2022-11-20 18:37
Hi, I am a pro backer, but I can't see that repository, @tagliala 

I tried following the `account/services` link, but searching that page for `github` only shows the generic footer link.  Are these instructions out of date?  Would be reasonable, they're four years old

As the creator of the `cthulhu` issue, I would like to request it in the pro repo, but I don't know how to get access

**Comment by tagliala** [comment] 2022-11-20 19:30
> As the creator of the cthulhu issue, I would like to request it in the pro repo, but I don't know how to get access

Hi @StoneCypher ,

things have changed in the laste few months, and this repository is currently being used for both Pro and Free requests

**Comment by StoneCypher** [comment] 2022-11-20 20:30
Understood.  Thanks.
