### ISSUE TITLE
Icon request: fa-cakephp

### ISSUE THREAD

**Issue by kesepara** [FortAwesome/Font-Awesome#9037] opened 2016-04-22 07:26 UTC
Hi,

Can you please add a slice of cake icon ? CakePHP developers wants it :)

Thanks.

**Comment by PeterShaggyNoble** [comment] 2016-04-22 11:33
Dupe of [#8391](https://github.com/FortAwesome/Font-Awesome/issues/8391)?

**Comment by tagliala** [comment] 2016-04-22 12:18
thanks, I wasn't able to find #8391

**Closed by tagliala** 2016-04-22 12:18 UTC
Labels: brand icons, new icon
