### ISSUE TITLE
Icon Request: fa-award

### ISSUE THREAD

**Issue by dpfahlert** [FortAwesome/Font-Awesome#8826] opened 2016-03-24 23:34 UTC
First off, thanks for providing so many great icons! I would like to request an 'Award' icon. I have come across multiple scenarios where I am in need of it. Example: Employee awards won for websites, athlete awards won, company awards won, etc... It would be great to have this as a part of your inventory, because currently we are having to hand make them. 

Thanks

David

![award1](https://cloud.githubusercontent.com/assets/18060386/14034200/3bcc5a18-f1de-11e5-895f-136fe773a953.jpg)
![award2](https://cloud.githubusercontent.com/assets/18060386/14034201/3bce8630-f1de-11e5-8aa2-d1075d147f2e.jpg)

**Comment by tagliala** [comment] 2016-03-24 23:44
Duplicate of #1898 , please +1 that request

closing here

**Closed by tagliala** 2016-03-24 23:44 UTC
