### ISSUE TITLE
Icon request: cow | cattle | bovine

### ISSUE THREAD

**Issue by ManasMadrecha** [FortAwesome/Font-Awesome#17938] opened 2021-05-26 10:17 UTC
**What can it be used for?**
The animal cow or any bovine category.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-05-26 11:45
Hi!

Thanks for being part of the Font Awesome Community.

Instagram icon is already available for Pro customers, and it is a duplicate of #4166:
- https://fontawesome.com/v5.15/icons/cow?style=solid

If you are wondering why some icons are only add to the Pro set, please take a look at our [FAQs](https://fontawesome.com/community/leaderboard/new#faqs) 

Closing here

**Closed by tagliala** 2021-05-26 11:45 UTC
