### ISSUE TITLE
Icon request: box-times

### ISSUE THREAD

**Issue by angus-mcritchie** [FortAwesome/Font-Awesome#17836] opened 2021-04-22 01:57 UTC
**What can it be used for?**
For a shipping application you can use box-check if the receiver has approved for the parcel to be left safe, you can use box-times when the receiver has not (signature required). You could also use it if the parcel was damaged.

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-04-22 07:51
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/hufysvg0/5/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by aethior** [comment] 2023-02-25 18:15
Duplicate of #16407?

cc/ @tagliala

**Comment by tagliala** [comment] 2023-02-25 18:59
Yes, thanks

**Closed by tagliala** 2023-02-25 18:59 UTC
Labels: new icon, logistics (category)
