### ISSUE TITLE
IconRequest: fa-bathroom

### ISSUE THREAD

**Issue by darkfire56j** [FortAwesome/Font-Awesome#8204] opened 2015-12-22 11:56 UTC
Hi,
it would be nice to add some extra room like bathroom:

http://www.realdealbathrooms.com/wp-content/uploads/2013/12/Accommodation-Hot-tube-icon.png

And also extend with alias "fa-bedroom" the already existing "fa-bed"

**Comment by caduvieira** [comment] 2015-12-22 12:25
related to #708

**Comment by tagliala** [comment] 2015-12-22 12:32
duplicate of #708

**Closed by tagliala** 2015-12-22 12:32 UTC
