### ISSUE TITLE
Icon request: fa-pixiv

### ISSUE THREAD

**Issue by adriculous** [FortAwesome/Font-Awesome#15876] opened 2019-11-27 19:20 UTC
**What can it be used for?**
Pixiv (https://pixiv.net) is a Japanese art community which can be considered as a lighter version of DeviantArt. A few years ago, Pixiv has opened their community memberships to global artists, and many of us global artists have opened Pixiv accounts. We'd like to have a Pixiv social media icon to link our accounts to our portfolio sites and other social media channels.

I was building my portfolio and was looking for a Pixiv icon from FA and did not come up at the results.

**Example image (optional)**
https://images.app.goo.gl/qJHws12anX3w8MQA8

This will be under "Brand" icon category.

The "P" on the Pixiv logo is what Japanese artists use as their icon. Carrd.co also offers the Pixiv icon (the "P" from their logo) for artists who have an account.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-11-28 08:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5093, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-11-28 08:01 UTC
