### ISSUE TITLE
Icon request: bathroom

### ISSUE THREAD

**Issue by braewood** [FortAwesome/Font-Awesome#6967] opened 2015-07-17 04:33 UTC
![bath](https://cloud.githubusercontent.com/assets/13375534/8740662/d137dc12-2c90-11e5-9a5d-7528e2ce2df8.jpg)
I would like a bathroom / bath / shower icon so it can be displayed on a builders website to show how many bathrooms there are in the house.

**Comment by tagliala** [comment] 2015-07-17 11:10
duplicate of #708 , please +1 that request

closing here

**Closed by tagliala** 2015-07-17 11:10 UTC
