### ISSUE TITLE
Icon request: fa-magento

### ISSUE THREAD

**Issue by themecs** [FortAwesome/Font-Awesome#9932] opened 2016-09-19 07:38 UTC
Why you have not added Magento icon ?

**Comment by tagliala** [comment] 2016-09-19 13:31
Duplicate of #1754, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-19 13:31 UTC
