### ISSUE TITLE
Icon Request: fa-javascript

### ISSUE THREAD

**Issue by OnlyDrey** [FortAwesome/Font-Awesome#9944] opened 2016-09-22 12:04 UTC
Something like [this](https://wp-andypiapps.rhcloud.com/wp-content/uploads/2016/08/js4560_450.png), HTML5 & CSS3 exists, but not JavaScript.

It would be nice to have an icon for JavaScript as well as HTML5 & CSS3, it will be easier to make websites that needs to include programming language icons

**Comment by tagliala** [comment] 2016-09-22 13:34
Duplicate of #1711 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-22 13:34 UTC
