### ISSUE TITLE
Icon request: Network connected/disconnects (Link/Link Broken)

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#5555] opened 2015-02-01 19:42 UTC
There are the 'chain' icons but they're not QUITE what you'd expect

Also - we have "Wifi" but no "Wifi unavailable" icon

TIA!

**Comment by aawaara** [comment] 2015-03-17 14:34
+1

**Comment by paolofulgoni** [comment] 2015-03-25 16:47
+1

**Comment by jaykay2342** [comment] 2015-03-31 08:33
+1

**Comment by ckeryakes** [comment] 2015-10-07 17:05
+1 however, I don't agree with a chain link/unlink - that is typically associated with creating a hyperlink in a wysisyg environment. 

Personally I like this one (from Spotify, Offline indicator). 
![offline](https://cloud.githubusercontent.com/assets/11856569/10344894/daa1c918-6cf3-11e5-8d28-9c0324337af8.png)

Or something similar to this:
![5bce067c-6930-11e5-9c63-33cb1f2c5ed3](https://cloud.githubusercontent.com/assets/11856569/10344908/fa94afce-6cf3-11e5-9ddf-03727390614f.png)

Though I think the plug thing is a little overused, but essentially I would want to see something obviously broken. A bar, lightning bolt, or jagged horizontal line, split by a line. Just my 2 cents.

**Comment by leesah** [comment] 2015-11-10 05:04
+1

**Comment by kousha-icracked** [comment] 2015-12-08 19:06
+1

**Comment by Richie765** [comment] 2016-01-27 12:08
+1

**Comment by michaelhogg** [comment] 2016-02-21 12:13
+1

I think "plug" icons are probably the most common way of illustrating connection state.

A pair of icons like this would be great:
![](http://i.imgur.com/RbKZkI3.png)
I'm not sure whether the "disconnected" icon should have a warning triangle or not. It depends whether being disconnected is considered to be a bad thing. For use in apps which are designed to continue functioning while offline, it may not be desirable to have the "disconnected" state illustrated as a warning. I guess [`fa-exclamation-triangle`](http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/) can always be [stacked](http://fortawesome.github.io/Font-Awesome/examples/#stacked) separately.

**Comment by chillinski** [comment] 2016-03-03 10:45
+1

**Comment by sacredseven** [comment] 2016-03-04 14:02
+1

**Comment by tagliala** [comment] 2016-03-04 15:16
possible duplicate of #4611

**Comment by denkan** [comment] 2016-03-17 12:46
+1

**Comment by denkan** [comment] 2016-03-17 12:54
wifi-slash +1

**Comment by mickeyvip** [comment] 2016-03-28 08:21
+1

**Comment by schurter-cw** [comment] 2016-04-01 06:57
+1

**Comment by givanfp** [comment] 2016-07-19 21:05
+1

**Comment by WangJi** [comment] 2016-08-09 10:50
+1
disconnect/unplug

**Comment by beaster80** [comment] 2016-08-17 11:57
+1

**Comment by seasquawks** [comment] 2016-08-17 22:11
+1

**Comment by artamigo** [comment] 2016-10-11 15:52
+1

**Comment by jeanpijon** [comment] 2016-11-25 12:59
+1

**Comment by murone** [comment] 2016-12-19 14:51
+1

**Comment by Moxide** [comment] 2017-01-21 20:28
+1

**Comment by odintsaq** [comment] 2017-02-02 19:43
+1

**Comment by aklef** [comment] 2017-02-09 21:38
+1

**Comment by ptandler** [comment] 2017-02-21 19:26
+1 I really like the suggested icons! But the "disconnected" / "offline" icon should be without the warning trangle

**Comment by desombre** [comment] 2017-03-07 20:06
+1

**Comment by Ant1Zykl0n** [comment] 2017-03-07 20:06
+1

**Comment by oufresh** [comment] 2017-07-05 09:08
+1

**Comment by paulslaby** [comment] 2017-08-08 21:00
+1

**Comment by jimmy84** [comment] 2017-08-21 18:39
+1

**Comment by screambeard** [comment] 2017-08-23 13:17
+1

**Comment by henoSH** [comment] 2017-08-30 14:04
+1

**Comment by vfranchi** [comment] 2017-09-21 20:50
+1

**Comment by jpmnteiro** [comment] 2017-10-02 11:05
+1

**Comment by JuliuszJ** [comment] 2017-10-13 07:25
+1

**Comment by mtiutiu** [comment] 2017-11-06 12:23
+1

**Comment by JamiePrentice** [comment] 2017-12-06 15:20
+1

**Comment by Koubi4cK** [comment] 2017-12-15 02:01
+1

**Comment by egeersoz** [comment] 2017-12-18 04:13
Wow, two years and tons of upvotes and we still don't have this? :)

**Comment by xpleria** [comment] 2018-02-13 11:11
+1

**Comment by jmdavid** [comment] 2018-05-10 20:58
+1
What's the status for that?

**Comment by ThaJay** [comment] 2018-05-29 10:18
+1, specifically, this one:

https://material.io/tools/icons/?search=signal%20wifi%20off&icon=signal_wifi_off&style=baseline

**Comment by Bobsar0** [comment] 2018-06-26 17:48
Offline icon without the warning +1

**Comment by ZSkycat** [comment] 2018-08-23 06:12
wifi-slash 
![image](https://user-images.githubusercontent.com/20368649/44507804-89398980-a6de-11e8-87b0-0bc29f70be72.png)

**Comment by Cremba** [comment] 2018-08-23 15:39
+1

**Comment by sensibleworld** [comment] 2018-12-11 16:12
Do these cover this request, or are we still missing something?

- link: https://fontawesome.com/icons/link?style=solid
- unlink: https://fontawesome.com/icons/unlink?style=solid
- wifi: https://fontawesome.com/icons/wifi?style=solid
- wifi-slash: https://fontawesome.com/icons/wifi-slash?style=solid

**Comment by jmdavid** [comment] 2018-12-11 17:30
@sensibleworld I like them.

**Comment by beaster80** [comment] 2018-12-11 21:01
Yes very nice!
This is what I was looking for.

Best Regards,

Tjeerd van Beek

[GoMoCha]

Tjeerd van Beek | Product Owner
T +31 (0)418 572 888 | M +31 (0)627 031 750 | W www.gomocha.com<http://www.gomocha.com/>
More: LinkedIn<https://www.linkedin.com/company/gomocha> | Blog<http://www.gomocha.com/blog-en-gb/> | Trial<http://go.gomocha.com/l/273862/2016-12-20/21x9> | Demo<http://go.gomocha.com/l/273862/2016-12-19/z8p>

**Comment by sensibleworld** [comment] 2018-12-11 21:52
Awesome. Closing this issue :)

**Closed by sensibleworld** 2018-12-11 21:52 UTC
Labels: new icon, web application icons

**Comment by Llorx** [comment] 2019-12-03 11:21
Although those cover the issue for the OP, do not cover it for the rest of +1
