### ISSUE TITLE
Icon request: diameter

### ISSUE THREAD

**Issue by lennartvdd** [FortAwesome/Font-Awesome#6861] opened 2015-07-02 12:11 UTC
There are some usable size icons in fa (vertical/horizontal arrows), but i'm missing a diameter icon.

**Comment by tagliala** [comment] 2015-07-05 12:39
any example?

**Comment by lennartvdd** [comment] 2015-07-05 13:19
![diameter](http://www.i2symbol.com/images/symbols/technical/diameter_sign_u2300_icon_128x128.png)

**Comment by tagliala** [comment] 2015-07-05 16:53
duplicate of #5852, please +1 that request

You will also find a workaround

closing here

**Closed by tagliala** 2015-07-05 16:53 UTC
Labels: waiting for feedback
