### ISSUE TITLE
Icon request: Shrimp

### ISSUE THREAD

**Issue by veringm** [FortAwesome/Font-Awesome#15080] opened 2019-05-27 13:23 UTC
### What can it be used for?
To be displayed in an mobile-app for reporting various animal-crew sizes. Already using the existing fontawesome pro animal icons.

The user can easily find the right animal-type to update (icon follow by helper text).

### Example image (optional)
http://lcrws.org/wp-content/uploads/Shrimp1_1.jpg

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-05-27 13:24
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5764, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-05-27 13:24 UTC

**Comment by veringm** [comment] 2019-05-27 13:32
Sorry for not looking thoroughly enough. And thanks for your great work!

**Comment by tagliala** [comment] 2019-05-27 13:37
Don't worry 👍
