### ISSUE TITLE
Icon Request: fa-blog

### ISSUE THREAD

**Issue by jiemushi** [FortAwesome/Font-Awesome#10976] opened 2017-04-22 21:19 UTC
Hi!

I'm such a huge fan of these icons. I was just wondering if you'd make an icon that would represent a blog or maybe Blogger icon? I am placing a link to my blog/Blogger from my personal site. I'm not really sure how a blog should be represented. I'm completely happy using the pencil icon at the moment though it seems to be a bit lacking. Perhaps a pencil and paper icon? Or maybe something with the word "blog?" Thank you very much! :)

**Comment by tagliala** [comment] 2017-04-22 22:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1088 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-22 22:06 UTC
