### ISSUE TITLE
request: Open envelope

### ISSUE THREAD

**Issue by thomasbjorndahl** [FortAwesome/Font-Awesome#9078] opened 2016-04-28 10:50 UTC
...for showing already read messages....

**Comment by RoumedG** [comment] 2016-04-28 11:07
+2

**Comment by tagliala** [comment] 2016-04-28 11:12
Duplicate of #897 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-28 11:12 UTC
