### ISSUE TITLE
Icon request: fa-weight

### ISSUE THREAD

**Issue by leorue** [FortAwesome/Font-Awesome#7250] opened 2015-08-17 19:37 UTC
As part of your health and medicine section I would like to see a barbell icon added. For people in the healthcare industry this is a good representation and option for iconography for workouts, fitness and other health concepts.

Here is an example I like:
![dumbbell-512](https://cloud.githubusercontent.com/assets/2694712/9314273/ddfb4d58-44f5-11e5-93cb-ac7fccd750a6.png)

**Comment by KevRyan2** [comment] 2015-08-17 19:41
Lost count of the amount of times I wished this existed

**Comment by tagliala** [comment] 2015-08-17 20:41
Duplicate of #1500 :)

Please +1 that request

Closing here

**Comment by tagliala** [comment] 2015-08-17 20:41
Please also post there your example

**Closed by tagliala** 2015-08-17 20:41 UTC
