### ISSUE TITLE
Icon Request: fa-tractor

### ISSUE THREAD

**Issue by luchi20** [FortAwesome/Font-Awesome#9382] opened 2016-06-09 11:48 UTC
Hello,
Could you add an icon for a tractor? a agricultural machine. It is very util for everyone.
Could be: fa-tractor
Something like:
![tractor](https://cloud.githubusercontent.com/assets/19836484/15928708/e109eae6-2e1e-11e6-902c-45d5ac68c7a2.png)

Thank you very much

**Comment by tagliala** [comment] 2016-06-09 12:46
Duplicate of #5052, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-09 12:46 UTC
