### ISSUE TITLE
Icon Request: Barnes&Noble

### ISSUE THREAD

**Issue by sbarclay01** [FortAwesome/Font-Awesome#19018] opened 2022-05-09 00:49 UTC
I'd like to request Barnes&Noble be added to the Brands icons. A lot of authors sell books through B&N, and they often request buttons be created for this and other stores.

Thank you!

**Comment by sbarclay01** [comment] 2022-05-09 00:49
Here are a couple options: 
![Barnes   Noble-logo](https://user-images.githubusercontent.com/98122410/167323298-373507c6-17d9-4f3f-9a37-518c4b7dc001.svg)
![355e9c22ee7a62467bb2d7b8f3800907](https://user-images.githubusercontent.com/98122410/167323320-53159979-947e-4f36-bbe8-1f7d22715c1d.svg)

**Comment by tagliala** [comment] 2022-05-09 08:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12992, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-05-09 08:11 UTC
