### ISSUE TITLE
Icons request: icon-paint-bucket

### ISSUE THREAD

**Issue by Killerbear** [FortAwesome/Font-Awesome#10794] opened 2017-03-15 15:33 UTC
i´m building a simple texteditor and miss an icon for changing the text background color.
something like this would be very nice.

![paintbucket](https://cloud.githubusercontent.com/assets/5721655/23956313/a432bbde-099c-11e7-86cb-00e8c5ca686a.jpg)

**Comment by tagliala** [comment] 2017-03-15 15:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3270, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-15 15:37 UTC
