### ISSUE TITLE
Icon request: Buy-Me-A-Coffee

### ISSUE THREAD

**Issue by Robobulo** [FortAwesome/Font-Awesome#20030] opened 2023-11-30 14:37 UTC
![bmc-logo_light](https://github.com/FortAwesome/Font-Awesome/assets/145817463/bc2dc3e6-4b10-4fec-b26f-544573365166)

![bmc-logo](https://github.com/FortAwesome/Font-Awesome/assets/145817463/68d1083e-c6c0-4bca-bde1-a3221e529096)

I thought that we could add a "buy me a coffee" icon, because in my website, I needed a "Support-me" icon, and having a "buymeacoffee" icon would have been a lot easier, and would fix a lot of bugs.

**Comment by tagliala** [comment] 2023-11-30 14:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16336, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-11-30 14:45 UTC
