### ISSUE TITLE
Icon Request: fa- bandcamp

### ISSUE THREAD

**Issue by Pavelitooo** [FortAwesome/Font-Awesome#9764] opened 2016-08-17 13:43 UTC
Dear support,

there is a huge music platform called bandcamp. Many independet bands use it to promote their music and to built own bandwebsites. Right now, I am creating a bandwebsite with wordpress. In the header I use the fontawesome widget to link the social profiles of the band. You can see it here if you want. http://redensart.pavelito.com/
The bands wants me to link their bandcamp site (https://redensart.bandcamp.com/). Right now, Fontawesome does not support the Bandcamp Icon. It would be wonderful, if you could include it with the next update. Thank you very much!
Best regards from Berlin
Pavel
![bcamp160113](https://cloud.githubusercontent.com/assets/21082600/17738372/43306f76-6491-11e6-985a-6a00c03c174c.png)

**Comment by tagliala** [comment] 2016-08-17 14:09
Duplicate of #1725, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-17 14:09 UTC
