### ISSUE TITLE
Icon Request: fa-telegram

### ISSUE THREAD

**Issue by LateWiksi** [FortAwesome/Font-Awesome#5474] opened 2015-01-25 09:57 UTC
I would like to use Telegram (logo) icon justl ike I'm using WhatsApp icon. Telegram is WhatsApp alternative which is working with all oprating systems (Windows, OS X, Android, iOS, WPhone, Debian [Linux])

Telegram http://www.telegram.org/
<img src="http://icons.iconarchive.com/icons/froyoshark/enkel/128/Telegram-icon.png" border="0" />

**Comment by Theminijohn** [comment] 2015-01-25 11:57
Isn't there `fa-paper-plane` which is exactly that ?

**Comment by tagliala** [comment] 2015-01-25 12:11
hmmm @Theminijohn good point

btw duplicate of #3034, please +1 that request

closing here

**Closed by tagliala** 2015-01-25 12:11 UTC

**Comment by amraei** [comment] 2016-01-12 22:04
+1

**Comment by OxGroup** [comment] 2016-03-28 11:37
+1

**Comment by maherAshori** [comment] 2016-04-09 12:53
+1

**Comment by tagliala** [comment] 2016-04-09 12:53
locking here, this is a duplicate
