### ISSUE TITLE
Icon request: TailwindCSS

### ISSUE THREAD

**Issue by TylerAPfledderer** [FortAwesome/Font-Awesome#17636] opened 2021-02-16 20:23 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.

As there is already an icon for Bootstrap and TailwindCSS is a growing CSS Framework, this should be included in the set. It can be used as an import for project tags like when a developer displays a portfolio.

**Example image (optional)**
Insert the example image here if necessary.

### 'fa-tailwind': 
![image](https://user-images.githubusercontent.com/65234762/108116752-0e147c80-706a-11eb-8a00-112678f190a6.png)

### 'fa-tailwind-circle': 
![image](https://user-images.githubusercontent.com/65234762/108117203-985ce080-706a-11eb-8dfa-5b80c8d6292e.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-02-16 20:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15389, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-02-16 20:29 UTC
