### ISSUE TITLE
New icon request fa:industry or fa:factory

### ISSUE THREAD

**Issue by edpichler** [FortAwesome/Font-Awesome#6882] opened 2015-07-06 12:56 UTC
I need an icon that represents the factory/industry idea:

![captura_de_tela_070615_095605_am](https://cloud.githubusercontent.com/assets/358696/8522510/38e414ea-23c5-11e5-93cc-9d80f52f3398.jpg)

**Comment by mattjacobsen** [comment] 2015-07-06 14:25
+1

**Comment by tagliala** [comment] 2015-07-06 17:21
duplicate of #1330 , please +1 that request

closing here

**Closed by tagliala** 2015-07-06 17:21 UTC
