### ISSUE TITLE
Icon Request: wc icon

### ISSUE THREAD

**Issue by You85** [FortAwesome/Font-Awesome#11363] opened 2017-08-06 11:59 UTC
![toilet-svg-5](https://user-images.githubusercontent.com/30325749/29003028-7145dace-7aaf-11e7-9ce3-fe8e409b1896.png)

**Comment by tagliala** [comment] 2017-08-06 12:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10126, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-06 12:28 UTC
