### ISSUE TITLE
I want an icon : pentagon

### ISSUE THREAD

**Issue by zhe123321** [FortAwesome/Font-Awesome#12248] opened 2018-02-05 03:43 UTC

**Comment by tagliala** [comment] 2018-02-05 10:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9077, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-05 10:47 UTC
