### ISSUE TITLE
Icon request: icon-swords

### ISSUE THREAD

**Issue by PlasticProd** [FortAwesome/Font-Awesome#11308] opened 2017-07-19 09:31 UTC
Hi!

We're currently working with my team on a game-themed project, and we're actively using your product (thank you for your hard work by the way).

Today we're missing a "fight" icon, and I came with the idea of 2 swords crossed, I've already created a draft for that (I would be really happy to help!).

<img width="14" alt="fichier 2 2x" src="https://user-images.githubusercontent.com/30287724/28360450-be41a062-6c75-11e7-934b-81e451dfdc63.png">
 Zoom x2: <img width="28" alt="fichier 2 2x" src="https://user-images.githubusercontent.com/30287724/28360450-be41a062-6c75-11e7-934b-81e451dfdc63.png"> 

Use cases would be:

- Fight
- Game
- Weapons
- Medieval
- War

Let me know if you need more information.

Thank you for your time and have a great day!

**Comment by tagliala** [comment] 2017-07-19 10:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6504, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-19 10:09 UTC
