### ISSUE TITLE
Icon request: icon-ubuntu

### ISSUE THREAD

**Issue by RafoxSama** [FortAwesome/Font-Awesome#14038] opened 2018-09-29 14:16 UTC
http://konpa.github.io/devicon/devicon.git/icons/ubuntu/ubuntu-plain.svg

**Comment by troe** [comment] 2018-12-04 07:41
Icons of other distros also need to be added.

**Comment by tagliala** [comment] 2018-12-04 21:02
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #980 , please add a 👍 reaction to that request.

That request is in progress, popular linux distros will be soon part of the set 🎉 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-12-04 21:02 UTC
