### ISSUE TITLE
Icon request: fa-report-builder

### ISSUE THREAD

**Issue by abhimanyusingh** [FortAwesome/Font-Awesome#13592] opened 2018-07-21 02:09 UTC
I need an icon of report-builder like this one

![report-builder](https://user-images.githubusercontent.com/3057450/43031136-8652ee44-8c69-11e8-983f-d1be105c3e6b.png)

Thanks!

**Comment by tagliala** [comment] 2018-07-21 12:48
Do
- https://fontawesome.com/icons/chart-bar?style=solid
- https://fontawesome.com/icons/signal?style=solid
- https://jsfiddle.net/tagliala/ydq3jrne/54/
fit your needs?

Could this be considered a duplicate of #1076?

**Comment by abhimanyusingh** [comment] 2018-07-26 15:24
I don't think so..the dotted circle represents the reports building is in progress. because some time report generation take one or two days.

**Comment by abhimanyusingh** [comment] 2018-07-30 18:19
@tagliala waiting for response?

**Comment by tagliala** [comment] 2018-07-30 20:09
Please take a look at this comment: https://github.com/FortAwesome/Font-Awesome/issues/13593#issuecomment-408993589

**Comment by sensibleworld** [comment] 2024-07-11 19:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 19:23 UTC
Labels: new icon, Declined
