### ISSUE TITLE
Icon Request: fa-arrows-inwards-alt

### ISSUE THREAD

**Issue by SylvainCorlay** [FortAwesome/Font-Awesome#6620] opened 2015-06-01 20:20 UTC
This is an inwards version of fa-arrows-alt.

Icon name  | Example
------------- | -------------
fa-arrows-inwards-alt  |  ![inward](https://cloud.githubusercontent.com/assets/2397974/7922396/f75b2d3a-0879-11e5-949c-723915a17218.png)

I have svg and glyph versions of this icon if you are willing to use this design. (Should be pixel perfect at 14px).

**Comment by sccolbert** [comment] 2015-06-01 20:26
+1 makes sense

**Comment by goanpeca** [comment] 2015-06-02 08:07
:+1:

**Comment by tagliala** [comment] 2015-06-02 13:27
Duplicate of #1468, please +1 that request

Edited #1468 to include fa-arrows-inwards-alt in the title

@SylvainCorlay please post there your comment

**Closed by tagliala** 2015-06-02 13:27 UTC
Labels: new icon, waiting for feedback, web application icons
