### ISSUE TITLE
Icon request: AO3

### ISSUE THREAD

**Issue by Fallowsthorn** [FortAwesome/Font-Awesome#17014] opened 2020-08-08 22:51 UTC
I'd like to have an icon to keep my Archive of Our Own page link in line with my other external site links (also, I'm not good enough at HTML to make my own image version). Simply using their logo should work:

![](https://archiveofourown.org/images/ao3_logos/logo_42.png)

unless the icon needs to be square, in which case.... maybe the version that shows in the browser tab?

**Comment by aethior** [comment] 2022-04-11 20:02
Duplicate of #5188.

cc/ @tagliala

**Closed** 2022-04-11 21:08 UTC
Labels: brand icon
