### ISSUE TITLE
Request New Icon

### ISSUE THREAD

**Issue by naradado** [FortAwesome/Font-Awesome#11515] opened 2017-09-12 12:17 UTC
Booking.com icon

**Comment by tagliala** [comment] 2017-09-12 12:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5257, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-12 12:35 UTC
