### ISSUE TITLE
could you make icon for Terraform https://www.terraform.io/

### ISSUE THREAD

**Issue by sahotay** [FortAwesome/Font-Awesome#16017] opened 2020-01-04 22:22 UTC
could you make icon for Terraform `https://www.terraform.io/`

**Comment by tagliala** [comment] 2020-01-04 22:32
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9611, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

If you are interested in understanding how requests work, please take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs)

Closing here

**Closed by tagliala** 2020-01-04 22:32 UTC
