### ISSUE TITLE
Icon Request: icon-air-conditioning

### ISSUE THREAD

**Issue by deyacol** [FortAwesome/Font-Awesome#3211] opened 2014-04-08 22:30 UTC
I am making an application for a hotel, I need more icons. Could I develop? How do I do?

**Comment by aquerrec** [comment] 2015-08-25 15:43
+1

**Comment by MarGraz** [comment] 2016-05-07 17:27
+1

**Comment by coleby210** [comment] 2016-05-29 05:08
+1

**Comment by tagliala** [comment] 2016-07-20 08:57
is this a duplicate of #1739 ?

If not, could you please provide a single color example?

**Comment by CreativeNative** [comment] 2018-07-24 13:48
+1

**Comment by sensibleworld** [comment] 2019-12-11 19:06
We have few options to keep up cool now: https://fontawesome.com/search?q=air%20%20conditioner&s=solid%2Cbrands

**Closed by sensibleworld** 2019-12-11 19:06 UTC
Labels: in progress, new icon, released, web application icons
