### ISSUE TITLE
Icon Request: fa-disco

### ISSUE THREAD

**Issue by 79137913** [FortAwesome/Font-Awesome#10146] opened 2016-10-31 17:26 UTC
Disco Ball light

**Comment by tagliala** [comment] 2016-10-31 17:41
Duplicate of #5050, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-31 17:41 UTC
