### ISSUE TITLE
Icon request: Electron.js

### ISSUE THREAD

**Issue by florian-lefebvre** [FortAwesome/Font-Awesome#17142] opened 2020-09-13 15:18 UTC
# Single icon
![image](https://user-images.githubusercontent.com/69633530/93021787-fcbfd380-f5e4-11ea-8114-5058b43bca4b.png)

**Comment by tagliala** [comment] 2020-09-13 15:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11955, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-13 15:55 UTC
