### ISSUE TITLE
Icon request: fa-skills, fa-think

### ISSUE THREAD

**Issue by Chej0** [FortAwesome/Font-Awesome#11054] opened 2017-05-11 17:42 UTC
I need an icon that represent mental skills and other that represent personal interests. I was thinking something like this.

Mental Skills
![image](https://cloud.githubusercontent.com/assets/26882572/25963455/96f38a6a-363e-11e7-9661-9d4c3416fcbb.png)

Interests
![image](https://cloud.githubusercontent.com/assets/26882572/25963497/b5b20508-363e-11e7-92b9-0e2dcc3d8b52.png)

I need to use in a psycological page that make mental skills tests

**Comment by Jacharsam** [comment] 2018-02-13 00:31
You can use the <i class="fas fa-paint-brush"></i> paint brush icon. This also is often used by some companies to depict skill-set. So I think you can use that instead in case you don't find what you are looking for in fontawesome.

**Comment by tagliala** [comment] 2018-02-13 13:33
Hi!

Thanks for being part of the Font Awesome Community.

"Mental Skills" is a duplicate of #8675, please add a 👍  reaction to that request.
We need a better title for "interests". I will go for `user-thinking`

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

**Comment by stevemao** [comment] 2019-01-13 03:08
Or this:

<img width="166" alt="screen shot 2019-01-13 at 2 07 42 pm" src="https://user-images.githubusercontent.com/6316590/51081129-a24de000-173c-11e9-93de-a0c7705a2505.png">

**Comment by t-boye** [comment] 2023-03-27 16:40
I need an icon that represent all the programming skliis
like this :
<i class="fa-brands fa-css3 "></i>

**Comment by sensibleworld** [comment] 2024-07-15 15:10
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-15 15:10 UTC
