### ISSUE TITLE
Icon Request: money-slash

### ISSUE THREAD

**Issue by Farenheith** [FortAwesome/Font-Awesome#9287] opened 2016-05-27 17:55 UTC
Greetings!

First of all I loved fontAwesome, it's really great!
I would love with you guys could add a "money-slash" icon like this one http://fontawesome.io/icon/money/, but with a slash, as in this one http://fontawesome.io/icon/microphone-slash/

The idea is to have a button to mark some item of a grid as "paid" (money icon) when it is not paid yet, and a button to mark it as "not paid" (money-slash icon) when the user want to cancel the action

Thank you!

**Comment by tagliala** [comment] 2016-05-28 10:27
Refers to #1181

**Comment by Farenheith** [comment] 2016-05-30 14:14
Actually, yes. It fits. Thank you. Sorry for the duplicate request.

**Comment by tagliala** [comment] 2016-05-30 19:00
Not a duplicate, but #1181 contains techniques to implement this icon

**Comment by sensibleworld** [comment] 2024-07-10 15:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/14534)

**Closed by sensibleworld** 2024-07-10 15:23 UTC
Labels: new icon, payments & shopping (category), Duplicate
