### ISSUE TITLE
Icon Request: milk

### ISSUE THREAD

**Issue by el-duderino5** [FortAwesome/Font-Awesome#13960] opened 2018-09-17 22:43 UTC
A milk icon would be nice to have, one for spoiled and non-spoiled milk. Something like this:

Non-spoiled milk
![image](https://user-images.githubusercontent.com/6808300/45654329-2e127100-baa9-11e8-9705-f1fe3580efd6.png)

Spoiled milk:
![image](https://user-images.githubusercontent.com/6808300/45654400-76319380-baa9-11e8-8722-1f9a6691c7db.png)

(and/or) this:
![image](https://user-images.githubusercontent.com/6808300/45654421-8e091780-baa9-11e8-8d17-ff973f7d6d72.png)

**Comment by tagliala** [comment] 2018-09-18 08:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3663, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-18 08:44 UTC
