### ISSUE TITLE
Icon Request: fa-walk

### ISSUE THREAD

**Issue by somsharp** [FortAwesome/Font-Awesome#8180] opened 2015-12-19 06:02 UTC
It would be nice if we can have a walk icon similar to attached .svg in the zip
[Icon_Walk.zip](https://github.com/FortAwesome/Font-Awesome/files/67381/Icon_Walk.zip)

**Comment by tagliala** [comment] 2015-12-19 10:47
duplicate of #844, please +1 that request

**Closed by tagliala** 2015-12-19 10:47 UTC
