### ISSUE TITLE
New icon request: clipboard

### ISSUE THREAD

**Issue by ErikBosma** [FortAwesome/Font-Awesome#6645] opened 2015-06-03 08:28 UTC
Dear FortAwesome / Font-Awesome,

I would like to request a new 'clipboard' icon. One clipboard icon allready exists, but this is not suitable for our purposes yet. Could you please develop a new one, like the one I attached in this request?

I'd like to use it for indicating a service concept called 'Stock management'. We allready use a couple of other Fontawesome icons for other service concepts, this one will complete the whole package.

![icon clipboard](https://cloud.githubusercontent.com/assets/12727887/7955774/2e1fbbee-09db-11e5-84e2-6475a139b305.JPG)

Thanks in advance!

Kind regards,

Erik Bosma

**Comment by tagliala** [comment] 2015-06-03 14:12
I think this is a duplicate of #1230

**Comment by ErikBosma** [comment] 2015-06-12 08:45
Could be, but in the proposed icon there are no lines and multpile V's.

Any idea how long it takes for a new icon to be launched?

Thanks!

2015-06-03 16:12 GMT+02:00 Geremia Taglialatela <notifications@github.com>:

**Comment by sensibleworld** [comment] 2019-04-11 12:59
We have a few options for this now: https://fontawesome.com/icons?d=gallery&q=clipboard

**Closed by sensibleworld** 2019-04-11 12:59 UTC
Labels: waiting for feedback
