### ISSUE TITLE
Icon request: Slot machine icon

### ISSUE THREAD

**Issue by Madaluna** [FortAwesome/Font-Awesome#18083] opened 2021-07-16 10:04 UTC
**What can it be used for?**
For gambling industry
![slot machine](https://user-images.githubusercontent.com/84723532/125931155-d4202382-1913-4d72-96c4-644a563b76bd.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-07-16 10:08
Hi!

This request is a duplicate of #5839, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Do you have issues with search?

**Closed** 2021-07-16 10:09 UTC
