### ISSUE TITLE
Icon Request: fa-freelancer

### ISSUE THREAD

**Issue by prahladyeri** [FortAwesome/Font-Awesome#10443] opened 2016-12-29 07:24 UTC
The freelancing community is ever expanding and it has evolved to be a professional and much more serious career option in recent years. Lots of freelancers are in fact, web developers and many web based systems are in place that help in hiring freelancers for projects. So, I request a freelancer icon to be added to the fa library.

**Comment by tagliala** [comment] 2016-12-29 10:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6426, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-29 10:19 UTC

**Comment by bagewadi-akram** [comment] 2022-06-10 07:43
hi 
Please add a Freelancer icon
