### ISSUE TITLE
Website crashes on Firefox

### ISSUE THREAD

**Issue by rmcmorran** [FortAwesome/Font-Awesome#7788] opened 2015-10-31 19:41 UTC
The FontAwesome website crashes Firefox every time I open it on Firefox.
Firefox v. 41.0.2 on Win Vista

works fine on Chrome. The only site that does this - has been happening for the past week. Really odd.

**Comment by tagliala** [comment] 2015-10-31 20:09
Cannot confirm on Windows 10. Could you please try firefox in safe mode? (shift + click to open)

**Comment by rmcmorran** [comment] 2015-11-02 16:09
Hi there

thanks - I tried in safe mode as you suggest and it still has the same problem. 

Here's what seems to be happening: the site is stable on the home page and other site pages, but as soon as I click on the Icons link in the top navigation bar, Firefox falls over and I have to restart the browser.

Would it be helpful if I copied the code from the Mozilla crash report and sent it to you? 

thanks 

Robin

  ----- Original Message -----

**Comment by brendan-pike** [comment] 2015-11-03 06:59
I'm a Linux Cinnamon user and FontAwesome crashes my entire X windows every time it loads.
[AMD/ATI] Tahiti PRO [Radeon HD 7950/8950 OEM / R9 280]
$ dpkg -l | grep AMD
ii  fglrx-amdcccle-updates                                      2:15.200-0ubuntu0.5                                 amd64        Catalyst Control Center for the AMD graphics accelerators
ii  fglrx-updates                                               2:15.200-0ubuntu0.5                                 amd64        Video driver for the AMD graphics accelerators
ii  fglrx-updates-core                                          2:15.200-0ubuntu0.5                                 amd64        Minimal video driver for the AMD graphics accelerators
ii  libc6-i386                                                  2.19-0ubuntu6.6                                     amd64        Embedded GNU C Library: 32-bit shared libraries for AMD64
ii  xserver-xorg-video-radeon                                   1:7.5.99+git1510261932.7186a8~gd~t                  amd64        X.Org X server -- AMD/ATI Radeon display driver

**Comment by tagliala** [comment] 2015-11-13 14:21
@rmcmorran sorry but I think I cannot read a crash report.

Maybe someone experiencing this issue should test the documentation locally and see if it happens

Some questions:

1. What does it happen if you navigate other websites using fontawesome, such as:
  https://www.whitehouse.gov/
  https://www.maxcdn.com/
  http://ruby2-rails4-bootstrap-heroku.herokuapp.com/

2. What does it happen with javascript disabled?

**Comment by rmcmorran** [comment] 2015-11-13 15:31
Dont worry - the problem disappeared as quickly as it appeared. I suspect a recent Firefox update had something to do with it. All stable now. Thanks.

**Comment by tagliala** [comment] 2015-11-13 20:43
@brendan-pike same for you?

**Comment by evilaliv3** [comment] 2016-06-07 13:03
just as note we are experiencing the same using the Torbrowser that is based on Firefox 45: https://github.com/globaleaks/GlobaLeaks/issues/1680

**Comment by tagliala** [comment] 2016-06-07 13:18
IIRC, Torbrowser uses NoScript which blocks webfonts by default

**Comment by evilaliv3** [comment] 2016-06-07 13:46
nope that is not true but i'm sorry to have not attached the full detail i've right now on the issue.

the issue is affecting only the current Torbrowser on windows, and some versions of firefox, still on windows:
https://bugzilla.mozilla.org/show_bug.cgi?id=1228799#c26
https://bugzilla.mozilla.org/show_bug.cgi?id=1228799#c28

this is common between Glyphicons and FontAwesome causes somethimes simply to not see the fonts and other times to make the browser crash.

**Comment by tagliala** [comment] 2016-06-07 13:51
So this is an issue with firefox?

**Comment by tagliala** [comment] 2018-10-03 09:14
No feedback, closing here

**Closed by tagliala** 2018-10-03 09:14 UTC
Labels: waiting for feedback
