### ISSUE TITLE
Icon Request: icon-eBook

### ISSUE THREAD

**Issue by Linda-TAFE-NSW** [FortAwesome/Font-Awesome#11241] opened 2017-06-30 03:07 UTC
I would love to see an icon for eBooks so i can differentiate resources in a list of mixed formats.
![ebook-icon](https://user-images.githubusercontent.com/29789239/27719337-fcd851b2-5d94-11e7-995b-310e3400686a.png)
![ibooks](https://user-images.githubusercontent.com/29789239/27719335-fcd6a38a-5d94-11e7-9d4d-55d3e6eb4013.png)
![th72201db2](https://user-images.githubusercontent.com/29789239/27719336-fcd7d1e2-5d94-11e7-9669-4f5e7b255ef1.jpg)

**Comment by tagliala** [comment] 2017-06-30 06:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2356, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-30 06:36 UTC
