### ISSUE TITLE
Icon request: epic-games-store

### ISSUE THREAD

**Issue by Nicoooooo** [FortAwesome/Font-Awesome#18555] opened 2022-01-06 16:09 UTC
**What can it be used for?**
Lost of the equivalent logos (unity, steam, app store, ..) are available, but there is nothing about Unreal Engine or Epic Games Store.
A page offering a game on different platforms may therefore require such a logo.

**Example image (optional)**
<img width="135" alt="Capture d’écran 2022-01-06 à 17 09 27" src="https://user-images.githubusercontent.com/15833774/148413153-72146159-b33e-48ab-be91-30f7768a3ed1.png">

**Comment by tagliala** [comment] 2022-01-06 16:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16761, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2022-01-06 16:49 UTC
