### ISSUE TITLE
Icon request: fa-backspace

### ISSUE THREAD

**Issue by NielsHolt** [FortAwesome/Font-Awesome#13254] opened 2018-06-01 11:58 UTC
![image](https://user-images.githubusercontent.com/11357972/40839682-df0e812a-65a3-11e8-9ee4-55c170cb1323.png)

**Comment by tagliala** [comment] 2018-06-01 13:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1980 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-01 13:50 UTC
