### ISSUE TITLE
Icon Request: fab fa-tune-in

### ISSUE THREAD

**Issue by abelini** [FortAwesome/Font-Awesome#17764] opened 2021-03-23 00:27 UTC
Hi.

I think we need another brand icon: [TuneIn](https://tunein.com/).

I would use this icon to show visitors where to find my radio station in TuneIn or to link my site to its profile page inside TuneIn. It would be just another social network to connect to.

**Comment by tagliala** [comment] 2021-03-23 08:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3159, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-23 08:38 UTC

**Comment by abelini** [comment] 2021-04-05 21:55
The issue #3159 is 7 years old. And we still have no TuneIn icon...
