### ISSUE TITLE
Icon request: soda glass

### ISSUE THREAD

**Issue by rodlowe** [FortAwesome/Font-Awesome#13735] opened 2018-08-08 22:31 UTC
### What can it be used for?

restaurants, summer, beach, etc.

### Example image (optional)

Simple soda glass with straw, got attached from competitor.
![soda](https://user-images.githubusercontent.com/9307446/43867936-e0fb9816-9b30-11e8-8c45-c1e62d2d5328.png)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-09 07:31
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6122, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-09 07:31 UTC
