### ISSUE TITLE
Icon request: icon-line

### ISSUE THREAD

**Issue by mahmoodma** [FortAwesome/Font-Awesome#10582] opened 2017-01-29 07:28 UTC
LINE is a social messaging app worldwide, mostly like WhatsApp.
The users are mainly located in Asia area (https://line.me/)

Why I would like to request this icon is because I want to use in my social networking share link, thanks :D

**Comment by tagliala** [comment] 2017-01-29 12:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2631, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-29 12:27 UTC
