### ISSUE TITLE
Icon Request: fa-parking

### ISSUE THREAD

**Issue by morislubin** [FortAwesome/Font-Awesome#11228] opened 2017-06-26 08:20 UTC
Hi! Could you add please a Parking Icon? [P] Someting like that...

**Comment by tagliala** [comment] 2017-06-26 09:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1559, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-26 09:33 UTC

**Comment by morislubin** [comment] 2017-06-26 10:54
Ok! Thanks!
