### ISSUE TITLE
piggy bank icon requested

### ISSUE THREAD

**Issue by himanshu-u-crest** [FortAwesome/Font-Awesome#8511] opened 2016-02-09 07:22 UTC
Kindly requested to add piggy bank icon in next release.  Like this.
![piggy-icon](https://cloud.githubusercontent.com/assets/16666651/12909925/e93b77c2-cf2b-11e5-99e1-2871eb5f08b1.png)

**Comment by tagliala** [comment] 2016-02-09 10:13
duplicate of #1413 , please +1 that request

closing here

**Closed by tagliala** 2016-02-09 10:13 UTC
