### ISSUE TITLE
New Google Logo

### ISSUE THREAD

**Issue by ferkennedy** [FortAwesome/Font-Awesome#7384] opened 2015-09-03 21:29 UTC
Please change de g+ icon for the new one.

**Comment by TheChen5** [comment] 2015-09-03 22:22
Dupe #7357 
+1 that
Please  :mag:before:heavy_plus_sign:

**Comment by astropelusa** [comment] 2015-09-05 13:15
+1 please!

**Comment by meebwolf** [comment] 2015-09-08 07:14
+1 as well!

**Comment by FSElias** [comment] 2015-09-09 12:10
+1

**Comment by tagliala** [comment] 2015-09-11 12:11
closing here, duplicate of #7357

**Closed by tagliala** 2015-09-11 12:11 UTC
