### ISSUE TITLE
Icon-request:fa-sailing-ship

### ISSUE THREAD

**Issue by vito52** [FortAwesome/Font-Awesome#7312] opened 2015-08-26 20:29 UTC
Hi

I'm aware that there is a ship icon but i feel, and need :-) a sailing ship icon.

I did a quick sketch to clarify my request. An idea? possible?

best regards

Martin
![sailing-ship](https://cloud.githubusercontent.com/assets/5521779/9505283/d5471a4a-4c41-11e5-8644-74e09e3c7017.png)

**Comment by caduvieira** [comment] 2015-08-27 20:02
Dupe of #5079?

**Comment by vito52** [comment] 2015-08-28 12:39
yes and... I'd like one that keeps with the over-all look and feel of the rest of the icons. #5079 is pretty nice but I think too detailed to work as a black/white

**Comment by vito52** [comment] 2015-08-28 15:31
forgot to add a few examples of usage.

right now I need the sailing boat icon for a site i make for a small sailing club. Other than this, any site that deal with sailing boats, yachting or water-sports could benefit from a sailing boat icon.

I hope that there are others who agree :-)

**Comment by tagliala** [comment] 2015-09-13 19:07
closing here as a duplicate of #5079 

Feel free to post your example there

**Closed by tagliala** 2015-09-13 19:07 UTC
