### ISSUE TITLE
Icon request: sketchfab

### ISSUE THREAD

**Issue by Alverspin** [FortAwesome/Font-Awesome#18699] opened 2022-02-15 14:04 UTC
Sketchfab is one of the most important 3D assets websites and I need this icon!

**Comment by tagliala** [comment] 2022-02-15 19:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2757, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-02-15 19:54 UTC
