### ISSUE TITLE
Icon request: localised electrical outlets

### ISSUE THREAD

**Issue by Spatchy** [FortAwesome/Font-Awesome#18953] opened 2022-04-24 22:42 UTC
There is currently only one `outlet` icon, depicting a US outlet. It would be useful to have outlets from other regions e.g. UK, EU, etc.

**Potential Uses**
- Electrical/Electronics suppliers that need to differentiate compatibility
- Smart home devices
- Any app/site intended for a specific region that generally wants to use that region's outlet

**Comment by tagliala** [comment] 2022-04-25 11:12
Hi!

Thanks for being part of the Font Awesome Community.

> UK, EU, **etc.**

I think this request is legit, but the word "etc." is usually a red flag that a request is hard to manage

Is there any wikipedia page to show a list of the most common outlets, in order to make a comprehensive list of the icons that should be implemented?

**Comment by Spatchy** [comment] 2022-04-25 11:42
There is [this Wikipedia page](https://en.wikipedia.org/wiki/AC_power_plugs_and_sockets#Types_in_present_use) However, it seems overly verbose. A better source is the [IEC](https://www.iec.ch/world-plugs) (The organisation responsible for publishing electrical standards) which has a list of the 15 currently used outlets labelled A-O. These can be better seen visually on [this worldstandards.eu page](https://www.worldstandards.eu/electricity/plugs-and-sockets/)

**Comment by tagliala** [comment] 2022-04-25 11:50
Thanks. I can see 15 types at the moment. Given that Type B is already here, 14 * 5 styles, this is a request for 70 icons

**Comment by sensibleworld** [comment] 2022-04-28 11:20
What are the most common outlet types? I imagine starting with a list of those typically included in "universal adaptor" kits could be a good starting point.

**Comment by sensibleworld** [comment] 2024-07-11 15:14
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/8691)

**Closed as not planned by sensibleworld** 2024-07-11 15:14 UTC
Labels: new icon, waiting for feedback, travel-hotel (category), household (category), energy (category), Duplicate
