### ISSUE TITLE
Icon request: plex

### ISSUE THREAD

**Issue by xerosys** [FortAwesome/Font-Awesome#15946] opened 2019-12-15 22:37 UTC
**What can it be used for?**
It can be used to represent the popular client–server media player system called Plex (https://www.plex.tv/).

**Example image (optional)**
![plex-png](https://user-images.githubusercontent.com/58919902/70870444-48efc180-1f48-11ea-9994-dff2df2d9484.png)

**Icon request checklist**
- [Y] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [Y] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [Y] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Y] I have included at least one example image if it could be helpful (optional)
- [Y] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-12-16 07:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7732, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-12-16 07:34 UTC
