### ISSUE TITLE
Icon request: first-aid-band, healing-band (alias), band-aid (alias), cross-band-aid

### ISSUE THREAD

**Issue by htbasaran** [FortAwesome/Font-Awesome#10210] opened 2016-11-12 18:28 UTC
cross-band-aid and single-band-aid needed, thanks
![cross-band-aid](https://cdn4.iconfinder.com/data/icons/medical-and-healthcare-2/64/x-07-128.png)

**Comment by tagliala** [comment] 2016-11-13 18:39
Duplicate of #4298, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Please also clarify the use cases in which you need them both (single and cross band-aid) 

Closing here

**Closed by tagliala** 2016-11-13 18:39 UTC
