### ISSUE TITLE
Icon request: icon-responsive

### ISSUE THREAD

**Issue by tareqbeituni** [FortAwesome/Font-Awesome#5666] opened 2015-02-13 09:39 UTC
Would be great to have a Responsive style icon with mobile, tablet and dekstop.  Please see example below for an idea: 
![responsive-design](https://cloud.githubusercontent.com/assets/6548724/6185249/1bc17f14-b364-11e4-96c5-5f841f40339b.png)

**Comment by tagliala** [comment] 2015-02-14 13:09
duplicate of #1446 , please +1 that request

closing here

PS: this will never fit the 14px icon size

**Closed by tagliala** 2015-02-14 13:09 UTC
