### ISSUE TITLE
Icon request: icon-kotlin

### ISSUE THREAD

**Issue by gabrielpal** [FortAwesome/Font-Awesome#17334] opened 2020-10-29 21:07 UTC
Hello! I would like to request the "K" logo for the [Kotlin](https://kotlinlang.org/) programming language.

**Comment by tagliala** [comment] 2020-10-29 21:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13450, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-10-29 21:39 UTC
