### ISSUE TITLE
Icon Request: fa-ideal

### ISSUE THREAD

**Issue by ScreamerHS** [FortAwesome/Font-Awesome#8576] opened 2016-02-15 10:32 UTC
![ideal-logo](https://cloud.githubusercontent.com/assets/7648323/13046056/f61d627a-d3d6-11e5-9b45-9d6f1e8a1bfe.jpg)
I would like to see a iDEAL logo in the catagorie "Payment Icons". Its the #1 Dutch payment system since 2005 and still will be used and accepted by every dutch webshop. Its a online payment through your own bank (every bank accept iDeal payments)

Since its introduction in 2005, more than 500 million online payments have been made using iDEAL.
More info: [https://www.ideal.nl/en/](url)

Thx
Marco Pavone

**Comment by jtrienekens** [comment] 2016-02-15 13:13
+1

**Comment by tagliala** [comment] 2016-02-15 13:22
Duplicate of #4330, please +1 that request

closing here

**Closed by tagliala** 2016-02-15 13:22 UTC
