### ISSUE TITLE
Icon Request: fa-tenge (fa-kzt)

### ISSUE THREAD

**Issue by Chaosito** [FortAwesome/Font-Awesome#11999] opened 2017-12-27 06:03 UTC
Font-Awesome 5 is released! What about tenge?
Four issues closed without explaning the reason (Two closed recursively)

![sa](https://camo.githubusercontent.com/ea0a78192cf3022b5fa6be9f1ca7603824762107/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313538323939362f313530303034362f34373163616537382d343836622d313165332d386232312d6436656439343163626138312e706e67)

Tenge is a currency of Kazakhstan: [Link](https://en.wikipedia.org/wiki/Kazakhstani_tenge)
[UnicodeTable](https://unicode-table.com/en/20B8/)

Previous issues:
[#2378](https://github.com/FortAwesome/Font-Awesome/issues/2378) Closed because exists 11618
[#4277](https://github.com/FortAwesome/Font-Awesome/issues/4277) Closed because exists 2378
[#9707](https://github.com/FortAwesome/Font-Awesome/issues/9707) Closed because exists 2378
[#11618](https://github.com/FortAwesome/Font-Awesome/issues/11618) Closed because exists 2378

**Comment by kpdushanmaduka** [comment] 2017-12-27 06:37
I like

**Comment by tagliala** [comment] 2017-12-27 09:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2378, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-27 09:27 UTC
