### ISSUE TITLE
Icon request: excavator - equipment

### ISSUE THREAD

**Issue by awillness** [FortAwesome/Font-Awesome#7160] opened 2015-08-06 20:55 UTC
Would I be able to have this icon created? I would appreciate it, thank you
![excavator](https://cloud.githubusercontent.com/assets/13684572/9123166/0ff084da-3c4b-11e5-8ef8-f8ae48db5c9c.jpg)

**Comment by TheChen5** [comment] 2015-08-06 21:52
Dupe of #5305
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-07 14:21
@TheChen5 thanks

**Closed by tagliala** 2015-08-07 14:21 UTC
