### ISSUE TITLE
icon request: icon-one

### ISSUE THREAD

**Issue by tharunkumarnataraj** [FortAwesome/Font-Awesome#14670] opened 2019-02-22 12:04 UTC
Please create numbers as icons

**Comment by tagliala** [comment] 2019-02-22 13:51
Hi!

Thanks for being part of the Font Awesome Community.

At the moment, I'm considering these requests as a duplicate of #5019, which is labeled as won't fix

Numbers and letters are out of the scope now, but they can come in the future

Hope it helps

Closing here

**Closed by tagliala** 2019-02-22 13:51 UTC
