### ISSUE TITLE
Icon request: fa-rand (e.g., Icon request: icon-Rand currency symbol)

### ISSUE THREAD

**Issue by stacybchapman** [FortAwesome/Font-Awesome#11764] opened 2017-11-16 14:11 UTC
We love font awesome and all the additions you make!  We have a multi-currency software that we are now extending to the South African Rand. We'd love to maintain a consistent interface using only font-awesome icons where possible.

**Comment by tagliala** [comment] 2017-11-16 14:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7045, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-16 14:25 UTC
