### ISSUE TITLE
Icon request: icon-virtual reality headset

### ISSUE THREAD

**Issue by thejameshay** [FortAwesome/Font-Awesome#11038] opened 2017-05-09 02:07 UTC
I plan on using it as a service icon for my website. The usual Font Awesome blue color would be preferable, Thanks in advance! 
![vrheadset](https://cloud.githubusercontent.com/assets/28551362/25832774/f75d169e-3429-11e7-9d41-2496baaae3f0.png)

**Comment by tagliala** [comment] 2017-05-09 08:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6590 or #9785, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-09 08:52 UTC
