### ISSUE TITLE
Icon Request: fa-icon-CONFERENCES

### ISSUE THREAD

**Issue by mecoder2** [FortAwesome/Font-Awesome#11032] opened 2017-05-08 04:43 UTC

**Comment by tagliala** [comment] 2017-05-08 08:51
Hi!

Thanks for being part of the Font Awesome Community.

Could you please post a single color, suitable for 16px icon size example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by melTr** [comment] 2017-05-25 04:20
Hi,
Need the same. 
[idea 1](https://www.google.ca/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwir6677lorUAhXi7IMKHbESBtEQjRwIBw&url=http%3A%2F%2Fkingglobalinc.com%2Fthe-firm%2Fevents%2F&psig=AFQjCNGqbKHRAv_IZT0EbLOKMxvElorisQ&ust=1495771975530274)
[idea 2](https://www.google.ca/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwiqvdibl4rUAhVp6IMKHa-iB7wQjRwIBw&url=https%3A%2F%2Fkinglimo.ca%2F&psig=AFQjCNHFA_9KP-8lsNxcAv6dborTBG-uNA&ust=1495771975696188)

Maybe similar to issue https://github.com/FortAwesome/Font-Awesome/issues/472

Thanks!

**Comment by tagliala** [comment] 2017-06-13 08:38
Cannot see your examples.

Closing here as a duplicate of #472, please add a 👍 reaction to that request

**Closed by tagliala** 2017-06-13 08:38 UTC
Labels: waiting for feedback
