### ISSUE TITLE
Icon Request: fa-discount

### ISSUE THREAD

**Issue by balangi** [FortAwesome/Font-Awesome#10238] opened 2016-11-17 13:51 UTC
hi,
there is not any icon for discount

![discount](https://cloud.githubusercontent.com/assets/14180653/20391809/34aaacf4-acea-11e6-9c6a-faf30df27747.jpg)

**Comment by caduvieira** [comment] 2017-01-13 12:00
Dupe of #2760
Please add your reaction there

**Comment by tagliala** [comment] 2017-01-13 13:06
@caduvieira thanks

**Closed by tagliala** 2017-01-13 13:06 UTC
