### ISSUE TITLE
Icon request: approximately-equal

### ISSUE THREAD

**Issue by svendavison** [FortAwesome/Font-Awesome#17061] opened 2020-08-21 02:12 UTC
**What can it be used for?**
Math and similar. It's not equal, greater, or less than X, its approximately X.

**Example image (optional)**
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR4yQTV6dVk3SXz3uuo3-CLI4mVsbklDu6UCA&usqp=CAU

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-03-08 03:38
Duplicate of #14414.

cc/ @tagliala

**Closed** 2022-03-08 11:54 UTC
Labels: new icon, mathematics (category)
