### ISSUE TITLE
Icon Request: fa-password

### ISSUE THREAD

**Issue by nokaoii** [FortAwesome/Font-Awesome#13741] opened 2018-08-09 16:21 UTC
Need an icon for Passwords.

Similar to this: [https://www.123rf.com/photo_42620684_stock-vector-password-field-line-art-icon-for-apps-and-websites.html](https://www.123rf.com/photo_42620684_stock-vector-password-field-line-art-icon-for-apps-and-websites.html)

Except remove the 4th asterisk should be a vertical text cursor icon.

An alt version could be dots instead of asterisks.

**Comment by tagliala** [comment] 2018-08-09 16:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11156, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-09 16:58 UTC
