### ISSUE TITLE
Icon Request: crown

### ISSUE THREAD

**Issue by aportx** [FortAwesome/Font-Awesome#10040] opened 2016-10-09 12:02 UTC
![crown-icons-vector](https://cloud.githubusercontent.com/assets/6645911/19220243/349dd888-8e42-11e6-9c20-5892a2b40a8a.jpg)

**Comment by tagliala** [comment] 2016-10-09 12:50
Duplicate of #486  or #1903 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-09 12:50 UTC
