### ISSUE TITLE
Icon request: fa-football-shoes

### ISSUE THREAD

**Issue by Max-Krieg666** [FortAwesome/Font-Awesome#6086] opened 2015-03-28 11:49 UTC
pls add icon 'shoe'

**Comment by tagliala** [comment] 2015-03-28 19:04
duplicate of #3704 or #3473 ?

**Comment by Max-Krieg666** [comment] 2015-03-30 12:01
oh. sorry. I think about football boots, no shoes.

**Comment by sensibleworld** [comment] 2024-07-10 21:44
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-10 21:44 UTC
Labels: new icon, web application icons (legacy category), Declined
