### ISSUE TITLE
better business bureau icon needed for font awesome

### ISSUE THREAD

**Issue by thyronne** [FortAwesome/Font-Awesome#12740] opened 2018-03-30 13:04 UTC
Help

**Comment by JCCasey** [comment] 2018-03-30 14:45
@thyronne sorry but a lot of people have been waiting years for a BBB icon to be added. It won't happen anytime soon.

**Comment by tagliala** [comment] 2018-04-06 09:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5797, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 09:52 UTC
