### ISSUE TITLE
Icon request: fa-times-normal

### ISSUE THREAD

**Issue by jhall3rd** [FortAwesome/Font-Awesome#7522] opened 2015-09-23 13:05 UTC
The current fa-times icon is super BOLD -- we need a regular one that's normal weight. Just like fa-angle-right, but for the "x" (close) symbol.

**Comment by tagliala** [comment] 2015-09-23 13:47
duplicate of #1540 , please +1 that request

please also consider the default html `&times;` entity

closing here

**Closed by tagliala** 2015-09-23 13:47 UTC
