### ISSUE TITLE
We need a website logo

### ISSUE THREAD

**Issue by NOKAgisser** [FortAwesome/Font-Awesome#13070] opened 2018-05-08 17:14 UTC
Website address：https://www.bilibili.com/
You can see this picture here：https://pbs.twimg.com/profile_images/813934430867759105/bGAicSr_.jpg

**Comment by tagliala** [comment] 2018-05-08 17:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9789, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-08 17:54 UTC
