### ISSUE TITLE
add fa-target icon

### ISSUE THREAD

**Issue by dit-j** [FortAwesome/Font-Awesome#8933] opened 2016-04-09 22:09 UTC
Please add GPS target icon like this: 
https://www.iconfinder.com/icons/351642/gps_location_navigate_navigation_pointer_position_target_icon

**Comment by tagliala** [comment] 2016-04-09 22:54
duplicate of #560 , please +1 that request

closing here

**Closed by tagliala** 2016-04-09 22:54 UTC
