### ISSUE TITLE
Icon request: Pickaxe

### ISSUE THREAD

**Issue by Relyk-x** [FortAwesome/Font-Awesome#18175] opened 2021-08-17 02:50 UTC
**What can it be used for?**
To display or convey the message of mining

**Example image (optional)**
[pickaxe-icon-pickax-symbol-flat-vector](https://cdn4.vectorstock.com/i/1000x1000/46/83/pickaxe-icon-pickax-symbol-flat-vector-28334683.jpg)

**Comment by tagliala** [comment] 2021-08-17 06:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1680, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-08-17 06:35 UTC
