### ISSUE TITLE
Unable to override the `role` attribute.

### ISSUE THREAD

**Issue by justin-schroeder** [FortAwesome/Font-Awesome#14791] opened 2019-03-22 18:38 UTC
### Describe the problem

When using the Font Awesome SVG with JS it is not possible to override the `role` attribute. Given the following:

```html
<i class="fa fa-arrow-right" role="presentation" data-custom-attr="true"></i>
```
Font Awesome converts this into:

```html
<svg class="svg-inline--fa fa-arrow-right fa-w-14" aria-hidden="true" data-prefix="fa" data-icon="arrow-right" role="img" data-custom-attr="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg="">
    <path fill="currentColor" d="M190.5 66.9l22.2-22.2c9.4-9.4 24.6-9.4 33.9 0L441 239c9.4 9.4 9.4 24.6 0 33.9L246.6 467.3c-9.4 9.4-24.6 9.4-33.9 0l-22.2-22.2c-9.5-9.5-9.3-25 .4-34.3L311.4 296H24c-13.3 0-24-10.7-24-24v-32c0-13.3 10.7-24 24-24h287.4L190.9 101.2c-9.8-9.3-10-24.8-.4-34.3z"></path>
</svg>
```

Specifically the issue is `role="img"` was not overridden even though `role="presentation"` was defined on the icon.

### What did you expect?

`role="img"` to be replaced with `role="presentation"`.

```html
<svg class="svg-inline--fa fa-arrow-right fa-w-14" aria-hidden="true" data-prefix="fa" data-icon="arrow-right" role="presentation" data-custom-attr="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg="">
    <path fill="currentColor" d="M190.5 66.9l22.2-22.2c9.4-9.4 24.6-9.4 33.9 0L441 239c9.4 9.4 9.4 24.6 0 33.9L246.6 467.3c-9.4 9.4-24.6 9.4-33.9 0l-22.2-22.2c-9.5-9.5-9.3-25 .4-34.3L311.4 296H24c-13.3 0-24-10.7-24-24v-32c0-13.3 10.7-24 24-24h287.4L190.9 101.2c-9.8-9.3-10-24.8-.4-34.3z"></path>
</svg>
```

Ideally, `<i>` tag attributes would take precedent over attributes being injected on the svg. Most of them do, but to my knowledge _at least_ the `role` attribute does not transfer.

### What version and implementation are you using?

Version: 5.3.1 
Browser and version: Chrome, safari, firefox 

- [X] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

https://codepen.io/justin-schroeder/pen/NJeMGV

Pretty simple test case, you'll see role="presentation" is not being overridden, and I've broken out all the existing attributes on the element for easy viewing.

**Comment by robmadole** [comment] 2019-03-22 18:55
Thanks @justin-schroeder ! We'll get it rolling.

**Comment by justin-schroeder** [comment] 2019-03-27 15:25
> We'll get it rolling.
😄 no pun intended i'm sure.

**Comment by robmadole** [comment] 2019-03-27 16:53
That was intended! But you caught it :clap:. My kids would say the appropriate response is 🙄

**Comment by arnorhs** [comment] 2021-01-29 12:48
Any word on this issue?

It seems to still be behaving the same way. Also affecting the react version.

**Comment by tagliala** [comment] 2021-01-29 13:54
This should have been fixed in version 5.8.2

I can see it is fixed by changing the Font Awesome version in the reproducible test case (https://codepen.io/justin-schroeder/pen/NJeMGV)

Could you please provide a reproducible test case?

(labeling and closing here, but feel free to comment, I will reopen if it is the case)

**Closed by tagliala** 2021-01-29 13:54 UTC
Labels: bug, svg

**Comment by joewhitsitt** [comment] 2021-01-29 14:28
From the example in https://github.com/FortAwesome/Font-Awesome/issues/14791#issuecomment-769818166
<img width="426" alt="Screen Shot 2021-01-29 at 8 26 23 AM" src="https://user-images.githubusercontent.com/4663676/106286825-b2459900-620b-11eb-8de0-a1e5b9a22fdd.png">

Isn't it supposed to be `presentation` instead of `img`?

**Comment by joewhitsitt** [comment] 2021-01-29 14:30
Sorry. I jumped to conclusions. The pen was set to 5.8.0. Changed it to 5.8.2 and I got this:

<img width="658" alt="Screen Shot 2021-01-29 at 8 29 27 AM" src="https://user-images.githubusercontent.com/4663676/106287247-30a23b00-620c-11eb-9757-7bfb696302e9.png">

Thank you for this!

**Comment by justin-schroeder** [comment] 2021-01-29 14:40
@joewhitsitt I just updated my codepen to 5.8.2 and saved it so the next person can see its been fixed too 👍

**Comment by tagliala** [comment] 2021-01-29 15:18
Good, thanks for the feedback
