### ISSUE TITLE
Icon request: airconditioner

### ISSUE THREAD

**Issue by ergec** [FortAwesome/Font-Awesome#13743] opened 2018-08-10 10:04 UTC
### What can it be used for?

Could be used on hotel/travel/dorm websites to indicate taht facility

### Example image (optional)

https://www.google.com/search?q=aircon+icon

**Comment by tagliala** [comment] 2018-08-10 10:30
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/snowflake?style=solid fit your needs?

Otherwise, this request is a duplicate of #3211, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-10 10:30 UTC
