### ISSUE TITLE
Icon Request: fa-clipboard-list

### ISSUE THREAD

**Issue by rclar** [FortAwesome/Font-Awesome#9795] opened 2016-08-23 18:33 UTC
Hi,

I would like to request a clipboard-list icon. Something to symbolize filling out or results from a survey or assessment.
![list-icon-88849](https://cloud.githubusercontent.com/assets/2432636/17904705/3407df96-6925-11e6-9a47-9ec195816df4.png)
![clipboard](https://cloud.githubusercontent.com/assets/2432636/17904740/64eac9ac-6925-11e6-8318-32f53152259e.PNG)

Thanks,
Ray

**Comment by tagliala** [comment] 2016-08-23 18:57
Duplicate of #773 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-23 18:57 UTC
