### ISSUE TITLE
Icon Request: fa-lift

### ISSUE THREAD

**Issue by nimmyy** [FortAwesome/Font-Awesome#11462] opened 2017-08-30 12:25 UTC
Hi,

I'd like to request a lift icon. I think it would be a good addition to the existing 'accessibility' group of icons.

Examples: https://cdn3.iconfinder.com/data/icons/glypho-signs/64/lift-up-down-512.png, https://d30y9cdsu7xlg0.cloudfront.net/png/149307-200.png, https://tombarden.files.wordpress.com/2011/02/lifts.jpg

I'd like to use this for some mockups I'm creating at work.

Thank you!

**Comment by tagliala** [comment] 2017-08-30 12:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6047 , please add a 👍  reaction to that request.

Also added `lift` to #6047's title to simplify search

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-30 12:52 UTC

**Comment by nimmyy** [comment] 2017-08-30 13:19
Sorry, I did do a search for lift which returned no results. Didn't think to search elevator!
