### ISSUE TITLE
Icon request: Caret NE/SE/SW/NW

### ISSUE THREAD

**Issue by TheColorRed** [FortAwesome/Font-Awesome#8038] opened 2015-11-29 21:14 UTC
It would be nice to have a few more carets that point in 4 more directions. Here is an example SE caret:

![caret-sw](https://cloud.githubusercontent.com/assets/1571806/11460105/de1a5d8a-96ab-11e5-9c1a-0842e278784c.png)

**Comment by sensibleworld** [comment] 2024-07-10 21:19
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/16965)

**Closed by sensibleworld** 2024-07-10 21:19 UTC
Labels: new icon, arrows (category), Duplicate
