### ISSUE TITLE
Icon Request: fa-yin-yang

### ISSUE THREAD

**Issue by Code-Name-Debian** [FortAwesome/Font-Awesome#7066] opened 2015-07-29 00:49 UTC
A Yin Yang is well overdue.  I am reissuing this request as the previous request was improperly labeled, but is requested often.

https://github.com/FortAwesome/Font-Awesome/issues/647

Please and thank you :+1:

**Comment by Code-Name-Debian** [comment] 2015-07-29 00:51
Yin Yang example

https://cloud.githubusercontent.com/assets/2425804/4080727/46c7414c-2ee1-11e4-89e2-cdd01fbe0b04.png

**Comment by tagliala** [comment] 2015-07-29 08:47
Thanks, but it's fine for us having `icon-*` instead of `fa-*`.

if you need this icon in a short while, please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

closing here as a duplicate of #647

**Closed by tagliala** 2015-07-29 08:47 UTC
