### ISSUE TITLE
Icon Request: fa-user-search

### ISSUE THREAD

**Issue by Linux4ever** [FortAwesome/Font-Awesome#6994] opened 2015-07-20 19:52 UTC
Creating an internal work web application. That would search employees within the company. This this icon as part of the title bar. Be able to stack ti with a box around it.

![image](https://cloud.githubusercontent.com/assets/13423721/8785634/e04c33d4-2ec4-11e5-9fbc-eb1b50b4b5b6.png)

https://cdn1.iconfinder.com/data/icons/user-pics/512/find_user-512.png

**Comment by tagliala** [comment] 2015-07-23 12:13
duplicate of #6760 , please +1 that request

refers to #1181 , you will find a solution there

closing here

**Closed by tagliala** 2015-07-23 12:13 UTC

**Comment by ashinzekene** [comment] 2018-07-15 13:19
+1
