### ISSUE TITLE
Icon Request: fa-cooker

### ISSUE THREAD

**Issue by RixBtrfly** [FortAwesome/Font-Awesome#11681] opened 2017-10-29 05:25 UTC
A generic looking slow cooker/pressure cooker icon. Would be great for use in recipes to indicate a slow cooker/pressure cooker application.
![pressure cooker](https://user-images.githubusercontent.com/32779287/32140918-47eb34f2-bc37-11e7-9714-4af76f50daa2.png)

**Comment by tagliala** [comment] 2017-10-29 09:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3000, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-29 09:45 UTC

**Comment by RixBtrfly** [comment] 2017-10-29 21:55
That other one is for just a pressure cooker, wouldn't work for slow cooker.

**Comment by timtjtim** [comment] 2017-10-29 23:39
+1 for slow cooker.
