### ISSUE TITLE
Icon Request: Floorplan

### ISSUE THREAD

**Issue by stevegoodger** [FortAwesome/Font-Awesome#20323] opened 2024-08-05 09:38 UTC
### Checklist

- [X] The title of this issue starts with "Icon Request: " and is followed by the new icon name *(ex. "Icon Request: Proton Torpedo")*
- [X] This icon does not represent a brand
- [X] This request is for a single icon or a matched pair *(ex. `lock` and `unlock`)*
- [X] I've already [searched through existing issues](https://github.com/FortAwesome/Font-Awesome/issues), and to the best of my knowledge this request isn't a duplicate
- [X] I understand [how new icon requests work](https://fontawesome.com/support#requesting-icons)

### Request type

✨ New icon

### Use case

The floorplan icon will be used on real estate agent websites and literature to showcase the specifics of a property.

### Visual example

<img width="178" alt="floorplan-example" src="https://github.com/user-attachments/assets/54de2256-3c43-4e9e-b1ad-f396d22d842a">

**Comment by tagliala** [comment] 2024-08-05 09:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12064

No need to upvote that request, it has been accepted.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-08-05 09:49 UTC
Labels: new icon
