### ISSUE TITLE
TikTok

### ISSUE THREAD

**Issue by borjagiron** [FortAwesome/Font-Awesome#16049] opened 2020-01-10 14:26 UTC
**What can it be used for?**
Social Network

**Example image (optional)**
https://www.flaticon.es/icono-gratis/tik-tok_1946538?term=tik%20tok&page=1&position=3

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-01-10 15:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14340, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-10 15:08 UTC
