### ISSUE TITLE
Icon Request: fa-jquery

### ISSUE THREAD

**Issue by DrCustUmz** [FortAwesome/Font-Awesome#9157] opened 2016-05-09 19:49 UTC
http://i.imgur.com/nmWjsXI.png

while we're adding JS, why not add jQuery too! =)

**Comment by tagliala** [comment] 2016-05-09 20:39
Duplicate of #1665 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-09 20:39 UTC
