### ISSUE TITLE
Icon Request: fa-javascript

### ISSUE THREAD

**Issue by DrCustUmz** [FortAwesome/Font-Awesome#9156] opened 2016-05-09 19:48 UTC
http://i.imgur.com/gEfWUZN.png

we have html and css icons, why not a js one =)

**Comment by tagliala** [comment] 2016-05-09 20:42
The problem is that javascript has not an official logo

Duplicate of #1711 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-09 20:42 UTC
