### ISSUE TITLE
Icon request: music-lyrics or music-list

### ISSUE THREAD

**Issue by cameronjonesweb** [FortAwesome/Font-Awesome#14228] opened 2018-11-06 13:16 UTC
### What can it be used for?

Used to notate songs with lyrics, or potentially as a list of musical items

### Example image

(from https://cdn.iconscout.com/icon/premium/png-256-thumb/lyrics-6-893020.png)
![image](https://user-images.githubusercontent.com/12673074/48066544-a24fd200-e219-11e8-8856-bc7d8023ae84.png)

(from https://developer.wordpress.org/resource/dashicons/#playlist-audio)
![image](https://user-images.githubusercontent.com/12673074/48885895-a0bb1680-ee75-11e8-85a3-e1357ba30110.png)

**Comment by sensibleworld** [comment] 2019-05-24 17:33
This is a duplicate of an existing issue: https://github.com/FortAwesome/Font-Awesome/issues/639

(Which I'm happy to say is currently `in-progress`)

**Closed by sensibleworld** 2019-05-24 17:33 UTC
