### ISSUE TITLE
Missing Icons in Microsoft Word (FA >= 5.7.0)

### ISSUE THREAD

**Issue by SAID-developer** [FortAwesome/Font-Awesome#14614] opened 2019-02-06 18:21 UTC
### Describe the problem

I updated my version of FontAwesome last week and now I am missing several icons in the symbol window in Microsoft Word. These icons were there previously and working without any issue. The screenshot shows what I am seeing and recently used icons from the sets that are no longer there. I downloaded the most recent version again and reinstalled and nothing changed. I've also rebooted the computer completely, opened and closed Word and nothing fixes it. This issue is across everyone in my office, not just my computer.

![image](https://user-images.githubusercontent.com/19313118/52363645-2c722700-2a11-11e9-8cde-774cb8637908.png)

### What did you expect?

I expected to see the full icon set as I always have.

### What version and implementation are you using?

Version: The issue started with 5.7.0 and is still there with 5.7.1
Microsoft Word Version 1901, Office 365 Business
- [ X] On the Desktop

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by SAID-developer** [comment] 2019-02-06 18:55
Just a note, I've also tried entering the character code and that doesn't work either. It brings up the wrong character, selecting one from the set that is showing rather the one from the full set that it should show.

**Comment by tagliala** [comment] 2019-02-06 19:43
Ok, I'm able to replicate this even on Office 2007.

Apparently, only microsoft products are affected by this issue

I'm using the .otf file 5.7.1

![image](https://user-images.githubusercontent.com/556268/52368581-12573980-2a4f-11e9-81e2-4073674f6016.png)

This is what happens when I try to write unicorn on Word:
![image](https://user-images.githubusercontent.com/556268/52368117-fa32ea80-2a4d-11e9-9bae-53c7a4deef47.png)

Wordpad have the same issue, too

Photoshop and other graphics suite looks fine

**Comment by SAID-developer** [comment] 2019-02-08 15:58
Hi, just checking if there are any thoughts about this issue? Thanks!

**Comment by tagliala** [comment] 2019-02-08 16:05
I've forgot to assign @robmadole

**Comment by robmadole** [comment] 2019-02-12 15:58
@SAID-developer I can confirm that there is an issue as well but as of now do not have a fix for it. We'll keep working on this one.

**Comment by SAID-developer** [comment] 2019-02-12 16:09
@robmadole Thank you! I appreciate that. I built out a series of ux documents using the icons and it would be ideal to have a fix as opposed to redoing them.

**Comment by tagliala** [comment] 2019-02-12 17:44
I've just checked 5.7.2 and the problem is still there

I think that a proper description of the issue is that ligatures stopped working on 5.7+ on certain applications

![image](https://user-images.githubusercontent.com/556268/52656164-0efffa00-2ef6-11e9-92e7-2d99f8ec901a.png)

**Comment by Gehanii** [comment] 2019-03-26 16:38
Tried using v5.8.1 and the issue persists. :(

**Comment by loesje001** [comment] 2019-06-05 13:00
I have the same problem since I updated to V5.8.1, also tried V5.8.2 als problems. 
Only when I installed the .ttf V5.6.3 en then the .otf V5.6.3 I got that one working, newer versions are all missing icons.
I hope this will get fixed soon!

**Comment by rdhar** [comment] 2019-06-22 06:38
Just to add on to this, I experience the same issue of missing/incorrect glyphs when using the Desktop OTFs. In my case, when I copy-pasted the unicode glyph for Diploma ([f5ea](https://fontawesome.com/icons/diploma?style=regular)), it would actually display Paste ([f0ea](https://fontawesome.com/icons/paste?style=regular)) instead. Attempting to paste a number of other glyphs have the same erroneous behaviour of switching to a different one.

Following on from @loesje001's message, I replaced the Desktop OTFs with Web TTFs instead and that appears to have resolved this issue immediately. _(At some point, I'll have to look up the difference between the Web and Desktop packages because, right now, it seems like the Web one has the relevant font files as well as all the SVGs... which makes the Desktop one seem somewhat redundant)._ 

**System**: Windows 10 Pro, v1903
**Office**: Microsoft Word 2019
**FA5**: Pro, v5.9.0

**Comment by tagliala** [comment] 2019-06-23 11:54
@rdhar could you please confirm that 5.6.3 works properly?

**Comment by qkflies** [comment] 2019-06-23 15:17
While I don't use the Pro version, I've also been running into this issue as described by rdhar with newer versions of FA. I've been sticking with v5.6.3, which does appear to work as intended.

System: Windows 10 Pro, v1803
Office: Office 365 / Microsoft Word v1905 (Build 11629.20246 Click to Run)

**Comment by avinoamsn** [comment] 2019-06-23 21:24
+1 for the Adobe Acrobat workaround

**Comment by rdhar** [comment] 2019-06-24 12:03
> @rdhar could you please confirm that 5.6.3 works properly?

@tagliala Here are my results with FA5 Pro v5.6.3.

| Format | Processor       | Status   |
| ------ | --------------- | -------- |
| OTF    | Word            | Fine     |
| OTF    | Word Export PDF | Fine     |
| TTF    | Word            | Fine     |
| TTF    | Word Export PDF | Missing* |

*Of my sample doc with only 4 icons, only Briefcase ([f0b1](https://fontawesome.com/icons/briefcase?style=light)) appeared as expected in both MS Word as well as its in-built PDF export. The following characters were missing:

- Graduation-cap ([f19d](https://fontawesome.com/icons/graduation-cap?style=solid))
- Hand-holding-heart ([f4be](https://fontawesome.com/icons/hand-holding-heart?style=solid))
- File with award ([f559](https://fontawesome.com/icons/award?style=light))

The export via Adobe Acrobat DC remains as a viable workaround throughout. It really seems like the issue is isolated to MS Office. I just tried out LibreOffice's in-built PDF export and that rendered the TTF icons with no problems whatsoever, neither in Writer nor in the PDF.

Hope this helps.

**Comment by Gehanii** [comment] 2019-07-26 19:06
I was able to use Desktop Pro 5.10.0-11 (or whatever that versioning is supposed to be) for 1 day in MS Word before glyphs started to no longer render. I was able to continue my work in InDesign ES4 for another 2 days beyond that before that *too* stopped rendering glyphs. The truly bizarre thing is that my XDF file is still able to access icons that are no longer rendering if I am inserting the character into a field via JavaScript. The characters were copied to the standard clipboard from MS Word & pasted into the XML edit-stream of the XDF file.

I made a composite image from this document with both 5.6.3 & 5.10.0. Maybe some of the differences in the character matching might help? The char code column is the character code value Word displays in its Insert Symbol dialog window when selecting the said character.

I also find it interesting that with >5.6.3, Word displays a secondary box next to the glyphs (as well as at the end of each table row & paragraph.) These are *NOT* the hidden text characters that Word uses; they still appear if hidden text is displayed.

![563 vs 5100](https://user-images.githubusercontent.com/40069515/61975142-f704ca00-afad-11e9-9ed3-45e259872e95.png)

Another observation is that the Windows 10 font view/installation window shows the "th" ligature in the font-view for 5.6.3 but does not for subsequent (and "broken") versions.

Thank you for your attention to this issue.

**Comment by samayo** [comment] 2019-07-28 17:12
Same issue. Last year it was working just fine, but I guess someone decided to break it :/

**Comment by rdhar** [comment] 2019-07-30 00:07
> Same issue. Last year it was working just fine, but I guess someone decided to break it :/

I think it's a bit unfair to describe it as _someone deciding to break it_. Not least because it makes absolutely no sense for the maintainers to intentionally add regression issues to their product. Additionally, as mentioned just a couple of posts above, viable workarounds currently exist in the form of:

* Using desktop fonts (i.e., .otf) FA <=v5.6.3
* Using web fonts (i.e., ttf) FA latest (← obviously my recommendation to get the most up-to-date icon pack)

**Comment by ischang** [comment] 2019-09-16 21:46
Unfortunately, these workarounds aren't working for me -- using Microsoft Word 2019 (version 16.29) on MacOS Sierra. I've tried Desktop FA <=v.5.6.3 (tried using 5.6.3 and using 5.6.0, etc). This is for both FA Brands and FA Regular/Solid. I tried the recent Web FA (latest and older) as well.

For example, from brands, I'm missing some of the Github icons (f09b, f092, etc) and all the LinkedIn ones. From regular FA, I've noticed I'm missing the globe icon, along with envelope.

**Comment by Gehanii** [comment] 2019-09-25 21:13
Any further word on this? 5.11 is broken immediately on installation.

**Comment by pixeokoen** [comment] 2019-10-15 10:15
I used FontAwesome in Microsoft Word, in Photoshop and in websites. But the Word issues made me switch to a different icon font: https://materialdesignicons.com/

If it were up to me, I'd use FontAwesome, but I have a very strong feeling they just don't care about this ...

**Comment by robmadole** [comment] 2019-10-15 14:48
Just a quick update on this issue. We've worked on this issue a couple of times an have not been able to identify the cause. Since it continues to be a problem for folks we'll try again to take a look. However, since Word appears to be the issue (it works fine in other programs) we consider this to be an issue with Word itself. We'll try to fix it if we can but has anyone filed a bug with Microsoft? Or has anyone ran across a thread that might be related to this?

**Comment by pixeokoen** [comment] 2019-10-15 14:54
> Just a quick update on this issue. We've worked on this issue a couple of times an have not been able to identify the cause. Since it continues to be a problem for folks we'll try again to take a look. However, since Word appears to be the issue (it works fine in other programs) we consider this to be an issue with Word itself. We'll try to fix it if we can but has anyone filed a bug with Microsoft? Or has anyone ran across a thread that might be related to this?

Thank you for the response!
I have not filed the issue with Microsoft. The main reason for this is that earlier versions of FontAwesome, and other icon fonts (like the one I suggested) do work fine. I'm not sure I want to be in the middle of a ping-pong game between FontAwesome and Microsoft.
I'm a FontAwesome paying customer by the way. ;-)

**Comment by robmadole** [comment] 2019-10-15 15:02
I just raised this up with Dave and Travis (CEO and CTO) to see if this needs to be prioritized. @pixeokoen I understand the ping-pong match and you have a better chance of us fixing it than of Microsoft paying attention to it. This is just a difficult one to solve so any feedback we could get from them (a clue, a hint, a trail to follow) might be the thing that breaks the case.

**Comment by tagliala** [comment] 2019-10-15 15:02
@robmadole since this has been introduced from 5.6.3 to 5.7.0, and we fixed something about the font name (it was wrong before), we can try the following to check if it works with:

- (if we have updated dependencies) rebuild 5.6.3
- rebuild 5.11's`.otf` without #13900
- build a subset of 5.11 with just a few icons
- `git bisect` on the build system

This link may be useful:
- https://github.com/FortAwesome/Font-Awesome/issues?utf8=✓&q=is%3Aclosed+label%3Abug+milestone%3A5.7.0

Anyway, this is a time consuming task. At the moment I cannot help on this :\

**Comment by robmadole** [comment] 2019-11-08 21:31
OK, folks. We've got this on the work list for 5.12.0. I'm going to give it another go. No guarantees that I can fix it but we're going to try.

**Comment by pixeokoen** [comment] 2019-11-11 17:50
> OK, folks. We've got this on the work list for 5.12.0. I'm going to give it another go. No guarantees that I can fix it but we're going to try.

Any ETA on 5.12.0 or is that wishful thinking? :-)

**Comment by robmadole** [comment] 2019-11-11 20:30
5.12.0 should go out within the next few weeks. Again, no guarantee that we will be able to fix this issue with that release but it's our goal.

**Comment by robmadole** [comment] 2019-11-26 19:03
Alrighty. I think I _may_ have fixed this sucker. Anyone who has the time can you give this a try and let me know?

[Font Awesome 5.12.0-1 OTF.zip](https://github.com/FortAwesome/Font-Awesome/files/3893571/Font.Awesome.5.12.0-1.OTF.zip)

**Comment by qkflies** [comment] 2019-11-26 19:10
The issue is resolved in my documents, and scrolling through the `Insert Symbols` dialog, there are no longer any missing icons.

Thanks for your work on the fix, @robmadole!

**Comment by pixeokoen** [comment] 2019-11-26 19:15
There is improvement, and I would say it's fixed although 1 thing seems off ...

- Brands load fine in modal and export fine to Pdf
- Solid load fine in modal and export fine to Pdf
- Regular don't all load so it seems, but there are also no gaps like before so I don't know what to think of it

I attached some screenshots.

![fa-screen-regular](https://user-images.githubusercontent.com/4553188/69664838-748a3500-1089-11ea-87fa-a08c6cde0727.JPG)
![fa-screen-brands](https://user-images.githubusercontent.com/4553188/69664839-748a3500-1089-11ea-8153-8ca14ff032d1.JPG)
![fa-screen-solid](https://user-images.githubusercontent.com/4553188/69664841-7522cb80-1089-11ea-97da-be1a792e41d6.JPG)

**Comment by pixeokoen** [comment] 2019-11-26 19:19
I'm will test this on some other computers tomorrow, when I'm at the office. 😉

**Comment by robmadole** [comment] 2019-11-26 19:22
@pixeokoen sweet! thanks for testing and the screenshots! So this is the Free version of Font Awesome so the Regular style is very limited (basically just the icons that make it backward-compatible with version 4). So I think that's correct.

@qkflies thank you for testing!

With two successful results I'm going to tentatively call this one fixed. It was a one line change in the code that took a LONG time to figure out!

**Comment by pixeokoen** [comment] 2019-11-26 19:28
> @pixeokoen sweet! thanks for testing and the screenshots! So this is the Free version of Font Awesome so the Regular style is very limited (basically just the icons that make it backward-compatible with version 4). So I think that's correct.

Oh, okay, cool. I'm a pro user so wasn't aware. 😎
 
> With two successful results I'm going to tentatively call this one fixed. It was a one line change in the code that took a LONG time to figure out!

Aaah, 1-line-bugs. Them funny ones ...
I guess it's fixed indeed! Now I can finally use 1 icon set again for docs and designs!
Thank you for all the efforts!

**Comment by robmadole** [comment] 2019-11-26 19:32
![giphy](https://user-images.githubusercontent.com/132895/69665984-180b2380-1051-11ea-92b5-d7040fb3de31.gif)

Excellent. This will be going out in 5.12.0 then!

**Comment by rdhar** [comment] 2019-11-26 19:38
> It was a one line change in the code that took a LONG time to figure out!

Go on then, spill!

**Comment by emottet** [comment] 2019-11-26 19:40
Hi,
I've done some tests too.
For me, it works fine on Word through the Insert Symbols dialog.
![word](https://user-images.githubusercontent.com/2139348/69666613-d304e280-108c-11ea-8fcc-34033bd9019e.PNG)

But it doesn't work on Power Point throught the Insert Symbols dialog.
![power-point](https://user-images.githubusercontent.com/2139348/69666611-d304e280-108c-11ea-8f17-8a17b4883e9d.PNG)

Could it just be a cache issue ?
For those that have been testing successfully, have you done your tests in Power Point too?

**Comment by robmadole** [comment] 2019-11-26 19:42
@rdhar It involved adding more sets to the OS/2 codepages which allow some of the applications on Windows (including Character Map, Word, Wordpad) to see the OpenType font as supporting Unicode.

```
font.os2_codepages = (-1, -1)
```

☝️ that was it.

**Comment by robmadole** [comment] 2019-11-26 19:42
@emottet I haven't tried PowerPoint yet but I will add it to the list. Thank you for testing!

**Comment by qkflies** [comment] 2019-11-26 19:50
@emottet I'm able to replicate what you're seeing, unfortunately.

![image](https://user-images.githubusercontent.com/8078226/69667386-88b33f80-1053-11ea-8927-a5972aad1e3b.png)
![image](https://user-images.githubusercontent.com/8078226/69667395-8f41b700-1053-11ea-8a6d-822a8fe602fd.png)
![image](https://user-images.githubusercontent.com/8078226/69667409-97015b80-1053-11ea-8fe4-6f64733dc2f1.png)

**Comment by pixeokoen** [comment] 2019-11-27 10:52
> @emottet I haven't tried PowerPoint yet but I will add it to the list. Thank you for testing!

So Word is fixed. Even if Powerpoint is not working yet, will the fix be released to the Pro version anytime soon?

**Comment by robmadole** [comment] 2019-12-02 17:14
Yes, this will be going out in 5.12.0. We don't have an exact schedule for release but it should be in the next 2 weeks.

**Comment by robmadole** [comment] 2019-12-11 18:53
Ok everyone. We have released 5.12.0 and I think I was able to fix the PowerPoint issue as well. Please try the final release out and let me know your results!

**Comment by pixeokoen** [comment] 2019-12-11 20:12
> Ok everyone. We have released 5.12.0 and I think I was able to fix the PowerPoint issue as well. Please try the final release out and let me know your results!

I've checked FA Pro in Word. Looks great. If anyone can verify Powerpoint, we're all good!

**Comment by Gehanii** [comment] 2019-12-11 22:25
Of course, it'd be me with another problem. :(

Starting at char point F900, Word's insert symbol dialog gives a Unicode
name of "CJK Compatability Ideograph-####" where the #### matches the char
point number. The glyphs render fine in the dialog window, but do not
render when inserted in the actual document. I've rebooted once already;
I'm going to nuke the fonts outright, reboot, reinstall & see where that
gets me. My sneaking suspicion, however, is that it'll still be an issue.

I really hate to be the bearer of bad news after all the work that's gone
into trying to fix this issue. :( :( :(

.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.
 Geoffrey B. Webb, Limbo Games Press - "A double negative is a no-no."
.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.

**Comment by Gehanii** [comment] 2019-12-11 22:34
Or now I *can't* uninstall the fonts. :( Even with elevated rights. :(

.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.
 Geoffrey B. Webb, Limbo Games Press - "A double negative is a no-no."
.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.

**Comment by Gehanii** [comment] 2019-12-11 22:37
The glyphs that won't appear in the Word document itself are being set to
the Malgun Gothic font-face & crazily is not able to be changed in the UI.
:(

.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.
 Geoffrey B. Webb, Limbo Games Press - "A double negative is a no-no."
.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.

**Comment by robmadole** [comment] 2019-12-11 22:59
Ok @Gehanii. Let's get a few more people trying. But that sounds like some deeper Word-related issue to me.

**Comment by Gehanii** [comment] 2019-12-11 23:02
I agree. I just tried using those same glyphs in Excel: the same dialog
content is used in both applications. Weirdly, the cell as rendered shows
the FA glyphs just fine, but the cell content review shows the CJK glyphs.
"Thank you, Word..."

I'll try some other applications & see where that gets me.


.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.
 Geoffrey B. Webb, Limbo Games Press - "A double negative is a no-no."
.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.

**Comment by emottet** [comment] 2019-12-12 07:24
Hello @robmadole 
You made my day! It's working just fine on Power Point! Thank you so much for your time!

**Comment by zetoken** [comment] 2019-12-12 08:07
I just tried Powerpoint and Word (Office 365) with the new 5.12 font: it's now working as intended. Thank you.

**Comment by Bistaff** [comment] 2019-12-12 16:44
Hi all,

I have downloaded today font-awesome.pro 5.12 otf for Microsoft Word, but I can see only the icons in the images.

![pro-light](https://user-images.githubusercontent.com/8402993/70730977-3b4af980-1d06-11ea-9ebe-935fcb2b94c2.jpg)
![pro-regular](https://user-images.githubusercontent.com/8402993/70730978-3b4af980-1d06-11ea-8fe5-2ae940739020.jpg)
![pro-solid](https://user-images.githubusercontent.com/8402993/70730979-3b4af980-1d06-11ea-842a-3113d81facda.jpg)

**Comment by robmadole** [comment] 2019-12-12 16:58
@Bistaff how about using Character Map. Does that work?

**Comment by Bistaff** [comment] 2019-12-13 09:07
With Character Map I have the same results of images I've attached in previous comment. I've noticed that until char code F8EE icons are visible, but after F8EE I have chars of this font "Malgun Gothic"

**Comment by Bistaff** [comment] 2019-12-13 10:00
I've installed fonts again and again, restarted word, installed office again and icons now works!

**Comment by Gehanii** [comment] 2019-12-13 17:10
Here's what I'm dealing with in Word 2016/Windows 10. I'm still unable to
uninstall the fonts either. :(

[image: image.png]


.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.
 Geoffrey B. Webb, Limbo Games Press - "A double negative is a no-no."
.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.

**Comment by Gehanii** [comment] 2019-12-13 17:25
Okay, got the fonts to uninstall (PEBKAC error :( ) but after
uninstall/reboot/install, still having the issue

The regular font-faces are all displaying symbol-substitutions in the
installation window:
[image: image.png]

Where as the duotone & brands do not:
[image: image.png]

Not sure if that helps or not.

Thank you!

.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.
 Geoffrey B. Webb, Limbo Games Press - "A double negative is a no-no."
.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.

**Comment by robmadole** [comment] 2019-12-13 17:34
Hey @Gehanii I don't think the screenshots are coming through in your comment.

**Comment by Gehanii** [comment] 2019-12-13 19:12
Of course not, because why would they. :(

I've attached them as PNGs. Hope they help.

.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.
 Geoffrey B. Webb, Limbo Games Press - "A double negative is a no-no."
.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.

**Comment by tagliala** [comment] 2019-12-13 20:46
@Gehanii sorry, unfortunately email attachments don't work.

Please follow this url: https://github.com/FortAwesome/Font-Awesome/issues/14614 and post screenshots there

**Comment by Gehanii** [comment] 2019-12-13 20:52
> @Gehanii sorry, unfortunately email attachments don't work.
> 
> Please follow this url: #14614 and post screenshots there

Gotcha. 
![fa_brands](https://user-images.githubusercontent.com/40069515/70831440-2fb80b00-1db8-11ea-8f6d-53b6dfdcaac3.png)
![fa_solid](https://user-images.githubusercontent.com/40069515/70831441-2fb80b00-1db8-11ea-8b0d-f9084d99616b.png)

**Comment by robmadole** [comment] 2019-12-13 21:14
@Gehanii those are probably just the ligatures doing their job. You can type "dog" and it will be replaced with the dog symbol. Is that what are referring to?

**Comment by Gehanii** [comment] 2019-12-16 16:45
I realize it was the ligatures functioning. Just not expecting them to be
functioning the font preview per se. I can't recall if 5.6.1 did that or
not, just that there was difference between the way the version that did
function and the version that didn't function, displayed in the font
installation preview. (I.e., one would display the ligatured glyphs, the
other would not.)

To my great annoyance, I have cleverly forgotten to check if this problem
persists on my home system. Will endeavor to remember to test tonight or
tomorrow night.

.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.
 Geoffrey B. Webb, Limbo Games Press - "A double negative is a no-no."
.oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo. .oOo.

**Comment by tagliala** [comment] 2020-03-07 12:05
I'm going to close this since we have fixed it in 5.12.0.

I'm still having issues with ligatures and icons with a dash (eg: `user-md`) on old Microsoft applications, but please open a new thread with a detailed description of the issue if you still have problems

**Closed by tagliala** 2020-03-07 12:05 UTC
Labels: bug, otf

**Comment by Joshanity17** [comment] 2020-07-19 16:20
I am using `5.14.0` and the issue still persists. Wow. This bug is living like forever.

**Comment by Joshanity17** [comment] 2020-07-19 16:23
I am using `5.14.0` and I still encounter this issue. I encounter this whenever I try to export the document into PDF like [here](https://superuser.com/questions/1472511/font-awesome-not-embedded-to-pdf-when-exporting-from-microsoft-word).

**Comment by tagliala** [comment] 2020-07-19 16:35
@Joshanity17 please use the `.otf` file on desktop. `ttf` is optimized for the web

Please also open a new issue, providing all the information we could need to debug: OS, OS version, Word version, PDF export method (integrated? Third-party?)

We have a [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

I cannot replicate with the integrated pdf export functionality available on Word 2019 on Windows 10.

This is a screenshot from a PDF created via the cheatsheet

![image](https://user-images.githubusercontent.com/556268/87879997-7e80ef80-c9ee-11ea-9806-ea1159dc071f.png)
