### ISSUE TITLE
new icon ...

### ISSUE THREAD

**Issue by Alidad3250** [FortAwesome/Font-Awesome#13472] opened 2018-07-02 16:55 UTC
Hi, you have great icon's, and i"m using your service for my website relate to the shopping site. however, one of the icons that I need relate to women items which are "perfume" I was wondering if possible to make one so I can add that on my categories. 
Is going to be very ugly for our site without that icon because I added other icons for other categories. 
thank so for your help.

Alidad

**Comment by tagliala** [comment] 2018-07-02 20:02
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/spray-can?style=solid fit your use case?

**Comment by aethior** [comment] 2022-03-14 12:50
Duplicate of #5717.

Regards.

cc/ @tagliala

**Closed** 2022-03-14 12:52 UTC
Labels: waiting for feedback
