### ISSUE TITLE
Icon request: fab fa-spigot

### ISSUE THREAD

**Issue by LogicFlame-Dev** [FortAwesome/Font-Awesome#19585] opened 2023-02-27 03:05 UTC
SpigotMC Logo, which is attached

This is for Minecraft plugin marketplace, where developers can make their plugins so it would be good to make a icon for footers and other parts of a website

![spigotmc](https://user-images.githubusercontent.com/47160230/221463257-143fc9a3-f430-4dc8-b05c-f112754ca833.png)

**Comment by tagliala** [comment] 2023-02-27 09:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8270, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-02-27 09:30 UTC
