### ISSUE TITLE
Icon Request: fa-www

### ISSUE THREAD

**Issue by lebanggit** [FortAwesome/Font-Awesome#11026] opened 2017-05-06 15:41 UTC
![](http://icons.iconarchive.com/icons/icons8/ios7/512/Network-Domain-icon.png)

![](https://image.freepik.com/free-icon/domain-registration_318-64461.jpg)

**Comment by tagliala** [comment] 2017-05-06 16:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1192 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-06 16:51 UTC
