### ISSUE TITLE
Icon Request: fa-fan / fa-propellor

### ISSUE THREAD

**Issue by haydenkibble** [FortAwesome/Font-Awesome#7794] opened 2015-11-01 20:43 UTC
This would be great for fan speed indicators in apps.
I currently want it for a home automation app that turns on an extractor fan

p.s. I'm a huge *fan* of Font Awesome, keep up the good work! Ho ho ho

**Comment by tagliala** [comment] 2015-11-01 22:16
Duplicate of #3684?

**Closed** 2015-11-02 14:52 UTC
Labels: waiting for feedback

**Comment by haydenkibble** [comment] 2015-11-02 14:54
Yes was a duplicate. Thanks
