### ISSUE TITLE
Icon size 1px taller from 4.4.0 to 4.5.0

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [FortAwesome/Font-Awesome#8101] opened 2015-12-07 15:33 UTC
The `::before` pseudo-class seems to have increased by 1px in height.  Opening both plnkrs and cycling quickly through the tabs, you'll see the icons jump slightly.  Is this intended behavior?

[4.4.0 plunkr](http://plnkr.co/edit/jngaaXPaZRvpof0pCN1o?p=preview)
[4.5.0 plunkr](http://plnkr.co/edit/acFUXPtQlvWrqaqMxeMf?p=preview)

![4 4 0 screenshot](https://cloud.githubusercontent.com/assets/4612419/11630717/a6bf2c9a-9ccc-11e5-96ca-fb19a93f5df2.png)
![4 5 0 screenshot](https://cloud.githubusercontent.com/assets/4612419/11630718/a6bf8618-9ccc-11e5-86ec-98d424c0674b.png)

**Comment by tagliala** [comment] 2015-12-07 16:36
I think this is not intended

@davegandy ?

**Comment by Blackbaud-BobbyEarl** [comment] 2015-12-07 16:46
I should add, originally found on Chrome 47.0.2526.73 (64-bit) for OSX (El Capitan).

**Comment by Blackbaud-BobbyEarl** [comment] 2015-12-18 15:59
Any chance of an update on this?  I'd prefer the bug be closed if there's no intention in resolving.  Many thanks!

**Comment by timkendrick** [comment] 2016-01-06 15:17
I've come across this problem as well (Chrome 47.0.2526.106, 64-bit on OS X Yosemite). After upgrading to 4.5.0, I'm getting alignment issues for Font Awesome icons positioned within circles.

I've temporarily downgraded to 4.4.0 – is there any chance of this being fixed? I'd like to use 4.5.0 so that I can use the updated Google logo, but it's going to be a large amount of work to reposition everything that uses a Font Awesome icon, especially if this is fixed at some point in the future. Thanks!

**Comment by tagliala** [comment] 2016-04-05 23:06
@davegandy could you please take a look here?

**Comment by davegandy** [comment] 2016-04-05 23:41
Taking a look now. Hoping to have ready for 4.6.0.

**Comment by davegandy** [comment] 2016-04-07 22:51
Having issues replicating on El Capitan, Chrome 49.0.2623.110. Can anyone else validate? I'll also poke into a virtual machine and see what I can get.

**Comment by tagliala** [comment] 2016-04-07 22:55
I'm still able to reproduce it on W10/Chrome  49.0.2623.112.

Will check tomorrow on OSX (non-retina)

**Comment by davegandy** [comment] 2016-04-07 22:56
I'll try Chrome 46 on W10 next. Could not replicate on IE13 (wonder if it's becuase of retina).

**Comment by davegandy** [comment] 2016-04-07 23:02
Very strange. Chrome 46 on W10 via Browserstack:
<img width="403" alt="screenshot 2016-04-07 18 01 11" src="https://cloud.githubusercontent.com/assets/1076721/14369450/c9f94384-fcea-11e5-81b3-fe0c43b84c1a.png">

This is going to be tough if I can't replicate it.

**Comment by tagliala** [comment] 2016-04-07 23:06
Cannot replicate anymore on W10 Edge, but there is something wrong

![senza titolo-2](https://cloud.githubusercontent.com/assets/556268/14369520/0f85be24-fd26-11e5-9e1e-bdfb25ab0366.gif)

**Comment by tagliala** [comment] 2016-04-07 23:09
![image](https://cloud.githubusercontent.com/assets/556268/14369570/7f0c1e14-fd26-11e5-9601-a0086c740131.png)

**Comment by tagliala** [comment] 2016-04-07 23:15
Can replicate on Chrome 49 .0.2623.112 / OSX 10.11.4 non-retina MacBook Air mid '13

![screen shot 2016-04-08 at 01 14 21](https://cloud.githubusercontent.com/assets/556268/14369676/4bc68476-fd27-11e5-8b9c-52f505300f6f.png)

**Comment by davegandy** [comment] 2016-04-07 23:34
Goodness. Took my Retina Macbook to native full resolution (no scaling). Can't replicate in the exact same version of Chrome. Goodness. Might need until the weekend so I can get ahold of a non-retina machine.

**Comment by Blackbaud-BobbyEarl** [comment] 2016-04-08 00:36
Devices / Browsers I **AM** able to replicate on:

| Hardware                                | OS                        | Browser                          | Resolution |
|-----------------------------------------|---------------------------|----------------------------------|------------|
| Macbook Pro (Retina, 15-inch, Mid 2014) | OS X El Capitan (10.11.4) | Chrome 49.0.2623.112 (64-bit)    | 1920x1200  |
| Macbook Pro (Retina, 15-inch, Mid 2014) | OS X El Capitan (10.11.4) | Chrome 49.0.2623.112 (64-bit)    | 1440x900   |
| Macbook Pro (Retina, 15-inch, Mid 2014) | OS X El Capitan (10.11.4) | Firefox 45.0.1                   | 1920x1200  |
| Macbook Pro (Retina, 15-inch, Mid 2014) | OS X El Capitan (10.11.4) | Firefox 45.0.1                   | 1440x900   |
| Macbook Pro (Retina, 15-inch, Mid 2014) | OS X El Capitan (10.11.4) | Safari 9.1 (11601.5.17.1)        | 1920x1200  |
| Macbook Pro (Retina, 15-inch, Mid 2014) | OS X El Capitan (10.11.4) | Safari 9.1 (11601.5.17.1)        | 1440x900   |
| PC 2.93 GHz Intel i3                    | Windows 10 Pro            | Internet Explorer 11.162.10586.0 | 1680x1050  |
| PC 2.93 GHz Intel i3                    | Windows 10 Pro            | Chrome 49.0.2623.112 m           | 1680x1050  |
| PC 2.93 GHz Intel i3                    | Windows 10 Pro            | Microsoft Edge 25.10586.0.0      | 1680x1050  |

Devices / Browser I **AM NOT** able to replicate on:

| Hardware             | OS             | Browser        | Resolution |
|----------------------|----------------|----------------|------------|
| PC 2.93 GHz Intel i3 | Windows 10 Pro | Firefox 45.0.1 | 1680x1050  |

As @tagliala mentioned, on browsers where I'm having a hard-time reading the `:before` pseudo-class, I'm unable to confirm the icons are different sizes.  IE, Edge, and Safari being examples.  In all of those cases though, I'm seeing a "jumping" when cycling through the two Plunkers.

**Comment by davegandy** [comment] 2016-04-08 13:13
@Blackbaud-BobbyEarl Okay, my reading comprehension is terrible. I wasn't looking at the before element. Easily replicated.

Digging in further. This is definitely getting fixed before we release.

**Comment by tagliala** [comment] 2016-04-08 13:39
fff I didn't notice the missing `::before`

**Comment by davegandy** [comment] 2016-04-09 01:32
Okay, what's checked into 4.6.0 should be good to go. If you run the project locally, you can see the problem replicated for 4.5.0 and 4.4.0 and 4.6.0 (current) working at:
- http://localhost:7998/Font-Awesome/test/height/4.4.0/
- http://localhost:7998/Font-Awesome/test/height/4.5.0/
- http://localhost:7998/Font-Awesome/test/height/current/

Closing for now, but please let me know if there are any issues!

**Closed by davegandy** 2016-04-09 01:32 UTC
Labels: bug, waiting for feedback
