### ISSUE TITLE
Icon Request: fa-beme

### ISSUE THREAD

**Issue by emrkarata** [FortAwesome/Font-Awesome#9390] opened 2016-06-11 19:45 UTC
Beme is a Social Media that I use. I'm using the logo for my Personal Website; http://www.emrekaratas.org 

Beme: https://beme.com

![icon](https://cloud.githubusercontent.com/assets/19878141/15987131/c2416106-301d-11e6-95dc-df5c235eda14.png)

**Comment by aethior** [comment] 2016-06-11 23:17
Hi @emrkarata,

This request is duplicate of #7268. Please :+1: that.

**Closed** 2016-06-12 08:55 UTC
