### ISSUE TITLE
Icon request: structure/tree

### ISSUE THREAD

**Issue by hauva007** [FortAwesome/Font-Awesome#11647] opened 2017-10-19 09:23 UTC
We need icon for indicating structure, like bill of materials, folder-structure and tree (parent, children). Now we use sitemap icon for demonstrating structure.

[Tree](https://cdn0.iconfinder.com/data/icons/folder-line/512/folder_tree-512.png)

**Comment by tagliala** [comment] 2017-10-19 10:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2752 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-19 10:20 UTC
