### ISSUE TITLE
Icon Request: fa-sort-date-asc (and desc)

### ISSUE THREAD

**Issue by themitchweiss** [FortAwesome/Font-Awesome#9788] opened 2016-08-22 23:54 UTC
This would be the same arrow as the other sorts next to the calendar icon. Same use cases as other sorts, but with datatype of date. (similarly you could do sort-time-asc with a clock)

**Comment by tagliala** [comment] 2016-08-23 08:50
Duplicate of #4085, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-23 08:50 UTC
