### ISSUE TITLE
icon request : fa-caravan

### ISSUE THREAD

**Issue by stefankellens** [FortAwesome/Font-Awesome#8454] opened 2016-01-29 15:24 UTC
Hello

I would like to request a new icon for a caravan

Example : https://cdn3.iconfinder.com/data/icons/beach-and-vacation-icons/512/Caravan-512.png

Thanks

**Comment by tagliala** [comment] 2016-01-29 16:48
duplicate of #5429, please +1 that request

please also search before opening new requests

closing here

**Closed by tagliala** 2016-01-29 16:48 UTC
