### ISSUE TITLE
Icon request: Second Life (Game Category)

### ISSUE THREAD

**Issue by webtom** [FortAwesome/Font-Awesome#13823] opened 2018-08-27 10:39 UTC
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by webtom** [comment] 2018-08-29 21:02
Hi Jeremy.
Thanks for message.There are
https://marketplace.secondlife.com/ (left to top)
this images hand plus eye.
I pray for your success!! (○´∀｀)ﾉﾞ★



     ----- Original Message -----

**Comment by tagliala** [comment] 2018-08-29 21:08
Hi!

Thanks for being part of the Font Awesome Community.

If I'm getting this right, this is a duplicate of #8048, please +1 that request

Otherwise, please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2018-08-29 21:08 UTC
Labels: waiting for feedback

**Comment by webtom** [comment] 2018-08-30 01:55
i checked #8048. but i can't used awesome fonts...

**Comment by Extarys** [comment] 2018-08-30 03:44
@webtom I'm not sure I understand.

If you'd like to vote for this icon so it may be added in the future, just click the +1 emote on the issue tagliala gave you.

Thanks @tagliala I missed it ;)

**Comment by webtom** [comment] 2018-08-30 07:12
hi Jeremy.
Thank you so much! I hope the type can be typed, with the second life icon.I am sorry for my beginner's too much trouble. And thank you. .+:｡(´ω｀*)ﾟ.+:｡


     ----- Original Message -----
