### ISSUE TITLE
Better mechanism on fontawesome.io/icons for quickly copying icon name to clipboard

### ISSUE THREAD

**Issue by scottyantipa** [FortAwesome/Font-Awesome#10138] opened 2016-10-28 18:44 UTC
The primary reason I go to fontawesome.io is to find a great icon and then copy the text to clipboard, like `fa-bug` or just `bug`.   However due to how the html is structured, this isn't a quick task.  It would be great if the `bug` was a regular link that was easy to both click and/or copy the text from.

![fa_github_issue](https://cloud.githubusercontent.com/assets/3643611/19818266/d8e37ab8-9d03-11e6-8310-d9df03cc6863.png)

**Comment by tagliala** [comment] 2016-10-28 20:53
Duplicate of #1034, please post your comment there

**Closed by tagliala** 2016-10-28 20:53 UTC
