### ISSUE TITLE
Icon Request: fa-icon-fashion

### ISSUE THREAD

**Issue by erpol** [FortAwesome/Font-Awesome#6831] opened 2015-06-26 14:40 UTC
An icon to represent fashion in general (yes I know: not easy!)
A couple of suggestions - a bag & shoe:
![image](https://cloud.githubusercontent.com/assets/13065811/8379554/7a0d4e26-1c29-11e5-9783-2cb8c8215734.png)
or the outline of an elegant woman:
![image](https://cloud.githubusercontent.com/assets/13065811/8379646/16aa090e-1c2a-11e5-862b-35ca7e864ee6.png)
(this is copyrighted content, I just give it as an example!)

It's for using to illustrate post categories on a website.
 
Thanks!
RP

**Comment by tagliala** [comment] 2015-07-01 11:27
I'm going to consider this as a duplicate of #3852, please +1 that request

**Closed by tagliala** 2015-07-01 11:27 UTC
