### ISSUE TITLE
Icon request: flutter

### ISSUE THREAD

**Issue by PrerakGada** [FortAwesome/Font-Awesome#19760] opened 2023-06-10 18:47 UTC
I would like to request an icon for the Flutter brand to be added to Font Awesome. The icon should be a simple, stylized representation of the Flutter logo. It should be available in all of the same styles as other Font Awesome icons.

The Flutter brand is a registered trademark of Google, so any icon that is created must be approved by Google before it can be added to Font Awesome. I have already contacted Google and they have approved the request.

I believe that adding a Flutter icon to Font Awesome would be a valuable addition to the library. Flutter is a popular mobile development framework, and many developers use Font Awesome to add icons to their apps. An official Flutter icon would make it easier for developers to use the Flutter brand in their apps.

Thank you for your consideration.=

**Comment by tagliala** [comment] 2023-06-10 19:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14878 , please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-06-10 19:00 UTC
