### ISSUE TITLE
Icon request: icon-medal

### ISSUE THREAD

**Issue by onkarjit** [FortAwesome/Font-Awesome#10894] opened 2017-04-05 09:40 UTC
Right now font-awesome has the fa fa-trophy which is a cup. It would be great if you could also add a medal icon. I'm not really good at drawing myself, but something like in the link below would be great. 

https://d1yn1kh78jj1rr.cloudfront.net/preview/medal-2-glyph-icon_fkIrSaLu_S.jpg

**Comment by tagliala** [comment] 2017-04-05 09:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1898 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-05 09:51 UTC
