### ISSUE TITLE
网易云音乐icon

### ISSUE THREAD

**Issue by qq240814476** [FortAwesome/Font-Awesome#15064] opened 2019-05-26 15:27 UTC

**Comment by tagliala** [comment] 2019-05-26 15:38
Hi!

Thanks for being part of the Font Awesome Community.

As per google translate, I understand that This request is a duplicate of #8255, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-05-26 15:38 UTC
