### ISSUE TITLE
Icon Request: fa-checkout / fa-cashier

### ISSUE THREAD

**Issue by marceloverdijk** [FortAwesome/Font-Awesome#2452] opened 2013-11-20 20:48 UTC

**Comment by einewton** [comment] 2015-12-22 01:48
+1 for this..

And the more than 30+ other people who have requested it here: https://github.com/FortAwesome/Font-Awesome/issues/3467

**Comment by aethior** [comment] 2022-03-01 00:01
Duplicate of #3467.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-01 09:45
Thanks

**Closed by tagliala** 2022-03-01 09:45 UTC
Labels: new icon, web application icons
