### ISSUE TITLE
Icon Request: fa-deck

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#10004] opened 2016-09-29 18:24 UTC
Deck of cards/sheets/data/documents
![deck](https://cloud.githubusercontent.com/assets/539719/18966753/691d2482-8650-11e6-9bac-2438f7207ade.png)
 for use within a healthcare data app

**Comment by tagliala** [comment] 2016-09-30 09:00
Maybe http://fontawesome.io/icon/clone/ fits the case, or 

Duplicate of #6507, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 09:00 UTC
