### ISSUE TITLE
Icon Request: fa-houzz

### ISSUE THREAD

**Issue by jlr7245** [FortAwesome/Font-Awesome#6674] opened 2015-06-05 21:46 UTC
Hi,

I work with a lot of contractors who have a Houzz account & it would be treat to have a fontawesome icon for Houzz.

![](http://www.habachydesigns.com/images/icons/houzz.png)

Thanks!

**Comment by tagliala** [comment] 2015-06-06 09:36
duplicate of #2039 , please +1 that request

closing here

**Closed by tagliala** 2015-06-06 09:36 UTC
