### ISSUE TITLE
Icon request: fa-telegram

### ISSUE THREAD

**Issue by TassoneR** [FortAwesome/Font-Awesome#8855] opened 2016-03-29 22:16 UTC
It would be useful an icon representing the app Telegram. Here an example:
![t_logo](https://cloud.githubusercontent.com/assets/11615735/14125607/6575b440-f60c-11e5-8528-93a3ea05a5c4.png)
Moreover this is the official website of Telegram: https://telegram.org/

**Comment by tagliala** [comment] 2016-03-30 11:49
Duplicate of #3034, please +1 that request

Please also search before opening new requests

Closing here

**Closed by tagliala** 2016-03-30 11:49 UTC
