### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by Dagros** [FortAwesome/Font-Awesome#10456] opened 2017-01-02 15:48 UTC
Hi there,

I'm looking for easter-icons e.g. easteregg or easterbunny.
It would be a great help to embellish our website.

Thanks in advance from The Netherlands,

George

**Comment by tagliala** [comment] 2017-01-02 23:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6068, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-02 23:19 UTC
