### ISSUE TITLE
Icon Request: fa-tripadvisor

### ISSUE THREAD

**Issue by waspfreak** [FortAwesome/Font-Awesome#6782] opened 2015-06-18 17:15 UTC
![tripadvisor](https://cloud.githubusercontent.com/assets/8807626/8237269/f8ebac64-15e5-11e5-9760-29abbc505aca.png)

**Comment by tagliala** [comment] 2015-06-18 17:28
duplicate of #412 , planned for 5.0.0 release, please +1 that request

closing here

**Closed by tagliala** 2015-06-18 17:28 UTC
