### ISSUE TITLE
Icon request: icon-swim

### ISSUE THREAD

**Issue by vtorres1976** [FortAwesome/Font-Awesome#7593] opened 2015-10-02 12:02 UTC
Hi,
   I miss more sport icons :(. I would like to make use of them in a web site for a triathlon team.
![swim-512](https://cloud.githubusercontent.com/assets/14940018/10246069/1fd71284-690e-11e5-8d55-346a9e2c7800.png)

Thanks a lot! Love your project!
  Vicky.

**Comment by caduvieira** [comment] 2015-10-02 13:25
related to #325

**Comment by tagliala** [comment] 2015-10-02 16:30
This individual request is much better, leaving this open

**Comment by BenNG** [comment] 2016-01-22 11:58
I'm interested as well !

**Comment by SteveHarlington** [comment] 2016-01-25 22:05
+1
I'm very interested in a swim icon as I have a triathlon website I would like to include a swim icon. 
Fingers crossed.

**Comment by ryankane** [comment] 2017-01-12 15:41
The simpler, the better (especially for scaling)

In that respect, I have fabricated the following icon:

![fa-swim](https://cloud.githubusercontent.com/assets/1094151/21895980/ae9bf3e4-d8b2-11e6-859d-fec4bc6688b5.png)

### Source

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
  <g fill="#000000">
    <circle id="head" cx="424" cy="168" r="58" />
    <circle id="hand" cx="163.84" cy="221.56" r="29.789" />
    <path   id="body" d="M 280.17,227.14 143.29,315.18 C 256.56,345.95 254.93731,269.34 372.36,253.21 356.06,179.01 237.63,113.3 142.78,200.49 L 184.9,242.62 C 216.78,213.1 248.29,211.58 280.17,227.14 Z" />
  </g>
  <path id="water" d="M 50,326 C 89.775,356.23 160.41,403.48 255.69,367.26 324.40515,340.69006 343.22206,285.74445 459.12,317.54"
        fill="none" stroke="#000000" stroke-linejoin="round" stroke-linecap="round" stroke-width="38" />
</svg>
```

**Comment by solstice43** [comment] 2017-12-18 02:05
+1

**Comment by lickmydesign** [comment] 2018-01-02 18:14
+1

**Comment by PeterShaggyNoble** [comment] 2018-02-07 11:38
Duplicate of #5771

**Comment by tagliala** [comment] 2018-02-07 11:42
@PeterShaggyNoble thanks

There is also a comment of mine, I don't know how I missed #5771 🤷‍♂️ 

Closing here

**Closed by tagliala** 2018-02-07 11:42 UTC
Labels: new icon, sport icons
