### ISSUE TITLE
Icon request: mail-envelope-phone (contacts)

### ISSUE THREAD

**Issue by Bibendus83** [FortAwesome/Font-Awesome#16803] opened 2020-06-17 09:57 UTC
**What can it be used for?**
It can be used to show areas where you can add both your phone and email contacts data.
I know you can combine icons but, for what I'm aware of, combine results in two icons with different sizes.

**Example image (optional)**
https://www.iconfinder.com/icons/4017409/call_contact_us_mail_phone_icon
![image](https://user-images.githubusercontent.com/4517370/84883716-27a39580-b091-11ea-9688-b8f5cd08dd12.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by timwakeling** [comment] 2021-11-25 12:53
Yes please!

**Comment by sensibleworld** [comment] 2024-07-11 16:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/19413)

**Closed by sensibleworld** 2024-07-11 16:37 UTC
Labels: new icon, marketing (category), Duplicate
