### ISSUE TITLE
Icon request: fa-universe

### ISSUE THREAD

**Issue by tracysmith10** [FortAwesome/Font-Awesome#10606] opened 2017-02-02 16:50 UTC
An icon to depict the universe or space would be great for a project I am currently working on.  

![science-512](https://cloud.githubusercontent.com/assets/25510714/22558923/5c51f564-e967-11e6-891d-733857eddfda.png)

**Comment by tagliala** [comment] 2017-02-02 17:32
Looks like an atom. Duplicate of #664?

**Comment by sensibleworld** [comment] 2021-03-30 16:52
We have both `atom` and `atom-simple`, as well as `galaxy` and `solar-system`. Let me know if those don't work.

**Closed by sensibleworld** 2021-03-30 16:52 UTC
Labels: waiting for feedback
