### ISSUE TITLE
Icon request: icon-blogger

### ISSUE THREAD

**Issue by canpolat** [FortAwesome/Font-Awesome#10750] opened 2017-03-06 20:00 UTC
Hi,

In the list of icons I see one for Wordpress but could not see an icon for Blogger. Github search did not return any icon requests either. So, here we are. I think it would complement the Wordpress icon in "blogging platforms" context. I'm attaching the well known logo:

![Blogger Logo](http://3.bp.blogspot.com/_AcBUSVxs82w/S_dkXAZhaVI/AAAAAAAAdBY/G6qc_sbPhSU/s400/Blogger_Logo.jpg)

**Comment by PeterShaggyNoble** [comment] 2017-04-07 09:10
Dupe of #1088, you should 👍 that.

**Closed** 2017-04-07 09:26 UTC
