### ISSUE TITLE
Directory structure change in `6.5.0` release broke composer compatibility

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#20029] opened 2023-11-30 10:56 UTC
> Was the directory structure change done on purpose in the `6.5.0` release? Since `6.5.0` all assets reside in a `free` folder, this would be considered **backwards incompatible** for a minor right? It's also not mentioned in the [CHANGELOG.md](https://github.com/FortAwesome/Font-Awesome/blob/6.x/CHANGELOG.md), or did I miss something?
> 
> See [6.5.0](https://github.com/FortAwesome/Font-Awesome/tree/6.5.0) vs [6.4.2](https://github.com/FortAwesome/Font-Awesome/tree/6.4.2)

> You're familiar with [composer](https://getcomposer.org/)? Since font-awesome has a `composer.json` and it's available at [packagist](https://packagist.org/packages/fortawesome/font-awesome). Using `composer require fortawesome/font-awesome` would indeed 'clone' it in the `vendor` directory of your project.
> 
> Via `asset-mapper` you would need to link to the vendor directory to make the assets available, like `vendor/fortawesome/font-awesome/free/webfonts: 'fontawesome-fonts'` and that's were the path comes in.

_Originally posted by @evertharmeling in https://github.com/FortAwesome/Font-Awesome/issues/20016#issuecomment-1833482558_

**Comment by evertharmeling** [comment] 2023-11-30 12:28
[Symfony](https://symfony.com/what-is-symfony) recently introduced [AssetMapper](https://symfony.com/doc/current/frontend/asset_mapper.html) and since this library is also available as a composer package, you may install it with composer and [link to the files](https://symfony.com/doc/current/frontend/asset_mapper.html#importing-assets-outside-of-the-assets-directory) accordingly, therefore it's breaking the path. This goes also, for example, for bootstrap in terms of loading the package via composer, see [this video](https://www.youtube.com/watch?v=pyj1hvhcxGc&t=6340s) for example.

But I get that it's an odd situation and there are ways to work around this. If I'm the only one facing it and there are no other implications because of the directory structure change this issue could be closed.

**Comment by tagliala** [comment] 2023-11-30 13:35
Got it, but I wonder how the source code is related. Is font-awesome being vendored by cloning this repo?

**Comment by evertharmeling** [comment] 2023-11-30 13:46
You're familiar with [composer](https://getcomposer.org/)? Since font-awesome has a `composer.json` and it's available at [packagist](https://packagist.org/packages/fortawesome/font-awesome). 
Using `composer require fortawesome/font-awesome` would indeed 'clone' it in the `vendor` directory of your project.

Via `asset-mapper` you would need to link to the vendor directory to make the assets available, like `vendor/fortawesome/font-awesome/free/webfonts: 'fontawesome-fonts'` and that's were the path comes in.

**Comment by tagliala** [comment] 2023-11-30 13:50
Thanks. Not familiar with composer. Now it is pretty clear, thanks

**Comment by robmadole** [comment] 2023-11-30 14:37
Shoot, no this just slipped by. The directory change was not intentional. We've been working on some automation as of late and it was caused by a new process.

I'll get this fixed in 6.5.1.

**Comment by robmadole** [comment] 2023-11-30 15:13
I've moved the files out of the `free` directory for the time being. If anything is targeting the `6.x` branch that should fix things. I'll get a proper tag and release done today.

**Comment by tagliala** [comment] 2023-11-30 20:38
Should have been fixed in 6.5.1

**Closed as completed** 2023-12-01 16:28 UTC
Labels: bug, BREAKING CHANGE
