### ISSUE TITLE
Icon request: icon-topics

### ISSUE THREAD

**Issue by srsteinberg** [FortAwesome/Font-Awesome#12057] opened 2018-01-08 16:04 UTC
When building websites, I tend to have "topics" as one section of the website, and would love to have an icon for it. Perhaps an open book? Thank you.

**Comment by tagliala** [comment] 2018-01-08 17:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #176, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-08 17:48 UTC
