### ISSUE TITLE
Icon Request: fa-beBee

### ISSUE THREAD

**Issue by yedum** [FortAwesome/Font-Awesome#10892] opened 2017-04-05 03:26 UTC
![bebee](https://cloud.githubusercontent.com/assets/26915482/24688294/b76f5c34-19dc-11e7-8332-34f9cfe19377.png)

[beBee](https://www.bebee.com/) is a Personal Branding Platform founded by serial-entrepreneurs Javier Cámara and Juan Imaz. The network was created to allow people to showcase and share their personal brand and market themselves to employers, clients, customers, vendors and media in their respective industries. beBee allows users to network with each other through common personal and professional interests, uniting their personal and professional lives in one place.

The startup was established in February 2015, and originally launched in English, Spanish and Portuguese before expanding in French, Italian, German and Russian in 2016.

I would kindly suggest you to add the icon of beBee to the 'The Font Awesome' site, as it would be a lot beneficial for the beBee members.

**Comment by tagliala** [comment] 2017-04-05 07:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10879, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-05 07:52 UTC
Labels: brand icons, new icon
