### ISSUE TITLE
About a very famous icon you've lost

### ISSUE THREAD

**Issue by ZL-Asica** [FortAwesome/Font-Awesome#14784] opened 2019-03-21 09:46 UTC
Dear developers,
The website [Bilibili](https://www.bilibili.com) is one of the China biggest video website. I do not find this website's icon in the sheet. The icon of this website is so easy that just a mini TV symbole. I really hope you, developers of FontAwesome, make this icon and add it into your icon sheet.
Thank you so much!
By a high school student from China

**Comment by tagliala** [comment] 2019-03-21 10:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9789, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-03-21 10:16 UTC
