### ISSUE TITLE
Icon request: ban-alcohol

### ISSUE THREAD

**Issue by ilu002** [FortAwesome/Font-Awesome#18753] opened 2022-02-24 18:32 UTC
Request to create new icon based on existing 'ban' and 'martini-glass' icons. The new icon would be similar to the 'ban-smoking' icon. 
Use case: indicator for patient social status in medical/clinical use

**Comment by tagliala** [comment] 2022-02-26 16:44
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/624/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment] 2024-07-11 15:14
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](add "ban" mod to Wizard)

**Closed as completed by sensibleworld** 2024-07-11 15:14 UTC
Labels: new icon, medical / health (category), Duplicate

**Comment by tagliala** [comment] 2024-07-19 09:18
@sensibleworld this is missing a feature request for the icon wizard I guess

**Comment by sensibleworld** [comment] 2024-07-19 11:39
@tagliala Thanks! We've got the "ban" modifier tracked elsewhere.
