### ISSUE TITLE
Icon request: ringing-desk-bell

### ISSUE THREAD

**Issue by michelleTWS** [FortAwesome/Font-Awesome#12828] opened 2018-04-10 22:52 UTC
### A ringing desk bell.
Ringing & not ringing versions would be nice. 
I would use it for a quick service order or customer service request.
This example is from webdings font glyphs.
![ringing_desk_bell](https://user-images.githubusercontent.com/38265983/38587490-878fff82-3cd6-11e8-91ab-6f833f1a306d.PNG)

**Comment by tagliala** [comment] 2018-04-11 07:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3919, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-11 07:57 UTC

**Comment by michelleTWS** [comment] 2018-04-11 13:57
It’s not duplicate. That one has a hand in it. I did check already and upvoted it.

Sent from my iPhone

On Apr 11, 2018, at 12:58 AM, Geremia Taglialatela <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3919<https://github.com/FortAwesome/Font-Awesome/issues/3919>, please add a 👍 reaction to that request.

Please make sure you search existing requests<https://github.com/FortAwesome/Font-Awesome/search?type=Issues> before opening new ones

Closing here

**Comment by tagliala** [comment] 2018-04-11 15:06
hi @michelleTWS , the example provided in #3919 is just an example and does not reflect the exact design.

A ringing-desk-bell will probably be implemented without the hand on the top to be 16px icon size friendly
