### ISSUE TITLE
Icon Request: fa-gas-station

### ISSUE THREAD

**Issue by kinkazu** [FortAwesome/Font-Awesome#11237] opened 2017-06-29 10:51 UTC
Hi Font Awesome. Would you be so kind to consider creating an icon for fuel station? 
The icon could represent gas dispenser, same icon as used in all our cars and placed nearby fuel gauge.
I plan to use it combined with google maps and showing gas stations nearest to selected postcode.
This icon can represent, fuel, petrol, diesel, fuel station, small variation with vertical bar can represent fuel levels.
Kind Regards

**Comment by tagliala** [comment] 2017-06-29 11:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1676 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-29 11:04 UTC
