### ISSUE TITLE
Icon Request: fa-br_real

### ISSUE THREAD

**Issue by dfvascao** [FortAwesome/Font-Awesome#8915] opened 2016-04-07 14:57 UTC
Hello,

could create an icon with the currency here in Brazil (R$)
![br_real](https://cloud.githubusercontent.com/assets/18331656/14355575/ca64256a-fcb7-11e5-8e51-a88bb9491498.png)
. I'm designing a cart buying application and gently need this icon I put on my android application.

Thank you and look forward

**Comment by tagliala** [comment] 2016-04-07 21:57
Duplicate of #4916, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-07 21:57 UTC
