### ISSUE TITLE
Icon request: permille

### ISSUE THREAD

**Issue by Flightkick** [FortAwesome/Font-Awesome#13323] opened 2018-06-14 09:25 UTC
### What can it be used for?

About the same use cases as %.
Currently % is supported but there's no permille icon.

### Example image (optional)

![afbeelding](https://user-images.githubusercontent.com/8693699/41403474-410411a8-6fc5-11e8-837d-cb352f59d340.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-06-14 10:36
Hi!

Thanks for being part of the Font Awesome Community.

Not an English native speaker here. Is not that symbol referenced as `per mille`? https://en.wikipedia.org/wiki/Per_mille

**Comment by Flightkick** [comment] 2018-06-14 11:00
@tagliala You're absolutely right. My head was somewhere else. I've corrected my OP.

**Comment by Crissov** [comment] 2018-11-15 14:23
Related Unicode #222:

- ‰ U+2030 Per Mille Sign

**Comment by aethior** [comment] 2022-03-07 18:22
Duplicate of #9285.

cc/ @tagliala

**Closed** 2022-03-07 19:38 UTC
Labels: new icon, web application icons

**Comment by sensibleworld** [comment] 2025-12-08 17:45
Hey there!

We've made the decision to move our icon requests flow to **GitHub Discussions**, as opposed to issue tracking. No more +1s or thumbs-ups needed. There's an upvote system built in.

As part of this transition, we are closing existing icon requests with lower comment or reaction counts, but **we are not saying no** to your request. (We know some of these have been open since before I had gray hair. And I've had gray hair for a LONG time.)

**Could you do us a favor? If this icon request is still relevant for you, please re-open it in Discussions** (and feel free to include a link back to this issue):
→ https://github.com/FortAwesome/Font-Awesome/discussions/new?category=icon-requests

And listen. We know this is annoying. We would batch convert them to discussions if we could, but Github's removed that ability earlier this year. If you need to vent, here are some pre-written responses you can use when opening the new discussion:

* Cool cool cool. No worries at all. I love doing things twice.
* If an issue closes after seven years and nobody responds, did it ever really exist?
* I see you have chosen violence today. Re-opening per instructions.
* What's next? I have to file a TPS report, too?
* I am filled with the fury of a thousand suns. This request already HAS an auto-response saying that you're refining the workflow. What do you mean you're refining your refinement? That's a bunch of bull-phooey.
* No biggie. Thanks for letting us know what's up.
