### ISSUE TITLE
Icon Request: fa-blogger

### ISSUE THREAD

**Issue by binauralca** [FortAwesome/Font-Awesome#7438] opened 2015-09-11 15:58 UTC
icon will be use as a link to blogger page

**Comment by caduvieira** [comment] 2015-09-11 17:24
dupe of #1088

**Comment by TheChen5** [comment] 2015-09-12 18:45
To prevent dupes
Please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-09-12 20:25
thanks

closing here

**Closed by tagliala** 2015-09-12 20:25 UTC
