### ISSUE TITLE
Icon request: fa-times-octagon

### ISSUE THREAD

**Issue by qck1** [FortAwesome/Font-Awesome#8614] opened 2016-02-19 18:57 UTC
Stop sign is sort of universal for stop. Recommend one with an "X" in the middle as probably the most universal symbol

**Comment by tagliala** [comment] 2016-02-19 22:58
duplicate of #1872, please post an example if you have something different in mind

**Comment by qck1** [comment] 2016-02-20 00:36
I tried using the stop that is a square, and I got push back from some of the users, who did not understand the square. There is definitely a lack of traffic symbols in the font which is too bad. Comments on 1872 indicate that traffic symbols would be very desirable. I did research and the already see a number road symbols different in UIs. See https://en.wikipedia.org/wiki/Stop_sign to get background
![stop](https://cloud.githubusercontent.com/assets/11397635/13192739/3949278c-d724-11e5-8ff1-4154ee9e654c.png)

**Comment by tagliala** [comment] 2016-02-20 11:36
renaming to `times-octagon`

**Comment by tagliala** [comment] 2016-02-20 11:37
Refers to #1302

**Comment by aethior** [comment] 2022-03-09 01:07
Hi @qck1,

This icon was added in v5.0.0.
Check https://fontawesome.com/icons/octagon-xmark

Regards.

cc/ @tagliala

**Closed** 2022-03-09 17:10 UTC
Labels: new icon, Available in FA Pro, mathematics (category)
