### ISSUE TITLE
Icon request, space

### ISSUE THREAD

**Issue by teckel12** [FortAwesome/Font-Awesome#10495] opened 2017-01-08 18:21 UTC
When using CSS to manipulate an existing FA font, one can't use the **content** attribute to change/edit the content to include a space.  For example, lets say you want to do the following `content: " \f101"` (notice there's a space before the \f101).  That doesn't work.  If FA included a space, one could do something like this: `content: "\f255\f101"` (with 255 being a space, but whatever the number would actually be).

There's a work-around, to use the character '\A0'.  However, that's not well known.  It could be as simple as using '\A0' with FA instead of adding a new icon.  But, that would be up to the FA team.  I've run into this problem many times and finally figured found out about the '\A0' trick, but why make it a trick?  Just give people a space icon (how hard could that really be?)

Tim

**Comment by tagliala** [comment] 2017-01-08 18:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1606, which is labeled as `wontfix`

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-08 18:30 UTC
