### ISSUE TITLE
Icon request: redux-logo

### ISSUE THREAD

**Issue by Pedro-Goncal** [FortAwesome/Font-Awesome#18528] opened 2021-12-21 17:46 UTC
**What can it be used for?**
Usefull for developers portfolio or frelancer pages

**Example image (optional)**
[Insert the example image here if necessary.](https://seeklogo.com/images/R/redux-logo-9CA6836C12-seeklogo.com.png)

**Icon request checklist**
- [y ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ y] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [y ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [y ] I have included at least one example image if it could be helpful (optional)
- [ y] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-12-21 17:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12299, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-12-21 17:48 UTC
