### ISSUE TITLE
icon request: phonepad

### ISSUE THREAD

**Issue by SavantasNL** [FortAwesome/Font-Awesome#15099] opened 2019-06-01 21:03 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
This icon is shown in the interface when calling with your phone. For use with callcenters (dial 1 for ...) often needed.
**Example image (optional)**
Insert the example image here if necessary.
![61026](https://user-images.githubusercontent.com/33956440/58753575-7cde2a80-84c1-11e9-87e4-d6624aaca424.png)

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-06-01 21:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6266, please add a 👍 reaction to that request.

Closing here

**Closed by tagliala** 2019-06-01 21:11 UTC
