### ISSUE TITLE
Icons request: thermometer, coolers (air)

### ISSUE THREAD

**Issue by Heash** [FortAwesome/Font-Awesome#9008] opened 2016-04-18 11:43 UTC
It would be grate to have this icons!

**Comment by tagliala** [comment] 2016-04-18 11:45
thermometer: duplicate of #720 , planned for 5.0.0, please +1 that request
coolers = #3684 ?

**Comment by aethior** [comment] 2016-07-08 01:30
@tagliala I think you can close here. Usually 'cooler' and 'fan' are the same thing.

**Closed** 2016-07-08 10:39 UTC
