### ISSUE TITLE
Icon request: icon-discord

### ISSUE THREAD

**Issue by BelkoSenpai** [FortAwesome/Font-Awesome#9499] opened 2016-06-29 21:15 UTC
Something like this, in black and white color.
![687474703a2f2f692e696d6775722e636f6d2f65597779386c632e706e67](https://cloud.githubusercontent.com/assets/20213856/16469106/8241a1ca-3e4f-11e6-86ff-30dac4200bf2.png)

**Comment by tagliala** [comment] 2016-06-29 21:21
Duplicate of #7574, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-29 21:21 UTC
