### ISSUE TITLE
Cedi sign icon -  ¢

### ISSUE THREAD

**Issue by Sedoworld** [FortAwesome/Font-Awesome#10889] opened 2017-04-04 11:47 UTC
Hi font-awesome, the cedi sign icon is not part of your list of icons.. please come up with a cedi sign (¢)  icon. Thanks

**Comment by tagliala** [comment] 2017-04-04 11:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7287, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-04 11:51 UTC
