### ISSUE TITLE
Icon request: ethernet

### ISSUE THREAD

**Issue by moriartp** [FortAwesome/Font-Awesome#7632] opened 2015-10-07 15:58 UTC
![ethernet_on](https://cloud.githubusercontent.com/assets/13931458/10343213/c8d629bc-6cea-11e5-94c5-18b3c01e4509.png)

**Comment by tagliala** [comment] 2015-10-07 16:57
duplicate of #2565, please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-10-07 16:57 UTC
