### ISSUE TITLE
Icon Request: fa-money-bag

### ISSUE THREAD

**Issue by DmStepanov** [FortAwesome/Font-Awesome#10870] opened 2017-03-31 12:18 UTC
Hello there!
Please, give me a money bag!
Like this: https://goo.gl/YDEsPE
Thanks, Dmitry.

**Comment by tagliala** [comment] 2017-03-31 17:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1414 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-31 17:25 UTC

**Comment by DmStepanov** [comment] 2017-03-31 18:14
Ok, thanks!
