### ISSUE TITLE
Icon request: icon-vr (for Google Cardboard and other VR enabled content and apps)

### ISSUE THREAD

**Issue by PixelPartner** [FortAwesome/Font-Awesome#6590] opened 2015-05-29 11:52 UTC
To mark VR (virtual reality) enabled apps and WebVR enabled web sites and Cordova Apps it would be helpfull to use an icon with the catchy Google Cardboard logo but with a more general name
https://developers.google.com/cardboard/
i.e. /site-assets/logo-cardboard-white.svg

**Comment by davidneat** [comment] 2015-05-30 11:18
+1

**Comment by AndrewHazelden** [comment] 2015-05-30 20:10
+1

**Comment by markmooibroek** [comment] 2015-07-06 09:21
+1

**Comment by adamsar** [comment] 2015-10-09 04:39
+1

**Comment by RogueSheep-nl** [comment] 2015-12-21 10:11
+1

**Comment by pseudozach** [comment] 2015-12-29 09:18
+1

**Comment by Sneagan** [comment] 2016-01-05 18:32
Anything clearly a headset would work. If there's some copyright issue with using something that looks too close to a Google Cardboard we could use something more generic, though I admit that it's hard to get more generic than the cardboard icon. ;)

**Comment by b0bbyriggs** [comment] 2016-01-21 23:47
+1

**Comment by developius** [comment] 2016-02-07 17:08
+1

**Comment by syumai** [comment] 2016-02-08 04:35
+1

**Comment by SamRohn** [comment] 2016-02-16 10:41
+1

**Comment by sgenzer** [comment] 2016-02-17 16:16
+1

**Comment by jazzyjester** [comment] 2016-02-21 10:37
+1

**Comment by jasonrgd** [comment] 2016-02-22 05:25
+1

**Comment by umbreak** [comment] 2016-03-11 13:05
+1

**Comment by georgereason** [comment] 2016-03-16 14:32
+1

**Comment by blq** [comment] 2016-03-25 14:26
+1

**Comment by Youkho** [comment] 2016-03-31 20:55
+1

**Comment by rafaeleiki** [comment] 2016-04-07 19:11
+1

**Comment by otaviowillow** [comment] 2016-04-08 04:19
+1

**Comment by kldoon** [comment] 2016-04-20 14:27
+1

**Comment by teleyinex** [comment] 2016-05-12 07:47
+1

**Comment by Patrick-Wheeler** [comment] 2016-06-03 20:16
+1

**Comment by bknill** [comment] 2016-06-09 22:47
+1

**Comment by dbradleyfl** [comment] 2016-07-06 22:03
+1

**Comment by lin00** [comment] 2016-07-21 17:55
+1

**Comment by robmerki** [comment] 2016-08-09 21:55
+ 1

**Comment by babysharny** [comment] 2016-08-17 21:43
+1

**Comment by JordanMajd** [comment] 2016-08-31 05:10
+1

**Comment by BitcoinSolution** [comment] 2016-08-31 10:43
+1

**Comment by costellos2010** [comment] 2016-09-01 13:23
+1. This really needs to be a thing.

**Comment by SNeilson** [comment] 2016-09-12 15:43
+1

**Comment by bjorn-ali-goransson** [comment] 2016-09-26 18:26
Don't forget that simple logos of real trademarks are sometimes public domain, like the [Microsoft logo](https://commons.wikimedia.org/wiki/File:Microsoft_logo.svg). But I like a-frame's icon more, like here: https://aframe.io/examples/showcase/helloworld/

Already in SVG format ...

**Comment by AnnelVenter** [comment] 2016-09-30 11:18
+1

**Comment by ccharlton** [comment] 2016-10-07 22:38
+1

**Comment by calvintps** [comment] 2016-10-12 01:54
+1

**Comment by simonevitale** [comment] 2016-10-13 09:46
+1

**Comment by tagliala** [comment] 2016-10-25 09:05
Let's use this for a generic VR icon (examples would be appreciated), please 👍 #9785  for Google Cardboard

**Comment by NicklasBenRasmussen** [comment] 2016-10-29 09:12
+1

**Comment by inthesauce** [comment] 2016-12-04 20:14
+1 

In the meantime, I am using fa-simplybuilt [&#xf215;] 
Just flipped vertically  :)

**Comment by arapl3y** [comment] 2017-03-12 03:21
+1

**Comment by slmnm** [comment] 2017-03-18 18:30
+1

**Comment by jordonrupp** [comment] 2017-03-24 18:53
+1

**Comment by tadasstra** [comment] 2017-03-25 03:47
+1

**Comment by ccharlton** [comment] 2017-03-28 21:24
Virtual +1 :)

**Comment by garynobles** [comment] 2017-04-20 09:26
I'm looking for this kind of icon for a university project, very much needed for academia as well as for more generic VR +1

**Comment by hperrin** [comment] 2017-05-01 18:58
+1

**Comment by bhalial** [comment] 2017-05-22 06:42
+1

**Comment by gamereat** [comment] 2017-05-26 19:15
+1

**Comment by tgunz** [comment] 2017-06-13 19:35
For what it's worth, rotating the simply built icon 180deg works pretty well:
http://fontawesome.io/icon/simplybuilt/

**Comment by sabinedijt** [comment] 2017-06-19 13:02
+1

**Comment by aph-vsn** [comment] 2017-06-28 01:18
+1

**Comment by HAZARDU5** [comment] 2017-07-11 23:20
This would be really useful! I'm prototyping a bunch of WebVR demos using font-awesome / bootstrap for 2D UI so having an icon like this bundled in would be great :-) 👍

**Comment by MikelArnaiz** [comment] 2017-07-27 12:20
+1 for a generic VR headset

**Comment by SamRohn** [comment] 2017-07-31 12:50
+1 for google cardboard VR icon

**Comment by ableslayer** [comment] 2017-08-04 03:56
+1 for google cardboard VR icon

**Comment by Bagmaz** [comment] 2017-08-13 16:59
+1

**Comment by hhassan1230** [comment] 2017-08-29 19:17
+1 for Oculus/GearVR, HTC Vive & Google Cardboard/Daydream

**Comment by Disorrder** [comment] 2017-10-22 15:28
+1 for webvr

**Comment by Candie** [comment] 2017-11-14 16:19
+1 for generic one maybe with VR in the middle.

**Comment by dbodesign** [comment] 2017-11-24 14:57
It's not the best alternative, but...: http://fontawesome.io/icon/simplybuilt/

**Comment by ebuntario** [comment] 2017-12-04 02:52
+1 but is there any progress on this? this ticket has been open for some time now.

**Comment by m4d3** [comment] 2017-12-09 13:09
+1

**Comment by modusops** [comment] 2017-12-09 19:50
+1

**Comment by ccharlton** [comment] 2017-12-15 21:13
In the meantime, I feel like this guy: http://fontawesome.io/icon/grav/

**Comment by elipeters** [comment] 2018-02-15 10:19
+1

**Comment by satopy** [comment] 2018-02-27 06:24
+1

**Comment by Itee** [comment] 2018-03-07 20:33
+1

**Comment by tamasturcsanyi** [comment] 2018-03-09 11:00
+1

**Comment by Hunter-Bobeck** [comment] 2018-03-13 00:57
+1

**Comment by jochemstoel** [comment] 2018-05-25 22:09
+1
Cardboard / VR icon very much appreciated. 
![cardboard](http://kamerawerk.at/kamerawerk/wp-content/uploads/CardboardIcon-Kopie.png)

**Comment by adamhhhh** [comment] 2018-06-06 01:46
+1

**Comment by jfarmersp** [comment] 2018-06-18 20:29
+1

**Comment by alystair** [comment] 2018-07-12 13:42
I hope that we are able to have a more generic, universally identifiable icon for VR, I'm currently using the "cube" icon to represent 3D-ness. Thanks @sensibleworld :)

**Comment by ajmaurya99** [comment] 2018-07-16 10:45
+1

I am looking for an AR and VR icon

**Comment by come2thecabaret** [comment] 2018-08-07 13:13
+1

**Comment by ccharlton** [comment] 2018-08-17 21:30
Is this now a dupe of https://github.com/FortAwesome/Font-Awesome/issues/772 ?

**Comment by ccharlton** [comment] 2018-08-17 21:30
+1000

**Comment by equinox2k** [comment] 2018-08-29 18:45
Maybe a icon representing to enter vr and one to exit vr

**Comment by sensibleworld** [comment] 2018-10-12 15:05
This was added in 5.4: https://fontawesome.com/icons/vr-cardboard?style=solid (along with an alternate version: https://fontawesome.com/icons/head-vr?style=solid)

It's currently available in Font Awesome Pro, but will be added to Free in the next release. (Meant to do so in this release, but it slipped through the cracks).

**Closed by sensibleworld** 2018-10-12 15:05 UTC
Labels: new icon, released, web application icons

**Comment by equinox2k** [comment] 2018-10-12 15:22
@sensibleworld would be great to add to alternate version where the headset is off or being raised up to represent exiting vr

**Comment by sensibleworld** [comment] 2018-10-13 12:31
@equinox2k We've also added a `head-side` icon the matches the `head-vr` icon: https://fontawesome.com/icons/head-side?style=solid
