### ISSUE TITLE
Icon request: fa-houzz

### ISSUE THREAD

**Issue by kerbasaurus** [FortAwesome/Font-Awesome#6066] opened 2015-03-26 12:42 UTC
Could y'all do us a solid and add an icon for Houzz pretty pretty please?  Just the icon portion.  Thank you!

![Image of Houzz](http://www.houzz.com/pic/footer_houzz_logo.png)

I'll be using these on a very high end lighting company website.

**Comment by rtpHarry** [comment] 2015-03-26 21:32
FYI this is in the brandico fontset already
http://fontello.com/#search=houzz

**Comment by tagliala** [comment] 2015-03-27 13:55
Closing as a duplicate of #2039

**Closed by tagliala** 2015-03-27 13:55 UTC

**Comment by markream** [comment] 2015-05-27 19:15
+1
