### ISSUE TITLE
Icon Request: fa-chalk

### ISSUE THREAD

**Issue by timsmarketing** [FortAwesome/Font-Awesome#11503] opened 2017-09-08 18:54 UTC
I am looking for icons that speak to corporate training. Yes, PDF, XLS, DOC, Video all work, but I would like generic training icons. 

Chalk, Chalkboard, Projector, Projector Screen, Easel
![chalk-sticks](https://user-images.githubusercontent.com/31778071/30226861-d101a7a0-9494-11e7-960f-fe55b56131e6.jpg)
![easel](https://user-images.githubusercontent.com/31778071/30226860-d0fe9a06-9494-11e7-9d9e-4e27b7d7489e.png)
![screen_board](https://user-images.githubusercontent.com/31778071/30226863-d12c1ddc-9494-11e7-99a9-546ce1c941f1.png)

**Comment by tagliala** [comment] 2017-09-08 21:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3308, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-08 21:44 UTC
