### ISSUE TITLE
Icon Request: music key note

### ISSUE THREAD

**Issue by china-fengguan** [FortAwesome/Font-Awesome#12541] opened 2018-03-08 08:41 UTC
A music web page really need this. 
![stock-vector-simple-treble-clef-vector-icon-isolated-on-white-background-559871395](https://user-images.githubusercontent.com/33741121/37141247-5a059956-22ef-11e8-9b1e-ca14ed6d055e.jpg)
![stock-vector-simple-treble-clef-vector-icon-isolated-on-white-background-559871395](https://user-images.githubusercontent.com/33741121/37141277-7c5b72b4-22ef-11e8-8e45-722febe43ce8.jpg)

Thanks!

**Comment by tagliala** [comment] 2018-03-08 18:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10184, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-08 18:08 UTC
