### ISSUE TITLE
Icon request: icon-Office365

### ISSUE THREAD

**Issue by gusbn** [FortAwesome/Font-Awesome#13002] opened 2018-05-02 10:31 UTC
Is it possible to get the Microsoft product icon for Office 365? - Currently only Microsoft and Windows 10 icons are available, but it would be great to have the product specific icon as Windows 10 and Microsoft are not precise enough.  

 
![image](https://user-images.githubusercontent.com/38910103/39518756-879e401c-4e04-11e8-8aaf-3f7edc6e3726.png)

Thanks in advance

**Comment by tagliala** [comment] 2018-05-02 12:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1333, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-02 12:06 UTC
