### ISSUE TITLE
Icon request: fab fa-tiktok

### ISSUE THREAD

**Issue by aserra** [FortAwesome/Font-Awesome#16729] opened 2020-05-27 17:13 UTC
**What can it be used for?**
To link TikTok web page

**Example image (optional)**

https://lh3.googleusercontent.com/iBYjvYuNq8BB7EEEHktPG1fpX9NiY7Jcyg1iRtQxO442r9CZ8H-X9cLkTjpbORwWDG9d=s360-rw

https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Cib-tiktok_%28CoreUI_Icons_v1.0.0%29.svg/100px-Cib-tiktok_%28CoreUI_Icons_v1.0.0%29.svg.png

**Comment by aserra** [comment] 2020-05-27 17:15
sorry: https://www.tiktok.com/

**Comment by tagliala** [comment] 2020-05-27 18:42
Hi!

Thanks for being part of the Font Awesome Community.

Duplicate of #14340, +1 not needed because tiktok will be released with the new font awesome version (no eta yet, sorry)

**Closed by tagliala** 2020-05-27 18:42 UTC
