### ISSUE TITLE
Icon request: icon-led (led bulb)

### ISSUE THREAD

**Issue by mjra** [FortAwesome/Font-Awesome#5759] opened 2015-02-23 09:41 UTC
Another icon i need for my webpageproject: A Icon for LED lights.

**Comment by tagliala** [comment] 2015-02-26 14:06
(better) duplicate of #5721, but I really need an example

closing here

**Comment by tagliala** [comment] 2015-04-09 12:45
reopening here

**Comment by sensibleworld** [comment] 2024-07-10 21:44
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/lightbulb-cfl?f=classic&s=solid)

**Closed by sensibleworld** 2024-07-10 21:44 UTC
Labels: new icon, web application icons (legacy category), FA Pro
