### ISSUE TITLE
Icon Request: fa-gas

### ISSUE THREAD

**Issue by kosuhin-lexa** [FortAwesome/Font-Awesome#6981] opened 2015-07-19 09:33 UTC
Hi i've searched a several times and waited updates for this icon, but....
![gas_station](https://cloud.githubusercontent.com/assets/8445711/8765386/c5a203be-2e11-11e5-89c1-9ef2390ec4fe.png)

often needed for some fueling object presenations on web.
name may be varied: fa-gas, fa-fuel...

in other sets of icons something like this exists, but i think in't a good way to use only one set of icons.

**Comment by tagliala** [comment] 2015-07-26 13:39
duplicate of #1676 , please +1 that request

closing here

**Closed by tagliala** 2015-07-26 13:39 UTC
