### ISSUE TITLE
Icon Request: icon-bounding-box

### ISSUE THREAD

**Issue by SteveJordanKW** [FortAwesome/Font-Awesome#8640] opened 2016-02-23 22:20 UTC
We've been using Font-Awesome for quite some time within our OpenSource scientific tools. While building web applications for scientific simulation and visualization (ParaViewWeb, ArcticViewer, HPCCloud...) we sometime run short in type of icons that could match our needs.

Hence today, we thought we should try to contribute those we commonly use within our application. 

This icon c
![bounding-box](https://cloud.githubusercontent.com/assets/1433903/13268655/a94e3ad8-da51-11e5-9a7a-f744e7b42fd9.png)
ould be used as a 3D representation (outline) as well as referencing the volume of the current 3D data.

**Comment by tagliala** [comment] 2016-02-24 10:39
I'm going to consider this a duplicate of #2082, please +1 that request

@SteveJordanKW you made some requests about a specific field. That's fine, but I should advise you to consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

All you need is proper .svg files of icons and brands you are requesting and one of the online tools mentioned in the above wiki

**Closed** 2016-02-24 10:39 UTC
