### ISSUE TITLE
Icon Request: fa-add-document and fa-add-tag

### ISSUE THREAD

**Issue by tritone11** [FortAwesome/Font-Awesome#7723] opened 2015-10-20 02:10 UTC
Useful for databases, icons to add documents and tags for admins.
(fa-file with a plus and fa-tag with a plus)

**Comment by tagliala** [comment] 2015-11-01 22:17
refers to #1181 , you will find a solution there

**Comment by tagliala** [comment] 2015-11-01 22:18
add-tag is a duplicate of #1384, please +1 that request
file-add is a duplicate of #3041, please +1 that request

all duplicates, closing here

**Closed by tagliala** 2015-11-01 22:18 UTC
