### ISSUE TITLE
Icon Request: fa-VR Virtual Reality

### ISSUE THREAD

**Issue by TotemaVR360** [FortAwesome/Font-Awesome#11713] opened 2017-11-05 09:58 UTC
Icon request: icon-name Virtual Reality
![vr](https://user-images.githubusercontent.com/33390639/32413740-2ee5cbca-c218-11e7-9f7a-9e35b7181197.png)

**Comment by tagliala** [comment] 2017-11-05 13:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6590 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-05 13:07 UTC
