### ISSUE TITLE
Icon request: presentation / lectern

### ISSUE THREAD

**Issue by regua** [FortAwesome/Font-Awesome#11223] opened 2017-06-24 19:40 UTC
An icon representing an oral presentation of some sort would be useful.

Some examples would be an icon of a person presenting:
![presentation](http://redcarpetwebs.com/images/redcarpetwebsolution/pp.png)
or a person at a lectern:
![lectern](https://s-media-cache-ak0.pinimg.com/736x/44/0b/81/440b81d7d061a67e632a1844ab226e94.jpg)

**Comment by tagliala** [comment] 2017-06-24 19:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7630 or #472, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-24 19:45 UTC
