### ISSUE TITLE
JSON endpoint

### ISSUE THREAD

**Issue by melvinkoopmans** [FortAwesome/Font-Awesome#10802] opened 2017-03-17 18:09 UTC
Would it be possible to create a JSON endpoint on the fontawesome.io website to request a list of all available icons for a specific version? I would like to create a dropdown select with all the possible items and I'd rather not hardcode the options (or write an entire script to get all of the available icons).

**Comment by PeterShaggyNoble** [comment] 2017-03-17 19:24
Is [this YML file](https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml) of use to you?

**Comment by tagliala** [comment] 2017-03-18 00:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3366, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-18 00:13 UTC
