### ISSUE TITLE
Firefox fa-spin wobbling.

### ISSUE THREAD

**Issue by UNST4BL3** [FortAwesome/Font-Awesome#11651] opened 2017-10-20 08:12 UTC
On Firefox 57.0b8 and 55.0.3 I am seeing a ~2px wobble on icons using the `fa-spin` class. I am **not** seeing this issue on Chrome 61.0.3163.100.

I am not sure whether the issue is specific to these versions or not.

Firefox: https://i.imgur.com/F7RiQMs.gifv
Chrome: https://i.imgur.com/GvpjHPP.gifv
Sorry for the low framerate.

**Comment by tagliala** [comment] 2017-10-20 08:38
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I must consider this a duplicate of #671 

Please take a look there.

AFAIK, there is no silver bullet solution for webfont. SVG framework does not have this issue

**Closed by tagliala** 2017-10-20 08:38 UTC

**Comment by tagliala** [comment] 2017-10-20 22:40
@UNST4BL3 

Firefox 56, non-retina MacBook with macOS 10.13

https://jsfiddle.net/tagliala/p4do9La1/

It is spinning fine for me. Please make sure you are using multiples of 14px for your spinner, it definitely helps.

Please check: https://jsfiddle.net/tagliala/p4do9La1/1/

![spinner2 1](https://user-images.githubusercontent.com/556268/31844283-f8798bd4-b5f7-11e7-97cf-f292a620e559.gif)
(I'm also sorry for the quality)

You can see a 56px spinner vs a 64 px spinner. As you can see, the 64px pixel spinner is definitely wobbing more

**Comment by phthatcher-conocophillips** [comment] 2023-07-21 04:16
2023 I noticed the same thing using <fa-icon> in angular (@fortawesome/angular-fontawesome). Some have recommended multiples of 14px or using margins instead of padding but regardless I still had a wobble.  What I discovered was instead of using the native fa-spin class, use this instead in one of your stylesheets. It's a copy of the fa-spin class, but the animation-timing steps are set to 1 instead of 8, for me this fixed the wobble regardless if any padding/margin/font-size is set.

`<style>

.fa-pulse, .fa-spin-pulse {
  -webkit-animation-name: fa-spin;
  animation-name: fa-spin;
  -webkit-animation-direction: var(--fa-animation-direction, normal);
  animation-direction: var(--fa-animation-direction, normal);
  -webkit-animation-duration: var(--fa-animation-duration, 1s);
  animation-duration: var(--fa-animation-duration, 1s);
  -webkit-animation-iteration-count: var(--fa-animation-iteration-count, infinite);
  animation-iteration-count: var(--fa-animation-iteration-count, infinite);
  -webkit-animation-timing-function: var(--fa-animation-timing, steps(1));
  animation-timing-function: var(--fa-animation-timing, steps(1));
}

</style>`

**Comment by tagliala** [comment] 2023-07-21 06:56
> Some have recommended multiples of 14px

Nowadays (FA >=5) is multiples of 16px

> but the animation-timing steps are set to 1 instead of 8, for me this fixed the wobble regardless if any padding/margin/font-size is set.

This is a fix for some use cases. I would like to specify that fonts have a [descender](https://en.wikipedia.org/wiki/Descender) by design, so a perfect spin cannot be guaranteed with the webfont implementation

It is ok to use a workaround specific for a browser or a use case, but please switch to svg if you need perfect spinners
