### ISSUE TITLE
Icon request: Mixcloud [New design since Feb 2020]

### ISSUE THREAD

**Issue by dyrec** [FortAwesome/Font-Awesome#16772] opened 2020-06-07 01:46 UTC
Hi,
Mixcloud updated their branding for their 10th birthday. it would be nice to have new fontawsome brand icons updated as well.

https://blog.mixcloud.com/2020/02/18/mixcloud-is-10/
https://www.studio-output.com/work/mixcloud/

They use the **M-X**  acronym for their app icon. Fontawesome kit with the **M-X** logo would be relevant.

Thanks

**Comment by tagliala** [comment] 2020-06-07 11:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16532, please add a 👍 reaction to that request.

@dyrec actually, #16532 has a "waiting for feedback" label because it is not 100% clear which is their new brand and how it can play well in square-ish format.

Please post there your above comment, so I can remove the "waiting for feeback" label

**Closed by tagliala** 2020-06-07 11:12 UTC
