### ISSUE TITLE
Icon request: Strava logo

### ISSUE THREAD

**Issue by hannahvoelker** [FortAwesome/Font-Awesome#10033] opened 2016-10-07 12:03 UTC
Logo for Strava, the social network for runners and cyclists.

**Comment by tagliala** [comment] 2016-10-07 12:04
Duplicate of #3313, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-07 12:04 UTC
