### ISSUE TITLE
Icon Request: fa-calendar-month/week/day

### ISSUE THREAD

**Issue by trondhuso** [FortAwesome/Font-Awesome#11673] opened 2017-10-26 10:44 UTC
I would like to use the fa-calendar-month to in a dashboard where it will be used to indicate the number next to it is for an entire month. A possible design could be to have the first three letters in the month inside the current calendar-icon.

I would like to use the fa-calendar-week icon in a dashboard where it will be used to indicate the number is for the current week. I could see this being based on the calendar (with grid) and where one week (seven cells) are marked. 

For fa-calendar-day I could see one single cell being marked. this icon is also planned to be used to indicate the number next to it is for this day only. An alternative design to a marked cell, could be to have the current day number inside the calendar...

Thanks for developing the Font Awesome icons. They are ... as the name indicates - awesome. :)

**Comment by tagliala** [comment] 2017-10-26 14:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3609 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-26 14:45 UTC
