### ISSUE TITLE
Icon Request: fa-warranty

### ISSUE THREAD

**Issue by leonardstalder** [FortAwesome/Font-Awesome#5767] opened 2015-02-23 20:54 UTC
an icon to illustrate a warranty

**Comment by tagliala** [comment] 2015-02-26 14:06
any example?

**Comment by leonardstalder** [comment] 2015-02-26 14:11
![Image of Yaktocat](https://cdn2.iconfinder.com/data/icons/badges-2/204/badges06-128.png)

![Image of Yaktocat](https://cdn2.iconfinder.com/data/icons/medicine-5-1/512/sertificate_seal-512.png)

**Comment by tagliala** [comment] 2015-02-26 14:14
ok, so this is a duplicate of #1182 and/or #4420

closing here

**Closed by tagliala** 2015-02-26 14:14 UTC

**Comment by nikid506** [comment] 2020-04-04 19:53
how can I use this icon?  I'm new to github and fontawesome

**Comment by tagliala** [comment] 2020-04-04 20:27
Hi @nikid506 , the "warranty" icon is not available, it is a request

We have a couple of options suitable for this use case:
- https://fontawesome.com/icons/file-certificate?style=solid (FA Pro)
- https://fontawesome.com/icons/award?style=solid

If the above icons do not fit your use case, you can start a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) 

Just make sure to provide an example, because "warranty" is an abstract concept

**Comment by nikid506** [comment] 2020-04-04 20:43
Thank you.  I filled out the form but I’m not sure it uploaded my examples.  I’m very new to this so I have no idea how it works.  What happens next?  Will this new icon have a class assigned to it?  I work for the New Jersey Courts and I design web applications – we have the entire library installed.  How will I be able to hand this off to the technical folks to put on server?  Also, are you employed by font awesome?

Thanks for your help.
