### ISSUE TITLE
Icon Request: fa-package

### ISSUE THREAD

**Issue by GerritP** [FortAwesome/Font-Awesome#11465] opened 2017-08-30 23:55 UTC
Hi there,
a package or a box icon would very well complement the [Transport Section](http://fontawesome.io/icons/#transportation)

![image](https://user-images.githubusercontent.com/31493266/29900003-73d6e7f2-8db4-11e7-997b-987f1c17c123.png)
![image](https://user-images.githubusercontent.com/31493266/29900017-87a4538c-8db4-11e7-9601-acef4ea11e8f.png)

Greetings

**Comment by tagliala** [comment] 2017-08-31 09:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #908 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-31 09:19 UTC
