### ISSUE TITLE
Icon Request: fa-clean-up

### ISSUE THREAD

**Issue by jeff1326** [FortAwesome/Font-Awesome#6775] opened 2015-06-17 19:08 UTC
A brush like https://www.google.ca/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0CAcQjRw&url=http%3A%2F%2Fpixabay.com%2Fen%2Fwipe-clean-besom-broom-brush-icon-97583%2F&ei=isWBVcT6JvfLsASL0pyADw&bvm=bv.96041959,d.cWc&psig=AFQjCNEE9JgEa7EYgxFX8-gGB70OOEsTxw&ust=1434654467417092

**Comment by tagliala** [comment] 2015-06-18 18:25
duplicate of #239 , please +1 that request

closing here

**Closed by tagliala** 2015-06-18 18:25 UTC
