### ISSUE TITLE
Icon request: icon-data collection

### ISSUE THREAD

**Issue by MyIndicators** [FortAwesome/Font-Awesome#11163] opened 2017-06-12 10:56 UTC
Dear FontAwesome, 

I would love to request data collection icons as I unable to find the similar icons. The reason for request it because of it represent the data collection on webapplication. Thank you very much for your consideration. Looking forward to hear from you :)

![screen shot 2017-06-12 at 12 56 09](https://user-images.githubusercontent.com/29200803/27030948-88cfe98a-4f6e-11e7-93e2-26681c161c3c.png)

**Comment by tagliala** [comment] 2017-06-12 11:21
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1179 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-12 11:21 UTC

**Comment by MyIndicators** [comment] 2017-06-16 13:21
Hi thanks, can you teach me how to search it in a correct way? e.g. search find and type the words? May I know how did you able to search the same icons, could you tell me the steps? I was lost in searching the correct icons. Thanks again.

**Comment by tagliala** [comment] 2017-06-16 14:10
@MyIndicators I don't think there is a correct way to search.

You could try for synonyms or look for what the icon exactly represents. If you aren't able to get results, feel free to open a new request because it is easier for me to look for the original request, I often remember the name or the example provided
