### ISSUE TITLE
Icon request: device-rotate

### ISSUE THREAD

**Issue by terryschwarz** [FortAwesome/Font-Awesome#15174] opened 2019-06-18 14:29 UTC
**What can it be used for?**
Indicate rotating screen / device for some purpose. You might also want to consider an additional version called device-shake as some devices react to shaking and not just rotation (for this possibly up/down arrows compared to my curved arrow example for rotate.

**Example image (optional)** 
![image](https://user-images.githubusercontent.com/47600614/59692700-85b64800-91b3-11e9-8ad4-64c55c33eac0.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-06-18 16:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10228, please add a 👍 reaction to that request.

Please also post there your example

Closing here

**Closed by tagliala** 2019-06-18 16:51 UTC

**Comment by terryschwarz** [comment] 2019-06-18 17:29
The actual context we wanted the device-rotate for was rotate axis on a
chart and as such it isn't a duplicate but an alternate icon suggestion
because #10228 (which I will vote for) is clearly a phone device where my
image was much more generic.

So please reconsider as an alt image.
