### ISSUE TITLE
Icon Request: split icon-signal into icon-signal-[1..5]

### ISSUE THREAD

**Issue by eins78** [FortAwesome/Font-Awesome#1870] opened 2013-08-28 19:43 UTC
With the [new icon stacking feature](http://fortawesome.github.io/Font-Awesome/examples/#stacked) some of the icons could be revisited to have optional versions with their single components.

A simple example is signal-icon, which could have 5 single icons with 1 bar each.

I made a quick and dirty version with [IcoMoon](http://icomoon.io), but did not find any info on how to contribute icons. Besides, it is quick and easy to do.

Example code:

``` html
  <span class="icon-stack icon-4x">
    <i class="icon-check-empty icon-stack-base"></i>
    <i class="icon-signal-1"></i>
    <i class="icon-signal-2"></i>
    <i class="icon-signal-3"></i>
  </span>
  icon-signal-[1..3] on icon-sign-blank<br>

  <span class="icon-stack icon-4x">
    <i class="icon-sign-blank icon-stack-base" style="color:#ddd"></i>
    <i class="icon-signal-1"></i>
    <i class="icon-signal-2"></i>
    <i class="icon-signal-3"></i>
    <i class="icon-signal-4 icon-light"></i>
    <i class="icon-signal-5 icon-light"></i>
  </span>
  icon-signal-[1..5] on icon-sign-blank<br>

  <span class="icon-stack icon-4x">
    <i class="icon-sign-blank icon-stack-base" style="color:#ddd"></i>
    <i class="icon-signal-1" style="color:blue"></i>
    <i class="icon-signal-2" style="color:cyan"></i>
    <i class="icon-signal-3" style="color:red"></i>
    <i class="icon-signal-4" style="color:orange"></i>
    <i class="icon-signal-5" style="color:yellow"></i>
  </span>
  icon-signal-[1..5] on icon-sign-blank<br>
```

Example output:
![screen shot 2013-08-28 at 21 41 12](https://f.cloud.github.com/assets/134942/1044872/d867e36e-1019-11e3-815a-a8bc09ba70d1.png)

**Comment by luk156** [comment] 2015-08-05 11:25
+1

**Comment by patelrit** [comment] 2015-09-26 23:11
+1

**Comment by ntvsx193** [comment] 2015-10-12 09:48
+1

**Comment by NaWer** [comment] 2015-10-16 07:04
+1

**Comment by xaume** [comment] 2015-12-05 14:46
+1

**Comment by jgornick** [comment] 2015-12-18 22:19
Instead of stacking, it could follow the battery-X pattern:

signal-1
signal-2
signal-3
signal-4
signal-5

**Comment by jgornick** [comment] 2016-01-04 15:10
@tagliala or @davegandy With the ability to stack, what would be the preferred approach for something like signal level? 

Would it be like #437? Depending on the approach, it may be useful to flag #437 or this issue (#1870) as a duplicate of the other.

**Comment by codynguyen1116** [comment] 2016-01-04 20:37
+1

**Comment by jgornick** [comment] 2016-01-05 15:28
This same pattern could also be applied to the fa-wifi icon (#7856).

**Comment by cnelissen** [comment] 2016-02-12 17:45
+1 for following the same battery-(1-5) pattern. This would be tremendously useful.

**Comment by maisnamraju** [comment] 2016-03-01 05:42
+1

**Comment by humancopy** [comment] 2016-04-26 08:41
+1 for battery pattern

**Comment by lgm42** [comment] 2016-04-26 09:01
+1

**Comment by tagliala** [comment] 2016-04-26 09:39
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-193215139

**Comment by tagliala** [comment] 2016-04-26 09:40
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-143229545

**Comment by tagliala** [comment] 2016-04-26 09:40
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-128319765

**Comment by tagliala** [comment] 2016-04-26 09:40
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-110569718

**Comment by tagliala** [comment] 2016-04-26 09:40
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-73920140

**Comment by tagliala** [comment] 2016-04-26 09:41
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-54964045

**Comment by tagliala** [comment] 2016-04-26 09:41
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-46556663

**Comment by tagliala** [comment] 2016-04-26 09:41
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-43627712

**Comment by tagliala** [comment] 2016-04-26 09:41
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-37681842

**Comment by tagliala** [comment] 2016-04-26 09:41
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-33077263

**Comment by tagliala** [comment] 2016-04-26 09:41
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-29408690

**Comment by tagliala** [comment] 2016-04-26 09:42
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issuecomment-24018264

**Comment by tagliala** [comment] 2016-04-26 09:42
+1 https://github.com/FortAwesome/Font-Awesome/issues/437#issue-6581752

**Comment by betaver** [comment] 2016-06-24 10:15
+1

**Comment by MrEcho** [comment] 2016-07-06 05:23
+1 please

**Comment by Argun** [comment] 2016-07-22 08:33
+1

**Comment by jvvosantos** [comment] 2016-07-28 04:57
+1

**Comment by ashishtilara** [comment] 2016-08-04 00:47
+1

**Comment by khashabawy** [comment] 2016-08-11 08:41
+1

**Comment by kayleighbray** [comment] 2016-08-17 19:04
+1

**Comment by LongPotato** [comment] 2016-08-25 19:25
+1

**Comment by JordanDalton** [comment] 2016-09-10 00:10
+1

**Comment by amitnabarro** [comment] 2016-10-11 14:48
+1

**Comment by pepitooo** [comment] 2016-10-31 14:54
As I need it quickly, I did a ugly workaround, but work for me https://jsfiddle.net/sksxfbk2/
I'm not a web designer, so I hope it will for for you as well

**Comment by JTrotta** [comment] 2016-11-11 16:13
+1

**Comment by ektidey** [comment] 2016-11-29 09:09
+1

**Comment by Hossrod** [comment] 2016-12-12 15:55
+1, especially if following the battery-X pattern someone mentioned above:

signal-1
signal-2
signal-3
signal-4
signal-5

**Comment by bryanhamon** [comment] 2016-12-23 20:37
+1

**Comment by zacwitte** [comment] 2017-01-02 22:31
+1

**Comment by thegruffalo** [comment] 2017-01-17 12:04
+1

**Comment by rotsix** [comment] 2017-02-25 01:04
+1 !

**Comment by akosphp** [comment] 2017-02-25 22:47
+1

**Comment by Tadly** [comment] 2017-03-04 13:03
another big +1 for following the battery-x pattern

signal-1
signal-2
signal-3
signal-4
signal-5

**Comment by commandocoding** [comment] 2017-03-29 01:46
+1

**Comment by UnicodeAlt255** [comment] 2017-03-31 19:54
+1

**Comment by ahmadsyamim** [comment] 2017-04-11 03:55
+1

**Comment by kgillespieanaren** [comment] 2017-04-18 18:06
+1

**Comment by aenany-anaren** [comment] 2017-04-18 18:07
+1

**Comment by dcousens** [comment] 2017-04-27 00:22
+1

**Comment by DavidBerquist** [comment] 2017-05-03 00:31
+1

**Comment by drmikecrowe** [comment] 2017-05-22 13:25
+1

Expanded on @pepitooo hack -- https://jsfiddle.net/b649Lrct/ -- pure CSS solution

**Comment by danield137** [comment] 2017-06-13 13:45
+1

**Comment by gabrielpaim** [comment] 2017-06-19 19:43
+1

**Comment by FlorianFranzen** [comment] 2017-08-08 21:01
To quote the readme:
> At the moment we are not accepting pull requests containing icons

So what else can I do, to make this happen? I feel like it should be trivial to add these alternations if they are based on the ```signal``` or ```wifi``` icon and there is plenty of good reason to add them.

**Comment by raomin** [comment] 2017-08-18 21:14
+1 for signal-X

Until it's done, I truncate the icon where I need, to show the number of bars I want, like this:
```html
#one bar:
                    <i class="fa fa-signal" style="overflow:hidden; width:0.2em"></i>
#two bars:
                    <i class="fa fa-signal" style="overflow:hidden; width:0.4em"></i>
#three bars:
                    <i class="fa fa-signal" style="overflow:hidden; width:0.6em"></i>
etc.
```
You can also stack a grayish full icon under:
```html
<span class="fa-stack fa-lg">
<i class="fa fa-signal fa-stack-1x" style="opacity:.3"></i>
<i class="fa fa-signal fa-stack-1x" style="overflow:hidden; width:0.8em; margin-left:0.5em;"></i>
</span>
```
![image](https://user-images.githubusercontent.com/4460208/29477891-aab14cca-846a-11e7-8169-d8c546a0c1eb.png)

**Comment by azz0r** [comment] 2017-09-23 09:33
+1

**Comment by bchecketts** [comment] 2017-10-05 15:08
+1

**Comment by gb78** [comment] 2017-10-20 17:47
+1 , would be a +2 if possible ;)

I was surprised by not finding this already, I am currently developing a series of IoT monitors with a web interface, and along the sensors data there is also the need to log both battery and wifi status.

**Comment by zkhil1** [comment] 2017-11-29 09:46
+1

**Comment by BioK03** [comment] 2017-12-28 20:40
+1, still waiting for this

**Comment by plie** [comment] 2018-01-07 21:16
+1
I can use this right now in my new app. This would be great.
Thank you!

**Comment by rudevdr** [comment] 2018-01-09 02:06
+1

**Comment by jimmypt** [comment] 2018-02-02 11:38
Yes, please add this icon. 

+1

**Comment by FellipeBr** [comment] 2018-02-15 18:04
+1

**Comment by greenmr** [comment] 2018-03-01 03:23
4 1/2 years later and still no action on this? IoT is HUGE now and these signal level icons are needed for nearly every project. Couldn't find even one icon font library containing these indispensable glyphs so I guess I'll be dusting off Adobe Illustrator and making my own.

**Comment by MrEcho** [comment] 2018-03-01 04:19
It does seem like its some sort of sick joke now...

**Comment by greenmr** [comment] 2018-03-02 06:43
In the next day or so I'll be posting a full set of wifi signal quality and encryption svgs and icon fonts I just created for my own projects. Couldn't find anything anywhere on the web so I built my own in Illustrator. Stay tuned.

**Comment by greenmr** [comment] 2018-03-02 18:59
Ok, for those who are interested, here is a set of wifi signal quality and auth mode icons and fonts you can use free of charge in your projects. I am including both the generated fonts and the svg files used to create them, but not my Illustrator .ai files...

The svg icons:
[wifi-quality-svg.zip](https://github.com/FortAwesome/Font-Awesome/files/1776244/wifi-quality-svg.zip)

The "bars" font:
[wifi-quality-bars.zip](https://github.com/FortAwesome/Font-Awesome/files/1776254/wifi-quality-bars.zip)

The "waves" font:
[wifi-quality-waves.zip](https://github.com/FortAwesome/Font-Awesome/files/1776255/wifi-quality-waves.zip)

Both icon styles combined:
[wifi-quality-full.zip](https://github.com/FortAwesome/Font-Awesome/files/1776256/wifi-quality-full.zip)

Check the "Read Me.txt" file in the font zips for instructions. License info is in all four of the zip files.

The font files are not large, but for IoT you may find them too big for storage on your device flash. If so, I recommend you build your own minimal font with just the icons you use from the svg icons at [icomoon](https://icomoon.io/app).

Hopefully FontAwesome will add something similar soon and these won't be needed for long.

**Comment by Fluepke** [comment] 2018-03-10 18:26
+1 would be nice to use in IoT applications, i3pystatus and NetworkManager CLI

**Comment by nealot** [comment] 2018-03-15 22:34
+1 Hopefully the devs get around to add these soon.

**Comment by roskelld** [comment] 2018-06-04 03:30
This would be great. Maybe my post will achieve full signal strength and make it happen.

**Comment by shaimr** [comment] 2018-06-13 06:06
+1

**Comment by sensibleworld** [comment] 2018-08-29 18:02
https://fontawesome.com/icons?d=gallery&q=signal&v=5.3.0,5.3.1

**Closed by sensibleworld** 2018-08-29 18:02 UTC
Labels: new icon, released, web application icons

**Comment by mbates14** [comment] 2019-01-10 16:09
What makes this even worse, its "pro" only. WTF

**Comment by Baitinq** [comment] 2019-08-03 12:26
Indeed

**Comment by tagliala** [comment] 2019-08-03 13:42
@mbates14 I'm going to remove your comment, because it is against our contributing guidelines

Please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), they contain a lot of information on how requests work

Also, signal 1-5 are implementable with the SVG Framework and Font Awesome 5 Free

Here it is an example: https://jsfiddle.net/tagliala/L17f528g/147/

**Comment by mbates14** [comment] 2019-08-03 20:26
Wow, that only took several months to get recognized.
