### ISSUE TITLE
Icon request: unisex

### ISSUE THREAD

**Issue by seank18465** [FortAwesome/Font-Awesome#17815] opened 2021-04-14 04:42 UTC
**What can it be used for?**
This icon can be used in many places now that there is an increase of non-binary people. Also there are many apparel items that are Unisex.

**Example image (optional)**
Insert the example image here if necessary.
![14064-200](https://user-images.githubusercontent.com/82490956/114655395-24c9ff00-9cba-11eb-99e1-2375966f7730.png)**Icon request checklist**

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-03-18 00:28
Hi @seank18465,

This icon has been added in v6.1.0.
Check https://fontawesome.com/icons/person-half-dress

Regards.

cc/ @tagliala

**Comment by aethior** [comment] 2022-03-18 00:30
Duplicate of #14281.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-18 17:11
Thanks

**Closed by tagliala** 2022-03-18 17:11 UTC
