### ISSUE TITLE
Icon request: thumbtack with slash

### ISSUE THREAD

**Issue by isadoracreative** [FortAwesome/Font-Awesome#19690] opened 2023-04-24 17:05 UTC
If the thumbtack icon (which, IMHO, would be more accurately called a pushpin) represents the user action of pinning something, then a corresponding thumbtack icon with a slash is necessary to unpin something.

![image](https://user-images.githubusercontent.com/10870647/234066582-fb93c384-d57a-43e1-b669-04781fa988c5.png)

![image](https://user-images.githubusercontent.com/10870647/234066613-dfdcaa09-bb4b-4129-81f4-d9b8122c4a2b.png)

**Comment by tagliala** [comment] 2023-04-24 17:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15298, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

---

**In a web application** it is also possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/43/#save

**Heads-up!** Pro customers can also implement this icon with the [Icon Wizard](https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader)

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/556268/234067334-70560b4b-1b4c-44ee-8cdc-59dbbfd6de04.png">

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader

Closing here

**Closed as completed by tagliala** 2023-04-24 17:08 UTC
