### ISSUE TITLE
Icon request: PlayStation and XBOX

### ISSUE THREAD

**Issue by DoronBrayer** [FortAwesome/Font-Awesome#9138] opened 2016-05-07 05:35 UTC
Hello

Please add a PlayStation and XBOX icons, which are very useful for gaming articles/websites.

**Comment by aethior** [comment] 2016-05-12 16:47
Hi @DoronBrayer,

This request is duplicate of #1006. Please +1 that.

Regards.

**Closed** 2016-05-12 17:02 UTC
