### ISSUE TITLE
Icon request: Sensor Device

### ISSUE THREAD

**Issue by Grovkillen** [FortAwesome/Font-Awesome#13263] opened 2018-06-02 19:17 UTC
### What can it be used for?

I'm a member of the team behind [ESP Easy](https://github.com/letscontrolit/ESPEasy) and we would like a sensor device icon which indicate a connected device that will give back values. I've made a icon myself but would like it to be awesomized.

### Example image (optional)

![screenshot_20180602-165214 2](https://user-images.githubusercontent.com/26706274/40880029-42acf066-66aa-11e8-91d0-32b3608217d2.jpg)

### Icon request checklist

- [x ] This is a single icon
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-06-02 20:38
Hi!

Thanks for being part of the Font Awesome Community.

This could be a duplicate of #1399 or #7416

**Comment by Grovkillen** [comment] 2018-06-02 20:40
1399 was exactly what I was trying to find :+1:

**Comment by tagliala** [comment] 2018-06-02 20:47
@Grovkillen thanks

Feel free to add your example in a comment to #1399 and upvote that request

Closing here

**Closed by tagliala** 2018-06-02 20:47 UTC
