### ISSUE TITLE
Icon request: tag-[direction]

### ISSUE THREAD

**Issue by devou33** [FortAwesome/Font-Awesome#15439] opened 2019-08-27 17:08 UTC
**What can it be used for?**
A shape similar to the tag icon (without the hole) that can be used to imply a direction and also be used as a background. I have also seen an icon like this used to indicate vertical position when working through a body of text, like a bookmark.

**Example image (optional)**
<img width="889" alt="Screen Shot 2019-08-27 at 12 02 29 PM" src="https://user-images.githubusercontent.com/7987602/63792405-12236c00-c8c3-11e9-955c-4f5a4e313737.png">

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-08-27 20:00
@devou33 thanks for the suggestion, let's add both 👍

**Comment by sensibleworld** [comment] 2024-07-11 18:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/15875)

**Closed by sensibleworld** 2024-07-11 18:37 UTC
Labels: new icon, arrows (category), shapes (category), Duplicate
