### ISSUE TITLE
Icon request: Thin Plus + and Minus -

### ISSUE THREAD

**Issue by stev3reed** [FortAwesome/Font-Awesome#3874] opened 2014-07-08 16:38 UTC
I love the thinness of this:
![image](https://cloud.githubusercontent.com/assets/7061659/3512877/c214d4be-06bd-11e4-854c-98b551162885.png)

But then we have these thick plus and minus icons:
![image](https://cloud.githubusercontent.com/assets/7061659/3512889/dae2ee7c-06bd-11e4-88e7-9522618bd92a.png)
 
Could we get a thin plus and minus (perhaps even a thin search too)? Having a thin + for iOS designs would be great, even for web use. Usually I have to use another icon font or make my own +, it would be awesome if FontAwesome had one!

When I use the thick + with the icon caret left as a back button, it feels like two different icon sets.

![image](https://cloud.githubusercontent.com/assets/7061659/3513102/c949af50-06bf-11e4-8717-eba97e9cf1bf.png)

**Comment by becevka** [comment] 2015-01-13 18:28
+1

**Comment by vmasto** [comment] 2015-03-09 22:18
+1

**Comment by ddimaria** [comment] 2015-03-15 12:10
+1

**Comment by tagliala** [comment] 2015-11-17 11:28
fff...

I know that they are strictly related and could be merged in one request but this is duplicate of #2161 and #1540 

Sorry, closing here

**Closed by tagliala** 2015-11-17 11:28 UTC
Labels: new icon, web application icons
