### ISSUE TITLE
Icon request: Shopify

### ISSUE THREAD

**Issue by conversiongreen** [FortAwesome/Font-Awesome#5889] opened 2015-03-09 01:20 UTC
![shopify](https://cloud.githubusercontent.com/assets/11382035/6548736/75379914-c64e-11e4-8947-9e8c51aa8d14.png)

**Comment by tagliala** [comment] 2015-03-11 20:36
duplicate of #3850 , please +1 that request

closing here

**Closed by tagliala** 2015-03-11 20:36 UTC
