### ISSUE TITLE
Icon Request: fa-tow-truck

### ISSUE THREAD

**Issue by irisvanvoorden** [FortAwesome/Font-Awesome#10448] opened 2016-12-30 15:10 UTC
We are looking for a towtruck icon. 
![tow-truck](https://cloud.githubusercontent.com/assets/24843345/21567170/3cfca4ca-ceaa-11e6-8b45-bd88edc23993.png).

Thanks in advance.

Kind regards,

Iris van Voorden

**Comment by caduvieira** [comment] 2017-01-13 11:25
Dupe of #4972
Please react to that one and put your example there

**Comment by tagliala** [comment] 2017-01-13 13:45
@caduvieira thanks, also missed this one

**Closed by tagliala** 2017-01-13 13:45 UTC
Labels: new icon, transportation icons, web application icons
