### ISSUE TITLE
Icon request: Parler

### ISSUE THREAD

**Issue by GrocExp** [FortAwesome/Font-Awesome#17794] opened 2021-04-04 15:25 UTC
**What can it be used for?**
I have a TemplateMonster template referencing your library for social media links.  I want to replace Twitter with Parler

**Example image (optional)**
![Parler-Icon](https://user-images.githubusercontent.com/28729736/113513553-4e578d80-9538-11eb-96e3-220598d0a923.gif)
Insert the example image here if necessary.

https://parler.com/profile/FoodHome/posts
**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by pgroot91** [comment] 2021-04-04 15:27
Duplicate of #16275

**Comment by GrocExp** [comment] 2021-04-04 15:49
This thread does not provide a link to the Parler icon.

Please give your search term at fontawesome.com where I can reference the
Parler icon.

Kraig Johnston
*President*
FoodHome.com
p: 888-515-0008  m: 248-636-3223
f: 248-585-0001
a: 1491 w. 14 mile rd., Madison Heights, MI 48071
w: www.FoodHome.com <http://www.foodhome.com/>  e: KJohnston@FoodHome.com
<https://www.facebook.com/FoodHomeDetroit/>
<http://www.hubspot.com/www.linkedin.com/in/kraig-johnston-76b196114>
<http://twitter.com/foodhomedetroit>  [image: YouTube Channel for
FoodHome.com] <http://youtu.be/3gATbfkT2j0>
<https://www.yelp.com/biz/foodhome-com-madison-heights>

**Comment by tagliala** [comment] 2021-04-04 16:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16275, please add a 👍 reaction to that request.

> Please give your search term at fontawesome.com where I can reference the
Parler icon.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-04-04 16:07 UTC
