### ISSUE TITLE
fa-motor-scooter (the motorcycled vehicule)

### ISSUE THREAD

**Issue by martindubenet** [FortAwesome/Font-Awesome#15448] opened 2019-08-28 18:22 UTC
We already have `fa-motorcycle`, I already proposed a [new icon for the (kinda kids toy like) scooter](https://github.com/FortAwesome/Font-Awesome/issues/15447).
Since in English « scooter » refers to two different transport vehicules it seems natural to do both at the same time.

So I propose a new `fa-motor-scooter` to illustrate the **gaz moped** motorcycle vehicule. Here's [a link to an existing example](https://www.shutterstock.com/es/image-vector/classic-scooter-line-icon-moped-linear-1435586558)

**Comment by tagliala** [comment] 2019-08-28 20:40
Hi!

Thanks for being part of the Font Awesome Community.

I think that this request is a duplicate of #6897, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

If it is not a duplicate, feel free to comment

Closing here

**Closed by tagliala** 2019-08-28 20:40 UTC

**Comment by yacineblr** [comment] 2021-11-25 13:57
Any news ?
