### ISSUE TITLE
Icon Request: icon-functional

### ISSUE THREAD

**Issue by namratav2s** [FortAwesome/Font-Awesome#5594] opened 2015-02-05 11:04 UTC
![picture](https://cloud.githubusercontent.com/assets/10864540/6059215/e692f59e-ad54-11e4-90b8-87ebe5000a30.png)

**Comment by tagliala** [comment] 2015-02-05 13:50
duplicate of #2675 , please +1 that request

closing here

**Closed by tagliala** 2015-02-05 13:50 UTC
