### ISSUE TITLE
Icon request:fa-send-out-goods

### ISSUE THREAD

**Issue by SuperCreek** [FortAwesome/Font-Awesome#11832] opened 2017-12-04 03:11 UTC
I need an icon waiting for send out goods, hoping to help make one!
Thanks！
Icon style : 
![image](https://user-images.githubusercontent.com/31737534/33534650-cd73b82e-d8e3-11e7-82c3-17b6891d23a2.png)

**Comment by tagliala** [comment] 2017-12-04 11:57
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this request is a duplicate of #908, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-12-04 11:57 UTC
