### ISSUE TITLE
Icon request: icon-tent

### ISSUE THREAD

**Issue by campkids** [FortAwesome/Font-Awesome#8464] opened 2016-01-30 20:50 UTC
Would it be possible to get a TENT font created? Attaching example for consideration.  Thank you.

![camping5](https://cloud.githubusercontent.com/assets/16978617/12698360/bf95a386-c768-11e5-9b54-0cf6a6cff7ef.png)

**Comment by tagliala** [comment] 2016-01-30 20:58
duplicate of #3859 , please +1 that request

please also search before opening new requests

closing here

**Closed by tagliala** 2016-01-30 20:58 UTC

**Comment by Dr3am3rz** [comment] 2016-02-24 14:38
+1 When will it be done?

**Comment by tagliala** [comment] 2016-02-24 15:32
@Dr3am3rz if you need it in a short while you should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
