### ISSUE TITLE
Icon request: fa-contract or fa-agreement

### ISSUE THREAD

**Issue by schoutenzekerheid** [FortAwesome/Font-Awesome#8821] opened 2016-03-24 10:44 UTC
Hi all,

we need an icon for contracts / agreement etc, like:
![image](https://cloud.githubusercontent.com/assets/17614935/14014869/90a3a79a-f1b5-11e5-9be0-4f38b8a4efd2.png)

**Comment by tagliala** [comment] 2016-03-24 11:59
duplicate of #6430 , please +1 that request

closing here

**Closed by tagliala** 2016-03-24 11:59 UTC
