### ISSUE TITLE
Plant or Flower icon

### ISSUE THREAD

**Issue by marieneig** [FortAwesome/Font-Awesome#5500] opened 2015-01-28 01:45 UTC
To represent vegetation, environment, ecology, agriculture, florist, etc

**Comment by tagliala** [comment] 2015-01-28 14:34
there is already a leaf: http://fontawesome.io/icon/leaf/ and a tree http://fontawesome.io/icon/tree/

let me know if those fits your needs

**Comment by tagliala** [comment] 2015-01-28 14:34
btw flower is a duplicate of #2037

**Comment by marieneig** [comment] 2015-01-29 20:11
perfect thanks I didn't find it through the searches you can delete this

**Closed** 2015-01-29 20:12 UTC
Labels: waiting for feedback
