### ISSUE TITLE
We need Tensorflow and Pytorch icons!

### ISSUE THREAD

**Issue by slf188** [FortAwesome/Font-Awesome#17377] opened 2020-11-07 15:19 UTC
Hey FontAwesome,

Great experience so far using your products, but I would love to see some Tensorflow and Pytorch icons to incorporate into our websites as developers!

Best regards,
Felipe

**Comment by tagliala** [comment] 2020-11-07 15:30
Hi!

Thanks for being part of the Font Awesome Community.

Tensorflow is a duplicate of #15035, please add a 👍 reaction to that request
Pytorch is a duplicate of #15130, please add a 👍 reaction to that request

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-11-07 15:30 UTC
