### ISSUE TITLE
Icon request: sawhorse-bench / sawhorse-desk

### ISSUE THREAD

**Issue by stahlmanDesign** [FortAwesome/Font-Awesome#14204] opened 2018-10-31 18:56 UTC
### What can it be used for?
to indicate construction, or an improvised table/bench/desk sometimes seen in a university dorm room
 
### Example image (optional)
A sawhorse is a foldable construction bench in the form of an upside-down V. It is used to cut boards, or for making a temporary table by placing a sheet of plywood across two sawhorses.
 
### Icon request checklist
* [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
* [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
* [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
* [x]  I have included at least one example image if it could be helpful (optional)
* [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
![capture d ecran 2018-10-31 a 14 53 00](https://user-images.githubusercontent.com/972804/47811673-b2007f80-dd1c-11e8-9ea0-ef70095aa37f.png)

I created the pair of images on the upper right of this collection based on what I think FontAwesome would come close to doing

**Comment by sensibleworld** [comment] 2024-07-11 19:11
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/9495)

**Closed by sensibleworld** 2024-07-11 19:11 UTC
Labels: new icon, web application icons (legacy category), Duplicate
