### ISSUE TITLE
Icon Request: fa-dozer

### ISSUE THREAD

**Issue by Maraud3r** [FortAwesome/Font-Awesome#15269] opened 2019-07-16 12:32 UTC
Would like to see a icon for a side view of a bull dozer.

Would use to represent a property development icon. Construction industry.
<img width="136" alt="Screen Shot 2019-07-16 at 7 31 06 AM" src="https://user-images.githubusercontent.com/23086592/61294581-c6e24d80-a79b-11e9-9d3e-2361746c21e3.png">

**Comment by tagliala** [comment] 2019-07-16 12:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4084, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-07-16 12:39 UTC
