### ISSUE TITLE
Icon Request: fa-googleplus update

### ISSUE THREAD

**Issue by pixxies** [FortAwesome/Font-Awesome#7367] opened 2015-09-02 15:03 UTC
In light of Google's new logotype, the Google+ logo also needs to be updated.

The new Google+ logo looks like this : https://ssl.gstatic.com/images/branding/google_plus/2x/gplus_icon_flatsq_44dp.png (this is the official logo that shows when you scroll down the G+ feed.

**Comment by Gupocca** [comment] 2015-09-02 15:32
Deluxe size:

![google-plus](https://cloud.githubusercontent.com/assets/567038/9635821/0f3711fa-514d-11e5-8666-b79bbbd40546.png)

**Comment by caduvieira** [comment] 2015-09-02 17:32
dupe of #7357

**Comment by Cutcopy** [comment] 2015-09-02 18:42
+1

**Comment by tjeffree** [comment] 2015-09-11 11:10
Not sure if useful for creating the fonts, but here's the SVG from Google's pages:

```
<svg focusable="false" class="svg-icon svg-google-plus" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve"><path fill="none" d="M0 0h24v24H0V0z"></path><path d="M23 11h-2V9h-2v2h-2v2h2v2h2v-2h2M8 11v2.4h4c-.2 1-1.2 3-4 3-2.4 0-4.3-2-4.3-4.4S5.6 7.6 8 7.6c1.4 0 2.3.6 2.8 1.1l1.9-1.8C11.5 5.7 9.9 5 8 5c-3.9 0-7 3.1-7 7s3.1 7 7 7c4 0 6.7-2.8 6.7-6.8 0-.5 0-.8-.1-1.2H8z"></path><path fill="none" d="M1 5h14v14H1z"></path></svg>
```

**Comment by tagliala** [comment] 2015-09-11 11:11
closing as a duplicate of #7357

**Closed by tagliala** 2015-09-11 11:11 UTC
