### ISSUE TITLE
Icon request: icon-GG

### ISSUE THREAD

**Issue by h827539** [FortAwesome/Font-Awesome#11217] opened 2017-06-22 17:12 UTC
I would like to make an icon request for GG (old name: gadu-gadu). It is the most popular Polish instant messaging app and protocol, used by almost all logistics and transport companies.

If the hiperlink on that icon would be gg:_yournumber_, GG on PC would open and conversation with that number would start.

GG website: http://www.gg.pl/

Original logo: ![gg](https://user-images.githubusercontent.com/29635395/27446605-7965f846-577e-11e7-87e9-972a1ec75248.png)

Possible one-colour logo: ![ggszare](https://user-images.githubusercontent.com/29635395/27446617-899e7d00-577e-11e7-8a95-ffdfddb1e629.png)

**Comment by tagliala** [comment] 2017-06-22 18:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5270, please add a 👍  reaction to that request.

I've provided to edit #5270 title to include `icon-gg`

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-22 18:23 UTC
