### ISSUE TITLE
Icon Request: fa-layers

### ISSUE THREAD

**Issue by Zaida-3dO** [FortAwesome/Font-Awesome#11522] opened 2017-09-13 16:42 UTC
![layers-128](https://user-images.githubusercontent.com/21037558/30389520-f615d65a-98aa-11e7-936f-f353dc3dcd2f.png)

**Comment by tagliala** [comment] 2017-09-14 16:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1179, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-14 16:22 UTC
