### ISSUE TITLE
Icon Request: fa-hourglass

### ISSUE THREAD

**Issue by vguenichon** [FortAwesome/Font-Awesome#6077] opened 2015-03-27 16:20 UTC
Well I plan to use it to represent fast timer, short time
![vintage-hourglass_318-85582](https://cloud.githubusercontent.com/assets/1157822/6871830/88458010-d4a5-11e4-9c02-5133a1d27a6f.jpg)

**Comment by tagliala** [comment] 2015-03-28 17:42
duplicate of #492 , please +1 that request

closing here

**Closed by tagliala** 2015-03-28 17:42 UTC
