### ISSUE TITLE
Icon Request: fa-aparat

### ISSUE THREAD

**Issue by miladesign** [FortAwesome/Font-Awesome#12290] opened 2018-02-08 09:06 UTC
Aparat is like youtube service in iran.
http://aparat.com

https://www.aparat.com/public/public/aparat/img/rtl/logo.png

**Comment by tagliala** [comment] 2018-02-08 13:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5204, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-08 13:15 UTC
