### ISSUE TITLE
Icon request: icon-beach

### ISSUE THREAD

**Issue by boxuancui** [FortAwesome/Font-Awesome#10085] opened 2016-10-19 15:26 UTC
Use cases:
- Beach
- Vacation
- Relax

Something like the following:

![beach-512](https://cloud.githubusercontent.com/assets/3045138/19525355/b3ef7610-95ee-11e6-8a83-2498dcb1fc76.png)

**Comment by tagliala** [comment] 2016-10-19 21:58
Duplicate of #3787 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-19 21:58 UTC
