### ISSUE TITLE
Icon request: trustpilot-star

### ISSUE THREAD

**Issue by shmaltz** [FortAwesome/Font-Awesome#16055] opened 2020-01-12 05:22 UTC
I am requesting a Trustpilot star icon. Many websites use Trustpilot for their company reviews, just like Yelp, Google and other review platforms. It can be used to display links to a trustpilot review page.

Link for reference: www.trustpilot.com

**Comment by tagliala** [comment] 2020-01-12 11:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10564, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-12 11:54 UTC

**Comment by shmaltz** [comment] 2020-01-14 19:13
I did search for it, but did not notice it. Thank you!
