### ISSUE TITLE
Icon request: icon-Florida

### ISSUE THREAD

**Issue by BrianPortilo** [FortAwesome/Font-Awesome#6946] opened 2015-07-13 23:07 UTC
Hello I am a web developer from Florida(obviously) and when making a website I always use Font-Awesome. I would like a florida icon to use through out sites that is scalable and reliable as other icons I use from Font-Awesome.

**Comment by peiche** [comment] 2015-07-14 14:31
Dupe of #1304

**Comment by tagliala** [comment] 2015-07-14 16:11
@peiche thanks

I'm going to close this one too.

Also refers to #3992, at the moment this is a wontfix

**Closed by tagliala** 2015-07-14 16:11 UTC
