### ISSUE TITLE
Icon request: billboard

### ISSUE THREAD

**Issue by ordinaryhed** [FortAwesome/Font-Awesome#15645] opened 2019-10-03 05:30 UTC
**What can it be used for?**
Depicting a Billboard, used for advertising along the roads. Could be used as a category for advertising for Out of Home advertising on for example billboards (compare to TV/Radio/Print/Digital/Cinema). 

**Example image (optional)**
http://theneighborhoods.org/sites/the-neighborhoods/files/2019-07/Screen%20Shot%202019-07-18%20at%209.07.59%20AM.png

https://massachusettslandusemonitorboutique.lexblogplatformthree.com/wp-content/uploads/sites/834/2019/01/double-billboards-550x289.jpg

https://christianaidministries.ca/wp-content/uploads/2017/07/BBE.jpg

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-11-09 20:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4599, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-11-09 20:45 UTC
