### ISSUE TITLE
Icon request: fa-duckduckgo

### ISSUE THREAD

**Issue by thomasbnt** [FortAwesome/Font-Awesome#12181] opened 2018-01-29 21:16 UTC
**If you love [DuckDuckGo](https://duckduckgo.com), add this on Font Awesome !** :+1: :duck: 

This is the official package brand logo : 

[DuckDuckGo-Brand-Logo.zip](https://github.com/FortAwesome/Font-Awesome/files/1675257/DuckDuckGo-Brand-Logo.zip)

Or directly on the website  [here](https://duckduckgo.com/press).

![duckduckgo logo stacked](https://user-images.githubusercontent.com/14293805/35534858-0d738096-0542-11e8-8e62-dedc6644ace6.png)

**Comment by tagliala** [comment] 2018-01-30 09:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6731, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-30 09:07 UTC
