### ISSUE TITLE
Does not work in IE 11 in external host

### ISSUE THREAD

**Issue by Antonia5** [FortAwesome/Font-Awesome#5412] opened 2015-01-16 18:48 UTC
Is working perfectly on localhost, but use external host only works in Chrome and FF.
IE11 will not appear on the icons

**Comment by tagliala** [comment] 2015-01-16 19:33
Can you see icons on http://fontawesome.io/ with IE 11 ?

Of course I can't confirm your issue. Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

There might be issues with CORS

Closing here, but feel free to comment

**Closed by tagliala** 2015-01-16 19:33 UTC

**Comment by Antonia5** [comment] 2015-01-16 22:46
If I use internally it works.
The problem is that if I use externally does not work in IE
test in browsers: http://blog.arcasdearte.com/

**Comment by tagliala** [comment] 2015-01-16 23:03
I'm also having issues with firefox.

The problem is probably on the mime types: 
![image](https://cloud.githubusercontent.com/assets/556268/5785835/210abef6-9ddc-11e4-9898-f7247401c60b.png)

(Troubleshooting guide ==> https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up)

My advice here is to load fontawesome from the cdn, I don't know if you have control on mime types there

**Comment by Antonia5** [comment] 2015-01-19 12:52
Share solution:
incorrect
<link href="https://googledrive.com/host/0B3OkiMRv7LXpRTRTS01mLXJVRXc" rel="stylesheet" type='text/css' /> 
correct
<link href="https://googledrive.com/host/0B3OkiMRv7LXpRTRTS01mLXJVRXc" rel="stylesheet"  /> 

remove: type='text/css'

**Comment by tagliala** [comment] 2015-01-19 13:13
thanks for sharing
