### ISSUE TITLE
Icon Request: fa-shower,fa-bath

### ISSUE THREAD

**Issue by muraya** [FortAwesome/Font-Awesome#9527] opened 2016-07-06 16:57 UTC
+1 fa-shower
+1 fa-bath
Please include these icons plus other real estate icons

**Comment by tagliala** [comment] 2016-07-06 17:35
Duplicate of #708 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-06 17:35 UTC

**Comment by muraya** [comment] 2016-07-12 09:00
Thanks for that ... but i realised the icon request has been there from
last year ... why the slow pick up?

On Wed, Jul 6, 2016 at 8:36 PM, Geremia Taglialatela <
notifications@github.com> wrote:

> Closed #9527 <https://github.com/FortAwesome/Font-Awesome/issues/9527>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/9527#event-714669963>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANhZNmVJQCfAfHCBK3Ny-i2gSghQgCaPks5qS-ecgaJpZM4JGSjs>
> .
>



-- 
*Muraya Duncan*
Web | Systems | Graphics
