### ISSUE TITLE
Icon Request: icon-pin-empty

### ISSUE THREAD

**Issue by adamdonahue** [FortAwesome/Font-Awesome#11303] opened 2017-07-18 01:36 UTC
It'd be great to have an empty pin icon, similar to pin but without a solid fill.  This would be useful for allowing a user to toggle between having something pinned or not pinned.

**Comment by adamdonahue** [comment] 2017-07-18 01:40
I guess this PR covers it:  

#4899 

Although looking for an 'open' or 'empty' version of this, really:

![image](https://user-images.githubusercontent.com/2406542/28296812-759ffa68-6b38-11e7-95dc-41bae294625c.png)

Interested in alternative suggestions for a 'toggable' pin.

**Comment by tagliala** [comment] 2017-07-18 08:08
Hi!

Thanks for being part of the Font Awesome Community.

Yes, this is a duplicate of #4899, please +1 that request

Closing here

**Closed by tagliala** 2017-07-18 08:08 UTC

**Comment by ispysoftware** [comment] 2018-02-10 01:33
so this is a duplicate of 4899 which is a duplicate of 11303.. which is a duplicate of 4899... which is a duplicate of 11303...!
