### ISSUE TITLE
Icon request: icon-smoking

### ISSUE THREAD

**Issue by Bangkokmicha** [FortAwesome/Font-Awesome#7949] opened 2015-11-20 15:40 UTC
Dear Community,
i need a smoking icon, like a cigarette for one of my clients. Please help and create a cigarette icon. Thanks a lot dudes

**Comment by tagliala** [comment] 2015-11-20 17:26
duplicate of #726 , please +1 that request

closing here

**Closed by tagliala** 2015-11-20 17:26 UTC
