### ISSUE TITLE
Icon Request: fa-flickr

### ISSUE THREAD

**Issue by yogiee** [FortAwesome/Font-Awesome#6588] opened 2015-05-29 10:37 UTC
Alternative flickr icon without bounding box and just two dots.

Reference: http://www.endlessicons.com/wp-content/uploads/2012/10/flickr-icon-614x460.png

**Comment by TheChen5** [comment] 2015-07-26 00:52
Dupe of #4018
+1 that.
*Search before creating.*

**Comment by tagliala** [comment] 2015-07-26 13:04
@TheChen5 thanks

closing here

**Closed by tagliala** 2015-07-26 13:04 UTC
