### ISSUE TITLE
Icon Request: fa-medical-billing

### ISSUE THREAD

**Issue by fahim159** [FortAwesome/Font-Awesome#11848] opened 2017-12-06 18:43 UTC
Hi Community,

This is to request to issue following icon for web applications

![fa-madical-billing](https://user-images.githubusercontent.com/34315455/33678951-8e96486e-dae7-11e7-9530-d582fe593a20.png)

**Comment by aethior** [comment] 2022-03-19 15:13
Duplicate of #4325.

cc/ @tagliala

**Closed** 2022-03-19 15:37 UTC
