### ISSUE TITLE
Icon request: icon-drone

### ISSUE THREAD

**Issue by dialjam** [FortAwesome/Font-Awesome#11475] opened 2017-08-31 14:53 UTC

**Comment by tagliala** [comment] 2017-08-31 15:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5446 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-31 15:08 UTC

**Comment by jerrywalton** [comment] 2017-12-03 19:25
so where the drone icon?

**Comment by jerrywalton** [comment] 2017-12-03 19:25
how about stop playing games about how many/which request and add the drone icon already.
