### ISSUE TITLE
Icon Request: Shoe icon or running man icon would be great?

### ISSUE THREAD

**Issue by Vrutin** [FortAwesome/Font-Awesome#12792] opened 2018-04-06 12:39 UTC
Similar to 👟🏃‍♂️

**Comment by tagliala** [comment] 2018-04-06 12:45
Hi!

Thanks for being part of the Font Awesome Community.

run is a duplicate of #1156 , please add a 👍  reaction to that request.
running shoe is a duplicate of #3704, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 12:45 UTC
