### ISSUE TITLE
Icon request: theatre-masks

### ISSUE THREAD

**Issue by stirlinghewitt** [FortAwesome/Font-Awesome#13092] opened 2018-05-10 20:55 UTC
### What can it be used for?
Theatre events, our company ATBSS.com build ticket sites and you have all of the sports balls, and a microphone for concerts but nothing that can easily be used for a theatre category.

### Example image (optional)

https://d30y9cdsu7xlg0.cloudfront.net/png/15210-200.png

### Icon request checklist

- [ X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X ] I have included at least one example image if it could be helpful (optional)
- [ X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-05-10 21:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1270 , please add a 👍  reaction to that request.

> [ X ] I have searched for existing issues and to the best of my knowledge this is not a duplicate

No problem 👍 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-10 21:17 UTC
