### ISSUE TITLE
Icon request: code-pull

### ISSUE THREAD

**Issue by saintasia** [FortAwesome/Font-Awesome#13085] opened 2018-05-10 03:42 UTC
Seeing that there already are icons for merge, branch, and commit, it would be great if you could find time to add a pull request icon! The example is below:

<svg width="11" height="16" viewBox="0 0 11 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path id="Shape" fill-rule="evenodd" clip-rule="evenodd" d="M10.1751 1.9167C9.78247 1.52789 9.30602 1.33342 8.74532 1.33342C8.18487 1.33342 7.70842 1.52776 7.31595 1.9167C6.92362 2.30551 6.72739 2.77769 6.72739 3.33335C6.72739 3.69442 6.81834 4.02953 7.00051 4.33856C7.18268 4.64759 7.42781 4.88899 7.73629 5.06249C7.73629 5.42356 7.70661 5.74141 7.64714 6.01566C7.5874 6.28992 7.48948 6.53118 7.35285 6.73959C7.21597 6.94799 7.07431 7.12495 6.92697 7.27083C6.77977 7.41672 6.57295 7.55378 6.30679 7.68228C6.04051 7.81077 5.79344 7.9183 5.56573 8.00524C5.33802 8.09193 5.03135 8.19434 4.64598 8.31235C3.94517 8.52779 3.40562 8.72559 3.02722 8.90625V3.72907C3.33557 3.55557 3.58083 3.31418 3.763 3.00515C3.94517 2.69612 4.03625 2.361 4.03625 1.99994C4.03625 1.4444 3.84015 0.972095 3.44768 0.583283C3.05535 0.19447 2.57889 0 2.01819 0C1.45749 0 0.981034 0.194342 0.588569 0.583283C0.196233 0.972095 0 1.4444 0 1.99994C0 2.361 0.091085 2.69612 0.273255 3.00515C0.455425 3.31418 0.700683 3.55557 1.00903 3.72907V12.2711C0.700683 12.4444 0.455425 12.686 0.273255 12.9949C0.091085 13.304 0 13.6391 0 14.0002C0 14.5556 0.196104 15.0279 0.588569 15.4167C0.981034 15.8055 1.45762 16 2.01819 16C2.57876 16 3.05535 15.8055 3.44768 15.4167C3.84002 15.0279 4.03625 14.5556 4.03625 14.0002C4.03625 13.6391 3.94517 13.304 3.763 12.9949C3.58083 12.686 3.33557 12.4444 3.02722 12.2711V12.0001C3.02722 11.521 3.17262 11.1739 3.46342 10.9586C3.75422 10.7432 4.34808 10.4967 5.24513 10.219C6.1912 9.92028 6.90259 9.63887 7.37904 9.37497C8.94865 8.49314 9.74054 7.05565 9.75448 5.06249C10.0631 4.88899 10.3081 4.64759 10.4903 4.33856C10.6724 4.02953 10.7636 3.69442 10.7636 3.33335C10.7638 2.77782 10.5674 2.30564 10.1751 1.9167V1.9167ZM2.73294 14.7089C2.53671 14.9034 2.29841 15.0005 2.01819 15.0005C1.73784 15.0005 1.49955 14.9034 1.30332 14.7089C1.10721 14.5146 1.00903 14.2784 1.00903 14.0006C1.00903 13.7227 1.10708 13.4867 1.30332 13.2923C1.49955 13.0978 1.73784 13.0006 2.01819 13.0006C2.29841 13.0006 2.53671 13.0979 2.73294 13.2923C2.92917 13.4867 3.02722 13.7227 3.02722 14.0006C3.02722 14.2784 2.92917 14.5146 2.73294 14.7089V14.7089ZM2.73294 2.70829C2.53671 2.90276 2.29841 2.99994 2.01819 2.99994C1.73784 2.99994 1.49955 2.90276 1.30332 2.70829C1.10721 2.51382 1.00903 2.2778 1.00903 1.99997C1.00903 1.72214 1.10708 1.48598 1.30332 1.29164C1.49955 1.0973 1.73784 1 2.01819 1C2.29841 1 2.53671 1.0973 2.73294 1.29164C2.92917 1.48598 3.02722 1.72214 3.02722 1.99997C3.02722 2.2778 2.92917 2.51395 2.73294 2.70829V2.70829ZM9.46022 4.04167C9.26412 4.23601 9.02595 4.33331 8.7456 4.33331C8.46512 4.33331 8.22696 4.23601 8.03086 4.04167C7.83475 3.84733 7.73657 3.61117 7.73657 3.33334C7.73657 3.05551 7.83475 2.81949 8.03086 2.62502C8.22696 2.43055 8.46512 2.33337 8.7456 2.33337C9.02595 2.33337 9.26412 2.43055 9.46022 2.62502C9.65645 2.81936 9.7545 3.05551 9.7545 3.33334C9.7545 3.61117 9.65658 3.84733 9.46022 4.04167V4.04167Z" fill="black"/>
</svg>

**Comment by saintasia** [comment] 2018-05-10 03:42
<svg width="11" height="16" viewBox="0 0 11 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path id="Shape" fill-rule="evenodd" clip-rule="evenodd" d="M10.1751 1.9167C9.78247 1.52789 9.30602 1.33342 8.74532 1.33342C8.18487 1.33342 7.70842 1.52776 7.31595 1.9167C6.92362 2.30551 6.72739 2.77769 6.72739 3.33335C6.72739 3.69442 6.81834 4.02953 7.00051 4.33856C7.18268 4.64759 7.42781 4.88899 7.73629 5.06249C7.73629 5.42356 7.70661 5.74141 7.64714 6.01566C7.5874 6.28992 7.48948 6.53118 7.35285 6.73959C7.21597 6.94799 7.07431 7.12495 6.92697 7.27083C6.77977 7.41672 6.57295 7.55378 6.30679 7.68228C6.04051 7.81077 5.79344 7.9183 5.56573 8.00524C5.33802 8.09193 5.03135 8.19434 4.64598 8.31235C3.94517 8.52779 3.40562 8.72559 3.02722 8.90625V3.72907C3.33557 3.55557 3.58083 3.31418 3.763 3.00515C3.94517 2.69612 4.03625 2.361 4.03625 1.99994C4.03625 1.4444 3.84015 0.972095 3.44768 0.583283C3.05535 0.19447 2.57889 0 2.01819 0C1.45749 0 0.981034 0.194342 0.588569 0.583283C0.196233 0.972095 0 1.4444 0 1.99994C0 2.361 0.091085 2.69612 0.273255 3.00515C0.455425 3.31418 0.700683 3.55557 1.00903 3.72907V12.2711C0.700683 12.4444 0.455425 12.686 0.273255 12.9949C0.091085 13.304 0 13.6391 0 14.0002C0 14.5556 0.196104 15.0279 0.588569 15.4167C0.981034 15.8055 1.45762 16 2.01819 16C2.57876 16 3.05535 15.8055 3.44768 15.4167C3.84002 15.0279 4.03625 14.5556 4.03625 14.0002C4.03625 13.6391 3.94517 13.304 3.763 12.9949C3.58083 12.686 3.33557 12.4444 3.02722 12.2711V12.0001C3.02722 11.521 3.17262 11.1739 3.46342 10.9586C3.75422 10.7432 4.34808 10.4967 5.24513 10.219C6.1912 9.92028 6.90259 9.63887 7.37904 9.37497C8.94865 8.49314 9.74054 7.05565 9.75448 5.06249C10.0631 4.88899 10.3081 4.64759 10.4903 4.33856C10.6724 4.02953 10.7636 3.69442 10.7636 3.33335C10.7638 2.77782 10.5674 2.30564 10.1751 1.9167V1.9167ZM2.73294 14.7089C2.53671 14.9034 2.29841 15.0005 2.01819 15.0005C1.73784 15.0005 1.49955 14.9034 1.30332 14.7089C1.10721 14.5146 1.00903 14.2784 1.00903 14.0006C1.00903 13.7227 1.10708 13.4867 1.30332 13.2923C1.49955 13.0978 1.73784 13.0006 2.01819 13.0006C2.29841 13.0006 2.53671 13.0979 2.73294 13.2923C2.92917 13.4867 3.02722 13.7227 3.02722 14.0006C3.02722 14.2784 2.92917 14.5146 2.73294 14.7089V14.7089ZM2.73294 2.70829C2.53671 2.90276 2.29841 2.99994 2.01819 2.99994C1.73784 2.99994 1.49955 2.90276 1.30332 2.70829C1.10721 2.51382 1.00903 2.2778 1.00903 1.99997C1.00903 1.72214 1.10708 1.48598 1.30332 1.29164C1.49955 1.0973 1.73784 1 2.01819 1C2.29841 1 2.53671 1.0973 2.73294 1.29164C2.92917 1.48598 3.02722 1.72214 3.02722 1.99997C3.02722 2.2778 2.92917 2.51395 2.73294 2.70829V2.70829ZM9.46022 4.04167C9.26412 4.23601 9.02595 4.33331 8.7456 4.33331C8.46512 4.33331 8.22696 4.23601 8.03086 4.04167C7.83475 3.84733 7.73657 3.61117 7.73657 3.33334C7.73657 3.05551 7.83475 2.81949 8.03086 2.62502C8.22696 2.43055 8.46512 2.33337 8.7456 2.33337C9.02595 2.33337 9.26412 2.43055 9.46022 2.62502C9.65645 2.81936 9.7545 3.05551 9.7545 3.33334C9.7545 3.61117 9.65658 3.84733 9.46022 4.04167V4.04167Z" fill="black"/>
</svg>

**Comment by saintasia** [comment] 2018-05-10 03:42
`<svg width="11" height="16" viewBox="0 0 11 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path id="Shape" fill-rule="evenodd" clip-rule="evenodd" d="M10.1751 1.9167C9.78247 1.52789 9.30602 1.33342 8.74532 1.33342C8.18487 1.33342 7.70842 1.52776 7.31595 1.9167C6.92362 2.30551 6.72739 2.77769 6.72739 3.33335C6.72739 3.69442 6.81834 4.02953 7.00051 4.33856C7.18268 4.64759 7.42781 4.88899 7.73629 5.06249C7.73629 5.42356 7.70661 5.74141 7.64714 6.01566C7.5874 6.28992 7.48948 6.53118 7.35285 6.73959C7.21597 6.94799 7.07431 7.12495 6.92697 7.27083C6.77977 7.41672 6.57295 7.55378 6.30679 7.68228C6.04051 7.81077 5.79344 7.9183 5.56573 8.00524C5.33802 8.09193 5.03135 8.19434 4.64598 8.31235C3.94517 8.52779 3.40562 8.72559 3.02722 8.90625V3.72907C3.33557 3.55557 3.58083 3.31418 3.763 3.00515C3.94517 2.69612 4.03625 2.361 4.03625 1.99994C4.03625 1.4444 3.84015 0.972095 3.44768 0.583283C3.05535 0.19447 2.57889 0 2.01819 0C1.45749 0 0.981034 0.194342 0.588569 0.583283C0.196233 0.972095 0 1.4444 0 1.99994C0 2.361 0.091085 2.69612 0.273255 3.00515C0.455425 3.31418 0.700683 3.55557 1.00903 3.72907V12.2711C0.700683 12.4444 0.455425 12.686 0.273255 12.9949C0.091085 13.304 0 13.6391 0 14.0002C0 14.5556 0.196104 15.0279 0.588569 15.4167C0.981034 15.8055 1.45762 16 2.01819 16C2.57876 16 3.05535 15.8055 3.44768 15.4167C3.84002 15.0279 4.03625 14.5556 4.03625 14.0002C4.03625 13.6391 3.94517 13.304 3.763 12.9949C3.58083 12.686 3.33557 12.4444 3.02722 12.2711V12.0001C3.02722 11.521 3.17262 11.1739 3.46342 10.9586C3.75422 10.7432 4.34808 10.4967 5.24513 10.219C6.1912 9.92028 6.90259 9.63887 7.37904 9.37497C8.94865 8.49314 9.74054 7.05565 9.75448 5.06249C10.0631 4.88899 10.3081 4.64759 10.4903 4.33856C10.6724 4.02953 10.7636 3.69442 10.7636 3.33335C10.7638 2.77782 10.5674 2.30564 10.1751 1.9167V1.9167ZM2.73294 14.7089C2.53671 14.9034 2.29841 15.0005 2.01819 15.0005C1.73784 15.0005 1.49955 14.9034 1.30332 14.7089C1.10721 14.5146 1.00903 14.2784 1.00903 14.0006C1.00903 13.7227 1.10708 13.4867 1.30332 13.2923C1.49955 13.0978 1.73784 13.0006 2.01819 13.0006C2.29841 13.0006 2.53671 13.0979 2.73294 13.2923C2.92917 13.4867 3.02722 13.7227 3.02722 14.0006C3.02722 14.2784 2.92917 14.5146 2.73294 14.7089V14.7089ZM2.73294 2.70829C2.53671 2.90276 2.29841 2.99994 2.01819 2.99994C1.73784 2.99994 1.49955 2.90276 1.30332 2.70829C1.10721 2.51382 1.00903 2.2778 1.00903 1.99997C1.00903 1.72214 1.10708 1.48598 1.30332 1.29164C1.49955 1.0973 1.73784 1 2.01819 1C2.29841 1 2.53671 1.0973 2.73294 1.29164C2.92917 1.48598 3.02722 1.72214 3.02722 1.99997C3.02722 2.2778 2.92917 2.51395 2.73294 2.70829V2.70829ZM9.46022 4.04167C9.26412 4.23601 9.02595 4.33331 8.7456 4.33331C8.46512 4.33331 8.22696 4.23601 8.03086 4.04167C7.83475 3.84733 7.73657 3.61117 7.73657 3.33334C7.73657 3.05551 7.83475 2.81949 8.03086 2.62502C8.22696 2.43055 8.46512 2.33337 8.7456 2.33337C9.02595 2.33337 9.26412 2.43055 9.46022 2.62502C9.65645 2.81936 9.7545 3.05551 9.7545 3.33334C9.7545 3.61117 9.65658 3.84733 9.46022 4.04167V4.04167Z" fill="black"/>
</svg>
`

**Comment by tagliala** [comment] 2018-05-10 10:31
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2497, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-10 10:31 UTC

**Comment by saintasia** [comment] 2018-05-11 06:45
Sorry! Couldn't find it when I searched.
