### ISSUE TITLE
Icon Request: icon-tape-measure

### ISSUE THREAD

**Issue by midnightkitty** [FortAwesome/Font-Awesome#12421] opened 2018-02-22 00:50 UTC
I'm building a flooring website for a client - there are many places where a beautiful Font Awesome tape measure icon could be used, most notably on the instructions of how to buy (measure, choose a floor type, get it delivered, & install).

![tape-measure_](https://user-images.githubusercontent.com/30906961/36513930-a2fa5f16-1737-11e8-91dd-581fa8b961b0.png)
![diy-09-tape-measure-512](https://user-images.githubusercontent.com/30906961/36513961-c37024c4-1737-11e8-978f-5f2b840b44be.png)

**Comment by tagliala** [comment] 2018-02-22 10:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8437, please add a 👍  reaction to that request and post your examples there

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-22 10:59 UTC
