### ISSUE TITLE
Icon request: icon-world wide web

### ISSUE THREAD

**Issue by kapilgorve** [FortAwesome/Font-Awesome#8795] opened 2016-03-20 15:39 UTC
I am really surprised to see that there is no icon for WWW( world wide web).Please add this this icon as it is necessary to represent website links.There is a similar globe icon but there should be atleast one icon to represent internet or "World Wide Web".[https://pixabay.com/static/uploads/photo/2014/05/21/19/49/www-350195_640.png ]() [https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/domain.png](url)

**Comment by tagliala** [comment] 2016-03-20 15:45
Duplicate of #6763, please +1 that request

refers to #2655

**Closed by tagliala** 2016-03-20 15:45 UTC
