### ISSUE TITLE
Icon request: Wind turbine

### ISSUE THREAD

**Issue by RvWensen** [FortAwesome/Font-Awesome#13435] opened 2018-06-27 12:33 UTC
in v 5.1.0 there is a solar panel so a wind turbine could be extra icon for alternate energy source

**Comment by tagliala** [comment] 2018-06-27 13:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1300, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-27 13:00 UTC
