### ISSUE TITLE
Icon request: fa-roles

### ISSUE THREAD

**Issue by ruimelodev** [FortAwesome/Font-Awesome#9136] opened 2016-05-06 17:20 UTC
Icon to reference the user roles inside an application.

I thought of something like a scroll:
![script-512](https://cloud.githubusercontent.com/assets/16306125/15080647/20c2bdfc-13b7-11e6-8d4c-8b76a00b28d7.png)

Or a user silhouette with a little gear icon next to it (like fa-user-times and fa-user-plus):
![user_options-512](https://cloud.githubusercontent.com/assets/16306125/15080648/20d24fce-13b7-11e6-810d-3890b9de541e.png)

**Comment by tagliala** [comment] 2016-05-06 17:47
Duplicate of 

Scroll: #1173
User with cog: #2553

please +1 the proper request

closing here

**Closed by tagliala** 2016-05-06 17:47 UTC
