### ISSUE TITLE
Icon Request: fa-pullrequest or fa-mergerequest

### ISSUE THREAD

**Issue by lianguan** [FortAwesome/Font-Awesome#8164] opened 2015-12-17 08:55 UTC
![image](https://cloud.githubusercontent.com/assets/15666864/11865411/d7fc2708-a4de-11e5-9c2e-1d86ebbd0e89.png)

**Comment by phecho** [comment] 2015-12-18 08:49
Is there anyone who supports my request?

**Comment by SatanicGeek** [comment] 2015-12-18 09:58
+1

**Comment by caduvieira** [comment] 2015-12-18 13:31
dupe of https://github.com/FortAwesome/Font-Awesome/issues/3743

please +1 that issue

**Comment by aethior** [comment] 2022-03-12 16:13
Hi @lianguan,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/code-pull-request

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-12 17:45
Duplicate of #3743

**Closed by tagliala** 2022-03-12 17:45 UTC
