### ISSUE TITLE
Icon Request: fa-cricket-bat

### ISSUE THREAD

**Issue by Jeyanthinath** [FortAwesome/Font-Awesome#7199] opened 2015-08-11 11:15 UTC
![bat](https://cloud.githubusercontent.com/assets/2253649/9196365/41be1ca6-4048-11e5-86ad-ad49145a54aa.jpg)

**Comment by TheChen5** [comment] 2015-08-11 19:49
Dupe of #5706
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-15 09:30
@TheChen5 thanks

closing here

**Closed by tagliala** 2015-08-15 09:30 UTC
