### ISSUE TITLE
Greek alphabet

### ISSUE THREAD

**Issue by simon88** [FortAwesome/Font-Awesome#10459] opened 2017-01-03 10:29 UTC
Hi,

I think Greek alphabet would be useful, especially for mathematics. Or at least the most used letters like Pi, Ohm, etc.

What do you think of it?

**Comment by Crissov** [comment] 2017-01-16 22:53
Letters should be handled by a real font.

**Comment by tagliala** [comment] 2017-01-17 12:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of  #2828, which is labeled as wontfix. You can read more information on that thread

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-17 12:56 UTC
