### ISSUE TITLE
Icon request: skip

### ISSUE THREAD

**Issue by steyo** [FortAwesome/Font-Awesome#18354] opened 2021-10-13 13:27 UTC
**What can it be used for?**
The icon can be used whenever a user wants to indicate to an application to skip over a current/default state/action etc.

**Example image (optional)**

Typically the default 'thing' is represented by a dot and then an arrow can be used to represent skipping over or otherwise taking an alternative route.

![image](https://user-images.githubusercontent.com/18593750/137141349-7d0b6d82-be75-4e96-8b8b-7ae856289f79.png)
![image](https://user-images.githubusercontent.com/18593750/137141817-11fb31b5-c5cd-4ddb-9a12-f63ae66eee01.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-10-13 14:43
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #5673, which was closed by the original author

I've reopened it because it had 9 upvotes, please upvote that request

If the original request will be closed again, I will reopen this one

**Closed by tagliala** 2021-10-13 14:43 UTC

**Comment by steyo** [comment] 2021-10-13 14:58
Hi,


Thanks for reopening the similar issue. I hadn't found it as I didn't look for 'jump' but 'skip'.


Anyway, if I can contribute by helping adding icons I wouldn't mind that either if you could point me in the right direction (for compatible tools). I'm familiar with vector graphics and such but not with icon design.


Kind regards,

Derrick Pluim
[1596013965830]

Keizerschild 7
8253 BH  DRONTEN
tel  +31 (0)321 - 311 973
fax  +31 (0)321 - 325 626
https://www.steyo.com


________________________________
