### ISSUE TITLE
Icon request: buy-order

### ISSUE THREAD

**Issue by paulor1c4rd0** [FortAwesome/Font-Awesome#9417] opened 2016-06-19 16:40 UTC
I want a icon to represent a buy order. The customers of the website cannot buy directly, they'll have to fill an order. 

But i didn't find any icon like this. My idea is something like this:
![images](https://cloud.githubusercontent.com/assets/20029183/16178593/299f0a78-3623-11e6-99d6-c903c2e3b0f4.png)
![untitled-21-512](https://cloud.githubusercontent.com/assets/20029183/16178598/4f0c0590-3623-11e6-95e5-553557dbb6e9.png)

**Comment by tagliala** [comment] 2016-06-19 17:47
Duplicate of ##773, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-19 17:47 UTC
