### ISSUE TITLE
Icon request: cursor-drag

### ISSUE THREAD

**Issue by SaroGFX** [FortAwesome/Font-Awesome#20235] opened 2024-05-28 15:31 UTC
Looking for this drag cursor hand.

![Screenshot 2024-05-28 at 17 31 23](https://github.com/FortAwesome/Font-Awesome/assets/3781800/12f2fc2c-6ecb-462e-8428-4e035637fb0c)

**Comment by jabronus** [comment] 2024-07-12 15:40
Thanks for requesting an icon! But this is actually a duplicate of #17229, so I'm closing this one.

**Closed as not planned by jabronus** 2024-07-12 15:40 UTC
Labels: new icon
