### ISSUE TITLE
Icon request: icon-Alexa

### ISSUE THREAD

**Issue by elizabethbarr** [FortAwesome/Font-Awesome#12807] opened 2018-04-09 00:56 UTC
Hi FontAwesome folks, 

Any plans for an Alexa icon? There are now more than 30,000 Alexa skills, many of them belonging to big brands, so they'll be wanting to link to their skills page from their websites. And devs will be wanting to link to their Alexa page (in addition to GitHub, Dribbble, Twitter, etc.)

Thanks!

This may help:
https://developer.amazon.com/docs/alexa-voice-service/logo-and-brand.html

**Comment by tagliala** [comment] 2018-04-09 07:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #alexa, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-09 07:52 UTC

**Comment by damianfok** [comment] 2019-03-22 10:39
+1
