### ISSUE TITLE
Icon Request: fa-check

### ISSUE THREAD

**Issue by Slantsixx** [FortAwesome/Font-Awesome#11665] opened 2017-10-24 07:15 UTC
It would be great to have an icon for checks to go along with the credit cards on payment pages to indicate all accepted payment methods when paying in person.

![iu](https://user-images.githubusercontent.com/32253216/31929264-98a4c558-b858-11e7-8a91-94bc23e3af84.png)

**Comment by tagliala** [comment] 2017-10-24 10:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2603 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-24 10:54 UTC
