### ISSUE TITLE
Icon Request:fa-web

### ISSUE THREAD

**Issue by Yannick86** [FortAwesome/Font-Awesome#7886] opened 2015-11-14 18:06 UTC
At the moment you do not have an icon resembling a website, webpage, WWW, url, ...
You do have icons for Internet Explorer for example, but this is not the same.

An example would be;

![image](https://cloud.githubusercontent.com/assets/11870681/11165022/d2d07770-8b02-11e5-91d8-c8bee003d224.png)

Kind regards,

Yannick

**Comment by SamBrishes** [comment] 2015-11-14 18:28
Such an icon does already exist:
http://fontawesome.io/icon/globe/

**Comment by tagliala** [comment] 2015-11-14 23:29
duplicate of #2655, please +1 that request or consider `fa-globe`

closing here

**Closed by tagliala** 2015-11-14 23:29 UTC
