### ISSUE TITLE
Icon request: icon-quantity

### ISSUE THREAD

**Issue by ShockRaver** [FortAwesome/Font-Awesome#6311] opened 2015-04-24 14:24 UTC
Hi guys,

i like to request an icon for use in shoppingcarts for the quantity.
![icon-quantity](https://cloud.githubusercontent.com/assets/12100526/7320666/511ae0ee-ea9e-11e4-9d94-607c8fdbaaa9.png)

**Comment by tagliala** [comment] 2015-04-25 12:42
I suppose this is a duplicate of #1179 , please +1 that   request

closing here

**Closed by tagliala** 2015-04-25 12:42 UTC
