### ISSUE TITLE
Icon Request: fa-coffee-papper

### ISSUE THREAD

**Issue by Programazing** [FortAwesome/Font-Awesome#12099] opened 2018-01-14 14:45 UTC
I'm sure the name could be better but I'd love to see a [paper coffee cup](https://www.google.com/search?q=paper+coffee+cup&client=firefox-b-1-ab&tbm=isch&source=lnt&tbs=isz:i&sa=X&ved=0ahUKEwi11tGe19fYAhUr4YMKHQS7C98QpwUIIA&biw=1600&bih=767&dpr=1) like you'd get in a coffee shop.

**Comment by tagliala** [comment] 2018-01-14 14:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3068, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-14 14:54 UTC
