### ISSUE TITLE
Icon request: Python icon

### ISSUE THREAD

**Issue by davidmpaz** [FortAwesome/Font-Awesome#11098] opened 2017-05-21 10:23 UTC
Hi FA,

Please could you add the snake python icon?

thanks for such a great project

**Comment by tagliala** [comment] 2017-05-21 10:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3016, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-21 10:53 UTC

**Comment by davidmpaz** [comment] 2017-05-22 06:05
Oops,

Sorry. I did, but obviously did not search properly. Thanks!! 

Reaction added.

Cheers
