### ISSUE TITLE
Why the width is 2em when I set `fa-fw`?

### ISSUE THREAD

**Issue by hiyangguo** [FortAwesome/Font-Awesome#14223] opened 2018-11-05 04:34 UTC
I found when I set `fa-fw` , It will change the widh to `2em`:

[_variables.less#11](https://github.com/FortAwesome/Font-Awesome/blob/master/web-fonts-with-css/less/_variables.less#L11)

```
@fa-li-width:         2em;
```

But in the old version (eg:[4.7.0 variables.less#L12](https://github.com/FortAwesome/Font-Awesome/blob/v4.7.0/less/variables.less#L12)), the value is `30em / 14`
```
@fa-li-width:         (30em / 14);
``` 

So I want know, how did you defined this value?

**Comment by tagliala** [comment] 2018-11-05 11:00
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome use icons with different width by design, so you can't align `envelope` and `key` without having an helper class as `fa-fw`

In FA 4, 30em/14 was supposed to be "large enough" to work with every icon in the set

In FA5 we are using a different grid system and 2em is a good value 

Example: https://jsfiddle.net/tagliala/0apjghcr/19/

Hope it helps

Closing here

**Closed by tagliala** 2018-11-05 11:00 UTC
Labels: question

**Comment by hiyangguo** [comment] 2018-11-06 03:13
OK, Thanks for your answer very much.
