### ISSUE TITLE
Icon Request: fa-firefox and fa-chrome

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7015] opened 2015-07-23 01:09 UTC
Request for most popular browser icons.

fa-firefox icon:

![Firefox](http://i.imgur.com/iD2kDKr.png)
Source: http://plainicon.com/download-icon/50215/firefox

fa-chrome icon:
![Chrome](http://i.imgur.com/F3J92fw.png)
Source: http://findicons.com/icon/80504/chrome

**Comment by tagliala** [comment] 2015-07-23 07:58
duplicate of #219 , please +1 that request

closing here

**Closed by tagliala** 2015-07-23 07:58 UTC

**Comment by tuxy** [comment] 2015-07-24 04:20
@tagliala, done. Thank You!
