### ISSUE TITLE
Icon request: Capacity

### ISSUE THREAD

**Issue by Minikibber** [FortAwesome/Font-Awesome#10422] opened 2016-12-22 11:50 UTC
Capacity on a production line.
![520950-waight_machine-512](https://cloud.githubusercontent.com/assets/24714037/21424765/262dbfec-c845-11e6-989b-4ac37c67d06e.png)

**Comment by tagliala** [comment] 2016-12-22 13:42
Duplicate of #7797, please add a 👍  reaction to that request and post there your example

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-22 13:42 UTC
