### ISSUE TITLE
Icon Request: fa-cd-rom

### ISSUE THREAD

**Issue by Adsidera** [FortAwesome/Font-Awesome#9603] opened 2016-07-20 14:41 UTC
Hello, 
I was developing a webpage for a classical musician, who recorded some CDs and DVDs. In your icons, I tried to look for an icon representing a CD-Rom or a DVD-rom and I could not find any icon resembling a CD-ROM.
Such an icon could help developers like me who have to do with musical promotion. 

Thank you in advance, 
Anna Costalonga

**Comment by aethior** [comment] 2016-07-20 19:56
Duplicate of #702. Please :+1: that.

**Closed** 2016-07-20 21:23 UTC
