### ISSUE TITLE
Icon Request: fa-tenge

### ISSUE THREAD

**Issue by Max95Cohen** [FortAwesome/Font-Awesome#11618] opened 2017-10-13 11:36 UTC
Hello, FontAwesome team!

Please add a Kazakhstan currency icon, e.g. tenge. You can find info in this link:

https://unicode-table.com/ru/20B8/

Thanks.

**Comment by PeterShaggyNoble** [comment] 2017-10-13 11:52
Duplicate of #2378 - you should give that a 👍 instead.

**Closed** 2017-10-13 11:55 UTC
