### ISSUE TITLE
NEW ICON: horse, dog , cat

### ISSUE THREAD

**Issue by somethingworks** [FortAwesome/Font-Awesome#5688] opened 2015-02-16 14:56 UTC
Hey all,

a few icons for (domestic) animals would be great.
Dog, cat, horse, bird etc.

I know there are a few topics requesting this but not much seems to happen there.
So therefor this new topic.

Please +1
or
Let me know how to make them myself ;-)

I am using Ninja Kick: Sliding Panel which uses Font Awesome and no custom pictures...
Hope you guys can help.

Thanx!!!

**Comment by kkirsche** [comment] 2015-02-17 20:07
Per [CONTRIBUTING.md](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md) — Please title your new issue Icon request: `icon-name` (e.g., Icon request: `icon-car`).

**Comment by tagliala** [comment] 2015-02-22 00:33
@kkirsche thanks again

horse is a duplicate of #280 , please +1 that request
dog is a duplicate of #4755 , please +1 that request
cat is a duplicate of #2226, please +1 that request

Please also open individual requests for each icon and try to avoid the "etc." word

all dups, closing here

**Closed by tagliala** 2015-02-22 00:33 UTC
