### ISSUE TITLE
Icon request: fa-select

### ISSUE THREAD

**Issue by MightyFo0l** [FortAwesome/Font-Awesome#8551] opened 2016-02-12 15:34 UTC
For use in applications that give you the option to select objects (or any other kind of stuff). 
I plan to use it in my drawing application. 
Similar buttons already exist in Adobe programs like Photoshop.

![iconmonstr-selection-1 1](https://cloud.githubusercontent.com/assets/16845714/13011235/20614c0a-d1a6-11e5-9cb0-b5dc39a1dba4.png)

(More cool examples: http://iconmonstr.com/?s=select)

**Comment by tagliala** [comment] 2016-02-12 17:21
Duplicate of #8402, please +1 that request

closing here

**Closed by tagliala** 2016-02-12 17:21 UTC

**Comment by MightyFo0l** [comment] 2016-02-12 17:23
It's not the same at all though
