### ISSUE TITLE
Icon Request: fa-repair

### ISSUE THREAD

**Issue by densenator** [FortAwesome/Font-Awesome#8971] opened 2016-04-13 14:04 UTC
I want to see icon repair, like this
![screwdriver-wrench_318-27835](https://cloud.githubusercontent.com/assets/18443709/14495819/56ce769e-0191-11e6-9d97-f7ff76a226b0.jpg)

**Comment by PeterShaggyNoble** [comment] 2016-04-13 14:10
Dupe of [#736](https://github.com/FortAwesome/Font-Awesome/issues/736), you should +1 that.

**Closed** 2016-04-13 17:19 UTC
