### ISSUE TITLE
Brand request: Link by Stripe

### ISSUE THREAD

**Issue by jmp-12** [FortAwesome/Font-Awesome#20194] opened 2024-04-13 17:43 UTC
### Description

[Link](https://link.com) is a product built by Stripe that allows folks to save their payment information for ecommerce checkouts.
Additional info can be found here: [What is Link?](https://docs.stripe.com/payments/link/what-is-link).

Font Awesome currently supports the following [Stripe Icons](https://fontawesome.com/search?q=stripe&o=r&f=brands):
![image](https://github.com/FortAwesome/Font-Awesome/assets/15693673/d60e8cd2-fbb9-4624-bf4b-f4d873ce5ecc)

No icons relevant to Link were found via [Font Awesome search](https://fontawesome.com/search?q=link&o=r&f=brands) or [issues search](https://github.com/FortAwesome/Font-Awesome/issues?q=label%3A%22new+icon%22+link+in%3Atitle+is%3Aopen). 

I think Link would be a good addition to the existing payment gateway icons (i.e. Google Pay, Apple Pay, etc.).

The icon in question would be their logo which is rendered on their official site as an SVG already:
![image](https://github.com/FortAwesome/Font-Awesome/assets/15693673/aa5b67ac-5cd5-4d11-b331-b7107d9131e4)

### Official website

https://link.com/

### Brand guidelines

Unfortunately, I could only find brand guidelines for [Stripe itself](https://stripe.com/newsroom/information), not Link.

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2024-04-13 18:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19978, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-04-13 18:03 UTC
Labels: brand icon
