### ISSUE TITLE
Icon Request: fa-sandwich

### ISSUE THREAD

**Issue by sdf1992** [FortAwesome/Font-Awesome#11783] opened 2017-11-21 17:53 UTC
Hello i need a sandwich icon for my website

**Comment by sdf1992** [comment] 2017-12-06 18:16
i post you my handmade icone
![paninio](https://user-images.githubusercontent.com/33875709/33677718-f91f9330-dab9-11e7-9949-d320a72749f8.jpg)

**Comment by tagliala** [comment] 2017-12-06 18:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9874, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-12-06 18:34 UTC
