### ISSUE TITLE
Icon Request: fa-skiing

### ISSUE THREAD

**Issue by lukerwigley** [FortAwesome/Font-Awesome#9364] opened 2016-06-07 15:42 UTC
Please can you make a skiing icon

**Comment by tagliala** [comment] 2016-06-07 18:03
I'm going to consider this a duplicate of #6878, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-07 18:03 UTC

**Comment by futureweb** [comment] 2018-03-16 16:35
+1
