### ISSUE TITLE
blackberry Icon

### ISSUE THREAD

**Issue by developerajain** [FortAwesome/Font-Awesome#9572] opened 2016-07-14 11:47 UTC
I love font-awesome because i can find every icon on fontawesome but i need one more icon of blackberry.

**Comment by tagliala** [comment] 2016-07-14 11:53
Duplicate of #1537 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-14 11:53 UTC
