### ISSUE TITLE
Icon Request: fa-container: node, container, app, hexagon, cube

### ISSUE THREAD

**Issue by arzynik** [FortAwesome/Font-Awesome#7655] opened 2015-10-11 00:07 UTC
![image](https://cloud.githubusercontent.com/assets/27974/10413886/028b9218-6f71-11e5-927a-47999e68b6eb.png)

hopefully with a bit of rounded corner love

a fa-container-o would also be appreciated, possibly named fa-cube with its wireframe lines

**Comment by tagliala** [comment] 2015-10-11 16:20
duplicate of #1302 , please +1 that request

closing here

**Closed by tagliala** 2015-10-11 16:20 UTC
