### ISSUE TITLE
Icon request: calender-monthly

### ISSUE THREAD

**Issue by vickyindiar** [FortAwesome/Font-Awesome#10538] opened 2017-01-20 04:44 UTC
Can you add a specific calendar icon with a number inside. 
like :
calender-mothly: number "31" inside
calender-weekly: number "7" inside
calender-daily: number "1" inside
best regards,
![calender-week](https://cloud.githubusercontent.com/assets/24713484/22136198/9ef77630-df05-11e6-8cc0-4f10cb51d45a.jpg)

**Comment by tagliala** [comment] 2017-01-20 09:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3609, please add a 👍  reaction to that request.

If you need to stack number with icons, please take a look at this blog post: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-20 09:52 UTC
