### ISSUE TITLE
Icon Request: fa-sewing-machine

### ISSUE THREAD

**Issue by Milaap** [FortAwesome/Font-Awesome#6691] opened 2015-06-09 09:18 UTC
We are looking for an icon of sewing machine. "Small businesses" in rural India is one of the major causes we support, and sewing is one such small business. Here is one idea for the icon:

![image](https://cloud.githubusercontent.com/assets/417503/8054422/33e1006c-0eb6-11e5-83c0-c6bb1ab97ec9.png)

It will be great if font-awesome can provide an icon for this.

Thanks!

**Comment by tagliala** [comment] 2015-06-30 16:50
duplicate of #4598, please +1 that request

closing here

**Closed by tagliala** 2015-06-30 16:50 UTC
