### ISSUE TITLE
Icon Request: fa-icon-heli

### ISSUE THREAD

**Issue by ncd200** [FortAwesome/Font-Awesome#11485] opened 2017-09-03 10:29 UTC
Starting a website for a helicopter business and need a helicopter icon for this project.

![helicopter-icon-7](https://user-images.githubusercontent.com/31587626/30002198-8f2e6132-90a3-11e7-9f95-ca0d78c78d3a.png)

**Comment by tagliala** [comment] 2017-09-03 11:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2007, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-03 11:17 UTC
