### ISSUE TITLE
Icon Request: fa-line

### ISSUE THREAD

**Issue by vencaPPL** [FortAwesome/Font-Awesome#11222] opened 2017-06-24 14:56 UTC
Hi,

I would like to request a new icon representing LINE messenger. This messenger is massively popular in several Asian countries (Japan, Korea, Thailand, ...).

Here are some examples on google:
https://www.google.co.th/search?q=line+messenger&safe=active&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjmyMiX3tbUAhVJRY8KHRERClEQ_AUICigB&biw=1920&bih=970
![line](https://user-images.githubusercontent.com/8980588/27509480-fb9f5ef6-5927-11e7-8772-423e95c13afb.png)

**Comment by tagliala** [comment] 2017-06-24 15:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2631 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-24 15:34 UTC
