### ISSUE TITLE
Icon Request: Set operations

### ISSUE THREAD

**Issue by iuliux** [FortAwesome/Font-Awesome#11196] opened 2017-06-19 12:17 UTC
Operations like intersection, subtraction, union are applicable in many scenarios.
The most iconic use is in selections (be it in a visual environment or in a dataset etc.). They also can be symbols for "Include"/"Exclude" in any context.

My current use case is for combining filters in a search.

From Photoshop interface:
<img width="73" alt="screen shot 2017-06-19 at 3 19 15 pm" src="https://user-images.githubusercontent.com/1446677/27284681-731d0872-5502-11e7-93b4-77b18a6c3ffd.png">

Other example:
![set-operations-illustrated-with-venn-diagrams](https://user-images.githubusercontent.com/1446677/27284590-10520062-5502-11e7-8564-bcdd50094b43.png)

**Comment by tagliala** [comment] 2019-03-13 17:33
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I've missed this request.

This is a duplicate of #2164, please add a 👍 reaction to that request

**Closed by tagliala** 2019-03-13 17:33 UTC
