### ISSUE TITLE
Icon Request: fa-comedy, fa-drama

### ISSUE THREAD

**Issue by wpaflightpath** [FortAwesome/Font-Awesome#6776] opened 2015-06-17 21:41 UTC
A simple icon for the two masks that depict comedy and drama in theater.

I found a quick example of a simpler version of the two masks, not perfect but also not as detailed as some others out there
https://s-media-cache-ak0.pinimg.com/736x/e7/21/68/e72168a7122f85d6583ef6ba0364c5a6.jpg

Maybe have one version filled in and one version just outlines too?

**Comment by jlr7245** [comment] 2015-06-25 21:00
+1

**Comment by tagliala** [comment] 2015-07-01 10:37
duplicate of #1270 , please +1 that request

closing here

**Closed by tagliala** 2015-07-01 10:37 UTC
