### ISSUE TITLE
Icon request: protonmail

### ISSUE THREAD

**Issue by gwendolyngoetz** [FortAwesome/Font-Awesome#17503] opened 2020-12-22 00:05 UTC
**What can it be used for?**

This would be for a single brand icon for ProtonMail (https://protonmail.com) using their email/lock logo. It would just represent their service like the twitter or facebook icons do.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/195162/102833442-f7bdad80-43a5-11eb-82df-24378a35e1f1.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-12-22 08:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11246, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-12-22 08:14 UTC
