### ISSUE TITLE
Icon Request: the stamp logo

### ISSUE THREAD

**Issue by VolinHe** [FortAwesome/Font-Awesome#18184] opened 2021-08-19 09:11 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
Show stamped logo
**Example image (optional)**
Insert the example image here if necessary.
![企业微信截图_16293464381942](https://user-images.githubusercontent.com/24776882/130042187-b76e26c0-2191-4cb1-982a-9de25ed5f1e3.png)
![企业微信截图_16293464298925](https://user-images.githubusercontent.com/24776882/130042222-165cf01f-ce04-447a-85ab-f5a025fe2ada.png)
![企业微信截图_16293464622223](https://user-images.githubusercontent.com/24776882/130042235-ad93707d-2073-4416-8610-836d540104c2.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-03-10 11:38
Hi @VolinHe,

This request is duplicate of #1886. The icon was added in v5.1.0.
Check https://fontawesome.com/icons/stamp

Regards.

cc/ @tagliala

**Closed** 2022-03-10 11:39 UTC
