### ISSUE TITLE
Icon Request: fa-user-minus

### ISSUE THREAD

**Issue by dheil** [FortAwesome/Font-Awesome#10386] opened 2016-12-16 10:01 UTC
The idea is simple: an icon just like "user-plus" and "user-times" - just with a "minus"-symbol on the side.

**Comment by tagliala** [comment] 2016-12-16 10:12
Duplicate of #2893, please add a 👍  reaction to that request

Closing here

**Closed by tagliala** 2016-12-16 10:12 UTC
