### ISSUE TITLE
Icon request: stellar

### ISSUE THREAD

**Issue by oauo** [FortAwesome/Font-Awesome#17513] opened 2020-12-28 14:22 UTC
**What can it be used for?**  
[Stellar](https://www.stellar.org/) is a proof of stake crypto which is far easier, cheaper, and faster to implement into a website unlike bitcoin and ethereum, who both have icons.  
There is a need for an icon for a good crypto to be used in price selections and billing.

**Example image (optional)**  

![Stellar logo](https://assets-global.website-files.com/5deac75ecad2173c2ccccbc7/5dec8960504967fd31147f62_Stellar_lockup_black_RGB.svg)

**Icon request checklist**  
- [×] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ×] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [× ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [× ] I have included at least one example image if it could be helpful (optional)
- [× ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-12-28 14:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15817, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-12-28 14:57 UTC

**Comment by oauo** [comment] 2020-12-28 15:14
Ah, well the link on the site to search for icons should be changed.

Search for icon that doesn't exist > "Make an icon request" > "existing requests" > search bar has `is:open` by default

**Comment by oauo** [comment] 2020-12-28 15:16
Oh nvm, but I definitely already searched "stellar", "lumen", "lumens", "stellar lumens", "xlm" and got 0 results for all of them.

**Comment by tagliala** [comment] 2020-12-28 15:25
Oh, that happens. I will add lumen  and xlm to the #15817's title to improve search
