### ISSUE TITLE
Icon Request: fa-tree-palm

### ISSUE THREAD

**Issue by miketedeschi** [FortAwesome/Font-Awesome#12353] opened 2018-02-14 05:33 UTC
I see the new deciduous tree (alt) but I think a palm tree would be cool.  I want to use the evergreen to represent temperate cold, the alt tree to represent temperate warmer, and the palm tree to represent tropic and subtropic temperature zones. I'll be purchasing either way soon. Thanks!

**Comment by tagliala** [comment] 2018-02-14 10:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7640, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-14 10:16 UTC
