### ISSUE TITLE
Icon request: dialpad on phone

### ISSUE THREAD

**Issue by savinayd** [FortAwesome/Font-Awesome#15059] opened 2019-05-24 06:43 UTC

**Comment by savinayd** [comment] 2019-05-24 06:44
![2c7dc7b89d](https://user-images.githubusercontent.com/50899300/58307840-7f83b480-7e1d-11e9-9f44-51cf29012dd5.png)

**Comment by savinayd** [comment] 2019-05-24 06:45
Icon reference

![dialpad](https://user-images.githubusercontent.com/50899300/58307885-9fb37380-7e1d-11e9-8b7a-a29cdc7fb8f4.png)

**Comment by tagliala** [comment] 2019-05-24 08:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6266, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-05-24 08:26 UTC
