### ISSUE TITLE
Icon Request: fa-discord

### ISSUE THREAD

**Issue by InkxtheSquid** [FortAwesome/Font-Awesome#10860] opened 2017-03-29 21:54 UTC
I added my discord bot to a website called https://bots.discord.pw/ and it was made with Bulma and Bulma is compatible with Font Awesome Icons. I want the Discord logo to be an icon to be on a button to represent that it is for Discord .

**Comment by tagliala** [comment] 2017-03-29 22:31
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-29 22:31 UTC
