### ISSUE TITLE
Icon request:fa-pay

### ISSUE THREAD

**Issue by SuperCreek** [FortAwesome/Font-Awesome#11831] opened 2017-12-04 02:52 UTC
Need an icons to be paid, can you do one?
Thanks!
icon style: ![image](https://user-images.githubusercontent.com/31737534/33534287-99e1b36e-d8e1-11e7-81fe-bd3eb0eb5f8f.png)

**Comment by tagliala** [comment] 2017-12-04 11:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2317 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-12-04 11:57 UTC
