### ISSUE TITLE
Icon Request: icon-award

### ISSUE THREAD

**Issue by LN22** [FortAwesome/Font-Awesome#8790] opened 2016-03-19 10:52 UTC

**Comment by quinen** [comment] 2016-03-19 16:10
i use [fa-trophy](http://fontawesome.io/icon/trophy/) but maybe you think a specific like icon-oscar ?

**Comment by tagliala** [comment] 2016-03-19 20:03
closing here as  a duplicate of #1898

**Closed by tagliala** 2016-03-19 20:03 UTC
