### ISSUE TITLE
Icon Request: fa-flipboard

### ISSUE THREAD

**Issue by sunipeyk** [FortAwesome/Font-Awesome#10515] opened 2017-01-12 04:30 UTC
I would like to see [Flipboard](https://flipboard.com/) icon. It is the best curate and/ or aggregator magazine app/service. And i am sure it is not difficult to make it, i suppose. :)
Thank you.
Icons from [source ](https://about.flipboard.com/tools/)

![flipboard_mbsw](https://cloud.githubusercontent.com/assets/9592953/21876959/a0aca554-d898-11e6-9e80-87a70f6fa1ec.png)  ![flipboard_mrrt](https://cloud.githubusercontent.com/assets/9592953/21876988/f1312388-d898-11e6-89b4-712247e103a9.png)

**Comment by tagliala** [comment] 2017-01-12 10:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1382, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-12 10:16 UTC
