### ISSUE TITLE
Icon request: icon-projector

### ISSUE THREAD

**Issue by davidhendrickmb** [FortAwesome/Font-Awesome#12750] opened 2018-03-31 22:05 UTC
Hi,
It would be great to have a projector icon!
Thanks,
David

**Comment by tagliala** [comment] 2018-04-06 15:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2748, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 15:10 UTC
