### ISSUE TITLE
Icon Request: fa-18+

### ISSUE THREAD

**Issue by Evgeny812** [FortAwesome/Font-Awesome#5073] opened 2014-11-27 08:35 UTC
Age limit. In the circle write 18+
Thanks!!!

**Comment by bertoost** [comment] 2015-02-27 10:49
+1 for @oxguy3

**Comment by Macsch15** [comment] 2015-02-27 10:56
+1

**Comment by pixelloop** [comment] 2015-03-05 07:32
+1

**Comment by turbospaces** [comment] 2017-12-25 15:28
+1

**Comment by 0x19** [comment] 2018-01-11 18:22
+1

**Comment by oxguy3** [comment] 2018-01-12 04:02
**Stop leaving +1 comments on this issue!** Per the [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons), you should leave a 👍 reaction on Evgeny812's original comment if you want to vote for this.

**Comment by narutards** [comment] 2019-05-01 16:33
Could we get some traction into this? It has been 4.5 years and should be simple enough to make.

**Comment by aethior** [comment] 2022-03-19 16:40
🔞 [U+1F51E](https://emojipedia.org/emoji/%F0%9F%94%9E/) No One Under Eighteen

Also known as NSFW.

**Comment by Zinnorov** [comment] 2023-08-09 22:26
Almost 9 years. Cmon guys, you can do it. How long should we wait? 10 years more?

**Comment by sensibleworld** [comment] 2024-07-11 13:33
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/5298)

**Closed by sensibleworld** 2024-07-11 13:33 UTC
Labels: new icon, web application icons (legacy category), Duplicate
