### ISSUE TITLE
Icon request: fa-brands fa-tidal

### ISSUE THREAD

**Issue by MaraLanz** [FortAwesome/Font-Awesome#19070] opened 2022-05-24 17:57 UTC
Hi I'm looking to have the icon for **https://www.Tidal.com** added to the brands category.
![tidal](https://user-images.githubusercontent.com/106180211/170100933-fb0999bf-b905-4316-9e45-cacca6906cc5.png)

Thanks!

**Comment by tagliala** [comment] 2022-05-24 18:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8850, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-05-24 18:03 UTC

**Comment by MaraLanz** [comment] 2022-05-24 19:31
My Apologies,
I did a quick search and didn't see it. Thanks!
