### ISSUE TITLE
Brand request: LiveSpace

### ISSUE THREAD

**Issue by TylerMWise** [FortAwesome/Font-Awesome#19937] opened 2023-10-07 15:33 UTC
### Description

LiveSpace is a community to express yourself and discover new content on a platform made for creators, by creators

![image](https://github.com/FortAwesome/Font-Awesome/assets/74430503/5a9ce0a9-6016-444c-8372-b9c489c4efd7)

### Official website

https://live.space/

### Brand guidelines

https://drive.google.com/drive/folders/1EsxFVYaMfqak2ZOLrLNp3y-6yGkbh0fc

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2023-10-07 15:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19893, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-10-07 15:48 UTC
Labels: brand icon
