### ISSUE TITLE
Icon Request: fa-sort-horizontal

### ISSUE THREAD

**Issue by lucidstudios** [FortAwesome/Font-Awesome#3498] opened 2014-05-21 14:05 UTC
![screen shot 2014-05-27 at 11 21 44](https://cloud.githubusercontent.com/assets/556268/3089562/57d88fcc-e580-11e3-9ab1-3cd3559d8ef1.png)
I would like to make a request for double arrows like you see in numeric stepper field (html5). An example can be seen at http://cssdeck.com/labs/styling-select-box-with-css3 in the styling of the select element.

Double arrows both left-right and top-bottom will be useful for many applications.

**Comment by aethior** [comment] 2022-04-21 21:22
@tagliala `arrows (category)` label for this request?

**Comment by sensibleworld** [comment] 2024-07-11 13:56
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/8144)

**Closed by sensibleworld** 2024-07-11 13:56 UTC
Labels: new icon, arrows (category), Duplicate
