### ISSUE TITLE
Icon request: fa-export fa-import

### ISSUE THREAD

**Issue by danielone** [FortAwesome/Font-Awesome#9554] opened 2016-07-12 23:02 UTC
Something like this for export
https://www.iconfinder.com/icons/979791/arrow_direction_exit_go_move_out_right_icon#size=128

import (similar to above but arrow points in)
https://www.iconfinder.com/icons/979790/arrow_go_in_left_icon#size=128

But the "box" part could look like the current file upload
http://fontawesome.io/icon/upload/

**Comment by tagliala** [comment] 2016-07-13 09:30
Duplicate of #1020 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-13 09:30 UTC

**Comment by danielone** [comment] 2016-07-13 23:58
Sorry about that. will do moving forward
