### ISSUE TITLE
Icon Request: dice-1, dice-2, dice-3, dice-4, dice-5, dice-6

### ISSUE THREAD

**Issue by zengLH1981** [FortAwesome/Font-Awesome#12533] opened 2018-03-07 13:01 UTC
dice with 1~6 points

Example image:
https://upload.wikimedia.org/wikipedia/commons/4/4c/Dice.png

**Comment by tagliala** [comment] 2018-03-07 14:27
Hi!

Thanks for being part of the Font Awesome Community.

Dice is a duplicate of #2622 

Apparently you are requesting dice faces from 1 to 6. I'm going to rename this issue

**Comment by luminarious** [comment] 2018-04-19 06:13
If d4, d8, d10, d12 or d20 is added at a later point, it would make sense to use more precise naming like d6-1 or dice6-1 or dice-6-1

**Comment by sensibleworld** [comment] 2018-05-10 20:49
https://fontawesome.com/icons?d=gallery&q=dice%20

**Closed by sensibleworld** 2018-05-10 20:49 UTC
Labels: new icon, released, web application icons
