### ISSUE TITLE
Icon Request: fa-laravel

### ISSUE THREAD

**Issue by josealgardataborges** [FortAwesome/Font-Awesome#9644] opened 2016-07-26 09:40 UTC
Could it be possible to have font-awesome icon for the laravel php framework? The icon: 
![laravel-logo](https://cloud.githubusercontent.com/assets/8929655/17133258/49d81d22-531d-11e6-9972-565c0fb44d50.png)

**Comment by tagliala** [comment] 2016-07-26 10:10
Duplicate of #2151, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-26 10:10 UTC
