### ISSUE TITLE
Icon Request: fa-fingerprint

### ISSUE THREAD

**Issue by mantiqueira** [FortAwesome/Font-Awesome#12804] opened 2018-04-08 00:05 UTC
For finger print authentications in mobile apps :)

**Comment by tagliala** [comment] 2018-04-08 07:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4431 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-08 07:49 UTC
