### ISSUE TITLE
Icon Request: Glitch

### ISSUE THREAD

**Issue by aboutDavid** [FortAwesome/Font-Awesome#17398] opened 2020-11-12 18:09 UTC
**What can it be used for?**
The Glitch Icon can be used for linking to Glitch profiles (glitch.com/@[username]) like how many websites will use the font awesome Twitter icon to link to their Twitter account. 

**Example image (optional)**
![](https://cdn.glitch.com/e200ca48-8caa-472f-b105-1ab0ed3d605d%2Fglitch-fish-big.png)
All brand assets may be downloaded at [glitch.com/about/press](https://glitch.com/about/press)

**Icon request checklist**
- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-11-12 18:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11883, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-11-12 18:14 UTC

**Comment by aboutDavid** [comment] 2020-11-12 18:16
Oh sorry, Something went wrong in my GitHub search 😆

**Comment by tagliala** [comment] 2020-11-12 18:38
no problem, it happens 👍
