### ISSUE TITLE
Icon Request: icon-weather

### ISSUE THREAD

**Issue by andreinass** [FortAwesome/Font-Awesome#5506] opened 2015-01-28 11:08 UTC
Hello!

It would be really nice if you can add icons reffered to weather. My app's name is SmartPort, and I'm trying to change all the icons from menu to fontAwesome icons, and the only icon that seems to miss to me is a weather icon. Here are some images from weather icons that would be awesome if you can add.

![cloudy19](https://cloud.githubusercontent.com/assets/7526598/5936556/1c41aea8-a6e6-11e4-89d0-667fe4e3c6a4.png)
![sun79](https://cloud.githubusercontent.com/assets/7526598/5936558/1c58a842-a6e6-11e4-81fc-ca6f969d4f2d.png)
![sunny18](https://cloud.githubusercontent.com/assets/7526598/5936557/1c41f836-a6e6-11e4-81dd-f4adf00eb468.png)

This would be perfect for me if you can add icons like this.

Thank you so much! Your font is really Awesome :)

Regards.

**Comment by tagliala** [comment] 2015-01-28 14:30
duplicate of #2587, please +1 that request

please also consider that all weather icons may be considered beyond the scope of Font Awesome. There are icon sets focused on weather only

closing here

**Closed by tagliala** 2015-01-28 14:30 UTC

**Comment by andreinass** [comment] 2015-01-28 14:44
Hello,

I'm not asking for ALL weather icons, I'm asking for an icon prettier that the sun you already have.

That's all :)

Thanks

**Comment by tagliala** [comment] 2015-01-28 16:53
@andreinass ok but you still need to open individual requests, as per our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Since fa-sun is already here, if you want to ask Dave to redesign the icon is more than fine, but you need an individual request with a proper title

The "black sun" could be named as "Icon request: icon-sun"

Then open a new request for a cloudy icon

Closing here
