### ISSUE TITLE
Icon request: fa-swim

### ISSUE THREAD

**Issue by bhrg** [FortAwesome/Font-Awesome#12817] opened 2018-04-09 22:10 UTC
Hey, 

Could you add a swimming icon? It could be used when talking about amenities of a certain business or posting rules about a business.  

Example:
https://d30y9cdsu7xlg0.cloudfront.net/png/1506443-200.png

**Comment by tagliala** [comment] 2018-04-10 06:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5771, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-10 06:06 UTC

**Comment by bhrg** [comment] 2018-04-10 20:10
It looks like its been YEARS since the original request. Why hasn't it been
added?


Brittany Hargis
SEO Specialist
m: 801.663.5792 <(801)%20663-5792>
e: b@echomarketers.com
