### ISSUE TITLE
Icon request: strongbox

### ISSUE THREAD

**Issue by StephanArnas** [FortAwesome/Font-Awesome#16377] opened 2020-03-28 11:14 UTC
**What can it be used for?**
I am building a saas service and it would be amazing if you could develop to a strongbox image.
Because one of my feature is a strongbox :) 

**Example image (optional)**
Some example here: https://www.flaticon.com/search?word=strongbox

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-03-28 11:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1813, please add a 👍 reaction to that request.

I'm also going to add `strongbox` as a synonym in the title

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-28 11:45 UTC
