### ISSUE TITLE
Icon request: New icon

### ISSUE THREAD

**Issue by Madaluna** [FortAwesome/Font-Awesome#18081] opened 2021-07-16 08:49 UTC
**What can it be used for?**
For new products/elements

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-07-16 09:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11002, please add a 👍 reaction to that request.

Please also read my comment at https://github.com/FortAwesome/Font-Awesome/issues/11002#issuecomment-297929306 about icons containing words

We have also an example of layering text on icons at https://fontawesome.com/v5.15/how-to-use/on-the-web/styling/layering

**Closed by tagliala** 2021-07-16 09:07 UTC
