### ISSUE TITLE
Icon Request: fa-paddling

### ISSUE THREAD

**Issue by GustavoArriola** [FortAwesome/Font-Awesome#16933] opened 2020-07-18 16:56 UTC
**What can it be used for?**
Sport category

**Example image (optional)**
![remo](https://user-images.githubusercontent.com/13947325/87857611-10f19800-c8f6-11ea-83ec-dd03bfe628da.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by GustavoArriola** [comment] 2020-08-04 17:49
This is also important, as there are currently few icons for sports.

**Comment by GustavoArriola** [comment] 2021-07-08 20:41
Are you planning to add more icons to the Sport category in version 6?

**Comment by sensibleworld** [comment] 2024-07-11 16:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/18743)

**Closed by sensibleworld** 2024-07-11 16:37 UTC
Labels: new icon, sport (category), Duplicate
