### ISSUE TITLE
Icon request: bottle

### ISSUE THREAD

**Issue by Max-Krieg666** [FortAwesome/Font-Awesome#6083] opened 2015-03-28 07:08 UTC
pls add bottle

**Comment by tagliala** [comment] 2015-03-28 19:05
duplicate of #1762 ?

**Comment by Max-Krieg666** [comment] 2015-03-30 12:05
as like as http://img.carpati.org/users/mi/mike/mike/editor/09/5.4.jpg

**Comment by jesseflorig** [comment] 2015-04-01 04:21
@tagliala seems like a yes to me.

**Comment by tagliala** [comment] 2016-09-20 14:44
no feedback, closing here

**Closed by tagliala** 2016-09-20 14:44 UTC
