### ISSUE TITLE
No Icons found for DOTNET, MVC, CSharp, ASP.Net or DotNet Core.

### ISSUE THREAD

**Issue by kunalpgithub** [FortAwesome/Font-Awesome#14637] opened 2019-02-13 15:53 UTC

**Comment by tagliala** [comment] 2019-02-13 16:04
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

csharp is a duplicate of #8365, please +1 that request
asp.net is a duplicate of #12996, please +1 that request

About the other requests, please open new issues filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2019-02-13 16:04 UTC
