### ISSUE TITLE
Icon request: icon-category

### ISSUE THREAD

**Issue by rgb4u** [FortAwesome/Font-Awesome#7707] opened 2015-10-18 18:54 UTC
Hi, i'm searching category icon similar to this:
https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT4xT-L6M263RGB5SORTZplWiEYz_bXmOPBjA1DH1svWmdAyij3jlMoHQ
Or advice how to make your own icons, and add them to wordpress
Thank you :))

**Comment by tagliala** [comment] 2015-10-18 20:11
duplicate of #1343 , please +1 that request

closing here

**Closed by tagliala** 2015-10-18 20:11 UTC
