### ISSUE TITLE
Icon request: icon-file-plus

### ISSUE THREAD

**Issue by fashionmingle** [FortAwesome/Font-Awesome#11141] opened 2017-06-06 20:35 UTC
I would like to use this for showing the user where to add a document or file. 

I would use this icon http://fontawesome.io/icon/file-text/

With the plus sign concept from this icon http://fontawesome.io/icon/user-plus/

**Comment by tagliala** [comment] 2017-06-06 21:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1525, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-06 21:15 UTC
