### ISSUE TITLE
Icon request: solar-panel

### ISSUE THREAD

**Issue by amrocs** [FortAwesome/Font-Awesome#9073] opened 2016-04-28 07:00 UTC
Icon Request: Solar panel for renewable energy
like this:

![icon_si](https://cloud.githubusercontent.com/assets/2367923/14878085/2b5680fc-0d5c-11e6-93c5-4d425b019faa.png)

[https://en.wikipedia.org/wiki/Solar_panel](https://en.wikipedia.org/wiki/Solar_panel)

**Comment by tagliala** [comment] 2016-04-28 08:24
Duplicate of #3326, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-28 08:24 UTC
