### ISSUE TITLE
Icon request: svelte

### ISSUE THREAD

**Issue by donghhan** [FortAwesome/Font-Awesome#18122] opened 2021-07-30 04:42 UTC
**What can it be used for?**
This can be used as same as other programming languages

**Example image (optional)**
![svelte](https://user-images.githubusercontent.com/84304078/127601350-d2d5f6c0-0d33-4549-84a6-eed98ef22755.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-07-30 09:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16764, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-07-30 09:41 UTC
