### ISSUE TITLE
fa-rabbit-fast not showing up

### ISSUE THREAD

**Issue by rthomas88** [FortAwesome/Font-Awesome#15266] opened 2019-07-15 17:48 UTC
This icon doesn't show up no matter the weight. Have pro license and have CSS hooked to our website. 

Had a similar issue with fas fa-alarm-exclamation and all of its iterations.

**Comment by tagliala** [comment] 2019-07-15 19:00
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/9oj78abe/8/

Since there are too few information, I can only guess what is happening:
1. You are serving the assets from your server
2. The server is loading a version of Font Awesome < 5.4 (`fa-rabbit-fast` has been introduced in 5.4.0, as per [docs](https://fontawesome.com/icons/rabbit-fast?style=solid))
3. You have only updated the CSS and not the webfont folder (you must update them both)
4. There are cache issues on the client side (the client is using outdated css/webfont)

If you still think there is an issue with Font Awesome, feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case. A link to your website should be enough

Refs:
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Meanwhile, closing here

**Closed by tagliala** 2019-07-15 19:00 UTC
