### ISSUE TITLE
split brand icons.

### ISSUE THREAD

**Issue by My1** [FortAwesome/Font-Awesome#9009] opened 2016-04-18 13:04 UTC
well let's say it short.
There are 167 brand icons listed on the fontawesome page (including 9 aliases, amking it 158 distinct icons)
My idea would be to split off most of those as a seperately used file (still included in the fa downloads but just as different font and CSS files) because let's be honest, most of those brands I haven't even heard and we still have 1040 issues under the search `is:open label:"new icon" label:"brand icons"` meaning requests for new brand icons.
my Idea would be to keep only the most basic and known brands (google, fb twitter etc.) in the basic set thereby reducing the filesize for icons almost no one uses or even knows in the first place and those who do want it just list another CSS file.

**Comment by tagliala** [comment] 2016-04-18 14:09
> My idea would be to split off most of those as a seperately used file (still included in the fa downloads but just as different font and CSS files) because let's be honest, most of those brands I haven't even heard and we still have 1040 issues under the search is:open label:"new icon" label:"brand icons" meaning requests for new brand icons.

This is how [Font Awesome Black Tie](http://blacktie.io/) works and it should be part of FA 5.0.0

> my Idea would be to keep only the most basic and known brands (google, fb twitter etc.) in the basic set thereby reducing the filesize for icons almost no one uses or even knows in the first place and those who do want it just list another CSS file.

I agree with you. I was also searching for an "objective" way to valuate brands, like "include in the core font if brand has more than 100M users". Black Tie completely separates brands and that approach is reasonable.

Please also keep in mind that for a specific use case, [customization](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome) is a good approach

Btw... considering this as a duplicate of #1322, please share there your thoughts

**Closed by tagliala** 2016-04-18 14:09 UTC
