### ISSUE TITLE
Icon request: fa-yummly

### ISSUE THREAD

**Issue by oxjox** [FortAwesome/Font-Awesome#10821] opened 2017-03-22 04:23 UTC
I'd really appreciate an icon for the website Yummly.  This would be helpful to incorporate in to my Wordpress theme using the FA font. I used the hires logo found here to create the png in photoshop http://about.yummly.co/press/. Thanks :)

![fa-yummly_insert](https://cloud.githubusercontent.com/assets/26589061/24182055/64a2835c-0e95-11e7-8212-9d2831adfacd.jpg)

![fa-yummly](https://cloud.githubusercontent.com/assets/26589061/24181945/a5c89958-0e94-11e7-82b9-349c613fa589.png)

**Comment by tagliala** [comment] 2017-03-22 15:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6138, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-22 15:52 UTC
