### ISSUE TITLE
The git tags newest version on GitHub repository is different from website

### ISSUE THREAD

**Issue by sufuf3** [FortAwesome/Font-Awesome#11913] opened 2017-12-12 05:58 UTC
Hi Font-Awesome team members,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We hosted this [library](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/font-awesome).

I saw the library release v5.0.1 & v5.0.0 on the [website](https://fontawesome.com/how-to-use/upgrading-from-4), such as `https://use.fontawesome.com/releases/v5.0.0/js/all.js`.
But there is no v5.0.0 and v5.0.1 of git tag from GitHub repo.
The git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) relies on [**git tags**](https://github.com/FortAwesome/Font-Awesome/releases) so that it can recognize the correct version and automatically update the repo.

Would you mind adding git tag or telling me your new git repository that CDNJS's bot can automatically add the new versions of this awesome library?

Sorry for bothering you.
If you have any questions or concerns, please let me know.

Many thanks.

cdnjs/cdnjs#12307

**Comment by wolfy1339** [comment] 2017-12-12 16:12
This would be a duplicate of #11908

**Comment by tagliala** [comment] 2017-12-12 18:07
Hi!

Thanks for being part of the Font Awesome Community.

The free repo has not been updated yet.

AFAIK, there isn't a public github repository with the free font

Let's use #11908 for discussion

**Closed by tagliala** 2017-12-12 18:07 UTC
Labels: bug

**Comment by sufuf3** [comment] 2017-12-15 17:06
Thanks for your response.
Hope I can wait for good news.
Many thanks.
