### ISSUE TITLE
Icon request: transmission

### ISSUE THREAD

**Issue by hilmarhalldors** [FortAwesome/Font-Awesome#19033] opened 2022-05-11 11:29 UTC
Car rental transmission
![image](https://user-images.githubusercontent.com/46356245/167839014-b3ddddd6-3b1b-417c-b7ba-a5a6229113fd.png)

**Comment by tagliala** [comment] 2022-05-12 12:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3141, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-05-12 12:08 UTC
