### ISSUE TITLE
Icon Request: fa-lighthouse

### ISSUE THREAD

**Issue by kevinbruce** [FortAwesome/Font-Awesome#11218] opened 2017-06-22 18:08 UTC
Hello,
I thought it would be useful to have a lighthouse for situations like "landing page", "refuge", and the like
[lighthouse.pdf](https://github.com/FortAwesome/Font-Awesome/files/1095748/lighthouse.pdf)

**Comment by tagliala** [comment] 2017-06-22 18:24
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5579, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-22 18:24 UTC
