### ISSUE TITLE
Icon Request: fa-registered

### ISSUE THREAD

**Issue by caban13** [FortAwesome/Font-Awesome#5207] opened 2014-12-13 22:13 UTC
Very similar to "fa-copyright" but with a "R" inside, is commonly used for registered trademarks.

**Comment by zeebe** [comment] 2015-01-28 12:38
+1 This is needed, especially since since there is a Copyright one

**Comment by tagliala** [comment] 2015-01-28 14:28
duplicate of #3276,  please +1 that request

closing here

**Closed by tagliala** 2015-01-28 14:28 UTC
