### ISSUE TITLE
Icon request: fa-burger

### ISSUE THREAD

**Issue by lokeshg91** [FortAwesome/Font-Awesome#13583] opened 2018-07-20 05:43 UTC
### What can it be used for?
Can be used for restaurant food menu.

### Example image (optional)
<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/153732-200.png" alt="icon-signature" style="max-width:100%;">

**Comment by tagliala** [comment] 2018-07-20 08:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1961, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-20 08:15 UTC
