### ISSUE TITLE
Icon request: element

### ISSUE THREAD

**Issue by ZDVokoun** [FortAwesome/Font-Awesome#17976] opened 2021-06-03 16:22 UTC
**What can it be used for?**
Element is the most popular messenger using Matrix protocol. The icon could be used to share username.

**Example image (optional)**
![](https://upload.wikimedia.org/wikipedia/commons/c/cb/Element_%28software%29_logo.svg)
![](https://element.io/images/logo-ele-secondary.svg)

Edited (black):
https://drive.google.com/drive/folders/1nRN3qgQpWfEQvK9VyqiNuXGkTi2dWEnb?usp=sharing

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-04-11 22:01
Duplicate of #11270.

cc/ @tagliala

**Closed** 2022-04-12 09:15 UTC
Labels: brand icon
