### ISSUE TITLE
Icon Request: Radio Icon

### ISSUE THREAD

**Issue by danyob** [FortAwesome/Font-Awesome#13915] opened 2018-09-07 16:12 UTC
I would love to see a radio icon. Something like this: [https://www.flaticon.com/free-icon/radio_54245](https://www.flaticon.com/free-icon/radio_54245)

**Comment by tagliala** [comment] 2018-09-07 16:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #892, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-07 16:28 UTC

**Comment by danyob** [comment] 2018-09-07 17:32
5 Years and still waiting! Any ideas when this will be pushed?
