### ISSUE TITLE
Icon Request: fa-construction

### ISSUE THREAD

**Issue by ichbas** [FortAwesome/Font-Awesome#7815] opened 2015-11-04 17:01 UTC
Would love a construction type icon, maybe a guy with a hardhat, or a digger, dump truck...

**Comment by TheChen5** [comment] 2015-11-05 03:20
Dupe of #4084 and #3934
+1 those
Please :mag:before:heavy_plus_sign:

**Closed** 2015-11-05 09:18 UTC

**Comment by myrmecia** [comment] 2016-05-27 13:29
+1 for digger
