### ISSUE TITLE
Icon request: Geolocation

### ISSUE THREAD

**Issue by cccruzr** [FortAwesome/Font-Awesome#11268] opened 2017-07-07 14:38 UTC
It would be nice to have a geolocation icon like [this one](https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_my_location_48px-512.png), now that there's only a crosshair icon. 

Thanks a lot for such a nice work!

**Comment by tagliala** [comment] 2017-07-08 11:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #560 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-08 11:23 UTC
