### ISSUE TITLE
fal fa-book-reader icon is not rendering on chrome, but works fine on IE/firefox

### ISSUE THREAD

**Issue by Nimmi92** [FortAwesome/Font-Awesome#15251] opened 2019-07-10 10:54 UTC
I am using @fortawesome/fontawesome-pro@5.9.0. 
`<i class="fal fa-book-reader"></i>`
fa-book-reader icon is not rendering on chrome(version 68+), but works fine on IE/firefox

**Comment by tagliala** [comment] 2019-07-10 12:18
Hi!

Thanks for being part of the Font Awesome Community.

Because of the approach used (self-hosted / npm / pro package / unknown build system / unknown configuration / unknown included css files), this issue is extremely hard to replicate. 

The best I can do is the following:

Demo with parcel / FA 5 free on Codesandbox: https://codesandbox.io/s/pensive-mendel-4yrbd

Screenshot from the same project on my own machine with FA5 Pro and light icon / Chrome 75:

![image](https://user-images.githubusercontent.com/556268/60968439-595a9b00-a31d-11e9-8556-cc7ac5d38f78.png)

Relevant source code:
```
# index.js
import "@fortawesome/fontawesome-pro/css/all";

# index.html
<h1><span class="fal fa-book-reader"></span> Hi!</h1>
```

I'm going to ask you to check:
- your browser cache (try to clear the cache in an incognito window)
- browser console (check if chrome is loading the proper font files)
- check that there aren't third-party modules/libraries/plugins/themes loading older version of font awesome that may take precedence over your version

Then, if you still have issue, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md), having care of providing a reproducible test case

Sorry, this is the best I can do for you at the moment.

Meanwhile, closing here

**Closed by tagliala** 2019-07-10 12:18 UTC
