### ISSUE TITLE
Using large icon, there exists gaps in the :before pseudo-element

### ISSUE THREAD

**Issue by Weiyu-Chen** [FortAwesome/Font-Awesome#11472] opened 2017-08-31 03:15 UTC
Such as `<i class="fa fa-television fa-5x" ></i>`. 
<br>
![th fe o ex o p u84abw](https://user-images.githubusercontent.com/13402013/29904662-7e3ad860-8e3c-11e7-8240-2d6f8be24f7a.png)

And the others icon may exists the same problem.

**Comment by tagliala** [comment] 2017-08-31 09:23
Hi!

Thanks for being part of the Font Awesome Community.

We cannot do so much for top and bottom gaps.

The problem of right margin is already known, duplicate of #8628

Closing here

**Closed by tagliala** 2017-08-31 09:23 UTC
