### ISSUE TITLE
Icon Request: fa-panoramio

### ISSUE THREAD

**Issue by glogloman** [FortAwesome/Font-Awesome#5437] opened 2015-01-21 22:43 UTC
Hi there, please, can you add Panoramio icon to your Font-Awesome icon set? I would like to use it in header of my personal webpage, where I already have Facebook, YouTube and RSS icons.. Panoramio is great service for placing photos to Google maps. ;) Big thanks in advanced.

**Comment by tagliala** [comment] 2015-01-22 13:30
duplicate of #2562, please +1 that request

closing here

**Closed by tagliala** 2015-01-22 13:30 UTC
