### ISSUE TITLE
Icon request: pizza-slice

### ISSUE THREAD

**Issue by dexterwasaham** [FortAwesome/Font-Awesome#14168] opened 2018-10-24 18:12 UTC
### What can it be used for?

Everyone loves pizza, personally I wanted to use it to showcase my love of pizza on my personal website.

### Example image (optional)

triangular pizza slice, with or without little circle pepperonis 

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-10-24 21:22
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #4493, please add a 👍  reaction to that request.

Closing here

**Closed by tagliala** 2018-10-24 21:22 UTC
