### ISSUE TITLE
Icon Request: Conductor

### ISSUE THREAD

**Issue by grootstebozewolf** [FortAwesome/Font-Awesome#14060] opened 2018-10-03 14:25 UTC
As a user, but with an conductor hat 
![conductor](https://user-images.githubusercontent.com/2713718/46416979-f7835a00-c728-11e8-90b8-e9ea5bb64b21.png)

**Comment by tagliala** [comment] 2018-10-03 18:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7743 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-03 18:41 UTC
