### ISSUE TITLE
ICON REQUEST: Tiktok

### ISSUE THREAD

**Issue by leadsengine** [FortAwesome/Font-Awesome#16693] opened 2020-05-21 15:25 UTC
Please make the icon https://i.gyazo.com/8d1987139084727e99a2cdd207c3a272.png

for tiktok.com

**Comment by tagliala** [comment] 2020-05-21 17:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14340. No need to +1 that request, tiktok will be available in the next version of Font Awesome

Closing here

**Closed by tagliala** 2020-05-21 17:47 UTC
