### ISSUE TITLE
fa-internet-explorer uses IE 7/8 logo instead of IE9-11 logo

### ISSUE THREAD

**Issue by webwizgordon** [FortAwesome/Font-Awesome#7081] opened 2015-07-29 20:53 UTC
Notice how the IE9-11-style logo has a much more consistent thickness and overall leaner look.

![IE Logo comparison](http://i.imgur.com/ct8xnoY.png)

**Comment by tagliala** [comment] 2015-07-30 19:06
I can confirm

**Comment by tiesont** [comment] 2015-08-01 06:58
For what it's worth, I don't see an obvious difference between the FA icon and the image used on http://windows.microsoft.com/en-us/internet-explorer/download-ie

**Comment by Studio384** [comment] 2015-08-01 14:20
The icon in FA is not even IE7/8 but IE6. Who's idea was it to include that old logo instead of going with the new one? The logo show on the page mentioned by @tiesont should have been the base.

**Comment by tvirelli** [comment] 2015-08-05 16:58
@Studio384 I see your point, but really, does it matter that much. At the normal usage size of FA, I think that your average user knows what it is and can't tell the difference. At even a larger size, it still holds up.

**Comment by acshef** [comment] 2015-08-05 17:56
Would it be too much to ask for more than one of the "families?" As an example, someone might maintain a site that shows the browsers (user-agents) of its users. Although Opera, Firefox, and Chrome have also gone through icon revisions over the years, the userbase of the "older versions" is much smaller than the distribution of IE versions. What's more, the user experience of each IE is a significant enough difference to warrant a unique identification for each version (it would not make sense to lump all IE users together). For that reason, I could see wanting IE7/8, IE9/10/11, and Edge all uniquely. Thoughts?

**Comment by tvirelli** [comment] 2015-08-05 18:06
Here is an image showing icons of IE for all versions: http://logos.wikia.com/wiki/Internet_Explorer

I honestly don't think that when represented as a single color, flat icon, there is enough of a difference to warrant multiple icons. However, that is just my opinion.

**Comment by My1** [comment] 2015-09-04 13:00
I'd even say the fa icon is the IE5 icon since the IE6 is a 3D version of the IE5 logo
at least the main difference is that in the flat version of the ie11 icon has the arc connected to the e.
also the cut in the e is way sharper then in the fa icon.

**Comment by Studio384** [comment] 2015-10-25 20:42
So does this ticket include adding fa-edge or should there be another issue for that?

**Comment by davegandy** [comment] 2015-11-19 20:19
Okay, think we're using the latest one here now. Sorry about that. Updated in 4.4.1-wip branch. Closing.

**Closed by davegandy** 2015-11-19 20:19 UTC
Labels: brand icons, bug

**Comment by My1** [comment] 2015-11-20 17:19
IE10? shouldnt it rather be IE11? (assuming it changed a bit)
