### ISSUE TITLE
I am Missing a "gold bag" or money bag

### ISSUE THREAD

**Issue by Batacus** [FortAwesome/Font-Awesome#12315] opened 2018-02-09 23:32 UTC
To have a sign for tax. 
There is nothing that can be used to show tax 
Even nothing to find for "gold" 

thx

**Comment by tagliala** [comment] 2018-02-09 23:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1414 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-09 23:35 UTC
