### ISSUE TITLE
Brand request: Recut URL Shortener (recut.in) 

### ISSUE THREAD

**Issue by gauravkumaar** [FortAwesome/Font-Awesome#19954] opened 2023-10-16 01:35 UTC
### Description

Hey,
Please create an icon for Recut URL Shortener (recut.in).
Thank you.

### Official website

https://recut.in

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2023-10-16 05:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19951 

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-10-16 05:39 UTC
Labels: brand icon
