### ISSUE TITLE
Icon request: computer-mouse-right and computer-mouse-left

### ISSUE THREAD

**Issue by TheGameSpider** [FortAwesome/Font-Awesome#19582] opened 2023-02-26 18:50 UTC
### Use case

Can be used to tell the user which mouse button to use to perform a certain action.

### Example image

https://prnt.sc/MWfT4iMcFuzb

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by aethior** [comment] 2023-02-26 20:26
Hi @TheGameSpider,

This request is a duplicate of #13250.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed as completed** 2023-02-26 20:28 UTC
Labels: new icon
