### ISSUE TITLE
Icon Request: fa-google-hangout

### ISSUE THREAD

**Issue by anaflasker** [FortAwesome/Font-Awesome#7029] opened 2015-07-23 19:46 UTC
There are already bunch of icons for chat (skype, slack, whatapp) ... but I'm somehow missing google hangouts! Would be awesome to add it.

**Comment by TheChen5** [comment] 2015-07-25 23:23
Dupe of #4045.
Go "+1" that one.
(Search for the issue before creating it)

**Comment by tagliala** [comment] 2015-07-26 13:11
@TheChen5 thanks

**Closed by tagliala** 2015-07-26 13:11 UTC
