### ISSUE TITLE
Icon Request: fa-bandsintown

### ISSUE THREAD

**Issue by englande** [FortAwesome/Font-Awesome#8831] opened 2016-03-25 17:26 UTC
I am making a musician web site and they use the app [Bandsintown](http://news.bandsintown.com/home) for their tour dates. I am requesting an icon for this app.  

It is fairly popular among artists and the web plugin makes it easy to update tour dates across platforms anywhere they are located without actually having to have any coding knowledge or be at a computer. 

I plan on using the icon in a button so fans can "track" the artist on Bandsintown, much like the Facebook follow button. 

Here is a suggested icon (the Bandsintown logo):

![Bandsintown icon](https://cloud.githubusercontent.com/assets/16142152/14049629/78c84476-f284-11e5-9cc8-8334f24bbb81.png)

**Comment by tagliala** [comment] 2016-03-25 17:47
Duplicate of #6687, please +1 that request

closing here

**Closed by tagliala** 2016-03-25 17:47 UTC
