### ISSUE TITLE
Icons for shopify

### ISSUE THREAD

**Issue by davidipp** [FortAwesome/Font-Awesome#12765] opened 2018-04-03 09:37 UTC
Lack of SD Memory Icon.

**Comment by tagliala** [comment] 2018-04-06 09:25
Hi!

Thanks for being part of the Font Awesome Community.

sd card is a duplicate of #1109, please add a 👍  reaction to that request.
shopify is a duplicate of #3850, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 09:25 UTC
