### ISSUE TITLE
Icon Request: fa-exclamation-triangle-o

### ISSUE THREAD

**Issue by danzaner** [FortAwesome/Font-Awesome#8872] opened 2016-04-01 15:27 UTC
My request is for an icon the same as "fa-exclamation-triangle" but in the "-o" style. Thanks for considering it.

**Comment by tagliala** [comment] 2016-04-01 15:38
Duplicate of #5718, please +1 that request

Please also search before opening new requests

Closing here

**Closed by tagliala** 2016-04-01 15:38 UTC
