### ISSUE TITLE
Icon request: icon-alergens

### ISSUE THREAD

**Issue by RBDay** [FortAwesome/Font-Awesome#18929] opened 2022-04-21 08:51 UTC
Please, a list of icons for the alergens (milk-alergen, soy-alergen, etc)

Thx

**Comment by tagliala** [comment] 2022-04-21 15:27
Hi!

Thanks for being part of the Font Awesome Community.

Managing this issue is a little bit hard to manage

Duplicate of #13383, we should check if in the meanwhile we added more icons and what are left

**Closed as completed by tagliala** 2022-04-21 15:27 UTC
