### ISSUE TITLE
Icon request: NSFW / 18+ Icon

### ISSUE THREAD

**Issue by shylor** [FortAwesome/Font-Awesome#15596] opened 2019-09-24 20:48 UTC
**What can it be used for?**
We have a site that has Safe for Work communities, but also Not Safe for Work communities and we have a toggle on the site for this. I could also see this being used for sites verification checks for games and adult content.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/1676257/65549089-d17f3880-deea-11e9-99f5-a3cf713fe8f7.png)

![image](https://user-images.githubusercontent.com/1676257/65549132-eb208000-deea-11e9-8c34-b14fd38a864e.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-09-25 13:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5298, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-25 13:26 UTC
