### ISSUE TITLE
Icon Request: fa-tabs

### ISSUE THREAD

**Issue by mikethedj4** [FortAwesome/Font-Awesome#5333] opened 2015-01-03 22:16 UTC
![tabs-icon](https://cloud.githubusercontent.com/assets/2473707/5603959/cd380536-9363-11e4-8e4d-a4de886d392a.png)

I'm working on a web design application for touch users. I love using Font-Awesome for my apps and I noticed when it comes to html element components there's only a few to choose from and some elements like buttons, select element, textbox's, textarea's are not available. I also plan on adding moduals so users can add their twitter feed, lightbox, slider/fotorama, email, etc:

In this case I've already designed the icon for my tabs modual (.svg & .png). Because I enjoy using Font-Awesome I thought I'd come here and request it.

**Comment by tagliala** [comment] 2015-01-04 14:21
duplicate of #2419 , please +1 that request and post there your example.

PS. this will hardly fit 14x14 icon size

**Closed by tagliala** 2015-01-04 14:21 UTC
