### ISSUE TITLE
Icon request: icon-brain

### ISSUE THREAD

**Issue by David-R-Guymon** [FortAwesome/Font-Awesome#11302] opened 2017-07-17 21:53 UTC
For anything mind or brain related. Thinking, brain health or mindful.
![brain](https://user-images.githubusercontent.com/15332549/28291534-195f4ce8-6b08-11e7-962a-27d32c7c08f0.png)

**Comment by tagliala** [comment] 2017-07-17 22:21
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2075 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-17 22:21 UTC

**Comment by David-R-Guymon** [comment] 2017-07-17 22:26
Thanks, if it was on the current page of icons for version 4.7.0 then I would not have made a ticket.

**Comment by David-R-Guymon** [comment] 2017-07-20 22:44
The link to the duplicate does me no good. I need an icon I can use NOW! Why close this when there is no icon in the latest version. Who's running the asylum?
