### ISSUE TITLE
CDN trouble | fontawesome.com domain issue [SOLVED, PLEASE WAIT FOR DNS PROPAGATION]

### ISSUE THREAD

**Issue by krezzsy** [FortAwesome/Font-Awesome#10453] opened 2017-01-02 11:34 UTC
Hi, I'm developing my web app locally and included font-awesome icons via CDN (system generated my personal script) 2 months ago. It worked properly, but today I have a problem with it, I can't see any icons (nothing at all). Also, I can't send a request to get a new script, response page doesn't work. I tried to include icons with downloading css, but I see rectangles instead icons:(
Please, help me! Thank you!
Happy New Year:)

**Comment by gurenovich** [comment] 2017-01-02 11:38
yes and iam

**Comment by ThomasRenard** [comment] 2017-01-02 11:56
Looks like the CDN server is down?

**Comment by tagliala** [comment] 2017-01-02 12:42
@robmadole could you please check?

**Comment by ThomasRenard** [comment] 2017-01-02 12:56
It looks like there is a problem with ICANN verification: http://cdn.fontawesome.com/

**Comment by tagliala** [comment] 2017-01-02 12:57
Yes, I can confirm. I'm trying to reach Dave

**Comment by tagliala** [comment] 2017-01-02 13:32
*UPDATE*: It appears that the domain has been verified and now it is up and running for me

**Comment by ThomasRenard** [comment] 2017-01-02 16:38
Works like a charme again! Thanks!

**Comment by krezzsy** [comment] 2017-01-02 16:43
Tnx! Everything works!

**Comment by probc** [comment] 2017-01-02 17:40
It is still down here in Canada.  Any idea when this will get resolved?

**Comment by probc** [comment] 2017-01-02 17:56
My apologies. It is now working here in Canada

**Comment by sandes93** [comment] 2017-01-02 20:43
This link use to work for me but it's not working anymore: https://use.fontawesome.com/337ee3c2a3.js

**Comment by leonardoRC** [comment] 2017-01-02 21:51
working now!

**Comment by sandes93** [comment] 2017-01-02 23:16
@leonardoRC Was that a reply to my post? It still does not seem to be working. Should I need to wait some time before the changes take effect?

**Comment by tagliala** [comment] 2017-01-02 23:16
I'm going to reopen here for another day or two because there are some dns delay issues

**Comment by leonardoRC** [comment] 2017-01-03 11:52
The problem came back again

**Comment by robmadole** [comment] 2017-01-03 18:49
We are still within the 48 hour window for this issue. It may be another 24 before this is completely fixed across the Internet. Sorry everyone but we just don't have any way to speed this up.

**Comment by tagliala** [comment] 2017-01-04 16:42
Hi guys, how are things going?

/cc @leonardoRC @sandes93 @probc

**Comment by probc** [comment] 2017-01-04 16:48
Everything is fine for me now in the West coast of Canada

**Comment by sandes93** [comment] 2017-01-04 19:21
I was using https://use.fontawesome.com/337ee3c2a3.js 
It is working now.

**Comment by leonardoRC** [comment] 2017-01-06 01:21
Sorry for my delay, Everything ok here in Brazil

**Comment by tagliala** [comment] 2017-01-09 15:31
Closing here!

Please leave a comment if you are still experiencing issues

**Closed by tagliala** 2017-01-09 15:31 UTC
Labels: bug, cdn
