### ISSUE TITLE
Icon Request: fa-ngn

### ISSUE THREAD

**Issue by strategsolutions** [FortAwesome/Font-Awesome#12162] opened 2018-01-27 00:05 UTC
Hi.

Please i would like to request for a fontawesome icon for the naira (&#x20A6;) symbol (characterized by the html code `&#x20A6;`)

It would make building apps in my country smoother, so we can just use the symbol instead of using 'NGN'

Thank you.

**Comment by tagliala** [comment] 2018-01-27 10:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1969, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-27 10:34 UTC
