### ISSUE TITLE
Icon Request: fa-icon-sewing

### ISSUE THREAD

**Issue by sezeresen** [FortAwesome/Font-Awesome#9279] opened 2016-05-26 10:47 UTC
It can be used for sewing progress in manufacturing.
I really need this.
[sample](http://image005.flaticon.com/1/svg/115/115831.svg)

**Comment by tagliala** [comment] 2016-05-26 14:37
Duplicate of #4598, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-26 14:37 UTC
