### ISSUE TITLE
Icon request: file-map-marker-alt

### ISSUE THREAD

**Issue by bryanllewis** [FortAwesome/Font-Awesome#15450] opened 2019-08-28 19:44 UTC
We use a lot of files in the Geo-spacial/GIS space (shape files, kml, etc) that I would like to represent with an FA icon.  I would propose a new icon that is essentially a file icon with the map-marker or map-marker-alt icon inside of it.

It would look something like this: https://www.iconfinder.com/icons/2966862/document_file_location_map_marker_pin_icon

**Comment by tagliala** [comment] 2019-08-28 20:43
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/175/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment] 2024-07-11 18:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](add map pin mod to Wizard?)

**Closed by sensibleworld** 2024-07-11 18:23 UTC
Labels: new icon, web application icons (legacy category), Duplicate

**Comment by tagliala** [comment] 2024-07-19 06:56
@sensibleworld missing feature request here
