### ISSUE TITLE
Icon request: fa-no-parking

### ISSUE THREAD

**Issue by tpeyrard** [FortAwesome/Font-Awesome#6935] opened 2015-07-12 13:37 UTC
Icone used to show that there is a parking : https://www.iconfinder.com/icons/415895/complex-facilities_o_parking_icon#size=128

It would be nice to have the opposite icon (no-parking)

**Comment by tagliala** [comment] 2015-07-16 19:14
duplicate of #1559 , please +1 that request

if you want, you can rename this as no-parking or you should close this request

**Comment by Samoht-fr** [comment] 2015-07-18 20:28
Hi,

thanks for your answer. I +1 the other and turned this one into no parking.

**Comment by tvirelli** [comment] 2015-08-05 17:43
@Samoht-fr you could use icon stacks with text. Here is an example: http://jsfiddle.net/wdozmays/1/

**Comment by pke** [comment] 2016-03-24 11:46
@tvirelli Nice temp, solution However at `2x` it does not play well alongside other, non-stacked `2x` icons. Any ideas?

**Comment by aethior** [comment] 2022-02-28 02:32
Hi @tpeyrard,

Check [fa-square-parking](https://fontawesome.com/icons/square-parking) and [fa-square-parking-slash](https://fontawesome.com/icons/square-parking-slash).
Regards.

cc/ @tagliala

**Comment by pke** [comment] 2022-02-28 07:19
Cool! A little late for my project, but nice to see it ;)

**Comment by tagliala** [comment] 2022-02-28 10:12
Hi!

`no-parking` is part of FA6 Pro. FA6 Free users, **in a web application**, can achieve the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/29/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Closed by tagliala** 2022-02-28 10:12 UTC
Labels: new icon, Available in FA Pro, maps (category)
