### ISSUE TITLE
Icon Request: fa-firetruck

### ISSUE THREAD

**Issue by tomhrose** [FortAwesome/Font-Awesome#7067] opened 2015-07-29 03:39 UTC
Hello would it be possible to request a firetruck icon?  You can use this as a guide (it's one of my companies truck).  I would not include the company name or number on the image so it's generic for all to use:  https://www.facebook.com/ClarksSummitFireCompany/photos/a.583327718418006.1073741831.579775692106542/642413415842769/?type=3&theater

Thank you and please let me know if you have any questions.

**Comment by tagliala** [comment] 2015-07-29 08:45
duplicate of #5738, please +1 that request

closing here

**Closed by tagliala** 2015-07-29 08:45 UTC
