### ISSUE TITLE
Icon request: Medication/Pill

### ISSUE THREAD

**Issue by mfahner** [FortAwesome/Font-Awesome#11124] opened 2017-05-30 16:35 UTC
Hello,
Our company would like to request that FontAwesome, make a pill icon similar to the one attached.

![image](https://cloud.githubusercontent.com/assets/29067895/26594072/280becd2-451b-11e7-97c9-01e0599febb9.png)

Thanks,
Matt

**Comment by tagliala** [comment] 2017-05-30 16:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1778 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-30 16:38 UTC
