### ISSUE TITLE
Icon Request: fa-pokerchip

### ISSUE THREAD

**Issue by evydaemon** [FortAwesome/Font-Awesome#11803] opened 2017-11-25 15:14 UTC
simple single pokerchip from top, one-dimentional without value on top
something like this without the 1
http://cdn.onlinewebfonts.com/svg/img_549572.png

**Comment by tagliala** [comment] 2017-11-25 16:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1004, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-25 16:10 UTC
