### ISSUE TITLE
Icon Request: fa-bing

### ISSUE THREAD

**Issue by oil4lessllc** [FortAwesome/Font-Awesome#10224] opened 2016-11-15 00:29 UTC
Please be patient with me; I have asked for fa-bing before and the issue was closed.
I have looked; i cannot find fa-bing on our website or in ver 4.7.0 file.
Also, it does not work (no icon).
Thank you.

**Comment by oil4lessllc** [comment] 2016-11-15 00:31
sorry: "..on YOUR website.." instead of "..on OUR website..".

**Comment by tagliala** [comment] 2016-11-15 16:02
@oil4lessllc the issue was closed because it is a duplicate of #2499 and you should add a 👍  reaction to that request

Unfortunately the icon is not present at the moment in the set, #2499 is a request to add the icon in the set. If you need a `bing` icon in a short while, I should suggest you to [Customize Font Awesome](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome)

Closing here

**Closed by tagliala** 2016-11-15 16:02 UTC
