### ISSUE TITLE
new Font for Hacker Rank

### ISSUE THREAD

**Issue by JamesDaniel** [FortAwesome/Font-Awesome#10670] opened 2017-02-15 18:18 UTC
Hey, I was wondering if anyone was going to add an icon for Hacker Rank. That'd be great. Thanks.

**Comment by tagliala** [comment] 2017-02-15 22:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5702, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-15 22:45 UTC
