### ISSUE TITLE
Icon request: theatre

### ISSUE THREAD

**Issue by somenxavier** [FortAwesome/Font-Awesome#7334] opened 2015-08-28 18:52 UTC
Is it possible to put threatic (plays)

**Comment by caduvieira** [comment] 2015-09-02 17:39
dupe of #1987 ?

**Comment by tagliala** [comment] 2015-09-14 06:22
any example?

**Comment by somenxavier** [comment] 2015-09-14 07:40
Yes, It could be like this: https://pixabay.com/es/etapa-teatro-mostrar-158366/

**Comment by tagliala** [comment] 2015-09-14 08:05
Ok, duplicate of #1987. Closing here. Add theatre in #1987 title

**Closed by tagliala** 2015-09-14 08:05 UTC
Labels: waiting for feedback
