### ISSUE TITLE
Icon request: oasis

### ISSUE THREAD

**Issue by khoanguyen123** [FortAwesome/Font-Awesome#8069] opened 2015-12-02 23:58 UTC
Something like this:

![places_and_locations_oasis-512](https://cloud.githubusercontent.com/assets/6828860/11548030/90b0025c-9926-11e5-8f01-db5495175fe6.png)

**Comment by tagliala** [comment] 2015-12-03 09:01
I'm going to consider this a duplicate of #3786 , please + that request

closing here

**Closed by tagliala** 2015-12-03 09:01 UTC
