### ISSUE TITLE
Icon request: icon-chip

### ISSUE THREAD

**Issue by naluoli** [FortAwesome/Font-Awesome#12461] opened 2018-02-26 23:35 UTC
### What can it be used for?

Gambling, poker, games, chance

### Example image (optional)
Couple of examples

![image](https://user-images.githubusercontent.com/36716550/36702075-7e63c7ce-1b0a-11e8-8a6b-281dbe46029b.png)
![image](https://user-images.githubusercontent.com/36716550/36702101-9677fe48-1b0a-11e8-98b9-3d77d01b17b2.png)

### Icon request checklist

- [single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [yes ] I have included at least one example image if it could be helpful (optional)
- [ yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-02-28 13:33
duplicate of #1004

**Closed by tagliala** 2018-02-28 13:33 UTC
