### ISSUE TITLE
Icon request: Science

### ISSUE THREAD

**Issue by diff-** [FortAwesome/Font-Awesome#7235] opened 2015-08-14 14:06 UTC
Take a look at these pictures, please:

![physics](https://cloud.githubusercontent.com/assets/7093244/9275572/3656cb8e-42b3-11e5-8147-d55f9d8a87fa.png) , ![chemistry](https://cloud.githubusercontent.com/assets/7093244/9275573/365b41e6-42b3-11e5-9ea7-5ae2ff68eda7.png) , ![biology](https://cloud.githubusercontent.com/assets/7093244/9275574/365e8f04-42b3-11e5-9753-afdc59b4a83c.png) , ![lab](https://cloud.githubusercontent.com/assets/7093244/9275575/366ae3e4-42b3-11e5-90f5-e01ecdfee037.png)

Physics , Chemistry , Biology , Laboratory

- What about geology, mathematics, philosophy and engineering?!

**Comment by caduvieira** [comment] 2015-08-14 14:19
Dupe of icon-atom #664 
Flask: http://fontawesome.io/icon/flask/
Dupe of icon-DNA: #1195 
Dupe of icon-microscope: #515
Related to #5190

**Comment by tagliala** [comment] 2015-08-14 15:56
@caduvieira thanks!

All dups, and flask is already here. closing here

**Closed by tagliala** 2015-08-14 15:56 UTC
