### ISSUE TITLE
Icon request: sheet-music-treble/bass

### ISSUE THREAD

**Issue by celebrir** [FortAwesome/Font-Awesome#16091] opened 2020-01-20 01:54 UTC
**What can it be used for?**
eg. for a repository of musical note sheets.
Yes, there is `file-music` but I want to distinguish between music files (like mp3) and music sheets and especially separate it for the female and male voices.
(choir website)

It's a matched pair with one having the treble "g" clef and the other the bass "f" cleff.

**Example image (optional)**
![generic](https://www.free-scores.com/IMG/claude-lachapelle/claude-lachapelle_20121203053958.jpg) ![iconscout](https://cdn.iconscout.com/icon/premium/png-256-thumb/music-note-10-530649.png)![music-document-interface-symbol-of-a-paper-sheet-with-a-musical-note-in-it-icon 1](https://user-images.githubusercontent.com/1256828/72692961-14ff5180-3b2f-11ea-9b94-030182811887.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment] 2024-07-11 16:46
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/11614)

**Closed by sensibleworld** 2024-07-11 16:46 UTC
Labels: new icon, music (category), Duplicate
