### ISSUE TITLE
Icon request: kettle (to boil water)

### ISSUE THREAD

**Issue by STiiTii** [FortAwesome/Font-Awesome#19913] opened 2023-09-28 14:01 UTC
### Use case

This icon could be used for hotel room equipment.

### Example image

![kettle](https://github.com/FortAwesome/Font-Awesome/assets/97702213/bb0e9903-3d49-430e-8b95-f3cd3dea809a)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment] 2024-07-11 14:35
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/6226)

**Closed as completed by sensibleworld** 2024-07-11 14:35 UTC
Labels: new icon, Duplicate
