### ISSUE TITLE
Icon request: search-within or search-file

### ISSUE THREAD

**Issue by jgrinsted** [FortAwesome/Font-Awesome#14379] opened 2018-12-10 21:01 UTC
### What can it be used for?

Indicating to a user that they are searching *within* a page, element, list, or document rather than searching globally or generally.

### Example image (optional)

Here's an example from Symbolicons Junior by Jory Raphael:

![search-inside example](https://cl.ly/9175da9378ea/Image%2525202018-12-10%252520at%2525203.55.38%252520PM.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-12-11 07:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6190, please add a 👍 reaction to that request.

You can implement this icon with the SVG framework and layering and masking features: 

https://jsfiddle.net/tagliala/wks0e6pa/50/

https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons
https://fontawesome.com/how-to-use/on-the-web/styling/masking

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

PS:

> Here's an example from Symbolicons Junior by Jory Raphael:

@sensibleworld 😉

**Closed by tagliala** 2018-12-11 07:53 UTC
