### ISSUE TITLE
Icon Request: fa-mental-health

### ISSUE THREAD

**Issue by cwilcoxc** [FortAwesome/Font-Awesome#10918] opened 2017-04-10 12:55 UTC
eg: http://www.cqc.org.uk/sites/all/themes/cqc/images/popular-services/mentalhealth_16_white.png

**Comment by tagliala** [comment] 2017-04-10 13:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8443, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-10 13:10 UTC
