### ISSUE TITLE
Icon Request : icon-user-admin

### ISSUE THREAD

**Issue by BadChoice** [FortAwesome/Font-Awesome#7674] opened 2015-10-14 14:44 UTC
http://www.wpeka.com/rgh/wp-content/uploads/2014/03/Changing-the-default-admin-user-in-WordPress1-460x575.jpg

**Comment by tagliala** [comment] 2015-10-14 14:54
duplicate of #3397, please +1 that request

closing here

**Closed by tagliala** 2015-10-14 14:54 UTC
