### ISSUE TITLE
Icon Request: fa-tooth

### ISSUE THREAD

**Issue by sbsmithjax** [FortAwesome/Font-Awesome#11994] opened 2017-12-26 14:57 UTC
Would love to see an FA icon for a tooth.

You already have several different body parts, this would be a great addition.  

Thank you, you guys are doing smashing great work.

Stephen

**Comment by tagliala** [comment] 2017-12-26 15:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1289 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-26 15:06 UTC
