### ISSUE TITLE
Suggestion : About auto copy font name on click

### ISSUE THREAD

**Issue by santbohara** [FortAwesome/Font-Awesome#10201] opened 2016-11-11 08:22 UTC
Isn't its better to copy (to clipboard) font name while clicking on Icon (instead of opening icon full details) ? 

Please don't call me lazy :) but it will be easy to copy paste name in project and save much times.

**Comment by tagliala** [comment] 2016-11-11 13:57
Duplicate of #1034, please +1 that request

Closing here

**Closed by tagliala** 2016-11-11 13:57 UTC
