### ISSUE TITLE
Icon request: icon-phpbb

### ISSUE THREAD

**Issue by rmcgirr83** [FortAwesome/Font-Awesome#10366] opened 2016-12-14 11:38 UTC
I see there is an icon for wordpress.  How about one for phpBB?

**Comment by tagliala** [comment] 2016-12-14 13:34
Duplicate of #1883, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-14 13:34 UTC

**Comment by rmcgirr83** [comment] 2018-01-19 10:09
Apparently it takes longer than 4 years to get icons included?  Not sure why people waste their time in making requests if they are never fulfilled.
