### ISSUE TITLE
Icon request: fa-openoffice

### ISSUE THREAD

**Issue by F0urchette** [FortAwesome/Font-Awesome#8467] opened 2016-01-31 11:50 UTC
Can you please include OpenOffice's logo ? I plan using it on my resume on Internet. Here is an image of the logo.
![orb](https://cloud.githubusercontent.com/assets/16985364/12701940/228d2bfc-c819-11e5-91a8-48146db1b347.jpg)

**Comment by tagliala** [comment] 2016-01-31 15:44
duplicate of #3661, please +1 that request

closing here

**Closed by tagliala** 2016-01-31 15:44 UTC

**Comment by aethior** [comment] 2016-02-01 17:09
Hi @tagliala,

I think this suggestion is a brand icon request `fa-openoffice` and #3661 is a file type request `fa-file-odt-o`.

**Comment by tagliala** [comment] 2016-02-01 18:30
@aethior thanks.

title and example didn't match

let's use #3661 for the brand and #4000 for odt
