### ISSUE TITLE
Icon request: fa-tub

### ISSUE THREAD

**Issue by DerZolf** [FortAwesome/Font-Awesome#9742] opened 2016-08-11 20:06 UTC
We need an icon for bathtub to use it on a Real Estate site.

Icons like this:

![shower and tub-64](https://cloud.githubusercontent.com/assets/20977506/17602964/450445ce-600f-11e6-9cf7-7bfd068de371.png)

**Comment by tagliala** [comment] 2016-08-11 20:38
Duplicate of #708, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-11 20:38 UTC
