### ISSUE TITLE
Icon Request: the MODX CMS/CMF logo

### ISSUE THREAD

**Issue by bertoost** [FortAwesome/Font-Awesome#3506] opened 2014-05-22 09:14 UTC
Like others as Wordpress or Joomla (bleh!) it would be great to have the MODX logo also included in the icons. Since the new upcoming major version of MODX also uses FontAwesome icons!

The original logo can be found here:
http://modx.com/assets/i/logos/modx-logo-color.png
Black version:
http://modx.com/assets/i/logos/modx-logo-black-transparent.png

Thanks in advance!

@modxcms

**Comment by jaygilmore** [comment] 2015-08-27 14:47
I think this should be merged with #3455 as it's in the proper format per the instructions for font requests. @bertoost

**Comment by shabang** [comment] 2015-08-28 07:18
+1

**Comment by stalemate-resolution-associate** [comment] 2015-08-29 02:04
+1

**Comment by Jcr3** [comment] 2015-09-29 07:00
+1

**Comment by tagliala** [comment] 2015-09-29 07:33
is this a duplicate of #3455 ?

**Comment by zaigham** [comment] 2015-09-29 14:58
@tagliala Yes, this is duplicate of #3455.

**Comment by tagliala** [comment] 2015-09-29 16:03
So closing here in favour of #3455

Please +1 that request

Please also mention me if you find an open duplicate

**Closed by tagliala** 2015-09-29 16:03 UTC
Labels: brand icons, new icon, waiting for feedback
