### ISSUE TITLE
Icon fa-user-lock not visible (Version Free 5.15.3)

### ISSUE THREAD

**Issue by unol** [FortAwesome/Font-Awesome#17969] opened 2021-06-02 10:08 UTC
Hey,
Im using Font Awesome Free 5.15.3 and the icon <i class="fas fa-user-lock"></i> is not visible. Other icons are working fine.

**Comment by tagliala** [comment] 2021-06-02 11:03
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, can't reproduce.

Demo: https://jsfiddle.net/tagliala/ajLpzuf8/4/

[fa-user-lock](https://fontawesome.com/v5.15/icons/user-lock?style=solid) has been introduced in Font Awesome 5.9.0.

Please make sure that you are using FA >= 5.9.0

Please also double check that there aren't third-party plugins/themes/libraries loading an older version of Font Awesome that may have priority over yours

If you are still experiencing this issue, please open a new request, fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md), and provide a reproducible test case

Hope it helps

Closing here

Ref: 
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Closed by tagliala** 2021-06-02 11:03 UTC
