### ISSUE TITLE
Icon request: icon-can

### ISSUE THREAD

**Issue by mrdink** [FortAwesome/Font-Awesome#15517] opened 2019-09-11 16:09 UTC
**What can it be used for?**
This would be great for breweries or to depict a use for recycling.

**Example image (optional)**
![thin-0862_soda_coke_pepsi_can-512](https://user-images.githubusercontent.com/514751/64714750-26ec2c00-d48d-11e9-87b1-69b808822e7f.png)

**Comment by tagliala** [comment] 2019-09-12 07:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9217, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-12 07:09 UTC
