### ISSUE TITLE
Jquery Icons not available on font awesome 6.1.0

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#18833] opened 2022-03-18 14:56 UTC
I would really like it if jquery brand icon(s) is made available on font awesome

**Comment by tagliala** [comment] 2022-03-18 15:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1665, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-03-18 15:47 UTC
