### ISSUE TITLE
Icon Request: fa-older

### ISSUE THREAD

**Issue by heiyaz** [FortAwesome/Font-Awesome#11372] opened 2017-08-08 01:48 UTC
Icon did not find the logo of the elderly, want to add one

![older](https://user-images.githubusercontent.com/8477970/29052757-b42580c2-7c1e-11e7-95eb-621e7d07da78.png)

**Comment by tagliala** [comment] 2017-08-08 07:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7183, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-08 07:27 UTC
