### ISSUE TITLE
Icon Request: fa-forklift

### ISSUE THREAD

**Issue by bwhite71** [FortAwesome/Font-Awesome#11083] opened 2017-05-18 02:23 UTC
Hello, I would like to request a forklift icon to be used for our logistics web application.  This would be used to indicate the loading or unloading of freight.  This icon would be used within a service flow (i.e. fa-truck -> fa-forklift (i.e. load) -> fa-plane).

Thank you,
Brian

**Comment by tagliala** [comment] 2017-05-18 08:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #692, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-18 08:34 UTC
