### ISSUE TITLE
Icon request: Chauffer

### ISSUE THREAD

**Issue by Emobe** [FortAwesome/Font-Awesome#18001] opened 2021-06-12 14:51 UTC
**What can it be used for?**
Chauffer related services

**Example image (optional)**
https://e7.pngegg.com/pngimages/283/2/png-clipart-chauffeur-computer-icons-taxi-driver-driving-photography-thumbnail.png

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-06-12 15:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7743, please add a 👍 reaction to that request. I'm going to add chauffer to the title for future searches

Closing here

**Closed by tagliala** 2021-06-12 15:14 UTC

**Comment by Emobe** [comment] 2021-06-12 15:17
Thanks! I was wondering why there was no "chauffer" but i didn't search for driver.
