### ISSUE TITLE
Icon Request: fa-checking

### ISSUE THREAD

**Issue by lhoezee** [FortAwesome/Font-Awesome#10324] opened 2016-12-06 20:49 UTC
I was looking for an icon to represent another payment option. Currently there are 12 payment icons with Font Awesome, however I don't see a "Check" image. This would be nice for banking applications. 

For example:
If I'm listing a users bank transactions and of the the transactions is a check. I'd like that check icon to be clickable.

Also a company could show the forms of payment they accept on their website.

The image here was something I found by doing a quick Google Image search. The pencil icon doesn't need to be there, but you get the idea...

![freebillpay](https://cloud.githubusercontent.com/assets/4121585/20942855/38997efe-bbcb-11e6-9a4b-895f827699eb.png)

**Comment by tagliala** [comment] 2016-12-07 00:05
Duplicate of #2603 , please add a 👍  reaction to that request and post there your example

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-07 00:05 UTC

**Comment by lhoezee** [comment] 2016-12-07 01:26
Wow.. how did I miss this when I searched! There are over 500+ results containing "check" haha :) Thanks.
