### ISSUE TITLE
Icon Request: icon-teamspeak

### ISSUE THREAD

**Issue by HadrienX** [FortAwesome/Font-Awesome#6601] opened 2015-05-30 21:23 UTC
Hello,
I'm a webdesigner, and I use a lot your awesome icons, they are very useful, thanks again.
On many projects, I use icon to show a network, and a lot of people use TeamSpeak.
Unfortunately, you didn't include this icon.
![teamspeak-icon](https://cloud.githubusercontent.com/assets/5130572/7899423/92424f12-0722-11e5-8b99-8bba5506ae64.jpg)
![teamspeak-original](https://cloud.githubusercontent.com/assets/5130572/7899424/9249b8e2-0722-11e5-86ff-b9914c2b7249.png)

I attached the original icon, and the icon you may use.
Thanks again for your work !

Hadrien Rannou, from Brittany, France.

**Comment by tagliala** [comment] 2015-05-30 21:46
duplicate of #1474 , please +1 that request

closing here

**Closed by tagliala** 2015-05-30 21:46 UTC
