### ISSUE TITLE
Icon Request: fa-footprint

### ISSUE THREAD

**Issue by bbolcsa** [FortAwesome/Font-Awesome#19024] opened 2022-05-09 08:19 UTC
Please create an icon for us with the attached graphics.
We would like to use it on csempe-shop.hu as an icon for "non slippery"

![noun-footprint-1013396](https://user-images.githubusercontent.com/105200693/167369295-42558f07-7a20-4447-9ad6-9e8d5e0accdf.svg)

**Comment by tagliala** [comment] 2022-05-09 08:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2140, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-05-09 08:42 UTC
