### ISSUE TITLE
Icon Request: fa-user-suit

### ISSUE THREAD

**Issue by Stormcloud** [FortAwesome/Font-Awesome#8312] opened 2016-01-12 06:25 UTC
A standard user icon wearing a business suit, similar to fa-user-secret ( https://fortawesome.github.io/Font-Awesome/icon/user-secret ), but without the hat, glasses and upturned flap.

Meant to signify a business person or consultant.

**Comment by tagliala** [comment] 2016-01-12 10:04
duplicate of #3397 , please +1 that request

closing here

**Closed by tagliala** 2016-01-12 10:04 UTC
