### ISSUE TITLE
Icon Request: fa-alipay

### ISSUE THREAD

**Issue by weihongyu12** [FortAwesome/Font-Awesome#11067] opened 2017-05-16 06:17 UTC
![alipay](https://cloud.githubusercontent.com/assets/19792747/26092240/6bacfda2-3a42-11e7-8174-7d32325229d0.png)

Alipay is the most widely used payment platform in China, and I hope that fa can provide an icon and use it with the payment icons

**Comment by tagliala** [comment] 2017-05-16 17:18
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3854, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-16 17:18 UTC
