### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by MuhammadNCheema** [FortAwesome/Font-Awesome#10781] opened 2017-03-12 08:32 UTC
lightbulb-turned-on
![lightbulb-icon-png-effects-17 1](https://cloud.githubusercontent.com/assets/26357616/23830253/402e92fa-0728-11e7-8cd0-db0634f8e87a.png)

**Comment by tagliala** [comment] 2017-03-12 08:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2817, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-12 08:42 UTC
