### ISSUE TITLE
Icon Request: fa-curch

### ISSUE THREAD

**Issue by ijakic** [FortAwesome/Font-Awesome#9869] opened 2016-09-06 15:59 UTC
Curch icon for web page

**Comment by tagliala** [comment] 2016-09-06 17:49
Duplicate of #2088 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-06 17:49 UTC

**Comment by ijakic** [comment] 2016-09-06 18:53
I agree, and I apologize to my rashness.
