### ISSUE TITLE
Icon Request: fa-handshake

### ISSUE THREAD

**Issue by geert-haegens** [FortAwesome/Font-Awesome#9055] opened 2016-04-25 11:45 UTC
hi,
can a handshake icon be added to your collection ?

![handshake1](https://cloud.githubusercontent.com/assets/18004489/14782811/defeeb08-0aeb-11e6-87a2-c9d092ee6d70.JPG)
![handshake2](https://cloud.githubusercontent.com/assets/18004489/14782815/e6a6dffa-0aeb-11e6-8e4a-6062027dec9f.JPG)

**Comment by tagliala** [comment] 2016-04-25 11:49
Duplicate of #878 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-25 11:49 UTC
