### ISSUE TITLE
Icon Request: fa-teamviewer

### ISSUE THREAD

**Issue by Dulcin** [FortAwesome/Font-Awesome#12211] opened 2018-02-01 13:40 UTC
So similar to the social media icons, a [teamviewer icon](https://tv-static.net/c3613269c72c44b18f3c68b43fc13018/resources/images/logos/teamviewer-icon-logo-big.svg
) would be nice. Teamviewer has an option to share your desktop through a web browser, and we use that option on our website so that we can walk clients through a presentation.

**Comment by tagliala** [comment] 2018-02-01 13:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5383 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-01 13:58 UTC
