### ISSUE TITLE
ICON REQUEST: FIVERR ICON

### ISSUE THREAD

**Issue by ideacoding101** [FortAwesome/Font-Awesome#17127] opened 2020-09-07 07:36 UTC
**What can it be used for?**
There's no icon for Fiverr and other freelancing platforms. It's very common for freelancers to have a website where we show our potrfolio. Not having any of this icons is not a good experience and having to use different icon libraries is pretty annoying. For examples, I need this icon to put it in py footer as a link to my Fiverr account. I've also seen that there's an older issue for it's from 2015, this is a strong need lots of freelancers have.
![fiverr-icon-0](https://user-images.githubusercontent.com/70473461/92360592-5a3bb800-f0ed-11ea-8dce-dd95b72c7825.png)

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [unlock] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-09-07 08:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5970, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-07 08:30 UTC
