### ISSUE TITLE
Icon Request: fa-raspberry-pi

### ISSUE THREAD

**Issue by tylerr514** [FortAwesome/Font-Awesome#11865] opened 2017-12-07 23:45 UTC
This could be a Brand icon for the Raspberry pi logo
![pi-v3](https://user-images.githubusercontent.com/22574513/33744331-c0a32d1c-db7e-11e7-8627-e99de303da9c.png)

**Comment by tagliala** [comment] 2017-12-08 00:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2944, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-08 00:10 UTC
