### ISSUE TITLE
Icon request: Sketchfab

### ISSUE THREAD

**Issue by maddisondesigns** [FortAwesome/Font-Awesome#20051] opened 2023-12-20 03:57 UTC
### Use case

Would love it you could add a Sketchfab logo, please. Sketch fab is the leading platform for 3D & AR. It allows creatives to manage their 3D assets, distribute 3D & AR experiences, as well as showcasing your work. It also allows people to buy & sell 3D models.

I've attached SVG versions of their logo.

### Example image

![Sketchfab-logo](https://github.com/FortAwesome/Font-Awesome/assets/2078245/b0b83f9f-5684-4ef9-b944-0fae4a51ad6e)

![sketchfab-logo-sml](https://github.com/FortAwesome/Font-Awesome/assets/2078245/9a1814af-f2a8-4ecd-a2e1-2dd568326861)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2023-12-20 07:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2757, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-12-20 07:03 UTC
Labels: new icon

**Comment by maddisondesigns** [comment] 2023-12-20 07:14
Thanks @tagliala. Will Do. I did perform a search before adding this request but nothing came up. Looking at the Title for #2757 I notice that it says `icon-sketchfab` instead of just `sketchfab`. It might be a good idea to change that Title to just 'sketchfab' since it doesn't currently return in the results when you perform a search for 'sketchfab' within all the Icon Requests.

I just noticed it also doesn't have the "new icon" label either.

<img width="915" alt="screenshot_1826" src="https://github.com/FortAwesome/Font-Awesome/assets/2078245/c73045de-e32e-4599-9869-bf41ec70de19">

**Comment by tagliala** [comment] 2023-12-20 07:22
Did you follow the search link from somewhere outside the template?

If it is the case, please let me know where

The problem in the search is with the "new icon" label, since this is a brand request. In fact, you did check

<img width="309" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/556268/01725cb6-8dcd-43b0-96ef-c200b39bdf08">


We have separate templates and labels for icon and brand requests

<img width="369" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/556268/635487e5-81d4-41a7-905b-9b31e2c234bc">

**Comment by maddisondesigns** [comment] 2023-12-20 07:25
@tagliala I followed the link from the official Font Awesome website. It's at the bottom of the [Leaderboard page](https://fontawesome.com/leaderboard/new).

<img width="900" alt="screenshot_1829" src="https://github.com/FortAwesome/Font-Awesome/assets/2078245/a6e22c26-fc84-4f50-bfc4-b8544d33b1c2">

**Comment by maddisondesigns** [comment] 2023-12-20 07:30
And apologies, but I didn't even notice the "Brand Request" issue button. I just noticed the "Icon Request" at the top of the list and clicked on that. It seems a bit silly having two separate requests when all that information could easily be added into the one request. If the field isn't relevant, such as the brand URL, then people wont fill it in.

**Comment by tagliala** [comment] 2023-12-20 07:36
No problem!

>  It seems a bit silly having two separate requests when all that information could easily be added into the one request.

For managing purposes, it is better to have two separate templates and two different labels, so we can also have two separate leaderboards:
- https://fontawesome.com/leaderboard/new
- https://fontawesome.com/leaderboard/brands

However, if this request was not a duplicate, I would have changed the label and the title, so even using a wrong template is not a problem
