### ISSUE TITLE
Icon request: escooter

### ISSUE THREAD

**Issue by achuinar** [FortAwesome/Font-Awesome#19110] opened 2022-06-09 01:29 UTC
### Use case

E-scooters are everywhere. This icon could be used on any content touching on new mobility modes.

### Example image

![image](https://user-images.githubusercontent.com/26856205/172744860-37f0af05-f3aa-4fab-b6fa-668b51de45c1.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2022-06-09 07:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15447, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-06-09 07:28 UTC
Labels: new icon
