### ISSUE TITLE
Icon Request: fa-hardhat (construction helmet)

### ISSUE THREAD

**Issue by spc197** [FortAwesome/Font-Awesome#5790] opened 2015-02-26 09:59 UTC
Please can we have an icon for a hard hat as used in construction

**Comment by rmtweb** [comment] 2015-02-26 11:05
+1

**Comment by groovy21** [comment] 2015-04-16 13:44
+1 really needed

**Comment by CountZachula** [comment] 2015-06-10 13:50
+1.

Sorry for the duplicate (#6704).

**Comment by jlr7245** [comment] 2015-06-10 20:02
+1 would love this icon. Something like this 
![image](https://cloud.githubusercontent.com/assets/12768542/8092760/276b4c6e-0f8a-11e5-9ac8-2bd3afd79a56.png)

**Comment by JuliaShier** [comment] 2015-06-30 20:54
+1 Please

**Comment by workmaster2n** [comment] 2015-06-30 21:22
+1 would love this

**Comment by cmeassociates** [comment] 2015-07-16 12:18
+1

**Comment by uducharm** [comment] 2015-08-01 17:47
+1

**Comment by jbonnier** [comment] 2015-09-27 21:30
+1

**Comment by forestmarie** [comment] 2015-10-21 14:29
+1

**Comment by caduvieira** [comment] 2015-11-25 16:19
dupe of #3934 ?

**Comment by ianbale** [comment] 2016-01-04 07:56
+1

**Comment by NinjaWaffles** [comment] 2016-01-10 05:26
+1

**Comment by Row-Z** [comment] 2016-01-20 19:39
+1

**Comment by ChanceDriven** [comment] 2016-02-26 21:02
+1

**Comment by chicagomom** [comment] 2016-03-01 14:59
+1

**Comment by vinnyamp** [comment] 2016-03-18 20:32
+1

**Comment by bulljustin** [comment] 2016-03-23 17:26
+1

**Comment by somereality** [comment] 2016-05-06 15:28
+1

**Comment by ffuentes** [comment] 2016-05-18 21:46
+1

**Comment by Melloyell** [comment] 2016-06-13 20:22
+1

**Comment by johnclittle** [comment] 2016-06-15 20:11
+1

**Comment by pewtel** [comment] 2016-07-09 23:43
+1

**Comment by iLovebooks100per** [comment] 2016-09-02 21:39
+1

**Comment by debaugh** [comment] 2016-09-03 18:16
+1

**Comment by MackieeE** [comment] 2016-09-07 14:29
+1 for weight :)

**Comment by progietheus** [comment] 2016-09-07 18:35
+1 we need this!

**Comment by Crissov** [comment] 2016-11-14 23:11
Perhaps U+26D1 ⛑ in Unicode #222, not U+1F477 👷

**Comment by vsajja** [comment] 2016-11-16 10:18
+1,000,000,000

**Comment by samc449** [comment] 2017-05-11 13:18
+1

**Comment by HexDT** [comment] 2017-05-15 19:12
+1

**Comment by schowes** [comment] 2017-05-24 18:48
+1

**Comment by thomasbjorndahl** [comment] 2017-07-10 10:57
+1

**Comment by ksddearing** [comment] 2017-07-26 22:06
+1

**Comment by vheimpel** [comment] 2017-08-01 15:11
+1

**Comment by grafikat** [comment] 2017-08-18 15:17
+1

**Comment by grafikat** [comment] 2017-08-18 15:55
Here are a couple I drew up.

![constructionfa1](https://user-images.githubusercontent.com/8459555/29466756-584bd9ba-83fb-11e7-9be7-1b7083bcfddf.png)
![constructionfa2](https://user-images.githubusercontent.com/8459555/29466757-585083d4-83fb-11e7-95a2-e6219baab5d6.png)
![hardhaticonfa](https://user-images.githubusercontent.com/8459555/29466758-58537c88-83fb-11e7-8e07-63101d7a1c10.png)

**Comment by challe** [comment] 2017-10-20 12:10
+1

**Comment by admincotecnologias** [comment] 2017-11-01 22:16
+1

**Comment by xNicoPaz** [comment] 2017-11-10 17:53
+1

**Comment by ionutab** [comment] 2017-11-15 22:17
+1

**Comment by callkeeper** [comment] 2017-11-16 15:11
+1

**Comment by klb-rodriguez** [comment] 2017-11-17 16:29
+1

**Comment by zilhont** [comment] 2018-01-11 13:09
+1

**Comment by medez** [comment] 2018-01-15 12:03
+1

**Comment by yanfrank** [comment] 2018-02-25 01:24
+1

**Comment by parooninmaenmoukari** [comment] 2018-04-19 07:16
+1

**Comment by norcalfox** [comment] 2018-04-24 22:01
+1

**Comment by melksedeque** [comment] 2018-05-07 19:18
+1

**Comment by ilyankou** [comment] 2018-06-13 14:37
+1

**Comment by RocketMan777** [comment] 2018-06-29 23:42
+3

**Comment by deepjaisia** [comment] 2018-07-16 17:17
+1

**Comment by charlygut** [comment] 2018-07-19 14:53
+1 !!!

**Comment by castoldi** [comment] 2018-08-13 14:06
+1

**Comment by dgonzalezn** [comment] 2018-08-17 15:04
+1

**Comment by RabidPuffin** [comment] 2018-08-29 18:09
Oh man, for sure this.

**Comment by ATLAdamL** [comment] 2018-09-28 15:03
+1

**Comment by sensibleworld** [comment] 2019-01-29 12:42
We've added `hard-hat` to Font Awesome Free: https://fontawesome.com/icons/hard-hat?style=solid
And `user-hard-hat` to Font Awesome Pro: https://fontawesome.com/icons/user-hard-hat?style=solid

**Closed by sensibleworld** 2019-01-29 12:42 UTC
Labels: in progress, new icon, released, web application icons

**Comment by pieterdb4477** [comment] 2020-01-16 06:39
+1

**Comment by tagliala** [comment] 2020-01-16 09:03
@pieterdb4477 https://fontawesome.com/icons/hard-hat?style=solid

Just make sure you are using Font Awesome >= 5.7.0
