### ISSUE TITLE
Icon Request: fa-askfm

### ISSUE THREAD

**Issue by Eiskaltereistee** [FortAwesome/Font-Awesome#9605] opened 2016-07-20 17:17 UTC
http://ask.fm/

**Comment by tagliala** [comment] 2016-07-20 21:26
Duplicate of #3762, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-20 21:26 UTC
