### ISSUE TITLE
Icon request: fa-line

### ISSUE THREAD

**Issue by KazuyoshiTsuchiya** [FortAwesome/Font-Awesome#8901] opened 2016-04-06 13:45 UTC
LINE users are 22 million people in Japan. And it has more than 2 billion people in the world. It is expanding in Asia.

![aaso4sy](https://cloud.githubusercontent.com/assets/12079595/14318605/a3580ed8-fc48-11e5-884e-9c90f3536f24.png)

**Comment by tagliala** [comment] 2016-04-06 13:48
Duplicate of #2631 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-06 13:48 UTC

**Comment by KazuyoshiTsuchiya** [comment] 2016-04-06 14:00
Oh! I'm so sorry!
