### ISSUE TITLE
Icon Request: mySQL

### ISSUE THREAD

**Issue by Nojil** [FortAwesome/Font-Awesome#13196] opened 2018-05-23 14:28 UTC
Used when creating a personal profile website and detailing your skills.

![mysql](https://user-images.githubusercontent.com/11978772/40430854-46e62868-5e63-11e8-9fac-920ee4ef5237.png)

**Comment by tagliala** [comment] 2018-05-23 21:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6052, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-23 21:15 UTC
