### ISSUE TITLE
Is CDN Asynchronous mode conflicting with other frameworks?

### ISSUE THREAD

**Issue by hakuseki** [FortAwesome/Font-Awesome#9168] opened 2016-05-11 06:19 UTC
Hi

When using Async mode in CDN the icons is not loaded and we see errors in console (not related to icons).
We think it might be a conflict with either Dojo or jQuery which we use.

Please advice

/M

**Comment by Archie22is** [comment] 2016-05-11 12:29
Just out of curiosity, can you share the console log screen showing the list of errors?

**Comment by hakuseki** [comment] 2016-05-11 12:32
`dojo.js:15 Error: multipleDefine
    at _f (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:436)
    at _f9 (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:16129)
    at http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:16717
    at _9 (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:328)
    at _7e (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:16687)
    at _f4 (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:15216)
    at Function.req.getText (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:3020)
    at _32 (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:15776)
    at _24e (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:53213)
    at Object.$DDWJ_ [as require] (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:53512)`

**Comment by hakuseki** [comment] 2016-05-12 12:06
If I load FA before jQuery I get these errors:

`dojo/parser::parse() error TypeError: Cannot read property '_noScript' of undefined
    at Object.$DDSw_ [as scan] (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/ibm/xsp/widget/layout/layers/xspClientDojo.js:5:15803)
    at http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/ibm/xsp/widget/layout/layers/xspClientDojo.js:5:17657
    at _45c (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:118591)
    at Promise.then._469.then (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:120499)
    at Object.$DDSz_ [as parse] (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/ibm/xsp/widget/layout/layers/xspClientDojo.js:5:17629)
    at http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:104362
    at Function.$DDcf_ [as _onQEmpty] (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:147259)
    at _3ba (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:100275)
    at HTMLDocument.$DDP4_ (http://10.211.55.4/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js:15:100472)`

**Comment by hakuseki** [comment] 2016-05-12 12:12
head without Async…
```html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title></title>
<script type="text/javascript">var dojoConfig = {locale: 'sv', parseOnLoad: true};</script>
<script type="text/javascript" src="/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js"></script>
<script type="text/javascript" src="/xsp/.ibmxspres/dojoroot-1.9.7/ibm/xsp/widget/layout/layers/xspClientDojo.js"></script>
<script type="text/javascript">dojo.require("dojo.parser")</script>
<meta name="Cache-Control" content="no-cache">
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans%3A400italic%2C400%2C600%7CInconsolata">
<script type="text/javascript" src="https://use.fontawesome.com/01afa80dfc.js"></script><link href="http://use.fontawesome.com/01afa80dfc.css" media="all" rel="stylesheet">
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<script type="text/javascript">dojo.require("dojox.widget.Standby")</script>
<script type="text/javascript">dojo.registerModulePath("extlib", "/xsp/.ibmxspres/.extlib");</script>
<script type="text/javascript">dojo.require("extlib.dijit.Menu")</script>
<script type="text/javascript">dojo.require("extlib.dijit.OneUINavigator")</script>
<script type="text/javascript">dojo.require("dojo.fx")</script>
<script type="text/javascript">dojo.require("dijit.Toolbar")</script>
<script type="text/javascript">dojo.require("dijit.form.Button")</script>
<script type="text/javascript">dojo.require("extlib.dijit.OneUIDialog")</script>
<meta name="d41d8cd98f00b204e9800998ecf8427e_lib_detect" id="d41d8cd98f00b204e9800998ecf8427e_lib_detect" content="jQuery:2.2.2,Dojo:1.9.7-20150127-IBM (2dfbbaf)">
`

**Comment by hakuseki** [comment] 2016-05-12 12:16
head with Async
```html
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title></title>
<script src="http://use.fontawesome.com/webfontloader/1.6.24/webfontloader.js"></script><script type="text/javascript">var dojoConfig = {locale: 'sv', parseOnLoad: true};</script>
<script type="text/javascript" src="/xsp/.ibmxspres/dojoroot-1.9.7/dojo/dojo.js"></script>
<script type="text/javascript" src="/xsp/.ibmxspres/dojoroot-1.9.7/ibm/xsp/widget/layout/layers/xspClientDojo.js"></script>
<script type="text/javascript">dojo.require("dojo.parser")</script>
<meta name="Cache-Control" content="no-cache">
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans%3A400italic%2C400%2C600%7CInconsolata">
<script type="text/javascript" src="https://use.fontawesome.com/01afa80dfc.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<script type="text/javascript">dojo.require("dojox.widget.Standby")</script>
<script type="text/javascript">dojo.registerModulePath("extlib", "/xsp/.ibmxspres/.extlib");</script>
<script type="text/javascript">dojo.require("extlib.dijit.Menu")</script>
<script type="text/javascript">dojo.require("extlib.dijit.OneUINavigator")</script>
<script type="text/javascript">dojo.require("dojo.fx")</script>
<script type="text/javascript">dojo.require("dijit.Toolbar")</script>
<script type="text/javascript">dojo.require("dijit.form.Button")</script>
<script type="text/javascript">dojo.require("extlib.dijit.OneUIDialog")</script>
</head>
`

**Comment by hakuseki** [comment] 2016-05-12 12:18
With Async:
![image](https://cloud.githubusercontent.com/assets/5478862/15214236/45ec56da-184c-11e6-9fbf-c55e629d161b.png)

Without Async:
![image](https://cloud.githubusercontent.com/assets/5478862/15214284/6e5b650c-184c-11e6-80f0-4250009cd57c.png)

**Comment by hakuseki** [comment] 2016-06-10 04:09
Anymore on this?

**Comment by hakuseki** [comment] 2016-07-05 17:42
ping ^^^

**Comment by tagliala** [comment] 2016-07-06 00:14
@robmadole

**Comment by robmadole** [comment] 2016-07-06 13:12
@hakuseki I'm looking at this now. The console stacktrace looks like it's the minified/uglified version. Would it be possible for you to get a stacktrace from source maps or the un-uglified code? I'm going to attempt to setup a codepen using Dojo and jQuery to reproduce this. I thought we had the async code fairly closed off :/

**Comment by robmadole** [comment] 2016-07-06 16:01
I am able to reproduce this. Looks like I'll need to convert the script to be AMD-compatible. I'll see if I can get this done this week.

**Comment by robmadole** [comment] 2017-06-05 15:21
We are going to include builds of Font Awesome 5 that will be compatible with other frameworks. For now I'm going to close this as we focus these efforts on the new version.

**Closed by robmadole** 2017-06-05 15:21 UTC
Labels: cdn, question
