### ISSUE TITLE
Icon request: fa-friends

### ISSUE THREAD

**Issue by r0bdiabl0** [FortAwesome/Font-Awesome#9803] opened 2016-08-24 14:37 UTC
We use to use a custom icon representing friendship for when someone has added another user as a friend. The image we used was 2 hands handshaking together.

Would love to see something like that on fa as it would be useful for friend and partner scenarios.
![request_friendship_or](https://cloud.githubusercontent.com/assets/432557/17934648/f038014a-69d5-11e6-8437-322c093875f1.png)

**Comment by tagliala** [comment] 2016-08-24 15:03
Duplicate of #5802  or #2883 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-24 15:03 UTC
