### ISSUE TITLE
Icon Request: user-ok

### ISSUE THREAD

**Issue by Jacco-V** [FortAwesome/Font-Awesome#9476] opened 2016-06-25 18:54 UTC
In addition to [`user`](http://fontawesome.io/icon/user/), [`user-times`](http://fontawesome.io/icon/user-times/) and [`user-plus`](http://fontawesome.io/icon/user-plus/), I would like to propose: `user-ok`

![user-ok](https://cloud.githubusercontent.com/assets/19333579/16358570/f93226b0-3b16-11e6-85ce-a374dedb07ba.png)

**Comment by tagliala** [comment] 2016-06-25 19:16
Duplicate of #6053, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

Ref: #1181

**Closed by tagliala** 2016-06-25 19:16 UTC
