### ISSUE TITLE
SVG Sprites are sized differently than their Font counterpart.

### ISSUE THREAD

**Issue by Nooobody** [FortAwesome/Font-Awesome#15818] opened 2019-11-16 03:01 UTC
**Describe the bug**
What happened? What are you seeing? How did you arrive here?

SVG Sprites are sized differently than their Font counterpart.

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

https://codepen.io/Nooobody/pen/YzzRLaP
Basically, the SVG's use element always makes the icon a tad smaller than the svg element itself. One other curious thing is that the font icon always overflows the i element.

**Expected behavior**
How would you like this to work instead?

Both font icon and svg sprite should be the same size.

**Screenshots**

https://imgur.com/L6G95I9
Here the bitcoins seem like they're identical, but the SVG is 4px smaller. On the balance-scale, it's more noticeable.

**Version and implementation**
Version: fontawesome-free-5.11.2-web
Browser and version: 

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [x] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2019-11-16 06:31
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome icons have not the same width by design choice, so if you set `width: 1em`, you are forcing some icons to have a smaller size than they are expected to have

Please try with
```
svg, i {
  height: 1em;
  font-size: 2em!important;
  vertical-align: middle;
}
```
Demo: https://codepen.io/tagliala/pen/xxxQzaO

You can assume that this works for some other icons, example: https://codepen.io/tagliala/pen/rNNQKqV

Hope it helps

Closing here, but feel free to comment

**Closed by tagliala** 2019-11-16 06:31 UTC

**Comment by Nooobody** [comment] 2019-11-16 07:51
Thanks, that helped with the balance scale. However, the issue persists for some icons like the bitcoin.

I'm using the /sprite SVGs in my project, so I have to wrap them with svg>use. This creates some issues with the width of the element if there's no viewBox. 

But for the bitcoin, it does this:
https://imgur.com/9cDfLLE

The svg element is 112x112, but for some reason it tries to scale down the inner element even though the svg element's width is set to auto.

The same setup works perfectly for the balance-scale, if supplied with the same viewBox that it has in the spritesvg file.

Please advise.
