### ISSUE TITLE
Icon request: Yoga

### ISSUE THREAD

**Issue by aggie1288** [FortAwesome/Font-Awesome#16184] opened 2020-02-12 09:12 UTC
**What can it be used for?**
I want a single icon to replace the "lock" icon that is on the checkout button for a website. A women's yoga pose would be perfect!

**Comment by tagliala** [comment] 2020-02-18 23:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6032, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-02-18 23:09 UTC
