### ISSUE TITLE
Icon request: icon-measure

### ISSUE THREAD

**Issue by DimitriXs** [FortAwesome/Font-Awesome#11402] opened 2017-08-14 17:20 UTC
was looking for an icon regarding haute couture, dresses, and measure. I would love if you could add some relevant icons to this. I am attaching you an icon i would do myself for the 
![mesure](https://user-images.githubusercontent.com/31009201/29283129-f9d77364-812d-11e7-9af5-a5a6844531a2.png)
![size-512](https://user-images.githubusercontent.com/31009201/29283130-fa2b714e-812d-11e7-8704-2d1b2755fa94.png)

**Comment by tagliala** [comment] 2017-08-14 19:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of ##8437, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-14 19:20 UTC

**Comment by DimitriXs** [comment] 2017-08-16 11:24
Hey, thx for the prompt reply. 
Its kinda hard to search all the way back all the previous requests… Let me know if there’s anything I can do to help/speed up processes. i.e. specs you want this icon, to make it for you, etc.
best, 
Dimitri

**Comment by tagliala** [comment] 2017-08-16 11:49
> Let me know if there’s anything I can do to help/speed up processes. i.e. specs you want this icon, to make it for you, etc.
best,

Hi, unfortunately you can't. If you need this icon, the best you can do is to customize font awesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by DimitriXs** [comment] 2017-08-16 16:19
I made it an SVG, and inserted it at fontello. I ‘m attaching you the sag, and have downloaded the relevant fontello folder, should it help in anyway, let me know so I can also fwd it to you.

let me know if you can insert it in the fa-icons
rgds, 
Dimitri

**Comment by DimitriXs** [comment] 2017-08-17 09:47
Hey, I am not a programer (evidently) but have serious graphics background. 
I made an SVG file and uploaded it to Fontello, but my site is based on fa-. Meaning that I ll have to add css etc from fontello, which is only gonna slow down my website, unless I switch completely to fontello, which I have no reason to, do just for an icon i designed…
Is there any fast way to include the icon i offer you, and since there isn’t any relevant one to keep it if you like it in your fa list?
Please advice.
rgds, 
Dimitris

**Comment by tagliala** [comment] 2017-08-17 12:17
> Is there any fast way to include the icon i offer you, and since there isn’t any relevant one to keep it if you like it in your fa list?

Nope, sorry. As per contributing guidelines, we are not accepting PR containing icons

A custom version of Font Awesome is the best you can do at the moment

**Comment by DimitriXs** [comment] 2017-08-17 12:34
Tx, I understand your policy, and I would go for the “custom version", but its not worth paying a subscription for just using a single icon…  :-(  I will either give up, or go with fontello an replace all fa icons..

Last question: Any prediction as to when to expect a similar fa-icon? 
(Are we talking about a month, or a year?)
rgds, D/
