### ISSUE TITLE
Icon request: icon-times-thin

### ISSUE THREAD

**Issue by homerjam** [FortAwesome/Font-Awesome#5423] opened 2015-01-18 20:10 UTC
I haven't supplied artwork but imagine a `icon-times` with the weight of `icon-angle-down/up`, that's sexy.

**Comment by homerjam** [comment] 2015-01-21 11:25
Bonus idea: `fa-thin` which uses `font-weight` to select a thinner glyph

**Comment by knownasilya** [comment] 2015-03-09 17:13
:+1: that was exactly what I was about to suggest.. because this looks quite ugly:

![screen shot 2015-03-09 at 1 12 56 pm](https://cloud.githubusercontent.com/assets/34726/6560114/09ded532-c65e-11e4-8682-588414fb8e19.png)

**Comment by vmasto** [comment] 2015-03-09 22:24
+1

**Comment by tagliala** [comment] 2015-03-10 12:00
duplicate of #1540 , please +1 that request

closing here

**Closed by tagliala** 2015-03-10 12:00 UTC

**Comment by tagliala** [comment] 2015-03-10 12:01
@homerjam your are referring to #1733 (it neesd a whole new set of icons)
