### ISSUE TITLE
Icon request: icon-broom

### ISSUE THREAD

**Issue by NicholasSiebert** [FortAwesome/Font-Awesome#10835] opened 2017-03-23 15:11 UTC
I need this Broom icon for a website I'm creating for a school project, I tried making it myself but the picture always turns out blurry.

If this icon can be created quickly it would be greatly appreciated.
My school project is that I have to create a business and I have but I took it one step further by creating a fully functional website. With this icon I'm gonna place it besides the "Clean Up" subtitle under the services my business does because I already have fa-trash beside "Garbage Disposal" the fa-paint-brush beside "Painting" and a few more.

Thank you!
![neat-512](https://cloud.githubusercontent.com/assets/26628840/24254507/7a59f58e-0fb9-11e7-99fa-4c7cb5371151.png)

**Comment by PeterShaggyNoble** [comment] 2017-03-23 15:14
Dupe of #239; you should add your 👍 to that.

**Comment by PeterShaggyNoble** [comment] 2017-03-23 15:18
I mean this request is a duplicate of an existing request - the icon has not yet been added.

**Comment by NicholasSiebert** [comment] 2017-03-23 15:19
I see

**Closed** 2017-03-23 15:58 UTC
