### ISSUE TITLE
Icon request: icon-diving

### ISSUE THREAD

**Issue by Dupindupin** [FortAwesome/Font-Awesome#6644] opened 2015-06-03 08:05 UTC
Icon request: icon-diving_silhouett 
![diving_silhouette_64](https://cloud.githubusercontent.com/assets/12727135/7955356/636aba1a-09e0-11e5-93f3-9f07ec95028d.png)

**Comment by ShamanFromSiberia** [comment] 2015-07-01 07:49
+1

**Comment by repat** [comment] 2017-08-03 12:28
+1

**Comment by nj167252** [comment] 2018-11-13 12:50
+1

Something like the NCAA diving logo would be great
![untitled_1](https://user-images.githubusercontent.com/16868815/48414432-65bd3280-e753-11e8-969d-27fadd901130.jpg)

**Comment by repat** [comment] 2018-11-13 13:15
Is this not a request for _scuba_ diving?

**Comment by nj167252** [comment] 2018-11-13 19:31
Oh, sorry about that. Thanks for pointing that out @repat

**Comment by sebastian-estudiob** [comment] 2018-12-18 16:41
+1

**Comment by sebastian-estudiob** [comment] 2018-12-18 16:44
![captura de pantalla 2018-12-18 a la s 13 43 14](https://user-images.githubusercontent.com/14235651/50168780-f9da6680-02ca-11e9-9dcb-95056e9bcf15.png)


like this.

**Comment by Dupindupin** [comment] 2018-12-19 10:57
Yes very nice

**Comment by aethior** [comment] 2022-05-06 23:51
Duplicate of #6448.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-05-07 11:03
Let's use #6448. It has more upvotes. Will change the title by adding synonyms

**Closed by tagliala** 2022-05-07 11:03 UTC
Labels: new icon, sport (category)
