### ISSUE TITLE
Icon Request: fa-bing

### ISSUE THREAD

**Issue by oil4lessllc** [FortAwesome/Font-Awesome#10214] opened 2016-11-13 07:30 UTC
plese tell me why this is missing

**Comment by tagliala** [comment] 2016-11-13 18:35
Duplicate of #2499, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-13 18:35 UTC

**Comment by oil4lessllc** [comment] 2016-11-14 01:16
Please be advised that we searched for fa-bing and did not find it;
that is why we requested it.
  Thanks for the update; we will try it later.
