### ISSUE TITLE
Icon Request: fa-bow

### ISSUE THREAD

**Issue by codebae** [FortAwesome/Font-Awesome#10299] opened 2016-11-30 04:04 UTC
Bow icon keywords: special event, formal dress code, black tie event, party, social gathering, fancy attire, save the date, invitation

![bow](https://cloud.githubusercontent.com/assets/22390467/20739233/cd139938-b66d-11e6-89f2-42757ef90ee7.jpg)

**Comment by tagliala** [comment] 2016-11-30 21:34
Duplicate of #4786, please add a 👍  reaction to that request and post there your example

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-30 21:34 UTC
