### ISSUE TITLE
Icon request: icon-handshake

### ISSUE THREAD

**Issue by lyho** [FortAwesome/Font-Awesome#7975] opened 2015-11-25 03:19 UTC
Use cases:
_ To show 2 entities is having relationship
_ To show the contract has been signed
_ To show agreement has been agreed

Sample icon: https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/handshake.png

**Comment by coclav** [comment] 2015-11-25 09:24
+1

**Comment by aethior** [comment] 2015-11-25 09:45
Hi @lyho,

This suggestion is duplicate of #878. Please +1 that.

Regards.

**Comment by tagliala** [comment] 2015-11-25 12:57
thanks

closing here

**Closed by tagliala** 2015-11-25 12:57 UTC
