### ISSUE TITLE
Icon Request: fa-golf-cart

### ISSUE THREAD

**Issue by junedhub** [FortAwesome/Font-Awesome#11277] opened 2017-07-11 18:06 UTC
can you please build this icon.
This to denote **Golf** related club/resorts.

Please consider attach image for reference/idea

![golfcart](https://user-images.githubusercontent.com/10570756/28082975-9f5be48a-6691-11e7-93f0-8e0d74e82581.png)

**Comment by tagliala** [comment] 2017-07-11 20:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10330, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-11 20:33 UTC
