### ISSUE TITLE
Icon Request: fa-key-modern

### ISSUE THREAD

**Issue by koup** [FortAwesome/Font-Awesome#8088] opened 2015-12-04 15:34 UTC
Hello Font Awesome Team

You do a great job. I would have liked a more modern icon for the key. the current icon looks a little antiquated. that's it. many thanks.

**Comment by tagliala** [comment] 2015-12-04 15:52
duplicate of #789, please +1 that request

closing here

**Closed by tagliala** 2015-12-04 15:52 UTC
