### ISSUE TITLE
Icon request: vultr

### ISSUE THREAD

**Issue by GlyphSH** [FortAwesome/Font-Awesome#18593] opened 2022-01-17 03:33 UTC
To advertise stacks used for web development or inform clients of specific options. Fairly similar to Digital Ocean.
![favicon](https://user-images.githubusercontent.com/56896608/149703829-2e4f6d13-a587-4e44-a823-1b267aaab6ae.png)

This issue has been properly formatted as per the latest rules. A duplicate exists, however it does not include the optional icon image, or a description for it's use-case. Reference: https://github.com/FortAwesome/Font-Awesome/issues/13205

**Comment by tagliala** [comment] 2022-01-17 08:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13205, please add a 👍 reaction to that request.

> A duplicate exists, however it does not include the optional icon image, or a description for it's use-case. Reference: #13205

Not a problem, just upvote that request 👍🏼 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-01-17 08:19 UTC
