### ISSUE TITLE
Icon request: fa-meter-slow, fa-meter-medium, fa-meter-fast

### ISSUE THREAD

**Issue by NielsHolt** [FortAwesome/Font-Awesome#13252] opened 2018-06-01 11:55 UTC
![image](https://user-images.githubusercontent.com/11357972/40839516-3985bd86-65a3-11e8-9f30-f31c46f2548a.png) ![image](https://user-images.githubusercontent.com/11357972/40839529-43ac5af4-65a3-11e8-9e6b-81cbd66fb3cf.png) ![image](https://user-images.githubusercontent.com/11357972/40839546-5290b9d4-65a3-11e8-8ca1-b164acf77a77.png)

**Comment by tagliala** [comment] 2018-06-01 13:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7884, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-01 13:51 UTC
