### ISSUE TITLE
Icon request: icon-disqus

### ISSUE THREAD

**Issue by UncaughtTypeError** [FortAwesome/Font-Awesome#9296] opened 2016-05-29 16:49 UTC
![disqus-icon](https://cloud.githubusercontent.com/assets/19621089/15634818/f782e8da-25cd-11e6-9959-ab4ac42385b1.png)

**Comment by tagliala** [comment] 2016-05-29 19:06
Duplicate of #2690 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-29 19:06 UTC

**Comment by UncaughtTypeError** [comment] 2016-05-29 21:52
Will do so in future, thank you.
