### ISSUE TITLE
Icon request: flip-horizontal

### ISSUE THREAD

**Issue by viking1972** [FortAwesome/Font-Awesome#16645] opened 2020-05-16 06:06 UTC
**What can it be used for?**
This icon can be used in an image editor for flipping an image or selection horizontal

**Example image (optional)**
![flip_horizontal](https://user-images.githubusercontent.com/18242813/82112253-8a7cd680-974b-11ea-8f55-e735c1c5fa9c.png)

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-16 09:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11624, please add a 👍 reaction to that request and post there your example

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-16 09:03 UTC
