### ISSUE TITLE
Icon Request: fa-spider

### ISSUE THREAD

**Issue by Suzdar** [FortAwesome/Font-Awesome#11613] opened 2017-10-11 12:38 UTC
a cool little mini spider. Can be used for Spider-bot websites

**Comment by PeterShaggyNoble** [comment] 2017-10-11 12:44
Duplicate of #828.

**Comment by sensibleworld** [comment] 2019-05-02 15:21
https://fontawesome.com/icons/spider?style=solid

**Closed by sensibleworld** 2019-05-02 15:21 UTC
