### ISSUE TITLE
Icon Request: fa-playstation

### ISSUE THREAD

**Issue by soulis3** [FortAwesome/Font-Awesome#10877] opened 2017-04-01 07:13 UTC

**Comment by tagliala** [comment] 2017-04-01 07:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1006 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-01 07:43 UTC
