### ISSUE TITLE
Icon request: icon-VR

### ISSUE THREAD

**Issue by gtroxell** [FortAwesome/Font-Awesome#10211] opened 2016-11-12 20:33 UTC
Generic icon for any type of device or app. 
![vr-icon](https://cloud.githubusercontent.com/assets/23423553/20240706/2188ee3e-a8ed-11e6-8d74-5897e1b39776.png)
![360-vr](https://cloud.githubusercontent.com/assets/23423553/20240711/317ffe90-a8ed-11e6-8e2d-c30aa18f206d.png)

Use case: quick reference links in website, google maps, html tables, and documents to indicate to viewers that a 360º Virtual Reality (VR) experience can begin by clicking the icon.

**Comment by LesDrones** [comment] 2016-11-12 21:45
+1 or [this](https://github.com/FortAwesome/Font-Awesome/issues/1043)

**Comment by tagliala** [comment] 2017-05-09 08:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6590, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-09 08:51 UTC
