### ISSUE TITLE
Facebook icon isn't working. Only Facebook. Others are OK.

### ISSUE THREAD

**Issue by erik-grigoryan** [FortAwesome/Font-Awesome#14433] opened 2018-12-21 10:31 UTC
Can you help me with this problem. I have social icons on my site, but only facebook icon from Font Awesome is not working...

**Comment by tagliala** [comment] 2018-12-21 13:10
Hi!

Thanks for being part of the Font Awesome Community.

Could you please try without browser extensions?

It could be an issue related to adblockers

Otherwise, please provide:

1. Font Awesome version
2. Browser version
3. OS version

or, better fill our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by erik-grigoryan** [comment] 2018-12-21 13:38
The problem is not only on my computer. Everywhere, where I open my site
FontAwesome 5.3.1
Google Chrome 71.0.3578.98
Windows 10

**Comment by tagliala** [comment] 2018-12-21 13:54
@erik-grigoryan could you please provide a link to your website or better a reduced test case on jsfiddle / codepen?

You can start with this one: https://jsfiddle.net/tagliala/j3gakye6/41/

**Comment by erik-grigoryan** [comment] 2018-12-21 13:56
https://aircairo.base.am/readera/

Look at the sidebar (follow me), or in footer.

**Comment by tagliala** [comment] 2018-12-23 12:46
@erik-grigoryan sorry for the very late reply

Your theme is loading Font Awesome from it own stylesheets

Please take a look at:
https://aircairo.base.am/readera/wp-content/themes/readera/libs/fontawesome-free-5.3.1-web/css/all.min.css?ver=5.0.2

There are no occurrencies of `fa-facebook-f`, please compare it with the css in our official CDN at https://use.fontawesome.com/releases/v5.3.1/css/all.css:

If you take a look at the source of your theme and search for `fa-facebook`, this is how it looks like:
![image](https://user-images.githubusercontent.com/556268/50383666-f4a95d00-06b8-11e9-8c0f-a76349adf1f0.png)

Please double check that the file has not been corrupted when uploading and if it has not been the case report the issue to your theme's author

Hope it helps 

Closing here

**Closed by tagliala** 2018-12-23 12:46 UTC
Labels: waiting for feedback

**Comment by mpmprudencio** [comment] 2019-05-17 23:25
I'm having the same issue on Android. The icon is showing on iOS tough.

Tried facebook-f and facebook-square none of them worked on Android.

Using the latest version of react-native-vector-icons

**Comment by tagliala** [comment] 2019-05-18 07:38
Hi @mpmprudencio 

> Using the latest version of react-native-vector-icons

This package? https://github.com/oblador/react-native-vector-icons

**Comment by mpmprudencio** [comment] 2019-05-18 07:48
Yes @tagliala, also notice PayPal also is missing now, maybe all brands. I had to update the missing icons and update the App.

**Comment by tagliala** [comment] 2019-05-18 08:00
@mpmprudencio sorry, we do not provide support for third-party libraries

**Comment by escaper01** [comment] 2019-07-12 11:47
I had the same problem but I fixed just by myself
for the problem was instead of using 

> 

> `<i class="fab fa-facebook-square"></i>`
I used `<i class="fa fa-facebook-square"></i>`
u should use "fab" instead of "fa"

**Comment by enknot** [comment] 2020-03-03 16:40
I've been fighting with that for a week. I'm sure there's a RTFM story here somewhere.

**Comment by tagliala** [comment] 2020-03-03 16:59
@enknot could you please clarify?

**Comment by enknot** [comment] 2020-03-03 17:01
I didn't read anywhere that the brand fonts were under the superclass "fab" and when i tried to include them with a "fa" or even "fas" they didn't work. There's bound to be some documentation that explains this on the fontawesome page somewhere, but i don't know where....and didn't for a week. :/

**Comment by tagliala** [comment] 2020-03-03 17:21
Hi @enknot , sure it is!

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

The [icon page themselves](https://fontawesome.com/icons/facebook-square?style=brands) show the proper syntax

![image](https://user-images.githubusercontent.com/556268/75800845-79424180-5d7a-11ea-9fcd-8e7edf8c9b58.png)

And if you have upgraded from FAv4 to v5: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#changes

Is there anything we can do to improve the documentation?

**Comment by yashrajvk** [comment] 2020-05-19 11:37
<i class="fab fa-shopify"></i> does not work

**Comment by tagliala** [comment] 2020-05-19 11:55
@yashrajvk feel free to open a new request by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

Please provide a reproducible test case
