### ISSUE TITLE
Icon Request: icon-balance

### ISSUE THREAD

**Issue by mm-habibi** [FortAwesome/Font-Awesome#5582] opened 2015-02-04 11:02 UTC
![balance](https://cloud.githubusercontent.com/assets/4964205/6039273/961a09d4-ac7a-11e4-828d-75c9b775c983.jpg)

**Comment by tagliala** [comment] 2015-02-04 23:35
duplicate of #2818 , please +1 that request

closing here

**Closed by tagliala** 2015-02-04 23:35 UTC
