### ISSUE TITLE
Desktop subsetter app - show unicode, html, etc on hover or click

### ISSUE THREAD

**Issue by morrow95** [FortAwesome/Font-Awesome#16774] opened 2020-06-07 17:06 UTC
Would like to see icon details shown on hover or click of the icons.  The subsetter is a fantastic idea and I will certainly use it to slim down, but other than showing the name of the icon it doesn't provide any other information at all about actually using it.  When developing it would be nice to just have the subsetter open to edit/save as you go or even just as a reference to the html/unicode since you can search through them.  Currently you would need the subsetter AND your site open in a browser to find this information.

I was kind of shocked to see this missing from the app to be honest.

**Comment by tagliala** [comment] 2020-06-07 17:59
Hi!

Thanks for being part of the Font Awesome Community.

We have several posts about the subsetter in FA Pro Repository at  

- Font-Awesome-Pro#1504 (maybe a duplicate of your request? If yes, please close this one)
- Font-Awesome-Pro#1070

Since the subsetter is a Pro exclusive functionality, I prefer to have those issues there

I can move this issue on the other repo, but I want to be sure that you have access before

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Closed** 2020-06-07 20:11 UTC
Labels: waiting for feedback
