### ISSUE TITLE
Icon Request: fa-attendant

### ISSUE THREAD

**Issue by fagnerdireito** [FortAwesome/Font-Awesome#10169] opened 2016-11-04 19:13 UTC
Attendant icon would be great.
suggest name of icon: fa-attendant

<img src="http://i.imgur.com/5hgY2qj.png">

**Comment by tagliala** [comment] 2016-11-04 19:52
Duplicate of #5586 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-04 19:52 UTC
