### ISSUE TITLE
Icon Request: fa fa-chat

### ISSUE THREAD

**Issue by M-Yusuf** [FortAwesome/Font-Awesome#7166] opened 2015-08-07 14:09 UTC
Hey Font-Awesome, 

I've been using your icons on my sites for quite a while and have been satisfied with the selection of icons available, however I am working on a site which has a chat functionality. My teammates and I could not find an icon for chat, messages, or text messages. We are currently using the fa-comments icon, but it is not sufficient for us. We were previously using fa-envelope and it does not provide what we yearn to achieve either. We would love it if you could create an icon for chat/messages. The design should be based around a bubble such as the examples below (Without the smiley face of course). 

Best, Yusuf

(Disclaimer. I do not own any of the images I have provided. They have been taken from the following webpages 

- https://cdn4.iconfinder.com/data/icons/flatified/512/messages.png
- https://lh4.ggpht.com/G1jalUvzKDBMEwP2iYSjWZKVwwN0WHJpFyzh9DOo-Jlnwclqft37T88w4DRMjpLD3ls=w300
- https://cdn0.iconfinder.com/data/icons/Android-R2-png/512/Messages-Android-R.png
)

![messages](https://cloud.githubusercontent.com/assets/8175253/9137539/5d8c268a-3cec-11e5-9640-a10d62d26d72.png)
![unnamed](https://cloud.githubusercontent.com/assets/8175253/9137538/5d8b8360-3cec-11e5-8ee6-a275019b938c.png)
![messages-android-r](https://cloud.githubusercontent.com/assets/8175253/9137540/5d9053d6-3cec-11e5-8818-0e21379240da.png)

**Comment by tagliala** [comment] 2015-08-07 14:11
this should be duplicate of #2790

**Closed by tagliala** 2015-08-07 14:11 UTC

**Comment by M-Yusuf** [comment] 2015-08-07 16:04
Your Right, I didn't find that. I hope you guys are working on it.
