### ISSUE TITLE
Icon Request: fa-podcast

### ISSUE THREAD

**Issue by priestap** [FortAwesome/Font-Awesome#5942] opened 2015-03-12 19:32 UTC
I've needed this one in LOTS of projects. :)  Something like the one iTunes uses would be perfect.

**Comment by kwendenarmo** [comment] 2015-03-23 23:00
It is quite similar to RSS icon. It could be:
![podcast icon](http://ccis.ucsd.edu/wp-content/uploads/2009/10/podcast-icon.gif)

**Comment by tagliala** [comment] 2015-07-01 19:21
duplicate of #2125, please +1 that request

closing here

**Closed by tagliala** 2015-07-01 19:21 UTC
