### ISSUE TITLE
Icon request: co2-cloud

### ISSUE THREAD

**Issue by dcdahl** [FortAwesome/Font-Awesome#15962] opened 2019-12-18 14:01 UTC
**What can it be used for?**
Used to represent CO2 emissions.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/14329052/71092153-fe1fb500-21a6-11ea-82fc-3f4e4ff91ffc.png)

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-01-06 09:56
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this request a duplicate of #12798, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-06 09:56 UTC
