### ISSUE TITLE
Icon Request: fa-palette

### ISSUE THREAD

**Issue by revof11** [FortAwesome/Font-Awesome#8846] opened 2016-03-28 13:53 UTC
Sample uses:

1. color selection
2. look & feel customization
3. doing artsy-fartsy stuff

Something like [this](https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Ic_palette_48px.svg/2000px-Ic_palette_48px.svg.png) would be cool - just being careful that it doesn't look like the Ocarina of Time.

**Comment by tagliala** [comment] 2016-03-28 14:35
Duplicate of #244 , scheduled for 5.0.0 but please +1 that request

closing here

**Closed by tagliala** 2016-03-28 14:35 UTC
