### ISSUE TITLE
Icon Request: fa-disconnect

### ISSUE THREAD

**Issue by wfssantos** [FortAwesome/Font-Awesome#7514] opened 2015-09-22 13:46 UTC
without connection with 3g, wifi or lan

**Comment by tagliala** [comment] 2015-09-22 14:24
any example?

**Comment by ckeryakes** [comment] 2015-10-02 22:09
![image](https://cloud.githubusercontent.com/assets/11856569/10258870/412878a2-6930-11e5-94c3-563d2dc328bd.png)
![image](https://cloud.githubusercontent.com/assets/11856569/10258886/5bce067c-6930-11e5-9c63-33cb1f2c5ed3.png)

**Comment by ckeryakes** [comment] 2015-10-02 22:12
Personally I like the first one (from Spotify, Offline indicator). I think the plug thing is a little overused, but essentially I would want to see something obviously broken. A bar, lightning bolt, or jagged horizontal line, split by a line. Just my 2 cents.

**Comment by Googlecloud12** [comment] 2015-10-03 04:08
+1

**Comment by tagliala** [comment] 2015-10-07 16:58
Duplicate of #5555, please +1 that request

closing here

**Closed by tagliala** 2015-10-07 16:58 UTC

**Comment by denkan** [comment] 2016-03-17 12:46
+1

**Comment by VitalyPankin** [comment] 2018-07-05 09:03
+1
