### ISSUE TITLE
Would like to see a Tidal icon for font awesome

### ISSUE THREAD

**Issue by imhotep06** [FortAwesome/Font-Awesome#17361] opened 2020-11-03 15:59 UTC
We need more icons for streaming services, including Tidal and Pandora.

**Comment by tagliala** [comment] 2020-11-03 16:06
Hi!

Thanks for being part of the Font Awesome Community.

Tidal is a duplicate of #8850, please add a 👍 reaction to that request.
Pandora is probably a duplicate of #5676, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-11-03 16:06 UTC
