### ISSUE TITLE
Icon Request: fa-count

### ISSUE THREAD

**Issue by maxsennin** [FortAwesome/Font-Awesome#7077] opened 2015-07-29 16:38 UTC
Hi,

I'd like an icon which represente a count before the playing of a music... Like "1, 2, 3, 4... Let's ♫"

Something like this maybe : ![decompte](https://cloud.githubusercontent.com/assets/13066669/8963547/00eb3aa0-3621-11e5-845e-a436136730ff.png)

Thanks a lot :-)

**Comment by tvirelli** [comment] 2015-08-05 17:01
@maxsennin , might I suggest something that might be more widely usable such as a metronome?

There is already a request for one [#6232](https://github.com/FortAwesome/Font-Awesome/issues/6232)

Below, I added some other examples:

[Example 1](http://www.fransabsil.nl/fig/metronome_icon.jpg)
[Example 2](http://thumb101.shutterstock.com/display_pic_with_logo/384598/280550963/stock-vector-metronome-icon-thin-line-for-web-and-mobile-modern-minimalistic-flat-design-vector-dark-grey-icon-280550963.jpg)

**Comment by tagliala** [comment] 2015-08-05 17:25
@tvirelli thanks for requesting additional details

**Comment by maxsennin** [comment] 2016-04-03 20:26
Sorry for the long response delay,

I'd like that icon in complement of a metronome icon...
This icon will be used for a countdown before the song beginning. :-)

Like in "Guitar Pro" :
![2016-04-03](https://cloud.githubusercontent.com/assets/13066669/14234741/03bfd586-f9eb-11e5-9940-32529a899564.png)

The first one is the metronome.
The second icon is the countdown.

Thank you ;-)

**Comment by tagliala** [comment] 2016-04-03 21:54
Duplicate of #6232, please +1 that request

Closing here

**Closed by tagliala** 2016-04-03 21:54 UTC
