### ISSUE TITLE
Icon Request: fa-tshirt

### ISSUE THREAD

**Issue by Maxxamillion** [FortAwesome/Font-Awesome#7242] opened 2015-08-16 00:52 UTC
I did a search for these and nothing popped up in the icons section. These would be good at representing merchandise icons on websites.
![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f353030383037322f323031343839302f63363263653362612d383761632d313165332d396562662d3337613430376438613862342e706e67](https://cloud.githubusercontent.com/assets/13814758/9291461/5296f90c-43b9-11e5-94be-9597d4c30487.png)

**Comment by TheChen5** [comment] 2015-08-16 02:47
Dupe of #715 
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-16 11:41
closing here

**Closed by tagliala** 2015-08-16 11:41 UTC
