### ISSUE TITLE
Icon request: fa-toolbox

### ISSUE THREAD

**Issue by bstolle** [FortAwesome/Font-Awesome#9652] opened 2016-07-26 18:31 UTC
This icon would be used for categories including "Tools & Settings", "Engineering Tools", or "Toolbox". ( I often use the metaphors of UI widgets being 'tools' that can be found in a 'toolbox' pattern library.)

The representative image is not ideal, but communicates the point. These seem to be common icons in web and desktop software applications.

![basic-toolbox-icon](https://cloud.githubusercontent.com/assets/7631008/17150413/00b86d82-5335-11e6-9f66-e3a25bfa57cf.png)

**Comment by tagliala** [comment] 2016-07-26 20:53
Duplicate of #4407, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-26 20:53 UTC
