### ISSUE TITLE
Icon Request: fa-omega

### ISSUE THREAD

**Issue by Disane87** [FortAwesome/Font-Awesome#9782] opened 2016-08-21 11:03 UTC
For a vaping site, I need the Ω-Symbol (greek Omega)
I guess for math sites, it would be great to have a general symbol set for greek formular symbols.

**Comment by tagliala** [comment] 2016-08-21 11:39
Duplicate of #2923, please add a 👍  reaction to that request

Please note that you can use the standard unicode point

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-21 11:39 UTC

**Comment by Disane87** [comment] 2016-08-21 11:41
Oh sorry! :) my fault.

**Comment by tagliala** [comment] 2016-08-21 11:41
no problem :+1:
