### ISSUE TITLE
Icon request: Pixelfed photo sharing

### ISSUE THREAD

**Issue by draconis3119** [FortAwesome/Font-Awesome#17184] opened 2020-09-22 06:27 UTC
What can it be used for?
Represent the photo sharing application [Pixelfed](https://pixelfed.org/). It's an alternative free and opensource to instagram. It's a several [fediverse ](https://fediverse.party/) web applications

Example image (optional)
https://fr.wikipedia.org/wiki/Pixelfed#/media/Fichier:Pixelfed_logo.svg

Thanks a lot.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-09-22 07:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14220, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-22 07:20 UTC

**Comment by draconis3119** [comment] 2020-09-22 15:01
I have do before request, it's weird.  Sorry for the inconvenience. Have a nice day.
