### ISSUE TITLE
icon i need and didnt find

### ISSUE THREAD

**Issue by Doronh75** [FortAwesome/Font-Awesome#17164] opened 2020-09-17 13:45 UTC
icon of rooster (chicken)

thanks

**Comment by tagliala** [comment] 2020-09-17 13:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14250 and/or #14251, please add a 👍 reaction to those request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-17 13:56 UTC
