### ISSUE TITLE
Icon request: heart-bolt and heart-bolt-lightning

### ISSUE THREAD

**Issue by djv-shyfoundry** [FortAwesome/Font-Awesome#19284] opened 2022-08-24 13:45 UTC
Would it be possible to get a heart-bolt and a heart-bolt-lightning icon? There's currently the heart-circle-bolt, but it would be nice to have the bolt placed inside of the heart for an AED icon.

![heart-bolt-lightning](https://user-images.githubusercontent.com/7468760/186434079-03a49f36-afed-4ecf-90ea-0b73277405e8.svg)
![heart-bolt](https://user-images.githubusercontent.com/7468760/186434084-ebfd88d9-5d44-4ae2-9d65-1c44118e9415.svg)

**Comment by tagliala** [comment] 2022-08-24 16:50
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/164/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by aethior** [comment] 2022-08-24 18:01
Duplicate or related? #4415

cc/ @tagliala

**Comment by tagliala** [comment] 2022-08-24 18:17
Thanks. Going to considerate this a duplicate of #4415

Ref: https://en.wikipedia.org/wiki/Automated_external_defibrillator

> The universal AED sign, developed by the [International Liaison Committee on Resuscitation](https://en.wikipedia.org/wiki/International_Liaison_Committee_on_Resuscitation) and adopted as [ISO](https://en.wikipedia.org/wiki/International_Organization_for_Standardization) 7010 E010

**Closed as completed by tagliala** 2022-08-24 18:17 UTC
Labels: new icon, medical / health (category)
