### ISSUE TITLE
icon request : fa-trailer

### ISSUE THREAD

**Issue by stefankellens** [FortAwesome/Font-Awesome#8453] opened 2016-01-29 15:20 UTC
Hello
I would like to request a new icon for a (car)trailer.

Example : https://www.wpclipart.com/transportation/car/icons_BW/small_trailer_BW_icon.png

Thanks

**Comment by tagliala** [comment] 2016-01-29 16:49
duplicate of #7369, please +1 that request

please also search before opening new requests

closing here

**Closed by tagliala** 2016-01-29 16:49 UTC
