### ISSUE TITLE
Icon Request: fa-houzz

### ISSUE THREAD

**Issue by MikeAyerTDS** [FortAwesome/Font-Awesome#7024] opened 2015-07-23 13:47 UTC
Hello-

I would love a houzz icon to utilize on sites. Can you guys create one?

http://www.houzz.com/

Thanks,
Mike Ayer

**Comment by TheChen5** [comment] 2015-07-25 23:59
Dupe of #2039 .
Go " +1 " that one.
*Search before creating issue.*

**Comment by tagliala** [comment] 2015-07-26 13:10
@TheChen5 thanks

**Closed by tagliala** 2015-07-26 13:10 UTC
