### ISSUE TITLE
icons are not showing up.

### ISSUE THREAD

**Issue by nesanmano** [FortAwesome/Font-Awesome#18648] opened 2022-02-06 18:32 UTC
Icons are not showing up.

Please take a look at this ticket:

https://stackoverflow.com/questions/71009635/ngx-sharebuttons-icons-not-showing-up

![image](https://user-images.githubusercontent.com/6265481/152695935-ae9acded-0381-4e7c-a8b6-76181ec35cdc.png)

**Comment by tagliala** [comment] 2022-02-06 19:29
Hi!

Thanks for being part of the Font Awesome Community.

> https://stackoverflow.com/questions/71009635/ngx-sharebuttons-icons-not-showing-up

This issue tracker is intended for FA issues, this looks like a support request so you did the right choice to post it on stackoverflow. Also, it seems that there is a third-party involved (ngx-sharebuttons/icons)

I'm not a JavaScript developer, so I can't help here. I can see that there are some differences with the usage https://github.com/FortAwesome/angular-fontawesome#usage 

I would start from https://github.com/FortAwesome/angular-fontawesome#usage and, if it works, incrementally add dependencies until the problem arises

If you think there is an issue with Font Awesome or a compatibility problem with a third party that should be fixed on our side, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case. You can use https://codesandbox.io/ 

Closing here, but feel free to comment

**Closed as completed by tagliala** 2022-02-06 19:29 UTC
