### ISSUE TITLE
Icon Request: treemap-chart

### ISSUE THREAD

**Issue by Szczawik** [FortAwesome/Font-Awesome#9421] opened 2016-06-20 03:29 UTC
I would like to request for a new icon for a [tree-map](https://en.wikipedia.org/wiki/Treemapping) chart. It could look for example like so:
![treemap](https://cloud.githubusercontent.com/assets/15626018/16182455/296d02c4-36d9-11e6-9213-968948f7f3f7.png)

There is also a separate request for the [tiles](https://github.com/FortAwesome/Font-Awesome/issues/1461) icon, but I think these two should be separate, as the tiles layout's order is independent from tiles' sizes, and an alternative icon (like the one in the tiles icon request) displaying a valid tile layout could misrepresent a (typical) tree-map with the smallest tiles in the right bottom corner.

Thanks for the consideration.

**Comment by tagliala** [comment] 2016-06-20 09:28
Sorry but I'm still seeing this as a duplicate of #1461.

Please add your comment there and explain why your design choice is better.

Closing here

**Closed by tagliala** 2016-06-20 09:28 UTC

**Comment by Szczawik** [comment] 2016-06-21 06:04
I can only guess what was the business case for the tiles icon, but I (and apparently a user _vlipman_, who commented in the other request post) got the impression it was not intended particularly for the treemap. Perhaps the tiles were generally meant to represent a layout of generic objects or user interface components (other options from that collection hypotetically being: side-by-side vertically, horizontally, or cascade).

The particular design image suggested for the tiles design cannot represent a typical treemap: it is neither arranged by sorting (the largest block would be first in the top left corner), nor stable and optimized for aspect ratio (the largest block would be aligned to the right edge), but it is perfectly valid for a generic "tiles" layout.

I would like to request an icon that could sit well next to the pie-chart icon, not something that would be used for arranging windows. Perhaps their appearance - based on what they visually represent - is similar, but the business goals are distinct. This is at least based on my understanding of the tiles icon request.
