### ISSUE TITLE
Icon request: icon-christian-cross

### ISSUE THREAD

**Issue by epelowski** [FortAwesome/Font-Awesome#10302] opened 2016-12-01 01:04 UTC
There are a quite a few Christian-Based Word Press themes that use your icons and there is no Icon for a traditional Christian Cross. 
Our church uses 'Forgiven' theme which makes use of Font-Awesome icons, which I love, but I cannot find any traditional Christian Crosses.

**Comment by tagliala** [comment] 2016-12-01 09:45
Duplicate of #1611 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-01 09:45 UTC
