### ISSUE TITLE
IE11 SCRIPT1003: ':' expected

### ISSUE THREAD

**Issue by HerrVoennchen** [FortAwesome/Font-Awesome#14382] opened 2018-12-11 11:42 UTC
Hi,

i'm not quite sure I'm in the right place for this issue but I like to explain it and maybe at least I get a better understanden where to address this.

I'm using FA5 

```
        "@fortawesome/fontawesome-svg-core": "^1.2.9",
        "@fortawesome/free-brands-svg-icons": "^5.6.0",
        "@fortawesome/free-regular-svg-icons": "^5.6.0",
        "@fortawesome/free-solid-svg-icons": "^5.6.0",
        "@fortawesome/react-fontawesome": "^0.1.3",
```

with react 16/babel 7/Webpack 4

and babel is set up to boil it down to IE11. Now it seems like IE11 has a problem with the following code which is located in all 3 (brands, regular and solid) packages of FA5 (index.js):

error: `SCRIPT1003: ':' expected` 

line points to:
```
var _iconsCache = {
    fa500px,
    faAccessibleIcon,
    faAccusoft,
    faAcquisitionsIncorporated,
    faAdn,
...
```

which is correct, it's ES6 syntax and IE11 does not support it.

I consume FA as follows:

```
import { fab } from '@fortawesome/free-brands-svg-icons/index';
import { fas } from '@fortawesome/free-solid-svg-icons/index';
import { far } from '@fortawesome/free-regular-svg-icons/index';

import { library } from '@fortawesome/fontawesome-svg-core';

library.add(fab, fas, far);
```

so now my point is, should babel transform this or is this an issue on FA side since IE11 is official supported and at least the JS files are not.

I tried to include the `node_modules` to babel in the process (was excluded  before) but it had no effect.

```
{
  test: /\.jsx?$/,
  loader: 'babel-loader',
  include: [path.resolve(__dirname, 'src')]
  //exclude: [/node_modules/]
}
```

If anything is missing, I'm happy to provide info. :)

best regards,

Sebastian

**Comment by robmadole** [comment] 2018-12-12 14:50
Confirmed! We'll start working on getting this fixed up.

**Comment by robmadole** [comment] 2018-12-12 16:45
![](https://github.trello.services/images/mini-trello-icon.png) [JS packages bug](https://trello.com/c/L41iBWjV/425-js-packages-bug)

**Comment by robmadole** [comment] 2018-12-12 16:48
We have the fix for this and are going to start the release process now.

**Comment by robmadole** [comment] 2018-12-12 22:42
This should be all fixed up now. Let us know if you still have issues.

**Closed by robmadole** 2018-12-12 22:42 UTC
Labels: waiting for feedback

**Comment by AdemHodzic** [comment] 2018-12-13 09:23
I was banging my head on work yesterday because of this bug.
Good job guys!

**Comment by HerrVoennchen** [comment] 2018-12-13 09:52
Yes, very fast fix. Thanks so much for the great work.
