### ISSUE TITLE
Problem with icon fa-tasks

### ISSUE THREAD

**Issue by dgvaleria** [FortAwesome/Font-Awesome#12255] opened 2018-02-05 14:49 UTC
It should look like this: 
<img width="73" alt="captura de pantalla 2018-02-05 a las 11 47 53 a m" src="https://user-images.githubusercontent.com/11396659/35810445-86e3d8d6-0a6a-11e8-82e4-17d0d8842b33.png"> 

but it looks like this:

<img width="95" alt="captura de pantalla 2018-02-05 a las 11 48 00 a m" src="https://user-images.githubusercontent.com/11396659/35810458-8e5736b2-0a6a-11e8-9ab4-10539c9a4e3a.png">

**Comment by tagliala** [comment] 2018-02-05 18:02
Hi!

Thanks for being part of the Font Awesome Community.

I agree that the "task" name is quite confusing, they represent progress bar, that's why we are asking for concrete objects in the title of the request.

By the way, your example could be seen as a todo list, and it is a duplicate of #773. Please 👍 that request if you need a different design for tasks

Closing here

**Closed by tagliala** 2018-02-05 18:02 UTC
