### ISSUE TITLE
Icon request: user-patient

### ISSUE THREAD

**Issue by niteshp** [FortAwesome/Font-Awesome#9066] opened 2016-04-27 05:18 UTC
We don't have a patient icon in the medical icons.  Couple of patient icons would be great.  A user (similar to user-md) but with broken arm would be good perhaps.

![](http://icons.iconarchive.com/icons/icons8/android/256/Healthcare-Triangular-Bandage-icon.png)

**Comment by PeterShaggyNoble** [comment] 2016-04-27 08:35
Dupe of [#3780](https://github.com/FortAwesome/Font-Awesome/issues/3780) (or possibly [#3629](https://github.com/FortAwesome/Font-Awesome/issues/3629)).

**Closed** 2016-04-27 09:13 UTC
