### ISSUE TITLE
cricket icon

### ISSUE THREAD

**Issue by kishoreL99** [FortAwesome/Font-Awesome#16826] opened 2020-06-23 08:20 UTC
+ i need cricket icon in font awesome 
+ can u please fix these issue

**Comment by tagliala** [comment] 2020-06-24 17:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of one of the following:
- #5706 
- #7201
- #7200
- #16700

Please add a 👍 reaction to the requests that fit your needs

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-06-24 17:23 UTC
