### ISSUE TITLE
Icon Request:  fa-artificial-intellect or fa-brain 

### ISSUE THREAD

**Issue by Acid5000** [FortAwesome/Font-Awesome#11621] opened 2017-10-13 21:12 UTC
Hello, with the increasing interest in the topic could you add a similar icon?

**Comment by tagliala** [comment] 2017-10-14 09:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2075 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-14 09:46 UTC
