### ISSUE TITLE
Icon request: Hen animal

### ISSUE THREAD

**Issue by veringm** [FortAwesome/Font-Awesome#15070] opened 2019-05-27 13:07 UTC
### What can it be used for?
To be displayed in an mobile-app for reporting various animal-crew sizes. Already using the existing fontawesome pro animal icons.

The user can easily find the right animal-type to update (icon follow by helper text).

### Example image (optional)
https://www.google.com/search?safe=active&biw=1536&bih=859&tbm=isch&sa=1&ei=seDrXKjNE4irmwWksb2gBQ&q=hen&oq=hen&gs_l=img.3..0i67j0l9.53816.54040..54814...0.0..0.311.813.2-2j1......0....1..gws-wiz-img.......35i39.X54RPN_80Fo

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-04-02 16:42
Duplicate of #14250?
`chicken` and `hen` are often used arbitrarily...

cc/ @tagliala

**Comment by tagliala** [comment] 2022-04-02 16:54
Thanks

**Closed by tagliala** 2022-04-02 16:54 UTC
Labels: new icon, animals (category)
