### ISSUE TITLE
Bug: Font awesome not being so awesome anymore, 404

### ISSUE THREAD

**Issue by tqrecords** [FortAwesome/Font-Awesome#20209] opened 2024-04-25 20:06 UTC
### Bug description

It looks like my font awesome kits are not loading just after going live. Here's the error from the browser console:

Access to script at 'https://kit.fontawesome.com/2*******.js' from origin 'https://*********.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I have the crossorigin="anonymous" attr added to the script tag. Seems like the server is down?

### Font Awesome version

v6

### Serving

Kit

### Implementation

SVG+JS

### Browser and Operating System

Chrome, Edge

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by ArturMoczulski** [comment] 2024-04-25 20:10
Same here but just getting 404

**Comment by cklenk** [comment] 2024-04-25 20:10
Yup looks like it's down for a lot of people including us ☹️
https://status.fortawesome.com/

**Comment by gnickoloff** [comment] 2024-04-25 20:13
Concur... Also seems most pages on their website are non-functional ATM as well.

**Comment by AndrewYimHST** [comment] 2024-04-25 20:14
same here! 404.

**Comment by luvduh** [comment] 2024-04-25 20:20
![image](https://github.com/FortAwesome/Font-Awesome/assets/105556713/571ce35a-371f-4805-9898-b9a450c0d972)
Ouch, been offline for 30m now

**Comment by ArturMoczulski** [comment] 2024-04-25 20:42
Here is a temporary solution I'm doing:

1. Switch to Pro CDN
2. Replace all `fa-solid` to `fa-down-fix fa fa-solid` and `fa-regular` to `fa-down-fix fa fa-regular`
3. After the issue is fixed find and replace all those occurrences should be super easy with just going back from `fa-down-fix fa fa-solid` to `fa-solid`.

**Comment by tqrecords** [comment] 2024-04-25 20:44
> Yup looks like it's down for a lot of people including us ☹️ https://status.fortawesome.com/

Fort Awesome!?

![image](https://github.com/FortAwesome/Font-Awesome/assets/19880425/8bbc0ca7-ddf1-47bc-9575-3734b17bca0f)

**Comment by ArturMoczulski** [comment] 2024-04-25 20:46
Lol solid phishing

**Comment by tqrecords** [comment] 2024-04-25 20:47
Looks like the issue has been rectified! Icons back up for me.

**Comment by tqrecords** [comment] 2024-04-25 20:53
Seems like the issue has been rectified, stable on my end so far..

**Comment by luvduh** [comment] 2024-04-25 21:02
Seems to be back online

**Comment by tagliala** [comment] 2024-04-26 10:40
`FoRtAwesome` is also the name of the organization here on GitHub :) 

<img width="332" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/556268/117dc501-7b15-47c8-aa89-a338d6a48959">


Closing here, apologies again for the issue

**Closed as completed by tagliala** 2024-04-26 10:40 UTC
Labels: bug, needs-triage
