### ISSUE TITLE
Capital sigma letter icon

### ISSUE THREAD

**Issue by chrismasters** [FortAwesome/Font-Awesome#13754] opened 2018-08-12 04:59 UTC
As an cue for aggregation, is it possible to add a Σ to the icon set?

**Comment by tagliala** [comment] 2018-08-12 10:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4834 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-12 10:10 UTC
