### ISSUE TITLE
Icon Request: fa-taxes

### ISSUE THREAD

**Issue by huyvandnc** [FortAwesome/Font-Awesome#5382] opened 2015-01-13 04:06 UTC
Hi,
Im need icon for Taxes but i can found it on Font-Awesome.
I think it like img attach:

![tax_percent_1-128](https://cloud.githubusercontent.com/assets/5999873/5715888/17b6ec50-9b14-11e4-9780-96e5058defbc.png)
![tax_percent_2-128](https://cloud.githubusercontent.com/assets/5999873/5715889/17b77fee-9b14-11e4-91ed-3f5194291517.png)

Can help me include it. Thank!

**Comment by technofreaky** [comment] 2015-01-13 05:06
+1

**Comment by imarrero** [comment] 2015-03-10 12:34
+1

**Comment by TonGarcia** [comment] 2015-08-08 11:46
+1

**Comment by tagliala** [comment] 2015-08-08 12:02
duplicate of #1292 , please +1 that request

closing here

**Closed by tagliala** 2015-08-08 12:02 UTC

**Comment by tkontogi** [comment] 2016-09-15 10:43
I reopen the case to give an idea. I found the following which is proprietary.

Just food for thoughts...

![image](https://cloud.githubusercontent.com/assets/15005048/18547100/4b0411d8-7b4a-11e6-9a7c-87e8718c05f7.png)

Thank you

**Comment by TheBuzzer67** [comment] 2016-10-24 14:57
Still not in??

**Comment by tagliala** [comment] 2016-10-24 21:52
this is is as icon-percent http://fontawesome.io/icon/percent/
