### ISSUE TITLE
Icon Request: fa-icon law

### ISSUE THREAD

**Issue by eX00r** [FortAwesome/Font-Awesome#9929] opened 2016-09-18 14:15 UTC
Will be used for law firms or any legal related website
could be a paragraph §

**Comment by tagliala** [comment] 2016-09-18 14:31
Duplicate of #1706 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

There is also http://fontawesome.io/icon/gavel/

Closing here

**Closed by tagliala** 2016-09-18 14:31 UTC
