### ISSUE TITLE
Icon request: stage

### ISSUE THREAD

**Issue by 1791delegates** [FortAwesome/Font-Awesome#18838] opened 2022-03-20 21:38 UTC
Theater curtains framing a stage. Maybe something like this (inspired by Shutterstock vector https://www.shutterstock.com/image-vector/theatre-stage-icon-simple-illustration-vector-482841973)

<img width="443" alt="Screen Shot 2022-03-20 at 5 40 16 PM" src="https://user-images.githubusercontent.com/68081772/159187124-c78dceb4-55cb-45a8-99a5-d6037d718f6d.png">

**Comment by aethior** [comment] 2022-03-22 22:06
Duplicate of #1987.

**Comment by tagliala** [comment] 2022-03-23 10:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1987, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-03-23 10:51 UTC
