### ISSUE TITLE
Icon request: icon-xboxlive

### ISSUE THREAD

**Issue by vsential** [FortAwesome/Font-Awesome#10563] opened 2017-01-24 18:43 UTC
Use case is for addition into multiple Jekyll templates.

![xbox](https://cloud.githubusercontent.com/assets/4664215/22261452/a67ec540-e232-11e6-9412-c0429ba241f3.png)

**Comment by tagliala** [comment] 2017-01-24 19:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1006 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-24 19:34 UTC
