### ISSUE TITLE
Icon request: leetcode

### ISSUE THREAD

**Issue by ziadsadek999** [FortAwesome/Font-Awesome#18916] opened 2022-04-18 15:03 UTC
![leetcode_logo_icon_145113](https://user-images.githubusercontent.com/68449722/163828042-414b2a38-6d81-473c-9fd9-767a72187e26.png)

**Comment by tagliala** [comment] 2022-04-18 15:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15337 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-04-18 15:15 UTC
