### ISSUE TITLE
Deezer ICON

### ISSUE THREAD

**Issue by siveryt** [FortAwesome/Font-Awesome#16394] opened 2020-03-31 13:57 UTC
Can you add a _Deezer_ icon into the fa- CSS-File?
Thanks
Sivery

**Comment by tagliala** [comment] 2020-03-31 14:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2802 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-31 14:20 UTC
