### ISSUE TITLE
Icon request: icon-vr-goggles

### ISSUE THREAD

**Issue by RedRock3D** [FortAwesome/Font-Awesome#11620] opened 2017-10-13 13:52 UTC
virtual reality goggles 
Here is a web url to a site with many options: https://thenounproject.com/term/virtual-reality/123780/

**Comment by tagliala** [comment] 2018-04-23 13:29
Hi!

Thanks for being part of the Font Awesome Community.

Possible duplicate of #6590?

**Comment by sensibleworld** [comment] 2019-05-02 15:22
https://fontawesome.com/icons/head-vr?style=solid
https://fontawesome.com/icons/vr-cardboard?style=solid

**Closed by sensibleworld** 2019-05-02 15:22 UTC
