### ISSUE TITLE
Icon Request: fa-patreon

### ISSUE THREAD

**Issue by lexbmeyer** [FortAwesome/Font-Awesome#11129] opened 2017-06-01 21:16 UTC
I love font awesome!
I would like to request an icon for the Patreon logo.
Thank you for all you do.

![patreon](https://cloud.githubusercontent.com/assets/4129466/26701143/8d8ae420-46e5-11e7-82a9-2eec753db363.png)

**Comment by tagliala** [comment] 2017-06-01 21:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3257, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-01 21:39 UTC
