### ISSUE TITLE
Icon Request: Please add Google Blogger

### ISSUE THREAD

**Issue by vinayprajapati** [FortAwesome/Font-Awesome#7349] opened 2015-08-31 17:20 UTC
I find WordPress icon and others too but missing Google Blogger icon please add this asap.

**Comment by Mohika** [comment] 2015-08-31 18:25
I got surprised its not in there as well. I need it too :-) Realized this 30 minutes ago .. coincidence if you believe it :-)

**Comment by TheChen5** [comment] 2015-08-31 19:41
Dupe #1088 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by jclarkcds** [comment] 2015-09-02 04:31
PLEASE ADD!!

**Comment by TheChen5** [comment] 2015-09-02 04:33
@jclarkcds 
This is a duplicate of request #1088 .
There are way more support there.
Please go +1 that issue.

**Comment by tagliala** [comment] 2015-09-13 12:21
closing here as a duplicate

**Closed by tagliala** 2015-09-13 12:21 UTC
