### ISSUE TITLE
Your license server just broke - 402 Payment Required

### ISSUE THREAD

**Issue by stevensacks** [FortAwesome/Font-Awesome#16046] opened 2020-01-10 09:05 UTC
I reported this on the react-fontawesome repo, but your license server is broken and people can no longer build on CI.

https://github.com/FortAwesome/react-fontawesome/issues/315

**Comment by ReneS1991** [comment] 2020-01-10 09:07
Got the exact same problem. Quite a big problem for us as our builds are breaking due to it and therefore clients cannot update etc.

**Comment by nicolomanni** [comment] 2020-01-10 09:10
Same problem with Angular. We are completely stuck, it is no longer possible to build projects.

**Comment by Kocal** [comment] 2020-01-10 09:21
Same here, I can download the Pro version on https://fontawesome.com/download but not with npm/yarn :(

**Comment by se** [comment] 2020-01-10 09:25
We can't do anything right now, our build pipelines are crashing...

**Comment by dottodot** [comment] 2020-01-10 09:27
Same issue here builds are failing

**Comment by ybiquitous** [comment] 2020-01-10 09:30
Same here, please fix... 🙏

**Comment by yasindilekci** [comment] 2020-01-10 09:30
Same here.. :(

**Comment by tagliala** [comment] 2020-01-10 09:34
Hi!

Thanks for being part of the Font Awesome Community, thanks for reporting this and sorry for this issue.

@robmadole could you please take a look?

**Comment by peternijssen** [comment] 2020-01-10 09:36
@tagliala, Since @robmadole seems to be located in the US, does this mean this issue will continue to exist for the upcoming hours? Because then I need to start a work-around to be able to continue an important release.

**Comment by peturh** [comment] 2020-01-10 09:38
Same issue here.

**Comment by ablanco** [comment] 2020-01-10 09:45
Same problem here.

**Comment by planetflash** [comment] 2020-01-10 09:46
Shouldn't https://status.fortawesome.com/ and Twitter be updated? This must be breaking a great many builds across the world

**Comment by tagliala** [comment] 2020-01-10 09:49
@peternijssen I don't tell for sure, but your guess may be correct.

I've sent a message to @robmadole, that's the best I can do, sorry 🙏🏼

@planetflash that is correct, but I do not have access to the social media accounts or status

**Comment by samuelgoddard** [comment] 2020-01-10 09:50
Same problem here 🙌

**Comment by nicolomanni** [comment] 2020-01-10 09:50
@robmadole we are all on your hands

**Comment by saidziani** [comment] 2020-01-10 10:09
Same issue here.
`npm ERR! 402 Payment Required`

**Comment by davidfurlong** [comment] 2020-01-10 10:10
Their fortawesome account servers are broken too it seems

**Comment by fwininger** [comment] 2020-01-10 10:13
Same problem 😢

**Comment by tagliala** [comment] 2020-01-10 10:15
I'm trying to find a workaround if someone needs to make an urgent deploy, but I'm not a node developer.

Please check if the following may work for you. I'm using `yarn`

1. Go to https://github.com/FortAwesome/Font-Awesome-Pro/releases
2. Download (and extract) the source code
3. Move the `/js-packages` folder where you `package.json` is
4. Edit `package.json` and replace (in example)
`"@fortawesome/fontawesome-pro": "^5.10.2",`
with
`"@fortawesome/fontawesome-pro": "file:./js-packages/@fortawesome/fontawesome-pro"`

With the above approach, at least I'm able to install the npm packages. You may need to download other source repositories, I guess for react and angular extensions.

**Please share if you find a better workaround**

Also, if you are going to try the above workaround **please do not commit the font awesome pro files in a public repository**. I would leave that in a separate development branch and then dismiss it when the license server is up again

**Comment by chrisGeonet** [comment] 2020-01-10 10:20
Can't do the above workaround as the Font-Awesome-Pro repo no longer exists.

**Comment by peturh** [comment] 2020-01-10 10:21
> Can't do the above workaround as the Font-Awesome-Pro repo no longer exists.

I think you have to link your github account through Fortawesomes website to access that repo.

**Comment by JustDoItSascha** [comment] 2020-01-10 10:25
Pipelines are crashing :(

**Comment by peturh** [comment] 2020-01-10 10:28
We have a designsystem that has a peerDependency to fortawesome packages. We  use that designsystem in almost all our repos. We can't deploy using that fix from above, since that means we have to deploy designsystem as well, push a new version of that than later revert that. 

I'd have to take a shower after doing such a hack.

**Comment by geekazoid-at** [comment] 2020-01-10 10:31
Same problem here
`error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-common-types/-/0.2.26/fontawesome-common-types-0.2.26.tgz: Request failed \"402 Payment Required\"".`

**Comment by davidfurlong** [comment] 2020-01-10 10:32
Somewhat tempting to publish their private git repo packages publicly so we can simply use a different package name install, but don't want to breach their copyright or whatever

**Comment by designbyadrian** [comment] 2020-01-10 10:32
`insert DRM joke here`

**Comment by davidfurlong** [comment] 2020-01-10 10:35
It's likely going to be hours before someone in the US wakes up and fixes this, right?

**Comment by shakesBeardZ** [comment] 2020-01-10 10:38
so we have to wait for some one to fix this ?!!! can anyone wake those people 😂 and tell them it's urgent

**Comment by davidfurlong** [comment] 2020-01-10 10:38
@tagliala can you call someone with access?

**Comment by JustDoItSascha** [comment] 2020-01-10 10:41
Can someone please call 911 to wake them up? 🚨 🤣

**Comment by Nicolasclearleaf** [comment] 2020-01-10 10:41
Same here... +1

**Comment by Undistraction** [comment] 2020-01-10 10:45
https://fontawesome.com/icons/fragile?style=solid

**Comment by Se7en-IT** [comment] 2020-01-10 10:45
+1

**Comment by webkhushboo** [comment] 2020-01-10 10:47
> Same issue here.
> `npm ERR! 402 Payment Required`

I am also getting the same error . `npm ERR! 402 Payment Required .`

**Comment by webkhushboo** [comment] 2020-01-10 10:47
> I'm trying to find a workaround if someone needs to make an urgent deploy, but I'm not a node developer.
> 
> Please check if the following may work for you. I'm using `yarn`
> 
> 1. Go to https://github.com/FortAwesome/Font-Awesome-Pro/releases
> 2. Download (and extract) the source code
> 3. Move the `/js-packages` folder where you `package.json` is
> 4. Edit `package.json` and replace (in example)
>    `"@fortawesome/fontawesome-pro": "^5.10.2",`
>    with
>    `"@fortawesome/fontawesome-pro": "file:./js-packages/@fortawesome/fontawesome-pro"`
> 
> With the above approach, at least I'm able to install the npm packages. You may need to download other source repositories, I guess for react and angular extensions.
> 
> **Please share if you find a better workaround**
> 
> Also, if you are going to try the above workaround **please do not commit the font awesome pro files in a public repository**. I would leave that in a separate development branch and then dismiss it when the license server is up again

Not able to access URL : `https://github.com/FortAwesome/Font-Awesome-Pro/releases`

**Comment by simonb-has** [comment] 2020-01-10 10:48
https://status.fortawesome.com/

**Comment by IlanHZ** [comment] 2020-01-10 10:49
Same here

**Comment by scriptcoded** [comment] 2020-01-10 10:49
> I'm trying to find a workaround if someone needs to make an urgent deploy, but I'm not a node developer.
> 
> Please check if the following may work for you. I'm using `yarn`
> 
> 1. Go to https://github.com/FortAwesome/Font-Awesome-Pro/releases
> 2. Download (and extract) the source code
> 3. Move the `/js-packages` folder where you `package.json` is
> 4. Edit `package.json` and replace (in example)
>    `"@fortawesome/fontawesome-pro": "^5.10.2",`
>    with
>    `"@fortawesome/fontawesome-pro": "file:./js-packages/@fortawesome/fontawesome-pro"`
> 
> With the above approach, at least I'm able to install the npm packages. You may need to download other source repositories, I guess for react and angular extensions.
> 
> **Please share if you find a better workaround**
> 
> Also, if you are going to try the above workaround **please do not commit the font awesome pro files in a public repository**. I would leave that in a separate development branch and then dismiss it when the license server is up again

For anyone looking to solve this, @tagliala's solution seems to work just fine. Thanks!

Also, let's perhaps keep this issue clean of "I've got it too" comments so that users with the same issue can find the solution :)

**Comment by paulyoung5** [comment] 2020-01-10 10:50
thanks @tagliala, your solution's been helpful!

**Comment by davidfurlong** [comment] 2020-01-10 10:54
> I'm trying to find a workaround if someone needs to make an urgent deploy, but I'm not a node developer.
> 
> Please check if the following may work for you. I'm using `yarn`
> 
> 1. Go to https://github.com/FortAwesome/Font-Awesome-Pro/releases
> 2. Download (and extract) the source code
> 3. Move the `/js-packages` folder where you `package.json` is
> 4. Edit `package.json` and replace (in example)
>    `"@fortawesome/fontawesome-pro": "^5.10.2",`
>    with
>    `"@fortawesome/fontawesome-pro": "file:./js-packages/@fortawesome/fontawesome-pro"`
> 
> With the above approach, at least I'm able to install the npm packages. You may need to download other source repositories, I guess for react and angular extensions.
> 
> **Please share if you find a better workaround**
> 
> Also, if you are going to try the above workaround **please do not commit the font awesome pro files in a public repository**. I would leave that in a separate development branch and then dismiss it when the license server is up again

Solution doesn't work for `react-fontawesome`

**Comment by webkhushboo** [comment] 2020-01-10 10:54
@stevensacks 
Its not working for me . Its showing 404 when I am trying to access that github repo for font-awesome-pro

**Comment by davidfurlong** [comment] 2020-01-10 10:56
> @stevensacks
> Its not working for me . Its showing 404 when I am trying to access that github repo for font-awesome-pro

@webkhushboo check your email - you would have needed to link your github acc to your fontawesome acc

**Comment by jdelStrother** [comment] 2020-01-10 10:59
> Solution doesn't work for react-fontawesome

You'll need to download it from https://github.com/FortAwesome/react-fontawesome/releases, then move the entire directory to js-packages/@fortawesome/react-fontawesome.

It works ok, but does bloat my directory by 180MB, which I'm not too keen on pushing to permanent git history...

**Comment by davidfurlong** [comment] 2020-01-10 11:02
> I'm trying to find a workaround if someone needs to make an urgent deploy, but I'm not a node developer.
> 
> Please check if the following may work for you. I'm using `yarn`
> 
> 1. Go to https://github.com/FortAwesome/Font-Awesome-Pro/releases
> 2. Download (and extract) the source code
> 3. Move the `/js-packages` folder where you `package.json` is
> 4. Edit `package.json` and replace (in example)
>    `"@fortawesome/fontawesome-pro": "^5.10.2",`
>    with
>    `"@fortawesome/fontawesome-pro": "file:./js-packages/@fortawesome/fontawesome-pro"`
> 
> With the above approach, at least I'm able to install the npm packages. You may need to download other source repositories, I guess for react and angular extensions.
> 
> **Please share if you find a better workaround**
> 
> Also, if you are going to try the above workaround **please do not commit the font awesome pro files in a public repository**. I would leave that in a separate development branch and then dismiss it when the license server is up again

Neither does it work for `fontawesome-svg-core`
due to
```js
  "dependencies": {
    "@fortawesome/fontawesome-common-types": "^0.2.26"
  },
```

**Comment by tagliala** [comment] 2020-01-10 11:09
@davidfurlong use the above method and replace with

```
    "@fortawesome/fontawesome-common-types": "file:./js-packages/@fortawesome/fontawesome-common-types",
```

**Comment by jdelStrother** [comment] 2020-01-10 11:10
> Neither does it work for fontawesome-svg-core

Download the source release from https://github.com/FortAwesome/Font-Awesome/releases, and copy fontawesome-common-types from js-packages.

**Comment by tagliala** [comment] 2020-01-10 11:12
@jdelStrother thanks for helping @davidfurlong .

I've specified that you may need more extensions to download

> It works ok, but does bloat my directory by 180MB, which I'm not too keen on pushing to permanent git history...

Sure. Please do not commit to master and keep this stuff in a different branch. It should be used just for extremely urgent deploys

**Comment by tagliala** [comment] 2020-01-10 11:12
@webkhushboo sorry for the late reply

If you don't have access to the Pro repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by EvanBurbidge** [comment] 2020-01-10 11:16
Getting the same here, whole frontend team is blocked.

**Comment by 0xdeafcafe** [comment] 2020-01-10 11:16
This is an outrageously bad way to do DRM. If something like this happens it should default to open. Sure some people may get access for a few hours, but it isn't like you can't get full copies of fontawesome online anyway.

All this does is punish and piss-off paying customers 🙄

**Comment by ceresnam** [comment] 2020-01-10 11:17
Same here... +1

**Comment by Karabur** [comment] 2020-01-10 11:20
> > I'm trying to find a workaround if someone needs to make an urgent deploy, but I'm not a node developer.
> > Please check if the following may work for you. I'm using `yarn`
> > 
> > 1. Go to https://github.com/FortAwesome/Font-Awesome-Pro/releases
> > 2. Download (and extract) the source code
> > 3. Move the `/js-packages` folder where you `package.json` is
> > 4. Edit `package.json` and replace (in example)
> >    `"@fortawesome/fontawesome-pro": "^5.10.2",`
> >    with
> >    `"@fortawesome/fontawesome-pro": "file:./js-packages/@fortawesome/fontawesome-pro"`
> > 
> > With the above approach, at least I'm able to install the npm packages. You may need to download other source repositories, I guess for react and angular extensions.
> > **Please share if you find a better workaround**
> > Also, if you are going to try the above workaround **please do not commit the font awesome pro files in a public repository**. I would leave that in a separate development branch and then dismiss it when the license server is up again
> 
> Neither does it work for `fontawesome-svg-core`
> due to
> 
> ```js
>   "dependencies": {
>     "@fortawesome/fontawesome-common-types": "^0.2.26"
>   },
> ```

With yarn, if you put all those dependencies to "resolution" field in package.json that will work. This way it will not matter if that direct dependency or some other module requires it - will be always installed from file folder.

Not sure about if npm allows the same.

**Comment by CallumHogg** [comment] 2020-01-10 11:23
Aye, same here :(

**Comment by TiagoPortfolio** [comment] 2020-01-10 11:26
![Chaos](https://media.giphy.com/media/3K0D1Dkqh9MOmLSjzW/giphy.gif)

**Comment by ninosaurus** [comment] 2020-01-10 11:27
Same here :(

**Comment by mariobento** [comment] 2020-01-10 11:28
+1

**Comment by EvanBurbidge** [comment] 2020-01-10 11:29
If we keep pinging this thread they might wake up :D :D 
+15 ( one for each of my devs ) :D

**Comment by eddiebragg** [comment] 2020-01-10 11:29
Us to....
ETA on fix?

**Comment by zverexe** [comment] 2020-01-10 11:29
sameeeeeeeeeeee here

**Comment by mennan** [comment] 2020-01-10 11:31
Same here ☹️

**Comment by sywesk** [comment] 2020-01-10 11:33
Guys, stop saying "same here". Please use the 👍 on the first post :)

**Comment by rodrigofariow** [comment] 2020-01-10 11:35
I'm thinking we should keep some packages like this one directly in our repos to avoid this type of issues.

Anyway I'm sure they are working on a fix but we can learn from this.

Cheers devs around the world!

**Comment by Walgermo** [comment] 2020-01-10 11:41
WWIII

**Comment by dottovan** [comment] 2020-01-10 11:51
Really? We're waiting some dudes to wake up to fix this?

**Comment by dschwank** [comment] 2020-01-10 11:55
I hope he is not a late riser :-D I bet his alarm is set to 8:00.

So ETW (estimated time to wakeup): 2 hours

:-D

**Comment by nicolomanni** [comment] 2020-01-10 11:57
the only paid service we have :( long live the free license

**Comment by dimitrisdovinos** [comment] 2020-01-10 11:57
I'd love to see the developer's face when he/she checks the inbox.

**Comment by peturh** [comment] 2020-01-10 11:58
Pipelines today all over the world: :red_circle: 

![2020-01-10-125538_3364x1601_scrot](https://user-images.githubusercontent.com/3379947/72151494-a7be2480-33a8-11ea-968e-422c6c6b7823.png)

**Comment by phoenix09208** [comment] 2020-01-10 11:58
Our CI/CD pipeline keeps failing, it also throws bunch other npm warning, because it happened to happen when i commit a major commit, i was scratching my head trying to figure out wtf is going on, i ended up even rebuilding my docker image.

@FontAwseome you should offer us at least one year free pro

**Comment by Coinhunter** [comment] 2020-01-10 11:59
Give them a few hours to rollback the service. Should be top prio, so probably won't stay broken for long. :) Just keep calm and carry on. I bet you can spend the time writing tests for that component you said you would write the tests for "later".

**Comment by EvanBurbidge** [comment] 2020-01-10 12:06
@Coinhunter can't write the tests because I can't run jest because my npm installs keep failing :D

**Comment by meiro-io** [comment] 2020-01-10 12:15
For the dev in FA re deploying on Friday: https://shouldideploy.today/

**Comment by se** [comment] 2020-01-10 12:22
We lost 4 man/days work today. Thank you.

**Comment by TiagoPortfolio** [comment] 2020-01-10 12:33
If any of your colleagues still have `@fortawesome` in _node_modules_ folder, ask for a copy of it.

- Remove any `@fortawesome` dependencies in _package.json_ file.
- Install again, I ran `rm -rf node_modules && yarn cache clean && yarn install`.
- Then copy the `@fortawesome` folder your colleague sent to the _node_modules_ folder.
- Run `yarn start`

It worked for me, thanks @rodrigofariow !

**Comment by gempain** [comment] 2020-01-10 12:33
Broke our builds this morning too, so we've made a few changes to ensure this doesn't happen in the future: we still had local copies of the packages on our laptops, so we published it on our private Npm registry and our builds are now pulling it from there. We've also set up a nightly job that pulls their registry and republishes on ours.

**Comment by planetflash** [comment] 2020-01-10 12:35
Even if you are not currently paying for a Pro licence, you should have continued access to your existing version - https://fontawesome.com/support#license-subscription-cancel

This begs the question why it's so aggressively preventing use.

**Comment by bjdelange** [comment] 2020-01-10 12:46
Same problem

**Comment by Flixbox** [comment] 2020-01-10 12:52
Our development team wants to know:

- Is there an ETA on a fix? It can't be "We're waiting for our single point of failure (the server admin) to wake up".
- Will there be a compensation for paying customers? Maybe an extension of our Pro subscription?

**Comment by felipedss** [comment] 2020-01-10 12:56
Same problem

**Comment by BramClocktimizer** [comment] 2020-01-10 12:58
As if it isn't bad enough, of course this happens on a Friday.

**Comment by nickdeveloop** [comment] 2020-01-10 12:59
![bank-run-1280x720](https://user-images.githubusercontent.com/36152888/72154619-c7117d80-33b9-11ea-84fb-549649798d89.jpg)

**Comment by andreladocruz** [comment] 2020-01-10 13:08
same issue here

**Comment by tagliala** [comment] 2020-01-10 13:09
@0xdeafcafe 

> This is an outrageously bad way to do DRM. If something like this happens it should default to open. Sure some people may get access for a few hours, but it isn't like you can't get full copies of fontawesome online anyway.
> 
> All this does is punish and piss-off paying customers 🙄

thanks for your suggestion, I __personally__ think that this is one of the best options when issues like this appear if we do not provide 24/7 support to Pro customers

@gempain 

> Broke our builds this morning too, so we've made a few changes to ensure this doesn't happen in the future: we still had local copies of the packages on our laptops, so we published it on our private Npm registry and our builds are now pulling it from there. We've also set up a nightly job that pulls their registry and republishes on ours.

Thanks for sharing your approach, I would suggest to use that if someone has a private npm repo. The source code of js pro packages is available at https://github.com/FortAwesome/Font-Awesome-Pro/tree/5.12.0

@Flixbox  

Apologies again, I've did all I could. I do not have an ETA, I do not have access to those servers, we should wait for the single point of failure

**Comment by NeilMasters** [comment] 2020-01-10 13:10
> we should wait for the single point of failure

We have no choice but to wait.

**Comment by tagliala** [comment] 2020-01-10 13:12
Ok, just got an answer from @davegandy :)

We are working on it 👍

**Comment by toxsick** [comment] 2020-01-10 13:12
This stuff happens, everybody here should know that, just sayin'

**Comment by gzamann** [comment] 2020-01-10 13:12
we can change from pro to free until the server is back up

**Comment by markbdev** [comment] 2020-01-10 13:13
Jackpot! This has made my Friday 🤔.
Same issue for our CI process.

**Comment by andreaslorenz** [comment] 2020-01-10 13:18
same here. but we only have the issue in our gitlab pipeline.

**Comment by NeilMasters** [comment] 2020-01-10 13:21
How often does this occur?

We switched to the npm repo because FA' CDN was so unreliable during december.

**Comment by calchuchesta** [comment] 2020-01-10 13:23
@NeilMasters My team has been using it for over a year and this is the first time it's happened. We're hoping it's just a one-off thing

**Comment by tagliala** [comment] 2020-01-10 13:23
> How often does this occur?

We had several issues in the past for the npm repo and we've recently switched to a better infrastructure.

IIRC this is the first major outage ever related to authentication

**Comment by dancrumb** [comment] 2020-01-10 13:27
Folks, before firing off another "Me too" and "I'm so angry" comment, please remember that it takes time and effort to read through all the noise; time and effort that these folks can better spend on getting things back on their feet.

If you have an issue with the commercial aspect of things then send an email to hello@fontawesome.com and deal with those issues there... we don't need to be clogging folks' inboxes with your ire.

**Comment by tagliala** [comment] 2020-01-10 13:29
looks like it is working again, at least for me. Could you please give a try?

**Comment by webkhushboo** [comment] 2020-01-10 13:30
> > @stevensacks
> > Its not working for me . Its showing 404 when I am trying to access that github repo for font-awesome-pro
> 
> @webkhushboo check your email (I sent) - you would have needed to link your github acc to your fontawesome acc

Thanks it worked for me 👍

**Comment by jordy-kommeren** [comment] 2020-01-10 13:30
@tagliala Confirmed to be working again!

**Comment by gzamann** [comment] 2020-01-10 13:32
download the node modules here
https://send.firefox.com/download/74b1a92219390d8c/#JJeuVYcWRT1Za2m0SxXKSw

**Comment by chaaya** [comment] 2020-01-10 13:33
Seems to work now!

**Comment by gzamann** [comment] 2020-01-10 13:38
@tagliala oops! my bad!

**Comment by maxime-lenne** [comment] 2020-01-10 13:39
Yes it's resolved 🙌

**Comment by giovannimazzuoccolo** [comment] 2020-01-10 13:40
I think you can close this issue.

**Comment by supercodepoet** [comment] 2020-01-10 13:40
Extremely sorry for the outage. We had a configuration issue with our service provider. This should be resolved now. We are working on better notifications to catch these issues sooner.
Again, very sorry for this issue. Please let us know if you are still experiencing problems.

**Comment by mckooiker** [comment] 2020-01-10 14:08
Are you sure all is well? One of our two webservers passed fine for the installation, 2 minutes after I tried installing the second and it failed.....It's just hanging on the fontawesome installation......

**Comment by sorin** [comment] 2020-01-10 15:30
At least it wasnt HTTP 418 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418

**Comment by scriptcoded** [comment] 2020-01-11 13:08
@supercodepoet Wonderful! Will you close the issue?

**Comment by tagliala** [comment] 2020-01-11 15:26
Closing here

Feel free to keep commenting if this is still an issue

**Closed by tagliala** 2020-01-11 15:26 UTC
Labels: bug, waiting for feedback

**Comment by minitesh** [comment] 2020-03-04 07:15
I am getting **_npm ERR! 402 Payment Required_** error on _npm install_ even after payment done today.

**Comment by tagliala** [comment] 2020-03-04 09:25
@minitesh please send an email to hello@fontawesome.com

**Comment by tagliala** [comment] 2020-03-04 09:25
@minitesh please send an email to hello@fontawesome.com
