### ISSUE TITLE
Icon request: icon-osf

### ISSUE THREAD

**Issue by naomibaes** [FortAwesome/Font-Awesome#18767] opened 2022-03-02 14:32 UTC
Usage: In CV to link Open Science Framework Profile (like people might link github and include the github icon).

Relevant site: https://osf.io/dashboard

Relevant icon attached (see PNG file below).

![image](https://user-images.githubusercontent.com/58921702/156381783-f58f6b48-49b2-4a6d-a11d-fd438e8ef491.png)

**Comment by tagliala** [comment] 2022-03-02 14:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13886, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-03-02 14:41 UTC

**Comment by naomibaes** [comment] 2022-03-03 03:12
Thanks, @tagliala!
