### ISSUE TITLE
Icon request: icon-door

### ISSUE THREAD

**Issue by z00tv** [FortAwesome/Font-Awesome#8927] opened 2016-04-09 04:37 UTC
a door - i.e. a door to a house, or something.

I use FA for a home automation dashboard where I have widgets for various sensors around the house.  One of those are door and window sensors.  It would be nice have an icon to represent an open door and an icon to represent a closed door.

thanks for your consideration.

**Comment by tagliala** [comment] 2016-04-09 09:26
Duplicate of #5394 or #2921  , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-09 09:26 UTC
