### ISSUE TITLE
Icon request: (F1) racing car

### ISSUE THREAD

**Issue by marceloverdijk** [FortAwesome/Font-Awesome#14145] opened 2018-10-21 09:12 UTC

**Comment by tagliala** [comment] 2018-10-21 09:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12846, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-21 09:36 UTC
