### ISSUE TITLE
Icon Request: icon-snowflake

### ISSUE THREAD

**Issue by m-ryll** [FortAwesome/Font-Awesome#9773] opened 2016-08-19 03:08 UTC
Hello!

I've tried to find a snowflake icon a couple times now so I suppose it would be pretty useful. In this particular case I'd like to represent "climate controlled" on a website for a dog groomer. It could also be useful in weather apps. Here's an idea:
![image](https://cloud.githubusercontent.com/assets/17148802/17797638/7b60c97e-6598-11e6-87d6-5064acaa89cc.png)

Thanks for the awesome work you do!
Mandy

**Comment by tagliala** [comment] 2016-08-19 09:44
Duplicate of #1739 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-19 09:44 UTC
