### ISSUE TITLE
Bug: Cannot import brand icons after 6.2.0

### ISSUE THREAD

**Issue by barackbrobama** [FortAwesome/Font-Awesome#19312] opened 2022-09-05 03:22 UTC
### Bug description

After updating to 6.2.0 brand icons seem to... not work for me when importing using the import macro.

`import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'`
`import { solid, brands } from '@fortawesome/fontawesome-svg-core/import.macro'`
`<FontAwesomeIcon icon={brands("facebook")} />`
results in
`Module not found: Error: Can't resolve '@fortawesome/pro-brands-svg-icons/faFacebook'`

Unfortunately I haven't been able to reproduce this with tools like codesandbox, but I have been able to reproduce this on two separate machines (laptop running macOS Monterey 12.5, desktop running Ubuntu 22.04).

- Rolling back to the 6.1.2 packages resolves the issue for me.
- Clearing node_modules and re-installing does not.
- Changing my license type to free in package.json resolves it (but obviously means I can't use any of the pro icons)

- node v18.8.0
- npm v8.18.0

Not sure if this is a react specific thing, so putting it here for now.

### Font Awesome version

6.2.0

### Serving

Self-hosted

### Implementation

SVG+JS

### Browser and Operating System

Firefox Developer 105.0b7 Ubuntu 22.04

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robbinjanssen** [comment] 2022-09-06 13:53
I am having the same error, using the same technique:

`Module not found: Error: Can't resolve '@fortawesome/pro-brands-svg-icons/faGithub' in '/home/dev/.../components'
resolve '@fortawesome/pro-brands-svg-icons/faGithub' in '/home/dev/.../components'`

**Comment by tagliala** [comment] 2022-09-06 14:53
Hi!

Thanks for being part of the Font Awesome Community and thanks for this report.

`pro-brands-svg-icons` does not look correct, so there is an issue in the resolver.

I can see that this issue is already known, will update this tracker when it is fixed

**Comment by robbinjanssen** [comment] 2022-09-07 06:24
@tagliala can you point me to the issue? Then I can track it myself as well :-)

**Comment by tagliala** [comment] 2022-09-07 07:11
> can you point me to the issue?

Keep track of this one, the other one is in a private upstream repository

**Comment by andrconstruction** [comment] 2022-09-09 08:57
have the same problem
brands( icon )  trying to import from pro-brands instead free-brands

**Comment by robmadole** [comment] 2022-09-20 20:31
I can confirm this is a bug. We've got it fixed and will get it released in the next version. No ETA yet on a release date.

**Comment by ghost** [comment] 2022-10-05 10:41
Just tagging on here; I'm also facing the same issue. Any news on a possible patch?

**Comment by wottpal** [comment] 2022-10-31 08:30
@robmadole facing the same issue, can't use `6.2.0` for almost 2 months now 😥

**Comment by audn** [comment] 2022-11-13 07:39
So brands are basically unusable until a fixed is rolled out? 🙄

**Comment by wottpal** [comment] 2022-11-13 10:34
yep :/

**Comment by mthottem** [comment] 2022-12-20 05:03
Any update on this?

**Comment by elmarsto** [comment] 2022-12-29 00:50
goodness. I'm incredibly grateful to Font Awesome, so I'm not going to complain about this. They've brought me great benefit. 

That said, this ticket has been open a surprising amount of time. I'm lowkey worried about the health of the project -- so many other things are teetering this eventful calendar year. 

My concern is that a core piece of functionality has been broken in production for over three months.  I smell smoke.

**Comment by robmadole** [comment] 2023-01-04 19:29
hey all. I didn't come back and update this issue after we released 6.2.1. But it is fixed and has been since Nov. 15.

Sorry for not communicating this and closing the loop.

**Closed as completed by robmadole** 2023-01-04 19:29 UTC
Labels: bug
