### ISSUE TITLE
Icon Request: fa-periscope

### ISSUE THREAD

**Issue by marcosauza** [FortAwesome/Font-Awesome#10756] opened 2017-03-07 18:10 UTC
Periscope https://www.periscope.tv

**Comment by tagliala** [comment] 2017-03-08 00:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6463 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-08 00:10 UTC
