### ISSUE TITLE
Icons searchable using FA version numbers 

### ISSUE THREAD

**Issue by cowwebmanager** [FortAwesome/Font-Awesome#13091] opened 2018-05-10 20:45 UTC
Hello, could you add the ability to search for icons by version number? This would make it much easier to see what the new icons are that were released, or what was released in each version. I found the leaderboard and released tab, but it doesn't show the icons... I'm a visual person! 

If we could search by version, like 5.0.0, or 5.0.13, that would be great! 

Thanks

**Comment by tagliala** [comment] 2018-05-10 21:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12483, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-10 21:17 UTC

**Comment by cowwebmanager** [comment] 2018-05-10 21:31
Sorry, I did search first but that one didn't come up based on my search terms. Thanks!

**Comment by tagliala** [comment] 2018-05-10 21:34
Don't worry, that was pretty hard to find 👍
