### ISSUE TITLE
Creative Commons icons are broken

### ISSUE THREAD

**Issue by nysander** [FortAwesome/Font-Awesome#15484] opened 2019-09-05 07:52 UTC
**Describe the bug**
What happened? What are you seeing? How did you arrive here?

When I want to use Creative Commons icons like creative-commons-by or creative-commons-sa it not renders

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Insert in code:
```
              <p>
                  <i class="fab fa-creative-commons fa-2x"></i>
                  <i class="fab fa-creative-commons-sa fa-2x"></i>
              </p>
```

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?

**Screenshots**

this should render two icons ... the only first one is rendered, second one renders error (no matter if it is *-by or *-sa

![image](https://user-images.githubusercontent.com/753327/64322345-b04dbb00-cfc2-11e9-8397-3be4d80403c3.png)

**Version and implementation**
Version: current
Browser and version: Firefox 69, Safari 12.1.2

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2019-09-05 08:07
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot reproduce: https://jsfiddle.net/tagliala/q2oa94hv/4/

Are you using kits?

Is there any third-party application or stylesheet that could interfer with Font Awesome?

Any live example?

**Comment by nysander** [comment] 2019-09-05 08:16
footer of this page: https://www.pawelmadej.com/tutorials/

**Comment by tagliala** [comment] 2019-09-05 08:22
Ok thanks

So your website is using Font Awesome 5.0.8 SVG.

[creative-commons-sa](https://fontawesome.com/icons/creative-commons-sa?style=brands) has been introduced in FA 5.0.11, please update to the latest version available (5.10.2)

One more thing: the website is full of references to localhost:4000, please also fix that. Check your development console

Hope it helps

Closing here

**Closed by tagliala** 2019-09-05 08:22 UTC
Labels: waiting for feedback

**Comment by nysander** [comment] 2019-09-05 08:38
I've updated FA to recommended version and now it is ok. site can contain broken links because is in WIP stage and uploaded for purpose of this issue.

thank you

one more question, where can I find sha checksums for released files?

**Comment by tagliala** [comment] 2019-09-05 08:58
You're welcome!

> one more question, where can I find sha checksums for released files?

I think that we don't have this option, also because we have several ways of download file and slightly different builds (cdn, free repo, pro repo, npm repos, zip files at GitHub...)

If you need md5 to provide a script tag with an SRI attribute, I don't know if this option is available for free users, but please do the following

1. Login to https://fontawesome.com/
2. Navigate to https://fontawesome.com/account/cdn
3. Check Free, All, SVG, 5.10.2
![image](https://user-images.githubusercontent.com/556268/64326908-16d6d700-cfcb-11e9-9ade-2e816bed4dba.png)
4. You will get a link with a SRI attribute containing sha384 checksum of the file
```
<script defer src="https://use.fontawesome.com/releases/v5.10.2/js/all.js" integrity="sha384-QMu+Y+eu45Nfr9fmFOlw8EqjiUreChmoQ7k7C1pFNO8hEbGv9yzsszTmz+RzwyCh" crossorigin="anonymous"></script>
```

@robmadole is there any place to check md5 of downloadable `zip` files? IMHO it is a good suggestion to provide md5 checksum of zip files both on the official website and on GitHub's releases page

**Comment by nysander** [comment] 2019-09-05 09:01
this is what I was looking for @tagliala. thank you for route to find it.
