### ISSUE TITLE
Icon request: Research gate

### ISSUE THREAD

**Issue by Alex--No** [FortAwesome/Font-Awesome#12336] opened 2018-02-12 18:31 UTC
Hi, 

It would be awesome if you add the icon of [ResearchGate](https://www.researchgate.net/) in your package! I would use it in my scientific CV  just next to my ResearchGate profile, and I'm sure it would be useful for others in the scientific community!

Here's the icon

![download](https://user-images.githubusercontent.com/7831701/36112854-ee5d53d2-0ff8-11e8-84b5-901f6099eba0.png)

Thanks, 
Alexandre

**Comment by tagliala** [comment] 2018-02-12 19:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3634 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-12 19:49 UTC
