### ISSUE TITLE
Icon Request: fa- icon verysmiley-o, angry-o

### ISSUE THREAD

**Issue by difeorleth** [FortAwesome/Font-Awesome#10114] opened 2016-10-25 15:18 UTC
I plan on using your smiley icons in a rating system for my wiki, however I was planning on using a 5 point system. I see frown-o, meh-o and smile-o in your database, but I was hoping that there may be more range to your smiley collection in the near future, namely verysmiley-o and angry-o. 

Best,

Difeorleth

**Comment by tagliala** [comment] 2016-10-25 15:29
Duplicate of #4217 and #1417, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-25 15:29 UTC
