### ISSUE TITLE
Move logos into a new font

### ISSUE THREAD

**Issue by migig** [FortAwesome/Font-Awesome#7598] opened 2015-10-02 21:26 UTC
With every release, there are more and more business/logo icons which we'll never use. I don't even know what most of them are.

We use the "majors" (Google, Twitter, etc.) but the rest just add to the font size and also make it harder to browse and find the ones we like.

I know we can just extract into a new font, but honestly, who has the patience for that, and to do it for every new release? The way it used to be was just plug and play.

*Why not have a separate font which only contains the logos?* So every release will have the main font, and the logos font.

Font Awesome is an awesome awesome (awesome!) font. It's just getting too heavy.

**Comment by tagliala** [comment] 2015-10-03 08:10
This was done in FontAwesome Black Tie. I don't know if Dave plans to do this also in Fontawesome

I will consider this a duplicate of #1322, please post there your thoughts

Meanwhile, you can subset FontAwesome. Take a look here https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2015-10-03 08:10 UTC
