### ISSUE TITLE
Icon request: trend-up and trend-down

### ISSUE THREAD

**Issue by alexrada** [FortAwesome/Font-Awesome#6584] opened 2015-05-28 18:21 UTC
The idea came from this font:
http://zavoloklom.github.io/material-design-iconic-font/icons.html

 md-trending-down
 md-trending-up
 md-trending-neutral

**Comment by tagliala** [comment] 2015-06-07 15:19
duplicate of #4397, please +1 that request

closing here

**Closed by tagliala** 2015-06-07 15:19 UTC
