### ISSUE TITLE
Icon Request: fa-gadugadu

### ISSUE THREAD

**Issue by Kucharskov** [FortAwesome/Font-Awesome#10020] opened 2016-10-04 17:52 UTC
Hi!
I'm sorry about my poor language.
Gadu-gadu (already renamed to "GG") is a very old and simple communicator with logo looks like sun.
Heres logo: http://grochu.eu/wp-content/uploads/2012/02/GG_nowe_logo.jpg
I need it (like my few web developers) for contact page icons. Already i had: skype, mail, steam, youtube, facebook, but not GG.
Regards!
Kucharskov

**Comment by tagliala** [comment] 2016-10-04 19:01
Duplicate of #5270, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-04 19:01 UTC
