### ISSUE TITLE
Icon request: fa-bullseye-arrow

### ISSUE THREAD

**Issue by ckshekhar73** [FortAwesome/Font-Awesome#10687] opened 2017-02-20 09:28 UTC
I would like fa-bullseye made with arrow to represent goal, target, mission. Some thing like below icon.
![goal](https://cloud.githubusercontent.com/assets/12582863/23119027/7d1132f6-f77c-11e6-97bc-446c48131bf5.png)

**Comment by tagliala** [comment] 2017-02-20 11:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5444, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-20 11:43 UTC
