### ISSUE TITLE
Icon Request: fa-firetruck

### ISSUE THREAD

**Issue by brechmos** [FortAwesome/Font-Awesome#5738] opened 2015-02-21 04:36 UTC
I would love to see a fire truck character.  I think it could be based off of the fa-truck.  Maybe just a little longer and then above the cab maybe some lines coming up diagonally as if it was lights. 

Thanks for any potential consideration!

**Comment by tomhrose** [comment] 2015-07-29 11:47
+1

**Comment by CarlosHAraujo** [comment] 2016-01-11 11:49
+1

**Comment by dpfem** [comment] 2016-05-13 01:37
+1

**Comment by devfunkd** [comment] 2016-11-03 19:34
+1

**Comment by LionelMeroni** [comment] 2017-01-18 07:51
+1

**Comment by andreygolubkow** [comment] 2018-02-05 12:57
+1

**Comment by carolinelindstrom** [comment] 2018-05-09 14:00
+1

**Comment by allor** [comment] 2018-05-27 11:18
+1 need for emergency services application

**Comment by dutchie027** [comment] 2018-07-25 17:49
+1

**Comment by xTey** [comment] 2019-03-24 15:49
+1

**Comment by tagliala** [comment] 2020-05-23 12:20
Sorry, this is a duplicate of #5738. I'm going to add `firetruck` to that title

**Closed by tagliala** 2020-05-23 12:20 UTC
Labels: new icon, vehicles (category)
