### ISSUE TITLE
Icon request: fa-syringe 

### ISSUE THREAD

**Issue by MadsCastle** [FortAwesome/Font-Awesome#7902] opened 2015-11-17 16:32 UTC
I work in a hospital and need an icon to represent patients having an operation
![syringe](https://cloud.githubusercontent.com/assets/15893535/11217537/b7677180-8d48-11e5-9158-9871b10d6598.gif)

**Comment by tagliala** [comment] 2015-11-17 18:15
duplicate of #1779  , please +1 that request

please also search for duplicates before opening new requests

closing here

**Closed by tagliala** 2015-11-17 18:15 UTC
