### ISSUE TITLE
icon request: instructor or teacher

### ISSUE THREAD

**Issue by RasterVector** [FortAwesome/Font-Awesome#10377] opened 2016-12-16 02:03 UTC
For LMS software to indicate an instructor vs a student or an instructor led class.

![image](https://cloud.githubusercontent.com/assets/16070681/21249077/7278ad76-c2f0-11e6-88bd-c6669ddeb44b.png)

![image](https://cloud.githubusercontent.com/assets/16070681/21249099/96fbfbf8-c2f0-11e6-8ec4-79bf5115402a.png)

![image](https://cloud.githubusercontent.com/assets/16070681/21249125/c78d6414-c2f0-11e6-9ed6-a8d9217a293c.png)

**Comment by Crissov** [comment] 2016-12-16 08:21
Emoji ZWJ sequences (without skin tone modifier or variation selector):

- 👨‍🏫 U+1F468-200D-1F3EB
- 👩‍🏫 U+1F469-200D-1F3EB

**Comment by kburke102** [comment] 2017-01-05 19:40
need this to identify an instructor module we are adding to our software application

**Comment by tagliala** [comment] 2017-01-05 20:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4079, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-05 20:05 UTC
