### ISSUE TITLE
Icon Request: fa-stamp

### ISSUE THREAD

**Issue by zengLH1981** [FortAwesome/Font-Awesome#13186] opened 2018-05-22 12:20 UTC
![image](https://user-images.githubusercontent.com/16136238/40361921-8616cd8c-5dfd-11e8-8e27-d3f31aaa5acf.png)

**Comment by tagliala** [comment] 2018-05-22 12:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1908, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-22 12:27 UTC
