### ISSUE TITLE
Icon request: icon-popcorn

### ISSUE THREAD

**Issue by geoffmckay** [FortAwesome/Font-Awesome#10652] opened 2017-02-11 18:33 UTC
It would be great to have a NEW Icon as part of Font Awesome 5 Pro:
popcorn
(i.e. an popped popcorn)
Would be handy as an icon related to snacks, movies, get-popping, etc.
Thanks!

**Comment by tagliala** [comment] 2017-02-11 19:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6879, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-11 19:41 UTC
