### ISSUE TITLE
Icon request: fa-tshirt

### ISSUE THREAD

**Issue by ezil91** [FortAwesome/Font-Awesome#9974] opened 2016-09-28 01:50 UTC

**Comment by tagliala** [comment] 2016-09-28 08:43
Duplicate of #715 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-28 08:43 UTC
