### ISSUE TITLE
Icon Request: fa-flower

### ISSUE THREAD

**Issue by pfrankowski** [FortAwesome/Font-Awesome#7071] opened 2015-07-29 08:31 UTC
Simple shape like trees and pagelines from current collection, 
similar to:
http://icons.iconarchive.com/icons/fasticon/nature/256/Red-Flower-icon.png

**Comment by tagliala** [comment] 2015-07-29 08:33
duplicate of #2037 , please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-07-29 08:33 UTC

**Comment by johnnyshields** [comment] 2016-06-22 12:10
Flower is available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.
