### ISSUE TITLE
Icon Request:fa-starbucks

### ISSUE THREAD

**Issue by TSStudio** [FortAwesome/Font-Awesome#12422] opened 2018-02-22 03:37 UTC
You know,just starbucks Mermaid

**Comment by tagliala** [comment] 2018-02-22 10:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4683, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-22 10:46 UTC
