### ISSUE TITLE
Icon request: Houzz

### ISSUE THREAD

**Issue by nashhagen** [FortAwesome/Font-Awesome#12617] opened 2018-03-15 18:44 UTC
### What can it be used for?

This icon would be for the website Houzz. They recently updated their logo so it would be awesome to have an updated version on font awesome.

### Example image (optional)

Here is the link to the new logo... https://www.houzz.com/photo/113061517-introducing-the-new-houzz-logo. I think it would be great to just have the house.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-03-15 21:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12561 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-15 21:42 UTC
