### ISSUE TITLE
Icon Request: fa-fiverr

### ISSUE THREAD

**Issue by dulanga91** [FortAwesome/Font-Awesome#16432] opened 2020-04-07 19:05 UTC
I am a freelancer, and I'm using fiver, up-work etc... then i need those icons for my won website display social icon section, I request that icon.

Thank you 
Dulanga Weerasuriya

**Comment by tagliala** [comment] 2020-04-07 19:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5970, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-04-07 19:08 UTC
