### ISSUE TITLE
Icon request: icon-snowflake

### ISSUE THREAD

**Issue by EESAdmin** [FortAwesome/Font-Awesome#9907] opened 2016-09-12 09:21 UTC
Hi I am just after a snowflake icon please. 

It will be used as a service icon on our site for air conditioning. 

I would like the icon in both white and charcoal back please. 

![icon request](https://cloud.githubusercontent.com/assets/22146029/18430887/fbcb0412-790c-11e6-93c5-2f7bd8be114d.png)

![snowflake05_product_page](https://cloud.githubusercontent.com/assets/22146029/18430779/9152677e-790c-11e6-8fb4-82ec5bcd2660.jpg)

**Comment by aethior** [comment] 2016-09-12 14:51
Hi @EESAdmin,

This request is duplicate of #1739, and this icon is planned for the next version (v5.0).

**Closed** 2016-09-12 16:11 UTC
