### ISSUE TITLE
Icon Request: fa-cooperation

### ISSUE THREAD

**Issue by MSalehi** [FortAwesome/Font-Awesome#7964] opened 2015-11-23 19:23 UTC
we need this icon for part of our website that invite users to cooperation.
![1342](https://cloud.githubusercontent.com/assets/5165298/11346986/513d513c-91d4-11e5-8259-0db7b6361657.png)

**Comment by aethior** [comment] 2015-11-24 11:58
Hi @MSalehi,

This suggestion is duplicate of #878. Please +1 that.

Regards.

**Comment by tagliala** [comment] 2015-11-24 12:10
@aethior thanks

**Closed by tagliala** 2015-11-24 12:10 UTC
