### ISSUE TITLE
Icon request: file-invoice-euro

### ISSUE THREAD

**Issue by Brilbroeder** [FortAwesome/Font-Awesome#17848] opened 2021-04-26 07:22 UTC
A similar icon as file-invoice-dollar, but with the euro sign.
In general it would be great to have all icons with a dollar sign on it to have a euro equivalent.

**Comment by sensibleworld** [comment] 2024-07-11 15:55
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/18397)

**Closed by sensibleworld** 2024-07-11 15:55 UTC
Labels: new icon, finance (category), Duplicate
