### ISSUE TITLE
fa-ladder & fa-stairs

### ISSUE THREAD

**Issue by ImanimalXI** [FortAwesome/Font-Awesome#9886] opened 2016-09-08 10:13 UTC
fa-ladder
fa-stairs (staircase)

Missing a ladder and stair case icon. both of these are fundamental so they should be able to fit many applications. 

Something similar to these, this is a quick hint not a finished design 

[<img src="https://image.freepik.com/free-icon/ladder-thin-outline_318-42071.png">](Ladder)

[<img src="http://www.tdmischke.com/clipart/2016/06/staircase-clipart.png">](Staircase)

**Comment by tagliala** [comment] 2016-09-08 18:27
Duplicate of #2479 and #5881, please add a 👍  reaction to those requests

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-08 18:27 UTC

**Comment by liudas-stonys** [comment] 2019-07-21 15:20
Please, add this icons. It's been 4 years since first request, man...
