### ISSUE TITLE
Icon request: fedex

### ISSUE THREAD

**Issue by NatLF** [FortAwesome/Font-Awesome#12630] opened 2018-03-16 22:33 UTC
Hi, 
it would be great to have a FedEx icon.

Thanks.

**Comment by tagliala** [comment] 2018-03-17 07:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1502, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-17 07:52 UTC
