### ISSUE TITLE
ruby icon

### ISSUE THREAD

**Issue by Tinix** [FortAwesome/Font-Awesome#15745] opened 2019-10-29 14:31 UTC
I propose the idea of, Ruby language icon,
I work with Ruby and I would like to implement it in several of my jobs.

Cheers!

Daniel Tinivella

**Comment by tagliala** [comment] 2019-10-29 14:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13553, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-10-29 14:33 UTC
