### ISSUE TITLE
Icon Request: fa-sailboat

### ISSUE THREAD

**Issue by SilverDario** [FortAwesome/Font-Awesome#12638] opened 2018-03-17 20:51 UTC
![sailboat-icon](https://user-images.githubusercontent.com/36082558/37559838-94f320d6-2a35-11e8-8241-954f366799be.png)
You need this icon ;)

**Comment by tagliala** [comment] 2018-03-17 20:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5079, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-17 20:53 UTC
