### ISSUE TITLE
Icon request: sum/total

### ISSUE THREAD

**Issue by rwb196884** [FortAwesome/Font-Awesome#11288] opened 2017-07-13 10:37 UTC
A capital sigma.
![download](https://user-images.githubusercontent.com/12090617/28162603-9afea6a0-67bf-11e7-85bc-13a6f1abf108.jpg)

**Comment by tagliala** [comment] 2017-07-13 10:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4834 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-13 10:44 UTC

**Comment by rwb196884** [comment] 2017-07-13 10:57
Sorry. I did search for both `sum` and `total`.
