### ISSUE TITLE
Icon Request: fa-popular

### ISSUE THREAD

**Issue by deepentim** [FortAwesome/Font-Awesome#7354] opened 2015-09-01 10:08 UTC
Please add new icon for 'Most popular' or 'Best Seller' or 'New' or 'Hot item
![most_popular_rotorua_tour_badge](https://cloud.githubusercontent.com/assets/14071397/9601464/6e112418-50c1-11e5-8b4b-4ffcf7013c95.gif)
'

**Comment by tagliala** [comment] 2015-09-13 13:28
I would suggest to use a flame, duplicate of #3577

closing here

**Closed by tagliala** 2015-09-13 13:28 UTC
