### ISSUE TITLE
viber

### ISSUE THREAD

**Issue by mikestotik** [FortAwesome/Font-Awesome#10944] opened 2017-04-13 20:32 UTC

**Comment by tagliala** [comment] 2017-04-13 21:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3554 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-13 21:10 UTC
