### ISSUE TITLE
Icon Request: fa-store

### ISSUE THREAD

**Issue by Hansjoerg2** [FortAwesome/Font-Awesome#7063] opened 2015-07-28 20:30 UTC
there exists the shopping cart in fontawesome but there is no icon for a store. both are different. a store icon would be great

**Comment by TheChen5** [comment] 2015-07-28 22:08
Dupe of #1958 
+1 that

**Comment by MigCan** [comment] 2016-10-15 18:54
![shop-icon-23328](https://cloud.githubusercontent.com/assets/22859639/19412568/0600e582-9311-11e6-8b51-6101fe1f0b6f.png)
+1

**Closed** 2016-10-15 19:08 UTC
