### ISSUE TITLE
Icon Request: fa-ribbon-medal

### ISSUE THREAD

**Issue by hina2329** [FortAwesome/Font-Awesome#10853] opened 2017-03-28 11:32 UTC
I want to medal icon with ribbon

**Comment by tagliala** [comment] 2017-03-28 15:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1898, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-28 15:13 UTC
