### ISSUE TITLE
Icon request: compare-files

### ISSUE THREAD

**Issue by Verovig** [FortAwesome/Font-Awesome#16514] opened 2020-04-23 20:31 UTC
**What can it be used for?**
This icon can be used in some feature to compare 2 things (files, codes, analysis, documentation, etc).

**Example image (optional)**
![compare-icon](https://user-images.githubusercontent.com/63020792/80146315-10ac5f80-8588-11ea-8116-9a1d98c816b7.jpg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-04-23 20:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12795, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Comment by tagliala** [comment] 2020-04-23 20:55
Changed my mind, let's use this one, has more +1s

**Comment by sensibleworld** [comment] 2024-07-11 16:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7616)

**Closed by sensibleworld** 2024-07-11 16:37 UTC
Labels: new icon, files (category), Duplicate
