### ISSUE TITLE
Icon Request: fa-engine

### ISSUE THREAD

**Issue by Indepent** [FortAwesome/Font-Awesome#10588] opened 2017-01-30 23:08 UTC
Hello, I would like to request a new icon: fa-engine. It would be as a Check Engine warning light on a car dashboard. I would use it to display Engine symbol using UI icons, for instance, in a classifieds portal.
You probably know the image, but here is the link to it: [https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Motorkontrollleuchte.svg/2000px-Motorkontrollleuchte.svg.png](url)

Kind regards,

**Comment by tagliala** [comment] 2017-01-30 23:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4175 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-30 23:14 UTC
