### ISSUE TITLE
Icon request: fa-responsive

### ISSUE THREAD

**Issue by FrancescoMussi** [FortAwesome/Font-Awesome#8792] opened 2016-03-19 18:41 UTC
Hello guys!
It could be 'awesome' to have the typical responsive icon.
That is: pc - tablet - phone (with the pc in the background).

It could be very useful for portfolio websites.

Thank you for the attention.

**Comment by tagliala** [comment] 2016-03-19 18:43
duplicate of #1446 , please +1 that request

closing here

**Closed by tagliala** 2016-03-19 18:43 UTC

**Comment by FrancescoMussi** [comment] 2016-03-19 18:52
Ok done, thanks
