### ISSUE TITLE
Icon request: Fishing Rod and Fish

### ISSUE THREAD

**Issue by johnspostsalotfishing** [FortAwesome/Font-Awesome#12560] opened 2018-03-09 16:05 UTC
### What can it be used for?

The concept of Fishing [can be dated back to 40,000 years ago](https://en.wikipedia.org/wiki/History_of_fishing). I was somewhat shocked to see there isn't an icon for the Angling or Fishing communities at all! (Yes, there's a difference!). There are many use cases for such an icon, Taken together, commercial and recreational fishing contributed nearly $90 billion to the U.S. economy in 2012, according to Hamilton Project data, including over 1.5 million jobs for American workers, and since then it's been on the increase. The UK government (my country) [reports that](https://www.gov.uk/government/news/fishing-industry-in-2016-statistics-published) UK vessels landed 701 thousand tonnes of sea fish into the UK and abroad with a value of £936 million. Whether it be discussing Angling & Fishing on social media to icons for the businesses specialising in the industry, there is a lot of potential for usage.  A fish caught on a rod would be tremendously useful. 

### Example image (optional)

I think we all know what a fishing rod looks like

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-03-09 16:59
Hi!

Thanks for being part of the Font Awesome Community.

Fish is a duplicate of #2722, please add a 👍  reaction to that request.

Fish-rod *may* be cover the same use case of #6445, but it is not a duplicate

I'm temporary renaming this to fishing-rod, but if #6445 covers your use case, please close here

**Comment by pacoweb** [comment] 2018-06-20 08:41
+1

**Comment by Crissov** [comment] 2018-11-15 13:48
Related Unicode emoji #222:

- [🎣](http://emojipedia.org/fishing-pole-and-fish/) U+1F3A3 Fishing Pole and Fish

**Comment by sensibleworld** [comment] 2021-09-29 19:47
https://fontawesome.com/v6.0/icons/fishing-rod?s=solid

**Closed by sensibleworld** 2021-09-29 19:47 UTC
Labels: new icon, web application icons
