### ISSUE TITLE
kit-pro.fontawesome not loading icons

### ISSUE THREAD

**Issue by BriianPowell** [FortAwesome/Font-Awesome#16491] opened 2020-04-17 17:27 UTC
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
Pro kit Icons we are using in our website are not loading 

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Error issue in developer console: 
Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID 
- https://kit-pro.fontawesome.com/releases/latest/css/pro.min.css

**Expected behavior**
How would you like this to work instead?
I would like the icons to show up.

**Screenshots**

Working example:
![working](https://user-images.githubusercontent.com/17599630/79594653-489c3a00-8092-11ea-8f3f-a7f221d4d42c.jpg)

Not-working Example:
![notworking](https://user-images.githubusercontent.com/17599630/79595429-b2691380-8093-11ea-8a36-cbdce6d0eb57.jpg)

**Version and implementation**
Version: 
https://kit-pro.fontawesome.com/releases/latest/css/pro.min.css

Browser and version: 
Google Chrome Version 81.0.4044.92

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2020-04-17 18:24
Thanks for reporting this, we are aware of the situation and sorry for the inconvenience

More information: https://status.fortawesome.com/

Duplicate of: #16482

**Closed by tagliala** 2020-04-17 18:24 UTC
