### ISSUE TITLE
Icon Request: fa-programme

### ISSUE THREAD

**Issue by JosMarRivera** [FortAwesome/Font-Awesome#9040] opened 2016-04-22 09:27 UTC
![programmer icon](https://cloud.githubusercontent.com/assets/6578923/14737594/1ac68a36-087d-11e6-8786-a419ac0b375b.png)

**Comment by tagliala** [comment] 2016-04-22 09:36
duplicate of #1230 , please +1 that request

closing here

**Closed by tagliala** 2016-04-22 09:36 UTC
