### ISSUE TITLE
Icon request: icon-airbnb

### ISSUE THREAD

**Issue by parce141** [FortAwesome/Font-Awesome#10697] opened 2017-02-23 05:37 UTC
I would like to use it on my new page to redirect to "airbnb" just like a link but I want to use  this icon

![airbnb](https://cloud.githubusercontent.com/assets/17696209/23246257/df791648-f957-11e6-84cd-622e0b1cd676.png)

**Comment by parce141** [comment] 2017-02-23 05:38
please

**Comment by parce141** [comment] 2017-02-23 05:38
i need it or how can I change it, some help please

**Comment by tagliala** [comment] 2017-02-23 10:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7650, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by tagliala** [comment] 2017-02-23 10:44
@parce141 please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2017-02-23 10:44 UTC

**Comment by mircsicz** [comment] 2017-04-10 03:14
+1
