### ISSUE TITLE
New Issue Icon request: icon-pointofsale

### ISSUE THREAD

**Issue by SanchaitaDey** [FortAwesome/Font-Awesome#10289] opened 2016-11-28 10:32 UTC
I want to use this icon for the dashboard we are working on. We want to label transactions received using POS machine and other from cash
![screen shot 2016-11-28 at 4 01 53 pm](https://cloud.githubusercontent.com/assets/14553623/20665056/0be9809a-b584-11e6-801f-ac0bd0cda9ad.png)
![screen shot 2016-11-28 at 4 01 25 pm](https://cloud.githubusercontent.com/assets/14553623/20665057/0bea1618-b584-11e6-8fc0-2a7226bbbee6.png)

**Comment by tagliala** [comment] 2016-11-28 13:44
Duplicate of #6792 please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-28 13:44 UTC

**Comment by olivierFr** [comment] 2018-05-15 10:43
Maybe the point of sale icon is already requested, but not a icon for the credit card reader. That would be very helpful. Please reopen the ticket, perhaps by changing the title of the ticket from pointofsale to "credit card reader".
