### ISSUE TITLE
Icon Request: drug

### ISSUE THREAD

**Issue by pl21** [FortAwesome/Font-Awesome#9200] opened 2016-05-13 10:37 UTC
I plan to use this icon for the tab in the pharma application with my drugs.
It may by a pill drug, or syringe.

**Comment by tagliala** [comment] 2016-05-13 11:20
Duplicate of #1778 #1779 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-13 11:20 UTC
