### ISSUE TITLE
Icon request: icon-anime

### ISSUE THREAD

**Issue by ralmanzar1108** [FortAwesome/Font-Awesome#18940] opened 2022-04-22 14:13 UTC

**Comment by tagliala** [comment] 2022-04-22 18:03
Any example?

**Comment by aethior** [comment] 2022-04-23 19:09
Duplicate of #16899.

**Comment by tagliala** [comment] 2022-04-23 19:47
Dejavu. Same problem there. Closing here, please post an example on #16899

**Closed as completed by tagliala** 2022-04-23 19:47 UTC
Labels: waiting for feedback
