### ISSUE TITLE
Icon Request: fa-phone-o

### ISSUE THREAD

**Issue by jennydocherty** [FortAwesome/Font-Awesome#5998] opened 2015-03-19 04:24 UTC
Requesting an outline version of this icon as a matter of urgency to complete a set for a mobile application.

<i class="fa fa-phone"></i>

**Comment by tagliala** [comment] 2015-03-20 15:37
duplicate of #2306, please +1 that request

@jennydocherty I **strongly** advise you to consider a custom build of fontawesome if you need this icon in a short while: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome 

Closing here

**Closed by tagliala** 2015-03-20 15:37 UTC
