### ISSUE TITLE
Icon request: icon-bath

### ISSUE THREAD

**Issue by yaratrump** [FortAwesome/Font-Awesome#8032] opened 2015-11-28 15:36 UTC
Hello,

I am always working on real estate web design, and I need an icon for bathroom for bathroom details, now I am using male and female icon for it.
See one of my web sites where I am using it: www.globalbrokersrd.com

Thank you.

**Comment by tagliala** [comment] 2015-11-28 17:19
Duplicate of #708 , please +1 that request

closing here

**Closed by tagliala** 2015-11-28 17:19 UTC
