### ISSUE TITLE
Icon request: icon-metals

### ISSUE THREAD

**Issue by Zokor** [FortAwesome/Font-Awesome#1630] opened 2013-07-22 09:35 UTC
Hi all,

It's a symbol for metals, i'm gonna be using it for financial business on metals.

I've attatched an svg made by myself and another image where i got the idea:

![icon-metais](https://f.cloud.github.com/assets/5063752/833993/d6565c2a-f2b1-11e2-9cc2-16c7ef09aea2.png)
![metal-bar](https://f.cloud.github.com/assets/5063752/833995/dabfcf30-f2b1-11e2-8c89-3a54076e5cba.png)

Best Regards!

**Comment by sensibleworld** [comment] 2024-07-11 16:46
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7729)

**Closed as completed by sensibleworld** 2024-07-11 16:46 UTC
Labels: new icon, Duplicate
