### ISSUE TITLE
Icon Request: fa-tools

### ISSUE THREAD

**Issue by sjssoft** [FortAwesome/Font-Awesome#12153] opened 2018-01-24 10:11 UTC
Thanks for providing us a treasure of icons. 
I want to request you to add a few icon for tools e.g. wrench, hammer, saw, screwdriver, Oar, Rudder, Spade, Drill.
Also a few of repair works e.g tyre repair, tow truck, paint service, washing service, Booster service.

I am ready to work, if I can do something, as I have a good hand in Photoshop.

**Comment by tagliala** [comment] 2018-01-24 15:47
Hi!

Thanks for being part of the Font Awesome Community and for your willing to help.

Unfortunately, we are not still accepting PR containing icons

I cannot leave this open as a request because it doesn't meet our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

In the specific:
- Tools is a duplicate of #736
- Drill is a duplicate of #3139
- I cannot allow request with a subset of icons that are not strictly related.

(Maybe there are other duplicates, you should [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones)

If you want to add icons to your own set, please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

The above wiki is valid for FA 4.0 and FA 5.0 CSS. The customization of the SVG framework is still a work in progress

Hope it helps

Closing here

**Closed by tagliala** 2018-01-24 15:47 UTC
