### ISSUE TITLE
Icon Request: fa-moodle/issuu

### ISSUE THREAD

**Issue by vnavarrou** [FortAwesome/Font-Awesome#7745] opened 2015-10-23 12:41 UTC
Hello Font Awesome guys!

In first place you are really awesome, you have a great quantity of icons that help me a lot.
But there are some icons that I need and I think it's related.

Moodle is a e-learning open source platform, and I had developed and installed in some servers in Chile, but I need the icon to promote the use of the platform in the corporative web page of the enterprise. 

And Issuu is a place to upload documents and see as a newspaper. We have an account on Issuu and uploaded some documents (in Spanish), and I need to link the Issuu account with the main web page of the company using an icon.

Have a nice day anf kind regards,
Víctor Navarro U.

**Comment by tagliala** [comment] 2015-10-23 13:04
Hi,

Moodle is a duplicate of #2167 , please +1 that request

Issuu is a duplicate of #1993, please +1 that request

all duplicates, closing here

**Closed by tagliala** 2015-10-23 13:04 UTC
