### ISSUE TITLE
Icon request: fa-package

### ISSUE THREAD

**Issue by leandroruel** [FortAwesome/Font-Awesome#6143] opened 2015-04-02 20:17 UTC
would be great if you add an icon like this:
![](http://thehuntingtonian.com/wp-content/uploads/2014/12/package_pic.jpg)
 a package, is very useful to represent any deliver of a product, or something else related with shopping or delivery

```html
<i class='fa fa-package'></i>
```

**Comment by tagliala** [comment] 2015-04-04 16:57
duplicate of #908 , please +1 that request

closing here

**Closed by tagliala** 2015-04-04 16:57 UTC
