### ISSUE TITLE
Icon Request: fa-teamspeak

### ISSUE THREAD

**Issue by Hismuth** [FortAwesome/Font-Awesome#5730] opened 2015-02-20 07:37 UTC
Teamspeak icon would be very helpful! It would be nice if you guys can add a teamspeak icon
many many many gaming communities will use this icon for sure.
http://www.gezginler.net/indir/resim-grafik/teamspeak-1378815466.png

**Comment by tagliala** [comment] 2015-02-22 00:20
duplicate of #1474 , please +1 that request

closing here

**Closed by tagliala** 2015-02-22 00:20 UTC
