### ISSUE TITLE
Icon request: app collection

### ISSUE THREAD

**Issue by stephenin** [FortAwesome/Font-Awesome#17029] opened 2020-08-12 19:55 UTC
**What can it be used for?**
To show a collection of items. Like google apps in gmail.
**Example image (optional)**
![image](https://user-images.githubusercontent.com/15639361/90061424-2028f300-dcb4-11ea-84fa-19dd7e973daa.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-08-12 20:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15452, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-08-12 20:17 UTC
