### ISSUE TITLE
Icon Request: fa-projects

### ISSUE THREAD

**Issue by mdurchholz** [FortAwesome/Font-Awesome#9281] opened 2016-05-26 16:55 UTC
This is an I con I would like to use in a navigation area for a projects link. This could also be a "files" icon, "stack" icon, or "papers" icon

![projects](https://cloud.githubusercontent.com/assets/3687595/15582795/cda592ae-2340-11e6-859c-54a1782dc522.png)

**Comment by tagliala** [comment] 2016-05-26 21:35
Duplicate of #1179, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-26 21:35 UTC
