### ISSUE TITLE
Icon request: icon-bathroom

### ISSUE THREAD

**Issue by valentinzaraf** [FortAwesome/Font-Awesome#4698] opened 2014-10-09 01:40 UTC

**Comment by antonvanhooydonk** [comment] 2015-02-05 04:11
+1 for this request
Icon Name: icon-bathroom
Look: bathtub with a showerhead
Use cases: real estate, hotel

Please and thank you!

**Comment by SamerX** [comment] 2015-02-23 16:17
+1

**Comment by laviku** [comment] 2015-04-22 15:05
What would be the difference between toilet and bathroom? 

https://cdn1.iconfinder.com/data/icons/hotel-and-restaurant-line-icons-vol-2/64/053-128.png

**Comment by tagliala** [comment] 2015-04-22 16:46
Sorry I still don't get this request.

It may be a water closet as pointed out by @laviku , it could be a toilet sign (in this case, duplicate of: #2670)

I'm going to close this one. Feel free to open a new request with an example

**Closed by tagliala** 2015-04-22 16:46 UTC
Labels: waiting for feedback
