### ISSUE TITLE
IDeal logo

### ISSUE THREAD

**Issue by MaxClasener** [FortAwesome/Font-Awesome#11496] opened 2017-09-06 23:20 UTC
Hi,

it would be great if you guy's could make an ideal logo. (payingmethod)
this is because i use it on my site and its not availble yet.
if you make it could it be in the same range like these:

fa fa-cc-visa
fa fa-cc-mastercard
fa fa-cc-paypal

for example:
fa fa-cc-ideal

thank you!

kind regards,

Max Clasener

**Comment by tagliala** [comment] 2017-09-07 07:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4330, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-07 07:45 UTC
