### ISSUE TITLE
Icon request: fa-aboutme (brand icon)

### ISSUE THREAD

**Issue by ChiscoLeiton** [FortAwesome/Font-Awesome#10264] opened 2016-11-22 06:59 UTC
Hi, thanks for all, you can create the "about me" icon?

https://about.me/

**Comment by tagliala** [comment] 2016-11-22 09:53
Duplicate of #447 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-22 09:53 UTC

**Comment by ChiscoLeiton** [comment] 2016-11-22 16:41
Thanks...
