### ISSUE TITLE
Icon Request: fa-file-chart-o (report)

### ISSUE THREAD

**Issue by ntfox** [FortAwesome/Font-Awesome#6366] opened 2015-05-02 11:06 UTC
hi
please add report icon

**Comment by tagliala** [comment] 2015-05-02 12:09
could you pleae provide a single color example suitable for 14px icon size?

**Comment by ntfox** [comment] 2015-05-02 15:03
https://www.iconfinder.com/icons/217123/analytics_bar_chart_diagram_document_file_graph_internet_marketing_optimization_page_paper_pie_presentation_report_statistics_icon

**Comment by ntfox** [comment] 2015-05-13 04:05
![image](https://cloud.githubusercontent.com/assets/3767882/7603572/08032496-f94b-11e4-8aa7-f3ab45f230cc.png)

**Comment by EddieFromFA** [comment] 2015-06-09 16:23
+1

**Comment by fsworld009** [comment] 2015-07-02 12:18
+1

**Comment by G-Driver** [comment] 2016-01-12 10:17
+1

**Comment by hpvd** [comment] 2016-02-22 15:22
+1

**Comment by tagliala** [comment] 2016-03-08 10:37
closing here as a duplicate of #1076

**Closed by tagliala** 2016-03-08 10:37 UTC
Labels: new icon, web application icons
