### ISSUE TITLE
Icon request: Nook Books

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#14127] opened 2018-10-17 18:04 UTC
### What can it be used for?
Used for social icons relating to ebooks through barnesandnoble.com

### Example image (optional)

https://www.google.com/search?q=Nook+Books+icon&newwindow=1&safe=off&rlz=1C1GGRV_enUS752US752&tbm=isch&source=iu&ictx=1&fir=2j_I0vadAyTmVM%253A%252Cfpcm-BLsklLZ0M%252C_&usg=AI4_-kRq8RFS0Goo5_YnHsXpFvr5BSayPw&sa=X&ved=2ahUKEwits4DRho7eAhWO7Z8KHVcJBfcQ9QEwAHoECAYQBA#imgrc=2j_I0vadAyTmVM:

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
Single
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
Yes
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
Yes
- [ ] I have included at least one example image if it could be helpful (optional)
Yes
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by cono-mich** [comment] 2018-10-18 16:49
Hi, I have an update for you. I attached an image of the current icon being used for NOOK Books. 
![nookbooksicon](https://user-images.githubusercontent.com/23465576/47170544-1d793480-d2bb-11e8-9610-76b6f7cbc6e5.png)

**Comment by cono-mich** [comment] 2018-10-30 14:51
Hi, wanting to quickly follow up with this request. If there is anything I can do to help, please reach out. Thank you.

**Comment by aethior** [comment] 2022-04-11 03:37
Duplicate of #15290.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-04-11 13:26
Same amount of +1, let's use #15290

**Closed by tagliala** 2022-04-11 13:26 UTC
Labels: brand icon
