### ISSUE TITLE
fa fa vaccine

### ISSUE THREAD

**Issue by rotakeo** [FortAwesome/Font-Awesome#6048] opened 2015-03-23 16:52 UTC
Please is it possible a icon related to vaccine?

**Comment by afrome** [comment] 2015-03-23 17:54
+1

**Comment by tagliala** [comment] 2015-03-23 19:13
any example?

**Comment by afrome** [comment] 2015-03-23 19:24
http://thenounproject.com/term/vaccine/4329/ ?

**Comment by tagliala** [comment] 2015-03-23 19:44
may this be considered a duplicate of #1779 ?

**Comment by afrome** [comment] 2015-03-23 20:19
Yes, for me #1779 would satisfy the vaccine requirement. Thanks!

**Comment by tagliala** [comment] 2015-03-23 21:19
So I should ask you and @rotakeo  to +1 #1779 because there will be more chances of being included.

But I should also advise to consider a custom build of FA: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2015-03-23 21:19 UTC
Labels: new icon, waiting for feedback, web application icons
