### ISSUE TITLE
Icon request: hand-holding-euro

### ISSUE THREAD

**Issue by kawurm** [FortAwesome/Font-Awesome#19891] opened 2023-09-13 13:55 UTC

**Comment by aethior** [comment] 2023-09-28 20:48
Duplicate of #12772, but this issue is more clear (IMHO).

cc/ @tagliala

**Comment by tagliala** [comment] 2023-09-29 13:20
Agreed, that request contains a lot of icons, has a negligible number of upvotes and includes other requests in the comments

**Comment by sensibleworld** [comment] 2024-07-11 14:35
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed as not planned by sensibleworld** 2024-07-11 14:35 UTC
Labels: new icon, charity (category), Declined
