### ISSUE TITLE
Icon Request: fa-youku

### ISSUE THREAD

**Issue by dawey** [FortAwesome/Font-Awesome#4365] opened 2014-09-08 09:59 UTC
There is a Chinese video platform called - 
www.youku.com 
and i would highly appreciate - if you could integrate that one. 

thank you
david

**Comment by mcarv63** [comment] 2015-03-28 00:38
+1 want it

**Comment by Aspirinwang** [comment] 2015-05-03 20:43
+1

**Comment by brajeshjadiya** [comment] 2015-07-01 10:27
I am also request for add "fa-youku" on your font list. Thank's

**Comment by tagliala** [comment] 2015-08-03 07:29
duplicate of #3487, please +1 that request

closing here

**Closed by tagliala** 2015-08-03 07:29 UTC
Labels: brand icons, new icon
