### ISSUE TITLE
Icon Request: fa-dental

### ISSUE THREAD

**Issue by dario6000** [FortAwesome/Font-Awesome#6800] opened 2015-06-22 01:19 UTC
Hi I need a dental icon brush
![cepillo](https://cloud.githubusercontent.com/assets/12993165/8274224/219197a6-185b-11e5-8c3c-992ee9745881.PNG)

**Comment by tagliala** [comment] 2015-07-05 12:41
duplicate of #5623, please +1 that request

closing here

**Closed by tagliala** 2015-07-05 12:41 UTC
