### ISSUE TITLE
Icon request: wet-floor-without-sign

### ISSUE THREAD

**Issue by hanselsen** [FortAwesome/Font-Awesome#13765] opened 2018-08-14 07:22 UTC
Refering to issue #10099, could it be possible to add this to the list without the triangle around it?  

Also, this icon #10099 is not yet in the list on the website. How does this work usually?

Can you make it compatible with the light series please?

![untitled](https://user-images.githubusercontent.com/1150323/44077412-e4a7c224-9fa3-11e8-8c64-96aa8c122ba9.png)

**Comment by tagliala** [comment] 2018-08-14 08:04
#10099 is a duplicate of #8054

> Also, this icon #10099 is not yet in the list on the website. How does this work usually?

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome and here https://fontawesome.com/community/leaderboard/new

**Comment by tagliala** [comment] 2018-08-14 19:25
this is not a duplicate

**Comment by sensibleworld** [comment] 2024-07-11 19:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/person-falling?f=classic&s=solid)

**Closed by sensibleworld** 2024-07-11 19:23 UTC
Labels: new icon, web application icons (legacy category), FA Pro
