### ISSUE TITLE
Icon request: hat-chef

### ISSUE THREAD

**Issue by l2aelba** [FortAwesome/Font-Awesome#14855] opened 2019-04-04 12:49 UTC
### What can it be used for?
- Cooking / Foods / Kitchen / Chefs / Bake
**Font Awesome** has [many hats](https://fontawesome.com/icons?d=gallery&q=hat), but why we are missing a **chef's hat**? 👨‍🍳 👩‍🍳
This icon should be **super usable** for restaurant websites, for example.

### Example image

![hat-chef](https://user-images.githubusercontent.com/983458/55557170-8a597d00-56e9-11e9-8f1b-0ce089a73f2a.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-04-04 13:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2598, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-04 13:19 UTC
