### ISSUE TITLE
Icon request: icon-tape-measure

### ISSUE THREAD

**Issue by naluoli** [FortAwesome/Font-Awesome#12451] opened 2018-02-26 23:20 UTC
### What can it be used for?

Used to show measurement of items.

### Example image (optional)

![image](https://user-images.githubusercontent.com/36716550/36701498-7b60eb1c-1b08-11e8-9aae-bd17f861e653.png)

### Icon request checklist

- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [yes ] I have included at least one example image if it could be helpful (optional)
- [ yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-02-28 13:29
duplicate of #8437

**Closed by tagliala** 2018-02-28 13:29 UTC
