### ISSUE TITLE
Icon Request: diploma-icon

### ISSUE THREAD

**Issue by Chej0** [FortAwesome/Font-Awesome#11045] opened 2017-05-09 19:08 UTC
I need a Diploma icon or Certificate icon, something like this
![image](https://cloud.githubusercontent.com/assets/26882572/25867981/8ec47796-34b8-11e7-900b-1c6f22a32e28.png)
I need it becouse I have an aplication where the people can upload pictures of their Diplomas. I have the Upload Icon but the people are confused about that so that's what I need a Diploma icon

**Comment by tagliala** [comment] 2017-05-09 19:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1379, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-09 19:16 UTC
