### ISSUE TITLE
Icon request: Discord logo

### ISSUE THREAD

**Issue by lepeli** [FortAwesome/Font-Awesome#10883] opened 2017-04-03 18:58 UTC
I request a new icon for the brand Discord

Like this
![discord-logo-black](https://cloud.githubusercontent.com/assets/24854702/24625707/272c5dde-18b0-11e7-92a5-02f92acc14e6.png)

Thanks.
Regards.

**Comment by tagliala** [comment] 2017-04-03 19:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-03 19:01 UTC
