### ISSUE TITLE
Icon Request: fa-bootstrap

### ISSUE THREAD

**Issue by loki1000101** [FortAwesome/Font-Awesome#7229] opened 2015-08-13 21:04 UTC
Hi im looking for icons for my portfolio www.
Icons of libraries and components for things like: 
"powered with fa-jquery".
fa-bootstrap
fa-jquery
fa-less
fa-w3c
![info](https://cloud.githubusercontent.com/assets/13787045/9261510/aa363a26-420e-11e5-9ee6-ba8a98066758.png)

**Comment by TheChen5** [comment] 2015-08-13 22:32
JQuery dupe #1665 
Bootstrap #1828 
W3C #1547
Less *probably* is a dupe of #2567
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-08-15 09:19
@TheChen5 thanks

less is a dup of #2567

All duplicates, closing here

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Closed by tagliala** 2015-08-15 09:19 UTC
