### ISSUE TITLE
Icon Request: fa-open-book

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7012] opened 2015-07-23 00:13 UTC
fa-open-book icon:

![Open Book](http://i.imgur.com/AKsCayG.png)
Source: https://www.iconfinder.com/icons/274892/book_ebook_education_learning_library_reading_school_science_study_text_icon#size=128

**Comment by tagliala** [comment] 2015-07-23 10:08
duplicate of #176  or #6595 , please +1 those requests

closing here

**Closed by tagliala** 2015-07-23 10:08 UTC

**Comment by tuxy** [comment] 2015-07-24 04:05
@tagliala, done on #176 but #6595 refers to wiki, so that different. Thank You!

**Comment by tagliala** [comment] 2015-07-24 11:56
#6595 is a github-style wiki that actually is an open book https://octicons.github.com/icon/book/
