### ISSUE TITLE
Icon request: font-size-increase font-size-decrease

### ISSUE THREAD

**Issue by demiantres** [FortAwesome/Font-Awesome#11009] opened 2017-04-30 09:20 UTC

**Comment by tagliala** [comment] 2017-04-30 10:31
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1469 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-30 10:31 UTC
