### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by ecyrbrengots** [FortAwesome/Font-Awesome#19551] opened 2023-02-08 21:32 UTC
Please add international currency icons such as Czech Koruna
![Czech Koruna](https://user-images.githubusercontent.com/57873505/217655710-6dea6227-2bb2-42b4-816c-dba6833572bc.png)

**Comment by tagliala** [comment] 2023-02-08 22:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1978, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-02-08 22:29 UTC

**Comment by ecyrbrengots** [comment] 2023-02-09 00:53
Hi Geremia,

I appreciate the update here. However, the request has been open since 2013. 

Will this icon be added or not? 
How long does it normally take to determine a direction on icon requests?
Is 10 years a normal timeframe?

Thank you,
Bryce Stogner

**Comment by tagliala** [comment] 2023-02-09 09:48
Hi,

All your questions have been answered in the [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), please take a look

Please consider a customization if you need this icon in a short while. There are many approaches to customize Font Awesome, both free and paid. One of the easiest one requires SVG+JS framework and a build system like webpack: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
