### ISSUE TITLE
Icon request: icon-infinity

### ISSUE THREAD

**Issue by DiedsFou** [FortAwesome/Font-Awesome#8989] opened 2016-04-15 08:03 UTC
&lt; i class="fa fa-infinity"&gt;&lt;/i&gt; possibilities!!

page 1 ....&lt; i class="fa fa-infinity"&gt;&lt;/i&gt;

![image](https://cloud.githubusercontent.com/assets/18479444/14555141/103e30fa-02f1-11e6-9d9a-9dfbd91c76fd.png)

**Comment by PeterShaggyNoble** [comment] 2016-04-15 08:20
Dupe of [#1647](https://github.com/FortAwesome/Font-Awesome/issues/1647), you should +1 that instead.

**Closed** 2016-04-15 09:15 UTC
