### ISSUE TITLE
Icon Request: fa-glitch

### ISSUE THREAD

**Issue by IbrahimTareq** [FortAwesome/Font-Awesome#13065] opened 2018-05-08 04:43 UTC
https://glitch.com/

[glitch_logo.zip](https://github.com/FortAwesome/Font-Awesome/files/1982325/glitch_logo.zip)

**Comment by tagliala** [comment] 2018-05-08 14:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11883, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-08 14:12 UTC
