### ISSUE TITLE
Icon Request: fa-itunes

### ISSUE THREAD

**Issue by susanaro** [FortAwesome/Font-Awesome#6029] opened 2015-03-21 01:08 UTC
Please I need de itunes icon and the Deezer icon. 
For musician sites. Thank you!

**Comment by sidewalkdriver** [comment] 2015-03-21 21:59
+1 for iTunes

**Comment by tagliala** [comment] 2015-03-21 22:00
duplicate of #919 , please +1 that request

closing here

**Closed by tagliala** 2015-03-21 22:00 UTC
