### ISSUE TITLE
Icon Request: fa-lattes

### ISSUE THREAD

**Issue by calex25** [FortAwesome/Font-Awesome#11392] opened 2017-08-12 17:07 UTC

**Comment by tagliala** [comment] 2017-08-12 17:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6883, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-12 17:09 UTC
