### ISSUE TITLE
Icon Request: fa-hanger

### ISSUE THREAD

**Issue by AVHristich** [FortAwesome/Font-Awesome#15209] opened 2019-06-30 03:50 UTC
Icon of hanger for clothes. Will be used on the pages of the online store

**Icon request checklist**
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2019-06-30 06:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1659, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-06-30 06:34 UTC
