### ISSUE TITLE
Icon Request: fa-podcast

### ISSUE THREAD

**Issue by MidoSpace** [FortAwesome/Font-Awesome#6749] opened 2015-06-14 11:20 UTC
Hello awesome people :)
Would you please add a podcast icon? 
I would use it in my podcast site, where I put description and subscribe button.

Here's how it should look like
https://camo.githubusercontent.com/9335e8734f708c008994fccf60973b4fb3458220/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313033303234322f313839323939382f32353262376262612d376136352d313165332d396632322d6535353263306337346433652e706e67

Thank you so much :)
~Ahmed

**Comment by tagliala** [comment] 2015-07-01 19:21
duplicate of #2125, please +1 that request

closing here

**Closed by tagliala** 2015-07-01 19:21 UTC
