### ISSUE TITLE
minecraft icon

### ISSUE THREAD

**Issue by speedmcyt** [FortAwesome/Font-Awesome#14490] opened 2019-01-10 21:13 UTC
Please Add Minecraft Icon

**Comment by tagliala** [comment] 2019-01-10 21:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1776, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-01-10 21:50 UTC
