### ISSUE TITLE
Icon request: bench

### ISSUE THREAD

**Issue by ashbryant1212** [FortAwesome/Font-Awesome#18600] opened 2022-01-22 00:02 UTC
**What can it be used for?**
This could be another option for a toolbox, or a stool, or chair

**Example image (optional)**
Insert the example image here if necessary.
<img width="121" alt="Screen Shot 2022-01-21 at 4 59 45 PM" src="https://user-images.githubusercontent.com/98194619/150614913-da6b75fe-c3e8-4e06-9185-8755d85080e7.png">

**Icon request checklist**
- [ ] This is a single icon 
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image.
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2022-01-22 09:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16451, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-01-22 09:04 UTC
