### ISSUE TITLE
Icon Request: icon pay-check

### ISSUE THREAD

**Issue by alissonbarison** [FortAwesome/Font-Awesome#5509] opened 2015-01-28 13:11 UTC
icon to be using in forms of payments, eg money, credit card, paypal.
this would be one more in the payment icons list.
a name for the icon would be: fa-payment-check

![cheque](https://cloud.githubusercontent.com/assets/4990115/5938022/b72c57b2-a6d5-11e4-8bd1-188f8e1b049f.png)

**Comment by tagliala** [comment] 2015-01-28 14:26
duplicate of #2603, please +1 that reqeust

closing here

**Closed by tagliala** 2015-01-28 14:26 UTC
