### ISSUE TITLE
Icon request: vehicle engine

### ISSUE THREAD

**Issue by daytonlowell** [FortAwesome/Font-Awesome#15034] opened 2019-05-15 21:28 UTC
### What can it be used for?

Represent an engine from a vehicle. Or the more abstract "part" from a vehicle.

### Example image (optional)

![image](https://user-images.githubusercontent.com/305993/57810801-4d43ca00-772e-11e9-8375-b6ec3f56b6a2.png)

**Comment by tagliala** [comment] 2019-05-16 07:23
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4175, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-05-16 07:23 UTC
