### ISSUE TITLE
Icon request: icon-google-amp

### ISSUE THREAD

**Issue by mennoweerepas** [FortAwesome/Font-Awesome#17192] opened 2020-09-23 14:22 UTC
**What can it be used for?**
brands.

**Example image (optional)**
Insert the example image here if necessary.

<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M8 0C3.568 0 0 3.568 0 8C0 12.4325 3.5675 16 8 16C12.4325 16 16 12.432 16 8C16 3.568 12.432 0 8 0ZM10.7223 6.77152H8.642L9.32677 3H8.63475L5.10674 8.61902C4.82194 9.08555 5.1972 9.229 5.1972 9.229L7.30977 9.24192L6.67627 13H7.34198L10.9352 7.25071C11.1615 6.77152 10.7223 6.77152 10.7223 6.77152Z" fill="#333333"/>
</svg>

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-09-27 07:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14739, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-27 07:53 UTC
