### ISSUE TITLE
fa-square and fa-square-o are not same size

### ISSUE THREAD

**Issue by wpc** [FortAwesome/Font-Awesome#7196] opened 2015-08-10 23:46 UTC
fa-square-o seems smaller than most of the other form icons. When font-size set to 280, fa-square is about 240px wide, fa-square-o is 220px wide. This make it hard to use the switching between them to represent a "select" effect on the UI.

**Comment by acshef** [comment] 2015-08-12 18:01
Duplicate of #4649.
The temporary workaround (http://jsfiddle.net/qexm7bf0/) is to use the `fa-fw` class (fixed-width) which give the character the widest width of any FontAwesome character, and centers the character. It's no where near perfect though.

**Comment by tagliala** [comment] 2015-08-15 09:27
Closing here as a duplicate of #4649

**Closed by tagliala** 2015-08-15 09:27 UTC
