### ISSUE TITLE
Icon Request: icon-hand-stop

### ISSUE THREAD

**Issue by balihoo-sbaird** [FortAwesome/Font-Awesome#3933] opened 2014-07-18 15:22 UTC
I'm designing an app where you start and stop marketing campaigns. The play/pause metaphor works and you've got icons for that, but I'd rather do more of a go/stop metaphor. I am using your thumbs up for go, but thumbs down has more of a "rejection" connotation than "stop". Could you do a stop sign, and/or a hand help up with all fingers extended together to say "halt!"? That would be ideal. I will attach an image of the ideal icon I got from another source.
Thanks for the awesome icons!
![halt](https://cloud.githubusercontent.com/assets/7987405/3627979/58eebc96-0e8f-11e4-854f-39125a964d2e.PNG)

**Comment by tagliala** [comment] 2015-03-16 20:33
duplicate of #1651 :)

**Closed by tagliala** 2015-03-16 20:33 UTC
Labels: new icon, web application icons
