### ISSUE TITLE
telgram icon

### ISSUE THREAD

**Issue by farbodDreamliner** [FortAwesome/Font-Awesome#9908] opened 2016-09-12 16:06 UTC
telegram icon as a social media . thank you .

**Comment by tagliala** [comment] 2016-09-12 16:12
Duplicate of #3034 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-12 16:12 UTC
