### ISSUE TITLE
Icon request: SQL and C# icons please

### ISSUE THREAD

**Issue by Fullsailer** [FortAwesome/Font-Awesome#17806] opened 2021-04-09 21:01 UTC
**What can it be used for?**
This would be good for people downloading you icon.
**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/40461634/114240154-134cc400-9955-11eb-9ee7-84a0a2c7e5ba.png)

![image](https://user-images.githubusercontent.com/40461634/114240226-2f506580-9955-11eb-849b-e2a25117d681.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-04-09 21:19
Hi!

Thanks for being part of the Font Awesome Community.

c# is a duplicate of #8365, please add a 👍 reaction to that request.
sql is a duplicate of #9555, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-04-09 21:19 UTC
