### ISSUE TITLE
Icon Request: fa-triangle + fa-triangle-o

### ISSUE THREAD

**Issue by maudnals** [FortAwesome/Font-Awesome#11412] opened 2017-08-16 15:31 UTC
Hi there, it would be great to have a **simple triangle** icon!

Typical use case: an **upvote icon** button as an alternative to facebook's thumbs up.
The filled + outline versions would help, so that the icon can be outlined by default, and filled when the user has upvoted.

Thanks a ton!

**Comment by tagliala** [comment] 2017-08-16 15:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3216, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-16 15:44 UTC

**Comment by timtjtim** [comment] 2017-08-16 15:46
Also http://fontawesome.io/icon/sort-asc/ is a filled triangle and http://fontawesome.io/icon/angle-up/ is kinda an outline, but not really suitable for that.

**Comment by maudnals** [comment] 2017-08-21 05:44
I'll upvote #3216 because I need an actual triangle rather than a hack, yet thanks @timtjtim for the suggestions!
