### ISSUE TITLE
Icon request: propane-cylinder

### ISSUE THREAD

**Issue by DavyNixon** [FortAwesome/Font-Awesome#17574] opened 2021-01-22 11:38 UTC
**What can it be used for?**
This icon could be used to represent propane cylinder

**Example image (optional)**
https://jeffsbackyardstore.com/wp-content/uploads/2018/07/propane-icon.png

**Icon request checklist**
Single icon request

**Comment by tagliala** [comment] 2021-01-22 12:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8142 or #4318, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Comment by aethior** [comment] 2022-07-25 05:49
Also known as `gas bottle` and `gas cylinder`  _(synonyms to optimize future searches)_.

**Comment by aethior** [comment] 2022-07-25 05:52
@tagliala `energy (category)` label for this request?

**Comment by sensibleworld** [comment] 2024-07-11 15:55
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 15:55 UTC
Labels: new icon, energy (category), Declined
