### ISSUE TITLE
Icon request: thumbtack-slash

### ISSUE THREAD

**Issue by SchutzPetr** [FortAwesome/Font-Awesome#15298] opened 2019-07-28 01:26 UTC
**What can it be used for?**
I'm planning to use it for unpin item from dashboard. 

**Example image (optional)**
![image](https://user-images.githubusercontent.com/4661328/62001060-5b777480-b0e7-11e9-89d0-72fe9889090c.png)

**Comment by tagliala** [comment] 2019-07-28 08:44
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/142/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by AlexDanault** [comment] 2022-02-01 16:27
+1 on this request.

Of course we could make this "unpin" icon using transforms/masking/layering, but the result woudn't be uniform with the all the other icons which do have a "-slash" variant. 

Also, combining "ban" with any icon results in a much bigger icon (so that the thumbtack fits in the ban icon) so this poses a lot of challenges to make them fit / align nicely.

**Comment by youssefqarri** [comment] 2024-02-05 16:23
I think that would be good to have it

**Comment by RuanWzo** [comment] 2024-05-03 15:36
Yes, we need this.

**Comment by sensibleworld** [comment] 2024-07-11 18:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/10749)

**Closed by sensibleworld** 2024-07-11 18:37 UTC
Labels: new icon, web application icons (legacy category), Duplicate
