### ISSUE TITLE
Icon request: cc-maestro

### ISSUE THREAD

**Issue by PinkMeNow** [FortAwesome/Font-Awesome#16185] opened 2020-02-12 11:07 UTC
This icon represents Maestro debt card (sub. of Mastercard, thats why it looks so similar) and on web and in apps is used as payment method icon along with other credit cards such as AmEx, Mastercard, Diners, etc,  we can usually see in the footers or payment method screens.
This card has been requested some 6 years ago, but it never happened.
The card is accepted globally and is rather popular in Europe and Asia (see Wikipedia entry below, and I know some markets are not listed on this list) and by not having this icon, people tend use other icons or fonts that make a credit card icon set.

Example image from Wikipedia [[LINK]](https://en.wikipedia.org/wiki/Maestro_(debit_card))

**Comment by tagliala** [comment] 2020-02-18 22:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4266, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-02-18 22:01 UTC
