### ISSUE TITLE
Icon request: icon-Fediverse

### ISSUE THREAD

**Issue by wznmickey** [FortAwesome/Font-Awesome#19016] opened 2022-05-08 07:32 UTC
Now mastodon is added. Mastodon is one kind of service in Fediverse. Why not add Fediverse so that other services can use it rather than using Mastodon icon to imply other services in Fediverse.

**Comment by tagliala** [comment] 2022-05-08 08:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16252, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-05-08 08:13 UTC
