### ISSUE TITLE
Icon Request: fa-dna

### ISSUE THREAD

**Issue by wdmeeste** [FortAwesome/Font-Awesome#8781] opened 2016-03-18 08:13 UTC
DNA strand
Example: http://www.iconarchive.com/show/medical-icons-by-icons-land/Body-DNA-icon.html

**Comment by aethior** [comment] 2016-03-18 11:57
Hi @wdmeeste,

This request is duplicate of #1195. Please +1 that.

Regards.

**Closed** 2016-03-18 15:04 UTC
