### ISSUE TITLE
Icon request: fa-paint-brush-o

### ISSUE THREAD

**Issue by fikipollo** [FortAwesome/Font-Awesome#7538] opened 2015-09-25 07:14 UTC
Would be nice if you include this icon. Anyway, thanks for the awesome library!!

![fa-paint-brush-o](https://cloud.githubusercontent.com/assets/11427394/10094962/14170e3e-6366-11e5-8b55-8f866a29edf8.png)

As I already did it, here you can find the TTF, SVG and PNG files, just in case you want to use it :)

https://github.com/fikipollo/font-awesome-add-icons

**Comment by tagliala** [comment] 2015-09-25 14:23
already here: http://fontawesome.io/icon/paint-brush/

**Comment by tagliala** [comment] 2015-09-25 14:24
ops sorry. but the example is wrong...

paint-brush-o: 
![image](https://cloud.githubusercontent.com/assets/556268/10103000/e233e554-63a1-11e5-92a9-1a6d3d6e0a12.png)

**Comment by tagliala** [comment] 2015-09-25 14:24
anyway... duplicate of #7327, please +1 that request

closing here

**Closed by tagliala** 2015-09-25 14:24 UTC
