### ISSUE TITLE
Icon Request: fa-bakery

### ISSUE THREAD

**Issue by nicho90** [FortAwesome/Font-Awesome#6736] opened 2015-06-12 11:46 UTC

**Comment by nicho90** [comment] 2015-06-12 11:53
Hey it would be awesome if you could provide a bakery-icon, e.g. the shape of a bread. 
Best, Nicho

**Comment by tagliala** [comment] 2015-07-05 12:46
duplicate of #1386 , please +1 that request

closing here

**Closed by tagliala** 2015-07-05 12:46 UTC
