### ISSUE TITLE
Icon Request: fa-line-messager   

### ISSUE THREAD

**Issue by fauzanrozaq** [FortAwesome/Font-Awesome#9951] opened 2016-09-22 16:44 UTC
i guess need add icon social media in     http://fontawesome.io/icons/

**Comment by tagliala** [comment] 2016-09-22 17:41
Duplicate of #2631 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-22 17:41 UTC
