### ISSUE TITLE
Icon request: tiktok

### ISSUE THREAD

**Issue by zsoltjanes** [FortAwesome/Font-Awesome#16089] opened 2020-01-19 18:38 UTC
**What can it be used for?**
I would like to use this icon on my website for link my profile. https://www.tiktok.com/en/

**Example image (optional)**
https://image.shutterstock.com/z/stock-vector-letter-icon-tiktok-vector-illustration-1273064443.jpg

**Comment by tagliala** [comment] 2020-01-19 19:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14340 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-19 19:47 UTC
