### ISSUE TITLE
translate(0, 0) kills z-index

### ISSUE THREAD

**Issue by mentor2k1** [FortAwesome/Font-Awesome#6023] opened 2015-03-20 14:35 UTC
The facebook icon should be lay under the red div:

http://jsfiddle.net/ovab9gL5/8/

there is an thread on stackoverflow: http://stackoverflow.com/questions/5472802/css-z-index-lost-after-webkit-transform-translate3d , but this doesn´t solve the problem

**Comment by davegandy** [comment] 2015-03-20 14:38
This is interesting. The `translate(0,0)` helps out with Firefox rendering, but it's not so important if it's breaking z-index.

@tagliala What do you think here?

**Comment by tagliala** [comment] 2015-03-20 14:55
I would remove that rule and preserve z-index

**Comment by herrquark** [comment] 2015-03-26 10:43
```css
@-moz-document url-prefix() { 
  .@{fa-css-prefix} {
    transform: translate(0, 0); // ensures no half-pixel rendering in firefox
  }
}
```

**Comment by tagliala** [comment] 2015-04-02 18:51
Also see #6142

**Comment by gameguy43** [comment] 2015-05-27 20:58
We just experienced this issue on our website as well.

We have social buttons in the footer. We also have a "notepad" that slides up from the bottom of the page, as an "overlay". The font-awesome icons from the footer appear /on top/ of the overlay, even though they have a lower z-index.

So I'd vote with @tagliala on this.

For now, we're patching this in our master CSS file like so:
.fa{
    transform: none !important;
}

**Comment by guibirow** [comment] 2015-07-15 07:38
I'm with the same problem, I had to fix as @gameguy43  described.

My doubt is.
Why do I need the transform?
I couldn't notice any difference!

**Comment by tagliala** [comment] 2015-07-15 07:55
@guibirow 
https://github.com/FortAwesome/Font-Awesome/issues/6023#issuecomment-84033518

I can confirm there is a difference

**Comment by guibirow** [comment] 2015-07-16 04:22
Sorry, But this doesn't answer my question.
the post above said it will improve firefox rendering, but I removed and checked everywhere, there is no difference into design, 
Just to be clear, the small difference I could notice is icon inside H2 tag, about 1px difference, nothing else different.
I'm using ff 39, maybe it only applies to some ff version.

**Comment by tagliala** [comment] 2015-07-16 10:22
![image](https://cloud.githubusercontent.com/assets/556268/8720796/36cc1a3e-2bb5-11e5-9ebb-c724a08947e2.png)

FF 39, windows 7. There is definitely a difference

**Comment by Download** [comment] 2015-07-17 15:38
Sorry if this is lame, but can you spell it out for me? I truly see no difference.

**Comment by tagliala** [comment] 2015-07-17 20:52
![image](https://cloud.githubusercontent.com/assets/556268/8756912/361783e0-2cd6-11e5-95e1-920599b21355.png)

`credit-card` and `envelope-o` at 800% zoom, no antialiasing.

1px vertical lines with transform (left side) are far better

**Comment by Download** [comment] 2015-07-17 20:56
Ok. Subtle! Weird that it would make such a difference. Thank you for showing it.

**Comment by tagliala** [comment] 2015-07-17 20:58
you're welcome. btw the z-index is more important so this rule will be probably removed

**Comment by guibirow** [comment] 2015-07-18 00:50
Now I see a light difference, but users doesn't care about this.
We see it everyday and hardly can notice any difference, 
I'm sure nobody will zoom at that point.
Thanks to spend your time too explain.

**Comment by tagliala** [comment] 2015-07-18 08:32
@guibirow I can clearly spot the difference at 100%. :confused:

**Comment by guibirow** [comment] 2015-07-18 21:59
Sorry, but I'm sure if you show the icon without transform to a regular person, and ask whats wrong, nobody will notice anything.
You can notice because you are used to handle it every day, I see the icons every day, after I removed I couldn't see any difference if you didn't tell.
it's that kind of thing you never notice, after the first time you can't forget even after fixed.

**Comment by tagliala** [comment] 2015-07-18 22:51
The problem is that we just need to provide icons, and we want to provide icons at the best we can. If a transform is needed to make vertical lines crisper, then we should use it.

But... if the before mentioned transform breaks z-index, I would definitely remove that rule :) https://github.com/FortAwesome/Font-Awesome/issues/6023#issuecomment-84036851

**Comment by davegandy** [comment] 2015-07-28 06:37
This is a really sad one for me to lose. I thought I had Firefox rendering finally down.

Any other things we can try to see about getting that pixel perfection back in Firefox?

**Comment by davegandy** [comment] 2015-07-28 06:51
Removed translate() from 4.4.0-wip branch. Closing...

**Closed by davegandy** 2015-07-28 06:51 UTC
Labels: bug, css

**Comment by joshperry** [comment] 2015-10-08 18:09
I was unintentionally relying on this bug for proper z-index stacking of a kebab menu icon. Ooops, that was a fun bug to track down.

**Comment by irthos** [comment] 2019-01-13 12:41
Revisting this issue. I have a use case where user behaviour dictates the size of button icons and transform is the best css method to scale without breaking layout. Has anyone at FA figured looked into this since?
