### ISSUE TITLE
Icon request: gatsby-js

### ISSUE THREAD

**Issue by joesanchezjr** [FortAwesome/Font-Awesome#15114] opened 2019-06-05 21:22 UTC
**What can it be used for?**
With the popularity among developers to use frameworks for their projects, this icon can be used as an indication of knowledge of the GatsbyJS framework in portfolios or as a simple way to indicate that the site is using the GatsbyJS - e.g. "Made with ❤ using [gatsby-js icon]" in the footer

**Example image**
Brand logo is found on their website: https://www.gatsbyjs.org

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-06-06 07:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12510, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-06-06 07:58 UTC
