### ISSUE TITLE
Icon Request:fa-machinelearning

### ISSUE THREAD

**Issue by chandrayee31** [FortAwesome/Font-Awesome#10091] opened 2016-10-20 09:44 UTC
![machinelearning_icondark](https://cloud.githubusercontent.com/assets/22955736/19554667/3e3e592e-96d7-11e6-9379-72f405452f6d.png)

Please make a icon for machine learning project.I have suggested one png file,but please make it.I need it for my project.

![machinelearning_icon](https://cloud.githubusercontent.com/assets/22955736/19554771/aec24200-96d7-11e6-9f1c-2da747b607cb.png)

This icon is for transparent background.you can name it as 'fa-machinelearning-o'

Thanks in advance

Chandrayee

**Comment by tagliala** [comment] 2016-10-20 12:20
Duplicate of #8675 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-20 12:20 UTC
