### ISSUE TITLE
icon request : icon-capture

### ISSUE THREAD

**Issue by meghna300** [FortAwesome/Font-Awesome#11826] opened 2017-12-03 05:10 UTC
* use it as a website brand
* ![camera-shutter-512](https://user-images.githubusercontent.com/31474001/33522594-4b172f50-d816-11e7-8361-b58ab6fc521c.png)

**Comment by tagliala** [comment] 2017-12-03 11:32
Could you please provide more information about this brand?

**Comment by axelrindle** [comment] 2017-12-03 15:47
I don't think this is a brand but rather an icon for a camera application (**capture** images).

**Comment by tagliala** [comment] 2017-12-03 15:49
@axelrindle thanks

the OP contains:

> use it as a website brand

btw, if this is not a brand, it is a duplicate of #6392

**Comment by tagliala** [comment] 2018-03-14 10:41
No feedback, considering this a duplicate of #6392

**Closed by tagliala** 2018-03-14 10:41 UTC
Labels: waiting for feedback
