### ISSUE TITLE
Naira icon

### ISSUE THREAD

**Issue by pianistprogrammer** [FortAwesome/Font-Awesome#11291] opened 2017-07-14 22:29 UTC
I write to font awesome a while ago begging them to create the naira icon as part of the icons in the currency section,  but unfortunately they seem to have issues with Nigerians I really don't know why, maybe the house can help us beg them

**Comment by tagliala** [comment] 2017-07-15 07:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9412 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Please note that Font Awesome receives dozens of new request every day and it is unlikely to implement them all in a single icon set. Please take a look at [Customize Font Awesome](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome) if you are interested in a custom version

Please also note that you can use standard unicode point: **₦** as a workaround. Example: https://jsfiddle.net/tagliala/s3msxtbe/20/

Hope it helps, closing here

**Comment by tagliala** [comment] 2018-06-07 10:49
Reopening because  #9412 has been closed by the author

**Comment by pianistprogrammer** [comment] 2018-06-07 11:10
This was a better work around, on the jsfiddle

**Comment by kusaasira** [comment] 2018-06-07 11:19
Thank you @tagliala . Remember the work around is different from the icon I do not know if you get. It is like quenching for water and you're given soda.

**Comment by oy3** [comment] 2020-08-03 22:13
Has this issue been resolved?

**Comment by sensibleworld** [comment] 2020-11-03 23:43
This is available as part of the v6 alpha release: https://fontawesome.com/download

**Closed by sensibleworld** 2020-11-03 23:43 UTC
Labels: currency (category), in progress, new icon
