### ISSUE TITLE
Icon request: ATM icon

### ISSUE THREAD

**Issue by ahmedbaghdadi1987** [FortAwesome/Font-Awesome#15469] opened 2019-09-02 09:10 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
In shiny app, I'm trying to add ATM icon to a valuebox
**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `**lock**` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-09-02 09:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5103, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-02 09:35 UTC

**Comment by ahmedbaghdadi1987** [comment] 2019-09-02 09:47
what should I do?

**Comment by ahmedbaghdadi1987** [comment] 2019-09-02 09:47
@tagliala  what should I do?

**Comment by tagliala** [comment] 2019-09-02 11:37
@ahmedbaghdadi1987 please add a 👍 reaction to #5103

![image](https://user-images.githubusercontent.com/556268/64112071-9c1d7a00-cd86-11e9-9ec2-9a4c43b2575c.png)

(click on 👍 )

If you need more information on how requests work, please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs)
