### ISSUE TITLE
Icon Request: fa-greek

### ISSUE THREAD

**Issue by imeidopf** [FortAwesome/Font-Awesome#8847] opened 2016-03-28 20:57 UTC
I'm developing an statistics app for a course of mine in university. I'd like to see the greek alphabet come to font-awesome so I can use the symbols/letters in my apps and for when I reference different statistics symbols.

**Comment by tagliala** [comment] 2016-03-28 22:34
you can use that via the standard unicode points

```css
.fa-alpha:before {
  content: 'α';
}
```

Duplicate of #2828, closing here

**Closed by tagliala** 2016-03-28 22:34 UTC
