### ISSUE TITLE
Diaspora

### ISSUE THREAD

**Issue by braegel** [FortAwesome/Font-Awesome#8932] opened 2016-04-09 17:27 UTC
It would be great to have a square icon for the Diaspora P2P Social network.

**Comment by tagliala** [comment] 2016-04-09 18:38
Duplicate of #414 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-09 18:38 UTC
