### ISSUE TITLE
Icon Request: fa-google-play

### ISSUE THREAD

**Issue by dbbwebdev** [FortAwesome/Font-Awesome#10986] opened 2017-04-24 20:49 UTC
Need a Google Play icon (right-pointing triangle) for a podcast list for our website.  Thank you!

**Comment by tagliala** [comment] 2017-04-24 21:30
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2272 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-24 21:30 UTC
