### ISSUE TITLE
Icon request: fa-playstation (and other consoles)

### ISSUE THREAD

**Issue by Pierrounator** [FortAwesome/Font-Awesome#9656] opened 2016-07-27 14:30 UTC
fa-playstation
http://www.logosurfer.com/sites/default/files/PlayStation_logo.svg_.png

fa-xbox
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Xbox_Logo.svg/2000px-Xbox_Logo.svg.png

fa-wiiu
http://gameswallpaperhd.com/wp-content/uploads/2013/12/wii-u-logo-pngwii-u-launch-successful-but-hindered-by-console-breakdowns-and-bsv6r47i.png

fa-gamecube
http://cf.juggle-images.com/matte/white/280x280/gamecube-logo-primary.jpg

**Comment by tagliala** [comment] 2016-07-27 14:56
Duplicate of #1006 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-27 14:56 UTC
