### ISSUE TITLE
animating icons fa-pulse incorrectly defined / missing fa-star-christmas

### ISSUE THREAD

**Issue by ollyradford** [FortAwesome/Font-Awesome#14694] opened 2019-02-27 17:00 UTC
The class fa-pulse appears to incorrectly defined to use fa-spin keyframes:

.fa-pulse {
    animation: fa-spin 1s infinite steps(8);
}

furthermore, there does not appear to be a fa-pulse set of keyframes...

We are using 5.7.2 from the CDN: https://pro.fontawesome.com/releases/v5.7.2/css/regular.css

THere is also an issue on https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons where the christmas star is not rendered, despite appearing the code example and markup

**Comment by tagliala** [comment] 2019-02-27 17:20
Hi!

Thanks for being part of the Font Awesome Community.

> furthermore, there does not appear to be a fa-pulse set of keyframes...

The pulse animation is working as intended 😅 

This is the designed use case: https://jsfiddle.net/tagliala/z12wdapb/36/

You are not the only one expecting a heartbeat-like pulse #14630 

If you need that animation, feel free to implement it by using custom css

Ref: https://jsfiddle.net/tagliala/z12wdapb/24/

> THere is also an issue on https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons where the christmas star is not rendered, despite appearing the code example and markup

Yes, that page is using a pro icon but the free set is loaded 🤔 

Let's assign @talbs

**Comment by ollyradford** [comment] 2019-02-27 17:28
Thanks for the pointer - I can see the difference now!

**Comment by tagliala** [comment] 2019-02-27 17:32
You're welcome. Reopening here because there is an issue in the docs

**Comment by ollyradford** [comment] 2019-02-27 17:34
sorry for closing, I clicked the wrong button!

**Comment by talbs** [comment] 2019-03-06 17:54
Hi, all.

Thanks for the good feedback about the pulse animation and its name. Since it was added in Font Awesome 4, the term pulse has come to be used for a particular type of animation (mostly dealing with opacity or slightly scaling things up). I'll bring this feedback to the team for future animations included with Font Awesome thoughts. If you have other icon animations you'd like to have right out of the box, feel free to share those too.

In the meantime, that missing icon in our [Animating Icons](https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons) docs should be fixed. Thanks for letting us know about that one. 😄

**Closed** 2019-03-06 17:55 UTC
Labels: bug, doc, in progress
