### ISSUE TITLE
Icon Request: mail-new

### ISSUE THREAD

**Issue by drumichael611** [FortAwesome/Font-Awesome#8416] opened 2016-01-25 21:45 UTC
I would LOVE to see an icon to compliment the email-related options to indicate a "new message".

Thanks so much for consideration!

**Comment by tagliala** [comment] 2016-01-26 09:09
mail read could be a duplicate of #897 

Could you please post an example of new email?

**Comment by drumichael611** [comment] 2016-01-26 13:33
I apologize, mail read is a duplicate of #897 

New mail would be an envelope with something like a star at the top right or top left corner like this: http://www.softicons.com/system-icons/oxygen-icons-by-oxygen/actions-mail-mark-unread-new-icon

**Comment by aethior** [comment] 2022-04-15 04:29
Hi @drumichael611,

Something like [**fa-envelope-dot**](https://fontawesome.com/icons/envelope-dot) icon?

Regards.

cc/ @tagliala

**Comment by sensibleworld** [comment] 2022-09-15 12:33
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!

**Closed by sensibleworld** 2022-09-15 12:33 UTC
Labels: waiting for feedback
