### ISSUE TITLE
Icon request: icon-infinity

### ISSUE THREAD

**Issue by DieterGrunewald** [FortAwesome/Font-Awesome#9894] opened 2016-09-09 13:31 UTC
Please create an infinity icon.

![infinity](https://cloud.githubusercontent.com/assets/22099649/18388561/6b58609e-76a2-11e6-82ee-81cf34abb63f.jpg)

**Comment by tagliala** [comment] 2016-09-10 15:24
Duplicate of #1647 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-10 15:24 UTC
