### ISSUE TITLE
Icon Request: icon-kitchen bell

### ISSUE THREAD

**Issue by Emanuele86** [FortAwesome/Font-Awesome#12039] opened 2018-01-04 16:37 UTC
![img_2434](https://user-images.githubusercontent.com/35109793/34573874-ec4c658e-f175-11e7-80af-23984b2cc88d.PNG)

**Comment by tagliala** [comment] 2018-01-04 17:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3919, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-04 17:37 UTC
