### ISSUE TITLE
Icon request: cloud-slash

### ISSUE THREAD

**Issue by martinweck** [FortAwesome/Font-Awesome#16944] opened 2020-07-22 11:40 UTC
**What can it be used for?**
If you write a chat software, where the chat functionality can be switched on/off, it is good to have a switched off version of the cloud icon.

**Example image**
`<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path d="M272,64a144,144,0,0,1,133.4,89.6A80,80,0,0,1,527.1,257.2a96,96,0,0,1,72,135.16l25.79,20a128.07,128.07,0,0,0-53.2-173.6A112.06,112.06,0,0,0,464,96a110.78,110.78,0,0,0-48,10.8A176,176,0,0,0,173.86,61.93l26.92,20.91A143.19,143.19,0,0,1,272,64Z"/><path d="M144,448a112,112,0,0,1-15-223,137.31,137.31,0,0,1-1-17,144.31,144.31,0,0,1,1.34-19.62l-28.35-22A176,176,0,0,0,96.2,200.2,144,144,0,0,0,144,480H504.63l-41.18-32Z"/><path d="M436.3,368.07l169,133.1a8,8,0,0,0,11.2-1.2l10-12.5a8.19,8.19,0,0,0,.35-9.7L152.61,104.36l-16.2-12.7L32.91,10.16a8,8,0,0,0-11.2,1.2l-10,12.5a8,8,0,0,0-.36,9.59L427.2,360.87Z"/></svg>`

**Comment by tagliala** [comment] 2020-07-22 14:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12554, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-07-22 14:53 UTC
