### ISSUE TITLE
Multi-word Font Family Names; font-family missing quotation marks (single or double)

### ISSUE THREAD

**Issue by Remzi1993** [FortAwesome/Font-Awesome#13231] opened 2018-05-29 12:33 UTC
Font Awesome's family name has spaces and therefore sometimes it's not loaded correctly. If i'm correct a font family who has multiple words, separated by spaces needs quotation marks (single or double)

See: https://css-tricks.com/almanac/properties/f/font-family/

### Describe the problem
Sometimes Font Awesome is not loaded.
 
### What did you expect?
font-family didn't work as expected.

### What version and implementation are you using?
Font Awesome v5.0.13 Free and implemented using your Free CDN, see: <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

Version: v5.0.13
Browser and version: Latest stable Firefox 60.0.1 and Chrome 66
- [ x ] Web Fonts with CSS

### Reproducible test case
Every website we have developed, see example website: https://isolatiedeskundige.nl

### Bug report checklist
- [ x ] I have filled out as much of the above information as I can
- [ x ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

EDIT:
It's about this: 

.fa, .far, .fas {
	font-family: Font Awesome 5 Free;
}

Should be this:

.fa, .far, .fas {
	font-family: 'Font Awesome 5 Free';
}

**Comment by tagliala** [comment] 2018-05-29 13:10
Hi!

Thanks for being part of the Font Awesome Community and for reporting this issue.

I don't know why the minimizer is stripping quotes.

Anyway, I've just found out that this request is a duplicate of #13050, let's use the other thread

**Closed by tagliala** 2018-05-29 13:10 UTC
