### ISSUE TITLE
Icon Request : icon-academiaedu

### ISSUE THREAD

**Issue by pmesperanca** [FortAwesome/Font-Awesome#9954] opened 2016-09-23 09:06 UTC
Hello all,

Would anyone be willing to create an icon for the academia.edu network? https://www.academia.edu (logo below)
I realise it is remarkably similar to the "A" in fa-font, but it would be nice to have the exact logo.

![apple-touch-icon-144x144](https://cloud.githubusercontent.com/assets/12113751/18780575/21316ef0-8176-11e6-9145-8d8f4f424204.png)

Thank you very much!

**Comment by tagliala** [comment] 2016-09-23 10:37
Duplicate of #2751, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-23 10:37 UTC
