### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by Co1002** [FortAwesome/Font-Awesome#18447] opened 2021-11-15 14:35 UTC
**What can it be used for?**
The "Origin" Brand-Icon for gaming-websites or all at this theme

**Example image (optional)**
![image](https://user-images.githubusercontent.com/73126555/141799241-99fc7f34-8c78-47d1-ae71-efa09b4aada1.png)

**Comment by tagliala** [comment] 2021-11-15 14:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1290, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-11-15 14:53 UTC
