### ISSUE TITLE
Icon Request: icon-vertical-line

### ISSUE THREAD

**Issue by fekoh** [FortAwesome/Font-Awesome#10812] opened 2017-03-20 11:27 UTC
To show the the amount of a product in an online shop it would be useful to have multiple icons that represent the stock.

Like:
|
|||||
|||||||||

Maybe it would be even enough to have one vertical line icon and repeat that icon as needed.

Regards
Felix

**Comment by ryankane** [comment] 2017-03-22 16:29
Couldn't you just stick to Unicode vertical lines/bars?

|Character|Name|Value|
|-|-|-|
|\||[VERTICAL LINE](http://www.fileformat.info/info/unicode/char/7c/index.htm)|U+007C|
|❘|[LIGHT VERTICAL BAR](http://www.fileformat.info/info/unicode/char/2758/index.htm)|U+2758|
|❙|[MEDIUM VERTICAL BAR](http://www.fileformat.info/info/unicode/char/2759/index.htm)|U+2759|
|❚|[HEAVY VERTICAL BAR](http://www.fileformat.info/info/unicode/char/275a/index.htm)|U+275A|

# CSS

```css
.fa-vertical-line:after       { content: "\007C" };
.fa-vertical-bar-light:after  { content: "\2758" };
.fa-vertical-bar-medium:after { content: "\2759" };
.fa-vertical-bar-heavy:after  { content: "\275A" };
```

**Comment by Soaku** [comment] 2017-10-03 14:52
Would also love to see a horizontal line too.

**Comment by djechelon** [comment] 2018-08-22 14:50
@Soaku once you have a vertical line, it's kids' play to fa-rotate it

**Comment by tagliala** [comment] 2018-08-22 14:59
🤦‍♂️ 

I didn't notice that this is a duplicate of #1072, please +1 that request

Closing here

**Closed by tagliala** 2018-08-22 14:59 UTC
Labels: new icon, web application icons
