### ISSUE TITLE
Icon request: fa-text

### ISSUE THREAD

**Issue by PennyFace** [FortAwesome/Font-Awesome#8349] opened 2016-01-15 12:54 UTC
Hi,
There are two icons text (text height and text width), but not just text. It's the same T as text height and text width but without an arrow

We want to use this in our application to specify a data type: text.

Greetings,

**Comment by marathia** [comment] 2016-01-20 11:28
+1

**Comment by dotnetchris** [comment] 2016-01-22 19:28
:+1:

**Comment by dnavarrojr** [comment] 2016-02-03 18:10
+1

**Comment by MightyFo0l** [comment] 2016-02-12 15:24
+1

**Comment by hpvd** [comment] 2016-03-23 15:37
+1

**Comment by fschaeffer** [comment] 2016-06-10 07:03
+1

**Comment by aethior** [comment] 2016-07-08 20:15
Duplicate of #8839?

cc @tagliala

**Comment by aethior** [comment] 2022-03-23 11:54
Hi @PennyFace,

This icon was added in v5.9.0.
Check https://fontawesome.com/icons/text

Regards.

cc/ @tagliala

**Closed** 2022-03-23 15:24 UTC
Labels: new icon, Available in FA Pro, text-formatting (category)
