### ISSUE TITLE
Icon Request: fa-no-location

### ISSUE THREAD

**Issue by schub** [FortAwesome/Font-Awesome#8811] opened 2016-03-23 15:35 UTC
It would be nice to have an icon indicating there is no (gps-) location available. Maybe something like a marker symbol which is crossed out.

![no-location](https://cloud.githubusercontent.com/assets/308471/13990609/46ca9f2a-f115-11e5-98ef-3f75c1e544cd.png)

**Comment by DaAwesomeP** [comment] 2016-03-28 00:38
You can stack a [ban symbol](http://fontawesome.io/icon/ban/) over a [map marker](http://fontawesome.io/icon/map-marker/) as shown how [here](http://fontawesome.io/examples/#stacked).

**Comment by tagliala** [comment] 2016-03-28 10:46
Duplicate of #6931, please +1 that request

closing here

**Closed by tagliala** 2016-03-28 10:46 UTC
