### ISSUE TITLE
Icon Request: fa-filter-cross

### ISSUE THREAD

**Issue by Hessar** [FortAwesome/Font-Awesome#8172] opened 2015-12-18 12:55 UTC
for fa-filter  new icon as unfilter icon
<i class="fa fa-filter"></i>
<i class="fa fa-unfilter"></i>

thnaks

**Comment by tagliala** [comment] 2015-12-18 13:13
duplicate of #650, please +1 that request

refers to #1181

**Closed by tagliala** 2015-12-18 13:13 UTC
