### ISSUE TITLE
Icon Request: fa-discord

### ISSUE THREAD

**Issue by Eyeic** [FortAwesome/Font-Awesome#9241] opened 2016-05-19 10:58 UTC
Would like to see a discord icon, becoming popular

**Comment by tagliala** [comment] 2016-05-19 11:02
Duplicate of #7574 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-19 11:02 UTC
