### ISSUE TITLE
Icon request: icon-customercare

### ISSUE THREAD

**Issue by Rabia-Ahmed92** [FortAwesome/Font-Awesome#10380] opened 2016-12-16 06:03 UTC

**Comment by Rabia-Ahmed92** [comment] 2016-12-16 06:12
i want this icon for my video based application
https://thenounproject.com/term/customer-service/6704/

**Comment by tagliala** [comment] 2016-12-16 10:16
Duplicate of #5586, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-16 10:16 UTC
