### ISSUE TITLE
Icon request: fa-rotation-icon

### ISSUE THREAD

**Issue by martypowell** [FortAwesome/Font-Awesome#10095] opened 2016-10-20 17:47 UTC
Would be nice to have this icon, wasn't sure what the intended class name would be though.

![rotate](https://cloud.githubusercontent.com/assets/1933400/19571270/7de044fe-96cb-11e6-9d0a-52aca1ef990d.png)

**Comment by tagliala** [comment] 2016-10-21 09:49
Do
* http://fontawesome.io/icon/repeat/
* http://fontawesome.io/icon/undo/
* http://fontawesome.io/icon/refresh/

do the job?

Or maybe a duplicate of #772

**Comment by martypowell** [comment] 2016-10-24 16:53
@tagliala definitely a duplicate of #7729

**Comment by tagliala** [comment] 2016-10-24 21:51
@martypowell please +1 #772, thanks

**Closed by tagliala** 2016-10-24 21:51 UTC
Labels: waiting for feedback
