### ISSUE TITLE
Icon request: sushi-icon

### ISSUE THREAD

**Issue by BlackOnyxs** [FortAwesome/Font-Awesome#16608] opened 2020-05-10 03:59 UTC
**What can it be used for?**
For Bottom Navigation View Android and Drawer on Web Page. The background colors are white and black.

**Example image (optional)**
[https://icons8.com/icon/97702/sushi](url)

**Icon request checklist**
- [ ] Only as the image
- [ ] sushi-icon

**Comment by tagliala** [comment] 2020-05-10 08:49
Hi!

Thanks for being part of the Font Awesome Community.

The description (sushi as navigation menu icon) do not match the actual icon (sushi as sashimi food)

Maybe this is a duplicate of:
- #4985 (sushi roll)
- #15452 (bento menu)

Could you please clarify?

**Comment by BlackOnyxs** [comment] 2020-05-24 03:07
Thanks for your anwser. 
Yes, my request is duplicated with #4985, sorry. That icon is on fontawesome website?

**Comment by tagliala** [comment] 2020-05-24 08:12
Hi, thanks for the clarification

No, it doesn't, it exists as a request

Please add a 👍 reaction to #4985, that is the best we can do.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-24 08:12 UTC
Labels: waiting for feedback
