### ISSUE TITLE
Icon request: icon-cross

### ISSUE THREAD

**Issue by techelpmike** [FortAwesome/Font-Awesome#10624] opened 2017-02-06 15:25 UTC
I have submitted this before and you referred me to a previous request that is two years old.  But the icon still does not exist.  This is a very universal icon of a Christian cross.  I will be using it on a website for a Christian preschool in a section that describes the chapel activities.  An alternative would be a church icon.
![cross-64](https://cloud.githubusercontent.com/assets/12036439/22653035/9d83f34e-ec45-11e6-8128-3c3ac971db35.png)
![church_icon](https://cloud.githubusercontent.com/assets/12036439/22653084/b60860e4-ec45-11e6-9d70-5f17c2ce1371.png)

**Comment by tagliala** [comment] 2017-02-06 17:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1611 #2088 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-06 17:55 UTC
