### ISSUE TITLE
Icon request: push-pin

### ISSUE THREAD

**Issue by wisercoder** [FortAwesome/Font-Awesome#13496] opened 2018-07-07 19:08 UTC
### What can it be used for?

A push-pin is used in user interfaces to indicate that a collapsible panel should stay open. The existing thumbtack icon does not meet the requirements because we need a pair, one icon to depict the unpushed state and another to depict the pushed-in state.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-07 19:29
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #10749?

**Comment by wisercoder** [comment] 2018-07-08 14:40
Yes it is a duplicate

**Comment by tagliala** [comment] 2018-07-08 14:47
@wisercoder thanks

please add a +1 reaction to that request

Closing here

**Closed by tagliala** 2018-07-08 14:47 UTC
Labels: waiting for feedback
