### ISSUE TITLE
icon request - PHP logo

### ISSUE THREAD

**Issue by freedmandil** [FortAwesome/Font-Awesome#11678] opened 2017-10-28 19:16 UTC
php icon and php elephant
https://www.google.co.il/search?q=php+elephant+logo&newwindow=1&safe=strict&client=safari&rls=en&dcr=0&tbm=isch&source=iu&pf=m&ictx=1&fir=haNEJHYImpEsHM%253A%252CdOxYCazQcmfzUM%252C_&usg=__RwrlQuFljgSSCh8cIr7xxczSFBk%3D&sa=X&ved=0ahUKEwjg7YbGgJTXAhWBTBoKHeoMAREQ9QEINzAD#imgrc=haNEJHYImpEsHM:

**Comment by tagliala** [comment] 2017-10-28 20:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1420, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-28 20:17 UTC
