### ISSUE TITLE
Icon request: icon-forklift

### ISSUE THREAD

**Issue by NicoleneL** [FortAwesome/Font-Awesome#11328] opened 2017-07-27 11:59 UTC
Hi, is there a chance we can get a forklift icon please. Thank you.

**Comment by tagliala** [comment] 2017-07-27 19:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #692 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-27 19:00 UTC
