### ISSUE TITLE
Icon Request: icon-grape

### ISSUE THREAD

**Issue by ariannaoddo** [FortAwesome/Font-Awesome#9192] opened 2016-05-12 16:07 UTC
I need to a "grape" for my website about wine.

I'm attaching an example of grape (right side of the page). 
![example of icon](https://cloud.githubusercontent.com/assets/19264212/15221014/f30da734-1869-11e6-8b3c-1e866350414d.png)

I'd like to have the same colour of the icon in this attachment 
![example of colour](https://cloud.githubusercontent.com/assets/19264212/15221581/50cd0746-186c-11e6-9125-f672f6ed3df1.png)

Thanks

**Comment by tagliala** [comment] 2016-05-14 10:14
Duplicate of #5691, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-14 10:14 UTC

**Comment by ariannaoddo** [comment] 2016-05-18 07:25
thanks!how can i insert that icon in my work? what is the the code or the words that have i'm writing to watching it?

**Comment by tagliala** [comment] 2016-05-18 08:33
Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by mariealix** [comment] 2016-11-24 16:02
+1
