### ISSUE TITLE
Icon Request: fa-diamonds, fa-spades, fa-clubs, fa-hearts (game card symbols)

### ISSUE THREAD

**Issue by htbasaran** [FortAwesome/Font-Awesome#10204] opened 2016-11-11 22:42 UTC
I need these symbols for my next project, thanks.

Also, having fa-card-game will be fantastic.
http://icons.iconarchive.com/icons/icons8/ios7/256/Gaming-Cards-icon.png
![http://icons.iconarchive.com/icons/icons8/ios7/256/Gaming-Cards-icon.png](http://icons.iconarchive.com/icons/icons8/ios7/256/Gaming-Cards-icon.png)

**Comment by tagliala** [comment] 2016-11-12 11:04
Duplicate of #606, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-12 11:04 UTC
