### ISSUE TITLE
Icon request: Tor Browser Onion Icon

### ISSUE THREAD

**Issue by TrackRunny** [FortAwesome/Font-Awesome#16715] opened 2020-05-25 19:05 UTC
**What can it be used for?**
This can be used to represent the tor project for those people who like using it and who like using the logo. This browser is very popular in its own different way and I believe people would like using this icon. 

**Example image (optional)**
![image](https://user-images.githubusercontent.com/45835198/82837833-219a0a80-9e7f-11ea-9464-f8e341330b98.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
-  [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-25 19:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5101, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-25 19:45 UTC
