### ISSUE TITLE
Icon Request: icon-shopping-bag

### ISSUE THREAD

**Issue by bogowicz** [FortAwesome/Font-Awesome#6668] opened 2015-06-05 09:50 UTC
Dear Font Awesome Team,

If there is such a possibility 
I really need a shopping bag icon, 
for boutique-type eshop site.

Smaller companies need suitable, 
seemly cart icon than the metal basket 
which is associated with a larger malls.

All the Best 
Pawel

![sb](https://cloud.githubusercontent.com/assets/3184941/8003293/7ee5da1c-0b76-11e5-88b4-2ddcf6a38f32.jpg)

**Comment by tagliala** [comment] 2015-06-07 09:33
duplicate of #829 , please +1 that request

closing here

**Closed by tagliala** 2015-06-07 09:33 UTC
