### ISSUE TITLE
Icon Request: fa-Icon Water tap 

### ISSUE THREAD

**Issue by saleometer** [FortAwesome/Font-Awesome#10667] opened 2017-02-15 12:10 UTC
Hi - would request for a tap icon similar to this one https://thenounproject.com/term/drinking-water/732154/ . We are using it for our event listing where we want to show different facilities available for the event like parking , accessibility etc we found everything except for water / tap kind of icon to indicate water is available. Please add the same. Thanks

**Comment by caduvieira** [comment] 2017-02-21 10:51
related #10092

**Comment by tagliala** [comment] 2017-02-21 11:50
@caduvieira thanks

I will consider this a duplicate of #10092 and I will edit the title to include water tap

**Closed by tagliala** 2017-02-21 11:50 UTC
Labels: new icon, web application icons

**Comment by fenderrex** [comment] 2018-11-10 13:16
screen tap not a thing yet? but we do need water.... much love to the project!
~passaveagressaveprogramer
