### ISSUE TITLE
Icon Request: fa-sports

### ISSUE THREAD

**Issue by tommyangelov** [FortAwesome/Font-Awesome#7048] opened 2015-07-26 22:14 UTC
Hi, I have a request about new icons about sports. For example about tennis might add a tennis racquet or soccer ball about soccer, basketball, hockey, golf.

Thank you.

**Comment by TheChen5** [comment] 2015-07-27 16:19
Dupe of issues #767 , #714 , #325 .
+1 those.

**Comment by tagliala** [comment] 2015-07-27 16:41
@TheChen5 thanks

also, all those requests don't meet our contributing guidelines anymore

**Closed by tagliala** 2015-07-27 16:41 UTC
