### ISSUE TITLE
Icon Request: fa-parking

### ISSUE THREAD

**Issue by nicho90** [FortAwesome/Font-Awesome#6739] opened 2015-06-12 12:01 UTC
Hey it would be awesome if you could provide a parking-icon for cars, e.g. a simple "P". 
And for a parking garage a simple "P" with the shape of a roof, maybe as a new name "fa-parking-g"
Best, Nicho

**Comment by tagliala** [comment] 2015-07-05 12:45
duplicate of #1559 , please +1 that request

closing here

**Closed by tagliala** 2015-07-05 12:45 UTC
