### ISSUE TITLE
扫描

### ISSUE THREAD

**Issue by 15085799565** [FortAwesome/Font-Awesome#15253] opened 2019-07-11 02:46 UTC

**Comment by tagliala** [comment] 2019-07-11 07:36
Hi!

Thanks for being part of the Font Awesome Community.

As per Google Translate, 扫描 means "scanning"

If that is correct, this request is a duplicate of #5985, please add a 👍 reaction to that request.

Otherwise, feel free to open a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Closing here

**Closed by tagliala** 2019-07-11 07:36 UTC
