### ISSUE TITLE
Can we get a Houzz logo icon please, I have this in eps, AI, JPG and png

### ISSUE THREAD

**Issue by markjdesign** [FortAwesome/Font-Awesome#6654] opened 2015-06-03 22:25 UTC
![houzz_logo](https://cloud.githubusercontent.com/assets/12738396/7972866/c1080ea6-0a04-11e5-9bbf-66bf69489c7b.jpg)

**Comment by tagliala** [comment] 2015-06-04 11:52
as you know this is a duplicate of #2039 . sorry but I have to close this one.

Please take a look here: https://github.com/brandoncordell/houzz-icon-font

**Closed by tagliala** 2015-06-04 11:52 UTC

**Comment by markjdesign** [comment] 2015-07-02 21:31
Right, so why is it so difficult to get this added to font awesome if you have people like myself begging and handing over the files needed for it to get done? if FA needs some help I will gladly create icons for them in my spare time, it takes literally no time.

**Comment by tagliala** [comment] 2015-07-03 08:08
@markjdesign please consider the above fork or a custom build

**Comment by markjdesign** [comment] 2015-07-14 15:03
I am not sure how to get this font available to me even after reading the post. Is there a walk though step by step copy n past here type of instructional? I get file paths, and extensions and css editor, I am just not clear where to place it and what to place.
Thanks MJ

**Comment by tagliala** [comment] 2015-07-14 15:49
@markjdesign here it is: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
