### ISSUE TITLE
Provide JSON of all icon class names.

### ISSUE THREAD

**Issue by tempusrname** [FortAwesome/Font-Awesome#10682] opened 2017-02-17 19:20 UTC

**Comment by tagliala** [comment] 2017-02-18 10:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3366, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-18 10:55 UTC

**Comment by tempusrname** [comment] 2017-02-20 06:08
Any news on this considering it was requested in 2014?
