### ISSUE TITLE
Icon Request: fa-ios

### ISSUE THREAD

**Issue by hstanleycrow** [FortAwesome/Font-Awesome#8104] opened 2015-12-07 17:20 UTC
the icon for operating system from Apple. It can be used on the tech blogs, pages, stores, etc that needs to show the icon with android, windows, etc
Keep in mind, iOS icon is different as Apple logo.

**Comment by webmaster128** [comment] 2015-12-07 19:06
Duplicate of https://github.com/FortAwesome/Font-Awesome/issues/4935. See also https://github.com/FortAwesome/Font-Awesome/issues/4936

**Comment by hstanleycrow** [comment] 2015-12-08 00:44
it is not the same, #4936 is OSX and i am requesting iOS, they are different

**Comment by TheChen5** [comment] 2015-12-08 01:40
Dupe #4935 (as @webmaster128 said)
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-12-08 10:18
closing here

**Closed by tagliala** 2015-12-08 10:18 UTC
