### ISSUE TITLE
Icon request: substack-logo

### ISSUE THREAD

**Issue by blpdelivery** [FortAwesome/Font-Awesome#20192] opened 2024-04-12 07:12 UTC
Substack is a social media platform.

Home page: [https://substack.com]
About page: [https://substack.com/about]
Brand centre: [https://substack.com/brand]

![substack](https://github.com/FortAwesome/Font-Awesome/assets/166796077/727aae0b-b7cc-4397-9b8a-52ded13eeb1d)
![substack_wordmark](https://github.com/FortAwesome/Font-Awesome/assets/166796077/dc3b5da5-4ce8-44b2-be96-110e439fa886)

**Comment by tagliala** [comment] 2024-04-12 07:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16586, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-04-12 07:15 UTC
