### ISSUE TITLE
Icon request: icon-unity

### ISSUE THREAD

**Issue by Ogx8** [FortAwesome/Font-Awesome#12077] opened 2018-01-11 12:46 UTC
[https://seeklogo.com/images/U/unity-logo-988A22E703-seeklogo.com.png](url)

**Comment by tagliala** [comment] 2018-01-11 12:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2888, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-11 12:48 UTC
