### ISSUE TITLE
3D PRINTERS REQUEST

### ISSUE THREAD

**Issue by ArnyminerZ** [FortAwesome/Font-Awesome#10426] opened 2016-12-24 13:42 UTC
Please, it would be fantastic if you could add 3D printing icons, like extruder, printer, plastic...

**Comment by tagliala** [comment] 2016-12-24 13:57
Duplicate of #7625, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-24 13:57 UTC
