### ISSUE TITLE
Icon Request: fa-balloon

### ISSUE THREAD

**Issue by MetteKathrine** [FortAwesome/Font-Awesome#11698] opened 2017-11-01 13:59 UTC
Hi GitHub,
If it's possible, we would really like a balloon icon. We are a webshop, and sell a lot of balloons in foil and latex and Helium. I would like to use the balloon icon to our new frontpage, to give the customers more information about balloons and the products they are buying from us.
I search after it on your site, and something simular, but I had no luck to find it.

I hope you are able to help us :-)

Kind regards

Mette Christensen

**Comment by tagliala** [comment] 2017-11-01 15:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3398 or #10494, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-01 15:59 UTC
