### ISSUE TITLE
Icon request: icon-grap

### ISSUE THREAD

**Issue by ewannin** [FortAwesome/Font-Awesome#17359] opened 2020-11-03 09:18 UTC
This is a single icon to be used in grap and wine production infographics (production, map).
![grap](https://user-images.githubusercontent.com/31482956/97967690-de44b000-1dbd-11eb-8c45-f23846f1e1cb.png)

**Comment by aethior** [comment] 2022-03-08 03:30
Hi @ewannin,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/grapes

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-08 11:57
duplicate of #5691

**Closed by tagliala** 2022-03-08 11:57 UTC
