### ISSUE TITLE
Icon Request: fa-ham-radio

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7935] opened 2015-11-20 06:23 UTC
Request for fa-ham-radio (or with alias to "Amateur Radio")

![fa-ham-radio](http://i.imgur.com/SaxBLLz.png)

**Comment by caduvieira** [comment] 2015-11-20 13:00
dupe of #6161
please +1 that one
please also put your example there

**Closed** 2015-11-20 14:57 UTC
