### ISSUE TITLE
Icon Request: icon-caravan

### ISSUE THREAD

**Issue by smithandre** [FortAwesome/Font-Awesome#7984] opened 2015-11-25 20:54 UTC
Need trailer, to represent just that. A trailer or caravan, as a product on a web app I helping to build. 
Going for something like this:
http://www.iconsplace.com/icons/preview/black/trailer-256.png

**Comment by tagliala** [comment] 2015-11-25 22:21
duplicate of #5429, please +1 that request

closing here

**Closed by tagliala** 2015-11-25 22:21 UTC

**Comment by smithandre** [comment] 2015-11-26 11:20
Hmm.. ok. 
I need a trailer one as well, but can't really find one suitable yet. Will create one and submit a new request for it.

**Comment by tagliala** [comment] 2015-11-26 12:24
Trailer: #7369
