### ISSUE TITLE
Icon request: water-slide

### ISSUE THREAD

**Issue by kenn213** [FortAwesome/Font-Awesome#14759] opened 2019-03-15 18:02 UTC
This can be used for a water slide at an amusement park, swimming pool, etc...

Something like the left or right half of this image could work well.
![Image of Water Slide](https://cdn2.iconfinder.com/data/icons/buildings-places-2/48/v-36-512.png)

Also something like this could work. 
![Image of Water Slide](https://cdn3.iconfinder.com/data/icons/yachting-2/640/Yacht_Slide-512.png)

**Comment by sensibleworld** [comment] 2024-07-11 19:07
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/19993)

**Closed by sensibleworld** 2024-07-11 19:07 UTC
Labels: new icon, web application icons (legacy category), Duplicate
