### ISSUE TITLE
Icon Request: directory tree hierarchy

### ISSUE THREAD

**Issue by sirbris** [FortAwesome/Font-Awesome#13107] opened 2018-05-11 08:50 UTC
An icon for a direcotry hierarchy structure would be really helpful. Not only to indicate a directory tree but also for a view type which is hierarchical (view types lik list or tiles already exist).

![folder_tree](https://user-images.githubusercontent.com/664179/39915797-245107d6-5509-11e8-82e4-6421456bf7eb.png)

**Comment by tagliala** [comment] 2018-05-11 10:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2752, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-11 10:33 UTC
