### ISSUE TITLE
Icon request: webhooks-icon

### ISSUE THREAD

**Issue by johnmorais** [FortAwesome/Font-Awesome#15236] opened 2019-07-04 01:41 UTC
**What can it be used for?**
I need an icon to represent Webhooks. This is critical for platforms that work with APIs.

**Example image (optional)**

![fb692b129e](https://user-images.githubusercontent.com/31970229/60633980-1ce9e500-9ddb-11e9-888e-80e47952b832.png)

**Comment by jarrodbell** [comment] 2019-07-04 05:25
#5139

**Comment by tagliala** [comment] 2019-07-04 07:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5139, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-07-04 07:41 UTC
