### ISSUE TITLE
deezer icon

### ISSUE THREAD

**Issue by dsgolfside** [FortAwesome/Font-Awesome#16117] opened 2020-01-26 22:01 UTC
music sites need this standard practice now please

**Comment by tagliala** [comment] 2020-01-27 08:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2802 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-01-27 08:04 UTC
