### ISSUE TITLE
Icon Request: fa-weight-scale

### ISSUE THREAD

**Issue by RixBtrfly** [FortAwesome/Font-Awesome#11682] opened 2017-10-29 05:27 UTC
A weight scale. Great to indicate something related to dieting.
![scale](https://user-images.githubusercontent.com/32779287/32140928-86e60ad8-bc37-11e7-9be1-8b95b2ad4ddf.png)

**Comment by tagliala** [comment] 2017-10-29 09:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7797, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-29 09:48 UTC
