### ISSUE TITLE
Icon request: fa-parentheses/fa-brackets

### ISSUE THREAD

**Issue by shaedrich** [FortAwesome/Font-Awesome#11444] opened 2017-08-25 08:45 UTC
Hello Font-Awesome Team,
would be great if you could add an icon for parentheses. In my case I need to differentiate between "tags" and "script". But the icon can commonly be used to indicate a function or a dictionary (aka object, structure, etc.).
Thanks in advance!

**Comment by tagliala** [comment] 2017-08-25 08:46
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this request a duplicate of #1797, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-25 08:46 UTC

**Comment by shaedrich** [comment] 2017-08-25 08:47
Hi!

Oh, sorry! I only searched for parentheses and got no result. Silly me.
