### ISSUE TITLE
Icon Request: fa-sign-language

### ISSUE THREAD

**Issue by AndreLGava** [FortAwesome/Font-Awesome#8247] opened 2015-12-30 16:30 UTC
acessibility on the web is very important, so we need an icon like this
http://www.notisurdo.com.br/icones/logosinais.jpg

**Comment by tagliala** [comment] 2015-12-31 21:29
Duplicate of #2026, please +1 that request

closing here

**Closed by tagliala** 2015-12-31 21:29 UTC
