### ISSUE TITLE
Icon Request: fa-gadu-gadu

### ISSUE THREAD

**Issue by whiteblXK** [FortAwesome/Font-Awesome#16778] opened 2020-06-09 13:59 UTC
**What can it be used for?**
On website to open gg.pl app(just like teamspeak)
https://www.gg.pl/

**Example image (optional)**
![image](https://user-images.githubusercontent.com/6029889/84156717-260f1780-aa6a-11ea-9fb7-c73ec855a759.png)

**Comment by tagliala** [comment] 2020-06-09 14:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5270, please add a 👍 reaction to that request.

I've edited #5270 to include `gadu-gadu` in the search

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-06-09 14:27 UTC
