### ISSUE TITLE
Icon Request: fa-maid

### ISSUE THREAD

**Issue by 888Plugin8COM** [FortAwesome/Font-Awesome#9045] opened 2016-04-23 13:44 UTC
![1485756-0-maidicon](https://cloud.githubusercontent.com/assets/18630685/14761718/63134592-092f-11e6-969e-446be25f9253.png)

image for personal use at website at www.ecospiritcleaners.com

Thank you in advance

**Comment by tagliala** [comment] 2016-04-23 13:46
Duplicate of #8719, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-23 13:46 UTC

**Comment by 888Plugin8COM** [comment] 2016-04-23 13:49
im sorry and thank you sir

**Comment by tagliala** [comment] 2016-04-23 14:37
@888Plugin8COM don't worry 👍
