### ISSUE TITLE
Icon request: vessel

### ISSUE THREAD

**Issue by SasanMameghani** [FortAwesome/Font-Awesome#13930] opened 2018-09-11 09:04 UTC
### What can it be used for?

The icon is to be used to illustrate commercial ships/fleet in a shipping app. The current "ships" does not do the trick. Need commercial vessel. 

### Example image (optional)

![image](https://user-images.githubusercontent.com/23580721/45349584-f5a6fa80-b5b1-11e8-9900-bd1f325f6a41.png)
![image](https://user-images.githubusercontent.com/23580721/45349627-1a02d700-b5b2-11e8-9777-21cf2a19640c.png)
![image](https://user-images.githubusercontent.com/23580721/45349729-5f270900-b5b2-11e8-914a-27506d2076fd.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by mrtnin** [comment] 2018-10-05 09:52
+1

**Comment by ekaterina-nikonova** [comment] 2018-10-05 10:02
+1

**Comment by xmuskrat** [comment] 2019-04-25 18:20
+1

**Comment by xmuskrat** [comment] 2019-07-18 15:30
+1

**Comment by sensibleworld** [comment] 2024-07-11 19:11
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/18626)

**Closed by sensibleworld** 2024-07-11 19:11 UTC
Labels: new icon, transportation (category), Duplicate
