### ISSUE TITLE
Icon request: icon-bbb and icon-yelp

### ISSUE THREAD

**Issue by wulfgen** [FortAwesome/Font-Awesome#11565] opened 2017-09-28 00:42 UTC
I am requesting two additional icons for any company to use:

1): for the Better Business Bureau (BBB), this is a pretty large organization and the other:

2) for Yelp, this also is a social registrar that is pretty large and has a lot of coverage.

**Comment by tagliala** [comment] 2017-09-28 08:32
Hi!

Thanks for being part of the Font Awesome Community.

bbb is a duplicate of #5797 , please add a 👍  reaction to that request.

yelp is already here: http://fontawesome.io/icon/yelp/

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-28 08:32 UTC
