### ISSUE TITLE
Font awesome icons are not rendering while generating PDF using HTML content.

### ISSUE THREAD

**Issue by jazzbpn** [FortAwesome/Font-Awesome#16950] opened 2020-07-24 10:47 UTC
Here is the full question: [FontAwesome icons Not rendering in PDF](https://stackoverflow.com/questions/63071723/font-awesome-icons-are-not-rendering-when-trying-to-convert-html-to-pdf-in-flutt)

**Comment by tagliala** [comment] 2020-07-24 11:45
Duplicate of #16934 ?

**Closed by tagliala** 2020-07-24 11:45 UTC
