### ISSUE TITLE
Icon Request: fa-bag-of-shop

### ISSUE THREAD

**Issue by Arkadia977** [FortAwesome/Font-Awesome#7118] opened 2015-08-01 21:59 UTC
Hello, sorry I don't speak english very well but I would like a icone for mention a shop thanks to a bag of shop:
http://i.gyazo.com/71ce88e24684bd245911b5a89565260d.png
http://i.gyazo.com/c5fd213c1ea31de25e38579157df0809.png

Thanks a lot

**Comment by Nektro** [comment] 2015-08-02 07:18
You could take fa-shopping-cart (http://fortawesome.github.io/Font-Awesome/icon/shopping-cart/) and put it inside a div yourself in the mean time :)

Nektro

**Comment by tagliala** [comment] 2015-08-02 08:31
duplicate of #829 , please +1 that request

closing here

**Closed by tagliala** 2015-08-02 08:31 UTC
