### ISSUE TITLE
Flattr icon?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [FortAwesome/Font-Awesome#5556] opened 2015-02-02 01:16 UTC
Since Flattr is becoming a well known donation platform, we could really use a Flattr icon in a pack.

> With Flattr, supporting creators becomes a natural part of life. Paying for content does not only feel good, it makes the world a better place.

![logo](http://upload.wikimedia.org/wikipedia/commons/0/0d/Flattr.svg)

[Flattr website](https://flattr.com/)

**Comment by tagliala** [comment] 2015-02-02 15:59
duplicate of #371 , please +1 that request

closing here

**Closed by tagliala** 2015-02-02 15:59 UTC
