### ISSUE TITLE
Icon request: network quality

### ISSUE THREAD

**Issue by lwenkin** [FortAwesome/Font-Awesome#11944] opened 2017-12-15 10:42 UTC
Hello,

There is the Wifi icon that is available in the icon set, but it could be great to have the possibility to give the quality of the Wifi signal too, a little bit like it is done for the battery.

**Comment by tagliala** [comment] 2017-12-15 10:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7856 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-15 10:47 UTC
