### ISSUE TITLE
Icon Request: fa-pc

### ISSUE THREAD

**Issue by chizernn** [FortAwesome/Font-Awesome#9668] opened 2016-07-28 14:02 UTC
Personal computer. Example in the application
Thanks!
![stock-vector-pc-icon-one-of-set-web-icons-298276043](https://cloud.githubusercontent.com/assets/20704692/17215263/fa2b9618-54e4-11e6-8c8b-ad01de2bc661.jpg)

**Comment by tagliala** [comment] 2016-07-28 14:13
Duplicate of #5094, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-28 14:13 UTC
