### ISSUE TITLE
Icon request: icon-salesforce

### ISSUE THREAD

**Issue by ali-farag** [FortAwesome/Font-Awesome#12178] opened 2018-01-29 15:26 UTC
PLEASE & THANK YOU!

**Comment by tagliala** [comment] 2018-01-29 15:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1744, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-29 15:51 UTC
