### ISSUE TITLE
Icon request: icon-google-play

### ISSUE THREAD

**Issue by robmarston** [FortAwesome/Font-Awesome#6903] opened 2015-07-08 13:51 UTC
I'd like to request a Google Play icon. I would use the icon as a hyperlink to downloadable content at http://play.google.com. The icon would most likely be a flat, single-color vector representing the signature triangle/play symbol seen here:

![Image of Google Play logo](https://www.gstatic.com/android/market_images/web/play_logo_x2.png)

**Comment by tagliala** [comment] 2015-07-09 19:23
duplicate of #2272 , please +1 that request

closing here

**Closed by tagliala** 2015-07-09 19:23 UTC

**Comment by baixiongmao** [comment] 2019-05-28 13:57
nice +1
