### ISSUE TITLE
Icon request: fa-users-exchange (move between users / transfer)

### ISSUE THREAD

**Issue by HTMLGuyLLC** [FortAwesome/Font-Awesome#15030] opened 2019-05-14 23:07 UTC
### What can it be used for?

Moving items between users.

### Example image (optional)

![move-between-users](https://user-images.githubusercontent.com/2415447/57737962-8cfda980-767b-11e9-83a1-925fc01f591a.jpg)

**Comment by tagliala** [comment] 2019-05-15 08:31
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve a couple of icons that could fit your use case with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/63/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by HTMLGuyLLC** [comment] 2019-05-15 13:02
If I used the js version, correct? I don’t.

**Comment by sensibleworld** [comment] 2024-07-11 18:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7184)

**Closed by sensibleworld** 2024-07-11 18:37 UTC
Labels: new icon, web application icons (legacy category), Duplicate
