### ISSUE TITLE
Icon request: indeed-logo

### ISSUE THREAD

**Issue by jessicamcdougall** [FortAwesome/Font-Awesome#14859] opened 2019-04-05 02:03 UTC
### What can it be used for?
Social media icon for Indeed logo. 
Would be great to have both the cut-out version and the block version

### Example image (optional)

<img width="169" alt="Screenshot 2019-04-04 19 01 14" src="https://user-images.githubusercontent.com/49296385/55599327-09f84380-570c-11e9-8ca9-a745e495120c.png">
<img width="200" alt="Screenshot 2019-04-04 19 01 08" src="https://user-images.githubusercontent.com/49296385/55599328-09f84380-570c-11e9-971c-144fc7425639.png">
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-04-05 08:49
Hi!

Thanks for being part of the Font Awesome Community.

I think this is a duplicate of #7261, please add a 👍 reaction to that request.

Feel free to comment if I'm wrong

Closing here

**Closed by tagliala** 2019-04-05 08:49 UTC
