### ISSUE TITLE
Icon Request: fa-video-camera-slash

### ISSUE THREAD

**Issue by XAMelleOH** [FortAwesome/Font-Awesome#7567] opened 2015-09-29 10:22 UTC
The same as fa-microphone and fa-microphone-slash it'll be good to have fa-video-camera-slash. It can be used when developing RTC web applications for making online audio/video calls.

**Comment by caduvieira** [comment] 2015-09-29 13:26
dupe of #3765

**Closed** 2015-09-29 14:19 UTC

**Comment by kisai** [comment] 2015-12-04 08:29
#3765 is deleted or at least github returns 404 page. Or are you giving priority to #3691 ?

**Comment by tagliala** [comment] 2015-12-04 09:38
??? contacting github

**Comment by tagliala** [comment] 2015-12-04 11:32
page restored
