### ISSUE TITLE
Icon request: fa-stocktwits

### ISSUE THREAD

**Issue by jplucas14** [FortAwesome/Font-Awesome#14930] opened 2019-04-22 16:04 UTC
StockTwits is a popular social media site for stock market talk. This would be used just as a "Facebook" or "Twitter" icon might be used to "follow us on XXX". Let me know if you have any questions, site is StockTwits.com just looking to have the icon

![ST_64x64-62246776745ceab2f58407428bfde60ed878a2977fd49f4918b8fba32c9ef64b](https://user-images.githubusercontent.com/47125917/56510084-032c4780-64e6-11e9-9ccc-8acd8f1388c5.png)

![ST ICON](https://user-images.githubusercontent.com/47125917/56510231-65854800-64e6-11e9-96d5-ab696360bff1.png)

**Comment by tagliala** [comment] 2019-04-22 16:38
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3593, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-22 16:38 UTC
