### ISSUE TITLE
Icon request: icon-leetcode

### ISSUE THREAD

**Issue by IamRajMayank** [FortAwesome/Font-Awesome#17311] opened 2020-10-24 18:11 UTC
**What can it be used for?**
It can be used while giving link for leetcode profile in resume.

**Example image (optional)**
![leetcode](https://user-images.githubusercontent.com/36547915/97088991-45da5d00-1652-11eb-900f-80d106540f4f.png)

**Comment by tagliala** [comment] 2020-10-24 18:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15337, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-10-24 18:20 UTC
