### ISSUE TITLE
Icon Request: fa-gmail

### ISSUE THREAD

**Issue by ricardopolo** [FortAwesome/Font-Awesome#5694] opened 2015-02-17 00:05 UTC

**Comment by Dehli** [comment] 2015-02-18 15:56
For the time being, can you use: http://fortawesome.github.io/Font-Awesome/icon/envelope-o/

**Comment by tagliala** [comment] 2015-02-19 15:22
duplicate of #4655 

please +1 that request

closing here

**Closed by tagliala** 2015-02-19 15:22 UTC
