### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by saveerreddy** [FortAwesome/Font-Awesome#17917] opened 2021-05-21 06:45 UTC
**What can it be used for?**
Paytm, PhonePay, UPI payments are the payments present in India hence developers from India can use these which are missing from your icons 

There are many latest icons missing from the store and also there are no freelancing websites like fiver or sites like canava were present lot are missing 

**Example image (optional)**
https://seeklogo.com/vector-logo/305549/paytm
https://www.logo.wine/logo/PhonePe
https://en.wikipedia.org/wiki/Unified_Payments_Interface#/media/File:UPI-Logo-vector.svg

**Icon request checklist**
- [ ] This is a single icon
- [ ] `Icon request: Paytm`,`Icon request: PhonePe`,`Icon request: UPI Payment`
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-05-21 07:34
Hi!

Thanks for being part of the Font Awesome Community.

> Paytm, PhonePay, UPI payments are the payments present in India hence developers from India can use these which are missing from your icons

paytm is a duplicate of #13448, please +1 that request
UPI is a duplicate of #12700, please +1 that request
phonepe is a duplicate of #15429, please +1 that request

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

All duplicates, closing here

**Closed by tagliala** 2021-05-21 07:34 UTC

**Comment by saveerreddy** [comment] 2021-05-21 11:03
Agreed they are duplicated but we see they are under process since ages and now this is high time so requesting to create the Icons and launch them

**Comment by tagliala** [comment] 2021-05-21 11:10
Please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), they contain a lot of information about how requests work
