### ISSUE TITLE
Icon request: plus-circle-o and minus-circle-o

### ISSUE THREAD

**Issue by DonaldBerk** [FortAwesome/Font-Awesome#7216] opened 2015-08-12 19:38 UTC
You have a plus-circle and minus-circle. I request '-o' versions.

**Comment by tvirelli** [comment] 2015-08-12 22:15
+1

**Comment by user-e** [comment] 2015-08-13 10:32
![image](https://cloud.githubusercontent.com/assets/13541254/9247906/fdd7718c-41ae-11e5-9073-ba247d52a50e.png)

**Comment by tagliala** [comment] 2015-08-13 15:06
Duplicate of #2417, please +1 that request

closing here

**Closed by tagliala** 2015-08-13 15:06 UTC
