### ISSUE TITLE
Icon Request: fa-file-xml-o

### ISSUE THREAD

**Issue by jpajuelo** [FortAwesome/Font-Awesome#11787] opened 2017-11-22 09:55 UTC
It would be interesting to have a file icon with the XML format. Something like this:

![fa-file-xml-o](https://user-images.githubusercontent.com/6609719/33120811-77ae4d38-cf73-11e7-90b2-24bccf2f149e.png)

Thank you!

**Comment by tagliala** [comment] 2017-11-22 10:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5016, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-22 10:46 UTC
