### ISSUE TITLE
Icon Request: fa-shopping-bag

### ISSUE THREAD

**Issue by KickinAss** [FortAwesome/Font-Awesome#7104] opened 2015-07-31 15:12 UTC
Hi guys,
could you please add a shopping bag icon for ecommerce? 

Fantastic work, we love you! :)

![bags](https://cloud.githubusercontent.com/assets/7668956/9010438/3083040a-37a7-11e5-8bb8-f8e2ccadeab5.jpg)

**Comment by TheChen5** [comment] 2015-07-31 17:35
Dupe of #829 & #4404
+1 those
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment] 2015-07-31 20:01
@TheChen5 thanks

**Closed by tagliala** 2015-07-31 20:01 UTC
