### ISSUE TITLE
Icon request: cheese

### ISSUE THREAD

**Issue by Starlin0428** [FortAwesome/Font-Awesome#14167] opened 2018-10-24 09:13 UTC
### What can it be used for?
May I suggest an icon for cheese lovers? And more food sector icons are welcome as well. I found that you don't have on fontawesome.com either paid or free version.

### Example image (optional)
https://goo.gl/ktYaUk

### Icon request checklist
- [x] This is a **single** icon or matched pair (Ex: lock / unlock)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Cheers~

**Comment by tagliala** [comment] 2018-10-24 16:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8046, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-24 16:00 UTC
