### ISSUE TITLE
Icon Request: fa-hangup

### ISSUE THREAD

**Issue by tvvignesh** [FortAwesome/Font-Awesome#7338] opened 2015-08-29 13:57 UTC
You can have a hangup icon while doing a video or audio call in web. 

![capture](https://cloud.githubusercontent.com/assets/1165845/9562223/e5854c4e-4e83-11e5-9012-5a381d832bbb.PNG)

Its used in Google Hangouts

**Comment by tagliala** [comment] 2015-09-14 06:05
duplicate of #4405, please +1 that request

closing here

**Closed by tagliala** 2015-09-14 06:05 UTC
