### ISSUE TITLE
Icon Request: fa-chrome

### ISSUE THREAD

**Issue by anaflasker** [FortAwesome/Font-Awesome#7028] opened 2015-07-23 19:42 UTC
Will the rise of apps integrated into chrome, a fa-chrome icon would be handy :)

**Comment by sha-2** [comment] 2015-07-23 21:50
Duplicate of #219

**Comment by TheChen5** [comment] 2015-07-25 23:18
To support #219 , go to that issue and "+1" .

**Comment by tagliala** [comment] 2015-07-26 13:16
@TheChen5 thanks

**Closed by tagliala** 2015-07-26 13:16 UTC
