### ISSUE TITLE
Please add an icon 

### ISSUE THREAD

**Issue by ahmetbcakici** [FortAwesome/Font-Awesome#15678] opened 2019-10-11 14:04 UTC
I can not find icon & logo for UDEMY

**Comment by tagliala** [comment] 2019-10-11 14:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8664, please add a 👍 reaction to that request.

You may be interested in taking a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), it contains a lot of information on how requests work

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-10-11 14:07 UTC
