### ISSUE TITLE
Icon request: clock-rotate-right

### ISSUE THREAD

**Issue by gilles-crealp** [FortAwesome/Font-Awesome#17687] opened 2021-03-04 14:23 UTC
**What can it be used for?**
You have a [`clock-rotate-left` icon](https://fontawesome.com/icons/history). It would be useful to have a paired `clock-rotate-right` icon so we can switch from history to live data…

**Example image**
The same icon as [`clock-rotate-left` icon](https://fontawesome.com/icons/clock-rotate-left) but with the arrow in the clockwise direction.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment] 2024-07-11 15:55
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/19001)

**Closed by sensibleworld** 2024-07-11 15:55 UTC
Labels: new icon, Duplicate
