### ISSUE TITLE
Weird characters on random refreshes

### ISSUE THREAD

**Issue by timgabrhel** [FortAwesome/Font-Awesome#14660] opened 2019-02-20 12:06 UTC
### Describe the problem

Searching for a problem similar to mine, I came across #10842. The behavior is identical. Some random refreshes will render weird characters. Typically a refresh fixes it.

![image](https://user-images.githubusercontent.com/791022/53090143-203b9e80-34d4-11e9-8761-95fe66d9ac93.png)

### What did you expect?

The icons to render appropriately

### What version and implementation are you using?

Version: Font Awesome 5 Pro
Browser and version: Chrome 72.0.3626.109

Font Awesome scss is imported into our site scss, ultimately compiled down to a single minified css.

### Reproducible test case

It is seemingly random. When it occurs, here's what I can see from dev tools. This time around, I was lucky enough to have dev tools already opened when the problem occurred, and did not see my site.min.css present in the network tab traffic. Perhaps this is browser caching. We have seen this issue surface on brand new page loads after a deployment, as random refreshes on a site deployed and accessed for days.

![image](https://user-images.githubusercontent.com/791022/53090316-a3f58b00-34d4-11e9-9abc-900608f8960f.png)

This doesn't feel like a server output encoding problem (mentioned in the other thread), as a refresh solves it. These are compiled down on our build server and deployed out. Typically, the icons come back after a refresh.

**Comment by tagliala** [comment] 2019-02-20 12:53
Hi!

Thanks for being part of the Font Awesome Community.

> Font Awesome scss is imported into our site scss, ultimately compiled down to a single minified css.

Could you please post the relevant part of your compiled css?

**Comment by timgabrhel** [comment] 2019-02-20 14:27
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> > Font Awesome scss is imported into our site scss, ultimately compiled down to a single minified css.
> 
> Could you please post the relevant part of your compiled css?

Just like I saw in the other related thread, here's the css.

![image](https://user-images.githubusercontent.com/791022/53098467-4ddf1280-34e9-11e9-8a4b-2dc521478756.png)

**Comment by tagliala** [comment] 2019-02-20 14:46
Ok, I can confirm that it is the same problem as #10842

I think there is an issue while precompiling font awesome in your stack, but I'm not so confident of the origin of this issue.

Could you please check that there are no Font Awesome 4 scss file in your repository?

Anyway, given the input:

```scss
// Convenience function used to set content property
@function fa-content($fa-var) {
  @return unquote("\"#{ $fa-var }\"");
}

$fa-css-prefix: fa;
$fa-var-pencil: \f040;

.#{$fa-css-prefix}-pencil:before { content: fa-content($fa-var-pencil); }
```

A proper compilation process will provide the following output:

```scss
.fa-pencil:before {
  content: "\f040";
}
```

You can check your sass compiler type and version, maybe you need an update.

All the versions I've checked on sassmeister.com provide the following correct output

![image](https://user-images.githubusercontent.com/556268/53099524-425e0c80-3526-11e9-9754-4e626cf086da.png)

Closing here, but feel free to comment.

I will reopen if we figure out that there is an issue in Font Awesome itself

**Closed by tagliala** 2019-02-20 14:46 UTC
Labels: waiting for feedback

**Comment by rafecolton** [comment] 2019-05-10 18:34
@tagliala we are still experiencing this with 5.8.1. It happens intermittently even when scss has not been recompiled. Is there any definitive solution?

**Comment by MitchTalmadge** [comment] 2021-03-04 01:05
Running into the same problem with random refreshes causing weird characters to display.

I've noticed that if you open the compiled CSS file in an editor and change the encoding mode to "Windows 1252", then it will show the exact same characters:

**UTF-8:**
![image](https://user-images.githubusercontent.com/8848080/109894553-eff27300-7c4a-11eb-98ac-9eb432da376a.png)

**Windows 1252:**
![image](https://user-images.githubusercontent.com/8848080/109894525-e49f4780-7c4a-11eb-9e7a-6e18555d402a.png)

Now to find out why the browser randomly uses this encoding.

**Comment by tagliala** [comment] 2021-03-04 09:38
@MitchTalmadge the proper output is UTF-8

Could you please check that your CSS starts with `@charset "UTF-8";`?

Ref: https://github.com/sass/dart-sass/issues/568#issuecomment-770105804

Anyway, I think that we have issues with dart sass again.

Will discuss this in our private repo

**Comment by MitchTalmadge** [comment] 2021-03-04 15:46
Hi @tagliala, 

I think our HTML page was missing a meta tag for the UTF-8 charset. Either way, we've added charset=utf-8 to our content-type header for CSS files and it seems to be working now. 

Thank you!

**Comment by tagliala** [comment] 2021-03-04 16:12
welcome

> I think our HTML page was missing a meta tag for the UTF-8 charset.

Oh, thanks.

I'm ashamed of myself, but now I've got that the utf `<meta>` tag also works for linked assets

If you set that meta tag, then you will not need `@charset "UTF-8"` in the CSS

### Scenario 1: UTF HTML `<meta>` tag + CSS `@charset`

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="style.css" rel="stylesheet">
    <title></title>
  </head>
  <body>
    <span class="monkey">
  </body>
</html>
```

```css
@charset "UTF-8";
.monkey::before {
  display: block;
  content: "🙈";
}
```

![image](https://user-images.githubusercontent.com/556268/109993101-3d82e480-7d0c-11eb-81d5-5097cc870dd8.png)

---

### Scenario 2: UTF HTML `<meta>` tag

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="style.css" rel="stylesheet">
    <title></title>
  </head>
  <body>
    <span class="monkey">
  </body>
</html>
```

```css
.monkey::before {
  display: block;
  content: "🙈";
}
```

![image](https://user-images.githubusercontent.com/556268/109993326-73c06400-7d0c-11eb-88b9-1acccc028815.png)

---

### Scenario 3: CSS `@charset`

```html
<!DOCTYPE html>
<html>
  <head>
    <link href="style.css" rel="stylesheet">
    <title></title>
  </head>
  <body>
    <span class="monkey">
  </body>
</html>
```

```css
@charset "UTF-8";
.monkey::before {
  display: block;
  content: "🙈";
}
```

![image](https://user-images.githubusercontent.com/556268/109993486-a2d6d580-7d0c-11eb-97f6-3715a2a0498c.png)

---

### Scenario 4: no meta tag, no charset

```html
<!DOCTYPE html>
<html>
  <head>
    <link href="style.css" rel="stylesheet">
    <title></title>
  </head>
  <body>
    <span class="monkey">
  </body>
</html>
```

```css
.monkey::before {
  display: block;
  content: "🙈";
}
```

![image](https://user-images.githubusercontent.com/556268/109993569-baae5980-7d0c-11eb-882e-39bef6579d25.png)

**Comment by tagliala** [comment] 2021-04-16 07:33
🔒 Locking here, let's use #17644
