### ISSUE TITLE
Icon Request: fa-amazon

### ISSUE THREAD

**Issue by peterherman** [FortAwesome/Font-Awesome#5612] opened 2015-02-07 15:14 UTC
Hi guys, thanks for all the nice icons in your project. I have a new idea. What think you of it to make an Amazon Icon? I could use it on my website to indicate to Amazon products. Thanks and regards

**Comment by tagliala** [comment] 2015-02-07 16:18
duplicate of #471 , please +1 that request

closing here

**Closed by tagliala** 2015-02-07 16:18 UTC
