### ISSUE TITLE
Icon request: letterboxd

### ISSUE THREAD

**Issue by stephan-strate** [FortAwesome/Font-Awesome#17978] opened 2021-06-04 08:00 UTC
**What can it be used for?**
Letterboxd is a global social network for movie lovers. You can also keep track on the movies you have watched in the past (like a diary). The icon could be used to link to your personal profile (similar to facebook, twitter, ...).

**Example image (optional)**
Letterboxd offers branding information: https://letterboxd.com/about/brand/
![](https://a.ltrbxd.com/logos/letterboxd-decal-dots-pos-rgb-500px.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-06-04 08:04
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3680, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-06-04 08:04 UTC

**Comment by stephan-strate** [comment] 2021-06-04 17:32
Sorry for that. But the link "existing requests" in your faqs does actually not show the "letterboxd" request (https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+icon%22+letterboxd), because it is missing the label "new icon". Maybe this should be adjusted to prevent more duplicates!

**Comment by tagliala** [comment] 2021-06-04 22:08
Hi, thanks for the feedback, I've got the issue.

@talbs @robmadole the link to search for existing requests in FAQs is the same for both New Icons and Brands

GitHub does not provide a filter to search for labels in or.

At the moment I can only see the following solutions:
1. Remove the label from the search
2. Provide two different links (change "new icons" with "brands icon" label in brands FAQs)
3. Create a common label for both requests and search for that

I have a slight preference for the third one

Ref:
- https://fontawesome.com/community/leaderboard/brands#faqs
- https://fontawesome.com/community/leaderboard/new#faqs

**Comment by robmadole** [comment] 2021-06-26 17:11
@tagliala I think removing the label in the search will probably be the easiest here. I know that's not your preferred but if you are cool with that I've got a PR up that can be merged pretty quick.
