### ISSUE TITLE
New Icon Request - a Cat

### ISSUE THREAD

**Issue by NJWebDesign** [FortAwesome/Font-Awesome#9326] opened 2016-06-03 07:16 UTC
I know there is a paw icon but I'm doing a site for a dog rescue charity and when I've used that icon in reference to a dog being "good with cats" they've highlighted that it's actually a dog paw print, not a cat.
Would it be possible to include a cat/feline icon in the next release/upgrade?

Thank you so much.
NJ

**Comment by tagliala** [comment] 2016-06-03 11:36
Duplicate of #2226, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-03 11:36 UTC
