### ISSUE TITLE
Icon request: XML

### ISSUE THREAD

**Issue by Berkmann18** [FortAwesome/Font-Awesome#13710] opened 2018-08-04 22:21 UTC
### What can it be used for?

XML is (alongside JSON) the core language when it comes to data interchange and configurations and more too (e.g: Windows gadget development, Android development, Semantic Web, ...)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by NickNiebling** [comment] 2018-09-05 09:37
Just adding my thoughts to help people "work around" current limitation.

I do think it's difficult to add "xml" icon, since [file-code](https://fontawesome.com/icons/file-code?style=regular) is looking exactly as I would suggest file-xml to look.

You could argue that [file-code](https://fontawesome.com/icons/file-code?style=regular) both covers "code", "xml", "html", "xhtml", "xaml" and any other "xml based" file format. It would be difficult to implement all those in different ways either way (might be required for some - but difficult for sure).

Currently I've been able to use [file-code](https://fontawesome.com/icons/file-code?style=regular) when I needed "xml icon", since I never need "code" and "xml" icons side by side. However, others might find that to be a limitation they cannot overcome and therefore need explicit code and xml file icons that works side by side.

**Comment by tagliala** [comment] 2018-09-05 10:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5016, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-05 10:27 UTC
