### ISSUE TITLE
Icon Request: fa-untappd

### ISSUE THREAD

**Issue by brewtalizer** [FortAwesome/Font-Awesome#11321] opened 2017-07-24 20:14 UTC
How about an Untappd Icon? Untappd has become the leading social media platform for the beer industry!
![image](https://user-images.githubusercontent.com/23245454/28542700-1dd2038c-708b-11e7-8bc0-9898cd9db8d6.png)

**Comment by tagliala** [comment] 2017-07-24 20:31
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1971 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-24 20:31 UTC
