### ISSUE TITLE
Brand request: Matomo

### ISSUE THREAD

**Issue by pstranghoener** [FortAwesome/Font-Awesome#19445] opened 2022-11-23 08:31 UTC
### Description

Matomo is an open source and self hosted analytics software for web and mobile tracking

### Official website

https://matomo.org/

### Brand guidelines

https://matomo.org/media

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2022-11-23 08:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14178, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-11-23 08:37 UTC
Labels: brand icon
