### ISSUE TITLE
Icon request: odysee

### ISSUE THREAD

**Issue by Binklebonk** [FortAwesome/Font-Awesome#18051] opened 2021-07-05 08:18 UTC
**What can it be used for?**
The Odysee icon, from the decentralised video platform Odysee.

**Example image (optional)**
https://odysee.com/public/img/odysee_white.png

Press Kit:
https://odysee.com/@OdyseeHelp:b/odyseepresskit:b

**Icon request checklist**
- ☑ This is a single icon or matched pair (Ex: `lock` / `unlock`)
- ☑ The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- ☑ I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- ☑ I have included at least one example image if it could be helpful (optional)
- ☑ The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by BWPanda** [comment] 2021-12-19 03:58
Duplicate of https://github.com/FortAwesome/Font-Awesome/issues/17320

**Comment by tagliala** [comment] 2021-12-19 11:47
Thanks. closing here

**Closed by tagliala** 2021-12-19 11:47 UTC
