### ISSUE TITLE
Icon request: Gab

### ISSUE THREAD

**Issue by anoduck** [FortAwesome/Font-Awesome#18369] opened 2021-10-17 19:30 UTC
**What can it be used for?**
Used exactly the same as icons for Facebook, Twitter, Instagram, TikTok, etc, etc, ...

Gab is an incredibly popular Social Media platform with millions of users worldwide. More users than many of the social media platform icons you already offer and have for some time.

**Example image (optional)**
https://img.flaticon.com/icons/png/512/3291/3291673.png?size=1200x630f&pad=10,10,10,10&ext=png&bg=FFFFFFFF

**Comment by tagliala** [comment] 2021-10-18 06:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10304, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2021-10-18 06:48 UTC
