### ISSUE TITLE
Icon Request: fa-bilibili 

### ISSUE THREAD

**Issue by tribute2nujabes** [FortAwesome/Font-Awesome#10907] opened 2017-04-07 09:07 UTC
Bilibili is one of the Chinese biggest video sharing site. Many people post their own videos as well. 

Uses: Just like using other social media icon (facebook, instagram, etc), the Bilibili icon can link the personal page of a specific Bilibili user so that others can see the video works of the user.

![image](https://cloud.githubusercontent.com/assets/25135269/24793304/6976c9f8-1b36-11e7-98c6-d0a257b92935.png)

**Comment by PeterShaggyNoble** [comment] 2017-04-07 09:12
Dupe of #9789, you should 👍 that.

**Closed** 2017-04-07 10:40 UTC
