### ISSUE TITLE
 Icon request: fa-brain

### ISSUE THREAD

**Issue by cbielich** [FortAwesome/Font-Awesome#12743] opened 2018-03-30 16:39 UTC
How do you not have a brain as an icon? I am requesting one.

**Comment by tagliala** [comment] 2018-04-06 15:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2075 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 15:19 UTC
