### ISSUE TITLE
new icon request

### ISSUE THREAD

**Issue by alxmat77** [FortAwesome/Font-Awesome#10886] opened 2017-04-04 08:37 UTC
Blackboard-lesson
![icona](https://cloud.githubusercontent.com/assets/26894806/24648060/9d012c5c-1922-11e7-8d20-a72784a0b805.png)

**Comment by tagliala** [comment] 2017-04-04 09:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3308, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-04 09:27 UTC
