### ISSUE TITLE
Icon request: litecoin

### ISSUE THREAD

**Issue by Supercircles** [FortAwesome/Font-Awesome#14894] opened 2019-04-14 04:48 UTC
Bitcoin, Ethereum, Litecoin. I think these are three good coins to have as a baseline.

![Capture-litecoin](https://user-images.githubusercontent.com/22516378/56088449-40396f80-5e3e-11e9-820e-9ff0521e267a.PNG)

**Comment by tagliala** [comment] 2019-04-16 15:40
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1768 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-16 15:40 UTC
