### ISSUE TITLE
Icon request: Dashboard

### ISSUE THREAD

**Issue by mgauthier77** [FortAwesome/Font-Awesome#15789] opened 2019-11-08 16:52 UTC
**What can it be used for?**
The icon would be used to represent a website dashboard or homepage.

**Example image (optional)**
![view-dashboard-variant](https://user-images.githubusercontent.com/47896793/68495423-26b6a580-021e-11ea-875e-5cab584fcb10.png)
**Icon request checklist**
- [ X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [ X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-11-09 08:47
Hi!

Thanks for being part of the Font Awesome Community.

I'm pretty confident that this is a duplicate, but the original name has something to do with masonry / bricks / layout etc.

At the moment I'm not able to find that, so leaving this open

**Comment by mgauthier77** [comment] 2019-11-09 22:44
I too was surprised to not find it. I searched using every word I could
think of.

**Comment by mgauthier77** [comment] 2019-11-11 15:02
I checked again manually and found nothing

**Comment by tagliala** [comment] 2019-11-11 15:37
Found #7865

**Comment by aethior** [comment] 2022-04-18 21:49
> Found #7865

And duplicate of #14488.

**Comment by aethior** [comment] 2022-05-20 19:17
> And duplicate of #14488.

@tagliala check here please.

**Closed** 2022-05-20 21:43 UTC
Labels: waiting for feedback
