### ISSUE TITLE
Icon request: discord

### ISSUE THREAD

**Issue by toby3d** [FortAwesome/Font-Awesome#11142] opened 2017-06-07 07:54 UTC
I plan to use this for highlight discord-server invite-links.
![](https://discordapp.com/assets/e05ead6e6ebc08df9291738d0aa6986d.png)

---

**P.S.**: Oh, god, [JUST ADD PATREON ICON TOO ISSUE JUST LIVE FROM 2014 YEAR ARE YOUR SERIOUS](https://github.com/FortAwesome/Font-Awesome/issues/3257)

**Comment by tagliala** [comment] 2017-06-07 08:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-07 08:03 UTC
