### ISSUE TITLE
Icon request: icon-piggy-bank

### ISSUE THREAD

**Issue by melm73** [FortAwesome/Font-Awesome#7909] opened 2015-11-18 09:01 UTC
hi Font-Awesome, I am writing an application for managing personal finances, and would like an icon to represent a savings account. A piggy bank would be perfect.

![piggy bank](https://cloud.githubusercontent.com/assets/8097255/11236662/44fb7262-8e2f-11e5-94f7-92a098971e2f.jpeg)

**Comment by tagliala** [comment] 2015-11-18 09:26
duplicate of #1413 , please +1 that request

closing here

**Closed by tagliala** 2015-11-18 09:26 UTC
