### ISSUE TITLE
Icon request: display-arrow-up

### ISSUE THREAD

**Issue by EchoNBounce** [FortAwesome/Font-Awesome#19349] opened 2022-09-23 22:38 UTC
For screen share etc to match the iconography used by e.g. Zoom and Teams.

**Comment by tagliala** [comment] 2022-09-24 09:34
Hi!

Thanks for being part of the Font Awesome Community.

I would consider this a duplicate of #18566 or #15050, please add a 👍🏼 reaction to those requests

I would also provide a single icon to represent screen sharing across multiple devices

**Closed as completed by tagliala** 2022-09-24 09:34 UTC
