### ISSUE TITLE
Icon request: icon-nuke

### ISSUE THREAD

**Issue by PCJinUY** [FortAwesome/Font-Awesome#12646] opened 2018-03-19 21:13 UTC
Hello,
I'm looking for something to replace the microphone icon  in the sub-header at caferadlab.com and was wondering if someone could create one or two icons to choose from. one could be called atom 
![atomic](https://user-images.githubusercontent.com/28397053/37622692-22adc27a-2ba1-11e8-8d8a-e0a331ad29ff.png)
 and the other nuclear or nuke 
![nuke](https://user-images.githubusercontent.com/28397053/37622728-3d52c85a-2ba1-11e8-8e24-b4ab38cb2c65.jpg)

Thanks a bunch!
Pia

**Comment by tagliala** [comment] 2018-03-20 08:18
Hi!

Thanks for being part of the Font Awesome Community.

Radiation is a duplicate of #4470, please add a 👍  reaction to that request.
Atom is a duplicate of #664, please add a 👍 reaction to that request that I'm going to reopen

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-20 08:18 UTC

**Comment by PCJinUY** [comment] 2018-03-20 19:03
Actually,sorry, I reviewed all the other fa atom references, including #664 and would really like the one I provided an example of above. Thanks for re-opening the thread on atom symbol yesterday in another thread.
