### ISSUE TITLE
Some icons do not show up

### ISSUE THREAD

**Issue by pantonis** [FortAwesome/Font-Awesome#14239] opened 2018-11-08 13:27 UTC
I am using 3 icons

far fa-chart-bar
far fa-chart-line
far fa-check 

chart bar is shown without any problems
chart-line and check dont show up just a rectable with white border:
![image](https://user-images.githubusercontent.com/3295086/48201389-afc8a180-e36a-11e8-8e6b-3ccf02ec989a.png)

All of them use the same style

![image](https://user-images.githubusercontent.com/3295086/48201381-a9d2c080-e36a-11e8-90fb-fc124e5c4b4d.png)

When I set the font-weight:600 on them (chart-line and check) they show up

**Comment by tagliala** [comment] 2018-11-09 08:45
Hi!

Thanks for being part of the Font Awesome Community.

There are a couple of issues in this report:

1. Since it is related to Font Awesome Pro, this issue belongs to the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro
If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

2. This bug report doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).
Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
Closing here

Given the above, I'm unable to replicate (Font Awesome 5.5.0 Pro loaded via CDN)

![image](https://user-images.githubusercontent.com/556268/48251959-a8a1a200-e403-11e8-8330-bd32b5f341a5.png)

I suspect that you are loading Font Awesome Pro from your own server, but something may be wrong with your installation.

`font-weight` has to be 400 and using 600 would load solid icons.

Also, `fa-bar-chart` is available in regular style in the Free set, so I can also suppose that you have lodaded the free font files and renamed as Pro, please check that.

Hope it helps

Closing here

**Closed by tagliala** 2018-11-09 08:45 UTC

**Comment by pantonis** [comment] 2018-11-26 07:07
@tagliala I am using angular I cant use CDN.
Here is what I have in my angular.json.

           ```
 "styles": [
              "node_modules/@fortawesome/fontawesome-pro/css/fontawesome.min.css",
              "node_modules/@fortawesome/fontawesome-pro/css/solid.min.css",
              "node_modules/@fortawesome/fontawesome-pro/css/regular.min.css",
              "node_modules/@fortawesome/fontawesome-pro/css/light.min.css",
              "node_modules/@fortawesome/fontawesome-pro/css/brands.min.css",
            ]
```

Am I missing something?
Before I updated from version 5.2.0 to 5.5.0 it was working without any issues.

**Comment by tagliala** [comment] 2018-11-26 09:04
@pantonis could we please continue on the Pro Repository?

> 1. Since it is related to Font Awesome Pro, this issue belongs to the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro
> If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Could this be caused by #12575 ?

Please try https://github.com/FortAwesome/Font-Awesome/issues/12575#issuecomment-437018110

**Comment by FernandoBoza** [comment] 2019-03-01 13:36
@tagliala whats the update on the new FortAwesome/Font-Awesome-Pro repo? Had a question about angular and the library method for pro icons, since they're not showing up.
