### ISSUE TITLE
Icon Request: fa-filter-empty

### ISSUE THREAD

**Issue by juncalguinea** [FortAwesome/Font-Awesome#11186] opened 2017-06-15 13:42 UTC
Hi!

I'm using the fa-filter icon and it would be great to have the very same icon but "empty" to represent whether filters are applied or not. The images attached represent what I'd like to achieve.

![captura de pantalla 2017-06-15 a las 15 41 23](https://user-images.githubusercontent.com/29458347/27184055-20dcd1ce-51e1-11e7-8ba4-c2bad72847c2.png)
![captura de pantalla 2017-06-15 a las 15 41 05](https://user-images.githubusercontent.com/29458347/27184060-226e31c2-51e1-11e7-9f84-f58ffab141d5.png)

Thank you so much! Font Awesome is an awesome project!

**Comment by tagliala** [comment] 2017-06-15 14:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4738, please add a 👍  reaction to that request.

You may also be interested in upvoting #650 

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-15 14:15 UTC
