### ISSUE TITLE
Icon request: icon-barrier

### ISSUE THREAD

**Issue by rockerest** [FortAwesome/Font-Awesome#9012] opened 2016-04-19 02:11 UTC
Alternatively: icon-construction, icon-road-barrier, icon-construction-barrier

A construction barrier could have a few use cases.
Most frequently, it would probably be used to indicate "under construction" - as an icon, this might mean a link to a prototype part of an application or a link that an automated system has detected is broken for many users.

In other scenarios, a "road barrier" could carry the meaning "Warning", "Detour", "Rough Travel Ahead", "Access Denied" or any other of many cautionary meanings.

Examples:
- **Warning**: [fa-barrier] "Click here for the advanced steps (requires Unix terminal experience)."
- **Detour**: [fa-barrier] "Temporarily Unavailable. Please use [Y] instead."
- **Rough Travel Ahead**: [fa-barrier] "This section is not for the faint of heart."
- **Access Denied**: [fa-barrier] "Your account has been denied access to this action. Please contact your administrator to determine why."

Here are some B&W images, but I don't think they have the right feel:

![12-512](https://cloud.githubusercontent.com/assets/277023/14625564/2f8126c0-05b2-11e6-9cd1-1e2ecd3bb334.png)
![1239167-clipart-of-a-black-and-white-road-block-construction-barrier-royalty-free-vector-illustration](https://cloud.githubusercontent.com/assets/277023/14625566/32806886-05b2-11e6-87b5-383bbdf40558.jpg)
![outlined-construction-barrier_gg71534247](https://cloud.githubusercontent.com/assets/277023/14625569/384ae412-05b2-11e6-94ed-f27d8befaf90.jpg)

The following color images capture what I think of when I think of "Construction Barrier":
![depositphotos_5428100-under-construction-barrier](https://cloud.githubusercontent.com/assets/277023/14625574/4f62840c-05b2-11e6-9f7e-9b0da1663421.jpg)
![construction_barrier](https://cloud.githubusercontent.com/assets/277023/14625575/52d75fa4-05b2-11e6-9034-af7b366f95d1.PNG)

**Comment by tagliala** [comment] 2016-04-19 10:54
Duplicate of #5653, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by rockerest** [comment] 2016-04-22 20:52
This is not remotely close to the same thing.

I also searched many themes - and found that one.

**Comment by tagliala** [comment] 2016-04-22 22:04
@rockerest sorry, you are right. Reopening here

**Comment by rockerest** [comment] 2016-04-23 02:08
I should apologize as well. Thanks for doing the work you do for this project.

I also misspoke: these *are* close to the same thing, but share a very small overlap of use cases.
Frankly, I think this is the superior choice as it can be used in the same situations but adds many more where `fa-roadworks`/`fa-under-construction` could not be.

Sorry for my short bluntness before. I deeply appreciate you re-opening!

**Comment by phuyem** [comment] 2016-04-26 11:55
This icon is useful . Really like it

**Comment by djereg** [comment] 2017-03-03 22:44
Any news about the barrier icon?

**Comment by invot** [comment] 2017-04-12 16:23
Great suggestion. I would love to see this added sometime soon.

**Comment by invot** [comment] 2017-04-12 16:23
Also, possible duplicate: #8384

**Comment by djereg** [comment] 2017-04-12 16:51
No no! The two icons are not same. This barrier icon is for vehicles, but the referenced is for humans.

**Comment by rockerest** [comment] 2017-04-16 06:16
> This barrier icon is for vehicles, but the referenced is for humans.

For whatever it's worth, in addition to the difference of motion (vehicle versus human), #8384 really makes me think of "ticketing" or "queuing" or "single-file throttling". The point of a turnstile like the one suggested in that issue is almost never to warn people of danger or unavailability (as `fa-barrier` would), it's almost always to let people through, but count them.

**Comment by mktaylorolsen** [comment] 2019-07-19 18:27
Is there any update on this icon?

I am working on an app that requires doctors to "Add a Barrier" if a treatment cannot be performed. Need this icon!!!

**Comment by aethior** [comment] 2022-03-20 20:20
🚧 [U+1F6A7](https://emojipedia.org/emoji/%F0%9F%9A%A7/) Construction

Also known as `Black And Yellow Striped Sign`, `Roadwork` and `Roadwork Sign`.

**Comment by aethior** [comment] 2022-03-20 20:21
Hi,

`fa-road-barrier` icon has been added in v6.1.0.
Check https://fontawesome.com/icons/road-barrier

Regards.

**Comment by aethior** [comment] 2022-03-20 20:21
Hi,

`fa-road-barrier` icon has been added in v6.1.0.
Check https://fontawesome.com/icons/road-barrier

Regards.

cc/ @tagliala 

Edit. I think this icon can also be added also to the `construction` category.

**Closed** 2022-03-20 20:29 UTC
Labels: new icon, transportation (category), logistics (category), humanitarian (category)
