### ISSUE TITLE
Icon Request: icon-vegan

### ISSUE THREAD

**Issue by vroup** [FortAwesome/Font-Awesome#13248] opened 2018-06-01 08:39 UTC
### What can it be used for?

Denoting that something is vegan friendly.

### Example image (optional)

http://teebragger.com/images/VegansymbolFINAL.jpg

### Icon request checklist

- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-06-01 09:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8293, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-01 09:07 UTC
