### ISSUE TITLE
Icon Request: Chat with a rep

### ISSUE THREAD

**Issue by lokeshnaicker** [FortAwesome/Font-Awesome#2372] opened 2013-11-07 21:23 UTC
Chat or
Chat with rep

**Comment by caih** [comment] 2015-06-21 20:56
+1

**Comment by caih** [comment] 2015-06-21 20:58
Wait, I think it's a dup: https://github.com/FortAwesome/Font-Awesome/issues/1146

**Comment by tagliala** [comment] 2015-06-21 21:31
thanks, @caih 

duplicate of #1146 or #5586  :)

Closing here

**Closed by tagliala** 2015-06-21 21:31 UTC
Labels: new icon, web application icons
