### ISSUE TITLE
Icon request: icon-Square-Pay brand icon

### ISSUE THREAD

**Issue by aready87** [FortAwesome/Font-Awesome#19145] opened 2022-06-21 16:50 UTC
A lot of people use Square for in-store credit card payments. (https://squareup.com/us/en).

I'm actually surprised one doesn't already exist!

![square](https://user-images.githubusercontent.com/33583755/174854195-c761aeed-f879-4016-8bae-14302e3612ae.svg)

**Comment by tagliala** [comment] 2022-06-27 20:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2477, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-06-27 20:19 UTC
