### ISSUE TITLE
Icon request: icon-fedora

### ISSUE THREAD

**Issue by Riverfount** [FortAwesome/Font-Awesome#12965] opened 2018-04-27 16:19 UTC
### What can it be used for?
I use fedora 27 with i3-wm and will be interesting to have a fedora icon to use on my status bar.

### Example image (optional)

[exemplo image](http://chittagongit.com/icon/fedora-icon-4.html)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-28 07:11
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this request a (better) duplicate of #980, which includes the most common linux distributions

Please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-28 07:11 UTC

**Comment by Riverfount** [comment] 2018-04-30 14:17
Thanks and I'm sorry to open a new issue unnecessarily!!!
