### ISSUE TITLE
Icon request: fa-earth, fa-earth-alt, fa-earth-alt2

### ISSUE THREAD

**Issue by NielsHolt** [FortAwesome/Font-Awesome#13253] opened 2018-06-01 11:57 UTC
![image](https://user-images.githubusercontent.com/11357972/40839605-a2ed81b4-65a3-11e8-919a-84f8ea945d08.png) ![image](https://user-images.githubusercontent.com/11357972/40839622-b818efa6-65a3-11e8-9011-5d4a1c8b0bf5.png) ![image](https://user-images.githubusercontent.com/11357972/40839637-bf4652b4-65a3-11e8-852f-83a498385a0d.png)

**Comment by tagliala** [comment] 2018-06-01 13:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #281 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-01 13:49 UTC
