### ISSUE TITLE
Icon request: hard-hat

### ISSUE THREAD

**Issue by ianbale** [FortAwesome/Font-Awesome#7981] opened 2015-11-25 16:06 UTC
![40289-200](https://cloud.githubusercontent.com/assets/8401461/11402117/13f752b2-938e-11e5-9ded-dde22ef8f043.png)

I would very much appreciate it if you would consider adding a "hard hat" as used on building sites. We plan to use it in place of a "home" icon to represent represent construction based training courses. We currently use fa-cutlery for Catering, fa-shopping-cart for Retail and fa-laptop for I.T. This would complete the set for us.

Many thanks,

Ian

**Comment by caduvieira** [comment] 2015-11-25 16:17
dupe of #5790
please +1 that one
Also related to #2658

**Closed** 2015-11-25 16:30 UTC
