### ISSUE TITLE
Icon Request: fa-fruits

### ISSUE THREAD

**Issue by tarunaggarwal54** [FortAwesome/Font-Awesome#9210] opened 2016-05-14 08:52 UTC
I am developing a online grocery store in which I need icons related to grocery.
![fruit](https://cloud.githubusercontent.com/assets/19358761/15267412/343eea62-19df-11e6-8aa2-58d0dea6bc70.png)

**Comment by tagliala** [comment] 2016-05-14 10:14
Duplicate of #5691, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-14 10:14 UTC
