### ISSUE TITLE
Icon request: Web/ www/ Internet

### ISSUE THREAD

**Issue by Niclas3er** [FortAwesome/Font-Awesome#14052] opened 2018-10-02 17:21 UTC
### What can it be used for?

Image for Websites/ Internet/ www

### Example image (optional)

![image](https://user-images.githubusercontent.com/31003182/46365189-386f6600-c678-11e8-84b7-d1d748d5e7ac.png)

![image](https://user-images.githubusercontent.com/31003182/46365202-491fdc00-c678-11e8-97e7-117da9eb0b90.png)

**Comment by tagliala** [comment] 2018-10-02 19:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6763, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-10-02 19:33 UTC
