### ISSUE TITLE
Fragrance bottle

### ISSUE THREAD

**Issue by BorisLechev** [FortAwesome/Font-Awesome#14849] opened 2019-04-02 11:46 UTC

**Comment by tagliala** [comment] 2019-04-02 12:02
Hi!

Thanks for being part of the Font Awesome Community.

Is this request a duplicate of #5717 ?

**Comment by BorisLechev** [comment] 2019-04-06 08:36
Yes, but when you will add that icon?

**Comment by tagliala** [comment] 2019-04-06 08:58
@BorisLechev thanks, please add a 👍 reaction to that request

> when you will add that icon?

Take at our [Icon Leaderboard](https://fontawesome.com/community/leaderboard/new). The [faqs section](https://fontawesome.com/community/leaderboard/new#faqs) contains a lot of information on how requests work

Hope it helps

Closing here

**Closed by tagliala** 2019-04-06 08:58 UTC
Labels: waiting for feedback
