### ISSUE TITLE
Icon request: icon-teacher

### ISSUE THREAD

**Issue by deleawo** [FortAwesome/Font-Awesome#10483] opened 2017-01-06 15:31 UTC
I am planning on using it on the homepage of our website to symbolise that we teach. Will appreciate it, if the teacher in the image is male. Thanks
![th 1](https://cloud.githubusercontent.com/assets/24961192/21722578/2dcd050a-d425-11e6-8f13-7e4d32ec6342.jpg)
![th](https://cloud.githubusercontent.com/assets/24961192/21722582/322ed290-d425-11e6-97c2-62db705b379c.jpg)

**Comment by tagliala** [comment] 2017-01-06 16:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4079 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-06 16:26 UTC
