### ISSUE TITLE
Icon request: brackets-slash

### ISSUE THREAD

**Issue by irontitan76** [FortAwesome/Font-Awesome#19263] opened 2022-08-11 15:02 UTC
There are several websites nowadays incorporating keyboard shortcuts for quicker traversal of the interface, such as a `/` for searching. I am requesting an icon similar to what is below (`[ / ]`) to alleviate the styling needed in code as well as give ample options to users (solid, thin, etc.).

<img width="516" alt="Screen Shot 2022-08-11 at 9 59 59 AM" src="https://user-images.githubusercontent.com/10472920/184164732-49290348-1b6d-4403-9825-a22ad1730053.png">

<img width="39" alt="Screen Shot 2022-08-11 at 9 58 33 AM" src="https://user-images.githubusercontent.com/10472920/184164404-ccc683d4-85fd-4fe6-9387-ac776b9d1016.png">

**Comment by aethior** [comment] 2022-08-20 11:32
Hi @irontitan76,

This request is a duplicate of #1465.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-08-21 08:09
Edited #1465's title to improve search

**Closed as completed by tagliala** 2022-08-21 08:09 UTC
