### ISSUE TITLE
Icon Request: fa-swimmingpool

### ISSUE THREAD

**Issue by kevinhusson1** [FortAwesome/Font-Awesome#8824] opened 2016-03-24 13:00 UTC
Hi,

For develop Hotel Website, i need icon for swimming pool.

Please, can you add this icon to your library ?

Thanks a lot

**Comment by tagliala** [comment] 2016-03-24 13:06
duplicate of #3285 , please +1 that request

closing here

**Closed by tagliala** 2016-03-24 13:06 UTC
