### ISSUE TITLE
Icon request: grip-hamburger

### ISSUE THREAD

**Issue by AdrianGasek** [FortAwesome/Font-Awesome#16266] opened 2020-03-04 10:50 UTC
**What can it be used for?**
The icon can be used as a replacement for the classic hamburger menu icon. A great example of using this icon is the page: https://www.google.com/ and https://translate.google.pl/ (upper right corner of the menu).
The icon should be assigned directly to the "Interfaces" category:
https://fontawesome.com/icons?c=interfaces

**Sample image (optional)**
**An example image of using the icon:** https://imgur.com/fyYT3Sm
**Examples of icon versions:** https://imgur.com/7zdgRrZ

**Icon request checklist**
- [ ] - This is a single icon or a matching pair [No, it will be a separate icon with different visual versions]
- [ ] - The title starts with "Icon request:" followed by the desired icon name [Icon request: grip-hamburger]
- [ ] - I was looking for existing problems, I found a similar icon: https://fontawesome.com/icons/grip-horizontal?style=solid and according to my best knowledge is not a duplicate.
- [ ] - I provided at least one sample image, if it may be helpful [I provided]
- [ ] -The request is for a specific object [yes, the request is for a specific icon]

**Comment by tagliala** [comment] 2020-03-04 11:00
Hi!

Thanks for being part of the Font Awesome Community.

We have [fa-th](https://fontawesome.com/icons/th?style=solid) which is almost identical

Also, this request is a duplicate of #6299, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-04 11:00 UTC
