### ISSUE TITLE
Please give option font width "Thin" or "Bold"

### ISSUE THREAD

**Issue by Pankaj-quad** [FortAwesome/Font-Awesome#9776] opened 2016-08-19 07:53 UTC
please give option font width **thin** or **bold** because some time bold font is looking very bold. 
thin font icon is best to view in website.  so please give second option font **Thin**. for all icon fonts.
for ex: navigation icon

**Comment by tagliala** [comment] 2016-08-19 09:36
Duplicate of #1733

Please note that every single icon should be redesigned, so maybe fontawesome is not the best choice for your project

Please take a look at [Font Awesome Black Tie](http://blacktie.io/) (note: commercial product) which comes with Black Tie - Regular and Black Tie - Light

**Closed by tagliala** 2016-08-19 09:36 UTC
