### ISSUE TITLE
Icon request: icon-firetruck

### ISSUE THREAD

**Issue by allor** [FortAwesome/Font-Awesome#13225] opened 2018-05-27 10:32 UTC
Need firetruck icon for emergency service application
![firetruck](https://user-images.githubusercontent.com/6686310/40584915-10247040-61ed-11e8-8e02-93b81163588d.png)

**Comment by tagliala** [comment] 2018-05-27 11:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5738, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-27 11:17 UTC
