### ISSUE TITLE
Icon request: icon-apps

### ISSUE THREAD

**Issue by Neonalig** [FortAwesome/Font-Awesome#8339] opened 2016-01-14 07:09 UTC
Thank you so much Font Awesome, Amazing work!!! I love your icons.
I have just 1 request: an Apps Icon (The Icon used with Chrome)
Would love for it to be used.
Reasons for creation: 1. Would be cool & easy for people to make websites like homepages with
2. There isn't one currently created and it would be amazing
3. I am currently needing one for a webpage i'm making and it would be very nice to have one.
Thanks for reading this request! ☺
![font awesome ideas](https://cloud.githubusercontent.com/assets/16698604/12317909/b41656ee-bad0-11e5-9f48-3abdbe029b3a.png)

**Comment by tagliala** [comment] 2016-01-14 12:09
Sorry, webfonts are limited to one color.

grid is a duplicate of #6299, please +1  that request

**Closed by tagliala** 2016-01-14 12:09 UTC
