### ISSUE TITLE
Feature Request: Provide ESM exports

### ISSUE THREAD

**Issue by csvan** [FortAwesome/Font-Awesome#18075] opened 2021-07-14 12:37 UTC
**Is your feature request related to a problem? Please describe.**

It should be easy for ESM projects, and projects using Webpack tree shaking (et al) to use Font Awesome in a pure ESM way.

**Describe the solution you'd like**

Each @fortawesome package should, like `material-ui` currently does, provide an `esm` folder where each source file exposes its exports using standard ESM syntax.

**Describe alternatives you've considered**

None, this needs to happen at compile time.

**Additional context**

Since the JS ecosystem at large is moving towards ESM as a standard, providing this would also create an easy crossover path for projects moving in that direction and using Font Awesome.

**Feature request checklist**
- [x ] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x ] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by cimchd** [comment] 2021-12-15 09:10
Additional info to this request. Vite provides a warning in esm projects with SSR:

```
vite v2.7.2 building SSR bundle for production...
@fortawesome/fontawesome-pro is incorrectly packaged. Please contact the package author to fix.
```

**Comment by mhatvan** [comment] 2022-01-08 09:46
Warning message from Vite looks ike this now:
`@fortawesome/fontawesome-free doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.`

**Comment by bhousel** [comment] 2022-02-15 17:06
Just wanted to echo the previous comment - it looks like there was an attempt to provide ESM exports for all of the fortawesome packages, but they are not currently working.

- recent versions of the javascript packages still have not configured their package.json with "type": module, so all their `.js` files will be treated as CJS modules, not ESM.
- but - the package.json now includes an "exports" map that specifies imports should come from "index.es.js". This looks like a valid ESM file, but is treated as CJS anyway and throws errors like this:
```
export { noAuto$1 as noAuto, config$1 as config, library$1 as library, dom$1 as dom, parse$1 as parse, findIconDefinition$1 as findIconDefinition, toHtml$1 as toHtml, icon, layer, text, counter, api };
^^^^^^
SyntaxError: Unexpected token 'export'
```

I _think_ this can be fixed just by renaming all of these `index.es.js` to `index.mjs` (and fixing the "exports" map in package.json) so that the node module loader knows how to treat this file.

**Comment by jaschaio** [comment] 2022-02-27 08:34
the fix suggested by @bhousel is working for me via `npx patch-package --exclude 'nothing' @fortawesome/fontawesome-svg-core`:

```diff
diff --git a/node_modules/@fortawesome/fontawesome-svg-core/index.es.js b/node_modules/@fortawesome/fontawesome-svg-core/index.mjs
similarity index 100%
rename from node_modules/@fortawesome/fontawesome-svg-core/index.es.js
rename to node_modules/@fortawesome/fontawesome-svg-core/index.mjs
diff --git a/node_modules/@fortawesome/fontawesome-svg-core/package.json b/node_modules/@fortawesome/fontawesome-svg-core/package.json
index 2167c1e..69c6438 100644
--- a/node_modules/@fortawesome/fontawesome-svg-core/package.json
+++ b/node_modules/@fortawesome/fontawesome-svg-core/package.json
@@ -52,35 +52,35 @@
   "version": "1.3.0",
   "name": "@fortawesome/fontawesome-svg-core",
   "main": "index.js",
-  "module": "index.es.js",
-  "jsnext:main": "index.es.js",
+  "module": "index.mjs",
+  "jsnext:main": "index.mjs",
   "style": "styles.css",
   "license": "MIT",
   "types": "./index.d.ts",
   "exports": {
     ".": {
-      "module": "./index.es.js",
-      "import": "./index.es.js",
+      "module": "./index.mjs",
+      "import": "./index.mjs",
       "require": "./index.js",
       "style": "./styles.css",
       "default": "./index.js"
     },
     "./index": {
-      "module": "./index.es.js",
-      "import": "./index.es.js",
+      "module": "./index.mjs",
+      "import": "./index.mjs",
       "require": "./index.js",
       "default": "./index.js"
     },
     "./index.js": {
-      "module": "./index.es.js",
-      "import": "./index.es.js",
+      "module": "./index.mjs",
+      "import": "./index.mjs",
       "require": "./index.js",
       "default": "./index.js"
     },
     "./plugins": {
-      "module": "./plugins.es.js",
-      "import": "./plugins.es.js",
-      "default": "./plugins.es.js"
+      "module": "./plugins.mjs",
+      "import": "./plugins.mjs",
+      "default": "./plugins.mjs"
     },
     "./import.macro": "./import.macro.js",
     "./import.macro.js": "./import.macro.js",
@@ -90,7 +90,7 @@
   },
   "sideEffects": [
     "./index.js",
-    "./index.es.js"
+    "./index.mjs"
   ],
   "scripts": {
     "postinstall": "node attribution.js"
diff --git a/node_modules/@fortawesome/fontawesome-svg-core/plugins.es.js b/node_modules/@fortawesome/fontawesome-svg-core/plugins.mjs
similarity index 100%
rename from node_modules/@fortawesome/fontawesome-svg-core/plugins.es.js
rename to node_modules/@fortawesome/fontawesome-svg-core/plugins.mjs
```

**Comment by GuilleDF** [comment] 2022-03-25 10:47
I'd argue this is a duplicate of #16439, right?

**Comment by robmadole** [comment] 2022-07-28 16:08
All we are going to focus the conversation about this in the PR https://github.com/FortAwesome/Font-Awesome/pull/19041

**Closed** 2022-09-29 07:44 UTC
Labels: feature
