### ISSUE TITLE
Icon request: icon-wheelchair-active

### ISSUE THREAD

**Issue by kangarolf** [FortAwesome/Font-Awesome#7214] opened 2015-08-12 16:51 UTC
I would love to see an active version of the wheelchair icon - something not as passive that indicates action. This is one I have used before

[chair](https://cloud.githubusercontent.com/assets/7556722/9230540/b16784d4-411a-11e5-9649-3847a57bc7c9.png)

**Comment by user-e** [comment] 2015-08-13 10:34
![Image](https://cloud.githubusercontent.com/assets/7556722/9230540/b16784d4-411a-11e5-9649-3847a57bc7c9.png)

**Comment by caduvieira** [comment] 2015-08-13 11:28
New accessibility icon
http://accessibleicon.org/support/
+1

**Comment by tagliala** [comment] 2015-08-13 13:29
@caduvieira thanks

closing here as a duplicate of #2746

**Closed by tagliala** 2015-08-13 13:29 UTC
