### ISSUE TITLE
Icon request: floorplan

### ISSUE THREAD

**Issue by chapeljuice** [FortAwesome/Font-Awesome#13721] opened 2018-08-06 20:54 UTC
### What can it be used for?
Single icon for conveying info such as # of bedrooms available, clicking on it could download a floorplan, etc.

### Example image (optional)
No example but I was thinking a top-down square with a room or two and a door arc.

**Comment by tagliala** [comment] 2018-08-07 08:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12064, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-07 08:17 UTC
