### ISSUE TITLE
Icon Request: fa-letter-b

### ISSUE THREAD

**Issue by themasudur** [FortAwesome/Font-Awesome#9914] opened 2016-09-14 12:36 UTC
### Font Awesome Letter Icon
Many websites may need icons to show letters in different purposes such as alphabetic ordered list, displaying prefix to the person names. This is why I make this issue to provide font awesome with alphabetic letters icon both uppercase and lowercase. 
_fa-letter-a_
_fa-letter-b_
_fa-letter-A_
_fa-letter-B_
A sample has been added to the issue for _letter B_. 
Thanks.

![b](https://cloud.githubusercontent.com/assets/6159808/18512151/85e5af60-7aa9-11e6-83c8-5174667b451f.png)
[Sample Image Courtesy](https://cdn2.iconfinder.com/data/icons/vkontakte-3/154/vkontakte-B-letter-sign-logotype-128.png)

**Comment by tagliala** [comment] 2016-09-15 09:58
Please use the standard unicode points

Duplicate of #5019

**Closed by tagliala** 2016-09-15 09:58 UTC
