### ISSUE TITLE
Tailwind, SQL

### ISSUE THREAD

**Issue by Ellen-Seghers** [FortAwesome/Font-Awesome#19093] opened 2022-06-02 09:28 UTC
Hi I really like font awesome but I miss some code icons like Tailwind and SQL. Maybe you could add them?

**Comment by tagliala** [comment] 2022-06-02 09:55
Hi!

Thanks for being part of the Font Awesome Community.

Tailwind is a duplicate of #17012, please add a 👍 reaction to that request.
SQL is a duplicate of #9555, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-06-02 09:55 UTC
