### ISSUE TITLE
Uncaught (in promise) Javascript error

### ISSUE THREAD

**Issue by hakuseki** [FortAwesome/Font-Awesome#9837] opened 2016-08-30 17:28 UTC
We are getting this error recently:

`undefined:1 Uncaught (in promise) hfamily: "FontAwesome"stretch: "normal"style: "normal"weight: "normal"__proto__: Objectconstructor: h(a,b)load: (a,e)__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()
2`

Enabled options
Font Awesome v4.6.3 · Auto Accessibility · Asynchronous Icons · Icon Stats

Pls advice

**Comment by tagliala** [comment] 2016-08-30 19:42
Could you please provide more details or a jsfiddle/codepen showing the issue?

**Comment by hakuseki** [comment] 2016-08-31 05:25
I don't know how to illustrate this but we have this Javascript error recently.

It comes in different shapes, this is a new one:

`undefined:1 Uncaught (in promise) h {family: "FontAwesome", style: "normal", weight: "normal", stretch: "normal"}Promise.reject (async)(anonymous function) @ 01afa80dfc.js:18Promise.reject (async)c @ 01afa80dfc.js:18setTimeout (async)(anonymous function) @ 01afa80dfc.js:18Promise.resolve (async)c @ 01afa80dfc.js:18
xregexp-min.js:2 Uncaught Error: can't load XRegExp twice in the same frame(anonymous function) @ xregexp-min.js:2`

**Comment by hakuseki** [comment] 2016-08-31 07:08
Hmm, the errors are gone now.
closing…

**Comment by dg-robinson** [comment] 2016-08-31 09:52
I'm getting a similar, intermittent error. I only started using the CDN version yesterday so can't really say how long this has been happening. This is the error I get in Chrome's console:

`Uncaught (in promise) h {family: "FontAwesome", style: "normal", weight: "normal", stretch: "normal"}`

It appears after the `Font Awesome CDN reporting has been enabled` line in the console. As I say, it's intermittent, and I haven't been able to identify a pattern so far.

**Comment by 91bananas** [comment] 2016-08-31 19:25
Also getting this when attempting to load a CDN based url, using `jQuery.getScript('https://use.fontawesome.com/<my hash>')`

**Comment by 91bananas** [comment] 2016-08-31 19:57
Seems to have cleared up, wonder if our instance just was not fully propagated out yet

**Comment by anselm-urban** [comment] 2016-09-07 10:27
I experience the same issue. Sometimes, icons aren't even loading!

**Comment by tagliala** [comment] 2016-09-07 15:03
Is there a way to replicate this issue?

**Comment by 91bananas** [comment] 2016-09-07 15:31
@tagliala for us it was just attempting to load the cdn url, it's been fine since that first day though

**Comment by tagliala** [comment] 2016-09-08 09:34
@talbs

**Comment by talbs** [comment] 2016-09-09 19:25
FYI, @robmadole. This may be more up your alley. Mind taking a look.

**Comment by robmadole** [comment] 2016-09-10 17:47
Hey, all. I'll look at this Monday morning and see what's going on. The stack trace might be enough for me to go on.

**Comment by robmadole** [comment] 2016-09-12 21:31
Got a fix for this now. It will be tomorrow before I get it deployed.

**Comment by robmadole** [comment] 2016-09-13 15:22
@hakuseki @dg-robinson @91bananas @anselm-urban I've put some fixes in for this that should prevent the uncaught exception. You'll need to edit and re-save your embed code so that the new changes can be pushed out to the CDN.

@91bananas icons not showing up is a separate issue from this. Can you reproduce this?

**Comment by hakuseki** [comment] 2016-09-14 07:31
Looks good!

**Comment by tagliala** [comment] 2016-09-14 09:56
Can I close this one?

**Comment by hakuseki** [comment] 2016-09-14 12:55
I can't answer for the other reporters but for me its fine to close.

**Comment by dg-robinson** [comment] 2016-09-14 13:00
It's not been happening for me since around 48 hours after signing up, so I can't confirm whether this is working.

@robmadole how do I edit and re-save my embed code? Do I just need to enter my email address at http://fontawesome.io/get-started/ again?

**Comment by robmadole** [comment] 2016-09-14 13:20
@dg-robinson you will have to register first. In the very first email you got after requesting an embed code there was a register link. Try https://cdn.fontawesome.com/forgot if you can't find that.

**Comment by JohnRoach** [comment] 2016-09-21 15:15
Awesome. So will be the fix be automagically in the JS code that got generated for us? or we will need to re-request https://use.fontawesome.com/...js file?

**Comment by 91bananas** [comment] 2016-09-21 15:18
I have a fairly reliable way of triggering this now, basically any page I request this on, if I put a debugger in that gets hit early before the promise resolves, let the debugger sit paused for a while, un-pause debugger. Generally every time I do this I will see the error occur. Noteworthy, we very rarely experience it under normal usage @robmadole

**Comment by tagliala** [comment] 2016-09-22 11:42
@JohnRoach you probably need to regenerate your code https://github.com/FortAwesome/Font-Awesome/issues/9837#issuecomment-246718159

**Comment by robmadole** [comment] 2016-09-22 12:49
@JohnRoach yes just like @tagliala mentioned you can generate a new code or you can update the existing one by registering for an account for cdn.fontawesome.com.

@91bananas thanks. That's the same technique I used to find the original. This should be fixed in any new embed code or embed codes that you update.

**Comment by tagliala** [comment] 2022-03-13 15:26
Closing here because of inactivity

If this is still an issue, feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

**Closed by tagliala** 2022-03-13 15:26 UTC
Labels: waiting for feedback, cdn
