### ISSUE TITLE
Icon Request: fa-export

### ISSUE THREAD

**Issue by jacobuid** [FortAwesome/Font-Awesome#10960] opened 2017-04-17 15:53 UTC
Have an icon that is an export file icon

**Comment by tagliala** [comment] 2017-04-17 17:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1020 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-17 17:17 UTC
