### ISSUE TITLE
Icon Request: fa-hexagon

### ISSUE THREAD

**Issue by ekkis** [FortAwesome/Font-Awesome#10776] opened 2017-03-11 13:40 UTC
I'd like to request a simple hexagon.  this could be used for chemistry or for any kind of component, since beehives are built of hexagons and it conveys the idea of a building block fairly well

**Comment by PeterShaggyNoble** [comment] 2017-03-13 10:16
Dupe of #1302.

**Closed** 2017-11-24 09:50 UTC
