### ISSUE TITLE
Icon request: icon-sleep

### ISSUE THREAD

**Issue by prowebuk** [FortAwesome/Font-Awesome#10174] opened 2016-11-05 06:31 UTC
Something like "Zzz" would be really useful thanks

**Comment by tagliala** [comment] 2016-11-05 14:45
Duplicate of #1627, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

I've also edited #1627's title to include zzz and sleep

Closing here

**Closed by tagliala** 2016-11-05 14:45 UTC
