### ISSUE TITLE
Icon request: rowing

### ISSUE THREAD

**Issue by annacushing** [FortAwesome/Font-Awesome#18583] opened 2022-01-13 21:02 UTC
**What can it be used for?**
I'm working on a project to show athletic programs at different high schools. An icon that represents rowing / crew would be super helpful! In the meantime I am using fa-water.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Rouseabouting** [comment] 2022-02-09 03:33
+1 - yes please, rowing related icons would be fantastic.

**Comment by aethior** [comment] 2022-04-02 15:06
*Related Unicode Emoji* #222
🚣 [U+1F6A3](https://emojipedia.org/emoji/%F0%9F%9A%A3/) Person Rowing Boat

**Comment by sensibleworld** [comment] 2024-07-11 15:14
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/18743)

**Closed as completed by sensibleworld** 2024-07-11 15:14 UTC
Labels: new icon, sport (category), Duplicate
