### ISSUE TITLE
Icon Request: icon-quizlet

### ISSUE THREAD

**Issue by tdchien88** [FortAwesome/Font-Awesome#9979] opened 2016-09-29 09:54 UTC
Hi!
Could you plz add icon of Quizlet. 

Thanks,

**Comment by tagliala** [comment] 2016-09-29 10:04
Duplicate of #8131, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-29 10:04 UTC
