### ISSUE TITLE
fa-warehouse

### ISSUE THREAD

**Issue by albertobelardi** [FortAwesome/Font-Awesome#11446] opened 2017-08-25 14:49 UTC

**Comment by tagliala** [comment] 2017-08-26 09:18
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4560 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-26 09:18 UTC
