### ISSUE TITLE
Icon-Request: icon-signup

### ISSUE THREAD

**Issue by tomprats** [FortAwesome/Font-Awesome#2103] opened 2013-10-04 22:47 UTC
There's already a icon-signin but in tons of places there's need for a signup and signin icon side-by-side.

What have other people been using for this?  I looked through and couldn't find any that made sense.

**Comment by davegandy** [comment] 2015-06-26 23:05
Going to reopen this one and put it in v5.0. I find myself wanting this one too.

**Comment by davegandy** [comment] 2015-06-26 23:09
Looks like this is a duplicate of #872. Closing here.

**Closed by davegandy** 2015-06-26 23:09 UTC
Labels: new icon
