### ISSUE TITLE
Icon Request: icon-playpause FA v5

### ISSUE THREAD

**Issue by aleki** [FortAwesome/Font-Awesome#11926] opened 2017-12-13 10:35 UTC
[Video player icons](https://fontawesome.com/icons?d=gallery&c=video-player-icons) category has [play icon](https://fontawesome.com/icons/play?style=solid) and [pause icon](https://fontawesome.com/icons/pause?style=solid), but not playpause icon.
I mean something like this:
![playpause](https://d30y9cdsu7xlg0.cloudfront.net/png/86425-200.png)

**Comment by tagliala** [comment] 2017-12-13 10:59
Hi!

Thanks for being part of the Font Awesome Community.

I should consider this a duplicate of #5065, because the title is quite the same.

Anyway, since the icon not the same, I would like to investigate this request a little bit.

Please check #5065, then please:
- clarify if this is different from #5065 and why and if #5065 is wrong
- provide a use case for this icon
- clarify why you can't use `fa-play` together with `fa-pause` to fit your use case
- clarify why you can't use custom css (webfont version: https://jsfiddle.net/tagliala/tgzouajm/6/ - svg version: https://jsfiddle.net/tagliala/f019sa7v/4/) to fit your use case

**Comment by aleki** [comment] 2017-12-13 13:08
@tagliala 

> clarify if this is different from #5065 and why and if #5065 is wrong
- #5065 created about 3 years ago;
- #5065 created not for v5;

> provide a use case for this icon

I don't know the state of the music (is playing or paused), so I need that icon.

> clarify why you can't use fa-play together with fa-pause to fit your use case

That icon is too wide.

**Comment by tagliala** [comment] 2017-12-13 14:59
Thanks.

> * #5065 created about 3 years ago;
* #5065 created not for v5;

All requests are still valid for FA5. If this request is a duplicate of #5065, we should use #5065

> I don't know the state of the music (is playing or paused), so I need that icon.

Could you please provide me a real world case that does this?

> clarify why you can't use fa-play together with fa-pause to fit your use case

The icon in your example is also too wide, I did the very same icon and it is going to be 2 times larger than play or pause. Otherwise, we should halve the height, but then it will be too small: https://jsfiddle.net/tagliala/tgzouajm/8/

**Comment by aleki** [comment] 2017-12-13 18:01
@tagliala

I agree that it is duplicate. 

I need this icon for my specific mobile application, cuz I don't know the state of playing music, so I can't use only `play` icon or only `pause`.  It is real case, I think.

I think icon can be not so wide, like [this](https://fontawesome.com/icons/step-forward?style=solid), but with two vertical lines.

**Comment by tagliala** [comment] 2017-12-13 19:28
@aleki thanks for the clarification

Please add a 👍  reaction to #5065, then post there an example

Closing here

**Closed by tagliala** 2017-12-13 19:28 UTC
Labels: waiting for feedback
