### ISSUE TITLE
Icon request: Codeacademy

### ISSUE THREAD

**Issue by timvlek** [FortAwesome/Font-Awesome#19241] opened 2022-08-05 11:24 UTC
https://www.iconfinder.com/icons/4691345/codecademy_icon

**Comment by tagliala** [comment] 2022-08-05 11:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3320, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-08-05 11:44 UTC
