### ISSUE TITLE
Icon request: user-key

### ISSUE THREAD

**Issue by renarena** [FortAwesome/Font-Awesome#16051] opened 2020-01-10 16:04 UTC
**What can it be used for?**
for user permissions (i dont like user-lock for this, it looks more like user is locked) 

**Example image (optional)**
combine the icons user and key like in user-clock / user-lock

**Comment by tagliala** [comment] 2020-01-10 16:41
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/302/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment] 2024-07-11 16:47
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/16199)

**Closed by sensibleworld** 2024-07-11 16:47 UTC
Labels: new icon, web application icons (legacy category), Duplicate
