### ISSUE TITLE
Icon request: materialize

### ISSUE THREAD

**Issue by JulianePires** [FortAwesome/Font-Awesome#17631] opened 2021-02-15 00:08 UTC
**What can it be used for?**
It could be used to specify the tecnologies presents on projects, blogs and portfolios.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/36718319/107893215-ab579f80-6f08-11eb-97ca-eae3ceab1fe1.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-04-11 03:39
Duplicate of #16680.

cc/ @tagliala

**Closed** 2022-04-11 10:23 UTC
