### ISSUE TITLE
Icon Request: fa-hadj

### ISSUE THREAD

**Issue by nihatokur** [FortAwesome/Font-Awesome#9370] opened 2016-06-08 08:35 UTC
Hi.
I need hadj icon (Kaaba) or muslim religion icon.
Thanx for help.

![stock-illustration-59992584-islamic-icon](https://cloud.githubusercontent.com/assets/19815529/15887829/045e1916-2d6d-11e6-855e-26b1465c5d5e.jpg)

**Comment by tagliala** [comment] 2016-06-08 12:08
Duplicate of #9315 , please take a look there

**Closed by tagliala** 2016-06-08 12:08 UTC
