### ISSUE TITLE
Icon request: sketchfab

### ISSUE THREAD

**Issue by ikapoura** [FortAwesome/Font-Awesome#13418] opened 2018-06-25 16:08 UTC
Sketchfab is turning to be a big player in the 3D modelling community and it would be nice if we could have an icon for it to go with the rest social media icons. 
The intended usage is to have an icon that redirects to our Sketchfab profile.

![Sketchfab original](https://pbs.twimg.com/profile_images/764190563679821824/uhR7l3c0.jpg)

**Comment by tagliala** [comment] 2018-06-25 17:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2757, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-25 17:22 UTC

**Comment by ikapoura** [comment] 2018-06-25 17:45
Thank you!
