### ISSUE TITLE
Icon Request: fa-netease

### ISSUE THREAD

**Issue by Dreamer-Paul** [FortAwesome/Font-Awesome#10638] opened 2017-02-08 07:36 UTC
Hello! I'm a middle school student from China with bad English...
I think "Netease music" is a great platform of discuss musics in China.
Can you add this icon to "FontAwesome" in new version?

![topbar](https://cloud.githubusercontent.com/assets/25198337/22727542/528a0290-ee14-11e6-8da6-7be2bc896dfe.jpg)

**Comment by tagliala** [comment] 2017-02-08 10:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8255, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-08 10:36 UTC
