### ISSUE TITLE
Icon request: search-people

### ISSUE THREAD

**Issue by lendrick** [FortAwesome/Font-Awesome#15775] opened 2019-11-05 19:38 UTC
**What can it be used for?**
Searching a user directory

**Example image (optional)**
A person with a magnifying glass

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-11-05 20:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15473, please add a 👍 reaction to that request.

You will also find there a solution to implement this icon right now

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-11-05 20:45 UTC
