### ISSUE TITLE
Icon request: icon-geolocation

### ISSUE THREAD

**Issue by johndubya** [FortAwesome/Font-Awesome#13026] opened 2018-05-03 17:47 UTC
### What can it be used for?

Used like with Google Maps, and when you click it, it uses GPS to show you your current position on the map.

### Example image

Example 1:
![Example geolocation icon](https://cloud.githubusercontent.com/assets/88540/4316574/79f39b38-3f08-11e4-87af-8daff3a17f84.png)

Example 2:
![Example geolocation icon 2](https://cloud.githubusercontent.com/assets/8761962/20485083/50c68d1e-affa-11e6-893d-69f7504b82dd.png)

Example 3:
![Example geolocation icon 3](https://cloud.githubusercontent.com/assets/661156/6020044/ffa8be9a-abb7-11e4-948d-a5feddebeeec.png)

### Additional notes
I'm not sure if my request is technically a duplicate or not. There is an old request that's been open since 2012, but it's not in the right "Icon request:" format, so I added this new one, in case the request must be in the right format. See https://github.com/FortAwesome/Font-Awesome/issues/560.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-05-03 18:39
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #560, please add a 👍  reaction to that request.

> I have searched for existing issues and to the best of my knowledge this is not a duplicate

No problem 👍 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-03 18:39 UTC

**Comment by tagliala** [comment] 2018-05-03 19:00
@johndubya sorry, I should have mentioned that old requests are not required to follow the new template because it wasn't available at the time
