### ISSUE TITLE
Icon request: open-book

### ISSUE THREAD

**Issue by RuthYMNg** [FortAwesome/Font-Awesome#11090] opened 2017-05-18 15:38 UTC
I think there's a gap in the market for an open book icon!
Use cases:
- Buttons where you can click to read more
- Academic links/material
- Personally I'll be using this to denote 'further study' as part of an application process for a course
For example
![book](https://cloud.githubusercontent.com/assets/22796164/26210693/5c3b46ba-3be8-11e7-9f8d-7d2a7796202f.jpeg)
Thank you - hope this helps..!

**Comment by tagliala** [comment] 2017-05-18 16:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #176 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-18 16:17 UTC
