### ISSUE TITLE
Icon Request: fa-vaccine

### ISSUE THREAD

**Issue by TejaManne** [FortAwesome/Font-Awesome#9821] opened 2016-08-26 15:36 UTC
Vaccine icon should be like injection (syringe). We are using font-awesome in all our projects and ours is health care based company. We are in need of vaccinations and immunizations icons. Please develop this icon asap because our we are going to move our project into production. Thanks in advance....

**Comment by tagliala** [comment] 2016-08-26 19:59
Duplicate of #1779 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-08-26 19:59 UTC
