### ISSUE TITLE
Icon request: Google Pay

### ISSUE THREAD

**Issue by Smexhy** [FortAwesome/Font-Awesome#16339] opened 2020-03-19 19:19 UTC
**What can it be used for?**
For the e-shops and ecommerce sites

**Example image (optional)**
https://lh3.googleusercontent.com/E7c0tXxOvvQDPlh9k4qe6Y5gxCc7qvSrap9C2vDKJ4L9SYDNseLmz5KhQ6uzTva3YO3cayGUhhlG_0Zf2Jh4e-Wz1FSqa_nC8MM2Lw

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-03-19 19:32
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12519, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-03-19 19:32 UTC
