### ISSUE TITLE
Icon request: icon-blogger

### ISSUE THREAD

**Issue by jmason1209** [FortAwesome/Font-Awesome#10412] opened 2016-12-21 18:53 UTC
Need the icon to link my blogger page to my personal website.

![image](https://cloud.githubusercontent.com/assets/8657133/21402048/c6fd8b58-c784-11e6-9bee-339f04488cb0.png)

**Comment by tagliala** [comment] 2016-12-22 00:39
Duplicate of #1088 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-22 00:39 UTC

**Comment by jmason1209** [comment] 2016-12-22 00:51
Sorry
