### ISSUE TITLE
icon request: e-commerce coupon/discount code

### ISSUE THREAD

**Issue by martinkearn** [FortAwesome/Font-Awesome#2760] opened 2014-01-19 17:11 UTC
I'd like to see an icon that represents a coupon or discount code in an eCommerce scenario.

Just a few examples:
![discount-512](https://f.cloud.github.com/assets/2410726/1949971/a8472e68-812c-11e3-878c-7a41fa94e431.png)
![capture](https://f.cloud.github.com/assets/2410726/1949973/a9efd4ae-812c-11e3-9762-9b85a82d2ba2.PNG)

:

**Comment by ntfox** [comment] 2015-05-09 03:13
+1

**Comment by forza020** [comment] 2015-05-17 16:33
+1

**Comment by mattybaer** [comment] 2015-07-03 19:17
I am using the http://fontawesome.io/icon/tag/ and http://fontawesome.io/icon/scissors/ to create a stacked icon that looks like this: http://jsfiddle.net/mattybaer/uj0zz59d/. It looks nice and I think it makes sense for discount. You're cutting tags!

**Comment by mewcrazy** [comment] 2015-11-02 00:15
awesome idea @mattybaer thanks ++

**Comment by potasiyam** [comment] 2016-05-29 07:41
+1 for the idea.
Temporarily I am using `fa-tag` and `fa-certificate` in a stack, looks something like this- http://codepen.io/potasiyam/pen/zBYEme

**Comment by sujjadyzi** [comment] 2016-11-05 05:54
+1
i used the `fa fa-tags` for showing in multiple context

**Comment by lmribeiro** [comment] 2017-09-20 13:58
+1

**Comment by FrancescoMussi** [comment] 2018-01-04 11:29
I was going to make the same request.
It would be a very needed icon.

3 years have passed since this request, any update on it?
Is it going to made in a future release?

**Comment by PetRockIt** [comment] 2019-01-31 07:51
I would also like to see an explicit icon for a coupon. For example:

https://www.flaticon.com/free-icon/coupon_287585

None of the suggestions so far represent a coupon the way coupons are used on so many sites. It is a shame this is missing.

**Comment by davequested** [comment] 2020-04-29 01:11
+1

**Comment by danielcongrove** [comment] 2020-07-31 13:57
+1

Looking for a coupon icon, with scissors or perforated lines.

**Comment by sensibleworld** [comment] 2024-07-11 13:56
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7330)

**Closed by sensibleworld** 2024-07-11 13:56 UTC
Labels: new icon, web application icons (legacy category), Duplicate
