### ISSUE TITLE
Icon request: symbol

### ISSUE THREAD

**Issue by GabiAxel** [FortAwesome/Font-Awesome#9289] opened 2016-05-27 21:36 UTC
For text editor "insert symbol" functionality. Omega should be standard.
![omega](https://cloud.githubusercontent.com/assets/968212/15621791/1d197cde-246c-11e6-8fd8-93a511b7e219.gif)

**Comment by tagliala** [comment] 2016-05-28 10:25
So let's call it for what it represents, `fa-omega`

Duplicate of #2923, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-28 10:25 UTC
