### ISSUE TITLE
Icon Request: fa-shopping-bag

### ISSUE THREAD

**Issue by andrea-86** [FortAwesome/Font-Awesome#7521] opened 2015-09-23 10:00 UTC

**Comment by tagliala** [comment] 2015-09-23 11:37
duplicate of #829 , scheduled for 5.0.0

closing here

**Closed by tagliala** 2015-09-23 11:37 UTC

**Comment by andrea-86** [comment] 2015-09-23 14:45
Thanks, and sorry for duplicated.

Andrea Nenci

2015-09-23 13:38 GMT+02:00 Geremia Taglialatela <notifications@github.com>:
