### ISSUE TITLE
Icon request: fa-hammer

### ISSUE THREAD

**Issue by kinganu** [FortAwesome/Font-Awesome#9433] opened 2016-06-21 08:58 UTC
Looking for something like a hammer to denote development or maintenance - building a website or project, or fixing something.  Legal gavel just wasnt cutting it.

http://thumb101.shutterstock.com/display_pic_with_logo/1816916/169645997/stock-vector-hammer-icons-set-isolated-vector-illustration-169645997.jpg

I think a square hammer like a maul is preferable, but a curved one is ok.

**Comment by tagliala** [comment] 2016-06-21 09:09
Duplicate of #1214, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-21 09:09 UTC
