### ISSUE TITLE
Icon Request: fa-beatport

### ISSUE THREAD

**Issue by jeffreyx185** [FortAwesome/Font-Awesome#9295] opened 2016-05-29 16:37 UTC
![34zd2rn](https://cloud.githubusercontent.com/assets/14817975/15634761/4fe22560-25cc-11e6-918d-fca15c54cb85.jpg)
![beatport_2-256](https://cloud.githubusercontent.com/assets/14817975/15634763/52ab8d72-25cc-11e6-9cd4-c191f2ed901d.png)

**Comment by tagliala** [comment] 2016-05-29 19:06
Duplicate of #2890 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-29 19:06 UTC
