### ISSUE TITLE
Icon Request: fa-rectangle

### ISSUE THREAD

**Issue by ardeva** [FortAwesome/Font-Awesome#8152] opened 2015-12-13 17:39 UTC
actually the square icon, but then as a rectangle.

My idea on using it is to stack is with a number to create a label. It should be great it could be with black number and with white number.. I tried to stretch the square icon, burt I can't seem to get number in there when I do that.

Thanks

![620](https://cloud.githubusercontent.com/assets/3111332/11768298/cc52e0f4-a1c8-11e5-85ac-d20bf90833d6.png)
![621](https://cloud.githubusercontent.com/assets/3111332/11768299/cc54400c-a1c8-11e5-9eb0-825560f4e876.png)

**Comment by tagliala** [comment] 2015-12-13 17:54
duplicate of #3639, please +1 that request

closing here

**Closed by tagliala** 2015-12-13 17:54 UTC
