### ISSUE TITLE
Icon request: icon-anon

### ISSUE THREAD

**Issue by skechboy** [FortAwesome/Font-Awesome#6725] opened 2015-06-11 11:12 UTC
Given the fact that privacy and anonymity are one of most popular topics on the net these days, it will be really nice if we as developers have such icons so we can use FA for such projects too. 

Example icon for: icon-anon: 

![image](https://cloud.githubusercontent.com/assets/399599/8105620/012f5c28-103b-11e5-8999-ed6dcfc34d35.png)

**Comment by tagliala** [comment] 2015-06-11 13:41
duplicate of #2578, please +1 that request

closing here

**Closed by tagliala** 2015-06-11 13:41 UTC
