### ISSUE TITLE
Icon request: passkey

### ISSUE THREAD

**Issue by ripla** [FortAwesome/Font-Awesome#19596] opened 2023-03-06 12:34 UTC
As passkeys (https://fidoalliance.org/, https://passkeys.dev/, https://developer.apple.com/passkeys/, https://developers.google.com/identity/passkeys) are gaining popularity, it would be nice to have an icon for passkey login. A fingerprint can be used, but as passkeys can also use facial recognition or other mechanisms, I think a more generic icon would be appropriate.

E.g. https://github.com/passkeydeveloper/passkeys.dev/blob/main/static/images/fido-passkey-black.svg

**Comment by tagliala** [comment] 2023-03-08 21:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19405, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-03-08 21:12 UTC
