### ISSUE TITLE
Please added partner icon

### ISSUE THREAD

**Issue by zaferlatif** [FortAwesome/Font-Awesome#9172] opened 2016-05-11 11:08 UTC
![partner-icon](https://cloud.githubusercontent.com/assets/16254470/15179081/55960aa6-1782-11e6-9d91-75d65439f3c4.png)

![values](https://cloud.githubusercontent.com/assets/16254470/15179089/61998f3a-1782-11e6-96b0-9fb4a2816263.png)

**Comment by tagliala** [comment] 2016-05-11 12:36
duplicate of #878, planned for 5.0.0 release

**Closed by tagliala** 2016-05-11 12:36 UTC

**Comment by Ronacs** [comment] 2018-03-26 08:48
May I know where can I find these logo for business partnership or someone like your service? Just like this one below.
![partners](https://user-images.githubusercontent.com/16950427/37896040-c389c43c-3097-11e8-93ba-f4da17c2c558.PNG)
