### ISSUE TITLE
Icon Request: Rock Climbing / Bouldering / Lead Climbing / Belaying

### ISSUE THREAD

**Issue by QuinnKWolter** [FortAwesome/Font-Awesome#18804] opened 2022-03-12 19:27 UTC
We've got luchador masks, it seems only fair we'd draft something up for this newly Olympicized sport.

**Comment by aethior** [comment] 2022-03-12 19:33
Hi @QuinnKWolter,

This request is duplicate of #13649.
Please 👍 that request.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-12 20:09
Reopening and renaming #13649 as rope climbing

**Comment by tagliala** [comment] 2022-03-12 20:10
Nope, sorry, I got confused. This is a duplicate of #13649

**Closed as completed by tagliala** 2022-03-12 20:10 UTC
Labels: new icon, sport (category)
