### ISSUE TITLE
Icon request: icon-name Tik-Tok

### ISSUE THREAD

**Issue by a96aorable** [FortAwesome/Font-Awesome#16752] opened 2020-05-31 17:51 UTC
**What can it be used for?**
This is social media platform icon, becoming very popular.

**Example image (optional)**
Search up TikTok for examples image(s)
**Icon request checklist**
- [YES ] This is a single icon or matched pair (Ex: `lock` / `unlock`) yes

- [YES ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)

- [YES ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate **YES**

- [NO ] I have included at least one example image if it could be helpful (optional)

**Comment by tagliala** [comment] 2020-05-31 18:49
Hi!

Thanks for being part of the Font Awesome Community.

Duplicate of #14340 .

No need to upvote #14340 , it will be released with the upcoming version of Font Awesome (no ETA, sorry)

**Closed by tagliala** 2020-05-31 18:49 UTC
