### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by imagedanceco** [FortAwesome/Font-Awesome#17532] opened 2021-01-06 13:22 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.  
this is a new icon to be utilized for social media links.  It is a new social media format. 

**Example image (optional)**
Insert the example image here if necessary.
https://www.google.com/search?q=parler+icon+image&rlz=1C1JZAP_enUS915US915&sxsrf=ALeKk0360HbpG8KxTrqPOzp666Yd3G03VA:1609939316940&tbm=isch&source=iu&ictx=1&fir=WuaOv122AUOJrM%252CgvbsXFUcswqJvM%252C_&vet=1&usg=AI4_-kQAndihhXbhzAidGET7jf_fiUniIA&sa=X&ved=2ahUKEwiL_eGos4fuAhVII6wKHSwxDwQQ9QF6BAgMEAE#imgrc=WuaOv122AUOJrM

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-01-06 13:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #16275, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-01-06 13:29 UTC
