### ISSUE TITLE
Icon request: fa-compass-drawing

### ISSUE THREAD

**Issue by veronicavg** [FortAwesome/Font-Awesome#10118] opened 2016-10-26 09:43 UTC
compass, not as a navigation device but as a device for drawing circles.
Example: The architect used a compass to draw a perfect circle.

![home-geometri-c_10](https://cloud.githubusercontent.com/assets/19815138/19721094/2208b990-9b71-11e6-80b1-8722332c60be.jpg)

**Comment by tagliala** [comment] 2016-10-26 10:14
Duplicate of #1378, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-26 10:14 UTC
