### ISSUE TITLE
Icon request: equal-housing-opportunity

### ISSUE THREAD

**Issue by mwhaling** [FortAwesome/Font-Awesome#17520] opened 2020-12-29 17:19 UTC
**What can it be used for?**
The Equal Housing Opportunity logo is used by real estate professionals to indicate that a house or apartment listing follows the applicable federal Fair Housing guidelines. This would be used on realtor and apartment websites, landing pages, and more.

**Example image (optional)**
Examples at [NAR.realtor](https://www.nar.realtor/logos-and-trademark-rules/equal-housing-opportunity-logo)
![equal-housing-opportunity-logo-1200w](https://user-images.githubusercontent.com/3207502/103301646-d117fc00-49cf-11eb-8419-ef01e07f83a5.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-12-29 19:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3574, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-12-29 19:52 UTC
