### ISSUE TITLE
Icon request: fa-weight-scale

### ISSUE THREAD

**Issue by fayazara** [FortAwesome/Font-Awesome#12288] opened 2018-02-08 08:35 UTC
**What can it be used for?**
There is a lack of icons for health/fitness related companies. We ask the users to enter their weight and height many times, Using seperate SVGs is making this a pain.

Example image (optional)
https://thenounproject.com/search/?q=weight%20scale&i=1359183

**Comment by tagliala** [comment] 2018-02-08 08:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7797, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-08 08:59 UTC
