### ISSUE TITLE
Icon-request: no-pets / no-dogs allowed

### ISSUE THREAD

**Issue by mForcella** [FortAwesome/Font-Awesome#16545] opened 2020-04-28 23:29 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
For displaying rules for a apartment/park/vehicle, etc

**Example image (optional)**
Insert the example image here if necessary.
Any of your current dog/pet icons with a slash through it. Something similar to fa-paw might be nice

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-07 19:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15087, please add a 👍 reaction to that request. You will also find an approach to implement this icon with the SVG framework

I can leave this open as pets-ban

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Comment by mForcella** [comment] 2020-05-07 20:48
Thanks! The SVG framework looks like it will accomplish what I want. However, I'm on Laravel and can't seem to find clear documentation on the packages I need to install. I have font-awesome-free and fontawesome-svg-core packages installed, but the SVG components don't seem to be functioning. Are there additional packages I need?

**Comment by tagliala** [comment] 2020-05-08 18:19
You're welcome!


> I have font-awesome-free and fontawesome-svg-core packages installed, but the SVG components don't seem to be functioning.

You don't need both packages.

I'm not a JavaScript developer, please forgive me if I do not use the proper terminology.

`@fortawesome/font-awesome-free` is an all-in-one package, with both css and svg framework JavaScript distributable files. In order to use the aforementioned features, you need the DVG JavaScript framework.

`@fortawesome/fontawesome-svg-core` is part of the dedicated node packages for the SVG framework, and it is not a standalone package. It is supposed to be used with font awesome icon packages like  `@fortawesome/free-solid-svg-icons`. You (probably) need an asset bundler, like webpack or rollup, and this apyou will be able to take advantage of tree-shaking feature and it is intended for advanced usage

Docs:
- https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
- https://fontawesome.com/how-to-use/javascript-api/setup/getting-started

**Closed** 2024-07-12 18:24 UTC
Labels: waiting for feedback
