### ISSUE TITLE
icon Request: icon users-tie

### ISSUE THREAD

**Issue by Lakshmanarao121777** [FortAwesome/Font-Awesome#14261] opened 2018-11-11 16:59 UTC

**Comment by tagliala** [comment] 2018-11-11 18:36
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fix this request by filling out our [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

**Comment by tagliala** [comment] 2022-03-19 15:04
duplicate of #9418

**Closed by tagliala** 2022-03-19 15:04 UTC
Labels: waiting for feedback
