### ISSUE TITLE
Icon request: icon-stitcher

### ISSUE THREAD

**Issue by lolepaille** [FortAwesome/Font-Awesome#16577] opened 2020-05-04 08:47 UTC
**What can it be used for?**
Stitcher is an easy way to listen to podcast. The icon will represent the company's logo and link to stitcher content. e.g podcasts. Similar icons are spotify and podcast

**Example image (optional)**
Insert the example image here if necessary.
http://www.empathymuseum.com/img/stitcher.png

**Icon request checklist**
- [ Single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-04 09:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3403, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-04 09:44 UTC
