### ISSUE TITLE
Icon Request: fa-coin

### ISSUE THREAD

**Issue by SkyBadPT** [FortAwesome/Font-Awesome#9089] opened 2016-04-30 13:19 UTC
I thing we should have this it's also good for many acasions like coin flip webpage and something like that 

![images](https://cloud.githubusercontent.com/assets/18751649/14936003/817dd4b6-0ede-11e6-9fa6-bfb01e04dde4.png)
![coin1](https://cloud.githubusercontent.com/assets/18751649/14936004/8841db8a-0ede-11e6-9891-e9c46ab1bf98.png)
![money_coin](https://cloud.githubusercontent.com/assets/18751649/14936005/8dc2ffb2-0ede-11e6-982a-1e2a1fad85c0.png)

**Comment by tagliala** [comment] 2016-04-30 16:25
Duplicate of #4350, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-30 16:25 UTC
