### ISSUE TITLE
Icon Request: fa-hanger

### ISSUE THREAD

**Issue by Pumizo** [FortAwesome/Font-Awesome#10675] opened 2017-02-17 12:27 UTC
Hi,

I would love to have a "hanger" icon on font awesome. It's commonly used in web shops, textile industry websites and in many other occasions.

Thanks in advance and keep up the excellent work!

Example image here: [https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Clothes_hanger_icon_3.svg/2000px-Clothes_hanger_icon_3.svg.png](url)

**Comment by tagliala** [comment] 2017-02-17 13:08
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1659, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-17 13:08 UTC
