### ISSUE TITLE
Icon Request: fa-ello

### ISSUE THREAD

**Issue by sandraslab** [FortAwesome/Font-Awesome#8970] opened 2016-04-13 09:38 UTC
Hello, 

I want to request a new icon for the social media network Ello to place it with the rest of the social media icons at the topbar, the sidebar and the footer  of our websites.

Here's the image:
![unnamed](https://cloud.githubusercontent.com/assets/18421462/14488947/fdd856e8-016a-11e6-8265-5f0d10976688.png)

Thank you so much in advance to attend my request.
I look forward to your response.

Have a wonderful day!
Sandra

**Comment by tagliala** [comment] 2016-04-13 09:45
Duplicate of #4208, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-13 09:45 UTC
