### ISSUE TITLE
Icon Request: fa-opentable

### ISSUE THREAD

**Issue by rachelpan525** [FortAwesome/Font-Awesome#9023] opened 2016-04-20 01:23 UTC
I'd like to request to have the OpenTable icon. I've been working on some restaurant projects and Yelp and OpenTable icon are necessary on websites. Hopefully, I could get the OpenTable icon soon.
Thanks!

**Comment by PeterShaggyNoble** [comment] 2016-04-20 06:09
Dupe of [#792](https://github.com/FortAwesome/Font-Awesome/issues/792). You should +1 that one instead.

**Closed** 2016-04-20 09:13 UTC
