### ISSUE TITLE
Font Awesome not rendering on IE11

### ISSUE THREAD

**Issue by ryan2** [FortAwesome/Font-Awesome#9674] opened 2016-07-28 18:26 UTC
I have had an issue with FA not rendering in IE11. It works when I run my own code from my local machine, or on my server side via localhost. If I connect to the server's address, the fonts all go away. After doing a lot of research, I also realized that Font Awesome's own website http://fontawesome.io/icons/ did not render any of the icons and so I'm beginning to think its an issue with my browser settings. Anybody come across an issue like this?

**Comment by tagliala** [comment] 2016-07-28 18:54
yes, somebody did but it probably depends on machine configuration

probably a duplicate of #8472 , covered in our Troubleshooting guide:  https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#fonts-not-rendering-properly-running-windows-10

**Closed by tagliala** 2016-07-28 18:54 UTC

**Comment by Stefhe68** [comment] 2017-07-12 13:40
I am Using IE 11.096 with secruity setting "Allow font downloads => Disabled". Now I can not see any Font Awesome Icon anymore and anywhere, not on my own webpage also not here e.g.: http://fontawesome.io/examples/
On my webpage all fonts are local and I think on fontawesome.io the fonts (icons) are local too. But they are not shown with IE11?! All other browsers works fine! Can you help me please to solve this IE11 issue? I tried many hours for nothing. Thank you.

**Comment by tagliala** [comment] 2017-07-12 16:14
@Stefhe68 : font awesome is a font. Please consider another solution if you need that security setting

Hope it helps
