### ISSUE TITLE
Icon request: multi-envelope multi-envelope-o

### ISSUE THREAD

**Issue by pk-fr** [FortAwesome/Font-Awesome#9246] opened 2016-05-20 13:11 UTC
like envelope but with a pack of envelopes ....
it  would be useful to have such  icons for "messages" and "unread messages" ....

**Comment by tagliala** [comment] 2016-05-20 14:03
Duplicate of #6767, please +1 that request

closing here

**Closed by tagliala** 2016-05-20 14:03 UTC
