### ISSUE TITLE
RFID Icon

### ISSUE THREAD

**Issue by marciodraw** [FortAwesome/Font-Awesome#17783] opened 2021-03-30 16:29 UTC
HI,

Have a provision to make an icon to rfID technology?

Thanks!

att
Marcio

**Comment by turbopixel** [comment] 2022-01-31 08:35
This icon would be great: https://github.com/FortAwesome/Font-Awesome/issues/6111#issuecomment-458273179 

Rel https://github.com/FortAwesome/Font-Awesome/issues/1695

**Comment by tagliala** [comment] 2022-01-31 09:14
@turbopixel thanks

Closing here as a duplicate of #6111 (please add a 👍🏼 reaction to that request)

**Closed by tagliala** 2022-01-31 09:14 UTC
