### ISSUE TITLE
Icon request: codeforces

### ISSUE THREAD

**Issue by proRamLOGO** [FortAwesome/Font-Awesome#16168] opened 2020-02-10 10:13 UTC
**What can it be used for?**
Just like we have social media icons of Facebook, Twitter, LinkedIn. We can even have icons for Codeforces which can be used to represent Competitive Programming Profiles of various programmers. We can further have icons for Codechef, TopCoder, Hackerrank, Hackerearth

**Example image **
[https://apprecs.org/gp/images/app-icons/300/0b/com.SoftTechs.CodeForces.jpg](url)

**Icon request checklist**
- [ ] This is a single icon.
- [ ] The title starts with "Icon request: " and is followed by the requested icon name 
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful 
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-02-10 12:24
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14584, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2020-02-10 12:24 UTC
