### ISSUE TITLE
Icon Request: fa-php

### ISSUE THREAD

**Issue by sanjeevk121** [FortAwesome/Font-Awesome#7751] opened 2015-10-24 06:42 UTC
Please add the icon for php, similar to this https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/PHP-logo.svg/2000px-PHP-logo.svg.png

**Comment by tagliala** [comment] 2015-10-24 15:56
duplicate of #1420  , please +1 that request

closing here

**Closed by tagliala** 2015-10-24 15:56 UTC
