### ISSUE TITLE
Icon request: Coins

### ISSUE THREAD

**Issue by JeroenCollier** [FortAwesome/Font-Awesome#8327] opened 2016-01-13 08:31 UTC
Please provide an icon for coins, small change. Now there are only credit cards and so included in FontAwesome. An icon with coins can be useful in information flyers, signage and so forth.

![schermafbeelding 2016-01-13 om 09 17 47](https://cloud.githubusercontent.com/assets/16594261/12288906/6a4e0492-b9d8-11e5-91b0-5f600f884999.png)
![schermafbeelding 2016-01-13 om 09 18 03](https://cloud.githubusercontent.com/assets/16594261/12288908/6b8e9d1c-b9d8-11e5-810d-87c52b5d2877.png)
![schermafbeelding 2016-01-13 om 09 18 24](https://cloud.githubusercontent.com/assets/16594261/12288909/6cdce476-b9d8-11e5-84e3-f43bb8e82b8e.png)

**Comment by aethior** [comment] 2016-01-13 11:24
Hi @JeroenCollier,

This suggestion is duplicate of #1400. Please +1 that.

Regards.

**Closed** 2016-01-13 13:56 UTC

**Comment by Patrick-W-McMahon** [comment] 2016-02-22 20:37
I would like to see two icons fa-coin-h and fa-coin-t for heads and tails.
