### ISSUE TITLE
Icon request: icon-busSeat.

### ISSUE THREAD

**Issue by pathmanabhankv** [FortAwesome/Font-Awesome#7346] opened 2015-08-31 09:44 UTC
hello team,

i requesting font for bus seat booking; font awesome really light weight so prefer to use only your icon. please kindly help me .
Thank advance

i attached sample image below ::
![available](https://cloud.githubusercontent.com/assets/13959013/9576505/d85386ee-4ff5-11e5-8d36-ffbb79290bf6.png)
![availableberth](https://cloud.githubusercontent.com/assets/13959013/9576506/d856593c-4ff5-11e5-91bf-2416d0ec079b.png)
![booked](https://cloud.githubusercontent.com/assets/13959013/9576507/d858566a-4ff5-11e5-926c-56c92f9a773a.png)
![bookedberth](https://cloud.githubusercontent.com/assets/13959013/9576508/d85b723c-4ff5-11e5-85ac-6118d910225a.png)
![selected](https://cloud.githubusercontent.com/assets/13959013/9576509/d87797c8-4ff5-11e5-9521-215d013b1ac2.png)
![selectedberth](https://cloud.githubusercontent.com/assets/13959013/9576510/d87c540c-4ff5-11e5-89ec-64f4360cc141.png)

**Comment by caduvieira** [comment] 2015-09-02 17:40
dupe of #2903

**Closed** 2015-09-14 06:21 UTC
