### ISSUE TITLE
Icon Request: fa-goodreads

### ISSUE THREAD

**Issue by OJFord** [FortAwesome/Font-Awesome#6875] opened 2015-07-05 03:13 UTC
Icon for [Goodreads](https://www.goodreads.com/), something like:

![lower-case 'g'](https://cdn4.iconfinder.com/data/icons/miu-black-social-2/60/goodreads-128.png)

Would be used in linking to profile on Goodreads.

**Comment by tagliala** [comment] 2015-07-05 10:24
duplicate of #1715 , please +1 that request

closing here

**Closed by tagliala** 2015-07-05 10:24 UTC

**Comment by OJFord** [comment] 2015-07-05 14:49
Whoops, sorry I searched for "fa-goodreads", and so missed the other one ("icon-goodreads").
