### ISSUE TITLE
Icon request: Ruler

### ISSUE THREAD

**Issue by braewood** [FortAwesome/Font-Awesome#6997] opened 2015-07-20 23:13 UTC
I would like a Ruler icon for a building/realestate website to indicate the size of a house

**Comment by MonkeyData** [comment] 2015-07-22 19:59
Ditto that.  I am trying to find items for a (street) mapping toolbar.  "fa-measure" would be nice

![image](https://cloud.githubusercontent.com/assets/3502679/8835802/af686a68-308a-11e5-8983-db170e2303c7.png)

**Comment by tuxy** [comment] 2015-07-23 00:02
+1 for fa-measure.

define: ruler; One, such as a monarch or dictator, that rules or governs.
Source: https://www.wordnik.com/words/ruler

**Comment by tagliala** [comment] 2015-07-23 10:08
duplicate of #1096 , please +1 that request

closing here

**Closed by tagliala** 2015-07-23 10:08 UTC

**Comment by tuxy** [comment] 2015-07-24 04:08
@tagliala, done. Thank You!
