### ISSUE TITLE
FA5: Webfont @Font-Face conflict problem

### ISSUE THREAD

**Issue by sebascomeau** [FortAwesome/Font-Awesome#11876] opened 2017-12-08 15:29 UTC
I try to upgrade my solution from 4.7 to 5 Free with WebFont method because we need to support IE9. I found that you css files have problems with @Font-Face for Regular and Solid.

Before my fix:
```css
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  src: url("../webfonts/fa-regular-400.eot");
  src: url("../webfonts/fa-regular-400.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-regular-400.woff2") format("woff2"), url("../webfonts/fa-regular-400.woff") format("woff"), url("../webfonts/fa-regular-400.ttf") format("truetype"), url("../webfonts/fa-regular-400.svg#fontawesome") format("svg"); }

.far {
  font-family: 'Font Awesome 5 Free';
  font-weight: 400; }
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 900;
  src: url("../webfonts/fa-solid-900.eot");
  src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"), url("../webfonts/fa-solid-900.woff") format("woff"), url("../webfonts/fa-solid-900.ttf") format("truetype"), url("../webfonts/fa-solid-900.svg#fontawesome") format("svg"); }

.fa,
.fas {
  font-family: 'Font Awesome 5 Free';
  font-weight: 900; }
```

After my fix:
```css
@font-face {
  font-family: 'Font Awesome 5 Regular';
  font-style: normal;
  font-weight: 400;
  src: url("../webfonts/fa-regular-400.eot");
  src: url("../webfonts/fa-regular-400.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-regular-400.woff2") format("woff2"), url("../webfonts/fa-regular-400.woff") format("woff"), url("../webfonts/fa-regular-400.ttf") format("truetype"), url("../webfonts/fa-regular-400.svg#fontawesome") format("svg"); }

.far {
  font-family: 'Font Awesome 5 Regular';
  font-weight: 400; }
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 900;
  src: url("../webfonts/fa-solid-900.eot");
  src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"), url("../webfonts/fa-solid-900.woff") format("woff"), url("../webfonts/fa-solid-900.ttf") format("truetype"), url("../webfonts/fa-solid-900.svg#fontawesome") format("svg"); }

.fa,
.fas {
  font-family: 'Font Awesome 5 Free';
  font-weight: 900; }
```

The Regular @Font-Face has the same name as the Solid and it cause problem.

**Comment by tagliala** [comment] 2017-12-08 16:38
I've also noticed this.

What is the actual issue you are experiencing? Could you please reproduce it on a fiddle?

**Comment by alecpl** [comment] 2017-12-08 19:37
That's the point, have the same name but different weight. What's the problem?

**Comment by sebascomeau** [comment] 2017-12-08 19:56
Only icons that is present in regular also is visible for free.

**Comment by sebascomeau** [comment] 2017-12-08 20:45
If I used fas fa-flag then the regular icon shows up. With fas fa-home nothing appear. Maybe its the minified version of all that caise that becaise I made a change in the non minified one and use this instead. I will get back at work mondau and check this futher. I understand what you mean with the font-weight and it should work.

**Comment by sebascomeau** [comment] 2017-12-08 20:57
Font-Family in minified is Font Awesome\ 5 Free instead of "Font Awesome 5 Free" like unminified. Dont know if this could cause such a bug in my case.

**Comment by tagliala** [comment] 2017-12-09 00:56
Hi, I'm still having troubles in understanding the issue

> If I used fas fa-flag then the regular icon shows up. With fas fa-home nothing appear

https://jsfiddle.net/tagliala/cq9rdny4/1/

This is using the minified version at https://use.fontawesome.com/releases/v5.0.0/css/all.css

**Comment by sebascomeau** [comment] 2017-12-09 01:08
Ok, I will try to reproduce the issue in my application. I use the bootstrap 3 template Metronic.

http://keenthemes.com/preview/metronic/theme/admin_1/dashboard_2.html

I will dig further to find the problem.

**Comment by ye21st** [comment] 2017-12-10 09:37
I reference all.js, but why it still shows no icon found

**Comment by tagliala** [comment] 2017-12-10 13:26
@ye21st please open a new issue explaining your problem

**Comment by tskipa** [comment] 2017-12-11 13:36
This is not a bug. If you do not set font-weight above 500, your custom css class will try to display regular font awesome icon.
https://jsfiddle.net/tskipa/6by3od7u/8/

**Comment by sebascomeau** [comment] 2017-12-11 13:51
I understand. To in my case I should put font-weight: 400!important for .far class and font-weigh: 900!important; for .fa and .fas.

**Comment by tagliala** [comment] 2018-03-05 14:30
I suppose it is solved.

Closing here

**Closed by tagliala** 2018-03-05 14:30 UTC
Labels: bug, css, waiting for feedback
