### ISSUE TITLE
Icon Request: fa-vaccine

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9987] opened 2016-09-29 18:14 UTC
![vaccine](https://cloud.githubusercontent.com/assets/539719/18966401/08a64ada-864f-11e6-8be5-dc7d1ce2703c.png)
Vaccine/Immunization icon to be used within a healthcare data app

**Comment by tagliala** [comment] 2016-09-30 09:09
Duplicate of #1779 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 09:09 UTC
