### ISSUE TITLE
Icon Request: fa-ebay and fa-alibaba

### ISSUE THREAD

**Issue by johnmadox** [FortAwesome/Font-Awesome#9429] opened 2016-06-20 22:46 UTC
Hi,
I need some icons of the following online selling and buying website: ebay and alibaba. I would appreciate it alot if these icons could get added on fontawesome.
Thank you very much
John

**Comment by aethior** [comment] 2016-06-20 23:37
Hi @johnmadox,

`fa-ebay`is duplicate of #1783 and `fa-alibaba`duplicate of #3855. Please :+1: these requests.

**Closed** 2016-06-21 08:16 UTC

**Comment by johnmadox** [comment] 2016-06-21 09:54
But sir, the icons are still not available? were can we find them on the site?

**Comment by aethior** [comment] 2016-06-21 13:52
Hi @johnmadox,

The icons aren't available. You have to :+1: the requests and maybe in the future will be available.
