### ISSUE TITLE
404 Error trying to access icons

### ISSUE THREAD

**Issue by mudsak** [FortAwesome/Font-Awesome#8302] opened 2016-01-08 23:16 UTC
page is throwing a 404 error if I attempt to view any icon on the fontawesome.io site. Error is as follows, and it appears for all icons. 

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus

**Comment by tagliala** [comment] 2016-01-08 23:54
Could you please post the steps to reproduce this issue?

**Comment by davemac** [comment] 2016-01-09 00:20
Same issue:

https://fortawesome.github.io/Font-Awesome/icons/
click any icon, for example, the 'commenting' icon
Links to https://fortawesome.github.io/Font-Awesome/icon/commenting, which gives a Github 404 page
Same as above when clicking any icon

**Comment by nruth** [comment] 2016-01-09 02:55
Same here, the docs page isn't showing the example snippets for each icons as it used to.

**Comment by gurisko** [comment] 2016-01-09 06:52
+1

**Comment by incace** [comment] 2016-01-09 07:22
Can confirm... individual icon pages down.

**Comment by jawittdesigns** [comment] 2016-01-09 08:27
That update to fort awesome push deleted all the icons pages.

**Comment by tagliala** [comment] 2016-01-09 11:15
Please use http://fontawesome.io/

**Comment by nruth** [comment] 2016-01-09 11:20
I get the same 404 error on fontawesome.io 
https://github.com/FortAwesome/Font-Awesome/commit/82aef1efcd55c12925eb65c0d332f31d723f6b45 looks like it deleted all the icon index.html files as @jawittdesigns said.

**Comment by tagliala** [comment] 2016-01-09 11:22
@nruth thanks, got it

**Comment by tagliala** [comment] 2016-01-09 13:47
Thanks for reporting this

Sorry if I didn't get the issue immediately :)

It should be fixed now

Closing here but feel free to comment if the issue is still present

**Closed by tagliala** 2016-01-09 13:47 UTC
Labels: bug, doc

**Comment by nruth** [comment] 2016-01-09 15:47
It's working now :+1: thanks!
