### ISSUE TITLE
Icon Request: codeigniter

### ISSUE THREAD

**Issue by hamafis** [FortAwesome/Font-Awesome#20278] opened 2024-07-08 10:03 UTC
### Checklist

- [ ] The title of this issue starts with "Icon Request: " and is followed by the new icon name *(ex. "Icon Request: Proton Torpedo")*
- [ ] This icon does not represent a brand
- [ ] This request is for a single icon or a matched pair *(ex. `lock` and `unlock`)*
- [ ] I've already [searched through existing issues](https://github.com/FortAwesome/Font-Awesome/issues), and to the best of my knowledge this request isn't a duplicate
- [ ] I understand [how new icon requests work](https://fontawesome.com/support#requesting-icons)

### Request type

✨ New icon

### Use case

hi, can you add new icon from freamwork codeigniter ?

### Visual example

you con look logo from website https://www.codeigniter.com/

**Comment by tagliala** [comment] 2024-07-10 07:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4316, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-07-10 07:12 UTC
Labels: new icon
