### ISSUE TITLE
Icon request: atmospheric-pressure

### ISSUE THREAD

**Issue by MarkLyck** [FortAwesome/Font-Awesome#19129] opened 2022-06-14 13:45 UTC
### Use case

This can be used for smart home, sensors and weather.

In my case I have air pressure sensors in my house I use in my smart home and I can't find a useful icon in font awesome for this.

But I imagine it would be used more often in weather applications.

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment] 2022-06-14 14:37
Hi!

Thanks for being part of the Font Awesome Community.

I think this is a duplicate of #16994, and probably an icon fitting the use case is already in Font Awesome

https://fontawesome.com/icons/gauge-high?s=solid

Could you please confirm or provide an example of the requested icon?

**Comment by sensibleworld** [comment] 2024-07-11 15:10
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed as not planned by sensibleworld** 2024-07-11 15:10 UTC
Labels: new icon, waiting for feedback, Declined
