### ISSUE TITLE
Icon request: BookBub

### ISSUE THREAD

**Issue by creativeblip** [FortAwesome/Font-Awesome#15930] opened 2019-12-11 22:02 UTC
**What can it be used for?**
BookBub ([https://www.bookbub.com](https://www.bookbub.com/) ) is a major promotional site for authors and many authors would want to link to their BookBub profile

**Example image (optional)**
[0200353B-A262-4418-8E30-AFF5162C0573](https://user-images.githubusercontent.com/13205259/70664015-6528f100-1c1e-11ea-89a0-0eb9f891c5c5.jpeg)

**Icon request checklist**
- [ X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X ] I have included at least one example image if it could be helpful (optional)
- [ X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-12-12 07:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9496, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-12-12 07:57 UTC
