### ISSUE TITLE
Icon Request : fa-preview

### ISSUE THREAD

**Issue by zendre4** [FortAwesome/Font-Awesome#7866] opened 2015-11-10 10:25 UTC
Text editor icon for preview like this :

![index](https://cloud.githubusercontent.com/assets/9673982/11059992/a1ec9390-879d-11e5-99eb-9784348b6fe0.jpg)

**Comment by tagliala** [comment] 2015-11-13 20:50
duplicate of #640, please +1 that request

closing here

**Closed by tagliala** 2015-11-13 20:50 UTC
