### ISSUE TITLE
Icon Request: fa-infinity

### ISSUE THREAD

**Issue by AnaPopa0** [FortAwesome/Font-Awesome#11119] opened 2017-05-28 12:08 UTC
Hi,
Could you please add the icon-infinity sign, I checked and there is not! 
![infinity_logo_300](https://cloud.githubusercontent.com/assets/26304227/26528581/88b863fc-43af-11e7-8911-5ce4df020e80.png)

Thank you!!

**Comment by tagliala** [comment] 2017-05-28 12:18
Hi!

Thanks for being part of the Font Awesome Community.

Is this a brand?

If yes, could you please provide more details? (website, etc.)

**Comment by AnaPopa0** [comment] 2017-05-28 20:43
No no, is not a brand :) I just copied from google, I just wanted to show what sign I mean etc,

It is just the icon :) usual infinity sign! 

Sorry for the confusion!

**Comment by tagliala** [comment] 2017-05-28 21:50
This request is a duplicate of #1647 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-28 21:50 UTC
Labels: waiting for feedback
