### ISSUE TITLE
[icon] Mixer

### ISSUE THREAD

**Issue by tremst** [FortAwesome/Font-Awesome#13409] opened 2018-06-24 16:26 UTC
Formerly known as BEAM, a streaming platform currently owned by microsoft.

website:
https://mixer.com

**Comment by tagliala** [comment] 2018-06-24 20:11
#
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11242, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-24 20:11 UTC
