### ISSUE TITLE
fa-xda

### ISSUE THREAD

**Issue by eagleeyetom** [FortAwesome/Font-Awesome#11059] opened 2017-05-14 17:25 UTC
Hi,
Could you please make an XDA icon? Would be very useful to link to the forum.

![image](https://cloud.githubusercontent.com/assets/1135618/26036288/0c2a8718-38db-11e7-96ca-1d080d0ada62.png)

Thank you!

**Comment by tagliala** [comment] 2017-05-14 17:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4114, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-14 17:56 UTC
