### ISSUE TITLE
Icon request: fa-stack-plus, fa-stack-times (used with fa-stack)

### ISSUE THREAD

**Issue by samotto** [FortAwesome/Font-Awesome#8179] opened 2015-12-18 21:17 UTC
It would be nice to make a fa-stack-plus and fa-stack-times (and minus and star?) that are not 'centered' but will be in the lower right of the icon. They would used to imply new/create or delete/remove.  Then those new icons can be used with any other icon using the fa-stack.   For example, it would be nice to have fa-file-plus or fa-file-times (create file and delete file); and there are many others where this would be useful.  You could then remove fa-user-plus and fa-user-times.

**Comment by tagliala** [comment] 2015-12-18 23:33
Closing here as a duplicate of #1181 . Please read the comment linked in the first post

**Closed by tagliala** 2015-12-18 23:33 UTC
