### ISSUE TITLE
blockchain

### ISSUE THREAD

**Issue by cheikh2017** [FortAwesome/Font-Awesome#12506] opened 2018-03-03 14:02 UTC

**Comment by tagliala** [comment] 2018-03-03 16:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11479, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-03 16:25 UTC
