### ISSUE TITLE
Icon request: icon-bridge

### ISSUE THREAD

**Issue by cmeassociates** [FortAwesome/Font-Awesome#6959] opened 2015-07-15 18:06 UTC
Could you please create a bridge icon. Thanks.

**Comment by TheChen5** [comment] 2015-07-15 22:29
+1
To be more specific:
fa-suspension-bridge
fa-arch-bridge
etc...

**Comment by tagliala** [comment] 2015-07-16 09:51
duplicate of #4053, please +1 that request

closing here

**Closed by tagliala** 2015-07-16 09:51 UTC
