### ISSUE TITLE
Icon request: phone-slash

### ISSUE THREAD

**Issue by thiebc92** [FortAwesome/Font-Awesome#11861] opened 2017-12-07 21:43 UTC
Hello, I would like to request that a new icon be made called phone-slash. It would effectively be a combination of the phone and microphone-slash icons. Use cases could be to mute a VOIP service, or (like in our case) to indicate that no phone number is available for a particular user. The two images I've attached are of the phone and microphone-slash icons, just to be clear about what I had in mind. 

Thanks!

![phone](https://user-images.githubusercontent.com/2627194/33740177-5e2750dc-db65-11e7-8d3c-71e9dd221fb7.png)
![microphone-slash](https://user-images.githubusercontent.com/2627194/33740169-589bf5be-db65-11e7-8023-4a15b886e30b.png)

**Comment by tagliala** [comment] 2017-12-07 23:42
Refers to #1181 

This should be possible with the new FA 5.0 SVG framework as soon a slash icon would be implemented #3691

**Comment by sensibleworld** [comment] 2018-03-15 18:15
![](https://github.trello.services/images/mini-trello-icon.png) [Chat icon category](https://trello.com/c/OCAVwJe3/33-chat-icon-category)

**Comment by sensibleworld** [comment] 2018-03-28 17:31
Released in 5.0.9

**Closed by sensibleworld** 2018-03-28 17:31 UTC
Labels: coming soon, new icon, web application icons

**Comment by tagliala** [comment] 2019-05-14 18:48
Duplicate of #2018
