### ISSUE TITLE
Icon request: icon-man-walking

### ISSUE THREAD

**Issue by robibi78** [FortAwesome/Font-Awesome#5632] opened 2015-02-10 16:19 UTC
Hello,
There are lots of transportation icons, but not a man walking... 

Thks for your job :)

**Comment by lenamtl** [comment] 2015-02-10 17:35
+1

**Comment by jmcopeland** [comment] 2015-02-18 07:55
+1

**Comment by tagliala** [comment] 2015-02-22 00:26
duplicate of #844 , please +1 that request

**Closed by tagliala** 2015-02-22 00:26 UTC
