### ISSUE TITLE
Icon Request: fa-tunein

### ISSUE THREAD

**Issue by gavin2812** [FortAwesome/Font-Awesome#10733] opened 2017-03-02 13:57 UTC
Hi Font Awesome guys!

Would it be possible to create an awesome icon for the brand TuneIn? They are huge now and I could really do with being able to use their icon on my project!

Pretty please?

Thank you!!

Icon here : http://d11im0xz45jykv.cloudfront.net/marketing/images/press/TuneIn_Logo_2000px.png

TuneIn website here : http://www.tunein.com

**Comment by tagliala** [comment] 2017-03-02 22:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3159, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-02 22:53 UTC
