### ISSUE TITLE
Icon Request: fa-rule

### ISSUE THREAD

**Issue by DarkReivin** [FortAwesome/Font-Awesome#10404] opened 2016-12-20 21:28 UTC
A regular rule (or any measuring tool). Thanks!.

**Comment by Crissov** [comment] 2016-12-21 10:12
Related Unicode emojis: #222

- [📏 U+1F4CF](http://emojipedia.org/straight-ruler/)
- [📐 U+1F4D0](http://emojipedia.org/triangular-ruler/)

**Comment by tagliala** [comment] 2016-12-21 12:37
Duplicate of #1096 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-21 12:37 UTC
