### ISSUE TITLE
Icon Request: fa-teamviewer, fa-teamviewer-o

### ISSUE THREAD

**Issue by atillabyte** [FortAwesome/Font-Awesome#10718] opened 2017-02-28 16:57 UTC
[TeamViewer](https://en.wikipedia.org/wiki/TeamViewer) is a proprietary computer software package for remote control, desktop sharing, online meetings, web conferencing and file transfer between computers.

I've found these appropriate icons, whose licenses would allow for commercial/non-commercial redistribution. [**#1**](https://www.iconfinder.com/icons/1915987/logo_media_social_teamviewer_icon#size=128l) [**#2**](https://www.iconfinder.com/icons/1907093/logo_media_social_teamviewer_icon#size=128)

![Teamviewer](https://atil.la/x/img/dboperizPX.svg)
![TeamViewer](https://atil.la/x/img/XqGFImxjoh.svg)

**Comment by tagliala** [comment] 2017-02-28 17:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5383, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Please note that brand logos are implemented as they are without any modification

Closing here

**Closed by tagliala** 2017-02-28 17:46 UTC
