### ISSUE TITLE
Icon Request: fa-kindle fa-kobo fa-ibooks fa-playbooks fa-knook ...

### ISSUE THREAD

**Issue by fabiograsso** [FortAwesome/Font-Awesome#7095] opened 2015-07-30 17:28 UTC
Will be useful icons with logos of major ebook stores: Kindle, Kobo, Apple iBooks, Google PlayBooks, B&N Knook

Thanks
Fabio

**Comment by tagliala** [comment] 2015-07-30 18:38
Duplicate of #2356, please +1 that request

Closing here

**Closed by tagliala** 2015-07-30 18:38 UTC
