### ISSUE TITLE
Icon Request: fa-odnoklassniki

### ISSUE THREAD

**Issue by ShamanFromSiberia** [FortAwesome/Font-Awesome#6846] opened 2015-06-30 11:54 UTC
First of all, thank you for all the icons.
But I highly request to add Odnoklassniki logo. Odnoklassniki is a popular network (over 40,000.000 hits a day) on territory of East Europe, and social icon of this network would be very useful in many web projects. Official logotype could be seen here: http://v.ok.ru/logo.html
It looks like a word "OK" in vertical position, stylized in a human.

Thank you in advance.

**Comment by tagliala** [comment] 2015-06-30 18:31
duplicate of #1685 , please +1 that request

closing here

**Closed by tagliala** 2015-06-30 18:31 UTC
