### ISSUE TITLE
Copyleft icon

### ISSUE THREAD

**Issue by CousCousPlayer** [FortAwesome/Font-Awesome#8522] opened 2016-02-10 13:30 UTC
Hello People from Font-Awesome!
It would be nice if you make additionally to the copyright icon an copyleft icon
https://en.wikipedia.org/wiki/File:Copyleft.svg
Thank You!

**Comment by tagliala** [comment] 2016-02-10 14:00
duplicate of #2934, please +1 that request

closing here

**Closed by tagliala** 2016-02-10 14:00 UTC
