### ISSUE TITLE
Calendar icon for number of days to show

### ISSUE THREAD

**Issue by ThinkCreateAct** [FortAwesome/Font-Awesome#9570] opened 2016-07-14 08:07 UTC
It would be nice to have a icon set for the number of days to show - like outlook:

one day
week 5 days
week 7 days
month

![calendar view](https://cloud.githubusercontent.com/assets/20428197/16832486/b50076f2-49aa-11e6-9eee-6736ddb87a00.PNG)

**Comment by ThinkCreateAct** [comment] 2016-07-14 09:21
Should be easy to draw:
fa-calendar-o and the number of days (1, 5, 7, 31)
![cal5](https://cloud.githubusercontent.com/assets/20428197/16834643/13f7289a-49b5-11e6-8901-0d0e45a04a3a.PNG)

**Comment by tagliala** [comment] 2016-07-14 09:27
Duplicate of #3609 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

If you need to stack numbers over icons, please take a look here: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Closing here

**Closed by tagliala** 2016-07-14 09:27 UTC
