### ISSUE TITLE
Icon Request: fa-wine

### ISSUE THREAD

**Issue by santinoalbert** [FortAwesome/Font-Awesome#7492] opened 2015-09-19 10:24 UTC
It would be useful for websites or online marketing related with wine, for graphic design in the wine sector, etc.
![wine-glass-symbol](https://cloud.githubusercontent.com/assets/14359200/9975786/63a50cea-5ec9-11e5-9709-e5b208125f52.jpg)

Thanks.

**Comment by tagliala** [comment] 2015-09-19 11:17
duplicate of #370, please +1 that request

closing here

**Closed by tagliala** 2015-09-19 11:17 UTC

**Comment by santinoalbert** [comment] 2015-09-19 13:31
+1


Thanks!
