### ISSUE TITLE
Icon Request: apple-fruit

### ISSUE THREAD

**Issue by jrowellfx** [FortAwesome/Font-Awesome#10533] opened 2017-01-18 17:41 UTC
I need a symbol for an apple in a latex document I am writing, the only apple icon I could find was here in fontawesome, which is indeed awesome, however, it's the apple logo for the company. I'm using it for now, the document is private so for now it doesn't matter that it's the company logo.

I was thinking that a general (and small) set of fruit icons might be useful.  If you go onto google docs, on windows and insert the symbol for "apple" (it's missing on linux, and shaded/colored on the mac! - totally inconsistent across platforms, so you need to see it on a PC - oh well) you can see the kind of icon that might be useful.

In addition, it might also be useful to have a couple of other really typical fruit items.  Like banana-fruit, cherry-fruit, pineapple-fruit - as in the kind of things you might see on a slot-machine?

Anyway, thanks so much - just throwing this out there for your consideration.  Thanks again!

**Comment by tagliala** [comment] 2017-01-18 18:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2979, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-18 18:15 UTC

**Comment by jrowellfx** [comment] 2017-01-18 20:22
Oops - apologies.  I'll add a comment/thumbs-up to the other request.
