### ISSUE TITLE
Icon Request: fa-island

### ISSUE THREAD

**Issue by mawz2042** [FortAwesome/Font-Awesome#10392] opened 2016-12-18 07:51 UTC
I was thinking something like one of these.

![island 1](https://cloud.githubusercontent.com/assets/5165168/21292263/89ee259e-c520-11e6-9d4e-d0512c844667.PNG)
![island 2](https://cloud.githubusercontent.com/assets/5165168/21292264/89f1125e-c520-11e6-8468-45beca662448.PNG)

**Comment by Crissov** [comment] 2016-12-21 10:08
Related Unicode emojis: #222

- **[🏝 U+1F3DD](http://emojipedia.org/desert-island/)**
- [🏖 U+1F3D6](http://emojipedia.org/beach-with-umbrella/)
- [🌴 U+1F334](http://emojipedia.org/palm-tree/)

**Comment by caduvieira** [comment] 2017-01-13 11:29
Dupe of #3786

Please react to that one and add your comments there

**Closed** 2017-01-13 13:44 UTC
