### ISSUE TITLE
Icon Request: fa-home-advisor

### ISSUE THREAD

**Issue by tp546** [FortAwesome/Font-Awesome#10528] opened 2017-01-17 02:33 UTC
Could you create an icon for Home Advisor so I can use it to link to my company page there from my website?

Here is an example image:
http://kineticgroupconsulting.com/kgc/wp-content/uploads/2015/08/HomeAdvisor-Logo-440x340.png

Thanks!

**Comment by tagliala** [comment] 2017-01-17 12:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6715, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-17 12:59 UTC
