### ISSUE TITLE
Icon request: icon-kickstarter

### ISSUE THREAD

**Issue by offdutyninja** [FortAwesome/Font-Awesome#11497] opened 2017-09-07 12:20 UTC
Many board game companies use Kickstarter. We consider it one of our networks and want people to follow us. Having this icon would be beneficial to us in many places on our site - and our theme uses your icon set.  I have attached the Brand Assets directly from the Kickstarter site. As well as just the icon I think is best for icon creation. 

Thank you for the consideration.

![kickstarter-logo-k-grey](https://user-images.githubusercontent.com/9140768/30163023-2111db66-938c-11e7-9bbc-a86e6b9feced.png)

[KickstarterBrandAssets.zip](https://github.com/FortAwesome/Font-Awesome/files/1284593/KickstarterBrandAssets.zip)

**Comment by tagliala** [comment] 2017-09-07 12:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2237 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-07 12:53 UTC
