### ISSUE TITLE
Icon Request: fa-wifi1, fa-wifi2, fa-wifi3...

### ISSUE THREAD

**Issue by williampayne23** [FortAwesome/Font-Awesome#8930] opened 2016-04-09 15:52 UTC
This could be used to show varied wifi strength similarly to the variable battery icons.

**Comment by aethior** [comment] 2016-04-10 01:30
Hi @williampayne23,

This request is duplicate of #7856. Please +1 that.

**Closed** 2016-04-10 08:38 UTC
