### ISSUE TITLE
Icon request: icon-bandcamp

### ISSUE THREAD

**Issue by nathansh** [FortAwesome/Font-Awesome#10041] opened 2016-10-09 18:52 UTC
It would be really helpful to have an icon for the music store/service Bandcamp. We have icons for Spotify and Apple (useful for Apple Music), but Bandcamp is missing. Bandcamp is one of the largest stores geared towards independent artists and labels.

The use case I've run into a few times is in an album detail view for an artist or record label. I can use Font Awesome for the Spotify, Apple Music, and SoundCloud links, but need a custom icon for Bandcamp.

![bandcamp-button-bc-circle-black-512](https://cloud.githubusercontent.com/assets/894613/19222829/54de7bce-8e16-11e6-8248-c678e32a6076.png)

**Comment by tagliala** [comment] 2016-10-09 19:42
Duplicate of  #1725 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-09 19:42 UTC
