### ISSUE TITLE
Icon Request: fa-sofort

### ISSUE THREAD

**Issue by seb-lpx** [FortAwesome/Font-Awesome#9487] opened 2016-06-28 09:34 UTC
Please create a new icon for the popular payment method sofortüberweisung.
https://www.sofort.com/eng-DE/kaeufer/su/online-zahlen-mit-sofort-ueberweisung/

![sofort-ueberweisung_productnavigation](https://cloud.githubusercontent.com/assets/20184044/16410738/370e1c8c-3d24-11e6-8e56-667f95b2c05d.png)

Thanx!

**Comment by seb-lpx** [comment] 2016-06-28 10:08
![sofort](https://cloud.githubusercontent.com/assets/20184044/16411762/02716e0c-3d29-11e6-850d-f8e8c7c16a52.png)

**Comment by JakeKydd** [comment] 2017-08-19 05:16
Any news on this?

**Comment by WEBixx** [comment] 2018-03-25 11:28
+1

**Comment by krsriq** [comment] 2018-06-18 19:21
+1

**Comment by Chriz74** [comment] 2019-03-13 13:27
+1

**Comment by KaiSchniggendiller** [comment] 2019-03-25 14:03
+1

**Comment by flohaun** [comment] 2019-05-05 15:14
+1

**Comment by tagliala** [comment] 2020-05-01 11:29
Ops... this is a duplicate of #4342 and I didn't notice

Please +1 that request, closing here

**Closed by tagliala** 2020-05-01 11:29 UTC
Labels: brand icon, payment (category)
