### ISSUE TITLE
Icon request: virtualization

### ISSUE THREAD

**Issue by fusion809** [FortAwesome/Font-Awesome#12394] opened 2018-02-20 04:31 UTC
### What can it be used for?
To represent virtual machines and the various virtualization applications like:
* KVM/QEMU
* VirtualBox
* VMWare

I am terrible at creating icons, or any form of art, so I'm afraid I do not have an icon for this. 

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Thanks for your time,
Brenton

**Comment by tagliala** [comment] 2018-02-20 11:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5134, please add a 👍  reaction to that request.

Since you have searched for duplicates, if this is not a duplicate please clarify your request

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-20 11:19 UTC
