### ISSUE TITLE
Icon request: fa-current-location

### ISSUE THREAD

**Issue by wencywww** [FortAwesome/Font-Awesome#10254] opened 2016-11-21 12:11 UTC
Useful icon for many cases when current user locations should be retrieved. Used in Google Maps, for example

![image](https://cloud.githubusercontent.com/assets/4987356/20482203/0f515c52-aff4-11e6-9f5b-442bd3e2d07b.png)

**Comment by tagliala** [comment] 2016-11-21 14:14
Duplicate of #10082 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-21 14:14 UTC

**Comment by avdept** [comment] 2017-04-04 09:40
@tagliala Sorry, but either link to issue is wrong, or you understood this request wrong.

**Comment by tagliala** [comment] 2017-04-04 10:24
@avdept sorry and thanks for reporting this

The duplicate issue is #560
