### ISSUE TITLE
Icon request: distance

### ISSUE THREAD

**Issue by mdomnita** [FortAwesome/Font-Awesome#11315] opened 2017-07-21 09:21 UTC
I would like an icon to represent distance between two points. 
Something like https://www.onlinewebfonts.com/icon/466583
or https://www.onlinewebfonts.com/icon/252520

**Comment by tagliala** [comment] 2017-07-21 09:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #933, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-21 09:49 UTC
