### ISSUE TITLE
Icon Request: fa-china-unionpay

### ISSUE THREAD

**Issue by arwcheek** [FortAwesome/Font-Awesome#10698] opened 2017-02-23 20:03 UTC
To compliment the Amex, Visa, MC, Discover, and other brand-name payment logos. Seen more frequently in the US and continuing to grow...

From Wikipedia: "UnionPay cards can be used in 141 countries and regions around the world, making it the third-largest payment network by value of transactions processed, behind Visa and MasterCard. Some UnionPay credit cards are also affiliated with American Express, MasterCard or Visa, and they can be used abroad as an American Express, MasterCard or Visa. UnionPay debit cards, however, can only be used in the UnionPay network and other networks that have signed contracts with UnionPay. Since 2006, China UnionPay cards can be used in over 100 countries outside China."

Logo: https://www.google.com/search?q=china+union+pay+logo&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiu3vuVgafSAhWU8oMKHeg7CjoQ_AUICCgB&biw=1634&bih=943

**Comment by tagliala** [comment] 2017-02-23 20:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4561, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-23 20:42 UTC
