### ISSUE TITLE
简书以及B站的图标

### ISSUE THREAD

**Issue by Tademzysy** [FortAwesome/Font-Awesome#14983] opened 2019-05-04 17:49 UTC

**Comment by tagliala** [comment] 2019-05-04 21:40
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I do not speak Chinese. As per google translate, your request means "Short book and icon of station B"

It is still not clear for me. 

Could you please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

**Comment by wolfan** [comment] 2019-05-05 16:02
@tagliala he hopes [bilibili](https://bilibili.com) and [简书](https://jianshu.io/) (a blog similar), but i think bilibili ok 简书 not.

also add [微信支付](https://cn.bing.com/images/search?q=%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98&FORM=HDRSC2) icon ?

**Comment by tagliala** [comment] 2019-05-05 16:15
@wolfan thanks for the clarification.

bilibili is a duplicate of #9789 
jiaunshu is a duplicate of #5999 

If you giv me the chinese representation of the above brand, I can add them to the title

ex:

bilibili: ...
jiaunshu: 简书


> also add 微信支付 icon ?

Is there any English transliteration available for this brand? Maybe this is a duplicate of #11284?

**Comment by wolfan** [comment] 2019-05-05 16:25
@tagliala sorry, emmmmm……  

i think 微信支付 = WeChat Pay ✔

sorry i trying english...

**Comment by tagliala** [comment] 2021-09-30 12:01
Closing here, feel free to open a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Closed by tagliala** 2021-09-30 12:01 UTC
