### ISSUE TITLE
Icon request: icon-sail-boat

### ISSUE THREAD

**Issue by steveneal** [FortAwesome/Font-Awesome#14451] opened 2018-12-29 11:07 UTC
This could be used for any sailing related sport or activity.

![sailboat](https://user-images.githubusercontent.com/342829/50537583-1a1ee680-0b51-11e9-982c-fa6bc44006f7.png)

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

I have searched for existing issues and  I can see there have been other requests for a similar icon. However, these haven't been updated for years so I'm opening a new issue.

Many thanks for a great project!

**Comment by tagliala** [comment] 2018-12-29 11:34
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5079, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-12-29 11:34 UTC
