### ISSUE TITLE
Latest release icons bug on desktop

### ISSUE THREAD

**Issue by dillon-pinto** [FortAwesome/Font-Awesome#16804] opened 2020-06-17 18:48 UTC
Latest release icons (5.13.0) of the Coronavirus set are not showing up when copied into Adobe Illustrator or InDesign. I'm on the Pro version of font awesome and have downloaded the newest version 5.13.0 for desktop. Seems like the same issue as #16366, people-arrows doesn't work for me either. I've uninstalled and reinstalled the fonts but it still produces the same issue.

**To Reproduce**
Copy the icon from the website, paste it into an Illustrator/InDesign textbox. Change the font to Font Awesome and it shows up as a rectangle or with UTF-8 characters.

**Expected behavior**
Should show the icon in the Illustrator/InDesign textbox when pasted.

**Version and implementation**
Version: Font Awesome 5.13.0
Adobe InDesign 2020, version 24.2 macOS
Adobe Ilustrator 2020, version 15.1 macOS

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case 
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate that has been answered

**Comment by tagliala** [comment] 2020-06-17 19:55
Hi!

Thanks for being part of the Font Awesome Community.

Windows or Mac?

**Comment by dillon-pinto** [comment] 2020-06-17 20:12
Mac, sorry I forgot to mention that!

**Comment by tagliala** [comment] 2020-06-17 21:13
Hi, Maybe there are some caching issues.

> I've uninstalled and reinstalled the fonts but it still produces the same issue.

How did you do that? I would suggest:

1. Uninstall the font
2. Restart the machine (yes, sorry) 
3. Open the program, make sure the font is not found
4. Close the program
5. Install the font
6. Check on FontBook that it is 5.13.0 in both version AND unique font name
6. Try again in your application

I've experienced the same with Pages. We are planning a little change that should improve desktop caching issues

**Comment by calpoly-richardrobinson** [comment] 2020-06-24 20:48
I've tried the [steps above](#issuecomment-645627910) and I'm still having the same issue. All of the icons are working except the new virus pack. I get a Chinese character instead, and the font in Illustrator changes from Font Awesome 5 Pro to a random Chinese font family

**Comment by tagliala** [comment] 2020-06-25 09:20
@calpoly-richardrobinson sorry that didn't help

Let's ask @sensibleworld if he has some suggestions, I do not use Illustrator

I've find more complicated steps here, but I won't recommend that if you are not sure of the effects of the steps provided: https://helpx.adobe.com/x-productkb/global/troubleshoot-fonts-mac-os-x.html

**Comment by calpoly-richardrobinson** [comment] 2020-06-25 18:17
I think I found the issue. It appears that Font Awesome is conflicting with a system font that's installed on OSX by default. For my case, it's AppleMyungjo.

Right clicking on the icons in Chrome will show a menu with the icon/glyph. When you copy and paste them into Illustrator and use the Font Awesome 5 Pro font, they should appear. Here are 4 different screenshots from the Pro Cheeatsheat (https://fontawesome.com/cheatsheet/pro):

fa-badge-sheriff
https://www.dropbox.com/s/hwwdexfn6ik8je9/fa-rightclick-sheriff.png?dl=0
This appears in the menu as it's shown on the page, and works when pasting in illustrator

fa-cannabis
https://www.dropbox.com/s/y5kdgrkaz4bfuj3/fa-rightclick-cannabis.png?dl=0
This appears in the menu as a mystery box with a question mark, but copying and pasting into illustrator works and it is dank

Virus glyphs
https://www.dropbox.com/s/ipm6obz9w8zhztv/fa-rightclick-virus.png?dl=0
https://www.dropbox.com/s/goqgbpiggsfctwn/fa-rightclick-virus-2.png?dl=0

These two appear in the menu as different Chinese characters. Pasting them into Illustrator results in their Chinese characters displaying, and the font in Illustrator switches to a Chinese font:

https://www.dropbox.com/s/i93o2xsy1wk3jhm/illustrator-chinese-font.png?dl=0

https://www.dropbox.com/s/ipm6obz9w8zhztv/fa-rightclick-virus.png?dl=0

Using the inspector in Chrome, I disabled the font stacks used in the Font Awesome CSS and it falls back to the system font, AppleMyungjo:
https://www.dropbox.com/s/wvtibnw3020gql8/Screenshot%202020-06-25%2010.38.21.png?dl=0

So it doesn't seem to be a caching issue, but instead a conflict with a system font (that can't be uninstalled easily).

Thoughts?

**Comment by tagliala** [comment] 2020-06-25 22:21
Hi,

Sorry but I cannot help.

> fa-badge-sheriff
> https://www.dropbox.com/s/hwwdexfn6ik8je9/fa-rightclick-sheriff.png?dl=0
> This appears in the menu as it's shown on the page, and works when pasting in illustrator

This should not happen. All icons should have seen as a question mark inside a square or the chinese character. I cannot replicate this, I correctly see a question mark.

No icons there should be visible: font awesome is a webfont using the Private Unicode Area, and the operating system's context menu should not be able to show any of the font awesome icons.

About Illustrator, I can't help. Please also send an email to hello@fontawesome.com, with an URL to this discussion

**Comment by amiremami** [comment] 2020-06-26 10:17
Hi. I'm not sure if I need to open separate ticket or not, but I have same issue. On windows 10, microsoft office word, some of the brands are shown as Chinese characters. For example:

https://i.imgur.com/hgIKZhD.png

So, I just copied icons from here:
https://fontawesome.com/cheatsheet/free/brands

Pasted in to word, and then selected all and chose font awesome brands icon font family, but some of them are not shown correctly.

**Comment by calpoly-richardrobinson** [comment] 2020-06-26 20:34
@amiremami I looked at your screenshots and compared the google-pay and instagram-square icons. I'm on OSX using FA 5.13. Those two are also showing Chinese characters for me, and they're very similar to yours.

**Comment by tagliala** [comment] 2020-06-26 21:09
Well, thank you both. I had time to take a deeper look at this

@amiremami I can confirm this issue

@robmadole we have a problem.

Some unicode points in the PUA used by Font Awesome are being used also by some CJK chars. Actually, F9xx and FAxx codes are taken by other chars.

Eg: instagram-square => https://www.compart.com/en/unicode/U+F955

This is causing issues for some applications under some circumstances.

I can reproduce this in Word on Windows, (but not on Photoshop). I've tried almost everything to clean up the cache, I think this is not a cache problem

At the moment I can confirm this is an issue for the following brand icons:

- [ ] dailymotion (f952)
- [ ] deezer (f977)
- [ ] edge-legacy (f978)
- [ ] firefox-browser (f907)
- [ ] google-pay (f979)
- [ ] ideal (f913)
- [ ] instagram-square (f955)
- [ ] microblog (f91a)
- [ ] mixed (f956)
- [ ] pied-piper-square (f91e)
- [ ] rust (f97a)
- [ ] shopify (f957)
- [ ] tiktok (f97b)
- [ ] unity (f949)
- [ ] unsplash (f97c)

I will download the Unicode DB and create a script to check other unicode points.

**Comment by calpoly-richardrobinson** [comment] 2020-06-26 21:12
> Well, thank you both. I had time to take a deeper look at this
> 
> @amiremami I can confirm this issue
> 
> @robmadole we have a problem.
> 
> Some unicode points in the PUA used by Font Awesome are being used also by some CJK chars. Actually, F9xx and FAxx codes are taken by other chars.
> 
> Eg: instagram-square => https://www.compart.com/en/unicode/U+F955
> 
> This is causing issues for some applications under some circumstances.
> 
> I can reproduce this in Word on Windows, (but not on Photoshop). I've tried almost everything to clean up the cache, I think this is not a cache problem
> 
> At the moment I can confirm this is an issue for the following brand icons:
> 
> * [ ]  dailymotion (f952)
> * [ ]  deezer (f977)
> * [ ]  edge-legacy (f978)
> * [ ]  firefox-browser (f907)
> * [ ]  google-pay (f979)
> * [ ]  ideal (f913)
> * [ ]  instagram-square (f955)
> * [ ]  microblog (f91a)
> * [ ]  mixed (f956)
> * [ ]  pied-piper-square (f91e)
> * [ ]  rust (f97a)
> * [ ]  shopify (f957)
> * [ ]  tiktok (f97b)
> * [ ]  unity (f949)
> * [ ]  unsplash (f97c)
> 
> I will download the Unicode DB and create a script to check other unicode points.

Could you make it a point to examine the Coronavirus icons as well? Originally, the issue stemmed from those

**Comment by tagliala** [comment] 2020-06-26 21:16
@calpoly-richardrobinson confirm

f964 is used: https://www.compart.com/en/unicode/U+f964

I will create a script to find them all 👍

**Comment by amiremami** [comment] 2020-06-26 22:01
Thanks. In my screenshot, some of them are Chinese and some of them are rectangular, do you know the reason of rectangular ones?
https://i.imgur.com/hgIKZhD.png

**Comment by tagliala** [comment] 2020-06-26 22:05
@amiremami please try to paste without formatting

**Comment by amiremami** [comment] 2020-06-26 22:11
Great, thanks, you were right. The Chinese characters were ok in notepad though, maybe helps you to debug the issue:
https://i.imgur.com/OmOeDCL.png

**Comment by tagliala** [comment] 2020-06-27 10:14
I've provided detailed information about this issue in a private repo.

This is affecting 136 icons

**Comment by robmadole** [comment] 2020-06-29 19:34
Ok, just to update this thread we can confirm the issue and will get busy on the fix.

**Comment by sensibleworld** [comment] 2020-06-30 15:07
As we work on a fix, I can suggest an immediate workaround. Instead of copying the unicode glyph from the website, copy the icon name. This will use our ligatures, as opposed to unicode points.

<img width="824" alt="Screen Shot 2020-06-30 at 11 07 09 AM" src="https://user-images.githubusercontent.com/529604/86142979-d9938680-bac1-11ea-90f3-8585ec05984a.png">

**Comment by tagliala** [comment] 2020-06-30 16:13
I cannot make ligatures work at all on MS Word 2019 / Windows
They do work on Wordpad, unless they are hyphenated (`instagram` works, `instagram-square` doesn't)

No problem with photoshop on windows

**Comment by sensibleworld** [comment] 2020-06-30 17:40
@tagliala Can you confirm if, in the font dialog box in MS Word, you have "contextual alternatives" set to on and have ligatures set to "all"?

**Comment by tagliala** [comment] 2020-06-30 19:55
@sensibleworld thanks, I was able to make it work.

It is worth to improve the desktop troubleshooting guide here: https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting#ligatures-not-working, because that option to enable contextual alternatives was grayed out at first, because an option called "Disable OpenType Font Formatting feature" was enabled by default for new documents in File -> Options -> Advanced -> Layout options for New documents

![image](https://user-images.githubusercontent.com/556268/86170963-391e8000-bb1c-11ea-83f9-1662c38f597f.png)

**Comment by stoem** [comment] 2020-07-03 11:35
I'm not sure if this is helpful at all but I was using some of the Virus icons in Font Awesome Pro 5.13.1, for example `<i class="fas fa-viruses"></i>`in my web project and they worked fine locally on Mac OSX 10.14.6 in Chrome but once I deployed my app to heroku I got what I think are Chinese icons instead.

**Comment by tagliala** [comment] 2020-07-04 09:17
@stoem I'm pretty confident it is not related, in the meaning that this issue should not affect functionality of the web font version of Font Awesome.

Are you self hosting fonts? Please check cache: maybe the deployed version on Heroku is still holding the old webfonts files. Feel free to share your heroku link, but until further confirmation let's use another [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

**Comment by tagliala** [comment] 2020-07-15 16:12
This is a list of all the icons affected by this issue

|style|name|unicode point|
|-|-|-|
|fa|bacteria|f959|
|fa|bacterium|f95a|
|fa|box-tissue|f95b|
|fa|caravan|f8ff|
|fa|caravan-alt|f900|
|fa|cat-space|f901|
|fa|coffee-pot|f902|
|fa|coffin-cross|f951|
|fa|comet|f903|
|brands|dailymotion|f952|
|brands|deezer|f977|
|brands|edge-legacy|f978|
|fa|fan-table|f904|
|fa|faucet|f905|
|fa|faucet-drip|f906|
|brands|firefox-browser|f907|
|fa|folder-download|f953|
|fa|folder-upload|f954|
|fa|galaxy|f908|
|fa|garage|f909|
|fa|garage-car|f90a|
|fa|garage-open|f90b|
|brands|google-pay|f979|
|fa|hand-holding-medical|f95c|
|fa|hand-sparkles|f95d|
|fa|hands-wash|f95e|
|fa|handshake-alt-slash|f95f|
|fa|handshake-slash|f960|
|fa|head-side-cough|f961|
|fa|head-side-cough-slash|f962|
|fa|head-side-mask|f963|
|fa|head-side-virus|f964|
|fa|heat|f90c|
|fa|house|f90d|
|fa|house-day|f90e|
|fa|house-leave|f90f|
|fa|house-night|f910|
|fa|house-return|f911|
|fa|house-signal|f912|
|fa|house-user|f965|
|brands|ideal|f913|
|brands|instagram-square|f955|
|fa|lamp-desk|f914|
|fa|lamp-floor|f915|
|fa|laptop-house|f966|
|fa|light-ceiling|f916|
|fa|light-switch|f917|
|fa|light-switch-off|f918|
|fa|light-switch-on|f919|
|fa|lungs-virus|f967|
|brands|microblog|f91a|
|fa|microwave|f91b|
|brands|mixer|f956|
|fa|outlet|f91c|
|fa|oven|f91d|
|fa|people-arrows|f968|
|brands|pied-piper-square|f91e|
|fa|plane-slash|f969|
|fa|planet-moon|f91f|
|fa|planet-ringed|f920|
|fa|police-box|f921|
|fa|portal-enter|f922|
|fa|portal-exit|f923|
|fa|pump-medical|f96a|
|fa|pump-soap|f96b|
|fa|radar|f924|
|fa|raygun|f925|
|fa|refrigerator|f926|
|fa|rocket-launch|f927|
|brands|rust|f97a|
|fa|sensor|f928|
|fa|sensor-alert|f929|
|fa|sensor-fire|f92a|
|fa|sensor-on|f92b|
|fa|sensor-smoke|f92c|
|fa|shield-virus|f96c|
|brands|shopify|f957|
|fa|sink|f96d|
|fa|siren|f92d|
|fa|siren-on|f92e|
|fa|soap|f96e|
|fa|solar-system|f92f|
|fa|sort-circle|f930|
|fa|sort-circle-down|f931|
|fa|sort-circle-up|f932|
|fa|space-station-moon|f933|
|fa|space-station-moon-alt|f934|
|fa|sprinkler|f935|
|fa|star-shooting|f936|
|fa|starfighter|f937|
|fa|starfighter-alt|f938|
|fa|starship|f939|
|fa|starship-freighter|f93a|
|fa|stopwatch-20|f96f|
|fa|store-alt-slash|f970|
|fa|store-slash|f971|
|fa|sword-laser|f93b|
|fa|sword-laser-alt|f93c|
|fa|swords-laser|f93d|
|fa|telescope|f93e|
|fa|temperature-down|f93f|
|fa|temperature-up|f940|
|brands|tiktok|f97b|
|fa|toilet-paper-slash|f972|
|fa|trailer|f941|
|fa|transporter|f942|
|fa|transporter-1|f943|
|fa|transporter-2|f944|
|fa|transporter-3|f945|
|fa|transporter-empty|f946|
|fa|ufo|f947|
|fa|ufo-beam|f948|
|brands|unity|f949|
|brands|unsplash|f97c|
|fa|user-alien|f94a|
|fa|user-robot|f94b|
|fa|user-unlock|f958|
|fa|user-visor|f94c|
|fa|users-slash|f973|
|fa|vacuum|f94d|
|fa|vacuum-robot|f94e|
|fa|virus|f974|
|fa|virus-slash|f975|
|fa|viruses|f976|
|fa|window-frame|f94f|
|fa|window-frame-open|f950|

**Comment by jplatte** [comment] 2020-07-17 13:03
This issue seems to be about an issue in 5.13.0? The firefox browser icon broke for me after upgrading to 5.14.0 (just being displayed as a f907 box replacement thing). I've downgrade to 5.13.1 for now, which brought it back.

**Comment by tagliala** [comment] 2020-07-17 13:08
Hi @jplatte 

> The firefox browser icon broke for me after upgrading to 5.14.0 (just being displayed as a f907 box replacement thing).

Cannot replicate:
- https://jsfiddle.net/tagliala/0x1qe4by/2/ (CSS)
- https://jsfiddle.net/tagliala/7xb2e854/1/ (SVG)

Could you please provide more details?
Are you using a custom pseudo-element to display icon?

**Comment by jplatte** [comment] 2020-07-17 13:09
I'm not talking about web, sorry for not being clear (although this issue is specifically about desktop).

I've tried both the OTF and TTF variant, both behave as if they just didn't contain that icon at all.

**Comment by tagliala** [comment] 2020-07-17 13:32
We had to change the unicode point: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#512x513x-to-5140


firefox-browser: `f907` ➡️  `e007`

**Comment by jplatte** [comment] 2020-07-17 13:55
Oh, okay. https://fontawesome.com/icons/firefox-browser?style=brands still shows the old one. Thanks!

**Comment by robmadole** [comment] 2020-07-17 13:57
@jplatte you caught us in the middle of an upgrade. We'll get the site updated shortly.

**Comment by tagliala** [comment] 2020-07-19 08:17
I can confirm this has been fixed on Microsoft Word for Windows.

Apologies for the breaking change. 

Closing here, but feel free to comment if this is still an issue

**Closed by tagliala** 2020-07-19 08:17 UTC
Labels: BREAKING CHANGE, bug, css, desktop, svg

**Comment by TaylorAkin** [comment] 2020-11-10 16:14
I'm still having an issue with using the "bacteria" icon. 

index.js:1 Could not find icon {prefix: "fas", iconName: "bacteria"} 
@tagliala 

I have a reused component in a create drawer, where I pass the icon="" as a prop, and I am using multiple icons, all working except "bacteria" and "bacterium". I saw these 2 on your list and figured i'd let you know. I'm currently running version 5.14

**Comment by tagliala** [comment] 2020-11-10 16:24
@TaylorAkin please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

Please notice that this issue is for Font Awesome Desktop and it is not related to javascript

**Comment by luizzinno** [comment] 2021-09-23 08:47
Hi guys! I've the same issue:

1. Copy char from cheatsheet web page
2. Paste on Illustrator MacOS (latest)
3. I can't change the font from `Myriad pro` to Font Awesome
4. Restart MacOS and not solved

Maybe is an Adobe CC Suite bug, the tranparency on PNG was into black too. << I think is a copy paste bug / data error on memory >>

Other times I have the bug and restarting Illustrator was enough. I will try on Windows 10 and maybe report Adobe Illustrator.
