### ISSUE TITLE
Icon request for Telegram App

### ISSUE THREAD

**Issue by mewsoft** [FortAwesome/Font-Awesome#8877] opened 2016-04-02 20:04 UTC
Telegram app https://telegram.org/ is now very popular almost like Whatsapp. It will be nice if you add an app icon for it.

**Comment by tagliala** [comment] 2016-04-02 20:16
Duplicate of #3034, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-02 20:16 UTC
