### ISSUE TITLE
Icon Request: Cookie

### ISSUE THREAD

**Issue by yocmen** [FortAwesome/Font-Awesome#12015] opened 2017-12-30 18:58 UTC
Hi, can we get a Cookie icon?

**Comment by tagliala** [comment] 2017-12-30 19:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2845, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-30 19:00 UTC
