### ISSUE TITLE
Icon request: tinder

### ISSUE THREAD

**Issue by xxczaki** [FortAwesome/Font-Awesome#12688] opened 2018-03-23 20:40 UTC
### What can it be used for?

- As a [Tinder](https://tinder.com/) logo on website etc.
- Alternative to `fa-fire`
- Example (replace fire emoji with fa-tinder): :fire: Powered by Font Awesome 5

### Example image (optional)

![Tinder](http://www.ebony.com/wp-content/uploads/2016/07/tinderlogo_art_caro_original_52367.jpg)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-06 14:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8125, please add a 👍  reaction to that request.

>  I have searched for existing issues and to the best of my knowledge this is not a duplicate

No problem

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 14:29 UTC
