### ISSUE TITLE
Icon request: dart-lang

### ISSUE THREAD

**Issue by Marco87Developer** [FortAwesome/Font-Awesome#13579] opened 2018-07-19 17:53 UTC
### What can it be used for?

This icon represent the Dart programming language. I think would be useful, for example, in a resume (i.e. _curriculum vitæ_).

### Example image
You can see the icon in the following page: [Dart programming language](https://www.dartlang.org/).

### Icon request checklist

- [ ] This is a single icon.
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and I found that the request is _very_ old (2015).

Thanks!

**Comment by tagliala** [comment] 2018-07-19 19:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8003, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-19 19:10 UTC
