### ISSUE TITLE
Icon Request: fa-slash

### ISSUE THREAD

**Issue by trackor** [FortAwesome/Font-Awesome#10553] opened 2017-01-23 18:35 UTC
Create a slash icon that can also be stacked on top of any other icon.

**Comment by tagliala** [comment] 2017-01-23 19:51
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3691, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-23 19:51 UTC
