### ISSUE TITLE
Icon request: Foodsafety

### ISSUE THREAD

**Issue by Minikibber** [FortAwesome/Font-Awesome#10417] opened 2016-12-22 09:49 UTC
F.eks. a neutral apple, not the company Apple logo.
It could also be an apple or tomato together with a milk bottle
![food-vegeterian-food-icon](https://cloud.githubusercontent.com/assets/24714037/21421635/384bcc5c-c834-11e6-8628-1a3428419509.png)
![food-vegetarian-food-icon](https://cloud.githubusercontent.com/assets/24714037/21421634/384af8ae-c834-11e6-8625-e13da5e8341e.png)

.

**Comment by tagliala** [comment] 2016-12-22 13:41
I would consider this a duplicate of +1 #2979 

An apple could cover more use cases than tomato + milk bottle

**Closed by tagliala** 2016-12-22 13:41 UTC
