### ISSUE TITLE
New sort-alpha-down and up icons are not as clear as the old ones

### ISSUE THREAD

**Issue by ramirez** [FortAwesome/Font-Awesome#13943] opened 2018-09-14 09:18 UTC
Hi,

I just upgraded to v5 and I noticed that the alpha sort ascending and descending icons are not as clear as they used to be. The old ascending one had an A stacked on top of a Z and an arrow pointing down. The descending one just swapped the A for Z, so the Z was on top of the A and the arrow stayed the same. The new ones in version 5 keep the A on top of the Z for both icons and just swap the arrow to point upwards. I feel this is confusing for example when using the icons in a column header, since visually, both icons represent same order: A is on top, Z is all the way down. Would it be feasible to either go back to the old ones, or to maybe include the old ones as well?

Cheers,

LEo

**Comment by tagliala** [comment] 2018-09-14 11:40
Hi,

I do agree

This is a duplicate of #9464

Please post there your comment

**Closed by tagliala** 2018-09-14 11:40 UTC
