### ISSUE TITLE
Brand request: Unreal Engine

### ISSUE THREAD

**Issue by ravenblackhart** [FortAwesome/Font-Awesome#19261] opened 2022-08-11 10:16 UTC
### Description

To be used to indicate projects / games made with unreal engine

### Official website

https://nypost-com.cdn.ampproject.org/c/s/nypost.com/2022/08/05/malcolm-gladwell-slams-working-from-home/amp/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by aethior** [comment] 2022-08-18 08:40
Hi @ravenblackhart,

Duplicate of #11420.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed as completed** 2022-08-18 08:41 UTC
Labels: brand icon
