### ISSUE TITLE
Icon Request: fa-lamp

### ISSUE THREAD

**Issue by elprincipe9** [FortAwesome/Font-Awesome#8690] opened 2016-03-02 16:08 UTC
Hello! Great job on all these FaFonts! They are great!!!
I'm a webmaster and I often need a lamp font awesome to convey furniture or light, etc.I use the lightbulb which I really like because it has the little reflection of light on the top (very nice touch) but now I am currently building a website for a lampshade manufacturer so I REALLY would like to see a fa-lamp

anyways.. enough compliments for one email... :)

thanks for you time!!

Diego
<img width="235" alt="24802c4e-da1f-11e5-973a-abb2fd18fea7" src="https://cloud.githubusercontent.com/assets/17434215/13466227/088743e4-e067-11e5-808d-237e2480bfcb.png">

**Comment by tagliala** [comment] 2016-03-02 16:53
Hi, as you know this is a duplicate of #8635 

If you need this icon in a short while, please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2016-03-02 16:53 UTC
