### ISSUE TITLE
Icon request: Alternate Line Chart Icons

### ISSUE THREAD

**Issue by iang0ld** [FortAwesome/Font-Awesome#16387] opened 2020-03-30 14:33 UTC
line-chart-alt line-char without the axis.
live-char-down-alt line-char without the axis.

**Comment by tagliala** [comment] 2020-03-30 15:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4397, please add a 👍 reaction to that request.

Closing here

**Closed by tagliala** 2020-03-30 15:22 UTC
