### ISSUE TITLE
Icon Request: fa-songkick

### ISSUE THREAD

**Issue by HernanMGC** [FortAwesome/Font-Awesome#9054] opened 2016-04-25 09:23 UTC
Include a few use cases for your requested icon. How do you plan on using it?

- For a cliente page in the social buttons section

Attach a single color image or two that represent the idea you're going for.
https://pbs.twimg.com/profile_images/469486037056499712/5O5V2jrE.png

**Comment by tagliala** [comment] 2016-04-25 10:23
Duplicate of #2871, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-25 10:23 UTC
