### ISSUE TITLE
Icon request: rod-of-asclepius

### ISSUE THREAD

**Issue by ltoews** [FortAwesome/Font-Awesome#17176] opened 2020-09-18 23:12 UTC
**What can it be used for?**
common medical symbol

**Example image (optional)**
![image](https://user-images.githubusercontent.com/1249230/93652280-57807300-f9c9-11ea-9880-ad1e0cc2d267.png)
![image](https://user-images.githubusercontent.com/1249230/93652290-6109db00-f9c9-11ea-9a1e-c9288e26df71.png)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-09-19 08:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2009 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-09-19 08:28 UTC
