### ISSUE TITLE
Icon request: e-scooter

### ISSUE THREAD

**Issue by RushalB** [FortAwesome/Font-Awesome#18097] opened 2021-07-23 23:15 UTC
**What can it be used for?**
To represent e-scooters
(Lime/Bird/Spin etc)

**Example image (optional)**
![download](https://user-images.githubusercontent.com/54552057/126849547-f12bb6d6-b54e-4a32-9e40-83c7d79d8b5d.png)

**Comment by tagliala** [comment] 2021-07-24 10:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15447, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-07-24 10:57 UTC
