### ISSUE TITLE
Icon request: Codeigniter PHP framework

### ISSUE THREAD

**Issue by Nudasoft** [FortAwesome/Font-Awesome#18425] opened 2021-11-09 09:28 UTC
**What can it be used for?**
This PHP framework is a very popular one. it would be great if we have fa icon for this.

**Example image (optional)**
Here is the link for the logo: https://forum.codeigniter.com/thread-74090.html
<img src="https://www.codeigniter.com/assets/images/codeigniter4logo.png" />

**Comment by Nudasoft** [comment] 2021-11-09 09:32
Need this icon specifically for the Codeigniter version 4 not for the version 3. version 3 no longer in the development.

**Comment by aethior** [comment] 2022-04-15 00:13
Hi @Nudasoft,

This request is duplicate of #4316.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed** 2022-04-15 07:53 UTC
