### ISSUE TITLE
Icon request: icon-mercadolibre & icon-mercadopago

### ISSUE THREAD

**Issue by soyXander** [FortAwesome/Font-Awesome#19130] opened 2022-06-14 16:12 UTC
MercadoLibre and MercadoPago are equivalent to Amazon and Paypal in Latin America

**Comment by tagliala** [comment] 2022-06-14 16:28
Hi!

Thanks for being part of the Font Awesome Community.

mercadolibre is a duplicate of #14846, please add a 👍 reaction to that request.
mercadopago is a duplicate of #10072, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-06-14 16:28 UTC
