### ISSUE TITLE
Icon Request: fa-halal

### ISSUE THREAD

**Issue by lakunova** [FortAwesome/Font-Awesome#12289] opened 2018-02-08 08:40 UTC
The "halal" icon is needed to describe the type of tourism for the site of tourist services. It will also be useful in all areas where services and products of the category "halal" are provided.
![halal-food-icon](https://user-images.githubusercontent.com/36259854/35963103-b9c26d24-0cc4-11e8-81f2-15eca51c0c76.png)
![halal-sign-31982829bae51675-512x512](https://user-images.githubusercontent.com/36259854/35963104-b9eb23ea-0cc4-11e8-95a3-61872a7e87d6.png)

**Comment by tagliala** [comment] 2018-02-08 08:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6566, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-08 08:53 UTC
