### ISSUE TITLE
icon request fa-solarPanel fa-renewableEnergy

### ISSUE THREAD

**Issue by edisonsalazatr** [FortAwesome/Font-Awesome#11954] opened 2017-12-17 18:54 UTC
Hi friends.
Please I need some icons of renewable enery source like solar panels, wind, solar power pole, etc.
Here are some ideas... https://www.google.cl/search?safe=strict&rlz=1C5CHFA_enCL774CL774&biw=1440&bih=786&tbm=isch&sa=1&ei=lx41WviNJouEwgSahK6gBg&q=icono+panel+solar&oq=icono+panel+solar&gs_l=psy-ab.3..0l2.491894.492970.0.493171.5.5.0.0.0.0.82.341.5.5.0....0...1c.1.64.psy-ab..0.5.339...0i7i30k1j0i7i5i30k1j0i8i7i30k1j0i8i30k1.0.NDMgCLR2E9c
Thanks a lot.

**Comment by tagliala** [comment] 2017-12-17 19:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3326, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2017-12-17 19:14 UTC
