### ISSUE TITLE
Icon request: icon-ruler, icon-measuring-tape 

### ISSUE THREAD

**Issue by erikaursi** [FortAwesome/Font-Awesome#10127] opened 2016-10-27 11:42 UTC
Hi!
I'm a designer who creates layouts for websites. I currently work for a website that sells real estate and vehicles that uses FontAwesome icons by default.
I'd like an icon for “measuring”, “measure”. It'd be a ruler icon. I'd like to place it next to the property size (measured in m2). The ruler can also be used to represent many other situations and would be very useful.
Other interesting and useful measuring icons are measuring tapes and self-retracting measuring tapes.
I wasn't able to find any icon indicating measuring/measures at FontAwesome and I think the community would find it very useful.
Here are some images for reference:
![icons_measure](https://cloud.githubusercontent.com/assets/23098388/19765894/a2c9da10-9c29-11e6-8961-97c542b6453e.jpg)

**Comment by tagliala** [comment] 2016-10-27 11:44
Duplicate of #1096 and #8437, please add a 👍  reaction to those requests

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-27 11:44 UTC

**Comment by m1rr0r1ng** [comment] 2016-11-21 20:47
Was this added to the icon set? I can't find it in the list: http://fontawesome.io/icons/

**Comment by tagliala** [comment] 2016-11-21 22:34
@m1rr0r1ng #1096 and #8437 are requests, they weren't added yet
