### ISSUE TITLE
Icon Request: fa-mechanical-shovel (digger)

### ISSUE THREAD

**Issue by luchi20** [FortAwesome/Font-Awesome#9380] opened 2016-06-09 11:41 UTC
Hello,
Could you add an icon for a mechanical shovel?something like a machine construction.  It is very util for everyone.
Could be: fa-shovel-construction
Something like:

![construccion](https://cloud.githubusercontent.com/assets/19836484/15928552/e99aa9c6-2e1d-11e6-84fa-96cf6807a8e9.png)

Thank you very much

**Comment by tagliala** [comment] 2016-06-09 12:45
Strictly related to #4084

**Comment by tpeelstand** [comment] 2016-08-04 15:59
So, I made this icon. It would work pretty well as a font-awesome icon. something like fa-construction.

White version is a bit difficult to see, if you drag it to you desktop you can look at it better. Looks the same as the black version.

White version (larger):
skidsteer-and-excavator-icon

Black version (small):
skidsteer-and-excavator-icon-sm-invert

**Comment by maartenmg** [comment] 2022-01-06 13:59
+1

**Comment by aethior** [comment] 2022-04-17 18:44
> Strictly related to #4084

And related or duplicated of #2997?

**Comment by tagliala** [comment] 2022-04-17 18:46
Ah, yes. Let's use this one (more upvotes)

**Comment by tagliala** [comment] 2022-04-22 09:41
Duplicate of #5305

**Closed by tagliala** 2022-04-22 09:41 UTC
Labels: new icon, construction (category)
