### ISSUE TITLE
Icon request: icon-zomato

### ISSUE THREAD

**Issue by urmisaha** [FortAwesome/Font-Awesome#9941] opened 2016-09-22 09:33 UTC
Icon for the brand Zomato (https://www.zomato.com). It will be used in websites.

**Comment by tagliala** [comment] 2016-09-22 11:41
Duplicate of #4022, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-22 11:41 UTC
