### ISSUE TITLE
Icon Request: Port of the old language icon

### ISSUE THREAD

**Issue by NightYoshi370** [FortAwesome/Font-Awesome#16587] opened 2020-05-07 05:42 UTC
**What can it be used for?**
The old language icon in 4.7 was more cube like as opposed to the more horizontal oriented current language icon

**Example image (optional)**
![image](https://user-images.githubusercontent.com/18664762/81258501-aca78380-8fea-11ea-9b1a-dc1913dccaf4.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-07 19:21
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13465, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-07 19:21 UTC

**Comment by NightYoshi370** [comment] 2020-05-07 19:24
Thank you. I have added a thumbs up emoji to the prior request. Is there an SVG of the old icon I could use in the meantime?

**Comment by tagliala** [comment] 2020-05-07 19:30
Thank you for your understanding!

> Is there an SVG of the old icon I could use in the meantime?

Sure! https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/language.svg

**Comment by tagliala** [comment] 2020-05-07 19:37
For the records: the official SVG path can be extracted from here: https://raw.githubusercontent.com/FortAwesome/Font-Awesome/v4.7.0/fonts/fontawesome-webfont.svg and that fork makes the process more user friendly
