### ISSUE TITLE
Icon request: icon-zhihu

### ISSUE THREAD

**Issue by wangpengfei15975** [FortAwesome/Font-Awesome#8755] opened 2016-03-15 05:00 UTC
urgently.

**Comment by tagliala** [comment] 2016-03-15 09:53
Duplicate of #4439, please +1 that request

if you need this icon urgently, go for a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2016-03-15 09:53 UTC
