### ISSUE TITLE
Icon request: Taka-Sign

### ISSUE THREAD

**Issue by saakeeb** [FortAwesome/Font-Awesome#17698] opened 2021-03-06 08:09 UTC
**What can it be used for?**
Logo for displaying Bangladesh countries currency sign

**Example image (optional)**
![bangladeshi-currency-sign](https://user-images.githubusercontent.com/60483192/110199948-3df2bb00-7e85-11eb-8f80-af2488039644.jpg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

https://en.wikipedia.org/wiki/Bangladeshi_taka

**Comment by saakeeb** [comment] 2021-03-06 08:10
It will be handy for the Bangladesh e-commerce community for their e-commerce site.

**Comment by tagliala** [comment] 2021-03-06 10:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1719, and it will be included in the upcoming Font Awesome 6

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-06 10:56 UTC

**Comment by saakeeb** [comment] 2021-03-06 15:45
Sorry, I miss that, Thank you for considering this icon for the upcoming version 6
