### ISSUE TITLE
Icon request: card-reader

### ISSUE THREAD

**Issue by luisalves73** [FortAwesome/Font-Awesome#18644] opened 2022-02-04 19:09 UTC
**What can it be used for?**
Illustrates when a card reader is going to be used to perform an operation.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/7095339/152588225-9ad437e0-b078-44ca-bca2-38d6171891c9.png)
![image](https://user-images.githubusercontent.com/7095339/152588240-06a24e10-30ab-424b-bca4-9f5fde80e6f6.png)

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-05-21 00:59
@tagliala `devices-hardware (category)` label for this request?

**Comment by sensibleworld** [comment] 2024-07-11 15:14
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/7326)

**Closed as completed by sensibleworld** 2024-07-11 15:14 UTC
Labels: new icon, devices-hardware (category), Duplicate
