### ISSUE TITLE
Icon Request: fa-scooter

### ISSUE THREAD

**Issue by Wiebe-K** [FortAwesome/Font-Awesome#8991] opened 2016-04-15 14:33 UTC
Hey font awesome, First off all i love your service!

So the icon i would like to see to be added is a Scooter mobile, Not a motorcycle but a scooter.
The scoters are super popular in europe and im making a few sites for rent companies thats where this icon will come in handy for me and im sure for many others aswel.

** I dont mean the scooter thing kids play with but the vehicle "Scooter" ** 

For example:
![image](https://cloud.githubusercontent.com/assets/18485644/14564524/37099a18-0327-11e6-8cef-0b39444f32d3.png)
![image](https://cloud.githubusercontent.com/assets/18485644/14564545/483d836c-0327-11e6-948b-1945ef705693.png)

Im planning on using this icon for a few sites and since you guys have so much vehicle icons this one cant be left out right? 

Greetings,
Wiebe

**Comment by PeterShaggyNoble** [comment] 2016-04-15 14:35
Dupe of [#6897](https://github.com/FortAwesome/Font-Awesome/issues/6897), you should +1 that one instead.

**Closed** 2016-04-15 16:21 UTC
