### ISSUE TITLE
Icon Request: fa-datacard

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#10003] opened 2016-09-29 18:23 UTC
Depicting a card/sheet/page of data 
![datacard](https://cloud.githubusercontent.com/assets/539719/18966731/574f1b02-8650-11e6-825a-af9504043ce5.png)
for use within a healthcare data app

**Comment by tagliala** [comment] 2016-09-30 09:01
Duplicate of #773, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-30 09:01 UTC
