### ISSUE TITLE
Icon Request: fa-broadcast

### ISSUE THREAD

**Issue by priestap** [FortAwesome/Font-Awesome#5943] opened 2015-03-12 19:35 UTC
Having an icon showing a radio tower signal or something would be great. Like this: http://cl.ly/image/2W0A411T2a01

**Comment by kwendenarmo** [comment] 2015-03-23 22:33
+1

**Comment by dngunraj** [comment] 2015-03-26 20:27
+1

**Comment by tagliala** [comment] 2015-07-23 08:20
duplicate of #2581 , please +1 that request

closing here

**Closed by tagliala** 2015-07-23 08:20 UTC

**Comment by nshaibu** [comment] 2020-04-16 00:11
+1
