### ISSUE TITLE
Icon request: oil-barrell

### ISSUE THREAD

**Issue by DavyNixon** [FortAwesome/Font-Awesome#17575] opened 2021-01-22 11:41 UTC
**What can it be used for?**
The icon could be used to represent a barrel of oil or other products

**Example image (optional)**
https://cdn0.iconfinder.com/data/icons/energy-technology-linear-black/2048/299_-_Oil_Barrel-512.png

**Comment by tagliala** [comment] 2021-01-22 12:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8142 or #4318, please add a 👍 reaction to that request.

Please make sure you search existing requests before opening new ones

You may also be interested in taking a look at our Icon Leaderboard FAQs, they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-01-22 12:28 UTC
