### ISSUE TITLE
Icon Request: fa-office365

### ISSUE THREAD

**Issue by ricardopolo** [FortAwesome/Font-Awesome#5695] opened 2015-02-17 00:05 UTC

**Comment by G-Driver** [comment] 2015-02-19 10:25
+1 for this:
<img src="http://www.skypeassets.com/content/dam/scom/images/text-and-image/mobile/office-logo_v3.jpg">

**Comment by Dehli** [comment] 2015-02-19 15:29
Duplicate of https://github.com/FortAwesome/Font-Awesome/issues/1333.

**Closed** 2018-05-02 12:06 UTC
