### ISSUE TITLE
Icon request: UpWork icon

### ISSUE THREAD

**Issue by danmct1995** [FortAwesome/Font-Awesome#16210] opened 2020-02-17 04:38 UTC
I created an icon for a popular freelancing website.  I would love if it were to be uploaded so that I and others could use it for basic HTML / CSS design.  I'd imagine it'd be nice for portfolio pages & linking up to clients easier as well. The picture is a blank square in this thread, but if you click on it you'll see the PNG with a black background.

![AKI_UPWORK_ICON](https://user-images.githubusercontent.com/54688438/74624141-54609400-5115-11ea-88d2-c1428bac6bdf.png)

**Comment by tagliala** [comment] 2020-02-18 20:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6537, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at how requests work, please read our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs)

Closing here

**Closed by tagliala** 2020-02-18 20:29 UTC
