### ISSUE TITLE
Icon Request: fa-discord

### ISSUE THREAD

**Issue by msro1** [FortAwesome/Font-Awesome#9960] opened 2016-09-25 10:32 UTC
![discord](https://cloud.githubusercontent.com/assets/18587036/18814710/e168a488-835e-11e6-8adf-5c88ea37e3cd.png)

Hi, I have an idea for having the discord logo (and maybe teamSpeak) icons so that way people can link to their own servers. I'm making my own website, and I have links to facebook, twitter, and twitch, but I'd also like to link to my discord server. I have attached an image of the current logo that is pretty much what I would want on my website.

Thanks

**Comment by tagliala** [comment] 2016-09-25 11:35
Duplicate of #7574  and #1474 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-25 11:35 UTC
