### ISSUE TITLE
Icon request: icon-line

### ISSUE THREAD

**Issue by naimbic** [FortAwesome/Font-Awesome#11415] opened 2017-08-17 01:56 UTC
Hello guys, thank you for the great job you are doing.
Kindly i request a Japanese social Apps icon LINE as shown in attachment file, thank you.
![share-d](https://user-images.githubusercontent.com/6326117/29392735-a2045d14-833a-11e7-854c-3402dd0262b6.png)

**Comment by timtjtim** [comment] 2017-08-17 02:04
This is a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/10088

**Closed** 2017-08-17 08:06 UTC
