### ISSUE TITLE
Icon Request: fa-clover

### ISSUE THREAD

**Issue by evydaemon** [FortAwesome/Font-Awesome#11801] opened 2017-11-25 15:07 UTC
Just need a simple clear 4 leaf clover icon. Theme: casino, game, luck

**Comment by tagliala** [comment] 2017-11-25 16:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1593, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-25 16:09 UTC
