### ISSUE TITLE
Icon Request: icon-open-door

### ISSUE THREAD

**Issue by simona6** [FortAwesome/Font-Awesome#6501] opened 2015-05-18 15:00 UTC
Sorry that my second post is about another icon, but we could do with some sort of "open door" icon, that indicator "come to our shop".

Thanks v much.

**Comment by tagliala** [comment] 2015-05-21 14:01
duplicate of #2921, please +1 that request

closing here

**Closed by tagliala** 2015-05-21 14:01 UTC

**Comment by jtbratcher** [comment] 2015-09-14 12:19
+1 again. I'd like to use it as a "leave group" icon.
