### ISSUE TITLE
Icon Request: fa-guitar

### ISSUE THREAD

**Issue by br-renatolima** [FortAwesome/Font-Awesome#8077] opened 2015-12-03 19:31 UTC
Please, make an acoustic and eletric guitar icon, as well every instrument.
Lot of thanks!

**Comment by TheChen5** [comment] 2015-12-04 04:46
Dupe #5059
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by ryankane** [comment] 2015-12-04 04:56
@br-renatolima Here, I whipped these up...

# fa-guitar-acoustic-o

![fa-guitar-acoustic-o](http://i.imgur.com/4rNOknH.png)

# fa-guitar-acoustic

![fa-guitar-acoustic](http://i.imgur.com/XxnLc3M.png)

# fa-guitar-electric-o

![fa-guitar-electric-o](http://i.imgur.com/6eCnvQe.png)

# fa-guitar-electric

![fa-guitar-electric](http://i.imgur.com/4XbaFCX.png)

**Comment by TheChen5** [comment] 2015-12-04 04:59
@ryankane As this request is a duplicate of #5059, please post your example there.

**Comment by ryankane** [comment] 2015-12-04 05:12
@TheChen5 OK, thanks.

**Closed** 2015-12-04 09:52 UTC
