### ISSUE TITLE
Icon request: icon-eye-close-alt

### ISSUE THREAD

**Issue by pepperstreet** [FortAwesome/Font-Awesome#2132] opened 2013-10-10 18:28 UTC
Hello, here is a gently request for an alternative "closed eye" icon. IMHO, the strike-through style is hard to read and distinguish from the normal eye icon. Especially in smaller sizes.
 Current icon: http://fortawesome.github.io/Font-Awesome/icon/eye-close/

Some ideas that represents "**closed**" in a better way:

**A.)** eye contour/clear without iris/pupil.  (similar to the lemon) 
**B.)** eye contour/clear with lashes at bottom
**C.)** eye-lid almost closed. Solid color.  (unfortunately the open eye icon has a rather big iris part, that is not centered)

Thanks for listening.
If there is any free-time, I would really like to contribute something on my own! Cross my finders... otherwise, any help is much appreciated.

**PS**: Related idea for an optional icon with the meaning of invisible / hidden:
- sun glasses (filled binocular)
- maybe this could have a counterpart (binocular clear/contour)
  I opened a separate issue/topic here... #2133

**Comment by hellsing71** [comment] 2015-09-02 17:19
+1 for version B.

The eye-slash is so hard to recognize.

**Comment by mariegithub** [comment] 2015-09-08 08:57
+1

**Comment by jmcudk** [comment] 2019-10-21 00:38
+1

**Comment by sensibleworld** [comment] 2024-07-11 14:12
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/8283)

**Closed by sensibleworld** 2024-07-11 14:12 UTC
Labels: new icon, enhancement, web application icons (legacy category), Duplicate
