### ISSUE TITLE
Icon request: save-as-icon

### ISSUE THREAD

**Issue by JackDjTom** [FortAwesome/Font-Awesome#16704] opened 2020-05-22 15:18 UTC
**What can it be used for?**
In many programms there is the option "Save" and "Save as", the icon can be used to visualize "save as"

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlaeiNP4KBwwRLBR0P_T6mFlYGfeeVDFo_rmkLbeP1AOxPyN9t&s

**Comment by tagliala** [comment] 2020-05-22 17:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #512, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-22 17:13 UTC
