### ISSUE TITLE
Icon request: bathtub

### ISSUE THREAD

**Issue by MarGraz** [FortAwesome/Font-Awesome#9145] opened 2016-05-07 17:16 UTC
I'm creating a website for a B&B, and I saw that in fontawesome there isn't an icon to indicate bathtub.
It's possible to add this new icon to font awesome?

Thank you again

![icon_bath](https://cloud.githubusercontent.com/assets/19241483/15093431/26a81fba-1488-11e6-8c1c-4ae51face40c.png)

**Comment by tagliala** [comment] 2016-05-07 17:17
Duplicate of #708 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-07 17:17 UTC

**Comment by MarGraz** [comment] 2016-05-07 17:25
I'm sorry. 
I only cheked here http://fontawesome.io/icons/ and not fot another request. 

Sorry :'(
