### ISSUE TITLE
Icon Requset - fa-bottle

### ISSUE THREAD

**Issue by zoharyosef** [FortAwesome/Font-Awesome#9935] opened 2016-09-20 09:39 UTC
Hi Font Awesome, your'e awesome!
I could really use a bottle icon, it can be just standing or pouring...
Thanks!
[Example](http://www.clipartkid.com/images/86/white-wine-bottle-29-99-white-wine-bottle-4-OEXED7-clipart.jpg)

**Comment by tagliala** [comment] 2016-09-20 14:45
Duplicate of #1762, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-20 14:45 UTC
