### ISSUE TITLE
Add a roblox icon.

### ISSUE THREAD

**Issue by MostafaMD** [FortAwesome/Font-Awesome#14891] opened 2019-04-13 09:03 UTC
We need a roblox icon, to put it in our websites. fa-roblox

**Comment by tagliala** [comment] 2019-04-16 15:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14194, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-16 15:56 UTC
