### ISSUE TITLE
Icon Request: fa-real

### ISSUE THREAD

**Issue by dgateles** [FortAwesome/Font-Awesome#9501] opened 2016-06-30 13:21 UTC
Brazilian-Real currency. Thank's!

**Comment by tagliala** [comment] 2016-06-30 13:27
Duplicate of #4916, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-30 13:27 UTC

**Comment by dfvascao** [comment] 2021-10-02 10:17
> Duplicate of #4916, please add a 👍 reaction to that request
> 
> Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests
> 
> Closing here

Friend,

Have you seen how many orders from the Brazilian currency source have been ordered since 2016 and until today, 5 years have passed and it has not been created until today?

Link: https://github.com/FortAwesome/Font-Awesome/issues/4916

Link currency icon: https://cdn-icons-png.flaticon.com/512/32/32665.png
