### ISSUE TITLE
Icon request: icon-vcard

### ISSUE THREAD

**Issue by endeavorm** [FortAwesome/Font-Awesome#5837] opened 2015-03-03 23:25 UTC
![vcard-2](https://cloud.githubusercontent.com/assets/11303896/6474851/52875e0c-c1b9-11e4-81ea-ed5ebfaab621.gif)

I create websites that need the ability to have a downloadable vcard and having an icon font would be awesome.

**Comment by tagliala** [comment] 2015-03-04 22:13
duplicate of #825 , please +1  that request

closing here

**Closed by tagliala** 2015-03-04 22:13 UTC
