### ISSUE TITLE
Icon Request: Autocad file

### ISSUE THREAD

**Issue by Sada-ko** [FortAwesome/Font-Awesome#12960] opened 2018-04-27 10:26 UTC
There are a lot of Autocad logo variations. We need all of them :))

https://i.ytimg.com/vi/XtorXzHg2UU/hqdefault.jpg
https://smartpro.com.tr/wp-content/uploads/2018/03/autocad-kad%C4%B1k%C3%B6y-2018.jpg
http://eduplus.net.in/img/autocad-logo.png

**Comment by tagliala** [comment] 2018-04-28 07:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12628, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-28 07:12 UTC
