### ISSUE TITLE
Duotone different alignment behaviour

### ISSUE THREAD

**Issue by Greigrm** [FortAwesome/Font-Awesome#15356] opened 2019-08-08 09:44 UTC
Using ExtJS (sorry!) I noticed a different behaviour between the new duotone and other fonts.  While I appreciate ExtJS isn't your thing, it may point to a difference/bug between the font sets.

Look at this example:
https://fiddle.sencha.com/#view/editor&fiddle/2uga

![Annotation 2019-08-08 104355](https://user-images.githubusercontent.com/6026410/62692952-7b514700-b9c9-11e9-8313-08c91c7d5f34.png)

The fonts are used identically, however the duotone aligns to the right of the text.  Whatever combination of css ExtJs brings to the party, the duotone behaves differently.

**Expected behavior**
All font sets align the same regardless of the framework they are used in.

**Version and implementation**
Version: 5.10.1
Browser and version: All browsers

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2019-08-08 11:03
Hi!

Thanks for being part of the Font Awesome Community.

Just for clarification, your kit is using the `css` implementation of Font Awesome instead of the `SVG` one.

duotone icons are also available with the css implementation of Font Awesome because we take advantage of `before` and `after` pseudoelements and putting them one on top of the other

The problem is due to third-party css rules that are conflicting with the `position: relative` rule of `.fad` (I see a lot of `position: absolute`), so you can either switch to the SVG implementation or **in that specific use case**, set `.fad` `position` to `absolute`.

Hope it helps

Closing here

**Closed by tagliala** 2019-08-08 11:03 UTC
