### ISSUE TITLE
Icon Request: fa-BBM

### ISSUE THREAD

**Issue by shahzoorali** [FortAwesome/Font-Awesome#5590] opened 2015-02-05 09:12 UTC
Would like to have BBM and BlackBerry logo

**Comment by tagliala** [comment] 2015-02-05 13:51
duplicate of #1537  and #2189 , please +1 those requests

closing here

**Closed by tagliala** 2015-02-05 13:51 UTC

**Comment by efixdent** [comment] 2016-01-21 03:16
+ 1

we need fontawesome to provide blackberry icon, thank you very much.
