### ISSUE TITLE
the ability to choose a small set of icon

### ISSUE THREAD

**Issue by calidion** [FortAwesome/Font-Awesome#9486] opened 2016-06-28 07:00 UTC
like 
http://iconfont.cn/search?q=scan
and then download.

**Comment by tagliala** [comment] 2016-06-28 12:01
Duplicate of #1773, but there are several tools out there

https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

closing here

**Closed by tagliala** 2016-06-28 12:01 UTC
