### ISSUE TITLE
Icon Request: icon-support

### ISSUE THREAD

**Issue by TraicionCraft** [FortAwesome/Font-Awesome#5864] opened 2015-03-06 00:47 UTC
Icon for support assistant

![](http://4.bp.blogspot.com/-sXnLwwewJxs/UnjLjX9StbI/AAAAAAAACWI/_Ip1U1O7JWg/s320/Telephone-customer-service-icon-0910124933.png)

**Comment by tagliala** [comment] 2015-03-07 13:57
duplicate of #5586 , please +1 that request

closing here

**Closed by tagliala** 2015-03-07 13:57 UTC
