### ISSUE TITLE
Icon request: icon-gnss

### ISSUE THREAD

**Issue by rmarzocchi84** [FortAwesome/Font-Awesome#9573] opened 2016-07-14 14:46 UTC
Other name: icon-gps

Use: for application of navigation or precise positioning

I attach an icon availble in openclipart.org
![gps-icon-2400px](https://cloud.githubusercontent.com/assets/4061154/16843614/405cf81a-49e2-11e6-948f-d498b9c6c178.png)

**Comment by tagliala** [comment] 2016-07-14 23:07
Is this a duplicate of #560?

**Comment by rmarzocchi84** [comment] 2016-07-15 07:28
I think a better name for #560 is icon-geolocation which is used in cartography application oriented to mobile phones, while this request is for GNSS applications

**Comment by sensibleworld** [comment] 2024-07-10 21:18
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/satellite?f=classic&s=solid)

**Closed by sensibleworld** 2024-07-10 21:18 UTC
Labels: new icon, web application icons (legacy category), FA Pro
