### ISSUE TITLE
Icon request: fa-running-man

### ISSUE THREAD

**Issue by fredleput** [FortAwesome/Font-Awesome#10590] opened 2017-01-31 11:15 UTC
just missing i think

**Comment by tagliala** [comment] 2017-03-04 12:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1156 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-04 12:46 UTC
