### ISSUE TITLE
Icon request: Threema Messenger

### ISSUE THREAD

**Issue by BMiZEL** [FortAwesome/Font-Awesome#15791] opened 2019-11-10 09:24 UTC
**What can it be used for?**
Threema Messenger for contacting or sharing

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-11-10 12:33
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #7057?

**Comment by BMiZEL** [comment] 2019-11-12 14:00
HI,

Ooops, yes it is. While searching it did not come up. Thks!

**Comment by BMiZEL** [comment] 2019-11-12 14:03
HI,

Ooops, yes it is. While searching it did not come up. Thks! Would be great if it could be included - I see some guys already wrote the code...

**Closed** 2024-07-12 16:19 UTC
Labels: brand icon, waiting for feedback
