### ISSUE TITLE
Improve website experience

### ISSUE THREAD

**Issue by georgemicheal21** [FortAwesome/Font-Awesome#11749] opened 2017-11-13 15:07 UTC
# Would you like to try Font Awesome PRO for JUST $60? CHECK IT OUT RIGHT NOWWWW!!!

or

>No thanks I'll keep being a fag and get the shitty free version

-----

This project has turned into nothing more than a cashgrab for the author, it is against everything that open source stands for.

Yes yes I know, issue closing in 3...2...

**Comment by tagliala** [comment] 2017-11-13 15:27
1...0 🔒 

I would be happy to discuss more, if you meet our contributing guidelines and use a polite language.

Closing here as a duplicate of #11748.

Also, this request doesn't meet the first point of our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

Regards

**Closed by tagliala** 2017-11-13 15:27 UTC
