### ISSUE TITLE
Icon Request: fa-Blogger

### ISSUE THREAD

**Issue by iamhassantahir** [FortAwesome/Font-Awesome#7121] opened 2015-08-02 08:42 UTC
Please add the the Google's Blogger.Com Icon in Font Awesome's next update.
![blogger-icon](https://cloud.githubusercontent.com/assets/13608699/9025384/55097072-391c-11e5-9e51-6baa652b7e74.png)

**Comment by tagliala** [comment] 2015-08-02 11:49
duplicate of #455 , please +1 that request

closing here

**Closed by tagliala** 2015-08-02 11:49 UTC
