### ISSUE TITLE
Icon request: icon-satellite

### ISSUE THREAD

**Issue by csthsl** [FortAwesome/Font-Awesome#6794] opened 2015-06-19 21:41 UTC
Communications icons needed. Simple is best. Dish with an antennae on it.

**Comment by ShamanFromSiberia** [comment] 2015-07-01 08:08
Two icons would be great: fa-sattelite (smth of [this kind](https://www.google.ru/search?q=weather+icons&newwindow=1&safe=off&rlz=1C1GGGE_ruRU550RU554&espv=2&biw=1536&bih=814&tbm=isch&imgil=60FQYEvf-_MKDM%253A%253B38O8E4UbMSbW7M%253Bhttp%25253A%25252F%25252Fdepositphotos.com%25252F34338603%25252Fstock-illustration-flat-weather-icons.html&source=iu&pf=m&fir=60FQYEvf-_MKDM%253A%252C38O8E4UbMSbW7M%252C_&usg=__4gls9Amwo4U3fY9UwW7ylKKZcnU%3D&ved=0CDUQyjc&ei=hZ2TVYnqFMTnygPiyp84#newwindow=1&safe=off&tbm=isch&q=sattelite+icon&imgrc=obANB8fNDt9kpM%3A)) and fa-sattelite-dish (smth like [this](https://www.google.ru/search?q=weather+icons&newwindow=1&safe=off&rlz=1C1GGGE_ruRU550RU554&espv=2&biw=1536&bih=814&tbm=isch&imgil=60FQYEvf-_MKDM%253A%253B38O8E4UbMSbW7M%253Bhttp%25253A%25252F%25252Fdepositphotos.com%25252F34338603%25252Fstock-illustration-flat-weather-icons.html&source=iu&pf=m&fir=60FQYEvf-_MKDM%253A%252C38O8E4UbMSbW7M%252C_&usg=__4gls9Amwo4U3fY9UwW7ylKKZcnU%3D&ved=0CDUQyjc&ei=hZ2TVYnqFMTnygPiyp84#newwindow=1&safe=off&tbm=isch&q=satellite+dish+icon&imgrc=rv_w66X-WAmi4M%3A))

**Comment by tagliala** [comment] 2015-07-01 09:48
duplicate of #2404, please +1 that request

closing here

**Closed by tagliala** 2015-07-01 09:48 UTC
