### ISSUE TITLE
Icon request: fa-mailbox

### ISSUE THREAD

**Issue by saraace** [FortAwesome/Font-Awesome#12663] opened 2018-03-21 16:48 UTC
Hi! 
I have clients that want to list their PO box on their website. I keep getting requests for a mailbox icon like this: 

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh9SY4rFCS_rVj5eVJiXDZx3WZH7OBKqCPAw8RohuY4zsyJyvx

**Comment by tagliala** [comment] 2018-04-06 13:27
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4849, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 13:27 UTC
