### ISSUE TITLE
Icon request: icon-confetti

### ISSUE THREAD

**Issue by dan003400** [FortAwesome/Font-Awesome#17557] opened 2021-01-14 17:49 UTC
![confetti](https://user-images.githubusercontent.com/1211542/104628837-56511100-565e-11eb-8b78-1c1afb5c4337.png)

**Comment by tagliala** [comment] 2021-01-25 20:43
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11888, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-01-25 20:43 UTC
