### ISSUE TITLE
Icon request: icon-note

### ISSUE THREAD

**Issue by norilog4** [FortAwesome/Font-Awesome#17518] opened 2020-12-29 06:55 UTC
**What can it be used for?**
Describe how this could be used / the use case for this icon.
https://note.com/

**Example image (optional)**
Insert the example image here if necessary.
https://help.note.com/hc/ja/articles/360000235582-%E3%83%AD%E3%82%B4%E3%83%87%E3%83%BC%E3%82%BF

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-12-29 09:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14888, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-12-29 09:53 UTC
