### ISSUE TITLE
Icon Request: fa-garage

### ISSUE THREAD

**Issue by GerardBol** [FortAwesome/Font-Awesome#11684] opened 2017-10-29 08:15 UTC
Please put in parking garage in as icon. i see a car with a roof on top of it,

**Comment by tagliala** [comment] 2017-10-29 09:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #713, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-29 09:47 UTC
