### ISSUE TITLE
Icon Request: fa-jira

### ISSUE THREAD

**Issue by Flower7C3** [FortAwesome/Font-Awesome#9905] opened 2016-09-12 07:42 UTC
Icon for jira issue tracking.

**Comment by tagliala** [comment] 2016-09-12 10:51
Duplicate of #2724, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-12 10:51 UTC
