### ISSUE TITLE
Icon Request: fa-statusNew

### ISSUE THREAD

**Issue by Gonzo2028** [FortAwesome/Font-Awesome#5478] opened 2015-01-26 11:37 UTC
A status overlay to mark something to be new.
Like attached
![neu](https://cloud.githubusercontent.com/assets/7795999/5899179/0b398412-a558-11e4-89dc-a92e42efee2c.png)

Thanks for your great stuff!

**Comment by tagliala** [comment] 2015-01-26 12:59
I'm going to consider this a duplicate of #1331, please +1 that request

I would also advise a css based solution for this stuff: https://github.com/FortAwesome/Font-Awesome/issues/1331#issuecomment-19571293

closing here

**Closed by tagliala** 2015-01-26 12:59 UTC
