### ISSUE TITLE
Icon Request: checklist

### ISSUE THREAD

**Issue by ultimasoul** [FortAwesome/Font-Awesome#11537] opened 2017-09-19 14:57 UTC
hi,
is it possible to add a checklist icon?
For example:
http://cdn2.iconfinder.com/data/icons/picons-essentials/57/checklist-128.png

Thanks

**Comment by hassanalami** [comment] 2017-10-03 11:19
You can use "list":
http://fontawesome.io/icon/list/
or
"th-list":
http://fontawesome.io/icon/th-list/

**Comment by tagliala** [comment] 2017-10-03 11:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #773, please add a 👍  reaction to that request.

Maybe a duplicate of #2965, too

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by ultimasoul** [comment] 2017-10-03 11:37
Hi hassanalami,
thank you for your response but it's not what I'm looking for: the "checklist" has a different meaning, it's not just a matter of generic list.

Thanks

**Closed by tagliala** 2017-10-03 11:37 UTC

**Comment by ultimasoul** [comment] 2017-10-03 11:41
Hi tagliala,
you're right, sorry for the duplicate.
I've added a reaction to #773.
Thanks
