### ISSUE TITLE
Icon request: fa-biohazard

### ISSUE THREAD

**Issue by RicCastagna** [FortAwesome/Font-Awesome#8516] opened 2016-02-09 15:20 UTC
Please consider adding the biohazard symbol to the Font Awesome catalog.

![biohazard](https://cloud.githubusercontent.com/assets/16654067/12920462/b493c124-cf16-11e5-9310-eb699775dfce.jpg)

**Comment by tagliala** [comment] 2016-02-09 21:12
duplicate of #255 , please +1 that request

closing here

**Closed by tagliala** 2016-02-09 21:12 UTC

**Comment by RicCastagna** [comment] 2016-02-09 22:32
#255 is a hodge-podge of requests: nuke, biohazard, X-ray, etc. They are not the same image.

**Comment by tagliala** [comment] 2016-02-09 22:34
#255 is only for bio hazard, don't mind about the comments

x-ray: #681

**Comment by cata92sv** [comment] 2017-09-12 12:53
do these requests actually work? cause the #255 was started 5 yrs ago..I mean what do we need to do to get that biohazard up and running?
