### ISSUE TITLE
Icon Request: fa-support

### ISSUE THREAD

**Issue by laxman1223** [FortAwesome/Font-Awesome#8252] opened 2015-12-31 04:51 UTC
icon for live support
![a](https://cloud.githubusercontent.com/assets/1289975/12061376/35c17cbe-afaa-11e5-9c9d-c7cd98d4909a.jpg)

**Comment by tagliala** [comment] 2015-12-31 09:11
duplicate of #5586 , please +1 that request

closing here

**Closed by tagliala** 2015-12-31 09:11 UTC
