### ISSUE TITLE
Problem with glyphs

### ISSUE THREAD

**Issue by shehi** [FortAwesome/Font-Awesome#8969] opened 2016-04-13 08:38 UTC
![image](https://cloud.githubusercontent.com/assets/653569/14487563/ed9d2d20-016b-11e6-9de0-3c80c91efc81.png)

These are glyphs ```check-square``` and ```square-o```. As you can see, the metrics among this kinda square-shaped glyphs change from glyph to glyph. In this condition, it's impossible to use these glyphs for, let's say two states of a checkbox (checked and not-checked states). Since glyph metrics are differing, you have to write tons of CSS to make them look alike, which doesn't really work.

Question is: are you guys planning on fixing these metrics so that they all have same base and height?

**Comment by shehi** [comment] 2016-04-13 08:39
If need be, I can fix all of them and send in a PR.

**Comment by tagliala** [comment] 2016-04-13 09:24
I'm going to consider this a duplicate of #4649, which is scheduled for 5.0.0

Thanks for your willing to help but at the moment we are not accepting PR containing modified font files.

**Closed by tagliala** 2016-04-13 09:24 UTC
