### ISSUE TITLE
Icon Request: fa-importexport

### ISSUE THREAD

**Issue by GaryWongCoins** [FortAwesome/Font-Awesome#9461] opened 2016-06-23 12:22 UTC
it will be good if we have a icon to show import and export in one logo

**Comment by tagliala** [comment] 2016-06-23 12:46
could you please provide an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by danielone** [comment] 2016-07-12 22:59
I would actually like one for import and one for export

Something like this for export
https://www.iconfinder.com/icons/979791/arrow_direction_exit_go_move_out_right_icon#size=128

import (similar to above but arrow points in)
https://www.iconfinder.com/icons/979790/arrow_go_in_left_icon#size=128

**Comment by tagliala** [comment] 2016-07-13 09:30
Duplicate of #1020 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-13 09:30 UTC
Labels: waiting for feedback

**Comment by danielone** [comment] 2016-07-13 23:56
Sorry about that. Will do moving forward
