### ISSUE TITLE
Icon request: metal fork / sign of the horns

### ISSUE THREAD

**Issue by CDaxi** [FortAwesome/Font-Awesome#7313] opened 2015-08-26 22:01 UTC
Hi there,

i found the rock-o, paper-o, scissors-o, lizard-o and spock-o - nice to see for all bbt fans.
But i'm missing a metal fork icon for all lovers of metal and rock music.

Examples:
https://en.wikipedia.org/wiki/Sign_of_the_horns
http://www.premierguitar.com/articles/What_Does_the_Horn_Hand_Mean

**Comment by caduvieira** [comment] 2015-08-27 20:09
Dupe of #3077

**Closed** 2015-09-14 15:50 UTC
