### ISSUE TITLE
Icon request: chevrons-opposite in/out

### ISSUE THREAD

**Issue by tonysamperi** [FortAwesome/Font-Awesome#14767] opened 2019-03-18 09:25 UTC
I would find useful to have single icons like these

![image](https://user-images.githubusercontent.com/5957244/54519932-daa1b280-4967-11e9-86f4-8b0e78af156e.png)

They're usable for shrink and expand, or in my case I need the first one for a slider starting from the center.

**Comment by tagliala** [comment] 2019-03-18 09:39
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/24/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by tonysamperi** [comment] 2019-03-18 09:52
Hi Geremia,

thanks for the tip. Unfortunately I'm using just the fontawesome scss in an Angular project.
I'm not even using the Angular imports, since generally I can adjuste my icons with `fa-2x` or some simple css styling (usually color).

PS. the <> image could also mean **embed** or **source**

**Comment by tagliala** [comment] 2019-03-18 10:22
> I'm using just the fontawesome scss in an Angular project.

It could also be implemented with scss, by taking advantage of pseudoelements: https://jsfiddle.net/tagliala/1o7sevju/12/

> PS. the <> image could also mean embed or source

Source is already available with this style: https://fontawesome.com/icons/code?style=solid

**Comment by tonysamperi** [comment] 2019-03-18 10:39
Thanks.
Good idea!

Yes I know source exists already, but it has the slash. 
But for example if you see up here...
![image](https://user-images.githubusercontent.com/5957244/54524511-69b3c800-4972-11e9-9512-5c453a949e9d.png)

**Comment by sensibleworld** [comment] 2024-07-11 19:07
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/8144)

**Closed by sensibleworld** 2024-07-11 19:07 UTC
Labels: new icon, arrows (category), Duplicate

**Comment by tonysamperi** [comment] 2024-07-14 18:54
Well better later than never!
By the way at the time I implemented via CSS like suggested!

Cheers
