### ISSUE TITLE
wargaming

### ISSUE THREAD

**Issue by Rodion15** [FortAwesome/Font-Awesome#15795] opened 2019-11-10 23:12 UTC
icon wargaming plz!

**Comment by tagliala** [comment] 2019-11-11 11:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10464, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-11-11 11:16 UTC
