### ISSUE TITLE
 Icon request: icon-customer-support

### ISSUE THREAD

**Issue by mrcasablr** [FortAwesome/Font-Awesome#13220] opened 2018-05-26 17:31 UTC
Looking for a customer support icon. Preferable a person with a head-set
![man-customer-care-service-support-icon-vector-flat-color-pictogram-illustration-person-profile-human-avatar-call-centre-97288329](https://user-images.githubusercontent.com/22866157/40578885-e3bf4e8e-6139-11e8-8be4-92fc3149f6f0.jpg)

**Comment by tagliala** [comment] 2018-05-26 19:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5586 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-26 19:16 UTC

**Comment by almalak20** [comment] 2019-09-18 05:04
#5586
