### ISSUE TITLE
Icon request: fa-brain

### ISSUE THREAD

**Issue by mabotn** [FortAwesome/Font-Awesome#12439] opened 2018-02-25 17:00 UTC
It'd be awesome to create an icon for the brain !
and thanks for the amazing job you did

**Comment by tagliala** [comment] 2018-02-25 17:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2075 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-25 17:12 UTC
