### ISSUE TITLE
Icon Request: icon-action

### ISSUE THREAD

**Issue by fr0980y** [FortAwesome/Font-Awesome#7398] opened 2015-09-05 21:16 UTC
Maybe a little stick-figure that is running.

**Comment by user-e** [comment] 2015-09-09 17:50
There is a newer icon request that shows a similar icon to this one.
No need to say "search before +" though, as your icon request
appeared before that one.
https://github.com/FortAwesome/Font-Awesome/issues/7427

**Comment by tagliala** [comment] 2015-09-13 09:31
duplicate of #844 / #1156 ?

**Closed** 2022-03-13 14:48 UTC
Labels: waiting for feedback
