### ISSUE TITLE
Icon request: Intuit Quickbooks

### ISSUE THREAD

**Issue by acsamusements** [FortAwesome/Font-Awesome#18846] opened 2022-03-23 20:25 UTC
Would love to see a QB icon?  I'm writing a web app that uses the integration with it and need to be able to show an icon with green/red to show if connected or not.

**Comment by tagliala** [comment] 2022-03-23 20:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2117, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed as completed by tagliala** 2022-03-23 20:53 UTC
