### ISSUE TITLE
Icon request: icon-shower

### ISSUE THREAD

**Issue by bobjohnston2000** [FortAwesome/Font-Awesome#9335] opened 2016-06-04 04:25 UTC
I would like a shower icon to use as icon fo rnumber of bathrooms in my real estate website

Like this... (See image file)

![shower](https://cloud.githubusercontent.com/assets/19742059/15797555/f78869c2-2a46-11e6-9bb7-b20899017581.JPG)

**Comment by aethior** [comment] 2016-06-04 15:57
Hi @bobjohnston2000,

This request is duplicate of #708. Please +1 that.

Regards.

**Closed** 2016-06-04 20:18 UTC
