### ISSUE TITLE
 Icon request: icon-presentation

### ISSUE THREAD

**Issue by mrcasablr** [FortAwesome/Font-Awesome#13221] opened 2018-05-26 17:33 UTC
![presentation-icon](https://user-images.githubusercontent.com/22866157/40578870-af45cb06-6139-11e8-82c0-e5147b1a40e2.png)
Could not find a icon that looks like a slide presentation that looks like a whiteboard with a stand

**Comment by tagliala** [comment] 2018-05-26 19:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #866, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-26 19:16 UTC
