### ISSUE TITLE
Icon Edit: fa-cc-mastercard

### ISSUE THREAD

**Issue by yabhiram** [FortAwesome/Font-Awesome#9684] opened 2016-07-31 05:04 UTC
Hello,

The mastercard rebranded it's logo. Is there a way the mastercard icon be changed to represent the changes mastercard made it to it's logo? 

Thank you

**Comment by tagliala** [comment] 2016-07-31 09:04
Duplicate of #9633, planned for the new release

**Closed by tagliala** 2016-07-31 09:04 UTC
