### ISSUE TITLE
Icon request: camera-switch

### ISSUE THREAD

**Issue by thinkcoin** [FortAwesome/Font-Awesome#14253] opened 2018-11-09 15:33 UTC
I would like to suggest a icon for extend camera usageicon, a “camera-switch” icon. 
Something to use on “change camera” button or similars, usually change the hear camera to front and vice versa.

There's some sample in this URL
https://www.iconfinder.com/icons/1279034/camera_switch_icon

Thank you very much!

**Comment by tagliala** [comment] 2018-11-09 15:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3956, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-11-09 15:56 UTC
