### ISSUE TITLE
Icon Request: fa-dj

### ISSUE THREAD

**Issue by Steffi3rd** [FortAwesome/Font-Awesome#5979] opened 2015-03-16 09:21 UTC
https://www.iconfinder.com/icons/465094/dj_hand_music_play_sound_vinyl_icon#size=128

**Comment by tagliala** [comment] 2015-03-16 13:45
duplicate of #1080, please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-03-16 13:45 UTC

**Comment by nagulian** [comment] 2015-03-19 13:39
+1
