### ISSUE TITLE
Icon Request: fa-truck

### ISSUE THREAD

**Issue by amyelzea** [FortAwesome/Font-Awesome#12988] opened 2018-04-30 18:09 UTC
Please create frontal truck icon. We have a few icons, that would like to have extended access to via Font-Awesome.
Thanks.

Truck
Frontal Truck

![frontal-truck](https://user-images.githubusercontent.com/24258716/39442661-a67ba6c0-4c77-11e8-8ec9-ecc4fff2e43b.png)

**Comment by tagliala** [comment] 2018-04-30 18:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12075, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-30 18:36 UTC
