### ISSUE TITLE
Icon request: Scratch

### ISSUE THREAD

**Issue by Chimi-Cat** [FortAwesome/Font-Awesome#19742] opened 2023-05-30 17:00 UTC
We need like the scratch logo on this. Like it could be the full word or just the S
![IMG_3581](https://github.com/FortAwesome/Font-Awesome/assets/135052030/9a56a6b5-cb52-4d78-bcb1-2ca2d2b4b3df)
![IMG_3582](https://github.com/FortAwesome/Font-Awesome/assets/135052030/012775b0-b599-404d-b295-e4eaf4fb111e)

**Comment by KadenAE** [comment] 2023-06-24 19:52
I think the last one isn't used anymore, and the first one just isn't what font awesome is for, we may as well have the full Google logo as well etc. 

I don't know if the Scratch cat is an icon or not, bit that's perfect on what's needed.

**Comment by aethior** [comment] 2023-08-09 23:20
Duplicate of #9336

cc @tagliala

**Closed as completed** 2023-08-10 09:46 UTC
