### ISSUE TITLE
Icon request: hand-point-click

### ISSUE THREAD

**Issue by haveben** [FortAwesome/Font-Awesome#15692] opened 2019-10-15 14:25 UTC
**What can it be used for?**
This icon can be used to guide an end user or represent a click is required or available.  Initially, I would suggest hand-point-help and the finger point to a question mark.  

My use case is that I have information to display in a popover and do not want to use a "button" as there are too many on the page.  I worry about using a question mark or "i" on the page.  While my end users are professors and are brilliant in their field, they can be pretty ignorant when it comes to technology.

**Example image (optional)**
![click 0](https://user-images.githubusercontent.com/19741411/66840335-824a8780-ef2d-11e9-9f99-790c5728d045.jpg)

![click 0a](https://user-images.githubusercontent.com/19741411/66840403-98584800-ef2d-11e9-9a65-ea47824fa74d.jpg)

![click 1](https://user-images.githubusercontent.com/19741411/66840420-9ee6bf80-ef2d-11e9-8d8e-0c2ee5c95f1b.png)

![click 3](https://user-images.githubusercontent.com/19741411/66840438-a6a66400-ef2d-11e9-8bfc-0957f9cb9486.jpg)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X ] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by chrise86** [comment] 2022-09-15 08:02
![icons8-natural-user-interface-2-100](https://user-images.githubusercontent.com/616956/190349427-2fb9ded5-6032-4369-ba03-55fd9624155a.png)

This would be great! I really like this sort of design.

**Comment by jwp528** [comment] 2022-10-20 21:26
This is exactly the icon I was looking for. good to know someone already suggested it. I'll try to find something else in the meantime.

![image](https://user-images.githubusercontent.com/2299134/197061921-e653ae86-d58e-4ce3-8e3e-746ee4d0025e.png)

**Comment by sensibleworld** [comment] 2024-07-11 18:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/8721)

**Closed by sensibleworld** 2024-07-11 18:23 UTC
Labels: new icon, design (category), Duplicate
