### ISSUE TITLE
Problems with Font Awesome and other css classes

### ISSUE THREAD

**Issue by robisonweb** [FortAwesome/Font-Awesome#11523] opened 2017-09-13 20:20 UTC
Hello, I'm having a problem with Awesome Font, I'm creating a page that I want to use the icons, I started typing the Awesome Font url, it shows the icons, then it includes 2 more CSS files, boot.css and style.css, after icons have stopped being displayed.

I use the Awesome Font link:
`<link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
`
Ex: showing the icons.
[http://infoxweb.com.br/wp-content/uploads/2017/09/logo_font_awoson_2.png](url)

Ex: with error when I add the classes: boot.css and style.css
[http://infoxweb.com.br/wp-content/uploads/2017/09/logo_font_awoson_3.png](url)

Has anyone ever experienced this?

Also I would like that in resolutions smaller than 480px only the icon was shown, and the text was hidden can you help me?

[ ]'s Robison

**Comment by tagliala** [comment] 2017-09-14 16:09
Hi,

please check that your custom css rules are not messing up with css.

Please use your development console to check rules applied to your font awesome element

Troubleshooting guidelines: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

I'm going to close this because I'm pretty sure it is not caused by Font Awesome.

PS: please notice that you are using version 4.3.0, actually Font Awesome is at 4.7.0.

**Closed by tagliala** 2017-09-14 16:09 UTC

**Comment by robisonweb** [comment] 2017-09-14 16:54
Thanks, actually a rule of my CSS class was causing the problem.

[  ]'s Robison
