### ISSUE TITLE
Icon Request: fa-panorama fa-360

### ISSUE THREAD

**Issue by airaromina** [FortAwesome/Font-Awesome#11080] opened 2017-05-17 14:35 UTC
I, want to use to show my 360 panoramas on my portfolio!
![pano](https://cloud.githubusercontent.com/assets/28759289/26159412/e408cbb6-3af4-11e7-95f3-ff9dfcd89c45.png)
![360](https://cloud.githubusercontent.com/assets/28759289/26159413/e42ae552-3af4-11e7-9b99-f5fbae96451e.png)

**Comment by tagliala** [comment] 2017-05-17 15:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #772 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-17 15:55 UTC
