### ISSUE TITLE
Icon request: fa-cloud-dash

### ISSUE THREAD

**Issue by mentorgashi** [FortAwesome/Font-Awesome#14751] opened 2019-03-14 16:44 UTC
### What can it be used for?
For synced files/changes in apps we use the cloud icon which is nice. 
Meanwhile for the changes that remain not synced we currently use the fa-repeat icon to encourage syncing however there are cases where cloud dash (not-synced) meaning not in the cloud, comes very useful.

### Example image (optional)
<img src="http://mentorgashi.com/cloud-dash.jpg" />

**Comment by tagliala** [comment] 2019-03-14 17:21
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12554, please add a 👍 reaction to that request.

Please also take a look at my comment there, you will find a solution: https://github.com/FortAwesome/Font-Awesome/issues/12554#issuecomment-472973828

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-03-14 17:21 UTC
