### ISSUE TITLE
Icon request: vlabel

### ISSUE THREAD

**Issue by gooloonetwork** [FortAwesome/Font-Awesome#17381] opened 2020-11-09 00:47 UTC
**What can it be used for?**
This could be very useful to mark out vegan products in a product category (f.ex. webshops) or for bloggers and editors to show that described product is vegan.

**Example image (optional)**
![0](https://user-images.githubusercontent.com/35598280/98489213-5d5a3e00-222d-11eb-99d1-65200283f7be.png)

**Icon request checklist**
- [single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-11-09 08:49
Hi!

Thanks for being part of the Font Awesome Community.

So the "V with a leaf" has been registered by someone?

The graphical part of the logo is a duplicate of #4950

**Comment by sensibleworld** [comment] 2024-07-12 13:11
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with https://github.com/FortAwesome/Font-Awesome/issues/12590

**Closed by sensibleworld** 2024-07-12 13:11 UTC
Labels: waiting for feedback
