### ISSUE TITLE
Icon Request: Spigot Icon

### ISSUE THREAD

**Issue by Plusgames** [FortAwesome/Font-Awesome#9705] opened 2016-08-04 22:06 UTC
I will use this to link to my Account on Spigotmc.org

![](http://worldartsme.com/images/spigot-clipart-1.jpg)

Yours

plusgames

**Comment by aethior** [comment] 2016-08-08 01:56
Duplicate of #8270.

cc @tagliala

**Closed** 2016-08-08 09:10 UTC
