### ISSUE TITLE
Icon Request: fa-feather

### ISSUE THREAD

**Issue by ricardobayes** [FortAwesome/Font-Awesome#9497] opened 2016-06-29 16:59 UTC
Hi,

Since many of these icons are used by startups describing product features, a feather indicating light weight would be extremely useful.

Ricardo

**Comment by tagliala** [comment] 2016-06-29 17:06
Duplicate of #9082, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-29 17:06 UTC
