### ISSUE TITLE
Icon request: dinosaur-trex

### ISSUE THREAD

**Issue by haunted-path** [FortAwesome/Font-Awesome#19589] opened 2023-03-02 19:50 UTC
Requesting a dinosaur-trex icon which looks like a Tyrannosaurus.  I imagine you can use the existing dragon icon, remove the wings and horns then maybe add legs, stubby arms, and round out the head.  I know it would work for sites like museums or history pages.  We are currently using the dragon for our purposes but our users comment that it isn't really a dinosaur.

You could also create more than one dinosaur icon so have dinosaur-trex, dinosaur-triceratops, dinosaur-raptor, etc.  The triceratops can also use the dragon model without the wings and with a new horn on the head.  Then orient the body and tail and then add legs.   A raptor would work similarly to the Tyrannosaurus.

**Comment by tagliala** [comment] 2023-03-08 21:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1580, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-03-08 21:12 UTC
