### ISSUE TITLE
Icon request: Icon-PianoKeys

### ISSUE THREAD

**Issue by jsepeta** [FortAwesome/Font-Awesome#11289] opened 2017-07-13 22:06 UTC
I would like an icon to represent piano-style keyboards. I've been helping people to restore vintage synthesizers for nearly 20 years, and it would be helpful to differentiate between piano keyboard and computer keyboard when building web documentation.

![pianokeys](https://user-images.githubusercontent.com/30161333/28189844-83830a38-67ed-11e7-8961-3a603bc50023.jpg)

**Comment by tagliala** [comment] 2017-07-13 22:46
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #770, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-13 22:46 UTC
