### ISSUE TITLE
Icon request: GraphQL

### ISSUE THREAD

**Issue by SamJamWillingham** [FortAwesome/Font-Awesome#17244] opened 2020-10-06 18:17 UTC
**What can it be used for?**
Building a portfolio, tutorials/tutorial videos, links to github repo or site.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment] 2022-05-21 01:56
>GraphQL is an open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data. GraphQL was developed internally by Facebook in 2012 before being publicly released in 2015. ([more info](https://en.wikipedia.org/wiki/GraphQL))
https://graphql.org/

@tagliala `brand (category)` label for this request?

**Comment by tagliala** [comment] 2022-05-21 07:39
This request is a duplicate of #12048, please add a 👍 reaction to that request.

**Closed by tagliala** 2022-05-21 07:39 UTC
