### ISSUE TITLE
Icon Request: fa-remove-o

### ISSUE THREAD

**Issue by scooterlord** [FortAwesome/Font-Awesome#8580] opened 2016-02-15 14:28 UTC
Hello, can you pretty please a thinner verion of the X button? Although all the other icons are great to use, this is too... fat compared to all other icons.

**Comment by tagliala** [comment] 2016-02-15 18:13
duplicate of #1540 , please +1 that request

closing here

**Closed by tagliala** 2016-02-15 18:13 UTC
