### ISSUE TITLE
Icon request: ship-steering-wheel

### ISSUE THREAD

**Issue by rychoo2** [FortAwesome/Font-Awesome#11806] opened 2017-11-27 11:51 UTC
Would be great to have an icon for ship steering wheel, something like this:
![image](https://user-images.githubusercontent.com/4820692/33265342-92b52fa0-d371-11e7-91b7-6e60845125d3.png)

Good candidate to work with spin animation as well.

Thanks

**Comment by PeterShaggyNoble** [comment] 2017-11-28 09:36
Duplicate of #9791.

**Comment by tagliala** [comment] 2017-11-28 10:35
@PeterShaggyNoble thanks. Missed that one

**Closed by tagliala** 2017-11-28 10:35 UTC
Labels: new icon, web application icons
