### ISSUE TITLE
Icon Request: fa-Actual Size

### ISSUE THREAD

**Issue by derryTWMP** [FortAwesome/Font-Awesome#7956] opened 2015-11-22 19:53 UTC
need an icon to zoom in / zoom out of a picture from the default size it was generated at to the actual size, same functionality as in Windows Photo Viewer .  Icon is a rectangle surrounded by 4 triangles, which are pointing into the rectangle 
![actual size](https://cloud.githubusercontent.com/assets/15970386/11325923/9d00ed04-9152-11e5-831d-dddeb2fc2bc9.PNG)

**Comment by tagliala** [comment] 2015-11-22 19:58
Dup of #1468 ?

**Comment by derryTWMP** [comment] 2015-11-23 09:11
hi there, im afraid that icon is not what i need . is it possible to have this ? 
![actual size](https://cloud.githubusercontent.com/assets/15970386/11332972/29cb8f5e-91c2-11e5-9728-9adbc9af84fd.PNG)

**Comment by derryTWMP** [comment] 2015-11-23 10:54
better mock up : 
![actual size](https://cloud.githubusercontent.com/assets/15970386/11334958/7ce682e4-91d0-11e5-824e-02e8dc532b76.png)

**Comment by caduvieira** [comment] 2015-11-23 11:27
i think this is dupe of #7198

**Comment by tagliala** [comment] 2015-11-23 11:46
Oh yes,

Thanks @caduvieira 

Closing here as a dup (subset) of #7198

**Closed by tagliala** 2015-11-23 11:46 UTC
Labels: waiting for feedback
