### ISSUE TITLE
Icon-Request Star of Life

### ISSUE THREAD

**Issue by smokinace** [FortAwesome/Font-Awesome#11546] opened 2017-09-21 17:44 UTC
I am working on our local Volunteer Fire Department website and I could really use the Star of Life Icon. I looked and couldn't find it in the inventory. Any help would be greatly appreciated.

https://en.wikipedia.org/wiki/File:Star_of_life2.svg

**Comment by tagliala** [comment] 2017-09-21 17:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3036, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-21 17:48 UTC
