### ISSUE TITLE
hanger please

### ISSUE THREAD

**Issue by lidfill** [FortAwesome/Font-Awesome#7638] opened 2015-10-08 11:56 UTC
hi can you create a hanger similar to http://www.endlessicons.com/wp-content/uploads/2013/10/clothes-hanger-icon-614x460.png    thanks!

---
edit by tagliala: fixed example

**Comment by tagliala** [comment] 2015-10-08 14:37
duplicate of #1659 , please +1 that request

closing here

**Closed by tagliala** 2015-10-08 14:37 UTC
