### ISSUE TITLE
Icon Request: icon-gluten-free for Gluten-Free awareness

### ISSUE THREAD

**Issue by webscot** [FortAwesome/Font-Awesome#8294] opened 2016-01-08 18:14 UTC
Icon Request: icon-gluten-free

Gluten-Free icon - Useful association icon for web use and for product labeling.

Here are a couple examples readily found online.

![gluten-free-no-wheat-icon](https://cloud.githubusercontent.com/assets/16613531/12205574/d6474f7a-b5f8-11e5-964d-489bdb951eef.png)

![gluten-free-icon](https://cloud.githubusercontent.com/assets/16613531/12205575/d65e77ae-b5f8-11e5-900d-17584b26d2b1.png)

**Comment by tagliala** [comment] 2016-01-08 18:23
duplicate of #2405 , please +1 that request

closing here

**Closed by tagliala** 2016-01-08 18:23 UTC
