### ISSUE TITLE
Icon Request: fa-blackberry

### ISSUE THREAD

**Issue by nosaku** [FortAwesome/Font-Awesome#9462] opened 2016-06-23 13:10 UTC
Requesting an icon for good old Blackberry.
![blackberry](https://cloud.githubusercontent.com/assets/5987370/16304208/02d6f750-3972-11e6-988c-e491c042ad65.png)

**Comment by tagliala** [comment] 2016-06-23 15:24
Duplicate of #1537 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-23 15:24 UTC
