### ISSUE TITLE
Icon Request: JavaScript

### ISSUE THREAD

**Issue by asazs** [FortAwesome/Font-Awesome#11281] opened 2017-07-12 10:04 UTC

**Comment by tagliala** [comment] 2017-07-12 11:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1711 , please add a 👍  reaction to that request.

Please also consider using [mfizz](http://fizzed.com/oss/font-mfizz)

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-12 11:25 UTC
