### ISSUE TITLE
Icon Request: icon-multiPlatform

### ISSUE THREAD

**Issue by edesdan** [FortAwesome/Font-Awesome#5899] opened 2015-03-09 14:22 UTC
It could be very handy to have an icon like this one:
![multiplatform](https://cloud.githubusercontent.com/assets/5745049/6556734/649291f4-c667-11e4-80ae-78cc0000dc33.PNG)

Use cases: every case when you need to show that your product is cross platform (it runs on a Desktop, on a mobile device, on a tablet).

**Comment by tagliala** [comment] 2015-03-09 15:20
duplicate of #1446 , please +1 that request

closing here

**Closed by tagliala** 2015-03-09 15:20 UTC
