### ISSUE TITLE
Icon request: fa-pkg

### ISSUE THREAD

**Issue by YesThatAllen** [FortAwesome/Font-Awesome#10513] opened 2017-01-11 17:52 UTC
When we'd like to indicate that a pkg is available from our site, a pkg icon would be useful to use in buttons

![image](https://cloud.githubusercontent.com/assets/2879972/21859996/65b0770e-d7f4-11e6-88db-31e9548047eb.png)

**Comment by tagliala** [comment] 2017-01-11 18:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #908 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-01-11 18:33 UTC
