### ISSUE TITLE
Weird behavior in Firefox with Font Awesome 5 Pro, watermark behind the actual icon

### ISSUE THREAD

**Issue by nammi-kobler** [FortAwesome/Font-Awesome#18317] opened 2021-09-30 15:10 UTC
**Describe the bug**
We are using the Font Awesome 5 Pro suite, with several icons on our site.
Suddenly we encountered a weird bug; basically the unicode is kinda printed as a weird watermark behind the actual icon.
Only happens in Firefox, not Chrome.
Toggling off the ::after content removes the watermark.
Will add screenshots.

**To Reproduce**
No idea how to reproduce, it doesn't happen other places in the app. Changing the icon does not remove the watermark.

**Expected behavior**
No watermark like everything else.

**Screenshots**

<img width="347" alt="Screenshot 2021-09-30 at 16 58 41" src="https://user-images.githubusercontent.com/88322539/135482078-f42ef71f-ae14-422f-92d8-ccd8df30f4dc.png">

<img width="336" alt="Screenshot 2021-09-30 at 16 58 50" src="https://user-images.githubusercontent.com/88322539/135482098-49996fb7-deb2-4490-a8d1-06a8dbcc597b.png">

<img width="319" alt="Screenshot 2021-09-30 at 16 58 56" src="https://user-images.githubusercontent.com/88322539/135482114-2caa63d9-296f-4fd3-a7e4-223c89badc37.png">

**Version and implementation**
Version: 5.15.4 Pro
Browser and version: Firefox 92.0.1

Implemented with className using styled, functional React components.

**Comment by tagliala** [comment] 2021-09-30 15:39
Hi!

Thanks for being part of the Font Awesome Community.

I'm not able to reproduce this issue, but the watermark (that I'm going to explain later) is not the only thing that is broken

Demo: https://jsfiddle.net/tagliala/5y4afu2c/4/

Are you able to provide a reproducible test case?

> Toggling off the ::after content removes the watermark.

The watermark is just the secondary unicode point of the icon. For some reason the browser is not able to render it, so it is falling back to a square containing that unicode point

Ref: https://fontawesome.com/v5.15/icons/caret-down?style=duotone

![image](https://user-images.githubusercontent.com/556268/135486024-43c43bda-3350-4aa4-9080-714954bf12ea.png)

The weird thing is that also the primary code does not look correct, it should be the left side of caret-down, truncated in the middle, but it looks like it is loading another glyph I can't recognize

PS: as a Font Awesome Pro customer, you can ask for dedicated support by sending an email at hello@fontawesome.com

**Comment by nammi-kobler** [comment] 2021-10-01 09:18
Hi!

I was able to figure out why.

The font-family was set to "Font Awesome 5 Pro” and not “Font Awesome 5 Duotone”, changing this fixed this error.

Am I correct that we shouldn’t explicitly set the font-family when using the all.css file?

Thnx,

Nam-Kha

**Comment by tagliala** [comment] 2021-10-01 11:09
> Am I correct that we shouldn’t explicitly set the font-family when using the all.css file?

Correct!

Could you please clarify why the font family was explicitly set?

I can't figure out a use case when you need to set the Font Awesome family on `fa` default classes when using the provided stylesheets

Meanwhile, closing here

**Closed by tagliala** 2021-10-01 11:09 UTC
Labels: waiting for feedback

**Comment by nammi-kobler** [comment] 2021-10-01 11:44
To be honest; I think the fact that finding the proper documentation is a bit of a hassle is a big factor. 
Since we're using Font Awesome 5 and not the 6 Beta - you have to be in-depth to understand there's a big difference how to use it. 

I have been using FA before, and I remember it was a lot easier to just read the quick start, add the css to your header, and use class names. Nowadays there's like 5 different ways to use FA, and I think it's not always easy to find the correct documentation, especially when you just google "font awesome <problem>". And that there are several versions out as well as older documentation (I think I have seen both v3 and v4). Idk maybe just an easier way on the homepage to select the correct version for the support/documentation part would be nice.

**Comment by tagliala** [comment] 2021-10-01 12:25
Thanks for the feedback

> Nowadays there's like 5 different ways to use FA

At least 5. If we count that FA has two different implementations - CSS and SVG+JS - and each implementation can be used with Kit, CDN, self-hosted, via npm. Then there are official packages for third-party libraries like React, Angular, Vue, Wordpress. I should also mention that occasionally third-party asset bundlers like webpack and rollup are involved in the process.

So yes, you still have the ability to drop in a line of html and start with Font Awesome, but that's not the case for everyone

> Idk maybe just an easier way on the homepage to select the correct version for the support/documentation part would be nice.

Now the team is focusing on the FA6 release. When the main website will switch to FA6, there will be room for improvement for the older docs. A dropdown would definitely help
