### ISSUE TITLE
Icon request: fa-shredder

### ISSUE THREAD

**Issue by alicemp1** [FortAwesome/Font-Awesome#11152] opened 2017-06-09 11:19 UTC

**Comment by tagliala** [comment] 2017-06-09 11:21
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #shredder, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-09 11:21 UTC
