### ISSUE TITLE
Icon request: publons

### ISSUE THREAD

**Issue by alperyazar** [FortAwesome/Font-Awesome#17753] opened 2021-03-20 19:21 UTC
**What can it be used for?**
https://publons.com/ is an academic platform like Orcid where many researchers (according to their claim, probably yes) have profiles on it. This can be useful on portfolio pages and links for Publons profiles. 

**Example image (optional)**
https://en.wikipedia.org/wiki/Publons#/media/File:Publons_logo.png or https://publons.com/favicon.ico

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate. **No** but #17333 looks stale and #13668 doesn't have current PR template (it is 3 years old!)
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-03-20 20:12
> No but #17333 looks stale and #13668 doesn't have current PR template (it is 3 years old!)

Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13668, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-20 20:12 UTC
