### ISSUE TITLE
Icon request: Flipagram logo

### ISSUE THREAD

**Issue by hugnat** [FortAwesome/Font-Awesome#8671] opened 2016-02-29 04:20 UTC
Will there be a Flipagram icon in FontAwesome soon?

**Comment by tagliala** [comment] 2016-02-29 10:07
Duplicate of #7383, you already +1'd that request

Please take e look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here

**Closed by tagliala** 2016-02-29 10:07 UTC
