### ISSUE TITLE
Pseudo-elements are not working with release v5.0.2

### ISSUE THREAD

**Issue by livan75** [FortAwesome/Font-Awesome#12014] opened 2017-12-30 16:33 UTC
Actually with this release, it's the element text before which (or, I guess, after which) you put your icon that is simply not showing. 

For example if you have a::before, the text link will not appear on your page...

Maybe I'm doing something wrong, but I didn't get this issue with the previous release.

**Comment by tagliala** [comment] 2017-12-30 18:20
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a fiddle showing the issue?

SVG: start with https://jsfiddle.net/tagliala/h3Lbjh0t/
CSS: start with https://jsfiddle.net/tagliala/nba5dg64/


Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by livan75** [comment] 2018-01-03 10:14
Can't reproduce it in a fiddle. But, sorry, i did found this issue has already been discuss : #11995. And it's a bug (which is tough to reproduce like robmadole said)

**Comment by tagliala** [comment] 2018-01-03 12:58
Good.

Closing here as a duplicate of #11995

**Closed by tagliala** 2018-01-03 12:58 UTC
Labels: waiting for feedback
