### ISSUE TITLE
Icon Request: fa-blog

### ISSUE THREAD

**Issue by mj13131** [FortAwesome/Font-Awesome#10923] opened 2017-04-11 08:44 UTC
make a icon for go to blog

**Comment by tagliala** [comment] 2017-04-11 08:47
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1088 or #455 , please add a 👍  reaction to the proper request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-11 08:47 UTC
