### ISSUE TITLE
Icon Request: Browsers; Chrome, Firefox, and Safari

### ISSUE THREAD

**Issue by nodesocket** [FortAwesome/Font-Awesome#6621] opened 2015-06-02 02:27 UTC
Chrome, Firefox, Safari icons please.

````
<i class="fa fa-chrome"></i>
<i class="fa fa-firefox"></i>
<i class="fa fa-safari"></i>
````

**Comment by raghunayyar** [comment] 2015-06-02 10:25
even Internet Explorer, Opera will be welcome.

**Comment by Denni007** [comment] 2015-06-02 11:41
+1

**Comment by plaperdr** [comment] 2015-06-02 12:02
This is a duplicate of #219. I think you should +1 there.

**Comment by tagliala** [comment] 2015-06-02 12:36
@plaperdr thanks

closing here

**Closed by tagliala** 2015-06-02 12:36 UTC
