### ISSUE TITLE
Icon  Update request: fa-gitlab

### ISSUE THREAD

**Issue by varghesejose2020** [FortAwesome/Font-Awesome#19120] opened 2022-06-12 06:19 UTC
Brand Name
GitLab

Official Resources for Icon and Color
https://about.gitlab.com/press/press-kit/

![GitLab New Icon](https://about.gitlab.com/images/press/logo/png/gitlab-logo-600.png)

**Comment by tagliala** [comment] 2022-06-12 08:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19015 and the update is in progress

Closing here

**Closed as completed by tagliala** 2022-06-12 08:22 UTC
