### ISSUE TITLE
Icon Request: Handshake

### ISSUE THREAD

**Issue by jaccao** [FortAwesome/Font-Awesome#9383] opened 2016-06-09 11:50 UTC
first of all, great job!
I don't found a handshake icon, I believe that this icon will improve the project,
thanks,

**Comment by tagliala** [comment] 2016-06-09 12:43
Duplicate of #878 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-09 12:43 UTC
