### ISSUE TITLE
Icon request: fa-quad / fa-atv

### ISSUE THREAD

**Issue by fusionsquare** [FortAwesome/Font-Awesome#14558] opened 2019-01-28 15:39 UTC
### What can it be used for?

Outdoor, Traveling, Fun 

### Example image (optional)

![image](https://user-images.githubusercontent.com/1528231/51846826-a839e880-231a-11e9-92e9-87869f257362.png)

![image](https://user-images.githubusercontent.com/1528231/51847008-1088ca00-231b-11e9-881d-425b24003922.png)

![image](https://user-images.githubusercontent.com/1528231/51846868-bd167c00-231a-11e9-879a-a355928f2c2f.png)

I think, there is a huge quad community in every country. FA includes a motorcycle, so we need a quad icon too :)

**Comment by danielcongrove** [comment] 2019-08-16 18:12
+1, would be nice to see some motorsports icons (land and water based)

**Comment by jonathanroy** [comment] 2020-02-08 18:00
+1, I need this icon.

**Comment by lsrael22T** [comment] 2020-11-04 18:31
+1, I need this icon too

**Comment by Aldus83** [comment] 2024-03-08 10:05
+1

**Comment by mysterycreative** [comment] 2024-04-09 01:38
+1

**Comment by sensibleworld** [comment] 2024-07-11 19:07
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/19873)

**Closed by sensibleworld** 2024-07-11 19:07 UTC
Labels: new icon, transportation (category), Duplicate
