### ISSUE TITLE
Icon Request: glassdoor-logo

### ISSUE THREAD

**Issue by Jhynnifer** [FortAwesome/Font-Awesome#10793] opened 2017-03-15 15:32 UTC
Along with icons like twitter, facebook, etc, our company would like to list the glassdoor logo to link to the site. 

This is the logo:

![glass-door-icon](https://cloud.githubusercontent.com/assets/24482862/23956425/99b37806-096a-11e7-8777-ece70f2e400e.png)

**Comment by tagliala** [comment] 2017-03-15 15:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6422, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-15 15:36 UTC

**Comment by Jhynnifer** [comment] 2017-03-15 15:41
Hi sorry about the only one I saw was from 2015 and had no resolution!

Jennifer Cooley | Web Designer
Kennedy Communications
D: 608.443.0966 | jcooley@kennedyc.com
9 Odana Ct, Suite 200 | Madison, WI 53719
