### ISSUE TITLE
Icon request: TypeScript

### ISSUE THREAD

**Issue by Nojil** [FortAwesome/Font-Awesome#13195] opened 2018-05-23 14:27 UTC
When creating a webpage and detailing my skill set i like to but the corresponding logo icon in front of the skill. So for Angular i put the angular icon and html i put the HTML5 icon.

![ts1](https://user-images.githubusercontent.com/11978772/40430755-13de3e6a-5e63-11e8-9d87-12945a1e4713.png)
![ts2](https://user-images.githubusercontent.com/11978772/40430757-13f0988a-5e63-11e8-98ee-b9bc42c5d031.png)

**Comment by tagliala** [comment] 2018-05-23 21:17
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11890, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-23 21:17 UTC
