### ISSUE TITLE
Icon request: family

### ISSUE THREAD

**Issue by ManasMadrecha** [FortAwesome/Font-Awesome#17939] opened 2021-05-26 10:22 UTC
**What can it be used for?**
Currently, there is only an icon for group of users which doesn't exactly denotes parents + children. So, there is a need for family icon

**Example image (optional)**
Inspiration take be sought from emojis: 👨‍👩‍👧‍👦

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-05-26 11:43
Hi!

Thanks for being part of the Font Awesome Community.

FA6 Pro, which is now in alpha, contains three new gender-neutral icons for this purpose

![image](https://user-images.githubusercontent.com/556268/119653978-3e697500-be28-11eb-8174-a29867913d03.png)

I'm going to close here as a duplicate of #3277

**Closed by tagliala** 2021-05-26 11:43 UTC
