### ISSUE TITLE
create adwords icon and create analytics icon

### ISSUE THREAD

**Issue by cerpnjaki** [FortAwesome/Font-Awesome#10050] opened 2016-10-11 18:32 UTC

**Comment by tagliala** [comment] 2016-10-11 19:10
Duplicate of #8314 and #2109, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-11 19:10 UTC
