### ISSUE TITLE
Icon request: fa-examine

### ISSUE THREAD

**Issue by MelSumner** [FortAwesome/Font-Awesome#11065] opened 2017-05-15 17:30 UTC
Use cases: There is a link to a report or maybe some sort of scanned image or paper check image. In the action icons, one of the icons could represent "examine this item". 

Example: 
![document_magnify-512](https://cloud.githubusercontent.com/assets/4587451/26070405/2587d6ea-396a-11e7-886f-8e64a437b37a.png)

Thank you for considering!

**Comment by tagliala** [comment] 2017-05-15 17:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6190, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-15 17:50 UTC

**Comment by MelSumner** [comment] 2017-05-15 18:45
Ahh I did search, but didn't think to look for those words. Thank you!
