### ISSUE TITLE
Icon Request [fa-no-filter]

### ISSUE THREAD

**Issue by deadmann** [FortAwesome/Font-Awesome#9068] opened 2016-04-27 07:35 UTC
i looking for a no-filter / clear-filter / remove-filter icon. can this be provided?

Or better, ability to put a line over the icon...
Like `<span class="fa fa-..."><span class="fa fa-over fa-line"></span></span>`
or more complete:
`<span class="fa fa-..."><span class="fa fa-over fa-cross fa-small fa-bottom-right-corner"></span></span>`

**Comment by tagliala** [comment] 2016-04-27 09:02
Duplicate of #650, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-27 09:02 UTC
