### ISSUE TITLE
Icon Request: fa-periscope

### ISSUE THREAD

**Issue by mikey186** [FortAwesome/Font-Awesome#8356] opened 2016-01-17 02:36 UTC
![capture](https://cloud.githubusercontent.com/assets/5152724/12375628/e568e56c-bc7f-11e5-9f15-71e9c6a6f054.JPG)
I want to use it to link users to a periscope account

**Comment by aethior** [comment] 2016-01-17 11:56
Hi @mikey186,

This sugestión is duplicate of #6463. Please +1 that.

Regards.

**Closed** 2016-01-17 15:09 UTC
