### ISSUE TITLE
Icon request: LeetCode

### ISSUE THREAD

**Issue by ivancraddock** [FortAwesome/Font-Awesome#16212] opened 2020-02-17 08:13 UTC
**What can it be used for?**
Creating a FA icon for LeetCode could allow programmers/hobbyists to easily link to their LeetCode profile, which shows code submissions and current rankings. [Here's mine as an example.](https://leetcode.com/ivancraddock/).

LeetCode is similar to HackerRank, which already has its own FA icon.

**Example image (optional)**
https://assets.leetcode.com/static_assets/public/webpack_bundles/images/LeetCode_nav.4d940ca72.png

https://imgur.com/a/NOHqBAI

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-02-18 19:56
Closing here as a duplicate of #15337

**Closed by tagliala** 2020-02-18 19:56 UTC
