### ISSUE TITLE
Icon Request: fa-freebsd

### ISSUE THREAD

**Issue by d4vidB** [FortAwesome/Font-Awesome#5575] opened 2015-02-03 20:13 UTC
Hello and nice job for 'Font Awesome' (30,231 stars!). Here is my request:
In the brand category, I don't see 'Beastie', the [BSD mascot](https://www.freebsd.org/) ([wiki](http://en.wikipedia.org/wiki/BSD_Daemon)).

![Logo](http://www.zupimages.net/up/15/06/bttq.png)

I hope that I don't ask too much...

**Comment by tagliala** [comment] 2015-02-04 23:32
duplicate of #1116 , please +1 that request

closing here

**Closed by tagliala** 2015-02-04 23:32 UTC
