### ISSUE TITLE
Icon Request: fa-onedrive and fa-googledrive

### ISSUE THREAD

**Issue by xenomarz** [FortAwesome/Font-Awesome#8904] opened 2016-04-06 15:57 UTC
It would be great if you could add an icon for Microsoft's 'OneDrive' and Google's 'Google Drive'.

Thanks!

**Comment by tagliala** [comment] 2016-04-06 21:45
Duplicate of #835 and #2887, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-06 21:45 UTC

**Comment by danpezzin-social** [comment] 2017-04-11 19:45
+1

**Comment by danpezzin-social** [comment] 2017-09-05 07:21
+1
