### ISSUE TITLE
Icon request: Ruby on rails 

### ISSUE THREAD

**Issue by sujeet-12** [FortAwesome/Font-Awesome#20356] opened 2024-09-15 11:02 UTC
### hello Font-Awesome Members

**I'm Hritik (web dev)**

well it's a programming language but i not get icon of this in font awesome that's why I want this for my next project.

`<i class="fa fa-brand-rubyonrails"></i>`

[https://upload.wikimedia.org/wikipedia/commons/6/62/Ruby_On_Rails_Logo.svg](url)

```[tasklist]
### Tasks
- [x] icon request #20356
```

**Comment by tagliala** [comment] 2024-09-15 11:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9004, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-09-15 11:03 UTC

**Comment by sujeet-12** [comment] 2024-09-15 11:07
thanks for your answer and well i don't look this in requests but that icon is not there in font awesome 😎
