### ISSUE TITLE
Icon request: fa-cpu (without text)

### ISSUE THREAD

**Issue by ztoliver** [FortAwesome/Font-Awesome#8630] opened 2016-02-23 06:46 UTC
Would like to have an icon that resembles a symbol for a CPU. Working on a system dashboard and there isn't anything related to system settings.

![image](https://cloud.githubusercontent.com/assets/8801099/13243744/cab41480-d9c6-11e5-866b-a0f9b9199746.png)

**Comment by MartinMuzatko** [comment] 2016-02-23 09:27
Agree! For System centric dashboards, you have almost nothing other than `server`

**Comment by aethior** [comment] 2016-02-23 11:44
There is a suggestion for computer chip (without text) #1840.

**Comment by aethior** [comment] 2016-02-23 11:53
There is a suggestion for computer chip (without text) #1840, but you can stack text and icons easily: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

**Comment by caduvieira** [comment] 2016-04-18 17:56
Dupe of #1840 
Please post your example there and +1 that request

**Comment by tagliala** [comment] 2017-04-01 07:46
Reopening here, because `fa-microchip` does not represent a modern CPU

**Comment by GNSubrahmanyam** [comment] 2017-04-01 08:38
+1

**Comment by webdes03** [comment] 2017-04-01 15:20
+1 since my CPU request was closed. I agree with the other comments in here... microchip doesn't solve the problem. For system dashboards, you frequently need CPU, Memory and Hard Disk. I feel that microchip represents memory well, but we need a modern CPU option. I personally would prefer it not be labeled on the icon as CPU like the original suggestion, just so it can be re-purposed better.

I'd suggest something like this: 
![image](https://cloud.githubusercontent.com/assets/371941/24579930/36a8b5b2-16cd-11e7-9283-0dc243bba1f7.png)

**Comment by Larspolo** [comment] 2017-09-22 15:59
GVD FIX

**Comment by s20691033** [comment] 2017-12-11 12:32
+1

**Comment by Bradyok** [comment] 2017-12-17 19:50
+1 I hope they actually do it

**Comment by ziltoidtheomiscient** [comment] 2018-01-31 09:57
+1 I personally need this one for my [polybar](https://github.com/jaagr/polybar) setup

**Comment by pcbailey** [comment] 2019-05-20 16:11
+1

**Comment by ShaunR** [comment] 2019-05-21 23:03
OK... I love font awesome but come on guys! There are literally hundreds of pointless icons... bong, burrito, frosty-head, hooli, jenkins, pied-piper just to name a few. Then you have icons that make sense and already exist like server, hdd, memory, ethernet, which all fit into the same category yet we still have no CPU icon! It's been requested time and time again for a long time now! What's hold up with this icon? Who do I need to bribe to make this happen?

**Comment by sparanoid** [comment] 2019-06-27 18:59
Vote for the CPU icon, we're building a service which needs some hardware symbols to present CPU, GPU, storage, and etc but surprisingly to see there's no CPU icon in Font Awesome (Pro).

**Comment by ShaunR** [comment] 2019-12-19 21:03
Still no CPU icon...

**Comment by fabdouglas** [comment] 2020-01-09 15:33
Workaround
`
<span class="fa-stack">
    <i class="fas fa-stack-1x fa-microchip fa-fw" style="transform: scale(1, .7);"></i>
    <i class="fas fa-stack-1x fa-microchip fa-fw" style="transform: rotate(90deg) scale(1, .7);"></i></span>
`
![image](https://user-images.githubusercontent.com/579170/72080871-cc10f700-32fd-11ea-90bd-957b082b851f.png)

**Comment by sensibleworld** [comment] 2020-11-05 00:38
The new microchip icon in the version 6 alpha might work for this one: https://fontawesome.com/download
<img width="444" alt="Screen Shot 2020-11-04 at 7 37 57 PM" src="https://user-images.githubusercontent.com/529604/98183029-40dc9f80-1ed5-11eb-895d-bd297db87790.png">

**Closed** 2021-01-04 21:03 UTC
Labels: new icon, released, web application icons
