### ISSUE TITLE
Icon request: icon-patreon and icon-issuu

### ISSUE THREAD

**Issue by seanVonDrake** [FortAwesome/Font-Awesome#8878] opened 2016-04-02 22:27 UTC
As you did for many other social networks and portals, I think that can be really useful if you include also these two:
https://www.patreon.com/
https://issuu.com/
![patreon_navigation_logo_mini_orange](https://cloud.githubusercontent.com/assets/11670332/14229386/dbe0f6e8-f932-11e5-9315-ac4b093bf664.png)
![download](https://cloud.githubusercontent.com/assets/11670332/14229387/df80e83a-f932-11e5-9ab8-ff3cad23df98.png)

**Comment by tagliala** [comment] 2016-04-02 22:47
Duplicate of #1993 and #3257 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-02 22:47 UTC
