### ISSUE TITLE
Icon request: fa-tools

### ISSUE THREAD

**Issue by WebGardenGeek** [FortAwesome/Font-Awesome#13734] opened 2018-08-08 22:03 UTC
### What can it be used for?

Example list of services provided by a contractor (carpentry, handyman work, etc, etc)

Actually it would be great to have a range of service-related icons: other tools (hammer & nail, trowel, shovel, saw, chisel, etc). But perhaps I'll submit those as separate requests.

### Example image (optional)

These ideas are pretty simple, not sure I need to upload images to spark your imagination...

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-08 22:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1214, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-08 22:05 UTC
