### ISSUE TITLE
Duotone layers not aligned (css / firefox / non-standard font size)

### ISSUE THREAD

**Issue by iwosid** [FortAwesome/Font-Awesome#18577] opened 2022-01-12 11:20 UTC
**Describe the bug**
the layers of the duotone icons are not aligned correctly in Firefox v96.0 (v95 affected too), looks ok on chrome based browser

**To Reproduce**
https://jsfiddle.net/2w05yxdk/

**Expected behavior**
icons should be aligned on all browsers

**Screenshots**
I took the screenshot of both and zoomed in the image, on the left the screenshot from chrome, on the right from firefox
![immagine](https://user-images.githubusercontent.com/88507338/149130041-a6702d93-7f8b-46cd-ad94-99c16fec3af3.png)

**Version and implementation**
Version: 6.0.0 beta 3 (from a fast test on fa-layer-group the issue is on v5.15.4)
Browser and version: Firefox v96.0 (v95 affected too)

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by iwosid** [comment] 2022-01-12 13:13
Hi tagliala,
could you please clarify what you mean by "the issue is caused by the "null" transformation applied to the before element"? Are you referring to the below rules?

```css
.fa-duotone.fa-fw::before, .fa-duotone.fa-stack-1x::before, .fa-duotone.fa-stack-2x::before, .fad.fa-fw::before, .fad.fa-stack-1x::before, .fad.fa-stack-2x::before {
	left: 50%;
	-webkit-transform: translateX(-50%);
	transform: translateX(-50%);
}
```

Also could you please check the links in your comment? First two are the same and the last one is the link i posted.

The 16px font size is fine, sadly i can't use 16px, also if i add fa-lg layers are closer together instead of not being aligned as you can see in the below screenshot:
![immagine](https://user-images.githubusercontent.com/88507338/149146771-65564260-0eae-45cb-82fb-ebd887d9e1c7.png)

**Comment by tagliala** [comment] 2022-01-12 13:23
> could you please clarify what you mean by "the issue is caused by the "null" transformation applied to the before element"? Are you referring to the below rules?

Yes, it is moving left by 50% and transforming horizontally by -50%, so I've used "null" 😅

> Also could you please check the links in your comment? First two are the same and the last one is the link i posted.

Fixed, thanks

> The 16px font size is fine, sadly i can't use 16px

You may try to remove the transformation rules if it works for your use case. I don't know why it is there, it has been added together with all the other styles from the first commit of duotone icons.

**Comment by iwosid** [comment] 2022-01-12 13:38
ok, without the transformation rules its ok, some issue when using browser zoom (issue only with firefox, chrome based browser are still 100% ok as i can see)
with svg+js is 100% perfect

**Comment by tagliala** [comment] 2022-01-12 13:48
Glad that workaround works. Let's keep this open for the moment

**Comment by robmadole** [comment] 2022-01-15 16:48
This is a limitation we can't really affect or get around. @tagliala is correct that we can't fix this.

Also glad the fix helps. I'm going to close as there is nothing further I can think of to address here.

**Comment by tagliala** [comment] 2022-01-15 17:02
@robmadole out of curiosity, what is the reason for the `left: 50%; transform: translateX(-50%);` rules?

**Comment by robmadole** [comment] 2022-01-15 17:05
@tagliala that's an old centering trick in CSS. https://css-tricks.com/centering-percentage-widthheight-elements/

**Comment by tagliala** [comment] 2022-01-15 17:41
Is there any edge case I'm missing?

As far as I can see, both primary and secondary glyphs have the same width and height, so I still didn't get why `position: absolute` is not enough and that transformation is needed

Some old browsers?

**Comment by robmadole** [comment] 2022-01-15 17:53
Shoot. I didn't read over this well enough! I see what's going on here now. Let me think on this one a bit. It might be an old IE workaround for duotone which we might be able to get rid of. Sorry @tagliala I wasn't paying close enough attention here.

**Comment by tagliala** [comment] 2022-01-15 19:14
No problem, maybe this rule can be removed from FA6, I can see it is still in the betas

**Comment by jasonlundien** [comment] 2022-03-29 18:36
Hi @iwosid ---
Are you seeing the discrepancies in a Firefox browser without using the js fiddle site ? 
I see that what you are referring to when I view in the fiddle, however I cannot reproduce this in a local html project ?!

**Comment by tagliala** [comment] 2022-03-29 19:11
Hi @jasonlundien I have a playground for tests so it is easy for me to provide reproducible test cases

Here it is a reproduction outside the fiddle: https://tagliala.github.io/fa18577.html

(left chrome, right firefox, hidpi)

<img width="234" alt="image" src="https://user-images.githubusercontent.com/556268/160688271-06c642ae-43a8-4e3e-a018-6849c0f63eb4.png">

It is not noticeable for me on low dpi mode

![image](https://user-images.githubusercontent.com/556268/160688825-cbbe1668-1bb8-48a8-a9d4-71a642bcadae.png)

**Comment by jasonlundien** [comment] 2022-03-29 20:21
@tagliala ---
Do you still see spacing problems with the `fa-layer-group` and `fa-user-group`, or is the issue with the `fa-folder-magnifying-glass` ?

I see what you are referring to on the `fa-folder-magnifying-glass` and can actually replicate that, but it seems like we no longer have spacing issues on the other 2 icons.  Are you seeing / getting the same ?

**Comment by tagliala** [comment] 2022-03-29 20:25
Cannot notice it on macOS hidpi resolution

it is a completely different thing on Win10 / Firefox 99 / lowdpi

![image](https://user-images.githubusercontent.com/556268/160700526-550d81b7-6658-44b2-b0ad-60296af81a89.png)

**Comment by jasonlundien** [comment] 2022-06-16 20:52
Hey @iwosid ---

We have a new release of Font Awesome that should have fixed this problem up.  I will go ahead close this issue.  If you run into any other problems on this let us know and we can open it back up.

**Closed by jasonlundien** 2022-06-16 20:52 UTC
Labels: bug, duotone
