### ISSUE TITLE
Icon request: Cpanel (small  icon)

### ISSUE THREAD

**Issue by roalvesrj** [FortAwesome/Font-Awesome#16894] opened 2020-07-10 23:06 UTC
**What can it be used for?**
The small cPanel icon and the WHM icon are essential for use in hosting services, cloud servers, among others. Currently Font Awesome has the standard cPanel icon, however, its use on buttons, for example, is bad, as the icon becomes unreadable when used small. So, I decided to include the request for the small version of cPanel and also WHM. For your attention, thanks.

**Example image**
cPanel (small icon)
![cP_orange_RGB](https://user-images.githubusercontent.com/13507838/87209562-b26e5d80-c2e8-11ea-8af0-bdb147d0d778.png)

WHM
![WHM_orange_RGB](https://user-images.githubusercontent.com/13507838/87209587-cd40d200-c2e8-11ea-8158-4820453a85cb.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by roalvesrj** [comment] 2020-08-07 11:26
Up!

**Comment by roalvesrj** [comment] 2020-08-07 11:27
@tagliala

**Comment by tagliala** [comment] 2020-08-07 12:08
Hi!

Thanks for being part of the Font Awesome Community.

I was pretty confident that I've answered to this issue, but maybe I forgot to press "comment"

I'm not sure if we can consider this an enhancement of the existing cPanel icon, because the small version works much better for our average use case

Anyway WHM is a different product and should have its own request, please split from this request

**Comment by roalvesrj** [comment] 2020-08-07 12:21
Hi @tagliala

Today, only the large cPanel icon is available and not the "cP", I see both as important, because in some cases, the complete icon, which is available, does not answer, as it is unreadable.

As for WHM, I already created requisition #17010 

Thanks for the feedback.

**Comment by hithomasmorelli** [comment] 2020-08-07 13:30
This seems like a duplicate of #13630

**Comment by tagliala** [comment] 2020-08-07 15:33
@hithomasmorelli thanks

will improve #13630's title for search purposes

**Closed by tagliala** 2020-08-07 15:33 UTC
