### ISSUE TITLE
Icon Request: Lions icons

### ISSUE THREAD

**Issue by pixieaka** [FortAwesome/Font-Awesome#14805] opened 2019-03-24 02:49 UTC
### What can it be used for?

It represents the power & animal icon [ It's not a brand ] You can change to any lion icon.

### Example images

![391-3912400_free-download-lion-face-drawing-simple-clipart-lion](https://user-images.githubusercontent.com/17777237/54874246-ea9a1600-4def-11e9-93b0-d2522989c132.png)
![lion-clipart-666597-3750673](https://user-images.githubusercontent.com/17777237/54874247-eec63380-4def-11e9-9a7d-82bb475e9f25.jpg)
![a3c374c10ebbd865307c252087de2629--lion-clipart-lion-vector](https://user-images.githubusercontent.com/17777237/54874259-259c4980-4df0-11e9-93c9-f442d613ce8a.jpg)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-03-24 08:59
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information about this request?

Is this a brand?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by pixieaka** [comment] 2019-03-24 09:32
@tagliala It's not a brand You can change to any lion icon.

**Comment by tagliala** [comment] 2019-03-24 10:01
Ok, this is a duplicate of #5403, please 👍 that request

**Closed by tagliala** 2019-03-24 10:01 UTC
Labels: waiting for feedback
