### ISSUE TITLE
Icon request: icon-parking

### ISSUE THREAD

**Issue by NichyXD** [FortAwesome/Font-Awesome#6926] opened 2015-07-10 17:17 UTC
I really need an icon with the parking "P" 
Exactly like this: http://www.foyleside.co.uk/perch/resources/mzl.giodzlin.png 
It's useful for hotels websites etc.
Thanks in advance! :)

**Comment by tagliala** [comment] 2015-07-12 19:12
duplicate of #1559 , please +1 that request

closing here

**Closed by tagliala** 2015-07-12 19:12 UTC
