### ISSUE TITLE
Icon request: fa-chain-broken

### ISSUE THREAD

**Issue by niksavc** [FortAwesome/Font-Awesome#20267] opened 2024-06-23 22:10 UTC
Can bring back the old icon but change its emoji style.
26D3_FE0F_200D_1F4A5 ⛓️‍💥 Broken Chain

Example:
![image](https://github.com/FortAwesome/Font-Awesome/assets/58150480/e07c6a7d-ffe2-467b-8eff-04a0bd5fc340)

**Comment by jabronus** [comment] 2024-07-12 13:36
Thanks for requesting an icon! But this is actually a duplicate of #10288 , so I'm closing this one.

**Closed as completed by jabronus** 2024-07-12 13:36 UTC
Labels: Duplicate
