### ISSUE TITLE
Icon request: pentacle

### ISSUE THREAD

**Issue by Nyx1961** [FortAwesome/Font-Awesome#16063] opened 2020-01-13 15:33 UTC
**What can it be used for?**
It is a religious symbol for Pagans (**NOT** satanists). You already have symbols for other religions such as Christianity, Judaism, Islam and others.

**Example image (optional)**
Insert the example image here if necessary.
![pentacle](https://user-images.githubusercontent.com/44875733/72268763-6cae3200-35f0-11ea-8aca-14e7d5ec1856.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by halocure** [comment] 2020-12-15 23:55
Is there any chance this will be added to the 6 release?

**Comment by starrymom** [comment] 2023-02-04 04:28
+1

**Comment by sensibleworld** [comment] 2024-07-11 16:46
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/16205)

**Closed by sensibleworld** 2024-07-11 16:46 UTC
Labels: new icon, religion (category), Duplicate
