### ISSUE TITLE
Icon Request: fa-stopwatch

### ISSUE THREAD

**Issue by sagimann** [FortAwesome/Font-Awesome#7980] opened 2015-11-25 14:32 UTC
A stopwatch symbol can be used to describe countdowns, special timers, lap times, etc
sample image:
http://simpleicon.com/wp-content/uploads/stopwatch-2.png

**Comment by caduvieira** [comment] 2015-11-25 16:16
dupe of #1340
please +1 that one

**Closed** 2015-11-25 16:30 UTC
