### ISSUE TITLE
Icon request: icon-desktop-share, icon-desktop-share-slash

### ISSUE THREAD

**Issue by savinayd** [FortAwesome/Font-Awesome#15050] opened 2019-05-22 04:52 UTC
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-05-22 07:46
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information about this request?

**Comment by savinayd** [comment] 2019-05-22 09:35
we are working on video app, we need **screenshare on** and **screenshare off** icon to use, when can i expect from you?

**Comment by tagliala** [comment] 2019-05-22 09:50
@savinayd could you please provide single color examples of the icon/couple of icons you want to request?

> when can i expect from you?

Please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information on how requests work.

If you need this icon right now, the best thing you can do is to [customize Font Awesome](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome)

**Comment by savinayd** [comment] 2019-05-22 11:46
![Untitled-1-01](https://user-images.githubusercontent.com/50899300/58172093-36185580-7cb5-11e9-89f5-3c91e5b0f871.jpg)

required all versions 
fas-fa, far-fa, fal-fa

**Comment by tagliala** [comment] 2019-05-22 19:33
Thanks for the examples

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/85/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by savinayd** [comment] 2019-05-23 05:45
yes absolutely fine, Please go a head

Thank you

**Comment by tagliala** [comment] 2019-05-23 09:18
@savinayd you're welcome, but please take another look at my comment here: https://github.com/FortAwesome/Font-Awesome/issues/15050#issuecomment-494734188

**Comment by savinayd** [comment] 2019-05-23 11:07
That icons is used in our application to **share the desktop screen to other user and to stop screen share**

**Comment by VictorQueiroz** [comment] 2020-07-17 03:02
Layering is nice but it'd be great to be able to achieve this without JS. I'd appreciate to be able to bake custom icons in the CLI, is there any way to do that as of now? Even if I have to switch to SVG icons, instead of webfonts.

**Comment by alecpl** [comment] 2020-07-21 09:06
+1. There's `microphone` and `microphone-slash`, `video` and `video-slash`. There is `desktop`, so it would be nice to have `desktop-slash`.

**Comment by k-funk** [comment] 2021-06-15 00:13
Would also like to see something built-in that represents screen-sharing/presenting.

**Comment by tagliala** [comment] 2022-09-24 09:33
I would like to consider #18566 as a duplicate of this and extend the concept of "desktop sharing" to other screens, so we can have a single icon to represent sharing of screens for any device

What do you think?

**Comment by sensibleworld** [comment] 2024-07-11 18:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)

**Closed by sensibleworld** 2024-07-11 18:37 UTC
Labels: new icon, web application icons (legacy category), Icon Wizard
