### ISSUE TITLE
No SVN Icon

### ISSUE THREAD

**Issue by sampsonliu** [FortAwesome/Font-Awesome#11085] opened 2017-05-18 07:44 UTC
fa-git is existence，but fa-svn is no

**Comment by tagliala** [comment] 2017-05-18 08:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7488, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-05-18 08:33 UTC
