### ISSUE TITLE
Icon request: icon-library

### ISSUE THREAD

**Issue by manukieli** [FortAwesome/Font-Awesome#10723] opened 2017-03-01 08:48 UTC
Icon that can represent local library, person read.

![library_reader](https://cloud.githubusercontent.com/assets/14294794/23452295/187c1556-fe64-11e6-934c-15a21cff0ff5.png)

**Comment by tagliala** [comment] 2017-03-01 11:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4808, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-01 11:54 UTC
