### ISSUE TITLE
Icon request: search-user

### ISSUE THREAD

**Issue by ux-jessica** [FortAwesome/Font-Awesome#16915] opened 2020-07-16 12:54 UTC
**What can it be used for?**
A magnifying glass with a user inside would be used to identity hiring related call-to-actions. 

**Example image**
https://www.iconfinder.com/icons/5004884/hiring_job_profile_recruitment_icon

**Icon request checklist**
[ Single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)

**Comment by tagliala** [comment] 2020-08-05 21:41
Hi!

Thanks for being part of the Font Awesome Community.

This is related but I will not consider this a duplicate of #15473

In any case, your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/430/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment] 2024-07-11 16:37
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)

**Closed by sensibleworld** 2024-07-11 16:37 UTC
Labels: new icon, web application icons (legacy category), Icon Wizard
