### ISSUE TITLE
Icon Request: fa-coins

### ISSUE THREAD

**Issue by irsh5** [FortAwesome/Font-Awesome#8808] opened 2016-03-23 06:06 UTC
We need one coins icon 
![coins](https://cloud.githubusercontent.com/assets/18022956/13977062/c9bbb57e-f0eb-11e5-835b-e7485dabe4c7.jpg)

**Comment by tagliala** [comment] 2016-03-23 11:10
Duplicate of #1400 , please +1 that request

closing here

**Closed by tagliala** 2016-03-23 11:10 UTC
