### ISSUE TITLE
Icon Request: icon-cluster

### ISSUE THREAD

**Issue by SteveJordanKW** [FortAwesome/Font-Awesome#8644] opened 2016-02-23 22:34 UTC
We've been using Font-Awesome for quite some time within our OpenSource scientific tools. While building web applications for scientific simulation and visualization (ParaViewWeb, ArcticViewer, HPCCloud...) we sometime run short in type of icons that could match our needs.

Hence today, we thought we should try to contribute those we commonly use within our application.

 Not easy to argue about... ;-)
![cluster](https://cloud.githubusercontent.com/assets/1433903/13269033/bdb43c32-da53-11e5-8284-b9e4154be04e.png)

**Comment by tagliala** [comment] 2016-02-24 10:31
Duplicate of #1342, please +1 that request and post there your example

Please also search before opening new requests

closing here

**Closed by tagliala** 2016-02-24 10:31 UTC
