### ISSUE TITLE
Icon request: Shopping-Cart-Full

### ISSUE THREAD

**Issue by Wallysantos** [FortAwesome/Font-Awesome#16466] opened 2020-04-14 11:05 UTC
**What can it be used for?**
This icon is useful to represents shopping carts with content. We already have versions to an empty or to add items to shopping cart, but nothing to represents a full one.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-23 13:27
Hi!

Thanks for being part of the Font Awesome Community.

Any idea? Something like https://fontawesome.com/icons/box-full?style=solid ?

**Comment by aethior** [comment] 2022-04-18 21:30
Duplicate of #13946.

**Closed** 2022-04-19 11:11 UTC
Labels: waiting for feedback
