### ISSUE TITLE
Icon request: floor-plan

### ISSUE THREAD

**Issue by MarceloFFranco** [FortAwesome/Font-Awesome#17781] opened 2021-03-29 12:16 UTC
**What can it be used for?**
Real estate market

Describe how this could be used / the use case for this icon.
We miss an icon that can be used to indicate floor plans
Real estate sites, construction companies, need to indicate floor plans, this can be very useful for companies to these segment

**Example image (optional)**
![FloorPlan](https://user-images.githubusercontent.com/72473083/112835157-4fd41200-906f-11eb-8295-86b3300923a4.jpg)

**Comment by tagliala** [comment] 2021-03-29 12:40
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12064, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-29 12:40 UTC
