### ISSUE TITLE
Icon Request: fa-pointer

### ISSUE THREAD

**Issue by sancou** [FortAwesome/Font-Awesome#5945] opened 2015-03-13 08:24 UTC
It would be great to have a pointer / cursor icon as shown below. 
Uses may include - as an action icon (in an editor) or as a representation of a 'click'.

Thanks.

![image](https://cloud.githubusercontent.com/assets/2262057/6635100/b9ff4466-c987-11e4-86d5-4582cb321fed.png)

**Comment by tagliala** [comment] 2015-03-13 11:45
duplicate of #1095 , please +1 that request

closing here

**Closed by tagliala** 2015-03-13 11:45 UTC
