### ISSUE TITLE
Icon Request: fa-endorsement

### ISSUE THREAD

**Issue by yalg** [FortAwesome/Font-Awesome#9373] opened 2016-06-08 15:33 UTC
Hi,

Could we have fa-endorsement like this to complete this powerfull project ?

![image](https://cloud.githubusercontent.com/assets/11456354/15899726/fdfad53e-2d9c-11e6-9d8c-cb8e2187df5a.png)

**Comment by tagliala** [comment] 2016-06-08 20:46
Duplicate of #6430, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-08 20:46 UTC
