### ISSUE TITLE
Icon request: icon-medal

### ISSUE THREAD

**Issue by erikaursi** [FortAwesome/Font-Awesome#10129] opened 2016-10-27 11:44 UTC
Hi!
I'm a designer who creates layouts for websites. I currently work for a website that sells real estate and vehicles that uses FontAwesome icons by default.
I'd like a medal icon.
It'’d be very useful for FontAwesome as it can be used in several ways.
Here are some images for reference:
![icons_medal](https://cloud.githubusercontent.com/assets/23098388/19765952/f84766c4-9c29-11e6-834a-4b1321d65380.jpg)

**Comment by tagliala** [comment] 2016-10-27 11:59
Duplicate of #1898 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by tagliala** [comment] 2016-10-27 11:59
@erikaursi please search before opening new requests

**Closed by tagliala** 2016-10-27 11:59 UTC
