### ISSUE TITLE
Icon Request: fa-donate

### ISSUE THREAD

**Issue by neofilm** [FortAwesome/Font-Awesome#9474] opened 2016-06-25 04:44 UTC
I helped a nonprofit setup a website and we chose the Enigma theme and they recently upgraded to the premium one. They contacted me today asking how to add a donate button in the header near where the social icons are. I have never used fa-icons before and the theme apparently uses this. Otherwise, if there was an image in the theme I could have simply created a new one and replaced one of the social icons with it and be done. But, this is more complicated, at least it appears that way. So, can you please make a donate Icon so the theme developer may include it. They just need the donating option to be more prevalent like the social icons... their website is myccrm.org if you're interested in checking it out. thanks!

**Comment by tagliala** [comment] 2016-06-25 09:18
Duplicate of #2224, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-25 09:18 UTC
