### ISSUE TITLE
Pre-release v5 release

### ISSUE THREAD

**Issue by odahcam** [FortAwesome/Font-Awesome#12027] opened 2018-01-02 12:08 UTC
**Can you publish a pre-release here for version 5?** I wanna start using it and I don't want to download and manage the package by hand. Also, docs have updated to version 5, but no publish to package managers was made. 😕

**Comment by tagliala** [comment] 2018-01-02 12:37
Hi!

Thanks for being part of the Font Awesome Community.

About the source code on the repo, this is a duplicate of #11908 

If you want to download FA5 Free or you need npm packages, please refer to https://fontawesome.com/ 

Hope it helps

Closing here

**Closed by tagliala** 2018-01-02 12:37 UTC

**Comment by odahcam** [comment] 2018-01-03 14:46
I'm still confused, is there anyway to use v5 without have to download the files by hand?
