### ISSUE TITLE
icon-request: icon-wagon

### ISSUE THREAD

**Issue by quinen** [FortAwesome/Font-Awesome#8867] opened 2016-03-31 14:00 UTC
we've got the train ... but what about the passengers ? a wagon icon would be so usefull !

examples :
[mine-wagon](https://cdn1.iconfinder.com/data/icons/industry-icon-set/512/Mine_wagon-256.png)
[passenger-wagon](http://www.iconshock.com/img_vista/IPHONE/transportation/jpg/passenger_car_icon.jpg)

**Comment by Tommuh** [comment] 2022-01-23 11:54
👍

**Comment by sensibleworld** [comment] 2024-07-10 21:18
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/8924)

**Closed by sensibleworld** 2024-07-10 21:18 UTC
Labels: new icon, transportation (category), Duplicate
