### ISSUE TITLE
Icon request: icon-Arabic

### ISSUE THREAD

**Issue by Mohmdthabet** [FortAwesome/Font-Awesome#8848] opened 2016-03-29 12:22 UTC
Kindly can we add an icon for Arabic language 
it is used as link for converting page language to Arabic language 

![ar-icon](https://cloud.githubusercontent.com/assets/9333195/14107611/8a8e6c2a-f5b9-11e5-9f89-3c705d5d813b.png)

**Comment by My1** [comment] 2016-04-20 12:46
why do you think that this symbol to symbolize arabic? it looks a bit like an inverted 3 or like the E in this style of cursive english:
https://en.wikipedia.org/wiki/D'Nealian

**Comment by AhmedOsama** [comment] 2016-12-31 16:40
It represents the letter "ع" of the arabic alphabet, which is also the first letter for the word Arabic in the Arabic language

**Comment by My1** [comment] 2016-12-31 16:52
okay that makes a lot of sense.
but then again the request has one problem. if this gets through every kind of Langugage will sooner or later want some kind of icon for itself.

**Comment by AhmedOsama** [comment] 2016-12-31 16:55
Yup, which would be very useful once done ;) 

Get Outlook for iOS




On Sat, Dec 31, 2016 at 6:52 PM +0200, "My1" <notifications@github.com> wrote:












okay that makes a lot of sense.

but then again the request has one problem. if this gets through every kind of Langugage will sooner or later want some kind of icon for itself.

**Comment by My1** [comment] 2016-12-31 17:06
-> @AhmedOsama how about next time a little bit less empty lines? you comment has almost my entire screen height covered.

but back to topic. the Problem is making understandable Labels for all the Languages, especially considering we have only fully opaque and fully transparent to deal with.

**Comment by tagliala** [comment] 2016-12-31 17:57
Maybe it is their email client messing up with spaces, I've cleaned up the post :)

**Comment by My1** [comment] 2016-12-31 18:00
@tagliala yeah probably, one more reason why I never reply by email, especially since quoting is mostly not needed and the meta text is never needed.

**Comment by dglassuw** [comment] 2020-09-16 15:22
Yes! Please add an icon for Arabic and other languages

**Comment by drattar** [comment] 2024-05-17 15:00
I agree with you about the need for icons for multiple languages; The Awesome Font project has many requests for multiple languages; This is a requirement in most websites and applications.
Currently, some developers use country icons; For example, the Kingdom of Saudi Arabia’s icon of the Arabic language, which is an official language of more than twenty countries; Iran's flag is the Persian language, which is spoken by several countries, including Iran, Afghanistan, Tajikistan, and others.
Some people use letters such as the letter (ع) for the Arabic language and the letter (ف) or (فا) for the Persian language.. I think this is more logical, as it is used in many designs and websites, but it is not uniform...
I suggest that the Awesome Font Project pay attention to the iconography of languages.

**Comment by My1** [comment] 2024-05-17 18:38
Problem with country flags tho is that many of these don't work in a monotone environment which webfonts generally are.
especially all the stripe-based ones like German, french, italian for example.

**Comment by sensibleworld** [comment] 2024-07-10 21:18
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-10 21:18 UTC
Labels: new icon, web application icons (legacy category), Declined
