### ISSUE TITLE
Icon Request: fa-parking 

### ISSUE THREAD

**Issue by Steffi3rd** [FortAwesome/Font-Awesome#5976] opened 2015-03-16 08:58 UTC
Blue icon parking P, like this one : http://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Parking_icon.svg/1024px-Parking_icon.svg.png

**Comment by tagliala** [comment] 2015-03-16 13:46
Duplicate of #1559 , please +1 that request

Please also search before opening new requests

**Closed by tagliala** 2015-03-16 13:46 UTC
