### ISSUE TITLE
Icon Request: fa-zillow

### ISSUE THREAD

**Issue by bobbyacker** [FortAwesome/Font-Awesome#12328] opened 2018-02-12 04:22 UTC
Need an icon for Zillow.com

**Comment by tagliala** [comment] 2018-02-12 09:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2623, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-12 09:48 UTC
