### ISSUE TITLE
Icon request: icon-prescription

### ISSUE THREAD

**Issue by gitnowlegal** [FortAwesome/Font-Awesome#5607] opened 2015-02-06 19:59 UTC
for use on medical site
![pill bottle 1](https://cloud.githubusercontent.com/assets/3269704/6086510/16b9a14c-ae08-11e4-8e18-0d1b4fb536d6.jpg)
![pill bottle 2](https://cloud.githubusercontent.com/assets/3269704/6086521/2bdb7762-ae08-11e4-8e32-93f23c259f0c.jpg)
![pill bottle 3](https://cloud.githubusercontent.com/assets/3269704/6086540/5038337a-ae08-11e4-9917-87dd7d6a783b.jpg)

**Comment by tagliala** [comment] 2015-02-06 23:40
duplicate of #4328 , please +1 that request

closing here

**Closed by tagliala** 2015-02-06 23:40 UTC
