### ISSUE TITLE
Icon request: ZODIAC ICONS

### ISSUE THREAD

**Issue by Ladiczek** [FortAwesome/Font-Awesome#9569] opened 2016-07-14 06:34 UTC

**Comment by tagliala** [comment] 2016-07-14 09:27
Duplicate of #2831 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-14 09:27 UTC
