### ISSUE TITLE
Icon Request: fa-hands-heart

### ISSUE THREAD

**Issue by LivelyDesigns** [FortAwesome/Font-Awesome#8667] opened 2016-02-28 19:41 UTC
Hands holding heart

![services-hands](https://cloud.githubusercontent.com/assets/3137322/13381400/462d3a90-de29-11e5-83c4-a3845aaf9f9f.png)

**Comment by caduvieira** [comment] 2016-04-05 16:48
Dupe of #6991?

**Comment by tagliala** [comment] 2016-04-05 17:03
@caduvieira thanks

Duplicate of #6991, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-04-05 17:03 UTC
