### ISSUE TITLE
Icon Request: fa-icon-beach

### ISSUE THREAD

**Issue by erpol** [FortAwesome/Font-Awesome#6830] opened 2015-06-26 14:22 UTC
A parasol/recliner/beach icon to suggest vacation and leisure, like this:

![image](https://cloud.githubusercontent.com/assets/13065811/8379264/7dd5618a-1c27-11e5-87ba-049f8ddaa5b4.png)
(this is copyrighted content, I just give it as an example!)

It's for using to categorize posts on a website.

Thanks!
RP

**Comment by tagliala** [comment] 2015-07-01 10:20
I'm going to consider this a duplicate of #3787, please +1 that request

Closing here

**Closed by tagliala** 2015-07-01 10:20 UTC
