### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by jrazap** [FortAwesome/Font-Awesome#18149] opened 2021-08-09 15:59 UTC
**What can it be used for?**
jquery 

**Example image (optional)**
![jquery-icon](https://user-images.githubusercontent.com/55711330/128738223-86659fa3-daf7-4406-a1d9-29d11befd802.png)

**Icon request checklist**
- [x] This is a single icon 
- [x] `Icon request: jquery `
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-08-09 17:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1665, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-08-09 17:28 UTC
