### ISSUE TITLE
Icon request: dotNET

### ISSUE THREAD

**Issue by mohammad-hosein-shahpouri** [FortAwesome/Font-Awesome#18562] opened 2022-01-07 12:35 UTC
**Description**
.NET is a free, cross-platform, open source developer platform for building many different types of applications.

**Example image**
![image](https://user-images.githubusercontent.com/58848912/148544460-f498bb8d-fe7e-41ad-aa8d-66541661eb7a.png)

**SVG**
[https://upload.wikimedia.org/wikipedia/commons/a/a3/.NET_Logo.svg](https://upload.wikimedia.org/wikipedia/commons/a/a3/.NET_Logo.svg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2022-01-07 13:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15505, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2022-01-07 13:19 UTC
