### ISSUE TITLE
Icon request: icon-mail-box

### ISSUE THREAD

**Issue by descendingleaves** [FortAwesome/Font-Awesome#11494] opened 2017-09-06 14:41 UTC
Hi,

I am working on a web map application and think a mail box icon would be great for identifying addresses.
Something like this?
![image](https://user-images.githubusercontent.com/31699611/30117965-636f5f42-92e7-11e7-9dd2-7395e4986299.png)
Thanks for providing these awesome icons!

**Comment by tagliala** [comment] 2017-09-06 15:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4849, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-06 15:21 UTC
