### ISSUE TITLE
icon request: fa-thermometer

### ISSUE THREAD

**Issue by evsar3** [FortAwesome/Font-Awesome#10028] opened 2016-10-06 08:45 UTC
A thermomether icon should be a good inclusion.

This is a good example:
http://www.freeiconspng.com/uploads/thermometer-png-icon-19.png

**Comment by PeterShaggyNoble** [comment] 2016-10-06 10:58
Dupe of [#720](https://github.com/FortAwesome/Font-Awesome/issues/720).

**Closed** 2016-10-06 11:45 UTC
