### ISSUE TITLE
Icon request:  fa-bancontact

### ISSUE THREAD

**Issue by kekev2001** [FortAwesome/Font-Awesome#19286] opened 2022-08-25 14:10 UTC
is it possble to add this 
![image](https://user-images.githubusercontent.com/56051728/186687843-6033aece-5b2f-4f3b-b7f9-f6e0a31f17b5.png)

**Comment by tagliala** [comment] 2022-08-25 14:12
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4817, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2022-08-25 14:12 UTC
