### ISSUE TITLE
Icon request: chart-donut-pie

### ISSUE THREAD

**Issue by 8BitSigdom** [FortAwesome/Font-Awesome#13966] opened 2018-09-19 07:31 UTC
A "Donut pie chart" icon would make my day :)

**Comment by aethior** [comment] 2022-03-28 16:35
Hi @8BitSigdom,

This request is a duplicate of #7520.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Closed** 2022-03-28 17:28 UTC
