### ISSUE TITLE
icon-tooth

### ISSUE THREAD

**Issue by hejtillanna** [FortAwesome/Font-Awesome#11674] opened 2017-10-26 11:24 UTC
Hello!
I could really use a tooth icon on our webbsite: www.liv.se. 
Is that possible?
Have a great day!
Anna

**Comment by tagliala** [comment] 2017-10-26 14:45
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1289 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-26 14:45 UTC

**Comment by timtjtim** [comment] 2017-10-26 15:05
Duplicate of #1289
