### ISSUE TITLE
GYm icon 

### ISSUE THREAD

**Issue by awatasoftsys** [FortAwesome/Font-Awesome#7833] opened 2015-11-06 07:36 UTC
I want gym icon

**Comment by BTVincent** [comment] 2015-11-07 16:40
Could you be more precise and/or give an example for the developpers ?

**Comment by voltechs** [comment] 2015-11-09 21:43
Maybe like, free-weights?

**Comment by tagliala** [comment] 2015-11-13 20:55
considering this as a duplicate of #1500 , in you have something different in mind please provide an example

Please also take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Closed by tagliala** 2015-11-13 20:55 UTC
