### ISSUE TITLE
appear.in

### ISSUE THREAD

**Issue by RakibFiha** [FortAwesome/Font-Awesome#13807] opened 2018-08-23 12:11 UTC
Add appear.in logo which is used by many people to do formal video chat

**Comment by tagliala** [comment] 2018-08-23 16:37
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9892, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-23 16:37 UTC
