### ISSUE TITLE
Icon request: bullet (unicode U+2022: •)

### ISSUE THREAD

**Issue by collimarco** [FortAwesome/Font-Awesome#18256] opened 2021-09-08 12:01 UTC
**What can it be used for?**
I have a list and I would like to use a bullet to represent each item. The circle icon is too large.

I would like to use FontAwesome, instead of unicode, because other items in the same list may use different icons from FontAwesome.

**Example image (optional)**

Bullet is a very small circle: •
https://www.compart.com/en/unicode/U+2022

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-09-08 12:45
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/565

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Also, a small circle is available in FA 6 Pro: https://fontawesome.com/v6.0/icons/circle-small?s=solid

@sensibleworld is `circle-small` the equivalent of https://www.compart.com/en/unicode/U+2022 ?

**Comment by sensibleworld** [comment] 2021-09-08 12:58
@tagliala Nope. `circle-small` is kind of it's own thing. We do (in v6) have a "[period](https://fontawesome.com/v6.0/icons/period?s=solid)" icon, though it's aligned to the bottom of its viewbox. I'll see about getting a version added for "bullet".

**Comment by sensibleworld** [comment] 2024-07-11 15:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/5732)

**Closed by sensibleworld** 2024-07-11 15:23 UTC
Labels: new icon, shapes (category), Duplicate
