### ISSUE TITLE
FontAwesome CDN script with icon stats reporting enabled gives an error on using the Wordpress Media Uploader

### ISSUE THREAD

**Issue by Syourt** [FortAwesome/Font-Awesome#9434] opened 2016-06-21 13:26 UTC
I have just included the new FontAwesome script using the FontAwesome javascript cdn method.

Now I'm trying to use the Wordpress media upload feature when editing or creating a new page. When the Font Awesome script is loaded I get the error stated below. When I deactivate the script, the media uploader works fine.

`Uncaught TypeError: this.activateMode is not a function`

**Comment by tagliala** [comment] 2016-06-21 14:42
Could you please provide more details?

Wordpress version? Step by step guide to reproduce issue?

**Comment by Syourt** [comment] 2016-06-21 15:00
Hi Tagliala, thanks for your reply. Sorry for the incomplete issue summary. I'm using Wordpress 4.5.2 on a local .dev development installation.

To reproduce the error, please install a new Wordpress installation (or try it on an existing one). Add the following code to your functions.php:

`function custom_admin_scripts() {
   wp_enqueue_script( 'font_awesome', 'https://use.fontawesome.com/332afd7265.js');
}
add_action( 'admin_enqueue_scripts', 'custom_admin_scripts' );`

After you've followed the previous steps, go to your Wordpress admin, add a new page/post and try to add an image using the "Add Media" button. The error console will log the error stated in my issue.

**Comment by tagliala** [comment] 2016-06-22 09:05
>  Add the following code to your functions.php:

which one? `/wp-includes/functions.php` or theme related files?

**Comment by Syourt** [comment] 2016-06-22 09:15
To your theme functions.php. I have included it inside a plugin but the result is the same.

**Comment by tagliala** [comment] 2016-06-22 09:30
It works for me.

WP: 4.5.3
Theme: twentysixteen
functions.php

```php
function custom_admin_scripts() {
  wp_enqueue_script( 'font_awesome', 'https://use.fontawesome.com/EDITED.js' );
}
add_action( 'admin_enqueue_scripts', 'custom_admin_scripts' );
```
(Please note that `wp_enqueue_script( 'font_awesome', 'https://use.fontawesome.com/EDITED.js', array(), null );` is better because otherwise WP adds `?ver=4.5.3` to the `src` attribute)

Result:
![screen shot 2016-06-22 at 11 26 20](https://cloud.githubusercontent.com/assets/556268/16261514/30183f3c-386c-11e6-8d63-afed2b1ee45b.png)


Could you please provide me your .js configuration at fontawesome cdn? This is mine.

![screen shot 2016-06-22 at 11 29 30](https://cloud.githubusercontent.com/assets/556268/16261655/a59de07c-386c-11e6-80f0-9615acd4db21.png)

**Comment by Syourt** [comment] 2016-06-22 09:43
![schermafbeelding 2016-06-22 om 11 40 17](https://cloud.githubusercontent.com/assets/12154823/16262016/32ed083a-386e-11e6-8a34-9a278524bcc6.png)

I've tried your options and found out that when I turn off "Icon stats reporting" everything works fine. So it works fine right now, people should turn off "Icon stats reporting" like below.

![schermafbeelding 2016-06-22 om 11 40 40](https://cloud.githubusercontent.com/assets/12154823/16262058/611ffa0a-386e-11e6-8570-afa1fb469e93.png)

Thanks for your help Tagliala, really appreciate it!

**Comment by tagliala** [comment] 2016-06-22 09:48
I can confirm this happens with the icon stats reporting enabled

@davegandy @robmadole @supercodepoet

**Comment by robmadole** [comment] 2016-06-22 16:33
@Syourt we'll get a fix for this. Let me carve out some time next week to look at this. Just to confirm, this isn't currently blocking you is it with the above workaround?

**Comment by robmadole** [comment] 2016-06-22 16:33
@tagliala thank you for running this down with the details!

**Comment by Syourt** [comment] 2016-06-23 07:08
Hi @robmadole, thanks for your effort. I'm fine with this workaround, it's a fun feature to see how many times certain icons are used, but absolutely not necessary for me. Good luck with the fix!

**Comment by robmadole** [comment] 2016-07-05 22:15
@Syourt we have a fix for this on the CDN project up in a PR. Should get merged and deployed tomorrow and then if you don't mind I'll ask you to give it a shot to see if we have it fixed for you. I'll let you know.

**Closed** 2016-07-06 15:19 UTC
Labels: bug, cdn

**Comment by robmadole** [comment] 2016-07-06 15:58
@Syourt this has been deployed. Can you give it a shot now? Just re-enable stats reporting for that embed code and then give it another try.

**Comment by Syourt** [comment] 2016-07-07 07:11
Hi @robmadole, it works! Now I don't get any errors anymore. This bug is solved, thanks!
