### ISSUE TITLE
Icon Request: fa-raspberrypi

### ISSUE THREAD

**Issue by campsoftware** [FortAwesome/Font-Awesome#9090] opened 2016-04-30 19:21 UTC
There are icons for Apple, Windows, and Linux. An icon for Raspberry Pi would also be helpful!

**Comment by tagliala** [comment] 2016-05-01 11:50
Duplicate of #2944 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-01 11:50 UTC
