### ISSUE TITLE
Icon Request : icon-wiki (open book with text - github like wiki - do not confuse with wikipedia)

### ISSUE THREAD

**Issue by xuv** [FortAwesome/Font-Awesome#6595] opened 2015-05-29 16:14 UTC
This is a tricky one. I'm not sure how you would represent a wiki.
Even at The [NounProject](https://thenounproject.com/search/?q=wiki), they don't have any.
But I would sure put it to good use on my website. And I guess other people too.
Github has a wiki icon (look on the right).
So far, I've been using 'files-o'. But I'm pretty sure we can find a better one.

The other solution would be creating icons for the popular "wiki brands" like Wikimedia, Dokuwiki, etc.

**Comment by tagliala** [comment] 2015-06-07 14:11
There is a wikipedia icon @ http://fontello.com/

You could also upload your .svg files

btw this is a duplicate of #388 , planned for 5.0.0, but please +1 that request

closing here

**Comment by xuv** [comment] 2015-06-07 15:38
@tagliala Oops sorry, I didn't check if the Wikipedia icon existed already.

But I think this issue should be re-opened as what I'm looking for is a "generic wiki" icon.
Wikipedia, Wikimedia, Dokuwiki are brands.
Although the concept of a "wiki" is, I would say, a tool, like a blog, or email or bookmarks. In that sense, I wish they would be some brainstorming on what an icon representinq a wiki could be.
There is so many different implementation of wiki engines, that it does not seem right to use the Wikipedia icon for all of it.

**Comment by tagliala** [comment] 2015-06-07 15:56
could you please provide an example?

**Comment by xuv** [comment] 2015-06-07 16:02
I'm sorry. I'm not sure I understand the question. You need an example of what? 
Here, on github, they have a "generic icon" for their wiki.
![screenshot-github com 2015-06-07 11-59-26](https://cloud.githubusercontent.com/assets/192539/8024769/eb6d8aee-0d0c-11e5-92d1-3c8ca064155f.png)
But I don't find this a very good icon for a generic wiki.
It works here, I guess, but in a different context, maybe not as much.
Does that answer your question?

**Comment by tagliala** [comment] 2015-06-07 16:05
Yes it does, thanks.

Github refers to that icon as `octicon-book`. Since we already have a book icon, I would call it `open-book`, which is requested here: #176

**Comment by xuv** [comment] 2015-06-07 16:38
@tagliala Yes, but I think that an "open book" icon does not really represent the idea of a wiki. 
Of course, wikis are mostly used for documentation. And documentation can be understood as a manual, or pages of information. So that's why they went for the "open book" icon. But the metaphor for a "wiki" is maybe a bit weak here.
A wikipedia puts it:
> A **wiki** (Listeni/ˈwɪki/ *WIK-ee*) is an application, typically a web application, which allows collaborative modification, extension, or deletion of its content and structure.
Not really a definition for a "book", is it? ;)

So I wish this issue would still be open to encourage collaborative thinking around what would be a symbol to represent a wiki. I'm not sure there is one we can agree on, but the discussion is worth it in my opinion.

**Comment by tagliala** [comment] 2015-06-07 18:40
From our contributing guidelines:  https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

So... if the wiki icon used by github is an open book with text then... the title should reflect what Dave is going to implement :)

Take a look at the octicon icon you are referring to: https://octicons.github.com/icon/book/

If you want, you can call this request `open-book-with-text (wiki)`, which could be different from #176 and could require a new implementation, and I'm perfectly fine with that

**Comment by xuv** [comment] 2015-06-08 13:57
Thx. Ok, I get it.

I was under the impression that a "wiki" was a "concrete" object from the web, a bit like [RSS](http://fontawesome.io/icon/rss/).

There is also concepts like "[share](http://fontawesome.io/icon/share/)" in the fontawesome set that can't be described in concrete terms but are a essential part of online activities. So it the "[retweet](http://fontawesome.io/icon/retweet/)", which could be called "reshare" in contexts different than twitter.

So I'm guessing, an icon for "wiki" could be ```markup-page-multi-pencil (wiki)```

What do you think?

**Comment by tagliala** [comment] 2015-06-08 15:17
The share icon is actually a logo owned by sharethis and is broadly accepted to represent share
The rss logo was invented by mozilla, is present on the rss wikipedia page and it is broadly accepted as a representation for an rss feed
At this point you will state that "the open book is broadly accepted as wiki representation by github users" and I cannot argue with that :)

Reopening here, but I need to add something in the title to avoid confusion, because I still think that an open book is what that icon represent

**Comment by xuv** [comment] 2015-06-08 16:41
Hey. Thx for reopening. :)

I agree with you that what github is using is an "open book" icon. And somehow the github community thinks this is acceptable to represent the wiki. It's mainly github's decision I guess.

But I hoped we could think of a better icon for a wiki. Maybe I'm mistaking asking this question here. Maybe the brainstorming for a general purpose wiki icon should not happen in the "fontawesome" discussions.

So I would like to change the title then to:
**Icon Request : icon-wiki (markup text with multi pencil - do not confuse with wikipedia)**

Would that be ok with you?

**Comment by sensibleworld** [comment] 2024-07-10 21:43
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)

**Closed by sensibleworld** 2024-07-10 21:43 UTC
Labels: new icon, web application icons (legacy category), Icon Wizard
