### ISSUE TITLE
con request: icon-gitlab

### ISSUE THREAD

**Issue by l0ner** [FortAwesome/Font-Awesome#8663] opened 2016-02-26 22:08 UTC
Gitlab is an alternative to github. It would be nice to have icons (normal and square) for this service.
link: [gitlab.com](https://about.gitlab.com/)

**Comment by tagliala** [comment] 2016-02-26 23:29
duplicate of #1530, please +1 that request

closing here

**Closed by tagliala** 2016-02-26 23:29 UTC

**Comment by l0ner** [comment] 2016-02-26 23:35
Sorry, couldn't find it before.

**Comment by tagliala** [comment] 2016-02-26 23:41
@l0ner don't worry, I'm here to help :+1:
