### ISSUE TITLE
Icon request: icon-drone

### ISSUE THREAD

**Issue by JamesOrlowski** [FortAwesome/Font-Awesome#8379] opened 2016-01-20 18:53 UTC
How about something like this? 

https://d30y9cdsu7xlg0.cloudfront.net/png/103844-200.png

**Comment by aethior** [comment] 2016-01-21 03:13
Hi @JamesOrlowski,

This suggestion is duplicate of #5446. Please +1 that.

Regards.

**Closed** 2016-01-21 09:01 UTC

**Comment by pitus** [comment] 2016-01-27 00:38
+1 for our Farming support site where they'll use Drones to do scouting
