### ISSUE TITLE
Icon request: filter-slash

### ISSUE THREAD

**Issue by jrdesignch** [FortAwesome/Font-Awesome#16813] opened 2020-06-19 15:02 UTC
**What can it be used for?**
to reset a filter

**Example image (optional)**
Insert the example image here if necessary.
![filter-slash](https://user-images.githubusercontent.com/67156959/85146837-50bd5500-b24e-11ea-82aa-d1409148e36e.png)

**Icon request checklist**
- [missing unfilter ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-06-19 15:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5309, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-06-19 15:20 UTC
