### ISSUE TITLE
Icon request: lacrosse

### ISSUE THREAD

**Issue by cklingdesigns** [FortAwesome/Font-Awesome#17680] opened 2021-03-01 17:47 UTC
**What can it be used for?**
For lacrosse sports activity

**Example image (optional)**
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.trentonian.com%2Fsports%2Fprinceton-mens-lacrosse-looks-to-respond-in-prime-time-game-at-stony-brook%2Farticle_e5df34b4-57e1-11e9-a89c-2ffc7ddad1fe.html&psig=AOvVaw35tREMgNKdRwGs-kk2PtNq&ust=1614707046252000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMj4r9_Sj-8CFQAAAAAdAAAAABAF

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-03-01 18:50
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14106, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-03-01 18:50 UTC
