### ISSUE TITLE
Icon Request: fa-meetup

### ISSUE THREAD

**Issue by tigusigalpa** [FortAwesome/Font-Awesome#5963] opened 2015-03-14 15:58 UTC
It will be great to make icon of meetup.com social service!

**Comment by mankintong** [comment] 2015-03-15 13:21
+1

**Comment by 972creative** [comment] 2015-04-22 07:18
+1

**Comment by gugaalves** [comment] 2015-09-02 22:11
+1

**Comment by rojoko** [comment] 2015-09-27 17:19
+1

**Comment by tagliala** [comment] 2015-09-27 18:14
Sorry, missed this one

Duplicate of #1588, please +1 that request

If you find a duplicate request, please do not +1 both but notify me, thanks

Closing here

**Closed by tagliala** 2015-09-27 18:14 UTC
