### ISSUE TITLE
Icon request: Uranium

### ISSUE THREAD

**Issue by BartHimitsu** [FortAwesome/Font-Awesome#8564] opened 2016-02-14 09:24 UTC
Evrybody knows that yellow logo representing uranium, like some of this: https://www.google.co.uk/search?q=uran+logo&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjlvvSB9_bKAhWKtRQKHbz6CSoQ_AUIBygB&biw=1366&bih=635

**Comment by tagliala** [comment] 2016-02-14 13:48
what is uranium? website? brand? product? could you please provide more information?

**Comment by IdolwSzutrab7** [comment] 2016-02-14 18:38
Uranium? Element of uranium? Uran? I don't know how to explain it. Everybody knows that biohazard symbol.

**Comment by tagliala** [comment] 2016-02-14 19:21
a proper image would explain better than 1000 words :)

is this a duplicate of #4470 ?

**Comment by IdolwSzutrab7** [comment] 2016-02-15 22:56
Yes.

**Comment by giuseb** [comment] 2016-02-18 15:58
That is NOT a symbol for uranium. Rather, it warns about *any* type of radioactivity.

**Comment by tagliala** [comment] 2022-03-13 15:09
> Yes.

Duplicate of #4470

**Closed by tagliala** 2022-03-13 15:09 UTC
Labels: waiting for feedback
