### ISSUE TITLE
Icon Request: fa-docker

### ISSUE THREAD

**Issue by aranderia** [FortAwesome/Font-Awesome#11164] opened 2017-06-12 20:40 UTC

**Comment by tagliala** [comment] 2017-06-12 21:06
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3316 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-06-12 21:06 UTC
