### ISSUE TITLE
Icon Request: Icon-aparat

### ISSUE THREAD

**Issue by ata24** [FortAwesome/Font-Awesome#10267] opened 2016-11-22 08:12 UTC
Hello
[aparat.com](http://www.aparat.com) is the most famous video sharing platform in Iran. I was wondering if you could add its official icon to your library. 
Thank you.

**Comment by tagliala** [comment] 2016-11-22 09:55
Duplicate of #5204, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-11-22 09:55 UTC
