### ISSUE TITLE
Icon Request: fa-ship

### ISSUE THREAD

**Issue by AnanthaVishnu** [FortAwesome/Font-Awesome#5344] opened 2015-01-06 06:30 UTC
![hipping-and-cargo-icons](https://cloud.githubusercontent.com/assets/10413685/5625184/b265932e-959b-11e4-8430-2340d3b61775.jpg)
I would like to have an icon with a ship or trailer that can be used as an icon for online shipment or cago.

**Comment by tagliala** [comment] 2015-01-06 09:44
duplicate of #1323 , please +1 that request

closing here

**Closed by tagliala** 2015-01-06 09:44 UTC
