### ISSUE TITLE
Icon Request: fa-chair

### ISSUE THREAD

**Issue by desspro** [FortAwesome/Font-Awesome#11636] opened 2017-10-17 08:13 UTC
Hello, sorry for my english. I use a translator to write this request. I use your icons in my projects for sites. For one of them I need furniture icons. I would really appreciate it if you did it. Icons: a chair, a table, a stool, a closet.
Examples:
https://www.iconfinder.com/icons/2216570/chair_furniture_household_office_sit_icon#size=128
https://www.iconfinder.com/icons/2216532/chair_furniture_household_office_sit_icon#size=128
https://www.iconfinder.com/icons/2216573/bar_design_furniture_household_out_side_product_table_icon#size=128
https://www.iconfinder.com/icons/2147994/chair_comfort_decor_furniture_seat_style_icon#size=128
https://www.iconfinder.com/icons/2147974/chair_comfort_decor_furniture_seat_sofa_style_icon#size=128
https://www.iconfinder.com/icons/2147964/chair_comfort_decor_furniture_seat_sofa_style_icon#size=128
https://www.iconfinder.com/icons/1831049/drawers_furniture_icon#size=128

Thank you in advance.

**Comment by tagliala** [comment] 2017-10-17 08:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1998 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-17 08:29 UTC

**Comment by desspro** [comment] 2017-10-23 10:35
I do not consider my proposal a duplicate. I wished for a few furniture icons. Only the chair is not enough for working out the furniture category.

**Comment by desspro** [comment] 2017-10-23 10:36
I do not consider my proposal a duplicate. I wished for a few furniture icons. Only the chair is not enough for working out the furniture category.

**Comment by desspro** [comment] 2017-10-23 10:41
I do not consider my proposal a duplicate. I wished for a few furniture icons. Only the chair is not enough for working out the furniture category.

**Comment by tagliala** [comment] 2017-10-23 13:38
You are free to request another chair, but please follow contribuite guidelines:

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
