### ISSUE TITLE
Icon Request: fa-vegetable

### ISSUE THREAD

**Issue by tarunaggarwal54** [FortAwesome/Font-Awesome#9209] opened 2016-05-14 08:51 UTC
I am developing a online grocery store in which I need icons related to grocery.
![vegetable](https://cloud.githubusercontent.com/assets/19358761/15267406/0f64f9fc-19df-11e6-8aab-2ca85b7f7f64.png)

**Comment by tagliala** [comment] 2016-05-14 10:13
Duplicate of #1499 #1183, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-14 10:13 UTC

**Comment by tarunaggarwal54** [comment] 2016-05-14 11:57
Hi tagliala,

I am not able understand. Where is the food icons ?? 
I can't find this icon in icons.
Please help.

**Comment by tagliala** [comment] 2016-05-14 12:35
there are requests for those icons, they are not actually available

**Comment by tarunaggarwal54** [comment] 2016-05-14 12:46
I checked original threads and some of them are opened 1 or 2 years ago and there is no icon yet. Is it like that ??

**Comment by tagliala** [comment] 2016-05-14 13:01
@tarunaggarwal54 please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome and here #1895 (pay particular attention to https://github.com/FortAwesome/Font-Awesome/issues/1895#issuecomment-72334749)
