### ISSUE TITLE
Icon Request: fa-guitar

### ISSUE THREAD

**Issue by jeekwong** [FortAwesome/Font-Awesome#8744] opened 2016-03-13 05:26 UTC
Cound you add some musical instruments? like guitar,violin etc.Great appreciation.

**Comment by aethior** [comment] 2016-03-13 12:25
Hi @jeekwong,

This request is duplicate of #5059. Please +1 that.

Regards.

**Closed** 2016-03-13 13:42 UTC

**Comment by jeekwong** [comment] 2016-03-13 14:50
@aethior OK, ths.
