### ISSUE TITLE
Icon Request: fa-plus. More control on icons. Ability to make icons slim

### ISSUE THREAD

**Issue by farhatrasheed** [FortAwesome/Font-Awesome#6484] opened 2015-05-15 04:34 UTC
There should be a features/properties that lets a user to make icon slim in appearance.
![slim-icons-issue](https://cloud.githubusercontent.com/assets/1029291/7646961/bf954982-fae9-11e4-8a47-e4379d8110c8.png)

**Comment by tagliala** [comment] 2015-05-15 08:06
Hi, this will require a complete rewrite of icons

Duplicate of #1733, refers to #2161 

Closing here

**Closed by tagliala** 2015-05-15 08:06 UTC

**Comment by tagliala** [comment] 2015-05-15 08:09
Sorry... I mean, `fa-plus` and `fa-plus-thin` (`fa-*` / `fa-*-thin`) are different icons. Thin versions should be rewritten from ground and added to the set.

**Comment by farhatrasheed** [comment] 2015-05-15 09:29
@tagliala Can we please have the fa-plus-thin & fa-minus-thin versions.
If not in font awesome, what could be the possible alternative.

**Comment by tagliala** [comment] 2015-05-15 10:44
Take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by farhatrasheed** [comment] 2015-05-15 11:08
Thanks :)
