### ISSUE TITLE
Brand request: BlueSky

### ISSUE THREAD

**Issue by akrabu** [FortAwesome/Font-Awesome#19855] opened 2023-08-09 04:10 UTC
### Description

New social media platform.  Not entirely sure how the logo could be done, since it's kind of just a blue square gradient.  Perhaps a b&w square gradient?

### Official website

https://bsky.app

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment] 2023-08-09 07:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #19855, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-08-09 07:49 UTC
Labels: brand icon

**Comment by akrabu** [comment] 2023-08-09 15:54
@tagliala 

> > This request is a duplicate of #19855, please add a 👍 reaction to that request.

This IS #19855 is it not?  I searched both open and closed issues and did not see a prior request.

**Comment by akrabu** [comment] 2023-08-09 15:54
@tagliala 

> > This request is a duplicate of #19855, please add a 👍 reaction to that request.

This IS #19855 is it not?  I searched both open and closed issues and did not see a prior request.

**Comment by akrabu** [comment] 2023-08-09 21:44
Ah, I found it.  #19810

I swear to you I searched first lol.  Not sure why it didn't show.  But cool, thanks.  I was really surprised no one else had brought it up.  Only reason I posted it.
