### ISSUE TITLE
Icon request: icon-web (icon-www)

### ISSUE THREAD

**Issue by seezee** [FortAwesome/Font-Awesome#5782] opened 2015-02-25 15:24 UTC
Could use an icon to represent the World Wide Web, icon-web w/ alias icon-www. I'm thinking something like this glyph I made with fontcustom:
![screenshot 2015-02-25 09 22 46](https://cloud.githubusercontent.com/assets/287836/6373374/e80de34a-bccf-11e4-9ccb-2305fdf74305.png)

**Comment by tagliala** [comment] 2015-02-25 22:31
duplicate of #1192, please post your example there

I'm still not convinced about the name.

For globe-wire, please +1 #2655 

closing here

**Closed by tagliala** 2015-02-25 22:31 UTC
