### ISSUE TITLE
Icon request: fa-footprints

### ISSUE THREAD

**Issue by shazic** [FortAwesome/Font-Awesome#13650] opened 2018-07-28 09:28 UTC
### What can it be used for?

I would like to request a **pair of icons** both of which would depict bare feet footsteps.
One icon with the left foot forward and the other with the right foot forward.  

_Issue #2140 is somewhat similar, but quite different use case.
Issue #6152 also requests a similar icon, though it is not clear from it's description what should the requested icon look like.
Issue  #3175 asked for a pair of footsteps but it looks like the request would get a pair of shoe-prints instead of bare feet. Hence, it is not the same that I am requesting._

I would be happy if my request is merged with any other existing request, as long as the icons are the exact same as requested under this issue.

### Example image
![image](https://user-images.githubusercontent.com/20720142/43355104-7793bd5a-9274-11e8-8b24-960b90efe6b6.png) ![image](https://user-images.githubusercontent.com/20720142/43355109-88d27fac-9274-11e8-860e-fa614f73d406.png)

### Icon request checklist

- [x] This is a matched pair icon request. One with the right feet as the lead and the other with the left feet as the lead foot.
- [X] The title starts with "Icon request: " and is followed by the requested icon name.
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate. 
- [X] I have included at least one example image if it could be helpful.
- [X] The request is for a concrete object.

**Comment by tagliala** [comment] 2018-07-28 09:56
Hi!

Thanks for being part of the Font Awesome Community.

I've closed #6152, because I was waiting for feedback and I didn't get it.

I'm going to consider #3175 as shoe prints, so this is related to #2140

The design will be decided by the team if we will include this icon

You can use power transforms to horizontally flip the icon if you need both your examples: http://jsfiddle.net/tagliala/9tercwpy/10/

**Comment by aethior** [comment] 2022-03-12 18:59
*Related Unicode Emoji* #222
👣 [U+1F463](https://emojipedia.org/emoji/%F0%9F%91%A3/) Footprints

**Comment by sensibleworld** [comment] 2024-07-11 19:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/2140)

**Closed by sensibleworld** 2024-07-11 19:23 UTC
Labels: new icon, web application icons (legacy category), Duplicate
