### ISSUE TITLE
Icon Request: Hammer

### ISSUE THREAD

**Issue by Robholte** [FortAwesome/Font-Awesome#10612] opened 2017-02-03 23:12 UTC
ARC projects
![hammer-icon-6](https://cloud.githubusercontent.com/assets/25539483/22612179/92a7a74e-ea34-11e6-9d91-a0d142b0c946.png)

**Comment by tagliala** [comment] 2017-02-03 23:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1214, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-03 23:35 UTC
