### ISSUE TITLE
Icon request: Language

### ISSUE THREAD

**Issue by raduluchian** [FortAwesome/Font-Awesome#784] opened 2013-02-20 08:42 UTC
I think a great addition to the set would be a language icon. Perhaps something similar to <a href="http://thenounproject.com/noun/speech/#icon-No1202">this icon</a>.

**Comment by aethior** [comment] 2022-04-16 16:52
I can't considerate duplicate of #2096 because the title is different but the requested icon is the same.
The other request has more upvotes.

@tagliala What do you think?

**Comment by tagliala** [comment] 2022-04-16 16:57
Yes, thanks, let's use #2096

**Closed by tagliala** 2022-04-16 16:57 UTC
Labels: new icon, web application icons
