### ISSUE TITLE
Icon Request: fa- customization

### ISSUE THREAD

**Issue by Pankajkumarbehera** [FortAwesome/Font-Awesome#10796] opened 2017-03-16 11:17 UTC
Hi Support,

Please create a new icon class for customization. So that it will be helpful to us.

Thanks & Regards
Pankaj
![customiazation](https://cloud.githubusercontent.com/assets/26458854/23993784/f5b6d960-0a67-11e7-8948-786249ac319c.png)

**Comment by tagliala** [comment] 2017-03-16 12:56
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #736 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-16 12:56 UTC
