### ISSUE TITLE
Icon request: star-pointy

### ISSUE THREAD

**Issue by spartie17** [FortAwesome/Font-Awesome#15318] opened 2019-08-01 02:27 UTC
FA 4 had a more pointy, less rounded star icon. For this reason I still keep FA 4 in all my sites, but would love to make the full upgrade to FA 5 and it's just this icon that's holding me back. It would be amazing if there was both options!

FA 4 Star:
<img width="44" alt="Screen Shot 2019-08-01 at 12 25 06 pm" src="https://user-images.githubusercontent.com/8684887/62261128-9535db80-b457-11e9-87f0-89d871efab3f.png">

FA 5 Star:
<img width="69" alt="Screen Shot 2019-08-01 at 12 24 58 pm" src="https://user-images.githubusercontent.com/8684887/62261139-9f57da00-b457-11e9-8baa-223836a7898e.png">

**Comment by tagliala** [comment] 2019-08-01 12:24
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5848, please add a 👍 reaction to that request.

I've also added a customization example to bring old stars in FA5 using the SVG framework: https://jsfiddle.net/tagliala/we7gtcvk/90/ (note: pseudoelements don't work in this case) 

Ref: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#svg-framework

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-08-01 12:24 UTC
