### ISSUE TITLE
Sort Asc and Desc Icons Appear to be Confusing to Clients

### ISSUE THREAD

**Issue by mtpultz** [FortAwesome/Font-Awesome#13920] opened 2018-09-07 21:08 UTC
We're finding a lot of clients are having issues with the sorting ascending and descending icons in v5.x vs v4.x

**Version 4.x**
They appear to understand the icons from version v4.x since it indicates what you expect from the top down with respect to the arrow and value.

![image](https://user-images.githubusercontent.com/599498/45242898-9cd01d00-b2a6-11e8-8fbb-121c73f51e5b.png)

**Version 5.x**
Unlike in v5.x were they appear to be quite confused by the arrow changing position and the values remaining constant.

![image](https://user-images.githubusercontent.com/599498/45242881-90e45b00-b2a6-11e8-9419-f2b1dda0f539.png)

This isn't just for the sort numeric, but has been pointed out for sort amount and sort alpha icons.

We're just using up and down chevrons now on our projects since it seems to be a common topic between our applications where the user is just clicking the icon until they get the result they expect to see with respect to the actual data instead of making an informed decision based on the icon.

**Comment by tagliala** [comment] 2018-09-07 22:33
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #9464 please post your comment there

**Closed by tagliala** 2018-09-07 22:33 UTC
