### ISSUE TITLE
Icon Request: fa-slip

### ISSUE THREAD

**Issue by Xer0fire** [FortAwesome/Font-Awesome#10099] opened 2016-10-21 09:39 UTC
This is a hazard symbol for slips I am going to use this as a Health and Safety icon on a homepage I'm working on. It is the logo from a hazard sign.

`<svg id="slip" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" height="224.37" width="262.6" version="1.0"  xmlns:dc="http://purl.org/dc/elements/1.1/">
<g id="g2833" transform="matrix(-1.0845 0 0 1.0845 -312.41 -263.15)">
<g id="body">
<path id="path1934" d="m-530.21 373.69v-51.988l32.76-32.76h82.968l33.828-26.35 12.819 15.668-39.065 31.978-27.132 0.33867 25.538 26.046 49.353-30.342 68.151-13.2 2.9183 23.28-59.11 10.326-39.525 27.062 51.276 10.326 47.003 32.76-12.819 17.804-45.935-30.267-73.353-8.546c-9.3134-0.84668-25.66-9.9229-29.911-13.887-1.0737-1.0014-39.525-45.935-39.525-45.935l-18.872 16.38v41.662l-21.365-0.35608z" fill-rule="evenodd"/>
<circle id="path1936" cy="264.35" cx="-465.43" r="21.703"/>
</g>
<path id="slip1" d="m-455.47 391.3s15.707-3.2905 21.57-2.1392c9.7601 1.9164 8.1277 6.0264 1.0696 9.8047-8.3745 4.483-8.2003 10.562 3.5653 15.866 10.012 4.5129 24.561 2.5871 35.653 3.9219 10.741 1.2924 12.969 3.5653 7.3089 8.3785-4.3964 3.7387-8.3349 9.0115 4.2784 11.587 15.029 3.0692 59.006 8.3785 59.006 8.3785" stroke="#000" stroke-width="4.9007" fill="none"/>
<path id="slip2" d="m-400.39 396.65s26.918 1.8272 37.436 5.7045 10.607 7.7546 4.6349 9.8047c-5.0933 1.7484-13.236 8.2448 0 11.231 13.107 2.9567 49.38 9.9829 49.38 9.9829" stroke="#000" stroke-width="4.9007" fill="none"/>
</g>
</svg>
`

![slip](https://cloud.githubusercontent.com/assets/1565969/19593859/6a720cb8-977a-11e6-91f5-53c08a1aeb12.png)

**Comment by ryankane** [comment] 2016-10-28 10:33
@tagliala This is a duplicate of **#8054 &mdash; Icon Request: icon-slip-hazard**

![fa-wet-floor-o](https://camo.githubusercontent.com/4fbd27562a91b1cf185428623e368f64081f7048/687474703a2f2f692e696d6775722e636f6d2f6a574b565263672e706e67)

![fa-wet-floor](https://camo.githubusercontent.com/65234aab7fb7eac9f6efd4cae2aa14589f8c39af/687474703a2f2f692e696d6775722e636f6d2f7177396e366a702e706e67)

**Comment by tagliala** [comment] 2016-10-28 12:17
@ryankane thanks!

**Closed by tagliala** 2016-10-28 12:17 UTC
Labels: new icon, web application icons
