### ISSUE TITLE
Icon Request: fa-city

### ISSUE THREAD

**Issue by r3robson** [FortAwesome/Font-Awesome#10037] opened 2016-10-08 17:17 UTC
For cities and big buildings....

**Comment by tagliala** [comment] 2016-10-08 19:35
Duplicate of #1932, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-08 19:35 UTC
