### ISSUE TITLE
Icon request: vip

### ISSUE THREAD

**Issue by ulluoink** [FortAwesome/Font-Awesome#13570] opened 2018-07-18 16:05 UTC
### What can it be used for?

VIP (very important person) icon can be used for person who are very important :-)
e.g. in a fundraising or finance context for people who donated huge amounts of money or baught expensive items in a webshop or are important users in general

### Example image (optional)

![grafik](https://user-images.githubusercontent.com/12530921/42893503-cee5923a-8ab4-11e8-862c-122023f3764a.png)

### Icon request checklist

- [X] This is a single icon 
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-18 20:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2862, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-18 20:55 UTC

**Comment by tagliala** [comment] 2018-07-18 20:57
There is a crown icon that may suit your needs https://fontawesome.com/icons/crown?style=solid
