### ISSUE TITLE
Icon Request: better-business-bureau or bbb

### ISSUE THREAD

**Issue by andrewgillingham** [FortAwesome/Font-Awesome#13517] opened 2018-07-10 18:16 UTC
## Example Image
![logo_square_200](https://user-images.githubusercontent.com/24575540/42529173-ba4249d2-844b-11e8-9b2b-c30a806f8cfc.jpg)

**Comment by tagliala** [comment] 2018-07-10 19:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5797, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-10 19:11 UTC
