### ISSUE TITLE
Icon Request: fa-infinite

### ISSUE THREAD

**Issue by lucilakawai** [FortAwesome/Font-Awesome#8256] opened 2016-01-01 05:06 UTC
Hey guys,
First of all congratulations for the amazing job. 
I would like to ask for a icon, could you please create a infinite icon?
Thank you in advance,
Cheers from Brazil

**Comment by tagliala** [comment] 2016-01-01 10:01
duplicate of #1647 , please +1 that request

closing here

**Closed by tagliala** 2016-01-01 10:01 UTC
