### ISSUE TITLE
Icon request: user-accept

### ISSUE THREAD

**Issue by TutoDS** [FortAwesome/Font-Awesome#12540] opened 2018-03-07 20:09 UTC
fa-user-plus - change plus to ok

**Comment by tagliala** [comment] 2018-03-07 22:20
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6053, please add a 👍  reaction to that request.

Please also note that you can achieve this icon with the new masking and layers feature of the SVG framework: https://jsfiddle.net/tagliala/qu83xrwp/10/

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-07 22:20 UTC
