### ISSUE TITLE
Icon request: icon-php

### ISSUE THREAD

**Issue by messmaker** [FortAwesome/Font-Awesome#6051] opened 2015-03-24 14:26 UTC
Hello and thanks for all the work you've done so far!
It would be great if you could include the php elephant ;)

**Comment by tagliala** [comment] 2015-03-24 23:17
duplicate of #1420 , please +1 that request

please also take a look here: http://fizzed.com/oss/font-mfizz

**Closed by tagliala** 2015-03-24 23:17 UTC

**Comment by messmaker** [comment] 2015-03-24 23:27
Sorry I didn't saw it ..

**Comment by tagliala** [comment] 2015-03-25 11:03
no problem
