### ISSUE TITLE
Icon request: icon-satellite (icon-antenna, icon-radar, icon-dish, icon-cable)

### ISSUE THREAD

**Issue by harnishdesign** [FortAwesome/Font-Awesome#12757] opened 2018-04-02 12:44 UTC
**Something Like this :**

<img src="https://cdn3.iconfinder.com/data/icons/gray-toolbar-5/512/antenna-128.png" />

**Comment by tagliala** [comment] 2018-04-06 09:48
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5659, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 09:48 UTC
