### ISSUE TITLE
Icon Request: fa-Tableau

### ISSUE THREAD

**Issue by makwad** [FortAwesome/Font-Awesome#13635] opened 2018-07-26 10:21 UTC
Tableau brand

I am using FontAwesome for my Tableau dashboards and noticed in the Brands you don't have this brand.

Official Tableau Logo https://cdns.tblsft.com/sites/all/themes/tabwat/logo.png

just need the icon on the left:
![tableau](https://user-images.githubusercontent.com/32903323/43256817-e40da78a-90c5-11e8-9c84-9471549a1259.png)

https://cdn.filepicker.io/api/file/jZDILlufSOSDOkuJTZ7J

**Comment by tagliala** [comment] 2018-07-26 17:59
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8942, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-26 17:59 UTC
