### ISSUE TITLE
Icon request: webrtc

### ISSUE THREAD

**Issue by lbfeenix** [FortAwesome/Font-Awesome#18084] opened 2021-07-16 18:27 UTC
**What can it be used for?**
Display of the existence, settings and status of the WebRTC device/technology. It could be regular and solid icon. Explanation: https://webrtc.org/ .. it was here as issue before years and was closed.

**Example image (optional)**
For example this: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngegg.com%2Fen%2Fpng-wgpyk&psig=AOvVaw16ZyHPCg3QV6q940AO6Acn&ust=1626545963313000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCJjml5Ga6PECFQAAAAAdAAAAABAK

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-07-16 21:33
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9401, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-07-16 21:33 UTC
