### ISSUE TITLE
Icon Request: fa-mix

### ISSUE THREAD

**Issue by ngrock90** [FortAwesome/Font-Awesome#15886] opened 2019-11-30 00:01 UTC
Stumbleupon is now Mix so i suggest Mix icon
![20191130_005906](https://user-images.githubusercontent.com/43019988/69893087-e0c89b00-130c-11ea-9d06-dbeb03725245.jpg)

https://stumbleupon.com

https://Mix.com

**Comment by tagliala** [comment] 2019-11-30 11:44
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13398, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-11-30 11:44 UTC
