### ISSUE TITLE
Icon request: icon-traffic-cone

### ISSUE THREAD

**Issue by Juke29** [FortAwesome/Font-Awesome#5462] opened 2015-01-24 14:30 UTC
Use cases : building website and adding a "site under construction" message with a traffic cone icon, or while working on new features, features being tested, etc...
![traffic-cone-pvc-389](https://cloud.githubusercontent.com/assets/6998453/5887645/c6ccdf5c-a3dd-11e4-8d75-f3fdc01042ce.jpg)

**Comment by tagliala** [comment] 2015-01-24 15:07
I'm going to consider this a duplicate of #4485, please +1 that request

added "cone" to #4485's title

**Closed by tagliala** 2015-01-24 15:07 UTC
