### ISSUE TITLE
Icon Request: fa-cd/fa-dvd

### ISSUE THREAD

**Issue by DerKnob** [FortAwesome/Font-Awesome#7990] opened 2015-11-26 10:45 UTC
Hi,
it would be great to have a CD/DVD disc icon.
Would be good for "CD Store" or as "(CD) Cover Browser" icon.

Example/Idea:
![cd](https://cloud.githubusercontent.com/assets/6618301/11421188/9e3ff082-9433-11e5-9af9-5141b3d10298.png)

Thanks for that awesome font! :+1:

**Comment by tagliala** [comment] 2015-11-26 11:09
Duplicate of #702 , please +1 that request

closing here

**Closed by tagliala** 2015-11-26 11:09 UTC
