### ISSUE TITLE
Icon Request: Okta (fa-okta)

### ISSUE THREAD

**Issue by setu4993** [FortAwesome/Font-Awesome#16533] opened 2020-04-27 19:52 UTC
**What can it be used for?**
For linking to the identity provider.

**Example image (optional)**

![logo](https://user-images.githubusercontent.com/1833708/80414356-c5df6000-8885-11ea-9fa8-eb38a78582ff.png)
**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by setu4993** [comment] 2020-04-27 19:53
This has been requested before (https://github.com/FortAwesome/Font-Awesome/issues/7879), but hasn't seen any activity in years and the logo is different now.

**Comment by tagliala** [comment] 2020-04-27 20:56
Hi!

Thanks for being part of the Font Awesome Community.

Yes, this request is a duplicate of #7879, please add a 👍 reaction to that request. The logo may have changed in the last years, but we use the latest available one

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-04-27 20:56 UTC
