### ISSUE TITLE
Icon request: emt-star-of-life

### ISSUE THREAD

**Issue by utahraptor** [FortAwesome/Font-Awesome#12605] opened 2018-03-15 01:14 UTC
### What can it be used for?

The EMT Star of Life symbol - used to point to emergency medical providers
### Example image (optional)

![image](https://user-images.githubusercontent.com/5694768/37439105-b96e0d4c-27cc-11e8-9626-683796371c64.png)

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-03-15 11:19
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3036, please add a 👍  reaction to that request.

> I have searched for existing issues and to the best of my knowledge this is not a duplicate

No problem, it happens 👍 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-15 11:19 UTC
