### ISSUE TITLE
 [FortAwesome/Font-Awesome] Library icon not available (#13573)Icon request: icon-name

### ISSUE THREAD

**Issue by raagoo** [FortAwesome/Font-Awesome#13584] opened 2018-07-20 05:57 UTC
### What can it be used for?

Whenever we want to talk or code or document or blog about Library, we need to represent it in terms of icon as we have icons for all other things. This will be useful for other Users as well.
### Example image (optional)
![library2 png](https://user-images.githubusercontent.com/41415817/42985556-962b7bd8-8c0f-11e8-9402-d95e87e91b68.jpg)
![library1](https://user-images.githubusercontent.com/41415817/42985557-9668bcfa-8c0f-11e8-90b9-b770f9030f73.png)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-07-20 08:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5098, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-07-20 08:14 UTC
