### ISSUE TITLE
Icon request: fa-microphone-muted

### ISSUE THREAD

**Issue by morninng** [FortAwesome/Font-Awesome#10674] opened 2017-02-17 09:45 UTC
In addition to fa-microphone , I want a microphone-mute.

![mute](https://cloud.githubusercontent.com/assets/7486461/23060466/21695d1c-f541-11e6-9dd3-776dccce1fad.png)

**Comment by tagliala** [comment] 2017-02-17 09:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8218, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-17 09:55 UTC
