### ISSUE TITLE
Icon Request - Handcuff

### ISSUE THREAD

**Issue by wmd-jrc** [FortAwesome/Font-Awesome#15544] opened 2019-09-16 19:52 UTC
Handcuff would make a great start to a Public Safety set. They will be used to indicate arrest made on campus. We strive to make safety a #1 priority and want update our website to reflect that. 

Example Icon: 
https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/handcuffs.png

- This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] I have handcuffs (https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2019-09-17 07:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8804, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-09-17 07:03 UTC
