### ISSUE TITLE
Icon request: icon-mineralwater

### ISSUE THREAD

**Issue by mrStenvik** [FortAwesome/Font-Awesome#10984] opened 2017-04-24 07:17 UTC
Something in this area: 

![mineralwater](https://cloud.githubusercontent.com/assets/27947303/25326085/ce234eda-28ce-11e7-9f3e-f4d2d95debbe.JPG)

**Comment by tagliala** [comment] 2017-04-24 09:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10741, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-24 09:36 UTC

**Comment by PeterShaggyNoble** [comment] 2017-04-24 11:11
@tagliala, #10741 is a request for a larger water bottle that would be used in a water cooler, whereas this one looks to be a smaller bottle that you would buy in the shops.

**Comment by tagliala** [comment] 2017-04-24 11:39
@PeterShaggyNoble thanks.

Maybe a duplicate of #5365?
