### ISSUE TITLE
Icon request: Interac

### ISSUE THREAD

**Issue by localdog** [FortAwesome/Font-Awesome#18419] opened 2021-11-07 16:21 UTC
**What can it be used for?**
I believe this may be in Canada only but Interac is a payment method used to purchase goods/services and can also be used to send and receive money via e-transfers (send money via email).  More info can be found here: https://www.interac.ca/en/

**Example image (optional)**
Sample image here: https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/InteracLogo.svg/2048px-InteracLogo.svg.png

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-11-07 16:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4445, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-11-07 16:58 UTC
