### ISSUE TITLE
Icon Request: fa-box-arrow-up (iphone share)

### ISSUE THREAD

**Issue by jwilliamsen** [FortAwesome/Font-Awesome#11712] opened 2017-11-04 15:55 UTC
I was looking for the box-arrow-up symbol used on an iPhone to send or save something.  I was going to use it in some help text describing how to bookmark our website on one's phone.

**Comment by aethior** [comment] 2022-03-22 21:32
Hi @jwilliamsen,

This icon has been added in v6.0.0.
Check https://fontawesome.com/icons/arrow-up-from-square

Regards.

cc/ @tagliala

**Comment by tagliala** [comment] 2022-03-22 21:40
also duplicate of #10619

**Closed by tagliala** 2022-03-22 21:40 UTC
Labels: new icon, web application icons
