### ISSUE TITLE
Icon Request: fa-volunteer

### ISSUE THREAD

**Issue by martinso2** [FortAwesome/Font-Awesome#9595] opened 2016-07-19 14:54 UTC
We need an icon for non-profits to volunteer and to become a "member" of the non-profit organization. 

This would be used for family organizations and fund raisers for non-profits.

**Comment by tagliala** [comment] 2016-07-20 08:59
could you please provide a single color example suitable for 14px icon size?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by kwitherite** [comment] 2017-03-13 02:52
How about some Volunteer icons like the ones I've provided? 
![volunteer1](https://cloud.githubusercontent.com/assets/26371171/23839727/7962abda-0776-11e7-8af9-76656c59c773.jpg)
![volunteer2](https://cloud.githubusercontent.com/assets/26371171/23839728/79635abc-0776-11e7-99a8-a3c7004e16d3.jpg)

**Comment by dhStudio** [comment] 2017-03-13 04:12
How about this for a Volunteer icon @kwitherite?

![fontawesome](https://cloud.githubusercontent.com/assets/25331188/23841149/2b01fe3c-07a3-11e7-9865-904a24a8d2ca.png)

**Comment by pratnala** [comment] 2018-01-07 23:24
Is there any update on this? A fa-volunteer would be really useful!

**Comment by kwitherite** [comment] 2018-01-08 03:28
Sorry I never replied! I like the concept of this for the fa-volunteer icon but the hand needs reworked just a tad... it looks unnatural but I love the concept of a hand holding a heart for this icon!

**Comment by kwitherite** [comment] 2018-01-08 03:30
Also another version for fa-volunteer2 could be a hand holding the earth.

**Comment by pratnala** [comment] 2018-01-08 03:31
@tagliala

**Comment by tagliala** [comment] 2018-03-06 18:53
Closing here because of missing feedback.

The example provided is a duplicate of heart in hand: #6991

**Closed by tagliala** 2018-03-06 18:53 UTC
