### ISSUE TITLE
Icon Request: icon-parking

### ISSUE THREAD

**Issue by Arnau-ads** [FortAwesome/Font-Awesome#6990] opened 2015-07-20 08:53 UTC
Need it for hotel facilities

img: https://cloud.githubusercontent.com/assets/13414782/8772569/8b558d68-2ecd-11e5-91ac-6d6f1b7d500b.png

**Comment by tagliala** [comment] 2015-07-20 08:54
duplicate of #1559 , please +1 that request

closing here

**Closed by tagliala** 2015-07-20 08:54 UTC
