### ISSUE TITLE
Icon request: icon-surgeon and more medical related icons

### ISSUE THREAD

**Issue by tohansen** [FortAwesome/Font-Awesome#9021] opened 2016-04-19 14:46 UTC
It would be nice to have several health care related icons like the following...
Icon request: icon-surgeon 
Icon request: icon-chemotherapy 
Icon request: icon-radiation 
Icon request: icon-nausea 
Icon request: icon-stomachache
Icon request: icon-depression
Icon request: icon-fatigue

**Comment by PeterShaggyNoble** [comment] 2016-04-19 15:21
[fa-user-md](http://fortawesome.github.io/Font-Awesome/icon/user-md/) should cover surgeon or is there something else you're looking for.

Radiation is a dupe of [#4470](https://github.com/FortAwesome/Font-Awesome/issues/4470), you should +1 that one.

What would you propose as an icons for the rest?

**Comment by tagliala** [comment] 2016-04-19 16:37
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Closed by tagliala** 2016-04-19 16:37 UTC
