### ISSUE TITLE
Icon request: MySQL

### ISSUE THREAD

**Issue by LuniaMage** [FortAwesome/Font-Awesome#15663] opened 2019-10-09 01:48 UTC
![mysql-icon](https://user-images.githubusercontent.com/38818721/66445547-25267180-ea15-11e9-9de4-0ecdf224c737.png)
**What can it be used for?**
Describe how this could be used / the use case for this icon.
     _Used as a brand name icon for web development_

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2019-10-09 05:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6052, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-10-09 05:57 UTC
