### ISSUE TITLE
Brand request: Rumble

### ISSUE THREAD

**Issue by ElectricOrBloxtric** [FortAwesome/Font-Awesome#20144] opened 2024-02-29 22:17 UTC
### Description

Rumble is a video sharing platform with 58 million Monthly Active Users [(Source)](https://corp.rumble.com/blog/rumble-reports-third-quarter-2023-results/). Many of my fellow developers and creators on the platform think it would be cool if the logo for Rumble were added as an icon to Font Awesome.
![Rumble Full Logo](https://github.com/FortAwesome/Font-Awesome/assets/69054622/7dd67265-64d7-4132-a228-f72a4f144543)
![Rumble Icon](https://github.com/FortAwesome/Font-Awesome/assets/69054622/8dc39c4a-5357-4e7c-878f-ed056ebb75e3)

### Official website

https://rumble.com

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tinyplayerss** [comment] 2024-02-29 22:24
Yes we Need this!

**Comment by nathanchere** [comment] 2024-03-01 20:24
"I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate"

https://github.com/FortAwesome/Font-Awesome/issues/17327
https://github.com/FortAwesome/Font-Awesome/issues/19546
https://github.com/FortAwesome/Font-Awesome/issues/18776
https://github.com/FortAwesome/Font-Awesome/issues/19322

I call bullshit.

**Comment by tagliala** [comment] 2024-03-01 20:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17327, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2024-03-01 20:28 UTC
Labels: brand icon

**Comment by nathanchere** [comment] 2024-03-01 20:37
> #17327

https://github.com/FortAwesome/Font-Awesome/issues/17327

Please thumbsup/comment on that issue. It doesn't even rank on top 50 of icon leaderboard probably in no small part thanks to the number of people creating duplicates instead of just using the existing request.

**Comment by ElectricOrBloxtric** [comment] 2024-03-01 22:32
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> This request is a duplicate of #17327, please add a 👍 reaction to that request.
> 
> You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.
> 
> You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work
> 
> Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)
> 
> Closing here

That one is very bland and don't explain what we really "want"

**Comment by ElectricOrBloxtric** [comment] 2024-03-04 16:14
> > #17327
> 
> 
> 
> https://github.com/FortAwesome/Font-Awesome/issues/17327
> 
> 
> 
> Please thumbsup/comment on that issue. It doesn't even rank on top 50 of icon leaderboard probably in no small part thanks to the number of people creating duplicates instead of just using the existing request.

That "duplicate" is very bland and gives no details on what logo we want to add
