### ISSUE TITLE
Icon request: fa-metro-square

### ISSUE THREAD

**Issue by samlachance** [FortAwesome/Font-Awesome#7439] opened 2015-09-11 18:51 UTC
Hey there.  It would be pretty great if you made a simple icon that would be used to indicate a metro/subway station.  The typical convention is a square with rounded corners that has a capital 'M' in the center.  

Thanks,
Sam

**Comment by caduvieira** [comment] 2015-09-11 19:03
dupe of #4038
also see http://jsfiddle.net/xg4Laq9x/ for a alternative

**Comment by user-e** [comment] 2015-09-12 11:29
The jsfiddle links by __*caduvieira*__ show how you can **create this
desired logo** with some **simple html and existing Font Awesome icons**.

The **first link shows** stacking a "square with curved corners" icon
right on top of a "subway train" icon.

The **second link shows** stacking a "square with curved corners" icon
on top of the letter "M" (not an icon, in any font).

**Comment by tagliala** [comment] 2015-09-12 20:37
closing as a duplicate of #4038 but AFAIK there is not a worldwide accepted metro logo

**Closed by tagliala** 2015-09-12 20:37 UTC
