### ISSUE TITLE
Icon Request: fa-skip

### ISSUE THREAD

**Issue by AndreVianna** [FortAwesome/Font-Awesome#5649] opened 2015-02-11 14:28 UTC
It is a very simple icon that I can't find in any library.
It should looks like a arrow going over a dot. 
It is used in workflows or wizards to indicate that you can skip a step, or avid some part of a task.
And alternative name could be fa-jump.

**Comment by tagliala** [comment] 2015-02-13 00:26
duplicate of #3575, please +1 that request

closing here

**Closed by tagliala** 2015-02-13 00:26 UTC
Labels: waiting for feedback

**Comment by AndreVianna** [comment] 2015-02-13 04:38
The icon I need is similar to this but not exactly this. In a sequence of steps (in a Wizard or Workflow) you may be able to jump the next step and go to a forward step.
The icon should have the arrow going around the dot. not end on it. To indicate that something was skipped or avoided.

--- Original Message ---

**Comment by AndreVianna** [comment] 2015-02-13 20:40
The icon you mention as duplicate is "jump to".
What I need is something like "jump over"
Like this (sorry I don't have a good design tool):
   __
-/  o \->
