### ISSUE TITLE
Icon request: European version of fa-globe

### ISSUE THREAD

**Issue by jkufner** [FortAwesome/Font-Awesome#5833] opened 2015-03-02 23:58 UTC
There really should be alternative version of `fa-globe`, called `fa-globe-eurasia` displaying the other side of Earth. You know, there are another continents than America ;)

**Comment by tagliala** [comment] 2015-03-03 13:04
duplicate of #281 , please read comments there

closing here

**Closed by tagliala** 2015-03-03 13:04 UTC
