### ISSUE TITLE
Icon Request: fa-icon-tooth

### ISSUE THREAD

**Issue by jelesh** [FortAwesome/Font-Awesome#6888] opened 2015-07-07 06:12 UTC
Please add tooth icon to the list
![tooth](https://cloud.githubusercontent.com/assets/13214059/8539789/3839e3fc-249d-11e5-9986-e7c25f02a7fb.png)
![tooth](https://cloud.githubusercontent.com/assets/13214059/8539793/46ee0d38-249d-11e5-8c7a-0e9cda353044.png)

**Comment by tagliala** [comment] 2015-07-07 08:55
duplicate of #1289 , please +1 that request

closing here

**Closed by tagliala** 2015-07-07 08:55 UTC
