### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by ColinMoulds** [FortAwesome/Font-Awesome#11338] opened 2017-07-29 21:07 UTC
I have seen so many discord icon post requests can we please make this a thing its been open since 2015.

Icon request: icon-discord #7574

**Comment by tagliala** [comment] 2017-07-29 21:16
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I must close this request, because it is a duplicate of #7574

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Closed by tagliala** 2017-07-29 21:16 UTC
