### ISSUE TITLE
Icon Request: fa-engine

### ISSUE THREAD

**Issue by halenharper** [FortAwesome/Font-Awesome#7442] opened 2015-09-12 08:12 UTC
I work with cars and spare parts. And I need more icons car topics.

**Comment by user-e** [comment] 2015-09-12 11:14
@halenharper 

I'm not part of the Font Awesome team, but I have a suggestion for you.

You should make their job easier by uploading an image of your icon
(so the team know what you want the new icon to look like).

PS: The image should ideally be a vector (such as SVG), not a bitmap
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(such as PNG or JPG) as Font Awesome use vector graphics in their font.

**Comment by caduvieira** [comment] 2015-09-12 18:51
Dupe of #4175

**Comment by tagliala** [comment] 2015-09-12 20:23
closing as a duplicate of #4175

If you need a comprehensive set of icons related to cars, please open new individual requests and consider a custom build: 

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Closed by tagliala** 2015-09-12 20:23 UTC
