### ISSUE TITLE
Icon request: data types

### ISSUE THREAD

**Issue by booleangate** [FortAwesome/Font-Awesome#9473] opened 2016-06-24 20:59 UTC
We've been using fontawesome for our API documentation, specifically for giving icons to data types.  We've gotten by with things like:

- `fa-clock` for Datetime/timestamp 
- `fa-hashtag` for number
- `fa-check` for boolean
- `fa-quote-left` for string

However, finding icons to represent arrays, objects, or int vs float numbers is hard.  So I submit the request for the following group of strictly related icons:

- fa-string: alias for `fa-quote-left` or `fa-quote-right`
- fa-number: alias for `fa-hashtag`
- fa-boolean: `Y/N` or just alias for `fa-check`
- fa-int: `123`
- fa-float: `1.2`
- fa-array: `[ ]` or `[..]`
- fa-object: `{ }` or `{..}`
- fa-binary:  ![binary](https://cloud.githubusercontent.com/assets/181567/16350416/6cc3474e-3a13-11e6-9a1e-25a8eee34fb6.png) (nevermind my horrible design skills)

**Comment by tagliala** [comment] 2016-06-25 01:30
Duplicate of #8303 and #4867, please take a look there

Closing here

**Closed by tagliala** 2016-06-25 01:30 UTC

**Comment by ashishRudder** [comment] 2022-07-09 06:47
+1
