### ISSUE TITLE
Icon request: vipps

### ISSUE THREAD

**Issue by simonbognoe** [FortAwesome/Font-Awesome#16661] opened 2020-05-18 08:11 UTC
**What can it be used for?**
Vipps is the leading mobile payments app in the Nordics. The Vipps mobile wallet has achieved worldwide attention, and is widely recognised for its success, having achieved nearly 80 percent market penetration in the Norwegian market.

[Vipps on the App Store](https://apps.apple.com/no/app/vipps/id984380185?l=nb)
[Vipps on Google Play](https://play.google.com/store/apps/details?id=no.dnb.vipps&hl=no)

**Example image (optional)**
The Vipps smile can be used as an icon:
https://github.com/vippsas/vipps-design-guidelines/blob/master/vipps-brandkit-full/4-vipps-emojis/kun-emojis/screen/oransje/svg/vipps-rgb-kun-emoji-oransje-02.svg

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2020-05-18 11:42
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8920, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-18 11:42 UTC
