### ISSUE TITLE
Icon Request: fa-core

### ISSUE THREAD

**Issue by mcpe-yossi1114** [FortAwesome/Font-Awesome#9893] opened 2016-09-09 13:30 UTC
Please add CPU core FontAwesome icon.
Thanks!

**Comment by mcpe-yossi1114** [comment] 2016-09-09 13:37
I want to suggest this:
[https://imgur.com/gallery/DbzMHn6](url)

**Comment by tagliala** [comment] 2016-09-10 15:24
Duplicate of #1840, planned for 5.0.0, but please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-09-10 15:24 UTC
