### ISSUE TITLE
Icon Request: ko-fi

### ISSUE THREAD

**Issue by oauo** [FortAwesome/Font-Awesome#16897] opened 2020-07-12 15:52 UTC
**What can it be used for?**
Easier way to link to https://ko-fi.com/

**Example image (optional)**
Official assets https://www.dropbox.com/sh/am6zv113bbri2bu/AAB-urMNd_lb-kYTXcXOf8lWa?dl=0

**Comment by oauo** [comment] 2020-07-12 15:53
Github ate the transparency
![ko-fi](https://user-images.githubusercontent.com/46975001/87250934-2a12c880-c460-11ea-9570-609cd200f052.png)

**Comment by tagliala** [comment] 2020-07-14 15:54
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12607, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-07-14 15:54 UTC

**Comment by oauo** [comment] 2020-07-14 17:17
Oh, that issue doesn't show up when searching for "ko-fi"

**Comment by aleksandar-todorovic** [comment] 2020-07-19 07:59
![Screenshot from 2020-07-19 09-58-01](https://user-images.githubusercontent.com/4890548/87870252-6d13f500-c9a6-11ea-9510-8a907d430875.png)

@oauo is right. The open issue doesn't show up when searching for "ko-fi" for some weird reason.
