### ISSUE TITLE
Icon request: jquery

### ISSUE THREAD

**Issue by justingolden21** [FortAwesome/Font-Awesome#17517] opened 2020-12-29 06:24 UTC
**What can it be used for?**
Mentioning a website was made with jquery, in a resume mentioning someone is proficient in jquery, mentioning that a framework or library requires jquery or works with jquery.

**Example image**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/30274440/103262970-59a88500-495b-11eb-9baa-31b4f6cd1a69.png)
from https://jquery.com/

**Icon request checklist**
- single icon
- not a duplicate
- example image provided

**Comment by tagliala** [comment] 2020-12-29 09:53
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1665, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-12-29 09:53 UTC

**Comment by justingolden21** [comment] 2021-01-04 05:49
I had searched before and somehow missed it. Thank you for linking to 1665, just thumbs up reacted it : ) Have a great day
