### ISSUE TITLE
Icon request: fa-teamspeak & fa-discord

### ISSUE THREAD

**Issue by EchoLivee** [FortAwesome/Font-Awesome#10042] opened 2016-10-10 02:57 UTC
I would like to see a fa-icon of Discord and a Teamspeak icon as an Font-Awesome icon. I would use it on serveral websites and forums to allow people to easily join our TS or Discord server.

Teamspeak [icon](https://camo.githubusercontent.com/fd83c643b192c27ed87784133b15ac74ca40722e/687474703a2f2f692e696d6775722e636f6d2f577064715a416e2e706e67)
Discord [icon](https://camo.githubusercontent.com/4b028e8e841f57ee96b472fa88ea7ed66ddd3720/687474703a2f2f692e696d6775722e636f6d2f65597779386c632e706e67)

**Comment by tagliala** [comment] 2016-10-10 08:22
Duplicate of #1474 and #7574 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-10-10 08:22 UTC
