### ISSUE TITLE
Icon Request: icon-virtual-reality-headset

### ISSUE THREAD

**Issue by samosale** [FortAwesome/Font-Awesome#8310] opened 2016-01-11 20:41 UTC
It would be nice to have some icon for VR headsets, that are like this but more prettier. :)

![vr](https://cloud.githubusercontent.com/assets/13149550/12245890/a88ba94a-b8ab-11e5-91ea-5cb95010f878.jpg)
![vr2](https://cloud.githubusercontent.com/assets/13149550/12245894/ab67ba78-b8ab-11e5-9a9c-735f2fb2dc89.jpg)

**Comment by tagliala** [comment] 2016-01-12 10:05
I'm going to consider this a duplicate of #6590, please +1 that request and post there your example

closing here

**Closed by tagliala** 2016-01-12 10:05 UTC
