### ISSUE TITLE
Icon Request: fa-ether

### ISSUE THREAD

**Issue by rednaxus** [FortAwesome/Font-Awesome#12163] opened 2018-01-27 01:46 UTC
ethereum!

**Comment by tagliala** [comment] 2018-01-27 10:29
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8754, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-27 10:29 UTC
