### ISSUE TITLE
Icon request: fish

### ISSUE THREAD

**Issue by channaaah** [FortAwesome/Font-Awesome#8307] opened 2016-01-11 10:28 UTC
![fishes7](https://cloud.githubusercontent.com/assets/16646180/12231250/6842c63e-b856-11e5-8a9b-7d02da9fbce7.png)

I would love to see a fish icon so I can use it for my categories!

**Comment by AndreLGava** [comment] 2016-01-11 15:31
This is related to 
https://github.com/FortAwesome/Font-Awesome/issues/2722
plese +1 on that

**Comment by tagliala** [comment] 2016-01-11 15:44
@AndreLGava thanks

closing here as a duplicate of #2722

**Closed by tagliala** 2016-01-11 15:44 UTC

**Comment by tagliala** [comment] 2016-01-11 15:46
I suspect this could be a request for a tropical fish. In this case, feel free to change the request title and comment and I will reopen

**Comment by channaaah** [comment] 2016-01-11 16:25
Any fish will do the job, I don't want to be difficult, haha! Thanks
