### ISSUE TITLE
Icon request: Assistance

### ISSUE THREAD

**Issue by davidetwc** [FortAwesome/Font-Awesome#8699] opened 2016-03-04 12:48 UTC
Hello, I'm looking for a assistance operator icon like this:
[https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/assistant.png](url)

[https://cdn0.iconfinder.com/data/icons/thin-communication-messaging/57/thin-217_call_support_phone_help_assistance-512.png](url)

Is it possible to have it?

Thanks

**Comment by tagliala** [comment] 2016-03-04 13:03
Links are broken, but this is a duplicate of #5586 , please +1 that request

closing here

**Closed by tagliala** 2016-03-04 13:03 UTC
