### ISSUE TITLE
Icon Request: fa-open-book

### ISSUE THREAD

**Issue by aminiz** [FortAwesome/Font-Awesome#12738] opened 2018-03-29 23:22 UTC
This icon would indicate open documents. 

Here is what I am thinking.

![book_open 2x](https://user-images.githubusercontent.com/4204621/38118063-41c78186-336d-11e8-9922-b92a93c30276.png)

**Comment by tagliala** [comment] 2018-04-06 10:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #176, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 10:13 UTC
