### ISSUE TITLE
Icon request: codingame

### ISSUE THREAD

**Issue by camilledtr** [FortAwesome/Font-Awesome#19729] opened 2023-05-22 04:46 UTC
![codingame](https://github.com/FortAwesome/Font-Awesome/assets/97107181/e6eb5f07-be17-49a1-ba51-46db9dc30595)

**Comment by tagliala** [comment] 2023-05-22 07:24
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10268, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-05-22 07:24 UTC
