### ISSUE TITLE
Icon request: icon-ebook

### ISSUE THREAD

**Issue by DeNelo** [FortAwesome/Font-Awesome#10365] opened 2016-12-14 11:21 UTC
I'd like an icon representing an e-book.
Something like the tablet icon, but with a book (or some lines of writing) inside...

**Comment by tagliala** [comment] 2016-12-14 13:36
Duplicate of #2356, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-12-14 13:36 UTC
