### ISSUE TITLE
Icon request: icon-website

### ISSUE THREAD

**Issue by ammar-bacha** [FortAwesome/Font-Awesome#9602] opened 2016-07-20 13:43 UTC
Hello, I need a website icon like : 
 
![1468865572_internt_web_technology-01](https://cloud.githubusercontent.com/assets/20518877/16988412/aed1013a-4e90-11e6-9499-80020551804c.png)

**Comment by tagliala** [comment] 2016-07-20 13:54
Duplicate of #2655, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-20 13:54 UTC
