### ISSUE TITLE
Icon request:  Ubisoft, debian

### ISSUE THREAD

**Issue by Akiroto** [FortAwesome/Font-Awesome#14744] opened 2019-03-13 09:10 UTC
Uplay or ubisoft its same ^^

**Comment by tagliala** [comment] 2019-03-13 10:43
Hi!

Thanks for being part of the Font Awesome Community.

Ubisoft is a duplicate of #4581, please add a 👍 reaction to that request.
Debian is a duplicate of #1125 , please add a 👍 reaction to that request.

All duplicates, closing here 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-03-13 10:43 UTC
