### ISSUE TITLE
Icon Request: fa-wikipedia

### ISSUE THREAD

**Issue by ronaldbradford** [FortAwesome/Font-Awesome#5636] opened 2015-02-10 17:08 UTC
For Brand Icon
See http://commons.wikimedia.org/wiki/File:Wikipedia-W-bold-in-square.svg for image

**Comment by tagliala** [comment] 2015-02-10 23:39
duplicate of the ancient #388, please +1 that request

closing here

**Closed by tagliala** 2015-02-10 23:39 UTC
