### ISSUE TITLE
Icon request: scatter/bubble chart

### ISSUE THREAD

**Issue by nickfinch71** [FortAwesome/Font-Awesome#13828] opened 2018-08-28 13:43 UTC
### What can it be used for?

There are already a number of chart objects that can be used for different chart type selection. Scatter/bubble charts are an obvious omision

### Example image (optional)

![chart-scatter-solid](https://user-images.githubusercontent.com/7850654/44726898-a7352e80-aad0-11e8-8487-d62102e80fb2.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-28 14:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4240, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-28 14:13 UTC
