### ISSUE TITLE
Icon request: naver

### ISSUE THREAD

**Issue by nw-gomdure** [FortAwesome/Font-Awesome#18492] opened 2021-12-08 12:02 UTC
**What can it be used for?**
Naver is the major internet portal of South Korea. By adding their icon to the list of icons developers can more easily refer to Naver and cater to the Korean audience. Naver contains many social functions each with their own icon, but the very well known N icon can already do a lot of lifting.

Describe how this could be used / the use case for this icon.
As mentioned this can help developing links to a service catered specifically to South Korea since Naver is the premier internet portal of South Korea akin to Google. It quintessential N could already do a lot of lifting though introducing the icons for its various services such as Naver Blog, Knowledge IN, etc. might make it even better.

**Example image (optional)**
![naver](https://user-images.githubusercontent.com/91887888/145205204-8041d35b-ee54-48f9-9c0d-32a5e01d2ac7.png)

**Icon request checklist**
- [X] This is a single icon
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-12-08 12:10
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8730, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-12-08 12:10 UTC
