### ISSUE TITLE
Icon Request: fa-dove

### ISSUE THREAD

**Issue by pittster** [FortAwesome/Font-Awesome#5358] opened 2015-01-08 18:46 UTC
Use case: peace, dove, funeral, obituary

![image](https://cloud.githubusercontent.com/assets/10453752/5668286/131cace8-9745-11e4-893f-6323bf898254.png)

**Comment by tagliala** [comment] 2015-01-08 19:36
Duplicate of #1612, please +1 that request and post there your example

closing here

**Closed by tagliala** 2015-01-08 19:36 UTC
