### ISSUE TITLE
Icon request: EyeEm

### ISSUE THREAD

**Issue by T3chnician** [FortAwesome/Font-Awesome#13989] opened 2018-09-22 07:23 UTC
### What can it be used for?

EyeEm is a famous website and app community for photographers to showcase their work. This can be used as a "social link" icon for developers who are also photographers. This is a brand icon and a new icon. Their URL is: https://www.eyeem.com/

### Example image (optional)

![eyeem icon](https://user-images.githubusercontent.com/12258962/45914628-2108cf80-be65-11e8-918b-875dce58fec4.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-09-22 08:13
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2346, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-09-22 08:13 UTC
