### ISSUE TITLE
Icon request: air-conditioning

### ISSUE THREAD

**Issue by MarGraz** [FortAwesome/Font-Awesome#9141] opened 2016-05-07 16:55 UTC
I'm creating a website for a B&B, and I saw that in fontawesome there isn't an icon to indicate air conditioning system.
It's possible to add this new icon to font awesome? 

Thank you

![ac_icon](https://cloud.githubusercontent.com/assets/19241483/15093340/3cd4f158-1485-11e6-82c7-ddb56e1513b1.png)

**Comment by tagliala** [comment] 2016-05-07 17:16
Duplicate of #3211, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-05-07 17:16 UTC

**Comment by MarGraz** [comment] 2016-05-07 17:27
I'm sorry :'(
