### ISSUE TITLE
Icon request: icon-map-pointer

### ISSUE THREAD

**Issue by rjbathgate** [FortAwesome/Font-Awesome#13123] opened 2018-05-11 18:47 UTC
A combination of map and map-marker - a paper map with a pin dropped on it.

Such as: 

![screenshot-uat wildthings club-2018 05 15-09-45-45](https://user-images.githubusercontent.com/14904553/40025140-c7781e7c-5824-11e8-8672-24b7761626b5.png)

The current map and pointer icons are handy but this addition would be useful for representing points on a map rather than just a map.

As a workaround I guess I could use map and map-pointer and overlay one onto the other, but a dedicated icon would be better 😀

Thoughts?

**Comment by Eldenroot** [comment] 2018-05-11 19:15
+1

**Comment by tagliala** [comment] 2018-05-14 15:51
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fix the example?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by rjbathgate** [comment] 2018-05-14 21:47
Hi @tagliala 

Ah sorry, not sure why it's now 404ing.

Have edited the original post with an embeded image.

Cheers

**Comment by tagliala** [comment] 2018-05-14 22:01
Fine, thanks

This is a duplicate of #8779, please +1 that request

Closing here

**Closed by tagliala** 2018-05-14 22:01 UTC
Labels: waiting for feedback
