### ISSUE TITLE
Icon request: instagram_inverse

### ISSUE THREAD

**Issue by curtisday** [FortAwesome/Font-Awesome#14835] opened 2019-03-29 06:08 UTC
### What can it be used for?

An alternative to the current Instagram icon on your system.

### Example image (optional)

See attached PDF

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
[instagram_inverse.pdf](https://github.com/FortAwesome/Font-Awesome/files/3021342/instagram_inverse.pdf)

**Comment by tagliala** [comment] 2019-03-29 10:14
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #14526, please add a 👍 reaction to that request.

Please also take a look at my comment there: https://github.com/FortAwesome/Font-Awesome/issues/14526#issuecomment-455801057

Closing here

**Closed by tagliala** 2019-03-29 10:14 UTC
