### ISSUE TITLE
Icon Request: fa-analog

### ISSUE THREAD

**Issue by drathnow** [FortAwesome/Font-Awesome#8814] opened 2016-03-23 21:20 UTC
I have a need for an analog signal icon.  Our app has the ability to configure analog input sensors and I would like to include this icon beside the title on the menubar.  This is the closest thing I could find to what I'm looking for but a more symmetric wave would be nice.
 
![analog](https://cloud.githubusercontent.com/assets/1458259/14001209/6cca06f8-f10a-11e5-89c6-1dac4e290b24.jpg)

**Comment by tagliala** [comment] 2016-03-24 14:22
I'm going to consider this a duplicate of #3206, please +1 that request

closing here

**Closed by tagliala** 2016-03-24 14:22 UTC

**Comment by drathnow** [comment] 2016-03-24 14:29
Yes!  Sorry about that.  I searched but didn't find that one.

Thanks!

**Comment by tagliala** [comment] 2016-03-24 14:30
no problem :+1:
