### ISSUE TITLE
Icon request: icon-cash-register

### ISSUE THREAD

**Issue by lucho07** [FortAwesome/Font-Awesome#6986] opened 2015-07-19 16:30 UTC
Please make a icon for cash register.
Link for a picture below:
https://www.iconfinder.com/icons/114425/cash_register_shop_icon#size=128

**Comment by tagliala** [comment] 2015-07-23 12:34
duplicate of #3467 , please +1 that request

closing here

**Closed by tagliala** 2015-07-23 12:34 UTC
