### ISSUE TITLE
Icon request: fa-dblp

### ISSUE THREAD

**Issue by cxsyzx** [FortAwesome/Font-Awesome#16665] opened 2020-05-18 11:45 UTC
**What can it be used for?**
Computer science researchers are encouraged to put links to their DBLP pages on their personal webpages, and they could use the icon there.

**Example image (optional)**
![images](https://user-images.githubusercontent.com/6269623/82209936-80c4c000-9951-11ea-8e8f-83c6f83a7208.png)
([source](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQMpCOjjhAdL47_le4WqyFpYXUaw6LY6AVrF8H8d9dcE7NYktbC&usqp=CAU))

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Notes**
From [DBLP](https://dblp.org/):

> The dblp computer science bibliography is the on-line reference for bibliographic information on major computer science publications. It has evolved from an early small experimental web server to a popular open-data service for the whole computer science community. Our mission at dblp is to support computer science researchers in their daily efforts by providing free access to high-quality bibliographic meta-data and links to the electronic editions of publications.
> 
> As of January 2019, dblp indexes over 4.4 million publications, published by more than 2.2 million authors. To this end, dblp indexes about than 40,000 journal volumes, more than 39,000 conference and workshop proceedings, and more than 80,000 monographs. Please find more statistics on dblp here.

**Comment by tagliala** [comment] 2020-05-18 11:57
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6562, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2020-05-18 11:57 UTC

**Comment by cxsyzx** [comment] 2020-05-18 12:01
Hi!

Thank you for your prompt response.
I've seen that post, but it does not provide enough information. Since I cannot edit that post, I made a new issue.
