### ISSUE TITLE
Icon-request: Clear or Clean

### ISSUE THREAD

**Issue by invot** [FortAwesome/Font-Awesome#8178] opened 2015-12-18 17:38 UTC
I think a concept not properly conveyed is that of cleaning or clearing. I think wrapping the times icon in a directional box may convey this concept quite well:

![images](https://cloud.githubusercontent.com/assets/2650927/11902973/49172536-a57b-11e5-92ef-19b44386184d.png)
![images2](https://cloud.githubusercontent.com/assets/2650927/11902974/49184394-a57b-11e5-9e7e-70dc3bbfbd19.png)

In this case, I think a general idea of "clear" is presented. Also, I feel these shapes surrounding the icon would, in general, make a lot of sense to implement in arrangement with other things like pluses and minuses. 

However, I think the concept of sweeping with a broom conveys the idea of cleaning or clearing more effectively:

![broom_icon](https://cloud.githubusercontent.com/assets/2650927/11902986/6c3f15be-a57b-11e5-8592-6e676f9d7e9e.png)

I would like to see a clever implementation of a broom/sweep icon. Something that shows cleaning is being done:

![broom_clean_clear_sweep_housework_dust-128](https://cloud.githubusercontent.com/assets/2650927/11903017/be2fa302-a57b-11e5-95b7-4eeefe0d9188.png)

It's hard to find something pre-existing that really hits the mark while keeping the icon simple in design, but I have a feeling there's something out there.

**Comment by caduvieira** [comment] 2015-12-18 17:53
broom/clear dupe of #239

**Comment by invot** [comment] 2015-12-18 17:57
Very clear dupe. I can't close this, but I also think we should consider the pointed container element.

**Comment by tagliala** [comment] 2015-12-18 18:18
backspace: #1980 

all dups, closing here

**Closed by tagliala** 2015-12-18 18:18 UTC
