### ISSUE TITLE
Icon Request: GrabCAD

### ISSUE THREAD

**Issue by JoeyDiamond** [FortAwesome/Font-Awesome#11386] opened 2017-08-10 12:21 UTC
It would be nice to have a GrabCAD icon for use. Specifically see things like the awesomeCV template. It would be awesome. Thanks!!

**Comment by tagliala** [comment] 2017-08-10 15:26
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4645, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-08-10 15:26 UTC
