### ISSUE TITLE
Icon Request: fa-monopoly

### ISSUE THREAD

**Issue by arraja1992** [FortAwesome/Font-Awesome#10926] opened 2017-04-11 16:00 UTC
Hi font-awesome team,

Just to start off, you guys are doing a great job, keep it up! Love your icons.
I was wondering if it's possible to add in an icon with the face of the monopoly man. I have attached a picture. Thank you.

Sincerely,
Monopoly lover
![687474703a2f2f7777772e69636f6e3130302e636f6d2f75702f333432322f3235362f4d6f6e6f706f6c79312e706e67](https://cloud.githubusercontent.com/assets/24459908/24918453/78ce1804-1eae-11e7-8f3e-4012e12fee6b.png)

**Comment by tagliala** [comment] 2017-04-11 18:16
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6035, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-11 18:16 UTC

**Comment by arraja1992** [comment] 2017-04-11 21:52
Okay so I sent a reaction to request #6035. How long will it take to complete this request?
