### ISSUE TITLE
Icon request: tracktor

### ISSUE THREAD

**Issue by gregsaxton** [FortAwesome/Font-Awesome#13758] opened 2018-08-13 02:19 UTC
### What can it be used for?

This could be used to denote Farming or Rural related activities such as Farm insurance

### Icon request checklist

- Single Icon
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-13 08:49
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5052, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-08-13 08:49 UTC
