### ISSUE TITLE
Icon request: fa-teeth

### ISSUE THREAD

**Issue by ximreh** [FortAwesome/Font-Awesome#6176] opened 2015-04-07 10:44 UTC
Please include in the medical icons section

![fa-teeth](https://cloud.githubusercontent.com/assets/7629142/7021602/17d9818e-dd2c-11e4-896c-1ca028390da8.png)

**Comment by tagliala** [comment] 2015-05-16 19:01
what could be a different use case from #1289 ?

**Comment by HLFH** [comment] 2017-07-30 08:07
Duplicate of https://github.com/FortAwesome/Font-Awesome/issues/1289.

Please close. @tagliala

**Closed** 2019-04-11 13:01 UTC
Labels: waiting for feedback
