### ISSUE TITLE
Icon Request: Dance Slipper

### ISSUE THREAD

**Issue by upace** [FortAwesome/Font-Awesome#11789] opened 2017-11-22 18:11 UTC
Use for a mobile app to represent dance classes
<img width="432" alt="screen shot 2017-11-22 at 1 11 18 pm" src="https://user-images.githubusercontent.com/10821656/33143067-ad2a6f42-cf86-11e7-9c35-0329dc9316c5.png">

**Comment by tagliala** [comment] 2017-11-22 21:15
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7563, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-22 21:15 UTC
