### ISSUE TITLE
Icon request: icon-layer

### ISSUE THREAD

**Issue by lipegon** [FortAwesome/Font-Awesome#12372] opened 2018-02-16 11:52 UTC
Layers can be a helpful icon to support some menus, represent a feature of the software, etc.

Plenty of "layer" icons here: https://www.flaticon.com/free-icons/layer

![image](https://user-images.githubusercontent.com/22617512/36306471-264f517e-1318-11e8-94fc-c5bef347afef.png)

Thank you in advance :)

**Comment by tagliala** [comment] 2018-02-16 12:22
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1179, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-02-16 12:22 UTC
