### ISSUE TITLE
Icon request: TIDAL

### ISSUE THREAD

**Issue by jprasad12** [FortAwesome/Font-Awesome#17630] opened 2021-02-13 13:01 UTC
**What can it be used for?**
Tidal is a music streaming service ,if the icon is added to fontawesome we can use it just like Spotify,Apple,Youtube etc.

**Example image of Tidal**
![tidal](https://user-images.githubusercontent.com/47057222/107850594-89d3b680-6e29-11eb-86b2-06cc25bc4903.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2021-02-13 13:03
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8850, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-02-13 13:03 UTC
