### ISSUE TITLE
Icon Request: fa-untappd

### ISSUE THREAD

**Issue by filipe0513** [FortAwesome/Font-Awesome#8695] opened 2016-03-03 16:40 UTC
Hello guys, first of all, your work is awesome! As a beer lover, I would appreciate if you launch the https://untappd.com icon to the social media group. I am sending an example of the icon that I am expecting, and hope that you like the idea.
ps: they provide this tag to us, but it is not that fancy... <a href='https://untappd.com/cervejababylon?ref=followbtn'><img src='https://d1c8v1qci5en44.cloudfront.net/widgets/ut_follow_md.png' /></a>
Thanks
![untappd_dark](https://cloud.githubusercontent.com/assets/1923102/13501125/337b22e0-e144-11e5-8a15-53340ee02674.png)

**Comment by tagliala** [comment] 2016-03-03 17:50
Duplicate of #1971, please +1 that request

closing here

**Closed by tagliala** 2016-03-03 17:50 UTC
