### ISSUE TITLE
Icon request: icon-opacity / icon-transparency

### ISSUE THREAD

**Issue by WouterDeRyck** [FortAwesome/Font-Awesome#8082] opened 2015-12-04 11:00 UTC
This icon represents opacity and transparency.

Would use this anywhere where a layer's opacity can be manipulated:
- in a visual editor: Photoshop or sketch like app.
- a map where you can adjust the opacity of a layer.

![image](https://cloud.githubusercontent.com/assets/15377764/11588051/06da1cbc-9a7e-11e5-9637-6a6cca8afbaa.png)
OR
![image](https://cloud.githubusercontent.com/assets/15377764/11588078/3304c4f4-9a7e-11e5-9a87-75daf4b9344b.png)

**Comment by MrGrigri** [comment] 2015-12-04 17:50
+1

**Comment by MrZach** [comment] 2015-12-09 04:05
Would `fa-adjust` work? [fontawesome.io/icon/adjust](http://fontawesome.io/icon/adjust/)

**Comment by WouterDeRyck** [comment] 2015-12-09 06:59
Yes, it would actually. Sorry for that.

Verstuurd vanaf mijn iPhone

Op 9 dec. 2015 om 05:05 heeft MrZach <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Would fa-adjust work? fontawesome.io/icon/adjust<http://fontawesome.io/icon/adjust/>

**Comment by r03ert0** [comment] 2016-08-08 18:38
i liked that opacity icon... the 'adjusted' one looks like a bright&contrast one, and doesn't make much sense for opacity/transparency

**Comment by sensibleworld** [comment] 2024-07-10 21:19
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/diagram-venn?f=classic&s=solid)

**Closed by sensibleworld** 2024-07-10 21:19 UTC
Labels: new icon, web application icons (legacy category), FA Pro

**Comment by tagliala** [comment] 2024-07-20 13:26
Let's mark this as a duplicate of #2164
