### ISSUE TITLE
Showcase for version 4.7.0 is broken

### ISSUE THREAD

**Issue by Berger1994** [FortAwesome/Font-Awesome#13417] opened 2018-06-25 14:46 UTC
The details page for the showcase is broken (no CSS?). Not all of my projects are migrated to 5.0.0 so I need the showcase.

Example:
https://fontawesome.com/v4.7.0/icon/globe

**Comment by tagliala** [comment] 2018-06-25 14:58
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13394, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-06-25 14:58 UTC
