### ISSUE TITLE
Icon request: WWE LOGO

### ISSUE THREAD

**Issue by loveforall1** [FortAwesome/Font-Awesome#19508] opened 2023-01-08 12:06 UTC
hi please add WWE (World Wrestling Entertainment) Logo

**Comment by tagliala** [comment] 2023-01-08 12:09
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17100, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Closed as completed by tagliala** 2023-01-08 12:09 UTC
