### ISSUE TITLE
Icon Request: fa-beach-umbrella

### ISSUE THREAD

**Issue by hasandogu** [FortAwesome/Font-Awesome#6747] opened 2015-06-13 22:02 UTC
It would be awesome to have some icons related with holiday.

fa-beach-umbrella, fa-beach-ball, fa-swimsuit, fa-bikini

**Comment by ShamanFromSiberia** [comment] 2015-07-01 07:55
+1

**Comment by tagliala** [comment] 2015-07-01 10:21
duplicate of #3787, please +1 that request

closing here

**Closed by tagliala** 2015-07-01 10:21 UTC
