### ISSUE TITLE
Bug: unicode symbols displayed instead of glyphs

### ISSUE THREAD

**Issue by mellodev** [FortAwesome/Font-Awesome#20128] opened 2024-02-22 17:27 UTC
### Bug description

A few of our projects using FA 6.1.1 exhibit a very rare bug in the browser where all the glyph icons on the page will render as symbols rather than the intended icons. I figured someone here may have seen this before (or know of a related gh issue) and be able to point me in the right direction? Most likely a problem with our build tool, but I wanted check here if this is a known issue.

We have two similar projects, React apps which are built with Parceljs. We include the fontawesome.css and font files in our build/bundle output and host everything from an S3 bucket. 

### Screenshots

Symbols appearing instead of icons:
![image (3)](https://github.com/FortAwesome/Font-Awesome/assets/1292059/a8e6c608-846f-42ef-a3ac-dc9df7d4cfce)

How the page should look:
![image (2)](https://github.com/FortAwesome/Font-Awesome/assets/1292059/2dffe778-bb8a-45a0-9b0a-9706df1ff43c)

### Font Awesome version

6.1.1

### Serving

Other (as specified in the bug description)

### Implementation

CSS

### Browser and Operating System

Chrome on Windows and Safari on MacOS

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2024-02-22 18:25
Hi,

this is a duplicate of #17644 and is related to self-hosting the css version compiled by a "broken" version of Sass (in the meaning that there was a breaking change during a minor release which broke the correct behaviour)

You will find solutions some there, for the moment we can't fix this because it will be a breaking change

Closing here as a duplicate, feel free to comment at #17644

**Closed as completed by tagliala** 2024-02-22 18:25 UTC
Labels: bug, needs-triage
