### ISSUE TITLE
Icon Request: fa-blogger

### ISSUE THREAD

**Issue by CantonBolo** [FortAwesome/Font-Awesome#5645] opened 2015-02-11 07:46 UTC
![blogger](https://cloud.githubusercontent.com/assets/146246/6143522/32e1c65a-b205-11e4-943b-94e75725ec8c.png)

**Comment by CantonBolo** [comment] 2015-02-11 07:49
In a project recently, I want to create a share button link to Blogger. But I can't find the icon in FA :Cry:.
And I don't want change to other icon fonts.

**Comment by tagliala** [comment] 2015-02-14 23:00
duplicate of #1088 , please +1 that request

@CantonBolo take a look at this wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here

**Closed by tagliala** 2015-02-14 23:00 UTC
