### ISSUE TITLE
Icon Request: fa-bing

### ISSUE THREAD

**Issue by thesilvacesar** [FortAwesome/Font-Awesome#12193] opened 2018-01-31 04:23 UTC
To most integration of bing search on my project

**Comment by tagliala** [comment] 2018-01-31 10:11
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2499 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-01-31 10:11 UTC
