### ISSUE TITLE
Icon Request: fa-pay-check

### ISSUE THREAD

**Issue by hmmmmmm** [FortAwesome/Font-Awesome#9731] opened 2016-08-09 20:45 UTC
In the [Payment Icons](http://fontawesome.io/icons/#payment) there are lots of credit cards available but no icon for checks. This could be very helpful for anyone wanting to put paper checks as one of their accepted forms of payment. I personally just use the credit card ones for my web page, but I might end up using the check icon if it was available. I imagine it could look similar to either fa-credit-card, fa-credit-card-alt, or fa-money.

Here is an example of a payment method icon I found.
![paper-check](https://cloud.githubusercontent.com/assets/10553093/17532665/5cc2b48a-5e47-11e6-94db-2c271937e6c0.png)

I'll be making a better version and will post it later.

**Comment by aethior** [comment] 2016-08-10 01:49
Duplicate of #2603. Please :+1: that.

**Closed** 2016-08-10 08:45 UTC
