### ISSUE TITLE
Icon request: icon-total

### ISSUE THREAD

**Issue by csneed** [FortAwesome/Font-Awesome#11543] opened 2017-09-21 15:10 UTC
Requesting an icon that onClick would show numeric totals / sum. See annotation 4a below. 
Use case: above a table, onClick, totals of col's cells are shown / hidden. 

![screen shot 2017-09-21 at 11 09 07 am](https://user-images.githubusercontent.com/32171144/30703321-612bdaa8-9ebd-11e7-8258-4a1439f4851b.png)

**Comment by tagliala** [comment] 2017-09-21 15:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4834 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-21 15:35 UTC
