### ISSUE TITLE
Fontawesome (.css) cannot found

### ISSUE THREAD

**Issue by gansfilm** [FortAwesome/Font-Awesome#13396] opened 2018-06-23 03:43 UTC
Please resolve this problem, cause i'm always using fontawesome old version. Thanks #

**Comment by tagliala** [comment] 2018-06-23 08:51
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by tagliala** [comment] 2018-06-23 08:52
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more details?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by rikkilake** [comment] 2018-06-25 11:48
I believe what gansfilm means if you use Font Awesome 4.7 and try to search for an icon the Stylesheet is not loading.

**Comment by tagliala** [comment] 2018-06-25 13:19
Oh, thanks.

I can confirm. It's a duplicate of #13394, please follow that request

**Closed by tagliala** 2018-06-25 13:19 UTC
Labels: waiting for feedback
