### ISSUE TITLE
Icon Request: yammer

### ISSUE THREAD

**Issue by urms** [FortAwesome/Font-Awesome#3611] opened 2014-06-02 21:18 UTC
Hi,

I would like to ask if you could create a Yammer-icon, if time permits. 

The 'Y' with three 'shouting' indicators to the right.

https://www.yammer.com

Thanks for fa anyway. It's so wonderful to use :)

Cheers,
Ulf

**Comment by hobe** [comment] 2015-01-05 07:09
duplicate of https://github.com/FortAwesome/Font-Awesome/issues/2707

**Comment by tagliala** [comment] 2015-01-05 10:13
@hobe thanks

**Closed by tagliala** 2015-01-05 10:13 UTC
Labels: brand icons, new icon
