### ISSUE TITLE
Icon request:fa-qzone

### ISSUE THREAD

**Issue by Amazing-Z** [FortAwesome/Font-Awesome#9442] opened 2016-06-22 09:02 UTC
it's a personality space by tencent like facebook.  So it's also used to share something in china. thx.[http://qzone.qq.com/](url)

**Comment by tagliala** [comment] 2016-06-22 09:56
Duplicate of #3993, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-06-22 09:56 UTC

**Comment by Amazing-Z** [comment] 2016-06-22 09:59
@tagliala fine,thx.
