### ISSUE TITLE
Icon Request:Popup

### ISSUE THREAD

**Issue by ryanlin1986** [FortAwesome/Font-Awesome#8297] opened 2016-01-08 18:27 UTC
![qq 20160109022738](https://cloud.githubusercontent.com/assets/11850439/12205857/90a0daba-b678-11e5-8dda-61ce49256f14.png)

Something like this.

**Comment by tagliala** [comment] 2016-01-08 18:36
duplicate of #2478, please +1 that request

closing here

**Closed by tagliala** 2016-01-08 18:36 UTC
