### ISSUE TITLE
Icon request: fa-brain

### ISSUE THREAD

**Issue by jwintz** [FortAwesome/Font-Awesome#11563] opened 2017-09-26 19:31 UTC
Hello,

I use `font-awesome` in many places: [Emacs](https://github.com/domtronn/spaceline-all-the-icons.el), web applications, [Qt applications](https://github.com/gamecreature/QtAwesome).

Many thanks for it, it is just awesome.

As a request, if I may, many applications using your glyphs are domain specific, and when it comes to addressing medical issues, organs are semantically preponderant.

As such, an `fa-brain` icon would be nice for me, as a start, amongst many others like `fa:kidneys`, `fa:lungs`, and so on.

**Comment by tagliala** [comment] 2017-09-26 21:25
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2075 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-09-26 21:25 UTC
