### ISSUE TITLE
Icon request: icon-json

### ISSUE THREAD

**Issue by deandevl** [FortAwesome/Font-Awesome#8892] opened 2016-04-05 10:52 UTC
an icon that shows something similar to json tree with parent-child relationships,  Used to reference reading/writing json files,

**Comment by tagliala** [comment] 2016-04-05 11:14
Duplicate of #1797, please +1 that request

If you have something different in mind please provide an example

Closing here

**Closed by tagliala** 2016-04-05 11:14 UTC
