### ISSUE TITLE
Icon Request: fa-file-csv

### ISSUE THREAD

**Issue by xuancanpro** [FortAwesome/Font-Awesome#10678] opened 2017-02-17 13:35 UTC
I need file type *.csv

**Comment by tagliala** [comment] 2017-02-17 13:36
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5015, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-02-17 13:36 UTC

**Comment by xuancanpro** [comment] 2017-02-17 13:43
why i can't display it in my website
