### ISSUE TITLE
Icon Request: fa-hammer

### ISSUE THREAD

**Issue by DERNERSERFT** [FortAwesome/Font-Awesome#11001] opened 2017-04-27 15:54 UTC
I very much appreciate Font Awesome, and implement it in my projects when possible. However, many of my clients are in the construction industry, and FA lacks a construction hammer. I use the wrench when possible, but recently had a client insist on a hammer, so I had to switch the icons to images. [Something like this would work](https://thenounproject.com/term/hammer/1306/)!

**Comment by tagliala** [comment] 2017-04-27 16:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1214, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-04-27 16:56 UTC

**Comment by DERNERSERFT** [comment] 2017-04-27 17:03
Will do! I noticed it was posted in 2013, so wasn't sure if it was still a relevant request.
