### ISSUE TITLE
stupid to make the homepage slow

### ISSUE THREAD

**Issue by jinghuasoft** [FortAwesome/Font-Awesome#12303] opened 2018-02-09 11:18 UTC
lots of icons there, the computer got stuck everytime I opened https://fontawesome.com/icons.

**Comment by tagliala** [comment] 2018-02-09 13:48
Hi!

Thanks for being part of the Font Awesome Community.

Please edit the title to meet our [code of conduct](https://github.com/FortAwesome/Font-Awesome/blob/master/CODE_OF_CONDUCT.md#our-standards)

**Comment by SwiftShard** [comment] 2018-02-11 03:05
The issue isn't on Font Awesome's side, its your computer. What browser are you using? This is what it looks like to me: 
![image](https://user-images.githubusercontent.com/28634390/36068947-8e0679fa-0eae-11e8-8c73-8ac473552578.png)

**Comment by tagliala** [comment] 2018-02-11 09:10
Closing here, waiting for a proper title before reopening.

Code of conduct: https://github.com/FortAwesome/Font-Awesome/blob/master/CODE_OF_CONDUCT.md#our-standards

**Closed by tagliala** 2018-02-11 09:10 UTC
Labels: doc, enhancement, waiting for feedback
