### ISSUE TITLE
Icon request: Mongodb

### ISSUE THREAD

**Issue by internetstyle** [FortAwesome/Font-Awesome#12378] opened 2018-02-16 18:54 UTC
It would be cool to have the mongodb icon. Thanks.

**Comment by internetstyle** [comment] 2018-02-16 18:55
Sorry... duplicated.

**Comment by tagliala** [comment] 2018-02-16 19:27
@internetstyle don't worry

Duplicate of #2725, closing here

**Closed by tagliala** 2018-02-16 19:27 UTC
