### ISSUE TITLE
Can you please create an icon fa-headset with headphones and microphone

### ISSUE THREAD

**Issue by YuryKondrashov** [FortAwesome/Font-Awesome#11755] opened 2017-11-14 12:25 UTC
Hello, 
Can you please create an icon fa-headset with headphones and microphone?
This icon will be popular for applications supporting audio/video calls using e.g. USB headset.
Actually I can see separate icons microphone and headphones, but there is no icon combining them.
Thank you.
Best regards,
Yury.

**Comment by tagliala** [comment] 2017-11-14 12:55
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1146 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-11-14 12:55 UTC

**Comment by shahenalgoo** [comment] 2018-04-17 08:45
+1
