### ISSUE TITLE
Icon request: Billboard

### ISSUE THREAD

**Issue by ezequias** [FortAwesome/Font-Awesome#14919] opened 2019-04-17 19:29 UTC
Would be nice if you have a billboard icon like this one:

https://www.flaticon.com/free-icon/billboard_1294357#term=billboard&page=2&position=47

**Comment by tagliala** [comment] 2019-04-17 21:07
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4599, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2019-04-17 21:07 UTC
