### ISSUE TITLE
Icon Request: fa-t-shirt

### ISSUE THREAD

**Issue by Marcel0024** [FortAwesome/Font-Awesome#9510] opened 2016-07-01 11:56 UTC
For a printing and embroidery website. Just the form of a T-shirt.
Like this: 

http://cdn.mysitemyway.com/icons-watermarks/simple-black/raphael/raphael_t-shirt/raphael_t-shirt_simple-black_512x512.png

It would be cool ta have in your already awesome collection. It's ok if it's not made. No biggy.

Cheers

**Comment by ryankane** [comment] 2016-07-01 12:26
I would go with an outline, in the case where a user might want to stack.

# fa-tshirt

![fa-tshirt][1]

  [1]: https://cloud.githubusercontent.com/assets/1094151/16521530/6b1c9c0e-3f65-11e6-9a7f-ab682c00b63b.png

**Comment by tagliala** [comment] 2016-07-01 12:28
Duplicate of #715 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2016-07-01 12:28 UTC
