### ISSUE TITLE
Icon Request: fa-plus-light

### ISSUE THREAD

**Issue by fartbutton** [FortAwesome/Font-Awesome#7895] opened 2015-11-17 04:06 UTC
Dear Font Awesome,

I'm a frontend developer and this wanted icon is one that comes up very often for me in practical situations when I am coding designs. The current plus icons are quite chunky. 

My request is for a skinnier version of the plus icon. I often get designs with interactive button elements that have a plus on them to show they can be clicked to expand a menu. The vertical and horizontal bars on the plus is usually quite svelte. 

Essentially, I'm after the plus equivalent of fa-chevron-right and fa-angle-right, being fat and thin versions of a similar shape.

Thanks very much for your consideration, and for providing excellent icons.

![plus-demo](https://cloud.githubusercontent.com/assets/3108221/11202423/f20e5e08-8d4c-11e5-8b8c-040fb7279d80.png)

**Comment by tagliala** [comment] 2015-11-17 11:29
Duplicate of #2161 , please +1 that request

closing here

**Closed by tagliala** 2015-11-17 11:29 UTC

**Comment by MbF-Sathya** [comment] 2017-12-27 12:46
Same issue
