### ISSUE TITLE
Request Icon - Zip Line

### ISSUE THREAD

**Issue by Third-Hyperion** [FortAwesome/Font-Awesome#14909] opened 2019-04-17 08:36 UTC
It would be cool to have a zip line icon, there could be a few different variations, person zip lining, zip line wire, zip line track, zip line from tree.

**Comment by tagliala** [comment] 2019-04-17 08:42
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fix this request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

Please note that this will be considered as a request for a single icon. If you need a comprehensive set of icons about zip lines, Font Awesome Pro backer can request sets in the Pro Repository

**Comment by aethior** [comment] 2022-03-12 22:15
Duplicate of #14912.

cc/ @tagliala

**Closed** 2022-03-12 22:18 UTC
Labels: waiting for feedback
