### ISSUE TITLE
cc-google-pay icon is missing

### ISSUE THREAD

**Issue by Kaos-Industries** [FortAwesome/Font-Awesome#18310] opened 2021-09-29 00:13 UTC
There is currently a `cc-` (credit card) version of every payment icon except the Google Pay equivalent. I'm unsure why this oversight would have been made since across the world more Androids are in use than iPhones, but I would really like for it to be rectified so I can consistently use the credit card icons to indicate payment for my sites.

![Screenshot 2021-09-29 at 01-10-28 Font Awesome Cc Icons](https://user-images.githubusercontent.com/16962031/135182001-319f4b50-4832-4452-bd0c-22195ac6712f.png)

**Bug report checklist**
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment] 2021-09-29 08:41
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17529, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Closed by tagliala** 2021-09-29 08:41 UTC
