### ISSUE TITLE
Icon request: Cents

### ISSUE THREAD

**Issue by parampreetGit** [FortAwesome/Font-Awesome#12537] opened 2018-03-07 17:02 UTC
Cents icon can be used to display money. 

I have a screen where i want a slider, which will increment dollars, would love to increments cents as well, that's the reason am looking for an icon.
 
PFA the screenshot.

<img width="311" alt="cents" src="https://user-images.githubusercontent.com/21226317/37106247-4b6d6022-21ff-11e8-803d-b4aba185d8b7.png">

**Comment by tagliala** [comment] 2018-03-07 18:05
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1602, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-03-07 18:05 UTC
