### ISSUE TITLE
Icon request: iDeal

### ISSUE THREAD

**Issue by amvanleeuwen** [FortAwesome/Font-Awesome#12704] opened 2018-03-26 14:33 UTC
### What can it be used for?

iDeal is a common payment method in The Netherlands. Almost 90% of online paymenst are done using iDeal. It would be great to have an icon for this on FA similar to the ones created for Visa and Mastercard.

### Example image (optional)

https://goo.gl/images/N3fLrF

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-04-06 14:52
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4330, please add a 👍  reaction to that request.

>  I have searched for existing issues and to the best of my knowledge this is not a duplicate

No problem

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-04-06 14:52 UTC
