### ISSUE TITLE
Icon request: ASM x86 and MIPS

### ISSUE THREAD

**Issue by Berkmann18** [FortAwesome/Font-Awesome#13711] opened 2018-08-04 22:24 UTC
### What can it be used for?
There are no icons for any assembly languages (Intel x86, AT&T, MIPS) but it would be great if FA had one for ASM x86 (Intel Assembly x86) and MIPS.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment] 2018-08-05 20:45
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide examples and clarify why they should be both implemented in the same PR? 

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by Berkmann18** [comment] 2018-08-05 21:16
ASM Intel x86 is one of the most important an popular low-level language (alongside the lesser known MIPS) and it would be ideal to have it among the other font icons for languages.

I don't think they have official ones.
Intel x86 ASM could be associated to an intel logo like this: ![x86](https://images.ecosia.org/HGnOVXchsAZHycghM-TIGS_TE54=/0x390/smart/https%3A%2F%2Fwiki.chaosdorf.de%2Fimages%2Fthumb%2F7%2F75%2FIntel_chip.png%2F300px-Intel_chip.png) or this: ![asm](https://www.nayuki.io/res/page-icon/64/a-fundamental-introduction-to-x86-assembly-programming.png).

For MIPS, there's this:
![mips](https://images.ecosia.org/xFCBbEOUis2p4SZZkdYdnBDhB7U=/0x390/smart/http%3A%2F%2Fwww.techweekeurope.co.uk%2Fwp-content%2Fuploads%2F2012%2F11%2FMIPS-logo.jpg) or this ![chip](https://tse3.mm.bing.net/th?id=OIP.rO7OPoQxEPineYWaOPv6dwHaE9&pid=Api)

**Comment by tagliala** [comment] 2018-08-06 09:46
could we consider ASM a duplicate of #3916, which is the intel brand ?

**Comment by Berkmann18** [comment] 2018-08-06 23:15
Well, unless there's some aliases and that it makes sense to users then I wouldn't see a problem.
I'm not sure about if it would be obvious for ASM coders that the _brand_ icon of intel would also be a _language_ icon.

**Comment by sensibleworld** [comment] 2024-07-11 19:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Closed by sensibleworld** 2024-07-11 19:23 UTC
Labels: new icon, waiting for feedback, Declined
