### ISSUE TITLE
Icon request: fa-color-bucket

### ISSUE THREAD

**Issue by ahmed997** [FortAwesome/Font-Awesome#11279] opened 2017-07-11 23:59 UTC
A color bucket icon like this 
![441-512](https://user-images.githubusercontent.com/24213589/28095915-6b88b32c-66a5-11e7-9cd2-44f666a92c5d.png)
using it in website to change the main color

**Comment by tagliala** [comment] 2017-07-12 07:00
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3270 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-12 07:00 UTC
