### ISSUE TITLE
Icon Request: icon-groucho or icon-impersonate

### ISSUE THREAD

**Issue by muleycharge** [FortAwesome/Font-Awesome#13122] opened 2018-05-11 18:35 UTC
We were implementing a user impersonation feature where a user could use our application in the context of a subordinate user and were looking for an icon to encapsulate this. It would be great if font-awesome had a modified user icon with Groucho Marx eyeglasses/mustache/nose mask. I'm sure others would find a use for this.

**Comment by tagliala** [comment] 2018-05-11 21:01
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10691, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Closed by tagliala** 2018-05-11 21:01 UTC
