### ISSUE TITLE
Icon Request: fa-car-headlight or fa-car-headlamp

### ISSUE THREAD

**Issue by mseminatore** [FortAwesome/Font-Awesome#13602] opened 2018-07-22 21:54 UTC
Need an icon for automotive headlights.

**Comment by mseminatore** [comment] 2018-07-24 19:55
Here is an example of a headlamp.

![image](https://user-images.githubusercontent.com/16830648/43162714-c62131dc-8f40-11e8-91a8-50d8aa291657.png)

**Comment by mseminatore** [comment] 2019-09-30 21:34
@tagliala have you looked at this one yet?

**Comment by DraugDev** [comment] 2020-04-27 21:33
Any updates here?

**Comment by tagliala** [comment] 2020-04-28 07:34
Hi @DraugDev 

You may be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

**Comment by sensibleworld** [comment] 2024-07-11 19:23
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/3264)

**Closed by sensibleworld** 2024-07-11 19:23 UTC
Labels: new icon, automotive (category), Duplicate
