### ISSUE TITLE
add a icon that popular in China.

### ISSUE THREAD

**Issue by damaohub** [FortAwesome/Font-Awesome#11271] opened 2017-07-09 09:59 UTC
May be adding the icons about aliPay(支付宝）is very necessary considering of the population in China.

**Comment by tagliala** [comment] 2017-07-09 11:28
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3854 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-07-09 11:28 UTC
