### ISSUE TITLE
Icon request: icon-new!

### ISSUE THREAD

**Issue by ilovemakonnen** [FortAwesome/Font-Awesome#6536] opened 2015-05-22 11:02 UTC
Be great to have an icon that said the word "New !" with a solid background or no background.

To use for listings

**Comment by smaspe** [comment] 2015-05-22 18:38
not localized, also can't you just write it?

**Comment by tagliala** [comment] 2015-05-22 20:11
@smaspe I agree with you

btw this is a duplicate of #1331, please +1 that request

closing here

**Closed by tagliala** 2015-05-22 20:11 UTC
