### ISSUE TITLE
cant forgot password

### ISSUE THREAD

**Issue by firstbook18** [FortAwesome/Font-Awesome#17200] opened 2020-09-26 22:26 UTC
i cant forgot my password

**Comment by tagliala** [comment] 2020-09-27 07:48
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

There was an issue, please check if it is fixed now

**Comment by tagliala** [comment] 2020-09-27 07:51
Duplicate of #17196

**Closed by tagliala** 2020-09-27 07:51 UTC
Labels: waiting for feedback
