### ISSUE TITLE
Icon request: fa-bell-ringing (youtube style bell)

### ISSUE THREAD

**Issue by emma-15** [FortAwesome/Font-Awesome#14847] opened 2019-03-30 18:07 UTC
About 1,300million people use YouTube and most of them want subscribers. 
I know there is already a fa-youtube icon, but with the subscribe bell icon, people could use it as a referral link to subscribe to their youtube channel.
example: `https://www.youtube.com/channel/CHANNEL_ID?sub_confirmation=1`
![bell1](https://user-images.githubusercontent.com/48891420/55279922-a70e4300-52ec-11e9-9b0c-893752ab791f.png)
![bell2](https://user-images.githubusercontent.com/48891420/55279923-a83f7000-52ec-11e9-805c-e8e3113e5719.png)

**Comment by aloisdg** [comment] 2019-04-01 09:24
We already ha ve a [bell icon](https://fontawesome.com/icons/bell?style=solid). IMHO, the 'ringing' bell would be a nice addition.

**Comment by qwazix** [comment] 2019-07-10 12:10
Something like this?

![image](https://user-images.githubusercontent.com/1202892/60968085-e5bc8c00-a324-11e9-8637-3ded75c323b0.png)

**Comment by moofawsaw** [comment] 2019-11-25 02:47
The bell-ringing would be a great addition. Is there an update?

**Comment by tagliala** [comment] 2021-09-30 12:39
I think this has been addressed in FA6 Pro: https://fontawesome.com/v6.0/icons/bell-on?s=solid

**Comment by aloisdg** [comment] 2021-10-01 07:26
@tagliala so now way to get it in the free version?

**Comment by drewgeraets** [comment] 2021-12-24 16:57
Is this a dupe of https://github.com/FortAwesome/Font-Awesome/issues/7518

**Comment by aethior** [comment] 2022-03-07 00:30
> Is this a dupe of #7518

@tagliala please check this.

**Comment by tagliala** [comment] 2022-03-07 14:19
I've not considered this a duplicate because of the "on" style, but they both work for the same use case. Don't know exactly what to do

@sensibleworld ?

**Comment by sensibleworld** [comment] 2023-11-28 18:31
https://fontawesome.com/icons/bell-ring?f=classic&s=solid

**Closed by sensibleworld** 2023-11-28 18:31 UTC
Labels: new icon, web application icons (legacy category), in progress
