### ISSUE TITLE
Icon Request: fa-laravel

### ISSUE THREAD

**Issue by vdmeijer** [FortAwesome/Font-Awesome#11166] opened 2017-06-13 07:56 UTC
I'm currently updating the company website, and one of the wishes is to show on what cms and programming frameworks we work. We mostly use wordpress, joomla. opencart and laravel (Depending on the project). For all of these are icons, exept for laravel.

![laravel](https://user-images.githubusercontent.com/15979712/27070291-b7662d22-5018-11e7-885b-6af39b5d6845.png)
![laravel-icon](https://user-images.githubusercontent.com/15979712/27070335-deffe080-5018-11e7-82e8-2a299cb9e99b.png)

**Comment by aethior** [comment] 2017-06-14 08:07
Duplicate of #2151.

**Closed** 2017-06-14 08:10 UTC
