### ISSUE TITLE
Icon Request: fa-dessert

### ISSUE THREAD

**Issue by tzeller** [FortAwesome/Font-Awesome#11601] opened 2017-10-07 12:44 UTC
hardly anything for the restaurant industry in the icon set so far
[fa-dessert.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364620/fa-dessert.pdf)

**Comment by tagliala** [comment] 2017-10-07 12:56
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5561, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-10-07 12:56 UTC
