### ISSUE TITLE
Icon Request: icon-Scan

### ISSUE THREAD

**Issue by zihu903** [FortAwesome/Font-Awesome#10765] opened 2017-03-09 09:05 UTC
Prompted users to use mobile phones to scan two-dimensional code Icon

![01](https://cloud.githubusercontent.com/assets/26291998/23742829/61b68f36-04e9-11e7-8b1b-841051a6c96b.jpg)
![02](https://cloud.githubusercontent.com/assets/26291998/23742830/61fc776c-04e9-11e7-9df2-a0d69a0ae58a.jpg)

**Comment by tagliala** [comment] 2017-03-09 10:35
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9485, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Closed by tagliala** 2017-03-09 10:35 UTC
