### ISSUE TITLE
Icon Request: fa-radar (monitor)

### ISSUE THREAD

**Issue by heruan** [FortAwesome/Font-Awesome#7068] opened 2015-07-29 07:05 UTC
A "radar" monitoring icon could be useful to represent network monitoring menu items or buttons.
For example:
<img src="https://cloud.githubusercontent.com/assets/851745/8951650/d689c8a4-35cf-11e5-8779-bc9d034a37e4.png" alt="radar1" width="128">
<img src="https://cloud.githubusercontent.com/assets/851745/8951656/da3453a2-35cf-11e5-82e9-070b8f96f3f1.png" alt="radar2" width="128">
<img src="https://cloud.githubusercontent.com/assets/851745/8951658/dd017006-35cf-11e5-83dd-4bcf37e720f6.png" alt="radar3" width="128">

**Comment by tagliala** [comment] 2015-07-29 08:37
duplicate of #5659, please +1 that request

closing here

**Comment by heruan** [comment] 2015-07-29 09:11
It's not a duplicate, see the image link in #5659: that's a satellite dish, not a radar monitor.

**Comment by tagliala** [comment] 2015-07-29 09:45
Sorry, reopening as radar monitor

**Comment by tvirelli** [comment] 2015-08-05 17:03
+1

**Comment by simonfranz** [comment] 2015-08-05 21:40
+1

**Comment by baalthazaar1** [comment] 2015-08-13 17:53
+1

**Comment by maximvd** [comment] 2015-09-27 14:16
+1

**Comment by kwinne** [comment] 2015-09-27 14:18
+1

**Comment by apinner** [comment] 2016-02-08 13:42
+1

**Comment by Pasha49** [comment] 2016-06-20 09:15
+1

**Comment by HambroRoofing** [comment] 2016-06-22 11:15
+1

**Comment by JoranBeaufort** [comment] 2016-07-29 23:02
+1 Any word on progress? Awesome would be radar + radar-spinner where only the scan line spins :)

**Comment by SynchroM** [comment] 2016-09-14 06:37
+1

**Comment by jarrodbell** [comment] 2016-09-28 01:40
+1

**Comment by besharp** [comment] 2016-09-28 08:07
+1

**Comment by danbernier** [comment] 2016-10-19 16:50
+1

**Comment by dumboxp** [comment] 2017-03-20 13:37
+1   A radar-icon would be great and very useful (the first example is great) A spinning version e.g. to visualise a "scanning"-tasks would be perfect as well.

**Comment by poblabs** [comment] 2017-04-02 18:25
+1

**Comment by benmccallum** [comment] 2017-07-19 01:06
+1

**Comment by sedrakpc** [comment] 2017-12-05 13:16
+1

**Comment by geri777** [comment] 2017-12-07 21:13
+1

**Comment by KurtJacobson** [comment] 2018-01-12 23:22
+1

**Comment by lichtamberg** [comment] 2018-01-19 14:11
+1

**Comment by DaniloOliveira28** [comment] 2018-03-09 19:36
+1

**Comment by inakuhn** [comment] 2018-04-03 14:02
+1

**Comment by reneseses** [comment] 2018-05-23 03:04
+1

**Comment by erijonhson** [comment] 2018-07-09 16:24
+1

**Comment by fdamore-xnoova** [comment] 2018-08-06 10:15
+1

**Comment by venarius** [comment] 2018-12-13 13:47
+1

**Comment by HarpunDK** [comment] 2019-09-06 07:56
+1

**Comment by NickJorens** [comment] 2019-09-20 17:14
A spinning one would be awesome :wink:

**Comment by DavydeVries** [comment] 2019-11-27 11:05
+1

**Comment by inakuhn** [comment] 2019-11-27 13:34
+1

**Comment by sensibleworld** [comment] 2019-12-11 19:17
https://fontawesome.com/icons/radar?style=duotone

**Closed by sensibleworld** 2019-12-11 19:17 UTC
Labels: in progress, new icon, released, web application icons
